### ISSUE TITLE
Grid API for expand/collapse of detail rows

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#100]
There [have been](http://stackoverflow.com/questions/40786124/opening-the-kendodetailtemplate-programmatically) [requests](http://stackoverflow.com/questions/40786625/kendo-ui-angular2-detailrow-width-html-and-autoexpand) for more control over the expanding and collapsing of the detail rows. The grid should provide methods that allow that.

**Comment by rusev** [comment]
Adding public API for expand/collapse is in your to-do list. We'll update the documentation when it is available.

**Comment by gyoshev** [comment]
It would be easier for customers to track this item, so let's close it when the functionality has been implemented.

**Comment by burkeholland** [comment]
Is there currently a preferred way to handle the expand/collapse event? Perhaps off of the `dataStateChange` event?

**Comment by rusev** [comment]
@burkeholland there isn't event for expand/collapse yet. `dataStateChange` is related to data state - like page index/size, sorting etc.

**Comment by burkeholland** [comment]
Understood. It would be nice to have the event to decide whether or not to destroy/recreate the detail grid on expand/collapse.

**Comment by lelong37** [comment]
Hey guys, is there away to show the grid fully expanded all rows?

e.g. the old way:

`dataBound: function() {
    this.expandRow(this.tbody.find("tr.k-master-row"));
}`

**Comment by rusev** [comment]
@lelong37 There isn't `dataBound` event analogue as the Grid is repainted right after `data` property is provided.

Here is a possible implementation of the scenario - http://plnkr.co/edit/Rqc2lBCljEF4x5WOJj0C?p=preview

**Comment by tsvetomir** [comment]
Perhaps we can add this snippet to the docs as well?
