### ISSUE TITLE
Cannot reset ComboBox in a reactive form after clicking clear icon

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#1001]
## I'm submitting a...
* Bug report

## Current behavior
When click clear button in combobox and then try to reset formControl with value it isn't displayed in DOM.

## Expected behavior
Selected value is displayed in DOM.

## Minimal reproduction of the problem with instructions
1. [Open plunk](http://plnkr.co/edit/z2WVQePyspINlPmxaaf4?p=preview)
2. Click clear (x) icon in combobox.
3. Click button "Select first value"

## Environment

Package versions: 1.2.2
Browser:
- Chrome (desktop) version 61

**Comment by ipeshev** [comment]
Fixed in v1.2.3-dev.201711071404
