### ISSUE TITLE
Chart: Doc for notes

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1002]
I have to implement some really specific shapes on charts and i have to decide how to proceed.
Main request here is to have a doc or plunker that shows how to use `SeriesNotes` (it could be one way to solve my request):

https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesNotes/

I could try to imagine how it works reading API but i guess doc is missing on Kendo documentation. Could you please check and just add a simple example to start with it?

**Comment by danielkaradachki** [comment]
Documentation for [notes](https://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/notes/) and the other missing elements has been added.
