### ISSUE TITLE
DropDownList: How to test a component that use it

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1003]
Hi to all,
i have a complex component to tests that use DropDownList. Actually when i just test other components i use something link:

```
var select = elem.find('#test-code-select');
var oneOption = select.find('option:contains("236")');
oneOption.prop('selected', 'selected').trigger('change');
expect(scope.code).toEqual('236');
```

From Angular test documentation we have also:
```
it('should raise selected event when clicked', () => {
  let selectedHero: Hero;
  comp.selected.subscribe((hero: Hero) => selectedHero = hero);

  heroEl.triggerEventHandler('click', null);
  expect(selectedHero).toBe(expectedHero);
});
```
But native element of DropDownList is just a little bit more complicated and it could be changed in future. So i just would like to know how to test user changes on that component. Do you have any best practice to do that?

I guess i have to trigger events directly on component to have a change, for example: 

https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/DropDownListComponent/#toc-filterchange

but i'm waiting for a "official" approach.
Thanks

**Comment by ggkrustev** [comment]
Hi @meriturva,

I definitely agree that it is better to treat any internal component as a black box and communicate with it through its API. That being said, we follow all best  practices that the framework itself implies.

Simulating user actions upon Angular component is something supported by the [`DebugElement`](https://angular.io/api/core/DebugElement) object and it is perfectly fine to use it. That being said, testing the DropDownList events using [`triggerEventHandler`](https://angular.io/guide/testing#triggereventhandler) is the way to go. Plunging into the component internals, even for testing, is a wrong path to take on.

I will close the thread as it is not bug, nor feature request. Feel free to comment if something is not clear.
