### ISSUE TITLE
Dialog enhancement - add min-width option

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1004]
The Dialog has a default min-width of 450px set, which seems to be on the bigger side in multiple use cases. 

Currently the only way to set a different min-width is by overriding our CSS either via setting ViewEncapsulation to none or use the deprecated ">>>" syntax.

It would be nice to expose a configuration property for setting the min-width of the Dialog, as multiple customers have raised concerns about this issue.

**Comment by gyoshev** [comment]
Added in the `v1.3.0-dev.201710161038` version, available on the dev channel.

**Comment by gyoshev** [comment]
Released officially in `v1.3.0`.
