### ISSUE TITLE
[Bug] Multiselect Dropdown with Preventing Opening and Closing 

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#1006]
## I'm submitting a...
* Bug report 

## Current behavior
I am using the Mutliselect Dropdownlist with Preventing Opening and Closing

https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/open-state/#toc-preventing-opening-and-closing

I've created a Plunkr 

http://plnkr.co/edit/UgVDsdGQZv6CyfidxMJT?p=preview

Its a copy from your plnkr just with much more Listentries. The Problem is, when you select a entry at the end of the list, the list will scroll up to show the current selected Item and I have to scroll down again, ... and when you have a really large list, where you have to select the last 10 items I have to scroll down the hole list 10 Times. 

Sometimes I see the current behaviour: When I select one of the the last Items the list jumps up to the first item and then scrolls down to my selected entry, but thats not working all the time and in my local example with about 100 entries I never seen this behaviour.

## Expected behavior
when you select a Item, the list should stay at the current item.

## Minimal reproduction of the problem with instructions

see my plnkr above

## Environment
your demo on the current webpage

Browser:
- Chrome (desktop) version newest
- Firefox version newest

**Comment by tapopov** [comment]
Thanks for the report @squadwuschel!

This behavior is already logged as an issue in #970, so I will mark this thread as duplicate and close it.
