### ISSUE TITLE
bootstrap font family i

### ISSUE THREAD

**Issue by donaldhook** [telerik/kendo-angular#1007]
I have created a new angular application using the bootstrap theme.  I installed the bootstrap theme, however, when I view the app, the font family is not the same as what is used on the Telerik angular theme customization page for bootstrap.  I am including the bootstrap theme in the styles.scss.   It looks as though the font is times new roman....

Not sure what I am doing wrong.

Thanks in advance

**Comment by gyoshev** [comment]
The Kendo UI themes will inherit the page font, by default. The default browser font is Times New Roman.

If you want the components to look like the [preview page of the Bootstrap theme](https://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/), you can use the following font declaration:

```css
body {
    font-family: "Roboto", Helvetica, Arial, sans-serif;
    font-size: 14px;
}
```

To use the `Roboto` font family, load it from [Google fonts](https://fonts.google.com/specimen/Roboto).

**Comment by donaldhook** [comment]
Thank you!
