### ISSUE TITLE
DropDownList with filtering does not allow tabbing to the next input

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1008]
When the filtering is enabled in the DropDownList, the user cannot tab to the next focusable element when the value is changed:

[http://plnkr.co/edit/SUMZqk5yP9Xz40LrOoCD?p=preview](http://plnkr.co/edit/SUMZqk5yP9Xz40LrOoCD?p=preview)

1) Open the DropDownList and change the value

2) Press Tab // the next input is not focused

When there is a selected value, and this value is not changed (open and close the DropDownList without changing the value), the next input is focused as expected.

The issue is not present when "filterable" is not set/ is set to **_false_**.

Reported in Ticket ID: 1135174

**Comment by nm-a** [comment]
Hi,
Any tentative timeline for this?

thank you

**Comment by ipeshev** [comment]
Fixed in v1.5.1-dev.201801081634
