### ISSUE TITLE
Enhance Date type export functionality for Excel Export to work for various locales

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1010]
The export of multiple dates with different locales is not supported when using Excel Export's [cellOptions] input. Also the date type in the exported Excel file becomes "custom".

[http://plnkr.co/edit/z2Pq6XuplQjRavQnzBbw?p=preview](http://plnkr.co/edit/z2Pq6XuplQjRavQnzBbw?p=preview)

**Comment by tsvetomir** [comment]
The format works as expected. Excel will show "Custom" as it does not match any of the known date formats for the system locale.

![image](https://user-images.githubusercontent.com/247917/42377998-5163fca0-812e-11e8-954b-4f3ebc9987df.png)
