### ISSUE TITLE
Multiselect: permit to add new value

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1011]
I'm just looking for a way to add new tags on a multi select. I have seen just few examples on Kendo UI for Jquery where there is a special template with add button where "no data is found" on valid values.

I have also seen how to customise templates here: https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/NoDataTemplateDirective/

do i have to develop new NoDataTemplate to permit user to add new item or that feature is on backlog already?
Thanks.

**Comment by tapopov** [comment]
Hi @meriturva 

Indeed, this is already in our backlog.  Please, feel free to share any thoughts you might have regarding the feature in #478.
