### ISSUE TITLE
Use different orientations for the caret on the PanelBar

### ISSUE THREAD

**Issue by RajeshAtGithub** [telerik/kendo-angular#1012]
Hi, 
Is there a way to set the orientation of the caret or use a different icon in the Kendo panelbar? The demo would be the sample provided by Kendo (http://plnkr.co/edit/?p=preview), which I tried to tweak a little-bit to get what I want without success (http://plnkr.co/edit/ekpcIy5ywhmSv8jvSlwD?p=preview).

Presently, in the demo, the caret points downward, when the panel is collapsed and upward, when it is open. I would like the orientations to be pointing to the right when collapsed and downward, when opened as in the picture below. 
![image](https://user-images.githubusercontent.com/5778079/31627716-d04c3404-b273-11e7-9416-3a6052592674.png)

Also, I would like to know how to hide the caret altogether (the panel-bar just has the title and no carets at all). My go at getting the caret pointing right can be seen in the following plunkr for the title "Projects" (http://plnkr.co/edit/ekpcIy5ywhmSv8jvSlwD?p=preview), but it seems that Kendo 's caret is still showing. Thank you for your assistance.

-Raj

**Comment by tsvetomir** [comment]
This repository is for bug reports only, please refer to the [README](https://github.com/telerik/kendo-angular#how-do-i) for details.

Please file a support ticket for assistance with these customization requests.
