### ISSUE TITLE
Column resize when mouse outside grid

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1013]
* Bug report 

## Current behavior
If you start resizing column and go out of grid boundaries without releasing mouse button resize will continue.
## Expected behavior
Resize should stop when mouse leaves grid boundaries

## Minimal reproduction of the problem with instructions
1.Open this [plunkr](http://plnkr.co/edit/L0w2K4XXTBU3EfonuuiY?p=preview)
2.Start resize column and without releasing mouse button go out of the grid.

## Environment

Package versions:
```
v1.5.0
```

Browser:
N/A

**Comment by rusev** [comment]
This is expected behavior. It is the only way to increase the width of the last column in the Grid with horizontal scrolling.
