### ISSUE TITLE
Empty AutoComplete selects first item on Enter

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#1014]
## I'm submitting a...
* Bug report

## Current behavior
Clearing the AutoComplete value followed by an Enter keypress selects the first item from the `[data]` array. 

## Expected behavior

Nothing should happen.

## Minimal reproduction of the problem with instructions
  1. Go to any of our demos
  2. Start typing and select any of the suggested items
  3. Blur the component, then focus it again
  4. Delete the text and press Enter

## What is the motivation or use case for changing the behavior?
Unexpected behavior.

## Environment
Browser:
All

**Comment by tapopov** [comment]
Fix available in `kendo-angular-dropdowns` `v1.2.3-dev.201710271132`

**Comment by lohiarahul** [comment]
Should I wait for v1.2.3 before using it in production?

**Comment by tapopov** [comment]
Hey @lohiarahul,
Although the dev version passed QA, you might want to wait a bit, as we're about to release v1.2.3 this week.

**Comment by tapopov** [comment]
@lohiarahul 
v1.2.3 is officially released.
