### ISSUE TITLE
Angular radio button not working with kendo ui radio style classes

### ISSUE THREAD

**Issue by FrancoisM** [telerik/kendo-angular#1017]
I'm trying to use the radio button binding as described on the angular [website](https://angular.io/api/forms/RadioControlValueAccessor) using the kendo ui button style but this doesn't work as per this [plunker](http://plnkr.co/edit/FWbOKBjt6ZcJIBZfqSjR?p=preview). The radio button  first binding is ok but then clicking on the buttons as no effect.

**Comment by gyoshev** [comment]
To associate the labels with the radio buttons, the radios need to have an `id` attribute equal to the label `for` attribute. [Updated plunkr](http://plnkr.co/edit/HL9PS7mwwVchlxkYrCOj?p=preview).
