### ISSUE TITLE
Grid auto-scrolls when virtual scrolling and locked columns are used

### ISSUE THREAD

**Issue by anottest** [telerik/kendo-angular#1020]
## I'm submitting a...
* Regression report 

## Current behavior
In the Kendo Grid, with virtual scrolling enabled and at least one locked column, the scrollable content area can become stuck in "auto-scroll" mode. This results in the grid triggering multiple pageChange events in sequence, each time with an increased skip value until it reaches the bottom of the results. Attempting to scroll up will trigger it again and it scrolls back to the bottom. Scrolling all the way to the top seems to pause the behavior, but it will resume if you scroll down again. I have also been able to trigger the behavior by clicking in the middle of the vertical scrollbar to load another page, and then activating a column sort, so it seems like any change to the bound data while the grid is not scrolled all the way to the top can trigger the auto-scroll.

The scrolling behavior works as expected if the locked columns are changed to not be locked. This bug was not observed in version 1.2, and appeared when we upgraded to 1.4.2. I also tested on 1.5.0 and the issue still exists. Also, this bug doesn't seem to appear when testing in IE or Edge - only in Chrome.

## Expected behavior
The expected behavior is to be able to scroll up and down normally with pageChange events triggered according to the scroll position without auto-scrolling down after the bound data changes.

## Minimal reproduction of the problem with instructions
I'm currently unable to recreate the issue based on the samples page.

## What is the motivation or use case for changing the behavior?
Bug fix

## Environment

Package versions:
+-- @angular/core@4.3.4
+-- @progress/kendo-angular-buttons@1.1.0 
+-- @progress/kendo-angular-dateinputs@1.2.0 
+-- @progress/kendo-angular-dropdowns@1.2.0 
+-- @progress/kendo-angular-excel-export@1.0.1 
+-- @progress/kendo-angular-grid@1.5.0 
+-- @progress/kendo-angular-inputs@1.0.5 
+-- @progress/kendo-angular-intl@1.1.0 
+-- @progress/kendo-angular-l10n@1.0.0 
+-- @progress/kendo-data-query@1.0.2 
+-- @progress/kendo-drawing@1.3.0 
+-- @progress/kendo-theme-default@2.43.1 

```

Browser:
- Chrome (desktop) version 61
- Internet Explorer version 11
- Edge version 40

System:
- TypeScript version: 2.3.4
- Node version: Node 6.11.2, npm 3.10.10
- Platform:  Windows

**Comment by rkonstantinov** [comment]
Hey @anottest, thanks for the report. Unfortunately, I'm not able to re-create the behavior you have described locally. Please check the following plunkr, maybe I'm missing something.
http://plnkr.co/edit/fCVIuNABeuII7wzkRviF?p=preview

Also you should verify that there are no dynamic changes made to the Grid's layout during the rendering.  For example something that can resize the rows height just after the data is being rendered. This could result in Grid's layout re-calculation, causing browser to trigger a scroll event.

**Comment by anottest** [comment]
After further testing, it seems like there is one other factor involved in producing this issue - asynchronous loading of the paged data. If the pageChange event calls an asynchronous function to load the page of data, this issue will start to appear. The update of the grid's data source when the asynchronous loading completes frequently triggers another pageChange event with different skip values. If you change the logic in the pageChange event to just update the grid's data source synchronously, this issue goes away. I was able to create a sample that demonstrates the behavior:
http://plnkr.co/edit/Sd7c5iCWvGVmA8h5xz1T?p=preview

If you scroll down toward the bottom and then start scrolling back up, you'll notice the scroll position bouncing around erratically. In the console log you'll also see pageChange events with skip values out of order. i.e. - when scrolling up and the skip value decreasing, you may suddenly see a higher skip value appear after the grid's data changes. You may need to scroll to the bottom and then up and down a few times to trigger the erratic behavior. Scrolling all the way to the top seems to reset it again temporarily.

This isn't the best example, and in my application the behavior is far worse and makes the virtual scroll  paging unusable. Also, this behavior is only appearing in Chrome. I've tested in IE11, Edge and Firefox and in those other browsers it behaves as expected.

**Comment by rkonstantinov** [comment]
It seems that the behavior you have described is caused by the multiple requests resetting the data. Could you try wiring the observables in slightly different manner as demonstrated in this [modified plunkr](http://plnkr.co/edit/Zn9jkwzGtOSt5EcC3V6N?p=preview) and see if this helps.

**Comment by anottest** [comment]
I tried your suggestion in changing the observables, but it didn't help the problem. Even a single page event (or any event that updates the grid's data) can result in triggering a cascading effect where it goes into a paging loop as it scrolls down to the bottom. i.e. - scroll just enough to trigger a single pageChange event, new data is retrieved asynchronously and passed to the grid, data update in the grid automatically triggers another pageChange event, and this cycle continues. I have also seen this happen when scrolled to the middle of the grid and initiating a Sort - which also updates the data and then triggers the pageChange event loop.

**Comment by rkonstantinov** [comment]
Unfortunately, I'm not able to re-create such auto-scrolling behavior locally. Could you please describe the exact steps which needs to be taken in order to observe the issue in the sample you have provided.
