### ISSUE TITLE
Row index is wrong when there are more than two levels of grouping

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1021]
When there are more than two levels of grouping, the row index of all items is wrongly offset by increasing margin. Observable in the following example when the data is grouped by more than two fields:

[https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/](https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/)

**Comment by ipeshev** [comment]
Fixed in v1.6.0
