### ISSUE TITLE
MultiSelect's options lists opens each time a selected tag is deleted

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1022]
The MultiSelect's dropdown list of options is opened each time a selected item is deleted via clicking the respective Tag's close ("X") button.

Reproducible only in applications, built with Angular CLI.

**Comment by rusev** [comment]
Seems to be silently fixed by some other code :)

Works in the example - https://stackblitz.com/edit/angular-cu9xaq
