### ISSUE TITLE
Label directive [for] doesn't generate a "for" attribute

### ISSUE THREAD

**Issue by MattWorrall** [telerik/kendo-angular#1023]
## I'm submitting a...

* Bug report 

## Current behavior

The documentation states that by adding a template reference variable to a Kendo form input directive such as a datepicker or dropdownlist, then using the Label directive, adding a [for] binding to a label referencing that template reference variable, the for attribute will be added to the rendered label linking it to the form input. This does not seem to work. 

## Expected behavior

A "for" attribute should be added to the label referencing the input element created by an associated Kendo form input directive.

## Minimal reproduction of the problem with instructions

This issue can be seen in the online demo / documentation. I've saved the Plunker from the Label directive documentation: http://plnkr.co/edit/29EnefthqsPneVXL27HX?p=preview

Inspect the rendered code and the label is rendered as `<label>Age:</label>` with no "for" attribute being rendered.

## What is the motivation or use case for changing the behavior?
This behaviour is important for satisfying accessibility requirements.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 61
- Edge version 40.15063.674.0

System:
- TypeScript version: 2.5.3 
- Node version: 6.9.1 & 3.10.8
- Platform:  Windows

**Comment by ggkrustev** [comment]
Hi @MattWorrall,

the Label directive focuses the component using its API, unlike rendering a specific `for` attribute. The main reason is that the component doens't render any ID to the HTML focusable element.

I agree that connecting the `<label>` element to the focusable element (`<input />` in most cases) will be a nice addition to the directive and will improve its accessibility. We will need to change the input components rendering (add an ID to the input) before the Label directive is connected to them. We will start working on this feature right away as it has high implication to all targeting accessible app.

Will update the thread with more details once the required changes are done.

**Comment by MattWorrall** [comment]
Hi @ggkrustev 

Any progress update on this?

**Comment by ggkrustev** [comment]
Hi @MattWorrall, please excuse us for the delay. We shifted the priority a bit. Nevertheless, this issue has high priority and we should start working on it pretty soon (within a week time period). I will update the thread right after we have a dev version.

**Comment by ggkrustev** [comment]
Here I will list all related components that should be modified in order to allow the label to focus by ID. You can also see the progress done so far:
- [ ] DateInputs package
- [ ] Inputs package
- [ ] Buttons package
- [ ] DropDowns package
- [ ] Upload

**Comment by MattWorrall** [comment]
Thanks for teh update @ggkrustev

**Comment by ggkrustev** [comment]
All relevant packages are officially released and the desired behavior should be already available. Will close the thread as resolved.
