### ISSUE TITLE
Selecting in grids with nested grouping

### ISSUE THREAD

**Issue by PhilSinnett** [telerik/kendo-angular#1024]
## I'm submitting a...

* Bug report 

## Current behavior

when using selection in the Kendo grid where there are nested groups, sometimes multiple rows either side of a group bracket are unintentionally selected.  This seems to happen only when there are multiple items in the group above the bracket, and the grouping bar contains two groups. 

## Expected behavior
only one row should be selected.

## Minimal reproduction of the problem with instructions
Try selecting either 'Scottish Longbreads', 'Gudbrandsdalsost' or 'Pâté chinois' in the plunker:
[](http://plnkr.co/edit/WQoRLPFQtjxnf9znc0eM?p=preview)

## What is the motivation or use case for changing the behavior?
I have nested grouping e.g. Business Zone>Aisle>Planogram and need to multi select in order to edit properties on multiple products at once.

## Environment

Browser:

- Chrome (desktop) version 61.0.3163.100

**Comment by PhilSinnett** [comment]
sorry the link in the previous comment should be:

http://plnkr.co/edit/WQoRLPFQtjxnf9znc0eM?p=preview

**Comment by Raisolution** [comment]
Hi @PhilSinnett,

Thank you for reporting this issue. It is related to the [following one](https://github.com/telerik/kendo-angular/issues/1021) - row indexes are used to generate the unique checkbox id attributes, and become incorrect in the case of more than 2 groups. Fixes for both are coming shortly.

**Comment by evan-carey** [comment]
Just to add another example:

http://plnkr.co/edit/uYofVz7YrSaBvp2onZ2z?p=preview

It logs the rowIndex on cellClick. You can see Boston Crab Meet has the same rowIndex (2) as the second Aniseed Syrup.

Thanks for looking into this!

**Comment by PhilSinnett** [comment]
According to the ChangeLog the 1.6.0 release is supposed to fix the [Row index Issue](https://github.com/telerik/kendo-angular/issues/1021) Does this mean that this issue should be fixed too?
I am now running 1.6.1 and I am still getting this problem.

**Comment by Raisolution** [comment]
The fix is available in versions 1.6.0 and later.
