### ISSUE TITLE
Do we have ListView in Kendo Angular ??

### ISSUE THREAD

**Issue by sunpasup** [telerik/kendo-angular#1025]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ggkrustev** [comment]
Hi @sunpasup, currently we do not have a dedicated ListView component. You can find more details in the other issue opened on the same subject:

https://github.com/telerik/kendo-angular/issues/813

Closing as duplicate
