### ISSUE TITLE
How to trigger upload button programatically

### ISSUE THREAD

**Issue by afsalcodehack** [telerik/kendo-angular#1028]
How can i trigger upload with my form submit in kendo angular ui. I need to trigger upload event from my post function

**Comment by Raisolution** [comment]
Hi @afsalcodehack,

You could use the [uploadFiles method](https://www.telerik.com/kendo-angular-ui/components/upload/api/UploadComponent/#toc-uploadfiles). Please use our support channels for issues, which are not bug reports.
