### ISSUE TITLE
Add the newly introduced DatePicker fast navigation options to the Grid DateFilterCellComponent

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1029]
The DatePicker now has new properties related to its newly introduced fast navigation feature, such as **activeView**, **topView**, **bottomView**.

It would be nice to introduce these options as configuration properties of the Grid DateFilterCellComponent as well.

**Comment by rkonstantinov** [comment]
This has been addressed with 1.6.3 version of `kendo-angular-grid` package.
