### ISSUE TITLE
Gauge chart for Angular 2/4

### ISSUE THREAD

**Issue by AkhilNaidu09** [telerik/kendo-angular#1030]
I want to implment gauge chart in my application, im using **Angular 4** with **Kendo UI**. do we have any gaguge chart components in **Kendo UI with Angular 4** implentation

![gauge-chart-3](https://user-images.githubusercontent.com/13352708/31881747-1fb1343e-b802-11e7-8066-3e55bfea2fc0.png)

**Comment by danielkaradachki** [comment]
We are currently working on the gauge components. You can follow their progress in [this](https://github.com/telerik/kendo-angular/issues/761) issue.
