### ISSUE TITLE
Latest date inputs package breaks server-side rendering

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1031]
Latest version of the kendo-date-inputs package triggers a reference error (document is not defined) during server-side rendering.

Seems to be caused by the following lines of code (for internal use only):

[https://github.com/telerik/kendo-angular-dateinputs/blob/4593ab967d8cfaed5523025f236607dabbb4d07b/src/calendar/services/dom.service.ts#L78](https://github.com/telerik/kendo-angular-dateinputs/blob/4593ab967d8cfaed5523025f236607dabbb4d07b/src/calendar/services/dom.service.ts#L78)

**Comment by ggkrustev** [comment]
Fixed in `@progress/kendo-angular-dateinputs@**1.3.1**`. 

Will close the thread as resolved. Please comment if the problem still persists.
