### ISSUE TITLE
kendo ui for angular grid date filter template not displaying as anticipated 

### ISSUE THREAD

**Issue by imgregduh** [telerik/kendo-angular#1032]
## I'm submitting a...

* Bug report 

## Current behavior

I am trying to have specific filter options for a date filter in the grid.  When I use filter="date" by itself it displays all the possible filters which is fine but I want to reduce the options.  So I removed the filter="date" filter from the column properties and added the ng-template with the kendo-grid-date-filter-cell to contain my own selected options but when I do that "is greater than or equal to" does not turn into "is after or equal to" when I open the dropdown.

## Expected behavior

I expect the dropdown to say "is after" instead of "is greater" and from the code in the package it looks like it was supposed to do that but it didnt.
## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/6hLq0WsHJzsi97ZCfpyC?p=info

## What is the motivation or use case for changing the behavior?

We expected a specific phrase to apply which was given out of the box that was already approved by our business unit.  Since, it does not display the correct phrase it is not approved by our business unit.
## Environment

Package versions:

```
+-- @angular/animations@4.4.6
+-- @angular/cli@1.4.9
+-- @angular/common@4.4.6
+-- @angular/compiler@4.4.6
+-- @angular/compiler-cli@4.4.6
+-- @angular/core@4.4.6
+-- @angular/forms@4.4.6
+-- @angular/http@4.4.6
+-- @angular/language-service@4.4.6
+-- @angular/platform-browser@4.4.6
+-- @angular/platform-browser-dynamic@4.4.6
+-- @angular/router@4.4.6
+-- @progress/kendo-angular-buttons@2.0.0
+-- @progress/kendo-angular-dateinputs@1.3.0
+-- @progress/kendo-angular-dropdowns@1.2.2
+-- @progress/kendo-angular-excel-export@1.0.4
+-- @progress/kendo-angular-grid@1.5.0
+-- @progress/kendo-angular-inputs@1.3.1
+-- @progress/kendo-angular-intl@1.2.2
+-- @progress/kendo-angular-l10n@1.0.4
+-- @progress/kendo-data-query@1.0.7
+-- @progress/kendo-drawing@1.4.0
+-- @progress/kendo-theme-default@2.43.1
+-- @types/jasmine@2.6.0
+-- @types/node@8.0.46
+-- codelyzer@3.2.1
+-- core-js@2.5.1
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.2.0
+-- rxjs@5.5.0
+-- ts-node@3.3.0
+-- tslint@5.8.0
+-- typescript@2.5.3
`-- zone.js@0.8.18


```

Browser:

- Chrome (desktop) version 61.0.3163.100  64bit
- Firefox version 56.0 64bit
- IE version 11.674.15063.0
- Edge version 40.15063.674.0
System:
- TypeScript version: 2.5.3
- Node version: 8.5.0
- Platform:  Windows

I also posted a question on stackoverflow with images. please to refer to there if you guys dont understand what I was explaining
https://stackoverflow.com/questions/46894859/date-filter-cell-template-not-showing-the-correct-filter-name-kendo-angular

**Comment by rkonstantinov** [comment]
Hey @imgregduh,

In this scenario you will need to manually customize the text for the operator using its `text` setting:

```html
<ng-template kendoGridFilterCellTemplate let-filter let-column="column">
   <kendo-grid-date-filter-cell [column]="column" [filter]="filter" operator="gte">
       <kendo-filter-gte-operator text="Is after or equal to"></kendo-filter-gte-operator>
  </kendo-grid-date-filter-cell>
</ng-template>
```

**Comment by imgregduh** [comment]
Hi @rkonstantinov 
Is what youre recommendation the intended behavior or was it supposed to automatically convert the text?

**Comment by rkonstantinov** [comment]
Indeed, this is the intended behavior as the `gte operator` is not aware of the type of the filter it is used with. 
However, we have added separate `after` and `after-eq` operator components, which to be used with the date filter in the place of the `gte` operator component. They are already available in the [@dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
