### ISSUE TITLE
DateInput appending new digits to segments instead of replacing the current value

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1034]
When a value (e.g. day or month) is entered in a DateInput segment, and then this segment is focused again, newly typed numbers are appended to the existing value (instead of replacing it) leading to unexpected results:

[https://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/#toc-basic-usage](https://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/#toc-basic-usage)

Click the "days" segment, type "1", blur. Click there again, type 0 (or other digit) - it is appended to the previously typed 1, the focus goes on the next segment. 

Click the days segment again (it now contains for example "10"). As more digits cannot be added and still have a valid day, the input now behaves as expected and typing a digit replaces the whole segment.

**Comment by ipeshev** [comment]
Fixed in v1.4.0-dev.201710310730

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.
