### ISSUE TITLE
Multiple GridComponent on one page

### ISSUE THREAD

**Issue by zchpit** [telerik/kendo-angular#1035]
Hi. 

I'm tring to have 2 pivot grids on one page. In example 2 this kinds of grid:
https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/grouping/grouping/
https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/hierarchy/

In one page. I need to use: GridComponent 
https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/

But how to match first grid component with first grid and second grid component with second grid?

**Comment by gyoshev** [comment]
We strive to keep this repository for bugs related to the components, as stated in the README and the issue template. For questions about how to implement a given scenario, please [submit a support ticket](https://www.telerik.com/account/support-tickets) or [ask on StackOverflow](http://stackoverflow.com/questions/ask?tags=kendo-ui-angular2,angular2).

**Comment by MaklaCof** [comment]
May I suggest open question on StackOverflow and open support ticket to answer your question on SO.
I once ask question on SO, but never get an answer. I then open support ticket and ask them to answer my question on SO and they did in the next hour.

I prefer SO (and kendo Angular team should too). This way another kendoAngular user may benefit from the answer instead multiple users open same support tickets.

**Comment by zchpit** [comment]
I have asked question on SO earlier: 
https://stackoverflow.com/questions/46892779/multiple-gridcomponent-in-kendo-ui-for-angular

**Comment by nijat12** [comment]
Bump
