### ISSUE TITLE
Incorrect tab order in IE of autocomplete

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1038]
## I'm submitting a...

* Bug report 

## Current behavior
Autocomplete is always first focused when TAB is pressed

## Expected behavior
Autocomplete should follow tab order in the page, according to tabindex
## Minimal reproduction of the problem with instructions
 

- Open [this demo](http://plnkr.co/edit/cqKe8bLeOeeR01fpPZWd?p=preview)

- Try to click in result tab to focus it and then press TAB

## Environment

Package versions:

```
v1.2.3-dev.201710120510
```

Browser:

- IE version 11

**Comment by tapopov** [comment]
Native tabindex support added in `1.3.0`.
