### ISSUE TITLE
Grid selection triggers a JavaScript error when ChangeDetectionStrategy is OnPush

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1040]
The issue is observable in the following example:

[http://plnkr.co/edit/WARFBrOHNI8n3fyimOUb?p=preview](http://plnkr.co/edit/WARFBrOHNI8n3fyimOUb?p=preview)

Click on the same row twice, and check the console:

VM807 zone.js:195 Uncaught TypeError: Cannot read property 'ProductID' of undefined
    at t.e.getItemKey (VM477 kendo-angular-grid.js:3)
    at eval (VM477 kendo-angular-grid.js:3)
    at Array.forEach (<anonymous>)
    at t.e.onSelectionChange (VM477 kendo-angular-grid.js:3)
    at b.schedulerFn [as _next] (VM465 core.umd.js:3679)
    at b.__tryOrUnsub (VM468 Rx.system.min.js:7)
    at b.next (VM468 Rx.system.min.js:7)
    at b._next (VM468 Rx.system.min.js:7)
    at b.next (VM468 Rx.system.min.js:7)
    at EventEmitter.b.next (VM468 Rx.system.min.js:7)

Reported in Ticket ID: 1086384

**Comment by ipeshev** [comment]
Shipped with v1.6.2

**Comment by cod7alex** [comment]
Hi, i am still seeing this on 1.6.4 with the similar code to example in first post.

**Comment by cod7alex** [comment]
@Raisolution Hi, thank you for quick response. I need to use the `selectedRows` and `deselectedRows` in current approach. I guess it is not possible with `selectedKeysChange`?

**Comment by Raisolution** [comment]
@cod7alex the `selectedKeysChange` event is fired after the `selectedKeys` collection is updated -
 [documentation on the topic](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-persisting-the-selection). It holds the currently selected rows by the specified `kendoGridSelectBy` key. Here is an [example of this](https://plnkr.co/edit/TC2hH2aa8gyc0l0WzlGq?p=preview). Is this suitable for the case, instead of manual handling of the selected and deselected row?

**Comment by cod7alex** [comment]
@Raisolution I am using ngrx/store and selected keys are coming from store because selection can change as a result of user action outside grid. It looks something like this:

```
@Component({
    selector: 'my-app',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <kendo-grid #kendoGrid
            [data]="data | async"
            [height]="500"
            [selectable]="true"
            [kendoGridSelectBy]="'ProductID'"
            [selectedKeys]="selected| async"
            (selectionChange)="onSelectionChange($event)"
            >
            <kendo-grid-checkbox-column>

            </kendo-grid-checkbox-column>
            <kendo-grid-column field="some" title="some" [width]="300"></kendo-grid-column>
        </kendo-grid>
    `
})
export class AppComponent {
    private data: Observable<any[]>;
    private selected: Observable<number[]>;
    
    constructor() {
        this.data = // get it from store
        this.selected= // get it from store
    }

    onSelectionChange(event: any) {
      // update store here and after that selected observable will receive new value
    }
```
