### ISSUE TITLE
PDF Export on Hidden Elements

### ISSUE THREAD

**Issue by Milan03** [telerik/kendo-angular#1041]
Is there a way to export an HTML element into the PDF while having that element hidden from user view? I've been looking through the documentation - if someone could point me in the right direction.

**Comment by tsvetomir** [comment]
The [Positioning Content Off-Screen](https://www.telerik.com/kendo-angular-ui/components/pdfexport/content-styling/#toc-positioning-content-off-screen) section addresses this scenario.

Please note that this issue tracker is for bug reports only. Assistance with specific scenarios can be obtained through the support system or on community sites like StackOverflow.

**Comment by tsvetomir** [comment]
The help section describes how to hide the entire exported content from the user. If your scenario calls for hiding specific elements only, then you should use the `k-pdf-export` class or the `kendo-pdf-document` element, also described in the same article. For example:

```css
.export-elements {
  display: none;
}
.k-pdf-export .export-elements {
  display: block;
}
```

**Comment by Milan03** [comment]
The positioning off-screen doesn't seem to be working - even in the demo plunkr it is not displaying the off-screen content.

I just tried your example using the `k-pdf-export` and not sure if I'm implementing it wrong but doesn't seem to work either: 
`.export-elements {
    display: none;
}

.k-pdf-export .export-elements {
    display: block;
}`

`    <div *ngIf="submitButtonValue == UPDATE_MODE" class="operator-display k-pdf-export">
        <ul class="nav navbar-nav">
            <li>
                <span aria-label="current operator" class="header-display"> Log Operator: {{ logOperator }}  </span>
            </li>
        </ul>
    </div>`

**Comment by tsvetomir** [comment]
The demo is indeed broken, as discusses in #1044. A fix is proposed there.

I've created [a plunkr](http://plnkr.co/edit/BW8MvHort9mWSG6DzWBf?p=preview) demonstrating the use of the `.k-pdf-export` class to hide content on screen. Please note the usage of `ViewEncapsulation.None`, as the exported content is appended to the document body.

**Comment by Milan03** [comment]
Thanks for clarification - can close this.
