### ISSUE TITLE
Kendo bootstrap theme is not applied properly

### ISSUE THREAD

**Issue by codehippie1** [telerik/kendo-angular#1042]
I have customized bootstrap theme and loaded them in variables.css and included before importing kendo-bootstrap-theme

```
@import "variables"; /*Contains the downloaded variable created using bootstrap theme builder.*/
@import "~bootstrap/scss/bootstrap";
@import "~@progress/kendo-theme-bootstrap/scss/all";
```
Contents of downloaded variable.scss

```
$base-theme: Bootstrap;
$skin-name: t-latest;
$accent: #8cc63f;
$secondary: #005596;
$info: #5bc0de;
$success: #5cb85c;
$warning: #ffbb5b;
$error: #e3470e;
$body-bg: #ffffff;
$body-color: #000000;
$component-bg: #f5f5f5;
$component-color: #1c3a4c;
$card-cap-bg: #4189c7;
$card-cap-color: #ffffff;
$series-a: #d26e46;
$series-b: #ac941c;
$series-c: #40a9e3;
$series-d: #016a98;
$series-e: #7a8c95;
$series-f: #355261;
```
Unfortunately, the styles are getting applied only partially. Button color is still grey(#f6f6f6), Grid column header are black and not bold.

**Comment by gyoshev** [comment]
@codehippie1 can you please provide the version of the kendo-theme-bootstrap and the bootstrap package?

**Comment by codehippie1** [comment]
@gyoshev Thanks for responding. Here are the versions I use.
kendo-theme-bootstrap **v2.8.4**
bootstrap **v4.0.0-beta**

Interestingly enough I have even tried **v3.0.0-dev.201707131512** to see if this is fixed. I have also tried bootstrap **v4.0.0-beta.2**

Unfortunately none of the combinations seem to work. Please note that kendo-theme-default and variables customizations works without any issues.

**Comment by gyoshev** [comment]
To resolve the problem, include the kendo-theme-bootstrap source before importing bootstrap:

```scss
@import "variables";
@import "~@progress/kendo-theme-bootstrap/scss/all";
@import "~bootstrap/scss/bootstrap";
```

This way the variables from the ThemeBuilder are expanded correctly, before compiling the Bootstrap framework.

**Comment by codehippie1** [comment]
@gyoshev Thank you. That fixed it. It would be great mentioning this in the documentation to help other developers.

**Comment by shamilovtim** [comment]
This was never added to the docs, FYI.

**Comment by gyoshev** [comment]
@shamilovtim Thanks for the feedback. The code was added to the ThemeBuilder help topic, but it might be worthwhile to move this information to the styling overview, where it is easier to find.

**Comment by EoinGriffin-AI** [comment]
Oh wow, took me 2 days to come across this solution by @gyoshev 
Re-ordering the imports worked!

I still have a problem where importing the specific styles for a `dropdownlist` don't import all the necessary dependencies, but this at least gets me closer to what I'm aiming for.

**Comment by Raisolution** [comment]
Note is available in the [documentation](https://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/#toc-installation).
