### ISSUE TITLE
Documentation PDF Export Styling: Positioning Content Off-Screen

### ISSUE THREAD

**Issue by ramious76** [telerik/kendo-angular#1044]
## I'm submitting a...

* Documentation issue or request

## Current behavior

The documentation and example for  Angular 4 Kendo UI PDF Export Styling: Positioning Content Off-Screen does not work properly and the PDF comes out blank.  The provided plunker link supplied at https://www.telerik.com/kendo-angular-ui/components/pdfexport/content-styling/#toc-positioning-content-off-screen 
New plunker link for the identical code if required.  http://plnkr.co/edit/ZG5CpzuiDqznYpWwSkyI?p=preview 
## Expected behavior

PDF should have the text supplied in the kendo-pdf-export tag visible in the PDF
## Minimal reproduction of the problem with instructions

The provided plunker link supplied at https://www.telerik.com/kendo-angular-ui/components/pdfexport/content-styling/#toc-positioning-content-off-screen 
Click the plunker link under Content off screen and click the Save as PDF link once the page is loaded. 
New plunker link for the identical code if required.  http://plnkr.co/edit/ZG5CpzuiDqznYpWwSkyI?p=preview and click the Save as PDF link once the page is loaded. 
## What is the motivation or use case for changing the behavior?

To have a working documentation example
## Environment
Windows 7 IE 11 and Windows 10 Edge.
Package versions:

```
Unknown.  Supplied by Kendo
```

Browser:

- IE version 11
- Edge version 40.15063.674.0

**Comment by tsvetomir** [comment]
Thanks for the heads-up. I couldn't locate the exact change that broke this example. In any case, moving the styles to a wrapping element works, [see plunkr](http://plnkr.co/edit/3FlM8FzsZVKiz6DhoJGo?p=preview):

```html
    <div style="position: absolute; left: -1000px; top: 0;">
      <kendo-pdf-export #pdf paperSize="A4" margin="1cm">
      ...
      </kendo-pdf-export>
    </div>
```

I'll update the snippet to use this approach unless we manage to identify a specific regression.

**Comment by tsvetomir** [comment]
Fixed in the current version of the [Hidden Content](https://www.telerik.com/kendo-angular-ui/components/pdfexport/hidden-content/) exporting example.
