### ISSUE TITLE
Please a "hidden" property to the PanelBarItemModel

### ISSUE THREAD

**Issue by jmaronge** [telerik/kendo-angular#1048]
## I'm submitting a...

* Suggestion for improvement

## Expected behavior

 
Add "**hidden**" property to the PanelBarItemModel.  

When binding to the "**items**" property we need to have a way to hide certain items in the list.  The scenario we are dealing with now involves filtering items in the panelbar.

**Comment by jmaronge** [comment]
Is this something that is in consideration to be done?  If so, has any time line been set?

**Comment by ipeshev** [comment]
Feature available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0

https://stackblitz.com/edit/angular-dvyat5?file=app/app.component.ts
