### ISSUE TITLE
A Grid with resizeable columns resets on page change  

### ISSUE THREAD

**Issue by rvrn22** [telerik/kendo-angular#1049]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
The grid columns sizes reset after page change.

## Expected behavior
The grid should remember the columns sizes across page changes.

**Comment by rusev** [comment]
@rvrn22 Seems like the Grid operates correctly in this example - https://plnkr.co/edit/qO0SX2VU9YQm0dIMczT6?p=preview

Column width is persisted over Grid page changes. Am I missing something in the example?
