### ISSUE TITLE
A checkbox in DropDowns Item template is not working as expected

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1051]
When there is a regular (or a Kendo UI) checkbox within an item template in a component from the DropDowns module, clicking in the checkbox is not reflected in any way (no click or change event triggered), and the list of options is closed even when **_autoClose_** is set to **false**:

[http://plnkr.co/edit/akHurCxHiaTkWCXLd81Y?p=preview](http://plnkr.co/edit/akHurCxHiaTkWCXLd81Y?p=preview)

It would be nice to provide an enhancement allowing for scenarios using checkboxes (possibly with some associated custom logic) within the DropDowns item templates.

**Comment by dimitar-pechev** [comment]
Checkboxes inside a multiselect template are now clickable (they emit the corresponding events) and don't trigger the closing of the multiselect. The enhancement is abailable in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) - kendo-angular-dropdowns package  v3.1.1-dev.201810100906.

**Comment by dimitar-pechev** [comment]
The fix is released in v3.2.0 of the `@progress/kendo-angular-dropdowns` package.
