### ISSUE TITLE
valueChange not fired on first clear click

### ISSUE THREAD

**Issue by chrisdreams13** [telerik/kendo-angular#1052]
## I'm submitting a...

* Bug report 

## Current behavior

When the page is loaded, autocomplete has an initial value and click the clear button the valueChange function is not fired. After this, change function works ok on clear button.
## Expected behavior

Clear button should fire valueChange when has an initial value.

## Minimal reproduction of the problem with instructions

1. Open plunker http://plnkr.co/ESeEfh2ZIKxBZMKYnWGK
2. Click on clear
3. Notice valueChange function not fired
4. Enter a new value (alert is fired)
4. Click on clear (alert is fired)

## What is the motivation or use case for changing the behavior?

Clear related data in model, when the autocomplete is used with complex items (eg User{ id, name }), the text is cleared (name), but the id remains in the model as valueChange is not fired to clear it.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 61.0.3163.100
- Firefox version 56.0.2 (64-bit)
- IE version 11.0.9600.18816

System:
- TypeScript version: XX 
- Node version: XX  
- Platform: Windows

When I test in IE, also changeValue is fired twice when the text is entered

**Comment by ipeshev** [comment]
Shipped with v1.4.0
