### ISSUE TITLE
Demo not responding to interactions

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1054]
## I'm submitting a...

* Bug report 

## Current behavior
This [demo](https://www.telerik.com/kendo-angular-ui/components/dropdowns/) is not working on SAFARI 10 ( on Safari 9 it does)

## Expected behavior
Demo should be working 

## Environment

Package versions:
```
v1.2.3-dev.201710301334
```

Browser:

- Safari (desktop) version 10

**Comment by valchev** [comment]
It works fine on Safari version 11.0.1 (11604.3.5.1.1) which is the current version of the browser.
Safari version 10 is outdated and not supported by Apple according to [this chart](https://en.wikipedia.org/wiki/Safari_version_history).
