### ISSUE TITLE
Grid filter operator with ignoreCase not working anymore

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#1060]
## Current behavior
We use the kendo grid and with several filters on it. We use case insensitive filtering since for our use cases case sensitive filtering would be bad.

We are using unittests which are are built on a daily bases and we found one of our tests starting to fail today (06.11.2017) morning testing the usage of the filter operator for our purposes. It looks like that in the latest versions of the kendo package with the filter something went wrong.

## Expected behavior
We would expect that the filter operators are really doing case insensitive comparison if we configure so as it did a day ago.

## Minimal reproduction of the problem with instructions
The reason for this issues seems to lie in this lines of code:
Filter-no-eval.js: 78
`
var transformFilter = function (_a) {
    var field = _a.field, ignoreCase = _a.ignoreCase, value = _a.value, operator = _a.operator;
    field = !isPresent(field) ? function (a) { return a; } : field;
    var itemProp = typedGetter(isFunction(field) ? field : getter(field, true), value, ignoreCase);
    value = convertValue(value, ignoreCase);
    var op = isFunction(operator) ? operator : operatorsMap[operator];
    return function (a) { return op(itemProp(a), value, ignoreCase); };
};
`
Because the itemProp(a) is not doing any value conversion according to the ignoreCase property. The operator function itself lacks any functionality too and hasn't even a parameter for ignoreCase. Therefore nothing happens in this function either.

## Environment

Package versions:

progress/kendo-angular-buttons@1.1.0
progress/kendo-angular-popup@1.3.0
progress/kendo-popup-common@1.2.3
progress/kendo-angular-dateinputs@1.3.1
progress/kendo-date-math@1.1.0
progress/kendo-angular-dialog@1.3.0
progress/kendo-angular-dropdowns@1.2.2
progress/kendo-angular-resize-sensor@1.0.4
progress/kendo-angular-excel-export@1.0.4
progress/kendo-file-saver@1.0.4
progress/kendo-ooxml@1.0.2
progress/kendo-angular-grid@1.6.0
progress/kendo-angular-pdf-export@1.0.1
telerik/kendo-draggable@1.5.1
progress/kendo-angular-inputs@1.3.2
telerik/kendo-inputs-common@2.2.2
progress/kendo-angular-intl@1.2.2
telerik/kendo-intl@1.2.1
progress/kendo-angular-l10n@1.0.4
progress/kendo-angular-layout@1.0.7
progress/kendo-data-query@1.1.0
progress/kendo-drawing@1.4.0
progress/kendo-theme-default@2.43.2

**Comment by rkonstantinov** [comment]
Hi @rdnscr, the issue is a regression due to the re-write of how the filter function predicate is created. The fix is currently available in the latest [`@dev`](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version of the `kendo-data-query` package. Or you could downgrade the package to v1.0.7.

**Comment by tsvetomir** [comment]
Fix shipped in v1.1.1 of `@progress/kendo-data-query`
