### ISSUE TITLE
Angular 5 complete Support 

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#1061]
* Documentation issue or request

## Current behavior
Is the current Stable Release Angular 5 compatible? Or when can I Upgrade my internal projects to Angular 5, when I use Kendo Ui?

**Comment by tsvetomir** [comment]
All packages have been updated to support Angular 5. There are no known compatibility issues.

Please note that the Upload component has been bumped to 2.0 with added support for HttpClient, see #1055. The new module has been available since Angular 4.3 and 5.0 deprecates the old one. Existing projects can continue to use Upload 1.x until the module is dropped in Angular 6.

We'll also be switching the online demos to 5.0 with a site update later today.

**Comment by DGolverdingen** [comment]
Hi @tsvetomir 

Are you sure the latest version of upload is correct? I was not able to import the class FileInfo.
I got it only to work after downgrading to 1.2.1.

layout and sortable have wrong angular peers in angular 5 project.

![image](https://user-images.githubusercontent.com/29942500/32484175-2eebf328-c39f-11e7-841f-3eef896edb7d.png)

**Comment by nlgi** [comment]
Hi,

Something is wrong with UploadModule, maybe a "known error" with TypeScript 2.5 compiler.
Error:
`ERROR Error: Uncaught (in promise): Error: Unexpected value 'UploadModule' imported by the module 'MyModule'. Please add a @NgModule annotation.`

There are others components with this error, see https://github.com/gund/ng-dynamic-component/issues/69#issuecomment-342273627 

Many thanks,

**Comment by tsvetomir** [comment]
@DGolverdingen can you please open a separate issue for the Upload with more details? There are no changes to the FileInfo class, and we'll need to investigate. The Sortable and Layout were released only in the dev channel, apologies - will double-check the rest.

@nlgi Angular seems to be [locked down](https://github.com/angular/angular/blob/master/package.json#L101) to Typescript 2.4.2, this is what the Angular CLI sets up as well.

**Comment by haltinok** [comment]
When I upgrade to Angular 5 I get this error on npm start "ERROR in src/app/app.module.ts(5,30): error TS2307: Cannot find module '@progress/kendo-angular-layout'.Hash: 3d2f45dbccadd891ebc6"

**Comment by vijay342** [comment]
is kendo still compatable with anguler 5
