### ISSUE TITLE
ComboBox list of options remains in an unexpected position when filtered

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1069]
When the ComboBox is positioned near the bottom of its container such that the list of options is forced to be opened above the component, and the list is filtered to the point where only the first few items remain, the popup, containing these items, remains at the same place where it was before filtering, and there is an empty space between the popup and the ComboBox:

[http://plnkr.co/edit/O1tMgJIsRqqpf0aulPuR?p=preview](http://plnkr.co/edit/O1tMgJIsRqqpf0aulPuR?p=preview)

1) Open the list
2) Type "s"

Suggested workaround:

Toggle the popup programmatically to trigger re-rendering in the correct position:

[http://plnkr.co/edit/Ro9o3OPv6Levu06LsvH1?p=preview](http://plnkr.co/edit/Ro9o3OPv6Levu06LsvH1?p=preview)

**Comment by tapopov** [comment]
Seems to be related to https://github.com/telerik/kendo-angular/issues/1101

**Comment by ipeshev** [comment]
Shipped with: v1.3.1
