### ISSUE TITLE
Grid emits selectionChange event when Grid has no any data

### ISSUE THREAD

**Issue by tkadm** [telerik/kendo-angular#1072]
## Current behavior

 When grid has no data, clicking on the label "No records avalable" emits selectioinChange event with filled (with useless data) SelectedRows property of event object. It looks like some data were selected. But they were not. Is it a bug? I think it is.
## Expected behavior

When grid has no data, selectionChange event must not be emitted. (In my opinion)
## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/ZK1ZfoyqOFWjYKUvZg3z?p=preview
Click the "No records avalable" label and see some information in console.

## Environment

Package versions:
@angular/... v5.0.0
@progress/kendo-angular-grid v1.6.1

Browser:

- Chrome (desktop) version  59.0.3071.86

System:
- TypeScript version: 2.6.1
- Node version: 8.9.1 , npv version: 5.5.1
- Platform:  Windows 7 64-bit

**Comment by ipeshev** [comment]
Fixed in v1.6.2-dev.201711201320
