### ISSUE TITLE
[DatePicker]: disabled applies hover style

### ISSUE THREAD

**Issue by tipag** [telerik/kendo-angular#1073]
## I'm submitting a bug

* Bug report:
If you set disabled to true on DatePicker there is a hover style applied, which doesn't give the impression that the control is disabled.

## Current behavior
background color is set to #fff

## Expected behavior
shouldn't apply hover style or at least leave barckground color the way it is on hover (I think it is transparent but please check.)

## Minimal reproduction of the problem with instructions
Is reproduceable with the disabled datepicker example. Add a background color to the example-wrapper to better visualize the problem:

@Component({
    selector: 'my-app',
    template: `
        <div class="example-wrapper" style="background:red;">
            <p>Select a date:</p>
            <kendo-datepicker [disabled]="true" [value]="value"></kendo-datepicker>
        </div>
    `
})

class AppComponent {
    public value: Date = new Date(2000, 2, 10);
}

## What is the motivation or use case for changing the behavior?
DateInput has the expected behavior (no change on hover in disabled mode), and DatePicker should behave the same way.

**Comment by ggkrustev** [comment]
Hi @tipag,
thanks for reporting this issue. Indeed, the component didn't apply `k-state-disabled` class properly. This is fixed in the latest `@dev` version of the package.
We will release the fix officially later this week.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.

Please feel free to comment if something is not correct.

**Comment by DhDhanesh** [comment]
how to not allow enter date manually?
