### ISSUE TITLE
DialogService and CustomComponent -> how to permit component to close dialog itself

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1075]
I just would like to permit custom component to be used as Dialog so i have something as:

```
this.dialogRef = this.kendoDialogService.open({
            title: "Please confirm",
            appendTo: this.dialogContainerRef,
            content: MyCustomComponent
        });
```

Now i would like to generate results and close dialog inside `MyCustomComponent` and i would like to have `dialogRef` as Dependency on `MyCustomComponent` constructor. is it possible? i don't see any documentation related to that.
Only solution find right now is to assign dialogRef to component instance for example:
```
const myCustomComponent = <MyCustomComponent>this.dialogRef.content.instance;
myCustomComponent.dialogRef = this.dialogRef;
```

but i really don't like approach like that.
Any advice? Improvements?

**Comment by gyoshev** [comment]
@meriturva I believe that the workaround that you have found is the shortest way to achieve this. If I understand correctly, the changes in https://github.com/telerik/kendo-angular/issues/1046 should provide the same functionality?

**Comment by meriturva** [comment]
@gyankov Actually this issue is related to have injector with dialogRef during creation of dialog component. So it could be possible to have constructor like:

`constructor( public dialog: DialogRef )`

Issue #1046 is related to dialog view and find a way to use same template directive (so it is different in my case).

**Comment by gyoshev** [comment]
Ah, I see. This will be easier to implement than the functionality in the other issue.

**Comment by meriturva** [comment]
Hi @gyoshev ... any news here? thanks

**Comment by gyoshev** [comment]
@meriturva we are currently adding this functionality to the dialog service; I will update the thread once it is released in the development channel.

**Comment by gyoshev** [comment]
The functionality has been released on the development channel, version `v2.1.0-dev.201801191448`.

**Comment by gyoshev** [comment]
The fix is officially released in `2.1.0` of the dialog package.

**Comment by meriturva** [comment]
Thanks @gyankov . Are you going to update doc to show this behaviour?

**Comment by gyoshev** [comment]
Yes, the docs are updated and pending a website upload. You can see this on the [site development channel](https://www.telerik.com/kendo-angular-ui-develop/components/dialogs/dialog/service/#toc-access-dialog-from-child-component).
