### ISSUE TITLE
[Sortable] Template containing a component prevents dragging in Safari

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#1077]
## I'm submitting a...
* Bug report 

## Current behavior

Having a component in the template prevents the items to be dragged around.
## Expected behavior
One should always be able to move items around.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/8KlEo6eQPcJIyDJl03sY?p=preview
Open in Safari and try moving an item with the mouse.

## Additional information
Reported in ticket 1140044

**Comment by christied** [comment]
We have this same issue - when using a kendo-switch component inside the sortable template it won't drag/drop in Safari and in Mac Chrome the dragged row isn't being contained and seems to move to the top of the page.
Is there any timeline on working on this bug?

**Comment by tapopov** [comment]
Hi @christied 
The Sortable component is still going under a major overhaul. This issue is taken into consideration, however we cannot provide a time-frame yet.

**Comment by ipeshev** [comment]
Works [properly](https://stackblitz.com/edit/angular-mizblr-rvr7uj?file=app/app.component.ts) with[ latest dev versions](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of @telerik/kendo-draggable and @progress/kendo-angular-sortable.

**Comment by danielkaradachki** [comment]
Fixed in 2.1.0
