### ISSUE TITLE
PDF Export Multiple Margin Settings

### ISSUE THREAD

**Issue by ramious76** [telerik/kendo-angular#1078]
## I'm submitting a...
* Documentation issue or request

## Current behavior
Any attempt to assign more than one margin setting leaves no margins .

## Expected behavior
To be able to give different margins for headers and footers (top and bottom) than that of the side margins to give a professional look

## Minimal reproduction of the problem with instructions
Tried multiple different ways to set multiple margins in the margin setting for pdf export
In plunker is a direct way
Attempted a var in TypeScript as var margin = { ...settings...}

Plunker:
http://plnkr.co/edit/XBfcEkXUkpFbfcHftWqR?p=preview

## What is the motivation or use case for changing the behavior?
With a longer footer for a privacy statement required by law this takes up a bit of the page and with out the ability to set a custom footer this leaves the page looking very shrunk.

## Environment

Package versions:
As provided by Kendo multi-page automatic example at https://www.telerik.com/kendo-angular-ui/components/pdfexport/multi-page-content/ 

Browser:

IE 11.1532.14393.0
Edge 38.14393.1066.0
Firefox 56.0.2 (x64)

System:
Not necessary

**Comment by danielkaradachki** [comment]
You should [bind the property](https://angular.io/guide/template-syntax#property-binding--property-) in order to correctly set its value:
http://plnkr.co/edit/HvL1kdiULjhfQPOcwqbe?p=preview
