### ISSUE TITLE
AbstractControl.setValue has a delayed update on the UI for kendo datepicker

### ISSUE THREAD

**Issue by eatinasandwich** [telerik/kendo-angular#1079]
## I'm submitting a...

* Regression report 

## Current behavior

Using the setValue function on an angular AbstractControl causes a delayed update to the UI. After calling the function the UI will initially look like the value has not changed. However, any validators on the component will work showing that the value has been updated internally. Upon focusing the datepicker control (tabbing to it or clicking on it) will update the view showing the new value.

## Expected behavior

The new value should update in the view without user interaction. 

## Minimal reproduction of the problem with instructions

Pasting repro code here because I don't believe the plunkr examples are using date inputs version 1.4.0 yet.

app.component.ts:
```
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators, FormBuilder} from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app works!';
  form: FormGroup;

  constructor( private fb: FormBuilder) {  }

  ngOnInit() {
    this.form = this.fb.group({
      oeStart: new FormControl(),
      oeEnd: new FormControl(),
    });
  }

  oeStartSelect(newDate: Date) {
    this.form.get('oeEnd').setValue(newDate);
  }
}
```

app.component.html:
```
<form [formGroup]="form">

  <kendo-datepicker
  (valueChange)="oeStartSelect($event)"
  formControlName="oeStart"
  ></kendo-datepicker>

  <kendo-datepicker
  formControlName="oeEnd"
  ></kendo-datepicker>

</form>
```

app.module.ts:
```
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { DateInputsModule } from '@progress/kendo-angular-dateinputs';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, 
    BrowserAnimationsModule, 
    DateInputsModule,
    FormsModule,
    ReactiveFormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Rest is for the most part just an "ng new" project

## Environment

Package versions:

```
+-- @angular/animations@4.2.5
+-- @angular/cli@1.0.0
+-- @angular/common@4.2.5
+-- @angular/compiler@4.2.5
+-- @angular/compiler-cli@4.2.5
+-- @angular/core@4.2.5
+-- @angular/forms@4.2.5
+-- @angular/http@4.2.5
+-- @angular/platform-browser@4.2.5
+-- @angular/platform-browser-dynamic@4.2.5
+-- @angular/router@4.2.5
+-- @progress/kendo-angular-buttons@1.1.1
+-- @progress/kendo-angular-dateinputs@1.4.0
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @types/jasmine@2.5.38
+-- @types/node@6.0.91
+-- bootstrap@3.3.7 extraneous
+-- codelyzer@2.0.1
+-- core-js@2.5.1
+-- jasmine-core@2.5.2
+-- jasmine-spec-reporter@3.2.0
+-- jquery@3.2.1
+-- karma@1.4.1
+-- karma-chrome-launcher@2.0.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@0.2.3
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.5.2
+-- ts-node@2.0.0
+-- tslint@4.5.1
+-- typescript@2.2.2
`-- zone.js@0.8.18
```

Browser:

- Chrome (desktop) version 61
- Firefox version 56

System:
- TypeScript version: 1.0.3.0
- Node version: 6.11.0
- Platform:  Windows

**Comment by ggkrustev** [comment]
Thanks for the report. Indeed, the component doesn't reflect the form model update. I prepared a simple plunker demo that replicates the issue:

http://plnkr.co/edit/kAE41VNdAN7XQerhhO1v?p=preview

**Comment by ggkrustev** [comment]
Hi @eatinasandwich,

We've pushed a fix in our @dev channel. Could you install `@progress/kendo-angular-dateinputs@dev` and let me know whether the issue still persists? The latest dev version is `1.4.1-dev.201711151210`.

**Comment by JaapMosselman** [comment]
I have installed the latest dev and I can confirm it is fixed.

**Comment by ggkrustev** [comment]
Version `1.4.1` is out. Please update `@progress/kendo-angular-dateinputs` package to get this issue resolved.

Will close the thread as resolved. Please comment if I'm missing something.
