### ISSUE TITLE
[Datepicker] format yyyy-MM-dd with null value not typing the year correctly

### ISSUE THREAD

**Issue by Badbarbie** [telerik/kendo-angular#1080]
* Bug report 

The datepicker with format yyyy-MM-dd having a value at null, try to enter with the keyboard 2017, it will enter 1017. The result is suppose to be 2017 ! :) I use the latest package versions.

Plunker :
http://plnkr.co/edit/laxekZWrZGeOG2v55q8v?p=preview

The code:
@Component({
    selector: 'my-app',
    template: `
      <div class="example-wrapper" style="min-height: 400px;">
          <div class="col-xs-12 col-sm-6 example-col">
              <p>Select a long date:</p>
              <kendo-datepicker
                  [format]="'dd-MMM-yyyy HH:mm:ss'"
                  [value]="value"
              ></kendo-datepicker>
          </div>

          <div class="col-xs-12 col-sm-6 example-col">
              <p>Select a short date:</p>
              <kendo-datepicker
                  [format]="'yyyy-MM-dd'"
                  [value]="value"
              ></kendo-datepicker>
          </div>
      </div>
    `
})
class AppComponent {
    //public value: Date = new Date(2000, 2, 10, 13, 30, 0);
}

Browser:

- Chrome (desktop) version 62.0.3202.94 
- IE11

System:
- Platform:  Windows

**Comment by tsvetomir** [comment]
Appears to be fixed in the latest [develop version](https://www.telerik.com/kendo-angular-ui-develop/components/dateinputs/) ([see plunkr](http://plnkr.co/edit/MVM7N8jPqttJulhBGQin?p=preview)).

**Comment by Badbarbie** [comment]
Thanks I downloaded it and it work perfectly! :)
