### ISSUE TITLE
kendo- combobox accessibility issue with expanded list using NVDA on firefox

### ISSUE THREAD

**Issue by kietresolve** [telerik/kendo-angular#1081]
When navigate using keyboard and expand the combo box using alt+down arrow and then hit the down arrow key to move onto the next selection in the list... for some reason NVDA screen reader always announce the first option on the list along with what is selected. 

Bug:
So it would say "select option2 list option1", "select option 3 list option1", "select option4 list option1"

Expected behavior:

Would just announce the selection option that highlighted on screen without saying the first option on the list...

Cheers,

Kiet Tran

**Comment by tapopov** [comment]
Related to https://github.com/telerik/kendo-angular/issues/1070

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.0-dev.201901311605**.

**Comment by dimitar-pechev** [comment]
Shipped in **v3.5.0**.
