### ISSUE TITLE
Calendar doesn't display months correctly if date range is set.

### ISSUE THREAD

**Issue by unumtresocto** [telerik/kendo-angular#1083]
## I'm submitting a ..

* Bug report 

## Current behavior
If the calendar has a date range with min-date's month different from january and max-date's month different from december, not all months are being rendered on yearView.

## Expected behavior
All months which fit in the selected date range are rendered on calendar.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/X0yLyOpnHt8hr1MHZmZS?p=preview
Steps to reproduce:
Click `month` button on calendar to switch calendar on Year View.
Observe that not all months are displayed.

## Notes:
The issue seems to be in YearView service of DateInputs' module. There is method called something like 'isInRange' which checks if provided date fits in the given date range. Current implementation is incorrect.

**Comment by ipeshev** [comment]
@unumtresocto we can confirm the issue.
Thank you for the bug report !

**Comment by ggkrustev** [comment]
Indeed, this is a known issue with `1.3.1` version of the DatePicker. I am glad to inform you that the latest official release `1.4.0` has this issue fixed. Check the updated plunker demo:

http://plnkr.co/edit/Vs7nl9UIPPD85EwWyznC?p=preview

I will close the issue as duplicate to the internal one logged on the same subject. Please feel free to comment I am missing something.
