### ISSUE TITLE
Need ability to define textValue on kendo-autocomplete

### ISSUE THREAD

**Issue by mcblum** [telerik/kendo-angular#1084]
## Current behavior
In the kendo-autocomplete it does not take a `textField` and `valueField` like the kendo-dropdown list. As a result, we're limited to processing on the display text when the `valueChange` event fires. The problem with that is we may have duplicate display text and it feels like we should be able to access the value of our complex object in the event:

```
[
    {
        text: 'SimpleLabel', // used for display
       value: '123-123-123' // would like this from the event
   }
]
```

## Expected behavior
Ideally, we'd be able to access the value rather than the display text or at least you'd be able to define which you'd like.

## Minimal reproduction of the problem with instructions
Since this is the default behavior, basically any version will work to see what I mean.

## What is the motivation or use case for changing the behavior?
We have a series of items that need to be pushed to the autocomplete where we need the hash or ID but obviously don't want to display that for the user.

## Environment
Browser:

- Chrome (desktop) version 64

System:
- TypeScript version: 4.2
- Node version: 8
- Platform: Mac

**Comment by tsvetomir** [comment]
The core premise of the AutoComplete is that its a text input with suggestions. The user is not required to pick any of the suggestions. So it's not a bug, it's a feature.

The ComboBox addresses the scenario where the user input is restricted to a set of predefined values.

**Comment by mcblum** [comment]
@tsvetomir is there a Kendo equivalent to the Material component that allows the user to type but underneath actually forces them to make a selection and not enter random text?

**Comment by valchev** [comment]
@mcblum by default the combobox component does not allow the user to enter custom (random) text. See [this topic](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/) for more information.
