### ISSUE TITLE
Unnecessary change detection triggered when there is a Grid on the page

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1086]
Angular change detection is triggered, and functions, bound to Grid properties (i.e. rowClass) are executed unexpectedly in the following scenarios that do not really require such behavior:

1) Clicking on the Grid cells

2) Clicking on the Grid header triggers it twice

3) Resizing the Grid via resizing the viewport

4) Blurring the page - click somewhere on the page and then either in an opened console window, or in another browser tab

[http://plnkr.co/edit/xogM45C9dds3S7qma0B2?p=preview](http://plnkr.co/edit/xogM45C9dds3S7qma0B2?p=preview)

**Comment by ipeshev** [comment]
Shipped with v1.6.2
