### ISSUE TITLE
[Expected/desired behavior] Grid Column Reordering (Angular4 & 5)

### ISSUE THREAD

**Issue by 00SHUAI00** [telerik/kendo-angular#1087]
## Expected behavior
Angular version.
Expected: **grid column reordering**.

Can I know which version can include grid column reordering feature? In what month?

**Comment by rusev** [comment]
Grid [1.7.1](https://www.telerik.com/kendo-angular-ui/components/grid/changelog/#release-9215395) introduces the [column reordering](https://www.telerik.com/kendo-angular-ui/components/grid/columns/reordering/) feature.
