### ISSUE TITLE
[Grid] - When using the FilterMenu, the filter menu stays the same whether it is active or not

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#1091]
Plunker: [http://plnkr.co/edit/6XAK6hZGYiYctb1fLMjs?p=preview](http://plnkr.co/edit/6XAK6hZGYiYctb1fLMjs?p=preview)

When using the FilterMenu for filtering grid, if any of the filters are active, there is no indication of that. The active and inactive filters look the same. 

Just the sorting, there should also be some type of indication that the filter is active.

![grid](https://user-images.githubusercontent.com/12758783/32928969-0974134c-cb7d-11e7-99a6-a7b90fc6ae3a.png)

**Comment by yordanov** [comment]
Selected state should be applied to the active filter button.

References:
https://github.com/telerik/kendo-ux/blob/master/themes/default/buttons.psd
https://github.com/telerik/kendo-ux/blob/master/themes/default/grid.psd

**Comment by rkonstantinov** [comment]
This issue has been addressed and the fix is currently available in the `kendo-angular-grid` package [@dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). Also it can be previewed in [the develop version of our site](https://www.telerik.com/kendo-angular-ui-develop/components/grid/data-operations/filtering/).

**Comment by sboyd** [comment]
Hi @rkonstantinov. I hope you are well.
Any idea when this enhancement will be released?

**Comment by rkonstantinov** [comment]
Hey @sboyd,
The change in question is available with version 1.6.2 of the `kendo-angular-grid package`.

**Comment by sboyd** [comment]
FAAAAANTASTIC! Thank you. Aside from asking you is there some way to monitory when a new package is 

What's the base kendo package is available as well as a list of changes?

**Comment by rkonstantinov** [comment]
For latest changes you could keep an eye on [the change log page](https://www.telerik.com/kendo-angular-ui-develop/components/grid/changelog/) for each component.

**Comment by sboyd** [comment]
Excellent! Thank you sir. Have a great day.
--Steve
