### ISSUE TITLE
Sortable on mobile devices throws an warning

### ISSUE THREAD

**Issue by mak633** [telerik/kendo-angular#1092]
Hello.
I have a problem with sortable component on mobile device. This is my code: 
```html
<kendo-sortable 
        [data]="items" 
        [navigatable]="true"
        [animation] = "true"
        class="dfs-reoder"
        [activeItemStyle] = "{'box-shadow': '2px 2px 3px 0px rgba(0,0,0,0.5)'}">
        <ng-template let-item="item" class="list-group">
          <div class="list-group-item d-flex">
            <span class="k-icon k-i-menu d-flex"></span>
            <span class="reorder-title mx-4"><h4>{{item.title}}</h4></span>
            <span class="reorder-description">{{item.description}}</span>
          </div>
        </ng-template>
</kendo-sortable>

```
When I try to sort my items on mobile I get warning and I scroll my screen.
> Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted. sortable.component.js:591

Can you please fix it.

**Comment by smickus** [comment]
Having the same issue here.

**Comment by tapopov** [comment]
We're currently overhauling the Sortable component, so we will keep in mind of this scenario while working on the 2.0 version.

**Comment by ipeshev** [comment]
The warning possible is not related with scroll when try to sort.
Though we still have some issues inside scrollable container on mobile device will link another issues that are addressing those.
