### ISSUE TITLE
Calendar or DatePicker layouts days incorrect when range is smaller than a week

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#1099]
## I'm submitting a...
* Bug report 

## Current behavior
When date range is smaller than 1 week and does not start on the first day of that week, the days are placed incorrectly
![image](https://user-images.githubusercontent.com/22192317/33061545-cac989b0-ce9c-11e7-9eb8-2903eaae47bc.png)

## Expected behavior
Correctly aligned

## Minimal reproduction of the problem with instructions
Take standard Calendar date range demo and make the min date some days before max date.
[http://plnkr.co/edit/gUUoktF2JgWLfmQ3LGq2?p=preview](url)

## What is the motivation or use case for changing the behavior?
Better layout

## Environment
Browser:
- Chrome (desktop) latest
- Edge latest

**Comment by ipeshev** [comment]
Shipped with v2.45.3
