### ISSUE TITLE
Popup's vertical position is calculated before its height

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#1101]
## I'm submitting a...
* Bug report 

## Current behavior
Changing the content of the Popup does not result in re-adjustment of its vertical position until the next rendering cycle. 

## Expected behavior
The position should be recalculated as soon as the content's height has changed.

## Minimal reproduction of the problem with instructions
1. Open [example](http://plnkr.co/edit/8Yo8dEgyyaImGD7dOgs2?p=preview) and find the ComboBox at the bottom
2. Type "edi" 
3. Observe how the Popup is resized and re-positioned after each keystroke

**Comment by danielkaradachki** [comment]
Seems to be caused by this issue:

https://github.com/angular/angular/issues/19094

**Comment by ipeshev** [comment]
Shipped with: v1.3.1
