### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart'/'touchmove' event.

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1102]
When using Grid or Sortable component, the following warnings appear in the browser's console when displaying Verbose level:

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Please check the following video demonstrating how to observe the reported behavior:

[https://www.screencast.com/t/xkZUh861T2V](https://www.screencast.com/t/xkZUh861T2V)

**Comment by tsvetomir** [comment]
We can't mark the events as passive, as we need to prevent the default (scroll) action.

Will fix the warning by explicitly marking the events as active.

**Comment by tsvetomir** [comment]
Turns out there's no way to disable the warning through code. The only option at the moment is to disable the Verbose logging level:
![image](https://user-images.githubusercontent.com/247917/33164207-7dee28f4-d03a-11e7-9af0-20ed7148d84d.png)

**Comment by tsvetomir** [comment]
This is fixed in the latest [Develop version](https://www.telerik.com/kendo-angular-ui-develop/components/grid/) of the Grid. We now use Pointer Events that don't have effect on scrolling performance.

**Comment by tsvetomir** [comment]
Note that the fix also applies to the [ScrollView develop version](https://www.telerik.com/kendo-angular-ui-develop/components/scrollview/).

The Sortable still produces the same warnings.

**Comment by tsvetomir** [comment]
We don't have plans to migrate the Sortable to Pointer Events at the moment. The warning can be ignored as the Sortable prevents scrolling - there's no performance benefit to be gained.

The issue remains "Won't Fix" in regards to the Sortable and is fixed for the Grid and ScrollView.
