### ISSUE TITLE
Grid contains filter on numeric fields.

### ISSUE THREAD

**Issue by Influencer** [telerik/kendo-angular#1103]
I understand how the filter works and of course it only works for strings.

Currently the function is as follows:
`function (a, b) { return (a || "").indexOf(b) >= 0; },`

I am attempting to add an external 'search' function to my grids that compares all of the columns with the search query. I am doing this by adding this filter:
```
logic:"or",
            filters: [
                { field:"column1", operator:"contains", value: queryString },
                { field: "column2", operator: "contains", value: queryString },
                { field: "column3", operator: "contains", value: queryString },
                { field: "column4", operator: "contains", value: queryString },
                { field: "column5", operator: "contains", value: queryString }
            ]
```

This works fine if every column is of string type. Suppose column 5 is of numeric type, we get an error that (a || "").indexOf(b) is not a function, because numeric types do not have the indexOf method (I have seem the disclaimer that the descriptors such as contains only work for strings).

I do not know of the possible repercussions of the suggestion within your project, but would it be possible to instead  do:
`function (a, b) { return (a.toString() || "").indexOf(b) >= 0; },`
so that numeric types can be included in a contains search?

I have tested this locally modifying the filter-no-eval.js and it works as expected. Thoughts?

**Comment by rkonstantinov** [comment]
Hi @Influencer, thanks for your suggestion. 
Unfortunately, such change will have performance impact with questionable value for the customers.

You could consider using custom [operator function](https://www.telerik.com/kendo-angular-ui/components/dataquery/api/FilterDescriptor/#toc-operator) which to handle all of the required value types. Something similar to the following:
```js
{ field: "column1", operator: (value) => (value + "").indexOf(queryString) >= 0  }
```

**Comment by Influencer** [comment]
That works, I was unaware you could pass a function in as the operator. Thanks for the information!
