### ISSUE TITLE
DatePicker min validation behaves inconsistently for a manually entered and selected value

### ISSUE THREAD

**Issue by alexeykostevich** [telerik/kendo-angular#1106]
## I'm submitting a...

* Bug report 

## Current behavior

The [min](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DatePickerComponent/#toc-min) validation behaves differently for a manually entered and selected value if `[min]` represents a date with a time part.

## Expected behavior
Validation works consistently regardless of an input type.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/UZAoBiz0ussCUZVCeaSf?p=preview

Steps to reproduce:
1. Open the demo
2. Pick a today date
3. Enter a today date

Validation works differently for steps 2 and 3.

## What is the motivation or use case for changing the behavior?

It is a common scenario when the selected date should be in the future. Specifying `[min]` with `new Date()` (now) can be handy in this case.

From the other hand, since a time part in a DatePicker can be confusing, the most important is to have a consistent behavior regardless of an input type.

## Environment

Package versions:

```
+-- @angular/animations@5.0.2
+-- @angular/common@5.0.2
+-- @angular/compiler@5.0.2
+-- @angular/core@5.0.2
+-- @angular/forms@5.0.2
+-- @angular/platform-browser-dynamic@5.0.2
+-- @angular/router@5.0.2
+-- @progress/kendo-angular-dateinputs@1.4.1
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-theme-default@2.45.1
```

Browser:

- Chrome (desktop) version 62
- Firefox version 57

System:
- TypeScript version: 2.4.2
- Node version: 6.10.3 (npm 4.6.1)
- Platform:  Windows

**Comment by gkarapeev** [comment]
Related: https://github.com/telerik/kendo-angular-dateinputs/pull/169
