### ISSUE TITLE
node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

### ISSUE THREAD

**Issue by CodeguruEdison** [telerik/kendo-angular#1107]
## I'm submitting a...

* Bug report

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by gyoshev** [comment]
Given that the template wasn't filled out with any details, and that the packages are already compatible with Angular 5, I'm closing this issue. If there are any details that can be used to reproduce the error, feel free to add them.

**Comment by tsvetomir** [comment]
Please make sure that you've removed any references to the now defunct Progress NPM Registry, see #712
