### ISSUE TITLE
Сhange of value in a slider selects the surrounding text (Firefox)

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#1112]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When we change value in slider by dragging draghandle the surrounding text becomes selected.

## Expected behavior
The surrounding text doesn't change the selected state

## Minimal reproduction of the problem with instructions

  1. [Open plunker](http://plnkr.co/edit/WxrQ1uCBYWzWZqLSqKY6?p=preview)
  3. Change value in slider by dragging draghandle
  5. The surrounding text ('Popup content.') becomes selected.

## Environment

Package versions:
- Kendo Inputs v1.3.3

Browser:

- Firefox version v57

**Comment by ipeshev** [comment]
Fixed in v1.4.1-dev.201712151445

**Comment by destus90** [comment]
@ipeshev when 1.4.1 will be published?
