### ISSUE TITLE
Sparkline stacked bar chart scaling issue

### ISSUE THREAD

**Issue by cubidobusinesssolutions** [telerik/kendo-angular#1113]
## I'm submitting a...

* Bug report 

## Current behavior

sparklines of type stack bar have several scaling issues, i.e. 

- when only two values provided, it gets completely wrong
- width differs depending on the size of data even if specified width exactly

## Expected behavior

- all data should be displayed correctly

## Minimal reproduction of the problem with instructions

see [Plunker](http://plnkr.co/edit/4mKReSFl3zASe184v9ao?p=preview)

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop)
- IE version 11
- Edge

System:
- Platform:  Windows

**Comment by danielkaradachki** [comment]
The automatic axis range depends on the values. The reason for the difference can be seen if the value axis is made visible. To make them all the same, use [100% stacked](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesStack/#toc-type) series and force the range to start from zero with the [narrowRange](https://www.telerik.com/kendo-angular-ui/components/charts/api/ValueAxis/#toc-narrowrange) option:

http://plnkr.co/edit/6MAUXBAXRLX8uRJ1PAoS?p=preview

**Comment by cubidobusinesssolutions** [comment]
@danielkaradachki thanks!
