### ISSUE TITLE
I have some issue regarding the kendo UI Grid Pagination Customization part will you can help me with same.?

### ISSUE THREAD

**Issue by nick412** [telerik/kendo-angular#1114]
I have some issue regarding the kendo UI Grid Pagination Customization part will you can help me with same.?

I want some customization over pagination part where I'm using kendoUI angular 2+ version.

**what is actual behavior** 
Default kendo UI behavior is like we need to render all the grid data once to activate pagination functionality if pageSize <= actual records then and then the only pagination will active but if we got pageSize > actual records the pagination won't work.

**what is expected behavior** 
I need to set pageSize = 50 and API return me 50 records with total records field so, for now, we can assume that API return total 50 records and it has fields to indicate total records which let's say 200 so pagination will set accordingly [ 200 (total) / 50 (pageSize) = 4 page ] and pagination will active also with the pageSize <= actual logic and we can call separate API call for next 50 records after we click on next button which is been created on total records.

Thanks,
Nicks.

**Comment by rkonstantinov** [comment]
@nick412,
If I understood your description correct the expected behavior is how the pager currently function. This is demonstrated in [this example](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/paging/#toc-paging). 
Basically, the Grid component expects a page of data - an array which holds only the items for the current page  and a total - which is the total number of records in a form of [GridDataResult](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridDataResult/). The [pageChange event ](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-pagechange)should be handled in order to provide the next pages.

**Comment by nick412** [comment]
Hello @rkonstantinov,

Thanks for the reply so would like to ask can you provide me an example or link to achieve my expected behavior is it possible with Kendo UI grid ..?

what is expected behavior
I need to set pageSize = 50 and API return me 50 records with total records field so, for now, we can assume that API return total 50 records and it has fields to indicate total records which let's say 200 so pagination will set accordingly [ 200 (total) / 50 (pageSize) = 4 page ] and pagination will active also with the pageSize <= actual logic and we can call separate API call for next 50 records after we click on next button which is been created on total records.

**Comment by rkonstantinov** [comment]
Did you mange to take a look at the example I have linked in my previous message? How it is different than the one you have described?

**Comment by nick412** [comment]
Hello @rkonstantinov ,

Thanks a lot your example helps me a lot now I can use pagination synchronized way nut I found some issue with search when I click on next page and then try to use search record it will not make any impact on pagination please check the image which I attached below.

![prob](https://user-images.githubusercontent.com/32121809/33476565-681da4f4-d6a8-11e7-8983-b7c79aa0a2dc.PNG)

the pagination is not getting reset after any external event trigger. please check the image once.

**Comment by rkonstantinov** [comment]
@nick412 
As the Grid component does not persist the paging state, the developer is responsible for managing it. Thus, in case of external filtering, you will need to reset it explicitly, by setting the field bound to the Grid's `skip` input field to `0`.

**Comment by nick412** [comment]
Hello @rkonstantinov ,

as we discussed the pagination issue it was fixed as per your guidance but after it applied to my grid I faced another issue that my grid is not shorting anymore.

I am using " (sortChange)="sortChange($event) " at HTML side and 

`sortChange(sort: SortDescriptor[]) {
    if (sort[0].field === 'UID') {
      this.sortExternal = !this.sortExternal;
      this.sort = [{ field: 'SourceUid', dir: this.sortExternal ? 'asc' : 'desc' }];
      this.gridData = orderBy(this.gridData, this.sort);
    }
  }`

is using the component side where if I got 'UID' at that moment I need to prevent it from shorting.
please help me with the solution,

**Comment by rkonstantinov** [comment]
Hey @nick412,
could you please modify the sample I have referenced in order to demonstrate the issue you are currently facing.
