### ISSUE TITLE
Combobox empty textfield string

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#1115]
Hey,

if i select an item in the combobox, where the textfield is an emptystring, the combobox sets the value, but shows the placeholder and hides the button to clear the value ('x').

Plunkr:
http://plnkr.co/edit/Pe0sAvvLZqGWCcCJvouh?p=preview

Is there a way, to set the textfield even if it's an empty string and display the clear button if a value is set.

Thanks, Simon

**Comment by tapopov** [comment]
Hey @simon11196 
This behavior is expected, since the ComboBox shows the clear button and placeholder based on whether there is text or not. While changes in that regard are unlikely, you might override the component's `text` property manually. [Here](http://plnkr.co/edit/aoM5xu93tjbD24lryp6V) is an example.

**Comment by simon11196** [comment]
Hey @tapopov,
if i select the value with the empty textstring and click outside the combobox, the value will reset...
Is that another bug of the combobox?

**Comment by tapopov** [comment]
The ComboBox relies on having a text. You can either iterate the data set and assign some text where it is missing or use a DropDownList instead.

**Comment by simon11196** [comment]
1. Select the value with the empty textfield
2. Click outside the combobox

![comboboxemptystringtextfield](https://user-images.githubusercontent.com/21359517/33362923-89e5eb8a-d4de-11e7-91f7-d59c81155568.gif)

The combobox text will reset on click outside the box...

**Comment by tapopov** [comment]
The ComboBox requires data items of type object to have their text field populated. As mentioned above you can assign it where it's missing. [Here](http://plnkr.co/edit/JMkjmlZZ5p6ocF97w416?p=info) is an example, where the empty string is replaced with a blank space.
