### ISSUE TITLE
kendo-datepicker does not display the value when using ngModel until it gets focus

### ISSUE THREAD

**Issue by yanbu0** [telerik/kendo-angular#1116]
## I'm submitting a...

* Bug report 

## Current behavior

When a date picker is bound using ngModel it does not display the date until it is clicked on (receives focus).  Seems to work as expected when using [(value)], however.  I am using examples from your own sandbox below to eliminate the possibility of it being something on my end, but see the same issue in my project across multiple browsers and multiple computers.  It is possibly caused by the kendo CSS perhaps since I have tested in 1.4.1 and rolling back to both 1.4.0 and 1.3.1 and it still happens.  Will update this after I roll back my kendo bootstrap theme to an earlier version.  Angular is version 4.4.6.  

The below is from the Kendo Angular docs page.  Note that the date picker is not displaying the date. 
![image](https://user-images.githubusercontent.com/26099646/33353153-d8031332-d458-11e7-9ed1-253e696ed1bc.png)

The below is what is displayed after I click on the datepicker.  I do not have to click the calendar icon, just anywhere on the datepicker to give it focus.  It now displays the value expected.
![image](https://user-images.githubusercontent.com/26099646/33353204-147fe9de-d459-11e7-8160-cc39381d9d1a.png)

## Expected behavior

Date is displayed.  It is neccessary to use ngModel for forms validation, so simply using [(value)] as a workaround isn't possible.

## Minimal reproduction of the problem with instructions

Go to [https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/](https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/)
 and click on "Run Code" on any of the examples provided which use [(ngModel)] to bind the control value.

## What is the motivation or use case for changing the behavior?

This is clearly a bug.

## Environment

Package versions:

```
+-- @progress/kendo-angular-buttons@1.0.5
+-- @progress/kendo-angular-dateinputs@1.3.1
+-- @progress/kendo-angular-dropdowns@1.2.4
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@1.6.2
+-- @progress/kendo-angular-inputs@1.3.3
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-layout@1.0.10
+-- @progress/kendo-angular-upload@1.2.2
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-drawing@1.4.0
+-- @progress/kendo-theme-bootstrap@2.9.0
+-- @progress/kendo-theme-default@2.45.2
+-- @progress/telerik-angular-report-viewer@1.17.822

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ggkrustev** [comment]
Hi @yanbu0, thanks for the report.
I can confirm that the described issue is related to the one reported here:

https://github.com/telerik/kendo-angular/issues/1079

*It is already fixed in `1.4.1`*. Here is a plunkr demo that actually uses it (the site still don't use it):

https://plnkr.co/edit/seJ4jLg9WziemQtCVuxk?p=preview

![screen shot 2017-11-29 at 10 40 44 am](https://user-images.githubusercontent.com/495188/33365714-c540fe1e-d4f1-11e7-9557-27cb52f3f443.png)

As you can see the value is displayed without a need to focus the input.

I will close the issue as duplicate. If I am missing something, please modify the demo in my post.
