### ISSUE TITLE
Links at export as Excel

### ISSUE THREAD

**Issue by mak633** [telerik/kendo-angular#1119]
Hello. 
Is there some example how I can add hypelinks when I do export as Excel?
Now I have just string in the excel file at the links place.
Can you help me with it.

**Comment by danielkaradachki** [comment]
This is not currently supported. I would suggest to submit a feature request in our [user voice](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/) forum.
