### ISSUE TITLE
Dialog - provide service for creating dialogs

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#112]
Currently the dialog cannot be opened without placing the dialog in the component template. For some scenarios like confirm dialogs, providing a service that creates the dialog is more convenient.

Something in the terms of:

    // kendoDialog: DialogService

    const dialog = kendoDialog.confirm()
          .title("Are you sure")
          .content("This operation cannot be undone. You may lose progress.")
          .ok("I understand what I'm doing")
          .cancel("Get me out of here!");

    kendoDialog.show(dialog).then(function() {
      // dialog OK, proceed
    }, function() {
      // dialog cancel, hide
    });

[Requested on StackOverflow](http://stackoverflow.com/questions/40921365/possible-to-use-kendo-ui-ng2-modal-like-the-old-ui-bootrap-modal-from-ng1/40927649#40927649).

**Comment by squadwuschel** [comment]
I like the idea of implementation from the ui-bootstrap ng2 team for this toppic

https://ng-bootstrap.github.io/#/components/modal

**Comment by gyoshev** [comment]
This feature is now available in `@progress/kendo-angular-dialog` -- see the [Dialog Service help topic](http://www.telerik.com/kendo-angular-ui/components/dialog/service/) for information on how to use it.

**Comment by bipin244** [comment]
Can i add html like 
const dialog: DialogRef = this.dialogService.open({
          title: "Please confirm",
          content: "<b>Are you sure></b>",
          actions: [
              { text: "No" },
              { text: "Yes", primary: true }
          ]
      });

**Comment by gyoshev** [comment]
@bipin244 the dialog service does not compile HTML template dynamically. You can use a template or a component, as [shown in the documentation](http://www.telerik.com/kendo-angular-ui/components/dialog/service/#toc-rendering-the-content).
