### ISSUE TITLE
"Open as Plunker" doesn't work at Kendo UI for Angular Example

### ISSUE THREAD

**Issue by hugoestevam** [telerik/kendo-angular#1120]
Hi,

The plunker examples from http://www.telerik.com/kendo-angular-ui/components/ doesn't work anymore. For example:

https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/globalization/

Console:

Failed to load https://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-intl/dist/cdn/js/kendo-angular-intl.js: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.

**Comment by tsvetomir** [comment]
Please, try clearing your browser cache to see if that helps.

**Comment by hugoestevam** [comment]
Hello @tsvetomir ,

Thanks for the reply. It works for me.
