### ISSUE TITLE
Grid with custom templates works very slow in IE

### ISSUE THREAD

**Issue by AkunaMatata** [telerik/kendo-angular#1122]
Hello,
I'm submitting an issue with grid performance in IE.
Grid with custom templates and several dozen of column work very slow in IE.
Letters in filter appear with big delay (unable to type anything smoothly),
Simple check row  with checkbox column takes about a second.
Sorting for just 50 items takes several second.
It seems like each action fires a change detection for whole grid.

## Minimal reproduction of the problem with instructions
There is a plunker
http://plnkr.co/edit/ItazegxZhDjd7bx7dwGT?p=preview

I've checked behavior. Change detection is called for each cell even in cases when there are no any changes.

Browser:
- IE version 11

System:
- TypeScript version: 2.2.2
- Node version: 6.11.0 npm  5.0.3
- Platform:   Windows

**Comment by tsvetomir** [comment]
Missed that issue - sorry. Recent versions of the Grid bring two important performance improvements:
* DOM elements are reused to reduce reflows
* The filter input changes are debounced

Please give it another go with the latest version to see how it behaves in your scenario.
