### ISSUE TITLE
Component is misaligned when opened in a zoomed window

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#1124]
## I'm submitting a...
* Bug report
## Current behavior
The Popup component is misaligned when opened in a zoomed window. It seems that the zoom should be more than 150% in order to see the erroneous behavior.

## Expected behavior
Position popup next to the anchor even when zoom is more than 150%.

## Minimal reproduction of the problem with instructions
1. Run http://plnkr.co/edit/el8XsnnCBzFpAVnKfsp7?p=preview
2. Open the DatePicker popup
3. Notice how the popup is shifted down.

## What is the motivation or use case for changing the behavior?
Enable proper work with popup elements when zoom is applied.

## Environment

Package versions:
```
├── @angular/animations@4.4.6
├── @angular/common@4.4.6
├── @angular/compiler@4.4.6
├── @angular/compiler-cli@4.4.6
├── @angular/core@4.4.6
├── @angular/platform-browser@4.4.6
├── @angular/platform-browser-dynamic@4.4.6
├── @angular/platform-server@4.4.6
├── @krux/condition-jenkins@1.0.1
├── @progress/kendo-angular-tasks@9.1.33
├── @progress/kendo-theme-default@2.45.2
├── @progress/kendo-angular-dateinputs@1.4.1
├── @progress/kendo-angular-popup@1.3.0
├── @progress/kendo-popup-common@1.2.3
├── @telerik/semantic-prerelease@1.2.1
├── @types/core-js@0.9.35
├── @types/jasmine@2.2.34
├── @types/zone.js@0.0.27
├── codelyzer@3.2.2
├── core-js@2.5.1
├── cz-conventional-changelog@1.2.0
├── ghooks@1.3.2
├── gulp@3.9.1
├── rxjs@5.5.2
├── semantic-release@6.3.6
├── tslib@1.8.0
├── tslint@5.8.0
├── typescript@2.3.4
├── validate-commit-msg@1.3.0
└── zone.js@0.8.12
```

Browser:
All

System:
- TypeScript version: All
- Node version: All
- Platform:  All

Reported in TicketID: 1142748

**Comment by tsvetomir** [comment]
Seems to be fixed in the current version.
