### ISSUE TITLE
Date picker doesn't show initial value when using [(ngModel)]

### ISSUE THREAD

**Issue by kdubious** [telerik/kendo-angular#1125]
## I'm submitting a...
* Bug report

## Current behavior
On the Kendo site, any Date Picker example that uses [(ngModel)] suffers from this. You do not see the default (initial) value in the date picker. It shows the placeholder, even though the value is set. Once the date picker gets focus, it shows the actual value.

## Expected behavior
I expect the initial value to be shown without having to select the date picker.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/
Any demo with [(ngModel)] will fail. Like: Template-Driven Forms & Date Ranges samples.

## What is the motivation or use case for changing the behavior?
Well, people like to see the value in the control before they select it. They assume there's no value set.

## Environment

Package versions:
On demo site, and my setup.

**Comment by ggkrustev** [comment]
Thank you for submitting the issue. This is a known bug, which is already resolved in `v1.4.1`. More details can be found in the original issue - https://github.com/telerik/kendo-angular/issues/1079

Closing the thread a duplicate.
