### ISSUE TITLE
Wrong position of calendar in datepicker (popup)

### ISSUE THREAD

**Issue by iwnow** [telerik/kendo-angular#1128]
Chrome 62.0.3202.94

http://plnkr.co/edit/HPVPCV7RdwEPIXhfAt4t?p=info

the problem is tag td with no static position in style, in file:

...kendo-popup-common/dist/es/offset-parent.js

```javascript
var offsetParent = function (element) {
    var offsetParent = element.offsetParent;

    while (offsetParent && offsetParent.style.position === "static") {
        offsetParent = offsetParent.offsetParent;
    }

    return offsetParent || documentElement(element);
};
```

**Comment by ggkrustev** [comment]
Thanks for the bug report. We will look into it.

**Comment by ggkrustev** [comment]
The issue seems to be fixed in the latest DateInputs/Popup packages.
- http://plnkr.co/edit/F51CEMQvUoZ8kNXKkizq?p=preview

Will close the thread as resolved.
