### ISSUE TITLE
Date not select when its pass as string

### ISSUE THREAD

**Issue by kanji-keraliya** [telerik/kendo-angular#1130]
Error while bind date using model and model have string but date object.

ERROR Error: Uncaught (in promise): TypeError: date.getTime is not a function
TypeError: date.getTime is not a function
    at cloneDate (clone-date.js:24)

**Comment by tsvetomir** [comment]
Property bindings of type "Date" will not be converted automatically from and to strings. Such parsing would have to assume the date format, leading to hard to debug errors. For example "1/2/2001" can be assumed both to be Feb 1 and Jan 2.

We recommend parsing the date in advance, for example by using [parseDate](https://www.telerik.com/kendo-angular-ui/components/internationalization/api/IntlService/#toc-parsedate) from the [IntlService](https://www.telerik.com/kendo-angular-ui/components/internationalization/services/).

**Comment by ggkrustev** [comment]
Just to chime in, @kanji-keraliya check our `Integration with JSON` demo that demonstrates how to consume date strings:

https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/#toc-integration-with-json

**Comment by kanji-keraliya** [comment]
but when pass universal date format then its will be convert automatically.
Ex : "2017-12-11T18:30:00Z" This comes from rest api and can not convert but new use new Date('2017-12-11T18:30:00Z') it will convert right one.

**Comment by ggkrustev** [comment]
Yes, the `new Date('string value')` will use internally `Date.parse` to convert the string into Date milliseconds and then to create Date object. Similarly, this is achieved with `IntlService parseDate`, which has greater capabilities than `Date.parse`. This is clearly demonstrates in the aforementioned documentation.

https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/#toc-integration-with-json

Please note that component doesn't support passing date strings to its properties. They should be converted into Date instances before feeding the component.

If we are missing something, then I will ask you to send us a simple repro demo that demonstrates the issue you are referring to.

**Comment by kanji-keraliya** [comment]
I understand what you are saying but its support in version 1.0.5 but not support in latest version.
So its create problem while updating to latest build.

**Comment by ggkrustev** [comment]
Probably I am missing something here, because `@progress/kendo-angular-dateinputs@1.4.1` works just fine with the aforementioned approach (working with JSON). I prepared a simple plunker demo that proves that:

http://plnkr.co/edit/9UqUOp9qWlBWwwMk2Ncq?p=preview

Could you elaborate a bit more on your issue? Could you send us a repro demo or just modify the one I've send?

**Comment by kanji-keraliya** [comment]
Please check  plinker for error http://plnkr.co/edit/gIy8HuEWIznp20r40Ynu?p=preview

Why need to parse date object if its a universal date format string.So my suggestion is you can check is date format is valid then parse it otherwise throw error. Why user need to parse universal date format every where in code instead of you can check one place

**Comment by ggkrustev** [comment]
@kanji-keraliya, the described behavior is intended and expected. The component can and should expect only Date object. 

To answer your question "Why need to parse date object if its a universal date format string", please consider the most common scenario when 2-way binding is used (`[(value)]` or `[(ngModel)]`). In this case, the component will accept a value and will return a new one based on user interaction. *It will be quite surprising and unexpected to receive value of type `String` and then return value of type `Date`.* That is why we request from the developer to parse the JSON into valid JavaScript object and work with the corresponding data types available in the language.

I hope the given details clarifies why the component works only with Date objects and will thrown an exception when different type is provided.

The solution is to parse the date strings before binding the form.

**Comment by clabough** [comment]
For anyone that's interested in voting for this, I've created a UserVoice request at http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/33352846-enable-date-time-components-to-convert-string-type

**Comment by stedice** [comment]
Wouldn't be enough to remove the getTime() from the following
`const cloneDate = (date) => date ? new Date(date.getTime()) : null;`
to avoid throwing an error in the constructor of Date. 

This will also make possible to pass numbers (milliseconds), strings and Date objects as well, to the component without throwing an error.
