### ISSUE TITLE
ScrollTop position changes when using MultiSelect in a locked column

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1131]
When using a MultiSelect in a locked column within a Grid, the vertical scrollbar moves incorrectly when selecting a value from the MultiSelect.

Please check the following sample plunker demonstrating the issue:

[http://plnkr.co/edit/Yasxvc7TO4Ou2HmqC3hS?p=preview](http://plnkr.co/edit/Yasxvc7TO4Ou2HmqC3hS?p=preview)

A possible workaround is on valueChange event of the MultiSelect to get the current scrollTop position of the scrollbar and then set it manually as shown in the following sample plunker:

[http://plnkr.co/edit/f4XCMAmPUZcBAdO7pl8B?p=preview](http://plnkr.co/edit/f4XCMAmPUZcBAdO7pl8B?p=preview)

**Comment by ipeshev** [comment]
Shipped with v1.6.4
