### ISSUE TITLE
Bound value is lost in DropDownList with filtering

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1132]
When the DropDownList is filtered such that the list no longer contains the current value, the value is lost:

[https://www.screencast.com/t/o8gzbPzUSaMj](https://www.screencast.com/t/o8gzbPzUSaMj)

[https://www.screencast.com/t/o8gzbPzUSaMj](https://www.screencast.com/t/o8gzbPzUSaMj)

Issue is not observable in v. 1.2.2 of the DropDowns package.

**Comment by ipeshev** [comment]
Shipped with 1.4.0
