### ISSUE TITLE
Hitting SpaceBar on upload control scrolls the web form to the end of the page

### ISSUE THREAD

**Issue by ranag14** [telerik/kendo-angular#1133]
Hi,

When user hits spacebar on upload control to open the upload dialogue, it scrolls the page to the end. Though it behaves correctly on Enter button. 

I noticed same behaviour on plunker. Is there any way to fix this issue?

**Comment by Raisolution** [comment]
Hi @ranag14,

We are handling the Enter and Space keys the same way. Could you send us small plunkr in order to reproduce the case and elaborate in which browser are you observing the behavior?

**Comment by ranag14** [comment]
I'm having this issue on Firefox 57.0.1.

You can try it on
 https://www.telerik.com/kendo-angular-ui/components/upload/

Just try to open upload window by hitting spacebar.

**Comment by Raisolution** [comment]
Thank you for the info. We reproduced the behavior on our end and will investigate further.

**Comment by ranag14** [comment]
Thanks!!

When can we expect it to be fixed as I've to release this feature soon.

**Comment by Raisolution** [comment]
Issue has been fixed in v2.1.1
