### ISSUE TITLE
[Dialog] Disable animation effect

### ISSUE THREAD

**Issue by shanelovesmarvel** [telerik/kendo-angular#1134]
Hi kendo team,

I have been using kendo dialog for several months,   when open dialog,  it has animation effect will show from up and then to center.

But when computer or machine our app deployed on has bad performance,  when open the dialog, it will get stuck a little bit, then several seconds later adjusts down to center.

I try to check API to disable animation but without success, because in other components like dropdown etc, there is an interface to specify the animation.

So I am wondering is there any plan to provide an interface to disable animation effect when opening dialog ? Or any workarounds to accomplish it ?

**Comment by gyoshev** [comment]
At this time, animations can be disabled for the whole application, through the use of `NoopAnimationsModule`. See [this StackOverflow thread](https://stackoverflow.com/q/43362898/25427) for more information.

We will consider adding a property to disable the animation of the dialog component specifically in a future version.

**Comment by Raisolution** [comment]
Currently this enhancement is not planned for a built in implementation.

If you consider it for a must have functionality, please log it as an item in [our Feedback portal](https://feedback.telerik.com/kendo-angular-ui). This way we could measure the demand for it and plan it accordingly. Thanks you in advance.
