### ISSUE TITLE
DropDownList call valueChange when lost focus

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1135]
## I'm submitting a...
* Bug report.  **I did.**

I was following [Reusable custom filter tutorial](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/reusable-filter/).

## Current behavior
When drop down list lost focus, valueChange is called, and filter is cleared.

## Expected behavior
valueChange is not called on blur.

## Minimal reproduction of the problem with instructions
Open official [plunkr](http://plnkr.co/edit/?p=preview).

## What is the motivation or use case for changing the behavior?
It is a bug. A nasty one.

## Environment

Browser:
- Chrome (desktop) version XX

System:

Additional information:
![2017-12-05_08-09-02](https://user-images.githubusercontent.com/1589573/33594585-c5a949fe-d994-11e7-852f-43d4d809ad50.gif)

**Comment by tapopov** [comment]
Thanks for reporting this. We will investigate immediately.

**Comment by tapopov** [comment]
@MaklaCof 
The issue you described seems to be related to https://github.com/telerik/kendo-angular/issues/1104, which is already fixed. You can check the same scenario on our [develop branch site](https://www.telerik.com/kendo-angular-ui-develop/components/grid/data-operations/filtering/reusable-filter/) or update and confirm.

**Comment by MaklaCof** [comment]
My apologise. It works with latest dev version.
