### ISSUE TITLE
Sortable: When an input element is used within a template, its content cannot be selected

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1136]
When an HTML input element is used in a template, the text it contains cannot be selected via mouse (dragging of the whole item is initiated instead).

**Comment by ipeshev** [comment]
Works [properly](https://stackblitz.com/edit/angular-mizblr-rvr7uj?file=app/app.component.ts) with[ latest dev versions](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of @telerik/kendo-draggable and @progress/kendo-angular-sortable.

**Comment by danielkaradachki** [comment]
Fixed in 2.1.0:

https://stackblitz.com/edit/angular-8tbdnr?file=app/app.component.ts
