### ISSUE TITLE
ComboBox receive valueChange on blur

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1137]
## I'm submitting a...
* Bug report

## Current behavior
Kendo combobox triggers valueChange on blur.

## Expected behavior
Does not receive valuChange on blur.

## Minimal reproduction of the problem with instructions
[Plunkr](http://plnkr.co/edit/Kc9MH74RLpRn20cXoGiw?p=preview). Just focus in and out.

## What is the motivation or use case for changing the behavior?
To fix a bug.

## Environment

Package versions:
```
"@progress/kendo-angular-dropdowns": "^1.3.0-dev.201711300918",
```

Browser:
- Chrome (desktop) version XX
- Firefox version XX

System:
- TypeScript version: 2.1.6
- Node version: 7.10.0
- Platform:  Windows

Seems similar to [this](https://github.com/telerik/kendo-angular/issues/1104) and [this](https://github.com/telerik/kendo-angular/issues/1135), but both are closed and it also does not work in development [plunkr](https://plnkr.co/edit/Zg3LpjHchA5jH0dgDJ6m?p=preview) so I think this one is new.

**Comment by tapopov** [comment]
@MaklaCof 
It seems that the example you shared uses a `numeric` property for a `textField`. This fails one of the conditions, thus the multiple `valueChange` events. I would recommend using a `string` property for a `textField`.
[Here](http://plnkr.co/edit/bE9EkTfB1S2bnI5qVX8r?p=info) is an example using the recommended configuration.

**Comment by MaklaCof** [comment]
Hi, this is great (work around) but I still see it as a bug. Numbers seems valid format for combo box. 
My users enter sizes in this combo boxes. There is also some standard sizes which can be used with drop down. I also receive numbers form server.
In this case I need to map all values to string. Unnecessary. Please reconsider to threat it as a bug and fix the issue.

**Comment by tapopov** [comment]
Basically the scenario half-worked only because the native input element converts its value property to a string automatically. Numbers are a great candidate for a ComboBox value, however not so much when it comes to its text. That's exactly why the component has both `textField` and `valueField` options. Just use the numbers for value and strings for text ([see example](http://plnkr.co/edit/bE9EkTfB1S2bnI5qVX8r?p=preview)).
