### ISSUE TITLE
Datepicker causes error if destroyed on blur

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#1138]
Example: http://plnkr.co/edit/voAJquUwdUhXS87NeMSs?p=preview

To reproduce - click the inside the input and then anywhere else on the page

**Comment by BaHXeLiSiHg** [comment]
still happening with `"@progress/kendo-angular-dateinputs": "1.4.3"` and Angular 5.2.1

**Comment by ipeshev** [comment]
Shipped with v2.1.0
