### ISSUE TITLE
Button border-radius

### ISSUE THREAD

**Issue by j-pdx** [telerik/kendo-angular#1142]
## I'm submitting a...
* Bug report

## Current behavior
Kendo splitbutton and dropdownbutton root elements don't have a border-radius set. Because of this, the buttons don't appear to have a radius on a dark background.

## Expected behavior
Button root element should have border-radius.

## Minimal reproduction of the problem with instructions
On the Kendo-Angular demo site, just change the example to have a dark background:

![screenshot 2017-12-05 12 44 09_preview](https://user-images.githubusercontent.com/1747494/33629789-2cfec708-d9ba-11e7-9c81-fffd662ebcdd.png)

If I set style="border-radius: 2px" on the element itself, it fixes the issue:

![screenshot 2017-12-05 12 46 23_preview](https://user-images.githubusercontent.com/1747494/33629842-537e473c-d9ba-11e7-9cef-60f258793d9e.png)

**Comment by tsvetomir** [comment]
Seems to be fixed in the current version.

![image](https://user-images.githubusercontent.com/247917/40542294-498d389c-6028-11e8-9b37-cae1909fb6a5.png)
