### ISSUE TITLE
disable kendo-timepicker 

### ISSUE THREAD

**Issue by kelumKP** [telerik/kendo-angular#1143]
How to allow only **picker** option, and disable **edit typing** option in kendo-timepicker 

I just tried following scenarios, but not working any of them

1. Approach 
`<kendo-timepicker readonly></kendo-timepicker>`

2. Approach 
`<kendo-timepicker readonly="true"></kendo-timepicker>`

3. Approach 
`<kendo-timepicker readonly="readonly"></kendo-timepicker>`

**Comment by ggkrustev** [comment]
@kelumKP, the [TimePicker component supports the `disabled` behavior right now](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/TimePickerComponent/), which will disable all available interactions. The desired functionality is not supported and I am afraid that there is no feasible way to achieve it.

The best I can suggest is to cast your vote for it in our UserVoice portal.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19197673-disable-user-input-on-datepicker

**Comment by DhDhanesh** [comment]
this is kendo datepicker, i want it only in readonly.

   <kendo-datepicker name="activationDate" placeholder="mm/dd/yyyy" [max]="maxActiveDate" [class.form-control-danger]="fromDate.invalid && fromDate.touched"
                             id="fromDate" [disabled]="disableSchool"  [(value)]="activationDate" (valueChange)="changeActivationDate();changeExpirationDate(); minExpiryDate = activationDate"  [(ngModel)]="activationDate" #fromDate="ngModel"
                            ></kendo-datepicker>

**Comment by TUSHARDM** [comment]
I have used onkeydown="return false;"  on date picker and it worked as above desired behavior.

**Comment by mboulemkhali** [comment]
Thanks @TUSHARDM, that helps me a lot.

works with kendo-datepicker and angular.

<kendo-datepicker
                #model="ngModel"
                required
                name="date"
                [(ngModel)]="date"
                [min]="minDate"
                        [max]="maxDate"
                [placeholder]="'Sélectionner une date'"
                [format]="'dd/MM/yyyy'"
                (valueChange)="onDateChange($event)"
                onkeydown="return false;">
              </kendo-datepicker>

well done.

**Comment by dimitar-pechev** [comment]
The desired functionality is also available as a component feature now by setting the [`readOnlyInput`](https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/readonly-state/#toc-read-only-input) prop to `true`. Implemented in the DatePicker, TimePicker and DateTimePicker.
