### ISSUE TITLE
MultiSelect's placeholder gets trimmed after an item is selected and deselected

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1144]
The undesired behavior can be observed in the following Plunker after removing the custom styles:

[http://plnkr.co/edit/QAcKumzNxABCOs11AaQX?p=preview](http://plnkr.co/edit/QAcKumzNxABCOs11AaQX?p=preview)

As a temporary workaround set **min-width** to the element, holding the placeholder like in the example above.

**Comment by ipeshev** [comment]
Fixed in v1.4.1-dev.201712180927

**Comment by gyoshev** [comment]
Released in `1.4.1`
