### ISSUE TITLE
DropDownList lose value when blurred 

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1146]
## I'm submitting a...

* Bug report 

## Current behavior
Untouched DropDownList lose its value when focused and then blurred and valuePrimitive="true"

## Expected behavior
It should not lose it value when blurred, no matter valuePrimitive="true"

## Minimal reproduction of the problem with instructions
1. Open this [plunk](http://plnkr.co/edit/DbQs8QQQBzPqoJ2HmKRe?p=preview).
2. Open dropdownlist and then click out of it.

## Environment

Package versions:
Broken in
```
 v1.3.0
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by tapopov** [comment]
Cannot reproduce on current `development` branch. Possibly duplicate of https://github.com/telerik/kendo-angular/issues/1104

**Comment by ipeshev** [comment]
Yes indeed it is fixed in v1.3.1-dev.201712120900

**Comment by ipeshev** [comment]
Shipped with v1.4.0
