### ISSUE TITLE
Calendar's navigation is broken when used within a Dialog

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1147]
Calendar's navigation is not working properly when the Calendar (version 1.4.0) is used within a Dialog component:

[http://plnkr.co/edit/bBWyh3OWNyyO4i7INvQQ?p=preview](http://plnkr.co/edit/bBWyh3OWNyyO4i7INvQQ?p=preview)

Working as expected with version 1.3.1:

[http://plnkr.co/edit/p03ydLpQmCakDBesC4Sg?p=preview](http://plnkr.co/edit/p03ydLpQmCakDBesC4Sg?p=preview)

**Comment by ipeshev** [comment]
It is also valid for window , https://plnkr.co/edit/j1jr8ZVG6UIqeStn1hug?p=preview - from client ticket.

**Comment by heinzer** [comment]
Hi,
I just want to say that we have exactly the same problem with the Calendar within a dialog. Does anyone have a work around for this issue?

**Comment by ggkrustev** [comment]
Hi @heinzer,

the component stops working in Dialog/Window, because it is created in a hidden container by the Angular. The solution is to postpone the calendar creation with a tick. Check the suggested workaround.

https://plnkr.co/edit/IpGX9gW4gisLdahPFFk2?p=preview

**Comment by NicolasDiab** [comment]
Hi,

The same problem is happening with a calendar inside a splitter. The workaround is working well though.

https://stackblitz.com/edit/angular-mjtb2z?file=app%2Fapp.component.ts

**Comment by yhorak** [comment]
We have the same issue when we display calendar in multiple tabs and just hide it to keep calendar state. 
Calendar navigation is broken when the calendar is placed in a hidden container (display = none).
Does someone plan to work on it? 

Very simple example 
https://stackblitz.com/edit/angular-1iaw73?embed=1&file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by tapopov** [comment]
Fix available in 4.4.0
