### ISSUE TITLE
DropDownList does not fire valueChange event after data is updated

### ISSUE THREAD

**Issue by SimonNodel-AI** [telerik/kendo-angular#1151]
## I'm submitting a...

* Bug report 

## Current behavior

If the bound data changes and the new list has an option for a value that was previously selected, the valueChange event won't fire unless you select a different option.

## Expected behavior

The valueChange event should fire every time when a user selects a value from the drop down control.

## Minimal reproduction of the problem with instructions

[plunker](http://plnkr.co/edit/ZHnCYDi4RaGCpvVopwvP?p=preview)

  1. Select 'Item 3' from the drop down
  2. Click 'Update Data' button
  3. Select 'Item 3' from the drop down.  valueChange event isn't called and selected value remains 'Item 0'.  

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Safari (iOS) version XX

System:
- TypeScript version: 2.4.2
- Node version: 6.11.3
- Platform:   Mac, linux

I am quite sure the control was working in 1.1.3 as expected (can't easily verify it now)

**Comment by SimonNodel-AI** [comment]
I have also tried to switch to reactive forms data binding and observed the same problem

**Comment by tapopov** [comment]
Thank you for the provided example. We will investigate what's causing this.

**Comment by ipeshev** [comment]
Fixed in v1.4.1-dev.201712180927

**Comment by ipeshev** [comment]
Shipped with v1.4.1
