### ISSUE TITLE
form.reset() does not reset a ComboBox component

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1153]
When resetting the form, the value of the ComboBox is not reset as well. 

Please check the following sample plunker that reproduces the issue:

[http://plnkr.co/edit/VBUpJsDMrcAcJTQ1CxW2?p=preview](http://plnkr.co/edit/VBUpJsDMrcAcJTQ1CxW2?p=preview)

**Comment by DGolverdingen** [comment]
I also would like to see this fixed with form reset.

**Comment by SebLz** [comment]
I'm also having this problem, having to use the reset method of the component is not always convenient.

**Comment by ipeshev** [comment]
Shipped with 1.6.0
