### ISSUE TITLE
Browsers behave differently when clicking on a label to focus a DatePicker

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1154]
Clicking on the label in Chrome focuses the year of the DatePicker. This contrasts with the behavior in Firefox and IE where the month is focused.

In order to reproduce the behavior please check the following sample plunker [http://plnkr.co/edit/Hm3G8RRWqifINU9VrjXU?p=preview](http://plnkr.co/edit/Hm3G8RRWqifINU9VrjXU?p=preview) in different browsers.

**Comment by ggkrustev** [comment]
The desired unification of the segment select behavior won't be an easy task. 

When wrapped inside a label element, the native click event is triggered, which tricks the component to think that a user has clicked the `<input />` element. In this case, we cannot determine whether to override the caret position given by the browser (different in major browser vendors). I am afraid that we cannot do much here.

**The best solution in this case is to use Kendo Label for Angular** and link the component using `for` property binding:
```
<label [for]="datepicker">Select a date:</label>
<kendo-datepicker
     #datepicker
     [(value)]="value"
></kendo-datepicker>
```
Demo: http://plnkr.co/edit/CPOxFEZ9VkMCUAV0wLpW?p=preview
