### ISSUE TITLE
TypeError:  Textbox Component produces error in Firefox (srcElement is undefined)

### ISSUE THREAD

**Issue by prabh-62** [telerik/kendo-angular#1155]
*TypeError*
columnNumber: 73
fileName: "http://localhost:4200/vendor.bundle.js line 2999 > eval"
lineNumber: 84
message: "e.srcElement is undefined"
stack: 
"TextBoxContainerComponent.prototype.ngAfterContentInit/<@webpack-internal:///../../../../@progress/kendo-angular-inputs/dist/es/textbox/textbox-container.component.js:84:73\n
TextBoxContainerComponent.prototype.listen/listener<@webpack-internal:///../../../../@progress/kendo-angular-inputs/dist/es/textbox/textbox-container.component.js:123:13

## I'm submitting a...
* Bug report

## Current behavior
Kendo Textbox produces an error in Firefox due to usage of non-standard API (srcElement)

## Expected behavior
Kendo Textbox should ideally work without any issues across all browsers

## Minimal reproduction of the problem with instructions
- `Ctrl + F` in  `\node_modules\@progress\kendo-angular-inputs\dist\es\textbox\textbox-container.component.js` for srcElement

## What is the motivation or use case for changing the behavior?
[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement)

## Environment

Package Versions
```
@angular/______@5.0.3
@progress/kendo-angular-inputs@1.3.3
```

Browser:
- Firefox version 57.0.2

System:
- TypeScript version: 2.6.2
- Node version: 8.9.0
- Platform:  Windows 10

**Comment by gyoshev** [comment]
Thank you for the bug report. This has already been fixed in the development channel, version `1.4.1-dev.201712151445`.
