### ISSUE TITLE
Grid: Selection doesn't work with OnPush

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1156]
## I'm submitting a...
* Bug report

## Current behavior
With OnPush change detection strategy selection doesn't work really well.

## Minimal reproduction of the problem with instructions
See: http://plnkr.co/edit/Xr0FNgIVZ6pHW5aRragi

**Comment by tsvetomir** [comment]
Seems to work well with the latest update.

**Comment by meriturva** [comment]
Seems fixed. Thanks
