### ISSUE TITLE
MultiSelect filter not firing event when filter data deleted

### ISSUE THREAD

**Issue by gchurchley** [telerik/kendo-angular#1157]
## I'm submitting a BUG for the MultiSelect Component Filtering.

There is an example of filtering here: https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/filtering/

My code is identical except that it is running in an Angular CLI application.
The filtering works when filter characters are entered, but no filter event is fired when the filter string is deleted. 

## Current behavior
If I enter the letter 'a' - then all items containing 'a' will be displayed in the dropdown.
If I then delete the letter 'a' - no filter event is fired!
This cannot be reproduced in plnkr because plnkr uses systemJs and Angular CLI uses webpack.

## Expected behavior
Removing the filter text should fire a filter event even if the filter text is deleted.

## Minimal reproduction of the problem with instructions
* Create Angular CLI app
* Add MultiSelect control with filtering
* Test

## Environment

Package versions:

    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@progress/kendo-angular-buttons": "^1.0.5",
    "@progress/kendo-angular-dateinputs": "^1.2.0",
    "@progress/kendo-angular-dropdowns": "^1.4.0",
    "@progress/kendo-angular-grid": "^1.4.1",
    "@progress/kendo-angular-inputs": "^1.3.0",
    "@progress/kendo-angular-intl": "^1.2.2",
    "@progress/kendo-angular-l10n": "^1.0.3",
    "@progress/kendo-angular-label": "^1.0.3",
    "@progress/kendo-angular-layout": "^1.0.7",
    "@progress/kendo-theme-default": "^2.43.1",
    "angular2-jwt": "^0.2.3",
    "apx-ui-core": "^2.8.2",
    "apx-ui-core-styles": "^1.0.0",
    "apx-ui-reg-config-interface": "^1.0.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"

Browser:
- Chrome (desktop) version XX

System:
- TypeScript version: 2.4.2
- Node version: 6.9.5
- Platform:  Windows

**Comment by valchev** [comment]
@gchurchley thank you for bringing this to our attention.

**Comment by gchurchley** [comment]
@valchev - Hi, any update on a fix for this issue?

**Comment by valchev** [comment]
@gchurchley I just pushed a fix for the issue.

It will take some time before it passes QA check and propagates to the official release.

**Comment by ipeshev** [comment]
Shipped with 1.6.0
