### ISSUE TITLE
Documentation of changes not up to date

### ISSUE THREAD

**Issue by DGolverdingen** [telerik/kendo-angular#1158]
## I'm submitting a...

* Documentation issue or request

## Current behavior
Changelog of components not up to date with latest versions of packages.

## Expected behavior
Only release new version if changelog is updated. (Please add changelog to the npm package).

## Minimal reproduction of the problem with instructions
Get latest npm package or compare with ncu tooling:
![image](https://user-images.githubusercontent.com/29942500/33980602-e3087706-e0a9-11e7-99e6-da36ec5c6e20.png)

Go to [changelog ](https://www.telerik.com/kendo-angular-ui/components/grid/changelog/)of component to see what changes are finally added or what bug is solved:
![image](https://user-images.githubusercontent.com/29942500/33980659-1781e760-e0aa-11e7-8807-feca6b1642cc.png)

What is fixed or changed in grid 1.6.2 and 1.6.3?
What is fixed or changed in dropdown 1.3.0 and 1.4.0?

Please improve the quality of the documentation

**Comment by tsvetomir** [comment]
The changelog is uploaded as part of the site updates. These usually happen at least once a week, but the last update got delayed due to some internal reorganization.

This still leaves a gap of few days so we are also considering a real-time solution. Related to #974.

**Comment by tsvetomir** [comment]
By the way, the [dev snapshot](https://www.telerik.com/kendo-angular-ui-develop/components/grid/changelog/) of the changelog is usually in sync with the latest version.

**Comment by DGolverdingen** [comment]
Ok, good to know, the gap is now more then a month.. It was indeed faster in the past.

But how about adding the changelog into the readme of the package?
Thanks for the dev snapshot, I did not know of it.

**Comment by tsvetomir** [comment]
Good idea. I'm merging this issue into #974
