### ISSUE TITLE
license with npm @progress packages

### ISSUE THREAD

**Issue by stepet80** [telerik/kendo-angular#1159]
Hello,

We have a question regarding licenses and the @progress npm bundles.
The company where I work has a global license for Kendo UI and Kendo Angular UI falls within this license.
We want to use Kendo Angular UI and are pulling packages through npm install @progress/xxx.
How does the licensing work on these npm packages?

Kind regards

**Comment by tsvetomir** [comment]
The [license](https://github.com/telerik/kendo-angular/blob/master/LICENSE.md) requires each developer to have an assigned seat. Other than that you're free to install and use the packages.

I'll close this issue as this is a bug tracker. Please submit any additional licensing questions through our sales and support channels.

**Comment by nishant-tm** [comment]
We recently purchased 2 developer seat(s) for Progress® Kendo UI® Developer License - Lite Support.
We want to use @progress/kendo-ui  from npm https://www.npmjs.com/package/@progress/kendo-ui.
How we will get it done with licensed version which we recently purchased.

**Comment by tsvetomir** [comment]
@nishant-tm thank you for your purchase! Using Kendo UI for jQuery with NPM is covered in [this documentation article](https://docs.telerik.com/kendo-ui/intro/installation/npm#kendo-ui-professional).

**Comment by nishant-tm** [comment]
I can use it directly by installing npm package but I want to use it as licensed version. I purchased licensed version but I am not able to find npm package.

**Comment by tsvetomir** [comment]
This is the licensed version. Additional downloads are available through the "My Account" page.
Please, direct any further licensing questions through our support ticketing system.
