### ISSUE TITLE
DatePicker used in an Angular Material Dialog throws an error when the page is scrolled

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1160]
![image](https://user-images.githubusercontent.com/7533599/33986382-0cba085a-e0c6-11e7-800b-fbcfdd8657e4.png)

![image](https://user-images.githubusercontent.com/7533599/33986393-17fe3240-e0c6-11e7-9356-59d8672118b9.png)

Further details, and a sample project are available in the following support thread:

Ticket ID: 1144760

**Comment by ggkrustev** [comment]
The issue also occurs when view with datepicker is destroyed and in the same datepicker is opened.
Reported in TicketID: 1144871

**Comment by ggkrustev** [comment]
Similar to https://github.com/telerik/kendo-angular/issues/1138

**Comment by ggkrustev** [comment]
Seems to be fixed.

**Comment by ipeshev** [comment]
Shipped with v3.2.0
