### ISSUE TITLE
disable, delete and backspace keys in kendo-timepicker

### ISSUE THREAD

**Issue by kelumKP** [telerik/kendo-angular#1161]
I'm trying to block the functionalities of **Backspace** key and **Delete** key for kendo timepciker 
using following approaches

**Approach 1**
`<kendo-timepicker  onkeydown="if (event.keyCode == 46 || event.keyCode == 8) false;"></kendo-timepicker>`

**Approach 2**
`<kendo-timepicker  onkeypress="if (event.keyCode == 46 || event.keyCode == 8) false;"></kendo-timepicker>`

but none of this work properly

**Comment by ggkrustev** [comment]
Indeed, wiring the onkeydown event handler of the `kendo-timepicker` custom HTML element won't work. The only possible way to interact with the DateInput KB behavior is to select the visible `<input />` element and wire its keydown event. This could be done using a custom Angular Directive that will inject the component giving you control to the rendered HTML.

More about the Angular Directives can be found in the Angular documentation:
https://angular.io/api/core/Directive

Last but not least, please note that the Github issue threads should be used only for Bug reports or Feature requests. This restriction help us to keep the reported issues easily trackable and for future references. 

**If you need further assistance on this issue, please either open a support ticket or post your question in Stackoverflow.**
