### ISSUE TITLE
The cursor should always move to the end when selecting a value from the ComboBox

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1162]
The cursor won't move to the end of the ComboBox, as expected. Even after blurring the ComboBox and coming back to it by pressing the arrow on the right will not move the cursor to the end.

The reported behavior can be observed in the following sample plunker:

[https://plnkr.co/edit/hOIFxRdB2GvrzNl7SGLc?p=preview](https://plnkr.co/edit/hOIFxRdB2GvrzNl7SGLc?p=preview)

**Comment by ipeshev** [comment]
Fix available in latest  develop version v2.0.0-dev.201801261243

**Comment by ipeshev** [comment]
Shipped with v2.0.0
