### ISSUE TITLE
Grid column can disappears when the whole grid is resized

### ISSUE THREAD

**Issue by JBildstein** [telerik/kendo-angular#1163]
## I'm submitting a...
* Bug report 

## Current behavior
Define a grid with multiple columns, set a width to all but one column and resize the window. Once the window (and with it, the grid) gets small enough the column without a width disappears. Alternatively, reload the page where the window size is already small enough and the column will never show up.

## Expected behavior
The column should still be visible even if it's just very small and no data can actually be read. It must be apparent that there is a column.
When manually resizing a column this behavior is already there.
Ideally I would also be able to define a minimum width or minResizableWidth would be respected.

## Minimal reproduction of the problem with instructions

Here's a Plnkr: https://plnkr.co/edit/O8UmYXWLp0f6F2IFiFwU?p=preview
I took the example from here: https://www.telerik.com/kendo-angular-ui/components/grid/columns/#toc-column-resizing
and removed the width from the product name column.
To reproduce the problem, resize the window until the product name column disappears.

## What is the motivation or use case for changing the behavior?
A user should be able to see that there is another column even if they have a small screen. Then they can at least resize it until they are able to see the content.

## Environment

Package versions:
@progress/kendo-angular-grid 1.6.4

Browser:
- Chrome (desktop) version 63
- Firefox version 57
- Edge version 15

System:
- TypeScript version: 2.4.2
- Node version: 8.0.0 (npm 5.6.0)
- Platform:  Windows 10, Linux (Chromium only)

## References
This problem was already mentioned in this issue #145 but wasn't addressed.

**Comment by rkonstantinov** [comment]
The behavior you have described is how the HTML table element behaves when having fixed layout and width. You could verify this for yourself in [this sample](http://dojo.telerik.com/@rkonstantinov/eGUVI).

As in the case with the Grid component. You could set a `min-width` to the tables in order to constrain how much the column will be collapsed. The following is modified version of the previous sample, which demonstrates this in action:
https://plnkr.co/edit/qHPRLNDSIe7owPeHdBTf?p=preview

**Comment by JBildstein** [comment]
I was not aware of that, thank you for the example.
Setting the min-width of the table works for me but I have to be able to set different values to different tables so for now I use something like this:
```
.mytable  /deep/ table {
    min-width: 500px;
}
```
I'm aware that /deep/ is deprecated but for now that's the easiest solution (while still having view encapsulation).
Perhaps it would also be solvable with a directive and ElementRef/Renderer.

It would be great if I could set it directly to the kendo table but there's a workaround so I'll close the issue.
