### ISSUE TITLE
DateInput initially receives ng-dirty class while DatePicker does not

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1164]
There is a visual (styling) discrepancy when the DateInput and DatePicker are used in a form and are both initially invalid:

[https://plnkr.co/edit/rxAtHpn9o2XdVYsWVtcg?p=preview](https://plnkr.co/edit/rxAtHpn9o2XdVYsWVtcg?p=preview)

The DateInput initially receives "**ng-dirty**" class while the DatePicker remains "**ng-pristine**".

CSS workaround:

**kendo-theme-default:**
```
.ng-invalid.ng-untouched > .k-dateinput-wrap {
  color: #656565;
  border-color: rgba(0,0,0,.08);
 }
        
 .ng-invalid.ng-touched > .k-dateinput-wrap {
  color: #f31700;
  border-color: rgba(243,23,0,.5);
}
```
[https://plnkr.co/edit/3BViHkZOCDD5rw6H510k?p=preview](https://plnkr.co/edit/3BViHkZOCDD5rw6H510k?p=preview)

**kendo-theme-bootstrap:**
```
.ng-invalid.ng-untouched > .k-dateinput-wrap {
  color: #212529;
  border-color: rgba(33,37,41,.15);
}
        
.ng-invalid.ng-touched > .k-dateinput-wrap {
  color: #dc3545;
  border-color: #dc3545;
}
```
[https://plnkr.co/edit/4M8P6JJx5IOnrDKNjScV?p=preview](https://plnkr.co/edit/4M8P6JJx5IOnrDKNjScV?p=preview)

**Comment by ggkrustev** [comment]
Fixed in @progress/kendo-angular-dateinputs@2.1.1
