### ISSUE TITLE
expandGroup() will not expand the group

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1169]
Steps to reproduce:

1. Manually collapse the first group by clicking on its arrow.
2. Click the button "Expand First Group"

Result - The expand/collapse arrow changes but the group is not expanded.

sample plunker demonstrating the issue:

[http://plnkr.co/edit/1hdZngktZufzXQlZl6A6?p=preview](http://plnkr.co/edit/1hdZngktZufzXQlZl6A6?p=preview)

**Comment by rusev** [comment]
There is a limitation when using the `kendoGridGroupBinding` directive to implement grouping with virtual scrolling - the expand/collapse API methods are not supported in this case.
