### ISSUE TITLE
kendoPanelBarContent is not updating in Angular 5

### ISSUE THREAD

**Issue by kokhooi** [telerik/kendo-angular#1170]
## I'm submitting a...

* Bug report 

## Current behavior

Child component in kendoPanelBarContent is not updated in Angular 5
## Expected behavior

Child component should be updated whenever there's a change 

## Minimal reproduction of the problem with instructions

here's the plunker link
https://plnkr.co/edit/lU1ar8urMIn2nHiXwnib 

if click on the Append, the total is increasing, but child is not getting the update

go to systemjs.config.js, change the angularVersion to 4.4.6, and do the same action again

you will see the child is getting the update.

**Comment by kokhooi** [comment]
hi any update on this?

**Comment by Raisolution** [comment]
Hi @kokhooi,

This is rather related to the way Angular handles change detection, and not to the PanelBar itself. Concatenating the two arrays works as expected. Here is the [updated plunkr](https://plnkr.co/edit/yUm6d7UpP1JuUqZPfjnI?p=preview).

**Comment by Raisolution** [comment]
Hi @kokhooi 

I am closing this thread for the moment. Feel free to reopen it if needed.
