### ISSUE TITLE
Grid Filter Menu : on a column menu filter, second filter operator always mimics the first one if leave blank

### ISSUE THREAD

**Issue by budara** [telerik/kendo-angular#1171]
## I'm submitting a bug for a column menu filter
Here is in an plunker example of a default menu filter :
https://plnkr.co/edit/tDW2l8NMDwn5oajSrE9c?p=preview

## Current behavior
* If I filter a column selecting first operator other than default leaving the second operator as default
* and If I go to filter again the second filter operator changes to the first operator we selected before

## Expected behavior
* If I filter a column by first operator the extra operator should not mimic the first operator, it should leave as default. That will confuse user as they are not selecting the second operator.

## Minimal reproduction of the problem with instructions
1. Open it in Plunker : https://plnkr.co/edit/tDW2l8NMDwn5oajSrE9c?p=preview
2. Click on filter icon for Product column and filter by Is Null selecting the first operator leaving the second operator as it is
3. Click on filter icon for Product again and observe the second filter is changed to Is Null

Browser:
Chrome (desktop) version XX

**Comment by vivek201** [comment]
This causes even more problems. 

[https://plnkr.co/edit/XU04GJxTrMXnNr9bIXCi?p=preview](https://plnkr.co/edit/XU04GJxTrMXnNr9bIXCi?p=preview)

In the above plnkr, for the column "Notes", if you select the filter "Is Null" and filter and then again change the filter to "Is Empty", the grid becomes empty.

![filtermenu](https://user-images.githubusercontent.com/12758783/34292709-02b7f0a0-e72a-11e7-99e6-f8a2f0e621bb.gif)

**Comment by rkonstantinov** [comment]
Thanks for the report. The issue should be fixed with [the latest develop build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `kendo-angular-grid package`.

**Comment by budara** [comment]
Thanks @rkonstantinov
