### ISSUE TITLE
Chart tooltip offset when page is zoomed in Safari

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1172]
The chart tooltip is rendered in wrong position when the page is zoomed:

![image](https://user-images.githubusercontent.com/7533599/34336632-742fee34-e961-11e7-9bf3-4466482fd00e.png)

Observed when running the [online demos](https://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/tooltips/) in Safari on IPad Air 2 under iOS 11.2.1

**Comment by ipeshev** [comment]
Shipped with v1.4.0
