### ISSUE TITLE
Filter menu popup is not displayed correctly in RTL mode

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1173]
## I'm submitting a...

* Bug report 

## Current behavior
Filter menu is not flowing from right to left and it is not aligned with right corner of it's opener but to left.

## Expected behavior
It should be displayed as datepicker popup

## Minimal reproduction of the problem with instructions

- Open this [plunk](https://plnkr.co/edit/2KHqEwpps3kCocQX8A3D?p=preview)

- Check filter menu popup and datepicker popup

Browser:
All

**Comment by elena-gancheva** [comment]
This is fixed and available in latest dev version of the package - `v1.6.1-dev.201801181238`.

**Comment by ipeshev** [comment]
Shipped with v1.6.5
