### ISSUE TITLE
The Form reset() method does not clear the value of the DropDownList

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1175]
[https://plnkr.co/edit/leZ2xa6sU0acMggO6hvS?p=preview](https://plnkr.co/edit/leZ2xa6sU0acMggO6hvS?p=preview)

Select a value from the list and reset the form via the button.

The Form value is reset properly, and validation is triggered, but the selected value in the DropDownList remains.

**Comment by valchev** [comment]
@tapopov probably related with #1153

**Comment by ipeshev** [comment]
Fixed in v1.5.1-dev.201801081242

**Comment by ipeshev** [comment]
Shipped with v1.6.0
