### ISSUE TITLE
Detail Grid layout breaks when resolution changes

### ISSUE THREAD

**Issue by codehippie1** [telerik/kendo-angular#1176]
Kendo Angular Detail Grid Layout breaks while zooming in chrome.

**Steps to reproduce**
1. Open [](url)https://plnkr.co/edit/l1JgHqc56S1J3Fa4sVvo?p=preview in chrome
2. Either set the resolution to 1048 x 768. Or zoom in 'in chrome'
3. Grid layout breaks (no horizontal scrollbars to navigate)

**Expected behaviour**: Grid lay out should not break

**Comment by rkonstantinov** [comment]
I'm afraid that this is the default HTML table element behavior - it will overflow outside of its container element. You may verify this using [this sample](http://dojo.telerik.com/@rkonstantinov/iHUNOw). If you need to to show scrollbars when data does not fit into the container (detail row width), you will need to set the detail Grid component as [`scrollable`.](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-scrollable)

**Comment by codehippie1** [comment]
Thank you so much.
