### ISSUE TITLE
Not all Form Components scale with relative font-size

### ISSUE THREAD

**Issue by stefan-schweiger** [telerik/kendo-angular#1178]
## I'm submitting a ...

* Bug report 

## Current behavior
When the body font-size is changed some components also change their relative font-size (rem) but some components don't.

<img width="359" alt="screenshot 2017-12-29 12 53 25" src="https://user-images.githubusercontent.com/3532342/34436623-bbf4375a-ec97-11e7-941c-4b458541fe16.PNG">

## Expected behavior
At least all form controls should behave the same way, either scale to the font-size (I would prefer it this way) or don't change at all.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/OzgVtDj1iM5Fc86LqQYf?p=preview

## What is the motivation or use case for changing the behavior?
When displaying a form on a page and not all controls have the same font-size it just looks bad.

**Comment by tsvetomir** [comment]
Looks good in the [current version](https://plnkr.co/edit/iyFUS0j6GLnAXkOEpagu?p=preview).
