### ISSUE TITLE
DropDowns' anchor alignment is not reversed in RTL mode

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1180]
The components from the DropDowns package are not aligned to their anchors as expected in RTL mode (the top-left corner of the popup is aligned with the bottom-left corner of the anchor, while users expect the top-right corner of the popup to be aligned with the bottom-right corner of the anchor).

Same applies to the DropDownButton component.

Related to:

[https://github.com/telerik/kendo-angular/issues/1173](https://github.com/telerik/kendo-angular/issues/1173)

**Comment by elena-gancheva** [comment]
This is fixed and available in latest dev version of the package - `v1.6.1-dev.201801181238`.

**Comment by ipeshev** [comment]
Shipped with v1.6.5
