### ISSUE TITLE
Grid, Variable Filter and Locked columns lead to weird UI column bug

### ISSUE THREAD

**Issue by kotva006** [telerik/kendo-angular#1182]
## I'm submitting a...

* Bug report

## Current behavior
I have a grid which has locked columns and a filter row that is visibly toggled with a button.
When the row is toggled the grid lines in the filter row are not extending to the bottom of the row.

## Expected behavior
That the filter row look like every other row in the table

## Minimal reproduction of the problem with instructions
In the table below the first 2 columns are locked.
https://plnkr.co/edit/LydiwZDpdilaeANTx6HP?p=preview
To see the issue open the plnkr above and click the show filter button.
A filter row should appear on the table.
On the filter row that appears notice the some of the grid lines don't line up.  These columns are not locked, where as the grid lines that do line up are columns that are locked.

## What is the motivation or use case for changing the behavior?
So the table looks more professional

## Environment
Browser:
- Chrome (desktop) version 63.0.3239.84

**Comment by rkonstantinov** [comment]
Hi @kotva006,
Thanks for the report. The issue should be fixed in [the latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `kendo-angular-grid` package.
