### ISSUE TITLE
Discrepancy in MultiSelect behavior when selected items are cleared

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1191]
When the last selected value is cleared (there are no selected items), and the component is still focused, clicking in the section, containing the inner INPUT element will not trigger opening of the options list, while clicking to the right of it will:

[https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/multiselect/](https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/multiselect/)

![image](https://user-images.githubusercontent.com/7533599/34661626-8adcaa3a-f453-11e7-8808-4319d02a2496.png)

**Comment by ipeshev** [comment]
Fixed in [latest dev version](v3.0.3-dev.201808031552).

**Comment by tsvetomir** [comment]
Shipped in v3.0.3
