### ISSUE TITLE
DropdownList Observable.merge unimported

### ISSUE THREAD

**Issue by Zaixu** [telerik/kendo-angular#1192]
## I'm submitting a...
* Bug report

## Current behavior
DropDownList component uses rxjs patching, but forgets to include "import 'rxjs/add/observable/merge" that it uses.

This will fail builds that use lettable operators.

## Expected behavior
Use that import or start using lettable operators for benefits.

## Minimal reproduction of the problem with instructions
It can be seen in source of the component that Observable.merge is used, but never imported.

## What is the motivation or use case for changing the behavior?
Builds to work correctly without having to patch the error locally.
This is an error that first gets picked up in production builds, so only seen when already built.

**Comment by valchev** [comment]
@Zaixu thank you for bringing this to our attention.
I pushed a fix for the issue, it is currently available in the latest dev build.

**Comment by valchev** [comment]
Latest version (1.6.0) contains the fix and is shipped.

**Comment by jesulink2514** [comment]
![image](https://user-images.githubusercontent.com/2278766/34891663-534e6348-f7a4-11e7-8a30-559a94f0e10a.png)

I faced the same issue when the **kendo dropdown** is used in **a lazily loaded module with** **Angular 5**. Here is a minimal repo to reproduce the problem. 

[https://github.com/jesulink2514/kendo-dropdown-issue](https://github.com/jesulink2514/kendo-dropdown-issue)

**Comment by tsvetomir** [comment]
This issue turned out to be [more complicated](https://github.com/ReactiveX/rxjs/issues/3222) than we initially thought. We're investigating the possible fixes. Worst case, we'll have to upgrade to the latest RxJS version with lettable operators - a breaking change for users that are still on older versions.

**Comment by tsvetomir** [comment]
Tracking in #1214
