### ISSUE TITLE
KendoGrid row selection bug when selecting the same row multiple times

### ISSUE THREAD

**Issue by Hashemalrifai** [telerik/kendo-angular#1194]
## I'm submitting a...
* Bug report

## Current behavior
Kendo Grid -> Selection enabled -> An exception when clicking over a row for three times, and the grid doesn't respond to new selections.
Exception: 
`
Uncaught TypeError: Cannot read property 'ProductID' of undefined
    at t.e.getItemKey (kendo-angular-grid.js:3)
    at eval (kendo-angular-grid.js:3)
    at Array.forEach (<anonymous>)
    at t.e.onSelectionChange (kendo-angular-grid.js:3)
    at b.schedulerFn [as _next] (event_emitter.js:168)
    at b.__tryOrUnsub (Subscriber.ts:254)
    at b.next (Subscriber.ts:204)
    at b._next (Subscriber.ts:135)
    at b.next (Subscriber.ts:95)
    at EventEmitter.b.next (Subject.ts:61)
`

## Expected behavior
No exception, maybe deselecting the row is what meant 

## Minimal reproduction of the problem with instructions
An official example in plunker: 
https://plnkr.co/edit/9G0ZHNzQge1OkJR4eLKF?p=preview
Run -> Show console -> Click over a row for three times

## Environment

Package versions:
`
    "@progress/kendo-angular-dateinputs": "^1.4.2",
    "@progress/kendo-angular-dropdowns": "^1.5.0",
    "@progress/kendo-angular-excel-export": "^1.0.5",
    "@progress/kendo-angular-grid": "^1.6.4",
    "@progress/kendo-angular-inputs": "^1.4.1",
    "@progress/kendo-angular-intl": "^1.3.0",
    "@progress/kendo-angular-l10n": "^1.0.5",
    "@progress/kendo-angular-layout": "^1.2.0",
    "@progress/kendo-data-query": "^1.1.2",
    "@progress/kendo-drawing": "^1.4.0",
    "@progress/kendo-theme-default": "^2.46.0",
`

**Comment by Raisolution** [comment]
Hi @Hashemalrifai,

The fix is available in the latest dev release `v1.7.2-dev.201801161725` and will also be present in the next official one.

**Comment by ipeshev** [comment]
Shipped with v1.7.2
