### ISSUE TITLE
Multiple fields are not translatable

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#1195]
For example
FilterMenuContainer

captions: Filter, Clear are not translatable.  Hardcoded.

`                template: "\n        <form (submit)=\"submit()\" (reset)=\"reset()\"\n            class=\"k-filter-menu k-popup k-group k-reset k-state-border-up\">\n            <div class=\"k-filter-menu-container\">\n                <ng-container [ngSwitch]=\"hasTemplate\">\n                    <ng-container *ngSwitchCase=\"false\">\n                        <ng-container\n                            kendoFilterMenuHost\n                            [filterService]=\"childService\"\n                            [column]=\"column\"\n                            [filter]=\"childFilter\">\n                        </ng-container>\n                    </ng-container>\n                    <ng-container *ngSwitchCase=\"true\">\n                        <ng-template\n                            *ngIf=\"column.filterMenuTemplateRef\"\n                            [ngTemplateOutlet]=\"column.filterMenuTemplateRef\"\n                            [ngTemplateOutletContext]=\"templateContext\"\n                            >\n                        </ng-template>\n                    </ng-container>\n                </ng-container>\n                <div class=\"k-action-buttons k-button-group\">\n                    <button type=\"reset\" class=\"k-button\">Clear</button>\n                    <button class=\"k-button k-primary\" [disabled]=\"disabled\">Filter</button>\n                </div>\n            </div>\n        </form>\n    "`

**Comment by rkonstantinov** [comment]
Thanks for the report, the filter menu buttons will be available for localization with the next version of the `kendo-angular-grid` package. Currently, this is possible with the latest @dev channel version of the package.

**Comment by montella1507** [comment]
Is there any page where we can see Changelog for concrete package?  i cannot find it  there:
https://www.telerik.com/kendo-angular-ui/

**Comment by montella1507** [comment]
+ github doesnt work anymore:
https://github.com/telerik/kendo-angular-grid  (404)

**Comment by rkonstantinov** [comment]
`kendo-angular-grid` repository is a private one. A change log for the official version of the each packages is available in the appropriate [Changelog section](https://www.telerik.com/kendo-angular-ui/components/grid/changelog/).
