### ISSUE TITLE
Grid filter menu displaying incorrect logic after another filter is applied

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1196]
The Grid's menu filter can lose its AND/OR condition.

In the plunker for this section in your documentation: [https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#toc-filter-menu](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#toc-filter-menu)

Follow these steps, the filter will lose its "OR" condition:

1) Filter on Product Name: Contains "Chef" OR Contains "a"

2) Filter on Unit Price: Is equal to "18"

3) Display the Product Name filter.  The condition has changed to AND, not OR.  It should still be OR.

**Comment by rkonstantinov** [comment]
This has been fixed with the 1.7.1 version of the grid package.
