### ISSUE TITLE
'reorderable' properties not working...

### ISSUE THREAD

**Issue by Hemadri-befree** [telerik/kendo-angular#1197]
'reorderable' properties not working...
error: Can't bind to 'reorderable' since it isn't a known property of 'kendo-grid'.

If 'kendo-grid' is an Angular component and it has 'reorderable' input, then verify that it is part of this module.
If 'kendo-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this mess

**Comment by Hemadri-befree** [comment]
Freezing column headings Kendo grid Angular 2

**Comment by rusev** [comment]
You are probably using older version of the `@progress/kendo-angular-grid` package which doesn't have support for the `reorderable` feature. Please upgrade to the latest version.
