### ISSUE TITLE
Memory leak in Sortable

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1199]
When the Sortable component is rerendered multiple times, a memory leak is observed in IE:

[http://plnkr.co/edit/CepwUzvt486pwuS2Fst5?p=preview](http://plnkr.co/edit/CepwUzvt486pwuS2Fst5?p=preview)

The memory usage of the corresponding process increases over time, and the used memory does not seem to be released within a reasonable timeframe.

**Comment by tsvetomir** [comment]
Have you tried testing in production mode? Development mode is notorious for memory leaks.

**Comment by dtopalov** [comment]
Increased memory consumption is observed after enabling production mode as well:

[http://plnkr.co/edit/z0nL6mrXzL3v7ioeO2Ts](http://plnkr.co/edit/z0nL6mrXzL3v7ioeO2Ts)

**Comment by Raisolution** [comment]
Closing as IE is no longer supported by the Kendo UI for Angular library.
