### ISSUE TITLE
DropDownList: value disappear after filtering

### ISSUE THREAD

**Issue by Attosius** [telerik/kendo-angular#1200]
## I'm submitting a

* Bug report 

## Pre condition
* add on page dropdownlist (filterable) with filterChange
* items in ddl: smal, medium, large  (as in example https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/)
* add  [valuePrimitive]="true"
* add handleFilter as in example + add logic to display only 2 items

```
handleFilter(value) {
        this.data = this.source
        .filter((s) => s.text.toLowerCase().indexOf(value.toLowerCase()) !== -1)
        .filter((element, index) => index < 2);
    }
```

## Current behavior
After filtering and select item, item not appear in dropdownlist

## Minimal reproduction of the problem with instructions

* open dropdownlist 
* type on filter input e.g. "large" - on filtered list appear item "Large"
* select Large
* item not selected, in ddl text is empty

Planker: [planker](https://plnkr.co/edit/YoEpc1nPoaXvOteEAsXr?p=preview)

![kendo-filter-bug](https://user-images.githubusercontent.com/21027214/34775128-1b402b6c-f623-11e7-9071-a97b0fae04b0.gif)

## What is the motivation or use case for changing the behavior?

This case use as analog "page" property in kendoJQ

Browser:
- Chrome (desktop) version 56.0.2924.87 (64-bit)

Package versions:
```
"@progress/kendo-angular-dropdowns": "^1.5.0",
```

**Bug doesn't reproduce with  [valuePrimitive]="false"**

**Comment by tapopov** [comment]
@Attosius thanks for reporting this.
When an item is selected, the `filterChange` event is triggered with an empty string (allowing the application to clear the existing filters). This causes the data to be filtered again, where the `index < 2` criteria is not met, the "Large" item removed from the `data` and therefore from the selection. We will investigate further why the behavior is not consistent between primitive and complex values and will update the issue again.
Meanwhile, you can check for empty string in the filter as a workaround. [Here](https://plnkr.co/edit/2xemogHyjwGVJa0uhguQ?p=preview) is an example.

**Comment by Attosius** [comment]
@tapopov 
Yes, this will really help me, thanks!

**Comment by ipeshev** [comment]
Shipped with v1.6.1

**Comment by karthik2294** [comment]
> @Attosius thanks for reporting this.
> When an item is selected, the `filterChange` event is triggered with an empty string (allowing the application to clear the existing filters). This causes the data to be filtered again, where the `index < 2` criteria is not met, the "Large" item removed from the `data` and therefore from the selection. We will investigate further why the behavior is not consistent between primitive and complex values and will update the issue again.
> Meanwhile, you can check for empty string in the filter as a workaround. [Here](https://plnkr.co/edit/2xemogHyjwGVJa0uhguQ?p=preview) is an example.

The same bug is still combobox of latest version of kendo with angular 9 @Attosius

**Comment by dimitar-pechev** [comment]
@karthik2294, the solution is either to allow custom values (`[allowCustom]="true"`) or to omit filtering when the search query has no length ([example](https://stackblitz.com/edit/angular-zzta3w)).

As resolved custom values can too easily be discarded from a ComboBox, that is configured to disallow custom values, the component will not display a selected value that is not present in the data set. So this behavior is expected.
