### ISSUE TITLE
Sortable addDataItem leads to unexpected behavior

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1201]
When adding a new item via the API, and dragging an item from another group to the new one, the whole new group is dragged instead the item only:

[https://plnkr.co/edit/OBUUKkpZ49LdfAeWqdZr?p=preview](https://plnkr.co/edit/OBUUKkpZ49LdfAeWqdZr?p=preview)

[https://www.screencast.com/t/fPCsGUdAMn7](https://www.screencast.com/t/fPCsGUdAMn7)

**Comment by ipeshev** [comment]
Fixed in latest development version  - v2.0.0-dev.201810182222. Please do note that this is a breaking change and component should be configured in different fashion. 
Refactored sample available [here](https://stackblitz.com/edit/sortable-in-sortable?file=app/app.component.ts).

**Comment by tapopov** [comment]
Shipped in `kendo-angular-sortable` v2.0.0
