### ISSUE TITLE
Splitter pane resizing "forgets" cursor if cursor enters iframe

### ISSUE THREAD

**Issue by zrsio4** [telerik/kendo-angular#1204]
## I'm submitting a...
* Bug report 

## Current behavior
When dragging the splitter bar to resize panes, if the cursor enters the iframe box, resizing stops. When cursor re-enters the splitter bar, resizing happens again, but mouse-down state does not matter. i.e. returning to the splitter bar after mouse-over on the iframe, I can release the click and the splitter bar will still resize once the cursor is over it again.

Seems to work fine in Edge though.

## Expected behavior
Resizing happens even over an iframe and click states remembered.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/6G5ZTEdwtUcZHmqDZ5Wv
Chrome or FireFox

## What is the motivation or use case for changing the behavior?
I have a Kendo jQuery Editor in one of the frames, which uses an iframe.

## Environment
Browser:

- Chrome (desktop) version 63.0.3239.132
- Firefox version 57.0.3
- Edge version 40.15063.674.0

System:
- TypeScript version: 2.5.3
- Node version: node 6.10.3    npm 3.10.10
- Platform:  Windows

**Comment by gyoshev** [comment]
This functionality has been released in version `2.1.0` of the `@progress/kendo-angular-layout`.
