### ISSUE TITLE
Treeview: suggestion to add hasChildrenField and isCheckedField Inputs

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1206]
## I'm submitting a...
* Suggestion for improvement

## Expected behavior
It would be nice to have 2 additional Input properties:
* `hasChildrenField`: read this property to determine if node has children

* `isCheckedField`: read this property to determine if node is checked in case of `kendoTreeViewCheckable`
`isCheckedField` should also write to this property, when check state changed

## What is the motivation or use case for changing the behavior?
* `hasChildrenField`: avoid writing code like `public columnHasChildren = (item: IColumn) => item.hasChildren;`

* `isCheckedField`: Usually you need to send data to server together with some identifier which nodes are selected. If we have access to modified(checked state) nodes we could just easily send complete nodes to server.
In this case we could avoid writing code like this
```
const subject = this.treeviewColumns.data as BehaviorSubject<IColumn[]>;
            const nodes = subject.getValue();

            let recursion = (nodes: IColumn[], checkedPath: string) =>
            {
                for (const [index, node] of nodes.entries())
                {
                    node.checked = this.columnsCheckedKeys.indexOf(checkedPath + index.toString()) > -1;
                    if (node.children)
                        recursion(node.children, checkedPath + index.toString() + "_");
                }
            }
            recursion(nodes, "");

            //output:
            nodes = [{
                text: "Item 0",
                checked: false,
                children: [{
                        text: "Item 0_0",
                        checked: false
                }, {
                    text: "Item 0_1",
                    checked: true
                }]
            }];
```
to set checked to nodes and similar when columnsCheckedKeys must be set.

Browser:
- Chrome (desktop) version XX

System:
`"@progress/kendo-angular-treeview": "^1.0.0",`

**Comment by ggkrustev** [comment]
Hello @MaklaCof,

Thanks for the proposal. It contains two different features, hence I will comment them separately.

The `hasChildrenField` functionality is already implemented by the [HierarchyBindingDirective](https://www.telerik.com/kendo-angular-ui/components/treeview/api/HierarchyBindingDirective/) directive. When `childrenField` property is defined, the directive will define custom `hasChildren` function for you. Then the TreeView will use that function to check for children.

An `isCheckedField` property makes sense as a separate check directive. We will consider in future, but for now I would suggest you implementing a custom directive, e.g. CheckFieldDirective, that will modify the treeview data item field on checkedChange and will consider item checked when the specific `dataItem.checked` field is true. For your convenience I've prepared a simple demo that demonstrates one possible approach.

https://stackblitz.com/edit/treeview-custom-check-field

Could you post your suggestion for a feature enhancement in our UserVoice portal? We will need to gather community feedback before schedule it for further investigation.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

**Comment by MaklaCof** [comment]
Thank you @ggkrustev 
childrenField is OK for HierarchyBindingDirective.

But what about Remote Heterogeneous Data. hasChildrenField would really make sense here. In most cases server returned boolean field which contains information if node has children.

**Comment by ggkrustev** [comment]
Thanks for the clarification.

I suppose that a separate `hasChildrenField` could be useful in some cases. In order to determine whether such functionality will be useful to others, please post your request in our UserVoice portal. Thus more people will be able to cast their vote for it.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

I will close the this thread, because the decision whether this will be included as built-in feature depends entirely on the users' interest.

**Comment by MaklaCof** [comment]
Yes and we all know how this goes. It's never implemented.
Thank you anyway.

**Comment by ggkrustev** [comment]
I understand your frustration, but I hope you will agree that we should at least hear additional opinion on the subject. The channel used for such feedback is UserVoice.

If you believe that such functionality will be really useful to many others, then I would like to ask you to demonstrate it in a custom directive based on out `HierarchicalBindingDirective`. Thus we will get a better understanding what exactly such enhancement resolves and how useful it will be to the others. 
I will be more than happy to continue the discussion, but for that task I will need a concrete implementation to focus on.
