### ISSUE TITLE
TreeView: missing exports in main.d.ts

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1207]
## I'm submitting a...
* Bug report

## Current behavior
Looking main.d.ts I think is missing export for TreeItemLookup:
`export { ItemLookup, TreeItemLookup } from './treeitem-lookup.interface';`
and others.

I need to import it like:
`import { TreeItemLookup } from "@progress/kendo-angular-treeview/dist/es/treeitem-lookup.interface";`

## Expected behavior
I would like to import it like:
`import { TreeItemLookup  } from '@progress/kendo-angular-treeview';`

### System:
`"@progress/kendo-angular-treeview": "^1.0.0-dev.201801111327"`

**Comment by ggkrustev** [comment]
Hi @MaklaCof, thanks for the report. Indeed, some interfaces were missing, but the latest DEV release includes them. The version is `v1.0.1-dev.201801121319`. The fix will be released officially soon.

I will mark the issue as resolved. Please comment if I am missing something.
