### ISSUE TITLE
Date and time picker steal focus from clicked element

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#1212]
Example: https://plnkr.co/edit/yK66cQFM475n8pQo6MvG?p=preview

To reproduce, open the date or time picker popup and then click on the plain input. The focus should be on the clicked element but instead it is on the date or time picker input

**Comment by ggkrustev** [comment]
A possible fix will be to explicitly focus the input before the popup is closed. Right now the code utilizes the popupClose event, which seems to be too late.

**Comment by ggkrustev** [comment]
The latest DEV release fixes this issue - v1.4.4-dev.201801250830

**Comment by ggkrustev** [comment]
v1.4.4 is out. https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/
