### ISSUE TITLE
Source code of demo website

### ISSUE THREAD

**Issue by nm-a** [telerik/kendo-angular#1215]
Hi Team,
Will it be possible to share the source of demos (working solution), this will help to follow best practices & understand more about kendo components.

https://www.telerik.com/kendo-angular-ui

thank you

**Comment by gyoshev** [comment]
The demo site is not an angular application, but rather a static website that hosts the examples. It is of marginal value as an Angular learning resource, and there are no plans to release its source code.

For a complete application that uses the Kendo UI for Angular components, see the [ng-dashboard application](https://github.com/telerik/ng2-dashboard).

**Comment by L-Bouzid** [comment]
hi gyoshev, but what about the examples source on the same site.

**Comment by gyoshev** [comment]
@L-Bouzid The source code of each example can be run from the site, though the "Open in Plunker" button. If you need offline access to the examples, you can run the documentation of a specific package by [obtaining its source code](https://www.telerik.com/kendo-angular-ui/components/installation/source-code/) and running the `gulp docs` task. I am afraid that we do not ship a solution that includes all examples from the site.
