### ISSUE TITLE
Not able to get legend in bar series

### ISSUE THREAD

**Issue by nm-a** [telerik/kendo-angular#1216]
Hi Team,
I am not able to get the legend with bar / column series types. Do we need to add any extra settings to this.

    <kendo-chart>
 	  <kendo-chart-legend position="top"></kendo-chart-legend>
      <kendo-chart-series>
        <kendo-chart-series-item type="column" [data]="[1, 2, 3, 5]">
        </kendo-chart-series-item>
        <kendo-chart-series-item type="column" [data]="[-1, -2, -3, -5]">
        </kendo-chart-series-item>
      </kendo-chart-series>
    </kendo-chart>

thank you

**Comment by danielkaradachki** [comment]
You should set [name](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesItemComponent/#toc-name) to the series in order for the legend items to be displayed:

https://plnkr.co/edit/1pINW5kCfbZxeJuLc10c?p=preview

We will add note in the documentation.
