### ISSUE TITLE
Static bar of a resizable SplitterPane 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1226]
The bar is static of a resizable SplitterPane. 

Check the following sample plunker:

[https://plnkr.co/edit/eCfTML3lhw5Uacnls2g7?p=preview](https://plnkr.co/edit/eCfTML3lhw5Uacnls2g7?p=preview)

**Comment by gyoshev** [comment]
Fixed in `@progress/kendo-angular-layout@v1.2.1`. The site was deployed, so the plunker snippet now works correctly.
