### ISSUE TITLE
TreeView: updating selectedKeys does not update selection

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1227]
* Bug report

## Current behavior
When selectedKeys changes in code, selection is not updated.

## Expected behavior
Selection in html is updated.

## Minimal reproduction of the problem with instructions
[Plunkr](https://plnkr.co/edit/wYEYceHBucxhJHdQYyWh?p=preview).
After 2 seconds selections should change. Plunkr is provided with `selectBy` property set, but it also doesn't work without `selectBy`.

## What is the motivation or use case for changing the behavior?
I think it is a bug.

Browser:
- Chrome (desktop) version XX

**Comment by ggkrustev** [comment]
I just like to inform you that we are preparing an enhancement in the TreeView directives that will support the described scenario. I'll update the thread once the fix is out.

**Comment by ggkrustev** [comment]
The latest DEV release includes a fix for the discussed issue. Please give it a try and let us know if the problem still persists.
- v1.1.0-dev.201801241312

**Comment by ggkrustev** [comment]
Version 1.1.0 is out. Will close the thread as resolved.
