### ISSUE TITLE
(dragEnd) event for SplitterPane component

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1228]
Implementation of a (dragEnd) event for the SplitterPane component.

Requested in ticket 1148240.

**Comment by gyoshev** [comment]
Version `v2.1.0-dev.201802151013` of the `@progress/kendo-angular-layout` package introduces the `layoutChange` event, which is triggered after the splitter layout changes, either through resizing or when panes are collapsed. It can be used for reflowing content inside the splitter panes.
