### ISSUE TITLE
TreeView: Add a node to expandedKeys don't expand the node

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#1231]
## I'm submitting a...

* Bug report 

## Current behavior

When I add a node to the expandedKeys from code, the TreeView don't expand the node. After I click on the node text, it expand. Look at the punker demo.

## Expected behavior

The TreeView should be expand the node, after adding to the expandedKeys.

## Minimal reproduction of the problem with instructions

[Plunker Demo](https://plnkr.co/edit/tnYRRivDS770dplUp0XN?p=preview)
Click on the 'Expand Decor' button, nothing happens.

Browser:

- Chrome (desktop) version 63

System:
- TypeScript version: 2.6.1
- Node version: 8.1.0
- Platform:  Windows

**Comment by ggkrustev** [comment]
The TreeView component uses `OnPush` strategy by default, which makes it unresponsive when the list is mutated. We will further investigate the case and will post an update soon.

**Comment by ggkrustev** [comment]
I just like to inform you that we are preparing an enhancement in the TreeView directives that will support the described scenario. I'll update the thread once the fix is out.

**Comment by ggkrustev** [comment]
The latest DEV release includes a fix for the discussed issue. Please give it a try and let us know if the problem still persists.
- v1.1.0-dev.201801241312

**Comment by andrpelz** [comment]
I have tried with this version and it solves my problem. The nodes are now expanding when I add it to expandedKeys.

Thanks for the fast answer and the fixing the bug!

**Comment by ggkrustev** [comment]
Version 1.1.0 is out. Will close the thread as resolved. Please comment if smth is still not OK.

**Comment by seshu-uggina** [comment]
issue is still producible
