### ISSUE TITLE
Component should be focused when clearing its text through the X button

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#1232]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Clicking the AutoComplete and ComboBox's clear text button does not focus the component. 
The MultiSelect exhibits similar behavior, however this happens when clicking the tag's remove button.

## Expected behavior
The focus should be moved to the component's input element.

**Comment by ipeshev** [comment]
Shipped with v1.6.1
