### ISSUE TITLE
Grid column resizing breaks when scrollable = 'none'

### ISSUE THREAD

**Issue by tomfumb** [telerik/kendo-angular#1234]
## I'm submitting a...

* Bug report 

## Current behavior

Column resizing misbehaves when the grid's scrollable property is 'none'. Without a scrollable property columns correctly respect width and minResizableWidth properties. When scrollable is 'none' columns erroneously enforce a minimum width, which might be based on content. The user cannot resize a grid column to below this width. If the user tries to further reduce width other columns start responding to mouse movements. If the mouse is dragged outside the browser window then released column widths behave erratically when the mouse re-enters the grid.

## Expected behavior

It should be possible to disable scrolling with [scrollable]='none' without this interfering with column resizing. Resizing should behave the same.

## Minimal reproduction of the problem with instructions

[Plunkr](https://plnkr.co/edit/YEqGhjiihirxjZujNifb)

## What is the motivation or use case for changing the behavior?

It appears to be a bug. The documentation makes no reference to this interaction between the scrollable and resizeable properties and a flexible grid should support this configuration.

## Environment

Package versions:

```
See Plunkr
```

Browser:

- Chrome (desktop) version 63.0.3239.132

System:
See Plunkr

**Comment by ipeshev** [comment]
Fix available in [latest dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version.

**Comment by danielkaradachki** [comment]
Released in 3.10.0:
https://stackblitz.com/edit/angular-tfk4gt?file=app/app.component.ts
