### ISSUE TITLE
[kendo-theme-material] Undefined variables when individual files are imported

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#1235]
## I'm submitting a...
Bug

## Current behavior
Trying to import kendo-theme-material/scss/multiselect.scss however it leads to an error in the SASS loader.

**Error:**
Undefined variable: "$disabled-opacity".

##  Additional information that might be relevant.
Related to [Link](https://github.com/telerik/kendo-theme-bootstrap/issues/285)
Fix was implemented to kendo-theme-bootstrap. [Link](https://github.com/telerik/kendo-theme-bootstrap/commit/954404be85c6e6aecde473b616cccb8836aaf859)

## Suggested Fix 
As per previous fix add `@import "~@progress/kendo-theme-default/scss/variables";` in @progress\kendo-theme-material\scss\_variables.scss

**Comment by gyoshev** [comment]
A fix has been released in `v0.3.1-dev.201801241439` of the material theme (available through the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)), pending an official release with the next version.

**Comment by gyoshev** [comment]
The fix was officially released in `@progress/kendo-theme-material@0.3.4` and later.
