### ISSUE TITLE
Execute build prod failed with grid filters

### ISSUE THREAD

**Issue by nlgi** [telerik/kendo-angular#1236]
## I'm submitting a...

* Bug report 

## Current behavior

In chrome console, on pages with grid and filters enabled, I get the error "i.a.merge is not a function"
No problem with grid without filters.
Only with build prod, in the main bundle js file.

## Minimal reproduction of the problem with instructions

Command: node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build -prod
Everything compile fine, but error in execution (chrome console).

## Environment

Package versions:

```
+-- @agm/core@1.0.0-beta.2
+-- @angular/animations@5.2.1
+-- @angular/cdk@5.1.0
+-- @angular/cli@1.6.5
+-- @angular/common@5.2.1
+-- @angular/compiler@5.2.1
+-- @angular/compiler-cli@5.2.1
+-- @angular/core@5.2.1
+-- @angular/forms@5.2.1
+-- @angular/http@5.2.1
+-- @angular/material@5.1.0
+-- @angular/platform-browser@5.2.1
+-- @angular/platform-browser-dynamic@5.2.1
+-- @angular/platform-server@5.2.1
+-- @angular/router@5.2.1
+-- @progress/kendo-angular-buttons@2.0.0
+-- @progress/kendo-angular-charts@1.4.0
+-- @progress/kendo-angular-dateinputs@1.4.3
+-- @progress/kendo-angular-dialog@2.0.0
+-- @progress/kendo-angular-dropdowns@1.6.0
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@1.7.1
+-- @progress/kendo-angular-inputs@1.4.2
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-layout@1.2.0
+-- @progress/kendo-angular-messages@1.10.0
+-- @progress/kendo-angular-scrollview@1.0.7
+-- @progress/kendo-angular-upload@2.1.1
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-drawing@1.4.1
+-- @progress/kendo-theme-default@2.47.0
+-- @types/jasmine@2.8.4
+-- @types/jquery@3.2.18
+-- @types/node@9.3.0
+-- angular-gridster2@4.4.2
+-- angular-in-memory-web-api@0.5.2
+-- bootstrap@4.0.0
+-- cldr-data@32.0.1
+-- codelyzer@4.1.0
+-- core-js@2.5.3
+-- hammerjs@2.0.8
+-- immutable@3.8.2
+-- jasmine-core@2.9.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.2.1
+-- karma@2.0.0
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.3
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- lodash@4.17.4
+-- md2@0.0.29
+-- moment@2.20.1
+-- ng-dynamic-component@2.0.3
+-- ng2-tooltip-overlay@0.4.1
+-- ngx-cookie@2.0.1
+-- ngx-perfect-scrollbar@5.3.1
+-- ngx-tooltip@0.0.9
+-- pdfmake@0.1.35
+-- popper.js@1.12.9
+-- protractor@5.2.2
+-- reflect-metadata@0.1.12
+-- rxjs@5.5.6
+-- socket.io-client@2.0.4
+-- ts-node@4.1.0
+-- tslint@5.9.1
+-- typescript@2.6.2
+-- underscore@1.8.3
+-- webpack@3.10.0
`-- zone.js@0.8.20
```

Browser:

- Chrome (desktop) version 63

System:
- TypeScript version: 2.6.2
- Node version:6.10.1
- Platform:  Windows 

Many thanks for any help!

**Comment by kotva006** [comment]
I get this same exact issue, though i haven't been able to reproduce it outside of our build.

**Comment by kotva006** [comment]
We found a work around by turning off the build optimizer (--build-optimizer=false)
Try adding that flag to your ng build to see if it helps.

**Comment by nlgi** [comment]
Yes, working with --build-optimizer=false (and @progress/kendo-angular-grid@1.7.2)

**Comment by tsvetomir** [comment]
Should be working after updating to the latest package versions, see #1244

**Comment by nlgi** [comment]
It's not working with 2.0.1.
Ok with --build-optimizer=false

Many thanks for your feedback

**Comment by tsvetomir** [comment]
Please make sure that all packages are at the latest versions and you don't get "UNMET PEER DEPENDENCY" errors on "npm install".

You can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to automatically take the latest version:
```
npm install -g npm-check-updates
ncu -u -f /^@progress/
```

**Comment by nlgi** [comment]
yes I'm using ncu (awesome package!)
"All dependencies match the latest package versions :)"
No "UNMET PEER DEPENDENCY".

I tried to delete node_modules folder and reinstall: same error.

**Comment by tsvetomir** [comment]
Can you check the RxJS usage in your project? Particularly global operators should be replaced with [pipeable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md).

Also, can you paste the output from `npm ls --depth 0` just to double check?

**Comment by tsvetomir** [comment]
One last thing, remove `package-lock.json` and reinstall the packages if you haven't tried that already.

**Comment by nlgi** [comment]
Oh! Looks like it was package-lock.json.

Many thanks!
