### ISSUE TITLE
Multiselect: SummaryTag count update don't updates the visible items

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#1237]
## I'm submitting a...

* Bug report 

## Current behavior

When I update the 'kendoMultiSelectSummaryTag' directive count from the code, it not updates the current visible items in the multiselect. After a selection change it works.

## Expected behavior

Changing the count should immediately update the visible items.

## Minimal reproduction of the problem with instructions

[Plunker Demo](https://plnkr.co/edit/0WZ2Ak94ScRPI6y9OiFl?p=preview)
Click on the Button, nothing happens in the multiselect.

## Environment

Browser:

- Chrome (desktop) version 63

System:
- TypeScript version: 2.6.1
- Node version: 8.1.0
- Platform:  Windows

Dropdown Package Version: 1.6.0

**Comment by ipeshev** [comment]
Fixed in v2.1.0-dev.201802271249

**Comment by tsvetomir** [comment]
Released in v2.1.0
