### ISSUE TITLE
Grid filter menu - custom filter

### ISSUE THREAD

**Issue by tipag** [telerik/kendo-angular#1238]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Reusable custom filter only work with the default filter option filterable=true but not with filterable=menu.

## Expected behavior
It would be nice, if the custom filter could be displayed in the menu-filter popup.

## Minimal reproduction of the problem with instructions
In the Reusable Custom Filter Components tutorial set "filterable" to "menu". Then you will see that instad of the custom dropdown filter a text input filter is shown for the column "category".
https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/reusable-filter/

## What is the motivation or use case for changing the behavior?
I have a column in which I let the user choose a date range via a custom control. In the menu-filter I would like to allow the user to use the same control. In the meantime it is possible to just not use the menu filter, but in my case that is no long-term solution since my customers requested the menu-filter.

**Comment by mbrookson** [comment]
I agree with this post. You can do as you said above, but what about reusable filters?

I have played around with inheriting the `BaseFilterCellComponent` but this doesn't work properly with the menu filters because they are applied straight away, ignoring the 'Clear' and 'Filter' buttons.

Is this currently possible to do? If not, is the feature going to be added?

**Comment by tipag** [comment]
I only called updateFilter, apparently applyFilter will be called on filter button click. As for the clear button it only works if your filter field property is the same as the column field. The same goes for the styles that are applied (e.g. filter icon is blue if column is filtered).

In my case I could easily implement it that way. However, I agree that a new base class BaseFilterMenuComponent where you can implement onFilter and onClearFilter would be a great addition, maybe it would also be useful to have a property telling the filter to apply styles even if filtering for other properties than column.field. So I'm going to reopen.

**Comment by mbrookson** [comment]
Yeah I only call updateFilter(). I worked out it is actually possible to integrate, but like you said it would be better to have more control by exposing onFilter and onClearFilter events.

For the buttons to work properly you have to implement let-filter="filter" on the kendoGridFilterMenuTemplate, and an @Input() filter inside component (as per docs).

Then finally, to resolve the 

> filter field property is the same as the column field

**Comment by tipag** [comment]
There is an example in #1312 showing how to implement custom menu filter. Apparently no base class is needed, since everything can be implemented by adding filterService as input variable to the custom component. Therefore, I will close this issue again.
