### ISSUE TITLE
Grid: column width is not obeyed

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1239]
## I'm submitting a...
* Bug report 

## Current behavior
I set width to all columns, but grid ignores column width, if sum of all widths is less then grid width. It works if sum of all grid is more then grid width.
Grid should obey columns width. I try to skip setting last column width, but it is not working, because if sum of columns grid is more then grid width, last column width is not displayed. (probably his width is 0)

## Expected behavior
Grid obeys. 😄 

## Minimal reproduction of the problem with instructions
[Plunkr](https://plnkr.co/edit/WxwLBHSlDFewC8yvFZG8?p=preview).

**Comment by rusev** [comment]
Indeed this is how HTML table works. The `Grid` is using HTML tables for rendering and the same rules applies for columns width. That said you should either:
 - set `width` for the Grid, which is less or equal to the sum of all columns width
 - leave a column without explicit width set

Updated example - https://plnkr.co/edit/1cmGNDPPGWEmKCC1faly?p=preview

**Comment by MaklaCof** [comment]
I can not set Grid width, since I am using Grid inside my component and used on many places. I also don't know how many columns are [visible](https://www.telerik.com/kendo-angular-ui-develop/components/grid/columns/hidden/#toc-hidden).

If I manually shrink columns it works.
![chrome_2018-01-23_07-17-27](https://user-images.githubusercontent.com/1589573/35260781-7dca8464-000d-11e8-9d3b-3205d6c1a537.png)
Why it should work when setting width with code?

**Comment by rusev** [comment]
I'm not sure what you mean the following statement. Can you please elaborate?

> setting width with code

**Comment by MaklaCof** [comment]
My apologise. I mean when user resizes columns.  
When user resize columns, sum of all columns can be less then grid width. My uploaded image (2 posts up).
But when I set width in code ([column width property](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/ColumnComponent/#toc-width)) this doesn't work.

**Comment by rusev** [comment]
I see what you mean.

When the user resize a particular column (by dragging the header) Grid tables width is re-calculated. This is required in order to persist the rest of the columns width. 

This behavior however is not the _standart_ for HTML tables. We even do an extra step on the first resize. There is a code that sets the column width to match the current state from the DOM. Otherwise there is strange "jiggle" while resizing.
