### ISSUE TITLE
Grid column orderIndex all 0 until first reorder

### ISSUE THREAD

**Issue by zrsio4** [telerik/kendo-angular#1241]
## I'm submitting a...
* Bug report

## Current behavior
Upon reordering the columns via drag-drop, iterating through the columns in the reorder event shows all columns' orderIndex property is set to 0.

## Expected behavior
Columns' orderIndex property set to correct value

## Minimal reproduction of the problem with instructions
1) Enable column reordering
2) Reorder columns
3) In the reorder event, iterate through the columns, observe orderIndex == 0
4) Reorder columns
5) In the reorder event, iterate through the columns, observe orderIndex are expected values.
Repro
https://plnkr.co/edit/IbR3K8JDnn72V7HpAKkH

## What is the motivation or use case for changing the behavior?
Persisting order index requires accurate representation of grid state

## Environment
Package versions:
+-- UNMET PEER DEPENDENCY @angular/animations@5.2.1
+-- @angular/cdk@5.1.0
+-- @angular/cli@1.6.5
+-- @angular/common@5.1.3
+-- @angular/compiler@5.1.3
+-- @angular/compiler-cli@5.1.3
+-- UNMET PEER DEPENDENCY @angular/core@5.1.3
+-- @angular/forms@5.1.3
+-- @angular/http@5.1.3
+-- @angular/material@5.1.0
+-- @angular/platform-browser@5.1.3
+-- @angular/platform-browser-dynamic@5.1.3
+-- @angular/platform-server@5.1.3
+-- @angular/platform-webworker@5.1.3
+-- @angular/platform-webworker-dynamic@5.1.3
+-- @angular/router@5.1.3
+-- @ng-idle/core@2.0.0-beta.13
+-- @ng-idle/keepalive@2.0.0-beta.13
+-- @progress/kendo-angular-buttons@2.0.0
+-- @progress/kendo-angular-dateinputs@1.4.3
+-- @progress/kendo-angular-dialog@2.0.0
+-- @progress/kendo-angular-dropdowns@1.6.0
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@1.7.1
+-- @progress/kendo-angular-inputs@1.4.2
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-layout@1.2.0
+-- @progress/kendo-angular-sortable@1.0.5
+-- @progress/kendo-angular-treeview@1.0.1
+-- @progress/kendo-angular-upload@2.1.1
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-drawing@1.4.1
+-- @progress/kendo-theme-bootstrap@2.10.0
+-- @progress/kendo-theme-default@2.47.0
+-- @progress/kendo-theme-material@0.3.0
+-- @progress/kendo-ui@2018.1.117
+-- @types/file-saver@1.3.0
+-- @types/jasmine@2.8.4
+-- @types/jquery@3.2.18
+-- @types/node@8.5.9
+-- angular2-notifications@0.9.7
+-- angular2-uuid@1.1.1
+-- UNMET PEER DEPENDENCY bootstrap@4.0.0-beta.2
+-- codelyzer@4.0.2
+-- core-js@2.5.3
+-- file-saver@1.3.3
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.2.1
+-- karma@2.0.0
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.3
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- node-sass@4.7.2
+-- protractor@5.2.2
+-- rxjs@5.5.6
+-- sass-loader@6.0.6
+-- signalr@2.2.2
+-- ts-node@4.1.0
+-- tslint@5.8.0
+-- typescript@2.5.3
`-- zone.js@0.8.20

Browser:

- Chrome (desktop) version 63.0.3239.132

System:
- TypeScript version: 1.0.3.0
- Node version: 6.10.3 NPM version 3.10.10
- Platform:  Windows

**Comment by rusev** [comment]
`orderIndex` property is not part of the public API of the column. It is implementation detail, required by the column reordering feature. It is intentionally left undocumented in the [column API](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/).

In the context of [columnReorder](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnReorderEvent/) event you can use the arguments to obtain information about old/new column index. Example - https://plnkr.co/edit/o8aMIkThHg6C0pIoKcwb?p=preview.

**Comment by MaklaCof** [comment]
I know that I can use columnReorder event. But why should I be forced to do it?  
Problem is I have to recalculate all columns order before I send to server new columns order.

If I move column from 2 to 5 all columns greater then 5 needs to get increase in order. How can I know which columns?

**Comment by rusev** [comment]
Similar to https://github.com/telerik/kendo-angular/issues/1240
