### ISSUE TITLE
Changing the orientation of the Splitter causes undesired behavior

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1242]
Check the following sample plunker demonstrating the issue:

[https://plnkr.co/edit/DAqje4pT9y0kqmXXniaG?p=preview](https://plnkr.co/edit/DAqje4pT9y0kqmXXniaG?p=preview)

**Comment by gyoshev** [comment]
Fixed in `@progress/kendo-angular-layout@1.2.1`. [See plunker](https://plnkr.co/edit/WnGH4JGOVXl6p8Nscu3v?p=preview).
