### ISSUE TITLE
Grid > SelectionChangeEvent: deselectedRows empty when used with virtual scrolling

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#1243]
## I'm submitting a...

* Bug report 

## Current behavior

We have a grid that uses scrolling="virtual" and try to update an array of selected records using a subscription to grid.selectionChange. When a user select a record on page A, then scrolls and selects a record that is on page B, the SelectionChanged event will not contain the first record in deselectedRows. If both records are on the same page, everything works fine.

Steps to reproduce:

* Grid, scrolling=virtual, pagesize=100, selectable=multi, records named rec0...n
* Click on rec0 => ok
* Click rec101 => event.deselectedRows is empty.

## Expected behavior

event.deselectedRows contains rec0. It works as expected if the second record is on the same page (so for rec1 - rec99)

Package versions:

```
"@progress/kendo-angular-grid@^1.7.1":
```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 2.5.2 
- Node version: 6  
- Platform: Windows

**Comment by Raisolution** [comment]
Hi @cluetjen,

The described behavior is by design, as the selection operates only over the currently rendered items. You could use the `ctrlKey` parameter of the [SelectionEvent](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionEvent/) or the [SelectionDirective](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/) to handle the case. Further information regarding the selection could be found [here](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-during-data-operations).

**Comment by cluetjen** [comment]
Hi @Raisolution ,

thanks for your fast response.

> You could use the ctrlKey parameter of the SelectionEvent or the SelectionDirective to handle the case.

That's what I did. But...

... it's not working with checkbox selections.

If I say `if (!event.ctrlKey) clear selection` then I cannot select additional rows using their checkbox. 

* Select row 1
* Click Checkbox row 2
* Error: Selection of row 1 was removed (no ctrlKey)

Expected: row 1 keeps selection.

Here's the event from our row 2 checkbox click:

`"{"deselectedRows":[],"selectedRows":[{"dataItem":{"id":"id557","name":"Name 557","description":"Description 557"},"index":102}],"ctrlKey":false,"selected":true,"index":102}"
`

As you can see, it looks exactly as the event when we scroll down to the next page and select a single row there. deselectedRows = empty array, ctrlKey = false. No chance, I don't know if previously selected records must be removed.

**Comment by Raisolution** [comment]
Hi @cluetjen,

We have addressed this in the latest dev build 2.1.0-dev.201802131421. Selecting items via checkboxes is considered an addition i.e. the ctrlKey parameter of the SelectionEvent will be `true`. The fix will also be present in the next official release.
