### ISSUE TITLE
Grid state loses sort property on page changes (scrolling=virtual)

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#1245]
## I'm submitting a...

* Bug report 

## Current behavior

I've a grid with scrolling=virtual and load data using a subscription to grid.dataStateChange. When a user clicks a column header the state gets modified and provides the state.sort property containing field name and sort direction.
But... if you scroll down the grid updates state.skip but now state.sort is empty.

## Expected behavior

state.sort keeps sort information when loading additional pages.

## Minimal reproduction of the problem with instructions

Steps to reproduce:
* grid scrollable=virtual, pageSize=100, rowHeight=50
* Click header of column A
* dataStateChange emits: "{"group":[],"skip":0,"sort":[{"dir":"asc","field":"name"}],"take":100}"
* Scroll down about 150 rows
* dataStateChange emits: "{"group":[],"skip":143,"sort":[],"take":100}"

Error: State.sort is an empty array.

## What is the motivation or use case for changing the behavior?

I've to build a directive to load data from a store object.

## Environment

Package versions:

```
"@progress/kendo-angular-grid@^1.7.1":
  version "1.7.1"
  resolved "https://registry.yarnpkg.com/@progress/kendo-angular-grid/-/kendo-angular-grid-1.7.1.tgz#4a77c70beba24e971b8199d02d47ffe47a400ec2"
  dependencies:
    "@progress/kendo-angular-pdf-export" "^1.0.0"
    "@progress/kendo-angular-resize-sensor" "^2.0.0"
    "@progress/kendo-file-saver" "^1.0.0"
    "@telerik/kendo-draggable" "^1.6.0"
    tslib "^1.7.0"
```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 2.5.2 
- Node version: 6  
- Platform:  Windows

**Comment by rkonstantinov** [comment]
Could you please make sure that you are setting the sort descriptors to [the Grid's sort setting](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/GridComponent/#toc-sort) during the _DataStateChange_ event.

**Comment by cluetjen** [comment]
Thanks @rkonstantinov! That solves it.

Perhaps it's worth a note in the api docs?

Current: "Fires when the data state of the Grid is changed."

Imho it's more like "a state change was requested" (but it's (partly) not already applied,)

Thanks for a great product!
