### ISSUE TITLE
Kendo UI Fill Down Edit - Bulk Edit / Row Select

### ISSUE THREAD

**Issue by lelong37** [telerik/kendo-angular#1246]
I'm submitting a feature question

* Documentation issue or request

## Current behavior
Is there any documentation on how to do a bulk edit for Kendo UI Grid for Angular? e.g. Selecting multiple or all rows and make a single change that will update all selected rows?

## Expected behavior
N/A: Not sure where documentation is on how to implement the feature, we do already see documentation on selecting rows, don't know where editing all selected rows docs/examples are.

## Minimal reproduction of the problem with instructions
N/A

## What is the motivation or use case for changing the behavior?
N/A

## Environment
N/A

Browser:
N/A

**Comment by Raisolution** [comment]
The following documentation pages cover selecting multiple or all Grid rows, and accessing the corresponding dataItems through the `selectedKeys` collection (which could be used for bulk operations).

[https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-select-all-feature](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-select-all-feature)

[https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-persisting-the-selection](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-persisting-the-selection)
