### ISSUE TITLE
Kendo Chart - tooltip is surrounded by a white square

### ISSUE THREAD

**Issue by DOMZE** [telerik/kendo-angular#1247]
## I'm submitting a...

* Bug report 

## Current behavior
Using a kendo-chart-tooltip with a ng-template and kendoChartSeriesTooltipTemplate as for instance
```
<kendo-chart-tooltip>
	<ng-template kendoChartSeriesTooltipTemplate let-dataItem="dataItem" let-series="series">
		{{series.name}}: {{ dataItem.value | number:'1.0-0' }}
	</ng-template>
</kendo-chart-tooltip>
```
The tooltip is surrounded by a white square with a border and some padding.
Behavior is present in 1.4.0

## Expected behavior
The tooltip should not be surrounded by a white square with a border and some padding. This behavior is not present in 1.3.4

## Minimal reproduction of the problem with instructions
No code has changed from 1.3.4 to 1.4.0
Just updated the package

Package versions:

```
@angular/animations@4.4.6
@angular/common@4.4.6
@angular/compiler@4.4.6
@angular/compiler-cli@4.4.6
@angular/core@4.4.6
@angular/forms@4.4.6
@angular/http@4.4.6
@angular/platform-browser@4.4.6
@angular/platform-browser-dynamic@4.4.6
@angular/platform-server@4.4.6
@angular/router@4.4.6
@aspnet/signalr-client@1.0.0-alpha2-final
@ng-bootstrap/ng-bootstrap@1.0.0-alpha.26
@ngrx/core@1.2.0
@ngrx/effects@4.1.1
@ngrx/router-store@4.1.1
@ngrx/store@4.1.1
@ngrx/store-devtools@4.0.0
@progress/kendo-angular-charts@1.4.0
@progress/kendo-angular-dateinputs@1.4.3
@progress/kendo-angular-dropdowns@1.6.0
@progress/kendo-angular-excel-export@1.0.5
@progress/kendo-angular-grid@1.7.1
@progress/kendo-angular-inputs@1.4.2
@progress/kendo-angular-intl@1.3.0
@progress/kendo-angular-l10n@1.0.5
@progress/kendo-angular-pdf-export@1.0.1
@progress/kendo-angular-resize-sensor@1.0.5
@progress/kendo-data-query@1.1.2
@progress/kendo-drawing@1.4.1
@progress/kendo-file-saver@1.0.4
@progress/kendo-theme-bootstrap@2.10.0
@types/angular@1.6.40
@types/jasmine@2.8.4
@types/jquery@2.0.46
@types/jquery.slimscroll@1.3.30
@types/lodash@4.14.50
@types/node@7.0.22
@types/signalr@2.2.33
@types/source-map@0.5.7
@types/uglify-js@2.6.30
@types/webpack@2.2.16
angular2-busy@2.0.4
angular2-moment@1.7.1
angular2-template-loader@0.6.2
angular2-toaster@4.0.1
assets-webpack-plugin@3.5.1
awesome-typescript-loader@3.4.1
bower@1.8.0
child_process@1.0.2
clean-webpack-plugin@0.1.17
concurrently@3.5.1
copy-webpack-plugin@4.2.3
core-js@2.5.3
css-loader@0.28.9
del@3.0.0
es6-shim@0.35.3
extract-text-webpack-plugin@3.0.2
file-loader@0.11.2
gulp@3.9.1
gulp-concat@2.6.1
gulp-cssmin@0.2.0
gulp-rename@1.2.2
gulp-sass@3.1.0
gulp-uglify@3.0.0
hammerjs@2.0.8
ie-shim@0.1.0
json-loader@0.5.7
lodash@4.17.4
ngrx-store-freeze@0.2.0
ngx-infinite-scroll@0.5.2
node-sass@4.7.2
raw-loader@0.5.1
reflect-metadata@0.1.12
reselect@3.0.1
rimraf@2.6.2
rxjs@5.5.6
sass-loader@6.0.6
source-map-loader@0.2.3
string-replace-loader@1.2.0
style-loader@0.18.2
to-string-loader@1.1.5
typescript@2.4.2
webpack-md5-hash@0.0.5
webpack-merge@4.1.1
zone.js@0.8.20
```

Browser:

- Chrome (desktop) version 63.0.3239.132

System:
- TypeScript version: 2.4.2
- Node version: 6.11.2
- NPM version 5.5.1
- Platform:  Windows

**Comment by tsvetomir** [comment]
Can be observed in [this snippet](https://plnkr.co/edit/Kq1L0kosGZWrhvxppXbG?p=preview).

**Comment by gyoshev** [comment]
Fix is released in `@progress/kendo-theme-bootstrap@2.11.0` ([plunker](https://plnkr.co/edit/rGN9X1E2Hi9Mc2qy8eEX?p=preview)). There is a gray border that will be fixed in `2.11.1`.

**Comment by DOMZE** [comment]
I will reopen this because the problem is in part fixed.
See this [plunker](https://plnkr.co/edit/F4hjLbwNFofbAPU2kf37)

As you can see if I style the inner of the template, the background is still apparent yet in v1.3.4 and lower the problem was not there.

@tsvetomir @gyoshev

**Comment by gyoshev** [comment]
The tooltip has padding in order to look good when it contains only text. Changing this will break the look of tooltips for customers who set only text, and will require everybody to define a padding.

If you want to overlay the complete popup, you can set negative margins to the element in the template. Setting `margin: -.5rem -1rem;` [replaces the padding](https://plnkr.co/edit/QIj6V3u3lSHtbsqDqStS?p=preview) for the boostrap theme.
