### ISSUE TITLE
Incorrect Kendo typescript typing for GridColumnCommandItem

### ISSUE THREAD

**Issue by NewDark90** [telerik/kendo-angular#1248]
## I'm submitting a...

* Bug report 

## Current behavior

They type **GridColumnCommandItem** has an incorrect definition of property _text_.

## Expected behavior

They type **GridColumnCommandItem** should have it's property of _text_ be of type _GridColumnCommandItemText|string_ instead of just _GridColumnCommandItemText_.

This is how it's described in the documentation: https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/configuration/columns.command.text

I'm pretty sure you can't create the same behavior for "destroy" text using the object form. A string input causes typescript compiler errors.

## Minimal reproduction of the problem with instructions

Add a string to GridColumnCommandItem.text.

## What is the motivation or use case for changing the behavior?

Making type definitions more accurate

## Environment

Package versions:

```

```

Browser:

Not relevant

System:
- TypeScript version: 2.6.2 
- Node version: 8.9.3 npm: 5.2.0  
- Platform:  Windows

**Comment by rkonstantinov** [comment]
Hey @NewDark90, this repository is for Kendo UI for Angular product, not for Kendo UI for jQuery. You will need to report the issue [here](https://github.com/telerik/kendo-ui-core/issues).
