### ISSUE TITLE
Grid: selection not remove after removal

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1249]
## I'm submitting a...
* Bug report 
I search for similar and [found it](https://github.com/telerik/kendo-angular/issues/287), but it is closed from author without fix.

## Current behavior
If I select item and then remove it, selection is not emptied. Even more when I select new row, selection of deleted row is still in `selectedKeys`.
For example:
```
I select row 1.       selectedKeys = [1]           Expected: [1]
I remove row 1.    selectedKeys = [1]           Expected: []
I select row 3.       selectedKeys = [1, 3]       Expected: [3]
I select row 6.       selectedKeys = [1, 6]       Expected: [6]
```
## Expected behavior
`SelectedKeys` is correctly set.

## Minimal reproduction of the problem with instructions
[Plunk](https://plnkr.co/edit/6CMctIc8p6xjRzRlLCu4?p=preview).
Select row, remove same row, select another row.

**Comment by Raisolution** [comment]
Hi @MaklaCof,

We have addressed this issue in the latest dev build 2.1.0-dev.201802131421. It will also be present in the next official one.
