### ISSUE TITLE
Grid: 2 edit components for field - values (UI) not updated

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1250]
## I'm submitting a...  -  I am not sure what to choose
* Bug report
* Suggestion for improvement
* Documentation issue or request

## Current behavior
I have 2 components which can edit form control. (First is grid and second is outside grid.) But UI is not updated. Although row is updated when Update button is clicked.  (Even when setting value outside grid - kendo-switch.) 

![chrome_2018-01-23_16-48-12](https://user-images.githubusercontent.com/1589573/35285567-06ebccbc-005e-11e8-86c9-22cbcf59f710.png)

## Expected behavior
UI is updated when one component updates value.

## Minimal reproduction of the problem with instructions
Here is [plunkr](https://plnkr.co/edit/9qli86OgIGtrlRWqeOhP?p=preview).
Edit one row, and then change value for boolean column.

**Comment by rusev** [comment]
Seems like the official statement from Angular teams is that this is the expected behavior. More details in the following issue - https://github.com/angular/angular/issues/10036

See simplified version of the scenario - https://plnkr.co/edit/BKhBp9QqNsFcYG7wW4HV?p=preview

**Comment by MaklaCof** [comment]
Thank you. I will close this since it is Angular and not Telerik problem.
