### ISSUE TITLE
[TreeView]: Selection doesn't work in IE11/Edge

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#1251]
## I'm submitting a...
* Bug report

## Current behavior
The component doesn't trigger `selectionChange` due to a JavaScript error.

## Expected behavior
The component should select the clicked node.

## Minimal reproduction of the problem with instructions
  1. Open Selection demo - https://www.telerik.com/kendo-angular-ui/components/treeview/checkboxes/
  1. Try to select any node of the first demo

Plunker demo for future reference - https://plnkr.co/edit/eFx96yqorwBFNhAlW5yC?p=preview

## Environment
@angular/core@5.x.x
@progress/kendo-angular-treeview@1.0.1

Browser:
- IE version 11
- Edge

Reported in TicketID: 1149885

**Comment by ggkrustev** [comment]
We can easily polyfill the missing `closest` method:
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

**Comment by tsvetomir** [comment]
Not sure if adding a polyfill through the component package is a good idea. Feature detection would be better.

**Comment by ggkrustev** [comment]
It will be a feature detection. Don't worry :)

**Comment by ggkrustev** [comment]
The latest DEV release includes a fix for the discussed issue.
- v1.1.0-dev.201801241312

**Comment by ggkrustev** [comment]
Version 1.1.0 is out. Will close the thread as resolved - https://plnkr.co/edit/aaTeH8GKSZq1R41T2PsE?p=preview
