### ISSUE TITLE
Upload: HttpInterceptor

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1252]
## I'm submitting a...  (Could be any of this)
* Bug report
* Suggestion for improvement
* Documentation issue or request

## Current behavior
kendo-upload request are not intercept by HttpInterceptor which is defined in [HTTP_INTERCEPTORS array](https://angular.io/api/common/http/HTTP_INTERCEPTORS). Is this desire behaviour?  

I have global TokenInterceptor to add `Authorization: Beareer token`. But I have to duplicate this part of code in kendo-upload and [saveHeaders](https://www.telerik.com/kendo-angular-ui-develop/components/upload/api/UploadComponent/#toc-saveheaders), removeHeaders.

Maybe this is a bug?  
If it is not a bug, then I suggest improvement.
If suggestion is denied for some reason how kendo-upload works, that you should update documentation that [Angular HttpInterceptors](https://angular.io/api/common/http/HttpInterceptor) does not work with kendo-upload.

**Comment by tsvetomir** [comment]
Which version of the Upload are you using? Only [2.x is compatible](https://www.telerik.com/kendo-angular-ui/components/upload/) with HttpClientModule.

Try `npm ls @progress/kendo-angular-upload`

**Comment by MaklaCof** [comment]
Hi, that was quick.
`"@progress/kendo-angular-upload": "^2.1.0",`

**Comment by Raisolution** [comment]
Hi @MaklaCof,

Our demos utilize the HttpInterceptors (in our case to fake the request). For example [this one](https://www.telerik.com/kendo-angular-ui/components/upload/). Could you provide a runable example of this bug?

**Comment by MaklaCof** [comment]
To summarise, this(global http interceptors) should work. If will try to prepare plunkr.

**Comment by MaklaCof** [comment]
I found problem, but not sure how to solve it. It is related to Angular modules.
- I have a `basic` module and method [forRoot](https://stackoverflow.com/questions/40498081/routermodule-forrootroutes-vs-routermodule-forchildroutes), `forChild`. It imports/exports all kendo modules.
- I have `core` module. It imports `basic` with `forRoot` method.  kendo-upload interceptors works
- I have `featureA` module. It imports `basic` with `forChild` method. kendo-upload interceptors doesn't work.

**Comment by MaklaCof** [comment]
I am posting this if someone else encounter same problem.

I had one `basic` module which imports, re-exports all kendo/angular modules and common components.  
It also exported providers (with forRoot method).

Then each module (app, feature A ...) imported `basic` module. And here lies problem. Providers are loaded multiple times.

Solution (as usually lies in [documentation](https://angular.io/guide/ngmodule-faq#what-kinds-of-modules-should-i-have-and-how-should-i-use-them)) is to have at least 2 modules. First which imports/re-exports other modules and second with providers.
