### ISSUE TITLE
[Mobile]: skip input focus after popup is opened

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1253]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
Timepicker focuses input after popup is closed, which shows keyboard on mobile device.

## Expected behavior
Input focusing after closing popup should be preventable ( with some kind of widget setting ). 

## Minimal reproduction of the problem with instructions

1. Open official timepicker [demo](https://www.telerik.com/kendo-angular-ui-develop/components/dateinputs/timepicker/)
2. Click on the icon to open the timepicker popup
3. Click outside popup to close it.

## What is the motivation or use case for changing the behavior?
Open mobile keyboard is unwanted in this case.

## List of related components
- [x] DropDowns
- [x] DateInputs

## Environment

Package versions:

```
v1.4.3
```

Browser:

- Any mobile browser

**Comment by ggkrustev** [comment]
*Some additional comments:*
In general, all modern mobile devices will benefit of such behavior. Basically, most users want to separate typing in the input from picking smth, which is not possible with the current focus management of the component.

**Comment by ggkrustev** [comment]
Done in latest official releases of DateInputs and DropDowns packages.
