### ISSUE TITLE
grid height is not working with pagination

### ISSUE THREAD

**Issue by joerg-bergner** [telerik/kendo-angular#1254]
## I'm submitting a...
  * Regression report 

## Current behavior
  * Giving grid a height by using: `[height]=500` works for the grid wrapper but pagination is not at the bottom of grid component

## Expected behavior
  * pagination should be at the bottom of component

## Minimal reproduction of the problem with instructions
See here: https://plnkr.co/edit/P31jccS50E7K3oIWFsS5?p=preview

## What is the motivation or use case for changing the behavior?
Using grid component like always.

## Environment
grid: v1.7.1

**Comment by tsvetomir** [comment]
Should be fixed in 1.7.2, the site is still on 1.7.1

**Comment by joerg-bergner** [comment]
Thank you. It works.
