### ISSUE TITLE
Grid reordering and grouping issue when right-click occurs during dragging

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1257]
The drag element freezes where the right-click occurred. Observable in the online demos:

[https://www.telerik.com/kendo-angular-ui/components/grid/columns/reordering/](https://www.telerik.com/kendo-angular-ui/components/grid/columns/reordering/)

Same goes for grouping:

[https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/grouping/grouping/](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/grouping/grouping/)

**Comment by ipeshev** [comment]
It is enough to just right-click and hover draggable element to reproduce it.

**Comment by ipeshev** [comment]
Fixed in the [dev build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-grid` package **v3.10.0-dev.201811151126**.

**Comment by dtopalov** [comment]
Reopening this as it is observable in the online demos again.

**Comment by dtopalov** [comment]
Also reported in private support thread - Ticket ID: 1382535

**Comment by ipeshev** [comment]
Can't observe it with latest grid version.
