### ISSUE TITLE
Grid Filtermenu's messages localizeable

### ISSUE THREAD

**Issue by Zaixu** [telerik/kendo-angular#1259]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Currently the FilterMenuComponent hardcodes the 'And' and 'Or' texts. While the rest of the GridComponent utilizes localizable messages.

## Expected behavior
'And' and 'Or' of the filtermenu's in Grid to be localizeable. So it correlates with the rest of the texts of the grid.

## Minimal reproduction of the problem with instructions
Looked in source, since i18n did not have it.

## What is the motivation or use case for changing the behavior?
Since the grid is localizable, theese text should be too.

**Comment by rkonstantinov** [comment]
Thanks for the report. We have addressed this limitation and the texts in question should be localizeable using the [latest dev channel version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `kendo-angular-grid` package.
