### ISSUE TITLE
Changelog not up to date

### ISSUE THREAD

**Issue by kferstl** [telerik/kendo-angular#1261]
The changelog is weeks behind the actual release. 

e.g.
https://www.telerik.com/kendo-angular-ui/components/dateinputs/changelog/
currently on version  v1.4.3 (2018-01-05)
available version: v1.4.5

This often results in poor quality control as there is no reference to what has been changed and frequent bugs due to changes in the APIs.

**Comment by tsvetomir** [comment]
Changelogs are currently published during site updates. The next update is scheduled in a few days.

We're considering ways to improve the changelog publication process. Closing this issue in favor of #974

**Comment by tsvetomir** [comment]
Totally forgot about or [development snapshot](https://www.telerik.com/kendo-angular-ui-develop/components/) of the site. You can see all the latest changelogs there for the moment.
