### ISSUE TITLE
Dropdown reset/patch value doesn't work

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#1268]
Hey, 
I found a bug when trying to clear the value of the dropdownlist.

If I call the reset or patchValue method of the formGroup, the value (model) changed, but the selected item in the dropdownlist (ui / html) is not reseted.

Plunkr: 
https://plnkr.co/edit/ShcXLfASZdx0qqu9hFFQ?p=preview

**Comment by ipeshev** [comment]
Fixed in  v2.1.0-dev.201802271249

**Comment by tsvetomir** [comment]
Released in v2.1.0
