### ISSUE TITLE
npm warning rxjs@^5 <5.5

### ISSUE THREAD

**Issue by acohenOT** [telerik/kendo-angular#1270]
Since updating to rxjs 5.5.6, this warning is displayed when running "npm update --save" on a Kendo application

npm WARN @progress/kendo-angular-buttons@2.0.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-dateinputs@1.4.5 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-dialog@2.1.0 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-dropdowns@1.6.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-grid@1.8.0 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-inputs@1.5.0 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-layout@1.2.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-popup@1.3.4 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-treeview@1.1.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-upload@2.1.2 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.

## Environment

Package versions:
+-- @angular/animations@5.2.2
+-- @angular/cli@1.6.6
+-- @angular/common@5.2.2
+-- @angular/compiler@5.2.2
+-- @angular/compiler-cli@5.2.2
+-- @angular/core@5.2.2
+-- @angular/forms@5.2.2
+-- @angular/http@5.2.2
+-- @angular/language-service@5.2.2
+-- @angular/platform-browser@5.2.2
+-- @angular/platform-browser-dynamic@5.2.2
+-- @angular/router@5.2.2
+-- @progress/kendo-angular-buttons@2.0.1
+-- @progress/kendo-angular-dateinputs@1.4.5
+-- @progress/kendo-angular-dialog@2.1.0
+-- @progress/kendo-angular-dropdowns@1.6.1
+-- @progress/kendo-angular-excel-export@1.0.5
+-- @progress/kendo-angular-grid@1.8.0
+-- @progress/kendo-angular-inputs@1.5.0
+-- @progress/kendo-angular-intl@1.3.0
+-- @progress/kendo-angular-l10n@1.0.5
+-- @progress/kendo-angular-label@1.0.5
+-- @progress/kendo-angular-layout@1.2.1
+-- @progress/kendo-angular-popup@1.3.4
+-- @progress/kendo-angular-scrollview@1.0.7
+-- @progress/kendo-angular-sortable@1.0.5
+-- @progress/kendo-angular-treeview@1.1.1
+-- @progress/kendo-angular-upload@2.1.2
+-- @progress/kendo-data-query@1.1.2
+-- @progress/kendo-drawing@1.4.1
+-- @progress/kendo-theme-default@2.47.2
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.96
+-- codelyzer@4.1.0
+-- core-js@2.5.3
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.4.1
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- UNMET PEER DEPENDENCY rxjs@5.5.6
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.4.2
+-- web-animations-js@2.3.1
`-- zone.js@0.8.20

npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-buttons@2.0.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dateinputs@1.4.5
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dialog@2.1.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dropdowns@1.6.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-grid@1.8.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-inputs@1.5.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-layout@1.2.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-popup@1.3.4
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-treeview@1.1.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-upload@2.1.2
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-buttons@2.0.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dateinputs@1.4.5
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dialog@2.1.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dropdowns@1.6.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-grid@1.8.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-inputs@1.5.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-layout@1.2.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-popup@1.3.4
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-treeview@1.1.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-upload@2.1.2
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-buttons@2.0.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dateinputs@1.4.5
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dialog@2.1.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dropdowns@1.6.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-grid@1.8.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-inputs@1.5.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-layout@1.2.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-popup@1.3.4
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-treeview@1.1.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-upload@2.1.2
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-buttons@2.0.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dateinputs@1.4.5
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dialog@2.1.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-dropdowns@1.6.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-grid@1.8.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-inputs@1.5.0
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-layout@1.2.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-popup@1.3.4
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-treeview@1.1.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-upload@2.1.2
npm ERR! missing: hawk@3.1.3, required by node-pre-gyp@0.6.39
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.6.39
npm ERR! missing: rimraf@2.6.1, required by node-pre-gyp@0.6.39
npm ERR! missing: tar@2.2.1, required by node-pre-gyp@0.6.39
npm ERR! missing: boom@2.10.1, required by hawk@3.1.3
npm ERR! missing: cryptiles@2.0.5, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by hawk@3.1.3
npm ERR! missing: sntp@1.0.9, required by hawk@3.1.3
npm ERR! missing: hoek@2.16.3, required by boom@2.10.1
npm ERR! missing: boom@2.10.1, required by cryptiles@2.0.5
npm ERR! missing: hoek@2.16.3, required by sntp@1.0.9
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.0
npm ERR! missing: readable-stream@2.2.9, required by are-we-there-yet@1.1.4
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: combined-stream@1.0.5, required by request@2.81.0
npm ERR! missing: hawk@3.1.3, required by request@2.81.0
npm ERR! missing: mime-types@2.1.15, required by request@2.81.0
npm ERR! missing: safe-buffer@5.0.1, required by request@2.81.0
npm ERR! missing: delayed-stream@1.0.0, required by combined-stream@1.0.5
npm ERR! missing: combined-stream@1.0.5, required by form-data@2.1.4
npm ERR! missing: mime-types@2.1.15, required by form-data@2.1.4
npm ERR! missing: extsprintf@1.0.2, required by jsprim@1.4.0
npm ERR! missing: extsprintf@1.0.2, required by verror@1.3.6
npm ERR! missing: mime-db@1.27.0, required by mime-types@2.1.15
npm ERR! missing: safe-buffer@5.0.1, required by tunnel-agent@0.6.0
npm ERR! missing: glob@7.1.2, required by rimraf@2.6.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.1.2
npm ERR! missing: inflight@1.0.6, required by glob@7.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: brace-expansion@1.1.7, required by minimatch@3.0.4
npm ERR! missing: balanced-match@0.4.2, required by brace-expansion@1.1.7
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.7
npm ERR! missing: block-stream@0.0.9, required by tar@2.2.1
npm ERR! missing: fstream@1.0.11, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by tar@2.2.1
npm ERR! missing: inherits@2.0.3, required by block-stream@0.0.9
npm ERR! missing: graceful-fs@4.1.11, required by fstream@1.0.11
npm ERR! missing: inherits@2.0.3, required by fstream@1.0.11
npm ERR! missing: mkdirp@0.5.1, required by fstream@1.0.11
npm ERR! missing: rimraf@2.6.1, required by fstream@1.0.11
npm ERR! missing: fstream@1.0.11, required by tar-pack@3.4.0
npm ERR! missing: once@1.4.0, required by tar-pack@3.4.0
npm ERR! missing: readable-stream@2.2.9, required by tar-pack@3.4.0
npm ERR! missing: rimraf@2.6.1, required by tar-pack@3.4.0
npm ERR! missing: tar@2.2.1, required by tar-pack@3.4.0
npm ERR! missing: fstream@1.0.11, required by fstream-ignore@1.0.5
npm ERR! missing: inherits@2.0.3, required by fstream-ignore@1.0.5
npm ERR! missing: minimatch@3.0.4, required by fstream-ignore@1.0.5
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: buffer-shims@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: core-util-is@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.2.9
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.2.9
npm ERR! missing: process-nextick-args@1.0.7, required by readable-stream@2.2.9
npm ERR! missing: string_decoder@1.0.1, required by readable-stream@2.2.9
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.2.9
npm ERR! missing: safe-buffer@5.0.1, required by string_decoder@1.0.1
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-popup@1.3.4
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-popup@1.3.4
npm ERR! peer dep missing: rxjs@^5 <5.5, required by @progress/kendo-angular-popup@1.3.4

System:
- TypeScript version: 1.0.3.0
- Node version: v8.9.3; NPM version 5.6.0
- Platform:  Windows

**Comment by tsvetomir** [comment]
We identified [some compatibility issues](https://github.com/telerik/kendo-angular/issues/1244) with RxJS 5.5 and updated all packages to address them. You need to update your project to the latest Kendo package versions if you're using rxjs 5.5+

**Comment by acohenOT** [comment]
I've updated my Kendo project today using these commands, I still get the same warnings on npm install. Is there some other way to update to the latest Kendo packages?

npm update --global
npm update --save
npm update --save-dev
npm install
npm WARN @progress/kendo-angular-buttons@2.0.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-dateinputs@1.4.5 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-dialog@2.1.0 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-dropdowns@1.6.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-grid@1.8.0 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-inputs@1.5.0 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-layout@1.2.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-popup@1.3.4 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-treeview@1.1.1 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-upload@2.1.2 requires a peer of rxjs@^5 <5.5 but none is installed. You must install peer dependencies yourself.

**Comment by acohenOT** [comment]
Never mind. I updated my package.json using ncu (npm-check-updates)

**Comment by tpronschinske** [comment]
Is there a list somewhere that show the Package Versions that Work with 5.5 and rxjs?
