### ISSUE TITLE
Sparkline charts do not respect the crosshair.visible option for horizontal axes

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1271]
Vertical crosshair is visible on hover:

`public defaultConfig = {
      crosshair: {
        visible: false
      }
    };`

[https://plnkr.co/edit/rRl2lgiyZvcAOPPWYYkf?p=preview](https://plnkr.co/edit/rRl2lgiyZvcAOPPWYYkf?p=preview)

Both horizontal and vertical crosshairs are visible (expected):

`public defaultConfig = {
      crosshair: {
        visible: true
      }
    };`

[https://plnkr.co/edit/RhBBAck8O8yNYDDiDLII?p=preview](https://plnkr.co/edit/RhBBAck8O8yNYDDiDLII?p=preview)

Using horizontal axis settings individually does not help hiding the vertical crosshair either.

**Comment by danielkaradachki** [comment]
The sparkline has visible crossahair by default for the categoryAxis and the option should be set to the categoryAxis in order for the default to be overridden:
https://plnkr.co/edit/NZaYIMRgLt8QTZhMwdGp?p=preview
