### ISSUE TITLE
Splitter: collapsed two-way binding or CollapsedChanged event

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1273]
## I'm submitting a...
* Suggestion for improvement

## What is the motivation or use case for changing the behavior?
* I would like to save (on server for example) in what collapsed state user leaved splitter pane.
* I would like to control collapsed state from code. Current the only option is to do it without `[collapsible]="true"`, because there is no way I can track if user changed collapsed property in UI.

I suggest two-way binding for [collapsed property](https://www.telerik.com/kendo-angular-ui-develop/components/layout/api/SplitterPaneComponent/#toc-collapsed).  
If for some reason this is not possible, I suggest adding event `CollapsedChange`.

Same is done for [size property](https://www.telerik.com/kendo-angular-ui-develop/components/layout/api/SplitterPaneComponent/#toc-size) as described [here](https://www.telerik.com/kendo-angular-ui-develop/components/layout/splitter/panes/#toc-persisting-the-size).

**Comment by gyoshev** [comment]
This functionality has been released on the development channel, version `v2.1.0-dev.201802151013`.

**Comment by MaklaCof** [comment]
@gyoshev 
Can I ask what was released. 2-way binding, event or both? I check documentation on DEVELOP channel but not find that information.

**Comment by gyoshev** [comment]
@MaklaCof both, because two-way binding is implemented through an event :slightly_smiling_face: In Angular, two-way binding is available for the property `propName` when there's a `@Output() public propNameChange` event emitter.

This is documented in the [SplitterPaneComponent API page](https://www.telerik.com/kendo-angular-ui-develop/components/layout/api/SplitterPaneComponent/#toc-collapsedchange).

**Comment by Kevat** [comment]
When will this functionality be available on the main channel? Is there a workaround for using that functionality with the current stable release? How can I bind to the collapsed event without using a development build?

**Comment by gyoshev** [comment]
@Kevat version `2.1.0` of the package has just been released, and includes the above functionality.
