### ISSUE TITLE
Dragging Kendo Window fails with a type error: t.kendo.release.do is not a function

### ISSUE THREAD

**Issue by msalmank** [telerik/kendo-angular#1278]
## I'm submitting a...
* Bug report

## Current behavior
Kendo Window renders correctly but when you click on it to drag it, it cannot be dragged. Version: 3.0.0 of @progress/kendo-angular-dialog

## Expected behavior
The window should allow the user to drag it across the screen.

## Minimal reproduction of the problem with instructions
  1. Open this [plunk](https://plnkr.co/edit/i73HmbNOigmLPhKektRK?p=preview).
  2. Run the code and Drag the window.Open it in Plunker by using the **OPEN AS PLUNKER** button.
  3. Observe the Browser Dev Tools for the error.

## Environment

Package versions:
Broken since v3.0.0

**Comment by ipeshev** [comment]
Thank you for the bug report @msalmank !

**Comment by RamonMueller** [comment]
Resizing also no longer works properly.

**Comment by tsvetomir** [comment]
A fix will be available in the next patch release. Workaround is to include the global "do" operator:

```
import 'rxjs/add/operator/do';
```

**Comment by msalmank** [comment]
Confirmed as fixed with the latest release. Thanks.
