### ISSUE TITLE
TreeView shows expandable folder when item is null/undefined

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#1282]
## I'm submitting a...
* Bug report 

## Current behavior
When  I use the treeview and I have the following data I would like to bind then the treeview shows the open tile for each items array what is undefined or null.

when I let my backend system create a complete Tree I don't have the possiblity to not generate the items property.

      public data: any[] = [
        {
            text: "Furniture", items: [
                { text: "Tables & Chairs",  items : undefined  },
                { text: "Sofas",  items : undefined  },
                { text: "Occasional Furniture", items : undefined }
            ]
        },
        {
            text: "Decor", items: [
                { text: "Bed Linen",  items : undefined  },
                { text: "Curtains & Blinds",  items : undefined  },
                { text: "Carpets",  items : undefined  }
            ]
        }
      ];

## Expected behavior

when the items list is empty/null/undefined then there should be no open symbol

![image](https://user-images.githubusercontent.com/1572878/35691195-1d09ae08-0778-11e8-88ac-89b02f61755a.png)

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/Y6fuAmP6EfrfWS3csWEq?p=preview

## What is the motivation or use case for changing the behavior?
when you generate your tree from your backend and you have a TreeItem which contains a TreeItem for recursion, then the "items" property is allways there in every entry it can be null or empty list or undefined but I can't remove it from the TreeItem.

Cool would be that empty List or null would not generate the open icon

**Comment by ggkrustev** [comment]
Hi @squadwuschel, thanks for logging the bug report. Indeed, the component does show the expand icon even for the nodes without children items. We are aware of this limitation and a fix was pushed in the dev branch. Please give a try to the latest DEV version - v2.1.1-dev.201802020837

**Comment by squadwuschel** [comment]
works, when you set the item to null it works. With empty item it shows the expand icon.
