### ISSUE TITLE
k-alt applied to wrong rows on grid component

### ISSUE THREAD

**Issue by jmaronge** [telerik/kendo-angular#1283]
## I'm submitting a...

* Bug report 

## Current behavior

The k-alt class is applied to the wrong rows.  The first row should never be the "alt" row.  This is true of just about all other grids out there including the Kendo JQuery one.  It appears the error is in the isOdd function for the tr elements. 

`    public isOdd(item: any): boolean {
        return item.index % 2 === 0;
    }
`

The first row is 0 based causing it to start as the k-alt row.  If you inspect the first two rows in the [JQuery version ](https://demos.telerik.com/kendo-ui/grid/index)you will see it is done correctly.  

## Expected behavior

Only odd number rows should be marked with k-alt class.
`    public isOdd(item: any): boolean {
        return item.index % 2;
    }
`

## Minimal reproduction of the problem with instructions

https://run.plnkr.co/NOEx9l2f2vESzEMj/

**Comment by rkonstantinov** [comment]
Thanks for the report. We managed to address the issue in question and the fix is available in the latest [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version of `kendo-angular-grid` package.

**Comment by ipeshev** [comment]
Fixed in v2.0.2-dev.201802021006
