### ISSUE TITLE
maskedinput maskValidation not working without form

### ISSUE THREAD

**Issue by nm-a** [telerik/kendo-angular#1291]
## I'm submitting a...
* Bug report

## Current behavior
maskValidation not working without form

https://plnkr.co/edit/CAJYjKGsuwgaqQkXY8ha

## Expected behavior
work with form & without form

## Minimal reproduction of the problem with instructions
Please refer the plunker link
https://plnkr.co/edit/CAJYjKGsuwgaqQkXY8ha

**Comment by rusev** [comment]
Indeed your observations are correct. The [maskValidation](https://www.telerik.com/kendo-angular-ui/components/inputs/api/MaskedTextBoxComponent/#toc-maskvalidation) property has meaning only in when the component is used inside Angular form.

**Comment by nm-a** [comment]
Thank you, is there any alternative / api to validate mask input value without form?

thank you
-nm

**Comment by rusev** [comment]
Input validation is useful in the context of form. 

Of course you can use the component `value`, `mask` etc. to execute logic for validation, but the component will not change its state.
