### ISSUE TITLE
Buttons break Angular AoT compilation with the '--fullTemplateTypeCheck' option

### ISSUE THREAD

**Issue by alexeikostevich** [telerik/kendo-angular#1292]
## I'm submitting a...

* Bug report 

## Current behavior

An Angular application cannot be compiled in the AoT mode with the [--fullTemplateTypeCheck](https://angular.io/guide/aot-compiler#fulltemplatetypecheck) option if [Kendo UI for Angular Buttons](https://www.telerik.com/kendo-angular-ui/components/buttons/button/) are used.

```
ERROR in node_modules/@progress/kendo-angular-buttons/dist/es/splitbutton/splitbutton.component.d.ts.SplitButtonComponent.html(35,17): : Property 'keyDownHandler' is protected and only accessible within class 'ListButton' and its subclasses.
node_modules/@progress/kendo-angular-buttons/dist/es/splitbutton/splitbutton.component.d.ts.SplitButtonComponent.html(36,17): : Property 'keyPressHandler' is protected and only accessible within class 'ListButton' and its subclasses.
node_modules/@progress/kendo-angular-buttons/dist/es/splitbutton/splitbutton.component.d.ts.SplitButtonComponent.html(37,17): : Property 'keyUpHandler' is protectedand only accessible within class 'ListButton' and its subclasses.
node_modules/@progress/kendo-angular-buttons/dist/es/dropdownbutton/dropdownbutton.component.d.ts.DropDownButtonComponent.html(28,17): : Property 'keyDownHandler' is protected and only accessible within class 'ListButton' and its subclasses.
node_modules/@progress/kendo-angular-buttons/dist/es/dropdownbutton/dropdownbutton.component.d.ts.DropDownButtonComponent.html(29,17): : Property 'keyPressHandler' is protected and only accessible within class 'ListButton' and its subclasses.
node_modules/@progress/kendo-angular-buttons/dist/es/dropdownbutton/dropdownbutton.component.d.ts.DropDownButtonComponent.html(30,17): : Property 'keyUpHandler' is protected and only accessible within class 'ListButton' and its subclasses.
```

## Expected behavior

The application is successfully compiled in the AoT mode with the [--fullTemplateTypeCheck](https://angular.io/guide/aot-compiler#fulltemplatetypecheck) option if [Kendo UI for Angular Buttons](https://www.telerik.com/kendo-angular-ui/components/buttons/button/) are used.

## Environment

Package versions:

```
├── @angular/animations@5.2.3
├── @angular/cli@1.6.7
├── @angular/common@5.2.3
├── @angular/compiler@5.2.3
├── @angular/compiler-cli@5.2.3
├── @angular/core@5.2.3
├── @angular/forms@5.2.3
├── @angular/http@5.2.3
├── @angular/language-service@5.2.3
├── @angular/platform-browser@5.2.3
├── @angular/platform-browser-dynamic@5.2.3
├── @angular/router@5.2.3
├── @progress/kendo-angular-buttons@3.0.1
├── @progress/kendo-angular-charts@2.0.0
├── @progress/kendo-angular-dropdowns@2.0.0
├── @progress/kendo-angular-intl@1.3.0
├── @progress/kendo-angular-l10n@1.0.5
├── @progress/kendo-drawing@1.4.2
├── @progress/kendo-theme-default@2.47.2
```

System:
- TypeScript version: 2.6.2
- Node version: 8.9.3 (npm 5.6.0)
- Platform:  Mac

The [fullTemplateTypeCheck](https://angular.io/guide/aot-compiler#fulltemplatetypecheck) compiler option was introduced in Angular 5.2: https://blog.angular.io/angular-5-2-now-available-312d1099bd81

**Comment by alexeikostevich** [comment]
Please, pay attention that the same issue can be also reproducible with other Kendo packages. I apologize for not being able to verify them now.

**Comment by rkonstantinov** [comment]
Thanks for the report. We managed to address the issue in question. The latest version of buttons package should contain the fix.

**Comment by alexeikostevich** [comment]
Thank you for addressing this so quickly! The Kendo team is just awesome.
