### ISSUE TITLE
theme-default > splitbar: vars not marked as "default"

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#1293]
## I'm submitting a...

* Bug report 

## Current behavior

Trying to set the background color of splitbar component using an scss variable has no effect.

```
// example-styles.scss
$splitter-bg: transparent;
@import "~@progress/kendo-theme-default/scss/all";
```

$splitter-bg will be ignored.

## Expected behavior

$splitter-bg should be used as background color for splitbar in generated css file.

It works as expected, if I add "!default" in kendo-theme-default/scss/splitter/_theme.scss.

CURRENT (not working)
```
@include exports("splitter/theme") {

    $splitter-bg: rgba( try-darken( $panel-bg, 8 ), .8 );
    $splitter-text: $panel-text;
```

WORING
```
@include exports("splitter/theme") {

    $splitter-bg: rgba( try-darken( $panel-bg, 8 ), .8 ) ! default;
    $splitter-text: $panel-text ! default;
```

## Environment

Package versions:

```
  "name": "@progress/kendo-theme-default",
  "description": "SASS resources for the default Kendo UI theme",
  "version": "2.47.2",
```

**Comment by gyoshev** [comment]
Thank you for reporting this, it has been fixed in `@progress/kendo-theme-default@2.47.6`
