### ISSUE TITLE
Grid multiple selection by clicking on the rows bug

### ISSUE THREAD

**Issue by anagram92** [telerik/kendo-angular#1294]
When you select multiple rows by clicking on them instead on the checkbox, the css doesn't show the multiple selection but only a single row.

https://plnkr.co/edit/qy91u9cuithpfRISmIAT?p=info

**Comment by DanielHirschTpg** [comment]
seems to work as intended. you have to use CTRL + clicking a row to apply more then one selection over rows. using SHIFT will select a range of rows.

**Comment by Raisolution** [comment]
I can confirm that the current behavior is expected. Please let us know if we are missing something here.

**Comment by anagram92** [comment]
My bad, thanks
