### ISSUE TITLE
option element selection triggers a cellClick event in IE

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1297]
When selecting an option from a select element within an ng-template with a kendoGridEditTemplate directive, IE throws a click event, which triggers the (cellClick) event of the grid. Check the following sample plunker demonstrating the issue in IE:

[https://plnkr.co/edit/nJKgER6Y3qCNJXCIuJBF?p=preview](https://plnkr.co/edit/nJKgER6Y3qCNJXCIuJBF?p=preview)

As a workaround, we could check in the (cellClick) event handler if it fired a different rowIndex and prevent the call of this.editHandler when not needed. Please check the following sample plunker demonstrating this approach:

[https://plnkr.co/edit/kzihLeCF4CwT1g5rrsh3?p=preview](https://plnkr.co/edit/kzihLeCF4CwT1g5rrsh3?p=preview)

**Comment by ipeshev** [comment]
Shipped
