### ISSUE TITLE
DropDowns do not fire selectionChange event after the value is reset and the same selection is made

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1298]
The erroneous behavior is observable in the following Plunker:

[https://plnkr.co/edit/pmFFwEoTQzDxBkFxdoNz?p=preview](https://plnkr.co/edit/pmFFwEoTQzDxBkFxdoNz?p=preview)

**Reproduction steps:**
- manually change the droplist value
- click "reset form"
- manually change the droplist value
    changing the value to the same value from step 1 erroneously results in the (selectionChange) method 
    not being called
    changing the value to any other value correctly results in the (selectionChange) method being called

Internal reference: Reported in Ticket ID: 1152417 and Ticket ID: 1152406

**Comment by wohral** [comment]
have same problem.

**Comment by tsvetomir** [comment]
Try testing with the dev version:
`npm install @progress/kendo-angular-dropdowns@dev`

**Comment by ipeshev** [comment]
Fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
