### ISSUE TITLE
TreeViewComponent nodeClick event

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#1299]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

It seems that there's no easy way to get informend when a user clicks a tree node. 

## Expected behavior

A TreeViewComponent > nodeClick event that fires everytime a user clicks a node.

## What is the motivation or use case for changing the behavior?

This event would allow us to implement a context menu as described in documentation for the grid component: https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/context-menu/

**Comment by ggkrustev** [comment]
The available `selectionChange` event behaves exactly like a `nodeClick` would. It will be raised once the user clicks the node. Would that be sufficient to accomplish your goal?
- https://www.telerik.com/kendo-angular-ui/components/treeview/api/TreeViewComponent/#toc-selectionchange

**Comment by cluetjen** [comment]
Hi @ggkrustev, thanks for your suggesting but that seems not to work...

tree.selectionChange - what I expected: It gets called when selection changes. That means, if I click the same node multiple times, I would expect, that selectionChange fires only the first time. (selection does not change, its the same node...)

tree.selectionChange - what happens: It fires for every click on a node, even if the selection does NOT change. BUT... it does not fire on mouse right click - only left clicks. (tested right now with @progress/kendo-angular-grid@^1.7.1)

grid.cellClick: gets called when the user does a right or left click on a grid cell.

So I thought I cannot use it because of the multiple clicks on the same node but it turns out that I cannot use it because it's not fired for context menu clicks.

**Comment by danielkaradachki** [comment]
Available in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version.

https://stackblitz.com/edit/angular-rsk776?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Available in 2.3.0

**Comment by markzolotoy** [comment]
Is it possible to intercept a click and see whether the CTRL was pressed?
