### ISSUE TITLE
Add columnMenu configuration setting

### ISSUE THREAD

**Issue by j-pdx** [telerik/kendo-angular#1301]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
The grid currently doesn't provide an option to add/remove columns via a column menu.

## Expected behavior
A column menu like the jQuery control has: https://demos.telerik.com/kendo-ui/grid/column-menu

**Comment by rkonstantinov** [comment]
Hi @j-pdx,
This repository is for reporting bugs with the product. If you wish to suggest a feature please visit [our uservoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback?_ga=2.45045668.1038340948.1517815113-193260906.1483424128).
