### ISSUE TITLE
wrong pristine status of the DropDownList

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1302]
Opening and closing the DropDownList without changing the selection changes the "pristine" value of the form control from "true" to "false".

Check the following sample plunker demonstrating the issue:

[https://plnkr.co/edit/wbBuIT8SAiBHjKpFpCBI?p=preview](https://plnkr.co/edit/wbBuIT8SAiBHjKpFpCBI?p=preview)

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
