### ISSUE TITLE
Error when try to move column to lock column

### ISSUE THREAD

**Issue by diegobs2** [telerik/kendo-angular#1303]
## I'm submitting a ...
* Bug report 

## Current behavior

i used a locked grid with reorderable columns and when i took the reorderable column over locked column, it stay bad.

## Minimal reproduction of the problem with instructions

Image with the error

![image](https://user-images.githubusercontent.com/25430580/36029788-e9920e16-0da4-11e8-939e-6b026d475d87.png)

Browser:

- Chrome (desktop) latest version

System:
- TypeScript version: 2.7.1
- Node version: 5.6.0
- Platform: Windows

**Comment by rusev** [comment]
Can you verify whether the error message in the browser console is similar to the following:
>Uncaught TypeError: n.draggable.drag.takeUntil is not a function

This error is caused by the migration to the new [rxjs](https://github.com/telerik/kendo-angular/issues/1244). We will address this error. Other than that I'm not seeing any other issues.

**Comment by diegobs2** [comment]
Its correct, the error displayed is 

`Uncaught TypeError: e.draggable.drag.takeUntil is not a function`

No other issues, thanks!

**Comment by rusev** [comment]
The fix is available in the [latest dev build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). You can give it a try.

**Comment by ipeshev** [comment]
Shipped with v2.1.0
