### ISSUE TITLE
Kendo Gauge Component does not compile with AOT

### ISSUE THREAD

**Issue by drjofu** [telerik/kendo-angular#1304]
## I'm submitting a...
* Bug report 

## Current behavior
New project with current version of ng-cli 
included Kendo-Gauge-Component as from sample 
works with ng serve (without AOT)
 fails with ng build --prod:

ERROR in : Unexpected value '**GaugesModule** in ...node_modules/@progress/kendo-angular-gauges/dist/es/gauges.module.d.ts' imported by the module 'AppModule Please add a @NgModule annotation.

## Expected behavior
should compile with AOT

System:
Angular CLI: 1.6.5
Node: 6.10.0
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

**Comment by rkonstantinov** [comment]
Thanks for the report. We will address this with the next release of the package.

**Comment by tsvetomir** [comment]
Fixed in v1.0.2 of the package
