### ISSUE TITLE
Bootstrap theme: Input groups not working with Bootstrap 4.0.0

### ISSUE THREAD

**Issue by ngreniermajor** [telerik/kendo-angular#1305]
Bug report: Input groups are not displayed correctly when using the bootstrap theme and Bootstrap v4.0.0

## Current behavior
The input group addons, are shown on a different line.  Moreover, they are not styled correctly.  

See in demo page: https://www.telerik.com/kendo-angular-ui/components/forms/integration-with-bootstrap/#toc-using-with-input-groups

## Expected behavior
Input groups should be style according to Bootstrap's input groups. I edited the second control of the plunker so that it shows the expected behavior.

## Minimal reproduction of the problem with instructions
See plunker: https://plnkr.co/edit/gHTvDt5eCHfTss28qLmg?p=preview

## Environment
Package versions:
+-- @&#8203;angular/animations@5.2.4
+-- @&#8203;angular/cli@1.6.5
+-- @&#8203;angular/common@5.2.4
+-- @&#8203;angular/compiler@5.2.4
+-- @&#8203;angular/compiler-cli@5.2.4
+-- @&#8203;angular/core@5.2.4
+-- @&#8203;angular/forms@5.2.4
+-- @&#8203;angular/http@5.2.4
+-- @&#8203;angular/language-service@5.2.4
+-- @&#8203;angular/platform-browser@5.2.4
+-- @&#8203;angular/platform-browser-dynamic@5.2.4
+-- @&#8203;angular/platform-server@5.2.4
+-- @&#8203;angular/router@5.2.4
+-- @&#8203;ng-bootstrap/ng-bootstrap@1.0.0
+-- @&#8203;ngrx/store@5.0.0
+-- @&#8203;ngx-translate/core@9.1.1
+-- @&#8203;ngx-translate/http-loader@2.0.1
+-- @&#8203;progress/kendo-angular-dateinputs@2.0.1
+-- @&#8203;progress/kendo-angular-dropdowns@2.0.0
+-- @&#8203;progress/kendo-angular-excel-export@1.0.5
+-- @&#8203;progress/kendo-angular-grid@2.0.1
+-- @&#8203;progress/kendo-angular-inputs@2.0.0
+-- @&#8203;progress/kendo-angular-intl@1.3.0
+-- @&#8203;progress/kendo-angular-l10n@1.0.5
+-- @&#8203;progress/kendo-angular-upload@3.0.1
+-- @&#8203;progress/kendo-data-query@1.1.2
+-- @&#8203;progress/kendo-drawing@1.4.2
+-- @&#8203;progress/kendo-theme-bootstrap@2.11.5
+-- @&#8203;types/jasmine@2.8.6
+-- @&#8203;types/jasminewd2@2.0.3
+-- @&#8203;types/jquery@3.3.0
+-- @&#8203;types/node@6.0.97
+-- bluebird@3.5.1
+-- bootstrap@4.0.0
+-- cldr-data@31.0.3
+-- codelyzer@4.1.0
+-- core-js@2.5.3
+-- font-awesome@4.7.0
+-- http-server@0.10.0
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.3.1
+-- json-loader@0.5.7
+-- karma@2.0.0
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.4.1
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- lodash@4.17.5
+-- mkdirp@0.5.1
+-- ngx-toastr@8.2.0
+-- UNMET PEER DEPENDENCY popper.js@^1.12.9
+-- protractor@5.1.2
+-- reselect@3.0.1
+-- rimraf@2.6.2
+-- rxjs@5.5.6
+-- tether@1.4.3
+-- ts-node@4.1.0
+-- tslint@5.9.1
+-- typescript@2.5.3
+-- uuid@3.2.1

Browser:
- Chrome (desktop) version 63.0.3239.132
- Firefox version 58.0.1

System:
- TypeScript version: 2.5.3
- Node version: node 8.2.1 - npm 5.3.0
- Platform:  Windows

**Comment by gyoshev** [comment]
A fix for this has been released on the development channel of the theme (version `2.12.0-dev.0fcc32fe`), and the demos are pending for upload. You can see both in action on the [development staging site](https://www.telerik.com/kendo-angular-ui-develop/components/forms/integration-with-bootstrap/).

**Comment by gyoshev** [comment]
Fix officially released, here's the [updated plunker](https://plnkr.co/edit/spGGCFo282ODDH2S3D9Z?p=preview).
