### ISSUE TITLE
Binding the grid to a GridDataResult breaks filter menu filter state restoring in filter menu components

### ISSUE THREAD

**Issue by JackD111** [telerik/kendo-angular#1306]
## I'm submitting a...

* Bug report 

## Current behavior
After applying a filter, the filter gets applied to the grid data properly. When pressing the filter menu button again, the filter doesn't apply the current set filters to the filter menu component

## Expected behavior
After applying the filter and then opening the filter menu again, the filter state should be restored properly to the filter menu components and showing the last filtered values and their operators

## Minimal reproduction of the problem with instructions

Plunker is based on the "External Form" demo since that's one I found that binds the data to an Observable<GridDataResult>. Only change from the demo is that the "filterable" property was added and set to "menu":
https://plnkr.co/edit/RKbiQRrYydsyxrbFqWWs?p=preview

## Environment

Browser:

- Chrome (desktop) version 63.0.3239.132

System:
- TypeScript version: 2.5.3
- Platform: Windows

**Comment by rkonstantinov** [comment]
In the sample, the filter menu does not show the selected filter, as the [`filter`](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-filter) setting is not bound to the `gridState` field, as it is done with the skip, pageSize and sort. Adding the following line in the Grid declaration will fix the issue:

```html
 <kendo-grid
          [filter]="gridState.filter"
          filterable="menu"
          .....
        >
```
Additional information can be found in [the documentation](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#toc-getting-started).
