### ISSUE TITLE
Can't validate inputs in kendoGridDetailTemplate

### ISSUE THREAD

**Issue by mak633** [telerik/kendo-angular#1310]
Hello. I have an issue. I'm using Reactive forms for editing grid and I have a logic for edit values in Detail Row Template. 
This example for my form group 
```
this.formGroup = new FormGroup({
  'id': new FormControl(dataItem.id, Validators.required),
  .....
  'mailingAddress': new FormGroup({
  'address1': new FormControl(dataItem.mailingAddress.address1, Validators.required),
  .....
})
```
And I tried to use this variant, but I can't disable button when form is invalid. 
```
<ng-template kendoGridDetailTemplate let-dataItem let-rowIndex="rowIndex">
   <input [(ngModel)]="dataItem.mailingAddress.address1" name="address2" class="k-textbox"/>
</ng-template>
```
When I tried to use "formControlName" or "[formControl]" in input I had an errors.

**Comment by destus90** [comment]
@mak633 
try this
```
<ng-template kendoGridDetailTemplate let-dataItem let-rowIndex="rowIndex">
   <div [formGroup]="formGroup">
       <input formControlName="address1" class="k-textbox"/>
   </div>
</ng-template>
```

**Comment by mak633** [comment]
@destus90  
ERROR Error: Cannot find control with name: 'address1'  and ERROR TypeError: Cannot read property 'address1' of undefined. I have this control in nested form group
When I add formControlName 
```
<div [formGroup]="formGroup">
   <label formGroupName="mailingAddress" class="k-form-field col-4" >
      <span>Address1</span>
      <input formControlName="address1" name="address1" class="k-textbox" />
  </label>
</div>
```
I get only one ERROR TypeError: Cannot read property 'address1' of undefined . I have problem with pre field this input now.

**Comment by mak633** [comment]
Can you close this issue. I found a mistake.
