### ISSUE TITLE
[Grid] Reusable Custom Filter for Menu

### ISSUE THREAD

**Issue by tipag** [telerik/kendo-angular#1312]
## I'm submitting a...
  * Feature request
  * Bug report

## Current behavior
It is not possible to filter for more than one value with the BaseFilterCellComponent base class, since the updateFilter method only takes a FilterDescriptor. Also there are no events for click on "filter button" and "clear button".

## Expected behavior
I would like to be able to create resuable custom menu filters where I can nest multiple filters with both "and" and "or" logic as well as events for the buttons. Ideally I would like a new base class for creating reusable custom menu filters (BaseMenuFilterCellComponent).

## What is the motivation or use case for changing the behavior?
I'd like to easily create reusable custom menu filters, where I can filter for multiple values like the default filters do.

I know that I can hack around by using operator functions an so on to achieve that, since I have already done so, but I would like to finally have a clean solution, and some feedback from any person related to telerik concerning the issues I have with implementing custom menu filters.

I already opened a similar issue about a month ago with no response here: #1238, which is part of this one and would be resolved at the same time.

**Comment by rkonstantinov** [comment]
As the name suggests, the `BaseFilterCellComponent` is intended to be used with filter cell template and not directly used with filter menu. Also this base class does indeed support adding multiple filters via the applyFilter method, as it provides access to the root filter composite descriptor allowing to modify it as one wishes.

When using filter menu, there is no need to use the `BaseFilterCellComponent`. The template can host any custom component. The only requirement for grid integration is to set the filter descriptor for the column field via provided by the template filterService instance. This will also activate the 'filter' and 'clear' buttons.
 
To demonstrate this I have extracted [custom filter menu example](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/built-in-template/#toc-customizing-filter-menus) as custom component:

https://plnkr.co/edit/MiyXoWRdszfE79j2FDJM?p=preview

**Comment by tipag** [comment]
Thanks, for your answer I applied your solution to my code and it works!

I already had tried the exact same thing, with only one difference, I injected the filterService in my custom filter's constructor. However, in that case it was filtering instantly after I called filterService.filter which wasn't a satisfactory solution.
