### ISSUE TITLE
MultiSelect does not show dropdown after click on placeholder text

### ISSUE THREAD

**Issue by Chris380** [telerik/kendo-angular#1313]
## I'm submitting a...

* Bug report 

## Current behavior
When I deselect all items of a kendo-multiselect a click on the placeholder text does not open the dropdown.
Focussing the input control again or clicking next to the placeholder opens the dropdown as expected.

## Expected behavior
After deleting all items a click on the placeholder should open the dropdown

## Minimal reproduction of the problem with instructions

1. open https://plnkr.co/edit/ImJ8P59fmxIrLGGErnU9?p=preview
2. deselect "baseball"
3. click on placeholder ("Bitte wählen")

**Comment by valchev** [comment]
Related to #1219

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://github.com/telerik/kendo-angular-dropdowns/releases/tag/v3.0.3-dev.201808011119).

**Comment by tsvetomir** [comment]
Shipped in v3.0.3
