### ISSUE TITLE
Dialog - minHeight, maxHeight support

### ISSUE THREAD

**Issue by luka-robnik** [telerik/kendo-angular#1315]
## I'm submitting a...
  * Feature requests
  * Suggestion for improvement

## Current behavior
No support for minHeight, maxHeight properties like jQuery version.
Only height property is available which displays scrollbar if dialog content is dynamic and changes after dialog is shown (in case when then is more content than i predict). if property is not set than it is immediately resized when content is changed which is sometimes annoying.

## Expected behavior
set minHeight when I open a dialog, because content is dynamic and i want that dialog is initiality at some min height so no resize happens. If there is more content than i predict dialog is automatically resized.
set maxHeight to prevent the dialog is to big if lots of content is added (scrollbar is shown)

it would be great if Dialog control supports minHeight, maxHeight properties like jQuery version

**Comment by siyka-marinova** [comment]
This feature is now available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `@progress/kendo-angular-dialog` package

**Comment by siyka-marinova** [comment]
The feature is now also available in `kendo-angular-dialog v4.1.1`
