### ISSUE TITLE
There is any method available for filter Grid data in Kendo UI Angular 4 version.

### ISSUE THREAD

**Issue by nick412** [telerik/kendo-angular#1316]
Hello @rkonstantinov ,

So I Have a scenario like below.

![image](https://user-images.githubusercontent.com/32121809/36259941-e25925fe-1285-11e8-9590-6e05e0462d20.png)

Where I have using Kendo UI Virtual Scroll to load over 10k Records which have simple object like {id: number, name: string} now I have a separate search box to filter grid data.

So, is there any way to filter grid data dynamically there is only one field now talking to my full picture like I have custom drag and drop component where single + multiple(with ctrl key + select & shift key + select) data can drag drop from left hand side list to right hand side area and the search area is not part of that drag drop component it is outer entity of that component so now If I search something using outer entity and pass to the component I need to filter Grid Data dynamically because any task perform on 10k+ data is highly costly ,time consuming as well as it degrade performance as well.

So Please Try to resolve this issue ASAP It is an humble request.

**Comment by rkonstantinov** [comment]
Hi @nick412,
This repository is for reporting issue with the components. For general support questions, please [open a support ticket via our ticketing system](https://www.telerik.com/account/support-tickets).

**Comment by nick412** [comment]
Hello @rkonstantinov ,

Agree this repository is for reporting issue with the components. I am also reporting same thing with Kendo UI Grid Part that we don't have any feature to filter grid Data if there any Please suggest me same.

Thank You,
Nicks.

**Comment by nick412** [comment]
Hello @rkonstantinov,

I am facing a bug in Kendo UI editable grid where I am using multiple editable grids within one page where I Found that If one grid is in edit mode the other grid can't be editable it is throwing an error.

I have a Tabular structure on my page where each tab hold it's corresponding grid where If I go in one tab try to edit a row grid but I am not going to save that I leave it as it is in edit mode now I am going to another tab and try to edit another grid it will throw an error. I think it is a bug when we are going to use multiple editable grids within a grid.

So, @rkonstantinov I think it is a bug please look into it or if there is some method to close the edit mode when I am going to leave that tab. is there any such method with kendo UI editable grid.?

**Comment by nick412** [comment]
Please refer this link also it will help you to understand this well. @rkonstantinov 

https://drive.google.com/file/d/1wxCy86oncmCxyE_qDzWNkkMeTrcRN5jX/view

**Comment by rkonstantinov** [comment]
@nick412, could you please open a new issue and fill-in the issue template as well as providing a simplified plunker in which the issue can be observed locally.
