### ISSUE TITLE
 Is there any opportunity to implement automatically "Go to the next(prev) page"-functionality from kendo's box for grid  by clicking on the custom buttons ?

### ISSUE THREAD

**Issue by juve23** [telerik/kendo-angular#1318]
Hi, guys !
Have a question about customization of pager component.
Need to create own custom buttons for paging. Is there any opportunity to implement automatically "Go to the next(prev) page"-functionality from kendo's box by clicking on the custom buttons ?

Have the next template of pager:
```
<ng-template kendoPagerTemplate let-totalPages="totalPages" let-currentPage="currentPage">
          <button kendoButton [look]="'bare'" [primary]="true" class="pager-left-nav">
            <kendo-pager-prev-buttons></kendo-pager-prev-buttons>
            <span>Prev</span>
          </button>
          <kendo-pager-input></kendo-pager-input>
          <button kendoButton  [look]="'bare'" [primary]="true" class="pager-right-nav">
            <span>Next</span>
            <kendo-pager-next-buttons></kendo-pager-next-buttons>
          </button>
</ng-template>
```
Tried to go by adding for custom button event-handler for click:

```
          <button kendoButton (click)="currentPage !== 1 ? changePage(currentPage - 2) : false" [look]="'bare'" [primary]="true" class="font-weight-bold pager-left-nav">
            <kendo-pager-prev-buttons></kendo-pager-prev-buttons>
            <span>Prev</span>
          </button>
```
But don't see opportunity to fire method changePage() of pager for corresponding instance of grid...

## Current behavior
As I can see, "Go to the next(prev) page" takes place when user clicks on link(button) generated by kendo-pager-prev-buttons (or kendo-pager-next-button) component.

## What is the motivation or use case for changing the behavior?
Creating own custom buttons for pager-component.

Thank you !

**Comment by rusev** [comment]
The issue tracker is intended for reporting bugs or suggestions for improvement. For such questions you can open [Support request](https://www.telerik.com/account/support-tickets).
