### ISSUE TITLE
intl, CldrIntlService: inconsistent behavior between formatNumber(), formatDate() and format()

### ISSUE THREAD

**Issue by Btruckses** [telerik/kendo-angular#1319]
## Current behavior
I create an instance of a **CldrIntService** with a given locale, e.g.:
````
import '@progress/kendo-angular-intl/locales/de/all';
(...)
public deIntl: CldrIntlService = new CldrIntlService('de');
````

Now I format a number via **deIntl.formatNumber()** and **deIntl.format()**, both without formating instructions, and I get different results (the same for dates, see Plunk below).
When adding format instructions, the numbers and dates will be formated correctly.

```
export class AppComponent {
  public date: Date = new Date();
  public numVal: number = 10000.023;
  public deIntl: CldrIntlService = new CldrIntlService('de');
    
  public out1: string;
  public out2: string;
  public out3: string;

  constructor(public intl: IntlService) {
    this.out1 = this.deIntl.formatNumber(this.numVal); // -> 10.000,023
    this.out2 = this.deIntl.format('{0}', this.numVal); // -> 10000.023
    this.out3 = this.deIntl.format('{0:n}', this.numVal); // -> 10.000,023
  }
}
```

## Expected behavior
**format()** should produce the same output for numbers and dates as **formatNumber()** and/or **formatDate()** when no formating instructions are given. 

## Minimal reproduction of the problem with instructions

See the following plunk: [https://plnkr.co/edit/U1rc874GBCE6jeg5etKq?p=preview](https://plnkr.co/edit/U1rc874GBCE6jeg5etKq?p=preview)

**Comment by danielkaradachki** [comment]
The behavior is by design. format will just replace the placeholder with the value if no format is specified. This allows using both formatted and not formatted values in the same format.
