### ISSUE TITLE
404 no such package available : @progress/kendo-angular-treeview

### ISSUE THREAD

**Issue by mgraves247** [telerik/kendo-angular#1320]
When trying to install the Kendo UI treeview control I am getting the following error in NPM....

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "@progress/kendo-angular-treeview"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 no such package available : @progress/kendo-angular-treeview
npm ERR! 404
npm ERR! 404  '@progress/kendo-angular-treeview' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by ggkrustev** [comment]
@mgraves247, could it be that you are using our old private repo that is now retired? More details about the issue and the possible fixes could be found in this thread:
- https://github.com/telerik/kendo-angular/issues/712

If this is not the case, could you post a repro demo which replicates the issue? **Please fill in the whole ticket template that is shown on initial ticket submission**. This information is important to us and help us to determine the issue faster.
