### ISSUE TITLE
Manual column reordering

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1322]
When trying to implement our own column reorder on (columnReorder) event, the columns do not re-render as the event handler is executed outside the Angular zone:

A sample plunker demonstrating the issue:

[https://plnkr.co/edit/59TEpqMQhiEgRuJTpaYd?p=preview](https://plnkr.co/edit/59TEpqMQhiEgRuJTpaYd?p=preview)

and here is a sample plunker demonstrating a workaround:

[https://plnkr.co/edit/QdyuNdsIVWCkO3Q5SAB2?p=preview](https://plnkr.co/edit/QdyuNdsIVWCkO3Q5SAB2?p=preview)

**Comment by rusev** [comment]
The fix is available in the [latest development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds).

**Comment by tsvetomir** [comment]
Fixed in v2.1.1
