### ISSUE TITLE
DatePicker Weekday Issue

### ISSUE THREAD

**Issue by maiktiedtke** [telerik/kendo-angular#1326]
## Bug report
The day number is not shown in the correct column

     [weekNumber]="true"
     [min]="min"
     [max]="max">

    public min: Date = new Date(2018,1,28);
    public max: Date = new Date(2018,2,3);
## Current behavior

![image](https://user-images.githubusercontent.com/20223518/36478364-b825502c-1704-11e8-84cc-d1dccda1b59d.png)

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/W9l4RhFFaFM0SQ6JuIgw?p=preview

## Environment

Browser:

- Chrome (desktop) version 60.0.3112.101

**Comment by ggkrustev** [comment]
I will close the thread as the described scenario is expected. Please elaborate on the issue, if I am missing something.
