### ISSUE TITLE
How to change the culture programmatically

### ISSUE THREAD

**Issue by anagram92** [telerik/kendo-angular#1327]
Hi,

I might be missing something here so I ask, what is the way to change the language of the messages from the components programmatically or is this example the only way?

https://plnkr.co/edit/XSbiMDBHQX6SopebwKOi?p=preview

Basically, I have an application where after the user logs in, I need to change the language/culture to the one he had selected previously (this value comes from the database and he can change through a dropdown). I would like to be able to have a solution where I call a function, pass the value as a string (eg "en-us") and it changes automatically.

**Comment by tsvetomir** [comment]
You can supply dynamic translations using a [Message Service](https://www.telerik.com/kendo-angular-ui/components/localization/messages/#toc-using-the-message-service).

It's probably best to use the Angular DI system to configure the provided service with the current user culture.

**Comment by tsvetomir** [comment]
Please check out the new [Updating Messages Dynamically](https://www.telerik.com/kendo-angular-ui/components/localization/messages/#toc-updating-messages-dynamically) help topic.
