### ISSUE TITLE
Combobox suggest feature not working, when filterable="true"

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#1328]
## I'm submitting a...

* Bug report 

## Current behavior

The ComboBox suggestion feature isnt working, when using filterable="true".

## Expected behavior

It should work even with filtered ComboBox.

## Minimal reproduction of the problem with instructions
- Open [Plunker](https://plnkr.co/edit/7jOofRlh4bHfPMHVNZ2U?p=preview)
- Type 'A' into the first ComboBox and it will suggest ' Albania' (everything OK!)
- Now type 'A' into the second ComboBox (with filterable="true") and get no suggestion.  :(

Browser:

- tested on Chrome (Desktop) 64.0.3282.167

**Comment by valchev** [comment]
@simon11196 thanks for bringing this to our attention.
I will investigate the case further and provide a fix as soon as possible.

**Comment by valchev** [comment]
The issue occurs because the data is not actually filtered.

In order to resolve the scenario, the developer should update the `listItems` on `filterChange` according to the filter text entered by the user. Here is a working example:

https://stackblitz.com/edit/kendo-issue-1328
