### ISSUE TITLE
AutoComplete "textField" support like Combobox

### ISSUE THREAD

**Issue by DanielHirschTpg** [telerik/kendo-angular#1329]
Hello,

I'm struggling with using the AutoComplete component with complex objects for data. The data is a list of "user" objects, having an id property and a name. Since the bound data is a complex object I have to use the "valueField" property and set the to the property of the user name. The problem is now that users with the same name can exist and I'll not be able to associate the user name with the user id of the picked user when retrieving the value of the component.

Having checked the source code of the component I've also seen that the "valueField" will be used in the "kendo-list" component of the popup for both the "textField" and "valueField" property. Having a "textField" for the AutoComplete component would make it possible to change the binding of the "textField" property of the "kendo-list" component to the new AutoComplete "textField" property for better complex objects support without having to use the "kendoAutoCompleteItemTemplate" directive

Sadly, without "textField" support for complex object I can't use the component.

**Comment by valchev** [comment]
Hi @DanielHirschTpg 

The AutoComplete component is designed to operate with a single primitive value. For the scenario that you described, I suggest to use the ComboBox (single value) or MultiSelect (multiple values) component.

**Comment by DanielHirschTpg** [comment]
Thank you, I see. I'll go with the combobox component then.
