### ISSUE TITLE
Buttons :: CSS class inconsistency for buttons with icon 

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#1330]
## I'm submitting a...

* Bug report 
* Suggestion for improvement

## Current behavior

There is some inconsistency in css classes for buttons with icons:

Icon Type | Has text | Css class
|---|---|---|
Kendo UI | No |  `.k-button.k-button-icon`
Kendo UI | Yes | `.k-button.k-button-icontext`
Fontawesome | No | `.k-button`
Fontawesome | Yes | `.k-button`
Image | No | `.k-button`
Image | Yes | `.k-button`

`.k-button-icon` & `.k-button-icontext` are missing for non Kendo UI iconed buttons.

## Expected behavior

Buttons have `.k-button-icon` & `.k-button-icontext` no matter which icon type they use.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/Z75p7pl6H0qeiExnm7nZ?p=preview

## What is the motivation or use case for changing the behavior?

I need to style the icon if no there is no text in the button and my app use Fontawesome icons.

## Environment

Package versions:

```
@progress/kendo-angular-buttons@3.0.3
```

**Comment by ilianiv** [comment]
Hi,
I've checked the latest version of buttons module and still cannot select buttons with fontawesome icon and text. And they look stacked 😢 for me
![image](https://user-images.githubusercontent.com/3925630/37143554-29ca1684-22c4-11e8-9582-73fa34508092.png)

**Comment by gyoshev** [comment]
The classes have been added in the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), `@progress/kendo-angular-buttons@v4.0.0-dev.201803231552`. This package requires `v1.1.0` or above of the `@progress/kendo-angular-l10n package`, and will be released as `4.0.0`.

**Comment by tsvetomir** [comment]
Fix released in v4.0.0
