### ISSUE TITLE
Unexpected result of Grid column reordering in RTL mode

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1331]
When the RTL mode is enabled and a Grid column is reordered and dropped between two other columns, the dragged column ends up to the left of these columns (instead of between them where the indicator is):

1. Drag "Name" column 

2. Drop between "Price" column to "In stock"  column.

The "Name" column show to the left of "In stock"  column.:

[https://plnkr.co/edit/sZxjpP7HZWCU8y0d947R?p=preview](https://plnkr.co/edit/sZxjpP7HZWCU8y0d947R?p=preview)

**Comment by ipeshev** [comment]
Fix available in [latest dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version.

**Comment by danielkaradachki** [comment]
Released in 3.10.0
https://stackblitz.com/edit/angular-wmarci?file=app%2Fapp.component.ts
