### ISSUE TITLE
How to open kendo-dropdownlist/kendo-combobox on focus

### ISSUE THREAD

**Issue by kanji-keraliya** [telerik/kendo-angular#1333]
Can you please suggest best way to open kendo-dropdownlist/kendo-combobox on focus.
I want to open dropdown when cursor focus on control.
I tried using Directive handle focus event HostListener but problem is when user click on control its close and open when user reclick
here is my code

```
import { Directive, ElementRef, HostListener, Input } from '@angular/core';
import { DropDownListComponent } from '@progress/kendo-angular-dropdowns';

@Directive({ selector: '[pponf]' })
export class PPOnF {
    element: any;
    constructor(el: DropDownListComponent) {
     this.element=el;
    }
    @HostListener('focus') onMouseEnter() {
      this.element.toggle(true);
    }
}
```

can you please help/suggest best way to solve this.
Thanks

**Comment by nm-a** [comment]
try this
`
@ViewChild("inputControlDropdownlist") public inputControlDropdownlist: DropDownListComponent;

public onDropdownlistFocus() {
        if (this.inputControlDropdownlist != null
            && this.inputControlDropdownlist != undefined) {
            setTimeout(() => {
                if (!this.inputControlDropdownlist.isOpen) {
                    this.inputControlDropdownlist.toggle(true);
                }
            }, 200);
        }
    }
`

**Comment by kanji-keraliya** [comment]
@nm-a  Thanks. your solution work for me

```
import { Directive, ElementRef, HostListener, Input } from '@angular/core';
import { DropDownListComponent } from '@progress/kendo-angular-dropdowns';

@Directive({ selector: '[pponf]' })
export class PPOnF {
    element: DropDownListComponent;
    constructor(el: DropDownListComponent) {
        try {
            this.element = el;
        } catch (e) {
            console.error(e);
        }
    }
    @HostListener('focus') onMouseEnter() {
        try {
            if (this.element) {
                setTimeout(() => {
                    if (!this.element.isOpen) {
                        this.element.toggle(true);
                    }
                }, 100);
            }
        } catch (e) {
            console.error(e);
        }
    }
}
```
but there is some issue in Kendo control. some time its not close after lost focus

**Comment by tsvetomir** [comment]
Please note that this issue tracker is only for bug reports. Questions regarding implementation scenarios are better suited for our support system, forums or StackOverflow.
