### ISSUE TITLE
Localization - Pager and No Data template

### ISSUE THREAD

**Issue by DominicSachs** [telerik/kendo-angular#1334]
If I change the localization (we us ngx-translate) certain parts of the grid won't be localized. The pager and the "No Data" text still have the same initial language. Is there a way to change this text if the locale has changed. We use the MessageService for Kendo-Localization.

I read that post: https://github.com/telerik/kendo-angular/issues/362
Is there another way, without wrapping the grid in a component?

**Comment by tsvetomir** [comment]
This issue tracker is for bug reports only.

Please, submit a support ticket with more details regarding your project.

**Comment by zhengyanghuaer** [comment]
Have you resolved this question? I also meet the same question, and i have no idea. Can you help me with this question?Thanks a lot.

**Comment by tsvetomir** [comment]
@zhengyanghuaer Please, file a bug report and share a runnable example, if possible.
