### ISSUE TITLE
"Binding to Remote Data" documentation-example-fix 

### ISSUE THREAD

**Issue by theredpea** [telerik/kendo-angular#1335]
## I'm submitting a...
* Documentation issue or request
https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/data-binding/#toc-binding-to-remote-data

## Current behavior
https://plnkr.co/edit/asbJP64UMdQR3xgEtpHl?p=preview
ERROR TypeError: products.pipe is not a function
    at b.eval [as _next] (run.plnkr.co/OvAfCCDcLgc0UMzY/app/app.component.ts!transpiled:55)

that's true; line 50 in app.component.ts ; products is not an Observable; it is an array

                    this.queryChildItems(item.CategoryID)
                        .subscribe(products => {
                            data.children = products.pipe(map(product => {

## Expected behavior
https://plnkr.co/edit/Tf5go90BEew9b48UZDMc?p=preview

So I just used `products.map(...)` instead

**Comment by tsvetomir** [comment]
Thanks! Fixed and will go live with the next site update.
