### ISSUE TITLE
[Window] Action bar not working on Safari iOS

### ISSUE THREAD

**Issue by Felx-B** [telerik/kendo-angular#1337]
## I'm submitting a...

* Bug report 

## Current behavior

Window default actions (minimize/maximize/close) not working on touch on Safari iOS 
The window is not closed on touching close button in action bar.

## Expected behavior

The window should close on touching close button in action bar

## Minimal reproduction of the problem with instructions

1. [Open basic usage on Kendo documentation](https://www.telerik.com/kendo-angular-ui/components/dialogs/window/#toc-basic-usage) on Safari iOS
2. Click on the close button (x) in action bar
3. The window does not close

## Environment

Browser:
- Safari (iOS) version 11.2.5

**Comment by Raisolution** [comment]
Hi @Felx-B,

Thank you for reporting this. We have addressed the issue and the fix will be available in the next dev release.

**Comment by Raisolution** [comment]
The fix is available in v3.2.0

**Comment by Felx-B** [comment]
Nice, thank you !
