### ISSUE TITLE
When exporting a grid to PDF, the chart is not included in the exported file.

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1338]
When exporting a grid to PDF and the grid has a chart in the detail template, the chart is not added to the exported PDF file.

Check the following sample plunker demonstrating the reported issue:
[https://plnkr.co/edit/clJ74omp05tRZQzcLI3q?p=preview](https://plnkr.co/edit/clJ74omp05tRZQzcLI3q?p=preview)

**Comment by tsvetomir** [comment]
Works as expected with the latest versions, [see example](https://stackblitz.com/edit/angular-hvnqus?file=app%2Fapp.component.ts).

**Comment by danielkaradachki** [comment]
Still doesn't work with paging and allPages:

**Comment by Crossfir3** [comment]
:heavy_check_mark: Tested OK on the dev version of the grid. No issues were spotted.

**Comment by Raisolution** [comment]
Provided through the new `delay` pdf export option in `v5.3.0`.
