### ISSUE TITLE
Grid - Multi selection does not work properly after reorder column - regression

### ISSUE THREAD

**Issue by jacekbartek** [telerik/kendo-angular#1339]
## I'm submitting a...
* Regression report

## Current behavior
Problem #1276 was fixed in kendo-angular-grid 2.0.1 version but still exists after upgrade to 2.1.0 version.
In short:  
2.0.1, 2.0.2 works
2.1.0 does not work

## Expected behavior
Problem #1276 should be fixed in future releases.

## Minimal reproduction of the problem with instructions
#1276 

## Environment

Package versions:
    "kendo-angular-buttons": "3.0.3",
    "kendo-angular-dateinputs": "2.1.1",
    "kendo-angular-dialog": "3.1.2",
    "kendo-angular-dropdowns": "2.0.2",
    "kendo-angular-excel-export": "1.0.6",
    "kendo-angular-grid": "2.1.0",
    "kendo-angular-inputs": "2.1.1",
    "kendo-angular-intl": "1.3.1",
    "kendo-angular-l10n": "1.0.6",
    "kendo-angular-layout": "2.0.1",
    "kendo-data-query": "1.2.0",
    "kendo-drawing": "1.5.1",
    "kendo-theme-default": "2.48.1",
    "kendo-ui": "2018.1.221",

Browser:
- Chrome (desktop) Version 64.0.3282.186 (Official Build) (64-bit)

System:
- TypeScript version: 2.6.1
- Node version: node: v6.11.3, npm: 3.10.10
- Platform:  Windows 10 64bit

**Comment by jacekbartek** [comment]
Hi, 
 is there any chance, to verify this notification ? 

Regards

**Comment by tsvetomir** [comment]
Thanks for the heads-up, on it.

**Comment by tsvetomir** [comment]
Fixed in v2.1.2

**Comment by jacekbartek** [comment]
Works, thanks.
