### ISSUE TITLE
Kendo UI for Angular Project Templates

### ISSUE THREAD

**Issue by espenloeke** [telerik/kendo-angular#1340]
## I'm submitting a...

* Bug report 

## Current behavior
I have installed "Kendo UI for Angular Project Templates" (https://marketplace.visualstudio.com/items?itemName=TelerikInc.KendoAngularExtensions) in Visual Studio 2017.

When trying to create a new project using this template in Visual Studio 2017 I get the following error message: "This project template requires Visual Studio 2017 v.15.3 or later"

I have Visual Studio Community v.15.5.7 installed.

Second, is this a product that will be updated and supported in the future?

## Expected behavior
New project created 

## Minimal reproduction of the problem with instructions
Install Visual Studio Community v.15.5.7. Install template https://marketplace.visualstudio.com/items?itemName=TelerikInc.KendoAngularExtensions

Try to create a new project using the template.

## Environment

Package versions:
Not relevant.```

```

Browser:
Not relevant.
System: Windows 10

<!-- Add any additional information that might be relevant. -->

**Comment by espenloeke** [comment]
Thanks for reply!

 

I am using VS 2017 community. Its a VS Solution containing 2 projects. One project for REST webservices using .NET Core 2.0 and one Angular project.

 

Not really sure what you mean by .NET Core workload…

 

Fra: Boyan Dimitrov [mailto:notifications@github.com] 
Sendt: tirsdag 6. mars 2018 09.42
Til: telerik/kendo-angular <kendo-angular@noreply.github.com>
Kopi: espenloeke <espen.loeke@gmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [telerik/kendo-angular] Kendo UI for Angular Project Templates (#1340)

 

Hi @espenloeke <https://github.com/espenloeke>  ,

We performed various tests against Visual Studio 2017 15.5.7 including Enterprise, Professional and Community editions. They all worked just fine and no errors were thrown. Could you please confirm whether you are using Preview and whether there is .NET Core 2.0 workload in your Visual Studio?

Also a screenshot of the error will be very helpful.

**Comment by andrewgpl** [comment]
Same problem here. I'm using VS2017 15.6.2 Enterprise edition. Windows 7. .NET Core 2.0 is in place.

**Comment by boyandim** [comment]
Thank you all for the provided feedback. We managed to replicate the problem locally and we are working on fixing it. As soon as it is done I will provide information here.

**Comment by boyandim** [comment]
The problem should be resolved now. By default VS 2017 will update the extensions automatically as soon as a new version is released in the marketplace. In case that the automatic updated is disabled with your VS instance please update the extension manually.

**Comment by espenloeke** [comment]
Hey,

I just signed the petition "The Norwegian government: Let us change the
CPS!" and wanted to see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/pvWnkFksgv

Thanks!
Espen
