### ISSUE TITLE
Grid: Filter popup has double border with bootstrap theme

### ISSUE THREAD

**Issue by stefan-schweiger** [telerik/kendo-angular#1341]
## I'm submitting a...

* Bug report

## Current behavior
Because the border is applied to .k-popup and that class is applied to both the wrapper and the form there are two borders.

<img width="796" alt="screenshot 2018-02-27 00 50 16" src="https://user-images.githubusercontent.com/3532342/36702741-a18e5afe-1b58-11e8-9b98-d6cf22f25535.PNG">

## Expected behavior
The filter popup should not have a double border.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/pMURMIkADF30p452TnyE?p=preview

## What is the motivation or use case for changing the behavior?
To look better and be more consistent with other themes.

## Environment

Package versions:
bootstrap@4.0.0
@progress/kendo-theme-bootstrap@latest

Browser:
Chrome 64 (probably every other browser too)

**Comment by stefan-schweiger** [comment]
Removing the set `margin` from `.k-popup` and set `padding: 0;` fixes the issue.

So the right "custom bootstrap" style should be:

.k-popup {
    border-radius: .125rem 0 0;
    padding: 0;
}

<img width="297" alt="screenshot 2018-03-02 14 15 18" src="https://user-images.githubusercontent.com/3532342/36900622-4ca41366-1e24-11e8-8af3-49812014de4d.PNG"><img width="350" alt="screenshot 2018-03-02 14 15 08" src="https://user-images.githubusercontent.com/3532342/36900618-49f66484-1e24-11e8-9bfe-7dc015da502f.PNG">

**Comment by tsvetomir** [comment]
Fixed in `@progress/kendo-angular-grid` v3.2.0+
