### ISSUE TITLE
Bug: splitter min for last panel is not obeyed

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1344]
## I'm submitting a...
* Bug report 

## Current behavior
If I sett min property for last panel, that min is applied to previous pane, not the last.

## Expected behavior
Min is applied to last pane, not before last.

## Minimal reproduction of the problem with instructions
Run [this plunkr](https://plnkr.co/edit/eIhbeu79C4PLQ8HyRAbB?p=preview).
![2018-02-27_12-11-21](https://user-images.githubusercontent.com/1589573/36725723-7c48d8be-1bb7-11e8-910b-eb6349a8d29c.gif)

**Comment by gyoshev** [comment]
The issue has been fixed in version `2.1.1`. Here is the [updated plunker](https://plnkr.co/edit/gZ73ehVvnQNwJDLtskPR?p=preview).
