### ISSUE TITLE
Grid - Different checkbox design for Edit and Selection features 

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#1345]
## I'm submitting a...
  * Suggestion for improvment 

## Current behavior
Checkboxes in Edit and Selection features have not the same design.

## Expected behavior
Same design for both checkboxes.

## Minimal reproduction of the problem with instructions
The editing sample with selection feature activated : https://plnkr.co/edit/8jqrZJhDZcgjT5YjBgCL?p=preview

## What is the motivation or use case for changing the behavior?
Harmony with the design.

## Environment
Same package as sample

**Comment by inikolova** [comment]
@ChrisProlls I am glad to inform you that this enhancement has been already implemented - it is available in Kendo UI Grid for angular version 4.8.4
