### ISSUE TITLE
Failed unit test: "No provider for NgControl"

### ISSUE THREAD

**Issue by mak633** [telerik/kendo-angular#1346]
I have unit test coverage. My grid has edit mode with Reactive form. And I have problem at this line 

```
<ng-template kendoGridEditTemplate let-formGroup="formGroup">
          <div class="form-check form-check-inline">
            <input type="radio" name="idType" class="k-radio" [value]=0 [formControl]="formGroup.get('idType')">
            <label class="k-radio-label" for="userId">User ID</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="radio" name="idType" class="k-radio" [value]=1 [formControl]="formGroup.get('idType')">
            <label class="k-radio-label" for="name">User name</label>
          </div>
          <input type="text" class="k-textbox" maxlength="100" [formControl]="formGroup.get('id')" />
      </ng-template>
```
Failed: Template parse errors:
No provider for NgControl

I have a similar page, but there test run without errors. The main difference that I have template-driven form above my grid.

**Comment by DanielHirschTpg** [comment]
This is an issue in your testing code and not the product itself. Are you using Angulars TestBed? If so, have you setup the providers in the testing module correctly?

**Comment by ggkrustev** [comment]
Closing the thread as it does not report nor a bug or suggests an improvement. If it is a bug, please fill in the issue template providing the whole required information.
