### ISSUE TITLE
Introduce a visual indicator for filtered columns in the Grid

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1348]
Currently when the filtering mode is "row", there is no visual indicator that the Grid data is filtered by some field in the respective column (like the one, available in the Filter menu mode).

Introducing such will be useful especially in scenarios where some column(s) is filtered using the IsNull, IsNotNull, IsEmpty or IsNotEmpty operators.

The suggested temporary workaround is a custom implementation, similar to the following:

[https://plnkr.co/edit/NVdhqXoGLQPvGiwwvKPo?p=preview ](https://plnkr.co/edit/NVdhqXoGLQPvGiwwvKPo?p=preview )

**Comment by joerglang** [comment]
I suggest that if someone selects the "isnull" or "isempty" operator, that the operator text (in brackets) is shown in the filter text field. Then it is obvious what filter is active and the "remove filter" button would be shown.

**Comment by Raisolution** [comment]
By design the 'visual indicator' that a filter is applied in Row Filter Mode is the appearance of the 'Clear Filter' icon. If further visual indication is needed, we recommend using a `kendoGridFilterCellTemplate`.
