### ISSUE TITLE
[AutoComplete] Popup does not display on first click in input on Android

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1349]
## I'm submitting a...

* Bug report 

## Current behavior

Popup is showed only after second click in input 

## Expected behavior
Popup should be showed always.

## Minimal reproduction of the problem with instructions
1. Open official [autocomplete demo](https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/autocomplete/) in Android device
2. Click in input and type a letter(no popup).
3. Blur input and then click again in input ( popup is showed )

## Environment

Package versions:

```
broken since v2.1.0-dev.201802271249
```

Browser:

- Chrome (Android) version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by KristofGilis** [comment]
We have the same problem with our app, but there is something strange with it. When the search inside the autocomplete starts with a number, the autocomplete popup is working correctly.

When we search with a letter (ex. a) it doesn't open directly, if we enter a space the popup opens with saying "no data found", when we delete the space the popup opens with the correct search results.

I took the official example plnkr of the Autocomplete filtering and added an extra element to the array, starting with a 1.

On a desktop this works exactly how I expect it, on mobile (Android/Chrome) I got the result I mentioned above.
Here is my plnkr: [https://plnkr.co/peyiZRe57hG45lGEO7kW](https://plnkr.co/peyiZRe57hG45lGEO7kW)

**Comment by dimitar-pechev** [comment]
Related to #1958.

**Comment by dimitar-pechev** [comment]
Fixed in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.2-dev.201903141745**.

**Comment by tsvetomir** [comment]
Shipped in v3.5.2
