### ISSUE TITLE
Drag and drop for Treeview

### ISSUE THREAD

**Issue by harg** [telerik/kendo-angular#1350]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
Treeview component does not support drag and drop

## Expected behavior
Will you support drag and drop for the treeview component in a near future?
JQuery implementation  #https://demos.telerik.com/kendo-ui/treeview/dragdrop

**Comment by ggkrustev** [comment]
@harg, thanks a lot for the suggestion. Indeed, drag&drop will be a beneficial enhancement.

Right now it is under consideration and depends mostly on the votes that users cast for it in our UserVoice portal. That being said, I will close the thread and will move interested parties to the specific UserVoice discussion The benefit is that all different posts/cross-posts will be pointed and concentrated in one thread, which will help to increase the priority of the desired enhancement.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/33369232-drag-drop-for-treeview-component
