### ISSUE TITLE
TabStripComponent should have possibility to prevent changing its tab in Observable manner

### ISSUE THREAD

**Issue by maciej-bielecki** [telerik/kendo-angular#1351]
## I'm submitting a...

* Suggestion for improvement
* Asking for possible solution

## Current behavior
Hi there,

kendo-tabstrip component  (TabStripComponent) offers tabSelect event with SelectEvent argument which can cancel changing tab :  event.preventDefault();

This works fine, but, in case we need to ask user (for example after some validation) if he is sure of changing tab, how can we .preventDefault() determined of users choise?

Dialog result subscription is an Observable so there is no point of using event.preventDefault() inside .subscibe()

## Expected behavior
I expects that tab selection would be observable friendy, or there will be any way to wait for user choise.

## Minimal reproduction of the problem with instructions
I've prepared small plnkr that shows the problem https://embed.plnkr.co/ebFp58VO9NjxSn0HkKX0/

## Environment

Package versions:
"kendo-angular-buttons": "3.0.3",
"kendo-angular-dateinputs": "2.1.1",
"kendo-angular-dialog": "3.1.2",
"kendo-angular-dropdowns": "2.0.2",
"kendo-angular-excel-export": "1.0.6",
"kendo-angular-grid": "2.1.0",
"kendo-angular-inputs": "2.1.1",
"kendo-angular-intl": "1.3.1",
"kendo-angular-l10n": "1.0.6",
"kendo-angular-layout": "2.0.1",
"kendo-data-query": "1.2.0",
"kendo-drawing": "1.5.1",
"kendo-theme-default": "2.48.1",
"kendo-ui": "2018.1.221",

Browser:

Chrome (desktop) Version 64.0.3282.186 (Official Build) (64-bit)
System:

TypeScript version: 2.6.1
Node version: node: v6.11.3, npm: 3.10.10
Platform: Windows 10 64bit

**Comment by Raisolution** [comment]
Hi @maciej-bielecki,

a possible solution would be to prevent the `tabSelect` event before showing the Dialog and then programatically select the tab depending on the DialogResult. Here is a [possible implementation](https://plnkr.co/edit/hvmyK0sB42TUS9XSBWjR?p=preview), that you could extend if needed.

**Comment by maciej-bielecki** [comment]
Thanks for quick response. I've figured out similiar solution - it seams like there is no other option, but still - workaround based on some blocking / awaitable for dialog result would suit better.
In my app I have another mechanism that executes tabStrip.selectTab and also showing dialog is conditional - mixing it with this flag solution isn't really best idea.

**Comment by tsvetomir** [comment]
I don't see how an observable would improve the existing solution. 

Such feature would mean that the Tabstrip would not change tabs unless the developer wires up the tabSelect event in order to emit from the "confirmation" observable.
