### ISSUE TITLE
Grid filter menu visual bug on Safari 11

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#1352]
## I'm submitting a...
* Bug report

## Current behavior
The filter menu icon is not inline with the column titles on Safari 11.

## Expected behavior
The filter menu icon should be inline with the column titles on Safari 11 as with other browsers.

## Minimal reproduction of the problem with instructions
View the filter menu in Safari 11
https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#toc-filter-menu
![ss](https://user-images.githubusercontent.com/5023169/37000605-08c27204-2118-11e8-9acd-d57b04aed647.jpg)

**Comment by gyoshev** [comment]
Fixed by https://github.com/telerik/kendo-themes/commit/bb6fef9bae6771be2bedda65594b7a5a1c4811eb and released in `@progress/kendo-theme-default@2.51.0` and later.
