### ISSUE TITLE
Combobox: Clear button has wrong alignment with bootstrap theme

### ISSUE THREAD

**Issue by stefan-schweiger** [telerik/kendo-angular#1353]
## I'm submitting a...

* Bug report 

## Current behavior
When using the bootstrap theme the clear button is to far left, and therefore overlapping the text.

**EDIT**: Another bug when using the class `.form-control` it sets a padding which overrides the padding set for `.k-combobox-clearable .k-input` and messes up the text alignment.

```
.form-control.k-block .k-input, .k-widget.form-control .k-input
{
    padding: .5rem .75rem;
    height: 2.25rem;
}
```

## Expected behavior
As in other themes it should be right next to the dropdown indicator and not overlap text

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/k5OZeJybNJfv2oO7RarG?p=preview

Simply select an item with a long name (eg. Baseball).

Bootstrap:
<img width="175" alt="screenshot 2018-03-05 23 06 45" src="https://user-images.githubusercontent.com/3532342/37002594-87fd7fc6-20ca-11e8-8fc8-023be88d676c.PNG">

Default:
<img width="137" alt="screenshot 2018-03-05 23 06 56" src="https://user-images.githubusercontent.com/3532342/37002597-8a8cc8dc-20ca-11e8-8aaa-5bcea7737b4b.PNG">

## Fix

The css property right now is `calc(16px + 2.25rem)` which is way to much distance, simply change it to this and everything looks fine:

```
.k-combobox .k-dropdown-wrap>.k-i-close,
.k-combobox .k-dropdown-wrap>.k-i-group-delete:before
{
    right: calc(16px + 1.5rem);
}
```

<img width="163" alt="screenshot 2018-03-05 23 07 15" src="https://user-images.githubusercontent.com/3532342/37002518-468edd3c-20ca-11e8-82b2-e6603ccbdee9.PNG">

**EDIT:** And also move `.k-combobox-clearable .k-input` to be applied after `.form-control.k-block .k-input, .k-widget.form-control .k-input`.

## Environment
Browser:
- Chrome (desktop) version 64

**Comment by gyoshev** [comment]
This appears to be fixed with telerik/kendo-themes@0d5e6a6a791d9780ef9256eb132bdadac4df2ba3, available in the latest theme packages. Since the new theme versions are deployed on the site, the plunker doesn't show the problem anymore.
