### ISSUE TITLE
DatePicker switches into next segment when switching from year segment into first segment and typing number

### ISSUE THREAD

**Issue by gravityctrl** [telerik/kendo-angular#1355]
## I'm submitting a...

* Bug report 

## Current behavior

The datapicker has a strange behavior, when the year segment is selected, the user clicks into the month segment and enters a number (for example `1` or `0`) via the keyboard. The second number of the month will be updated and it jumps into the day segment.

## Expected behavior
-> The first segment changes to `0` and the component doesn't jump to the next segment.

## Minimal reproduction of the problem with instructions

Please see this demo page:
[https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/](https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/)

![2018-03-06_11-47-27](https://user-images.githubusercontent.com/34040477/37028355-5551f15a-2134-11e8-996c-4fa23b74bdaa.gif)

1. Type `11` `02` `2014`
2. Click on the first segment
3. Type `0` instantly after clicking
-> The first segment changes to `10` and the component jumps to the second segment.

## What is the motivation or use case for changing the behavior?

- Our customer experiences this issue.

## Environment

Package versions:
- dateinputs v2.1.0

Browser:

- Chrome (desktop) version 64.0.3282.186
- IE version 11.64.16299.0

System:
- Typescript Version: 2.4.2
- Platform:  Windows 10

**Comment by ggkrustev** [comment]
@gravityctrl, thanks for drawing our attention to this issue. It seems that the component doesn't have enough time to select the whole segment and hence only part of it is updated. 
We will look into this and will post a update once more details are available.
