### ISSUE TITLE
DropDownList and reactive from

### ISSUE THREAD

**Issue by mak633** [telerik/kendo-angular#1358]
valueChange runs when you don't change a value.
Here is example https://plnkr.co/edit/QpiTlXPgjfW0bv9BYWDo?p=preview

Step to reproduce: 
1. Open dropdown
2. Don't change value - close dropdown
3. Just click near dropdown
4. You have a console log message but you didn't change the dropdown value. 

It runs when you do it the first time.

**Comment by valchev** [comment]
@mak633 thank you for reporting this. I will investigate the case further and provide a fix as soon as possible.

**Comment by meriturva** [comment]
I have the same issue. Any news here? 

do i have to open a "commercial/private" ticket on telerik portal?

Thanks.

**Comment by ipeshev** [comment]
Fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
