### ISSUE TITLE
Paste Cleanup in angular

### ISSUE THREAD

**Issue by ddoe8** [telerik/kendo-angular#1359]
Hi,

I'm trying to use paste cleanup but I'm not being able to integrate it in my text area. According to the documentation it should be possible use an attribute like k-pastecleanup or k-paste-cleanup or k-paste-clean-up or another "relevant k- editor Angular attribute definition" that i have to guess.

HTML:
<textarea kendo-editor k-ng-model="vm.mail.body" 
                              k-tools="vm.toolbarSettings"
                              k-paste-clean-up="vm.pasteCleanup">
</textarea>

JS:
this.pasteCleanup = {
          all: true,
};

doing something like this is possible? do i have to set all the other pasteCleanup options to false? Can i set the options directly on the attribute like this:

k-paste-clean-up="{all:true}"

I tried all this different approaches that i asked and none of them seem to work. Doing it inline in <script></script> is not an option (like is described on your documentation)

Thank you,

br,

Daniel Doe

**Comment by gyoshev** [comment]
Hello @ddoe8,

This repository is for reporting issues in the Kendo UI for Angular project, which targets Angular 2 and above. For support questions, as well as questions regarding AngularJS and Kendo UI for jQuery, please [submit a support ticket](https://www.telerik.com/account/support-tickets).

**Comment by ddoe8** [comment]
Thank you
