### ISSUE TITLE
Failed to build with Angular 5.0.0

### ISSUE THREAD

**Issue by venkateswararao** [telerik/kendo-angular#1360]
I am working on Angular 5  i had Problem with   @progress/ kendo-angular-grid .   Due to this breaking change:
common: NgTemplateOutlet#ngOutletContext has been removed as it was deprecated since v4. Use NgTemplateOutlet#ngTemplateOutletContext instead.  Let me know how to resolve this I am using 

![error](https://user-images.githubusercontent.com/2831915/37134167-2e985894-22bd-11e8-8033-6f3198e9a4c6.png)

Here are my package.json

       @angular/animations": "^5.2.7",
      @angular/cdk": "^5.2.4",
      "@angular/common": "^5.2.7",
      "@angular/compiler": "^5.2.0",
       "@angular/core": "^5.2.0",
       "@angular/flex-layout": "^5.0.0-beta.13",
        "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@progress/kendo-angular-buttons": "^1.0.5",
    "@progress/kendo-angular-charts": "^1.2.1",
    "@progress/kendo-angular-dialog": "^1.0.4",
    "@progress/kendo-angular-dropdowns": "^1.1.1",
    "@progress/kendo-angular-excel-export": "^1.0.3",
    "@progress/kendo-angular-grid": "^1.2.1-dev.201706261335",
    "@progress/kendo-angular-inputs": "^1.0.6",
    "@progress/kendo-angular-intl": "^1.2.1",
    "@progress/kendo-angular-l10n": "^1.0.2",
    "@progress/kendo-angular-layout": "^1.0.5",
    "@progress/kendo-data-query": "^1.0.5",
    "@progress/kendo-drawing": "^1.1.1",
    "@progress/kendo-ui": "^2017.2.621",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "relative": "^3.0.2",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"

**Comment by tsvetomir** [comment]
Please check that you're using the official npm registry. The Progress NPM registry has been deprecated and contains only legacy versions, [see documentation](https://www.telerik.com/kendo-angular-ui/components/troubleshooting/#toc-i-cannot-install-the-latest-versions-of-kendo-ui-packages-for-angular).

**Comment by venkateswararao** [comment]
How can i check i am using official  registry in my node modules i didn't find any .npmrc file, please help how to resolve issue?

**Comment by tsvetomir** [comment]
Remove your `node_modules` and `package-lock.json` files and try again.

**Comment by tsvetomir** [comment]
Closing until further information becomes available.
