### ISSUE TITLE
Typing an empty space in Grid filter triggers "dataStateChange" but state.filter is undefined

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1361]
When the user types an empty space (press the spacebar) in a Grid filter, the dataStateChange event is fired, but the event data's filter property is _undefined_, making it hard to apply custom logic for handling such scenarios (for example not issuing remote data service request that will essentially return the same data):

[https://plnkr.co/edit/OI1VMUK6fHH0lNtJD6pj?p=preview](https://plnkr.co/edit/OI1VMUK6fHH0lNtJD6pj?p=preview)

Perhaps it would be better to still fire the dataStateChange event, but provide the respective filter descriptor with the space value in the event data.

**Comment by rkonstantinov** [comment]
Indeed, the filterChange/dataStateChange event should not be triggered when filtering on an empty string. This behavior will be addressed with v2.1.3-dev.201803121517 of the kendo-angular-grid package.
