### ISSUE TITLE
Filterable DropDownList not closed the second time it is opened

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1368]
When a filterable DropDownList is opened, then closed via clicking elsewhere on the page, then opened again, clicking elsewhere on the page does not close the popup (the component behaves as expected when opened/closed by clicking the header):

Observable in the online demos:

[https://www.screencast.com/t/9W3KzmAMK](https://www.screencast.com/t/9W3KzmAMK)

**Comment by ipeshev** [comment]
fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
