### ISSUE TITLE
Building package from Source

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#1369]
## I'm submitting a...
* Regression report 

## Current behavior
In https://www.telerik.com/kendo-angular-ui/components/installation/source-code/ is described how to build a modified package. In the latest version you added flatModuleId setting in the tsconfig.es.json, tsconfig.es2015.json and tsconfig.npm.json files.
I need to change the flatModuleId now also to the new package name else an Angular/cli oat build will give the error: Module not found: Error: Can't resolve '@progress/kendo-angular-dropdowns' in '......\node_modules\@mycompany\kendo-angular-dropdowns\dist\es2015'

## Expected behavior
Fix the documentation

**Comment by tsvetomir** [comment]
Thanks for the heads-up, fixed it.

**Comment by tsvetomir** [comment]
Article updated on live site.
