### ISSUE TITLE
ArcGauge stroke color

### ISSUE THREAD

**Issue by Kalemstorm94** [telerik/kendo-angular#1370]
Hello! Is there a posibility to change the ArcGauge stroke color to green just like inside this picture? 
![kendo angular stroke](https://user-images.githubusercontent.com/23106751/37395289-9373d66a-277e-11e8-9dac-d426fa7f30a0.PNG). For some reason my stroke rgba is set to rgba(0,0,0,0), and I'm looking for a way to change this programatically.

**Comment by danielkaradachki** [comment]
The [rangePlaceholderColor](https://www.telerik.com/kendo-angular-ui/components/gauges/api/ArcScale/#toc-rangeplaceholdercolor) option can be used for this purpose:

https://plnkr.co/edit/6n8W4zNjXsAOyUPLSGfO?p=preview

Also, note that this issue tracker is for bug reports only. If you have questions regarding implementation scenarios or configuration please open a support ticket.
