### ISSUE TITLE
Column Reordering on touch devices has issues

### ISSUE THREAD

**Issue by shawnhancock** [telerik/kendo-angular#1371]
## I'm submitting a...

* Bug report

## Current behavior

The 'Reorderable' column feature in the grid has issues on touch devices. On iOS you can drag the column header, but dropping it has no effect on the ordering. On Android, holding in the grid header creates a browser prompt (open in new tab, etc.) which then causes the dragged element to freeze which requires you to refresh the page to rectify.

https://www.telerik.com/kendo-angular-ui/components/grid/columns/reordering/

## Expected behavior

Should work as the desktop (non-touch) functionality.

Browser:

- Chrome (Android) 
- Safari (iOS)

**Comment by rusev** [comment]
@shawnhancock Thank you for the report. 

We will investigate further and will post update once we have more information on the case.

**Comment by doctorssm** [comment]
I found similar issue for sorting and filtering.

STEPS TO REPRODUCE:

Open it in Plunker https://plnkr.co/edit/bvE55QQLJv8E0asyvsr6?p=preview
Please note that I just set [reorderable]="true"
Use any tablet devices
Click on table header to sort it
AR: Sorting is not working
ER: Sorting should work

Browser:

Chrome (Android)
Chrome (iOS)
Safari

When you click on filter icon it is not opening too.

**Comment by ipeshev** [comment]
Still same behavior on Android Chrome

**Comment by ipeshev** [comment]
It is fine now on both Android and iOS devices. 
Available in [latest dev version](https://github.com/telerik/kendo-angular-grid/releases/tag/v3.6.1-dev.201808060737).

**Comment by tsvetomir** [comment]
Fixed in v3.6.1

**Comment by tsvetomir** [comment]
Fixed in v3.7.0
