### ISSUE TITLE
Upload : Confirm before remove

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#1372]
## I'm submitting a...

* Bug report 

## Current behavior

Cannot prompt for confirmation before removing files

## Expected behavior

Provide a mechanism to confirm before removing files using Observables.

## What is the motivation or use case for changing the behavior?

It's a must to ask before performing destructive operations.

**Comment by Raisolution** [comment]
Hi @ilianiv,

Thank you for the idea. Currently we don't have plans to implement Observable confirmation mechanism for removal.

At the moment, this could be achieved by using a file template with a custom remove button, as demonstrated on the [following documentation page](https://www.telerik.com/kendo-angular-ui/components/upload/templates/). On button click, a confirmation popup could be displayed and the file removed via the component API. I hope this approach will be suitable for the current case.

**Comment by moxival** [comment]
Hi @Raisolution i hope you realize that this is not only bad UX design but dangerous one. Whenever there is a destructive operation one should ask for confirmation and that is valid since '92 (maybe earlier).

If you will not give the developers the possibility to implement the confirmation (because your component will not wait for async result, and the confirmation process is async) just remove the removal functionality altogether as it is useless at the moment.

I really am expecting more from a library that costs 900$ per license!

Cheers!

**Comment by Raisolution** [comment]
Hi @moxival,

Thank you for the feedback. As stated in the previous reply, we recommend to use a template, if displaying the confirmation is needed.

If you consider this feature a must, please log it as a suggestion in our [User Voice Portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback?category_id=181429). This way we could update our development plans accordingly and include the most voted ideas.

**Comment by ilianiv** [comment]
Yes, @moxival is right. In 100% of cases with option to delete files devs will need to confirm before remove. In order to do this they'll need to recreate the upload component template (which is very good looking) only to add a custom button.

**Comment by Raisolution** [comment]
Hi @ilianiv,

Please log the suggestion in the [User Voice Portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback?category_id=181429). We will consider to add in our future development plans.

**Comment by ilianiv** [comment]
Link to User Voice Portal issue:  
http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/33679105-confirm-before-remove
