### ISSUE TITLE
DatePicker editor inside in-cell Grid: cannot choose some months by mouse

### ISSUE THREAD

**Issue by AlexBilonog** [telerik/kendo-angular#1373]
## I'm submitting a...

* Bug report 

## Current behavior
User cannot choose first 3 months of a year in calendar by using a mouse.

## Expected behavior
User should have possibility to choose first 3 months of a year in calendar by using a mouse.

## Minimal reproduction of the problem with instructions
Plunker:
https://plnkr.co/edit/ygVjf6WRmVyPk0PGbtQF?p=preview

Steps:
1. Click on "Units In Stock" cell. You will see DatePicker editor (it's OK, because I didn't find a better example with date fields).
2. Open calendar.
3. Click on "March 2018" button.
4. Click on "Jan" or "Feb" or "Mar" (inside 2018 year). You will see that instead of "drill down" to month view, DatePicker is closed and cell is closed too. User cannot select these months by using a mouse.

Additional notes to help investigate this bug:
1. Note that if you click other months, then "drill down" to month view works fine.
2. As I understood the bug is because of cell is losing focus if you click on some calendar months. This leads to closing cell and calendar.

## What is the motivation or use case for changing the behavior?

User should have possibility to choose first 3 months of a year by using a mouse. Base functionality does not work.

## Environment

Package versions:
See Plunker

```

```

Browser:

- Chrome (desktop) version 64
- Firefox version 59
- IE version 11
Didn't check other browsers

System:
See Plunker

**Comment by ipeshev** [comment]
Shipped with v3.5.0
