### ISSUE TITLE
Treeview don´t work full check parent on init

### ISSUE THREAD

**Issue by aquesi** [telerik/kendo-angular#1374]
Hi, 

When I load the treeview  on init and the children is all checked, the parent is partial checked.

In this  sample, sofa 1 and sofa 2 are checked, but their parent "Sofas" is partial checked

https://plnkr.co/edit/z1LpordBNYiPPNhiuVEy?p=preview

Thank you,
Excuse me, my english is poor.
Regards,
Abel

**Comment by ggkrustev** [comment]
Hi @aquesi,
The built-in CheckDirective supports `indeterminate` state only when `hierarchical index` is used. This is mentioned in the TreeView documentation:

https://www.telerik.com/kendo-angular-ui/components/treeview/checkboxes/#toc-multiple-check-by-item-field

I reviewed the demo and noticed that along with the CheckDirective a custom `isChecked` callback is provided. My assumption is that the custom code used in the demo is incorrectly implemented. I would suggest you examine the custom method and try to find the issue on your side. 

If you have any further questions about the custom implementation, please either open a support thread using your license or post your question in Stackoverflow. This channel is used only for feature requests and bug reports related to the built-in functionality that Kendo UI for Angular provides.
