### ISSUE TITLE
Disable actions in kendo-window 

### ISSUE THREAD

**Issue by aquesi** [telerik/kendo-angular#1375]
Hi,

How can I disable all actions (close, maximize, minimize) on kendo-window?

Thank you

Regards
Abel

**Comment by Raisolution** [comment]
Hi @aquesi,

this was an issue regarding the action buttons. I pushed a fix, which is available in v3.3.0-dev.201803150836 and will also be present in the next official release v3.3.0.

You will be able to use the `disabled` property of `kendoButton` to disable the default actions (and any other `kendoButton` property too).

```
<kendo-window>
        <kendo-window-titlebar>
            <div class='k-window-title'>My title</div>
            <button kendoButton (click)="onClick($event)" [icon]="'folder'" [look]="'bare'">Custom action</button>
            <button kendoWindowMaximizeAction [disabled]="true"></button>
            <button kendoWindowRestoreAction></button>
        </kendo-window-titlebar>
        <p>Content</p>
 </kendo-window>
```

**Comment by Raisolution** [comment]
v3.3.0 has been released.

**Comment by konampruthvirajkumar** [comment]
how can we use this same using window service
