### ISSUE TITLE
Upload : Remove files loader indicator

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#1378]
## I'm submitting a...

* Bug report 

## Current behavior

Upload status is missing when you remove files. No loader, no result.

## Expected behavior

Show the loading indicator while files are being removed. Show the result at the end of operation (Done, Failed, etc...) just like when you upload files.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/?p=preview

1. Upload file
2. Remove the file - there is no indicator

## What is the motivation or use case for changing the behavior?

It is natural to have status indicator when you remove files just like when you upload ones.

## Environment

Package versions:

```
@progress/kendo-angular-upload@3.0.3
```

**Comment by Raisolution** [comment]
Hi @ilianiv,

Thank you for noticing the discrepancy between the upload and remove behaviour. I have logged this for fixing.

**Comment by Raisolution** [comment]
The loader indicator will be intended for display only during an upload operation. This will be further emphasized with a change of the loader icon.
