### ISSUE TITLE
toOdataString cannot handle special character (& and +)

### ISSUE THREAD

**Issue by RonnyRen** [telerik/kendo-angular#1380]
I leverage toOdataString API (as below) convert State(Kendo Grid) to string to send to API server. However API server cannot parse query string below correctly.
Code: '/api/data?' + `${toODataString(this.state)}`
Query String: $filter="contains(PortfolioCode,%27%&%27)"&$skip=0&$top=20
Reason: & is considered as separator of parameters.
Example: console log
![image](https://user-images.githubusercontent.com/33855404/37453446-e8fb874c-27f4-11e8-9102-6826f409feca.png)

If I changed URL as following (**escape & to %26**), it can work.
Query String: $filter="contains(PortfolioCode,%27%%26%27)"&$skip=0&$top=20

How to resolve this issue? Is there any simple workaround to fix it?

**Comment by rkonstantinov** [comment]
@RonnyRen, thanks for the report. The issue should be fixed in the latest version of `kendo-data-query` package.

**Comment by RonnyRen** [comment]
@rkonstantinov Is there any draft plan when this case will be fixed, one week, or one month? This fix is critical for my project. If the new version will be released after one week(maybe two weeks), I need to find an alternative solution. Do you have any suggestion or idea?

**Comment by rkonstantinov** [comment]
As I have mentioned in my previous message, the issue in question should be already fixed with v1.2.1 of `kendo-data-query` package. Did you try it?

**Comment by RonnyRen** [comment]
@rkonstantinov 
I did not see the changelog for new version 1.2.1, but I can install the new version. I did a quick test, and it works well. Thanks for your quick fixing.
