### ISSUE TITLE
Incorrect column index in a Grid with locked columns and reordering

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1381]
When reordering columns such that a locked column becomes the first non-locked one, and vice versa - a non-locked column becomes the last locked one (i.e. a column is placed directly on the other side of the locked/non-locked vertical line), the "newColumn" index is incorrect:

[https://plnkr.co/edit/jPVUeFMVclbE9cMHS1sl?p=preview](https://plnkr.co/edit/jPVUeFMVclbE9cMHS1sl?p=preview)

**Comment by ipeshev** [comment]
Fix available in [latest dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version.
