### ISSUE TITLE
DropDownList ARROW_LEFT/RIGHT selection not working as expected

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1384]
## I'm submitting a...

* Bug report 

## Current behavior
RIGHT_ARROW does not select next popup item on first click. 

## Expected behavior
It should select next item on first click ( as in jQuery components ) 

## Minimal reproduction of the problem with instructions
1. Open this [demo](https://plnkr.co/edit/WHqjv2NuifDzD9Xgd3q3?p=preview)
2. Open dropdownlist popup ( mouse click ) 
3. Hit ARROW_DOWN the first item gets selected 
4. Hit ARROW_DOWN the second item gets selected
5. Reopen the demo
6. Open dropdownlist popup ( mouse click ) 
7. Hit ARROW_RIGTH the second item gets selected 

## Environment

Package versions:

```
Broken in v2.1.0
```

**Comment by ipeshev** [comment]
Fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
