### ISSUE TITLE
TreeView: disabling selection still renders grey border

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1386]
## I'm submitting a...
* Bug report
* Suggestion for improvement

## Current behavior
I disabled selection, but grid still renders grey border when I click item.

## Expected behavior
Border is not set when item is clicked.

## Minimal reproduction of the problem with instructions
[Plunkr](https://plnkr.co/edit/F9Clcv5tWwZ9D0MjRJK6?p=preview).
Click item, grey border is showned:

![chrome_2018-03-17_19-06-17](https://user-images.githubusercontent.com/1589573/37558583-4d157f08-2a16-11e8-843c-88da5b0a9fac.png)

## What is the motivation or use case for changing the behavior?
It looks ugly in my application.

**Comment by ggkrustev** [comment]
Hi @MaklaCof, the gray border is part of the focused state of the component. By default, the component navigation is enabled. You can easily disable it using the `navigable` property:

https://www.telerik.com/kendo-angular-ui/components/treeview/api/TreeViewComponent/#toc-navigable
