### ISSUE TITLE
DropDownList's selectionChange event does not fire

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1390]
When selecting a value from the DropDownList, then programmatically changing it and finally selecting the initial value, the (selectionChange) does not fire.

[https://plnkr.co/edit/NAk5zz77k9UwqwfjtbjG?p=preview](https://plnkr.co/edit/NAk5zz77k9UwqwfjtbjG?p=preview)

Steps to reproduce:
1. Select 'Small'
2. Click the button "click me"
3. Select 'Small' --> (selectionChange) is not fired.

**Comment by shulamitmisa** [comment]
Is there an estimate for when this is going to be fixed? I want to know how to handle our task internally (in our project).

**Comment by ipeshev** [comment]
Fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
