### ISSUE TITLE
Chart's SeriesHighlights interface is missing a "markers" property

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1391]
The "markers" property should be included in the interface and respective documentation. It is working properly, but is not a part of the SeriesHighlights interface:

[https://plnkr.co/edit/sJ3Yi3pnbaFY9iGKgVzy?p=preview](https://plnkr.co/edit/sJ3Yi3pnbaFY9iGKgVzy?p=preview)

[https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesHighlight/](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesHighlight/)

**Comment by danielkaradachki** [comment]
Available in the latest version:
https://www.telerik.com/kendo-angular-ui-develop/components/charts/api/SeriesHighlight/#toc-markers
