### ISSUE TITLE
Grid's Column Resizing leaves white space in the last column and does not show original invisible words

### ISSUE THREAD

**Issue by 00SHUAI00** [telerik/kendo-angular#1393]
## I'm submitting a...

* Bug report: Grid's Column Resizing leaves white space in the last column and does not show original invisible words

## Current behavior

Scenario: grid shows multiple columns, the last column's content if full of cell, some words are invisible. 
Step 1: resizing last column from right to left
Observed Result: last column invisible words are still invisible, instead there is white space.

## Expected behavior

Invisible words are visible, there is no white space.

## Minimal reproduction of the problem with instructions

Step 1: resizing last column from right to left
Observed Result: last column invisible words are still invisible, instead there is white space.
https://plnkr.co/edit/QupYBYxyeMt4Y3FappQl?p=preview

## What is the motivation or use case for changing the behavior?

resizing last column from right to left
## Environment
Windows Server 2016 Standard

Package versions:

    "@progress/kendo-angular-buttons" : "2.0.0",
    "@progress/kendo-angular-charts" : "1.3.4",
    "@progress/kendo-angular-dateinputs": "1.4.2",
    "@progress/kendo-angular-dialog": "1.3.0",
    "@progress/kendo-angular-dropdowns": "1.6.0",
    "@progress/kendo-angular-excel-export": "1.0.5",
    "@progress/kendo-angular-grid": "1.7.2",
    "@progress/kendo-angular-inputs": "1.4.2",
    "@progress/kendo-angular-intl": "1.3.0",
    "@progress/kendo-angular-l10n": "1.0.5",
    "@progress/kendo-angular-layout": "1.2.0",
    "@progress/kendo-angular-popup": "1.3.1",
    "@progress/kendo-angular-sortable": "1.0.5",
    "@progress/kendo-data-query": "1.1.2",
    "@progress/kendo-drawing": "1.4.0",
    "@progress/kendo-theme-default": "2.47.0",

Browser:

- Chrome (desktop) version 64.0.3282.186 (Official Build) (64-bit)

System:
- TypeScript version: XX 2.5.3
- Node version: XX  v6.11.0
- Platform:  Windows

**Comment by rkonstantinov** [comment]
This is the designed behavior. It is required for the columns to have width. Thus, resizing one column will not modify the width of the others.
