### ISSUE TITLE
Bug: Master-detail grid - selecting detail grid navigate also master cell

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1394]
## I'm submitting a...
* Bug report 

## Current behavior
When I select row in detail grid (click in cell 2) row is not selected. As side effect master grid navigates to cell 2 which cause grid scroll.

## Expected behavior
Events on detail grid does not effect master grid.

## Minimal reproduction of the problem with instructions

  1. Run this [plunkr](https://plnkr.co/edit/tNwhyEwNMIX9rmel3Mle?p=preview). _I duplicate data to get desired effect._
  2. Scroll down, and open detail grid.
  3. Select any row in detail grid.
  4. Grid scroll to the top and cell in master is navigated.

## Note
If you click twice on the same row in detail, row is selected and no scroll on master is executed.

## Screen recording
![2018-03-21_07-58-38](https://user-images.githubusercontent.com/1589573/37697533-b080f396-2cdd-11e8-9b2b-104dcde21c7b.gif)

**Comment by tsvetomir** [comment]
Keyboard navigation in master-detail grids is not supported currently, see [Known Limitations](https://www.telerik.com/kendo-angular-ui/components/grid/accessibility/#toc-limitations).

That said, we're looking forward to fix it soon. I'll leave this issue open for tracking.

**Comment by danielkaradachki** [comment]
Fixed in 3.10.1:
https://stackblitz.com/edit/angular-kfd2fz?file=app/category-details.component.ts

**Comment by MaklaCof** [comment]
Awesome. I needed and wanted this fix for a long time.
