### ISSUE TITLE
PDF EXPORT STYLING

### ISSUE THREAD

**Issue by XXsjogsXX** [telerik/kendo-angular#1395]
## I'm submitting a...
* Bug report 

## Current behavior
when clicking on PDF Export when trying to export a gantt chart from our website, using the browser "Microsoft Edge" or "Internet Explorer" the styling of the  exported pdf is messed up. ( see included image 1). causing for it to look messy and unprofessional, when using "google chrome" or "firefox" this is not an issue and the pdf export works smoothly

## Expected behavior
the exported pdf should have all the correct styling and same fonts over all different tested browsers

## Minimal reproduction of the problem with instructions
due to this being in our company environment in sharepoint I am not able to put it into plunker.
We just opened up a project, went to project planning and clicked on  gantt chart PDF Export button
In the internet explorer and microsoft edge browsers the exported pdf seems messy
http://prntscr.com/iuaxem , while in google chrome and firefox the exported pdf works as expected.
http://prntscr.com/iuaxvv

## What is the motivation or use case for changing the behavior?
wanting to export the gantt chart for use in a presentation

## Environment

Sharepoint online

Package versions:

```

```

Browser:

- Chrome (desktop) version 65.0.3325.162
- Firefox version 59.0.1
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version 11
- Edge version  41.16299.248.0

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by danielkaradachki** [comment]
We will need a runnable sample in order to be able to investigate what is causing the issue. Please try to isolate the problem in a plunker or a standalone project. If not possible, then please open a [support ticket](https://www.telerik.com/account/support-tickets) with more detailed information about the setup.

**Comment by tsvetomir** [comment]
Closing this due to insufficient information, will revisit if a repro case becomes available.
