### ISSUE TITLE
Ripple effect applied everywhere in Edge / Internet Explorer 

### ISSUE THREAD

**Issue by shawnhancock** [telerik/kendo-angular#1396]
## I'm submitting a...

* Bug report 

## Current behavior
According to documentation the Kendo Ripple effect should only be applied to buttons, checkboxes and radio buttons. In Edge and Internet Explorer, the effect is applied to every element inside the 'kendoRippleContainer' as it seems to apply the 'k-ripple-target' class to every parent element inside the main 'kendoRippleContainer'.

## Expected behavior
As per documentation, buttons, checkboxes and radio buttons should have the ripple effect. 

## Minimal reproduction of the problem with instructions

View the basic usage example in the link below in Edge/Internet Explorer and click the containers that the elements sit in.
https://www.telerik.com/kendo-angular-ui/components/ripple/

## Environment

Browser:

- IE version 11
- Edge

**Comment by gyoshev** [comment]
The issue has been fixed in version `v0.2.5` of the `@progress/kendo-angular-ripple` component. It will be published to the site with the next website upload.
