### ISSUE TITLE
LegendLabelsContentArgs.percentage does not exist for 100% stacked chart

### ISSUE THREAD

**Issue by kkalitowski** [telerik/kendo-angular#1399]
## I'm submitting a...
Bug

## Current behavior
When customizing the legend labels for a 100% stacked area chart, the percentage value is not available. The [documentation](https://www.telerik.com/kendo-angular-ui/components/charts/api/LegendLabelsContentArgs/) says it should be.

## Expected behavior
[LegendLabelsContentArgs.percentage](https://www.telerik.com/kendo-angular-ui/components/charts/api/LegendLabelsContentArgs/#toc-percentage) should be populated for a 100% stacked area chart.

## Minimal reproduction of the problem with instructions
See [Plunkr](https://plnkr.co/edit/uhIH922VrYIlTLOILv2T?p=preview)
There is a `console.log` showing that only the `text` and `series` fields are populated on the `LegendLabelsContentArgs`.

## Environment
Reproducible on Plunkr; omitting environment info.

**Comment by danielkaradachki** [comment]
The documentation seems to be incorrect. The percentage is available only for pie, donut and funnel series because the legend items represent individual points. For the other charts stacked or not, the legend items represent the entire series. We will update documentation.

**Comment by danielkaradachki** [comment]
The documentation seems to be incorrect. The percentage is available only for pie, donut and funnel charts because the legend items represent individual points. For the other charts stacked or not, the legend items represent the entire series so no percentage is available. We will update the documentation.

**Comment by tsvetomir** [comment]
Fixed and published [on staging](https://www.telerik.com/kendo-angular-ui-develop/components/charts/api/LegendLabelsContentArgs/#toc-percentage), will be updated live in a few days.

Thanks for reporting the issue!
