### ISSUE TITLE
[TextBox]: focus/blur events are triggered twice

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#1400]
## I'm submitting a...
* Bug report

## Current behavior
Focus/blur events are triggered twice.

## Expected behavior
To get only one call of focus/blur event.

## Minimal reproduction of the problem with instructions
  1. Open https://plnkr.co/edit/gHP32ccprhvDYZslsPpf?p=preview
  2. Open browser dev console
  3. Focus/blur the input and notice the erroneous behavior

Reported in TicketID: 1159223

**Comment by ggkrustev** [comment]
As a workaround, the one can detect focus/blur calls and omit the second callback execution.

https://plnkr.co/edit/47TCRiW8kca43IDx9pzt?p=preview

**Comment by fabriziodebortoli** [comment]
after more than two months has not yet been solved?

**Comment by ipeshev** [comment]
Available in latest developmen version v3.2.1-dev.201807091519

**Comment by danielkaradachki** [comment]
fixed in 3.2.1
