### ISSUE TITLE
MultiSelect renders dropdown items with an id='undefined-*'

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#1402]
## I'm submitting a...
* Bug report 

## Current behavior
![image](https://user-images.githubusercontent.com/90405/37832560-a33647ec-2eb1-11e8-97e4-2926244603d8.png)

## Expected behavior

If the IDs are used for ARIA purposes, they should perhaps be unique, perhaps prefixed with the list id (which is already a GUID).

If the IDs serve no purpose, perhaps it's best to remove them.

## Minimal reproduction of the problem with instructions
[See this plunker](https://plnkr.co/edit/Hr6KICG0qsJk6nQE9iJS?p=preview)

## Environment

Package versions:

```
@progress/kendo-angular-dropdowns@2.1.0
```

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://github.com/telerik/kendo-angular-dropdowns/releases/tag/v3.0.3-dev.201808011119).

**Comment by tsvetomir** [comment]
Shipped in v3.0.3
