### ISSUE TITLE
DateInput: Spinner disapears with Bootstrap theme

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1404]
## I'm submitting a...
* Bug report 

## Current behavior
Using the DateInput Control with spinner enabled and Bootstrap theme, the spinner disapears.

## Expected behavior
Spinner visible and usable

## Minimal reproduction of the problem with instructions
Using your spinner sample, replacing the inlcude of the default theme with the bootstrap theme:

https://plnkr.co/edit/zwEos8dHZisrfZjCUXIT?p=preview

Browser:
- Chrome (desktop) version 62

**Comment by gyoshev** [comment]
@EricSch thanks for reporting this. We will be fixing this in the themes soon, an immediate workaround is to add the following style to the page:

```css
.k-dateinput .k-select {
    width: 32px;
}
```

**Comment by gyoshev** [comment]
The issue was fixed in `@progress/kendo-theme-bootstrap@2.11.11`.
