### ISSUE TITLE
[kendoTextArea] Add auto-resizing functionality

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1405]
Add auto-resizing functionality to the <textarea> element as follows:

![2018-03-26_1052](https://user-images.githubusercontent.com/20015190/37893493-dbefe384-30e3-11e8-9760-22a822587d27.png)

[https://material.angular.io/components/input/overview#auto-resizing-code-lt-textarea-gt-code-elements](https://material.angular.io/components/input/overview#auto-resizing-code-lt-textarea-gt-code-elements)

**Comment by gyoshev** [comment]
Available on the development channel of `@progress/kendo-angular-inputs`. [Online demo](https://www.telerik.com/kendo-angular-ui-develop/components/inputs/textarea/#toc-auto-resizing).

**Comment by danielkaradachki** [comment]
Released in 3.2.0
