### ISSUE TITLE
[TextBoxContainer] Allow error messages to be displayed for associated components

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1406]
Display error messages when the input is not valid:

![2018-03-26_1056](https://user-images.githubusercontent.com/20015190/37893636-52d557ea-30e4-11e8-9af0-fa155cf156e8.png)

[https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown](https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown)

**Comment by elena-gancheva** [comment]
Closing this issue, since it is a part of https://github.com/telerik/k2/issues/139
