### ISSUE TITLE
Dropdownlist popup setting appendTo breaks keyboard navigation

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1412]
## I'm submitting a...

* Bug report 

## Current behavior
Dropdownlist popupSettings as function breaks keyboard navigation (selection by typing on opened popup , selection with arrow keys on opened popup ) 

## Expected behavior
Keyboard navigation should work in any case.

## Minimal reproduction of the problem with instructions
1. Open this [demo](https://plnkr.co/edit/nYUGNQFTlJkIBcd7ewdo?p=preview)
2. Toggle dropdown popup 
3. Try to type - nothing selected
4. Try to navigate with arrow keys - nothing selected

## Environment

Package versions:

```
broken in v2.1.0
```

**Comment by ipeshev** [comment]
Fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
