### ISSUE TITLE
De-select all does not work in grid when grouping

### ISSUE THREAD

**Issue by cknightdevelopment** [telerik/kendo-angular#1413]
## De-select all does not work in grid when grouping programatically

* Bug report 

## Current behavior

When using grouping in a grid and select all, the de-select all functionality does not work. It works if you drag a column to be grouped by or if you don't group at all. But when you have the grouping set programatically, it breaks.

## Expected behavior

After selecting all items in the grid, clicking the select all checkbox again should de-select all the items 

## Minimal reproduction of the problem with instructions

1. Open Plunker: https://plnkr.co/edit/lWt05OhlhcJd0ItMKftY
2. Run Plunker
3. Select all items via checkbox in top right.
4. Click the same checkbox

## What is the motivation or use case for changing the behavior?

De-select all functionality should be consistent regardless of how you group.

## Environment

Package versions:

Reproducible on demo site.

Browser:

- Chrome (desktop) Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by Raisolution** [comment]
The fix is available in `v2.1.3-dev.201803281558` and will also be present in the next official release.

**Comment by tsvetomir** [comment]
This fix has been released in v2.1.3
