### ISSUE TITLE
Grid editCell() method opens a wrong cell for editing when there are locked columns

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1414]
When there are locked columns, the (correct) cellIndex, received in the cellClick event handler is shifted such that the received index is applied to the non-locked section, and the wrong cell is put in edit mode:

[https://plnkr.co/edit/YyWsskgCdWH5eJUqWwVU?p=preview](https://plnkr.co/edit/YyWsskgCdWH5eJUqWwVU?p=preview)

Workaround - pass **column.field** instead of **columnIndex** to the **editCell** method:

[https://plnkr.co/edit/QWqWN7gRbHSKChhr7JUY?p=preview](https://plnkr.co/edit/QWqWN7gRbHSKChhr7JUY?p=preview)

**Comment by tsvetomir** [comment]
Published in v3.1.0
