### ISSUE TITLE
Data binding to textbox

### ISSUE THREAD

**Issue by vadsamm** [telerik/kendo-angular#1418]
when i bind date column to textbox from sql, data is binding like this /Date(1466188200000)/. how to format the date in mvc textbox. date format should be dd/mm/yyyy.

Thanks in Advance

## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by rkonstantinov** [comment]
Your question does not seems to be related to our product.

**Comment by vadsamm** [comment]
binding date field to kendo textbox in mvc but it is not displaying date correctly.
