### ISSUE TITLE
Multiple axes on Kendo Angular Chart

### ISSUE THREAD

**Issue by sreeraagmohan** [telerik/kendo-angular#1419]
Is it possible to have multiple axes on Kendo Angular Chart? 

https://demos.telerik.com/kendo-ui/line-charts/multiple-axes

Something similar to this, for Angular?

**Comment by danielkaradachki** [comment]
Yes, it is possible. The configuration is pretty much the same as with the jQuery version:
https://plnkr.co/edit/3x9COlVSyvIunKA2py1R?p=preview

Please note that this issue tracker is for bug reports only. If you have questions regarding implementation scenarios or configuration please open a support ticket.
