### ISSUE TITLE
Data Query & Grid: Support for case insensitive 

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1420]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
When I add a filter to a grid, I see no way to define "case insensitivity" for the odata filter query.
I see there is a property in the Data Query library (toLower) but it seems only to work for the value and not accessible from grid. 
I'm using the function "toODataString" to get the query string.

## Expected behavior
A query string with a filter like `$filter=contains(tolower(Projektleiter),tolower('Wett'))` or `$filter=contains(tolower(Projektleiter),'wett')` when i call "toODataString"

## What is the motivation or use case for changing the behavior?
I have to do case insensitive queries. I prefer to do it via the query string and not in the API-

## Environment
`@progress/kendo-data-query@1.1.2
`

**Comment by svetq** [comment]
also requested in #1399088

**Comment by hidegh** [comment]
@EricSch @svetq this and much more already proposed (with code snippets) exists in: https://github.com/telerik/kendo-angular/issues/2102

**Comment by PaskalevStoyan** [comment]
To be tracked in the Feedback Portal - [link](https://feedback.telerik.com/kendo-angular-ui/1609391-data-query-grid-support-for-case-insensitive-for-odata).
