### ISSUE TITLE
Numeric menu filter input minus sign

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#1421]
## I'm submitting a...
* Bug report

## Current behavior
Open the numeric filter menu. Click inside the input. Type a minus sign -- nothing happens. Type a minus sign again -- a minus sign is shown in the input.

## Expected behavior
A minus sign should be entered on the first key press.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/cL6Wx7lMyNovwuAzxbA1?p=preview

## Environment

Browser:
- Chrome (desktop)
- Firefox
- Safari (desktop)

**Comment by danielkaradachki** [comment]
Thank you for bug report. We will look into it.

**Comment by ipeshev** [comment]
Shipped with v3.0.0
