### ISSUE TITLE
How to Add Icon in Header Cell of Kendo Angular UI.  Like below. 

### ISSUE THREAD

**Issue by sunpasup** [telerik/kendo-angular#1423]
<img width="225" alt="screen shot 2018-03-28 at 4 57 52 pm" src="https://user-images.githubusercontent.com/24596204/38062568-78c7d498-32a9-11e8-98b5-6c6afa931627.png">

## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by rkonstantinov** [comment]
This repository is for reporting issue with the components. For general support questions, please [open a support ticket via our ticketing system](https://www.telerik.com/account/support-tickets)
