### ISSUE TITLE
k-form class breaks the calendar layout

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1424]
## I'm submitting a...

* Bug report 

## Current behavior
If we put kendo-calendar component in element with k-form class, calendar becomes broken.

## Expected behavior
Kendo-calendar should be usefull inside form.

## Minimal reproduction of the problem with instructions
1. Open this [plunker sample](https://plnkr.co/edit/eIr2TVJSfRvsVktVSwuH?p=preview).

## Environment

Package versions:

```
broken in v2.2.0
```

**Comment by gyoshev** [comment]
Workaround is to set `display: inline-flex` on the calendar component, like shown in the [updated plunker](https://plnkr.co/edit/GKVAmHrpN300JH7fN1An?p=preview).
