### ISSUE TITLE
A typo in the '@progress/kendo-ooxml' package codebase

### ISSUE THREAD

**Issue by alexeikostevich** [telerik/kendo-angular#1425]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
There is a typo in the `@progress/kendo-ooxml` package codebase. _hierachy_ is used instead of `hierarchy`.

## What is the motivation or use case for changing the behavior?
Avoid warnings from code quality tools which verify source code grammar.

## Environment

Package versions:

```
@progress/kendo-angular-excel-export@1.0.7
```

This is an extra minor issue. Since it was accidentally caught by the code quality tools on our project, we are sharing the finding.

**Comment by tsvetomir** [comment]
Fixed, thanks!
