### ISSUE TITLE
Grid Filter Template Multi Select State not persisting

### ISSUE THREAD

**Issue by kotva006** [telerik/kendo-angular#1426]
## I'm submitting a...

* Bug report 

## Current behavior
Here is a plnkr that exhibits the issue: https://plnkr.co/edit/VVTmnQR0x5uepIHx99Uj?p=preview
Filtering by Category filters the first time, but the selected category is no longer persisted in the multi-select in the filter menu, and selecting any other category, or clear has no positive effect (except clearing the whole list)

## Expected behavior
I expect the multi-select to persist the selected values and being able to clear the filter and select new values to re-filter the grid.

## Minimal reproduction of the problem with instructions
Here is the plnkr again: https://plnkr.co/edit/VVTmnQR0x5uepIHx99Uj?p=preview
This is an almost exact copy of the Customizing Filter Menu example (which works as expected).  The only thing changed from the demo example was in the function categoryChange.  I changed the field from the string 'CategoryID' to a function which returns the value of CategoryID.  (I am under the impression that is the expected return value of the field function but could find little documentation on what is the expected behavior of the function.)
It appears that changing the field property of the filter from a string to a function breaks the expected behavior.

## What is the motivation or use case for changing the behavior?
The documentation says it supports the filter being a function (which i guess it kind of does, but the interaction with the multi-select appears broken)

## Environment

Package versions:
Reproducible on demo site

Browser:

- Chrome (desktop) version 65.0.3325.181
- Firefox version 59.0.1

System:

**Comment by rkonstantinov** [comment]
Having the FilterDescriptor's field as a function is not supported by the Grid. As the filter field is used for mapping the descriptor to a column there is no way this to be done when field is a function.

**Comment by kotva006** [comment]
Could you clarify that on the documentation then?
The documentation for FilterDescriptor doesn't mention anything about it:
https://www.telerik.com/kendo-angular-ui/components/dataquery/api/FilterDescriptor/
