### ISSUE TITLE
grid - packages version available on npm is 1.2.1 but 2.1.2 is the current

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#1427]
A

## I'm submitting a...
bug

* Bug report 

## Current behavior
run "npm view @progress/kendo-angular-grid" and the most recent version listed is 1.2.1

save issue with other components (i.e. buttons)

## Expected behavior
the most recent version should at least be 2.1.2
https://www.telerik.com/kendo-angular-ui/components/grid/changelog/

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by rkonstantinov** [comment]
Most probably you are using the our retired NPM registry. For more information please refer to this [issue](https://github.com/telerik/kendo-angular/issues/712).

**Comment by djarekg** [comment]
That was it. Thank you.
