### ISSUE TITLE
Changing the view of a Calendar affects other Calendars on the page

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1428]
The issue can be observed when switching between the month, year, etc. views in both calendars, at some point the view, selected in one of the Calendars gets automatically set to the other one too:

[https://plnkr.co/edit/hFTVYmO8L1bSJUKe1uEq?p=preview](https://plnkr.co/edit/hFTVYmO8L1bSJUKe1uEq?p=preview)

**Comment by ggkrustev** [comment]
This is addressed in the latest DEV release of the components. 
Just run `npm i @progress/kendo-angular-dateinputs@dev` to check the updates.

**Comment by tsvetomir** [comment]
Fixed in v3.4.0
