### ISSUE TITLE
Default item does not work as expected with non-null values

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1432]
Currently the default item of the DropDownList works as expected only when its value field is **_null_**. The default item's text is not displayed when the component is value-bound (either via forms or the _value_ property), and the value of the default item is different than null (for example an empty string for string values, or some random number for numeric ones):

[https://plnkr.co/edit/5sfNsWSkZanJq09AbYRi?p=preview](https://plnkr.co/edit/5sfNsWSkZanJq09AbYRi?p=preview)

**Comment by ipeshev** [comment]
Fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
