### ISSUE TITLE
EditCommandDirective removes classes from a button in the kendo grid

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#1433]
## I'm submitting a...
* Bug report 

## Current behavior
The classes that are set for a button with EditCommandDirective are missing in the final html.

## Expected behavior
The classes should be preserved and applied to the button.

## Minimal reproduction of the problem with instructions
In the [example in the documentation](https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-template-forms/#code-0)  class "k-primary" is used for "Edit" button with kendoGridEditCommand directive
`<button kendoGridEditCommand type="button" class="k-primary">Edit</button>`

But the class does not apply and final html is
`<button class="k-button k-grid-edit-command" kendogrideditcommand="" type="button" dir="ltr" tabindex="-1">Edit</button>`

and looks like:
![image](https://user-images.githubusercontent.com/33227044/38188890-863847b4-3666-11e8-908e-edba67b02c7b.png)

Expected html to be
`<button class="k-button k-grid-edit-command k-primary" kendogrideditcommand="" type="button" dir="ltr" tabindex="-1">Edit</button>`

and look like:
![image](https://user-images.githubusercontent.com/33227044/38189215-b8dd0f00-3667-11e8-985b-8b53d5d5a67a.png)

**Comment by ipeshev** [comment]
@vbakavets in deed it is a problem, thank you for the bug report !

**Comment by ipeshev** [comment]
@dmihaylo we might need this explained in separate section.
