### ISSUE TITLE
[TimePicker]: Last literal is not visible in the popup

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#1435]
### Description
The component will render all literals along with the time format specifiers. This, however, will result in incorrectly sized popup element, because the last literal will not expand the popup width.

![screen shot 2018-04-03 at 3 32 01 pm](https://user-images.githubusercontent.com/495188/38249425-46fc6938-3754-11e8-9b9e-003250841e10.png)

Repro demo: https://plnkr.co/edit/0mXJGGIDX9CMZeWkQhQv?p=preview

**Comment by gyoshev** [comment]
Workaround: add the rule `.k-time-separator { width: auto }`. [Plunker demo](https://plnkr.co/edit/TsuDUGlnTmvlnOffXvpK?p=preview).
