### ISSUE TITLE
regarding kendo ui editor for angular 4

### ISSUE THREAD

**Issue by swapnilshinde48** [telerik/kendo-angular#1436]
do kendo ui editor support for angular 4? can you provide any document with step by step integration

**Comment by gyoshev** [comment]
This repository is for reporting issues in the Kendo UI for Angular product. For questions on how to use the components, [submit a support ticket](https://www.telerik.com/account/support-tickets) or [ask on StackOverflow](http://stackoverflow.com/questions/tagged/kendo-ui-angular2). For more details, [see the README](https://github.com/telerik/kendo-angular#kendo-ui-for-angular) of this repository.

That said, you can refer to the [integration help topic](https://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/).
