### ISSUE TITLE
Sortable: Enable dropping an item between disabled items

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1437]
Currently dropping an active items between disabled ones is not possible (Item1 cannot be dropped between Item2 and Item3):

[https://plnkr.co/edit/GR98MJTvdXEb3ZKKgmJR?p=preview](https://plnkr.co/edit/GR98MJTvdXEb3ZKKgmJR?p=preview)

... but it would be nice to add an enhancement matching the Kendo UI for jQuery functionality:

[https://demos.telerik.com/kendo-ui/sortable/filter-disable](https://demos.telerik.com/kendo-ui/sortable/filter-disable)

**Comment by tapopov** [comment]
Fixed in v2.0.0-dev.201811021110

**Comment by tapopov** [comment]
Shipped in kendo-angular-sortable v2.0.0
