### ISSUE TITLE
Virtual scrolling causes undesired effect when using DownArrow or PageDown button

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1438]
When using the DownArrow or PageDown key for scrolling a grid in virtual scrolling mode, the grid jumps to an improper position.

Check the following sample plunker:

[https://plnkr.co/edit/J7FqyRMnLiPqBsyhL3Oi?p=preview](https://plnkr.co/edit/J7FqyRMnLiPqBsyhL3Oi?p=preview)

**Comment by tsvetomir** [comment]
To clarify, holding down the arrow/page keys while loading data can cause the current page to be skipped. Will look into it.

**Comment by Raisolution** [comment]
Issue is no longer reproducing with kendo-angular-grid `v5.4.0`.
