### ISSUE TITLE
Angular 6.x support time frame?

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#1439]
## I'm submitting a...
Question

* Suggestion for improvement

## Current behavior
only angular 5.x supported

## Expected behavior
support angular 6.x

**Comment by ggkrustev** [comment]
At the time of writing this, Angular 6 is still in RC.1 phase. We will introduce a support for it once the Angular team releases `Angular 6` officially.

https://github.com/angular/angular/blob/master/CHANGELOG.md#600-rc1-2018-03-30

Stay tuned for updates. Will close the thread as it doesn't report a bug.

**Comment by lucho78** [comment]
Sdrasti Georgi,
I guess the new version will be release very soon. So that means once the version 6.0.0 will be release we can assume that the Kendo components will support this version. Am I right?
Thanks
Luc

**Comment by tsvetomir** [comment]
We are not aware of any issues with the RC versions at the time. There are some gotchas to watch out for. Most importantly, you need to include [rxjs-compat](https://www.npmjs.com/package/rxjs-compat) to maintain compatibility with RxJS 5.5+ as this is what Kendo UI uses.

**Comment by lucho78** [comment]
I did a test today with rxjs-compat and it works well
Thanks for this tip
Luc

**Comment by tsvetomir** [comment]
Official update instructions will be published soon. The short version is:

Update to the latest Kendo UI package versions:
```sh
npm install -g npm-check-updates
ncu -u -f /^@progress/
```

Install rxjs-compat:
```sh
npm install --save rxjs-compat@6
```

**Comment by tsvetomir** [comment]
All components have been updated to address Angular 6 compatibility. Update instructions can be found in [the documentation](https://www.telerik.com/kendo-angular-ui/components/installation/angular-6/).

Closing this issue as resolved. Please, open new issues for any specific problems that pop up after the upgrade.
