### ISSUE TITLE
Consider Adding Kendo UI Components To app.module

### ISSUE THREAD

**Issue by burkeholland** [telerik/kendo-angular#144]
The Angular CLI currently adds any generated modules to the `app.module.ts` file for the developer automatically. Should we consider doing the same when a user installs a Kendo UI Widget? This might be tricky....

- We don't know the developer's file structure
- We don't know if they called their main app module `app.module.ts`

Perhaps we could do our best to add it to the app module, and if we are unable to, shell out a message to the console.

**Comment by eeasss** [comment]
I think we can do that when we start shipping CLI extensions to scaffold specific Kendo components.

Until then, as you remarked, we will have no idea whether the project was generated by the CLI, by the seed or something else.

**Comment by burkeholland** [comment]
As long as we've got it on our radar, I think we're headed in the right direction.

**Comment by tsvetomir** [comment]
Closing this as we can't solve it from within the library itself.
