### ISSUE TITLE
Focusing and then blurring a DropDownList causes the form to become dirty

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1441]
Check the following sample plunker:

[https://plnkr.co/edit/QTMa7V0ebqN1yLu33zi9?p=preview](https://plnkr.co/edit/QTMa7V0ebqN1yLu33zi9?p=preview)

1. Focus the DropDownList
2. Blur the DropDownList
3. The form becomes dirty even though the value is not changed

**Comment by ssmartin** [comment]
Hi @svetq 

Is there an estimate for when this is going to be fixed? I want to know how to handle our ticket/task internally (in our project).

Thank you.

**Comment by ipeshev** [comment]
Fixed in v3.0.2-dev.201806051505

**Comment by tsvetomir** [comment]
Fix released in v3.0.2 of the `@progress/kendo-angular-dropdowns`
