### ISSUE TITLE
Grid - kendoGridSelectAllCheckbox selection does not work properly when reorder column is turned on.

### ISSUE THREAD

**Issue by jacekbartek** [telerik/kendo-angular#1445]
## I'm submitting a...
* Bug report

## Current behavior
When kendo-datepicker has focus and we try to click on the kendoGridSelectAllCheckbox, the selection does not work. Only works by  double click.

This behavior occurs when [reorderable] = true; Otherwise it works.

Interestingly, this works on Edge (41.16299.334.0) and Firefox (59.0.2) but no on Chrome (65.0.3325.181).

## Expected behavior
kendoGridSelectAllCheckbox selection should be work properly.

## Minimal reproduction of the problem with instructions
1. Click on kendo-datepicker to select value.
2. Try to select all rows by kendoGridSelectAllCheckbox.

https://embed.plnkr.co/naB5XLGj92zDzt4xoXjR/

## Environment

Package versions:
    "kendo-angular-buttons": "4.0.0",
    "kendo-angular-dateinputs": "2.2.0",
    "kendo-angular-dialog": "3.4.0",
    "kendo-angular-dropdowns": "2.1.0",
    "kendo-angular-excel-export": "1.0.7",
    "kendo-angular-grid": "3.0.0",
    "kendo-angular-inputs": "2.2.0",
    "kendo-angular-intl": "1.4.0",
    "kendo-angular-l10n": "1.1.0",
    "kendo-angular-layout": "2.2.1",
    "kendo-data-query": "1.2.2",
    "kendo-drawing": "1.5.2",
    "kendo-theme-default": "2.49.1",
    "kendo-ui": "2018.1.403",

Browser:
- Chrome (desktop) Version 65.0.3325.181 (64-bit)

System:
- TypeScript version: "2.7.2
- Node version: node : v6.11.3 , npm: 3.10.10
- Platform: Windows 10 64bit

**Comment by rkonstantinov** [comment]
Thanks for the report. The behavior in question should be addressed with the [latest `dev` channel](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/) version of the `kendo-angular-grid` package.

**Comment by jacekbartek** [comment]
I tested on 3.0.1-dev.201804101334 and it works. I am waiting for release version. Regards

**Comment by tsvetomir** [comment]
Published in v3.1.0
