### ISSUE TITLE
Is there a way to changes the name="files" from the payload?

### ISSUE THREAD

**Issue by LeFredd** [telerik/kendo-angular#1446]
Is there a way to changes the name="files" from the payload? 
Because if my api needs only name="file" so the api should adapt the name. And I don't think that it's a great idea ;)

**Comment by Raisolution** [comment]
Hi @LeFredd,

Yes, this could be achieved by specifying the [saveField](https://www.telerik.com/kendo-angular-ui/components/upload/api/UploadComponent/#toc-savefield) property of the Upload.
