### ISSUE TITLE
text-input does not work properly in Kendo TreeView-- Node Template

### ISSUE THREAD

**Issue by MohamedSaydSaleh** [telerik/kendo-angular#1448]
## I'm submitting a...
Question or Bug

## Current behavior

When adding text input in TreeView Node Template, It doesn't work,
textBox is enabled but doesn't receive any character input from keyboard

## Minimal reproduction of the problem with instructions
I created Plunker for issue
https://plnkr.co/edit/dNKXwI8izgvMZh152Y7A?p=preview

## Environment

Package versions:
 @progress/kendo-angular-treeview@2.1.3

```

```

Browser:

- Chrome (desktop) version 65.0.3325.181
-FireFox 59.0.2

System:
- TypeScript version:2.4.1
- Node version:v8.9.1  
- Platform: Winows server

**Comment by ggkrustev** [comment]
Hi @MohamedSaydSaleh,
In general, the TreeView is designed to recognize focusable item elements, but for the time being it doesn't fully support such focusable behavior. We will further investigate the case and will update the thread once we have more details to share. Stay tuned.

**Comment by ipeshev** [comment]
Fixed in v2.3.0-dev.201808161041

**Comment by danielkaradachki** [comment]
Fixed in 2.3.0
