### ISSUE TITLE
Dialogs opend from a window are behind window

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#1451]
## I'm submitting a...
* Bug report 

## Current behavior
If we open a dialog from a window, dialog will be below window and invisible. There's no way to bring the dialog in front of the window.

## Expected behavior
Dialog should show on top. Dialogs are modal, so there's no situation where it makes sense to show them behind something.

## Minimal reproduction of the problem with instructions
Plunker: https://plnkr.co/edit/QCdaPWmFUF3tzO7k6S1g?p=preview

## What is the motivation or use case for changing the behavior?
Case: Window contains list of records with button "delete record". When user clicks "delete record" we want to show a dialog "really delete?".

## Environment
progress/kendo-angular-dialog: 3.4.0

Browser:
Chrome

## Suggested fix

This change works for me:

kendo-theme-default/scss/dialog/_layout.scss, line 13

```
    .k-dialog-wrapper {
...
        z-index: 10001; 
=>  z-index: 11000;
...
    }
```

**Comment by Raisolution** [comment]
Hi @cluetjen,

I recommend manually adding the appropriate `z-index` styles as a fix for the current application. I'll add this to our backlog and discuss general solution with the development team.

**Comment by seanmcnamee45** [comment]
This issue was closed in 2018, but I am still facing this issue. Is this still being discussed?
