### ISSUE TITLE
Switch display error if component has change detection strategy OnPush

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#1452]
## I'm submitting a...
* Bug report

## Current behavior
When
* a component has change detection strategy set to OnPush 
* and contains a switch component
* with initial value = true

then
* component is rendered incorrectly: Switch color is gray, should be accent color (red in the example)

## Expected behavior
Switch has color red.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/vi4vpTjnVsBFUJQ7Fvya?p=preview

## What is the motivation or use case for changing the behavior?
We try to use OnPush for performance reasons.

## Environment

Package versions:
progress/kendo-angular-buttons: 4.0.0

Browser:
Chrome

**Comment by ipeshev** [comment]
Fixed in v3.0.0
