### ISSUE TITLE
Mark Friday and Saturday as non-workdays for he locale of Calendar

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1454]
Currently the Calendar marks Saturday and Sunday as weekend for the he locale. It should be Friday and Saturday instead:

[https://plnkr.co/edit/FY7zn2cXM4YO3n7UOgiT?p=preview](https://plnkr.co/edit/FY7zn2cXM4YO3n7UOgiT?p=preview)

**Comment by danielkaradachki** [comment]
Fixed in kendo-angular-dateinputs 4.0.0 and kendo-angular-intl 2.00

https://stackblitz.com/edit/angular-dynr4q?file=app/app.component.ts
