### ISSUE TITLE
kendo-window: appendTo option

### ISSUE THREAD

**Issue by mrnetforge** [telerik/kendo-angular#1456]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

I was try to implement kendo-window component inside container that are pretty small and my created window cannot be maximize.

## Expected behavior
I expected that my component with window gonna be append to body so window can be maximize from anywhere i create that component

In jQuery version of kendo-window there is option with 'appendTo'. So.. is there any solution for now?

**Comment by danielkaradachki** [comment]
You can specify the container in which the window is rendered when creating the window via the [WindowService](https://www.telerik.com/kendo-angular-ui/components/dialogs/window/service/#toc-specifying-the-window-container). Changing the container of the component is not supported.
