### ISSUE TITLE
Error deleting row in grid

### ISSUE THREAD

**Issue by rtaschetto** [telerik/kendo-angular#1462]
## I'm submitting a...

* Bug report 

## Current behavior

When delete a row (for example row 2) and then delete another row, the second row index is wrong.

## Expected behavior

I have this situation:
row 1
row 2
row 3
row 4 
row 5

after delete "row 2" i have :
row 1 
row 3
row 4
row 5

after delete "row 3" I would expect to have this situation
row 1 
row 4
row 5

but I have this:
row 1 
row 3
row 5

## Minimal reproduction of the problem with instructions
You can reproduce the problem also in documentation example:
https://www.telerik.com/kendo-angular-ui/components/grid/editing/custom-reactive-editing/#

## What is the motivation or use case for changing the behavior?

It's a bug?

## Environment

Package versions:

```
@coreui/angular@1.0.10 D:\work\lab\angular2\sbp-project-backend
+-- @angular/animations@5.2.9
+-- @angular/cli@1.6.7
+-- @angular/common@5.2.3
+-- @angular/compiler@5.2.3
+-- @angular/compiler-cli@5.2.3
+-- @angular/core@5.2.3
+-- @angular/forms@5.2.3
+-- @angular/http@5.2.3
+-- @angular/language-service@5.2.3
+-- @angular/platform-browser@5.2.3
+-- @angular/platform-browser-dynamic@5.2.3
+-- @angular/router@5.2.3
+-- @angular/upgrade@5.2.3
+-- @auth0/angular-jwt@1.1.0
+-- @progress/kendo-angular-buttons@4.0.0
+-- @progress/kendo-angular-dateinputs@2.2.0
+-- @progress/kendo-angular-dropdowns@2.1.0
+-- @progress/kendo-angular-excel-export@1.0.7
+-- @progress/kendo-angular-grid@3.0.0
+-- @progress/kendo-angular-inputs@2.2.0
+-- @progress/kendo-angular-intl@1.4.0
+-- @progress/kendo-angular-l10n@1.1.0
+-- @progress/kendo-data-query@1.2.2
+-- @progress/kendo-drawing@1.5.1
+-- @progress/kendo-theme-bootstrap@2.11.10
+-- @types/jasmine@2.8.6
+-- @types/jasminewd2@2.0.3
+-- @types/node@9.4.0
+-- bootstrap@4.0.0
+-- chart.js@2.7.1
+-- codelyzer@4.1.0
+-- core-js@2.5.3
+-- flag-icon-css@2.9.0
+-- font-awesome@4.7.0
+-- jasmine-core@2.9.1
+-- jasmine-spec-reporter@4.2.1
+-- jquery@1.9.1 - 3
+-- karma@2.0.0
+-- karma-chrome-launcher@2.2.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.4.1
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- moment@2.20.1
+-- ng2-charts@1.6.0
+-- ngx-bootstrap@2.0.2
+-- popper.js@^1.12.9
+-- protractor@5.3.0
+-- rxjs@5.5.6
+-- simple-line-icons@2.4.1
+-- ts-helpers@1.1.2
+-- ts-node@4.1.0
+-- tslint@5.9.1
+-- typescript@2.6.2
`-- zone.js@0.8.20

```

Browser:

- Chrome (desktop) version 65.0.3325.181
- Firefox version 55.0.3 
- Edge version 38.14393.0.0

System:
- TypeScript version: 2.8.1
- Node version: 8.10
- Platform:  Windows

**Comment by danielkaradachki** [comment]
Thank you for the bug report. The problem should already be fixed in the [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version of the package:
https://www.telerik.com/kendo-angular-ui-develop/components/grid/editing/custom-reactive-editing/

**Comment by tsvetomir** [comment]
Published in v3.1.0

**Comment by develop-algoritma** [comment]
Thank you very much for the response!

**Comment by shreenil** [comment]
I am having same issue in v3.5.0
