### ISSUE TITLE
api docs: Info for window close results missing

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#1463]
## I'm submitting a...
* Documentation issue or request

## Current behavior
https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowRef/#toc-close
(window/window-settings.ts)

* close(): Function
* result: Observable<WindowCloseResult>

Info how to provide a custom result is missing and would be helpful.

## Expected info

1) close(result?: any)
Allows you to close the Window through code. You can pass a result value as parameter that will be emitted in results stream.

2) result: Observable<WindowCloseResult | any>
Emits events when the Window is closed. Value is of type WindowCloseResult if window was closed through the Close button of the title bar or the value provided in close(result) function call.

## Question

If there's something missing in your docs I could write it to our internal confluence or post it as an issue here. Are you interested in those issues?

**Comment by Raisolution** [comment]
API description has been updated.
