### ISSUE TITLE
Provide Before- and BeforeEqFilterOperatorComponent similar to the After- and AfterEq

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1466]
Currently there are [AfterFilterOperatorComponent](https://www.telerik.com/kendo-angular-ui/components/grid/api/AfterFilterOperatorComponent/) and [AfterEqFilterOperatorComponent](https://www.telerik.com/kendo-angular-ui/components/grid/api/AfterEqFilterOperatorComponent/) components, but no Before- and BeforeEq- counterparts.

Perhaps we should provide such filter operator components too for consistency.

**Comment by rkonstantinov** [comment]
Available in v3.1.0 of the `kendo-angular-grid` package.
