### ISSUE TITLE
kendo-angular-grid 3.0.0 showing Clear filter icon always

### ISSUE THREAD

**Issue by srijuvr** [telerik/kendo-angular#1469]
## kendo-angular-grid 3.0.0 showing Clear filter icon always

kendo-angular-grid 3.0.0 showing Clear filter icon always

## Current behavior
* kendo-angular-grid 3.0.0 showing Clear filter icon always

## Expected behavior

* Display the clear filter icon only when we have given value for filter.
## Minimal reproduction of the problem with instructions

  1. Create a page
 2. place a kendo grid with  [filter]="state.filter" and  [filterable]="true"

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by tsvetomir** [comment]
I tried reproducing this issue in [a plunkr](https://plnkr.co/edit/5gb6ke5Z9DMFkakQTf4w?p=preview), but the clear icon does not appear when the filter is bound to `undefined` or `null`. Perhaps I'm missing something?
