### ISSUE TITLE
How to change angular kendo UI RTL Dynamically

### ISSUE THREAD

**Issue by afsalcodehack** [telerik/kendo-angular#1471]
```
import {RTL } from '@progress/kendo-angular-l10n'
@NgModule({
  .......
  .........
,providers: [{provaider: RTL , useValue: true}] // i need to change true or false dynamically depands on localstorage values

})
```

i want to change RTL value dynamically i cannot use any function in useValue property how do i achieve this

**Comment by tsvetomir** [comment]
There's a [preliminary support](https://www.telerik.com/kendo-angular-ui-develop/components/localization/messages/#toc-updating-messages-dynamically) for dynamic messages/text direction changes in the develop version of the Localization package.

Please note that it works via the [Message Service](https://www.telerik.com/kendo-angular-ui-develop/components/localization/messages/#toc-using-the-message-service). You call the `notify` method of the base service class and pass the new RTL token value. If you're not actually translating the messages, you can implement a stub `get` method:

```ts
export class MyMessageService extends MessageService {
  public get(key: string): string {
    return undefined;
  }
}
```

See [plunkr](https://plnkr.co/edit/EOFoxuwc6ooUm5Ctho2q?p=preview) for a runnable demo.

**Comment by afsalcodehack** [comment]
@tsvetomir thanks working well

**Comment by ShuaibKunji** [comment]
> There's a [preliminary support](https://www.telerik.com/kendo-angular-ui-develop/components/localization/messages/#toc-updating-messages-dynamically) for dynamic messages/text direction changes in the develop version of the Localization package.
> 
> Please note that it works via the [Message Service](https://www.telerik.com/kendo-angular-ui-develop/components/localization/messages/#toc-using-the-message-service). You call the `notify` method of the base service class and pass the new RTL token value. If you're not actually translating the messages, you can implement a stub `get` method:
> 
> ```ts
> export class MyMessageService extends MessageService {
>   public get(key: string): string {
>     return undefined;
>   }
> }
> ```
> 
> See [plunkr](https://plnkr.co/edit/EOFoxuwc6ooUm5Ctho2q?p=preview) for a runnable demo.

+1 for the plunkr link. Was able to make it work, thanks!
