### ISSUE TITLE
Jasmine  code coverage fails!

### ISSUE THREAD

**Issue by snspvd** [telerik/kendo-angular#1473]
Please find the below code,how can i mock the highlighted code in jasmine.It fails in code coverage!
```
public RowsaveHandler({sender,formGroup,rowIndex})
 {
       **if (formGroup.valid) {
  this.service.create(formGroup.value);
  sender.closeRow(rowIndex);**
       }
 }
```

**Comment by tsvetomir** [comment]
Please, open a support ticket for assistance with setting up your project. This repository is meant for reporting issues with the components.
