### ISSUE TITLE
ComboBox does not correctly bind to FormControl (without some mystery dependency?)

### ISSUE THREAD

**Issue by thejohnfreeman** [telerik/kendo-angular#1474]
# Bug report

## Current behavior

I'm trying to bind a ComboBox to a Reactive FormControl using the `[formControl]` directive. It works for the initial binding, but does not update when the control updates.

## Expected behavior

When I click the "Choose Male" button, it calls `choose(1)`, which sets the value of the FormControl `myForm.controls.gender`. The ComboBox should reflect that new value (just like the `<p>` above it does).

## Unexpected Twist

If you try this same example *on the Kendo site*, **it works!** Navigate to [Components / DropDowns / ComboBox / Forms Support](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/forms/), scroll down to [Reactive Forms](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/forms/#toc-reactive-forms), open the Plunkr with "RUN CODE", then paste the exact same contents of `app/app.component.ts` (quoted below), and it works. I suspect there is some mystery dependency missing on Plunkr that isn't diagnosed in the console, but it's anybody's guess.

```ts
import { Component } from '@angular/core';

import {
    FormsModule,
    ReactiveFormsModule,
    FormGroup,
    FormControl
} from '@angular/forms';

@Component({
  selector: 'my-app',
  template: `
    <form [formGroup]="myForm">
        <div class="example-config">
            <p>The form is valid: <strong>{{myForm.controls.gender.valid}}</strong></p>
            <p>The form.gender value is: <strong>{{myForm.controls.gender.value}}</strong></p>
        </div>
        <label>
            Select gender
            <kendo-combobox
                [formControl]="myForm.get('gender')"
                [data]="genders"
                [textField]="'text'"
                [valueField]="'value'"
                required
            >
            </kendo-combobox>
        </label>
        <button (click)="choose(1)">Choose Male</button>
    </form>
  `
})
export class AppComponent {
    public genders: Array<{ text: string, value: number }> = [
        { text: "Male", value: 1 },
        { text: "Female", value: 2 },
        { text: "Other", value: 3 }
    ];

    public myForm: FormGroup = new FormGroup({
        gender: new FormControl(2)
    });
  
    public choose (value: number): void {
        //this.myForm.get('gender').setValue(value)
        this.myForm.patchValue({ gender: value })
    }
}
```

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/D7qqBfVrFqu0ZoQpstY1?p=preview

## Environment

Browser:
- Chrome (desktop) version 65.0.3325.181 (Official Build) (64-bit)

**Comment by thejohnfreeman** [comment]
Did this get the question tag because it has a question mark in the title? I think it's a bug. Has anyone tried the reproduction?

**Comment by ggkrustev** [comment]
@thejohnfreeman, you need to enable the `valuePrimitive` property, that will tell the component to use primitive values.

https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/value-binding/#toc-primitive-values-from-object-fields

Check the updated example:
https://plnkr.co/edit/aP9HEsn0jmINxwKqCaYE?p=preview

Will close the thread, as it doesn't report a bug. Let me know if I am missing something.

**Comment by tsvetomir** [comment]
Related issue #1484
