### ISSUE TITLE
Dateinput optional auto correction of days in the month count.  

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1475]
## I'm submitting a...

* Suggestion for improvement ( found by user )

## Current behavior
When we have format dd/MM/yy ( days before months ) and we have initial date 05/04/2018 we can not type 31/05/2018 starting from days since dateinput will correct 31, since April-04 has 30 days.

## Expected behavior
We would like suggest this type of auto correction to be applied optionally. 

## Minimal reproduction of the problem with instructions

1. Open this demo [https://plnkr.co/edit/k7DcZAKKuUn2dEu6uwHf?p=preview](url)
2. Try to enter date 31/05/2018 on one pass.

## What is the motivation or use case for changing the behavior?

We need more fine grained setting for auto correction in this use case. 
## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by fabriziodebortoli** [comment]
dd/MM/yy ( days before months ) is the most used format. [Date format by country](https://en.wikipedia.org/wiki/Date_format_by_country)

Autocorrection is very good for User Experience, please adapt it to that format, not only implement possibility to apply it optionally

**Comment by GianlucaAnedda** [comment]
We're having the same problem, lots of customers type dates instead of picking them, the result of auto correction in those cases can be pretty confusing. In the mentioned format typing 31 while the month is still a 4 is not a mistake, if you're planning to type 5 as month after. It'd be great to be able to apply validation on demand (on blur, for example).

**Comment by ipeshev** [comment]
Closed in favor of https://github.com/telerik/kendo-angular/issues/1366
