### ISSUE TITLE
Multiselect doesn't open dropdown after cursor hovers over previous selection

### ISSUE THREAD

**Issue by yanbu0** [telerik/kendo-angular#1477]
## I'm submitting a...

* Bug report 

## Current behavior

If you add a selection to the multiselect, then hover over the new selection, then click into the multiselect to add another selection, the click doesn't register and the dropdown does not open.  

Note: this only happens with new selections.

## Expected behavior

Dropdown opens.

## Minimal reproduction of the problem with instructions

1. Go to https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/
2. Click in the multiselect, add "Cricket"
3. Hover your mouse over the newly added "Cricket" selection then drag the mouse to the right inside the multiselect box and click into it as if you are attempting to add an addition selection.
4. Box will not open

## What is the motivation or use case for changing the behavior?

Its broke

## Environment

Package versions:

```
"@progress/kendo-angular-dropdowns": "^2.1.0",
```

**Comment by DieterDS1983** [comment]
Hi,

We have the same issue here.

There is a textbox after the last item in the multiselect.
If you click inside the textbox, the click event is not raised. When you click in the multiselect behind the textbox, it is working.

**Comment by tsvetomir** [comment]
Fixed in v3.0.3
