### ISSUE TITLE
Issue with Navigation in angular kendo grid?

### ISSUE THREAD

**Issue by snspvd** [telerik/kendo-angular#1478]
Tab/Shift+Tab navigation is not working in grid. please look into below plunker to get my issue.
https://plnkr.co/edit/4Bp5k9XPhDMqlpXD5yxI?p=preview

**Comment by tsvetomir** [comment]
Looks like a duplicate of #1479

**Comment by Raisolution** [comment]
Closing this as a duplicate of #1479.
