### ISSUE TITLE
Tabbing across grid cells not working in kendo grid with Angular 4

### ISSUE THREAD

**Issue by DineshThangella** [telerik/kendo-angular#1479]
Hi,

I have a kendo grid in my application where I need the tabbing functionality across the cells. The grid works fine with the navigation keys(up, down, left and right arrow keys) with [navigable]="true" property, but could not find any such property for navigating through tab key.
Thanks in advance.

**Comment by rusev** [comment]
The `Grid` component doesn't have such functionality yet. This might be achieved if we export enough public API for keyboard navigation feature. //c.c. @tsvetomir  

I have one supplementary question though - do you expect this to work in the case of editable Grid, as in [Kendo UI for jQuery](https://demos.telerik.com/kendo-ui/grid/editing), or to simply highlight the next cell?

**Comment by DineshThangella** [comment]
yes @rusev we need editable grid on tab and can you please elaborate on **This might be achieved if we export enough public API for keyboard navigation feature**  what exactly it means

**Comment by tsvetomir** [comment]
What @rusev meant is that we don't yet have support for this scenario baked into the API. We plan to add it as a customization scenario alongside with new events/methods, if necessary to make it work.

As some background, the default Tab behavior is based on the [WAI-ARIA recommendations](https://www.w3.org/TR/wai-aria-practices-1.1/#grid) for accessibility. The Grid is included as a single tab stop on the page to allow users to easily navigate the page landmarks without getting stuck in the (potentially thousands) cells.

**Comment by tsvetomir** [comment]
An example directive that demonstrates how to move the focus to the next cell on Tab is included in the [develop version](https://www.telerik.com/kendo-angular-ui-develop/components/grid/keyboard-navigation/#toc-controlling-the-focus) of the documentation.

It relies on a set of 4 new methods, also included in the develop version - `focus`, `focusCell`, `focusNextCell` and `focusPrevCell`.

I'll appreciate any feedback.

**Comment by tsvetomir** [comment]
Published on the [official site](https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/#toc-controlling-the-focus).
