### ISSUE TITLE
Calendar: Today's date loses its k-today class

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1480]
If the Calendar is bound to a new Date() and then another date is selected, the "today" date is not marked as such:

[https://plnkr.co/edit/4S95j0DWwjbnukKRMvbC?p=preview](https://plnkr.co/edit/4S95j0DWwjbnukKRMvbC?p=preview)

Temporary workaround - bind the component to a new Date instance, created by calling the constructor with year, month and date arguments:

[https://plnkr.co/edit/1F2QVxmoKj7bBodpZmLC?p=preview](https://plnkr.co/edit/1F2QVxmoKj7bBodpZmLC?p=preview)

**Comment by ggkrustev** [comment]
The fix is available in the DEV release of the package. To check it out, just run 
`npm i @progress/kendo-angular-dateinputs@dev`

**Comment by ggkrustev** [comment]
Fixed in `v3.4.0`. Please install the latest package to see the changes.

`npm i @progress/kendo-angular-dateinputs@3.4.0`
