### ISSUE TITLE
aggregateBy does not aggregate when field has a dot in it

### ISSUE THREAD

**Issue by theredpea** [telerik/kendo-angular#1485]
## I'm submitting a...

* Bug report 

## Current behavior
aggregateBy does not sum if `field` contains a dot; the resulting sum is only the value of *one* of the datum; not the *sum* of the value for *all* data

## Expected behavior
aggregateBy resulting sum value is correct (i.e. sum across all data (in the group)), even if `field` contains a dot;

## Minimal reproduction of the problem with instructions
In this plunker, I have two data each has a property `{ sale : { amount : 1 } }` ; the sum (`aggregateBy(data, [{
aggregate: 'sum', field : 'sale.amount' }])`) should be `2`, but the resulting aggregation value is only `1`:
https://plnkr.co/edit/mnlBlesVkliR268Px7Gl?p=preview

The same issue affects me if I use groupBy with an aggregate.

I think the issue is in `transducers.js`, in the `aggregatesCombinator` function:

- the function *gets* the previous `state` (line 97, 101) using `getter` (from `accessor.js`). `getter` will *only* interpret the dot in `'sale.amount'` as a "nested property" operator, _and look for `state.sale.amount`_). **That property will never exist, because the next step doesn't `set` that nested property**
- the function then *sets* the current `state` (line 106) using bracket notation (which will not try to interpret the dot; _i.e. set `state['sale.amount']`_ ). **The `getter` will never find this value, because the `getter` doesn't look for that bracket property**

## What is the motivation or use case for changing the behavior?
My data is an array of FormGroups; I must access one of the values dot notation: `value.amount` (analogous to my example `sale.amount`).  I also must aggregateBy and sum across this amount.

## Options to workaround
I can do data pre-processing just map/assign `datum.sale.amount` to a single field on the root of datum: `datum.sale_amount`. Because  I don't use "dot" notation  there is no ambiguity between `getter(...)` vs `set with bracket notation`. 
But I don't want to create a new property, because it's redundant (already have existing property), and my datum is a `FormGroup`, and I don't want to modify `FormGroup` object  as if it were an arbitrary `any` object.

## Options to fix
1. Don't use the fancy `getter` function , just use bracket notation : `state['sale.amount']` 
  - `getter` is overkill in the `aggregatesCombinator` function : your users already expect the resulting `state` object to have *set* literal field like `aggregates['sale.amount'].sum`, so just *get* those field names using regular bracket notation `state['sale.amount']`
2. `getter` function will *also* check for literal field namesi.e. bracket notation  (if it doesn't find a value using the nested property names)
3. A `setter` function to complement the `getter` function; i.e. `setter` which can interpret dots and set multiple levels of property

**Comment by rkonstantinov** [comment]
Hey @theredpea, 
Thanks for the detailed report. We manged to address the behavior in question. The fix is available with v1.3.0 of the `kendo-data-query` package.

**Comment by theredpea** [comment]
Oops, I should've more current versions :)  Thank you @rkonstantinov
