### ISSUE TITLE
File selection/explorer window does not disappear after drag and drop

### ISSUE THREAD

**Issue by Kevat** [telerik/kendo-angular#1486]
## I'm submitting a...

* Bug report 

## Current behavior
The file selection/explorer window does not disappear when a file is dragged from the selection/explorer window and dropped on the Kendo Upload

## Expected behavior
Once the files are dropped on the Kendo Upload, the file selection/explorer window should disappear

## Minimal reproduction of the problem with instructions
Plnkr: https://embed.plnkr.co/ekWaU9n4cdj1G7h4zO4N/

1. Click on "Select Files". A file selection/explorer window should open
2. Drag and drop a file from this window on to the Kendo Upload
3. The file selection/explorer window remains open even after the files have finished uploading

## What is the motivation or use case for changing the behavior?
The end users should have a smooth experience. If they have already selected and dragged/dropped files, they should not have to manually close the selection/explorer window. This window should be closed automatically.

## Environment

Package versions:
@ progress/kendo-angular-dialog: ^3.4.0

```

```

Browser:

- Chrome (desktop) version  66.0.3359.117
- IE version 11
- IE version 10

System:
- TypeScript version: 2.5.3
- Node version: 8.9.4
- Platform:  Windows

**Comment by Raisolution** [comment]
Hi @Kevat,

This is a browser behavior and we have no control over the "File selection window". You could observe the same behavior by adding a regular <input type="file" /> element to the page and dragging a file to it.
