### ISSUE TITLE
Missing reference of UploadProgressEvent in @progress/kendo-angular-upload

### ISSUE THREAD

**Issue by yangzuo0621** [telerik/kendo-angular#1487]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

When use `import { UploadProgressEvent } from '@progress/kendo-angular-upload';` statement to import UploadProgressEvent, the intelligence gives error `[ts] Module '"d:/Projects/Tool/ClientApp/node_modules/@progress/kendo-angular-upload/dist/es2015/index"' has no exported member 'UploadProgressEvent'.`, which result in the compile error of `error TS2305: Module '"D:/Projects/Tool/ClientApp/node_modules/@progress/kendo-angular-upload/dist/es2015/index"' has no exported member 'UploadProgressEvent'.`. 

And find that in the `@progress/kendo-angular-upload/dist/es2015/main.d.ts`, there is no export of  `UploadProgressEvent`. Whether add UploadProgressEvent into it.

## Expected behavior

`import { UploadProgressEvent } from '@progress/kendo-angular-upload';` statement works just like the official document .

## Environment

Package versions:

```
npm i @progress/kendo-angular-upload@3.0.3
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Raisolution** [comment]
Hi @yangzuo0621,

thank you for noticing this. The exported `UploadProgressEvent` is available in `v4.0.0-dev.201804260838` and will be present in the next official release too.
