### ISSUE TITLE
[ComboBox] filterChange is not thrown when component blured

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1488]
## I'm submitting a...

* Bug report 

## Current behavior
Combobox is not throwing filterChange event when value is invalidated on blur.

## Expected behavior
It should throw filterChange event on blur.

## Minimal reproduction of the problem with instructions
1. Open this [plunk sample](https://plnkr.co/edit/TRfIwBoAZ0iMl2zIzrvB?p=preview)
2. Delete part of initial value and blur the component.
3. Open the popup only one item is there and in console you can see filterChange is not thrown when blured.

## Environment

Package versions:

```
broken in v3.0.0-dev.201804050943
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by dimitar-pechev** [comment]
The fix is included in **v3.4.0** of the `@progress/kendo-angular-dropdowns` package.
