### ISSUE TITLE
Missing reference of SelectionSettings in @progress/kendo-angular-treeview

### ISSUE THREAD

**Issue by unciax** [telerik/kendo-angular#1491]
## I'm submitting a...
* Bug report

## Current behavior

Got an error in the line
```typescript
import { SelectionSettings } from '@progress/kendo-angular-treeview';
```
`Module '"/Users/unciax/WorkSpace/Study/test-kendo-treeview/node_modules/@progress/kendo-angular-treeview/dist/es2015/index"' has no exported member 'SelectionSettings'.`
## Expected behavior

`import { SelectionSettings } from '@progress/kendo-angular-treeview';` statement works just like the official document .
## Minimal reproduction of the problem with instructions

1. Create a project with Angular CLI
```
ng new test-kendo-treeview
```
2. Install kendo-angular-treeview by following the [installation instruction ](https://www.telerik.com/kendo-angular-ui/components/treeview/)

3. import SelectionSettings in app.component.ts
```typescript
import { SelectionSettings } from '@progress/kendo-angular-treeview';
```

## Environment

Package versions:

```
@progress/kendo-angular-treeview@2.1.3
```

Browser:

- Firefox version 59.0.2

System:
- TypeScript version: 2.5.3
- Node version: 9.3.0
- Platform:  Mac

**Comment by rkonstantinov** [comment]
Indeed, there is no `SelectionSettings` type exposed by the `kendo-angular-treeview` package.

The type used by TreeView's [Select directive](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/api/SelectDirective/) is named [SelectableSettings](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/api/SelectableSettings/)

**Comment by unciax** [comment]
It looks like [document](https://www.telerik.com/kendo-angular-ui/components/treeview/selection/#toc-multiple-selection-mode) and plunker need to update.

**Comment by rkonstantinov** [comment]
Thanks for noticing this and bringing it to our attention. We will fix the documentation.
