### ISSUE TITLE
Docs: timepicker plunkr 404 not found

### ISSUE THREAD

**Issue by crh225** [telerik/kendo-angular#1492]
In chrome, go here
https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/formats/

click here
![image](https://user-images.githubusercontent.com/19475195/39253052-9c81c4f6-486c-11e8-9c40-323a62492270.png)

you get redirected to 
![image](https://user-images.githubusercontent.com/19475195/39253084-ab81bf60-486c-11e8-8051-e40d53106d69.png)

**Comment by Raisolution** [comment]
Hi @crh225,

The example is opened correctly now on our end. Probably it was a temporary problem on the plunkr end.
