### ISSUE TITLE
How can I extend existing Kendo Ui components (best practices?)

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#1493]
* Documentation issue or request

How can I extend existing components, or what are the best practices to extend existing components with addional features.

Like a helper directive which gives me the ability to add a "select all" Header Template to my multiselect Dropdown, so that I don't need to write the code for every single mutliselect

Like: https://stackoverflow.com/questions/50029169/replace-ng-template-within-a-component-with-custom-directive

**Comment by tsvetomir** [comment]
Extending built-in functionality should be done with custom directives that work with the public API. Avoid sub-classing components. That's the general advice.

Please, hit us with a support ticket if you need assistance with a particular scenario. Or a bug report here, if the API doesn't do what it's supposed to do.

If you feel that the functionality is generic enough - as with the scenarios described above - please vote for it on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback).
