### ISSUE TITLE
[Question] How to globally modify grid export excel ?

### ISSUE THREAD

**Issue by baiyunchen** [telerik/kendo-angular#1495]
When exporting Excel, we want to format the date type data. But we do not want developers to pay attention to the formatting of the date.
So,We want to develop a directive similar to kendoGridExcelCommand. 
Can anyone tell me what to do?

**Comment by danielkaradachki** [comment]
The excel export uses the 'mm-dd-yy' format for JS Date objects by default. The format can be overridden per column via the [excel columns](https://www.telerik.com/kendo-angular-ui/components/grid/export/excel-export/#toc-customizing-exported-columns) [cellOptions](https://www.telerik.com/kendo-angular-ui/components/excelexport/cells/#toc-data-cells) [format](https://www.telerik.com/kendo-angular-ui/components/excelexport/api/CellOptions/#toc-format) option. Changing the default format globally is not currently supported. We will consider it for future versions.

Also please note that this issue tracker is for bug reports only. If you have questions regarding implementation scenarios or configuration please open a support ticket.
