### ISSUE TITLE
Deselecting of items in MultiSelect malfunctions when having many items

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1498]
After some selecting and deselecting of items (deselect items from somewhere in the middle not the last ones) the deselection stops to function as expected.

Check the following example:

[https://stackblitz.com/edit/angular-mtegpw](https://stackblitz.com/edit/angular-mtegpw)

**Comment by valchev** [comment]
@svetq I suspect that the issue occurs because values in the data are not unique.

Each of the DropDowns components is designed to operate with **unique** values, we do not support scenarios where data contains duplicated values.

Please try to replicate the issue with unique values.
