### ISSUE TITLE
Material theme for kendo components

### ISSUE THREAD

**Issue by mhmo91** [telerik/kendo-angular#150]
Hello awesome team of telerik,
I'm submitting a feature...
Currently you guys support kendo default theme and bootstrap theme, since MD2 will be a base for most of the ng2 projects, we as developers need to keep things consistent in design, so, Are u planning to release a theme for Kendo components that is Material-Design alike, doesn't have to follow the exact specs but at least if i'm using MD, it won't feel  odd to find a kendo component within a form of material components..
Thanksss

**Comment by yordanov** [comment]
Hello @mhmo91 ,

Material UI is on our radar and we will have it in our action plans once we have the beta bits shipped by the end of Jan'17. 

We consider Material Design theme a major effort, as we need to fully comply with the [design specs](https://material.io/guidelines/). Because, not only "it won't feel odd to find a kendo component" within a Material form, but rather it is an expected behavior by default.

**Comment by MateMahinKhan** [comment]
Hi telerik, 

Any update regarding this?

**Comment by lelong37** [comment]
+10, I second @MateMahinKhan question, is there anyway the team could let us know when this will be on the Kendo road map? Even if it's just a rough estimate? Our team is building out a fairly large platform for Fortune 500 company, and it would make it extremely helpful for 100% enterprise wide adoption for Kendo UI if we if we could provide a rough time frame of when this (Kendo Google Material Design)  could potentially get released.

**Comment by petyosi** [comment]
Thank you very much for your interest @lelong37. We are going to start exploring the Google Material Design implement immediately after shipping the Bootstrap integration.

**Comment by djarekg** [comment]
So is it reasonable to say that it would be no earlier than mid-summer before an initial release is available?

**Comment by petyosi** [comment]
It is to early to give a timeline, given the complexity of the design language. Unlike other themes, material includes some specific interaction (ripples, form labels, etc).

**Comment by cime** [comment]
Anything new on this one? Is it in progress?

**Comment by pantonis** [comment]
I was thinking to purchase a license but lack of the material theme made me change my mind.

**Comment by tsvetomir** [comment]
Work has been ongoing for a while now, but there's not much to show at the moment. We intend to release a **preview** in about a month.

This initial release will cover mostly form components - buttons, inputs and labels. We'll move to the larger components once we're happy with the basics - effects and dimensions.

**Comment by pantonis** [comment]
:(

**Comment by tsvetomir** [comment]
The initial version of the [Material theme](http://www.telerik.com/kendo-angular-ui/components/styling/theme-material/) has been published. Issues can be filed in its [source repo](https://github.com/telerik/kendo-theme-material).

Styling for additional components is on [the roadmap](http://www.telerik.com/kendo-angular-ui/roadmap/):
> We will also continue our to work on our support for the Material theme. We already have initial support, but we will continue to include more components that can be styled by this theme.
