### ISSUE TITLE
Datepicker calendar is empty in Safari for iPad with iOS < v9

### ISSUE THREAD

**Issue by gbhive** [telerik/kendo-angular#1501]
Datepicker calendar is empty in Safari for iPad with iOS < v9
We use https://www.browserstack.com for testing in different iPads.
Bug was catch in our application, but it  can reproduce on your demo 
https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/

iPad Air 2 (iOS 8) - https://s18.postimg.cc/npxspzpeh/screenshot_1130.png
iPad 4 (iOS 7)- https://s18.postimg.cc/n0f0dt4c9/screenshot_1131.png
etc 
But in iOS 9 and later it works fine - for example https://s18.postimg.cc/os7z8tqax/screenshot_1132.png

**Comment by ggkrustev** [comment]
Hi @gbhive,

Thanks for the report. In general, we comply with the Angular browser support, which covers 2 most recent major versions of iOS and Safari.

https://angular.io/guide/browser-support

Nevertheless, we will look into the case and will post an update here if have more details to offer.

I will close the thread for now as we cannot suggest any workaround for the older unsupported iOS/Safari versions.
