### ISSUE TITLE
File to import not found or unreadable: chat.

### ISSUE THREAD

**Issue by systemmetaphor** [telerik/kendo-angular#1502]
## I'm submitting a:
* Bug report

## Current behavior
When adding the boostrap theme I get this error:
File to import not found or unreadable: chat.

## Expected behavior
The scss file whould compile to css successfully.

## Minimal reproduction of the problem with instructions
A) Use npm package in angular/cli project and include the file in the styles.scss using the @import "~@progress/kendo-theme-bootstrap/scss/all";
OR
B) Include the file in .angular-cli.json styles section

Package versions:
`"@progress/kendo-theme-bootstrap": "^2.12.0"`

Browser:
System:
- TypeScript version: 2.8
- Node version: v8.9.1
- Platform:  Windows

The file chat.scss is not present in the npm package. Please verify that.

**Comment by Felx-B** [comment]
Same error here, seems rolling back to 2.11.11 solves the issue, waiting for the fix

**Comment by gyoshev** [comment]
The issue has been fixed in `@progress/kendo-theme-bootstrap@2.12.1`.
