### ISSUE TITLE
Right mouse click opens the MultiSelect's drop down

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1503]
When clicking with the right mouse button the MultiSelct opens its drop down.

Check the following example:

[https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/)

**Comment by ipeshev** [comment]
Fixed in v3.0.3-dev.201808011119

**Comment by tsvetomir** [comment]
Shipped in v3.0.3
