### ISSUE TITLE
$switch-size set in switch layout scss

### ISSUE THREAD

**Issue by mudupalli** [telerik/kendo-angular#1507]
Current behavior
We are using $switch-size in our variables.scss to set our value and let kendo switch layout.scss calculate based on that. During build , it was using the value we set and generate css based on that. We upgraded to angular/cli: "^1.7.4", RxJS 5.5 "rxjs": "^5.5.10" and "kendo-angular-inputs": "^1.5.0". Now during build , it does not honor the $switch-size we set and uses the default value that switch\_layout.scss $switch-size: 3em !default to generate css.

Expected behavior
Honor  $switch-size in our variables.scss and generate css based on that.

**Comment by gyoshev** [comment]
We have recently changed the `$switch-size` behavior in the theme (in [this commit](https://github.com/telerik/kendo-themes/commit/277ca4fcc4c8a84bd8fd7e48df27812d5049428f)). 

![image](https://user-images.githubusercontent.com/90405/39614516-216e6f30-4f79-11e8-9ae3-49a82bc80db6.png)

Previously, the variable value was used as the half-size of the switch component, which made it confusing to use. Try doubling the variable value, and see if the problem persists.

**Comment by mudupalli** [comment]
ok, doubling the value in our app variable $switch-size worked. Thanks.
