### ISSUE TITLE
@jszip dependency issue

### ISSUE THREAD

**Issue by ranjith88** [telerik/kendo-angular#1509]
## I'm submitting a...

* Documentation issue or request

## Expected behavior

I need to Bind a Kendo grid with three columns.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) Version 66.0.3359.139 (Official Build) (64-bit)

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:  <--Windows -->

I am trying to add Kendo Grid(Angular) to my sample solution. I am facing the below error

**Homepage:26 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:28939/node_modules/jszip/dist/jszip

zone.js:2969 GET http://localhost:28939/pako/dist/pako_deflate 404 (Not Found)**
![image](https://user-images.githubusercontent.com/38937339/39565076-398761b2-4ed4-11e8-9a15-c57458b4237c.png)

Below is my system.js file 

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'client/app',
            'jszip': 'node_modules',
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            'jszip':'npm:jszip',

        // Kendo UI for Angular scopes 
        '@progress': 'npm:@progress',
        '@telerik':'npm:@telerik',

      // other libraries
      'rxjs':                      'npm:rxjs',
        'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
        'tslib': 'npm:tslib/tslib.js',
        '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        defaultExtension: 'js',
        meta: {
          './*.js': {
            loader: 'client/systemjs-angular-loader.js'
          }
        }
        },

      rxjs: {
        defaultExtension: 'js'
        },
      // Kendo UI for Angular packages
        'npm:@progress/kendo-angular-buttons': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },

        'npm:@progress/kendo-angular-dateinputs': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-dropdowns': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-grid': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-pdf-export': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-inputs': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-intl': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-l10n': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },

        'npm:@progress/kendo-angular-excel-export': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-popup': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-angular-resize-sensor': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },

        'npm:@progress/kendo-data-query': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-date-math': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-drawing': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-file-saver': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-intl': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-ooxml': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@progress/kendo-popup-common': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@telerik/kendo-draggable': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@telerik/kendo-intl': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        },
        'npm:@telerik/kendo-inputs-common': {
            main: './dist/npm/main.js',
            defaultExtension: 'js'
        }
          }
  });
})(this);

Package.json
---------------

 "dependencies": {
    "@angular/animations": "~5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/compiler-cli": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/platform-server": "~5.0.0",
    "@angular/router": "~5.0.0",
    "@angular/upgrade": "~5.0.0",
    "@progress/kendo-angular-buttons": "^4.0.0",
    "@progress/kendo-angular-dateinputs": "^3.0.0",
    "@progress/kendo-data-query": "^1.3.0",
    "@progress/kendo-drawing": "^1.5.3",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-grid": "^3.1.0",
    "@progress/kendo-angular-inputs": "^3.0.0",
    "@progress/kendo-angular-intl": "^1.4.0",
    "@progress/kendo-angular-l10n": "^1.1.0",
    "@progress/kendo-angular-popup": "^1.1.1",
    "@progress/kendo-theme-default": "^2.38.2",
    "angular-in-memory-web-api": "~0.5.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.0",
    "zone.js": "^0.8.4"
     
   
  },

Please help me out on this. I just want to binf 3 columns in my grid.

 <kendo-grid [data]="gridData" [height]="410">
        <kendo-grid-column field="UserName" title="UserName" width="40">
        </kendo-grid-column>
        <kendo-grid-column field="Email" title="Email" width="250">
        </kendo-grid-column>
        <kendo-grid-column field="isApproved" title="isApproved">
        </kendo-grid-column>
    </kendo-grid>

The data is coming fine from the backend. Please let me know if i need to provide any other information.

Also i have added Kendo button from sample example and it is working fine.

**Comment by danielkaradachki** [comment]
The dependency is required for the excel export feature. Please check the [example](https://github.com/telerik/kendo-angular-quickstart) linked [here](https://www.telerik.com/kendo-angular-ui/components/installation/system-js/) which demonstrates how to configure all dependencies.

**Comment by danielkaradachki** [comment]
Right, but systemjs needs the configuration no matter if it is used or not.
