### ISSUE TITLE
[Chrome] Focusing on a window partially under the screen forces a scroll down

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1511]
## I'm submitting a...

* Bug

## Current behavior

When you focus a window that is partially out of the screen, the window will jump to the middle of the screen or the container will automatically scroll to contain the whole window.
(only if you focus by clicking on the titlebar)

## Expected behavior
When you focus the window, it should not move and the container shouldn't scroll to it.

## Minimal reproduction of the problem with instructions

https://www.telerik.com/kendo-angular-ui/components/dialogs/window/

1- Move the window to the bottom of the container
2- Click on the container to lose the focus on the window
3- Click on the window's titlebar, it will jump to the middle of the container

Actually, it jumps to the middle because the container scrolls to the window's position.

## What is the motivation or use case for changing the behavior?

UX improvements. 

## Environment

Browser:

- Chrome (desktop) Version 66.0.3359.139 (Official Build) (64-bit) **not working**
- Firefox version 53.0.2 (32-bit) **Working as intended**
- Edge version 41.16299.248.0 **Working as intended**

System:
- Platform:  windows

**Comment by Raisolution** [comment]
Hi @Neaco,

The observed browser behaviour is expected. This is how Chrome handles focusing elements which are not fully visible i.e. tries to [scroll them into view](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView). This is not Window specific and could be observed with any partially hidden focusable element.
