### ISSUE TITLE
Columns order not respected when reorderable Grid is exported to Excel

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1512]
When the user reorders Grid columns and exports the Grid to Excel, the order of the columns in the exported workbook is the same as the initial one (before reordering).

**Comment by ipeshev** [comment]
Fixed in v3.5.0-dev.201805311315

**Comment by tsvetomir** [comment]
Fix released in v3.5.0 of the `@progress/kendo-angular-grid` package.
