### ISSUE TITLE
Draw custom Plot Bands behind the series

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#1514]
## I'm submitting a...
* Bug report 

## Current behavior
Default Plot Bands implementation works fine, but it doesn't allow to highlight a specific range of two numeric axes (e.g. in Scatter chart). Custom Plot Bands described in the [documentation](https://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/plot-bands/#toc-custom-plot-bands) are unsuitable because they are drawn over the series.

## Expected behavior
There should be a way to draw custom Plot Bands behind the series. For instance, it could be beforeRender event emitter in the kendo-chart component.

## Minimal reproduction of the problem with instructions
Here is a plank with an example: [link](https://plnkr.co/edit/YjEETz3ZNC8OfLeAri9C?p=preview). Notice that points behind the highlighted area are inaccessible(no tooltips and hover states).

**Comment by tsvetomir** [comment]
That's a good question - it's possible to place the plot band behind the series by prepending it in the [pane](https://www.telerik.com/kendo-angular-ui/components/charts/api/ChartComponent/#toc-findpanebyindex) visual element. See the [updated plunkr](https://plnkr.co/edit/H1EpNoeFb1xUgHcBbR8h?p=preview).

**Comment by vbakavets** [comment]
That works great, thank you! I'm closing the issue.
