### ISSUE TITLE
Group footers are not displayed when groups are collapsed

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1515]
Group footers are not displayed when groups are collapsed and using [scrollable]="'none'".

Check the following example:

[https://stackblitz.com/edit/kendo-ui-extensions-1zxbxz](https://stackblitz.com/edit/kendo-ui-extensions-1zxbxz)

**Comment by rkonstantinov** [comment]
This should be addressed in with `v3.2.0-dev.201805071340` version of the `kendo-angular-grid package`.
