### ISSUE TITLE
TreeView textField ignored

### ISSUE THREAD

**Issue by waltsully** [telerik/kendo-angular#1516]
## I'm submitting a...

* Bug report 

## Current behavior
 the binding of textField="< my_preferred_data_field >" has no effect in node rendering. I've been unable to get anything other than the  Caption field in [nodes] to display. My data sample below. In fact, if I remove the textField completely the TreeView still renders (including nesting). All the dojo and plnkr examples work as specified and when I remove the textField the TreeView renders as null.

## Expected behavior
I want to have a different field from my json displayed.

## Minimal reproduction of the problem with instructions
 <div #ktree class="treecontainer">
        <kendo-treeview style="font-size: inherit;"
            [nodes]="queues"
            textField="UserNetworkId"
            childrenField="Children"    
            [hasChildren]="hasChildren" 
            [children]="fetchChildren"        
            kendoTreeViewExpandable          
            [kendoTreeViewSelectable]="{ mode: 'single' }"
            [(selectedKeys)]="selectedKeys"
            [(expandedKeys)]="expandedKeys"            
            (selectionChange)="onSelectionChanged($event)" 
            (selectedKeysChange)="onSelectedKeysChanged($event)"           
        >

DATA (always the "Caption" is what renders):
[
{"NodeId":9,"Caption":"Assigned Testers","ParentId":0,"UserId":0,"UserNetworkId":"NA","Count":178,
"Children":[
  {"NodeId":4226,"Caption":"Aiste Tait","ParentId":9, "UserId":226,"UserNetworkId":"tait","Count":4,"Children":[ ] },{"NodeId":4227,"Caption":"Alan Deola","ParentId":9,"UserId":227,"UserNetworkId":"deola","Count":1,"Children":[ ] }
]

## What is the motivation or use case for changing the behavior?
desire the flexibility that is specified in the product documentation

## Environment

Package versions:
 npm ls --depth 0
tree@0.0.0 C:\Workspace\Angular\telerik\workorder
+-- @angular/animations@5.2.10
+-- @angular/cli@1.7.4
+-- @angular/common@5.2.10
+-- @angular/compiler@5.2.10
+-- @angular/compiler-cli@5.2.10
+-- @angular/core@5.2.10
+-- @angular/forms@5.2.10
+-- @angular/http@5.2.10
+-- @angular/language-service@5.2.10
+-- @angular/platform-browser@5.2.10
+-- @angular/platform-browser-dynamic@5.2.10
+-- @angular/router@5.2.10
+-- @progress/kendo-angular-buttons@4.0.0
+-- @progress/kendo-angular-dateinputs@2.2.0
+-- @progress/kendo-angular-dropdowns@2.1.0
+-- @progress/kendo-angular-excel-export@1.0.7
+-- @progress/kendo-angular-grid@3.1.0
+-- @progress/kendo-angular-inputs@2.0.0
+-- @progress/kendo-angular-intl@1.4.0
+-- @progress/kendo-angular-l10n@1.1.0
+-- @progress/kendo-angular-popup@2.2.0
+-- @progress/kendo-angular-treeview@2.1.3
+-- @progress/kendo-data-query@1.3.0
+-- @progress/kendo-drawing@1.5.3
+-- @progress/kendo-theme-bootstrap@2.11.11
+-- @progress/kendo-theme-default@2.50.0
+-- @types/angular@1.6.43
+-- @types/jasmine@2.8.6
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.106
+-- bootstrap@4.0.0
+-- codelyzer@4.3.0
+-- core-js@2.5.5
+-- jasmine-core@2.8.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@1.12.4
+-- karma@2.0.2
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@1.4.2
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- popper.js@1.14.3
+-- protractor@5.1.2
+-- rxjs@5.5.10
+-- ts-node@4.1.0
+-- tslint@5.9.1
+-- typescript@2.5.3 invalid
+-- yarn@1.6.0 extraneous
`-- zone.js@0.8.26

Browser:

- Chrome (desktop) version 66.0.3359.139 (Official Build) (64-bit)

System:
- TypeScript version: 2.8.3
- Node version: 6.11.5
npm version: 3.10.10
- Platform:  Windows 10

**Comment by ggkrustev** [comment]
Hi @waltsully, 

could you provide a runnable demo or at least the TreeView configuration? This will help us to get a better understanding of the case and find a resolution much faster.

**Comment by ggkrustev** [comment]
Hi @waltsully,

I am afraid that we won't be able to proceed with the investigation without reviewing the erroneous behavior locally. You can use any of our online demos as a base for reproduction example.

https://www.telerik.com/kendo-angular-ui/components/treeview/

I will close the thread for now. Looking forward to get more details soon.
