### ISSUE TITLE
Can't update to Angular v6

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular#1517]
I'm using the "[Angular Update Guide - 5.2 -> 6.0 for Medium Apps](https://update.angular.io/)"

I'm having an issue at step number 7. Running `ng update @angular/core` outputs an error for almost every kendo package, e.g.

    Package "@progress/kendo-angular-l10n" has an incompatible peer dependency to "rxjs" (requires "^5.0.1", would install "6.1.0").

When are you planning to address this issue?

Thanks!

**Comment by ncrawlins** [comment]
if it's vital that you upgrade to 6 right now and that you use that tool to do it, you can add --force to the ng update command and it will continue despite the telerik packages' peer dependency version ranges not matching the new angular version.

I'm really only using the grid and a couple of the inputs, but it built and seems to run without error with angular 6 despite not officially supporting it yet.

**Comment by tommykri** [comment]
I just got it to work with Angular 6 but I manually updated the angular packages with npm install and compared my project with a fresh Angular 6 project generated from ng new. I have added rxjs-compat package.

**Comment by tsvetomir** [comment]
We'll be publishing an updated version of the packages with corrected peer dependencies later today. For now, you should use "--force" to ignore the warning.

See #1439 for general information on Angular 6 compatibility.

**Comment by tsvetomir** [comment]
All components have been updated to address Angular 6 compatibility. Update instructions can be found in [the documentation](https://www.telerik.com/kendo-angular-ui/components/installation/angular-6/).

**Comment by tsvetomir** [comment]
Closing this issue as resolved. Please, open new issues for any specific problems that pop up after the upgrade.
