### ISSUE TITLE
Expandable/Collapsible Rows

### ISSUE THREAD

**Issue by joshidp** [telerik/kendo-angular#1518]
Hi,

Do you have expandable/collapsible row Kendo grid for Angular? If yes, please redirect me to that because I couldn't find it.

Thanks

**Comment by danielkaradachki** [comment]
Are you referring to the detail row functionality?
https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/detail-template/

Please note that this issue tracker is for bug reports only. If you have questions regarding implementation scenarios or configuration please open a support ticket.
