### ISSUE TITLE
 angular 6 Kendo UI release time

### ISSUE THREAD

**Issue by unosbaghaie** [telerik/kendo-angular#1519]
When angular 6 Kendo UI would be released? or any way to upgrade the latest version to support angular 6 !!

**Comment by tsvetomir** [comment]
The components are compatible with Angular 6. Uou need to install [rxjs-compat](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#backwards-compatibility) due to the update to RxJS 6. The official documentation will be updated later today.

Closing as duplicate of #1439

**Comment by squadwuschel** [comment]
how about changing the Major Version number from Kendo UI like the CLI did it, so everyone knows the compatible Angular Version number?

**Comment by tsvetomir** [comment]
There are no breaking changes in the components themselves, only the peer dependencies are extended to include Angular 6 / RxJS 6.

Users that are still on Angular 4 or 5 can continue to use the latest versions and get all updates. With the framework packages, you generally stop receiving updates for previous versions unless they are specifically back-ported, e.g. security fixes.

We aim to maintain our latest versions compatible with the latest Angular version, so you can update both in sync. Check our [Angular 6 Upgrade guide](https://www.telerik.com/kendo-angular-ui/components/installation/angular-6/) for details.

Existing applications can remain locked to a particular _major_ Angular and component versions indefinitely - we guarantee not to break compatibility in minor and patch releases.

We also retroactively tag deprecated versions with "ngx" tag, e.g. "npm install @progress/kendo-angular-grid@ng2" will get you the latest version of the Grid compatible with Angular 2. This addresses the scenario for adding components in older projects.
