### ISSUE TITLE
DatePickerComponent not FullTemplateTypeCheck compatible

### ISSUE THREAD

**Issue by Zaixu** [telerik/kendo-angular#1520]
## I'm submitting a...
* Bug report

## Current behavior
Unable to build with fullTemplateTypeCheck.
cellLeave and CellEnter is missing from component, but is implemented in html.

It was introduced at:
kendo-angular-dateinputs
Commit: 68422c0095a14b524e02353b07d60aae47a7ab1f

Resulting in:
ERROR in node_modules\@progress\kendo-angular-dateinputs\dist\es2015\index.d.ts.DatePickerComponent.html(65,17): : Property 'cellEnter' does not exist on type 'DatePickerComponent'.
node_modules\@progress\kendo-angular-dateinputs\dist\es2015\index.d.ts.DatePickerComponent.html(66,17): : Property 'cellLeave' does not exist on type 'DatePickerComponent'.

## Expected behavior
Build with full template type check.

## Minimal reproduction of the problem with instructions
Look at datepicker.component.ts.

## What is the motivation or use case for changing the behavior?
Build with full template type check.

**Comment by rkonstantinov** [comment]
Thanks for the report. The issue should already be fix in the latest @dev version of the `kendo-angular-dateinputs` package.

**Comment by ggkrustev** [comment]
I'll mark the thread as resolved.

@Zaixu, please comment if the issue still persists.
