### ISSUE TITLE
Close button of kendo-dialog stops working when using ngx-translate to set title

### ISSUE THREAD

**Issue by stefan-schweiger** [telerik/kendo-angular#1521]
## I'm submitting a...

* Bug report 

## Current behavior

When you use `ngx-translate` to set the title of a `kendo-dialog` the close button stops working. Hitting ESC on the other hand still works.

```
<kendo-dialog title="{{ 'HELLO' | translate }}" [hidden]="!opened" (close)="close('cancel')">
    <!-- ... -->
</kendo-dialog>
```

## Expected behavior

The dialog should close no matter where the title comes from.

## Minimal reproduction of the problem with instructions
(Sorry for not using your Plunkr but it's kind of cumbersome to set up with other external libraries)
https://stackblitz.com/edit/kendo-dialog-translate-bug

## What is the motivation or use case for changing the behavior?

It would be great to translate the dialog title and still be able to close it..

## Environment

```
rxjs@6.1.0
rxjs-compat@6.1.0
@angular/core@6.0.0
@angular/forms@6.0.0
@angular/common@6.0.0
@angular/router@6.0.0
@angular/compiler@6.0.0
@angular/animations@6.0.0
@angular/platform-browser@6.0.0
@angular/platform-browser-dynamic@6.0.0
@ngx-translate/core@10.0.1
@ngx-translate/http-loader@3.0.1
@progress/kendo-angular-l10n@1.1.0
@progress/kendo-angular-dialog@3.5.0
@progress/kendo-angular-buttons@4.0.0
@progress/kendo-theme-bootstrap@2.13.0
jquery@3.3.1
core-js@2.5.5
zone.js@0.8.26
bootstrap@4.0.0
popper.js@1.14.3
```

Browser:

- Chrome (desktop) version 66
- Firefox version 59

**Comment by ipeshev** [comment]
Hi @stefan-schweiger ,

You should use kendo-dialog-titlebar, as shown [here](https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/title/) second sample

**Comment by stefan-schweiger** [comment]
Hi @ipeshev ,

indeed that solve the problem. Thank you for your quick response.

I'm guessing the normal title isn't working because it's trying to get the string from title and make the `kendo-dialog-titlebar`, but the Observable hasn't completed yet which leads to problems, right?
