### ISSUE TITLE
The TreeView changes the scrollTop position

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1522]
When the TreeView's height is greater than the height of its containing element and we start selecting the different parent nodes, the TreeView changes the scrollTop position.

Check the following sample plunker:

https://stackblitz.com/edit/angular-wtcpnj?file=src%2Fapp%2Fapp.component.ts

Steps to reproduce:

1. Expand the tree to its deepest level.
2. Select the deepest level node in the tree.
3. Begin working up the tree selecting each nodes parent. When selecting the 3rd parent from the bottom, the tree should start showing the undesired behavior.

**Comment by Raisolution** [comment]
Not reproducible with [latest version](https://stackblitz.com/edit/angular-ju17ak?file=src%2Fapp%2Fapp.component.ts).
