### ISSUE TITLE
'kendo-slider' is not a known element:

### ISSUE THREAD

**Issue by joshidp** [telerik/kendo-angular#1523]
Hi,

I am getting below error while implementing custom pager for Kendo Angular Grid. It's based on https://www.telerik.com/kendo-angular-ui/components/grid/paging/ 

"): ng:///AppModule/AppComponent.html@52:12
'kendo-slider' is not a known element:
1. If 'kendo-slider' is an Angular component, then verify that it is part of this module.
2. If 'kendo-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("-currentPage="currentPage">
        <kendo-pager-prev-buttons></kendo-pager-prev-buttons>
        [ERROR ->]<kendo-slider  [tickPlacement]="'none'" [max]="totalPages" [min]="1" (valueChange)="sliderChange($eve"): ng:///AppModule/AppComponent.html@51:8
    at syntaxError (compiler.js:215)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14705)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:22712)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:22699)
    at compiler.js:22642
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:22642)
    at compiler.js:22552

**Comment by rkonstantinov** [comment]
Most probably you are missing to [import the `SliderModule`](https://www.telerik.com/kendo-angular-ui/components/inputs/#toc-installation) into the appropriate NgModule.

**Comment by joshidp** [comment]
I have added import { SliderModule } from '@progress/kendo-angular-inputs';

**Comment by rkonstantinov** [comment]
In case you need additional assistance, please open a support ticket.

**Comment by joshidp** [comment]
Why is this issue closed? The issue is not yet fixed. No solution is provided.

**Comment by rkonstantinov** [comment]
The issue has been closed as this issue tracker is for bug reports only. If you have questions regarding implementation scenarios or configuration please open a support ticket.

**Comment by joshidp** [comment]
Where should I open a support ticket?

**Comment by rkonstantinov** [comment]
You can submit a support ticket via [your telerik.com account](https://www.telerik.com/account/support-tickets).
