### ISSUE TITLE
Inline editing on row click breaks when scrollable set to none

### ISSUE THREAD

**Issue by yanbu0** [telerik/kendo-angular#1524]
## I'm submitting a...

* Bug report 

## Current behavior

When implementing inline editing on row click per your documentation, it stops working when you set the scrollable="none" option.  It also resizes all the columns, but only if there is more than one row.

## Expected behavior

Row editing on click works without resizing columns.

## Minimal reproduction of the problem with instructions

Go here: https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/

Click the "Open as Plunker" link.

Click into the grid, everything works as expected:
![image](https://user-images.githubusercontent.com/26099646/39828143-7d8eda48-5366-11e8-84df-d0da62cdbc85.png)

Set scrollable to none as per:
![image](https://user-images.githubusercontent.com/26099646/39828098-5afd37fe-5366-11e8-99ef-856f2bfeab90.png)

Now nothing works, clicking results in:
![image](https://user-images.githubusercontent.com/26099646/39828184-9db9d2be-5366-11e8-8afc-b476c623bac3.png)

## What is the motivation or use case for changing the behavior?

Not working as expected, and turning on scrolling breaks some of my custom form controls due to it applying `style="transform: translateY(0px)"` to the table that is generated.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by rkonstantinov** [comment]
The behaviour you have described is due to the way the sample is implemented. The implementation of the document click handler is relying on existence of a specific class, which is only available when Grid is set as scrollable. This can be easily adapted for the cases when the component is not scrollable, by changing the condition similar to the following:

```js
public ngOnInit(): void {
      this.view = this.service.products();
      this.renderer.listen(
          'document',
          'click',
          ({ target }) => {
              if (!isChildOf(target, 'k-grid-aria-root') && !isChildOf(target, 'k-grid-toolbar')) {
                  this.saveClick();
              }
          });
    }
``` 
Note the use of `k-grid-aria-root` class instead of `k-grid-content`

**Comment by tsvetomir** [comment]
The sample has been updated to work with non-scrollable grids. The change is:

![image](https://user-images.githubusercontent.com/247917/42323366-a247fce6-8068-11e8-9674-1aed516e26c4.png)
