### ISSUE TITLE
kendo-angular-dateinputs Reports Error on Upgrade

### ISSUE THREAD

**Issue by DBhail** [telerik/kendo-angular#1525]
Updated the Package json and did npm update. No Issues. Then do ng build and get error.
Tried Remove packages and did npm install. No Issues. Then  ng Build. Same Error.

**node_modules/@progress/kendo-angular-dateinputs/dist/es2015/daterange/date-range-popup.component.d.ts(2,28): error TS2305: Module '"D:/Documents/Development/hmo/frontend/node_modules/@progress/kendo-angular-popup/dist/es2015/index"' has no exported member 'Margin'.**

## Expected behavior
No Error

Package Json Extract:

```
"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@progress/kendo-angular-buttons": "^4.0.0",
    "@progress/kendo-angular-charts": "3.0.0",
    "@progress/kendo-angular-dateinputs": "^3.1.0",
    "@progress/kendo-angular-dialog": "^3.5.0",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-grid": "^3.1.0",
    "@progress/kendo-angular-inputs": "^3.0.0",
    "@progress/kendo-angular-intl": "^1.4.0",
    "@progress/kendo-angular-l10n": "^1.1.0",
    "@progress/kendo-angular-layout": "^3.0.0",
    "@progress/kendo-angular-upload": "^4.0.0",
    "@progress/kendo-data-query": "^1.3.0",
    "@progress/kendo-date-math": "^1.2.0",
    "@progress/kendo-drawing": "^1.5.3",
    "@progress/kendo-file-saver": "^1.0.5",
    "@progress/kendo-theme-bootstrap": "^2.12.1",
    "@progress/kendo-theme-default": "^2.51.0",
    "core-js": "^2.5.4",
    "guid-typescript": "^1.0.7",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.5",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.1.0",
    "zone.js": "^0.8.26"
  },
```

**Comment by tsvetomir** [comment]
I tried this with the latest and the 3.1 version of the `@progress/kendo-angular-dateinputs` package, but I could not reproduce the error. I did this in a freshly created Angular 6 project, so I might be missing something.

Can you share a runnable sample that has this problem?

**Comment by eastjie** [comment]
My project uses "kendo-angular-dateinputs: 3.2.0" and has the same problem by "ng serve".

**Comment by DBhail** [comment]
I did solve this problem by simply creating a new Angular 6 project and installing all the Telerik Controls again. I then simply copied and pasted over the folder @progress in node_modules in my new project to my existing project.  Viola ! All working. There is clearly a problem when it comes to upgrading Telerik Angular that can be overcome by copying over the files instead. And don't bother with "ng upgrade"...that's a complete waste of time that doesn't inform of  you of any updates. I hope that helps.

**Comment by eastjie** [comment]
@DBhail, Thanks very much. My problem is solved after copying them from a new project.

**Comment by dwayneforehand** [comment]
Same issue with kendo-angular-dateinputs: 3.2.0 here.

**Comment by ggkrustev** [comment]
Please install 3.3.0, which is the latest stable version of the package.

**Comment by DBhail** [comment]
Thank you...upgraded to 3.3.0 and buggered it up again. Why dont you lot test your upgrades before releasing them?


ERROR in Error during template compile of 'ɵcz'
  Could not resolve @progress/kendo-angular-dropdowns relative to D:/Documents/Development/hmo/frontend/node_modules/@progress/kendo-angular-grid/dist/es2015/index.d.ts..
node_modules/@progress/kendo-angular-dateinputs/dist/es2015/daterange/date-range-popup.component.d.ts(2,28): error TS2305: Module '"D:/Documents/Development/hmo/frontend/node_modules/@progress/kendo-angular-popup/dist/es2015/index"' has no exported member 'Margin'.
node_modules/@progress/kendo-angular-grid/dist/es2015/excel/excel.component.d.ts(3,58): error TS2307: Cannot find module '@progress/kendo-angular-excel-export'.
node_modules/@progress/kendo-angular-grid/dist/es2015/filtering/cell/filter-cell-operators.component.d.ts(2,39): error TS2307: Cannot find module '@progress/kendo-angular-dropdowns'.
src/app/modules/shared/shared.module.ts(11,33): error TS2307: Cannot find module '@progress/kendo-angular-dropdowns'.

**Comment by tsvetomir** [comment]
Since the error is not readily reproducible in a new project, it might be an environment issue:
* A package-lock.json file is holding onto older versions, despite what package.json says - try removing both node_modules, package-lock.json and run "npm install" again.
* The path might be too long on Windows - try moving the project to the drive root, re-install the modules and try building it again.

**Comment by eastjie** [comment]
For my problem, I haven't deleted "package-lock.json". Now the error doesn't appear after I delete old "package-lock.json" each time and reinstall node module complete new.

**Comment by DBhail** [comment]
renamed the package-lock.json to package-lock.bck, removed folder for node_modules and did "npm install". Went smoothly. No issues.

**Comment by ringodotnl** [comment]
adding   "@progress/kendo-angular-popup": "2.4.0" in package.json seem to solve it here
