### ISSUE TITLE
kendo-menu: openOnClick works only the first time

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1530]
## I'm submitting a 
* Bug report

## Current behavior
- Click on the menu.
- Menu opens
- Move the cursor away so the menu close again
- Move Cursor over the menu, menu opens without click

## Expected behavior
After Closing the menu, menu should only open with a click

## Minimal reproduction of the problem with instructions
Using your sample:
https://plnkr.co/edit/oTO9C7TcPAltit91mcBz?p=preview

## What is the motivation or use case for changing the behavior?
Need menu opened with a click

## Environment

Browser:
- Chrome (desktop) version 66

**Comment by danielkaradachki** [comment]
The behavior is described [here](https://www.telerik.com/kendo-angular-ui/components/menu/open-close/#toc-opening-on-click) - after an item is opened with click the menu will open/close on hover until an item is selected. The idea is to require a click to start interacting with the menu and then to allow the users to browse the items without a click. 
Could you provide more information about the behavior you are looking for? Should opening an item always require a click?

**Comment by EricSch** [comment]
I did read the behavior, but it isn't my understanding. I see your use case until the menu is closed. Why should the root menu open now on hover?

I'm looking for an menu which is opened with a click, not only the first time. When menu is closed again, it should open again with a click, means the next state of "item selected" and "menu closed" should be the same. I'm only talking about the root menu. 

The behavior now is very confusing. Imaging someone wants to checkout the menu content without selecting a menu item. When coming back to the menu, the behavior is suddenly different.

**Comment by danielkaradachki** [comment]
Right, but the menu could be closed if the user moves the mouse to another root item. If opening on hover is disabled on close then the user will again need to click the other item. That is why the selection is currently interpreted as end of interaction with the menu and not close of the item. We will consider making the behavior configurable.

**Comment by danielkaradachki** [comment]
Configuring the toggle behavior is available in the latest dev version:
https://www.telerik.com/kendo-angular-ui-develop/components/menu/open-close/#toc-opening-on-click

**Comment by EricSch** [comment]
That's great! Thank you :satisfied:

**Comment by ipeshev** [comment]
Fixed in v0.5.0-dev.201805301046

**Comment by danielkaradachki** [comment]
Available in 0.5.0
