### ISSUE TITLE
Modal support in Window like Dialog

### ISSUE THREAD

**Issue by hhiliahh** [telerik/kendo-angular#1532]
Is it possible to add the modal feature to the window. This feature is currently only available for Dialog.

**Comment by Raisolution** [comment]
Hi @hhiliahh,

The Window is not modal by design. However, you could easily add the modal feature by including a div element with the `k-overlay` CSS class to the page(the same is used for the Dialog). Here is an [example of this](https://plnkr.co/edit/iPb7M97kFvNHgoDweb0P?p=preview) in action.

**Comment by pfoedermayr** [comment]
Based on the solution of @Raisolution I built a `directive` that automatically adds a `div.k-overlay` to the dom when the `kendo-window` is rendered.

The source can be found here. ([Gist](https://gist.github.com/pfoedermayr/a666c1b1c990f3301fa8d3fb8b87ead8))
In case someone finds it useful, feel free to use it.

### Usage
Just import the `WindowWithBackdropDirective` in your module(s), and add it to the `kendo-window`(s) which shall/must be a modal.

````html
<kendo-window withBackdrop *ngIf="opened">
    <!-- window content -->
</kendo-window>
````
