### ISSUE TITLE
The DatePicker does not highlight the input

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1533]
When using "Tab" key in order to focus the DatePicker and the DatePicker has a defined placeholder, the input is not highlighted. Check the following sample plunker demonstrating this behavior:

[https://plnkr.co/edit/d8wyiUBbYAPcOiedGPuJ?p=preview](https://plnkr.co/edit/d8wyiUBbYAPcOiedGPuJ?p=preview)

**Comment by ggkrustev** [comment]
A fix is released in `v3.4.0-dev.201805210833`. The easiest to try the change is to install the `DEV` release:
`npm i @progress/kendo-angular-dateinputs@dev`

**Comment by ggkrustev** [comment]
Fixed in `v3.4.0`. Please install the latest package to see the changes.

`npm i @progress/kendo-angular-dateinputs@3.4.0`
