### ISSUE TITLE
[DateRange]: value shown is not updated when using reactive forms

### ISSUE THREAD

**Issue by pfoedermayr** [telerik/kendo-angular#1534]
## I'm submitting a...
* Bug report 

## Current behavior
When using the `kendo-daterange`-component with reactive forms, the value shown in the input is not updated, while the `FormGroup`s value is.

## Expected behavior
The `kendo-dateinput` should reflect the value of the `FormGroup`.

## Minimal reproduction of the problem with instructions
[Demo](https://plnkr.co/edit/hj7ubnu9AwnbUDdkABhN?p=preview). 
_The provided example is the demo found [here](https://www.telerik.com/kendo-angular-ui/components/dateinputs/daterange/), adopted to use reactive forms._

1. Change the value of the start (or end) range via the popup.
2. The change is not reflected in the `kendo-dateinput`

## What is the motivation or use case for changing the behavior?
Using the `kendo-daterange`-component w/ reactive forms.

## Environment

Package versions:
**angular:** 6.x _(or 5.x)_
**rxjs:** 6.x w/ rxjs-compat _(or 5.5.x)_
**kendo-angular-dateinputs:** 3.2.0

Browser:
- Chrome (desktop) version 66

System:
- TypeScript version: 2.7
- Node version: 8.9.4 (npm 5.8.0)
- Platform:  Windows 10 64bit

**Comment by ggkrustev** [comment]
Hi @pfoedermayr, thanks for the bug report. Indeed, the input won't update its value when a new date is picked from the popup calendar. This was addressed and the fix is available in the current DEV release of the `kendo-angular-dateinputs` package. Here is the updated plunkr:

https://plnkr.co/edit/YcHuOATPiCgK90qRXJUI?p=preview

Could you verify that the issue is already addressed?

**Comment by pfoedermayr** [comment]
@ggkrustev Thanks for the prompt reply. I will have a look at it tomorrow, when I'm back at work, and let you know.

**Comment by pfoedermayr** [comment]
I can confirm that this is fixed in the latest development build.
Shall I close this issue or do you want to keep it open until the next release?

**Comment by ggkrustev** [comment]
Let's keep it open until the fix is officially available.
