### ISSUE TITLE
Make editor read only over directive

### ISSUE THREAD

**Issue by sehaxx** [telerik/kendo-angular#1536]
Hi,

Not sure if this is a bug or a change in code. I want to make my editor read only and found online a solution. But the solution works for the version 2014 of kendo. But in 2017 R3 that I'm currenly using it doesn't work. (https://stackoverflow.com/questions/50366739/kendo-ui-in-angular-js-make-an-kendo-editor-readonly here also on SO.)

Working version: http://dojo.telerik.com/@sehaxx/OcafeyAn
Not working version: http://dojo.telerik.com/@sehaxx/ASeMUsUj

Hope you can help me. If there is a different event to call, what I need is the widget object.
I get the event "kendoRendered" but it does not have the object widget.

Thanks,

**Comment by ggkrustev** [comment]
Hello @sehaxx,

This issue tracker is dedicated to the Kendo UI for Angular components.

https://www.telerik.com/kendo-angular-ui/components/

Would it be possible to open a support incident for [Kendo UI for jQuery using](https://demos.telerik.com/kendo-ui/editor/angular) your Progress profile. Thus the most suitable support officer will be able to assist you promptly with the described issue.

Will close the thread as it is not related to the Kendo UI for Angular components.
