### ISSUE TITLE
dropdown and grid data does not load unless i click on it

### ISSUE THREAD

**Issue by Sevensnake** [telerik/kendo-angular#1537]
I upgraded from 5.2 to Angular6 .  The controls where working. I have to manually click on the dropdown like an onfocus event to initialize it.   The same thing with the grid, I have to search for something then all the data loads.  But I add console.log and see the data has loaded but nothing happens in the view until i click the dropdown or the grid search in the filter box then all data displays.

public dropdowndates: Array<string>;
public listFilter = "";
`<kendo-dropdownlist [data]="dropdowndates" [value]="listFilter"  (valueChange)="handleOrderChange($event)">
        </kendo-dropdownlist>`

`ngOnInit() {
this.dropdowndates = ["02/28/2018", "01/31/2018", "12/31/2017", "11/30/2017", "10/31/2017"]
this.listFilter  = this.dropdowndates[0];`
// this worked before the upgrade. not sure.
}

**Comment by tsvetomir** [comment]
There are no known issues with the DropDownList and Angular 6 at the moment. Please, open a support ticket for assistance with project-specific issues.
