### ISSUE TITLE
Duplicate "id" attribute on kendo-numerictextbox

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular#1539]
`<kendo-numerictextbox id="someId" ...></kendo-numerictextbox>`

The nested input element inside this component will have a duplicate id e.g.  `<input id="someId" .../>`. It does not seem semantically correct to have duplicate ids.

i am using the latest inputs package version: `"@progress/kendo-angular-inputs": "3.1.1"`

**Comment by ggkrustev** [comment]
All relevant packages are fixed in DEV. To try it just install the corresponding DEV release:
```
npm i @progress/kendo-angular-[package-name]@dev
```
The fixes should be released officially within a week or two time frame.

**Comment by tsvetomir** [comment]
Fix released in:

* `@progress/kendo-angular-dateinputs` v3.4.1
* `@progress/kendo-angular-dropdowns` v3.0.2
* `@progress/kendo-angular-inputs` v3.1.3
* `@progress/kendo-angular-upload` v4.1.2
