### ISSUE TITLE
Grid with virtual scrolling

### ISSUE THREAD

**Issue by rusev** [telerik/kendo-angular#154]
There is some unexpected visual behavior when you scroll the Grid:

> It looks like, whenever i scroll up or down, there's this weird refresh, in which i see for a sec the old detail item opened, replaced right after with the new items.

This "glitch" is observable for a second until the table is repainted. Maybe we can show loading panel or something while scrolling?

Plnkr - http://plnkr.co/edit/eXm5OKBwHpOLaXZPxVtE?p=preview
Original post - https://stackoverflow.com/questions/41359095/kendogrid-weird-scrolling-while-detail-item-is-open

//cc @yordanov

**Comment by meriturva** [comment]
Same behavior here...and to be honest it is really annoying.
What i would like to say is that i think a loading panel is not a solution. User would like just to scroll, not see loading panel.
What do you think to link _detail open/close property_ to an _item property from data model_  so developer could just control it? is it a solution?
i really don't know how kendo grid works internally.
So thanks.

**Comment by sigVince** [comment]
Loading panel would be great. Better plnkr (imo) here, I forked the plnkr from the official doc and added a timeout to simulate a slow webservice : http://plnkr.co/edit/KXRFimr9oSLwCLng7K3i?p=preview

**Comment by meriturva** [comment]
I repeat: a loading panel is not a solution. Fix that issue introducing a new graphical element is not correct. We have all data already available. We just need a callback that works not showing wrong values.

**Comment by sigVince** [comment]
I see what you mean. I agree that it should continue to scroll while loading, but if you reach the end of the current batch of items before your webservice answers it could be nice for the user to know that data is going to be displayed soon. Myybe just a text info "loading data..." displayed below the last row of the current batch.

**Comment by rkonstantinov** [comment]
@meriturva Did you try the latest version of the Grid package? We have already done some improvements in this area.

@sigVince we are considering adding a "loading panel" for future version of the component.

**Comment by FedericoGalf** [comment]
I agree with @meriturva. I've tried it with a remote web api and the behavior is too annoying. It's unusable by the final user. Is it possible to have a timing for a next release with at least a loading panel? 
Thanks in advance.

**Comment by sigVince** [comment]
About behavior for the user, after a bit of testing I think virtual scrolling is not a good solution. Infinite scroll is much better in most cases. Feel free to upvote my feature request about that :)
http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback/suggestions/17816359-infinite-scrolling-for-grid

**Comment by Delta388** [comment]
Agreeing with @meriturva and @FedericoGalf, right now virtual scrolling with a remote api is not really usable, the behavior of the grid under these circumstances really needs to be improved.

**Comment by tsvetomir** [comment]
We've added a demo on how to [Debounce pageChange Events](http://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/#toc-debounce-pagechange-events). This should make remote calls practical.

We're considering adding a loading panel to indicate that the data is being fetched.

**Comment by tsvetomir** [comment]
Tracking in #666

**Comment by pran2889** [comment]
Not able to select grid row in Kendo grid
Please find below sample 
https://stackblitz.com/edit/angular-kxdzur-jkx3of

Steps to reproduce :
1. Open above URL
2. Scroll to last row
3. Try to select row no 93.
4. Not able to select row as well as it jumps to other rows as well.

Let me know if anyone able to fix this issue

**Comment by ravi-b-m** [comment]
Were u able to solve the issue @pran2889 .. If so can you share what you did ?

**Comment by pran2889** [comment]
@ravi-b-m Yes Ravi I was able to solve this issue by setting fix row hight in grid.
If your rows are with different heights due to cell data, then this issue will come.

**Comment by melamudv** [comment]
@pran2889 Can you share example how you solve this issue with virtual scroll
Thanks
