### ISSUE TITLE
Packages with "mark as compatible with Angular 6.x, RxJS 6.x": Why are there compile errors?

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1540]
Could you explain what meaning of "mark as compatible with Angular 6.x, RxJS 6.x" is?
It seems that the packages aren't compatible.

When I compile the latestest Kendo packages with Angular 6.0.2 and RxJS 6.1.0, there are lot of errors like `node_modules/rxjs/Subject"' has no exported member 'Subject'`.

Does it mean, that the compatibility layer "rxjs-compat" is still needed? Also there is no native RxJS 6 support?

Thanks

**Comment by tsvetomir** [comment]
Please, make sure you install `rxjs-compat` as well, see [docs](https://www.telerik.com/kendo-angular-ui/components/installation/angular-6/).

In NPM world, there are no means to specify that we depend on either RxJS >5.5 or RxJS 6.x + rxjs-compat. Hence the lack of peer dependency errors.

**Comment by EricSch** [comment]
Sorry, didn't find those docs, was looking for them.
Thanks
