### ISSUE TITLE
Grid's scrollbar resets when using virtual scrolling

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1541]
When using virtual scrolling in combination with a Kendo command directive the scrollbar resets its position (only when the grid height is above 500px). This strange behavior occurs after package version 3.0.4 of @progress/kendo-angular-buttons.

Check the following sample plunker demonstrating the reported behavior:

[https://plnkr.co/edit/VYGd71c7oP3DMFmeBG26?p=preview](https://plnkr.co/edit/VYGd71c7oP3DMFmeBG26?p=preview)

**Comment by ipeshev** [comment]
Shipped with v3.5.0
