### ISSUE TITLE
Can't find "GroupTagTemplateDirective" in @progress/kendo-angular-dropdowns 

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#1543]
* Bug report 

## Current behavior
I need the GroupTagTemplateDirective inside my code to reference the ngtemple

## Expected behavior
I can't import the "GroupTagTemplateDirective" from the namespace "@progress/kendo-angular-dropdowns"

Like shown here:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/kendo-ui-extensions?file=app%2Fmultiselect%2Fsxp-multiselect%2Fsxp-multiselect.component.ts

I try to import the 

    import { HeaderTemplateDirective, GroupTagTemplateDirective,  MultiSelectComponent } from '@progress/kendo-angular-dropdowns'

but the "GroupTagTemplateDirective" Template is not found.

## Environment

Package versions:
"progress/kendo-angular-dropdowns"  3.0

**Comment by dimitar-pechev** [comment]
fixed in kendo-angular-dropdowns v3.1.1-dev.201810051435

**Comment by dimitar-pechev** [comment]
Shipped in v3.2.0 of the `@progress/kendo-angular-dropdowns` package.
