### ISSUE TITLE
Docs: Broken Link to W3C Accessibility Role Page

### ISSUE THREAD

**Issue by jbristowe** [telerik/kendo-angular#1546]
## I'm submitting a...

* Documentation issue or request

## Current behavior

https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/accessibility/

* The link to the role document - hosted by the W3C website - is broken (HTTP 404):

https://www.w3.org/TR/wai-aria/roles (this is the broken link)

## Expected behavior

* The link should point to the role document:

https://www.w3.org/WAI/PF/aria/roles

## Minimal reproduction of the problem with instructions

1. Visit accessbiliity document for `NumericTextBox` and click the role link. This results in a HTTP 404.

## What is the motivation or use case for changing the behavior?

* Improve the documentation experience for customers

## Environment

* Not applicable

Package versions: N/A
Browser: N/A
System: N/A

**Comment by tsvetomir** [comment]
Thanks for the heads-up, we'll publish a [fixed version](https://www.telerik.com/kendo-angular-ui-develop/components/inputs/numerictextbox/accessibility/) soon.

**Comment by tsvetomir** [comment]
Fixed on the live site.
