### ISSUE TITLE
Column headers should scroll when changing the [scrollable] input property of the grid

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1547]
Check the following sample plunker:

[https://plnkr.co/edit/u79QpbkG9dZFXJo1irz3?p=preview](https://plnkr.co/edit/u79QpbkG9dZFXJo1irz3?p=preview)

1. First time on load we get scroll on the grid. If you scroll on the grid, the grid header moves seamlessly. 
2. click on 'none' button to disable scroll on the grid.
3. Again click on 'scroll' button to  enable scroll again on the grid. If you scroll the grid, the grid header freezes. It does not move when we scroll.

**Comment by ipeshev** [comment]
Available in v3.4.1-dev.201805251236

**Comment by tsvetomir** [comment]
Fix released in v3.5.0 of the `@progress/kendo-angular-grid` package.
