### ISSUE TITLE
[Dialog]-Close not working when bind title

### ISSUE THREAD

**Issue by kanji-keraliya** [telerik/kendo-angular#1548]
[Kendo-Dialog] not close button work when we bind title property using variable also titlebar not shown

try this https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/title/

**Comment by ggkrustev** [comment]
The visibility of the Dialog component is controlled by `*ngIf` structure directive. You can find more details in the corresponding help topic.

https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/visibility/

Will close the thread as it doesn't report bug or requests a new feature.

**Comment by kanji-keraliya** [comment]
checkout this https://plnkr.co/edit/xDMeAHt4x5UUG4YVYgbM?p=preview

When we assign title dynamically title bar not shown at first load.

**Comment by ggkrustev** [comment]
Thanks for the repro demo.

In the given demo, the title is not shown initially, because `open` method is never called. If we close the popup and then call the `open()` method, the title is shown.  To prove that I've modified the demo and added a button inside the dialog which sets the title. As you can see the title is dynamically added once `title` property is set.

https://plnkr.co/edit/M0BxyoNk504hdAdZn0eX?p=preview

**Comment by kanji-keraliya** [comment]
My case is open modal popup for new/edit item show title is according it when its load first time not want to set after loaded.
what to do for my case?

**Comment by ggkrustev** [comment]
The best way to assist you is to open a support ticket from your Progress account. Thus the most suitable support officer will be able to assist you with this specific support scenario and provide up-to-the-point solution.

The Github issues are used only for bugs and enhancement requests. Hence the discussed scenario none of those, the best place to continue our discussion is the aforementioned support channel.

**Comment by kanji-keraliya** [comment]
I think it is a bug so I report here.
By the way its resolve by assigning default value to title variable

**Comment by ggkrustev** [comment]
If you are sure that the described behavior is a bug, then please update the initial post, providing all required information, including repro steps, repro demo, environment and etc. Without properly filled template I won't be able to reopen the thread.

Thank you for your understanding.

**Comment by kovaldenys96** [comment]
It's a bug as I have the same issue. If I pass title with translation pipe - close button doesn't work. In all another cases it works good
