### ISSUE TITLE
Blur and Focus Event Dropdowns

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#155]
Is there a way to catch the Focus and Blur event in dropdowns?

Plunkr:
http://plnkr.co/edit/0rKLbOKwZjOADMhleXmL?p=preview

No focus or blur event is thrown when you focus or leave the dropdown.

**Comment by tapopov** [comment]
Hi @simon11196,

The ComboBox currently does not emit focus and blur events. We're interested in the use-cases requiring those events - do you mind sharing one? 
On a related note, the DropDownList component does emit both focus and blur, as shown [here](http://plnkr.co/edit/azAwM9g8MlAKQkNt6qZ2).

**Comment by simon11196** [comment]
Hi @tapopov,

I'm using a combobox component in a grid cell template as content.

On every blur event of a cell template content I have to check if the leaved cell is the last one of displayed data, to switch the page programmaticly. (Pageable Grid)

**Comment by tapopov** [comment]
Thanks for the feedback @simon11196!
We will implement the feature in one of the upcoming releases. Stay tuned.

**Comment by KirilNN** [comment]
Hi @simon11196,

We have researched the current behavior of the focus/blur events, Currently events cannot be prevented inside `HostListener` construction, there is an open issue in the Angular repository: https://github.com/angular/angular/issues/9587

as we are moving the focus to the input elements inside the ComboBox component, when the parent if focused, we will need to prevent that event, so we can emit the correct (according to the component) focus/blur, and currently - we cannot do this.

A possible workaround would be to rely on the DOM `focusin/focusout` events, however they are currently [not supported](https://developer.mozilla.org/en-US/docs/Web/Events/focusin) in the Firefox browser. According to the Mozilla bug tracker and this [issue](https://hg.mozilla.org/integration/mozilla-inbound/rev/aa39c1a962ff) these events were implemented, however they will be released somewhere between March and June, according to the Firefox release cycle.

As soon as any of the above issues are resolved, we will revisit the current implementation and provide any possible improvements.

In the mean time - you can use the present DOM events and detect which is the focused element using `document.activeElement` and checking if the parent is the component or any other element on the page, so you can detect when the component is blurred.

**Comment by aarmora** [comment]
Hello @tapopov and @KirilNN,

I am currently using the combobox and wanted to provide my use case for focus and blur events.

We have labels for our input elements that change color when their input element is focused and change back to normal when focus is removed. Without focus/blur events we are unable to do this.

**Comment by tsvetomir** [comment]
This effort is tracked in #335
