### ISSUE TITLE
[Mobile]: Skip input focus after popup of ComboBox or MultiSelect is opened

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1550]
Skip input focus after selecting the ComboBox or MultiSelect components for mobile devices, so that the keyboard is not automatically displayed.

Linked issue: #1253

**Comment by munnaonc** [comment]
Hi, Any update on this one? When is the ETA for this one?
Thanks

**Comment by munnaonc** [comment]
Hi,
Is there any update about this issue? We would appreciate if we were provided any estimated timeline for this one.
Thanks.

**Comment by tapopov** [comment]
Hi @munnaonc 
Apologies for the delay. We will look into it and provide a fix as soon as possible.

**Comment by munnaonc** [comment]
Hi @tapopov,

Thanks for your reply. Could you please give us an estimated release date? So that we can plan an upgrade to our controls. 

(Note: I am not talking about nightly build or dev builds. We only integrate the public releases in our product)

Thanks.

**Comment by tapopov** [comment]
Hello @munnaonc 
This just landed in the dev release channel and we'll move it to official by the end of next week.

**Comment by tsvetomir** [comment]
Fixed in v3.3.0

**Comment by munnaonc** [comment]
Thanks.

**Comment by munnaonc** [comment]
Hi,
I have another question, To get the fix, can I update only the Dropdownlist package?

"npm install @progress/kendo-angular-dropdowns" 

Thanks.

**Comment by tsvetomir** [comment]
`npm install --save @progress/kendo-angular-dropdowns@latest` should do the trick.
