### ISSUE TITLE
The Upload "Select Files..." button text disappears when disabled in Internet Explorer and Edge

### ISSUE THREAD

**Issue by CrestedSquash** [telerik/kendo-angular#1552]
## I'm submitting a...
- Bug report

## Current behavior
- The Upload "Select Files..." button text disappears when disabled in Internet Explorer and Edge
- The text does not disappear in Firefox or Chrome

## Expected behavior
- The text should not disappear when the button is disabled

## Minimal reproduction of the problem with instructions
- See the Disabled Upload example on the Kendo UI site (https://www.telerik.com/kendo-angular-ui/components/upload/disabled-state/)
- Here is the Plunker for that example: https://plnkr.co/edit/vsBNYrBRopxix8d5rDFA?p=preview

## What is the motivation or use case for changing the behavior?
Poor user experience due to buggy UI

## Environment

Package versions:
Reproducible on demo site

Browser:
- Chrome (desktop) version 66.0.3359.181 (Official Build) (64-bit)
- Firefox version 60.0.1 (64-bit)
- IE version 11
- Edge version 41.16299.402.0

System:
- TypeScript version: Reproducible on demo site
- Node version: Reproducible on demo site
- Platform:  Windows

**Comment by Krishnan07** [comment]
I was able to temporarily resolve the issue by setting the z-index value for the Text Span to 1
The Current z-index of the button is set to 1

Example:
<button style="z-index:1" name ="abc">
<span>Select</span>
</button>

So the Text span hides behind the button (having z-index of 0).

Here is a quick solution
:host /deep/ .k-upload-button span
{
    z-index: 1!important;
}

**Comment by Raisolution** [comment]
Issue is no longer reproducing with the latest versions of the themes.
