### ISSUE TITLE
OData V4 grouping - toOdataString does not generate query for grouping

### ISSUE THREAD

**Issue by hidegh** [telerik/kendo-angular#1553]
## I'm submitting a...
* Bug report
* Suggestion for improvement

Since OData v4 is now avail for a while (specs. 2014),
**GROUPING with OData data source should be possible**
So this is now actual again: https://github.com/telerik/kendo-angular/issues/731

## Current behavior
**toOdataString does not generate GROUP odata query**

## Expected behavior
**have the query include group by expression, like:** $apply=groupby((Product/Name,Amount)) 

## Minimal reproduction of the problem with instructions
Use grid with odata endpoint, allow grouping, ... check out generated query

## What is the motivation or use case for changing the behavior?
To support grouping also with OData, 
**1st step would be to alter toOdataString to include the expression in the query (quick fix)**
Alteration of the grid itself might not be necessary.

## Environment
Angular 4+, Grid

Package versions:
N/A

Browser:
N/A

System:
N/A

**Comment by rkonstantinov** [comment]
Closing this as a duplicate. You can track the request in [our user voice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/20059975-toodatastring-should-support-groupby-and-agreggate).
