### ISSUE TITLE
Window with no [height] or [width] stops scaling after RestoreAction

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1554]
## I'm submitting a...

* Bug report 

## Current behavior
When you don't set a height or width to the window, it scales with the content. When you use RestoreAction (after a minimize or maximize), the window loses that scaling functionality.

## Expected behavior
The window's dimensions should still scale with its inner content. 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/LGrHHZS6DHleUkuCZDWh?p=preview

When you change the size of the div inside the window, the size of the window changes.
After a maximize then restore, the height and width of the window are fixed.

## What is the motivation or use case for changing the behavior?
UX improvements.

## Environment

Browser:
- Chrome (desktop) 
- Firefox

**Comment by Raisolution** [comment]
Issue has been addressed in `v3.6.2-dev.201806081223`.

**Comment by Raisolution** [comment]
The next official release `v3.6.2` has just been published.

**Comment by Neaco** [comment]
Thanks for the heads up.
