### ISSUE TITLE
[Example not working] CellClickEvent never returns type 'contextmenu' in grid-context-menu example

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1556]
## I'm submitting a...

* Documentation issue or request
* Maybe a regression

## Request
Hello. 
I couldn't find any documentation on the grid-context-menu when I tried to understand the example at 
https://www.telerik.com/kendo-angular-ui-develop/components/grid/advanced-features/context-menu/
(that might be broken because there is nothing in the context-menu and no cell click seems to trigger it).

**Comment by tsvetomir** [comment]
The `grid-context-menu` component is implemented as part of the example: 
![image](https://user-images.githubusercontent.com/247917/40527859-1f9fd804-5ff7-11e8-8996-4024bc08db1d.png)

**Comment by Neaco** [comment]
Sorry for that, I didn't see it. 
Still, the example on the website and the Plunkr are not working. 
I looked at the code, and the problem is in 

![image](https://user-images.githubusercontent.com/22844693/40592683-cbe87fda-6254-11e8-97a5-179ba2d15687.png)

The CellClickEvent always returns the type 'click', so the (type === 'contextmenu') condition is never fulfilled. 

In the documentation, there is no info on when the CellClickEvent returns type : 'click' or type : 'contextmenu', but it seems to be a bug that it always returns type : 'click'.

**Comment by tsvetomir** [comment]
Just checked the demo on Chrome and a right click sets "type" to "contextmenu". What browser are you testing with?

**Comment by Neaco** [comment]
I'm sorry, I never realized 'contextmenu' was set on a right click. I never met that term so I was unaware it meant the right click menu. Maybe you could make it clearer in the documentation.

Sorry again for the trouble.

**Comment by tsvetomir** [comment]
Added a note to the example to clarify:

> In order to discriminate between regular clicks and [contextmenu events](https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu), the example checks the [`cellClick.type`](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/CellClickEvent/#toc-type) field.
