### ISSUE TITLE
Extra whitespace in the Tooltip when used with bootrstap theme

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1557]
There is some extra white space in the Tooltip when used with bootrstrap theme. Check the following sample plunker demonstrating the undesired behavior:

[https://plnkr.co/edit/vclmNkEhZhYO37twasB9?p=preview](https://plnkr.co/edit/vclmNkEhZhYO37twasB9?p=preview)

**Comment by ipeshev** [comment]
Fixed in latest development version of kendo-themes
