### ISSUE TITLE
DropdownsModule causing build to fail after Angular 6 migration

### ISSUE THREAD

**Issue by graphicsxp** [telerik/kendo-angular#1559]
## I'm submitting a...

 Support requests to https://www.telerik.com/account/support-tickets.
* Regression report 

## Current behavior

After migrating my project to Angular 6, with latest version of Telerik packages and Rxjs (+rxjs-compat), the production build no longer works.

`ng build --prod ` gives me the following error : 

>  Function expressions are not supported in decorators in 'DropDownsModule' 'DropDownsModule' references 'DropDownsModule' 'DropDownsModule' references 'ɵ0' 'ɵ0' contains the error at @progress\kendo-angular-dropdowns\dist\es\dropdowns.module.js.ts(37,38) Consider changing the function expression into an exported function.

It was working fine before migrating.

## Expected behavior

It should build

## Minimal reproduction of the problem with instructions

Just import the DropDownsModule into the main app module

## Environment

Prod
Package versions:

```
+-- @angular-devkit/build-angular@0.6.3
+-- @angular/animations@6.0.3
+-- @angular/cli@6.0.3
+-- @angular/common@6.0.3
+-- @angular/compiler@6.0.3
+-- @angular/compiler-cli@6.0.3
+-- @angular/core@6.0.3
+-- @angular/forms@6.0.3
+-- @angular/http@6.0.3
+-- @angular/language-service@5.2.11
+-- @angular/platform-browser@6.0.3
+-- @angular/platform-browser-dynamic@6.0.3
+-- @angular/platform-server@6.0.3
+-- @angular/router@6.0.3
+-- @angular/upgrade@6.0.3
+-- @progress/kendo-angular-buttons@4.1.1
+-- @progress/kendo-angular-dateinputs@3.4.0
+-- @progress/kendo-angular-dialog@3.6.1
+-- @progress/kendo-angular-dropdowns@3.0.1
+-- @progress/kendo-angular-excel-export@2.1.0
+-- @progress/kendo-angular-grid@3.4.0
+-- @progress/kendo-angular-inputs@3.1.2
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-upload@4.1.2
+-- @progress/kendo-data-query@1.3.1
+-- @progress/kendo-drawing@1.5.5
+-- @progress/kendo-theme-default@2.53.2
+-- @tinymce/tinymce-angular@2.0.0
+-- @types/jasmine@2.8.7
+-- @types/jasminewd2@2.0.3
+-- @types/node@10.0.10
+-- angular-router-loader@0.8.5
+-- angular2-moment@1.9.0
+-- angular2-template-loader@0.6.2
+-- angular2-toaster@6.0.0
+-- angular2-uuid@1.1.1
+-- awesome-typescript-loader@5.0.0
+-- babel-cli@6.26.0
+-- babel-core@6.26.3
+-- babel-preset-env@1.7.0
+-- bootstrap@4.1.1
+-- breeze-bridge2-angular@1.1.0
+-- breeze-client@1.7.1
+-- breeze-client-labs@1.5.12
+-- codelyzer@4.3.0
+-- concurrently@3.5.1
+-- core-js@2.5.5
+-- css-loader@0.28.11
+-- faker@4.1.0
+-- file-loader@1.1.11
+-- font-awesome@4.7.0
+-- fullcalendar@3.9.0
+-- ie-shim@0.1.0
+-- UNMET PEER DEPENDENCY jasmine@>=3
+-- jasmine-core@3.1.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.3.1
+-- json-loader@0.5.7
+-- json-schema-faker@0.5.0-rc15
+-- json-server@0.12.2
+-- karma@2.0.2
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@1.4.3
+-- karma-jasmine@1.1.2
+-- karma-jasmine-html-reporter@1.1.0
+-- karma-junit-reporter@1.2.0
+-- karma-trx-reporter@0.2.9
+-- lodash@4.17.10
+-- ngx-bootstrap@3.0.0
+-- node-sass@4.9.0
+-- popper.js@1.14.3
+-- primeng@5.2.7
+-- raw-loader@0.5.1
+-- rimraf@2.6.2
+-- roboto-fontface@0.9.0
+-- rxjs@6.2.0
+-- rxjs-compat@6.2.0
+-- sass-loader@7.0.1
+-- source-map-loader@0.2.3
+-- style-loader@0.21.0
+-- tinymce@4.7.13
+-- tslint@5.10.0
+-- tslint-loader@3.6.0
+-- typescript@2.7.2
+-- url-loader@1.0.1
`-- zone.js@0.8.26
```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: Version 2.7.1
- Node version: v8.11.1
- Platform:  Windows

**Comment by tsvetomir** [comment]
Tried reproducing this in a new CLI project, but to no avail. Try removing "node_modules", "package-lock.json" and re-installing.

[ng6-dropdowns.zip](https://github.com/telerik/kendo-angular/files/2038616/ng6-dropdowns.zip)

**Comment by graphicsxp** [comment]
Indeed, in a new project it works. I have already removed  node_modules and package-lock.json and reinstalled everything. Still get the same error. Looks like migrating from Angular 5 to 6 or starting from scratch is a different story.

**Comment by tsvetomir** [comment]
At least in theory, the migrated project should work in the same way. Can you please submit a trimmed-down version of your project in a support ticket so we could take a look?

**Comment by graphicsxp** [comment]
In the end I figured out what the problem was. The DropDownsModule was imported like this :+1: 
`import { DropDownListModule } from '@progress/kendo-angular-dropdowns/dist/es/dropdownlist.module';`

importing like this fixed the error : 

`import { DropDownListModule } from '@progress/kendo-angular-dropdowns';`

Somehow this was not an issue before the migration.
