### ISSUE TITLE
Flat data binding doesn't work as expected for nested tree view nodes

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#1561]
## I'm submitting a...
* Bug report 

## Current behavior
When we bind TreeView to flat data using _kendoTreeViewFlatDataBinding_ it works well for root level nodes, but changes to the nested nodes do not appear on UI until we collapse/expand their parent nodes (assume that _kendoTreeViewExpandable_ directive is used). If _kendoTreeViewExpandable_ is removed the situation becomes even worse because in that case there is no way to see new items at all.

## Expected behavior
When nodes are changed all expanded tree nodes should be refreshed on UI.

## Minimal reproduction of the problem with instructions
Here is a plank with an example: [link](https://plnkr.co/edit/Xby0aua44dzGM5gaWAXu?p=preview)

**Comment by AlexKichkailo** [comment]
any update on this? We're experiencing the same issue. TreeView does not refresh child nodes, when a new array with "new child items" is bound to the nodes property.

**Comment by ggkrustev** [comment]
Indeed, the component won't update the list, because the group doesn't trigger its change detection accordingly. We will further investigate the case and will try to find a feasible solution.

For the time being, you can collapse-expand the group to force its re-render:
https://plnkr.co/edit/svC1IkLR470xEu9lPL91?p=preview

**Comment by cebamps** [comment]
Any update on this? Your collapse-expand workaround animates the treeview, which is a bit annoying...

I attempted to expand and collapse the group in two successive `setTimeout` calls, but even then the tree view is animated.

**Comment by rkonstantinov** [comment]
The issue in question has been fixed in [the latest develop version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `kendo-angular-treeview` package.

**Comment by danielkaradachki** [comment]
Fixed in 2.3.0
