### ISSUE TITLE
rxjs-compat

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#1563]
## I'm submitting a...

* ~~Regression report ~~
* ~~Bug report ~~
* ~~Suggestion for improvement~~
* ~~Documentation issue or request~~
* Query - where do I post this?

Will kendo release a version without  `rxjs-compat` in the future (or depends on `rxjs@^6.0.0`)?

**Comment by AlexGS74** [comment]
Second the question.

With rxjs-compat final app always has whole rxjs and rxjs-compat libs. Huge waste of resources.

**Comment by tsvetomir** [comment]
We will drop support for RxJS 5.x after Angular 5 reaches EOL in [April 2019](https://angular.io/guide/releases#long-term-support).

@AlexGS74 rxjs-compat only contains re-exports and does not affect the bundle size. Check that you're not importing the full 'rxjs'. Check out [Managing RxJS Imports with TSLint
](https://blog.angularindepth.com/managing-rxjs-imports-with-tslint-828cdc66b5ee) for a few handy TSLint rules that guard against this.

**Comment by AlexGS74** [comment]
RxJs 6 is tree shaking friendly and has huge potential of shaking unused code, which is impossible to utilize as long as rxjs-compat is in the bundle, thus the rxjs-compat increases the bundle size.

**Comment by AlexGS74** [comment]
@tsvetomir Thank you for this clarification! Will re-evaluate my results once my project is moved to pipeable operators only.

**Comment by strizzaflex** [comment]
Thanks for the info. Good to know you are just using the old imports. And thanks for the ts-lint link so I can enforce rjxs 6 best practices while using the compt lib.

**Comment by kylekatarnls** [comment]
Hi, it seems like @progress/kendo-angular-resize-sensor latest stable (3.2.0) still use rxjs-compat (while the 4.0.0-dev.201906030706 does not). Could you release a stable 3.x free from rxjs-compat please?

**Comment by tsvetomir** [comment]
This package has been merged with @progress/kendo-angular-common. Please update to the latest Kendo UI for Angular package versions and uninstall it.

This note has been added as a deprecation notice to the package on npm to help other users.
