### ISSUE TITLE
nested grids

### ISSUE THREAD

**Issue by Snehahazare** [telerik/kendo-angular#1564]
hi i'm trying to nest grids using kendo-grids in one single html template
the issue i face is that the data bound in the inner grid is interfering with the data bound in the parent grid. the columns of the inner grid also get appended to the parent grid. 
I have one single nested json for displaying both parent and inner grid

below is my sample code: 

<html>
<kendo-grid [data]="datasource"....
 
   
<ng-template kendoGridDetailTemplate let-dataItem>
 
     <kendo-grid [data]="dataItem.accountsList" .....
      </kendo-grid>

</ng-template>
   
</kendo-grid>
</html>

## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by rkonstantinov** [comment]
I'm not able to recreate the issue using the provided information. Please check [this plunker](https://plnkr.co/edit/1jxwEdzXAWLlXSV6rQ20?p=preview).
However, note that in case a more complex layout is required, we suggest to split the inner Grid into separate component. As demonstrated in [the documentation](https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/hierarchy/).

**Comment by rkonstantinov** [comment]
I'm going to close this. Please feel free to re-open it again if additional information becomes available.
