### ISSUE TITLE
Suggestion for improvement: enum instead of string

### ISSUE THREAD

**Issue by kob-e** [telerik/kendo-angular#1565]
## I'm submitting a Suggestion for improvement

* Suggestion for improvement

## Current behavior
When using `SelectableSettings` of `grid` the property `mode` should be `single` or `multiple` as `string`

## Expected behavior
The options should be `enum`

**Comment by Raisolution** [comment]
Hi @kob-e,

The `mode` property is of union type [SelectableMode](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectableMode/) allowing the values `single` and `multiple`.
