### ISSUE TITLE
Scrolling locked columns

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1566]
When scrolling a grid with locked columns, if we scroll the unlocked columns (cursor is on top of a not locked column) there is no issue. But if we scroll the grid while the cursor is on top of a locked column, we are also scrolling the entire page not just the grid. The reported behavior occurs only if the grid's scrollbar is positioned either at its top or at its bottom. If the scrollbar is moved, then the reported behaviors does not exist.

Check the example from the following article:

[https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/](https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/)

**Comment by tsvetomir** [comment]
Fixed in v3.7.0
