### ISSUE TITLE
Error when using together PopupModule and DateInputsModule

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1567]
When importing together the PopupModule and DateInputsModule the applications crashes with the following error:

> Error: Template parse errors:
> 	More than one component matched on this element.
> 	Make sure that only one component's selector can match a given element.

Check the following sample plunker demonstrating the error:

[https://plnkr.co/edit/IaLrQ862qCZjxQLVBzHg?p=preview](https://plnkr.co/edit/IaLrQ862qCZjxQLVBzHg?p=preview)

The error is caused by a wrong import in the DateRangeModule. If it is not needed we can temporarily avoid the error by importing just the needed module. For example, if we need the DatePicker, we need to import just the DatePickerModule as demonstrated in the following example (check the app/app.module.ts file):

[https://plnkr.co/edit/NXURLAs80L8ZFSy1izWJ?p=preview](https://plnkr.co/edit/NXURLAs80L8ZFSy1izWJ?p=preview)

**Comment by ipeshev** [comment]
Fixed in v3.4.1-dev.201805291438

**Comment by tsvetomir** [comment]
Fix released in v3.4.1 of the `@progress/kendo-angular-dateinputs` package.
