### ISSUE TITLE
RxJS 6 support

### ISSUE THREAD

**Issue by aalmajanob** [telerik/kendo-angular#1568]
Dear Telerik team,

  Any ETA on this update within your different Angular componenets?

  **Installing rxjs-compat@6 is not a valid solution**. Of all the Angular components we use at Production, Kendo is always by far the latest to keep up with any Angular upgrade.

  Regards,

**Comment by tsvetomir** [comment]
There seems to be a bit of misunderstanding on how rxjs-compat actually works. If you take a look at the [source code](https://github.com/ReactiveX/rxjs/blob/master/compat/operators/buffer.ts), you'll see that it only contains re-exports. They will be folded during the build process, resulting in an identical output as when using the new RxJS 6.0 entry points.

It's a very clever solution, that _does not alter how RxJS_ works. Any code that does not rely on backwards-compatibility will work in exactly the same way with rxjs-compat or not.

At the same time it allows us to keep updates flowing to Angular 4 and 5 users. It's a trade-off, but we feel it's important not to leave customers stranded.

**Comment by aalmajanob** [comment]
Dear tsvetomir,

  Thanks for the info, anyway **does Telerik plan to make its Angular components RxJS 6 native? If yes, do they have any estimated date?**

  Regards,

**Comment by tsvetomir** [comment]
We plan to drop the requirement for `rxjs-compat` shortly after Angular 5 reaches end-of-life in [April 2019](https://angular.io/guide/releases#long-term-support).

The initial plan was for October 2018 when Angular 4 reaches EoL, but the LTS was extended to include all releases.

**Comment by aalmajanob** [comment]
Thanks for the fast reply tsvetomir.

Regards,

**Comment by Ristaaf** [comment]
Could be good to know that using rxjs-compat seems to break unit-testing in angular-cli, so we are eagerly awaiting the removal of the dependency in kendo! https://github.com/angular/angular-cli/issues/10485

**Comment by tsvetomir** [comment]
@Ristaaf let's give the CLI team a bit more time - this looks like something that must be fixed there.

**Comment by aalmajanob** [comment]
Sincerely @Ristaaf, from our experience with Kendo UI, its better to look for any other Real alternative. Thanks we have been replacing the different modules and now we only use Grid´s one :)

Regards,

**Comment by shmuel-slate** [comment]
I think I am talking on behalf of all your customers, @tsvetomir, what the problem to have 2 versions?
While you keep some of your customers happy, you are making most of them upset!

**Comment by tsvetomir** [comment]
@shmuel-slate the most significant problems are:
* Users would have to figure out what version (or dist tag) of the components to use based on the Angular version in your project
* Projects using Angular 4 and 5 would break upon installing the latest versions of the Kendo UI packages. These versions are supported until October 2018 and April 2019 respectively.
* Users would have to update their projects to Angular 6 to receive updates to the Kendo UI components. The legacy versions would get only critical bug fixes, if any.

At the same time, the only noticeable improvement in user projects would be the omission of rxjs-compat. Please note that rxjs-compat does not include any legacy RxJS code - it only re-exports RxJS 6.x code at different locations.

**Comment by oocx** [comment]
Being able to ommit rxjs-compat is important for us, as otherwise our developers could just accidentally use the old apis. We have about 40 developers on our team. Simply removing rxjs-compat is much easier and cheaper than explaining to all of them which parts of rxjs are ok to use and which parts are not. Exposing two different sets of apis for rxjs is confusing and increases training and maintenance costs.

**Comment by tsvetomir** [comment]
We'll be getting rid of rxjs-compat in the coming month. We hope to release updated versions of all packages shortly after the support expiration date for Angular 5 - May 1.

**Comment by michaelfaith** [comment]
Any update on this fix?  Appears to be a couple months overdue.
