### ISSUE TITLE
TreeView with checkbox : indeterminate state problem

### ISSUE THREAD

**Issue by GuillaumeMante** [telerik/kendo-angular#1569]
## I'm submitting a...

* Bug report 

## Current behavior

In a treeview with checkbox, when the number of elements is superior to 10, if we check an element with an id superior to 10 (or 10), the element with the id : 1 switch to the indeterminate state.

## Expected behavior

The element with the same decimal number, as the one we check, doesn't have to switch to the indeterminate state.

## Minimal reproduction of the problem with instructions

Here is a plank with an example: [link](https://plnkr.co/edit/7fH4yjIIR8FUVEs8MDNk?p=preview)
You can reproduce the bug when you check element 0_10, 0_11, 0_12 or 10, 11 ,12.

**Comment by rkonstantinov** [comment]
Should be fixed with https://github.com/telerik/kendo-angular/issues/1701
