### ISSUE TITLE
Getting Started Guide includes deprecated steps

### ISSUE THREAD

**Issue by av8orbynight** [telerik/kendo-angular#1572]
## I'm submitting a...

* Documentation issue or request

## Current behavior

Created new Telerik account, am on Kendo UI for Angular trial. Got email. Email contained link to:

https://www.telerik.com/blogs/using-kendo-ui-with-angular-2?utm_medium=email&utm_source=eloqua&utm_campaign=dt-kui-angular-trials&elqTrackId=36A29C7ECD8D20E9E5F2144516EAC921&elq=c46fb12a2469499cacee75438aae2f2e&elqaid=11591&elqat=1&elqCampaignId=13963

This link contains steps to point to the Telerik registry, which has been deprecated. 

## Expected behavior

...

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by tsvetomir** [comment]
Thanks for reporting, I'll forward this to our marketing team.

/cc @bergenhem
