### ISSUE TITLE
Nested panelbar titles are not remembering previous expanded state 

### ISSUE THREAD

**Issue by Mathijs003** [telerik/kendo-angular#1574]
## I'm submitting a...
* Bug report
* Suggestion for improvement

## Current behavior
Nested panelbar titles are not remembering previous expanded state when parent panelbar is withdrawn and expanded again with and expanded child panelbar. This is also an issue in the example panelbar [here](https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/) 

When collapsing the parent panelbar the user must click twice on the nested panelbar in order to collapse the nested panelbar. Also the indication arrow seems to remember the previous state and points in the wrong direction

## Expected behavior
two possible ways: 

Best and first way: The nested panelbar should remember the state and when the parent panelbar withdraws and collapses again, the child panelbar should be in the same expanded state. 

second and possible quickfix: Make the indication arrow point to the right direction after withdrawing and collapsing a parent panelbar and make sure the user don't have to click twice to collapse the child again

## Minimal reproduction of the problem with instructions

The example page of the panelbar overview in Kendo UI for angular shows this problem.

https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/

Use the panelbar 'Projects', collapse 'Sales Forecasts', withdraw 'Projects' and collapse 'Projects' again. Now the 'Sales Forecasts' arrow is pointing upwards as if the panelbar was expanded but no expanded part is visible. When you now want to collapse the 'Sales Forecast' you need to click on it twice.

## What is the motivation or use case for changing the behavior?

This is a bug, and a bug visible in the example of Kendo UI

## Environment

Not related to environments.

Browser:
- Chrome (desktop) 
- Firefox

**Comment by danielkaradachki** [comment]
Possible workaround for the moment is to use the [keepItemContent](https://www.telerik.com/kendo-angular-ui/components/layout/api/PanelBarComponent/#toc-keepitemcontent) option:
https://plnkr.co/edit/svoFqQLhUWD3smQ87Aro?p=preview

**Comment by Mathijs003** [comment]
@danielkaradachki Works perfectly, thanks!

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0

https://stackblitz.com/edit/angular-gujygz?file=app/app.component.ts

**Comment by montella1507** [comment]
@danielkaradachki  same problem with:
"@progress/kendo-angular-treelist": "2.0.0"

Checkboxes / expanders dont keep their state  (even with correct doubleway binding to selections array) 

(keeping things in DOM is not a solution as you know) ->  so i mention treelist because i think you fixed this issue in PanelBar component (and nto treelist as well?)
