### ISSUE TITLE
Switch component with Material theme doesn't slide properly

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-angular#1577]
## I'm submitting a...
* Bug report

## Current behavior
Switch component with Material theme layout does not slide over properly when its current state is "on".
Image here:

![image](https://user-images.githubusercontent.com/8842674/40770206-aa952be2-64c2-11e8-8d4e-b14f30f64cb6.png)

## Expected behavior
When having a state "on", the switch handle should be transformed at the right end of the the switch tracker. 
Image here:
 
![image](https://user-images.githubusercontent.com/8842674/40770187-9e9a8c6a-64c2-11e8-9305-69221cd49112.png)

## Minimal reproduction of the problem with instructions
Plunker link here: https://plnkr.co/edit/02jWxvUtEgRm6jsa0KnV?p=preview

**Comment by ipeshev** [comment]
Fixed in v3.1.4-dev.201806221046

**Comment by danielkaradachki** [comment]
Released in 3.2.0

**Comment by danielkaradachki** [comment]
The latest version seems to work correctly on my side with or without production build. If you are experiencing problems with the latest version then please open a separate issue with more detailed information.
