### ISSUE TITLE
ButtonGroup can't be shown properly on IPad using angular mode

### ISSUE THREAD

**Issue by raysbo** [telerik/kendo-angular#1578]
The issue:
ButtonGroup can't be shown properly on IPad using angular mode.

The Demo:
Open the case on IPad. https://demos.telerik.com/kendo-ui/buttongroup/angular

* Bug report 

## Current behavior
 The issue exists on https://demos.telerik.com/kendo-ui/buttongroup/angular. if we open it on ipad, the button group can't be shown properly.

## Expected behavior

The button group should be shown properly.

## Package versions:
The latest version.

Browser:

- Safari (iOS) version XX

**Comment by tsvetomir** [comment]
Seems like this issue is related to Kendo UI for jQuery. Please log it in the [kendo-ui-core issue tracker](https://github.com/telerik/kendo-ui-core/issues) for assistance.
