### ISSUE TITLE
DateRange: Different behavior / view in IE11

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1580]
## I'm submitting a...
* Bug (or Feature) report  

## Current behavior
When I open the DateRange in Chrome, I see two months, in IE 11 only one

## Expected behavior
In IE11 also two months

## Minimal reproduction of the problem with instructions
Using your sample:
https://plnkr.co/edit/v8UG5Bgta4oeK5Y2POAD?p=preview

1. Open DateRange in IE 11

## Environment

Browser:
- IE version 11.48

**Comment by gyoshev** [comment]
The following CSS code workarounds the issue, until a theme fix is published:

```css
.k-calendar-view .k-content tbody {
    display: inline-block;
}
```

Here is the [updated StackBlitz demo](https://stackblitz.com/edit/angular-mpanhp?file=styles.css).

**Comment by dimitar-pechev** [comment]
Fixed way back in `@progress/kendo-theme-default@2.56.0`. ([#269](https://github.com/telerik/kendo-themes/pull/269))
