### ISSUE TITLE
Support drag events for TreeView nodes

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1582]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

The TreeView nodes when used with kendoTreeViewNodeTemplate does not allow for (dragstart) and (dragend) events to be fired.

## Expected behavior

div elements nested within a kendoTreeViewNodeTemplate should support drag events.

## Minimal reproduction of the problem with instructions

Check the following sample plunker:
[https://plnkr.co/edit/VG2J6g8rU2Q5kwG5WQtl?p=preview](https://plnkr.co/edit/VG2J6g8rU2Q5kwG5WQtl?p=preview)

When trying to drag any of the Tree nodes, the (dragstart) event is not fired. But the "Draggable DIV" element defined outside of the TreeView does fire the event.

**Comment by tsvetomir** [comment]
Please cast your vote for [this feature](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/33369232-drag-drop-for-treeview-component) on our UserVoice portal. I'm closing this issue to avoid duplication.

**Comment by hotdog1987** [comment]
@tsvetomir how many votes are needed for this feature request? I see there are 100+ votes already. We could really use this feature. Thank you.

**Comment by tsvetomir** [comment]
@hotdog1987 noted, the vote count is convincing as it is. I can't tell when we'll be able to get to it, but we will make sure to include it in our release planning.
