### ISSUE TITLE
document.getElementById() is not working for element inside Kendo Splitter

### ISSUE THREAD

**Issue by Mathijs003** [telerik/kendo-angular#1590]
## I'm submitting a...
* Bug report 

## Current behavior
document.getElementById() is returning 'null' for element in kendo splitter pane.

## Expected behavior
The function should return the element instead of 'null'

## Minimal reproduction of the problem with instructions
[https://plnkr.co/edit/Jqm9Y8QdHPls6g4RGVHR?p=preview](https://plnkr.co/edit/Jqm9Y8QdHPls6g4RGVHR?p=preview )

## What is the motivation or use case for changing the behavior?
This is a bug

## Environment

Angular 5.2.0
kendo-angular-buttons: "^4.0.0",
kendo-angular-dropdowns: "^2.1.0",
kendo-angular-inputs: "^2.2.0",
kendo-angular-intl: "^1.4.0",
kendo-angular-l10n: "^1.1.0",
kendo-angular-layout: "^2.2.1",
kendo-theme-default: "^2.50.0",

Browser:

- Chrome (desktop)

System:
- TypeScript version: 2.5.2
- Node version: v8.9.4
- Platform:  MAC OSx

**Comment by gyoshev** [comment]
[Updated plunker](https://plnkr.co/edit/ov2UwNXlW2EshrslClaC?p=preview). Please refer to the the [lifecycle events Angular documentation](https://angular.io/guide/lifecycle-hooks#afterview).
