### ISSUE TITLE
Dynamic switch of orientation breaks slider

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1592]
## I'm submitting a...

* Bug report 

## Current behavior

Dynamic change of orientation breaks slider totally
## Expected behavior

Dynamic change of orientation should not break the slider
## Minimal reproduction of the problem with instructions

1. Open this [plunk sample](https://plnkr.co/edit/mqSy2R2l0ohabznkeVli?p=preview)
2. Switch the orientation with the button.
## Environment

Package versions:

```
broken in v3.1.3-dev.201806011000
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by dtopalov** [comment]
This issue is fixed in the 6.4.2 version of the Inputs package

https://www.telerik.com/kendo-angular-ui/components/inputs/changelog/
