### ISSUE TITLE
Use TextBox with mask and floating label

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1594]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

When we have a masked text box with a floating label, the label will not move in and out of the textbox as there is a mask but it will stay on top of the textbox:

[https://plnkr.co/edit/PA8QIsJVPB0Bx2wydj3B?p=preview
](https://plnkr.co/edit/PA8QIsJVPB0Bx2wydj3B?p=preview
)
## Expected behavior
The floating label should move in and out of the masked textbox. Check the following sample plunker that demonstrates a workaround in order to achieve the desired behavior:

[https://plnkr.co/edit/a5R5sXenZLY5RkdSS6BC?p=preview](https://plnkr.co/edit/a5R5sXenZLY5RkdSS6BC?p=preview)

**Comment by tsvetomir** [comment]
The suggested workaround is the best that can be done at the moment. A built-in solution would require that the textbox container has control over the mask value.
