### ISSUE TITLE
[Grid filtering] Cannot hide filter menu buttons

### ISSUE THREAD

**Issue by talcarl** [telerik/kendo-angular#1596]
## I'm submitting a issue about Cannot hide filter menu buttons

* Bug report 

## Current behavior
Use https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-filter-menu here.
For the popup filter menu, we have no way to hide the button panel
![image](https://user-images.githubusercontent.com/35125543/41073404-ae29711e-6a35-11e8-932c-2a1aed3c9764.png)

## Expected behavior
Able to hide button panel, or even custom the entire popup content

## Minimal reproduction of the problem with instructions
1. Click filter icon on grid
2. Filter menu shows up

## What is the motivation or use case for changing the behavior?
To  customize a fulltext search on grid table in single field

## Environment
Test

Package versions:
+-- @angular/animations@4.4.7
+-- @angular/cli@1.4.10
+-- @angular/common@4.4.6
+-- @angular/compiler@4.4.6
+-- @angular/compiler-cli@4.4.6
+-- UNMET PEER DEPENDENCY @angular/core@4.4.6
+-- @angular/forms@4.4.6
+-- @angular/http@4.4.6
+-- @angular/language-service@4.4.6
+-- @angular/platform-browser@4.4.6
+-- @angular/platform-browser-dynamic@4.4.6
+-- @angular/router@4.4.6
+-- @ngrx/core@1.2.0
+-- @ngrx/store@2.2.3
+-- @ngrx/store-devtools@3.2.4
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-buttons@3.0.4
+-- @progress/kendo-angular-dateinputs@3.2.0
+-- @progress/kendo-angular-dialog@3.6.0
+-- @progress/kendo-angular-dropdowns@3.0.0
+-- @progress/kendo-angular-excel-export@2.0.0
+-- @progress/kendo-angular-grid@3.2.0
+-- @progress/kendo-angular-inputs@3.1.0
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-layout@3.1.0
+-- @progress/kendo-angular-menu@0.3.0
+-- @progress/kendo-angular-ripple@1.0.0
+-- @progress/kendo-angular-toolbar@0.2.0
+-- @progress/kendo-angular-tooltip@0.2.0
+-- @progress/kendo-angular-treeview@2.2.0
+-- @progress/kendo-data-query@1.3.1
+-- @progress/kendo-drawing@1.5.4
+-- @progress/kendo-theme-default@2.48.1
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.101
+-- angular-webstorage-service@1.0.2
+-- codelyzer@3.2.2
+-- core-js@2.5.3
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.4.2
+-- karma-jasmine@1.1.1
+-- karma-jasmine-html-reporter@0.2.2
+-- npm@6.0.1
+-- protractor@5.1.2
+-- rxjs@5.5.10
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.3.4
`-- zone.js@0.8.20

Browser:
- Chrome (desktop) Version 66.0.3359.181 (Official Build) (64-bit)

System:
- "typescript": "~2.3.3"
- Node version: v8.9.4
- Platform:  Windows 10

**Comment by rkonstantinov** [comment]
There is intentionally no built-in option to hide the filter menu buttons, as they are core part of the built-in filter menu functionality and hiding them will render the filter menu useless. 

However, if you insist on hiding them you could achieve this via custom CSS, similar to the following:
```js
    encapsulation: ViewEncapsulation.None,
    styles: [`
        .k-filter-menu .k-button-group {
            display:none;
        }
    `],
```

**Comment by talcarl** [comment]
@rkonstantinov Thank you. Your code works for my case.

**Comment by shreenil** [comment]
How do i hide those buttons only for specific columns?
I tried to see if there is anything from which i can identify column of filter popup but i was not able to do so. 
Any help on this will be appreciated. Thanks!

**Comment by aleixsuau** [comment]
Hi Kendo,

I'm really upset with this design, I think that using a template should never place additional elements in the UI. This is the expected behavior of a template, to fully customize the UI.

Furthermore, I don't understand why are you coupling the kendoGridFilterMenuTemplate to the FilterService, we should be free to filter the grid data in the way we want. 

Best
