### ISSUE TITLE
[Bug] Splitter - Wrong pane resized

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1597]
## I'm submitting a...

* Bug report 

## Current behavior

Hi.
Let's say you have 3 panes.
If you set the size of the last two, you can resize all of them correctly. 
But, if you set the size of the first two panes, the last pane will be resized when you try to resize the first one.

![](https://i.imgur.com/emlLzGV.gif)

## Expected behavior
The left one should be resized ?

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/IhMpaKTUdcfRKS8MClO8?p=preview

## Environment

Browser:
- Chrome (desktop) version 67.0.3396.79 
- Firefox version 53.0.2

**Comment by gyoshev** [comment]
Thanks for reporting this. A temporary workaround for this specific setup is to set the size of the first and last panes, leaving the middle pane with no set size ([updated plunker](https://plnkr.co/edit/Dq01K8MeQK7L8g9N9zyL?p=preview)).

**Comment by gyoshev** [comment]
A fix for this bug has been published on the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-layout` package, version `v3.1.3-dev.201809141347`.

**Comment by gyoshev** [comment]
Published officially in `v3.1.3`
