### ISSUE TITLE
Filter Menu is not accessible with keyboard

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1598]
## I'm submitting a...
* Bug report 

## Current behavior
The [Filter Menu](https://www.telerik.com/kendo-angular-ui/components/grid/filtering/#toc-filter-menu) is not accessible with the keyboard with both `navigable` set to `true` and `false`. In both cases:
* The tab order is inconsistent
* Esc/Enter do not close the menu

## Expected behavior
* The filter menu icon should gain focus when the cell is activated with Enter.
* Pressing Enter on the focused icon should open the menu
* The focus should be moved to the first focusable item in the menu
* Tab should cycle within the filter menu items
* Esc should close the menu, discarding any input
* Enter should confirm the filter action

## Minimal reproduction of the problem with instructions
* [Example with `[navigable]="true"`](https://plnkr.co/edit/VPmyKuS9OV2nYzyLvzIN?p=preview)
* [Example with `[navigable]="false"`](https://plnkr.co/edit/HuaDa0M37WfbPiyM8D6b?p=preview)

## What is the motivation or use case for changing the behavior?
The described behavior is in accordance to the WAI-ARIA Authoring Practices for [Editing and Navigating Inside a Cell](https://www.w3.org/TR/wai-aria-practices-1.1/#gridNav_inside).

## Environment
N/A

Browser:
N/A

**Comment by svetq** [comment]
The same seems relevant for the Column Menu.

**Comment by mbechev** [comment]
Reported in private support threads - **1483160**, **1483313**.
