### ISSUE TITLE
Multiselect DropDown - Feature Request

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#160]
With the current Kendo Ui ng1 Multiselect its not possible to avoid linebreaks when you have selected a lot of Items. 

![kendo multiselect](https://cloud.githubusercontent.com/assets/1572878/21632942/4dcd481e-d24b-11e6-8a19-0e50aefb488d.png)

But It would be cool if just the normal DropDown with its feautures would allow do multiselect its items or if the standard Multiselect would allow to avoid the linebreaks. A possible solution would be to add only one label with the text of the selected Items and an ellipsis when there get selected too many items to show all text, then you show the text hole text in the tooltip.

And also nice would be to have an option for "Select All" and "Deselect All"

![dropdown](https://cloud.githubusercontent.com/assets/1572878/21632879/b7cea664-d24a-11e6-86dc-dae0edffee7c.png)

**Comment by ggkrustev** [comment]
Hi @squadwuschel,

Thank you for the feature request! Indeed, an 'inline tag' mode will be helpful for those that want to avoid line breaking. 

The initial version of MultiSelect will have only 'multiple tags' mode for the time being, just like the current Kendo UI MultiSelect. Most probably, we will add a different tag rendering mode to the MultiSelect to support the desired behavior, something like the ['single tag' mode in the current Kendo UI MultiSelect](http://demos.telerik.com/kendo-ui/multiselect/tag-mode). Based on your suggestion, I tend to believe that this will be sufficient to accomplish your business requirements. Is that true?

With regards to the 'Deselect/Select All', what will be desired behavior? Clearly, those buttons will be select/deselect all items in the list. What should be the desired behavior when list is **filtered**? Considering that the data is missing, the button should be *disabled*. I'll be grateful to hear and your opinion on the topic.

**Comment by squadwuschel** [comment]
Hi,

yes the no linebreak behavior is very important for my business requirements, because the multiline mode breaks my formulars every time, e.g. when you habe two column formulars and you try to get them on the same "height".

I think it would be good do add a function where you can tell the dropdownlist how to fill up the single tag mode.


I think the select/deselect option should ignore the filter, because its only for removing all selections or to select all items in the list and not to filter and only add the filtered items. Mostly when I filter a list I am searching for a single item. 

Or when its possible for other people buisness requirements add a option to activate the other behavior you mentioned above.

**Comment by ggkrustev** [comment]
Hi @squadwuschel, 

thank you very much for the additional details. They will be very helpful when we decide how to proceed with the future multiselect development.

**Comment by ggkrustev** [comment]
I will close this issue for now, as there is logged UserVoice item:

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback/suggestions/17762557-dropdown-with-multiselect-ability

I would invite every interested in this functionality to cast his/her vote for it.

**Comment by squadwuschel** [comment]
I thought you where working on it like John Bristowe "tells" me

https://twitter.com/JohnBristowe/status/823928453346955264

:-)

**Comment by squadwuschel** [comment]
@ggkrustev any progress with the multiselect dropdown?

**Comment by bipin244** [comment]
Hello any progress with the multiselect dropdown?

**Comment by jburtondev** [comment]
Hi @ggkrustev. Any progress on the select all option?

**Comment by coderabin01** [comment]
Can you please add Select All/ Deselect All option in Kendo multi-select drop-down.
