### ISSUE TITLE
Grid not refreshed with pageable

### ISSUE THREAD

**Issue by nlgi** [telerik/kendo-angular#1600]
## I'm submitting a...

* Regression report 

## Current behavior

Exactly the same bug here: https://github.com/telerik/kendo-angular/issues/743
Only if pageable is setting on true (with pageSize of course)

## Expected behavior
Grid has to refresh when data is updated

Package versions:
@progress/kendo-angular-grid@3.4.0

Browser:

- Chrome (desktop) version 66

System:
- TypeScript version: 2.7.2
- Node version: 9.8
- Platform:  Windows

**Comment by rusev** [comment]
Hey @nlgi,

Does the solution proposed in https://github.com/telerik/kendo-angular/issues/743 work for you or you having a different type of a problem?
