### ISSUE TITLE
[MultiSelect] The items not get selected when changing the value

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1601]
## I'm submitting a...

* Bug report 

## Current behavior

The value of the MultiSelect does not get properly updated when changing it through its [value] input property.

## Expected behavior

The items of the MultiSelect should be properly selected when updating its value. (Currently, only the last item is selected and we can remove only it from the selection.)

## Minimal reproduction of the problem with instructions
Check the following sample plunker:
[https://plnkr.co/edit/PpF23iwqQjV1u7i6xZSw?p=preview](https://plnkr.co/edit/PpF23iwqQjV1u7i6xZSw?p=preview)

1. Click the "Change val" button.
2. Check the selected items and try to remove the first item.

**Comment by ipeshev** [comment]
Fixed in v3.0.3-dev.201808011119

**Comment by tsvetomir** [comment]
Shipped in v3.0.3
