### ISSUE TITLE
Kendo grid column not formatting date properly - angular 4

### ISSUE THREAD

**Issue by DineshThangella** [telerik/kendo-angular#1602]
I have a date column where am trying to format in the following way

`<kendo-grid-column title="Last Modified" field="lastModifiedDate" filter="Date"
format={0:MM/dd/yyyy}" [width] = "200">`

I am creating the field using FormControl

`const createFormGroup = dataItem => new FormGroup({
  'lastModifiedDate': new FormControl(dataItem.lastModifiedDate, 
});`

I am getting date field from rest api in the format "lastModifiedDate": "03-25-2018",  am trying to format it in "03/25/2018"  using above code but it is not formating.

**Comment by rkonstantinov** [comment]
In order formatting to work the value to be formatted should be a `Date` instance. In the described scenario it seems that it is a `String` instead. 

You will need to convert the value manually prior to passing it to the Grid component. For example:

```js
const createFormGroup = dataItem => 
      new FormGroup({ 
               'lastModifiedDate': new FormControl(new Date(dataItem.lastModifiedDate)), 
      });
```

If you need additional assistance please open [a support ticket](https://www.telerik.com/account/support-tickets), as this repository is for bug reports only.
