### ISSUE TITLE
keno numeric textbox change event in angular 2

### ISSUE THREAD

**Issue by kalyanimanu** [telerik/kendo-angular#1603]
<kendo-numerictextbox name="crowdAverageTime"  value="" [min]="0" [max]="100"  [(ngModel)]="crowdBudgetRequestData.crowdAverageTime" name="crowdAverageTime"
                                id="crowdAverageTime" #crowdAverageTime="ngModel">
                                </kendo-numerictextbox>

can anyone suggest me change event handling for this textbox in angular2 componenet.ts file

**Comment by ggkrustev** [comment]
The NumericTextBox has `valueChange` event, which follows the Angular name convention enabling banana in a box syntax ( [(value)] ). I would suggest you check the documentation for the `valueChange` event.

https://www.telerik.com/kendo-angular-ui/components/inputs/api/NumericTextBoxComponent/#toc-valuechange

Also It will be best if you peruse the Angular documentation for Input/Output properties.

https://angular.io/guide/template-syntax#binding-syntax-an-overview

As a side note I will close this thread as it discusses general topic and does not report neither a bug or feature request. Please open a support ticket if you need further assistance on the subject.
