### ISSUE TITLE
Tabbing methods not supported in kendo angular grid?

### ISSUE THREAD

**Issue by snspvd** [telerik/kendo-angular#1605]
The below mentioned methods and properties are working in kendo angular examples as mentioned in plunker but it's not  supporting in my local machine
 **activeCell , activeRow, focusPrevCell, focusNextCell**

https://plnkr.co/edit/?p=preview

**Comment by tsvetomir** [comment]
Please make sure that you're using the latest version of the `@progress/kendo-angular-grid` package.  
You can easily check and update all packages using the [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) utility:

```sh
npm install -g npm-check-updates
ncu -u -f /^@progress/
```

Make sure to consult the [Changelog](https://www.telerik.com/kendo-angular-ui/components/grid/changelog/) for each component for breaking changes when updating major versions.

**Comment by snspvd** [comment]
Even after updated to latest packages (3.5.0) it still throwing same issue

**Comment by tsvetomir** [comment]
Please, share a sample project in a support ticket and we'll investigate and provide assistance.
