### ISSUE TITLE
DropDowns list of options do not fill the Popup when popup height is set, but listHeight is not

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1607]
When the Popup height is set via popupSettings, but listHeight is not, the actual list of options has the default height of 200px while the rest of the Popup is empty:

[https://plnkr.co/edit/miQxWjKQL5M3ptsNw7Tx?p=preview](https://plnkr.co/edit/miQxWjKQL5M3ptsNw7Tx?p=preview)

It would be better to infer the list height of the popupSettings height set so that the developers do not have to set listHeight explicitly in such scenarios.

**Comment by carlosresendiz** [comment]
I think that in previous version the heigh was set as max-heigh and now is set as heigh

**Comment by dtopalov** [comment]
Also, the width of the Popup cannot be configured to be smaller than the width of the component.

**Comment by xinthose** [comment]
bump?

**Comment by xinthose** [comment]
Apparently, you have to set the [`listHeight` ](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/AutoCompleteComponent/#toc-listheight)property.
