### ISSUE TITLE
Ripple efect broken in Safari / OSX

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1608]
## I'm submitting a...

* Bug report 

## Current behavior
The ripple effect is not rendered correctly in Safari on OSX
![safari-ripple](https://user-images.githubusercontent.com/247917/41339855-9a6216cc-6efe-11e8-9fe6-65692d413450.gif)

## Expected behavior
The ripple effect should appear as in other browsers.

## Minimal reproduction of the problem with instructions
1. Open [Material Theme preview](https://www.telerik.com/kendo-angular-ui/components/styling/theme-material/)
1. Click on any of the buttons in the preview app

## Environment

Browser:
- Safari (desktop) version 11.1.1

**Comment by gyoshev** [comment]
Fixed in `@progress/kendo-angular-ripple@1.0.2` and will be deployed with the next site upload.
