### ISSUE TITLE
Issue with the kendo switch in grid column

### ISSUE THREAD

**Issue by pravekumar1** [telerik/kendo-angular#1610]
Please find the plunker link below where kendo switch is editing mode default. But it should be editable mode when we click on the switch
https://plnkr.co/edit/l0DPPDAtQsW6Z03fDXN1?p=info

**Comment by tsvetomir** [comment]
Please, use the support ticketing system for general inquiries regarding component usage.

If you think you've found a bug, use the provided template to submit a bug report.
