### ISSUE TITLE
TimePicker no message translation for Hour, Minute and Second

### ISSUE THREAD

**Issue by Jahrenski** [telerik/kendo-angular#1613]
Currently it is possible to translate some of the messages of the TimePicker but it is impossible to translate the hour, minute and second messages.

I expect to be able to translate all the messages.

Current messages : 
[https://github.com/telerik/kendo-angular-messages/blob/develop/messages/timepicker/timepicker.en-CA.yml](https://github.com/telerik/kendo-angular-messages/blob/develop/messages/timepicker/timepicker.en-CA.yml)

I don't want to open a new ticket for this but the same goes for "No data found" from the dropdownlist.

**Comment by ggkrustev** [comment]
The titles of the `hour`, `minute`, `second` messages are kept in the Internationalization scripts. If you would like to update them, then you will need to load the corresponding i18n script, as it is shown in this plunk.

https://next.plnkr.co/edit/LsQlmKas5OXh1buZ

I will close the thread as it doesn't report a bug, but rather discusses specific configuration of the component.

Please feel free to comment below if I am missing something.

**Comment by Jahrenski** [comment]
Thanks for the info!
Is there a particular reason parts of the translations are using a different system?

**Comment by ggkrustev** [comment]
The Unicode organization, particularly CLDR, which holds the format/parse details about the number/date types also keep track of the translation of all related date/number words, e.g. month names, currency naming and etc. That is why we use it in this particular case.

For all component related mesages, which cannot be retrieved from CLDR we provide specific message properties.

I hope this information clarifies a bit the case.

**Comment by grzechup** [comment]
Why don't you just let the user change these values ​​just like the rest. It would really spare unnecessary work

**Comment by tsvetomir** [comment]
@grzechup it's now possible to [modify the locale data](https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/loading-data/#toc-modifying-the-locale-data), see [runnable example](https://stackblitz.com/edit/angular-hvwary?file=app/app.module.ts).

For a list of the available fields, take a peek at the [locale definitions](https://unpkg.com/@progress/kendo-angular-intl@2.0.0/locales/en/calendar.js). We also ship [type definitions](https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/api/Locale/) that should enable auto-complete in your favorite IDE.

**Comment by grzechup** [comment]
@tsvetomir  Awesome, thanks!
