### ISSUE TITLE
kendo-angular-dateinputs 3.4.1 still depends on kendo-angular-popup ^2.0.0

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#1614]
## I'm submitting a...
* Bug report 

## Current behavior
kendo-angular-dateinputs 3.4.1 (and other kendo packages) still have a dependency on kendo-angular-popup ^2.0.0 in their package.json. So when installing it, the nested package of kendo-angular-popup version 2.0.2 is installed (inside the node_modules folder of the kendo-angular-dateinputs package). But it requires a newer version.
So now my angular-cli build fails with these errors:

ERROR in node_modules/@progress/kendo-angular-dateinputs/dist/es2015/daterange/date-range-popup.component.d.ts(2,28): error TS2305: Module '"node_modules/@progress/kendo-angular-dateinputs/node_modules/@progress/kendo-angular-popup/dist/es2015/index"' has no exported member 'Margin'.
node_modules/@progress/kendo-angular-dateinputs/dist/es2015/daterange/date-range-popup.component.d.ts(2,36): error TS2305: Module '"node_modules/@progress/kendo-angular-dateinputs/node_modules/@progress/kendo-angular-popup/dist/es2015/index"' has no exported member 'PopupAnimation'.

Seems to work fine in a fresh package.json. The popup package is installed automatically on the highest level and no nested package will be installed.

Added the popup package explicitly in my package.json does not solve the problem.

## Expected behavior
Correct versions installed

## Minimal reproduction of the problem with instructions
No idea :-(

## What is the motivation or use case for changing the behavior?
Getting my build running

**Comment by JaapMosselman** [comment]
When I install my packages with "yarn install --flat" (obviously I am using yarn package manager) it will not install the nested packages (but I need to choose which version of lots of packages, which will be saved as 'resolutions' in my package.json. Don't know if I like that).

**Comment by tsvetomir** [comment]
The `@progress-kendo-angular-popup` package is currently at v2.4.1 so ^2.0.0 is referencing the latest version. Have you tried re-creating the yarn.lock file - it might be holding on to an older version of the Popup.

**Comment by JaapMosselman** [comment]
Thanks for the suggestion. I already did try removing the whole node_modules folder and reinstall, but that didn't work. Now I also removed the yarn.lock file and the node_modules folder and reinstalled. And now everything seems to work fine!
(I am not aware of a yarn command to re-create the lock file, so I just deleted it)
