### ISSUE TITLE
kendo-menu : no reliable way to get mouseEvent

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#1615]
## I'm submitting a...

* Bug report 
* Suggestion for improvement

## Current behavior

Hello. 
I am trying to get the mouseEvent when a user selects a menu item, but it is unreliable.
If I use the (select) event of the menu, I only get the menuEvent.
If I use the (click) event of the menu, I don't get the mouseEvent for the submenus (items of the main menu).
If I use kendoMenuItemTemplate and set a (click) on the inside tag, the user can easily click outside of that tag and the menu closes without triggering the click event.
![image](https://user-images.githubusercontent.com/22844693/41516645-87dde5c4-72e8-11e8-90ec-cf1129ed2a1d.png)

(only the red part triggers the (click) event.)

## Expected behavior

I mainly need the altKey and ctrlKey booleans for the desktop version. Is there a way to add it to the menuEvent, retrieve the mouseEvent from the menuEvent, or get the (click) event from a whole cell ?

**Comment by danielkaradachki** [comment]
Would adding the original DOM event to the select event argument work for you? The selection may also be triggered via the keyboard. 
You could also use a [linkTemplate](https://www.telerik.com/kendo-angular-ui/components/menu/templates/#toc-link-template) to bind a handler to the entire element.

**Comment by Neaco** [comment]
Thanks for the quick answer. Adding the original DOM event would be perfect. 

I tried the linkTemplate and it does the trick. 🙂 
When I read the name I thought it was more related to urls and routing so I didn't check in enough details. I barely needed to add a span for the icons and it was perfect.
The keyboard navigation isn't really usable on my end so this is what I'll use.

Thanks !
