### ISSUE TITLE
Disable item selection from combobox

### ISSUE THREAD

**Issue by alohaprashant** [telerik/kendo-angular#1616]
Need to disable some items from selection in Kendo UI comboBox angular .

In Simple select option
`<select>`
`  <option value="aaa" [disabled]="">Volvo</option>`
`  <option value="bbb">Saab</option>`
`  <option value="ccc>V</option>`
`</select>`

In Kendo UI angular 2

`<div class="example-wrapper">`
`            <kendo-combobox`
`                [data]="listItems"`
`                [textField]="'text'"`
`                [valueField]="'value'"`
`                [value]="selectedValue"`
`                [valuePrimitive]="true">`
`                <ng-template kendoComboBoxItemTemplate let-dataItem>`
`                    <span class="template">{{ dataItem.value }}</span> {{ `
`                       dataItem.text }}`
`                </ng-template>`
`            </kendo-combobox>`
`</div>`

**Comment by valchev** [comment]
Hi @alohaprashant 

there is a feature request item for this functionality at Kendo Angular User Voice portal. You may vote for it using [this link](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/32809279-easy-support-for-disabled-items-in-dropdownlist). The more votes it collects, the higher priority it will have when we build the roadmap.
