### ISSUE TITLE
DateInput validation fails with numeric keys [HH:mm].

### ISSUE THREAD

**Issue by Danny908** [telerik/kendo-angular#1618]
The "min" and "max" validation fails using the "HH:mm" format.
Pressing any numeric key return the current day instead of change the provided date.

Here's the reproduction of the bug: [Plunker](https://next.plnkr.co/edit/4zO873ylPi3ORHyW?preview)

Change the "short date input" with the arrow keys and then with the numeric keys to reproduce the bug.

Only tested on  Chrome (desktop) version 67.0.3396.87

**Comment by ggkrustev** [comment]
A fix was pushed in the latest DEV release of the @progress/kendo-angular-dateinputs package. Please give it (v3.4.2-dev.201806190859) a try and let us know whether issue is still present.

**Comment by dannyTorres** [comment]
Hi! I updated the version and everything looks good, thanks!!

**Comment by Danny908** [comment]
Hi! I updated the version and everything looks good, thanks!!
