### ISSUE TITLE
ngModel not working in AutoComplete

### ISSUE THREAD

**Issue by gulitskiy** [telerik/kendo-angular#1619]
https://embed.plnkr.co/XsuaBrqnezaqqkMeJgQ4/

when i set complex value to ngModel or value i get error 

`ERROR Error: Uncaught (in promise): Error: Expected value of type string. See http://www.telerik.com/kendo-angular-ui/components/dropdowns/autocomplete/#toc-value`

**Comment by valchev** [comment]
Hi @gulitskiy 

The AutoComplete components works only with value of type **string**. The error occurs, because the ngModel field contains **object**.

**Comment by vdiaz1130** [comment]
Is there a way to access a complex object from the AutoComplete component rather than receiving a string? I can run a filter on change but what if there are duplicate entries (e.g. a list of names)?

**Comment by valchev** [comment]
Hi @vdiaz1130 

The AutoComplete component is intended to work with string values. If you need to work with the selected dataItem I suggest to use a ComboBox.

The GitHub issue tracker is intended for bug reports, in case you need further assistance please submit a support ticket.
