### ISSUE TITLE
kendo-chat cannot display avatar image the url of which starts with "blob."

### ISSUE THREAD

**Issue by mesztam** [telerik/kendo-angular#1620]
## I'm submitting a
* Bug report 

## Current behavior
If an avatarUrl uses an url scheme like "blob.http://", then the avatar is not displayed, because angular prefixes it with an "unsafe:" prefix.

## Expected behavior
An unsafe: prefix sholdn't be used. 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/Rhj3L8RCq7JJPCI4198X?p=preview

Here, I use this object:
  public readonly bot: User = {
    id: 0,
    name: 'Bobby McBot',
    avatarUrl: 'blob.https://demos.telerik.com/kendo-ui/content/chat/avatar.png'
  };
(I know that the file does not exist anyway).

=> the image object is displayed, but its href attribute starts with unsafe:.

I think the problem is here: message-list.component.js:104
<img *ngIf="group.author.avatarUrl" src="{{ group.author.avatarUrl }}"
=> instead of {{}}, it should use binding like [src]="group.author.avatarUrl". Furthermore, avatarUrl should support Safe strings I think.

Thanks,
Tamas

**Comment by danielkaradachki** [comment]
We have update the src attribute binding in the latest dev version. Note that you still need to use the [DomSanitizer bypassSecurityTrustUrl](https://angular.io/guide/security#bypass-security-apis)  method to avoid the unsafe prefix:

https://plnkr.co/edit/4TzdPiHh5I8x1leV04eV?p=preview

**Comment by ipeshev** [comment]
Available in latest development version v0.2.2-dev.201806250958

**Comment by tsvetomir** [comment]
Shipped in v0.2.2
