### ISSUE TITLE
kendo-calendar not working when placed inside kendo-window

### ISSUE THREAD

**Issue by sirarthurnell** [telerik/kendo-angular#1621]
## I'm submitting a...
* Bug report

## Current behavior
Actually, if I place a kendo-calendar inside a kendo-window and I try to pick another month different from the current one, the month picker doesn't work. Apart from that, if I select other month and then, I select a different day, the calendar shows again the current month, like if the selected day were from the current month and not the month I specified earlier.

## Expected behavior
Month picker working as expected and keeping the selected month even if I choose other day.

## Minimal reproduction of the problem with instructions
Simply write this code anywhere and try to select a different month and a different day:

```html
<kendo-window>
  <kendo-calendar></kendo-calendar>
</kendo-window>
```

## Environment

Package versions:
```
+-- @angular-devkit/build-angular@0.6.8
+-- @angular/animations@6.0.5
+-- @angular/cli@6.0.8
+-- @angular/common@6.0.5
+-- @angular/compiler@6.0.5
+-- @angular/compiler-cli@6.0.5
+-- @angular/core@6.0.5
+-- @angular/forms@6.0.5
+-- @angular/http@6.0.5
+-- @angular/language-service@6.0.5
+-- @angular/platform-browser@6.0.5
+-- @angular/platform-browser-dynamic@6.0.5
+-- @angular/router@6.0.5
+-- @progress/kendo-angular-buttons@4.1.1
+-- @progress/kendo-angular-dateinputs@3.4.1
+-- @progress/kendo-angular-dialog@3.6.2
+-- @progress/kendo-angular-dropdowns@3.0.2
+-- @progress/kendo-angular-excel-export@2.1.0
+-- @progress/kendo-angular-grid@3.5.0
+-- @progress/kendo-angular-inputs@3.1.3
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-messages@1.12.0
+-- @progress/kendo-data-query@1.3.1
+-- @progress/kendo-drawing@1.5.6
+-- @progress/kendo-theme-bootstrap@2.13.6
+-- @types/jasmine@2.8.8
+-- @types/jasminewd2@2.0.3
+-- @types/node@8.9.5
+-- bootstrap@4.0.0
+-- codelyzer@4.2.1
+-- core-js@2.5.7
+-- font-awesome@4.7.0
+-- jquery@3.3.1
+-- ngx-toastr@8.8.0
+-- popper.js@1.14.3
+-- rxjs@6.2.1
+-- rxjs-compat@6.2.1
+-- ts-node@5.0.1
+-- tslint@5.9.1
+-- typescript@2.7.2
`-- zone.js@0.8.26
```

Browser:
- Chrome (desktop) version 67.0.3396.62

System:
- TypeScript version: 2.9.1
- Node version: 10.1.0
- NPM version: 4.0.2
- Platform:  Windows

**Comment by alexandr-prikhodko** [comment]
Got the same issue when trying add a kendo-calendar inside a kendo-dialogue.
Also want to add my reproduction instructions of this problem:
- Use dialog or window component and put calendar component inside as mentioned in current report.
- Try to use mouse-wheel to scroll months.

I've added plunker link for quick check of this issue: https://plnkr.co/edit/bc0lFdRIDkeRG3NWiAsl?p=preview
