### ISSUE TITLE
TextBox directive causes blur and focus events to fire twice

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1622]
[https://plnkr.co/edit/0vAPa7eHFL6VsDJGAKra?p=preview](https://plnkr.co/edit/0vAPa7eHFL6VsDJGAKra?p=preview)

Suggested workaround - debounce the event:

[https://plnkr.co/edit/xMGUKNj2u6Akbn3FQ3IR?p=preview](https://plnkr.co/edit/xMGUKNj2u6Akbn3FQ3IR?p=preview)

**Comment by Jidehem** [comment]
Duplicate of #1400

**Comment by Raisolution** [comment]
Closing as a duplicate.
