### ISSUE TITLE
How to handle the Sorting within page of grid!

### ISSUE THREAD

**Issue by snspvd** [telerik/kendo-angular#1624]
How to handle the sorting within page data only, not entire grid data.

https://next.plnkr.co/edit/nyRluCRJXjLBMuLa

**Comment by rkonstantinov** [comment]
Sorting only a portion of the data will not yield correct results. However, if this is the behavior you are looking for, you could use the `kendo-data-query` [orderBy function](https://www.telerik.com/kendo-angular-ui-develop/components/dataquery/#toc-sorting) to sort the already paged data.

Please note that this repository is for submitting issues with the components. For general inquiries regarding component usage, use the support ticketing system .
