### ISSUE TITLE
Window can be dragged off screen and made inaccessible

### ISSUE THREAD

**Issue by oc-mclaassen** [telerik/kendo-angular#1626]
## I'm submitting a...

* Bug report 

## Current behavior
Window can be dragged off the page (like off the top).  If dragged far enough so that the title bar is not visible, it is impossible to drag it back into view.  If there are control buttons (like in a dialog) at the bottom, the window can be closed.  However, if there are no control buttons the window cannot be  closed either.

## Expected behavior
Dragging the top of a window outside of the browser's view should not be prevented.

## Minimal reproduction of the problem with instructions

https://www.telerik.com/kendo-angular-ui/components/dialogs/window/
Drag the Kendo window out of the top of the example area until the title bar is no longer visible and then release the mouse.
Window can no longer be moved. 

## What is the motivation or use case for changing the behavior?
The toolkit should prevent a user from accidentally doing something that will put them in a situation that they cannot get out of, except by browser refresh

## Environment

Browser:

- Chrome (desktop) version (latest)
- Firefox (desktop)  version (latest)

System:
- Platform:  Windows 10

**Comment by Raisolution** [comment]
Hi @oc-mclaassen,

The current behavior is by design, currently the Window component does not provide boundary detection. As a workaround I would suggest to use two-way binding for the `top` and `left` Window properties and use the `dragEnd` event to check and modify them if needed. Here is [an example of this](https://plnkr.co/edit/3Y7DHmmwMhxnUelHQ5t7?p=preview).

**Comment by jmaronge** [comment]
@Raisolution Any suggestions on how to accomplish this when using the Angular service and have it work for all four corners of the window?

**Comment by Raisolution** [comment]
@jmaronge in the latest version `3.7.0` we are introducing the `setOffset` and `setDimension` API methods which could be used in scenarios like the current one for positioning and resizing dynamically created Window components.
