### ISSUE TITLE
Dialog appearance is broken in IE when no width is set and there are other components inside

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1627]
When neither the Dialog nor the components used inside have their width set, the Dialog appearance is broken in IE (inner components get indefinitely wide too):

[https://stackblitz.com/edit/angular-lv4ap1-egeof5?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-lv4ap1-egeof5?file=app%2Fapp.component.ts)

When either the Dialog or the inner component have a set width, everything is OK:

[https://stackblitz.com/edit/angular-lv4ap1-i7yaps?file=app/app.component.ts](https://stackblitz.com/edit/angular-lv4ap1-i7yaps?file=app/app.component.ts)

Observable in IE only.

**Comment by oscarrodar** [comment]
**Note:** IE, version 11.

**Comment by dtopalov** [comment]
The current implementation of the components from the Dialog package does not add a max-width CSS rule to the container element out-of-the-box by design.

As a workaround, you can add a custom style to provide this rule, e.g.:

    .k-widget.k-dialog {
        max-width: 100%;
      }
    `]

We will consider addressing this issue in a future version of the package where the respective style (or a similar one, accomplishing the same) will be added out-of-the-box.
