### ISSUE TITLE
When zoom is applied via CSS, the right-most DropDown Popup appears in a wrong position

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1628]
Grid filtering UI DropDown's Popup appears in a wrong position (the wider the viewport, the further to the left) if the Popup is in the right-most column near the right edge of the viewport:

[https://plnkr.co/edit/1F8GqToacPosoe2lbT1C?p=preview](https://plnkr.co/edit/1F8GqToacPosoe2lbT1C?p=preview)

Reported in a private support thread:  
Ticket ID: 1171197

**Comment by tsvetomir** [comment]
Related to https://github.com/telerik/kendo-angular/issues/777

**Comment by svetq** [comment]
The non-standard [zoom property](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) is not supported. Its behavior is not specified and varies between browsers. To check an alternative approach please see the following article:

https://www.telerik.com/kendo-angular-ui-develop/components/popup/document-scale/
