### ISSUE TITLE
[DropDownList] does not update its value when bound using a [formControl] input

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1629]
## I'm submitting a...

* Bug report 

## Current behavior

The DropDownList does not reset its value when bound using the [formControl] input:

[https://plnkr.co/edit/DZ5SVcRHr5udvtm1CGj4?p=preview](https://plnkr.co/edit/DZ5SVcRHr5udvtm1CGj4?p=preview)
 
## Expected behavior
The value of the DropDownList should reset accordingly as the value of the formControl.

## Minimal reproduction of the problem with instructions
[https://plnkr.co/edit/DZ5SVcRHr5udvtm1CGj4?p=preview](https://plnkr.co/edit/DZ5SVcRHr5udvtm1CGj4?p=preview)

**Comment by tsvetomir** [comment]
Fixed in the latest [development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Shipped in v3.0.3
