### ISSUE TITLE
translateAggregateResults() expects field names to be PascalCase

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1631]
The Data Query translateAggregateResults() function expects some of the server response fields to be capitalized and throws a JavaScript error otherwise:

```
export const translateAggregateResults = (data: any[]): AggregateResult => (
   (data || []).reduce((acc, x) => set(x.**Member**, acc, set(x.**AggregateMethodName**.toLowerCase(), acc[x.**Member**] || {}, x.**Value**)), {})
);
```
It would be nice to introduce an enhancement to handle both camel and pascal casing on the client.

**Comment by rkonstantinov** [comment]
This enhancement is available with version 1.4.0 of `kendo-data-query package`
