### ISSUE TITLE
Tooltip does not work with svg in ie11

### ISSUE THREAD

**Issue by jinhoyim** [telerik/kendo-angular#1632]
## I'm submitting a...
* Bug report 

## Current behavior
 * The Tooltip does not work with svg in ie 11.
 * Except, it work with svn in the button tag.

## Minimal reproduction of the problem with instructions
 * [https://plnkr.co/edit/qXsi4wsh4zlIbNjJWp5M?p=preview](https://plnkr.co/edit/qXsi4wsh4zlIbNjJWp5M?p=preview)

## Environment

Package versions:
 * progress/kendo-angular-tooltip: ^0.4.0

Browser:
- Chrome (desktop) version 67.x well works.
- IE version 11.112.17134 does not work.
- Edge version 47.x well works.

System:
- Platform:  Windows

**Comment by tsvetomir** [comment]
Fixed in the latest [development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
