### ISSUE TITLE
Possibility to export multiple Grids to the same PDF document

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1635]
It would be nice to provide a possibility for exporting multiple Grids to the same PDF document, a functionality similar to the following Kendo UI for jQuery demo:

[https://docs.telerik.com/kendo-ui/knowledge-base/export-multiple-grids-in-the-same-pdf-file](https://docs.telerik.com/kendo-ui/knowledge-base/export-multiple-grids-in-the-same-pdf-file)

**Comment by danielkaradachki** [comment]
Available in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:
https://www.telerik.com/kendo-angular-ui-develop/components/grid/export/pdf-export/#toc-exporting-multiple-grids-to-the-same-pdf

**Comment by danielkaradachki** [comment]
Released in 3.10.0

https://stackblitz.com/edit/angular-xuguah?file=app/page-template.css
