### ISSUE TITLE
KendoTextboxcontainer does not keep id

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1636]
## I'm submitting a...

* Bug report 

## Current behavior
KendoTextboxContainer does not keep id ( it may be valid for other attributes ) 

## Expected behavior
It should keep attributes.

## Minimal reproduction of the problem with instructions
1.Open following [demo](https://plnkr.co/edit/X0BASyf730JN5xFR0Vi1?p=preview)

## Environment

Package versions:

```
broken in v3.1.4-dev.201806221046
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by elena-gancheva** [comment]
The `id` of `KendoTextBoxContainer` component is not rendered and this is implementation design decision. Check the documentation page [here](https://www.telerik.com/kendo-angular-ui/components/inputs/api/TextBoxContainerComponent/#toc-id).

However, if `id` is needed to be rendered, the following [Plunker](https://next.plnkr.co/edit/dpQJ3sx3JLn82VMG625O?p=preview&preview) shows this scenario.
