### ISSUE TITLE
Provide an option for adding custom classes to the SplitButton inner buttons

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1639]
Currently there is no built-in way for providing custom classes/styling to the buttons, rendered by the SplitButton component (for example to mimic the primary button styling):

![image](https://user-images.githubusercontent.com/7533599/42090836-a2134f58-7bab-11e8-9ed3-a0f0069f5c07.png)

It would be nice to provide an option for adding custom class(es) to these buttons via the component's options.

**Comment by siyka-marinova** [comment]
The feature is available in `kendo-angular-buttons v5.1.0` and later.
