### ISSUE TITLE
Missing properties on CellClickEvent interface

### ISSUE THREAD

**Issue by revov** [telerik/kendo-angular#1640]
## I'm submitting a...
* Bug report
* Documentation issue or request

## Current behavior
The Grid's [context menu example](https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/context-menu/) in the docs refers to the [CellClickEvent](https://telerik.com/kendo-angular-ui/components/grid/api/CellClickEvent/)'s `dataItem` property. However, the `CellClickEvent` interface seems to be outdated and does not declare the following properties (that are actually present in the emitted object):
- dataItem
- isEditedColumn
- isEditedRow

Developers have to extend `interface CellClickEvent` in order to get proper compile-time checks and IDE autocompletion. Beforementioned grid context menu docs example does not make use of strongly-typed event handler parameter.

## Expected behavior
`interface CellClickEvent` should properly declare all properties of the actual object that is emitted from the `GridComponent`. Ideally, the context menu example in the docs can make use of a strongly-typed event handler parameter.

## Environment

Package versions:

```
@progress/kendo-angular-grid@3.5.0
```

**Comment by danielkaradachki** [comment]
The dataItem was added in the latest [dev](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/CellClickEvent/#toc-dataitem) version.
The isEditedColumn and isEditedRow fields are intended for internal use. You should use the [isEdited](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/CellClickEvent/#toc-isedited) field instead.

**Comment by danielkaradachki** [comment]
Fixed in 3.5.1
