### ISSUE TITLE
Kendo grid (odata binding) filter not clear the grid after remove all character

### ISSUE THREAD

**Issue by afsalcodehack** [telerik/kendo-angular#1641]
I set kendo grid using odata end point for server side searching if i search three char using contain filter it bring all match when i try to remove char from the filter box it will send request to server until second char but not after first char removed

for example if i am searching 123 it will bring all data contain 123 
-->12 (removed 3) // OK
-->1 (removed 2) // OK
--"" (removed 1) // not sending request to server result data remain same like previous result

i did try your plunker example odata implementation had the same issue

**Comment by rkonstantinov** [comment]
Most probably the behavior you have described is caused by not binding the Grid's filter to the state. You should make sure you have something similar to the following in your Grid's declaration:

```html
<kendo-grid
       [data]="view | async"
       ....
       [filter]="state?.filter" <-----
       [filterable]="true"
       (dataStateChange)="dataStateChange($event)"
     >
     ......
</kendo-grid>
```
