### ISSUE TITLE
Unexpected value 'InputsModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by josephjelaskar** [telerik/kendo-angular#1642]
I am facing the below given issue after upgrading to angular 6.0.2
Uncaught Error: Unexpected value 'InputsModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:215)
    at compiler.js:10468
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:10443)
    at JitCompiler._loadModules (compiler.js:22567)
    at JitCompiler._compileModuleAndComponents (compiler.js:22548)
    at JitCompiler.compileModuleAsync (compiler.js:22508)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:143)
    at PlatformRef.bootstrapModule (core.js:4790)
    at HTMLDocument.bootApplication (boot-client.ts:34)

my package.json looks like the below
dependencies": {
    "@angular/animations": "6.0.2",
    "@angular/cdk": "6.0.2",
    "@angular/common": "6.0.2",
    "@angular/compiler": "6.0.2",
    "@angular/core": "6.0.2",
    "@angular/forms": "6.0.2",
    "@angular/http": "6.0.2",
    "@angular/material": "6.0.2",
    "@angular/platform-browser": "6.0.2",
    "@angular/platform-browser-dynamic": "6.0.2",
    "@angular/platform-server": "^4.3.0",
    "@angular/router": "6.0.2",
    "@angular/upgrade": "6.0.2",
    "@compodoc/compodoc": "^1.1.3",
    "@progress/kendo-angular-buttons": "4.1.1",
    "@progress/kendo-angular-charts": "3.2.1",
    "@progress/kendo-angular-dateinputs": "3.4.2",
    "@progress/kendo-angular-dropdowns": "3.0.2",
    "@progress/kendo-angular-excel-export": "2.1.0",
    "@progress/kendo-angular-grid": "3.5.0",
    "@progress/kendo-angular-inputs": "3.1.3",
    "@progress/kendo-angular-intl": "1.4.1",
    "@progress/kendo-angular-l10n": "^1.2.0",
    "@progress/kendo-angular-popup": "2.4.1",
    "@progress/kendo-angular-scrollview": "^2.0.1",
    "@progress/kendo-angular-upload": "4.1.2",
    "@progress/kendo-data-query": "1.4.0",
    "@progress/kendo-drawing": "1.5.6",
    "@progress/kendo-file-saver": "^1.0.4",
    "@progress/kendo-theme-bootstrap": "^2.13.5",
    "@progress/kendo-theme-default": "2.54.0",
    "@reactivex/rxjs": "^5.4.1",
    "@telerik/kendo-intl": "^0.14.1",
    "@telerik/kendo-theme-bootstrap": "^0.10.0",
    "@telerik/kendo-theme-default": "^1.33.4",
"rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0"
}

I have also tried up with deleting node_modules=> npm cache clear --force => npm install
No more luck so far.
Please help me to resolve the issue.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a support ticket with more detailed information about the setup.
