### ISSUE TITLE
Dropdowns: Provide an opportunity for implementing custom data-binding and filtering directive

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1645]
Currently the filtering functionality does not work as expected when the component's "data" property is manipulated directly (not via binding the respective input):

[https://plnkr.co/edit/vU2DwbdE81lFKqlgOokj?p=preview](https://plnkr.co/edit/vU2DwbdE81lFKqlgOokj?p=preview)

We should consider adding an opportunity for developers to implement a custom binding/filtering directive where they should be able to access and set the data property directly.

**Comment by hidegh** [comment]
I have created a similar sample as in the original plunker, but this time:

1. i kept the original [data]="data" reference
2. created a copy of the original source
3. on filter I was **mutating the original data** property (no reason for ngOnChanges to be called, so the error is somewhere else, **seems as if data.length is somewhere stored locally which leads to this behaviour.**

here's the link: https://plnkr.co/edit/5n9pxPerBYpXymrz6g1M?p=preview

despite all those efforts the result is the same as in the original plunker.

also i'd like to point out that:
1. the errorous behaviour is not a steady one (sometimes I can't reproduce it on the 1-st 2 tries)
2. and by pressing arrow up multiple times (despite having just 1 item) I manage to get the "medium" item selected

**Comment by hidegh** [comment]
@dtopalov A quick fix to the 1. plunker seems to do a bypass, since de facto this is what is executed if the filter expression is changed (base on the samples in docs).

So I just alter data and execute ngOnChanges on the data property

      this.list.data = newItems
      this.list.ngOnChanges({"data": undefined});

**Comment by dimitar-pechev** [comment]
The internal state of dropdowns is reset in the `data` prop setter now, so direct manipulations with it (e.g. `dropdownlist.data = [/* ... */]`) will work as expected, i.e. the value, selection and focus will be set accordingly even if we change the `data` of the component directly.

Included in **v3.4.0** of the `@progress/kendo-angular-dropdowns` package.
