### ISSUE TITLE
ComboBox textfield multiple properties

### ISSUE THREAD

**Issue by adiii4** [telerik/kendo-angular#1646]
Imagine I have an array like the following binded to the combobox component:

``` typescript
public countries: Country[] = [
      {
         id: 1,
         name: 'Germany',
         continent: 'Europe'
      },
      {
         id: 2,
        name: 'China',
        continent: 'Asia'
      },
      {
         id: 3,
         name: 'South Africa',
         continent: 'Africa'
      }
];
```

What I want now is that when I have selected an item the textfield of the comobox should show the following:

**Germany - Europe**

_So basically I want to combine two properties (name & continent) of an object to display in the textfield of the combobox component._

I have not found an example which does this and according to the api of the component only a value of type string can be applied to the property textField.

**Comment by tsvetomir** [comment]
Note that this repository is for bug reports only. Please, open a support ticket for assistance with specific scenarios.
