### ISSUE TITLE
Add ability to add attributes to the buttons of a ToolBar

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1647]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
Currently, we cannot set attributes to the buttons of a ToolBar.

## Expected behavior

We have the option to set attributes to the buttons.

## What is the motivation or use case for changing the behavior?

Check the following sample plunker:
[https://next.plnkr.co/edit/s7q13dQej3f965qw](https://next.plnkr.co/edit/s7q13dQej3f965qw)

We should be able to set a specific class to one of the buttons, so that we can further target only this button with the [filter] input property of the kendoTooltip directive.

**Comment by svetq** [comment]
Requested also in 1342136.

**Comment by dtopalov** [comment]
Also requested in 1387370

**Comment by Raisolution** [comment]
The issue has been addressed in `v1.1.0` of the `kendo-angular-toolbar` package.
