### ISSUE TITLE
Can we separate the grid header while grouping, i need to achieve as per the image attached

### ISSUE THREAD

**Issue by ranjith88** [telerik/kendo-angular#1649]
## I'm submitting a...

* Documentation issue - It is not an issue but it is something new which i did not find in documentation

## Expected behavior

```

Browser:
<!-- Leave only the browsers that you tested the issue with. -->
Any browser: this is not browser specific issue/question.

This is the version of Kendo Grid for Angular which i am using

 "@progress/kendo-angular-grid": "2.0.2",
![2018-07-04_18-11-33](https://user-images.githubusercontent.com/38937339/42278180-8bd5f5f0-7fb7-11e8-8c37-e4d56d4326b4.jpg)


<!-- Add any additional information that might be relevant. -->

**Comment by danielkaradachki** [comment]
This repository is for bug reports only. Please, open a support ticket for assistance with specific scenarios.

**Comment by ranjith88** [comment]
Can you help me with the path for support ticket? Should i do it from Telerik site or github?

**Comment by danielkaradachki** [comment]
Tickets can be opened from the Telerik site:
https://www.telerik.com/account/support-tickets
