### ISSUE TITLE
Grid with Batch Editing

### ISSUE THREAD

**Issue by ultimatemm** [telerik/kendo-angular#165]
Hi,

I am looking for batch editing like kendo ui :) http://demos.telerik.com/kendo-ui/grid/editing
do you have any plan to come out with RC version?
Thanks

**Comment by rusev** [comment]
Currently there is only an example for [editing with external form](http://www.telerik.com/kendo-angular-ui/components/grid/editing/). Angular forms gives you very flexible way of building edit forms.

We are also working on "inline" editing mode for the Grid. You can check [this issue](https://github.com/telerik/kendo-angular2/issues/157) for more details.

"incell" editing is not in our immediate plans. However it shouldn't be hard to achieve similar behavior by using [CellTemplateDirective](http://www.telerik.com/kendo-angular-ui/components/grid/api/CellTemplateDirective/) with current version of the Grid component.

**Comment by HJoost** [comment]
For us incell editing is even more important than inline editing...

**Comment by tsvetomir** [comment]
May we rename this issue to in-cell editing then? Batch editing a bit misleading as we have no control over how the updates are posted.

**Comment by emmawi** [comment]
I am actually trying to achieve this using the kendoGridCellTemplate, the form is dataArray. As long as i only edit current rows its working (e.g updating the values of the form), but when i push another row to the form(dataArray), every other input on the other rows gets blank, however when i log the value of the dataArray the values are still there, but they are not shown in the input in the grid. 

```
 <kendo-grid
        [data]="dataArray"
        [sortable]="true"
        [selectable]="true"
        [sort]="sort" (sortChange)="sortChange($event)" (selectionChange)="selectChange($event)">

        <kendo-grid-column field="longtext" title="Text *">
          <template kendoGridCellTemplate let-dataItem let-rowIndex="rowIndex">
                <input [(ngModel)]="dataItem.longtext" name="longtext" #longtext="ngModel" >
          </template>
        </kendo-grid-column>
</kendo-grid>
```

**Comment by PeterStaev** [comment]
+1 for supporting in-cell editing

**Comment by tsvetomir** [comment]
Dedicated support for in-cell editing is on our roadmap for our autumn release. I'm closing this issue as we don't have a good workaround for the current version.

**Comment by codehippie1** [comment]
I was able to change kendo angular grid's custom editing functionality to achieve something in line with batch/cell editing. Please see this stackoverflow answer.

[](https://stackoverflow.com/questions/44267493/batch-editing-in-kendoui-grid-for-angular-2-4/44268194#44268194)

**Comment by TheoGit** [comment]
@codehippie1 great example, however I can't seem to get a handle for the grid - I noticed you used the "#grid" for that - it's not working for me - which version of the grid are you using in your example?

**Comment by TheoGit** [comment]
@codehippie1 actually I figured out the handle for the grid - closeRow is not working - any ideas?

**Comment by DotNetPart** [comment]
@tsvetomir Is in-cell editing still on the roadmap for the autumn release?

**Comment by tsvetomir** [comment]
@DotNetPart indeed, it's actually available in the [development builds](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), see [plunkr](http://plnkr.co/edit/um3bykjeXgwoBYgdSoE1?p=preview).

We'll need about a week for some last-minute adjustments and testing.

**Comment by DotNetPart** [comment]
@tsvetomir thanks! Looking forward to getting this.
