### ISSUE TITLE
Cannot reset the kendo-chat component

### ISSUE THREAD

**Issue by mesztam** [telerik/kendo-angular#1650]
## I'm submitting a...

* Bug report 

## Current behavior

Setting the messages property of kendo-chat component to an empty array does not clear the current chat history. Instead, if keeps the previous message items in the UI.

## Expected behavior
When setting the messages property to an empty array, the chat component should be reset.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/nbrErbYPtsdUYI9X06Tm?p=preview

At the 3rd message, it should reset to [] -> empty, but it does not. At the 4th message, it detects the change, and display it.

**Comment by tsvetomir** [comment]
Shipped in the official v1.0.0 release.
