### ISSUE TITLE
Multi-page column's contents disappears between the pages.

### ISSUE THREAD

**Issue by rcadhikari** [telerik/kendo-angular#1651]
## I'm submitting a...

* Bug report 

## Current behavior

1. When we export the table on Kendo Grid using PDF Export feature, if the column has long text that runs onto multiple page, all the contents get cropped out after the first page.

For example, please check the attachment at the bottom about how text is currently showing for the `Name` column value for row ID `1` .

## Expected behavior

In fact, the expected output on exported PDF would be should all the text below into multiple pages 
`
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. 222 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ` 

Page 2 should continue with the following text:
`It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
`

## Minimal reproduction of the problem with instructions

For bug reports, please provide the **STEPS TO REPRODUCE** and, if possible, a **MINIMAL DEMO** of the issue. You can use https://plnkr.co or share your project in a public repository.

  1. When we export the table on Kendo Grid using PDF Export, if the column has long text that can run on multiple page, all the contents get cropped out after the first page.
  2. For example, the 
  2. Open it in Plunker by using the link **[here](https://plnkr.co/edit/0pVIasQEfOLDXg23f4qq?p=preview)**.

## Environment

Package versions:

```
├── @angular/animations@5.2.10
├── @angular/cdk@5.2.0
├── @angular/cli@1.7.4
├── @angular/common@5.2.10
├── @angular/compiler@5.2.10
├── @angular/compiler-cli@5.2.10
├── @angular/core@5.2.10
├── @angular/forms@5.2.10
├── @angular/http@5.2.10
├── @angular/platform-browser@5.2.10
├── @angular/platform-browser-dynamic@5.2.10
├── @angular/platform-server@5.2.10
├── @angular/router@5.2.10
├── @ng-idle/core@2.0.0-beta.15
├── @ng-idle/keepalive@2.0.0-beta.15
├── @progress/kendo-angular-buttons@4.0.0
├── @progress/kendo-angular-dateinputs@3.0.0
├── @progress/kendo-angular-dropdowns@2.1.0
├── @progress/kendo-angular-excel-export@1.0.7
├── @progress/kendo-angular-grid@3.4.0
├── @progress/kendo-angular-inputs@2.2.0
├── @progress/kendo-angular-intl@1.4.0
├── @progress/kendo-angular-l10n@1.1.0
├── @progress/kendo-angular-pdf-export@1.1.1
├── @progress/kendo-angular-popup@2.2.0
├── @progress/kendo-data-query@1.3.0
├── @progress/kendo-drawing@1.5.3
├── @progress/kendo-theme-default@2.51.0
├── @progress/kendo-ui@2017.3.1116
├── @telerik/kendo-theme-default@1.33.4
├── @tinymce/tinymce-angular@1.0.8
├── @types/jasmine@2.5.38
├── @types/node@6.0.106
├── angular2-moment@1.8.0
├── animate.css@3.1.1
├── auth0-js@9.5.0
├── auth0-lock@11.6.0
├── bootstrap@3.3.7
├── chart.js@2.7.2
├── codelyzer@4.3.0
├── core-js@2.5.5
├── font-awesome@4.7.0
├── html2canvas@1.0.0-alpha.12
├── html2pdf.js@0.9.0
├── intl@1.2.5
├── jasmine-core@2.5.2
├── jasmine-spec-reporter@3.2.0
├── jquery@3.3.1
├── jquery-slimscroll@1.3.8
├── jquery-sparkline@2.4.0
├── jspdf@1.4.1
├── jvectormap-next@3.0.0
├── karma@1.4.1
├── karma-chrome-launcher@2.0.0
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@0.2.3
├── karma-jasmine@1.1.1
├── karma-jasmine-html-reporter@0.2.2
├── metismenu@2.7.7
├── mydatepicker@2.6.3
├── ng2-charts@1.6.0
├── ng2-file-upload@1.3.0
├── ngx-bootstrap@2.0.5
├── ngx-chips@1.8.2
├── ngx-editor@3.3.0
├── ngx-permissions@3.2.4
├── ngx-toastr@6.5.0
├── oidc-client@1.5.1
├── peity@3.3.0
├── protractor@5.3.1
├── rxjs@5.5.10
├── ts-node@2.0.0
├── tslint@5.9.1
├── typescript@2.6.2
├── weakmap-polyfill@2.0.0
├── web-animations-js@2.3.1
├── webpack@3.11.0
└── zone.js@0.8.26
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:  

![snip20180705_4](https://user-images.githubusercontent.com/988548/42331110-8c3500bc-806c-11e8-8c28-f337bacbd53a.png)

**Comment by danielkaradachki** [comment]
This is a limitation of the PDF export page breaking:
https://www.telerik.com/kendo-angular-ui/components/pdfexport/multi-page-content/#toc-known-limitations

Table rows cannot be split into multiple pages.

Depending on the size of the of the cell content it may be possible to fit the cell in a single page by increasing the column width or by using [scale](https://www.telerik.com/kendo-angular-ui/components/grid/api/PDFComponent/#toc-scale).
