### ISSUE TITLE
PanelBarItem ItemTitle Directive Button

### ISSUE THREAD

**Issue by TylerOrtiz** [telerik/kendo-angular#1652]
## I'm submitting a...

* Bug report 

## Current behavior

I added a button to the PanelBar Title and noticed that the button's click event is bubbling through to the PanelBar. I've tried preventing the default action in the click event handler for the button but it does not help.

## Expected behavior

I expect to be able to add a button the the PanelBar title and take control of the events on the button without toggling the PanelBar over and over.

## Minimal reproduction of the problem with instructions

Plunker: https://next.plnkr.co/plunk/9boj7nfrCJDk673V 

1. Click on the button "Click Me" in the first PanelBar's title
2. Notice the PanelBar toggles continously each time the button is clicked.

## Environment
Package versions:
N/A

Browser:

- Chrome (desktop) version Version 67.0.3396.99 (Official Build) (64-bit)

System:
- Node version: Node v8.11.3 npm v5.6.0
- Platform:  Windows

This has to do with the use of the `kendoPanelBarItemTitle` for the `<kendo-panelbar-item>` template

**Comment by danielkaradachki** [comment]
You should stop the event propagation to prevent the panelbar from handling the event:
https://plnkr.co/edit/sYfKNN8NNsevbz9ZPLNy?p=preview

We will consider ignoring clicks on buttons and other focusable elements by default

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0

https://stackblitz.com/edit/angular-iqzjd2?file=app/app.component.ts
