### ISSUE TITLE
In Sortable - the draggable directive does not work on templated elements in Firefox

### ISSUE THREAD

**Issue by Mygi** [telerik/kendo-angular#1653]
## I'm submitting a...

* Bug report/Documentation issue

## Current behavior
In the documentation, there is a description and plunker for using the "draggable" directive on specific elements in the sortable template.https://www.telerik.com/kendo-angular-ui/components/sortable/#toc-known-limitations. Yet when you run the sample code you can not drag the buttons in Firefox. They just click like normal buttons. This does however work on Chrome 67.0.3396.99.

Code used is described in the documentation as follows (the issue is with using `<button draggable="true">`):

`import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <kendo-sortable [data]="items">
      <ng-template let-item="item">
        <button draggable="true">
          {{item}}
        </button>
      </ng-template>
    </kendo-sortable>
  `
})
export class AppComponent {
  public items: string[] = [
    'Item 1', 'Item 2', 'Item 3', 'Item 4'
  ];
}`

## Expected behavior
You expect to be able to drag and drop the buttons and reorder them. 

## Minimal reproduction of the problem with instructions
Open the Plunker or Sandbox at https://www.telerik.com/kendo-angular-ui/components/sortable/#toc-known-limitations and attempt to drag'n'drop in Firefox.

## Environment
OsX 10.13.4

Package versions:
From Online documentation

Browser:

- Firefox version 60.0.2

System:
- From Online Documentation

**Comment by tapopov** [comment]
This appears to be an almost a decade old [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=568313). As such, there's not much we could suggest, other than replacing buttons with similarly styled divs or spans.
