### ISSUE TITLE
Grid filterChange event doesn't provide which filter was cleared

### ISSUE THREAD

**Issue by Pradhyo** [telerik/kendo-angular#1655]
## I'm submitting a...

* Bug report 

## Current behavior

The [filterChange](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-filterchange) event doesn't provide information about the filter when a filter is cleared.

## Expected behavior

The event should provide which filter was just cleared.

## Minimal reproduction of the problem with instructions

Check console.log output on line 52.. Entering a value in the "Product Name" filter produces information about the value and filter used but clearing it doesn't provide information that "ProductName" filter was cleared.
https://plnkr.co/edit/joBcwIiTy0XrCpmr4Tqa?p=preview

![image](https://user-images.githubusercontent.com/7895492/42480666-94037772-83ac-11e8-877d-2f92bfd41c7f.png)

## Environment

Browser:

- Chrome (desktop) version 67

System:
- Platform:  Windows

**Comment by rkonstantinov** [comment]
Hi @Pradhyo, the descriptor provided in filter change event represents the current state of the Grid component. It is intentional that it does not give explicitly information about what has been changed between state changes. If you need such information you should manually compare the current and previous state of the descriptor.

**Comment by Pradhyo** [comment]
Ah got it, thanks for getting back.
In my actual code, I forgot this line.

```html
<kendo-grid
        ....
        [filter]="filter"
        ....
>
```
Without this, the event only had information for the filter that just changed but not all of them. This is why I was using this information to track all the filters myself which I don't need to do anymore.
