### ISSUE TITLE
Rollup Issues

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#1656]
## I'm submitting a...
* Suggestion / Bug

## Current behavior
I'm trying to optimize my code. So I changed like recommended an Angular Compiler options: 
From  "annotationsAs": "decorators" to the Default Settings "static fields". Since then rollup throws errors. The problem is with exported interfaces like "FileRestrictions" in `@progress/kendo-angular-upload` or "DateFormatOptions" in `@progress/kendo-angular-intl`. Those files are after compilation empty and rollup can't handle them correctly.
I'm aware it's more an Typescript compilation or rollup issue (see for ex. https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897), but when those interfaces would exported as classes, the problem would also go away.

## Expected behavior
rollup is able to do treeshaking correctly .

If there is any other solution, would happy to hear it.
Thank you

**Comment by tsvetomir** [comment]
Replacing interfaces with classes seems like an overkill. It will result in larger bundles, as they must be retained in the final output.

Do you have a sample project that reproduces the error? I'd try turning on [allowEmptyCodegenFiles
](https://angular.io/guide/aot-compiler#allowemptycodegenfiles) to see if it helps.

**Comment by EricSch** [comment]
I'm trying to prepare something. Give me some time. Thanks

**Comment by tsvetomir** [comment]
I'll close this issue as we don't plan immediate actions.
Feel free to reopen if more information becomes available.
