### ISSUE TITLE
Set the cursor in the beginning of masked inputs

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1663]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When clicking in a masked input the cursor stays at the position of the click

## Expected behavior

When clicking in a masked input the cursor should go the the beginning of the input as demonstrated in the following example:
[https://codepen.io/anon/pen/MBajgp](https://codepen.io/anon/pen/MBajgp)

**Comment by danielkaradachki** [comment]
Implemented for the maskedtextbox in 3.5.0:
https://stackblitz.com/edit/angular-dhlf1x?file=app/app.component.ts

At least for now this is not planned for the dateinput. Please open a feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui/1364454-a-built-in-option-for-setting-both-default-operators-in-a-grid-filter-menu) so we can track its interest.
