### ISSUE TITLE
Error is thrown if the gauges are removed and there is a Intl change

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#1665]
Example: https://plnkr.co/edit/Ow1Pk1ojmnkBCp4ksc3R?p=preview
To reproduce: uncheck the show checkbox and click the change locale button

**Comment by ipeshev** [comment]
Available in [latest development](https://github.com/telerik/kendo-angular-gauges/releases/tag/v2.3.1-dev.201807160717) version

**Comment by danielkaradachki** [comment]
Published in 2.3.1
