### ISSUE TITLE
Kendo grid behaves abnormally when removing groups

### ISSUE THREAD

**Issue by jmsaunders001** [telerik/kendo-angular#1666]
## I'm submitting a...

* Bug report 

## Current behavior
When grouping and animations are enabled while viewing via Internet Explorer, the grid detail rows shrink horizontally and are out of alignment with Grid Headers. 
Steps:
1) Open the Plunker  https://plnkr.co/edit/RGMsu3?p=preview
2) Drag a column to grouping area (I used _Name_)
3) Remove the column group (_Name_ in my case)

Observe that the grid detail rows squish to the left, and are now out of alignment with headers. 

## Expected behavior
Grid rows don't squish.

## Minimal reproduction of the problem with instructions

This is the plunker for the issue. https://plnkr.co/edit/RGMsu3?p=preview

This is the same code from the kendo ui site with some additions. 

You will see that I have imported animations and added them to the component. This is all that is needed to re-create the issue. There is another other way to replicate it, however, it involved a hidden div that I didn't feel like creating in plunker. I can show you that if needed.  

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 67.0.3396.79 (Official Build) (64-bit) - works
- IE version 11 - broken
- Edge version 38.14393.2068.0 - works with animation, does not with hidden div

System:
- TypeScript version: 2.7.2
- Node version: 8.9.4 / 6.0.0
- Platform:  Windows

![image](https://user-images.githubusercontent.com/41197666/42704260-2fc902ce-869d-11e8-8c2a-1fdbcff173a4.png)

![image](https://user-images.githubusercontent.com/41197666/42704065-7ec86ab4-869c-11e8-91fb-a910ed5001b8.png)

**Comment by jmsaunders001** [comment]
You may have to pop the preview window out in Plunker too fully see it 
![image](https://user-images.githubusercontent.com/41197666/42704494-ff9991bc-869d-11e8-864f-1bc1acbe79fb.png)

**Comment by elena-gancheva** [comment]
The issue is no longer reproducible on Chrome and Edge latest versions, supported by the Angular framework https://angular.io/guide/browser-support.

The problem is presented in IE 11.
