### ISSUE TITLE
@progress kendo-angular-grid  Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by paulsperanza** [telerik/kendo-angular#1667]
## I'm submitting a bug report
 I am upgrading from Angular 5 to Angular 6. Followed all steps from Angular upgrade guide. Cleaned out node_modules. 

  <kendo-grid 
              filterable="menu"
              [height]="400"
              [data]="gridView"
              [pageable]="true"
              (pageChange)="pageChange($event)"
              [pageSize]="pageSize"
              [reorderable]="true"
              [resizable]="true"
              (selectionChange)="handleNameSelected(name, $event)"
              [selectable]="{
                checkboxOnly: false,
                mode: 'single'
              }"
              [skip]="skip"
              [sortable]="{
                allowUnsort: true,
                mode: 'multiple'
              }"
              style="width: 500px">

    <ng-template kendoGridToolbarTemplate>
      <button type="button" kendoGridExcelCommand><span class="k-icon k-i-file-excel"></span>Export to Excel</button>
      <button kendoGridPDFCommand><span class='k-icon k-i-file-pdf'></span>Export to PDF</button>
    </ng-template>

Produces the following error in the Chrome developer window

    <ng-container *ngFor="let column of gridInfo.columns">
      <kendo-grid-column [field]="column.name"
                         [title]="column.label"
                         [hidden]="!column.isVisible"
                         [width]="getColumnWidth(column)"></kendo-grid-column>
    </ng-container>
    <ng-template kendoPagerTemplate let-totalPages="totalPages" let-currentPage="currentPage">
      <kendo-pager-prev-buttons></kendo-pager-prev-buttons>
      <kendo-pager-info></kendo-pager-info>
      <kendo-pager-next-buttons></kendo-pager-next-buttons>
      
    </ng-template>
    <kendo-grid-pdf fileName="Products.pdf" [allPages]="true" paperSize="A4" [repeatHeaders]="true" [landscape]="true">
      <kendo-grid-pdf-margin top="2cm" left="1cm" right="1cm" bottom="2cm"></kendo-grid-pdf-margin>
      <ng-template kendoGridPDFTemplate let-pageNum="pageNum" let-totalPages="totalPages">
        <div class="page-template">
          <div class="header">
            <div style="float: right">Page {{ pageNum }} of {{ totalPages }}</div>
            Multi-page grid with automatic page breaking
          </div>
          <div class="footer">
            Page {{ pageNum }} of {{ totalPages }}
          </div>
        </div>
      </ng-template>
    </kendo-grid-pdf>
    <kendo-grid-excel fileName="Products.xlsx"></kendo-grid-excel>
  </kendo-grid>

Error from dev console in Chrome

ERROR TypeError: Cannot read property 'subscribe' of undefined
    at new GridComponent (grid.component.js:330)
    at createClass (core.js:9096)
    at createDirectiveInstance (core.js:8971)
    at createViewNodes (core.js:10191)
    at createEmbeddedView (core.js:10099)
    at callWithDebugContext (core.js:11136)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (core.js:10637)
    at TemplateRef_.push../node_modules/@angular/core/fesm5/core.js.TemplateRef_.createEmbeddedView (core.js:8686)
    at ViewContainerRef_.push../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createEmbeddedView (core.js:8552)
    at NgIf.push../node_modules/@angular/common/fesm5/common.js.NgIf._updateView (common.js:3343)

## Environment

Package versions:
{
  "name": "MpWebAngCli",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:ssr": "npm run build -- --app=ssr --output-hashing=media",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.0.9",
    "@angular/common": "6.0.9",
    "@angular/compiler": "6.0.9",
    "@angular/core": "6.0.9",
    "@angular/forms": "6.0.9",
    "@angular/http": "6.0.9",
    "@angular/platform-browser": "6.0.9",
    "@angular/platform-browser-dynamic": "6.0.9",
    "@angular/platform-server": "6.0.9",
    "@angular/router": "6.0.9",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "@ngx-loading-bar/http-client": "^1.1.0",
    "@progress/kendo-angular-buttons": "^4.1.2",
    "@progress/kendo-angular-dateinputs": "^3.4.3",
    "@progress/kendo-angular-dialog": "^3.1.2",
    "@progress/kendo-angular-dropdowns": "^3.0.2",
    "@progress/kendo-angular-excel-export": "^2.1.1",
    "@progress/kendo-angular-grid": "^3.5.1",
    "@progress/kendo-angular-inputs": "^3.2.0",
    "@progress/kendo-angular-intl": "^1.3.0",
    "@progress/kendo-angular-l10n": "^1.0.5",
    "@progress/kendo-data-query": "^1.1.2",
    "@progress/kendo-drawing": "^1.4.2",
    "@progress/kendo-theme-bootstrap": "^2.11.5",
    "@progress/kendo-theme-default": "^2.47.2",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "3.2.1",
    "ng-sidebar": "^6.0.5",
    "ng2-simple-timer": "^1.3.3",
    "ngx-toastr": "^8.8.0",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "6.0.9",
    "@angular/language-service": "6.0.9",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.3.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "2.7.2"
  }
}
```

```

Browser:

- Chrome (desktop) Version 67.0.3396.99 (Official Build) (64-bit)

System:
- TypeScript version: 2.8.4
- Node version: XX  8.11.2  
- NPM version: 6.1.0
- Platform:  Windows  10 Pro Version 1709 Build 16299.492

Visual Studio 2017 15.7.5

**Comment by danielkaradachki** [comment]
The package.json seem correct. Please verify that you have the correct package versions installed:
- run `npm cache clean`
- try removing both node_modules and package-lock.json and run "npm install" again.

If the problem persists, please provide a runnable sample that demonstrates the problem.

**Comment by paulsperanza** [comment]
That worked. Did both at the same time. 

Thank you,
Paul
