### ISSUE TITLE
Enhancement: Allow different content in Grid top and bottom toolbars

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1669]
Currently the Grid renders only a single toolbar template either on top, bottom or both sides of the Grid. 

It would be a nice enhancement to allow the developer to specify different content of the top and bottom toolbars depending on the position.

**Comment by tsvetomir** [comment]
The Grid can provide a context variable to the toolbar template that indicates if the template is rendered at the top or at the bottom.

**Comment by tsvetomir** [comment]
Version 3.7.0 adds a `position` variable to the [toolbar template](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/ToolbarTemplateDirective/) context, [see demo](https://stackblitz.com/edit/angular-aehiys?file=app/app.component.ts).
