### ISSUE TITLE
Stock Chart show wrong data in the info box for the candlestick

### ISSUE THREAD

**Issue by fayhand** [telerik/kendo-angular#1670]
## I'm submitting a...
* Bug report 

## Current behavior
I go to https://demos.telerik.com/kendo-ui/financial/index
Scroll down and click the "Edit this example" button
Here I run the example with developer tools open, so I can see the boing-stock.json file
I zoom in and select the date interval 1-jan 2000 to 1-feb 2000.
I can now see candlesticks for 3-jan, 5-jan, 7-jan and so on.

Mouseover/clicking a candlestick while show an info box with OCHL values.
I looks like each box covers data from 2 days. The day in the title of the info box plus the day after.
For example the info box says 3-jan. The data is for 3-jan and 4-jan.

But the info box for 5-jan shows something strange. 
It shows Open, Close, High, Low values all from the 6-jan.

## Expected behavior
In this example I would expect the the Open value to be from 5-jan.

And actually, I would expect these boxes to show values from days before and up to including the date in the title. So the 5-jan box I would expect to show values from 4-jan to 5-jan, not 5-jan to 6-jan. Maybe I am wrong here. 

## Environment
Browser:
- Chrome (desktop) version 67.0.3396.99
System:
- Platform:  Windows

**Comment by danielkaradachki** [comment]
The repository is for [Kendo UI for Angular](https://www.telerik.com/kendo-angular-ui/) issues. Are you using [Kendo UI for jQuery](https://demos.telerik.com/kendo-ui/)? If yes, then please open an issue in the [kendo-ui-core](https://github.com/telerik/kendo-ui-core) repo or open a [support ticket](https://www.telerik.com/account/support-tickets).

**Comment by fayhand** [comment]
I have created the issue on kendo-ui-core now. You can remove this.
