### ISSUE TITLE
Combobox fail if build is AOT

### ISSUE THREAD

**Issue by TheSegfault** [telerik/kendo-angular#1672]
Hi guys,

If I click the small arrow in my Combobox
![image](https://user-images.githubusercontent.com/5268918/42761260-4c99e2ac-890d-11e8-99d5-2eb860e3663d.png)

I got this error message if the build is AOT

![image](https://user-images.githubusercontent.com/5268918/42761249-45340d9e-890d-11e8-998e-3b6228f0e53e.png)

I tried to import and add PopupComponent to my AppModule but nothing change.

```
import { PopupComponent, PopupModule } from '@progress/kendo-angular-popup';

    entryComponents: [
        PopupComponent,
    ],
```

Chrome inspector: 
![image](https://user-images.githubusercontent.com/5268918/42761663-7fa6b8a4-890e-11e8-92d1-b2327881ff8d.png)

**Comment by tapopov** [comment]
Hi @TheSegfault 

We weren't able to reproduce this. Would you mind sharing more details about the environment in which it happens? You could do so by following the guide from our GitHub issue template:
```
## Environment

Package versions:
<!--
  Paste the output from "npm ls --depth 0" in the code block below.
  Omit this step if the problem is reproducible on our demo site.
-->
```

```

Browser:
<!-- Leave only the browsers that you tested the issue with. -->
- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX <!-- run tsc --version -->
- Node version: XX  <!-- run "node --version" and "npm --version"-->
- Platform:  <!-- Mac, Linux, Windows -->

```

**Comment by tapopov** [comment]
I've noticed that the dropdowns package is version 2.0.2, which isn't the latest one. Would you try removing all npm packages, then updating as explained [here](https://www.telerik.com/kendo-angular-ui/components/installation/angular-6/#toc-updating-the-component-packages)? It's not necessary to update to Angular 6 and RxJS 6.

**Comment by TheSegfault** [comment]
I edited my answer yesterday to explain that I tried it already 

"I also tried to install the latetest version for kendo dropdown, didnt change anything"

**Comment by TheSegfault** [comment]
It works ! As simple as that :) thanks ! I'll test a little bit further but It seems to work
