### ISSUE TITLE
Scrolling bug causes multi select drop down to close (Ionic 2)

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [telerik/kendo-angular#1676]
HI Telerik Team,

I'm using the multi-select dropdown in my Ionic Application. All the features that used in the app is working perfectly fine except one which is  [Preventing Closing Option List](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/open-state/#toc-preventing-opening-and-closing). **It is working on Android Device but not working on IOS Device**. The Option list is getting closed if I scroll the options.

Please help guys. Thanks in Advance.

**Comment by Jahrenski** [comment]
I have the same problem. This is iOS only and using Angular 7 with Ionic 4 in my case.
The same code works fine with Angular 5 and Ionic 3.

**Comment by ipeshev** [comment]
We tested on our side with and without Ionic and it seems like Ionic causes it, it is not related to KendoAngular components, probably all "popup" components are affected.
@Jahrenski thank you for the workaround it is good to know !

**Comment by Jahrenski** [comment]
Popups and dialogs too. If you have an input inside a dialog and click it the keyboard opens. If you scroll the dialog, the keyboard closes.

**Comment by ipeshev** [comment]
@Jahrenski we are reproducing it only with iPad 2 with newer devices it works fine , what version is your device ?
