### ISSUE TITLE
Tooltip always shown after click

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#1677]
## I'm submitting a...

* Bug report 

## Current behavior

In the Plunker demo move the mouse over the 'Hide Button' button, the tooltip is shown.
Now click on the button and DON'T move the mouse, the button disappears but the tooltip is always shown on the top of the page.

The same happens when a link button has an tooltip, and the button is no longer displayed after the routing to an other component.

## Expected behavior

The tooltip should no longer be displayed after the click.

## Minimal reproduction of the problem with instructions
Plunkter: https://next.plnkr.co/edit/WUU6eNq7zb1b07l5?preview

## Environment

Package versions:

```
+-- @angular-devkit/build-angular@0.6.3
+-- @angular/animations@6.0.3
+-- @angular/cli@6.0.3
+-- @angular/common@6.0.3
+-- @angular/compiler@6.0.3
+-- @angular/compiler-cli@6.0.3
+-- @angular/core@6.0.3
+-- @angular/forms@6.0.3
+-- @angular/http@6.0.3
+-- @angular/platform-browser@6.0.3
+-- @angular/platform-browser-dynamic@6.0.3
+-- @angular/router@6.0.3
+-- @fortawesome/fontawesome-free@5.1.0
+-- @ngx-translate/core@10.0.2
+-- @ngx-translate/http-loader@3.0.1
+-- @progress/kendo-angular-buttons@4.1.1
+-- @progress/kendo-angular-dateinputs@3.4.2
+-- @progress/kendo-angular-dropdowns@3.0.2
+-- @progress/kendo-angular-excel-export@2.1.1
+-- @progress/kendo-angular-grid@3.5.1
+-- @progress/kendo-angular-inputs@3.1.2
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-layout@3.1.1
+-- @progress/kendo-angular-tooltip@0.4.0
+-- @progress/kendo-angular-treeview@2.2.0
+-- @progress/kendo-data-query@1.4.0
+-- @progress/kendo-drawing@1.5.6
+-- @progress/kendo-theme-default@2.54.0
+-- @types/node@10.1.2
+-- bootstrap@4.1.1
+-- codelyzer@4.3.0
+-- core-js@2.5.6
+-- jquery@3.3.1
+-- ng2-signalr@6.0.0
+-- node-sass@4.9.0
+-- rxjs@6.2.0
+-- rxjs-compat@6.1.0
+-- rxjs-tslint@0.1.4
+-- sass-lint@1.12.1
+-- signalr@2.2.3
+-- tslint@5.10.0
+-- typescript@2.7.2
+-- web-animations-js@2.3.1
`-- zone.js@0.8.26
```

Browser:

- Chrome (desktop) version 67.0.3396.99
- IE version 11
- Edge version 42.17134.1.0

System:
- TypeScript version: 2.7.2
- Node version: v10.0.0, npm: 6.1.0
- Platform:  Windows

**Comment by elena-gancheva** [comment]
Hello @andrpelz,

Thanks for reporting this. 
We provided a fix in latest **dev** version of the package - `v1.0.0-dev.201807241049`.

**Comment by ipeshev** [comment]
@elena-gancheva  this is good candidate for test , as far as I understand it is the case when tooltip is shown and then element to whom it is attached is removed from the DOM.
