### ISSUE TITLE
NumericTextBoxComponent min attribute does not work

### ISSUE THREAD

**Issue by TylerOrtiz** [telerik/kendo-angular#1679]
## I'm submitting a...
* Bug report

## Current behavior

`NumericTextBoxComponent` min attribute is not working as expected.
It does prevent the user from using the arrow keys (keyboard or spinners) from going below the min value; however it does not do the same to typed input.
## Expected behavior
I expect the min value to be respected such that if a user types in a "-" symbol out front the component value will not get updated with the "-" value.

## Minimal reproduction of the problem with instructions
Example Plunkr:
https://next.plnkr.co/edit/bZOgmekd96WFAvlJ

1. Open Plunkr, view console
2. Click arrow buttons to change value
3. Note positive value is logged
4. Type a - character in the input field before the number, making it negative.
5. Note negative value is logged

## Environment

Package versions:
N/A

Browser:

- Chrome (desktop) version Version 67.0.3396.99 (Official Build) (64-bit)

System:
- Node version: 8.11.3 Npm version: 5.6.0 
- Platform:  Windows

**Comment by danielkaradachki** [comment]
Please check the numerictextbox [documentation](https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/precision/#toc-value-ranges).

**Comment by TylerOrtiz** [comment]
That makes sense now and works perfectly. Thank you and sorry for missing that.

For reference, this is how it worked for me:
` <kendo-numerictextbox
[(value)]="model.property"
[min]="0"
[autoCorrect]="true">
</kendo-numerictextbox>
`
