### ISSUE TITLE
Not all data in grid is accessible with keyboard

### ISSUE THREAD

**Issue by CalvinConnell** [telerik/kendo-angular#1681]
## I'm submitting a...
Bug

* Bug report 

## Current behavior
  Cannot `scroll` or `page` through grid with keyboard alone

## Expected behavior
`tab` or `arrow keys` scrolls or pages

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/OA2TRxBqpDWiZvyu8Rku?p=preview
https://plnkr.co/edit/Vc5Hfo9EJcDAo38DLKVz?p=preview

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 67.0.3396.99

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by danielkaradachki** [comment]
The keyboard navigation should be enabled in order to be able to change the page with the keyboard. Please refer to the keyboard navigation documentation for more detailed information:
https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/
