### ISSUE TITLE
[DropDownList] - ValueChange event firing without change when used with defaultItem

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#1684]
# I'm submitting a Bug report

## Current behavior
When using the `valueChange` in a DropDownList with `defaultItem` set, the valueChange event gets fired the first time even when no other item is selected

## Expected behavior
The event should only fire when the value is actually changed

## Minimal reproduction of the problem with instructions
[https://next.plnkr.co/edit/GXxifGXtx578CrWO](https://next.plnkr.co/edit/GXxifGXtx578CrWO)
- Open the dropdown 
- Click outside the dropdown without selecting any other item
- The valueChange event is triggered
![valuechange](https://user-images.githubusercontent.com/12758783/43036449-febec9ee-8d21-11e8-90fe-5180c5a5d522.gif)

**Comment by valchev** [comment]
Also requested in ticket 1410217

**Comment by svetq** [comment]
Closing this as it is no longer reproducible: https://stackblitz.com/edit/angular-5k6zkd?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fevent-log.component.ts,src%2Fapp%2Fapp.module.ts
