### ISSUE TITLE
Dialog close on escape key press not working inside the TabStrip in Internet Explorer

### ISSUE THREAD

**Issue by ShreeSanjeet** [telerik/kendo-angular#1691]
## Close on escape key press doesn't work in Internet Explorer when Dialog is being used inside a TabStrip

* Bug report 

## Current behavior

  * When Dialog is being used inside a TabStrip, Dialog is not closing on Escape key press in Internet Explorer.
  * I am using "@progress/kendo-angular-dialog": "3.6.2" for dialog and "@progress/kendo-angular-layout": "3.1.1" for TabStrip
 * Its happening on Internet Explorer - 11.0.7
 * However its working fine on Chrome.

## Expected behavior
Dialog should get close when Escape key is being pressed even if being used in TabStrip in Internet Explorer. 

## Minimal reproduction of the problem with instructions
 **STEPS TO REPRODUCE**

  1. [Plunkr example](https://plnkr.co/edit/baEi8DKKFnBebfW4g7Kq?p=preview)
  2. Open the above plnkr project in Internet Explorer
  3. Open the dialog using open dialog button
  4. Press the Escape button to close the dialog
  5. It doesn't close
  

## Environment

Package versions:
+-- @angular-devkit/build-angular@0.6.8
+-- @angular-devkit/core@0.6.8
+-- @angular/animations@6.0.4
+-- @angular/cli@6.0.8
+-- @angular/common@6.0.4
+-- UNMET PEER DEPENDENCY @angular/compiler@6.0.4
+-- @angular/compiler-cli@6.0.4
+-- UNMET PEER DEPENDENCY @angular/core@6.0.4
+-- @angular/forms@6.0.4
+-- @angular/http@6.0.4
+-- @angular/language-service@6.0.4
+-- @angular/platform-browser@6.0.4
+-- @angular/platform-browser-dynamic@6.0.4
+-- @angular/router@6.0.4
+-- @progress/kendo-angular-buttons@4.1.1
+-- @progress/kendo-angular-dateinputs@3.4.1
+-- @progress/kendo-angular-dialog@3.6.2
+-- @progress/kendo-angular-dropdowns@3.0.1
+-- @progress/kendo-angular-excel-export@2.1.0
+-- @progress/kendo-angular-grid@3.5.0
+-- @progress/kendo-angular-inputs@3.1.3
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-layout@3.1.1
+-- @progress/kendo-angular-ripple@1.0.1
+-- @progress/kendo-angular-sortable@1.1.1
+-- @progress/kendo-angular-upload@4.1.4
+-- @progress/kendo-data-query@1.3.1
+-- @progress/kendo-drawing@1.5.6
+-- @progress/kendo-theme-material@1.1.2
+-- @syncfusion/ej2-ng-popups@16.2.41
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.112
+-- auth0-js@9.6.1
+-- bootstrap@4.1.1
+-- classlist.js@1.1.20150312
+-- codelyzer@3.2.2
+-- core-js@2.5.7
+-- font-awesome@4.7.0
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- UNMET PEER DEPENDENCY jquery@1.9.1 - 3
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.4.3
+-- karma-jasmine@1.1.2
+-- karma-jasmine-html-reporter@0.2.2
+-- ng-packagr@1.7.0
+-- UNMET PEER DEPENDENCY popper.js@^1.14.3
+-- protractor@5.3.2
+-- rxjs@6.2.0
+-- rxjs-compat@6.2.1
+-- sass-loader@7.0.3
+-- scss-bundle@2.3.2
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.7.2
+-- web-animations-js@2.3.1
`-- zone.js@0.8.26

Browser:
- IE version 11.0.7

System:
- TypeScript version: 2.7.2
- Node version: 10.7.0
- Platform: Windows - 10

**Comment by Raisolution** [comment]
Hello,

Our recommendation in the described scenario would be to avoid nesting the Dialog component inside the TabStrip, but initialize it outside (best case would be on top level).
