### ISSUE TITLE
Custom Page Size Gets Removed Once Changing To Different Number In Dropdown

### ISSUE THREAD

**Issue by tpronschinske** [telerik/kendo-angular#1692]
## Current behavior

Setting custom page size on grid breaks when changing drop down. Once you open the paging drop down and change it to 5, 10, or 20 the 50 will disappear from the drop down.

## Expected behavior

I would expect that once you set a custom page size it should remain in the drop down at the bottom of the grid. It also should appear after the 20. If you default only show 5, 10, & 20 most common scenario suggest that someone is going to want to display a larger quantity of data. So the custom page size should appear after the 20 in the drop down and it should stay in the list. Being able to customize this list would be a great option.

## Minimal reproduction of the problem with instructions

If you visit the following link below. Change the page size from 5 to 50 and the records will display 50. Once you open the paging drop down and change it to 5, 10, or 20 the 50 will disappear from the drop down.

https://plnkr.co/edit/?p=preview

Browser:

- Chrome (desktop) Latest
- Firefox (desktop) Latest
- Edge (desktop) Latest

System:
- TypeScript version: 2.7.2 
- Node version: 10.7.0  
- Platform:  Windows

**Comment by danielkaradachki** [comment]
You can customize the list by setting the pageable pageSizes field to an array with the possible page sizes:
https://plnkr.co/edit/2taCi9dUc0qk6F2vJo3z?p=preview
