### ISSUE TITLE
DateInputs have unexpected section/text selection behavior

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1694]
Currently the DateInput/DatePicker allows for double and triple-clicking in the input. Triple-clicking briefly selects the whole content and then immediately selects only the first segment of the date.

Dragging within the input also briefly selects the whole value, but if the left mouse button is released while the cursor is still in the input, only the first segment stays selected (like when triple-clicking).

Expected behavior (based on input type="date"):

[http://dojo.telerik.com/eFiLuMAr](http://dojo.telerik.com/eFiLuMAr)

- clicking in the input selects the clicked segment

- double- and triple-clicking is ignored

- dragging across different segments is not possible

- pressing CTRL + A when the input is focused selects the whole content

The DateInput/DatePicker also differs from the INPUT type "date" behavior when the user clicks the white space to the right of the placeholder/value - currently the right-most (typically "year") section gets selected in the DateInput/DatePicker, while in the INPUT type "date", the left-most section gets selected.

**Comment by yanmariomenev** [comment]
Behavior improvement is available in version [14.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v14.0.0).
