### ISSUE TITLE
Grid sort order doesn't change after clicking on column title content when kendoGridHeaderTemplate is used

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#1695]
## I'm submitting a...
* Bug report 

## Current behavior
Grid sort order doesn't change after clicking on column title content when kendoGridHeaderTemplate is used.
![image](https://user-images.githubusercontent.com/33227044/43265877-ab77b50a-90f2-11e8-8d5b-50462bd0f1f2.png)

## Expected behavior
Sort order should work for kendoGridHeaderTemplate as well.

## Minimal reproduction of the problem with instructions
Here is a plunk with an example: [link](https://plnkr.co/edit/eIPHTDBtXMpGeYwETCQs?p=preview)

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://github.com/telerik/kendo-angular-grid/releases/tag/v3.6.1-dev.201808060737).

**Comment by danielkaradachki** [comment]
fixed in 3.6.1
