### ISSUE TITLE
Suggested improvement to Grid Reordering of Rows example

### ISSUE THREAD

**Issue by CasperAlant** [telerik/kendo-angular#1696]
## I'm submitting a...
* Documentation issue

## Current behavior
The example to demonstrate reordering of rows ([available here](https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/row-reordering/)) is a poor implementation and not really usable. It discouraged me from using the feature. It also has a couple Typescript errors.

## Expected behavior
The demo should demonstrate the features in such way as to be acceptable for use in applications.

## Minimal reproduction of the problem with instructions
[Open the Plunker](https://www.telerik.com/kendo-angular-ui/components/grid/advanced-features/row-reordering/)

## Fix
I've reworked the example to better demonstrate the feature and consider acceptable for use in an application. Fixed Typescript errors.
[Reworked example available here](https://plnkr.co/edit/DhCzYLJFjNxmKzj0T31e?p=preview)

#### PS 
I recall being able to contribute directly to the Kendo UI documentation repo, but couldn't find it now...

**Comment by CasperAlant** [comment]
A nice improvement to my example would be to use dragleave or dragexit to scroll the grid up or down. Right now you'd have to stop dragging, scroll, and drag again.

**Comment by danielkaradachki** [comment]
The [example](https://www.telerik.com/kendo-angular-ui/components/grid/how-to/row-reordering/) is updated.
