### ISSUE TITLE
A selectable and checkable TreeView does not allow to select other nodes

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1697]
## I'm submitting a...
* Bug report 

## Current behavior
When we load initially a TreeView, that uses both kendoTreeViewSelectable and kendoTreeViewCheckable directives and we check a node, then we cannot select another node.

## Expected behavior

We should be able to select other nodes.

## Minimal reproduction of the problem with instructions

[https://plnkr.co/edit/dRlJXi9REq5MyynBmc2a?p=preview](https://plnkr.co/edit/dRlJXi9REq5MyynBmc2a?p=preview)

1. Check the "Occasional Furniture" node.
2. Try to select another node.

**Comment by ipeshev** [comment]
Fixed in v2.3.0-dev.201808161041

**Comment by danielkaradachki** [comment]
Fixed in 2.3.0
