### ISSUE TITLE
ComboBox value not setting using api

### ISSUE THREAD

**Issue by josemolina001** [telerik/kendo-angular#1698]
## I'm submitting a...

* Bug report 

## Current behavior

  Setting the value this.element.value = mySelectedObject inside of directive does not set the value.

The only time this works properly without any other unwanted behavior is if I set valuePrimitive to true, call this.element.valueChange.emit(myselectedObject) then set this.element.text = mySelectedObject.text and this.element.value = mySelectedObject.value

However, this causes issues inside of my valueChange event. It restricts me to using just the primitive value being passed.

This almost works for me using selectionChange but when I re-focus in the combobox it seems that the selectionChange is no longer firing.

## Expected behavior
I expect that after setting the value as described above the value would be the selected item in the combo box. I have tried using the api by calling this.element.valueChange.emit(selectedObject) then setting the value and that does not work either.

## Minimal reproduction of the problem with 

import { Directive, HostListener } from '@angular/core';
import { ComboBoxComponent } from '@progress/kendo-angular-dropdowns';

@Directive({ selector: '[myComboBox]', exportAs: "myComboBox" })
export class MyComboBoxDirective {
    element: ComboBoxComponent;
    originaldata: any[];
    originalSelected: any;

    constructor(el: ComboBoxComponent) {
      this.element = el;
      this.element.valuePrimitive = true;
    }
    @HostListener('focus') onMouseEnter() {
      
      if (typeof this.originaldata === typeof undefined || this.element.data.length === 0) {
        this.originaldata = this.element.data;
      }
      if (this.element.data.length < this.originaldata.length && this.element.data.length !== 0) {
          this.element.data = this.originaldata;
      }

      if (typeof this.element.dataItem !== typeof undefined) {

        let idField = this.element.valueField;
        let textField = this.element.textField;
        this.originalSelected = this.element.dataItem[idField];

        let selectedIndex = this.element.data.findIndex(p => p[idField] === this.originalSelected);
        
        
        this.element.valueChange.emit(this.element.data[selectedIndex]);
        this.element.text = this.element.data[selectedIndex][textField];
        this.element.value = this.element.data[selectedIndex][idField];

        //this.element.selected = this.element.data[selectedIndex];

      }

      if (!this.element.isOpen) {       
        this.element.toggle(true);
      }
    }

## Environment

Package versions:
dropdowns - 2.1.0

**Comment by tapopov** [comment]
Hi @josemolina001 

Apologies for the delayed response. I managed to reproduce this and we'll address it as soon as possible. Stay tuned.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released in **v4.4.0.**
