### ISSUE TITLE
Window: wrong position, when opened in maximized state

### ISSUE THREAD

**Issue by rstabenow** [telerik/kendo-angular#1699]
## I'm submitting a...
* Bug report

## Current behavior
If a window is opened in 'maximized' state, it is positioned wrongly.

## Expected behavior
The window should be maximized.

## Minimal reproduction of the problem with instructions
It can be reproduced in the demo: [Minimizing and Maximizing](https://www.telerik.com/kendo-angular-ui/components/dialogs/window/minimizing-maximizing/)

1. Maximize the window
2. Close it
3. Re-Open it

Browser:
- Chrome (desktop) version 67
- IE version 11

**Comment by Raisolution** [comment]
Issue has been addressed in `v3.7.0-dev.201808011212`.

**Comment by rstabenow** [comment]
That fixes the problem, thank you!
