### ISSUE TITLE
Sibling nodes are treated as children when checking items

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1701]
## I'm submitting a...
* Bug report 

## Current behavior

When checking an element after the first ten, for example with an index number of "0_11", then the element with index "0_1" will incorrectly become half-checked as well. If we check element with index "0_20", then the element with index "0_2" will be half checked.

## Minimal reproduction of the problem with instructions
Check the following sample plunker:
[https://plnkr.co/edit/NiFFssYinwTyiv1az699?p=preview](https://plnkr.co/edit/NiFFssYinwTyiv1az699?p=preview)

and video demonstrating the issue:
[https://www.screencast.com/t/e1eluLvC4d8](https://www.screencast.com/t/e1eluLvC4d8)

**Comment by ipeshev** [comment]
Still observable in latest develop version ! https://plnkr.co/edit/0YT26081C8VBqDKXVddX?p=preview

**Comment by ipeshev** [comment]
Fixed in latest dev v2.2.1-dev.201808021108

**Comment by danielkaradachki** [comment]
Fixed in 2.3.0
