### ISSUE TITLE
Property active is undefined

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1702]
## I'm submitting a...
* Bug report 

## Current behavior
When using the visual function for the legend item of a pie chart, the returned object contains property "active", which is always undefined.

## Expected behavior
The "active" property should be set.

## Minimal reproduction of the problem with instructions
 Check the following sample plunker and inspect the browser's console:
[https://plnkr.co/edit/bv6N8YrgWfR5ISXCf4De?p=preview](https://plnkr.co/edit/bv6N8YrgWfR5ISXCf4De?p=preview)

**Comment by ipeshev** [comment]
Fixed in v3.3.2-dev.201808091334 of kendo-angular-charts

**Comment by tsvetomir** [comment]
Shipped in v3.3.2
