### ISSUE TITLE
Charts - Fixed Bar Size

### ISSUE THREAD

**Issue by shawnhancock** [telerik/kendo-angular#1703]
Our company is making use of the chart component and we require the bar chart to have a fixed size. 

We came across this link which references exactly what we need but in jQuery. We are not making use of jQuery at all in our project.
https://docs.telerik.com/kendo-ui/controls/charts/how-to/appearance/fixed-bar-size

Do you have a method of setting a fixed bar size for the Angular component?

**Comment by tsvetomir** [comment]
The purpose of this issue tracker is to log defects, encountered as part of the normal operation of the components. Please, file a support ticket for assistance with adapting this example for Angular.
