### ISSUE TITLE
Grid Excel Export - column groups are not exported

### ISSUE THREAD

**Issue by LambdaCruiser** [telerik/kendo-angular#1705]
## I'm submitting a...

* Bug report 

## Current behavior

Grid column groups (including any columns inside the group) are not present in the Excel export. 

## Expected behavior
Export should contain all the column groups and their inner columns 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/ndfAMbBAcp0qdQVZuB74?p=preview
Click the 'Export' button and see that the generated Excel file is empty.

**Comment by danielkaradachki** [comment]
Fixed in 3.6.1
