### ISSUE TITLE
DatePicker Component has accessibility issues

### ISSUE THREAD

**Issue by gchurchley** [telerik/kendo-angular#1707]
## I'm submitting a defect with the DatePicker component
* Bug report

## Current behavior
Our users ran an accessibility audit and reported the following:

1. The date picker buttons have an aria-controls attribute value that references an id that does not exist in the DOM. 

2. The Date input field must not have aria-expanded attribute. This ARIA attribute is not allowed on an input element. When the ARIA specification is not followed for attributes used, assistive technologies may not render the appropriate information to the users.

3. The date picker controls are implemented as spinbuttons however this role is not appropriate for the functionality of the control. A spinbutton typically allows the user to select from the given range through the use of an up and down button on the keyboard. However, the date field allows users to select the day, the month and the year separately by tabbing to each field. This functionality is not clear to screen reader users who will not expect to use a spinbutton to change a date field.

4. The Toggle calendar button is not keyboard accessible. It is implemented with a span element and mouse related event handlers. Most people with disabilities who rely on the keyboard as the some method of navigation will not have access to this button.

## Expected behavior
My opinion of the 4 points above:
1. the aria-controls attribute actually references the id of the calendar popup. The calendar is created when needed so this issue only appears when the calendar is collapsed. One solution that would fix this issue would be to have a permanently created calendar in the DOM that is referenced by the aria-controls attribute. The permanent calendar would then show/hide as necessary. (I believe this is how the PeterBlum picker used to work.)

2.  Apparently, the aria-expanded attribute is not allowed on an input element.  Can this attribute be moved to another element type?

3.  Implementing the date input as a spin button was clearly a design choice. Please could you comment on this? It appears that assistive technology struggles to interpret the control's meaning. Have you received other complaints about this issue?

4.  The calendar icon button is not keyboard accessible. The calendar can be expanded by using alt-downArrow but the calendar icon itself cannot be reached via the keyboard. Why would the calendar icon not be a button?

## Minimal reproduction of the problem with instructions
**STEPS TO REPRODUCE**
Any DatePicker component on the Kendo Angular UI Components demo web site can be viewed to see these issues.
**MINIMAL DEMO** 
Here's a plunker: https://plnkr.co/edit/6DITLiXmrikpQ3sROfzr?p=preview

## Environment
Any

Browser:
- Chrome (desktop) version 67.0.3396.99
- Firefox version 61.0.1
- Edge version 42.17134.1.0

System:
Any

**Comment by shreya-khajanchi** [comment]
Hi,

**Comment by shreya-khajanchi** [comment]
Hi,I am facing the same accessibility issue with Angular v5 and dateinputs version 2.2.0. Any update on this?

**Comment by dimitar-pechev** [comment]
Adding to this issue: too much redundant info is announced when the Popup Calendar is focused (e.g. the names of other rendered months which don't hold the focused data).

**Comment by svetq** [comment]
also referenced in private support thread 1552445

**Comment by ipeshev** [comment]
Still having problems with aria-activedescendant of the input , it is set to wrong date , and there is report for "Document has multiple elements referenced with ARIA with the same id attribute: kendo-calendarid-0"

**Comment by stnikolova** [comment]
Released with **v7.1.5** of `@progress/kendo-angular-dateinputs`
