### ISSUE TITLE
Compatiblity with rxjs 6.0.0?

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#1709]
Hello we have in all projects latets stable angular with rxjs: 6.0.0 however we are not able to build because of telerik charts:

`ERROR in node_modules/@progress/kendo-angular-charts/dist/es2015/chart.component.d.ts(5,10): error TS2305: Module '"C:/Users/Dynabit/Documents/Visual Studio 2015/Projects/mediware/seed/Source/Frontends/mw-portal/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/@progress/kendo-angular-charts/dist/es2015/common/collection-item.component.d.ts(2,10): error TS2305: Module '"C:/Users/Dynabit/Documents/Visual Studio 2015/Projects/mediware/seed/Source/Frontends/mw-portal/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/@progress/kendo-angular-charts/dist/es2015/common/collection.service.d.ts(1,10): error TS2305: Module '"C:/Users/Dynabit/Documents/Visual Studio 2015/Projects/mediware/seed/Source/Frontends/mw-portal/node_modules/rxjs/Observable"' has no exported member 'Observable'.`

and so on... 

HOw to develop angular 6 applicaitons (rxjs 6.0) with kendo?

**Comment by montella1507** [comment]
Fixed by installing npm install --save rxjs-compat@6 . I think it may be as dependency in kendo directly?

**Comment by tsvetomir** [comment]
The dependency on `rxjs-compat` is noted in the [Manual Setup section](https://www.telerik.com/kendo-angular-ui/components/charts/#toc-manual-setup) of the component docs. Using `ng add` also installs it automatically.

**Comment by xinthose** [comment]
> The dependency on `rxjs-compat` is noted in the [Manual Setup section](https://www.telerik.com/kendo-angular-ui/components/charts/#toc-manual-setup) of the component docs.
> Using `ng add` also installs it automatically.

https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/

**Comment by tsvetomir** [comment]
@xinthose removed this section as it's now obsolete, see https://github.com/telerik/kendo-angular/issues/2234. Thanks!
