### ISSUE TITLE
Filter row inputs do not have accessible labels

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1710]
## I'm submitting a...
* Bug report 

## Current behavior
Tabbing in the filter row inputs does not announce the purpose of the control.
The "filter" label is only announced while navigating grid cells with the arrow keys.

## Expected behavior
Each input control should have an associated label, e.g. "Unit Price Filter".

## Minimal reproduction of the problem with instructions
1. Open the [KB Navigation demo](https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/)
1. Select the Name filter cell
1. Tab two times to the Price filter cell
1. The screen reader announces the column name and "edit, typing text", but does not announce the purpose of the input.

## Environment

Package versions:
```
@progress/kendo-angular-grid 3.6.0
```

Browser:
- Chrome (desktop) version 68
- IE version 11

System:
- JAWS 2018

**Comment by Crossfir3** [comment]
Tested ok with the examples and demos we currently have. 
A proper aria-label is attached to all filter input fields, except when they are part of the filter menu.

**Comment by dtopalov** [comment]
Fixed in v. 5.1.0 of the @progress/kendo-angular-grid package.
