### ISSUE TITLE
Sorting is not possible with keyboard shortcuts

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1711]
## I'm submitting a...
* Bug report 

## Current behavior
It is not possible to sort any column using solely the built-in shortcuts.

## Expected behavior
Header cells should have an accessible Sort button that can be activated with the keyboard.

## Minimal reproduction of the problem with instructions
1. Open the [KB Navigation demo](https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/)
1. Navigate to the header cell for Name using the arrow keys
1. Press Enter to activate the cell
1. Nothing happens

## Environment

Package versions:
```
@progress/kendo-angular-grid 3.6.0
```

Browser:
- Chrome (desktop) version 68
- IE version 11

System:
- JAWS 2018

**Comment by ipeshev** [comment]
Available in v3.7.0-dev.201808151156

**Comment by tsvetomir** [comment]
The sorting order is not announced in JAWS and NVDA upon pressing Enter.

**Comment by tsvetomir** [comment]
The development channel now includes announcements for the sorting operations, see [demo](https://angular-a7mmcl.stackblitz.io).

**Comment by tsvetomir** [comment]
Shipped in v3.7.0
