### ISSUE TITLE
Update use of rxjs to comply with version 6 changes. 

### ISSUE THREAD

**Issue by strizzaflex** [telerik/kendo-angular#1712]
## I'm submitting a...
Bug report

## Current behavior
Using Kendo UI without the rxjs-compat library breaks the application.

## Expected behavior
I don't need to use the rxjs-compat library.

## Minimal reproduction of the problem with instructions
Upgrade project to angular 6 and don't install rxjs-compat.

## Environment

Package versions:
+-- @progress/kendo-angular-buttons@4.1.2
+-- @progress/kendo-angular-dateinputs@3.4.4
+-- @progress/kendo-angular-dialog@3.6.2
+-- @progress/kendo-angular-dropdowns@3.0.2
+-- @progress/kendo-angular-excel-export@2.1.1
+-- @progress/kendo-angular-grid@3.6.0
+-- @progress/kendo-angular-inputs@3.2.0
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-layout@3.1.1
+-- @progress/kendo-angular-popup@2.4.1
+-- @progress/kendo-angular-sortable@1.1.1
+-- @progress/kendo-data-query@1.4.0
+-- @progress/kendo-drawing@1.5.7
+-- @progress/kendo-theme-bootstrap@2.13.7
+-- @progress/kendo-theme-default@2.54.1
```

```

Browser:
-- NA

System:
- TypeScript version: 2.9.2
- Node version:  8.11.3 -Npm 5.3.0 
- Platform:  Windows

**Comment by gyoshev** [comment]
The components are compatible with RxJS 6. The `rxjs-compat` dependency is necessary in order to ensure long-term support for Angular 5. This package does not increase the bundle size, because operators are just re-exported. [See this thread](https://github.com/telerik/kendo-angular/issues/1563) for more information.

**Comment by strizzaflex** [comment]
Thanks for the link this is the info I was looking for.
