### ISSUE TITLE
Esc closing behaviour should be able to be cancelled

### ISSUE THREAD

**Issue by nicolas-b12** [telerik/kendo-angular#1713]
## I'm submitting a...

* Bug report 

## Current behavior

Currently, Dialog is closable using Esc but this behaviour should be able to be cancelled.

## Expected behavior
An Input flag should be used to describe whether to close or not with Esc key.

## Minimal reproduction of the problem with instructions

See Basic example of the Dialog docs page

## Environment

_Not related to the environment_

**Comment by Raisolution** [comment]
Hi @nicolas-b12,

The current behavior is by design and not a bug. You could post this as an improvement suggestion in our [User Voice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback).
