### ISSUE TITLE
toODataString serializes the string for "is empty" and "is not empty" operators differently

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1714]
## I'm submitting a...
* Bug report 

## Current behavior
When filtering a field like "Category.CategoryName", toODataString serializes the string for "is empty" operator as follows:

> CategoryName ne '' and Category.CategoryName eq ''

 whereas when using the other operators like "equals" the string is:

> Category/CategoryName eq 'Beverages'

## Expected behavior

The string serialization should be following the same convention with "/"

## Minimal reproduction of the problem with instructions
Check the following sample plunker and inspect the browsers' console when changing the filters for the second column:
[https://plnkr.co/edit/6Ar3bnZHoZtbAbHI9MSa?p=preview](https://plnkr.co/edit/6Ar3bnZHoZtbAbHI9MSa?p=preview)

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://github.com/telerik/kendo-angular-grid/releases/tag/v3.6.1-dev.201808060737).

**Comment by tsvetomir** [comment]
Fixed in v1.4.1
