### ISSUE TITLE
excel export:  autoWidth and colSpan doesn't work well

### ISSUE THREAD

**Issue by zzs1020** [telerik/kendo-angular#1716]
## I'm submitting a bug

* Bug report 
* Documentation issue
excel export's setting {autoWidth: true} doesn't work well with {colSpan: num}

## Current behavior

when setting excel export like following:
```
const workbook = new Workbook(<WorkbookOptions>{
            sheets: [{
                        columns: {
                                  autoWidth: true
                         },
                         rows: [{
                                  cells: [{value: 'this is a description of this excel blahblah blahblah', colSpan: 4}]
                          }, {
                                  cells: [{value: 'value2'},{value: 'value2'},{value: 'value2'},{value: 'value2'}
                               ]}]
             }]
        });
```
it generates an excel but having non-header row's first cell very long:
![capture](https://user-images.githubusercontent.com/23032993/43725051-8011f798-9969-11e8-8bb6-2a4dc690aa11.PNG)

## Expected behavior

when cellsOptions having colspan set up, it shouldn't be considered as the longest column of autoWidth.
correct effect should be:
![capture22](https://user-images.githubusercontent.com/23032993/43725335-3c3234e2-996a-11e8-9eb0-ca5a0d7ee7ba.PNG)

Or there should be a way to set autoWidth for specific cell, i.e.
```
cells: [{value: 'this is a description of this excel blahblah blahblah', autoWith: false}]
```

## Minimal reproduction of the problem with instructions

```
const workbook = new Workbook(<WorkbookOptions>{
            sheets: [{
                        columns: {
                                  autoWidth: true
                         },
                         rows: [{
                                  cells: [{value: 'this is a description of this excel blahblah blahblah', colSpan: 4}]
                          }, {
                                  cells: [{value: 'value2'},{value: 'value2'},{value: 'value2'},{value: 'value2'}
                               ]}]
             }]
        });
```

## Environment
window 8, chrome  68.0.3440.75,
Package versions:
"@progress/kendo-angular-excel-export": "2.1.0"

```

```

Browser:

- Chrome (desktop) version   68.0.3440.75
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 2.5.3
- Node version: XX  8.11.3
- Platform:   windows

**Comment by danielkaradachki** [comment]
The behavior is expected. The autoWidth option will set the size of the column depending on the cells value. You could set specific width based on the other cells to avoid this. 

Regarding the suggestion for the cell autoWidth option - feature requests for additional options can be submitted in our [uservoice forum](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback).
