### ISSUE TITLE
Seemingly unrelated user interaction causes grid's ngAfterContentChecked to fire, resulting in poor grid performance

### ISSUE THREAD

**Issue by zrsio4** [telerik/kendo-angular#1717]
## I'm submitting a...
* Bug report

## Current behavior
Any user interaction causes ngAfterContentChecked of the Kendo GridComponent to fire, resulting in high number of cell refreshes, slowing user experience

## Expected behavior
Significantly less cell refreshes for seemingly unrelated user interaction

## Minimal reproduction of the problem with instructions
[https://plnkr.co/edit/vhtmLxfM4gglvc4ZxwqW](https://plnkr.co/edit/vhtmLxfM4gglvc4ZxwqW)
1) Open developer tools
2) make row selections, observe console message count increase
3) type into textbox, observe console message count increase with each keystroke.

## Environment
Browser:

- Chrome (desktop) version 67.0.3396.99

System:
- Platform:  Windows

**Comment by danielkaradachki** [comment]
This is how the angular change detection works. On each change detection (triggered in this case on input by NgModel and by the selection) angular checks the current value of each expression and compares it with the previous one. Should be possible to avoid rechecking the grid on input by placing the grid in a nested component with OnPush strategy. You could also improve the performance by using [paging](https://www.telerik.com/kendo-angular-ui/components/grid/paging/) or [virtual scrolling](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/#toc-virtual-scrolling) to render less data at a time.

**Comment by zrsio4** [comment]
The component the grid is in is using the OnPush strategy. Are you suggesting I put the grid in a child component? What do I do if I want an input in the toolbar (as in the example)?
The grid in my project is virtual, but even with 100 rows and maybe 30 columns, there's a noticeable slowdown in user experience with the input in the toolbar, and even selection seems to lag. To be clear, the component the grid is in is using the OnPush strategy, grid is using virtual scrolling. 
Even a click on a non-interactive portion triggers ngAfterContentChecked on the grid.

**Comment by danielkaradachki** [comment]
The same behavior can be reproduced with any component:
https://plnkr.co/edit/D4ew4H98a9YGOkOMqiZX?p=preview

OnPush works only if the change is triggered by a parent component.

If the rendered data cannot be reduced further then I can suggest to use the input change event instead of NgModel so that the change detection is not triggered on each input.

Not sure if I understand the issue with the click on a non-interactive portion. At least on my side the change detection is triggered only on click of the rows which is required for the selection.
