### ISSUE TITLE
How to Edit data when funtion return type BehaviorSubject<any> 

### ISSUE THREAD

**Issue by vinhnguyennqweb1995** [telerik/kendo-angular#1718]
## I'm submitting a...

* Regression report 
* Bug report 
* Documentation issue

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by vinhnguyennqweb1995** [comment]
I have this.data= this.stateChange.pipe(
            tap(state => {
                this.state = state;
                this.loading = true;
            }),
            switchMap(state => service.fetch(state)),
            tap(() => {
                this.loading = false;
            })
        );
after I recieved data, how to change one record in array data

**Comment by danielkaradachki** [comment]
This repository is for bug reports only. Please, open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios.
