### ISSUE TITLE
Async pipe produces two subscriptions when bound to data in TreeViewComponent + FlatDataBindingDirective

### ISSUE THREAD

**Issue by cebamps** [telerik/kendo-angular#1719]
## I'm submitting a...

* Bug report 

## Current behavior

Binding the output of an `async` pipe to the `data` input of the `TreeViewComponent` causes a double subscription to the Observable when `FlatDataBindingDirective` is in use.

## Expected behavior

Using an `async` pipe to bind the output of an observable to a `TreeViewComponent`'s `data` input should produce a single subscription to the observable.

This is indeed what happens when using `HierarchyBindingDirective`, but using `FlatDataBindingDirective` produces *two* subscriptions to the observable, as demonstrated in the example below.

As a workaround, replacing `[data]="treeNodes$ | async` with `*ngIf="treeNodes$ | async as treeNodes" [data]="treeNodes"` also produces a single subscription, as expected.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/tcE9RC4m7dPAqvX6895B?p=preview

Open the console and notice the following output:
```
flatTreeNodes$ subscribed: 1
flatTreeNodes$ subscribed: 2
hierarchicalTreeNodes$ subscribed: 1
```

## Environment
See Plunker link above.

Browser:

- Chrome (iOS) version 68.0.3440.84
- Firefox version 61.0.1

**Comment by danielkaradachki** [comment]
I am not sure if I understand the issue. What problems are caused by the second subscription? The difference with the hierarchy directive is that the flat binding directive needs to transform the data and thus it also has a _nodes_ Input.

**Comment by cebamps** [comment]
The problem with the second subscription is that it is not expected. The expected behavior is that the async pipe should produce a single subscription.

If the observable subscribed to comes from Angular's [`HttpClient.request()`](https://angular.io/api/common/http/HttpClient#request) for example, one request will be performed for each subscription.

I now understand why flat binding is different from hierarchical: both the `TreeViewComponent` and the `FlatDataBindingDirective` have an input named `nodes`, and Angular must be evaluating the async pipe once for each, resulting in two instances of the pipe...

Here is a Plunker demonstrating the same double subscription behavior in Angular directives: https://plnkr.co/edit/3f0Z4VS8bobS3Quy?p=preview

I guess I can't blame Kendo then... But this indicates another safe solution: replacing `treeNodes$` with `treeNodes$.pipe(shareReplay(1))` will prevent the side effects of multiple concurrent subscriptions.

I am unsure whether this should be considered an Angular bug. I have not found it reported elsewhere but it is a bit tricky to search for...

Thanks for your reply!

**Comment by danielkaradachki** [comment]
Thanks for clarifying and for the suggested workaround. 
I guess the only thing that we can do on our side is to expose a separate input for the directive. We will reconsider it if the this becomes a common issue.
