### ISSUE TITLE
NumericTextbox - [format]="'d'" not working correctly

### ISSUE THREAD

**Issue by JStarkl** [telerik/kendo-angular#1720]
## I'm submitting a...
* Bug report

## Current behavior
NumericTextBoxComponent format-attribute "d/D" removes minus from negative values when unfocused

Alternatively I used "n0", which works correctly

## Expected behavior
Format "d" should behave like "n0"

## Minimal reproduction of the problem with instructions
`<kendo-numerictextbox [value]="value" [format]="'d'"></kendo-numerictextbox>`

## Environment

Package versions:
@progress/kendo-angular-inputs@3.2.0

Browser:
- Chrome (desktop) 67.0.3396.99 64bit
- Firefox (desktop) 59.0.3 (64-Bit)

System:
- TypeScript version: 1.0.3.0
- Node version: v8.11.3
- Node version: 5.6.0
- Platform: Windows 10

**Comment by danielkaradachki** [comment]
"d" is not a valid numeric format and is interpreted as custom format without decimal separator. Check [this](https://github.com/telerik/kendo-intl/blob/develop/docs/num-formatting/index.md) page for information about the valid numeric formats provided by the default CldrIntlService.
