### ISSUE TITLE
Australia locale en-AU datepicker date format bug

### ISSUE THREAD

**Issue by tennisprochase** [telerik/kendo-angular#1722]
## I'm submitting a...
* Bug report

## Current behavior
When using the LOCALE_ID to change the globalization/localization of the Kendo UI Angular DatePicker component, the proper date format is not applied to the textbox for the Australia locale ("en-AU"). When set to this locale, the datepicker is displaying the date format incorrectly as 'MDY'. This is the correct format for "en-US", but not for "en-AU".

## Expected behavior
According to the wiki page for date formats by country:
(https://en.wikipedia.org/wiki/Date_format_by_country)

Australia's date format should be 'DMY' instead of 'MDY'.

## Minimal reproduction of the problem with instructions
Here is the issue in plunker:
https://next.plnkr.co/edit/4wZohS3dnxuVg474?preview

## System Information
Browser:
- Chrome (desktop) Version 68.0.3440.84 (Official Build) (64-bit)

System:
- TypeScript version: 3.0.1
- Node version: v8.11.3
- NPM version: 5.6.0
- Platform:  Windows 10 Enterprise 64-bit

**Comment by danielkaradachki** [comment]
At least in the provided example you haven't loaded the en-AU locale so the intl service will fallback to the default locale for the language. Loading the locale seems to fix the issue:

https://next.plnkr.co/edit/IGmINAXXa6B5TEir

**Comment by tennisprochase** [comment]
@danielkaradachki 

Is there documentation somewhere that lists which locales are available for import? I haven't been able to find a working list yet.

Some locales are working and some are not. Here are a few that I tried to implement that are not working:

```
import '@progress/kendo-angular-intl/locales/en-US/all';
import '@progress/kendo-angular-intl/locales/pt-BR/all';
import '@progress/kendo-angular-intl/locales/fr-FR/all';
import '@progress/kendo-angular-intl/locales/zh-CN/all';
```

For these I had to load the default language codes of 'en', 'pt', 'fr', 'zh' to get things to work.

Here are the two that I was able to import and get working:

```
import '@progress/kendo-angular-intl/locales/en-GB/all';
import '@progress/kendo-angular-intl/locales/en-AU/all';
```

Just trying to find a list of locales that are available for import and work so that I can refer to it.

Thanks!

**Comment by danielkaradachki** [comment]
We provide a prebuilt locale for all locales available in the [CLDR](http://cldr.unicode.org/) data. You can check the full list in the package or in one of the CLDR repos:
https://github.com/unicode-cldr/cldr-dates-modern/tree/master/main
