### ISSUE TITLE
Grid with virtual scrolling in RTL mode is not rendered properly

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1723]
When in RTL mode, the Grid with virtual scrolling is not rendered as expected - there is a discrepancy between column content and headers:

![image](https://user-images.githubusercontent.com/7533599/43822098-c0908f56-9af3-11e8-8bf4-98d417d5affd.png)

[https://plnkr.co/edit/EJQuDLu8J3Tac9XVZstJ?p=preview](https://plnkr.co/edit/EJQuDLu8J3Tac9XVZstJ?p=preview)

**Comment by danielkaradachki** [comment]
Released in the latest versions of the themes

https://plnkr.co/edit/VTz1mOhC2aqf9B3DqZhQ?p=preview
