### ISSUE TITLE
DatePicker calendar must be tapped twice on IPad when on scrollable page

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1726]
On the iPad, the DatePicker requires two taps on the selected date before it recognizes the selection and closes. It seems as if the first tap is ignored, tapping a different date is ignored. The same exact date needs to be tapped twice. 

This problem only exists if the content is long enough to require scrolling (i.e. fills the entire container height or greater). If the content is small enough, the DatePicker works as expected.

[https://plnkr.co/edit/q2csXe506suHZsJyo9kw?p=preview](https://plnkr.co/edit/q2csXe506suHZsJyo9kw?p=preview)

(must be run in a separate window view)

Internal ref: Reported in a private support thread - Ticket ID: 1337074

**Comment by stnikolova** [comment]
The issue is no longer reproducible with latest (v14.1.0) @progress/kendo-angular-dateinputs version.
