### ISSUE TITLE
Grid filtering doesn't work if Enter key hit quickly after entering filter text

### ISSUE THREAD

**Issue by djm266** [telerik/kendo-angular#1727]
## I'm submitting a...

* Bug report 

## Current behavior

If you open the "Filter Menu" Plunker example located on this page https://www.telerik.com/kendo-angular-ui/components/grid/filtering/, the example shows a grid where the Product Name currently has a filter applied to it "contains Chef".  If you click on the funnel icon to view the currently applied filter and then change the word Chef to "Chefs" and quickly hit Enter, the filter reverts back to its original state.  In other words, the "Chefs" text is discarded and the old filter text returns "Chef".

I saved a Plunker demo here, but all I did was open the Pluker example described above and save it.  I didn't actually edit the existing Plunker example.

https://plnkr.co/edit/If2BChbSH7eL7piroxPS?p=preview

If you change the filter text to "Chefs" and wait about 1/2 second and then press the Enter key, it seems to work.  So the issue only occurs if you press the Enter key quickly after changing the filter text.

## Expected behavior

New filter text should be persisted.

## Minimal reproduction of the problem with instructions
I was able to produce the issue using the Plunker app provided by Kendo to demonstrate filtering using the filtering menu.  I saved a copy of the Pluker here (note I didn't change anything in the Plunker example to reproduce the issue).

https://plnkr.co/edit/If2BChbSH7eL7piroxPS?p=preview

## Environment

Browser:
- Chrome (desktop) version 68.0.3440.106
- Firefox version 61.0.2

**Comment by tsvetomir** [comment]
Fixed in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Shipped in v3.7.0
