### ISSUE TITLE
kendo-angular-ui  pdf export does not work in IE 11 

### ISSUE THREAD

**Issue by amullya** [telerik/kendo-angular#1729]
Current behavior
Grid -  export pdf shows 'sampleDoc.pdf couldn't be downloaded'  in IE 11 but it does render in Chrome OR MS EDGE.

Expected behavior
It should work in IE 11 as well.

Minimal reproduction of the problem with instructions
Environment
Package versions:

{
  "name": "vizer-ui-demo",
  "version": "0.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "copy-lib-res": "node copy-lib-res.js",
    "lint-lib": "ng lint vizer-ui-core",
    "link-lib": "npm link ./dist/vizer-ui-core",
    "pack-lib": "npm pack ./dist/vizer-ui-core",
    "build-prod-lib": "ng build --prod vizer-ui-core",
    "build-dev-lib": "ng build vizer-ui-core",
    "build-lib": "run-s lint-lib build-prod-lib copy-lib-res pack-lib",
    "run-lib": "run-s lint-lib build-dev-lib copy-lib-res",
    "setup-lib": "run-s lint-lib build-dev-lib copy-lib-res link-lib",
    "test-lib": "ng test vizer-ui-core",
    "test-lib:ci": "ng test vizer-ui-core --watch=false --browsers=ChromeHeadless --code-coverage"
  },
  "private": true,
  "publishConfig": {
    "registry": "http://clt-nexus.checksol2.pvt:8082/nexus/repository/npm-local/",
    "registry2": "http://10.9.102.44:7058/nexus/content/repositories/npm-internal/"
  },
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^6.3.1",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@ng-bootstrap/ng-bootstrap": "^2.1.1",
    "@progress/kendo-angular-buttons": "^4.0.0",
    "@progress/kendo-angular-dateinputs": "2 - 3",
    "@progress/kendo-angular-dropdowns": "2 - 3",
    "@progress/kendo-angular-excel-export": "1 - 2",
    "@progress/kendo-angular-grid": "^3.5.0",
    "@progress/kendo-angular-inputs": "2 - 3",
    "@progress/kendo-angular-intl": "^1.0.0",
    "@progress/kendo-angular-l10n": "^1.2.0",
    "@progress/kendo-angular-layout": "^3.1.1",
    "@progress/kendo-angular-menu": "^1.0.0",
    "@progress/kendo-angular-pdf-export": "^1.1.2",
    "@progress/kendo-angular-popup": "^2.0.0",
    "@progress/kendo-angular-treeview": "^2.2.0",
    "@progress/kendo-data-query": "^1.0.0",
    "@progress/kendo-drawing": "^1.0.0",
    "@progress/kendo-theme-default": "^2.54.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "fdl-bootstrap-4": "^4.0.3",
    "pako": "^1.0.6",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular-devkit/build-ng-packagr": "~0.6.1",
    "@angular/cli": "~6.0.1",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-scss-preprocessor": "^3.0.0",
    "ncp": "^2.0.0",
    "ng-packagr": "^3.0.0-rc.2",
    "node-sass": "^4.9.0",
    "npm-run-all": "^4.1.3",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tsickle": ">=0.25.5",
    "tslib": "^1.7.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}

**Comment by tsvetomir** [comment]
The [online demo](https://www.telerik.com/kendo-angular-ui/components/grid/export/pdf-export/) seems to work fine in IE11. Perhaps the error is due to the specific content or styling.

We will need a sample project that reproduces the error in order to debug it.
