### ISSUE TITLE
[ComboBox] selectionChange is not fired when selecting the same option

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1733]
## I'm submitting a...
* Bug report 

## Current behavior
selectionChange event is not fired, if the value is changed programmatically and then we select the same value from the UI.

## Expected behavior
selectionChange event should be fired

## Minimal reproduction of the problem with instructions
1. Select the "Small" option from the dropdown.
2. Click the "Click me" button.
3. Again, select the "Small" option from the dropdown. selectionChange is not fired at this time.

[https://next.plnkr.co/edit/7yfXS80aWhdP3yRG](https://next.plnkr.co/edit/7yfXS80aWhdP3yRG)

**Comment by LeFredd** [comment]
Hi, what is it?

**Comment by unrealmaker** [comment]
it looks like it works with the newest version.
@tapopov you should close the ticket if it's working...

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
Shipped with **v4.2.0**.
