### ISSUE TITLE
DatePicker focuses a day in each month

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1735]
## I'm submitting a...
* Bug report 

## Current behavior
Setting the [min] property of the DatePicker, causes each month to have the day of the value used for [min] to be focused (regardless of the used theme). 

## Minimal reproduction of the problem with instructions

Check the following example:
[https://stackblitz.com/edit/angular-axu3wb-hqmaqv](https://stackblitz.com/edit/angular-axu3wb-hqmaqv)

1. Change the month by clicking (not using scrolling)
2. Day 10 of each month is focused.

Check the following video demonstrating the issue:
[https://www.screencast.com/t/p5Yv4pBv](https://www.screencast.com/t/p5Yv4pBv)

**Comment by ipeshev** [comment]
Fix shipped with v4.3.2
