### ISSUE TITLE
Import error when opening example in StackBlitz

### ISSUE THREAD

**Issue by preetamjakhmola** [telerik/kendo-angular#1737]
https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/parsing-and-formatting/
in the given link I am trying to open into stackblitz and it is showing me 
"Import error, can't find file:
app/app.module.ts"
this kind of error.
Note: app.module.ts file is not there. I did not delete anything in stackblitz
![image](https://user-images.githubusercontent.com/35592214/44199849-d491ec00-a162-11e8-9d69-0e1ed66fed0a.png)

**Comment by Raisolution** [comment]
Hi @preetamjakhmola,

Thank you for noticing this problem. We will update the examples with the correct file name. As a quick fix you could rename the `ng.module.ts` file to `app.module.ts` in order to run the example correctly.
