### ISSUE TITLE
suggestion is wrong by telerik

### ISSUE THREAD

**Issue by preetamjakhmola** [telerik/kendo-angular#1738]
![image](https://user-images.githubusercontent.com/35592214/44199926-fee3a980-a162-11e8-877e-490859650f74.png)

Given suggestion by telerik is wrong.
follow the given link
https://www.telerik.com/kendo-angular-ui/support/#bug-reporting

**Comment by tsvetomir** [comment]
Fixed, will be live in a few hours. Thanks!
