### ISSUE TITLE
kendoGridBinding not working with OnPush

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1743]
## I'm submitting a...
* Bug report 

## Current behavior
It's not working. When you type strange behaviour is experienced.

## Expected behavior
It works with OnPush strategy.

## Minimal reproduction of the problem with instructions
[Plunkr](https://stackblitz.com/edit/angular-e9h2mh?file=app/app.component.ts).
- Press b.
- Wait for one second (no filtering)
- Press a (filter for b is applied, a is lost)

**Comment by ipeshev** [comment]
Thank you for the bug report we will investigate this faulty behavior further !

**Comment by tsvetomir** [comment]
Fixed in v3.7.0
