### ISSUE TITLE
Header part is not changed when date range selection is changed

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1744]
## I'm submitting a...

* Bug report 

## Current behavior

Header part ( month from -> month to ) is not changed when date range is changed programmatically 

## Expected behavior

Header part should be changed when date range is changed!

## Minimal reproduction of the problem with instructions

1. Open this [stackblitz sample](https://stackblitz.com/edit/angular-7zvybm-rd3dkh?file=app/app.component.ts).
2. Set date in the inputs to 8/10/2018 , 8/20/2018.
3. Header still shows September 2018 - October 2018
## Environment

Package versions:

```
v3.4.4
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dateinputs` **v3.5.5-dev.201901311329**.

**Comment by ipeshev** [comment]
Considre following example [https://stackblitz.com/edit/angular-7zvybm-zpuftv?file=app/app.component.ts](https://stackblitz.com/edit/angular-7zvybm-zpuftv?file=app/app.component.ts) should header shows Febryary - October ?

**Comment by dimitar-pechev** [comment]
The header shows which months are currently displayed. In the provided example February and March are displayed and hence the 'February - March' header. The fix handles the programmatic change of the `focusedDate` which didn't correctly update the header part.

**Comment by dimitar-pechev** [comment]
The fix is shipped with **v3.6.0**.
