### ISSUE TITLE
Multiselect with allowCustom parameter doesn't remove typed value

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#1745]
## I'm submitting a...

* Bug report 

## Current behavior

If you have a multiselect with allowCustom option, you won't have an ability to delete typed value in input box. You can clear all values, but not the only one.
## Expected behavior
Multiselect should clear typed value

## Minimal reproduction of the problem with instructions

1. Open https://stackblitz.com/edit/angular-l35tz4?file=app/app.component.ts
2. Type 'tennis' in input box and press enter
3. Open a list of variants and inspect that typed value hasn't got selected state and you can't remove it.
## Environment

Package versions: the newest version of Angular and kendo-dropdowns packages.
Browser:

- Chrome (desktop) version 68

**Comment by destus90** [comment]
@dimitar-pechev Has it been fixed? Could you update stackblitz example?

**Comment by dimitar-pechev** [comment]
@destus90 Yes, a fix has been introduced in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package (v3.3.0-dev.201810301151). Some testing is, however, still to be done. 

Usually, a feature or a bug fix is added to the official release withing a few weeks after being added to the dev channel. I'll notify you here when that happens.

You can see an example with the corrected behavior [here](https://stackblitz.com/edit/angular-jyxwfo). The dev version of the `@progress/kendo-angular-dropdowns` package is used in it, as you can see in the `package.json`.

**Comment by destus90** [comment]
@dimitar-pechev It seems to be working 👍

**Comment by dimitar-pechev** [comment]
Shipped in v3.3.0 of the `@progress/kendo-angular-dropdowns` package.
