### ISSUE TITLE
DateRange does not highlight the proper date range

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1746]
## I'm submitting a...
* Bug report 

## Current behavior
When changing the range of the DateRange programmatically, the highlighted range is not changed. The start and end dates in the inputs get properly changed. 

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-chrjvs-lup4sr?file=app/app.component.ts](https://stackblitz.com/edit/angular-chrjvs-lup4sr?file=app/app.component.ts)

1. Select Start and End dates.
2. Click the "Change dateRange" button in order to change the start date.
3. If the cursor remains in the boundaries of the Popup template, the start date, in the input, will be set properly to today, but the highlighted date range will not be updated. If we move the cursor outside of the boundaries of the Popup template, then the start date will be change to the initially selected date.

**Comment by dimitar-pechev** [comment]
Fixed in the latest dev version of the **DateInputs** package (`v4.0.1-dev.201907011518`).

**Comment by dimitar-pechev** [comment]
Shipped with **v4.0.1**.
