### ISSUE TITLE
DatePicker does not close on "Today" button click

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1748]
## I'm submitting a...
* Bug report 

## Current behavior
When the selected date is today and then we click the "Today" button, the popup of the DatePicker does not close.

## Minimal reproduction of the problem with instructions

Check the following video demonstrating the issue:
[https://www.screencast.com/t/inRgXMY7Ww](https://www.screencast.com/t/inRgXMY7Ww)

**Comment by ipeshev** [comment]
Fix available in [latest development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.5.2
https://stackblitz.com/edit/angular-cawbcp?file=app/app.component.ts
