### ISSUE TITLE
Add month labels to Multi-View calendar 

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1749]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Setting the number of views to 2 or more makes it hard to distinguish which month is which.
![image](https://user-images.githubusercontent.com/247917/44460072-78bcdc80-a614-11e8-9d67-f31e015dba45.png)

## Expected behavior
Each month should be labelled clearly.

## Minimal reproduction of the problem with instructions

1. Open the [Multiple Views](https://www.telerik.com/kendo-angular-ui/components/dateinputs/multiviewcalendar/multiple-views/) documentation page.
1. Set the number of months to 4

**Comment by JoomFX** [comment]
This is implemented in [this PR](https://github.com/telerik/kendo-angular-dateinputs/pull/369).

**Comment by JoomFX** [comment]
implemented in https://github.com/telerik/kendo-angular-dateinputs/pull/369
