### ISSUE TITLE
Allow elements within the dialog to take focus when dialog is opened.

### ISSUE THREAD

**Issue by rkonstantinov** [telerik/kendo-angular#1753]
## I'm submitting a...

* Suggestion for improvement  

Allow elements within the dialog to take focus when dialog is opened.
For example having an edit form in which the first input should be focused when the dialog is shown.

**Comment by uuggene** [comment]
Can you add an option (or make it by default) not to focus dialog if any child in dialog focused already?

**Comment by dtopalov** [comment]
Available in v3.12.0

https://www.telerik.com/kendo-angular-ui/components/dialogs/api/DialogComponent/#toc-autofocusedelement
