### ISSUE TITLE
Using format property of kendo-grid-column in ng-template?

### ISSUE THREAD

**Issue by NiceStepUp** [telerik/kendo-angular#1754]
## I'm submitting a...
* Suggestion for improvement  

`kendo-grid-column` has a great column property 'format'. [And it works perfectly.](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/)

```<kendo-grid [data]="gridData">
    <kendo-grid-column field="UnitPrice" title="Unit Price" format="{0:n0}">
        <ng-template kendoGridCellTemplate format="{0:n0}" let-dataItem>
            <a href="#" class="badge badge-info">{{ dataItem?.UnitPrice }}</a>      
        </ng-template>
     </kendo-grid-column>
     <kendo-grid-column field="UnitPrice" title="Unit Price" format="{0:n0}">         
     </kendo-grid-column>
</kendo-grid>
```

What I need is to add anchor tag and use format property of kendo-grid-column. So I've added ng-template to kendo-grid-column:

```
<kendo-grid-column field="UnitPrice" title="Unit Price" format="{0:n0}">
    <ng-template kendoGridCellTemplate format="{0:n0}" let-dataItem>
        <a href="#" class="badge badge-info">{{ dataItem?.UnitPrice }} </a>
    </ng-template>
</kendo-grid-column>
```
However, `format="{0:n0}` is not working in ng-template:

```
<ng-template kendoGridCellTemplate format="{0:n0} let-dataItem>
    <a href="#" class="badge badge-info">{{ dataItem?.UnitPrice }} </a>
</ng-template>

```
[I've created an example to show what I have.](https://stackblitz.com/edit/angular-tftp1d?file=app/app.component.ts)

Is it possible to use format property of kendo-grid-column in ng-template?

**Comment by danielkaradachki** [comment]
You can use the [Internationalization pipes](https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/pipes/) to format the values in the template:
https://stackblitz.com/edit/angular-tftp1d-zo3rbz?file=app/app.component.ts
