### ISSUE TITLE
Kendo UI dropdown angular 4 - add new item option not available. 

### ISSUE THREAD

**Issue by SatishKura** [telerik/kendo-angular#1755]
Hi , Can we have "Add New Item" option in kendo dropdown control with angular 4 / 2 version . as we have it for angular 1 .

https://demos.telerik.com/kendo-ui/dropdownlist/addnewitem

thanks,
satish.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration. If you want to see this as built-in feature then create a feature request in our [uservoice forum](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback).
