### ISSUE TITLE
Multi-axis Chart Documentation Error

### ISSUE THREAD

**Issue by kdubious** [telerik/kendo-angular#1756]
## I'm submitting a Documentation Bug

[Multi-axis Chart Example](https://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/axes/#toc-multiple-categorical-chart-axes)

* Documentation issue 

## Current behavior

The multi axis example is not actually pegging data to the right axis

## Expected behavior

The multi axis example should be pegging data to the right axis

## Minimal reproduction of the problem with instructions

View the example at: [Multi-axis Chart Example](https://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/axes/#toc-multiple-categorical-chart-axes).
The MPG data uses the wrong axis.

The fix is:
Add `[axis]="item.axis"` to:
`<kendo-chart-series-item`

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by tsvetomir** [comment]
Fixed in the [develop channel](https://www.telerik.com/kendo-angular-ui-develop/components/charts/chart/elements/axes/#toc-multiple-categorical-chart-axes), will be published with the next update.
