### ISSUE TITLE
The page numbers and page size drop-down are not labelled

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1764]
## I'm submitting a...

* Bug report 

## Current behavior
* The pager numeric buttons will simply read as numbers to screen readers.
* The page-size drop-down lacks any title

## Expected behavior
* Numeric buttons should read "Page #" when clicked.
* The page-size drop-down should be labelled as "Items per page"

## Minimal reproduction of the problem with instructions
1. Start a screen reader, e.g. JAWS, NVDA
1. Open https://angular-r1nmfr.stackblitz.io
1. Click on the pager numeric buttons. Only the number is read out, e.g. "Four Link".
1. Click on the page size drop-down. Only the numeric value is read out.

**Comment by tsvetomir** [comment]
Fixed in the latest [development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the Grid.

**Comment by ipeshev** [comment]
Fixed in v3.8.0-dev.201810090842

**Comment by danielkaradachki** [comment]
Fixed in 3.8.0
