### ISSUE TITLE
When is support for rxjs 6 planned?

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#1768]
## I'm submitting a...

* Suggestion for improvement  

## Current behavior

rxjs-compat package is required currently for KendoUI packages

## Expected behavior

Use KendoUI without rxjs-compat

## Environment

Package versions:

```
+-- @progress/kendo-angular-charts@3.2.1
+-- @progress/kendo-angular-dateinputs@3.4.1
+-- @progress/kendo-angular-intl@1.4.1
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-scrollview@2.0.1
+-- @progress/kendo-date-math@1.2.0
+-- @progress/kendo-drawing@1.5.6
+-- @progress/kendo-theme-default@2.54.0
```

System:
- TypeScript version: 2.7
- Node version: 8.11.3
- Platform:  Windows

**Comment by danielkaradachki** [comment]
The packages will be updated not to require rxjs-compat once Angular 5 is no longer supported:

https://angular.io/guide/releases#support-policy

Check [this](https://github.com/telerik/kendo-angular/issues/1568) thread for more detailed information.
