### ISSUE TITLE
The value of a masked textbox is concatenated on both sides with spaces

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1769]
## I'm submitting a...
* Bug report 

## Current behavior
If I enter the digit 6 in the middle of a masked textbox with mask="999999" , the value of the textbox becomes "  6   ".

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-4hnzjt-hn6wyy?file=app/app.component.ts](https://stackblitz.com/edit/angular-4hnzjt-hn6wyy?file=app/app.component.ts)

## Workaround
We could use **[(ngModel)]="value"** to bind the value of the maskedtextbox instead of **[(value)]="value"**

We could also set **promptPlaceholder="_"**:

>             <kendo-maskedtextbox
>                 [includeLiterals]="includeLiterals"
>                 [(value)]="value"
>                 [mask]="mask"
>                 promptPlaceholder="_">
>            </kendo-maskedtextbox>

**Comment by acohenOT** [comment]
The min repro isn't quite right as it has the workaround built-in (promptPlaceholder is set)

**Comment by danielkaradachki** [comment]
The problem occurs because the two-way value binding sets the value back to the maskedtextbox and there is no way for it to determine if the spaces represent the promptPlaceholder or valid for the used masked value. We will add a note to the documentation that the promptPlaceholder should be changed in such scenarios.

**Comment by danielkaradachki** [comment]
The documentation has been updated:
https://www.telerik.com/kendo-angular-ui-develop/components/inputs/maskedtextbox/masks/
