### ISSUE TITLE
Item stales when ngModel is updated from code

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1770]
## I'm submitting a...

* Bug report 

## Current behavior
When ngModel is updated from component's code , newly added items can't be deleted ( only by input X click ).
## Expected behavior
Newly added items should not be staled.
## Minimal reproduction of the problem with instructions
1. Open this [stackblitz sample](https://stackblitz.com/edit/angular-hbqcnf)
2. Click "Add value 'Tennis'"
3.Try to delete newly added item

## Environment

Package versions:

```
broken in v3.0.3, works in v3.0.2
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by slaptev** [comment]
Also item that is added from code into ngModel - has no selection in a drop down list of a multiselect component.

**Comment by dimitar-pechev** [comment]
The issue has been resolved and is available in the [Development Build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the kendo-angular-dropdowns package.

**Comment by dimitar-pechev** [comment]
The fix is released in v3.2.0 of the `@progress/kendo-angular-dropdowns` package.
