### ISSUE TITLE
How to show Kendo-chart-title in new line

### ISSUE THREAD

**Issue by amitdwivedi20** [telerik/kendo-angular#1772]
## I'm submitting an
 
Issue
 

## Current behavior

I am trying to display title based on the value received from the backend. When text value is small it fits properly in the chart area. But when large text value is coming from backend, it gets hidden.

Is there any way we can push it to a new line when large text value is returned from the server.

I am aware of \n which moves the text to a new line. But my data is dynamic so I am not sure when to add \n. 

One way I am thinking is to count the length of string and add '\n' not sure if this will be a right approach.

Any help will be highly appreciated.

Stackblitz for the issue: https://stackblitz.com/edit/angular-aqdtsd?file=app/app.component.ts
StackOverflow : https://stackoverflow.com/questions/52168689/how-to-show-kendo-chart-title-in-new-line

## Environment

Package versions:
    "@angular/animations": "^6.0.9",
    "@angular/common": "^6.0.9",
    "@angular/compiler": "^6.0.9",
    "@angular/core": "^6.0.9",
    "@angular/forms": "^6.0.9",
    "@angular/http": "^6.0.9",
    "@angular/platform-browser": "^6.0.9",
    "@angular/platform-browser-dynamic": "^6.0.9",
    "@angular/platform-server": "^6.0.9",
    "@angular/router": "^6.0.9",
    "@progress/kendo-angular-buttons": "^4.1.2",
    "@progress/kendo-angular-charts": "^3.3.2",
    "@progress/kendo-angular-dateinputs": "^3.4.4",
    "@progress/kendo-angular-dialog": "^3.6.2",
    "@progress/kendo-angular-dropdowns": "^3.0.2",
    "@progress/kendo-angular-excel-export": "^2.1.1",
    "@progress/kendo-angular-grid": "^3.6.0",
    "@progress/kendo-angular-inputs": "^3.2.0",
    "@progress/kendo-angular-intl": "^1.4.1",
    "@progress/kendo-angular-l10n": "^1.2.0",
    "@progress/kendo-charts": "^1.11.2",
    "@progress/kendo-data-query": "^1.4.0",
    "@progress/kendo-drawing": "^1.5.7",
    "@progress/kendo-theme-default": "^2.54.1",
    "angular": "^1.6.8",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.0",
    "intl": "^1.2.5",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "upgrade-angular": "^0.1.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"

Browser:

- Chrome (desktop) version Version 68.0.3440.106 (Official Build) (64-bit) 
- IE version 11.0.9600.19101

System:
TypeScript version: 2.7.2
Node version: 10.6.0
Npm version : 6.1.0
Platform: Windows

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
