### ISSUE TITLE
Scrollbar is scrolled to top when selecting any item of PanelBar

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1775]
## I'm submitting a...
* Bug report 

## Current behavior
When selecting any element of a PanelBar the parent div element is scrolled to top only in IE. 

## Minimal reproduction of the problem with instructions
Check the following example in IE 11:
[https://stackblitz.com/edit/angular-erxd4k-spxw8e?file=app/app.component.ts](https://stackblitz.com/edit/angular-erxd4k-spxw8e?file=app/app.component.ts)

1. Scroll to the bottom of the div element, that holds the PanelBar.
2. After selecting "Trigger Games" (or any of the items of the PanelBar), the scrollbar is scrolled to top

## Environment

Browser:
- IE version 11

**Comment by ipratyushks** [comment]
I am also facing this issue, has Telerik resolved this issue yet?
