### ISSUE TITLE
ComboBox does not recognize a value when it is not present in the data

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1777]
When the ComboBox is bound to asynchronous data and value-bound to an object (no allowCustom and valuePrimitive are false), the value is still not recognized even though the component has all required information to render the textField properly.

It would be a nice enhancement to introduce support for such scenarios, as the more intuitive behavior would be the component to be value-bound properly and the text field to be extracted from the provided object value.

Internal reference: Ticket ID 1341271

**Comment by dimitar-pechev** [comment]
Not implementing, as the change could cause confusing component behavior at times. Closing in favor of #2090, where the reasoning behind this decision is explained.
