### ISSUE TITLE
autoFitColumns(): Need an event to know when to call it

### ISSUE THREAD

**Issue by kdubious** [telerik/kendo-angular#1779]
## I'm submitting a...
* Bug report 

## Current behavior
Calling `autoFitColumns()` immediately after setting the array used as the value for the `[kendoGridBinding]` binding is too soon.

## Expected behavior
There should be an event raised when the grid has finished applying the data from the `[kendoGridBinding]`

**Comment by danielkaradachki** [comment]
The rendering is performed by angular you can use its hooks (AfterViewChecked or NgZone.onStable) to call the method after the grid is rendered:
https://stackblitz.com/edit/angular-6ozq9h?file=app/app.component.ts
