### ISSUE TITLE
Navigation on complex page with grid fails

### ISSUE THREAD

**Issue by AkunaMatata** [telerik/kendo-angular#1782]
## Navigation on complex page with grid fails
about navigation on complex page with grid
When I need to implement sections with keyboard navigation I use tabindex for ordering those groups.
Unfortunately when grid  retrieve focus or cell gets focus by code further navigation is broken.
https://stackblitz.com/edit/angular-dxgsyf?file=app/app.component.ts

Current behavior:
If you don't set attr and focus on grid then it becames active the very last on the page;
if you set tabindex and focus or focusout  then it disappears. Also any attemptto set focus by code on focusout fails (console shown appropriate element as active by neither navigation nor visual styles are applied)

Expected:
navigation should work throw all elements with tab index; at least element.focus() should work .

Browser:

- Chrome (desktop) version 68

Note: example is just about  added several controls with tabindex to default kendogridFocusable example, no any special requirements.

**Comment by tsvetomir** [comment]
If I get this correctly, you'd like to set a tab index on the Grid. Currently, we always uses tab index 0 for the focusable element(s). I suppose we can change that to be the tab index assigned to the Grid, but some research is required.

> If you don't set attr and focus on grid then it becames active the very last on the page;

This is normal, the WAI-ARIA Authoring practices [warn about](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_between) using positive tab index as it will take priority over focusable elements with no tab index.

**Comment by AkunaMatata** [comment]
You understand it partially correct.
Also is here any workaround to set focus outside the grid from the code? As you can see from example, element.focus() doesn't work if current focus in inside grid

**Comment by dtopalov** [comment]
Demand to be tracked in the following Feedback portal item:

https://feedback.telerik.com/kendo-angular-ui/1544667-grid-add-an-option-for-setting-the-tabindex-in-a-navigable-grid
