### ISSUE TITLE
Can't set "callout" property via TooltipSettings

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1785]
## I'm submitting a...

* Bug report 

## Current behavior
Can't set "callout" property via TooltipSettings

## Expected behavior
It should be set via TooltipSettings as describer in [this article](https://www.telerik.com/kendo-angular-ui/components/tooltip/api/TooltipSettings/). The article itself need improvement.
This is a good candidate for E2E test !!!
## Minimal reproduction of the problem with instructions
1.Open this [stackblitz sample](https://stackblitz.com/edit/angular-7jstrz?file=app/app.component.ts)
2.Hover the button
3.Tooltip has callout arrow

## Environment

Package versions:

```
broken in v1.0.0
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Shipped in v1.0.1
