### ISSUE TITLE
SeriesDefaultsLabels and SeriesLabels are missing the rotation property

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1787]
It is working as expected, but is missing from the respective documentation API pages:

[https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesDefaultsLabels/](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesDefaultsLabels/)

[https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesLabels/](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesLabels/)

**Comment by danielkaradachki** [comment]
Fixed in 3.3.3.
