### ISSUE TITLE
Using *ngIf on a SplitterPane throws an error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1788]
## I'm submitting a...
* Bug report 

## Current behavior
When we use *ngIf on a SplitterPane, we get the following error:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '-ms-flex-order: undefined'. Current value: '-ms-flex-order: 0'.

If the application is run in prod mode, the error is not thrown.

## Minimal reproduction of the problem with instructions

Check the following stack blitz example and inspect the browser's console:
[https://stackblitz.com/edit/angular-6srugv-hfztpg?file=app%2Fapp.component.html](https://stackblitz.com/edit/angular-6srugv-hfztpg?file=app%2Fapp.component.html)

**Comment by ipeshev** [comment]
There is a pending fix available in [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)  v3.2.0-dev.201810101229

**Comment by danielkaradachki** [comment]
Fixed in 3.2.0
