### ISSUE TITLE
Series Labels do not display when chart type is bullet

### ISSUE THREAD

**Issue by damdave1** [telerik/kendo-angular#1789]
## I'm submitting a...
* Bug report 

## Current behavior
series labels for the currentField and target do not appear for chart type bullet.  

## Expected behavior
labels should appear

## Minimal reproduction of the problem with instructions
I've modified a demo to reproduce the behavior

https://angular-8myinb.stackblitz.io

**Comment by danielkaradachki** [comment]
The bullet chart does not currently support labels. I can suggest to submit a feature request at our [uservoice forum](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback).
