### ISSUE TITLE
Need to avoid the column data to get trim automatically

### ISSUE THREAD

**Issue by patelmurtuza** [telerik/kendo-angular#1790]
Hi,

I get my grid columns data from stored procedure with white spaces at the begning of the column value.
e.g. "   MyCellValue" but kendo UI grid is automatically trimming the prefix white spaces from the cell value.
Can some one help me out to avoid the white space while binding the data to grid.

Thanks and regards
Murtuza

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
