### ISSUE TITLE
GridComponent.autoFitColumns does not handle hidden columns as expected

### ISSUE THREAD

**Issue by revov** [telerik/kendo-angular#1794]
## I'm submitting a...
  * Bug report

## Current behavior
Calling `GridComponent.autoFitColumns()` on a fresh grid [1] with hidden columns leads to an unexpected behavior - if we proceed to show the hidden columns after the autofit they will have 0 width and will be practically invisible.

## Expected behavior
`GridComponent.autoFitColumns()` should either "ignore" hidden columns when doing it's magic or set their width properly even when they are not visible. Otherwise it leaves you in a position where you can't rely on `autoFitColumns` (when you have columns hidden by default) or you have to explicitly set default width for all of your columns.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ph8bdl?file=app%2Fapp.component.ts

## Additional notes:
[1] - If you call `GridComponent.autoFitColumns()` when a column was hidden after `autoFitColumns` was called at least once the column is unaffected and persists its last width (from when it was visible).

**Comment by danielkaradachki** [comment]
Hidden columns are ignored by the autoFitColumns method but in order for the widths to applied the grid needs to set width to the table equal to the sum of the column width. The width is without the hidden column and thus the column will not be visible once hidden is set to true. You can either set initial width to the column:
https://stackblitz.com/edit/angular-ph8bdl-xijxm8?file=app/app.component.ts
or call the autoFitColumns method after chaging the hidden state.
