### ISSUE TITLE
The listener on document click cannot be removed if Grid display in the page

### ISSUE THREAD

**Issue by RonnyRen** [telerik/kendo-angular#1796]
I want to implement a function like downdroplist. When the dropdown items display, add a listener (document : click) that when user click outside of dropdownlist, the dropdown items disappear. Then remove the listener to avoid unused listen. Since this component works as dropdownlist that it will be displayed multiple times in one page and it may be released and re-generated, removing the listener is necessary, otherwise, it would lead to performance issue.
However, I found that when there is Grid display in the page, it could not work as expect. Could you please help provide a workaround?

I wrote an example: (Angular 5.0.2 and Kendo-Grid: 3.5.0)
 https://stackblitz.com/edit/angular-502-grid
Note: I also did try with different versions of Kendo-Grid (1.7.2 and 2.1.3), and they had the same issue.

Case 1: (unexpect result)
Steps:
1. Open Developer Tool (F12)
2. Click button 'Add Handler'
3. Click any area in the document
4. Click button 'Unbind Handler'
5. Click any area in the document many times
Check the console output, you can find output from console as following:
![image](https://user-images.githubusercontent.com/33855404/45674154-53bb6c80-bae1-11e8-85b1-659b20879b71.png)
**Note: The method that remove the listener was called, however, there is still new output from console.**

Case 2: (correct result)
Steps:
1. Open Developer Tool (F12)
2. Comment out code related to kendo-grid in file app.component.html
3. Refresh the preview window through clicking refresh icon as below
![image](https://user-images.githubusercontent.com/33855404/45674527-28854d00-bae2-11e8-9c3e-fd77a0721bf1.png)
4. Click button 'Add Handler'
5. Click any area in the document
6. Click button 'Unbind Handler'
7. Click any area in the document many times
Check the console output, you can find output from console as following: 
![image](https://user-images.githubusercontent.com/33855404/45674650-62eeea00-bae2-11e8-9465-2383e7d0f82a.png)
**Note: When the listener was removed, there was no new output from console.**

**Comment by danielkaradachki** [comment]
This is cause by a [bug](https://github.com/angular/angular/issues/20532) in angular that was fixed in 5.1.0 and later:
https://stackblitz.com/edit/angular-502-grid-d8farq?file=src/app/app.component.html
