### ISSUE TITLE
kendo grid edit row 

### ISSUE THREAD

**Issue by mudupalli** [telerik/kendo-angular#1797]
I am using kendo grid for edit, cancel, delete a row. I have my search box to filter rows on the kendo grid. Once rows are filtered, say to 4, clicking on edit for row 2, throws error in developer tools.
args.rowIndex is showing 60, instead of 1, so var dataItem is undefined and formGroups is also undefined.
Error says Cannot read property 'value' of undefined at line dataItem = formGroup.value;
I am using @progress/kendo-angular-grid": "^3.5.0
Please let me know how to fix this?

GridComponent.prototype.emitCRUDEvent = function (args) {
        var action = args.action, rowIndex = args.rowIndex, formGroup = args.formGroup;
        var dataItem = this.view.at(rowIndex - this.skip);
        if (action !== 'add' && !dataItem) {
            dataItem = formGroup.value;
        }

**Comment by tsvetomir** [comment]
This issue tracker is for reporting bugs with the components. Please, file a [support ticket](https://www.telerik.com/account/support-tickets/available-support-list) for assistance with your scenario.

**Comment by tobkoc** [comment]
this is bug, same as https://github.com/telerik/kendo-angular/issues/1752

**Comment by ironicicon** [comment]
HI @mudupalli was your issue/ticket resolved? I am having a similar issue in my side as well. version : 3.6.1

**Comment by mudupalli** [comment]
Yes, I had to apply filters to individual columns.
public onInput(filterText) {
      this.onStateChange({...this.gridState, filter: {
        logic: 'and',
        filters: [{
          field: 'ProductName',
          operator: 'contains',
          value: filterText
        }, {
field: 'UnitPrice',
operator: 'gte',
value: +numericInput // convert the input string value to number unless you are using for example a NumericTextbox component instead of a regular input
}]
}})
}
