### ISSUE TITLE
kendo-numerictextbox IE11

### ISSUE THREAD

**Issue by slewis30328** [telerik/kendo-angular#1798]
The kendo-numerictextbox component on IE11 does not show the spin buttons with the bootstrap theme.  Works fine on Chrome.  I'm using kendo-theme-bootstrap build 2.14.0.

**Comment by danielkaradachki** [comment]
Could you provide a runnable sample that replicates the issue? The arrows are visible with the bootstrap theme at least on my side here:
https://stackblitz.com/edit/angular-zraev7?file=index.html

**Comment by dtopalov** [comment]
Also make sure to enable/uncomment IE in the 'browserlist' file.

**Comment by slewis30328** [comment]
Adding a browserlist file to my project and un-commenting the IE line fixed the problem.  Thanks for your help.   On Wednesday, September 19, 2018, 10:42:58 AM EDT, Dimiter Topalov <notifications@github.com> wrote:  
 
 Also make sure to enable/uncomment IE in the 'browserlist' file.
