### ISSUE TITLE
autofitColumns() behaves improper

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1800]
## I'm submitting a...

* Bug report 

## Current behavior
There are a few undesired effects, when calling the autofitColumns() functions of a grid that is filterable.

When there is no data in the grid and we call the autofitColumns() function, the grid's columns get weirdly resized. 

When there is data in the grid and we call the autofitColumns() function multiple times, the columns' widths get resized.

If we set the width input property of the columns and then call the autofitColumns() function, the widths of the columns will not be the same as if the grid was not filterable.

## Minimal reproduction of the problem with instructions
Check the following examples demonstrating the three reported undesired effects:
[https://stackblitz.com/edit/angular-xsez53-5ngrot?file=app/app.component.ts](https://stackblitz.com/edit/angular-xsez53-5ngrot?file=app/app.component.ts)

1. Click "Auto Fit Columns" button 2 - 3 times.

and:
[https://stackblitz.com/edit/angular-xsez53-ogkfnm?file=app/app.component.ts](https://stackblitz.com/edit/angular-xsez53-ogkfnm?file=app/app.component.ts)

1. Click "Auto Fit Columns" button 2 - 3 times.

and:
[https://stackblitz.com/edit/angular-xsez53-pqvner?file=app/app.component.ts](https://stackblitz.com/edit/angular-xsez53-pqvner?file=app/app.component.ts)

1. Click "Auto Fit Columns" button.
2. If the grid is not filterable, the widths of the columns would be properly set after calling the autofitColumns() function.

**Comment by danielkaradachki** [comment]
Fixed in 3.8.0
