### ISSUE TITLE
The top and left attribute values of the kendo window are invalidated

### ISSUE THREAD

**Issue by GavinEnjoy2017** [telerik/kendo-angular#1802]
The top and left attribute values of the kendo window are invalidated. Drag the window window, then minimize the window change browser size, re-bind the top and left values, and then zoom in the window window. The top and left values are still dragged. Top, left value, not the value of the rebind

**Comment by Raisolution** [comment]
Hi @GavinEnjoy2017,

Please provide a runnable example and list of steps to follow in order to reproduce the issue.
