### ISSUE TITLE
Setting min and max of the TimePicker throws error in develop mode

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1803]
## I'm submitting a...

* Bug report 

## Current behavior
When setting the min input property of the TimePicker to be a date which time is PM and then setting the max input property to be a later date with any time AM, the TimePicker throws the following error:

>  Error: The max value should be bigger than the min.

The issue is observed only in dev mode. The issues is not present if the app is run in prod mode.

## Minimal reproduction of the problem with instructions
Check the following example:

[https://stackblitz.com/edit/angular-5uswek?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-5uswek?file=app%2Fapp.component.ts)

**Comment by danielkaradachki** [comment]
Setting min time after max time is not supported. Thus the component throws error.

**Comment by jayordway** [comment]
They should at least be allowed to be equal though...

**Comment by danielkaradachki** [comment]
@jayordway 

The timepicker seems to work with equal min and max values:

https://stackblitz.com/edit/angular-5uswek-j9sf4b?file=app/app.component.ts

Am I missing something?

**Comment by jayordway** [comment]
Actually I may of been referring to the date picker

**Comment by danielkaradachki** [comment]
Seem to also work with the datepicker:

https://stackblitz.com/edit/angular-jdflgk?file=app/app.component.ts
