### ISSUE TITLE
Different between all.css and button scss

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#1804]
## I'm submitting a...
* Bug report 

## Current behavior
I have the kendo-theme-default package installed.
When i look at the file all.css there are the styles with -ms-flexbox and -ms-flex:
```
.k-button-group-stretched{
   display:-ms-flexbox;
   display:flex
}

.k-button-group-stretched .k-button {
    display:inline-block;
    -ms-flex:1 1 0px;
    flex:1 1 0;
    overflow:hidden;
    text-overflow:ellipsis;
}
```

In the scss/button/_layout.scss the styles has no -ms-:
```
    .k-button-group-stretched {
        display: flex;

        .k-button {
            display: inline-block;
            flex: 1 1 0;
            overflow: hidden;
            text-overflow: ellipsis;

            > .k-icon {
                vertical-align: text-bottom;
            }
        }
    }
```

## Expected behavior

I using the scss styles in my project and have the following problem:
When i use a buttongroup component with [width]="'100%'", this works in chrome (the buttongroup are stretched). But it don't works with IE 11 (the buttongroup are not stretch).

Is there a reason for the different or is this a bug?

## Environment

Package versions:

```
+-- @angular-devkit/build-angular@0.7.4
+-- @angular/animations@6.1.3
+-- @angular/cli@6.1.4
+-- @angular/common@6.1.3
+-- @angular/compiler@6.1.3
+-- @angular/compiler-cli@6.1.3
+-- @angular/core@6.1.3
+-- @angular/forms@6.1.3
+-- @angular/http@6.1.3
+-- @angular/platform-browser@6.1.3
+-- @angular/platform-browser-dynamic@6.1.3
+-- @angular/router@6.1.3
+-- @fortawesome/fontawesome-free@5.2.0
+-- @hico/ng-core-utils@1.5.2
+-- @hico/ng-shared-utils@1.10.2
+-- @hico/ng-theme-default@1.3.0
+-- @ngx-translate/core@10.0.2
+-- @ngx-translate/http-loader@3.0.1
+-- @progress/kendo-angular-buttons@4.1.3
+-- @progress/kendo-angular-dateinputs@3.4.4
+-- @progress/kendo-angular-dropdowns@3.0.3
+-- @progress/kendo-angular-excel-export@2.1.1
+-- @progress/kendo-angular-grid@3.6.1
+-- @progress/kendo-angular-inputs@3.2.1
+-- @progress/kendo-angular-intl@1.5.0
+-- @progress/kendo-angular-l10n@1.2.0
+-- @progress/kendo-angular-layout@3.1.1
+-- @progress/kendo-angular-tooltip@1.0.0
+-- @progress/kendo-angular-treeview@2.3.0
+-- @progress/kendo-data-query@1.4.1
+-- @progress/kendo-drawing@1.5.7
+-- @progress/kendo-theme-default@2.56.0
+-- @types/node@10.7.1
+-- bootstrap@4.1.3
+-- codelyzer@4.4.4
+-- core-js@2.5.7
+-- jquery@3.3.1
+-- ng2-signalr@6.1.0
+-- node-sass@4.9.3
+-- popper.js@^1.14.3
+-- rxjs@6.2.2
+-- rxjs-compat@6.2.2
+-- rxjs-tslint@0.1.5
+-- sass-lint@1.12.1
+-- signalr@2.3.0
+-- tslint@5.11.0
+-- typescript@2.9.2
+-- web-animations-js@2.3.1
`-- zone.js@0.8.26
```

Browser:

- Chrome (desktop) version 68
- IE version 11
- Edge version 42.17134.1.0

System:
- TypeScript version: 2.9.2 
- Node version: 6.4.0 
- Platform: Windows

**Comment by gyoshev** [comment]
Our build process that produces the Kendo UI themes adds the required prefixes through the Autoprefixer PostCSS plug-in. When compiling the SCSS files in a different setting, the same plug-in is needed to add the prefixes. Fortunately, the Angular CLI has support for Autoprefixer, and in order for it to produce prefixed properties, you need to [configure the browserslist it to target IE](https://github.com/angular/angular-cli/wiki/stories-autoprefixer#change-target-browsers-for-autoprefixer).
