### ISSUE TITLE
Grid: Locking/Unlocking Columns Fires No Events

### ISSUE THREAD

**Issue by ngiebel** [telerik/kendo-angular#1806]
## I'm submitting a...

* Bug report 
* Suggestion for improvement  

## Current behavior

No event to bind to when locking/unlocking columns, even though the column order changes as a result of the action, that event is not emitted either.

## Expected behavior

Some sort of event notifying of the column change.

**Comment by danielkaradachki** [comment]
Available in the latest [dev](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/) version.

**Comment by danielkaradachki** [comment]
Released in 3.8.0
