### ISSUE TITLE
Tabstrip - add horizontal scroll functionality

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#1807]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Expected behavior
Can you add horizontal scroll when there are many tabs just like ngZorro does?

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. For feature requests please use our [uservoice forum](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback). The specific feature has already been requested. You can vote for it and follow its progress [here](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/33629752-scrolling-tabstrip).
