### ISSUE TITLE
Documentation 404 error for kendo-angular-messages (globalisation)

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1809]
## I'm submitting a...
* Documentation issue

## Current behavior
404.

## Expected behavior
List of `kendo-angular-messages`.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/

![image](https://user-images.githubusercontent.com/1589573/45869699-6c4db000-bd89-11e8-8554-737463c66ef0.png)

**Comment by danielkaradachki** [comment]
Fixed on the [dev site](https://www.telerik.com/kendo-angular-ui-develop/components/globalization/localization/messages/#toc-using-the-message-service)
