### ISSUE TITLE
Add "autoClose" to Multiselect like in ng1 version

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#181]
Hi,

I can't see a possibility to add a "autoClose" Property to the Multiselect.

And could you add an example to the documentation with "select all" and "deselect all" Template header when this is possible?

**Comment by KirilNN** [comment]
Thanks for the suggestion for the autoClose property. The plans are for adding this option on a later stage when other dependent features will be added as well. 

As for the select all - it should be straight forward:

http://plnkr.co/edit/9eqVhVs6pTOFGRtSf3BE?p=preview

**Comment by jeromepl** [comment]
@KirilNN Is there anyway to achieve the same result as in your Plunker but inside of a Grid when editing cells (with a Template-driven form)?
I am trying to achieve a "Select All" option in a multiselect inside of an editable grid.

This is what my `kendoGridEditTemplate` currently looks like:
```html
<ng-template kendoGridEditTemplate
    let-dataItem="dataItem"
    let-formGroup="formGroup"
>
    <kendo-multiselect
        [data]="multiselectData"
        [formControl]="formGroup.get(multiselectField)"
     ></kendo-multiselect>
</ng-template>
```

**Comment by tsvetomir** [comment]
The autoClose option will ship with the next update of the DropDowns package.

@jeromepl Please [submit a support ticket](https://www.telerik.com/account/support-tickets/contact-support-team?pid=1800) with your inquiry. This issue tracker is for bug reports and feedback only.

**Comment by siyka-marinova** [comment]
Released in kendo-angular-dropdowns v.1.1.0

**Comment by squadwuschel** [comment]
@siyka-marinova what is released the new Property ?
