### ISSUE TITLE
Documentation: kendoNumber and default format value

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1812]
On page: https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/api/NumberPipe/

we see that format defaul value is:

> If no format is provided, the default short date format is used.

Why `date`?

we just would like to know default format value on numeric pipe.
Thanks.

**Comment by danielkaradachki** [comment]
Thanks for noticing this issue. We will fix it. By default the value is formatted as decimal number with the ["n"](https://github.com/telerik/kendo-intl/blob/develop/docs/num-formatting/index.md#standard) format.
