### ISSUE TITLE
[Mobile] groups drag and drop

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1815]
## I'm submitting a...
* Suggestion for improvement  

## Current behavior
When using grouping on a touch device, the grid's headers' texts are selected. This interferes with the selection of the group and dragging it to the groups header. 

## Minimal reproduction of the problem with instructions
Check the following example on a touch device:
[https://plnkr.co/edit/0XBfyUwdzrMrvMFPRNpk?p=preview](https://plnkr.co/edit/0XBfyUwdzrMrvMFPRNpk?p=preview)

## Workaround

We could add the following styles in order to disable the text selection in the headers of the grid:
>  .k-grid-header-wrap tr th{
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
  }

**Comment by ipeshev** [comment]
Fix available in [latest dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version.

**Comment by danielkaradachki** [comment]
Released in the latest theme and grid versions
