### ISSUE TITLE
Kendo pager

### ISSUE THREAD

**Issue by papushe** [telerik/kendo-angular#1816]
Kendo angular 5

can kendo pager stand alone without kendo grid?

I want to add the pager in my code without the grid component

**Comment by danielkaradachki** [comment]
The pager is not currently available as standalone component. The idea was previously suggested. You can vote for it and follow its progress in our uservoice forum on [this](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/17814475-pager-component) page.
