### ISSUE TITLE
Double-Click for TreeView triggert "selectionChange" twice.

### ISSUE THREAD

**Issue by eastjie** [telerik/kendo-angular#1817]
## I'm submitting a...
  
* Bug report 
* Suggestion for improvement  
 

## Current behavior
Double Click is not implemented OutOfBox for TreeView, so we have to build it with HTML Event in node template. But when user double clicked node, the event of "selectionChange" is invoked twice. We don't know, in which version is the event "selectionChange" changed. At the beginning, the "selectionChange" seems to be invoked only if user selects other nodes, so we had no conflict between event "selectionChange" and double click in early version.

## Expected behavior
We have expected that Double Click could be implemented OutOfBox. In our use case, DoubleClick is only to expand or collapse the selected node. If node is to be expanded, the new children will be fetched from service. It is the common use case to reload data only for this node. 

## Minimal reproduction of the problem with instructions
 
Here is [example](https://stackblitz.com/edit/angular-oq7wh6?file=app/app.component.ts) in stackblitz.

**Comment by danielkaradachki** [comment]
Thanks for the suggestion. We will consider exposing dblclick event.

**Comment by eastjie** [comment]
Thanks for your answer. Only some information, which we have met in our HTML DoubleClick by expanding tree.  If man double clicks the node more than once,  the exception is thrown:
"main.js:1 Uncaught TypeError: Cannot read property 'item' of null".

This problem should not be caused by two-way binding of "expandedKeys". 
Here is another [example](https://stackblitz.com/edit/angular-v76tj3?file=app/app.component.ts) in stackblitz. In the example, if only button "Expand/Collapse Id 2" is clicked, there is no problem. If node "Decor" is double clicked. The first time, no problem, the second, the third, the exception displays in console. It seems, "zone.js" hat detected something wrong.

Thank you very much.

**Comment by danielkaradachki** [comment]
Thanks, I was able to replicate the error and opened a separate [issue](https://github.com/telerik/kendo-angular/issues/new) for it.

**Comment by ipeshev** [comment]
Available in latest dev version - v2.5.0-dev.201811150640

**Comment by danielkaradachki** [comment]
Released in 2.5.0
