### ISSUE TITLE
Child PanelBarItem does not open  

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1819]
## I'm submitting a...

* Bug report 

## Current behavior
When using [expandMode]="'single'", child PanelBarItem's arrow icon is displayed as open, when it should be closed and the PanelBarItem does not open.  

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-n9mudz-o92uwm?file=app/app.component.ts](https://stackblitz.com/edit/angular-n9mudz-o92uwm?file=app/app.component.ts)

1. Open the "Projects" panelbar.
2. Open the child "Sales Forecasts" panelbar.
3. Open the "My Teammates" panelbar.
4. Open the "Projects" panelbar. Note the direction of the arrow on the right side of the "Sales Forecasts" panelbar (it is in the open position even though the "Sales Forecasts" panelbar is closed).
5. The "Sales Forecasts" panelbar cannot be opened.

**Comment by danielkaradachki** [comment]
Seems similar to https://github.com/telerik/kendo-angular/issues/1574. The same workaround is applicable.

**Comment by danielkaradachki** [comment]
Fix released in 3.3.0

https://stackblitz.com/edit/angular-n9mudz-ocnu1g?file=app/app.component.ts
