### ISSUE TITLE
MultiSelect Filtering Bug

### ISSUE THREAD

**Issue by shawnhancock** [telerik/kendo-angular#1820]
## I'm submitting a...

* Bug report 

## Current behavior

With the latest release, when using the MultiSelect with filtering, if you type something and choose the option it becomes selected which is correct. It doesn't however remove it from the list and you are able to type the same value again. It then creates the impression of a duplicate item in the input field.

## Expected behavior

When an item is selected after filtering, it is removed from the list and you cannot filter on it again unless you remove it as a selected option.

## Minimal reproduction of the problem with instructions

https://7urzzs.run.stackblitz.io
Filter any value, e.g. Albania. Then after it's selected, search for Albania again. It gives the impressions that it's been added multiple times to the input field.

**Comment by shawnhancock** [comment]
Also just noting that I've tested these versions and the above issue didn't happen in "3.0.2"
"@progress/kendo-angular-dropdowns": "3.0.2"
"@progress/kendo-angular-dropdowns": "3.0.3"
"@progress/kendo-angular-dropdowns": "3.1.0"

**Comment by dimitar-pechev** [comment]
@shawnhancock The filtering of the component data is handled by you, so you have to filter out the already selected items in your code. You can see an example [here](https://stackblitz.com/edit/angular-ytsrvf). 

The issue with duplicated tags added temporarily to the component value while filtering is resolved and is available in the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the kendo-angular-dropdowns package v3.2.0-dev.201810111406. 

Closing the issue as the reported bug is tracked in #1767.
