### ISSUE TITLE
Error on node click after item is expaned and collapsed

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#1821]
Example: https://stackblitz.com/edit/angular-ml5ehw?file=app/app.component.ts

To replicate expand and then collapse one of the items and then click on it.

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Fixed in 2.3.2
https://stackblitz.com/edit/angular-ml5ehw-bef66n?file=app/app.component.ts
