### ISSUE TITLE
Weekdays not aligned when using [weekNumber]="true"

### ISSUE THREAD

**Issue by timlestander** [telerik/kendo-angular#1824]
## Current behavior
When using [weekNumber]="true" the weekdays do not align properly in it's column. 

## Expected behavior
Horizontal alignment.

## Minimal reproduction of the problem with instructions
Here is the code while not working: https://j7ye7u.run.stackblitz.io
Here is the code with some simple changes that makes it work: https://angular-3ibqno.stackblitz.io

I suppose the width using em differs from the actual dates and the table header since the table header has font size 10px and the clickable dates have 14px.

## Environment

Browser:
- Chrome (desktop) Version 69.0.3497.100 (Official version) (64 bitar)

**Comment by siyka-marinova** [comment]
Fix for this bug is available in the latest package `@progress/kendo-angular-dateinputs v4.1.0`
(it was fixed back in `@progress/kendo-angular-dateinputs v3.5.4`)
