### ISSUE TITLE
Undesired effect when using a TreeView inside a PopUp component

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1826]
## I'm submitting a...
* Bug report 

## Current behavior
When adding a TreeView to the content of a PopUp and we expand/collapse some nodes of the TreeView, it is not displayed properly. 

## Minimal reproduction of the problem with instructions
Check the following example and expand and collapse some nodes of the TreeView:
[https://stackblitz.com/edit/angular-tdqw4x-ecsdgf?file=app/app.component.ts](https://stackblitz.com/edit/angular-tdqw4x-ecsdgf?file=app/app.component.ts)

**Comment by siyka-marinova** [comment]
FIxed in `kendo-angular-popup v3.0.4`
