### ISSUE TITLE
Dialog is not shown using DialogService in ErrorHandler

### ISSUE THREAD

**Issue by phucthaidoan** [telerik/kendo-angular#1828]
## I'm submitting a...

* Bug report 

## Current behavior

No dialog is shown. There is only overlay.
![image](https://user-images.githubusercontent.com/1305623/46521900-39d4a480-c8ab-11e8-9002-68d5f84eba7b.png)

## Expected behavior

The dialog should be shown as sample in this one https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/

## Minimal reproduction of the problem with instructions

1. Expectation sample: https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/
**MINIMAL DEMO**
1. https://stackblitz.com/github/phucthaidoan/dialog-error-handler

## Environment

Package versions:

```
+-- @angular-devkit/build-angular@0.6.8
+-- @angular/animations@6.1.7
+-- @angular/cli@6.0.8
+-- @angular/common@6.1.7
+-- @angular/compiler@6.1.7
+-- @angular/compiler-cli@6.1.7
+-- @angular/core@6.1.7
+-- @angular/forms@6.1.7
+-- @angular/http@6.1.7
+-- @angular/language-service@6.1.7
+-- @angular/platform-browser@6.1.7
+-- @angular/platform-browser-dynamic@6.1.7
+-- @angular/router@6.1.7
+-- @progress/kendo-angular-buttons@4.1.3
+-- @progress/kendo-angular-dialog@3.7.0
+-- @progress/kendo-angular-l10n@1.2.1
+-- @progress/kendo-theme-default@2.57.0
+-- @types/jasmine@2.8.8
+-- @types/jasminewd2@2.0.3
+-- @types/node@8.9.5
+-- codelyzer@4.2.1
+-- core-js@2.5.7
+-- error-stack-parser@2.0.2
+-- jasmine-core@2.99.1
+-- jasmine-spec-reporter@4.2.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@2.0.4
+-- karma-jasmine@1.1.2
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.3.2
+-- rxjs@6.3.2
+-- rxjs-compat@6.3.3
+-- ts-node@5.0.1
+-- tslint@5.9.1
+-- typescript@2.7.2
`-- zone.js@0.8.26
```

Browser:

- Chrome (desktop) version 69.0.3497.100 (Official Build) (64-bit)
- Firefox version 62.0 (64-bit)

System:
- TypeScript version: 2.9.1 
- Node version: v9.3.0  
- Platform:  Windows

**Comment by Raisolution** [comment]
Hi @phucthaidoan,

the reason for the observed behavior is that the Dialog is not opened inside the NgZone. This is expected, as internally we don't make any explicit checks for this, but rely that the API is invoked inside the zone. Here is [the updated version](https://stackblitz.com/edit/github-ifukj3?file=src%2Fapp%2Fexample%2Fexample.component.ts) of the provided example. I will also log that this should be documented better in the troubleshooting section.
