### ISSUE TITLE
The empty node will not be refreshed by expanding it again in TreeView

### ISSUE THREAD

**Issue by eastjie** [telerik/kendo-angular#1829]
## I'm submitting a...
 
* Bug report 

## Current behavior
When the node data is fetched from service, it may be empty at the beginning. If the node is added to the "expandedKeys", the callback method "children" is not invoked. The node data itself can not be refreshed until the browser or its parent node is loaded newly.

It seems that callback "hasChildren" is executed firstly and then "children", but without retrieving data from service, the "hasChildren" has only the old value.

## Expected behavior
Just like other no-empty node, the service data will be retrieved newly if it is added to "expandedKeys".

## Minimal reproduction of the problem with instructions

Here is [example](https://stackblitz.com/edit/angular-v76tj3-rhmst6?file=app/app.component.ts) in stackblitz.  The second node "Decor" can not be refreshed, if it has no children by initialization.

Thanks very much.

**Comment by danielkaradachki** [comment]
Not sure if I understand the issue but at least in the provided example hasChildren returns false for the Decor item even if it is added to the expandedKeys. If the function returns true then the children are shown as expected:
https://stackblitz.com/edit/angular-v76tj3-d9ssn1?file=app/app.component.ts

Am I missing something?

**Comment by eastjie** [comment]
You are right. I have misunderstanding about "hasChildren" and "fetchChildren". I've just thought that the parameter of "item" from "hasChildren" should always return the current data.  
With checking "this.expandedKeys.indexOf(item.id) >= 0", the problem can be solved easily. Thanks very much.  I change the issue and close it.
