### ISSUE TITLE
Split button triggers postback when used inside .NET applications

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#1830]
The template for the split button does not have 'type="button"' set to each button, so if used inside a .NET form, clicking it triggers a postback and causes the page to reload.

Any workarounds for this?

**Comment by gyoshev** [comment]
There is a pending fix for this on the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), version `4.2.0-dev.201810091340`.

**Comment by LaniMoo** [comment]
Great, thank you. Has the fix been applied to all button components missing “type=‘button’” or just the split button?

On Oct 10, 2018, at 8:22 AM, Alex Gyoshev <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a pending fix for this on the development channel<https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/>, version 4.2.0-dev.201810091340.

**Comment by dtopalov** [comment]
The button within the DropDownButton component already has type="button" applied, while all other buttons' markup is available to the developer to alter as necessary (as they are regular <button> elements with a kendoButton directive applied).

**Comment by LaniMoo** [comment]
Oh, okay! So it was just the spilt button that had the issue then. Thank you so much, all!

**Comment by tsvetomir** [comment]
Fixed in v4.2.0
