### ISSUE TITLE
Tree-view with checkboxes select node problem

### ISSUE THREAD

**Issue by Abdullah0991** [telerik/kendo-angular#1833]
## I'm submitting a...

* Regression report

## Current behavior
Tree-view component with check-boxes, when click on a node it not shown as selected, click twice and it shown as expected.

I got this problem after upgrading from v1.0.1. I use the latest version (2.3.2) and the problem is still exists.

This picture must clarify the problem: [problem preview](https://drive.google.com/open?id=1ghni_RRGjGPooX3t7ZB7F6wPDWakuWnL)

## Minimal reproduction of the problem with instructions

[stackblitz example](https://stackblitz.com/edit/angular-swgmun)

## Environment

Browser:
- Chrome (desktop) version 69.0.3497.100 (Official Build) (64-bit)
- Firefox version 62.0.3 (64-bit)

System:
- TypeScript: v2.6.2
- Node version: v8.11.3
- Platform:  Windows

**Comment by danielkaradachki** [comment]
The treeview from the example does not have selection enabled. Once enabled the selection appears to work correctly on my side - [screen cast](https://www.screencast.com/t/7yc7F1eOJ)
https://stackblitz.com/edit/angular-swgmun-cyjhuf?file=app/app.component.ts

**Comment by Abdullah0991** [comment]
Thanks @danielkaradachki 

I already enabled the selection. but I tried to delete the [isSelected] attribute and it does solve the problem. Here is the html:

```
<kendo-treeview [nodes]="TreeItems" textField="name" kendoTreeViewExpandable
                  [isChecked]="isItemChecked" kendoTreeViewSelectable
                  [expandBy]="'id'" [(expandedKeys)]="expandedKeys"
                  [hasChildren]="hasChildren" [children]="fetchChildren"
                  (selectionChange)="handleSelection($event)" [selectBy]="'id'"
                  (checkedChange)="handleChecking($event)" [(selectedKeys)]="selectedKeys"
                  [isSelected]="isItemSelected" #layers_tv id="layers_tv">
</kendo-treeview>
```

and the function to check if is node selected:

```
public selectedKeys: any[];
public isItemSelected = (_: any, index: string) => this.selectedKeys.indexOf(index) > -1;
```

How can I use the [isSelected] again?

**Comment by danielkaradachki** [comment]
Removing the kendoTreeViewSelectable directive and its corresponding inputs should resolve the problem:
https://stackblitz.com/edit/angular-swgmun-bhwpxd?file=app/app.component.ts
The problem will occur because both the custom handler and the directive will update the state.

**Comment by Abdullah0991** [comment]
Hi again @danielkaradachki 

Your answer did solve the problem but it causes another problem for me since the `selectedKeys` now is contains the `indices` not the `ids` of the nodes.

I found another solution and it does solve both problems. I didn't remove anything from the html but I change the `selectionChange` and `isSelected` handlers to use node `id` instead of `index`.

```
public isItemSelected = (item: any, index: string) => this.selectedKeys.indexOf(item.id) > -1;

public handleSelection({ item: any, index }: any): void {
    this.selectedKeys = [item.id];
}
```

Thanks @danielkaradachki .
