### ISSUE TITLE
DataSourceRequestState and DataStateChangeEvent errors in dotnet-angular demo project

### ISSUE THREAD

**Issue by crgolden** [telerik/kendo-angular#1835]
## I'm submitting a...
* Bug report

## Current behavior
Encountering multiple TypeScript errors when checking out the `Kendo UI for Angular - Binding to an ASP.NET Core service` sample project

## Expected behavior
Not encountering any TypeScript errors when checkout out the `Kendo UI for Angular - Binding to an ASP.NET Core service` sample project

## Minimal reproduction of the problem with instructions

1. Clone the `kendo-angular-demo-aspnetcore-data` project from GitHub (https://github.com/telerik/kendo-angular-demo-aspnetcore-data/)
2. Open `dotnet-angular.csproj` in Visual Studio 2017
3. Restore npm/Nuget packages
4. Open `fetch-data.component.ts`
5. Observe three TypeScript errors:
    1. Cannot convert type '`{skip: number,take: number}`' to type '`State & {aggregates?: AggregateDescriptor[]}`': Types '`{skip: number,take: number}`' and '`State & {aggregates?: AggregateDescriptor[]}`' are incompatible: constituent '`{aggregates?: AggregateDescriptor[]}`' of the target intersection type is not assignable to the source type
    2. Cannot convert type '`DataStateChangeEvent`' to type '`State & {aggregates?: AggregateDescriptor[]}`': Types '`DataStateChangeEvent`' and '`State & {aggregates?: AggregateDescriptor[]}`' are incompatible: constituent '`{aggregates?: AggregateDescriptor[]}`' of the target intersection type is not assignable to the source type
    3. Supplied parameters do not match any signature of call target: parameter type mismatch. Parameter '`state`' should have type assignable to '`DataSourceRequestState`', but it has type '`DataStateChangeEvent`'.

## Environment

Package versions:
```
+-- @angular-devkit/core@0.6.3
+-- @angular/animations@5.2.11
+-- @angular/cli@1.6.3
+-- @angular/common@5.2.11
+-- @angular/compiler@5.2.11
+-- @angular/compiler-cli@5.2.11
+-- @angular/core@5.2.11
+-- @angular/forms@5.2.11
+-- @angular/http@5.2.11
+-- @angular/language-service@5.2.11
+-- @angular/platform-browser@5.2.11
+-- @angular/platform-browser-dynamic@5.2.11
+-- @angular/platform-server@5.2.11
+-- @angular/router@5.2.11
+-- @nguniversal/module-map-ngfactory-loader@5.0.0
+-- @progress/kendo-angular-buttons@4.1.3
+-- @progress/kendo-angular-dateinputs@3.4.4
+-- @progress/kendo-angular-dropdowns@3.1.0
+-- @progress/kendo-angular-excel-export@2.1.2
+-- @progress/kendo-angular-grid@3.7.1
+-- @progress/kendo-angular-inputs@3.2.2
+-- @progress/kendo-angular-intl@1.5.0
+-- @progress/kendo-angular-l10n@1.2.1
+-- @progress/kendo-data-query@1.5.0
+-- @progress/kendo-drawing@1.5.7
+-- @progress/kendo-theme-default@2.57.0
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.5
+-- @types/node@6.0.118
+-- aspnet-prerendering@3.0.1
+-- bootstrap@3.3.7
+-- codelyzer@4.5.0
+-- core-js@2.5.7
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.4.3
+-- karma-jasmine@1.1.2
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.5.12
+-- ts-node@3.2.2
+-- tslint@5.7.0
+-- typescript@2.4.2
`-- zone.js@0.8.26
```

System:
- TypeScript version: 2.4.2
- Node version: 9.8.0
- Platform:  Windows

**Comment by dtopalov** [comment]
The updated latest versions of the Kendo UI for Angular sample applications are moved to new repositories:

https://github.com/telerik/kendo-angular/tree/master/examples

https://github.com/telerik/kendo-angular/tree/master/examples-standalone

This particular sample project is located at:

https://github.com/telerik/kendo-angular/tree/master/examples-standalone/aspnetcore-data

... and is running as expected on our end.

Can you please try to clone and run this version as described in the README file, and let us know whether you are still experiencing any issues?
