### ISSUE TITLE
Not able to provide day input with numpad on grid date filter 

### ISSUE THREAD

**Issue by kbuschgens** [telerik/kendo-angular#1839]
## I'm submitting a...

* Bug report 

## Current behavior

When having a date filter with format 'dd-MM-yyyy' in a grid-column, it's not possible to provide day input with your numpad (only arrow navigation works and the number 0).

## Expected behavior

I should be able to fill in a day with my numpad. 

## Minimal reproduction of the problem with instructions

1. Use filter="date" and format="{0: dd-MM-yyyy}" on a kendo-grid-column
2. Open the datepicker filter and start typing a date in the input field.

**Comment by kbuschgens** [comment]
Also the hours and minutes with format="{0: dd-MM-yyyy HH:mm}" aren't providable.

**Comment by danielkaradachki** [comment]
We will look into it Should be possible to avoid the issue by removing the space after the placeholder or by not using a format placeholder:
https://stackblitz.com/edit/angular-ufokms?file=app/app.component.ts

**Comment by kbuschgens** [comment]
@danielkaradachki removing the whitespace seems to avoid the issue, thanks!

**Comment by dimitar-pechev** [comment]
Fixed in the `@progress/kendo-angular-intl@2.0.1` package - a dependency of the DateInputs, responsible for date format parsing.
