### ISSUE TITLE
Load US format Calendar for Thai Culture in Angular 5

### ISSUE THREAD

**Issue by suraj-nitor** [telerik/kendo-angular#1842]
Hi Team,

I am facing one challenge with Kendo UI Grid Column Date Filter in Angular 5.

The challenge is with internationalisation with Kendo UI Grid. I am using **Thai Culture** for my application but for one specific scenario in which i have to use US calendar in my Kendo Grid Column Date Filter. 
 
Is there any property in the Date filter option available which i can use to load the US Calendar instead of Thai?

Please note: my entire application works on Thai culture but only Kendo Date Picker should be work on US culture. For other

Is there any workaround for this by which i can achieve my requirement.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
