### ISSUE TITLE
Menu doesn't close after click on item inside ItemContentTemplateDirective

### ISSUE THREAD

**Issue by sv0505** [telerik/kendo-angular#1843]
I use "@progress/kendo-angular-menu": "1.1.0" component.
I want to close the menu after clicking on an item inside ItemContentTemplateDirective
<kendo-menu [openOnClick]="{ toggle: 'click' }"> doesn't  help.

See example on stackblitz here:
https://www.telerik.com/kendo-angular-ui/components/menus/api/ItemContentTemplateDirective/

It was working in "@progress/kendo-angular-menu": "0.4.0",

**Comment by danielkaradachki** [comment]
The behavior is by design. You can bind a click handler and close the item with the [toggle](https://www.telerik.com/kendo-angular-ui/components/menus/api/MenuComponent/#toc-toggle) method if this is required in your scenario.

**Comment by sv0505** [comment]
I was trying to use this method before but I neglected "indices" and it didn't work.
Now, it is works.  Thanks.

```
import {Component,ViewChild} from '@angular/core';
import {MenuComponent} from '@progress/kendo-angular-menu';

@Component({
   selector: 'my-app',
   template: `
       <kendo-menu>
         <kendo-menu-item text="item2">
             <ng-template kendoMenuItemContentTemplate let-item="item" let-index="index">
                 <div style="padding: 10px;" (click)="this.close()">
                     My Content Template for: {{ item.text }} at index: {{ index }}
                 </div>
             </ng-template>
         </kendo-menu-item>
       </kendo-menu>
   `
})
export class AppComponent {
  @ViewChild(MenuComponent) menu: MenuComponent;
  close() {
    this.menu.toggle(false, '0');
  }
}
```
