### ISSUE TITLE
Kendo date-picker placeholder is not rendered properly if it contains a conditional text

### ISSUE THREAD

**Issue by hidegh** [telerik/kendo-angular#1847]
## I'm submitting a...
Bug report

## Current behavior
i have a placeholder set up with ngModel binding
the placeholder text is conditional based on a flag
even with flag turned on and no value in input, placeholder is not shown
when i enter then leave input, placeholder get's displayed
**seems the flag (b) change does not get's reflected inside the control**

same behaviour with {{ }}

see sample:
https://stackblitz.com/edit/kendo-datepicker-dynamic-placeholder-issue?file=app/app.component.ts

<kendo-datepicker [placeholder]="b ? 'conditional placeholder' : ''" [(ngModel)]="d">
<kendo-datepicker placeholder="{{b ? 'conditional placeholder' : ''}}" [(ngModel)]="d">

## Expected behavior
if there's no date selected, input should react to binding changes and display placeholder accordingly

## Minimal reproduction of the problem with instructions
Try stackblitz sample

**Comment by elena-gancheva** [comment]
Hi @hidegh, thanks for logging this issue. The fix is merged and will be available in the latest `dev` version of the package.

**Comment by ipeshev** [comment]
We need to get in account the special case when , the placeholder is empty string .

**Comment by hidegh** [comment]
@ipeshev assume empty string means nothing to display, so it's the same as no placeholder, right? at least the link with sample in my case does (should) work this way. the only issue was that when i changed the placeholder's value via binding, the refresh did not occure. if you wan't to check out the desired behaviour it's simple: press button, enter the datetime control, leave it and the newly assigned placeholder (or no placeholder in case of empty string) will be rendered (refreshed)

**Comment by elena-gancheva** [comment]
Hi @hidegh, could you please provide information what are your expectations about the behavior when binding `placeholder` property of a `kendo-datepicker` component. I am proposing this behavior:

- If you bind empty string `placehoder=""`, the input will be empty and the default input mask `month/day/year` will not be rendered;
**Example:** `<kendo-datepicker placeholder=""></kendo-datepicker>`
**Image:**  
![image](https://user-images.githubusercontent.com/8842674/47011443-a6249300-d14a-11e8-88db-c3d72406572c.png)



- If you have not given any `placeholder` property, the input will render the default input mask `month/day/year`;
**Example:** `<kendo-datepicker></kendo-datepicker>`
**Image:**
![image](https://user-images.githubusercontent.com/8842674/47011480-b9376300-d14a-11e8-9f63-ba0354c797c5.png)




- If you have dynamic binding: `[placeholder]="flag? 'a' : 'b'"`, the input will render the value, accordingly to the flag.
**Example:** `<kendo-datepicker [placeholder]="flag? 'flag is true' : 'flag is false'"></kendo-datepicker>`
**Image:**
![image](https://user-images.githubusercontent.com/8842674/47011505-cd7b6000-d14a-11e8-94e7-e1860fcdd430.png)
![image](https://user-images.githubusercontent.com/8842674/47011535-dc621280-d14a-11e8-9b20-dad673018b90.png)

Do these cases meet your needs?

**Comment by elena-gancheva** [comment]
@hidegh 
Thanks for your input. The fix is merged and will be available in the latest `dev` version.

**Comment by ipeshev** [comment]
@hidegh currently if we have empty string , the default mask is displayed ? Switching is working correct without need to focus-blur input.

**Comment by ipeshev** [comment]
Fix available in [latest development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by elena-gancheva** [comment]
Shipped with `v3.5.0` of the package.
