### ISSUE TITLE
MultiViewCalendar with "max" option set ignores the "views" option

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1848]
When the "max" option of the MultiViewCalendar is set to a date that is not far enough in the future such that there are "views" number of months between today and "max", the rendered views do not correspond to the value, set via the "views" option, and navigating back via the left arrow button is not possible:

[https://stackblitz.com/edit/angular-rgtdgf-1jjxjt?file=app/app.component.ts](https://stackblitz.com/edit/angular-rgtdgf-1jjxjt?file=app/app.component.ts)

Reported in Ticket ID: 1346275

**Comment by vinayakshukre** [comment]
Any clue about when this will be fixed ?

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dateinputs` **v3.5.5-dev.201901311329**.

**Comment by dimitar-pechev** [comment]
The fix is available in **v3.6.0**.
