### ISSUE TITLE
kendo-textbox-container floating labels doesn't render in datepicker

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1849]
## I'm submitting a...
* Bug report

## Current behavior
Floating label is always on top, never inside input element.

## Expected behavior
If date is not set, floating label is inside input, not on top of input.

![image](https://user-images.githubusercontent.com/1589573/46947631-b7eb3500-d07b-11e8-9763-822a17c49611.png)

## Minimal reproduction of the problem with instructions
[Plunkr](https://stackblitz.com/edit/angular-jheqsr?file=app%2Fapp.component.ts).

**Comment by MaklaCof** [comment]
Maybe related with #1847. There placeholder is not rendered and here floating labels.

**Comment by elena-gancheva** [comment]
Hi @MaklaCof, could you please describe the desired behavior of using `dateinput` component with `text-box-container`. How do you think the floating label should interact with the default input mask `month/day/year`,  in these cases:

- input is clicked and focused
- input is empty
- input has a value
- input is blurred

You can use as a reference this [stackblitz ](https://stackblitz.com/edit/kendo-angular-dateinput) example.

**Comment by elena-gancheva** [comment]
The fix is shipped with `3.5.3` version of the package.
Working example [here](https://stackblitz.com/edit/angular-7q5byh?file=app/app.component.ts).
