### ISSUE TITLE
Date and time filtering in a grid

### ISSUE THREAD

**Issue by reiseder** [telerik/kendo-angular#1850]
## I'm submitting a...
* Bug report
* Feature request

## Current behavior
The date filter on a grid column includes the time on an 'equal' operation thus showing only results at 00:00:00.

## Expected behavior
I would expect a 'date' filter to exclude the time on filtering equal dates, showing all entries from 00:00:00 to 23:59:59. Otherwise call it a 'datetime' filter to avoid confusion.

## Minimal reproduction of the problem with instructions
I changed some values of FirstOrderedOn in SampleProducts to different times on September 9th 1996. When you use the 'equal' date filter they don't show up. They will be visible with the 'gte' filter.

Stackblitz: https://stackblitz.com/edit/angular-ugs64j

Browser:
- Chrome (desktop) version 69.0.3497.100

System:
- TypeScript version: 2.9.2
- Node version: 10.5.0  
- npm version: 6.1.0
- Platform:  Windows

**Comment by tsvetomir** [comment]
I agree on the filter name - including the time part is misleading. I'm afraid renaming it at this point would be worse, but we will consider adding a filter type that ignores the time.

For the moment, you can implement this behavior by modifying the produced filter expressions to include the full day:

**Comment by m-reiseder** [comment]
Thank you, I will look into that.

**Comment by vatsalRai** [comment]
Hi, I am facing the same problem and would like to know if we have a solution available?
