### ISSUE TITLE
DropDownsModule: title attribute of clear buttons not translated

### ISSUE THREAD

**Issue by dummdidumm** [telerik/kendo-angular#1852]
## I'm submitting a..

* Bug report 

## Current behavior

The title attribute of the clear buttons does not get translated. Happens in JIT and AOT mode. Happens for Autocomplete, Combobox, Multiselect.

![image](https://user-images.githubusercontent.com/5968653/47002792-2ee10600-d12e-11e8-93c8-364a9bbb7676.png)

## Expected behavior

The title attribute should get translated.

## Minimal reproduction of the problem with instructions
You can find the relevant title tags by searching for the following inside the DropDownsModule:
`class="k-icon k-clear-value k-i-close" title="clear" role="button" tabindex="-1"`

Browser: Browser independent.

System: System independent.

## Additional information

I think that there are more title attributes that are not translated. Maybe you could screen your codebase for untranslated title attributes.

**Comment by tapopov** [comment]
Fix is available in `kendo-angular-dropdowns@v3.5.2-dev.201903121528`

**Comment by tsvetomir** [comment]
Shipped in v3.5.2
