### ISSUE TITLE
Filters not cleared/set appropriately when DateRange is used in the Grid filter cell template

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1855]
The following documentation example is not working as expected:

[https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-filtering-by-date-ranges](https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-filtering-by-date-ranges)

When the filter is cleared, initially the date input values are cleared too, but after clicking in one of the date inputs, the other date input's value gets populated automatically.

**Comment by dimitar-pechev** [comment]
Fixed in the latest dev version of the **DateInputs** package (`v4.0.1-dev.201907011518`).

**Comment by dimitar-pechev** [comment]
Released with `@progress/kendo-angular-dateinputs@4.0.1`.
