### ISSUE TITLE
Opening the DropDownList and pressing Escape selects the highlighted item

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1858]
Opening the DropDownList and closing it via pressing the Escape button selects the highlighted (by default - first) item, while tabbing out of the DropDownList closes the popup and there is no selected item (the expected behavior in both scenarios):

[https://stackblitz.com/edit/angular-opdgnr-jwxutx?file=app/app.component.ts](https://stackblitz.com/edit/angular-opdgnr-jwxutx?file=app/app.component.ts)

**Comment by dimitar-pechev** [comment]
The fix is available in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package v3.2.1-dev.201810300907.

**Comment by dimitar-pechev** [comment]
Shipped in v3.3.0 of the `@progress/kendo-angular-dropdowns` package.
