### ISSUE TITLE
Installing the Kendo Bootstrap Theme via NPM returns 404...

### ISSUE THREAD

**Issue by nickniverson** [telerik/kendo-angular#186]
# Steps to Reproduce

1.  Follow the npm login steps @ http://www.telerik.com/kendo-angular-ui/getting-started/

2.  run the following command (as shown [here](http://www.telerik.com/kendo-angular-ui/components/styling/)):  _npm install --save @progress/kendo-theme-bootstrap_

3.  Note that the install fails with a 404.  

## Note
I did some research and found another thread where someone was using the @telerik namespace in npm and that package does seem to install via npm... However, I haven't verified whether or not it's the correct package yet.... but perhaps the documentation is just out of date or incorrect?  My gut feeling is that the @progress package is supposed to work, because @telerik namespace is inconsistent with the rest of the angular 2 packages (which are located under @progress)... 

(fyi, the "at" mentions are unintentional)

# Console Output

```bash
c:\code\git\TaxPlatform\Source\CH.Tax.TSDP.Web>npm install --save @progress/kendo-theme-bootstrap
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "c:\\nodejs\\npm-global\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@progress/kendo-theme-bootstrap"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
npm ERR! <title>404 - File or directory not found.</title>
npm ERR! <style type="text/css">
npm ERR! <!--
npm ERR! body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
npm ERR! fieldset{padding:0 15px 10px 15px;}
npm ERR! h1{font-size:2.4em;margin:0;color:#FFF;}
npm ERR! h2{font-size:1.7em;margin:0;color:#CC0000;}
npm ERR! h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
npm ERR! #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
npm ERR! background-color:#555555;}
npm ERR! #content{margin:0 0 0 2%;position:relative;}
npm ERR! .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
npm ERR! -->
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>404 - File or directory not found.</h2>
npm ERR!   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\code\git\TaxPlatform\Source\CH.Tax.TSDP.Web\npm-debug.log

```

**Comment by rusev** [comment]
Please make sure that you have followed the [Installation](http://www.telerik.com/kendo-angular-ui/getting-started/#toc-installation) instructions.

**Comment by nickniverson** [comment]
@rusev ... I followed the installation instructions... The default theme works fine, the bootstrap theme does not... I do not want the default theme...

**Comment by tsvetomir** [comment]
Please note that all packages are now in the `@progress` scope, including the themes. 

The full npm-debug.log file will come in handy in debugging this issue. Will appreciate it if you attach it here.

**Comment by nickniverson** [comment]
@tsvetomir  

[npm-debug.log.txt](https://github.com/telerik/kendo-angular2/files/714137/npm-debug.log.txt)

**Comment by gyoshev** [comment]
Hello @nickniverson,

I am sorry for the confusion. The @progress/kendo-theme-bootstrap theme is still in active development, and is not ready for consumption in the components. It should have not been listed on the site just yet.

If time is of the essence, please use `@progress/kendo-theme-default`. Its colors can be adjusted via [these variables](https://github.com/telerik/kendo-theme-default/blob/master/scss/_variables.scss), to match the bootstrap colors.

**Comment by nickniverson** [comment]
@gyoshev ... Ok, good to know.  Thanks!  Will there be an announcement or anything like that when this stuff is ready?... (i.e. as opposed to periodically trying to install the package... )

**Comment by gyoshev** [comment]
@nickniverson You can [subscribe to this issue](https://github.com/telerik/kendo-angular/issues/266) to get a notification when a stable release is shipped.
