### ISSUE TITLE
Splitter pane resizing not working as expected after changing the orientation

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1861]
When we change the Splitter orientation dynamically, the resizing is not working as expected anymore (only in the direction, opposite to the initial one).

For example the following Splitter is resizing as expected, but after pressing the button, when we try to resize the left pane, the splitterbar "jumps" to the right:

[https://stackblitz.com/edit/angular-3skvor-ctm72n?file=app/app.component.ts](https://stackblitz.com/edit/angular-3skvor-ctm72n?file=app/app.component.ts)

Reported in a private support thread - Ticket ID: 1347107

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0

https://stackblitz.com/edit/angular-3skvor-bihwf6?file=app/app.component.ts
