### ISSUE TITLE
Grid visual residual element 

### ISSUE THREAD

**Issue by Aaol** [telerik/kendo-angular#1864]
## I'm submitting a...
* Bug report

## Current behavior
When scrolling to the end of the grid, there may appear a visual glitch after the last row, which make thinking that there are some data left.
![image](https://user-images.githubusercontent.com/11680065/47344991-fd29eb00-d6a9-11e8-87d0-00691c2d4579.png)

This bug appears only on Safari.

## Expected behavior
There should not be a visual glitch.
## Environment

Package versions:
```
@progress/kendo-angular-dateinputs@1.4.5
+-- @progress/kendo-angular-dialog@2.1.0
+-- @progress/kendo-angular-dropdowns@1.6.1
+-- @progress/kendo-angular-excel-export@1.0.7
+-- @progress/kendo-angular-grid@1.8.0
+-- @progress/kendo-angular-inputs@1.5.0
+-- @progress/kendo-angular-intl@1.4.0
+-- @progress/kendo-angular-l10n@1.1.0
+-- @progress/kendo-data-query@1.3.0
+-- @progress/kendo-drawing@1.5.3
+-- @progress/kendo-theme-bootstrap@2.12.1
+-- @progress/kendo-theme-default@2.51.0
```

Browser:
- Safari (desktop) version 12

System:
- Platform:  Mac

**Comment by tsvetomir** [comment]
I reviewed a number of Grid samples with Safari 12.0, but I couldn't see anything similar to the artifact in the screenshot.

Can you please share an example, in StackBlitz or as a sample app, with a similar styling issue?

**Comment by tsvetomir** [comment]
Closing until more details become available.
