### ISSUE TITLE
MultiSelect with custom value should focus an available value if present

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1866]
## I'm submitting a...

* Bug report 

## Current behavior
When using the MultiSelect with custom values, if we type in the input a value, the focus does not move to any of the available items in the dropDown.

## Expected behavior
The focus should move to an item from the dropDown, that corresponds to the value in the input (if such is present).

## Minimal reproduction of the problem with instructions
Check the following example:

1. Type "S", or "Sm", or "Small" in the input of the MultiSelect. The already available "Small" item in the dropDown should be focused.

[https://stackblitz.com/edit/angular-yu4rva?file=app/app.component.ts](https://stackblitz.com/edit/angular-yu4rva?file=app/app.component.ts)

**Comment by ivan-pelly** [comment]
Agreed! When the list is long, it's awkward to have to scroll to an item. A couple of keystrokes should get the user close to where they want to be in the list. Thank!

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package (**v4.0.0-dev.201906101555**).

**Comment by dimitar-pechev** [comment]
Shipped with `@progress/kendo-angular-dropdowns@4.0.0`.
