### ISSUE TITLE
Angular 7 dependencies need to be updated

### ISSUE THREAD

**Issue by rvrn22** [telerik/kendo-angular#1867]
Suggestion for improvement

## Current behavior
With the latest packages, We get the following warnings.

warning "@progress/kendo-angular-buttons > @progress/kendo-angular-popup@2.4.1" has incorrect peer dependency "@angular/animations@4 - 6".
warning "@progress/kendo-angular-buttons > @progress/kendo-angular-popup@2.4.1" has incorrect peer dependency "@angular/common@4 - 6".
warning "@progress/kendo-angular-buttons > @progress/kendo-angular-popup@2.4.1" has incorrect peer dependency "@angular/core@4 - 6".
warning "@progress/kendo-angular-dropdowns > @progress/kendo-angular-resize-sensor@3.0.3" has incorrect peer dependency "@angular/common@4 - 6".
warning "@progress/kendo-angular-dropdowns > @progress/kendo-angular-resize-sensor@3.0.3" has incorrect peer dependency "@angular/core@4 - 6".
warning "@progress/kendo-angular-grid > @progress/kendo-angular-pdf-export@1.1.1" has incorrect peer dependency "@angular/common@4 - 6".
warning "@progress/kendo-angular-grid > @progress/kendo-angular-pdf-export@1.1.1" has incorrect peer dependency "@angular/core@4 - 6".
warning " > @progress/kendo-angular-sortable@1.1.1" has incorrect peer dependency "@angular/common@4 - 6".
warning " > @progress/kendo-angular-sortable@1.1.1" has incorrect peer dependency "@angular/core@4 - 6".

## Expected behavior
No warnings

## Environment
Windows 10

Package versions:
    "@progress/kendo-angular-buttons": "4.2.0",
    "@progress/kendo-angular-dateinputs": "3.5.1",
    "@progress/kendo-angular-dropdowns": "3.2.0",
    "@progress/kendo-angular-excel-export": "2.2.0",
    "@progress/kendo-angular-grid": "3.9.0",
    "@progress/kendo-angular-inputs": "3.3.0",
    "@progress/kendo-angular-intl": "1.6.0",
    "@progress/kendo-angular-l10n": "1.3.0",
    "@progress/kendo-angular-layout": "3.2.0",
    "@progress/kendo-angular-popup": "2.4.1",
    "@progress/kendo-angular-sortable": "1.1.1",
    "@progress/kendo-angular-treeview": "2.4.0",
    "@progress/kendo-data-query": "1.5.0",
    "@progress/kendo-drawing": "1.5.7",
    "@progress/kendo-theme-default": "2.57.1",

System:
- TypeScript version: 3.1.3
- Node version: 10.3.0
- Platform:  Windows

**Comment by tsvetomir** [comment]
Please, update to the latest version of all packages to resolve this issue. You can use a tool like [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to make the process easier:

```sh
npm install -g npm-check-updates
ncu -u -f /^@progress/
```

**Comment by rvrn22** [comment]
This is what I get.

WebAppNG>ncu -u -f /^@progress/
Using WebAppNG\package.json
[..................] - :
 @progress/kendo-angular-popup  2.4.1  →  2.5.0
Upgraded WebAppNG\package.json

I can't use 2.5.0, because that causes #1868

Thanks

**Comment by tsvetomir** [comment]
Looks like you've got two concurrent versions of the popup package installed. Try removing node_modules and package-lock.json and re-installing.

**Comment by rvrn22** [comment]
That did fix everything. Thanks a lot.
