### ISSUE TITLE
Can't show tooltip programmaticlly 

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1869]
## I'm submitting a...

* Bug report 

## Current behavior
Can't show tooltip without any interaction just in ngAfterViewInit ( like shown by default)  

## Expected behavior
It should be possible to show tooltip without user interaction.

## Minimal reproduction of the problem with instructions
1.Open this [stackblitz sample](https://stackblitz.com/edit/angular-mtudvb)
2.Open console , there is an error.
3.The button will do the same but it will show the tooltip without error.

## Environment

Package versions:

```
broken in v1.1.0
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by elena-gancheva** [comment]
updated stackblitz example here: https://stackblitz.com/edit/angular-mtudvb-vcy5ew

**Comment by elena-gancheva** [comment]
fix is available in the latest `dev` version of the package.

**Comment by elena-gancheva** [comment]
Fixed and shipped with `v1.1.2` of the package.
