### ISSUE TITLE
Angular 7 Supported?

### ISSUE THREAD

**Issue by Tiberriver256** [telerik/kendo-angular#1870]
Does this library support Angular 7?

**Comment by dtopalov** [comment]
Yes it does. If you are facing any issues you can check out this discussion too:

[https://github.com/telerik/kendo-angular/issues/1867#issuecomment-432694823](https://github.com/telerik/kendo-angular/issues/1867#issuecomment-432694823)

**Comment by Tiberriver256** [comment]
Cool thank you
