### ISSUE TITLE
Compile-time errors when using the Notification component

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#1873]
## I'm submitting a...

* Suggestion for improvement  

## Current behavior

1. The `NotificationRef` type is not exported by the module, which causes demos to trigger errors (due to a missing export)
2. The `NotificationRef.content` field does not return the actual type of the component, thus triggering compile-time errors like `error TS2339: Property 'message' does not exist on type 'ComponentRef<any>'.`

## Expected behavior

No compile-time errors when running the [Notification / Content / Component demo](https://www.telerik.com/kendo-angular-ui/components/notification/content/#toc-rendering-a-component). The second problem could possibly be alleviated with [TypeScript generics](https://www.typescriptlang.org/docs/handbook/generics.html).

## Minimal reproduction of the problem with instructions

Run the above demo in Angular CLI, and observe the errors. Resolving the first one triggers the second one.

## Environment

Package versions:

```
 @progress/kendo-angular-notification@1.0.0
```

**Comment by elena-gancheva** [comment]
Fixed in latest `dev` version of the package.

**Comment by tsvetomir** [comment]
Fixed in v1.0.1
