### ISSUE TITLE
I got KendoGrid error

### ISSUE THREAD

**Issue by pp07** [telerik/kendo-angular#1876]
Index:131 Uncaught TypeError: jQuery(...).kendoGrid is not a function
    at HTMLDocument.<anonymous> (Index:131)
    at fire (VM469 jquery-1.10.2.js:3062)
    at Object.fireWith [as resolveWith] (VM469 jquery-1.10.2.js:3174)
    at Function.ready (VM469 jquery-1.10.2.js:447)
    at HTMLDocument.completed (VM469 jquery-1.10.2.js:118)
(anonymous) @ Index:131
fire @ VM917 jquery-1.10.2.js:3062
fireWith @ VM917 jquery-1.10.2.js:3174
ready @ VM917 jquery-1.10.2.js:447
completed @ VM917 jquery-1.10.2.js:118

please guide me.

**Comment by tsvetomir** [comment]
This error, seems to be related to the Kendo UI Grid for jQuery. This is not the right place for it, as this issue tracker is dedicated to the Kendo UI for Angular suite.

Please, submit a support ticket to get this issue resolved.

**Comment by vinuav** [comment]
Uncaught TypeError: kendo.syncReady is not a function
    at Index:60 can u Help Me

**Comment by tsvetomir** [comment]
@vinuav this error also seems to be related to the Kendo UI Grid for jQuery. Please, submit [a support ticket](https://www.telerik.com/account/support-tickets/my-support-tickets) to get assistance.
