### ISSUE TITLE
PDFExport - page break not calculated properly when there is an element rendered in the PDF only

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1878]
When the PDFExport contains a Grid and an element, visible in the exported document only, the Grid page break for the first page is not calculated properly, and in turn an item gets cut off:

[https://stackblitz.com/edit/angular-qkj4p7?file=app%2Fpdf-styles.css](https://stackblitz.com/edit/angular-qkj4p7?file=app%2Fpdf-styles.css)

![image](https://user-images.githubusercontent.com/7533599/47640883-5643c400-db6d-11e8-94ee-864b7a06fc4a.png)

**Comment by danielkaradachki** [comment]
[kendo-pdf-document](https://www.telerik.com/kendo-angular-ui/components/pdfexport/content-styling/#toc-using-the-pdf-document-element) should be used to style multi-page content:
https://stackblitz.com/edit/angular-qkj4p7-gbjgrk?file=app/pdf-styles.css

The k-pdf-export class is applied only to the individual pages before export and using it may lead to incorrectly sized pages. Will keep the issue opened until the documentation is updated to make this clearer.

**Comment by AjayJagtap** [comment]
The same issue I am getting in Kendo MVC. I have done styles changes but it is not working for me in MVC.
Please help me to resolve this issue.
