### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by enyachoke** [telerik/kendo-angular#188]
We are working on an opensource product and accept external pull requests from forks. Unfortunately we can't use kendo with travis because of authentication any way around this?

**Comment by tsvetomir** [comment]
You can use the following `.travis.yml` configuration to set up your `.npmrc` file:

```
before_install:
  - echo "@progress:registry=https://registry.npm.telerik.com/" > .npmrc
  - echo "//registry.npm.telerik.com/:_authToken=\"$PROGRESS_REGISTRY_TOKEN\"" >> .npmrc
```

Here PROGRESS_REGISTRY_TOKEN is an environment variable set in the [build settings](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings). You can take it from your local `~/.npmrc` file after logging in.

**Comment by enyachoke** [comment]
@tsvetomir  Thanks for the response. My understanding is that for security reasons the env variables are not available to forks. In our current setup we don't do development on the main repo everybody works from a fork and makes pull request which means for us to use kendo we have to change our process I really hope there is another way because really like kendo.

**Comment by tsvetomir** [comment]
You can use [encrypted variables](https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables) in `.travis.yml` as alternative. Each user will have to encrypt his access token as the encryption keys are tied to the fork.

**Comment by enyachoke** [comment]
I see we shall try that

**Comment by tsvetomir** [comment]
The [Build Agents Authentication](http://www.telerik.com/kendo-angular-ui/components/installation/build-agents/) has been published. Let us know if you have any further questions.
