### ISSUE TITLE
NotificationService does not work with hybrid app (ngUpgrade)

### ISSUE THREAD

**Issue by jayr11** [telerik/kendo-angular#1881]
## I'm submitting a...
* Bug report 

## Current behavior
When trying to use the NotificationService in a hybrid application (using ngUpgrade), a JavaScript error is thrown from the show method at the following line:

var appRootComponent = this.appRef.components[0].location.nativeElement;

Because this is a hybrid application, there is no root (app) component.

## Expected behavior
That no error is thrown or that there is a way of providing a different "root" component (similar to POPUP_CONTAINER)

## Environment

Browser:
- Chrome (desktop) version 69.0.3497.100

**Comment by elena-gancheva** [comment]
Added in the latest `dev` version of the package.

**Comment by ipeshev** [comment]
In [this sample](https://stackblitz.com/edit/angular-btk7yu?file=app%2Fapp.module.ts) it fallback  very silently which is error prone.

**Comment by elena-gancheva** [comment]
Shipped with `v1.2.0` of the package.
