### ISSUE TITLE
Allow 'close' prevention of Window opened from a service

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1883]
Currently there is no straight-forward and clean approach to prevent a ~~Dialog~~ or Window component from closing, when it is created from the service (otherwise one can simply skip toggling the boolean the ***ngIf** directive is bound to in the _close_ event handler).

**Comment by AsifulNobel** [comment]
@Raisolution Is there any update on this? Any estimated release version?

**Comment by PetarMetodiev** [comment]
This feature has been implemented for the `DialogComponent` in the latest version of the `@progress/kendo-angular-dialog` package. Here is [the documentation on the topic](https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/#toc-dialog-close-prevention).

**Comment by Raisolution** [comment]
The feature is implemented in the Window component too in `v5.1.0`
