### ISSUE TITLE
[tabstrip] Clicking selected tab after initialization re-loads the same tab and animation

### ISSUE THREAD

**Issue by ksCookj** [telerik/kendo-angular#1887]
## I'm submitting a...

* Bug report 

## Current behavior
When a tabstrip has animations true and one tab is set to [selected]="true", after initial load if you click the selected tab it will trigger the animation and create a flash of the content. This only happens after initial load.

## Expected behavior
If the tab is already selected we should not load the content again or animation 

## Minimal reproduction of the problem with instructions

1. pull up tabstrip overview : https://www.telerik.com/kendo-angular-ui/components/layout/tabstrip/
2. In first example click the selected tab

## Environment

"@progress/kendo-angular-layout": "3.2.0"

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0

https://stackblitz.com/edit/angular-516pvt?file=app/app.component.ts
