### ISSUE TITLE
Grid: allow preventing of the detailCollapse event

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1888]
Currently preventing the **_detailCollapse_** event is not possible out-of-the-box, and it is hard to collapse (and thus destroy) the detail template conditionally (for example after the user confirms he is sure the Grid row should be collapsed, and thus the whole detail template and the data within - destroyed).

Providing developers with the opportunity to prevent collapsing of the master Grid row will be a nice enhancement to the current Grid functionality.

**Comment by ipeshev** [comment]
Available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) , example [here](https://stackblitz.com/edit/angular-ud5gjs).

**Comment by danielkaradachki** [comment]
Released in 3.10.0

https://stackblitz.com/edit/angular-dqzd9w?file=app/app.component.ts
