### ISSUE TITLE
Grid derives PDF encoding format problem

### ISSUE THREAD

**Issue by fengzhihenxs** [telerik/kendo-angular#1889]
If grid exports PDF for Chinese, there will be scrambling code. Have you set the encoding format attribute to make it export Chinese normally?

**Comment by danielkaradachki** [comment]
You need to define a font that includes the used characters. For more information please refer to [this](https://www.telerik.com/kendo-angular-ui/components/drawing/pdf-output/embedded-fonts/) documentation topic.
