### ISSUE TITLE
Tab problem Combobox

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#189]
**Plunkr:** 
http://plnkr.co/edit/G47seNBR8WEaMfEh4CWt?p=preview 

Have to press Tab twice to focus the next Combobox.

**Comment by tapopov** [comment]
Hi @simon11196 

This is closely related to issue https://github.com/telerik/kendo-angular2/issues/155

**Comment by KirilNN** [comment]
Will close this one and will keep the other issue open.
