### ISSUE TITLE
DropdownList Odata - Paging

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#1890]
## I'm submitting a...

* Suggestion for improvement  

## Current behavior

https://www.telerik.com/kendo-angular-ui/components/faq/#toc-does-the-dropdownlist-support-odata
https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/data-binding/

The links above show we can use subset of Odata features with the dropdownlist.

What would be great if we could paging on the dropdownlist.

## Expected behavior

We load a subset of items, (30), when we scroll to the bottom, we fetch another 30.

I believe this was possible in Kendo-UI

## Minimal reproduction of the problem with instructions

The links provided above, should work.

**Comment by valchev** [comment]
Hi @cheng93 

The data virtualization (e.g. paging) is not in our immediate plans. Currently the team is working on UI virtualization feature which aims to improve the performance of the component, when it is bound to a large data set. This means that all components from the DropDowns package will render the items on demand, but the data will be fetched at once.

You're correct that in Kendo UI for jQuerry, the dropdown widgets support both data and UI virtualization. This however requires [more complex configuration](https://docs.telerik.com/kendo-ui/controls/editors/combobox/virtualization#value-mapping), which according to the feedback that we collected is a stumbling block for many customers.

This is the main reason, we decided to implement UI virtualization at first, as this is the most requested feature and it does not require time consuming configuration from the developer.

**Comment by GOhlson** [comment]
@valchev Is there an estimate upon which the UI virtualization will be completed?

**Comment by tapopov** [comment]
Hi @GOhlson 
The UI virtualization is planned for the beginning of 2019, however at this point we cannot provide a more specific ETA.

**Comment by tapopov** [comment]
Closing this issue. Further updates on the topic should go to https://github.com/telerik/kendo-angular/issues/2195

**Comment by CptArn** [comment]
Is there any update on the odata paging? Is that already in the roadmap?
