### ISSUE TITLE
Kendo Chart : Field color in data is used

### ISSUE THREAD

**Issue by GuillaumeMante** [telerik/kendo-angular#1892]
## Current behavior
In a graph, if i use an object to be my data and in this object there is a field named specificly color with a value in hexa then this color will be use in my graph even if the color and the colorfield graph parameters are bind to null.

## Expected behavior
The field color in my data should not be use to set a color in a graph. Color and ColorField param should be the only wait to set a color. If they are null i want to see the default color.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-cakpxz?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
fixed in 3.5.0

https://stackblitz.com/edit/angular-h2d5bg?file=app/app.component.ts
