### ISSUE TITLE
Optimization of grid example 

### ISSUE THREAD

**Issue by geekloper** [telerik/kendo-angular#1893]
## I'm submitting a...

* Documentation issue 

## Current behavior

https://www.telerik.com/kendo-angular-ui/components/grid/#toc-basic-usage

In this example, specifically in the **products.ts**. `const sampleProducts` it's declared but never used. 

## Expected behavior

Just remove the declaration of  `const sampleProducts` from **products.ts**.

**Comment by Raisolution** [comment]
Hi @geekloper,

Thank you for the observation. The mentioned file is used in multiple examples in the documentation, which is why it provides differents sets of sample products data.
