### ISSUE TITLE
MaskedTextBox fails to handle number value

### ISSUE THREAD

**Issue by simonschuh** [telerik/kendo-angular#1894]
* Bug report

## Current behavior
A form value which is a number leads to an error.
```
TypeError: (value || "").split is not a function at toArray (parsers.js:3)
```

## Expected behavior
MaskedTextBox can handle number values.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-98hije?file=app/app.component.ts

## Environment

Package versions:

```
"@progress/kendo-angular-inputs": "3.3.0"
```

Browser:

- Chrome (desktop) version 70

System:
- Platform:  Windows

**Comment by danielkaradachki** [comment]
The maskedtextbox works only with strings as specified in the [API](https://www.telerik.com/kendo-angular-ui/components/inputs/api/MaskedTextBoxComponent/#toc-value)
