### ISSUE TITLE
Grid: Column reordering doesn't work with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by HolgerPersch** [telerik/kendo-angular#1896]
## I'm submitting a...

* Bug report

## Current behavior
Column reordering doesn't work with ChangeDetectionStrategy.OnPush

## Expected behavior
Column reordering should work when parent component's ChangeDetectionStrategy is OnPush

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-dwhqak

## Environment

Package versions:
```
lastest
```

Browser:
- Chrome (desktop) version 70.0.3538.77

System:
- TypeScript version: 3.1.6
- Node version: v10.1.0, 5.6.0
- Platform: Windows

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) - v3.10.0-dev.201811071329.

**Comment by HolgerPersch** [comment]
Works fine, thanks!

**Comment by ipeshev** [comment]
It will stay open for a while , till next master version.

**Comment by danielkaradachki** [comment]
Released in 3.10.0
https://stackblitz.com/edit/angular-jhtbjc?file=app/app.component.ts
