### ISSUE TITLE
Grid Enhancement: Responsive Pager

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1898]
Currently the Grid Pager is not responsive and its layout is distorted on smaller screens. Users can utilize the Pager template, and display various inner elements conditionally depending on the viewport size, but it would be a nice enhancement to provide responsive functionality out-of-the-box.

Sample workaround:

https://stackblitz.com/edit/angular-fawrcz?file=app/app.component.ts

Related internal issue - https://github.com/telerik/kendo-angular-grid/issues/191

Related themes issue - https://github.com/telerik/kendo-themes/issues/121

**Comment by Raisolution** [comment]
Available in `v5.0.0`

https://www.telerik.com/kendo-angular-ui/components/grid/paging/#toc-responsive-pager
