### ISSUE TITLE
[ComboBox] cannot pass a setter to the data input property

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1899]
## I'm submitting a...

* Bug report 

## Current behavior
The ComboBox does not behave properly, when we pass a setter to the data input property.

## Minimal reproduction of the problem with instructions
Check the following example and try to select a value from the dropdown using the mouse:
[https://stackblitz.com/edit/angular-nwm2zk?file=app/app.component.ts](https://stackblitz.com/edit/angular-nwm2zk?file=app/app.component.ts)

**Comment by tsvetomir** [comment]
That's expected behavior as the `getData()` function is returning a new array on each call. Pretty much nothing will work as the item instances constantly change.
