### ISSUE TITLE
ComboBox closing issue on mobile devices

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-angular#1900]
## Current behavior
When the ComboBox list is opened through the arrow on mobile devices, the underlying input element does not receive focus (which is expected as it prevents the keyboard from pop-ing up). However when you tap outside the ComboBox, the list remains opened.

## Expected behavior
The ComboBox list is closed when taping somewhere else on the page.

## Minimal reproduction of the problem with instructions
Can be reproduced on any demo opened on a mobile device.

Browser:
- Chrome (Android) version 70.0.3538.80

**Comment by ipeshev** [comment]
When testing on android noticed the following behavior, can close combobox and multicombobox unless it has focus in the input before opening. 
When testing on iOS got following discrepancies , can't close any of dropdowns with input unless clicking on done.
Got some situation like 
![Uploading 179968824_751700998718372_3696438443673793407_n.png…]()

**Comment by ipeshev** [comment]
iOS discrepancies seems like fixes with https://github.com/telerik/kendo-angular/issues/2079

**Comment by ipeshev** [comment]
Fix is available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds) of @progress/kendo-angular-dropdowns

**Comment by gkarapeev** [comment]
Fixed together with https://github.com/telerik/kendo-angular/issues/2079 and shipped with version [5.3.0](https://www.telerik.com/kendo-angular-ui/components/dropdowns/changelog/#1be0970a-a5e5-50dc-84e2-b0092d659a5e)
