### ISSUE TITLE
Angular CLI (Angular 7) build error

### ISSUE THREAD

**Issue by ngohungphuc** [telerik/kendo-angular#1901]
## Current behavior
When I run this command for my Angular CLI project 
```
ng build --aot
```

I get this error
![conemu64_2018-11-08_08-56-08](https://user-images.githubusercontent.com/13591213/48172903-226a5a80-e334-11e8-82e4-ab7a531f5e88.png)

## Expected behavior
Run ng build --aot successful

## Environment

Package versions:
```
    "@progress/kendo-angular-dateinputs": "^1.4.2",
    "@progress/kendo-angular-dialog": "^1.0.4",
    "@progress/kendo-angular-dropdowns": "^1.2.1",
    "@progress/kendo-angular-inputs": "^1.0.5",
    "@progress/kendo-angular-intl": "^1.2.1",
    "@progress/kendo-angular-l10n": "^1.0.4",
    "@progress/kendo-angular-upload": "^1.2.2",
    "@progress/kendo-theme-default": "^2.38.0",
```
 
System:
- TypeScript version: Version 3.1.1
- Node version: v10.13.0
- NPM version: 5.3.0
- Platform:  Windows

**Comment by ngohungphuc** [comment]
I try with new version
```
    "@progress/kendo-angular-dateinputs": "^1.4.2",
    "@progress/kendo-angular-dialog": "^1.0.4",
    "@progress/kendo-angular-dropdowns": "^1.2.1",
    "@progress/kendo-angular-inputs": "^1.0.5",
    "@progress/kendo-angular-intl": "^1.2.1",
    "@progress/kendo-angular-l10n": "^1.0.4",
    "@progress/kendo-angular-upload": "^1.2.2",
    "@progress/kendo-theme-default": "^2.38.0",
```

and get this error
![conemu64_2018-11-08_11-39-35](https://user-images.githubusercontent.com/13591213/48178174-e7bfec80-e34a-11e8-8716-dde2459277bb.png)

**Comment by tsvetomir** [comment]
@ngohungphuc package versions seem outdated. Please, check out the [I cannot install the latest versions of Kendo UI packages for Angular](https://www.telerik.com/kendo-angular-ui/components/troubleshooting/#toc-i-cannot-install-the-latest-versions-of-kendo-ui-packages-for-angular)

**Comment by ngohungphuc** [comment]
@tsvetomir  I have to install another package     
"@progress/kendo-angular-buttons": "^4.0.0"

Below is my full package.json in order to work with Angular 7
"@progress/kendo-angular-buttons": "^4.0.0",
    "@progress/kendo-angular-dateinputs": "^3.5.1",
    "@progress/kendo-angular-dialog": "^3.8.0",
    "@progress/kendo-angular-dropdowns": "^3.3.0",
    "@progress/kendo-angular-inputs": "^3.3.0",
    "@progress/kendo-angular-intl": "^1.2.1",
    "@progress/kendo-angular-l10n": "^1.0.4",
    "@progress/kendo-angular-upload": "^4.2.0",
    "@progress/kendo-theme-default": "^2.38.0",

**Comment by ngohungphuc** [comment]
I have to update and install this package
@progress/kendo-angular-buttons": "^4.0.0"
