### ISSUE TITLE
Kendo sortable generates additional link with href

### ISSUE THREAD

**Issue by MaraZ1** [telerik/kendo-angular#1902]
## I'm submitting a...

* Bug report 

## Current behavior

```
<kendo-grid [sortable]="true">
</kendo-grid>
```
This generates
`<a _ngcontent-c1="" class="k-link" href="#" tabindex="-1"></a>`

And it does redirect to localhost:4200/# when you click on some nested element.
For example a button in the header.

```
<kendo-grid [data]="gridData" style="height:400px" [sortable]="true">
        <ng-template ngFor [ngForOf]="columns" let-column>
            <kendo-grid-column
              field="{{column}}"
              [hidden]="hiddenColumns.indexOf(column) > -1"
            >
              <ng-template kendoGridHeaderTemplate let-dataItem>
                  {{dataItem.field}}
                  <button
                    (click)="hideColumn(dataItem.field)"
                    class="k-button k-primary"
                    style="float: right;"
                  >
                    Hide
                  </button>
              </ng-template>
            </kendo-grid-column>
          </ng-template>
        </kendo-grid>
```

## Expected behavior
Instead it should generate a `<div style="cursor: pointer;">` or` <a>` without href.

## Minimal reproduction of the problem with instructions

1. Run an example in documentation in stackblitz (https://www.telerik.com/kendo-angular-ui/components/grid/columns/hidden/)
2. Add `[sortable]="true"` to `<kendo-grid>`
3. Inspect the html source of the th and you will see `<a href="#">`

## Environment

Package versions:

```
+-- @progress/kendo-angular-buttons@4.2.0
+-- @progress/kendo-angular-dateinputs@3.5.1
+-- @progress/kendo-angular-dropdowns@3.2.0
+-- @progress/kendo-angular-excel-export@2.2.0
+-- @progress/kendo-angular-grid@3.9.0
+-- @progress/kendo-angular-inputs@3.3.0
+-- @progress/kendo-angular-intl@1.6.0
+-- @progress/kendo-angular-l10n@1.3.0
+-- @progress/kendo-angular-popup@2.5.0
+-- @progress/kendo-data-query@1.5.0
+-- @progress/kendo-drawing@1.5.7
+-- @progress/kendo-theme-default@2.58.0
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: Version 3.0.3
- Node version: v10.12.0
- NPM version: 6.4.1
- Platform: Windows

**Comment by danielkaradachki** [comment]
The element is link for accessibility reasons. Normally, the grid will handle the click event and prevent the navigation, but in this case the element is removed by the button click handler before the grid handles the event. You can avoid the problem by preventing the default action in the button click handler:
https://stackblitz.com/edit/angular-excjfl?file=app/app.component.ts
