### ISSUE TITLE
When set grid row filter operator are  (Is Null, Is Not Null, Is Empty, Is Not Empty) the cleared filter button not shown

### ISSUE THREAD

**Issue by kietresolve** [telerik/kendo-angular#1904]
## I'm submitting a...

* Bug report 

## Current behavior
It is still reproducible in v3.9.0 (2018-10-19)

When one of the 4  filters (Is Null, Is Not Null, Is Empty, Is Not Empty) is set, the clear filter button does not appear. 

## Expected behavior

The Clear filter button should appear as 4 of those filtered the data in the grid.
I have tried  the JQuery version of this which it is behaving correctly and you can find it here https://demos.telerik.com/kendo-ui/grid/filter-row

## Minimal reproduction of the problem with instructions
To reproduce this issue please go here
https://stackblitz.com/run/
Click on the filter icon and select "Is Null" option and you can see the data filtered but the button Clear filter does not appear.

**Comment by ipeshev** [comment]
Fix available in [latest dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version.

**Comment by danielkaradachki** [comment]
Released in 3.10.0:
https://stackblitz.com/edit/angular-lnnxec?file=app/app.component.ts
