### ISSUE TITLE
Timeline view requires height to be set

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#1905]
## I'm submitting a...

* Bug report 

## Current behavior
The Scheduler does not expand its height to accommodate all Timeline view slots. By default, only one will be visible:

![image](https://user-images.githubusercontent.com/247917/48265668-bec85600-e435-11e8-89bc-4f013aec902c.png)

The developer must set a height to make it usable. This height will be applied to all views, which may not be desired.

## Expected behavior
The Timeline view should not require vertical scrolling unless the Scheduler has a set height.

## Minimal reproduction of the problem with instructions
1. Configure [Timeline View](https://www.telerik.com/kendo-angular-ui/components/scheduler/views/timeline/) without setting height on the Scheduler, see [demo](https://stackblitz.com/edit/angular-kslban?file=app/app.component.ts).

## Environment

Package versions:

```
@progress/kendo-angular-scheduler@0.2.1
```

**Comment by danielkaradachki** [comment]
Fixed in 0.3.1
https://stackblitz.com/edit/angular-kslban-mlnqcp?file=app/app.component.ts
