### ISSUE TITLE
TreeView: Cannot read property 'matches' of null by clicking the arrow to collopse empty node

### ISSUE THREAD

**Issue by eastjie** [telerik/kendo-angular#1906]
## I'm submitting a...

* Bug report 

## Current behavior
Data of nodes come from service and we want to expand those nodes persistently. If an empty node is added to "expandedKey". The "Down"-Arrow will be displayed for this node. 
Then click "Down"-Arrow, the following error will shown in browser console:
 
> (main.js:1 Uncaught TypeError: Cannot read property 'matches' of null
    at Object.t.match (main.js:1)
    at Object.t.isContent (main.js:1)
    at e.clickHandler (main.js:1)
    at HTMLElement.eval (dom_renderer.ts:52)
    at HTMLElement.globalListener )

## Expected behavior

The error should be fixed. 

But I don't know, if it is correct for consistent behavior and the empty node should be operated as follows.
1. The empty node tree should have the same "right arrow" if it is not expanded yet, namely, the key is not added to expanded key.
2. If it has been expanded, empty node should not have the arrow any more.

## Minimal reproduction of the problem with instructions

The problme can be reproduced in the [example](https://stackblitz.com/edit/angular-v76tj3-4ktnef?file=app/app.component.ts)

1. Click button "Expand/Collapse "Decor" ;
2. Open browser console;
3. Click "down-arrow" of node "Decor";

Thanks very much.

**Comment by danielkaradachki** [comment]
We will fix the error but the expand/collapse icon is controlled only by the `hasChildren` function:
https://stackblitz.com/edit/angular-v76tj3-hfvait?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Released om 2.5.0

**Comment by eastjie** [comment]
Thanks very much. We have tested in our project. It works.
