### ISSUE TITLE
[NUmericTextbox] Min Value of 0 not correctly applied

### ISSUE THREAD

**Issue by ISSTJ** [telerik/kendo-angular#1910]
## Current behavior
I set the [min] value of the NumericTextBox to 0 (or 1), expecting the NumericTextBox to accept only numbers bigger then 0. But I am still able to enter negative numbers. Only if I use the up/down arrows at the right hand side, it is limited by the [min] value.

## Expected behavior
[min] value blocks entering numbers below the selected range. So if I enter have a [min] value of 0, then I should not be able to enter a -1. 

## Minimal reproduction of the problem with instructions
https://angular-ponuwn.stackblitz.io

## Environment
Most actual version

Browser:
- Chrome (desktop)
- Firefox

**Comment by danielkaradachki** [comment]
You should use the [autoCorrect](https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/precision/#toc-value-ranges) option to enforce the range. By default the min and max options enable only the validation.
