### ISSUE TITLE
Tooltip callout positioned wrong when in small table cell

### ISSUE THREAD

**Issue by ksCookj** [telerik/kendo-angular#1913]
## I'm submitting a...
* Bug report

## Current behavior
When a tooltip is in the last column of a table aligned left and that columns content is smaller then the toolip content the tooltip callout is positioned incorrectly.

## Expected behavior
The tooltip callout is postioned correctly

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-qnwfdc

click where it says "click me"

## Environment

Package versions:
"@progress/kendo-angular-tooltip": "1.1.0"

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by elena-gancheva** [comment]
Fixed and shipped with `v1.1.2` of the package.
