### ISSUE TITLE
Autocomplete does not show PopUp 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1914]
## I'm submitting a...

* Bug report 

## Current behavior
The AutoComplete does not show the Popup with options when using the default Google keyboard to type on Android devices. 

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-lqrkvr-woptyv?file=app/app.component.ts](https://stackblitz.com/edit/angular-lqrkvr-woptyv?file=app/app.component.ts)

## Environment
Android 6.0.1
Chrome 70

**Comment by dimitar-pechev** [comment]
Caused by #1958.

**Comment by dimitar-pechev** [comment]
Fixed in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.2-dev.201903141745**.

**Comment by tsvetomir** [comment]
Shipped in v3.5.2
