### ISSUE TITLE
Sortable on iOS Safari inside scrollable container

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1916]
https://www.telerik.com/kendo-angular-ui/components/sortable/templates/
## I'm submitting a...

* Suggestion for improvement  

## Current behavior
Inside scrollable container when try to reorder items the scroll is activated

## Expected behavior
Sortable zone should not not trigger scroll unless cursor is in the end of the screen.

## Minimal reproduction of the problem with instructions
1. Reproducible in this [stackblitz sample](https://stackblitz.com/edit/angular-mizblr).

Package versions:

```
v2.0
```

Browser:
- Safari (iOS) version XX

**Comment by ipeshev** [comment]
Works [properly](https://stackblitz.com/edit/angular-mizblr-rvr7uj?file=app/app.component.ts) with[ latest dev versions](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of @telerik/kendo-draggable and @progress/kendo-angular-sortable.

**Comment by danielkaradachki** [comment]
Fix released in 2.1.0
