### ISSUE TITLE
Sortable on modile inside scrollable container

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1917]
## I'm submitting a...

* Suggestion for improvement  

## Current behavior
Inside scrollable container it is difficult to scroll the container , though it is working smooth at some point. 

## Expected behavior
It should work smoother

## Minimal reproduction of the problem with instructions
1.Reproducible on this [stackblitz sample](https://angular-mizblr.stackblitz.io/).

Package versions:

```
v2.0
```

Browser:
- Chrome (Android) version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ipeshev** [comment]
Works [properly](https://stackblitz.com/edit/angular-mizblr-rvr7uj?file=app/app.component.ts) with[ latest dev versions](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of @telerik/kendo-draggable and @progress/kendo-angular-sortable.

**Comment by danielkaradachki** [comment]
Fix released in 2.1.0

**Comment by dtopalov** [comment]
Reopening since the described issues are observed with the latest versions again:

https://stackblitz.com/edit/angular-gmnceh?file=app/app.component.ts

Also not working properly under iOS.

**Comment by dtopalov** [comment]
As the issue initially discussed in this issue is resolved, we logged a separate issue that can be tracked here:

https://github.com/telerik/kendo-angular/issues/2645

Sortable on Android inside scrollable container
