### ISSUE TITLE
Moving grid column to a custom component makes it not showing up

### ISSUE THREAD

**Issue by MojtabaMontazery** [telerik/kendo-angular#1918]
Hi,

I would like to customise a kendo grid column and reuse it across my application (basically avoiding to repeat some codes related to that column). The following is a very basic example. Let's say I want a customised string grid column. So, I create the component below:
```typescript
@Component({

 selector: 'kendo-grid-string-column',

 template: `<kendo-grid-column [field]="field" [title]="title"></kendo-grid-column>`,

})
export class KendoGridStringColumnComponent {
  @Input()
  public field: string;
 
  @Input()
 public title: string;
 
 constructor() { }
}
```

Now, I use my component in the grid as follows, but neither that (first) column appears nor I get an error in the console!
```html
<kendo-grid [data]="data">

    <kendo-grid-string-column field="name" title="Name">
   </kendo-grid-string-column>

    <kendo-grid-column field="lastName" title="Last Name">
    </kendo-grid-column>
</kendo-grid>
```

Note that this example is only for the illustration purpose. Of course, I want to have a more complex column with custom editing, filtering menu etc. Because of that I want to make the column reusable.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

**Comment by MojtabaMontazery** [comment]
@danielkaradachki I suppose it can be considered as a Bug, because in Angular it is expected that a component is rendered in the place that it is found. Here, I see (when debugging) my custom component is rendered, but it not showing up.
