### ISSUE TITLE
Hint on sortable item offset is incorrect when nested in detail grid

### ISSUE THREAD

**Issue by mikef907** [telerik/kendo-angular#1921]
## I'm submitting a...

* Regression report 

## Current behavior

Item hint offset is below the cursor when dragging item from sortable nesting in a grid detail template

## Expected behavior

Item hint offset should be set to stick to the cursor

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-tt7mwm

Browser:

- Chrome (desktop) version 70.0.3538.77
- Edge version 42.17134.1.0

**Comment by tapopov** [comment]
Thanks for reporting this @mikef907

**Comment by ipeshev** [comment]
Fixed in latest dev version of @progress/kendo-angular-sortable

**Comment by danielkaradachki** [comment]
Fixed in 2.1.0:

https://stackblitz.com/edit/angular-tt7mwm-tic6j3?file=app/app.component.ts
