### ISSUE TITLE
ToolbarTemplateDirective - custom top and bottom

### ISSUE THREAD

**Issue by crh225** [telerik/kendo-angular#1922]
## I'm submitting a ticket

* Suggestion for improvement  
* Documentation issue 

## Current behavior
Here is my example
https://stackblitz.com/edit/angular-ggweb2?file=app/app.component.ts

           <ng-template kendoGridToolbarTemplate [position]="'bottom'">
               <button (click)="onClick()" class="k-button">top action</button>
           </ng-template>
          <ng-template kendoGridToolbarTemplate [position]="'top'">
               <button (click)="onClick()" class="k-button">bottom action</button>
           </ng-template>

I want a custom button on the top of the grid and custom buttons on the bottom of the grid. In this example, it appears they will be the exact same.

## Expected behavior

![image](https://user-images.githubusercontent.com/19475195/48634368-09445800-e98b-11e8-8f3b-c42f5cd5c4a9.png)

**Comment by dtopalov** [comment]
Set `position` to 'both' and use the let-position value to determine what content to show on top and what - on bottom of the Grid:

[https://stackblitz.com/edit/angular-ggweb2-ntarex?file=app/app.component.ts](https://stackblitz.com/edit/angular-ggweb2-ntarex?file=app/app.component.ts)
