### ISSUE TITLE
(activeViewDateChange) is fired only when hovering the dates area

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1923]
## I'm submitting a...

* Bug report 

## Current behavior

When clicking the "TODAY" button the (activeViewDateChange) event is fired only, when hovering the dates area.

## Minimal reproduction of the problem with instructions
Check the following example:

1. Click "October"
2. Click "TODAY"
3. Hover the dates area and check the fired events
[https://stackblitz.com/edit/angular-vpelwk?file=app/app.component.ts](https://stackblitz.com/edit/angular-vpelwk?file=app/app.component.ts)

and a video demonstrating the undesired behavior:
[https://www.screencast.com/t/WZuhNYVNf6](https://www.screencast.com/t/WZuhNYVNf6)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
