### ISSUE TITLE
window restore

### ISSUE THREAD

**Issue by markacx** [telerik/kendo-angular#1927]
## I'm submitting a...
* Bug report 

## Current behavior
Programmatic setting of window state does not set the window to the previous size

## Expected behavior
It should return to its previous size

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-hte3k1

1) Minimize the window.
2) Click the "Restore" button (not the restore button in the window header)

## Environment

Browser:
- Chrome (desktop) Version 70.0.3538.102 (Official Build) (64-bit)
- Firefox version 63.0.3 

System:
Windows 10 64-bit

**Comment by Raisolution** [comment]
The fix is available in the latest dev release `v3.10.0-dev.201811290926`.

**Comment by tsvetomir** [comment]
Released in v3.10.0
