### ISSUE TITLE
Timepicker not switching AM/PM when used with grid.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1928]
## I'm submitting a...

* Bug report 

## Current behavior
Timepicker can't switch AM/PM when used with grid on same page.

## Expected behavior
Should switch always AM/PM

## Minimal reproduction of the problem with instructions
1.Open this [stackblitz sample](https://stackblitz.com/edit/angular-65hvyd?file=src%2Fapp%2Fapp.component.ts).
2.Try to switch AM/PM.
## Environment

Package versions:

```
broken in v3.5.2-dev.201811071618
```

Browser:
- IE version XX
- Edge version XX

User ticket  1361996

**Comment by tsvetomir** [comment]
Fixed in `@progress/kendo-angular-dateinputs` v3.5.2 and newer
