### ISSUE TITLE
Splitter throws ExpressionChangedAfterItHasBeenCheckedError when collapsing a pane

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1929]
## I'm submitting a...

* Bug report 

## Current behavior
When we have a PanelBar inside a Splitter pane and we expand one of the PanelBar's items, then if we try to collapse the Splitter pane the ExpressionChangedAfterItHasBeenCheckedError will be thrown.

The error is not thrown in prod mode.

## Minimal reproduction of the problem with instructions

1. Expand the "Programs" item of the PanelBar
2. Collapse the Splitter pane

[https://stackblitz.com/edit/angular-n5chjh?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-n5chjh?file=app%2Fapp.component.ts)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0

https://stackblitz.com/edit/angular-n5chjh-ggmgky?file=app/app.component.ts
