### ISSUE TITLE
Scheduler Recurrence Rule - Monthly: wrongly select specific day of the month

### ISSUE THREAD

**Issue by cap7ainjack** [telerik/kendo-angular#1930]
## I'm submitting a...

* Bug report 

## Current behavior
When I select recurrence rule for every second Monday of the month, for example, in January -2019 Scheduler selects 07.01.2019 

## Expected behavior
Should select 14.01.2019

## Minimal reproduction of the problem with instructions
https://angular-f762yn.stackblitz.io
https://stackblitz.com/edit/angular-f762yn?file=app/app.component.ts

## Environment

Package versions:
@progress/kendo-angular-scheduler@0.3.0
```

```

Browser:
- Chrome (desktop) version 70.0.3538.102

System:
- TypeScript version: 2.7.2

**Comment by tsvetomir** [comment]
Appears to be wrongly calculated only for January, will investigate - thanks!

**Comment by tsvetomir** [comment]
Fixed in `@progress/kendo-recurrence@0.1.2`
