### ISSUE TITLE
DatePicker is not displayed properly in IE10

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1932]
## I'm submitting a...

* Bug report 

## Current behavior
When opening the DatePicker it renders as the image demonstrated below:
![image](https://user-images.githubusercontent.com/20015190/48839314-bd7f1d80-ed93-11e8-8442-943b4c1c8f37.png)

## Minimal reproduction of the problem with instructions
Use IE10 to browse an application using the DatePicker

**Comment by ipeshev** [comment]
Fix available in latest dev version.
