### ISSUE TITLE
Scheduler - Delete calendar event issue. (remove) Event not fired correctly

### ISSUE THREAD

**Issue by cap7ainjack** [telerik/kendo-angular#1933]
## I'm submitting a...
  * Feature requests to our UserVoice Portal at https://goo.gl/HsVr7R.

* Suggestion for improvement 

## Current behavior
Remove event fires when X icon is clicked. 

## Expected behavior
Should fire event when is Confirmed on the confirmation dialog

##Environment
Package versions:
@progress/kendo-angular-scheduler@0.3.0

##Browser:

Chrome (desktop) version 70.0.3538.102
System:

TypeScript version: 2.7.2

Also how can I catch the different events when deleting the Current Occurrence event and how to catch one when I want to delete series?

**Comment by Raisolution** [comment]
Implemented by introducing the [openRemoveConfirmationDialog](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerComponent/#toc-openremoveconfirmationdialog) and [openRecurringConfirmationDialog](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerComponent/#toc-openrecurringconfirmationdialog) methods. An example is available on the following [documentation page](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-reactive-forms/#toc-removing-events).
