### ISSUE TITLE
Memory Leak for DatePicker/NumericTextBox when using ComponentFactoryResolver.

### ISSUE THREAD

**Issue by plsimardpolygon** [telerik/kendo-angular#1934]
Memory Leak for DatePicker/NumericTextBox when using ComponentFactoryResolver.

When using ComponentFactoryResolver DatePicker and NumericTextbox are leaking.

I have provided an example in the zip file. When u press add it create the component but after you press removeAll DatePicker and NumericTextbox are still in memory. I only need a fix for the datepicker... This is preventing me from going in production with my application right now.

Source code is pretty simple.

export class AppComponent {
  title = 'DatePickerLeak';

  public myForm: FormGroup = new FormGroup({
    birthDate: new FormControl(new Date(2018, 11, 21)),
    salary: new FormControl(0.00),
  });

  constructor(protected componentFactoryResolver: ComponentFactoryResolver) {
  }

  @ViewChild(AddDirective) anchor: AddDirective;

  public executeAdd() {

    const componentRef = this.anchor.viewContainerRef
      .createComponent(this.componentFactoryResolver.resolveComponentFactory(DynamicComponent));

    (<any>componentRef.instance).myForm = this.myForm;
  }

  public executeRemoveAll() {
    this.anchor.viewContainerRef.clear();
  }
}

// Component contain telerik control.

@Component({
  selector: 'app-dynamic',
  templateUrl: './dynamic.component.html',
  styleUrls: ['./dynamic.component.scss']
})
export class DynamicComponent implements OnInit {

  @Input()
  public myForm;

  constructor() { }

  ngOnInit() {
  }

}

Browser:
[DatePickerLeak.zip](https://github.com/telerik/kendo-angular/files/2604685/DatePickerLeak.zip)

- Chrome (desktop) version  70.0.3538.102 (Official Build) (64-bit)
System:
- TypeScript version: 3.1.6
- Node version: XX  
- Platform:  Windows

**Comment by danielkaradachki** [comment]
You will get the same behavior for any component. The reason is that as explained [here](https://github.com/angular/angular/issues/7970#issuecomment-228624899), the form control does not automatically clear the references to the components when they are removed from the view. Should be possible to avoid this by removing the controls or by removing the group reference when removing the components.
