### ISSUE TITLE
Grid: save/restore columns state

### ISSUE THREAD

**Issue by HolgerPersch** [telerik/kendo-angular#1936]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
The grid component already has the functionality to resize and reorder columns by the user, but is missing functionality for saving an restoring columns configuration, so that changes done by the user are lost after a page change.

There is the [Persist the State](https://www.telerik.com/kendo-angular-ui-develop/components/grid/how-to/persist-state/) article in the `How to` section in the documentation, but the described solution is only applicable when adding grid columns by using *ngFor. When defining columns in the markup, due to extensive usage of templates (kendoGridColumnMenuTemplate, kendoGridFilterMenuTemplate, kendoGridCellTemplate, ..), there is no reasonable solution available.

## Expected behavior
Provide methods, similar to the [jQuery grid](https://demos.telerik.com/kendo-ui/grid/persist-state), to save and restore columns configuration. This should at least include the column's order, width and sort.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. For feature requests please use our [feedback portal](https://feedback.telerik.com/kendo-angular-ui/).
