### ISSUE TITLE
Is it possible to apply kendoGridHeaderTemplate for all columns?

### ISSUE THREAD

**Issue by Mickey-P** [telerik/kendo-angular#1937]
## Current behavior
In documentation for usage of kendoGridHeaderTemplate example contains only configuration with repeated template for all columns ([example from documentation](https://stackblitz.com/edit/angular-emwxk6?file=app/app.component.ts))

## Expected behavior
It is possible to apply one template for all columns in one place. In example it is possible to provide kendoGridHeaderTemplate like kendoGridToolbarTemplate ([example](https://stackblitz.com/edit/angular-emwxk6-zfe2xd?file=app/app.component.ts))

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration. If you want to see this as built-in feature then create a feature request in our  [feedback portal](https://feedback.telerik.com/kendo-angular-ui/).
