### ISSUE TITLE
MultiSelect tag list is not accessible

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular#1939]
## I'm submitting a...

* Bug report 

## Current behavior
By User ticket updated
MultiSelect tag list is not accessible for various combination off browsers/readers

## Expected behavior

MultiSelect tag list should render proper WAI-ARIA attributes and should be accessible with major sort of browsers/readers

## Minimal reproduction of the problem with instructions
1. Open [this demo](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/)
2. Try to search , navigate and select/deselect an items
3. NVDa has selected items not announces, With JAWS/VoiceOver navigation announce is not working.

## Environment

- latest version

Browser:
    nVDA 2018.3 + Firefox 60
    JAWS 2018 + IE11
    JAWS 2018 + Firefox 60
    VoiceOver 9 + Safari 12 (OSX)
    JAWS 2018 + Chrome

**Comment by JulianH** [comment]
Hello @dimitar-pechev, when can we expect a solution for the problem?

Thank you for the update!

Best regards
Julian

**Comment by dimitar-pechev** [comment]
@JulianH, finding a working fix for the different reader/browser combinations proved a bit tricky but we have a code fix in place and it will probably be introduced next week.

**Comment by dimitar-pechev** [comment]
The `taglist` accessibility improvements are included in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.0-dev.201901311605**.

**Comment by ipeshev** [comment]
Currently following issues are not resolved.
Chrome - deleting the last one tag is not announced
Firefox - deleting with BACKSPACE is not aanounced
Edge - deselecting item is not announced

**Comment by dimitar-pechev** [comment]
The enhancements are included in **v3.5.0**.

As @ipeshev already said, some reader/browser combinations don't announce value change after deleting the tags without focusing them first (with the backspace). However, deleting the tags after focusing them first, announces the value change on all mentioned browsers.

**Comment by JulianH** [comment]
Hello @dimitar-pechev,

i've identified, that the problem reported in ticket #1070, is not solved yet. The taglist component contains a list with role "listbox" but dont have an associated discription. This is not accepable from the WCAG 3.1 point of view.

Best regards
Julian

**Comment by dimitar-pechev** [comment]
@JulianH, sorry for the delayed response. 

Are you referring to the `aria-roledescription` attribute? I actually couldn't find a reference stating that such a description or a label is required, when the `listbox` element is part of another widget (i.e. it's not a standalone component). If it is mandatory according to the WCAG, we'll look to add it, where we use the role `listbox`. Can you elaborate on this?
