### ISSUE TITLE
Cell grid tooltip how to not working

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#1940]
## I'm submitting a...
* Documentation issue

## Current behavior
Code throws error. (It is not working).

![chrome_2018-11-24_11-18-15](https://user-images.githubusercontent.com/1589573/48967001-a67e3c80-efda-11e8-8b42-a22c816ca852.png)

## Expected behavior
It works.

## Minimal reproduction of the problem with instructions
[This how to](https://www.telerik.com/kendo-angular-ui-develop/components/tooltip/how-to/show-grid-cells-content/) doesn't work.

Browser:
- Chrome (desktop) version 70.0.3538.102

**Comment by dtopalov** [comment]
Hello,

Indeed, there is a breaking change in the 1.1.1 version of the Tooltip package that causes the observed JavaScript errors. Please revert to 1.1.0 until we fix the demo accordingly. Here is the same example with v. 1.1.0 with the Tooltip package:

[https://stackblitz.com/edit/angular-g4mijm-kyosc6?file=app/app.component.ts](https://stackblitz.com/edit/angular-g4mijm-kyosc6?file=app/app.component.ts)

**Comment by tsvetomir** [comment]
Fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by elena-gancheva** [comment]
Fixed and shipped with `v1.1.2` of the package.

**Comment by BhushanChandak** [comment]
Given solution for tool tip is worked for some cases only. [https://www.telerik.com/kendo-angular-ui-develop/components/tooltip/how-to/show-grid-cells-content/](kendo demo) Please hover on first item of category column tooltip will not work not that truncate text ('Beverages').

**Comment by BhushanChandak** [comment]
please reopen this issue.

**Comment by tsvetomir** [comment]
@BhushanChandak the tooltip is shown only for items with truncated text in this example. Please, open a new issue with more details if you think you've spotted a problem.
