### ISSUE TITLE
Tooltip does not show on second hover attempt

### ISSUE THREAD

**Issue by ksCookj** [telerik/kendo-angular#1943]
## I'm submitting a...

* Bug report 

## Current behavior
After tooltip is shown when hovering over element, if you hover off element then back on to it the tooltip will not show

## Expected behavior
The tooltip should always show when hovering over element

## Minimal reproduction of the problem with instructions

https://www.telerik.com/kendo-angular-ui/components/tooltip/default-conf/

1. hover over save button
2. hover off of save button (make sure not to hover over "cancel" button)
3. hover back over save button
4. tooltip will not show

## Environment

Package versions:
@progress/kendo-angular-tooltip": "1.1.1"

**Comment by tapopov** [comment]
Thanks for reporting this regression @ksCookj! We'll look into it and update the issue once this is fixed.

**Comment by elena-gancheva** [comment]
Fixed and shipped with `v1.1.2` of the package.
