### ISSUE TITLE
Combobox - search component issue with NULL text value

### ISSUE THREAD

**Issue by hidegh** [telerik/kendo-angular#1944]
## I'm submitting a...
Bug report

## Current behavior
Exception is thrown on leaving combobox if the text field is null.

## Expected behavior
a null value (which is displayed correctly as an empty string) should not throw error in the nested search-component.

FIX: consider null also in the code below - combobox.component.ts, line: 1222, function handleBlur(),
![image](https://user-images.githubusercontent.com/6331063/49028350-72557800-f1a2-11e8-8ea1-0459385c6ace.png)

## Minimal reproduction of the problem with instructions
Use any combobox with complex value and set one of the text property fields to NULL, then select that item, enter and then exit given combobox.

See sample: https://stackblitz.com/edit/kendo-bug-combobox-searchbox-with-null-text?file=app/app.component.ts

## Environment
Angular 4.3
Chrome (latest)
Windows 10.x 64bit

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the **DropDowns** package (`@progress/kendo-angular-dropdowns@3.5.0-dev.201901311002`).

**Comment by dimitar-pechev** [comment]
Shipped with `@progress/kendo-angular-dropdowns@3.5.0`.
