### ISSUE TITLE
[Grid] Navigation not working when kendoGridGroupBinding directive is used

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1946]
When both virtual scrolling and grouping are enabled via the kendoGridGroupBinding directive, and the Grid is `navigable`, focus is trapped in the header row when down or up arrow is pressed:

[https://stackblitz.com/edit/angular-icxejq?file=app/app.component.ts](https://stackblitz.com/edit/angular-icxejq?file=app/app.component.ts)

1. Focus any content cell

2. Press up/down - focus goes to the header cell of the respective column and is trapped in the header row

**Comment by tsvetomir** [comment]
Fixed in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Released in v3.10.2
