### ISSUE TITLE
[Scheduler] customization on the Edit Event cannot be done with new field like location, EventTitle etc

### ISSUE THREAD

**Issue by santutoshi** [telerik/kendo-angular#1947]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Current behavior
we can only edit the fields which is already in the Scheduler Event 

## Expected behavior 
Can be able to map to the Custom Fileds

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Raisolution** [comment]
Hi @santutoshi,

You are correct, currently the Scheduler can only edit `SchedulerEvent` items. Mapping them to custom fields is in our short term development plans. You could find the logged enhancement issue here #1907. Any feedback about it is welcomed. I am closing this as a duplicate.
