### ISSUE TITLE
https://stackblitz.com/edit/angular-hkpycf?file=app/app.component.ts

### ISSUE THREAD

**Issue by minkhantkyaw35** [telerik/kendo-angular#1948]
How can do :
- at top right corner menu, the action check box is not allow to uncheck and  it is checked by the default.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. If this is a bug report, please follow the issue template and provide more detailed information about the problem.

**Comment by Raisolution** [comment]
Hi @minkhantkyaw35,

This repository is used for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific implementation. If this is indeed a bug, please use our template for submitting an issue.

**Comment by danielkaradachki** [comment]
Will close the issue for now and will reopen it once sufficient information about the problem is available.
