### ISSUE TITLE
[MultiSelect] the value is not cleared after assigning it to an empty array

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1949]
## I'm submitting a...

* Bug report 

## Current behavior
When using the [value] input property of the MultiSelect, the value is not cleared when assigning an empty array to it. 

As a workaround, we can use the MultiSelect's reset() method.

## Minimal reproduction of the problem with instructions
Check the following example and click the "Remove" button:

[https://stackblitz.com/edit/angular-saqju7-3hfngh?file=app/app.component.ts](https://stackblitz.com/edit/angular-saqju7-3hfngh?file=app/app.component.ts)

**Comment by dimitar-pechev** [comment]
Fixed in the latest dev version `@progress/kendo-angular-dropdowns` **v3.5.0-dev.201901281700**.

**Comment by RedLion73** [comment]
@dimitar-pechev When will this package be fully released?  Thanks.

**Comment by RedLion73** [comment]
Note that installing the dev package 3.5.0-dev.201901311605 results in this new error upon building:

ERROR in node_modules/@progress/kendo-angular-dropdowns/dist/es2015/data.service.d.ts(1,29): error TS2307: Cannot find module '@progress/kendo-data-query'.

Is this a new dependency?

**Comment by tsvetomir** [comment]
We're investigating a regression with the keyboard navigation. Hopefully, we'll have a good release in a few days.

The data-query dependency has been removed in the latest `dev` build.

**Comment by dimitar-pechev** [comment]
The fix is available in `@progress/kendo-angular-dropdowns@3.5.0`. Also, as **tsvetomir** mentioned, the dependency to the `@progress/kendo-data-query` package is dropped, so a clean install shouldn't result in any errors.
