### ISSUE TITLE
PopupService: Allow to inject PopupRef into component

### ISSUE THREAD

**Issue by holger-at-schottel-de** [telerik/kendo-angular#1950]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When using `PopupService` with a component as content it is not possible to inject the `PopupRef` into the component's ctor.

## Expected behavior
Allow to inject `PopupRef` into component's ctor like it is possible with `DialogService` and `DialogRef`. This will allow to call `close` on the `PopupRef` from within the component.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-1xz1za?file=app%2Fcustom.component.ts

**Comment by meriturva** [comment]
Any news here?

**Comment by mbechev** [comment]
To be tracked in the following feature request item:
https://feedback.telerik.com/kendo-angular-ui/1656596-popup-allow-injecting-popupref-into-component
