### ISSUE TITLE
kendo ui angular integration with kendo jquery for angular 5

### ISSUE THREAD

**Issue by Coder-Sneha** [telerik/kendo-angular#1951]
## I'm submitting a...
* Bug report 

## Current behavior
integrated kendo jquery multicolumncombobox in kendo angualr project. select event is even called when we click outside the multicoulmncombox, and even when we click on dropdown icon it takes nearly 4sec to render already binded data.

## Expected behavior
select method should not be called when clicked outside the combobox. even when clear icon is clicked its expected to reset the value and icon to be disappeared but its still there.
```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by danielkaradachki** [comment]
The repository is for bug reports regarding the [Kendo UI for Angular](https://www.telerik.com/kendo-angular-ui/) components. For issues regarding [Kendo UI for jQuery](https://demos.telerik.com/kendo-ui/), please open an issue in the [kendo-ui-core](https://github.com/telerik/kendo-ui-core) repo with more detailed information or open a [support ticket](https://www.telerik.com/account/support-tickets).
