### ISSUE TITLE
Sortable not working in ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by zrsio4** [telerik/kendo-angular#1954]
## I'm submitting a...
* Bug report
* Suggestion for improvement

## Current behavior
The Sortable component does not work with the change detection strategy OnPush

## Expected behavior
Works regardless of change detection strategy.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-mxafpr
Remove changeDetection line and observe expected behavior.

## Environment
Browser:

- Chrome (desktop) version 70.0.3538.102

System:
- TypeScript version: 1.0.3.0
- Node version: node 8.12.0, npm 6.4.1
- Platform:  Windows

**Comment by jmmurphy09** [comment]
I'm also having this problem.

**Comment by tapopov** [comment]
Fix available in `kendo-angular-sortable` v2.1.0-dev.201902270841.

**Comment by danielkaradachki** [comment]
Fixed in 2.1.0:

https://stackblitz.com/edit/angular-mxafpr-j6er5r?file=app/app.component.ts
