### ISSUE TITLE
Can't clear custom value in multiselect with kendoMultiSelectSummaryTag directive

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#1959]
## I'm submitting a...
* Bug report 

## Current behavior
If you have a multiselect with kendoMultiSelectSummaryTag directive  and allowCustom parameter is set to true, you won't have an ability to clear inserted item when clicking 'x' in template which has kendoMultiSelectGroupTagTemplate directive.

## Expected behavior
Should clear all selected items.

## Minimal reproduction of the problem with instructions
  1. See demo example https://stackblitz.com/edit/angular-qwgks6?file=app/app.component.ts
  2. Type 'test' in input box and press enter.
  3. See that this item is not added in select as option and you can't remove it when clicking on icon 'x' in kendoMultiSelectGroupTagTemplate.

## Environment
The latest version of chrome and kendo-angular-dropdowns v.3.4.0 were used.

**Comment by dimitar-pechev** [comment]
The fix is available in the latest [dev release](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) **v3.4.2-dev.201812141400** of the `@progress/kendo-angular-dropdowns` package.

**Comment by destus90** [comment]
@dimitar-pechev 
It's time that v3.4.2 was published on npm, not dev release. When are you going to do it?

**Comment by dimitar-pechev** [comment]
@destus90, sorry for the delay on this one. The fix is now included in the **3.4.2** version of the dropdowns. Here's [your example](https://stackblitz.com/edit/angular-5vgfdb) with the new version.
