### ISSUE TITLE
Works without ngZone?

### ISSUE THREAD

**Issue by marcj** [telerik/kendo-angular#1960]
Hello guys,

I'm interested in the UI but have a question. We use zoneless Angular to maintain a good UI speed, so we use

```
platformBrowserDynamic().bootstrapModule(AppModule, {
  ngZone: 'noop',
})
```

Which means Zone.js is completely disabled. Angular Materials doesn't work with that change. Does Kendo Angular work without Zone.js?

**Comment by danielkaradachki** [comment]
The Kendo Angular components also rely on the automatic change detection triggered by the zone and will not work properly without it.
