### ISSUE TITLE
[Scheduler] event template is not rendered in Month and Timeline views

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1965]
Scheduler's event template is rendered as expected in Day, Week and Agenda views, but not in Month view:

[https://stackblitz.com/edit/angular-vkeizw-z36ywy?file=app/app.component.ts](https://stackblitz.com/edit/angular-vkeizw-z36ywy?file=app/app.component.ts)

**Comment by danielkaradachki** [comment]
Fixed in 0.3.4:
https://stackblitz.com/edit/angular-rkvt2q-7up6zj?file=app/app.component.ts
