### ISSUE TITLE
Bar for Column Chart doesn't show if the value is relatively smaller than other

### ISSUE THREAD

**Issue by amitdwivedi20** [telerik/kendo-angular#1966]
## I'm submitting a...
Bug

## Current behavior
If the chart data is very small than other data bar doesn't shows for Column chart but its opposite for Bar chart. In bar chart it shows.

## Expected behavior
bar should be visible for both bar and column chart

Stackblitz for the same: https://stackblitz.com/edit/angular-w5c6ir?file=src%2Fapp%2Fapp.component.html 

## Environment

Package versions:
  "dependencies": {
    "@angular/animations": "^6.0.9",
    "@angular/common": "^6.0.9",
    "@angular/compiler": "^6.0.9",
    "@angular/core": "^6.0.9",
    "@angular/forms": "^6.0.9",
    "@angular/http": "^6.0.9",
    "@angular/platform-browser": "^6.0.9",
    "@angular/platform-browser-dynamic": "^6.0.9",
    "@angular/platform-server": "^6.0.9",
    "@angular/router": "^6.0.9",
    "@progress/kendo-angular-buttons": "^4.1.2",
    "@progress/kendo-angular-charts": "^3.3.2",
    "@progress/kendo-angular-dateinputs": "^3.4.4",
    "@progress/kendo-angular-dialog": "^3.6.2",
    "@progress/kendo-angular-dropdowns": "^3.1.0",
    "@progress/kendo-angular-excel-export": "^2.1.1",
    "@progress/kendo-angular-grid": "^3.6.0",
    "@progress/kendo-angular-inputs": "^3.2.0",
    "@progress/kendo-angular-intl": "^1.4.1",
    "@progress/kendo-angular-l10n": "^1.2.0",
    "@progress/kendo-angular-layout": "^3.1.2",
    "@progress/kendo-angular-notification": "^1.0.0",
    "@progress/kendo-angular-popup": "^2.4.2",
    "@progress/kendo-charts": "^1.11.2",
    "@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-drawing": "^1.5.7",
    "@progress/kendo-theme-default": "^2.54.1",
    "@progress/kendo-ui": "^2018.2.530",
    "angular": "^1.6.8",
    "angular-webstorage-service": "^1.0.2",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.7",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.0",
    "intl": "^1.2.5",
    "jquery": "1.11.1",
    "jquery-ui": "1.12.1",
    "ngx-scrollbar": "^2.2.0",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.3.2",
    "underscore": "1.8.3",
    "upgrade-angular": "^0.1.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "^6.2.5",
    "@angular/compiler-cli": "^6.0.9",
    "@angular/language-service": "^4.4.7",
    "@types/gridstack": "0.0.39",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^10.5.2",
    "@types/underscore": "1.8.9",
    "codelyzer": "^4.4.2",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^2.0.5",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^2.0.0",
    "karma-jasmine-html-reporter": "^1.2.0",
    "protractor": "^5.4.0",
    "rxjs-tslint": "^0.1.5",
    "ts-node": "~3.2.0",
    "tslint": "^5.11.0",
    "typescript": "^2.7.2",
    "webpack": "^4.16.1"
  }
```

```

Browser:

- Chrome (desktop) version 70.0.3538.110 (Official Build) (64-bit)
 

System:
- TypeScript version:2.7.2 
- Node version:  10.6.0 
- Platform:  Windows 

Stackoverflow Url: https://stackoverflow.com/questions/53611757/bar-for-kendo-column-chart-doesnot-show-if-the-data-is-relatively-very-small

**Comment by danielkaradachki** [comment]
Seems that the columns are being clipped. Possible workaround for the moment is to disable clipping:
https://stackblitz.com/edit/angular-dvynmu?file=src/app/app.component.html

**Comment by amitdwivedi20** [comment]
@danielkaradachki Thanks for the workaround. Are we going to get this fixed in near future?

**Comment by danielkaradachki** [comment]
Should be fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:
https://stackblitz.com/edit/angular-grzyxg?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Released in 3.5.2:
https://stackblitz.com/edit/angular-y6nkw1?file=app/app.component.ts
