### ISSUE TITLE
All grid columns' widths increased after setting single column width to smaller size after drag resize

### ISSUE THREAD

**Issue by jogoertzen-stantec** [telerik/kendo-angular#1967]
## I'm submitting a...

* Bug report 

## Current behavior

The width of every column in the grid is increased after programmatically setting the width of a single column to a smaller value after increasing the width of the column with the 'drag and drop' feature.

## Expected behavior

Only the single column's width should be affected when programmatically set, and it should be set to the specified value (ie. not larger or smaller than the desired value).

## Minimal reproduction of the problem with instructions

This snippet was taken from [here](https://www.telerik.com/kendo-angular-ui/components/grid/how-to/persist-state/#toc-using-dedicated-methods).

https://stackblitz.com/edit/angular-pqrvar?file=app/app.component.ts

1. Click 'Save current state'
2. Increase the width of any column (eg. ID)
3. Click 'Load saved state'
4. Observe the width of every column in the grid has increased

## Environment

Browser:

- Chrome (desktop) Version 71.0.3578.80 (Official Build) (64-bit)

**Comment by andreevsm** [comment]
I have the same problem. Why is the table width not reset after resetting the column width?
For example:
```
<table role="presentation" style="width: 837px; min-width: 0px;">
    <colgroup kendogridcolgroup="" role="presentation">
        <col style="width: 40px;">
        <col style="width: 188px;">
        <col style="width: 240px;">
        <col style="width: 180px;">
        <col style="width: 120px;">
    </colgroup>
.....
</table>

40 + 188 + 240 + 180 + 120 != 837
```
The bug exists since 2018 year, could you fix it, please?
<img width="364" alt="kendo-grid bug" src="https://user-images.githubusercontent.com/26060516/78240202-5c1ea100-74e7-11ea-8ef7-91204d49b841.png">

**Comment by dtopalov** [comment]
Will be tracked in https://github.com/telerik/kendo-angular/issues/3335 and
https://feedback.telerik.com/kendo-angular-ui/1522416-grid-stored-state-does-not-restore-to-full-grid-width
