### ISSUE TITLE
Kendo Grid Data Bound

### ISSUE THREAD

**Issue by PrakashKumar-27** [telerik/kendo-angular#1968]
## I'm submitting a...

* Documentation issue : Kendo Grid Data Bound option is not available for Angular 6 , can any one suggest me how to achieve this feature?
## Environment
Browser:

- Chrome (desktop) version 70.0.3538.110
System:
- Platform:   Windows

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
