### ISSUE TITLE
Fire preventable event when user  clicks on some of popup items

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1969]
## I'm submitting a...

* Suggestion for improvement  

## Current behavior
MultiSelect fires preventable event when tag is removed via X click on the tag, but it does not fire any event ( except valueChange ) when user clicks on selected items in the popup.
## Expected behavior
It would be nice to have some event fired when user clicks on items in the popup.
The desired scenario is when user clicks on the item to not remove the item, while those can be removed with click on the X, if we have "itemClick" event fired we can achieve this and all other scenarios.

## Minimal reproduction of the problem with instructions
1. Reproducible on this [stackblitz sample](https://stackblitz.com/edit/angular-qsmnve).

## Environment

Package versions:

```
v3.4.0
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by dimitar-pechev** [comment]
Similarly to https://github.com/telerik/kendo-angular/issues/1285, we're not moving for a preventable event, as that would not only be a breaking change, also it would disallow the usage of the `[(value)]` short-hand syntax. Either [disabled items](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/disabled-items/) can be used to prevent interaction with items on the list, or the component can be manipulated directly through its API to prevent deselecting certain items. [Here's an example](https://stackblitz.com/edit/angular-qsmnve-rvk4fd) for the latter.
