### ISSUE TITLE
Splitter can't collapse pane completely

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#1970]
## I'm submitting a...

* Bug report 

## Current behavior
When we have both panes with [collapsible]="true", the right pane can't be collapsed with the arrow button.

## Expected behavior
It should be collapsible in all cases

## Minimal reproduction of the problem with instructions
1.Open this [stackblitz sample](https://stackblitz.com/edit/angular-jtak8j?file=app/app.component.ts).
2.Try to collapse right pane through arrow button. 
## Environment

Package versions:

```
v3.2.0
```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Merlino** [comment]
Hi All,
I still have this issue in the version 3.3.2 of kendo-angular-layout. I noticed that this issue resolved in the 4.1.0 but I need it solved in the compatible version for angular 5.

Thank you for your support,

Andrea

**Comment by PetarMetodiev** [comment]
Hello Merlino,

We only support the latest official version of Angular and those currently being under LTS(Long Term Support). At the time of writing these versions are 6, 7 and 8. You can read more about this [here](https://www.telerik.com/kendo-angular-ui-develop/components/installation/requirements/#toc-angular).
