### ISSUE TITLE
Scrollview control 2.1 styling broken with kendo-theme-bootstrap 2.17.0

### ISSUE THREAD

**Issue by dlmelendez** [telerik/kendo-angular#1971]
## I'm submitting a...
* Bug report 

## Current behavior

  - Describe the current (faulty) behavior which is caused by the issue.

-  Current scrollview example is broken on the demo website: https://www.telerik.com/kendo-angular-ui/components/scrollview/  
- Pictures are showing in a staggered formation, showing more than one picture at a time.

  

## Expected behavior
Images loaded in the scrollview would remain bounded inside the control and be able to scroll through them. 
## Minimal reproduction of the problem with instructions

- Can reproduce with "@progress/kendo-theme-bootstrap": "2.17.0", and  "@progress/kendo-angular-scrollview": "2.1.0" in an Angular 7 application.

## Workaround
Reverting to "@progress/kendo-theme-bootstrap": "2.16.0" fixes the issue.

## Environment

Package versions:
Problem is reproducible on the demo site.

Browser:

- Chrome (desktop) Version 70.0.3538.110 (Official Build) (64-bit)
- Microsoft Edge 42.17134.1.0

System:
- TypeScript version: 3.1.6
- Node version: v10.14.1
- npm 6.4.1
- Platform:  Windows 10

**Comment by danielkaradachki** [comment]
Fixed in the latest versions of the themes and the site has been updated:
https://www.telerik.com/kendo-angular-ui/components/scrollview/
