### ISSUE TITLE
How to set width of Kendo multiselect width to widest option?

### ISSUE THREAD

**Issue by zhaoyouliang** [telerik/kendo-angular#1972]
## Current behavior
I use the  [popupSetting] = "{width:450,height:300}" for the dropdown-list component is ok .but kendo-multiselect component not work .I found the multiselect has a default min-width value .How to set the width correctly
-->

## Expected behavior

  set the width for the  kendo-multiselect

System:
Angular 6

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
