### ISSUE TITLE
Chart series data binding stopped working with async pipe

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#1973]
## I'm submitting a...
* Regression report 

## Current behavior
If chart series data is bound to an observable using async pipe and the observable emits value after some delay (e.g. http request delay) then chart isn't being shown.
This issue was introduced in kendo chart v3.5.0.

## Expected behavior
The chart should work if chart series data is bound to delayed observable using the async pipe.

## Minimal reproduction of the problem with instructions
Here is a [link](https://stackblitz.com/edit/angular-wynaa9) to StackBlitz.

**Comment by danielkaradachki** [comment]
fixed in 3.6.0
https://stackblitz.com/edit/angular-sjs5t3?file=app/app.component.ts
