### ISSUE TITLE
TreeView: allow checking/unchecking items by clicking on their labels

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#1974]
## I'm submitting a...
* Suggestion for improvement  

## Current behavior
Currently, it is possible to check/uncheck treeview items only by clicking on the checkboxes.

## Expected behavior
It would be great to have an option that allows checking/unchecking items by clicking on their labels because this is the default behavior for html input element with type="checkbox" ([more info](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Providing_a_bigger_hit_area_for_your_checkboxes))

**Comment by MarkusSchneider** [comment]
How should this work together with the selection of the tree-items? Is the item selected and checked when the label is clicked?

**Comment by ipeshev** [comment]
Feature available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.1.0

https://stackblitz.com/edit/angular-rchtkc?file=app/app.component.ts
