### ISSUE TITLE
Notification: $notification-shadow not applied

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#1975]
## I'm submitting a...

* Suggestion for improvement  

## Current behavior
On `notification\_theme.scss` file is possible to override variable `$notification-shadow` to add shadow to notification box. Actually it is just used on `k-notification-animation-container` element. That element is not generated on kendo for Angular implementation.

## Expected behavior
Just add easily box shadows on notification via scss variable approach.

## Environment

Package versions:

```
"@progress/kendo-angular-notification": "1.1.1",
"@progress/kendo-theme-default": "2.62.0",
```

Here we have few strategy to implement a workaround (it is css so just add shadow box on `k-notification`  will help to have same visual effect), anyway i really don't know if issue is related to default theme or kendo notification that doesn't generate `k-notification-animation-container` element. So you are free to move issue on kendo theme project or keep it here!
So thanks.

**Comment by elena-gancheva** [comment]
The issue has been fixed and is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themеs.
