### ISSUE TITLE
Grid : Locked column : PageSizes : Height issue

### ISSUE THREAD

**Issue by Sujoy-Banerjee** [telerik/kendo-angular#1977]
## I'm submitting a...

* Bug report

## Current behavior
On Grid if we use set `locked` to `true` for some columns and also use `pageSizes` property of `pageable` config, and set it to something like `[5,10,15,20,25]` .
Now if we set `PageSize` to `20`, grid will adjust to some height, but now if we change the `PageSize` to `5` , grid remains in same height. Thus showing blank space 

![image](https://user-images.githubusercontent.com/38027171/49732116-82159780-fc4b-11e8-8ed2-eeb3a0897e29.png)

## Expected behavior
Grid Height should get adjust with the page size. 

## Minimal reproduction of the problem with instructions

[STACKBLITZ](https://stackblitz.com/edit/angular-kendo-locked)

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version Version 67.0.3396.99 (Official Build) (64-bit)

System:
- TypeScript version:  5.6.0
- Node version: Node: v8.11.3 , NPM: 5.6.0
- Platform:  Windows

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.13.1

https://stackblitz.com/edit/angular-kendo-locked-w5xzbx?file=app/app.component.ts
