### ISSUE TITLE
Kendo sortable drops items when there are multiple zones

### ISSUE THREAD

**Issue by CorySuper** [telerik/kendo-angular#1979]
## I'm submitting a...

* Bug report 

## Current behavior

This occasionally does happen with less erratic behavior, but swinging the mouse around while holding a sortable item causes other entries of the list to disappear.

One thing I've noticed is that the entires are **only** dropped when the dragged item is released in a different zone. If it is returned to the list it originated from, then everything is fine.

![Alt Text](https://media.giphy.com/media/3BZUXAM2b15T9sdZzE/giphy.gif)
## Expected behavior

Sortable should be retaining all entries.
## Minimal reproduction of the problem with instructions
See: https://www.telerik.com/kendo-angular-ui/components/sortable/api/SortableComponent/#toc-data

The gif was made opening the palette example in stackblitz. The link is underneath 'data' and no alterations were made.

## Environment

Browser:

- Chrome (desktop) Version 71.0.3578.80 (Official Build) (64-bit)
- Firefox (desktop) Version 63.0.3 (64-bit)
- Internet Explorer (desktop) Version 11.1387.15063.0

**Comment by tapopov** [comment]
Thanks for reporting this regression @CorySuper, we will look into it as soon as possible.

**Comment by k290** [comment]
Also have this issue. It becomes more apparent when dropping between two sortable kendo grids that both have headers and footers that are disabled/not filterable

**Comment by danielkaradachki** [comment]
Merging with: https://github.com/telerik/kendo-angular/issues/2065
