### ISSUE TITLE
Grid group tag is not updated when column configuration is applied

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#1981]
When grouping is applied before the columns configuration array is available, the Group tag displays the field (as expected). However after column configuration is applied, and titles are available, the Group tag is not updated accordingly until interacted with (e.g. clicked):

[https://stackblitz.com/edit/angular-kqg9qa-ee35u5?file=app/app.component.ts](https://stackblitz.com/edit/angular-kqg9qa-ee35u5?file=app/app.component.ts)

**Comment by danielkaradachki** [comment]
fixed in 3.13.0:
https://stackblitz.com/edit/angular-kqg9qa-sjyw1h?file=app/app.component.ts
