### ISSUE TITLE
PanelBar does not animate when expanded/collapsed programmatically

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#1985]
## I'm submitting a...

* Bug report 

## Current behavior

PanelBar does not do its usual expand/collapse animation when expand state is toggled programmatically. However, once the user toggles the PanelBar item manually for the first time, PanelBar will always animate on expand/collapse regardless of what triggered it.

## Expected behavior

PanelBar should always animate on expand/collapse regardless of the type of trigger.

## Minimal reproduction of the problem with instructions

1. Select the "Toggle Expand" 
2. Notice expand animations aren't applied
3. Toggle the expand state of the PanelBar item manually with cursor
4. Notice expand animations are applied
5. Select the "Toggle Expand" button again
6. Notice expand animations are now applied

Demo:
https://stackblitz.com/edit/angular-azl3xz

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0

https://stackblitz.com/edit/angular-azl3xz-lvbqmj?file=app/app.component.ts
