### ISSUE TITLE
Panel Bar Item (Custom Template)

### ISSUE THREAD

**Issue by SuyogShah** [telerik/kendo-angular#1986]
I have requirement to prevent expand and collapse on panel title click (default behavior) but only can be done using custom button presents in template of panel bar title. Disable default click on panel bar title

How can we achieve this ?

**Comment by tsvetomir** [comment]
This issue tracker is for bug reports only. Please, submit a [support ticket](https://www.telerik.com/account/support-tickets) for further assistance.
