### ISSUE TITLE
[MultiSelect] When entering a long value it is not fully displayed

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1988]
## I'm submitting a...

* Bug report 

## Current behavior
If we have to enter a long value in the input of the MultiSelect, the value is not fully displayed. 

## Minimal reproduction of the problem with instructions
1. Enter a value holding the "A" key down, so the input becomes too long "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.."

check the behavior at the following example:
[https://stackblitz.com/edit/angular-i87svq-jtqcsf?file=app/app.component.ts](https://stackblitz.com/edit/angular-i87svq-jtqcsf?file=app/app.component.ts)

**Comment by josefkoller** [comment]
.k-multiselect kendo-taglist  ul  li {
            max-width: 100%;

            span:first-child {
                float: none;
                display: inline-block;
                max-width: 100%;
                word-wrap: break-word;
                text-overflow: ellipsis;
                overflow: hidden;
                white-space: nowrap;
                text-align: left;
            }
        }

**Comment by yanmariomenev** [comment]
Workaround - https://stackblitz.com/edit/angular-1aympa?file=app/app.component.ts
` 
    .k-multiselect .k-multiselect-wrap .k-searchbar {
      float: none;
    }`

**Comment by svetq** [comment]
Using the latest version of Kendo UI for Angular DropDowns the behavior is expected: https://stackblitz.com/edit/angular-sxgxdx-brbej3?file=src%2Fapp%2Fapp.component.ts

If additional improvements of the behavior are needed please open a feature request item in the [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).
