### ISSUE TITLE
Tooltip shows complete content of a related grid on mouse over scrollbar

### ISSUE THREAD

**Issue by idseefeld** [telerik/kendo-angular#1990]
## I'm submitting a Bug Report
The tooltip module has an issue with grids. 

## Current behavior
It shows the whole grid content when the mouse is over i.e. active horizontal scrollbar. 

## Expected behavior
If this is a feature, there should be at least an disable option.

## Minimal reproduction of the problem with instructions
You'll find a reproduction demo based on the grids overview DEMO here:
https://stackblitz.com/edit/angular-4y42jf?file=app%2Fapp.component.ts

Browser:

- Chrome (desktop) version 71.0.3578.98 (Offizieller Build) (64-Bit)

## Screenshots

![grid-with-shortend-column-titels](https://user-images.githubusercontent.com/866917/50145466-f25a9380-02b1-11e9-87ca-2df1899ca148.png)
![grid-with-shortend-column-titels-mouse-over-scrollbar](https://user-images.githubusercontent.com/866917/50145471-f5ee1a80-02b1-11e9-83eb-721a90b5ee59.png)

**Comment by dtopalov** [comment]
Example updated in the latest dev build:

[https://www.telerik.com/kendo-angular-ui-develop/components/tooltip/how-to/show-grid-cells-content/#toc-render-tooltips-for-grid-cells](https://www.telerik.com/kendo-angular-ui-develop/components/tooltip/how-to/show-grid-cells-content/#toc-render-tooltips-for-grid-cells)
