### ISSUE TITLE
Kendo Sortable does not update the 'index' template input variable

### ISSUE THREAD

**Issue by alexeykostevich** [telerik/kendo-angular#1993]
## I'm submitting a...

* Bug report 

## Current behavior

Kendo Sortable does not update the `index` template input variable after calling [addDataItem](https://www.telerik.com/kendo-angular-ui/components/sortable/api/SortableComponent/#toc-adddataitem) or [removeDataItem](https://www.telerik.com/kendo-angular-ui/components/sortable/api/SortableComponent/#toc-removedataitem).

## Expected behavior

Kendo Sortable should update the `index` template input variable to reflect the actual index.

## Minimal reproduction of the problem with instructions

1. Open the demo app
2. Click 'Delete' on any item except of the last one

https://stackblitz.com/edit/angular-evuwqd-fdtub4?file=app/app.component.ts

## Environment
Browser:

- Chrome (desktop) version 71
- Firefox version 64

System:
- TypeScript version: 3.1.6
- Node version: Node 10.11.0 / npm 6.4.1
- Platform:  Mac, Windows

The issue causes difficulties with building numbered lists and requires to handle indexes manually after a data change.

It can be worth-noting, that [Angular CDK Drag & Drop](https://material.angular.io/cdk/drag-drop/overview) handles such scenarios correctly. This stems from CDK allowing to use `NgForOf` to render data explicitly.

**Comment by tapopov** [comment]
Thanks for reporting this @alexeykostevich. We'll investigate further.

**Comment by tapopov** [comment]
Should be fixed in the latest dev version (v2.0.2-dev.201902131315).

**Comment by danielkaradachki** [comment]
Fixed in 2.1.0:

https://stackblitz.com/edit/angular-evuwqd-hsqvfn?file=app/app.component.ts
