### ISSUE TITLE
[kendoTextArea] auto-resizing stops working when formGroup changes

### ISSUE THREAD

**Issue by dummdidumm** [telerik/kendo-angular#1995]
## I'm submitting a...
* Bug report 

## Current behavior
When the instance of the formGroup changes, kendoTextArea no longer resizes on changes coming from the form. Changes from the user (typing into the area) are still reflected in resizes.

## Expected behavior
Changes from new formGroup should be reflected in resizing.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-d8wxv6

## Environment

Package versions:
```
InputsModule latest (v3.5.0)
```

Browser independent.

System independent.

**Comment by danielkaradachki** [comment]
fixed in 4.1.0

https://stackblitz.com/edit/angular-d8wxv6-qxd4xj?file=app/app.component.ts
