### ISSUE TITLE
Loading text does not appear while grid is loading

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#1996]
## I'm submitting a...
* Bug report 

## Current behavior

The loading icon works fine, but the grid does not display the loading text while it is loading, even after setting a custom loading message.

## Expected behavior
The grid should display the loading text while it's loading.

## Minimal reproduction of the problem with instructions
1. Load a grid
2. As it's loading, notice the default message for empty data is displayed instead of the loading message
[Demo](https://stackblitz.com/edit/angular-zfes7p?file=app%2Fapp.component.ts)

## Environment

Package versions:
`kendo-angular-grid@3.10.2`

**Comment by dtopalov** [comment]
[Custom NoRecords message](https://www.telerik.com/kendo-angular-ui/components/grid/globalization/#toc-custom-messages) seems to be displayed as expected when properly set:

[https://stackblitz.com/edit/angular-zfes7p-rqxepz?file=app/app.component.ts](https://stackblitz.com/edit/angular-zfes7p-rqxepz?file=app/app.component.ts)

Let me know if I am missing something.

**Comment by LaniMoo** [comment]
Yes, the `noRecords` message works fine but I'd like to use the `loading` text instead. I could technically just do `noRecords="Loading..."` but I wouldn't want that to show up when I actually do have no records.

According to your docs, there's a `loading` message available: https://www.telerik.com/kendo-angular-ui/components/grid/api/CustomMessagesComponent/#toc-loading

Apologies, I forgot to include this in my original demo but it's in there now:
`<kendo-grid-messages loading="Loading..."></kendo-grid-messages>`

**Comment by dtopalov** [comment]
After further discussing this issue with our Grid developers, I can inform you that the "loading" message is hidden on purpose, and it is meant for accessibility reasons only. This is why not displaying it is the expected and designed behavior. You can still change the message (via setting the Grid messages).

The built-in Grid loading indicator is the mask with loading spinner, but you can customize it and add any message that you would like to be displayed like in the following example:

[https://stackblitz.com/edit/angular-ouvuya-wqjlfi?file=app/app.component.ts](https://stackblitz.com/edit/angular-ouvuya-wqjlfi?file=app/app.component.ts)

We will make sure to update the documentation accordingly and make the purpose of the "loading" message clearer.
