### ISSUE TITLE
kendoGridSelectBy directive overrides grid's selectable settings

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#1997]
## I'm submitting a...
* Bug report 

## Current behavior
Grid is still selectable even if `[selectable]="false"` if the `kendoGridSelectBy` directive is included. I have a scenario where I need the grid to be conditionally selectable which is why I have it set this way. 

## Expected behavior
`selectable` grid option should have higher priority over `kendoGridSelectBy` and not be selectable if set to false.

## Minimal reproduction of the problem with instructions
1. Set selectable to false but also include kendoGridSelectBy directive.
2. Click on a row
3. Notice it still gets selected
[Demo](https://stackblitz.com/edit/angular-3hf5gz?file=app/app.component.ts)

## Environment

Package versions:
`kendo-angular-grid@3.10.2`

**Comment by LaniMoo** [comment]
Workaround worked perfectly, thank you!

**Comment by danielkaradachki** [comment]
Documented as the recommended approach to toggle the selection:
https://www.telerik.com/kendo-angular-ui-develop/components/grid/selection/#toc-persisting-the-selection
