### ISSUE TITLE
please add provider for "Persian Calendar" & "Hijri Calendar" in Datepicker Components

### ISSUE THREAD

**Issue by meisamhasani** [telerik/kendo-angular#2000]
hi,

It is my wish that ,
add provider for "Persian Calendar" & "Hijri Calendar" in Datepicker Components

Impatiently waiting for this feature 

Please do not disappoint me

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. For feature requests please open an item in our  [feedback portal](https://feedback.telerik.com/kendo-angular-ui/).
