### ISSUE TITLE
kendo-datepicker does not work with kendo-textbox-container floating labels

### ISSUE THREAD

**Issue by groogiam** [telerik/kendo-angular#2001]
```html
      <kendo-textbox-container floatingLabel="Date of Birth">
        <kendo-datepicker [(value)]="vm.DateOfBirth"></kendo-datepicker>
      </kendo-textbox-container>
```

This code results in the following rendered output and error.

![image](https://user-images.githubusercontent.com/1992395/50386620-6af98f80-06b8-11e9-8d87-ddf8639473c3.png)

ERROR Error: The TextBoxContainer requires an element with the kendoTextBox or kendoTextArea directive or a forms-bound component to function properly.
    at TextBoxContainerComponent.push../node_modules/@progress/kendo-angular-inputs/dist/es/textbox/textbox-container.component.js.TextBoxContainerComponent.ngAfterContentInit 

The date picker is an input control just like a textbox and should work with material floating labels.

**Comment by svetq** [comment]
same as #1849 a fix is provided in the latest dev version of the DateInputs package

**Comment by danielkaradachki** [comment]
In order to avoid the error you should use a form bound control as explained [here](https://www.telerik.com/kendo-angular-ui/components/inputs/api/TextBoxContainerComponent/#toc-textboxcontainercomponent):

https://stackblitz.com/edit/angular-9uu6wm?file=app/app.module.ts
