### ISSUE TITLE
[Sortable]: Inputs cannot be focused in IE11 under Windows 7 when a Sortable is present

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2002]
Regular HTML Input elements cannot be focused when there is a Sortable component in the page. Observable on Windows 7 Pro 64 Bit on a regular desktop machine, and IE version 11.0.9600.19230.

No 3rd-party plugins installed or Javascript errors in the console.

Issue observed in the following example:

[https://stackblitz.com/edit/angular-t7vi5k-rq49hv?file=app/app.component.ts](https://stackblitz.com/edit/angular-t7vi5k-rq49hv?file=app/app.component.ts)

The example is working as expected in IE v. 11.472.17134.0

Internal information: video and further details available in support ticket with ID 1380862

**Comment by ipeshev** [comment]
Works [properly](https://stackblitz.com/edit/angular-mizblr-rvr7uj?file=app/app.component.ts) with[ latest dev versions](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of @telerik/kendo-draggable and @progress/kendo-angular-sortable.

**Comment by danielkaradachki** [comment]
Fix released in 2.1.0
