### ISSUE TITLE
Exaples not working: XHR error (404) loading https://unpkg.com/hammerjs@2.0.8

### ISSUE THREAD

**Issue by ppulwey** [telerik/kendo-angular#2003]
## I'm submitting a...
Documentation issue

## Current behavior
All Examples on https://www.telerik.com/kendo-angular-ui/components fail with error "Error: Error: XHR error (404) loading https://unpkg.com/hammerjs@2.0.8" shown in console

## Expected behavior
Examples work

## Minimal reproduction of the problem with instructions
Open any page e.g. https://www.telerik.com/kendo-angular-ui/components/buttons/button/

Browser:
- Chrome (desktop) Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by ppulwey** [comment]
Sorry for the late reply. Can confirm that it works again. Thanks.

**Comment by ppulwey** [comment]
I get this error again here: https://www.telerik.com/kendo-angular-ui/components/popup/

![image](https://user-images.githubusercontent.com/20904579/50967064-51897d80-14d7-11e9-80f7-7b48bfd028af.png)

**Comment by tsvetomir** [comment]
`ERR_BLOCKED_BY_CLIENT` usually shows up when a browser extension, e.g. an ad-blocker filters the request. Check if you still get the same error in private mode.

**Comment by ppulwey** [comment]
The problem is the 404 for hammer.js on unpkg.com. If you try to follow the link directly, you'll also get the 404: https://unpkg.com/hammerjs@2.0.8/index.js

**Comment by tsvetomir** [comment]
Should be fixed now.

**Comment by ppulwey** [comment]
> Should be fixed now.

Confirmed
