### ISSUE TITLE
Why colorpicker is still not done????? why

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#2007]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Current behavior

no colorpicer component
## Expected behavior

add colorpicer component

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Raisolution** [comment]
Hi @jiangyh1024,

We are currently considering the ColorPicker component for one of our upcoming releases, but no specific time-span is currently set.

I am closing this as it is not an issue. Please use our [feedback portal](https://feedback.telerik.com/kendo-angular-ui) for feature requests.
