### ISSUE TITLE
Alignment issue: month picker not showing month full name when you have less than 5 month to select in month picker

### ISSUE THREAD

**Issue by BhushanChandak** [telerik/kendo-angular#2009]
Alignment issue: month picker not showing month full name when you have less than 5 month to select in month picker
`<kendo-datepicker
        
         [bottomView]="'year'"
          [topView]="'decade'"
        [format]="'MMMM yyyy'"
        [(value)]="value"
        [min]="min"
        [max]="max"
    ></kendo-datepicker>`

`export class AppComponent {
public value: Date;

public min: Date= new Date(2018,10,1);

public max: Date= new Date(); 
}
`

**Comment by ipeshev** [comment]
Can be reproduced in following [stackblitz sample](https://stackblitz.com/edit/angular-nuf17r?file=app/app.component.ts)

**Comment by ipeshev** [comment]
@BhushanChandak the issue that we see on the stackblitz sample is that when switched to 2019 you can not select JAN.

**Comment by BhushanChandak** [comment]
![image](https://user-images.githubusercontent.com/21455547/50956453-b649d580-14e1-11e9-8a5d-a1cd56ae028a.png)

**Comment by BhushanChandak** [comment]
@ipeshev please see above screenshot. It looks like this when we click on datepicker.

**Comment by ipeshev** [comment]
@BhushanChandak we need more details to reproduce it, like browser and version.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Released in v3.7.2

**Comment by TUSHARDM** [comment]
After taking this update I got a new issue.
1. I am sharing 4 screenshots to batter understand this issue. 
![first-open-issue-resolved](https://user-images.githubusercontent.com/5736855/56484687-8487d800-64ee-11e9-9b89-ae54fa769830.PNG)
![click-on-earlier-month-its-good](https://user-images.githubusercontent.com/5736855/56484712-99fd0200-64ee-11e9-989b-d905c0996865.PNG)
![again-click-on-2019-its-blank](https://user-images.githubusercontent.com/5736855/56484719-9ff2e300-64ee-11e9-93ba-1bba12e3da2c.PNG)
![scroll-somewhat-up-it-reappears](https://user-images.githubusercontent.com/5736855/56484728-a97c4b00-64ee-11e9-8fb4-dfe617b066a9.PNG)

**Comment by TUSHARDM** [comment]
so, in the 1st glance when I open it it's now good. all months appear.
2nd time I click on earlier year the months shows up. that's good.
3rd time I click on 2019 I see all blank that's not good. (Bug)
4th time as I scroll as earlier time. it shows correct behaviour as earlier.
so, My expectation is when I click between the years current or earlier the current years months should be seen directly and should not hide behind the scroll. the above 4 screenshots are attached. To understand this bug. Thanks.

**Comment by ipeshev** [comment]
@TUSHARDM  could you try with [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), on this [updated sample](https://stackblitz.com/edit/angular-nuf17r-p1pvqh?file=app/app.component.ts) ?

**Comment by TUSHARDM** [comment]
@ipeshev The expected behavior of date control is correct in  "@progress/kendo-angular-dateinputs": "dev", in the updated sample which you shared. When you are planning to push it in kendo control release. so I can use it.  Thanks.
