### ISSUE TITLE
Datepicker autocorrects May to Mar

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2010]
## I'm submitting a...

* Bug report 

## Current behavior
When, the DatePicker does not have a valid JavaScript Date value, we cannot input the month of May via the keyboard. Instead, we will get the month of March. 

## Minimal reproduction of the problem with instructions
[https://stackblitz.com/edit/angular-eahgkd-6pjyv1?file=app/app.component.ts](https://stackblitz.com/edit/angular-eahgkd-6pjyv1?file=app/app.component.ts)

1. Try to enter "May" for the month field. 
2. Select a date and then try to implement the first point.

**Comment by ipeshev** [comment]
Fixed in [latest development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.7.0

https://stackblitz.com/edit/angular-eahgkd-d8vs7a?file=app/app.component.ts
