### ISSUE TITLE
The default browser's tooltip is displayed in Microsoft Edge

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2011]
## I'm submitting a...

* Bug report 

## Current behavior
When using the Tooltip in Microsoft Edge browser, the default browser's tooltip is opened as well.

![image](https://user-images.githubusercontent.com/20015190/50755043-69a39780-1260-11e9-889a-f34ee3ef5766.png)

The issue occurs when hovering the item somewhere on its boundaries. 

## Minimal reproduction of the problem with instructions

The issue can be reproduced on the following page opened with Edge:
[https://www.telerik.com/kendo-angular-ui/components/tooltip/](https://www.telerik.com/kendo-angular-ui/components/tooltip/)

**Comment by elena-gancheva** [comment]
This issue is caused by a bug in Edge.
For more information follow the [link](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20639726/).
