### ISSUE TITLE
Scheduler - Missing DOCTYPE in root html breaks styles

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2013]
## I'm submitting a...

* Bug report 

## Current behavior

When index.html has no DOCTYPE, scheduler css styles are broken.

## Expected behavior

Scheduler should be properly styled without DOCTYPE in root html.

## Minimal reproduction of the problem with instructions

1. remove ```<!DOCTYPE html>``` in your index.html file (not in Stackblitz - there it works fine)

## Environment

Package versions:

```
@progress/kendo-angular-scheduler@0.3.4
```

Browser:

- Chrome (desktop) version XX

 #System:
- TypeScript version: 2.9.2
- Node version: 10.12.0
- Platform:  #Windows

**Comment by danielkaradachki** [comment]
Quirks mode is not supported. You should always specify a DOCTYPE.
