### ISSUE TITLE
DatePicker issue with patterns

### ISSUE THREAD

**Issue by slyerrr** [telerik/kendo-angular#2016]
![datepicker-issue](https://user-images.githubusercontent.com/2980929/50966605-b7750580-14d5-11e9-8fe2-fcaabf6edb01.png)

## I'm submitting a question regarding a issue i have with datepicker, once following examples from documentation i got error like in screenshot. why is this happening ?

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by danielkaradachki** [comment]
Please follow the issue template and provide a runnable sample that demonstrates the error, or at least the code that you are using.

**Comment by danielkaradachki** [comment]
Will close the issue for now and will reopen it once there is sufficient information to replicate the error.
