### ISSUE TITLE
SplitButtonComponent - open property doesn't update with open state of popup

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#202]
If you set the property that is binded to the open property to true the popup is visible, but if the popup closes for another reason then setting the open property to false the binded property doesn't get changed to false. It stays true.

**Comment by Stamo-Gochev** [comment]
@djarekg The scenario will be investigated. I will notify you when a fix is available.

**Comment by nlazarov** [comment]
@djarekg - the open property of the `SplitButtonComponent` exposes a one-way binding. This means that the associated property from the components that uses the splitbutton can change the value of the open property in the SplitButtonComponent, but not vise versa.

Please, let me know if there is another use-case that I am missing?

**Comment by djarekg** [comment]
How are you supposed to know if the button is closed?

**Comment by nlazarov** [comment]
That is a valid case, indeed. Do you think that adding events for open and close of the popup would be a good fit for this scenario?

**Comment by djarekg** [comment]
That or provide another way to determine if the popup is currently open. Although, i would prefer two-binding on the open property.

**Comment by valchev** [comment]
Implemented in v0.22.0
