### ISSUE TITLE
New Scheduler doesn’t work with OnPush change detection

### ISSUE THREAD

**Issue by jcastillo-ait-asia** [telerik/kendo-angular#2024]
## I'm submitting a...

* Bug report 

## Current behavior

The new scheduler doesn’t work with OnPush change detection

## Expected behavior

See [https://angular-1v3oyf.stackblitz.io](https://angular-1v3oyf.stackblitz.io)

**Comment by danielkaradachki** [comment]
Seems that only the editing is not working with OnPush:
https://stackblitz.com/edit/angular-1v3oyf-e57tjx?file=app/app.component.ts
Am I missing something else?

**Comment by jcastillo-ait-asia** [comment]
Yes, 1. the edit window doesn’t appear and 2. The form fields on the edit form do not update (e.g. try to select some of the recurring form fields). Also having an issue getting updated form values when saving / updating.

**Comment by danielkaradachki** [comment]
Thanks for clarifying. We will look into it.

**Comment by danielkaradachki** [comment]
Should be fixed in 0.8.0

https://stackblitz.com/edit/angular-1nkd93?file=app/app.component.ts
