### ISSUE TITLE
Scroll View is not compatible with Angular 2.4.4

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#203]
As per title the scroll view is not compatible with Angular 2.4.4
[Plunker Link](http://plnkr.co/edit/zwChS7796OTdaU6CCHO5?p=preview)

**Comment by tsvetomir** [comment]
Thanks for the heads-up. The issue seems to affect operation with Angular 2.4.3 as well.

**Comment by ag-petrov** [comment]
The issue is now resolved please upgrade to v0.8.0
