### ISSUE TITLE
The height of a PanelBar in expand mode is not properly set

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2030]
## I'm submitting a...

* Bug report 

## Current behavior
The last item of a PanelBar is not fully displayed due to improper height.

It looks like the height of the expanded item is not calculated properly, which causes the issue. 

## Minimal reproduction of the problem with instructions
See the example from the following article:
[https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/expand-modes/](https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/expand-modes/)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.3.0
