### ISSUE TITLE
Grid: Columnmenu popup should open on top if space is too small to show menu.

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#2031]
## I'm submitting a...

* Bug report 
## Current behavior
When the grid is positioned at the bottom of a page and the height of the grid is too small to render the column menu, the height of the whole page grows, a scroll bar is rendered.
If the page is scrolled, the column menu flips above the grid.
Sometimes the column menu is not displayed.

## Expected behavior

The column menu should open above the grid, if the height is not sufficient to render the menu.

## Minimal reproduction of the problem with instructions

Run example:
https://stackblitz.com/edit/angular-wa5t37?embed=1&file=app/app.component.ts
Open "field 2" column menu -> filter. The Filter Dialog changes the height of the whole page (scrollbar is rendered).
Scroll -> Filter Dialog is rendered above the grid, scroll bar gets hidden.
## Environment

Browser:

- Chrome (desktop) 71.0.3578.98

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-grid v4.5.0`
