### ISSUE TITLE
Kendo sortable "activeItemClass" doesn't working correct

### ISSUE THREAD

**Issue by myushchenko** [telerik/kendo-angular#2032]
## I'm submitting a...
Regression report (Works in v1.1.1. Stopped working in 2.0.1)

## Current behavior
Now **activeItemClass** has different behavior compared to v1.1.1.  After drag item active state doesn't disappear and only changed when start drag another item. I haven't found any ways when active state can be removed.

## Expected behavior
When item dropped, active class should be removed for current item as in v.1.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-angular-ui/components/sortable/templates/

## Environment

Package versions:
```
    "@angular/animations": "7.2.1",
    "@angular/common": "7.2.1",
    "@angular/compiler": "7.2.1",
    "@angular/core": "7.2.1",
    "@angular/forms": "7.2.1",
    "@angular/platform-browser": "7.2.1",
    "@angular/platform-browser-dynamic": "7.2.1",
    "@angular/router": "7.2.1",
    "@progress/kendo-angular-buttons": "4.3.2",
    "@progress/kendo-angular-dateinputs": "3.5.4",
    "@progress/kendo-angular-dropdowns": "3.4.2",
    "@progress/kendo-angular-excel-export": "2.2.0",
    "@progress/kendo-angular-grid": "3.10.2",
    "@progress/kendo-angular-inputs": "3.5.0",
    "@progress/kendo-angular-intl": "1.6.1",
    "@progress/kendo-angular-l10n": "1.3.0",
    "@progress/kendo-angular-layout": "3.2.0",
    "@progress/kendo-angular-sortable": "^2.0.1",
    "@progress/kendo-angular-upload": "4.2.2",
    "@progress/kendo-data-query": "1.5.0",
    "@progress/kendo-drawing": "1.5.8",
    "@progress/kendo-file-saver": "1.0.7",
    "@progress/kendo-ui": "2018.3.1219",
    "bootstrap": "3.3.7",
    "chroma-js": "2.0.2",
    "core-js": "2.6.2",
    "jquery": "1.11.1",
    "jquery-ui": "1.12.1",
    "knockout": "3.0.0",
    "knockout-mapping": "2.5.0",
    "moment": "2.18.1",
    "ngx-bootstrap": "3.1.4",
    "rxjs": "6.3.3",
    "rxjs-compat": "6.3.3",
    "sha1": "1.1.1",
    "toastr": "2.1.2",
    "tslib": "1.9.3",
    "underscore": "1.9.1",
    "zone.js": "0.8.28"
```

Browser:
- Chrome (desktop) version 71

System:
- TypeScript version: 3.2.2
- Node version: 10.15.0
- Platform:  Windows

**Comment by tapopov** [comment]
Thanks for reporting this @myushchenko , we will look into it as soon as possible.

**Comment by andrexx** [comment]
@tapopov  Could you provide any schedule/estimation for fix? Can I have duplicate request via support ticket?
p.s. don't forget to fix unsubscribtion for dragLeaveSubscription :)

**Comment by PeterStaev** [comment]
I just stumbled uppon this nasty bug. The current workaround I found is to set the `activeIndex` to `-1` in the `dragEnd` event. You can see an example [here](https://stackblitz.com/edit/angular-kzc4zi?file=app/app.component.ts) (look at the second sortable widget).

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-sortable`

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-sortable v3.0.3`
