### ISSUE TITLE
When "text overflow:ellipsis" Text come proper in browser but when we export it in pdf using  <kendo-pdf-export> it break

### ISSUE THREAD

**Issue by BhushanChandak** [telerik/kendo-angular#2033]

**Comment by BhushanChandak** [comment]
I am using <kendo-pdf-export> to make pdf of page.
On this page i am using kendo grid. Heading of grid have css properties "text-overflow:ellipsis".
On browser 'Heading text' get ellipsis but when we export it as pdf full text came and overlap with column menu. Please see below screenshot.

**Comment by BhushanChandak** [comment]
![image](https://user-images.githubusercontent.com/21455547/51516685-335c3f80-1e3e-11e9-8ba8-d6563ea4b8d2.png)

**Comment by BhushanChandak** [comment]
![image](https://user-images.githubusercontent.com/21455547/51516792-8f26c880-1e3e-11e9-84ef-d45dc6c6be98.png)

**Comment by danielkaradachki** [comment]
This is a limitation of the PDF export documented here:
https://www.telerik.com/kendo-angular-ui/components/drawing/limitations-browser-support/#toc-elements-and-styles
