### ISSUE TITLE
Editor cannot be installed via schematics (ng add ...) in an Angular 7 app

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2034]
An attempt to install the Editor via ng add @progress/kendo-angular-editor results in the following warnings and error:

ng add @progress/kendo-angular-editor

Installing packages for tooling via npm.

npm WARN @progress/kendo-angular-editor@0.2.0 requires a peer of @angular/common@4 - 6 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-editor@0.2.0 requires a peer of @angular/core@4 - 6 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-editor@0.2.0 requires a peer of @angular/forms@4 - 6 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-editor@0.2.0 requires a peer of @progress/kendo-angular-dialog@^3.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-editor@0.2.0 requires a peer of @progress/kendo-angular-toolbar@^0.3.0 but none is installed. You must install peer dependencies yourself.

+ @progress/kendo-angular-editor@0.2.0

Installed packages for tooling via npm.
File **node_modules/@progress/kendo-angular-/package.json** does not exist.

This results in dependencies and the theme not being installed at all.

**Comment by tsvetomir** [comment]
Fixed in v0.2.1
