### ISSUE TITLE
<kendo-autocomplete> does not fire event in mobile without backspace works on desktop

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2035]
## I'm submitting a...

* Bug report 
* Suggestion for improvement  

## Expected behavior
It should populate autocomplete list as I type on each keystroke or after first 3 keystrokes.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 71.0.3578.98 (no issue)
- Chrome (Android) version 71(mobile browser with issue)
- Firefox version 64.0.1 (mobile browser with issue)
- Edge version 42.17134.1.0 (no issue)

System:
-Android 8.1.0 Mobile
- Platform:   Desktop

**Comment by dimitar-pechev** [comment]
Also reported in ticket `1385283`. 

The described undesired behavior is present in all the **DropDown** components on Android devices when using a mobile keyboard with suggestions/auto-correction enabled.

Related to #1958.

**Comment by dimitar-pechev** [comment]
Fixed in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-dropdowns` **v3.5.2-dev.201903141745**.

**Comment by tsvetomir** [comment]
Shipped in v3.5.2
