### ISSUE TITLE
Using kendo angular dialog in service

### ISSUE THREAD

**Issue by saikiranmarripati** [telerik/kendo-angular#2036]
I have an Angular application in which I'm trying to use DialogService as a service to use in different components across my app to prompt users an alert or to show a form. basically, I need to have a single dialog service across my App.

## Current behavior
I injected my service across components when I navigate between components the dialog service is not prompting. for an unknown reason.

I included a dialog container in **app.component.html** like below

`<div kendoDialogContainer></div>`

**My service:**

``` 
@Injectable({
  providedIn: "root"
})
export class GlobalService {
  private apiUrl: string = environment.cartApiURL;

  constructor(
    private http: HttpClient,
    private errorHandler: ErrorServiceHandler,
    private dialogService:DialogService
  ) {}

public showValidationAlert(msg="") {
  
  const dialogRef: DialogRef = this.dialogService.open({
    title: "Alert",
    // Show component
    content:msg!=""?msg:"Please review the missing required fields that are highlighted in RED!",
    actions: [{ text: "Ok", primary: true }]
  });

  return dialogRef.result.subscribe();

}
```

When i debug the call goes and executes **open** method but the dialog is not prompting.

## Expected behavior
It should prompt in all components, there should be an option to toggle action buttons conditionally.

## Environment

Angular CLI: 6.1.5
Node: 11.6.0
OS: win32 x64
Angular: 6.1.10

## Browser

Chrome (desktop) Version 71.0.3578.98 (Official Build) (64-bit).

**Comment by danielkaradachki** [comment]
Could you provide a runnable sample that demonstrates the issue? I tried to replicate it but to no avail:
https://stackblitz.com/edit/angular-wl3etn-v4ygrg?file=app%2Fapp.component.ts

**Comment by Raisolution** [comment]
We are closing this as it was not reproduced. Feel free to open it and provide a runnable example that demonstrates the issue.
