### ISSUE TITLE
Kendo Sortable is not reflecting changes in data array in binding. + dragging issue on image

### ISSUE THREAD

**Issue by KPtry** [telerik/kendo-angular#2045]
## I'm submitting a...

* Regression report (worked in 1.1.1, not working in 2.0.0 and 2.0.1)
* Bug report (appeared from v 2.0.0)

## Current behavior
I have a sortable component with a defined ng-template containing an image and delete button for each item.
When I am clicking on Delete button - UI is not reflecting correctly the data array items (still represents old items) and if I'm trying to drag and drop deleted item - it creates null objects in target array.
Also when I am draggin by image - it sticks the preview to the mouse cursor and is not releasing it automatically when I release mouse button. I need to do a mouse click to release it 

## Expected behavior
- Dragged item should be released when I release mouse button in case when I drag by image (was working in v.1.1.1.)
- UI should reflect changes in items array connected when items are deleted

## Minimal reproduction of the problem with instructions
Demo here: https://stackblitz.com/edit/angular-hqoei2?file=app/app.component.ts

## Environment

Package versions:

```

```

Browser:
- Chrome (desktop) version  71
- IE version 11
- Edge version 41

System:
- TypeScript version: 3.2.2
- Node version: 8.12
- Platform:  Windows

**Comment by danielkaradachki** [comment]
You should update the array instance in order for Angular to detect a change:
https://stackblitz.com/edit/angular-hqoei2-3xnise?file=app/app.component.ts

Updating the existing array will not work because, v2 of the Sortable component no longer modifies and works with the original data.

**Comment by ghous92** [comment]
Hi Daniel , 
Thanks for the update ,Using Kendo sortable when i am trying to drag and drop and fire a event from the dragEnd event i am getting transition state array where the in this example if you see the console when you try dragging china inside grp2 , china is there in grp2 as well as at outer index 1 

https://stackblitz.com/edit/kendo-hierarchy-sortable?file=app/app.component.ts

Can you help me what should be the work around here , as i need to fire a NGRX event on drag end event
