### ISSUE TITLE
Kendo Switch Doesn't Display Labels with Bootstrap or Material Themes

### ISSUE THREAD

**Issue by justincts1975** [telerik/kendo-angular#2047]
## I'm submitting a bug with the newer version of Kendo Switch, You don't have to go any further than your own website demo (with bootstrap or material themes). https://www.telerik.com/kendo-angular-ui/components/inputs/switch/labels/

* Regression report 

## Current behavior
Labels aren't rendered in the switch.

## Expected behavior
Labels should be rendered in the switch.

## Minimal reproduction of the problem with instructions
Just look at your own website with Bootstrap or Material themes. https://www.telerik.com/kendo-angular-ui/components/inputs/switch/labels/

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 71.0.3578.98

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:  

![image](https://user-images.githubusercontent.com/35084450/51786333-aca2ad80-2130-11e9-998d-7b477b130c90.png)

**Comment by dtopalov** [comment]
Hi,

The described layout is by design. To customize it, you can use overwrite the built in styling, as described here:

[https://github.com/telerik/kendo-themes/issues/567#issuecomment-456770102](https://github.com/telerik/kendo-themes/issues/567#issuecomment-456770102)
