### ISSUE TITLE
Editing cell in grid with presented locked column and horizontal scrolling in IE provide to unwanted scrolling to left

### ISSUE THREAD

**Issue by DaniilPalii** [telerik/kendo-angular#2049]
## I'm submitting a...

* Bug report 

## Current behavior

In grid that has locked column, in-cell editing and horizontal scrolling when scroll to right and click on editable cell, grid become scroll to left and cell with opened editor become near right border. After edited cell will closed - grid become scroll to left maximally. This behavior was observed on IE 11. In Chrome all is ok. 

## Expected behavior

After click on cell grid doesn't make any scroll, as in Chrome.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-li5xjx-wnwnmc

## Environment

Problem is reproducible on demo site.

Browser:
- IE version 11

**Comment by danielkaradachki** [comment]
Released in 3.13.1

**Comment by DaniilPalii** [comment]
Thank You!
