### ISSUE TITLE
internationalization - Loading locales Dynamically 

### ISSUE THREAD

**Issue by Sujoy-Banerjee** [telerik/kendo-angular#2052]
## I'm submitting a...

* Bug report 

## Current behavior
Many applications we get to know about user's culture after he/she login into application, same is the case with our application.
But in Kendo to load local information we need to write import statement like,
 
`import '@progress/kendo-angular-intl/locales/fr/all';`

Here we are just importing local information for 'fr' culture 

## Expected behavior
Will it be possible to import of local dynamically?
Else  I have to put a bunch of import statement to support different locals, like this,
`import '@progress/kendo-angular-intl/locales/de/all';` 
`import '@progress/kendo-angular-intl/locales/da/all';`
`import '@progress/kendo-angular-intl/locales/nl/all';`
`import '@progress/kendo-angular-intl/locales/en-NZ/all';`
`import '@progress/kendo-angular-intl/locales/es/all';`
`import '@progress/kendo-angular-intl/locales/fr-CA/all';`
`import '@progress/kendo-angular-intl/locales/zh/all';`

## Minimal reproduction of the problem with instructions

  Find an example in [the plnkr](https://next.plnkr.co/edit/kdaLcX4xsP50UXuN?preview) that looks similar to this case. Where **app.module.ts** file contains a bunch of import statement.
  

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version Version 67.0.3396.99 (Official Build) (64-bit)

System:
- TypeScript version:  **5.6.0**
- Node version: **Node: v8.11.3 , NPM: 5.6.0**
- Platform:  **Windows**

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
