### ISSUE TITLE
Question : how to set kendo text box default as invalid (highlighted red). 

### ISSUE THREAD

**Issue by ironicicon** [telerik/kendo-angular#2055]
## I'm submitting a Question : 

I would like to know how by default when the user clicks on Add button, the text box should be highlighted with red color border (all required fields) 

Right now I am getting the red color border only when the user is focusing on the control which has a required attribute 

Stack Blitz Link : https://stackblitz.com/edit/angular-jl4xpx

## Current behavior
Current behavior : I am getting the red colour border only when the user is focusing on the control which has a required attribute 

## Expected behavior

I would like to know how by default when the user clicks on Add button, the text box should be highlighted with red color border (all required fields)  - without focusing onto that element

## Minimal reproduction of the problem with instructions

Stack Blitz Link : https://stackblitz.com/edit/angular-jl4xpx

1.) Click on add button
2.) By Default, the textbox which is not focused (having required attribute is not highlighted as red )
3.) Only after focusing in and focusing out, the red border appears (ng-invalid class). 

Browser:
- Chrome (desktop) version 71

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
