### ISSUE TITLE
Grouping is not working consistently when [navigable] is set to true

### ISSUE THREAD

**Issue by AKrasovski** [telerik/kendo-angular#2057]
## I'm submitting a...
* Bug report

## Current behavior
When navigable=true and grouping functionality is turned on, you cannot re-add a column to grouping pane. The only workaround is to add another column to group and remove it. This also happens if drag drop was unsuccessful first time (lets say you missed the drop area).

## Expected behavior
You should be able to re-add same column to group

## Minimal reproduction of the problem with instructions
Take your basic example for grouping (https://www.telerik.com/kendo-angular-ui/components/grid/grouping/).

I have forked stackblitz for you
https://angular-6gzvjs.stackblitz.io

Steps:
1) add a column to grouping
2) remove this column from grouping
3) try to add same column to grouping again - you are not able.

Variation:
1) try to drag column to grouping but drop it outside of the grid (so drop is unsuccesfull)
2) to to add it again - you cannot.

## Environment

Package versions:
@progress/kendo-angular-grid@3.11.0

Browser:
- Chrome (desktop) version XX

System:
Windows

**Comment by ipeshev** [comment]
Fix available in [latest development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
fixed in 3.13.0
https://stackblitz.com/edit/angular-6gzvjs-vu74ko?file=app/app.component.ts
