### ISSUE TITLE
TypeError: BehaviorSubject.BehaviorSubject is not a constructor in PROD mode

### ISSUE THREAD

**Issue by PrakashPasalkar** [telerik/kendo-angular#2059]
## I'm submitting a PROD build issue for Kendo Angular UI component.

* Regression report 
* Bug report 
* Suggestion for improvement  
* Documentation issue 

## Current behavior

I am have created Angular 6 project using Web-pack configuration. And using some of the Kendo Angular UI (Free Trial) component such as Slider, Buttons, Accordion and etc. in project. Everything is working flawless in DEV mode. But when creating a PROD build facing mentioned issue. I think issue is with rxjs package bundling in web-pack.
So Team, Can you please give the resolution on this issue?
Thanks in advance :-)

## Expected behavior

Application should run in PROD mode also.
## Minimal reproduction of the problem with instructions

1. npm install
2. npm run build (webpack -p --progress --env.prod)
3. Check the application in browser (TypeError: rxjs_BehaviorSubject.BehaviorSubject is not a constructor)

## Environment

Package versions:

```
Please find below package information for kendo and rxjs
    "@progress/kendo-angular-buttons": "^4.3.2",
    "@progress/kendo-angular-charts": "^3.6.0",
    "@progress/kendo-angular-dateinputs": "^3.5.4",
    "@progress/kendo-angular-dropdowns": "^3.4.2",
    "@progress/kendo-angular-excel-export": "^2.3.0",
    "@progress/kendo-angular-grid": "^3.12.0",
    "@progress/kendo-angular-inputs": "^4.0.0",
    "@progress/kendo-angular-intl": "^1.6.1",
    "@progress/kendo-angular-l10n": "^1.3.0",
    "@progress/kendo-angular-layout": "^3.2.0",
    "@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-drawing": "^1.5.8",
    "@telerik/kendo-intl": "^1.4.4",
     "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
```

Browser:

All Desktop/Laptop Browsers

System:
- TypeScript version: Version 3.1.2
- Node version: v8.12.0
- Platform:  Windows
![prod build issue](https://user-images.githubusercontent.com/6847933/52279004-7d850b00-297e-11e9-92df-0deacc94d7f4.PNG)

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
