### ISSUE TITLE
Blur event for kendo-autocomplete

### ISSUE THREAD

**Issue by alexanderromanov** [telerik/kendo-angular#206]
Are there any plans to add blur event for kendo-autocomplete?

**Comment by ggkrustev** [comment]
@alexanderromanov we are planing to add focus/blur events for all focusable (mainly forms) components. There are several roadblocks that we need to overcome. 

Currently the required functionality is in `investigation` stage. Once we have a proper solution, we will implement it immediately.

**Comment by tsvetomir** [comment]
Closing this as a duplicate of #155
