### ISSUE TITLE
Kendo Scheduler selected wrong date, when clicked on month day slot.

### ISSUE THREAD

**Issue by dnshiroma** [telerik/kendo-angular#2060]
## I'm submitting a...

* Bug report

## Current behavior

I select a date by clicking on month day slot, the current view change to day view, and I get one day before that I expected.

![image](https://user-images.githubusercontent.com/12010663/52287634-73551380-2962-11e9-89c3-e35274965d01.png)

![image](https://user-images.githubusercontent.com/12010663/52287682-8bc52e00-2962-11e9-8c4c-ff5643294401.png)

## Expected behavior
the current selected date should be 5/29/2019

## Minimal reproduction of the problem with instructions

the problem is related to current timezone. 
My current timezone is UTC -2, when I change the timezone on browser to Etc/UTC the selection works perfectly.

## Environment

Browser:
- Chrome (desktop) version 71.0.3578.98

**Comment by dnshiroma** [comment]
Is there any workaround?

**Comment by danielkaradachki** [comment]
Should be fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:
https://stackblitz.com/edit/angular-6hj3v1?file=app/app.component.ts

**Comment by dnshiroma** [comment]
thanks!

**Comment by dnshiroma** [comment]
> Should be fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:
> https://stackblitz.com/edit/angular-6hj3v1?file=app/app.component.ts

Thanks!

**Comment by tsvetomir** [comment]
Fixed in v0.9.0

**Comment by Zaliro** [comment]
@tsvetomir Sorry for reopening this. Is this bug also corrected for kendo-ui-core, is it the same code base ?
