### ISSUE TITLE
Grid: Responsive Layout with flex box -> grid should scroll

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#2061]
## I'm submitting a...

* Bug report 

## Current behavior

I like to build a responsive layout with flex box where the grid should take 100% height and start scrolling if the content height overflows the available height of the page.
This is working in Chrome < Version 72 and Safari, but not in Chrome >= V72, FireFox, IE11

## Expected behavior

Enable scrolling of the grid if the content of the grid overflows the page size.
Fit the grid to the full height of the page if less content then the page size is available.

## Minimal reproduction of the problem with instructions
I've attache a sample app.

## Environment

Browser:

- Chrome (desktop) version 72
- Chromium version 62
- Firefox version 65
- IE version 11

**Comment by SchneiderMK** [comment]
[grid-demo.zip](https://github.com/telerik/kendo-angular/files/2833081/grid-demo.zip)

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
