### ISSUE TITLE
[TimePicker]: min/max validation fails when range is within the same hour

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2063]
Time range validation using **min** and **max** fails when both values fall in the same hour, and the value is greater than "max" (triggers the validation as expected both when the value is earlier than "min", and if the **min** and **max** values fall in different hours):

[https://stackblitz.com/edit/angular-mvnwkd-vkmvqz?file=app/app.component.ts](https://stackblitz.com/edit/angular-mvnwkd-vkmvqz?file=app/app.component.ts) // not working as expected

[https://stackblitz.com/edit/angular-mvnwkd-152nrp?file=app/app.component.ts](https://stackblitz.com/edit/angular-mvnwkd-152nrp?file=app/app.component.ts) // **max** changed from 2:59 to 3:00 - working as expected

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
fixed in 3.6.0

https://stackblitz.com/edit/angular-mvnwkd-rc2sxo?file=app/app.component.ts
