### ISSUE TITLE
(Sortable) Data loss when dragging item across multiple sortables.

### ISSUE THREAD

**Issue by armysquirrel** [telerik/kendo-angular#2065]
## I'm submitting a...

* Regression report (used to work in 1.1.1, appeared after upgrading to 2.0.1)
* Bug report (similar to https://github.com/telerik/kendo-angular/issues/1979, with notes on exact circumstances)

## Current behavior

When multiple Sortables are present, dragging an item over multiple Sortables without releasing will remove an extra unwanted item from the source list.  The item must be dragged through an intermediate Sortable for this data loss to happen.  In the example posted below, dragging an item from List 1 directly to List 3 without first dragging through List 2 will work fine, but dragging an item from List 1 to List 2 to List 3 without releasing will

## Expected behavior
Dragging an item between any number of Sortables should only remove that item from the source list.

## Minimal reproduction of the problem with instructions

[Example here](https://angular-u84fws.stackblitz.io)

Drag any item from List 1 to List 3, through List 2.  An item should disappear from List 1.  Same when dragging from List 3 to List 1 through List 2.  Dragging from 1 to 2, or 2 to 3, should work as expected, as is dragging from 1 to 3 without the item touching List 2.

Example is reproducible on the [documentation page for Sortable Templates](https://www.telerik.com/kendo-angular-ui/components/sortable/templates/)  Dragging an item over multiple palettes will remove additional unwanted items.

## Environment

Browser:
- Chrome (desktop) version 71.0.3578.98 (Official Build) (64-bit)
- Edge version 25.10586.0.0

**Comment by danielkaradachki** [comment]
Seems similar to: https://github.com/telerik/kendo-angular/issues/1979

**Comment by armysquirrel** [comment]
Hi Daniel,


It is (and I mentioned that in the report), I just think I've identified the issue a little more clearly.  You can merge the bug reports if you want, or close it and reference the behavior in 1979.

________________________________

**Comment by danielkaradachki** [comment]
Hi,
Indeed, the steps are more clear here. Will close the other one in favor of this issue.

**Comment by MaklaCof** [comment]
Same problem [here](https://stackblitz.com/edit/angular-1f8ym5?file=app%2Fapp.component.ts). Stackblitz is here, and 2 steps to reproduce:
- drag first item to last palette
- click refresh json

Not sure if this is a bug, but json is strange with `OnPush`.

![2019-03-06_16-58-26](https://user-images.githubusercontent.com/1589573/53894825-15831c80-4031-11e9-9004-da5b3f41ab3e.gif)

**Comment by tapopov** [comment]
Thanks for the details. We will further investigate what's causing this.

**Comment by stilgar** [comment]
Same problem described in issue 2101
https://github.com/telerik/kendo-angular/issues/2101

Any update for this ticket?

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Fixed in 2.1.0:

https://stackblitz.com/edit/angular-u84fws-wqzagb?file=app/app.component.ts
