### ISSUE TITLE
Incorrect time slots for some slot durations

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#2068]
Example: https://stackblitz.com/edit/angular-rhk7uu

Reported in: https://www.telerik.com/forums/issue-with-slotduration-and-slotdivsion

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v0.9.0
