### ISSUE TITLE
The column menu of the Grid does not support RTL

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2069]
## I'm submitting a...
* Bug report 

## Current behavior
The column menu of the grid does not support RTL mode. 

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-snuezk?file=app/app.component.ts](https://stackblitz.com/edit/angular-snuezk?file=app/app.component.ts)

**Comment by danielkaradachki** [comment]
fixed in 3.13.0:
https://stackblitz.com/edit/angular-snuezk-u2yc3q?file=app/app.component.ts
