### ISSUE TITLE
Grid Editing in Template-Driven Forms do not work when Grouping

### ISSUE THREAD

**Issue by cOwOsen** [telerik/kendo-angular#207]
Grid Editing in Template-Driven Forms do not work when Grouping

[PlunkerLink](http://plnkr.co/edit/WpSrUHUq0SMA1donSY93?p=preview)

EXCEPTION: Cannot read property 'value' of undefined

**Comment by rusev** [comment]
Seems that the error happens when you remove the group. We will look into the issue.
