### ISSUE TITLE
[Tooltip] Setting callout to false breaks the regular layout

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2070]
When the **callout** option is set to **_false_**,  the regular Tooltip layout is broken:

![image](https://user-images.githubusercontent.com/7533599/52623516-28cd1d00-2eb5-11e9-90ae-94f05f20a641.png)

[https://stackblitz.com/edit/angular-m6yeap?file=app/app.component.ts](https://stackblitz.com/edit/angular-m6yeap?file=app/app.component.ts)

Workaround - adjust the Tooltip via CSS:

encapsulation: ViewEncapsulation.None,
  styles: ['.k-tooltip .k-tooltip-content { margin-top: 0 !important;  }']

[https://stackblitz.com/edit/angular-m6yeap-qxwnx5?file=app/app.component.ts](https://stackblitz.com/edit/angular-m6yeap-qxwnx5?file=app/app.component.ts)

**Comment by mct123** [comment]
**Use tooltip.toggle() method to change the tooltip message.
In the component code, get the TooltipDirective instance through a @ViewChild property.
Use the Tooltip API to show, hide, or toggle the Tooltip.**

`import { Component, ChangeDetectorRef,ViewChild   } from '@angular/core';
import { TooltipDirective } from '@progress/kendo-angular-tooltip';

@Component({
  selector: 'my-app',
  template: `
    <div kendoTooltip style="text-align: center; padding-top: 10px;">
        <button  #btn class="k-button k-primary" [title]="msg" (click)="change(btn)" value="{{msg}}">
            save
        </button>
        {{ msg }}
    </div>
  `
})
export class AppComponent {
  public msg = "original message";
  @ViewChild(TooltipDirective)
  public tooltipDir: TooltipDirective;
  change(btn){
      this.msg= this.msg == 'changed message' ?  "original message" : "changed message";
      this.tooltipDir.toggle(btn);
  }
}`

**Comment by dtopalov** [comment]
@mct123 when no square brackets are used for the "callout" binding, the value is automatically assumed to be a string - the string "false" which in turn evaluates to the boolean **_true_**, as it is a truthy value. 

Thus the callout is rendered as if when the property is not used at all - there is no problem with the rendering in this case. 

The problem is when callout is set to **_false_**, so that the callout (triangle pointer) is not rendered - then the undesired layout of the Tooltip, observed in the initial post is observed.

**Comment by elena-gancheva** [comment]
Fixed and available in latest `dev` version of the package.

**Comment by elena-gancheva** [comment]
The fix is shipped with `v1.2.0` of the package.
