### ISSUE TITLE
Overlapping events in kendo-scheduler

### ISSUE THREAD

**Issue by thomashoferch** [telerik/kendo-angular#2072]
## I'm submitting a...
* Bug report 

## Current behavior
If there are several events in parallel, it may happen that they overlap graphically, although that would not be necessary.

## Expected behavior
Show all events in full length without overlapping.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-n1co2z
see 6/24, events with ID 34 and 42.

## Environment
Browser:
- Chrome (desktop) version 72

**Comment by tsvetomir** [comment]
Fixed in v0.9.0
