### ISSUE TITLE
Grid auto-scrolls when virtual scrolling and groups are used

### ISSUE THREAD

**Issue by kylekatarnls** [telerik/kendo-angular#2073]
## Current behavior
Merging grouping + virtual scrolling from documentation examples, I get scroll-jumps when reaching a new virtual page (scrolling down just after Confections in the stackblitz).

## Expected behavior
Linear scrolling to next rows.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-if46x8-2eidfk?file=app/app.component.ts

Browsers:
- Chrome (desktop) version 71.0.3578.98
- Firefox version 66.0b7
- IE version 11.523.17134.0
- Edge version 42.17134.1.0
- Opera version 57.0.3098.116

## Additional information
I noticed than the scrollHeight of the scroll area does not take groups into accounts. For example, 1 000 lines of 50px gives 50 000px even if there are 1 000 groups headers inside.

Possibly linked to https://github.com/telerik/kendo-angular/issues/1020

**Comment by danielkaradachki** [comment]
Using virtual scrolling with grouping is only supported with the `kendoGridGroupBinding` directive:
https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-using-virtualization-with-grouping

**Comment by kylekatarnls** [comment]
@danielkaradachki  `[kendoGridGroupBinding]` forces the scrollTop to 0 at each data change. The `[data]` hadn't this behavior. 

It's not possible in our situation. We had to force the scroll to be restored at each change and the performance cost is high.

If it can only works with `[kendoGridGroupBinding]`, then we need a option disable the scroll reset. Please re-open.

**Comment by danielkaradachki** [comment]
If you are having trouble adjusting the `kendoGridGroupBinding` directive to your requirements then please open a  [support ticket](https://www.telerik.com/account/support-tickets). Supporting grouping and virtualization without the directive is not currently planned.
