### ISSUE TITLE
Missing file in official docs demo

### ISSUE THREAD

**Issue by santutoshi** [telerik/kendo-angular#2075]
## I'm submitting a...

* Documentation issue 

## Current behavior
'./my-event.interface' file missing from the demo on [this page](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/external-editing/), the file is include in 'edit.service.ts'
## Expected behavior
It should be added accordingly

**Comment by danielkaradachki** [comment]
Thanks, fixed in the [develop](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/editing/external-editing/) version of the site.
