### ISSUE TITLE
dropdown list cannot roll up 

### ISSUE THREAD

**Issue by jiangen1016** [telerik/kendo-angular#2079]
when dropdown list on blur, dropdown can not roll up on ios 

`"@progress/kendo-angular-dropdowns": "3.4.2",`

**Comment by danielkaradachki** [comment]
Please provide more detailed information about the issue. A runnable sample if not reproducible on the online demos. Step by step instructions on how to replicate it or a screen-cast that demonstrates it. If applicable, IOS version.

**Comment by jiangen1016** [comment]
> Please provide more detailed information about the issue. A runnable sample if not reproducible on the online demos. Step by step instructions on how to replicate it or a screen-cast that demonstrates it. If applicable, IOS version.

**Comment by jiangen1016** [comment]
@danielkaradachki Is there a release plan for this issues?

**Comment by ipeshev** [comment]
Fix is shipped with v5.3.0.

**Comment by gkarapeev** [comment]
Closing the issue as the fix is available from 5.3.0, as mentioned above.
