### ISSUE TITLE
MaskedTextBox keyboard issues

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#208]
Here are some issues with MaskedTextBox:

1. Select all and clear with `Backspace` key does not work:
**Reproduce:** Select all text and hit `Backspace`.
**Behaviour:** Returns the cursor in the beginning of the field. 
**Expected behaviour:** Clear all contents.

1. Select any and clear with `Delete` key does not work:
**Reproduce:** Select all or some part of the text and hit `Delete`.
**Behaviour:** Nothing happens.
**Expected behaviour:** Clear all contents.

1. Delete next char with `Delete` key does not work
**Reproduce:** Move cursor somewhere in the middle of the field and hit `Delete` key.
**Behaviour:** Nothing happens.
**Expected behaviour:** Delete the first character (if any) after cursor.

You can reproduce all of these in the basic usage demo page: 
http://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/#toc-basic-usage

**Comment by ag-petrov** [comment]
Fix for the issues is availabe in version 0.18.5
