### ISSUE TITLE
Not able to install kendo-angular-dateinputs , produces error while installing.

### ISSUE THREAD

**Issue by ajazhmd** [telerik/kendo-angular#2083]
**Describe the bug**

I am trying to install **kendo-angular-dateinput** using following command
`npm install --save @progress/kendo-angular-dateinputs`

but it produces the following error
```
..\path>npm install --save @progress/kendo-angular-dateinputs
npm ERR! Unexpected end of JSON input while parsing near '...krux/condition-jenk
in'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\..\AppData\Roaming\npm-cache\_logs\2019-02-21T12_0
3_10_780Z-debug.log
```

**To Reproduce**
Angular version : 7
1. Execute **npm install --save @progress/kendo-angular-dateinputs**

**Expected behavior**
Package should install without any error.

**Comment by danielkaradachki** [comment]
Can't seem to be able to replicate the error. Could you try clearing the cache `npm cache clean --force`  and 
reinstalling the package?

Also verify that you are not using the old registry. More detailed information available [here](https://github.com/telerik/kendo-angular/issues/712)

**Comment by ajazhmd** [comment]
@danielkaradachki clearing cache solved the issue. Thanks
