### ISSUE TITLE
Strange behavior of TreeView node after navigation by right arrow

### ISSUE THREAD

**Issue by orlov11111** [telerik/kendo-angular#2084]
## I'm submitting a...

* Bug report 

## Current behavior

If you try to navigate by right arrow and there is no child in the node, the icon become spinning.
![image](https://user-images.githubusercontent.com/47855982/53170825-20ca5700-35f2-11e9-8866-548df5f9872e.png)

## Expected behavior

The icon should not become spinning.

## Minimal reproduction of the problem with instructions

Use this [example](https://stackblitz.com/edit/angular-x2vmfq)

- Make "Empty Array" node focused
- Use right arrow (node should be opened but there is no child)
- Use right arrow (icon should be spinning)

**Comment by danielkaradachki** [comment]
Fix released in 3.1.0

https://stackblitz.com/edit/angular-x2vmfq-jypkrw?file=app/app.component.ts
