### ISSUE TITLE
[Scheduler] Incorrect positioning of events on the scheduler

### ISSUE THREAD

**Issue by uranium62** [telerik/kendo-angular#2085]
Hi guys, 
We have a problem with the positioning of events on the schedule. When we create events that overlap, the scheduler positions these events one on another. (the version of the package **@progress/kendo-angular-scheduler0.8.0**)

**Steps to Reproduce**
1. Create event (i.e. from 7 AM till 12:30 PM)
2. Create the second event (i.e. from 8 AM till 9 AM)
3. Create a third event that starts before the first event and finishes in time frames of the first meeting (i.e. from 6:30 AM till 7:30 AM)

**Example**
https://stackblitz.com/edit/angular-tzvtg6

**Expected behavior**
We expect them to be displayed next to each other.

**Screenshots**

![scheduler](https://user-images.githubusercontent.com/1567570/53173285-0a230080-35f0-11e9-9931-4526a1ef19e8.png)

**Browser**
 - OS: Windows 10
 - Browser: Google Chrome 
 - Version: 72.0.3626.109 (Official Build) (64-bit)

**Question**
Is it your expected behavior or is it a bug?

**Comment by danielkaradachki** [comment]
Seems the same issue as the one described [here](https://github.com/telerik/kendo-angular/issues/2072).

The problem should be fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v0.9.0
