### ISSUE TITLE
[TimePicker]: min/max validation fails when range is within the same minute

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2087]
Same as https://github.com/telerik/kendo-angular/issues/2063, but if we provide same max and min (or max and min differ by less than a minute):

[https://stackblitz.com/edit/angular-kendo-timepicker-min-max-range-problem-wjiuxv?file=app/app.component.ts](https://stackblitz.com/edit/angular-kendo-timepicker-min-max-range-problem-wjiuxv?file=app/app.component.ts)

If we change the max date to be in the next minute relative to the min date, the validation is triggered as expected:

[https://stackblitz.com/edit/angular-kendo-timepicker-min-max-range-problem-v4nhg1?file=app/app.component.ts](https://stackblitz.com/edit/angular-kendo-timepicker-min-max-range-problem-v4nhg1?file=app/app.component.ts)

Reported in Ticket ID: 1386429

**Comment by dtopuzov** [comment]
Released with v13.5.0.
