### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#2088]
The Scheduler should include [RTL Support](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/#toc-rtl-support):
* [Dynamic updates of text direction](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/#toc-dynamic-update-of-text-direction)
* Dedicated view layouts with events anchored to the right

**Comment by tsvetomir** [comment]
Shipped in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)

**Comment by ipeshev** [comment]
![Screenshot from 2019-03-14 17-31-27](https://user-images.githubusercontent.com/4143177/54369767-2bbb5900-467f-11e9-9887-0008f13e0417.png)

**Comment by ipeshev** [comment]
My bad , it is fine with latest dev theme and scheduler packages !

**Comment by danielkaradachki** [comment]
Released in 0.10.0 of the @progress/kendo-angular-scheduler package and in the latest themes.
