### ISSUE TITLE
[Scheduler] Calendar not destroyed when routing

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2089]
If we open the Scheduler Calendar and navigate to a different page while it is still open, it locks to the top of the screen:

[https://stackblitz.com/edit/angular-ihy686?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-ihy686?file=app%2Fapp.component.ts)

Open the Calendar, and go to "Products":

![image](https://user-images.githubusercontent.com/7533599/53248180-cac2e580-36bd-11e9-943d-aedde3e772e5.png)

**Comment by ipeshev** [comment]
Fix availbale in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 0.10.0

https://stackblitz.com/edit/angular-ihy686-puzd3g?file=app/app.component.ts
