### ISSUE TITLE
ColumnGroupComponent Documentation includes invalid property includeInChooser

### ISSUE THREAD

**Issue by vtachkov** [telerik/kendo-angular#2093]
On the API Documentation page for the `ColumnGorupComponent`, https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnGroupComponent/#toc-includeinchooser it incorrectly lists the property `includeInChooser`. This property is valid for the `ColumnComponent`, but it is not recognized for the `ColumnGroupComponent`.

It would be nice if this property would actually be applicable to column groups because I would like to be able to toggle entire column groups from the column chooser component.

**Comment by danielkaradachki** [comment]
Thanks, we will update the documentation.
At this point we don't plan adding support for including groups in the column chooser. I can suggest to submit a feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui) so we can track its interest.

**Comment by danielkaradachki** [comment]
The documentation has been updated:
https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/ColumnGroupComponent/
