### ISSUE TITLE
Grid reorderColumn not completely working for column groups

### ISSUE THREAD

**Issue by vtachkov** [telerik/kendo-angular#2096]
## I'm submitting a...
* Bug report

## Current behavior
When programatically reordering column groups using GridComponent.reorderColumn, the column group does not move to the expected position in the grid header. This does not seem to be affecting normal columns, only column groups. Maybe I'm misunderstanding how this functionality should behave, but it does't seem right to me.

## Expected behavior
The column group should move to the index passed into the reorderColumn method.

## Minimal reproduction of the problem with instructions
Run example:
https://stackblitz.com/edit/kendo-angular-reorder-issue?file=app%2Fapp.component.ts
Change the value in the input to different indexes and see where the column group moves to. Only indexes 0 and 2 have any effect, but only index 0 seems to have the correct behavior.

**Comment by danielkaradachki** [comment]
The behavior seems correct. Using index 1 will not change the position because with the before flag it is the same as the original one for the root level columns Product, Price and Discontinued. Using index 2 also seems correct - moves the column before the second column(Discontinued). Using index 0 moves the column to the first position.
Am I missing something?

**Comment by vtachkov** [comment]
I see, perhaps I was incorrectly using the before option. I think I understand how this method works now. In order for it to work for my specific use case, it seems that I need to set before: false when the index of the column is increasing, and before: true when the index is decreasing, relative to the column's current index. That way, the column is inserted at the expected index instead of being offset by 1.
