### ISSUE TITLE
[Request for Comments] Scroll to specific time

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2100]
**Current behavior**
Currently, the Scheduler displays the day starting from midnight. Clicking "Show business hours" restricts the view to the working hours, but the rest of the day is no longer accessible.

![image](https://user-images.githubusercontent.com/247917/53494979-a98c3b80-3aa7-11e9-9d09-3ec550d8b920.png)

**Expected behavior**
The Scheduler should support a `focusedTime` that will be scrolled into view. The rest of the day is accessible using scroll.

![image](https://user-images.githubusercontent.com/247917/53495104-e35d4200-3aa7-11e9-9c72-4afddcf94155.png)

This is also the approach taken by Google Calendar and Microsoft Outlook.

**Workarounds**
The time range can be restricted with [`startTime` and `endTime`](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerComponent/#toc-starttime).
Unfortunately, this makes the "Show full time" less useful.

**Questions**
* What should be the default value for `focusedTime`, if any?

**Comment by Felx-B** [comment]
I think the default `focusedTime` should be the first worked hour.
=>Maybe a boolean like `focusOnFirstWorkedHour` would be more explicit

But a method should be available to focus on a specific hour : `focusOnTime(time: Date)`
This allows to focus on any event

**Comment by tsvetomir** [comment]
The [scrollTime property](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/SchedulerComponent/#toc-scrolltime) (defaults to `workDayStart`) and [scrollToTime method](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/SchedulerComponent/#toc-scrolltotime) have been shipped in v0.12, see [demos](https://www.telerik.com/kendo-angular-ui/components/scheduler/).
