### ISSUE TITLE
es2015 package entry point has been rerouted to fesm2015 source

### ISSUE THREAD

**Issue by elca-lan** [telerik/kendo-angular#2103]
**Describe the bug**
The package.json file of @progress/kendo-angular-dropdowns@3.5.1 has been changed such that the "es2015" entry point no longer points to the es2015 source but instead points to fesm2015 sources. This is a breaking change and messes with our Angular build quite severely.

**To Reproduce**
1. Compare package.json file from @progress/kendo-angular-dropdowns versions 3.4.0 and 3.5.1

**Expected behavior**
I would expect the es2015 entry point to actually point to the es2015 source and not to the flat module source.

**Screenshots**
![image](https://user-images.githubusercontent.com/43171533/53559986-b06c8a00-3b4b-11e9-89f4-75833f28b037.png)

**Browser**
irrelevant

**Additional context**
This was changed in commit 8fa069c89ec0dd73ca36a779087561743c047728.
Now there is also a new "esm2015" entry point that points to es2015 - which does not seem to make a lot of sense.

**Comment by tsvetomir** [comment]
@elca-lan can you provide more details about your build setup? Any specific errors that you see?

For background, the flat ES5 and ES2015 modules were added to:
* Workaround compatibility issues with ivy-ngcc in Angular 8 (Beta)
* Improve build times in customer projects
* Improve compatibility with the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.3kkc9d322g9f). It recommends that the default entry points are flat modules:
> ## Note about the defaults in package.json
> As of webpack v4 the flattening of ES modules optimization should not be necessary for webpack users, and in fact theoretically we should be able to get better code-splitting without flattening of modules in webpack, but in practice we still see size regressions when using unflattened modules as input for webpack v4. This is why "module" and "es2015" package.json entries still point to fesm files. We are investigating this issue and expect that we'll switch the "module" and "es2015" package.json entry-points to unflattened files when the size regression issue is resolved.

We deemed the change to be non-breaking as:
* The old entry points remain in the same locations.
* Flat vs. non-flat should make no difference to a module bundler. The former omit references to local files, but they're still regular modules.

**Comment by elca-lan** [comment]
More details about our build configuration:
We use the [resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields) configuration with `['es2015', 'browser', 'module', 'main']` to ensure that the es2015 is specifically used where available - of course, working under the assumption that said entry point actually _points to the es2015_ files and not something else.

We have to reference Kendo "somewhat-internals" like the dropdowns `SelectionService` in several places to customize certain behaviors. Since that service is not exposed in the bundle, we have to reference it directly as import from `@progress/kendo-angular-dropdowns/dist/es2015/selection.service` which has to include the full path including "es2015".

If the es2015 entry point now suddenly points to completely different files, then the dependency injection breaks down on runtime because `SelectionService` from es2015 is actually a different constructor resulting in a different token key from `SelectionService` from fesm2015.

> The old entry points remain in the same locations.

How exactly do the old entry points remain in the same locations if they are pointing to different directories?

I think it is fairly reasonable that the "es2015" entry point actually points to "es2015" source while the current _workaround_ for a _beta_ version of Angular seems... you know... pretty darn hacky ;)

**Comment by tsvetomir** [comment]
I see, thank you.

Deep imports are risky, regardless of the chosen approach. Paths can change without notice due to any minor refactoring.

Do you have a list of such internal members so we can export them through the index file. I can't promise they'll be "official API", but at least you won't have to deal with paths.

> How exactly do the old entry points remain in the same locations if they are pointing to different directories?

This does not hold true in case of using `mainFields` as it remaps the folders according to the entry point. A vanilla `import { foo } from '@progress/xyz/dist/es2015/foo';` would still resolve to the same module.

**Comment by elca-lan** [comment]
> Deep imports are risky, regardless of the chosen approach. Paths can change without notice due to any minor refactoring.
Very true, but we can deal with path changes of the individual services without too much of a problem.

Unfortunately, the list of such internal members is quite long since we need to customize the templates of several of the Kendo components which involves creating a custom implementation that derives from the Kendo component and _provides all the necessary services_. And we do that with several of the components. We also do some other "inadvisable" stuff to satisfy some weird requirements...

For the kendo-angular-dropdowns alone the internals that we use are:
* SelectionService
* DisabledItemsService
* NavigationService
* SearchBarComponent
* NoDataTemplateDirective
* TagTemplateDirective

> This does not hold true in case of using `mainFields` as it remaps the folders according to the entry point. A vanilla `import { foo } from '@progress/xyz/dist/es2015/foo';` would still resolve to the same module.

And _that_ is exactly the problem:
Say some class in the Kendo library expects ServiceX to be provided by some parent component. If the class is in fesm2015, then it references the ServiceX of fesm2015. If we provide the ServiceX from es2015, then that service won't be injected into the class - we will get an injection error on runtime because the ServiceX from es2015 has a different injector token from the one in fesm2015

**Comment by tsvetomir** [comment]
It's worth noting that the generated index file exports all directives and services for use by the by AoT compiler. See [dist/es/index.js](https://unpkg.com/@progress/kendo-angular-dropdowns@3.5.1/dist/es/index.js) and the bottom of [dist/fesm2015/index.js](https://unpkg.com/@progress/kendo-angular-dropdowns@3.5.1/dist/fesm2015/index.js).

If we export these symbols using their regular names you'd be able to import them from the package root. We have some corner cases to cover, such as duplicates, but it should be doable.

**Comment by elca-lan** [comment]
Yes, we actually used to import those mangled names from the package at some point, but that was an even worse idea for obvious reasons (the names change all the time). If you could export those with their regular names, that should work for our use cases.

**Comment by tsvetomir** [comment]
We've published an experimental build with [vanilla exports](https://unpkg.com/@progress/kendo-angular-dropdowns@3.5.2-dev-201903081421/dist/es/index.js) for the internal symbols. Try it out by installing the `export-symbols` dist tag:
`npm install --save @progress/kendo-angular-dropdowns@export-symbols`

If all goes well, we'll land the change in the development channel next.

**Comment by tsvetomir** [comment]
Available in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Shipped in v3.5.2
