### ISSUE TITLE
Kendo Editor has to prevent click propagation

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2104]
**Describe the bug**
Every click on Kendo Editor Toolbar generates Form Submit event (so form is submitted)

**To Reproduce**
https://stackblitz.com/edit/angular-ndiw7t

click on text toolbar and see console log

**Expected behavior**
Just prevent click without for submit

**Comment by Raisolution** [comment]
The issue has been addressed in `v1.1.0` of the `kendo-angular-toolbar` package.
