### ISSUE TITLE
[NumericTextBox] User can enter unlimited number of zeros (0) when decimals is set

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2106]
The **decimals** option is respected for all other digits, but the user is still able to enter an arbitrary number of zeros in the beginning or end after the decimal separator:

[https://stackblitz.com/edit/angular-t4ohzq?file=app/app.component.ts](https://stackblitz.com/edit/angular-t4ohzq?file=app/app.component.ts)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 4.2.1

https://stackblitz.com/edit/angular-t4ohzq-xvg3rp?file=app/app.component.ts
