### ISSUE TITLE
page can not srcoll on grid header area

### ISSUE THREAD

**Issue by jiangen1016** [telerik/kendo-angular#2108]
On mobile( IOS and Android), I can not do scroll the pages on grid header area.
And you can see this video https://youtu.be/C4lUXj3j96w

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.13.1
