### ISSUE TITLE
Visual jump when entering edit mode in not locked cell and there are locked columns.

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2109]
**Describe the bug**
When using a grid with in-cell editing mode and we click inside any cell, the columns, that are not locked,  are re-painted. 

**To Reproduce**
Check the following example:
[https://stackblitz.com/edit/angular-fflaz4?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-fflaz4?file=app%2Fapp.component.ts)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Released in 3.13.1

https://stackblitz.com/edit/angular-fflaz4-xzmanz?file=app/app.component.ts
