### ISSUE TITLE
MaskedTextBox update model programmatically

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#211]
MaskedTextBox behaves very strange when you try to update its model programmatically. Setting an invalid or empty values to the model will not change masked text box contents (maybe should clears the field). Also setting a valid value updates masked text box contents only if you click on it.

**Plunker:**
http://plnkr.co/edit/9iWsTq8RaYJuZ2vARIZR?p=preview
___
If you try to use [(ngModel)] without a form it throws an exception: `Expression has changed after it was checked.`

**Plunker:**
http://plnkr.co/edit/Wltz5hHwk6sw9bfxxdLP?p=preview

**Comment by rohit-b** [comment]
kendo masked text box mask change does not work
it gives error - Expression has changed after it was checked. Previous value: 
                              'undefined'. Current value: '__ ___'
Plnkr: http://plnkr.co/edit/nCvHtWgkrqr0KkYiXArQ?p=preview

**Comment by ilianiv** [comment]
Hi,
Is there any progress on this issue? Sorry for being impatient but this is a blocking issue for my project.

**Comment by ag-petrov** [comment]
We are currently researching the issue and will do our best to provide a solution as soon as possible.

**Comment by rusev** [comment]
@ilianiv @rohit-b There is a new version of `kendo-angular-inputs` package which addresses the issues related to the `MaskedTextBox` component mentioned in this thread.

@ilianiv Here are updated examples from your post. The value for the component will be updated when setting even invalid value (for the mask). The change is that the value set through the `value` property is left unchanged until the user interacts with the component by either types or paste content.

http://plnkr.co/edit/PNFQNFu5WD5nr87lf0lN?p=preview
http://plnkr.co/edit/lDA6OELBkfWjv1I8rlTf?p=preview

@rohit-b Updated example should run without errors- http://plnkr.co/edit/vUynIqOSL9PnrlFhNl03?p=preview

**Comment by ilianiv** [comment]
👍 yep issues are fixed now.

PS: May I suggest adding a (onComplete) event that fires when user completes the mask pattern?

**Comment by rusev** [comment]
You can assert this by checking the value of the component, like so http://plnkr.co/edit/M9PRfgbQHzTgR9zQtquz?p=preview

**Comment by ilianiv** [comment]
Yes, I've managed to assert this this way but valid/invalid control state is available just after next change detection cycle. 
If you try to figure this out at the current change detection cycle control.valid state is not updated yet.
http://plnkr.co/edit/HJhYa3y0WlJ4aQYyIDdC?p=preview

I know I can check with setTimeout() but it's kind of hacky.

**Comment by ilianiv** [comment]
And one more thing.
When I use component with `includeLiterals` set to TRUE and delete all chars from the control literals (like `-`) from mask remain as string in model. Maybe if all characters get erased (clear the input with backspace or del key) `null` should be sent to model even if includeLiterals is turned on.
http://plnkr.co/edit/U9VYNarIvGXK9RxkGTJ7?p=preview

**Comment by tsvetomir** [comment]
@ilianiv I agree, an empty value should be empty regardless of includeLiterals.

**Comment by ilianiv** [comment]
Hi guys! Any progress here?

**Comment by rusev** [comment]
@ilianiv Latest version of the `kendo-angular-inputs` addresses the empty value scenario. Please give it a try.

**Comment by ilianiv** [comment]
Yes it's fixed in kendo-angular-inputs@1.0.2.
Thanks!
