### ISSUE TITLE
How to have a grid inside dropdown template

### ISSUE THREAD

**Issue by crh225** [telerik/kendo-angular#2112]
**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**

I want to be able to put a grid inside a dropdown list template. My use case is I want to search for stuff, and it show in a grid/table. Think of an auto complete for customers, that could have a popover or something with a tiny grid that shows up.
https://stackblitz.com/edit/angular-2d8t1v?file=app/app.component.ts

**Comment by crh225** [comment]
I am able to put a table in the template row, but I have to keep up with column widths which is not ideal:
https://stackblitz.com/edit/angular-2d8t1v-ihlezu?file=app/app.component.ts

**Comment by dimitar-pechev** [comment]
@crh225, such a behavior is not supported out of the box, however, you can still put a `kendo-grid` with the `selectable` property enabled in the header template of the dropdownlist and wire the grid selection with the dropdownlist value. Here's [an example](https://stackblitz.com/edit/angular-2d8t1v-omve7p). 

I wouldn't really encourage though putting such a large component in a dropdownlist. Not only will it be harder for the users to navigate through larger data sets but the performance might not bee too good especially in slower browsers if you bind the grid to too many entries/columns (the animation of the dropdownlist might become laggy).

I would also ask you to submit such questions for custom scenarios in our [support portal](https://www.telerik.com/account/support-tickets). This repository is in principle for reporting bug reports or other issues with the component.

**Comment by kishore8190** [comment]
How to make use of filtering option of grid  under drop-down template?
