### ISSUE TITLE
Scheduler : Wrong DragEndEvent definition

### ISSUE THREAD

**Issue by Felx-B** [telerik/kendo-angular#2113]
**Describe the bug**
The DragEndEvent does not contains array `resource`.
Instead a `resources` property is provided wich is not an array

**To Reproduce**

Here is the [StackBlitz](https://stackblitz.com/edit/angular-scheduler-dragevent)
=> drag an event
=> open the console logs

**Expected behavior**
DragEndEvent should provide an array property named `resources`

**Comment by danielkaradachki** [comment]
Thanks, should be fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version.

**Comment by dhilgarth** [comment]
It also misses `isAllDay: boolean`

**Comment by danielkaradachki** [comment]
Thanks, fixed in the latest dev version:

https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/DragEvent/#toc-isallday

**Comment by dhilgarth** [comment]
Is that actually correct? I think it is the *new* value, not the current one. Similar to `end` and `start`.

**Comment by dhilgarth** [comment]
Also, have the typescript definitions been updated accordingly as well?

**Comment by danielkaradachki** [comment]
The value may change during dragging when switching between the time and all day slots, so the all day value is the current one in the drag event. The value in the dragEnd handler is the new one.

The API is generated from the code so the definitions in develop should be correct.

**Comment by danielkaradachki** [comment]
Released in 0.10.0
