### ISSUE TITLE
Setting [resizable] to false of the Window component allows to resize the Window from the keyboard

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2114]
**Describe the bug**
When setting [resizable]="false" to the Window we are still able to resize the Window from the keyboard. 

**To Reproduce**
[https://stackblitz.com/edit/angular-xtgbjb?file=app/app.component.ts](https://stackblitz.com/edit/angular-xtgbjb?file=app/app.component.ts)

use (Ctrl + arrow key) to resize the window

**Comment by Raisolution** [comment]
Fixed in `v3.11.0-dev.201903071522`
