### ISSUE TITLE
Dialog does not open through service from an OnPush component

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2118]
**Describe the bug**
The Dialog does not render correctly when calling `dialogService.open` asynchronously from a component with `OnPush` change detection strategy.

**To Reproduce**
1. Open https://angular-9vmvyv.stackblitz.io
1. Click the "Delete User" button

**Expected behavior**
The Dialog should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/247917/54118017-c1928200-43fa-11e9-9d55-d10304e367a4.png)

**Additional context**
The issue can be worked around by calling `changeDetector.markForCheck()`, see [updated snippet](https://stackblitz.com/edit/angular-9vmvyv-be9wtv?file=app%2Fapp.component.ts).

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by Raisolution** [comment]
The official version `v3.11.0` containing the fix has been released.
