### ISSUE TITLE
Grid row click and double click handlers

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#212]
Do you consider adding row click and row double click events? It will be useful for heavy datatables with a lot of columns that have no room for extra actions column with open/edit buttons. These actions may be performed on click/double click.

**Comment by ilianiv** [comment]
OK. I see.

**Comment by filiphr** [comment]
I might understand the reasoning for not having `mouse over / mouse out` events. However, I can't understand why having a double click handler is bad? You already have an indirect click handler (for selection). I am not sure how you have implemented, that, but why can't it be something similar for double click? 

Having a double click helps the user to open the items more quickly.
