### ISSUE TITLE
Column menu disappears when trying to select a filter operator

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2120]
**Describe the bug**
The column menu disappears when trying to select filter operator, when there is not enough space to display the column menu popup on the page.

**To Reproduce**
Check the following example:  https://stackblitz.com/edit/angular-3wdbkr-v5lnox?file=app/app.component.ts

**Expected behavior**
The column menu popup should not close.

**Comment by danielkaradachki** [comment]
Related to: https://github.com/telerik/kendo-angular/issues/2031

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-grid v4.5.0`
