### ISSUE TITLE
Moving an event in month view changes it to an All Day Event

### ISSUE THREAD

**Issue by dhilgarth** [telerik/kendo-angular#2122]
**Describe the bug**
When moving an event via the month view, it changes it to an all day event.

**To Reproduce**
1. https://stackblitz.com/edit/angular-pyra3t
2. Double click on event "Call Charlie about the project" and notice that it is not an All Day Event.
3. Move it from  6/11/19 to some other day
4. Double click it again and notice that it has changed to an All Day Event.

**Expected behavior**
It just changes the date, but does not change the start time and end time and it does not change it to an all day event.
The current behavior is unintuitive and does also deviate from the behavior of the KendoUI jQuery Scheduler component.

**Comment by dhilgarth** [comment]
Is there a problem with the description of this issue?

**Comment by danielkaradachki** [comment]
The description is fine, thanks. We are currently working on improving the drag and resize behavior. We will update the issues once there is a fix.

**Comment by tsvetomir** [comment]
Fixed in v0.12
