### ISSUE TITLE
autoFitColumns performance

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2124]
**Describe the bug**
The [autoFitColumns](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-autofitcolumns) is slow, taking 3-6 seconds to complete for a Grid with 1500 cells.

**To Reproduce**
1. Open https://stackblitz.com/edit/ka-grid-autofit?file=app/app.component.ts
1. Open the Browser Console
1. Click "Auto-fit Columns"

**Expected behavior**
The method call should be much faster.

**Screenshots**
![image](https://user-images.githubusercontent.com/247917/54259544-ced07d80-456e-11e9-833c-12f1ddece965.png)

**Browser**
 - Chrome, FF

**Additional context**
The current implementation seems to trigger excessive reflows.
Ideally, DOM updates should be batched.

**Comment by priteshkbasystems** [comment]
This issue has a high severity for our application. We need a resolution of this issue immediately.  Kindly let us know the ETA for this issue.

**Comment by tsvetomir** [comment]
There's no ETA for a fix at the moment, sorry. We'll post updates when more information is available.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-grid`

**Comment by tsvetomir** [comment]
Fixed in v4.6.0
