### ISSUE TITLE
Dialog with kendo-editor opens only once.

### ISSUE THREAD

**Issue by PawelSienko** [telerik/kendo-angular#2125]
## I'm submitting a...

* Bug report 

## Current behavior
Dialog with editor opens only once when click on button. Next time it is unable to open.

## Expected behavior
Dialog should be opened every time when user clicks on button. 

## Minimal reproduction of the problem with instructions
Click on following link to stackblitz  ->  https://stackblitz.com/edit/angular-lzskpe 
Click on this link to see only aplication (without code) -> https://angular-lzskpe.stackblitz.io
On right side application should run. 
Click on button 'Show Editor'.
Close dialog by clicking 'Cancel' or 'X'.
Click on button 'Show Editor' again.
Dialog doesn't open. 

## Environment

Browser:

- Chrome (desktop) Version 72.0.3626.121 (Official Build) (64-bit)

System:
- TypeScript version: 3.2.2
- Node version: 10.15.3
- Platform:  Windows

**Comment by PawelSienko** [comment]
Hi,

when are you going to fix it? 

Thanks

**Comment by Raisolution** [comment]
Hi @PawelSienko,

A fix for this issue will be released next week.

**Comment by Raisolution** [comment]
The fix is available in `v0.4.2-dev.201904151102`.

**Comment by cluetjen** [comment]
Tested and works for scenario described in #2201.

**Comment by ipeshev** [comment]
Shipped with version @progress/kendo-angular-editor@0.5.0.
