### ISSUE TITLE
Documentation "Modifying the Locale Data" contains broken example

### ISSUE THREAD

**Issue by tunger** [telerik/kendo-angular#2126]
## I'm submitting a...

* Documentation issue 

## Current behavior

```import { IntlModule, localeData } from '@progress/kendo-angular-intl';```
produces error
```Module '"/node_modules/@progress/kendo-angular-intl/dist/es2015"' has no exported member 'localeData'.```

## Expected behavior

https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/loading-data/#toc-modifying-the-locale-data
It should work as stated in the example to modify locale data. 
How does it work instead?

## Environment

Package versions:

```
"@progress/kendo-angular-intl": "^1.7.0"
```

**Comment by danielkaradachki** [comment]
Could you provide a runnable sample that demonstrates the problem? The example seems to work correctly on stackblitz and in a new project. Also, verify that the latest @progress/kendo-angular-intl version is installed in your project.

**Comment by tunger** [comment]
Oh, I'm sorry, seems like I didn't update the package correctly. Now it works.
Sorry to bother you.
