### ISSUE TITLE
Kendo Sortable removing item doesn't update the control

### ISSUE THREAD

**Issue by jaredgermano** [telerik/kendo-angular#2127]
**Describe the bug**
If you remove an item from the list the Sortable control is bound to, it doesn't visually update the control.

**To Reproduce**

StackBlitz: https://stackblitz.com/edit/angular-dy1czf

1. Click the Delete link in the Sortable template on one of the items

**Expected behavior**
Sortable control should update when the list its bound to changes. This worked in previous versions of the control.

Browser
Chrome 72.0.3626.121

**Comment by danielkaradachki** [comment]
You should update the array instance in order for Angular to detect a change and update the Sortable component:

https://stackblitz.com/edit/angular-dy1czf-4vpg8y?file=app/app.component.ts
