### ISSUE TITLE
Grid unselect with ctrl + click instead of click again

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#213]
Your jQuery version of Kendo UI grid selection works this way:
- Click - select single row (deselect all other)
- Ctrl+click - adds non selected row to selection or deselects a selected row
http://demos.telerik.com/kendo-ui/grid/selection

Now in NG2 version (still no multi select option):
- Click - selects non selected row or deselects a selected one

Are you going to change current NG2 version behaviour when you release multiselect option and make it like Kendo UI jQuery (which I think is the more natural way)?

**Comment by rusev** [comment]
@ilianiv The final decision on how selection will behave has not been taken yet. That said your feedback on the matter is highly appreciated and we will take it into consideration.

Could you share your expectations on how should multiple selection works for the Grid component?

**Comment by ilianiv** [comment]
In multiselect mode I would expect:
- Just a click selects the row and deselects all other ones;
- Ctrl+click on selected row unselects it;
- Ctrl+click on unselected row adds it to the selection;
- Shift+click selects all rows from previous selected (or first) row to currently clicked row

**Comment by ilianiv** [comment]
I also wonder why row data is missing from [Selection event](http://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionEvent/#toc-selectionchange) but only row index is there.

May paging/sorting change selected row index and lead to a bug in user app? May some lazy loading replace my grid data before I access selected row index?

**Comment by rusev** [comment]
@ilianiv Thank you for taking the time creating the list above. We will definitely have it in mind when implementing the multiple selection feature.

Regarding the second question - we intentionally left the API surface small as the feature is still not complete. This will eventually reduce the possible breaking changes as we extend it. For the final version we  should be able to provide the actual data item in the event arguments.

**Comment by ilianiv** [comment]
@rusev isn't it strange that you've referenced this issue 8 days ago https://github.com/telerik/kendo-angular/issues/287#issuecomment-278565009 this way
> If you may have any other suggestions/comments we will be more than happy to see them posted in this issue.

and now you are closing it? Is multiselection implemented?

**Comment by KirilNN** [comment]
Hi @ilianiv,

Multiple selection is part of our plans for the future improvements of the Grid. And as soon as it is ready, it will be published as part of the npm package.

**Comment by tsvetomir** [comment]
We'll keep the issue open until the multiple selection feature ships.

**Comment by ilianiv** [comment]
Hope you'll ship it soon because it's a blocking issue for my project 😓

**Comment by meriturva** [comment]
The same here! i think it is the main issue open regarding Grid plus #139

**Comment by moxival** [comment]
Hey @tsvetomir do you have any update on this, do you guys started the work (or maybe even almost finished it :) )?

**Comment by tsvetomir** [comment]
Not quite, we're start working on the selection after the v1 release this Friday.

**Comment by moxival** [comment]
Hey guys any update on the status of this?

**Comment by tsvetomir** [comment]
Nothing to show yet, but we're on it.

**Comment by moxival** [comment]
Hey guys any progress on this, is it started already?

**Comment by Raisolution** [comment]
We've started working on this feature, but will not rush it, as there are many scenarios to cover. We will update the issue when progress is made.

**Comment by moxival** [comment]
Guys i see that you have added an R3 milestone and we sure as hell are not OK with this timeframe. At the moment we are sitting on our hands because this issue is blocking the **WHOLE** project. I will appreciate at least an alpha/beta/whatever release so we can continue the work.

**Comment by tsvetomir** [comment]
This is just a catch-all milestone for the release planning. Individual features are released as they become ready.
Work is already underway and will share previews earlier.

**Comment by moxival** [comment]
Thanx for the clarification @tsvetomir , hope we will have something to work with by the end of the month

**Comment by tsvetomir** [comment]
Merging this issue into #634
