### ISSUE TITLE
Can not add angular kendo package to angular 7 project

### ISSUE THREAD

**Issue by BtShp** [telerik/kendo-angular#2130]
**Describe the bug**
Can not add angular kendo package to angular 7 project.
get error :
"

> The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support

."

I tried exactly like written in:
[https://www.telerik.com/kendo-angular-ui/getting-started/](url)

**To Reproduce**
add new angular 7 project
add kendo ui buttons package
like in :
[https://www.telerik.com/kendo-angular-ui/getting-started/](url)

**Expected behavior**
sucssess adding kendo ui packages

.

**Comment by danielkaradachki** [comment]
We are not sure what may be causing the problem. Could you check what is the result of `npm info @progress/kendo-angular-buttons`? Also try clearing the cache `npm cache clean --force`.

**Comment by danielkaradachki** [comment]
Closing until further information is available.
