### ISSUE TITLE
How to open Scheduler External Form in popup dialog on Event Edit ??

### ISSUE THREAD

**Issue by santutoshi** [telerik/kendo-angular#2131]
Use this template for questions that are relevant to the community as a whole.

**If the issue is specific to your project, please open a [support ticket](https://www.telerik.com/account/support-tickets).**

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
