### ISSUE TITLE
TreeView toggles the check-boxes for its children nodes

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2132]
**Describe the bug**
When using a TreeView with the following CheckableSettings configuration:

`{
    checkChildren: true,
    checkParents: false,
    mode: 'multiple'
 }
`
and we have checked some of the children of a parent node and the parent node itself, then if we try to uncheck the parent node its children check-boxes will be toggled. 

**To Reproduce**
Check the following example:
[https://stackblitz.com/edit/angular-c2ahlt?file=app/app.component.ts](https://stackblitz.com/edit/angular-c2ahlt?file=app/app.component.ts)

1. Uncheck 'Furniture' node.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by AbhijatSaxena** [comment]
@ipeshev - any updates on when you'll be including this fix in your next release ?

**Comment by dimitar-pechev** [comment]
Released in **v4.3.1**.
