### ISSUE TITLE
ComboBox grouping renders wrong group name when dynamically changed

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2134]
**Describe the bug**
When changing the data source of grouped items and the new data is inserted BEFORE the current data, the group name of the new group is wrong. This bug doesn't occure when adding new data AFTER the current data.

**To Reproduce**
I changed the example from https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/grouping/
here:
https://stackblitz.com/edit/angular-928dn4
1. Open the dropdown
2. Write some filter value
3. The first group has the same name as the second. After the dropdown is closed and reopened again, the group name is correct.

**Expected behavior**
Newly inserted data should have the correct group name.

**Screenshots**
![image](https://user-images.githubusercontent.com/39991506/54680121-5129e600-4b09-11e9-8f2c-21c5ed3c1b4f.png)

**Browser**
 - OS: Windows 10
 - Chrome
 - Version 72.0.3626.121

**Comment by kunajs** [comment]
Any news regarding this problem?

**Comment by dimitar-pechev** [comment]
Related to #2162.

@kunajs, we'll look to add the fix next week.

**Comment by dimitar-pechev** [comment]
The fix has been included in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package (**v3.5.5-dev.201905211245**).

**Comment by dimitar-pechev** [comment]
Shipped in `@progress/kendo-angular-dropdowns@3.5.5`.
