### ISSUE TITLE
Context menu popupOpen not fired when using ContextMenuComponent.show()

### ISSUE THREAD

**Issue by zrsio4** [telerik/kendo-angular#2135]
## I'm submitting a...
* Bug report

## Current behavior
programmatically showing the context menu using .show(target) does not fire the popupOpen event.
In the example linked below, there is a very small empty context menu popup on the bottom left corner of the button, but no event fires.

## Expected behavior
If popup opens, event fires

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-eh833o

**Comment by danielkaradachki** [comment]
The behavior is by design. The API should not trigger the event handlers. You could set the items in the click handler:

https://stackblitz.com/edit/angular-eh833o-tjo2pt?file=app/app.component.ts
