### ISSUE TITLE
Combobox item is not fully displayed when item is selected and popup has horizontal scrollbar

### ISSUE THREAD

**Issue by lon-yang** [telerik/kendo-angular#2136]
**Describe the bug**
Combobox item is not fully displayed when item is selected and popup has horizontal scrollbar

**To Reproduce**

Add a long long item for the listItems
https://stackblitz.com/edit/angular-8ach7r

**Expected behavior**
Full display the option text

**Screenshots**
![a](https://user-images.githubusercontent.com/9428909/54730738-7ed46500-4bc5-11e9-8918-442daabac46d.gif)

**Browser**
 - OS:  Windows
 - Browser: Chrome
 - Version: 73.0.3683.75

**Comment by tapopov** [comment]
Thanks for reporting this @lon-yang 

We will investigate further and check if a fix can be provided through the [kendo-themes](https://github.com/telerik/kendo-themes). Meanwhile you could use `display: grid` as a workaround ([see demo](https://stackblitz.com/edit/kendo-list-overflow?file=app%2Fapp.component.ts)).

**Comment by lon-yang** [comment]
Thanks

**Comment by mbechev** [comment]
The same issue is reproduced in DropDownList as well.
Reported in private support thread: **1493299**

**Comment by tapopov** [comment]
Closing in favor of https://github.com/telerik/kendo-themes/issues/2030
