### ISSUE TITLE
kendo angular grid column lock separately

### ISSUE THREAD

**Issue by itsmeanish** [telerik/kendo-angular#2137]
www.telerik.com/kendo-angular-ui/components/grid/columns/locked/

System:
- TypeScript version: NA
- Node version: v10.15.1
- Platform:  Windows 

I'm seeking support here to lock kendo angular grid column separately. As I can see that, all locked columns are in a div and unlocked are in another div. Is there any possibility to lock some columns are in left and some are in right? Attaching my design requirement here for more info.

![table](https://user-images.githubusercontent.com/3928086/54737648-0e364400-4bd7-11e9-836a-97936dfa2511.jpg)

**Comment by tsvetomir** [comment]
Hi @itsmeanish,

This repository is for bug reports only. To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).

**Comment by itsmeanish** [comment]
Sure, thanks @tsvetomir
