### ISSUE TITLE
The current time marker is misplaced when using the Scheduler in day view

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2140]
**Describe the bug**
When the scheduler day view is rendered for the first time and startTime and endTime are defined the current time marker is always placed incorrectly (over 8:00 AM). 

**To Reproduce**
Check the following example: 
https://stackblitz.com/edit/angular-jrvxwy-qqdppy?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Fixed in 0.11.0:

https://stackblitz.com/edit/angular-jrvxwy-qldmus?file=app/app.component.ts
