### ISSUE TITLE
Add slotClass to dynamically set slot appearance

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2141]
## Suggested Behavior
It's often convenient to customize the appearance of the slots through code. For example, business hours can differ for each specific date.

To address these scenarios, the Scheduler should accept a `slotClass` callback that is called at run-time with information regarding the specific slot:
* Slot kind - all day, regular
* Slot start and end time
* Slot Resources

The callback returns an object with keys corresponding to the classes that should be applied to the slot, as used by [`NgClass`](https://angular.io/api/common/NgClass). This is similar to [`rowClass`](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-rowclass) in the Grid.

## Example

```html
<kendo-scheduler [slotClass]="getSlotClass">
    <kendo-scheduler-week-view>
    </kendo-scheduler-week-view>
</kendo-scheduler>
```

```ts
export class AppComponent {
  // Use an arrow function to capture the 'this' execution context of the class.
  public getSlotClass = (context: SlotClassArgs) => {
    return {
      evening: slot.start.getHours() > 17
    };
   }
}
```

## Issues

* The function will be called very frequently and may degrade performance.
* The callback will be called in the context of the Scheduler. To bind `this` to the component class, the developer must use an arrow function or [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind).

**Comment by danielkaradachki** [comment]
Released in 0.11.0:

https://stackblitz.com/edit/angular-ssfdxz?file=app/app.component.ts

**Comment by MagenicMike** [comment]
Can you change the background color of a slot to a specific color using this, I've tried everything, have no idea what properties can be returned?

**Comment by tsvetomir** [comment]
Yes, it's possible to change the background color via the CSS class. The [example](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerComponent/#toc-slotclass) in the API reference tries to demonstrate this, but fails as the CSS selector is not specific enough. We'll fix this by changing it to:

```css
     .k-scheduler .evening {
       background-color: steelblue;
     }
```

See [updated demo](https://stackblitz.com/edit/angular-jewg2a?file=app/app.component.ts).
