### ISSUE TITLE
[Grid] Checkbox multiple selection allows selecting ranges with Shift modifier

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2142]
Currently the Grid checkbox column selection does not allow for selecting a range of rows via shift-click. 

As this seems to be a behavior that users expect, based on a similar experience with popular applications like for example Outlook and Gmail, we can consider introducing this behavior in the Grid too.

For example:

When we click on a check box and Shift+click on another checkbox all the rows in between these rows should be checked. Ex: click on 2nd row and shift click on 8th row, all the rows in between 2nd and 8th should be selected. 

Internal information: requested in a private support thread - Ticket ID: 1172430

**Comment by atmakup1** [comment]
Thanks Dimitter. This is much needed functionality for our team and we are waiting for it from long time.

**Comment by courage007** [comment]
As trying using the component, I found this feature has already existed in it. In the **Multiple Selection Mode**, you can  taste the feature. You can get more details on the [office website](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-multiple-selection-mode).

**Comment by dtopalov** [comment]
To avoid any potential misunderstanding, I would like to point out that the functionality, described in the initial post is still not present, and is not the same as the existing one, mentioned by @courage007.

The built-in and existing selection functionality would allow for selecting multiple items by shift-clicking on the Grid row, but not in the checkboxes in the checkbox column.

**Comment by courage007** [comment]
To avoid same potential misunderstanding Iike me, I suggest to update the issue title as **“[Grid]Selecting multiple items in using shift-clicking can not work in clicking the checkboxes in the checkbox column, but only in clicking on the Grid row”.**

**Comment by dtopalov** [comment]
Also requested in Ticket ID: 1425479

**Comment by dtopalov** [comment]
Demand to be tracked in the Feedback portal:

https://feedback.telerik.com/kendo-angular-ui/1544214-allow-selecting-ranges-with-shift-modifier-with-checkbox-selection
