### ISSUE TITLE
for daylight saving change date can't enter hours starting with 2 in kendo-timepicker

### ISSUE THREAD

**Issue by MarekKu** [telerik/kendo-angular#2143]
**Describe the bug**
for daylight saving change date i.e. 31.03.2019 I would like to type hour 22:00. It is impossible as firstly typed 2 is automatically transformed to 0. Instead of 22 I get 03. 

**To Reproduce**
https://stackblitz.com/edit/angular-fjk2ms?file=app/app.component.ts

**Expected behavior**
can type 22 during daylight saving time change

**Screenshots**
What happens what I would like to type 22 in kendo-timepicker
![obraz](https://user-images.githubusercontent.com/23501198/54827329-00092600-4cb2-11e9-804c-c3cf827b0cde.png)

**Browser**
all

**Comment by tsvetomir** [comment]
This is a limitation of the time picker - it converts the value to the nearest valid date as you type.

One possible workaround is to bind to a date that is known to have no DST transition (e.g. 1980-01-01) and apply the set time to the desired date as a second step. See [updated example](https://stackblitz.com/edit/angular-fjk2ms-onjp2o?file=app/app.component.ts).

```ts
export class AppComponent {
  // Actual value
  public value: Date = new Date(2019, 2, 31, 10, 30, 0);

  // [Hour, Minutes] time parts
  public time: number[];

  // Value to be bound to the time picker
  public get timeValue(): Date {
    if (!this.time) {
      this.time = [this.value.getHours(), this.value.getMinutes()];
    }

    return new Date(
      1980, 0, 1,
      this.time[0], this.time[1], 0
    )
  }

  public set timeValue(raw: Date) {
    this.time = [raw.getHours(), raw.getMinutes()];

    this.value = new Date(
      this.value.getFullYear(),
      this.value.getMonth(),
      this.value.getDate(),
      this.time[0], this.time[1], 0
    )
  }
}
```
