### ISSUE TITLE
[Dropdowns] Dynamic push item to datasource cannot be selected since upgrade to 3.5.2 from 3.4.2

### ISSUE THREAD

**Issue by lon-yang** [telerik/kendo-angular#2144]
**Describe the bug**
The data source item from dynamic pushed are not selectable. Maybe caused by we don't change the reference of `dataSource`. But at `3.4.2` it's working fine, because 3.4.2 not using the `DataService`

**To Reproduce**

- `@progress/kendo-angular-dropdowns@3.4.2`: https://stackblitz.com/edit/angular-htxvek-alymuo?file=app/app.component.ts
- `@progress/kendo-angular-dropdowns@3.5.2`: https://stackblitz.com/edit/angular-htxvek?file=app%2Fapp.component.ts

Same code, bug different behavior

**Expected behavior**
Same as the `3.4.2`

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 73.0.3683.75

**Additional context**
I have changed the souce code at line 11 of `data.service.ts`. And it's working. Can we fix this ?

```ts
public get itemsCount(): number {
  if (!this.grouped && this.data) {
    if (this._itemsCount !== this.data.length) {
      this._itemsCount = this.data.length;
    }
  }
  return this._itemsCount;
}
public set itemsCount(val: number) {
  this._itemsCount = val;
}
private _itemsCount: number = 0;
```

**Comment by tsvetomir** [comment]
Fix released in v3.5.3
