### ISSUE TITLE
multi-select: select filtered item will clear search bar.

### ISSUE THREAD

**Issue by strtsoia1983** [telerik/kendo-angular#2145]
## I'm submitting a...

* Bug report 

## Current behavior
Type letter l in search bar, two items shows up(small, large). After check one of them, letter I in k-searchbar will be cleared out automatically.

## Expected behavior
After select a item, search criteria(letter l) in search bar should stay the same.

## Minimal reproduction of the problem with instructions
Step for reproduce.
1. In search bar, type letter I. 
2. select one of the items.
3. letter l in the search bar gets wipe out. It causes.
Demo link: https://stackblitz.com/edit/angular-2gd6qr?file=app/app.component.ts

The cause of this issue comes from following code. (Pay attention to the last if statement)
`MultiSelectComponent.prototype.handleItemChange = function(event) {
    this.change(event);
    if (this.autoClose) {
        this.togglePopup(false);
    }
    if (isPresent(event.added) && event.added !== -1) {
       this.clearFilter();
    }
}`
## Environment

Package versions:
@progress/kendo-angular-dropdowns": "3.5.2"
```

```

Browser:
All browsers

System:
- TypeScript version: 2.7.2
- Node version: node --11.9.0  npm --6.7.0
- Platform:  Mac

I notice jquery version does not have this issue. I think to fix this issue, just remove the clearFilter calling.

**Comment by dimitar-pechev** [comment]
@strtsoia1983, we've reviewed the current behavior and will look to change it when `autoClose` is set to `false`. The filter text will not be automatically cleared until the the component is closed, as it does make sense to keep the filter text in that case. To allow the end user to quickly change their filter query, when a selection is made, the filter text will be selected. 

We'll also leave the current behavior as is, when `autoClose` is set to `true` (which is the default state).

**Comment by sehaxx** [comment]
Hi 

I'm currently facing this issue, is there an estimate when this fix will be released.

**Comment by ipeshev** [comment]
Feature is available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released in **v4.4.0.**
