### ISSUE TITLE
Pdf Export Arabic 

### ISSUE THREAD

**Issue by kokodda** [telerik/kendo-angular#2146]
Pdf Export When export words Utf8 like Arabic appear different letters

**Comment by tsvetomir** [comment]
The standard PDF fonts support only ASCII. To render Unicode symbols, use an [embedded font](https://www.telerik.com/kendo-angular-ui/components/drawing/pdf-output/embedded-fonts/).

Currently this is buried deep in our Drawing library documentation. We'll link to this topic in the main [PDF Export](https://www.telerik.com/kendo-angular-ui/components/pdfexport/) documentation as well.

**Comment by tsvetomir** [comment]
Added documentation topic on [Embedded Fonts](https://www.telerik.com/kendo-angular-ui/components/pdfexport/embedded-fonts/).

**Comment by amiraziz** [comment]
i define embedded font but it not works!

module:
```
import {defineFont} from "@progress/kendo-drawing/pdf";

defineFont({
  'BNazanin': '/font/bnazanin/BNazanin.ttf',
  'BNazanin|Bold': '/font/bnazanin/BNazaninBd.ttf',
  'IRANSans': '/font/IRANSans/ttf/IRANSans.ttf',
  'IRANSans|Bold': '/font/IRANSans/ttf/IRANSans_Bold.ttf',
});
```
component.css :
```
kendo-pdf-export {
  font-family: "BNazanin", "IRANSans", sans-serif;
  font-size: 14px;
}
```

i used two fonts for test their styles, but it not generate correct rtl pdf content. 


this picture maybe help you what i say:


![pdf](https://user-images.githubusercontent.com/5073250/79319738-f803d000-7f1d-11ea-9b89-2052460d6dd2.JPG)

**Comment by mohameds93** [comment]
I have tried to follow the steps there but couldn't get it working.
It would be great if this added with a working example.

**Comment by tsvetomir** [comment]
Right-to-left scripts are not supported by the PDF Export component. I'm sorry for the misleading initial reply.

Embedding the font solves only part of the issue. But it's not sufficient—proper rendering right-to-left scripts is extremely complex. Although the browser already has this implemented, the result is not available through the DOM. Our attempts at implementing this have failed so far.

We've listed the limitation in the [Embedded Fonts](https://www.telerik.com/kendo-angular-ui/components/pdfexport/embedded-fonts/) page in addition to the [Drawing Limitations and Browser Support](https://www.telerik.com/kendo-angular-ui/components/drawing/limitations-browser-support/).
