### ISSUE TITLE
Data Query Filter Of Array

### ISSUE THREAD

**Issue by kanji-keraliya** [telerik/kendo-angular#2147]
How to filter of objects's array element. check bellow stackblitz example, here I want to filter by tag name is 'tag 01'

https://stackblitz.com/edit/ck5mkk?file=index.js

**Comment by tsvetomir** [comment]
This issue tracker is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing this scenario.
