### ISSUE TITLE
[Grid][Chrome] Sorting triggered when grouping and an auto-binding directive is used

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2148]
In latest Chrome (v. 73.x) the Grid sorting is triggered when an autobinding (kendoGridBinding or kendoGridGroupBinding) directive is used, and a column header is dragged (regardless of whether it is dropped in the designated area or not).

Observable in the online demos:

[https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/#toc-built-in-directive](https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/#toc-built-in-directive)

[https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-using-virtualization-with-grouping](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-using-virtualization-with-grouping)

**Comment by danielkaradachki** [comment]
Fixed in 3.14.0:

https://stackblitz.com/edit/angular-ysq4m6?file=app/app.component.ts
