### ISSUE TITLE
grid head display the "field" attribute,not the "title"

### ISSUE THREAD

**Issue by lucifercha** [telerik/kendo-angular#215]
I upgrade the grid version from 0.10.0 to 0.13.0,grid head display the "field" attribute,not the "title" ,i am not sure whether it is a bug,but when the grid version is 0.10.0,it works.
![image](https://cloud.githubusercontent.com/assets/3349701/22193204/b48e1852-e174-11e6-83ac-b09c4fb5ccb4.png)

`<kendo-grid [data]="gridData" [height]="370">`
  `<kendo-grid-column field="infoName" title="ID" width="40">`
  `</kendo-grid-column>`
  `<kendo-grid-column field="oper" title="Oper" >`
`	  <template kendoGridCellTemplate let-dataItem>`
`		  <input value="{{dataItem.oper}}"/>`
`	  </template>`
 ` </kendo-grid-column>`
`</kendo-grid>`

**Comment by rusev** [comment]
This seems to be working in the docs examples. See the first example in the  [Grid Overview](http://www.telerik.com/kendo-angular-ui/components/grid/) page.

Could you share a runnable example demonstrating the behavior?

**Comment by lucifercha** [comment]
I know the examples is working.I copy the code from the doc example to my project,it still not work.
I think it should be because of my version of angular,i used angular 2.2.4

**Comment by lucifercha** [comment]
this is my version of angular and kendo-angular
`"@angular/common": "2.2.4",
    "@angular/compiler": "2.2.4",
    "@angular/core": "2.2.4",
    "@angular/forms": "2.2.4",
    "@angular/http": "2.2.4",
    "@angular/platform-browser": "2.2.4",
    "@angular/platform-browser-dynamic": "2.2.4",
    "@angular/router": "3.2.4",
    "@angular/upgrade": "2.2.4",
    "@progress/kendo-angular-buttons": "^0.16.0",
    "@progress/kendo-angular-dialog": "^0.14.0",
    "@progress/kendo-angular-dropdowns": "^0.26.4",
    "@progress/kendo-angular-grid": "^0.13.2",
    "@progress/kendo-angular-intl": "^0.9.0",
    "@progress/kendo-angular-layout": "^0.18.4",
    "@progress/kendo-angular-upload": "^0.10.0",
    "@progress/kendo-data-query": "^0.3.5",
    "@progress/kendo-theme-default": "^2.11.3",`

**Comment by lucifercha** [comment]
@rusev i think it is a bug in angular 2.2.4, i change the version in plunker
![image](https://cloud.githubusercontent.com/assets/3349701/22283124/65a609a4-e31b-11e6-854a-e99b95c99d2d.png)

 and the result is [http://run.plnkr.co/p6h4qYBQ2gi4f87n/](url)

**Comment by rusev** [comment]
Indeed it seems like an issue in Angular 2.2.4. My suggestion will be to upgrade to Angular 2.4.X.
