### ISSUE TITLE
Event triggered by clicking on filter/clear button in kendo angular UI.

### ISSUE THREAD

**Issue by sapankumarjha** [telerik/kendo-angular#2154]
I want to access which event gets triggered when we click on Clear button/Filter Button in kendo filtermenu in kendo angular(2+) ui.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
