### ISSUE TITLE
[Grid][Accessibility] Expand/collapse icons are links with no text

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2155]
The Wave accessibility tool reports errors related to the grouped Grid expand/collapse icons:

![image](https://user-images.githubusercontent.com/7533599/54991945-b593ec00-4fc6-11e9-84ff-6d97fe4e3b69.png)

Same goes for expand/collapse icons in master-detail scenarios.

**Comment by Raisolution** [comment]
The issue has been addressed in `v5.5.0` of the Grid package.
