### ISSUE TITLE
[Scheduler] The view selection dropdown is shown although only one view is activated.

### ISSUE THREAD

**Issue by MelvilQ** [telerik/kendo-angular#2156]
**Describe the bug**
The view selection dropdown is shown although only one view is activated.

**To Reproduce**
Start from the basic example for the scheduler and remove all views except the day-view.

[See on Stackblitz](https://stackblitz.com/edit/angular-zabp1t?file=app/app.component.ts)

**Expected behavior**
The dropdown is not displayed.

**Screenshots**
![kendo-scheduler1](https://user-images.githubusercontent.com/2684337/54992857-b295fd00-4fc0-11e9-84d8-0f1230e04ac1.PNG)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by MelvilQ** [comment]
I changed the version to "dev" in Stackblitz, but the dropdown is still displayed.

**Comment by danielkaradachki** [comment]
Seems to work as expected here:
https://stackblitz.com/edit/angular-zabp1t-wfqd7r?file=app/app.component.ts

**Comment by MelvilQ** [comment]
Not really. The whole view selection element should be removed in this case (the button is useless, it doesn't do anything).

**Comment by danielkaradachki** [comment]
We will keep the item for now. You can remove it via a [template](https://www.telerik.com/kendo-angular-ui/components/scheduler/toolbar/) or CSS. Will reconsider if the change is requested by other users.

**Comment by danielkaradachki** [comment]
Released in 0.11.0:

https://stackblitz.com/edit/angular-zabp1t-s5xnkd?file=app/app.component.ts
