### ISSUE TITLE
NumericTextBox displays value in scientific notation

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2160]
**Describe the bug**
When using a decimal number with many digits after the decimal point for the value of the NumericTextBox, it displays the number in scientific notation.

**To Reproduce**
Check the following example:
[https://stackblitz.com/edit/angular-e1c65d-7jgq3l?file=app/app.component.ts](https://stackblitz.com/edit/angular-e1c65d-7jgq3l?file=app/app.component.ts)

1. Click inside the Kendo NumericTextBox

**Additional context**
The issue is caused by the default JavaScript functionality as demonstrated in the following section of out documentation:
[https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/#toc-known-limitations](https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/#toc-known-limitations)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
