### ISSUE TITLE
Why kendogrid's row index is not start with 0 when page index > 0

### ISSUE THREAD

**Issue by BruceAndLee** [telerik/kendo-angular#2161]
Why kendogrid's row index is not start with 0 when page index > 0?
When pageIndex = 0, the rowIndex  like this: 1,2,3,4,5,6,7,8,9,10
but when pageIndex  = 1，the rowIndex like this:11,12,13,14,15.....

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
