### ISSUE TITLE
Labelling when filtering on grouped MultiSelect component

### ISSUE THREAD

**Issue by Baffour** [telerik/kendo-angular#2162]
**Describe the bug**
When using a MultiSelect component with grouping and filtering, if you start typing to filter the available items, the group labels do not update until you scroll, meaning the grouping label is wrong

 
**To Reproduce**
See the runnable snippet here: https://stackblitz.com/edit/angular-b94cce
1.  Click into multi-select input box
2.  Start typing "Mystery"

**Expected behavior**
You should see "Food Subcategory" as the group label, since the only option in "Food Category" has been filtered out.
Instead, I you still see "Food Category".
Scrolling down the list causes the group label to update correctly, so I imagine whatever is running on the scroll event to update the labels should also be running on a filter change event.

**Screenshots**
![image](https://user-images.githubusercontent.com/3619447/55090032-51485980-50a6-11e9-91bc-21235b23efb6.png)

![image](https://user-images.githubusercontent.com/3619447/55090187-9076aa80-50a6-11e9-9a87-2ca2f6d16ef9.png)

![image](https://user-images.githubusercontent.com/3619447/55090117-72a94580-50a6-11e9-857a-e2fa41efa855.png)

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 71

**Additional context**
None

**Comment by Baffour** [comment]
Hi @dimitar-pechev, any update on this?

**Comment by dimitar-pechev** [comment]
@Baffour, sorry for the delayed response and thanks for the good reproduction example. 

We have the code fix in place and we'll look to introduce it next week.

**Comment by Baffour** [comment]
@dimitar-pechev Hi dimitar, what's the status of the issue? I noticed a new release of the Kendo UI for angular but I can still reproduce the issue in the newest version.

**Comment by dimitar-pechev** [comment]
The fix has been included in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dropdowns` package (**v3.5.5-dev.201905211245**).

**Comment by Baffour** [comment]
@dimitar-pechev Thanks, can confirm the fix works in my code as well as my stackblitz reproduction!

**Comment by dimitar-pechev** [comment]
Shipped in `@progress/kendo-angular-dropdowns@3.5.5`.
