### ISSUE TITLE
[Scheduler] month and agenda header template

### ISSUE THREAD

**Issue by honzis1364** [telerik/kendo-angular#2165]
Hello, is it possible to edit month and agenda header template in the Scheduler? I've found https://www.telerik.com/kendo-angular-ui/components/scheduler/api/DateHeaderTemplateDirective/ but it only refers to day, week and timeline header template edit.

Thank you!

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
