### ISSUE TITLE
SplitButton open and close events fire twice 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2166]
**Describe the bug**
SplitButton dropdown events (open and close) fire twice each time when the popup is about to open or close.

**To Reproduce**
[https://stackblitz.com/edit/angular-dlxylj?file=app/app.component.ts](https://stackblitz.com/edit/angular-dlxylj?file=app/app.component.ts)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v4.4.0
