### ISSUE TITLE
Kendo Notification hyperlink 

### ISSUE THREAD

**Issue by HimanshuRising** [telerik/kendo-angular#2167]
Hi We are using kendo notification with angular 6. We have a requirement to display a hyperlink with-in the notification along with message. Currently we are displaying simple message in notification but now we need to add the hyperlink also. Can somebody help us achieving this.

Thanks 
Himanshu Rajput

**Comment by elena-gancheva** [comment]
Hi @HimanshuRising ,

This repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for further assistance with the specific scenario of your problem.
