### ISSUE TITLE
ComboBoxComponent  text.toLowerCase is not a function

### ISSUE THREAD

**Issue by romstyop** [telerik/kendo-angular#217]
EXCEPTION: Error in ./ComboBoxComponent class ComboBoxComponent - inline template:2:12 caused by: text.toLowerCase is not a function

i have template like this:
`<kendo-combobox
        name="person"
        [data]="dataPersons"
        [placeholder]="'Выберите сотрудника...'"
        [value]="selectedPerson"
        [valueField]="'Id'"
        (valueChange)="handlePersonChange($event)"
        [filterable]="true"
        (filterChange)="handlePersonFilter($event)"
        style="width:100%;">
        <template kendoComboBoxItemTemplate let-dataItem>
          {{ dataItem }}
        </template>
      </kendo-combobox>`

component implementation:

`this.dictService.persons(terms).subscribe(
     persons => {
     console.log(persons);
     this.dataPersons = persons || [];
     }}`

and person model implementation:

`export class Person {
  Id: string;
  FirstName: string;
  SecondName: string;
  LastName: string;

  toString(): string {
    return `${this.LastName} ${this.FirstName} ${this.SecondName}`;
  }
}`

Selecting some item and loses focus generates this error.

**Comment by ggkrustev** [comment]
@romstyop, It seems that you missed to define the [textField] property binding:

http://www.telerik.com/kendo-angular-ui/components/dropdowns/api/ComboBoxComponent/#toc-textfield

This property is required.

**Comment by romstyop** [comment]
Thanks, it's work!
But in this case i can use getter like this get FullName: string {...} instead toString() method.
