### ISSUE TITLE
Unable to scroll to next page by clicking on the last row

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2170]
**Describe the bug**
By user ticket
Scrolling page into view by clicking on last visible row stops functioning at some point withut recovery.

**To Reproduce**
   
1. Open https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/
2. Use first example of the Grid
3. Select last unhidden row (ID 12) by clicking on it
4. The view scrolls down so that the selected row is on top
5. Repeat that till you reach row with ID 51
6. After clicking on that row no scrolling happens

**Expected behavior**
Scrolling page into view by clicking last visible row should work no matter row index

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by tsvetomir** [comment]
The issue is caused by incorrect `rowHeight` set in the example - it is set to 35px while in reality it's 36px. This leads to inaccurate row index calculation.

I'll fix the demo, but we really need a way to enforce the set `rowHeight`.

**Comment by tsvetomir** [comment]
See updated demo at https://stackblitz.com/edit/angular-psrasc

**Comment by tsvetomir** [comment]
The example has been amended in the [development site](https://www.telerik.com/kendo-angular-ui-develop/components/grid/scroll-modes/virtual/). It will be published live with the next site update.
