### ISSUE TITLE
[Scheduler] - Scheduler swallows scroll events on iPhone Safari when editable

### ISSUE THREAD

**Issue by MelvilQ** [telerik/kendo-angular#2172]
**Describe the bug**
Editable scheduler on a scrollable page. When opening the page with an iPhone, the page is not scrollable on the scheduler area. The scheduler seems to swallow the scroll events. On other platforms, the scrolling behavior is as expected.

**To Reproduce**
Starting from the basic scheduler example, I made the scheduler editable and removed the height constraint:

https://stackblitz.com/edit/angular-fhccmj?file=app/app.component.ts

**Expected behavior**
The page is scrollable everywhere.

**Browser**
Safari on iPhone

**Comment by danielkaradachki** [comment]
Should be fixed in 0.11.0
