### ISSUE TITLE
The value of the noRecords input property is not adjusted if it is asynchronously changed

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2174]
**Describe the bug**
When we change the string passed to the noRecords field asynchronously, the Grid does not demonstrate the latest value for the translation.
**To Reproduce**

Check the following example:
[https://stackblitz.com/edit/angular-fewbuc?file=app/app.component.ts](https://stackblitz.com/edit/angular-fewbuc?file=app/app.component.ts)

**Comment by ipeshev** [comment]
When this , then https://github.com/telerik/kendo-angular-grid/pull/782

**Comment by danielkaradachki** [comment]
Should be fixed in the latest dev version of the @progress/kendo-angular-l10n package:

https://stackblitz.com/edit/angular-fewbuc-ezqgsf?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Released in v1.4.1 of the `@progress/kendo-angular-l10n` package

https://stackblitz.com/edit/angular-fewbuc-2cr1ns?file=app/app.module.ts
