### ISSUE TITLE
[Toolbar] Allow custom css classes

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-angular#2175]
Allow Toolbar component to render custom `CSS` classes.
For example: `<kendo-toolbar class="header"></kendo-toolbar>`

**Comment by ipeshev** [comment]
Enhancement available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Released in v1.1.1
