### ISSUE TITLE
Dynamic change of scheduler resources not working properly

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2178]
**Describe the bug**
When scheduler's resources are bind to a property that can be dynamically changed, the colors of the events are changed only to 1 color of the new resources. I have to do some click action to correct the colors (e.g. change the calendar view, change the selected date...)

**To Reproduce**
Here is the example on Stackblitz: https://stackblitz.com/edit/angular-b5acnf
Click the checkbox - all events' color is changed to #B6FF00, but there should be different colors dependent on ownerID

**Expected behavior**
The colors should be applied by currently used resources set.

**Screenshots**
WRONG:
![image](https://user-images.githubusercontent.com/39991506/55554077-3008ee00-56e2-11e9-85dc-02798291dd1d.png)
CORRECT: 
![image](https://user-images.githubusercontent.com/39991506/55554096-3dbe7380-56e2-11e9-9c59-c49601c12826.png)

**Browser**
 - OS: Windows 10
 - Chrome
 - 73.0.3683.86

**Additional context**

**Comment by danielkaradachki** [comment]
Fixed in 0.11.0:

https://stackblitz.com/edit/angular-b5acnf-bxavwe?file=app/app.component.ts
