### ISSUE TITLE
[NumericTextBox] Option for default formatted value

### ISSUE THREAD

**Issue by alpkarli** [telerik/kendo-angular#2179]
When I change format of the numeric text box to 'n', I can write with no format limitation as expected. But after 3 digits of the fraction if it is not on the focus it hides automatically the other digits as in the example below.

Out of focus:
![image](https://user-images.githubusercontent.com/28437603/55559119-386b2400-56f6-11e9-9059-f59934804a3e.png)

Focused:
![image](https://user-images.githubusercontent.com/28437603/55559142-45881300-56f6-11e9-93fc-e98d0b320732.png)

Is it possible to add an option to not hide or not limit the fraction part when out of the focus in this formatting? 

### Reproduction

[StackBlitz](https://stackblitz.com/edit/angular-bjvflz)

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
