### ISSUE TITLE
Can not add @progress/kendo-angular-sortable to angular 7.2.12 project.

### ISSUE THREAD

**Issue by ericardezp** [telerik/kendo-angular#2180]
**Describe the bug**
Can not add @progress/kendo-angular-sortable to angular 7.2.12 project.

get error :
"The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support."

**To Reproduce**
add new angular 7.2.12 project
add kendo ui sortable module `ng add @progress/kendo-angular-sortable`

**Expected behavior**
Sucssess adding kendo ui module

**Additional context**
Windows 10 Enterprise 64
Visual Studio Code 1.32.3
Angular CLI version 7.3.8
Node version 10.15.3
NPM version 6.4.1

`npm info @progress/kendo-angular-sortable`

@progress/kendo-angular-sortable@2.0.1 | SEE LICENSE IN LICENSE.md | deps: 3 | versions: 63
A Sortable Component for Angular 2
https://github.com/telerik/kendo-angular-sortable#readme

keywords: Kendo UI, Progress, Sortable, Angular 

dist
.tarball: https://registry.npmjs.org/@progress/kendo-angular-sortable/-/kendo-angular-sortable-2.0.1.tgz
.shasum: bc931d8db6f445c5e3da2c6f2bff1eb8ae57ad1b
.integrity: sha512-0QsP2jpIEUbQDguLFeo+KF91cJzEgsAs3k6RCD6RwMJxJ+mVONgsPZsi9sqAZ7fkoHJjD3tMnRpgnLPyCjArkQ==
.unpackedSize: 344.4 kB

dependencies:
@progress/kendo-schematics: ^0.2.0 @telerik/kendo-draggable: ^1.8.2   tslib: ^1.7.0

maintainers:
- progress <npm@progress.com>

dist-tags:
data-mutability: 2.0.0-data-mutability.2  dev: 2.1.0-dev.201903271642               flatmeta: 1.0.8-flatmeta.2                latest: 2.0.1                             ng2: 0.9.1

published 2 months ago by progress <npm@progress.com>

**Comment by tapopov** [comment]
Thanks for reporting this @ericardezp, we are working on it.

**Comment by tsvetomir** [comment]
Fixed in the latest development build:
`ng add @progress/kendo-angular-sortable@dev`

We'll need a few more days for the official release.

**Comment by danielkaradachki** [comment]
Released with 2.1.0
