### ISSUE TITLE
Wrong tooltip callout position near right screen border

### ISSUE THREAD

**Issue by eugene-sinitsyn** [telerik/kendo-angular#2181]
Callout shifted left.
![image](https://user-images.githubusercontent.com/23496057/55629868-f48f2200-57bc-11e9-835c-e838047072db.png)

**To Reproduce**
1 Open https://stackblitz.com/edit/angular-kq4b9o
    _(position of osaka is changed to { top: 201px; left: 600px; })_
2 Scroll all the way right
3 Hover "Osaka"

The issue occurs when right after `this.bindContent(...)` text takes 2 lines but in the end it takes 1 line.
![image](https://user-images.githubusercontent.com/23496057/55630536-982d0200-57be-11e9-8bc0-52a8c82f127b.png)
![image](https://user-images.githubusercontent.com/23496057/55630642-d4f8f900-57be-11e9-8708-8d0d213bfef1.png)

**Expected behavior**
Callout is aligned with anchor element.

**Browser**
 - OS: Widnows 10
 - Browser : Google Chrome
 - Version: 73.0.3683.86

**Comment by ipeshev** [comment]
Thank you for the bug report , in deed scroll right produces a bug in positioning.

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by tsvetomir** [comment]
Fixed in v1.2.1
