### ISSUE TITLE
[Scheduler] Agenda view does not trigger eventDblClick

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2182]
**Describe the bug**
In the current scheduler agenda view the `eventDblClick` event is not triggered when you do a double click on any event . 

**To Reproduce**
https://stackblitz.com/edit/scheduler-agenda-dblclick?file=app/app.component.ts

Try doubleclicking on an event. Nothing will be logged to the console. 

**Expected behavior**
An event should be triggered just like in any other view. 

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 73

**Additional context**
Probably other `event*` events are not triggered as well.

**Comment by danielkaradachki** [comment]
The events are left out for the agenda view on purpose. We will consider it for future versions.

**Comment by danielkaradachki** [comment]
Released in 0.15.0

https://stackblitz.com/edit/angular-1lcdaq?file=app/app.component.ts
