### ISSUE TITLE
Issue with onDateChange approach for events refreshing

### ISSUE THREAD

**Issue by robertfield** [telerik/kendo-angular#2183]
I am using the Kendo Scheduler for the first time and I am using the approach for OnDateChanged as documentation shown here 

https://www.telerik.com/kendo-angular-ui/components/scheduler/data-binding/ 

I noticed that on initialse the this.cd.detectChanges results in a console error 

'dayRanges' of undefined

and this is repeated each time the active view is changed. 

please note that this is also happening in the StackBlitz

**Comment by danielkaradachki** [comment]
Should be fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/) version:

https://stackblitz.com/edit/angular-xx4bv7-bbdtjy?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Fixed in 0.11.0:

https://stackblitz.com/edit/angular-t66dma?file=app/app.component.ts
