### ISSUE TITLE
Kendo grid inCellTab is unknown property

### ISSUE THREAD

**Issue by MaraZ1** [telerik/kendo-angular#2184]
**Describe the bug**
After filling [inCellTab]="something" the message below appears:
"Can't bind to 'inCellTab' since it isn't a known property of 'kendo-grid'."

**To Reproduce**
1) $ ng new someApp
2) $ ng add @progress/kendo-angular-grid
3) copy paste the code from tutorial example https://www.telerik.com/kendo-angular-ui/components/grid/

**Expected behavior**
The kendo grid should work and should not throw this error.

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 73.0.3683.86

**Comment by danielkaradachki** [comment]
inCellTab is no a built-in directive. It is implemented as part of the following example:

https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/#toc-controlling-the-focus
