### ISSUE TITLE
Object is not a function 

### ISSUE THREAD

**Issue by ngohungphuc** [telerik/kendo-angular#2185]
**Describe the bug**
I have this error when using these package with angular 7

```
    "@progress/kendo-angular-dateinputs": "^1.4.2",
    "@progress/kendo-angular-dialog": "^1.0.4",
    "@progress/kendo-angular-dropdowns": "^1.2.1",
    "@progress/kendo-angular-inputs": "^1.0.5",
    "@progress/kendo-angular-intl": "^1.2.1",
    "@progress/kendo-angular-l10n": "^1.0.4",
    "@progress/kendo-angular-tooltip": "^1.1.2",
    "@progress/kendo-angular-upload": "^1.2.1",
    "@progress/kendo-theme-default": "^2.38.0",
    "@progress/kendo-angular-popup": "^1.2.2",
```

**Screenshots**
![chrome_sliPDl3jEf](https://user-images.githubusercontent.com/13591213/55793954-49e56f00-5aee-11e9-9b97-f5272a8ccfd7.png)

So which package version I should you in order to work with angular 7
Thanks

**Comment by sbittis** [comment]
@ngohungphuc Did you find a solution for this? I get the same error.

**Comment by ngohungphuc** [comment]
@sbittis I just updated to lastest version and is work

**Comment by sbittis** [comment]
Thanks!
