### ISSUE TITLE
Release version 3.13.1 of grid exposes EditService class instead of EditService interface

### ISSUE THREAD

**Issue by idseefeld** [telerik/kendo-angular#2186]
Please compare version 3.13.0 and 3.13.1 while you build a class which implements EditService from @progress/kendo-angular-grid.
You'll notice a breaking difference in signature.

Kind regards,
Dirk

**Comment by tsvetomir** [comment]
Thanks for the heads-up! The issue is fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v3.14.0 of the Grid. This version may exhibit a few minor rounding errors 😀
