### ISSUE TITLE
The size of a SplitterPane is calculated incorrectly

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2192]
**Describe the bug**

When the size of a SplitterPane is set programmatically, it does not take into consideration the width of the SplitterBar - 8px.

**To Reproduce**
Check the following example:
[https://stackblitz.com/edit/angular-mxstj5?file=app/app.component.ts](https://stackblitz.com/edit/angular-mxstj5?file=app/app.component.ts)

As a workaround we can calculate the size with respect to the 8px width of the SpliterBar as demonstrated in the example. 

**Expected behavior**
The minimum width of the SplitterPane should be the same when dragging the SplitBar and when manualy changing the value of the size of the SplitterPane.

**Comment by PetarMetodiev** [comment]
The splitter does not allow for all panes to have `[size]` input. Those which have `[size]` have their widths calculated based on the width of the container. The remaining panes(the ones without `[size]`) fill the remaining space of the container and share it with the splitter bars.

Having said that, in the example only the right pane has a set `[size]` input. `[size]` takes precedence over `[min]`. The governing logic is that the right pane has a fixed `[size]` and the remaining space is filled by the left pane and the splitter. When the splitter bar is dragged, the `[size]` is no longer fixed and `[min]` is respected(the inner width of the left pane is exactly 15% of the whole container).
