### ISSUE TITLE
Grid: kendoGridGroupHeaderTemplate doesn't work with aggregates

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular#2193]
**Describe the bug**
kendoGridGroupHeaderTemplate doesn't work with aggregates.

**To Reproduce**
https://stackblitz.com/edit/angular-2kj1os?file=app/app.component.ts

**Expected behavior**
I expect the same behavoir like at kendoGridGroupHeaderTemplate. It should show the sums per columns.

**Version**
latest

**Comment by danielkaradachki** [comment]
aggregates is not default context variable and must be assigned:

https://stackblitz.com/edit/angular-2kj1os-kfjxpm?file=app/app.component.ts
