### ISSUE TITLE
Kendo-DropDownList performance issue in Internet Explorer 11

### ISSUE THREAD

**Issue by RahulMalhotraa** [telerik/kendo-angular#2194]
I'm using the Kendo-dropdownlist in my angular project which displays nearly 2500 values.When I run the solution it works fine in Google Chrome browser but when I run the same in Internet Explorer the List doesn't populate and even if it does it is not-responsive.Our Client has Internet Explorer as their default browser and we can't just ask them to switch to other browser to resolve the issue. Is there a way to improve the performance in IE browser? Any lead is much appreciated.

**Comment by tapopov** [comment]
Hi @RahulMalhotraa 
This seems related to https://github.com/telerik/kendo-angular/issues/2195

**Comment by dummdidumm** [comment]
Disclaimer: I'm not a Kendo developer

What I did was to use the combobox instead and then introduce a custom filter service which filters by the user's input and, when there are more than X (in my case 300) values, I set the data to an empty array and show a custom "no elements" message instead, saying something like "there are too many elements, please filter".
