### ISSUE TITLE
Virtual scrolling support

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#2195]
## I'm submitting a...
* Suggestion for improvement  
## Current behavior
Currently the `kendo-angular-dropdowns` components do not support virtual scrolling. This results in poor performance when huge datasets are used, due to number of elements rendered in the DOM.
## Expected behavior
The components should support virtual scrolling.

**Comment by Alex-Torres** [comment]
Any updates?

**Comment by tapopov** [comment]
The feature is available through the `dev` distribution channel.
