### ISSUE TITLE
[Scheduler] Slot duration not updated properly

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2197]
When the slotDuration property is dynamically changed, the Scheduler does not reflect the new value accordingly (only after a change in the day/week view and back, or a toggle of business hours/all day views):

[https://stackblitz.com/edit/angular-kvweyc?file=app/app.component.ts](https://stackblitz.com/edit/angular-kvweyc?file=app/app.component.ts)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v0.12
