### ISSUE TITLE
Editor content height

### ISSUE THREAD

**Issue by baltyan** [telerik/kendo-angular#2198]
**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**
Editor content's height is fixed 300px. It would be nice to pass as input binding.

**Comment by valchev** [comment]
Implemented in `v.0.5.0`

The developer can set the editor height via `style` attribute.
```
  <kendo-editor style="height: 600px;"></kendo-editor>
```

By default, the editor has no fixed height and will expand according to the content height.

**Comment by baltyan** [comment]
@valchev your solution works, but there is a another bug with toolbar icons
![2019-05-23_20-04-40](https://user-images.githubusercontent.com/9678938/58269057-bca56380-7d97-11e9-9a76-f4afa88f75ae.gif)
