### ISSUE TITLE
editor breaks DialogService

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#2201]
**Describe the bug**
After rendering the editor, `DialogService.open(..)` stops working. Simply nothing happens.

**To Reproduce**
* render a component containing the editor
* remove the component including the editor
* => dialogService.open() stopped working

**What happens...**

Assuming you have `<div kendoDialogContainer></div>` somewhere in your layout, it will set `DialogContainerService.container` during startup. Now we can use DialogService.open() and it will use our div as host  element. If we render an editor component (sometime during app lifetime), the following seems to happen:

* editor template has it's own kendorDialogContainer directive, this will set `DialogContainerService.container` to the div that is part of the editor.
* … let's navigate navigate to another page (= destroy the editor component, we have no editors rendered now).
* => `DialogContainerService.container` is still set the the div of the destroyed editor. That's a detached node and so nothing will happen when we call DialogService.open().

**Comment by Raisolution** [comment]
Hi @cluetjen,

Thanks for noticing this issue, it has been reported in #2125. A fix will be released next week.
