### ISSUE TITLE
Compile error after setup completes for Kendo Editor in Angular 0.4.0

### ISSUE THREAD

**Issue by avinash13jun** [telerik/kendo-angular#2202]
Using [https://www.telerik.com/kendo-angular-ui/components/editor/#toc-quick-setup-with-angular-cli-v6-or-later](url) documentation installed Kendo Editor with ng add and manuall installation but everytime I get error with prosemirror-state install. After manually installing prosemirror-state I get the following error - 

ERROR in node_modules\@progress\kendo-angular-editor\dist\es2015\index.d.ts.FileLinkDialogComponent.html(10,64): : Expected 0 arguments, but got 1.

Please help with this bug.

**Comment by Raisolution** [comment]
Hi @avinash13jun 

This looks like a duplicate of #2200. The issue is fixed in `v4.1.0`

**Comment by avinash13jun** [comment]
> Hi @avinash13jun
> 
> This looks like a duplicate of #2200. The issue is fixed in `v4.1.0`

Hi @Raisolution 

I can still see this issue. I deleted the packages manually and reinstalled using command "npm i @progress/kendo-angular-editor" but everytime it downloads 0.4.0 and throw the same error. 

Please guide me regarding this.

**Comment by avinash13jun** [comment]
Hi @Raisolution 

There was some issue I guess. I tried after system restart and it worked. Thanks for the fix. :)
