### ISSUE TITLE
Loading state for Kendo Grid is undefined

### ISSUE THREAD

**Issue by hutcj** [telerik/kendo-angular#2205]
**Describe the bug**
This affects the examples/projects/grid-jsdo project. 

In the template for app.component.ts, inside the <kendo-grid> definition, there is a [loading]="view?.pendingData" attribute set. Per the Kendo Grid documentation, [loading] must be set to true/false based upon the current state, since the data service/JSDO connects to the PASOE endpoint asynchronously. While set to true, the Grid displays a loading icon. Setting to false hides the loading icon. 

The problem is that the pendingData variable is undefined rather than true. Therefore, no loading icon is displayed while the user waits for the network call to complete.

**To Reproduce**

1. ng serve the grid-jsdo sub-project
2. No loading icon is displayed while the Grid populates.

**Expected behavior**

Loading icon should be displayed while Grid is waiting for the data to be returned.

**Browser**
 - OS: Windows 10 1803
 - Browser: Firefox 66.0.3

**Additional context**

Relevant files:
examples/projects/grid-jsdo/src/app/app.component.ts
examples/projects/grid-jsdo/src/app/data/data.service.ts

**Comment by dtopalov** [comment]
The issue is caused by binding the Grid **loading** option to the **view** as opposed to **dataService** pendingData property. We will update the example accordingly:

[loading]="dataService?.pendingData"
