### ISSUE TITLE
MultiSelect doesn't respect kendoMultiSelectSummaryTag parameter with reactive forms

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2207]
**Describe the bug**
MultiSelect is using [kendoMultiSelectSummaryTag]="1" and for the first time, it is displayed as expected. But if I hide it via *ngIf directive and then restore it again, the multiselect shows ALL the items in summary mode, not only values with index > 1.
If I click to multiselect and dropdown is shown, the summary tag is corrected.

**To Reproduce**
- multiselect has to use reactive forms
- kendoMultiSelectSummaryTag has parameter
Example: https://stackblitz.com/edit/angular-7fkuev
- click twice on button "Toggle visibility"

**Expected behavior**
The multiselect should show the summary items in correct way = always summarized by the parameter of kendoMultiSelectSummaryTag

**Screenshots**
expected result (ok for the first time):
![image](https://user-images.githubusercontent.com/39991506/56213530-7bb18500-605c-11e9-90d7-9d8e9ce31576.png)

when restored:
![image](https://user-images.githubusercontent.com/39991506/56213566-908e1880-605c-11e9-9fc5-6cc1ed13a0cf.png)

and then clicked on multiselect:
![image](https://user-images.githubusercontent.com/39991506/56213605-aa2f6000-605c-11e9-8e17-5748f7552095.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version 73.0.3683.103

**Comment by kunajs** [comment]
Hi, is there any progress with this bug?

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
Shipped with **v4.2.0**.
