### ISSUE TITLE
Filter reset during input composition

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2208]
When a keyboard that relies on character composition (e.g. Korean) is used to type in the Grid filter, some symbols are lost due to our internal logic related to the value accessor and the built-in filter delay.

As a workaround, the developer can set the filterDelay input to 0, or use the filter menu instead of the default filter row:

    <kendo-grid-column field="ProductName" title="Product Name">
           <ng-template kendoGridFilterCellTemplate let-filter let-column="column">
             <kendo-grid-string-filter-cell [column]="column" [filterDelay]="0" [filter]="filter">
             </kendo-grid-string-filter-cell>
           </ng-template>
     </kendo-grid-column>

We can handle [compositionstart and compositionend](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event) events for a more granular control in such scenarios.

**Comment by tsvetomir** [comment]
Fixed in v3.14.2
