### ISSUE TITLE
Bind object with category of kendo-chart

### ISSUE THREAD

**Issue by poddarkhushbu07** [telerik/kendo-angular#2209]
For kendo chart, when I bind object value with 'categoryField' , chart is not rendered properly

Here I have demonstrated this with bar chart:
[https://stackblitz.com/edit/angular-oykufy](https://stackblitz.com/edit/angular-oykufy)

Key binded to categoryField stores the object value. Why category does get bind to object value?
Or is there any other way to handle this?

**Comment by danielkaradachki** [comment]
You should set the categoryField to a field that holds the category value:
https://stackblitz.com/edit/angular-oykufy-qeeknu?file=app/app.component.ts

**Comment by poddarkhushbu07** [comment]
@danielkaradachki I want to access whole object instead of a string. So I binded object with categoryField

Check this: https://stackblitz.com/edit/angular-oykufy

**Comment by danielkaradachki** [comment]
You can get the object from the dataItem:
https://stackblitz.com/edit/angular-oykufy-eqrpii?file=app/app.component.ts

Note that the repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) if you have any further question.
