### ISSUE TITLE
Charts module size.

### ISSUE THREAD

**Issue by dzmitrypaulouski** [telerik/kendo-angular#221]
Hello,

We are using some Kendo for Angular 2 components in our solution and now we need to use Kendo Charts. But its size is about 3.5 MB so it's increasing our bundle size twice.

Is there any way to import only necessary charts? Do you plan to decrease the size of module or split it to several modules?
Does AOT compilation helps to decrease the size of this package?

**Comment by tsvetomir** [comment]
The size you get for the non-minified files, 3.5MB is close to what I get.

Minifying with the Closure Compiler brings the Chart contribution down to around 800kB.
This is roughly the same as the size of empty ng-cli project (850kB).

**Comment by dzmitrypaulouski** [comment]
@tsvetomir thank you. It helped us.
