### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError on making kendo-dialog-titlebar conditional with an *ngIf

### ISSUE THREAD

**Issue by rvrn22** [telerik/kendo-angular#2210]
**Describe the bug**
Adding an *ngIf to kendo-dialog-titlebar throws ExpressionChangedAfterItHasBeenCheckedError.

**To Reproduce**
Look into console at 
https://angular-csxvkm.stackblitz.io

**Expected behavior**
No errors.

**Browser**
 - OS: [Windows, Mac]
 - Browser [Chrome]
 - Version [3.11.0]

**Additional context**

**Comment by dtopalov** [comment]
Fixed in v3.12.0
