### ISSUE TITLE
[Grid] Improve the master-detail functionality

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2212]
Currently the master-detail functionality does not allow the developer to control the expanded state of the Grid rows in a straight-forward and consistent manner.

For example expanding a row, and sorting, paging or filtering the data leads to very unexpected results due to the fact that the expand/collapse functionality relies on the row index only.

A sample approach to greatly improve the current functionality is to introduce an "expanded" callback/directive similar to the one in the TreeView component, or to how the Grid selection functionality is implemented - the expanded state of the rows can rely on a boolean, returned by the callback, or a collection of "expandedKeys".

**Comment by dtopalov** [comment]
Also requested in:

private support thread 1407763;

https://feedback.telerik.com/kendo-angular-ui/1397988-expose-isrowexpanded-collapsed-methods

https://feedback.telerik.com/kendo-angular-ui/1360761-kendo-grid-details

**Comment by elena-gancheva** [comment]
The feature is available in the latest [`dev`](https://github.com/telerik/kendo-angular-grid/releases/tag/v4.7.0-dev.202003101536) version of the package. Please, check out the examples and the documentation [here](https://www.telerik.com/kendo-angular-ui-develop/components/grid/master-detail/expanded-state/).

**Comment by Raisolution** [comment]
Available in `v4.7.0`
