### ISSUE TITLE
Editor roadmap

### ISSUE THREAD

**Issue by ZbigniewKrzystanek** [telerik/kendo-angular#2213]
Hi, 
we are building our app based on this component, but we need to know when or if, will be provided functionalities such as:
a) direct converting headers (workaroud: going thru paragraph) into an ordered/bulletpoint list
b) converting an ordered/bulletpoint list to a paragraph/header
c) introduce a different style for bulletpoint list(e.g. dots and triangles) or possible indentation for them 

Thank you in advance.

**Comment by Raisolution** [comment]
Hi @ZbigniewKrzystanek,

Indeed at the moment conversion from/to ordered/unordered lists is problematic, so I have extracted those scenarios and logged them in a separate issue, that could be followed at #2214.

Regarding the different styles for a bullet point list, providing those is not in our immediate plans, so I would suggest to log an item in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui) so we could measure the demand for this enhancement and plan it accordingly.
