### ISSUE TITLE
Dropdown list null empty default item

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#2215]
**Describe the bug**
For a `Non ValuePrimitive` dropdown, there should be an ability for a null/empty option.

**To Reproduce**

https://stackblitz.com/edit/angular-5dgefs

Stackblitz has a form against it, with the form status to false
If we change the value to small, and then back to the empty option, the form status goes from  false -> true -> true

**Expected behavior**

It should go to false -> true -> false.
I believe this is happening because the empty option isn't actually empty!

**Comment by cheng93** [comment]
https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/forms/#toc-reactive-forms

Would be nice if we could use the built in required validator though

**Comment by ipeshev** [comment]
Consider following example https://stackblitz.com/edit/angular-5dgefs-w5mtdo?file=app/app.component.ts,
if open/close some of dropdownlist it will invalidate the form, but after choosing an item then choosing defaultItem it will not invalidate template nor reactive form.

**Comment by michaelmarcuccio** [comment]
Is this still being considered? It has been almost 3  years and seems like a pretty annoying bug for most users.

**Comment by stnikolova** [comment]
In a non-primitive dropdown for the value to be evaluated as either valid or invalid, it **must** be an Object. The required built-in validator does not support object validation. If a `defaultItem` is set, the developer needs to implement the required custom validation, as demonstrated in the example.

**Comment by cheng93** [comment]
https://stackblitz.com/edit/stackblitz-starters-ruydss?file=src%2Fmain.ts

@stnikolova 

>The required built-in validator does not support object validation

I don't believe this is true as given in the above demo

**Comment by yanmariomenev** [comment]
Hi @cheng93,

The following feature request item was opened on this matter - https://feedback.telerik.com/kendo-angular-ui/1616815-modify-defaultitem-to-allow-acceptance-of-null-values-and-display-them-as-empty-options-when-valueprimitive-is-set-to-false

Feel free to add a vote on your behalf and add any missing information.
