### ISSUE TITLE
Timepicker integration with datepicker

### ISSUE THREAD

**Issue by ansydor** [telerik/kendo-angular#2216]
Hello,
there is no support to integrate `kendo-datepicker` & `kendo-timepicker` for inline or to share `kendo-dateinput`

```
<kendo-datepicker [format]="'dd/MM/yyyy HH:mm'"  [(ngModel)]="model.date">
</kendo-datepicker>
<kendo-timepicker [(ngModel)]="model.date"  formatPlaceholder="short" [format]="'HH:mm'"> </kendo-timepicker>
```

What i would expect is 
![Date-Time](https://d585tldpucybw.cloudfront.net/sfimages/default-source/productsimages/kendo-ui-web/featuredetails/datetimepicker-overview.png)

but what i get is 
![Date & Time](https://image.prntscr.com/image/BNhCO98rSvqatCyzNfMJig.png)

**Comment by tsvetomir** [comment]
This is covered by the future DateTimePicker component. It is tentatively scheduled for our next release cycle (May - September).

Please, cast your vote for [the DateTimePicker component](https://feedback.telerik.com/kendo-angular-ui/1360679-datetimepicker-component) on our Feedback portal. This will help us gauge the overall interest and prioritize.
