### ISSUE TITLE
Show Disabled Months in Calendar

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2218]
We want to show data for last 3 months active in a total of 12 months (1 Year). of which 9 months should be disabled. with the help of min and max its correct, I am able to show data for active 3 months but for disabled months what can be done to show them disabled. If it's available to show disabled months of before and after a certain period it will be good. Thanks.

**Comment by ipeshev** [comment]
The repository is for bug reports only. For feature requests please use our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui).

**Comment by ipeshev** [comment]
We have [such request](https://feedback.telerik.com/kendo-angular-ui/1360666-disable-certain-days-of-the-week-in-the-angular-2-datepicker-e-g-i-want-to-say-disable-every-weekend-day) already you can support it by voting.
