### ISSUE TITLE
Button text disappears when disabled in panel

### ISSUE THREAD

**Issue by mikef907** [telerik/kendo-angular#2220]
## I'm submitting a...

* Bug report 

## Current behavior

Button text inconstantly showing up in panel bar when button is disabled using bootstrap theme

## Expected behavior

Button text should always remain visible when panel is expanded

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-nf3gjt

## Environment

Browser:

- Chrome (desktop) version Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by ipeshev** [comment]
@mikef907 can't reproduce it on our side, are there some other conditions ? Please provide snapshot if possible.

**Comment by ipeshev** [comment]
We managed to reproduce it , will look at it.

**Comment by tsvetomir** [comment]
Fixed in v3.3.1
