### ISSUE TITLE
Treeview checked and disabled items display weird behavior in Microsoft Edge

### ISSUE THREAD

**Issue by AsifulNobel** [telerik/kendo-angular#2221]
## I'm submitting a...

* Bug report

## Current behavior

Disabled items with checkboxes enabled are not rendered properly in Microsoft Edge browser. But it is rendering properly in Chrome and IE 11. This issue also does not seem to occur when developer tools pane is opened in Microsoft Edge.

In Edge:
![image](https://user-images.githubusercontent.com/7826129/56467140-cb1cfa00-643c-11e9-9fc9-85a72fd5b6eb.png)

In Chrome & IE 11:
![image](https://user-images.githubusercontent.com/7826129/56467147-f7d11180-643c-11e9-9d38-dc2730890e7d.png)

## Expected behavior

Disabled Treeview items with checkboxes should be rendered same as Chrome in Edge browser.

## Minimal reproduction of the problem with instructions

[https://stackblitz.com/edit/angular-hwjrrd](https://stackblitz.com/edit/angular-hwjrrd)

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 73.0.3683.103
- IE version 11.0.14393.0
- Edge version 38.14393.0.0

**Comment by ipeshev** [comment]
With IE 11.1029. and Edge  41.16299.1004.0 is fine
![Screenshot from 2019-04-22 09-55-25](https://user-images.githubusercontent.com/4143177/56487753-f5c28d80-64e4-11e9-82e8-6e42a049e80f.png)

**Comment by ipeshev** [comment]
@AsifulNobel  are there some other conditions to reproduce it ?

**Comment by AsifulNobel** [comment]
@ipeshev It works fine in IE 11. The issue is actually only in Edge. Here is another stackblitz [demo link](https://stackblitz.com/edit/angular-hwjrrd-wbuhmb). Try to expand and collapse the items a few times, you will notice the rendering issue.

I checked it in Edge v41.16299.15.0 as well, the issue persists.

**Comment by ipeshev** [comment]
We managed to reproduce it , will look at it.

**Comment by tapopov** [comment]
The issue is not reproducible in Microsoft Edge Version 86.0.622.58 (Official build) (64-bit)
