### ISSUE TITLE
Unnecessary class updates in DropDowns

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2222]
**Describe the bug**
Some of the element classes are updated on each change detection cycle.

Seems to be caused by https://github.com/angular/angular/issues/25518
Reported in ticket 1406079.

**To Reproduce**
1. Navigate to https://stackblitz.com/edit/angular-bx88tm in Chrome
1. Open any of the drop-downs
1. Inspect the drop-down list
1. Notice how the `k-list-scroller` class is changed on each change detection cycle

**Expected behavior**
The class should not be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/247917/56558112-38986a00-65a6-11e9-92c9-3a72df4882e2.png)

**Browser**
 - OSX 10.14
 - Chrome 73

**Comment by shaharvaldman** [comment]
hi,

I am attaching another DOM image.

![image](https://user-images.githubusercontent.com/14073751/56860450-4f243400-699f-11e9-8a60-5e5d3ff77092.png)

**Comment by tsvetomir** [comment]
@shaharvaldman the `k-dropdown-wrap` element will toggle between `k-state-default` and `k-state-focused`. I don't see unexpected changes to the element class.

**Comment by tsvetomir** [comment]
@shaharvaldman my mistake, I was looking at the DropDownList. The problem with the ComboBox is confirmed.

**Comment by danielkaradachki** [comment]
The latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version should fix this as well.

**Comment by tsvetomir** [comment]
Fixed in v3.5.4
