### ISSUE TITLE
[kendoGridGroupBinding] with virtual scrolling does not load all records

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2224]
**Describe the bug**
When using [kendoGridGroupBinding] with virtual scrolling and initially scroll to the bottom, not all records are loaded. We need to scroll back to the top and then to the bottom so that all records are loaded in the Grid.

**To Reproduce**
[https://stackblitz.com/edit/angular-xaxm9f-ddyrnm?file=app/app.component.ts](https://stackblitz.com/edit/angular-xaxm9f-ddyrnm?file=app/app.component.ts)

1. Scroll to the bottom. (we reach item with ProductID: 20)
2. Scroll to the top.
3. Scroll to the bottom (we reach item with ProductID: 28)

**Comment by ciiara** [comment]
The issue is no longer reproducible with the current latest version of the Grid `5.4.0`
https://stackblitz.com/edit/angular-jcssrj?file=app/app.component.ts
