### ISSUE TITLE
Reorder column with kendo-grid-column-group will stick column to wrong column group

### ISSUE THREAD

**Issue by neochikoo** [telerik/kendo-angular#2225]
## I'm submitting a ...

* Bug report 

## Current behavior

https://stackblitz.com/edit/angular-blkm3r

In the demo, there are two column groups defined.
1. Reorder the column in each group. e.g. "Unit in stock", "unit price" and "unit not in stock", "unit not price"
2. Reorder the column group (i.e. move "not Availability" before "Availability"

Current result: the columns which belong to group "Availability" will be nested under "not Availability" and vice versa.

## Expected behavior

Expect that the column under each group will follow the grouping even if column groups reordered.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version  73.0.3683.103 (Official Build) (64-bit)
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: 3.3.4000
- Node version: v10.15.3
- Platform:  Windows 10

**Comment by neochikoo** [comment]
Any workaround or quick fix?

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
