### ISSUE TITLE
kendo-grid-date-filter-menu Custom Date Picker

### ISSUE THREAD

**Issue by Sujoy-Banerjee** [telerik/kendo-angular#2226]
Is it possible to have a custom date-picker component in `kendo-grid-date-filter-menu`  ? 
currently it's using `<kendo-datepicker>`  , is it possible to use another component in place of `<kendo-datepicker>`

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
