### ISSUE TITLE
Whitespaces are trimmed at the end of a text in FF

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2227]
**Describe the bug**
Whitespaces are trimmed when are typed at the end of an existing text. If a character (at the end) is deleted then whitespaces are shown correctly.

**To Reproduce**
[https://stackblitz.com/edit/angular-stbmhg?file=app/app.component.ts](https://stackblitz.com/edit/angular-stbmhg?file=app/app.component.ts)

Steps in which the bug appears:
1. Try to add new whitespaces at the end of an existing text;
2. Delete a character at the end of an existing text and try to add whitespaces; 
3. Try to add new whitespaces in a new line;
4. Try to add whitespaces at the end of a character in a new line;
5. Delete a character at the end in a new line;

**Browser**
 - FireFox [latest]

**Comment by valchev** [comment]
Related to telerik/kendo-react#270

**Comment by PeterStaev** [comment]
Getting the same behavior here, basically in FF the widget is unusable since the user cant add any spaces - they are trimmed resulting into one long word 😞 When can we expect a fix for this?

**Comment by PetarMetodiev** [comment]
The issue has been fixed in the latest version of kendo-themes:
@progress/kendo-theme-bootstrap@4.5.0
@progress/kendo-theme-default@4.7.0
@progress/kendo-theme-material@3.5.0

**Comment by mbechev** [comment]
The fix is not applied when the **iframe** option is set to true.

**Comment by Aayush9507** [comment]
> The issue has been fixed in the latest version of kendo-themes:
> @progress/kendo-theme-bootstrap@4.5.0
> @progress/kendo-theme-default@4.7.0
> @progress/kendo-theme-material@3.5.0

We are using @progress/kendo-theme-default@4.7.0, but still, the whitespace is getting trimmed in firefox.
