### ISSUE TITLE
Grid: Button-Click in Header triggers sort

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular#223]
When adding a button to the header via `kendoGridHeaderTemplate`, the click on the button also triggers the `sortChange`/`dataStateChange` event.
I've also tried to disable the event via `preventDefault()` but that did not work either.

### Expected behavior
Do not trigger the `sort` event, when the `target` is not the header.

### Plunker
http://plnkr.co/edit/YeCLUUscECIIUxBIBXrh?p=preview

### Version
`@progress/kendo-angular-grid: 0.13.2`

**Comment by rusev** [comment]
Indeed it is how Angular handle events. You should use `event.stopPropagation()` instead.

Here is updated example - http://plnkr.co/edit/gnUIZq43fx0bBAjOEyTJ?p=preview

**Comment by P-H-F** [comment]
Thanks!
