### ISSUE TITLE
How to localize page of kendo-angular-grid?

### ISSUE THREAD

**Issue by zhengyanghuaer** [telerik/kendo-angular#2231]
![image](https://user-images.githubusercontent.com/35128870/56721882-6af9c100-6778-11e9-8e38-7aae99d7d7f3.png)

**Comment by tsvetomir** [comment]
@zhengyanghuaer this repository is for bug reports only. Please, review the [Localization help topic](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/) open a [support ticket](https://admin.telerik.com/support/my-threads) if you need assistance with your project.
