### ISSUE TITLE
The content property of NotificationRef is not of type ComponentRef

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2232]
**Describe the bug**
The [content](https://www.telerik.com/kendo-angular-ui/components/notification/api/NotificationRef/) property of NotificationRef is of type object, while it should be of type ComponentRef.

**To Reproduce**
[https://stackblitz.com/edit/angular-j1zisg?file=app/app.component.ts](https://stackblitz.com/edit/angular-j1zisg?file=app/app.component.ts)

**Comment by rolandschuster** [comment]
I can confirm this problem.

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-notification v2.0.1`
