### ISSUE TITLE
Notice: Dropping support for Angular 4 and 5, RxJS 5.x

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2234]
In May 2019 we will ship major versions of all packages with the following breaking changes:
* Peer dependency for Angular will be updated to 6.x - 8.x
* Installing `rxjs-compat` will be no longer required.
* Minor component-specific breaking changes - TBD

We strongly recommend upgrading to Angular 7](https://update.angular.io/) which will be supported until Apr 18, 2020.

### Rationale

The goal for this update is to remove the need to use `rxjs-compat`.

The timing is in line with the [Angular Support Policy](https://angular.io/guide/releases#support-policy):
* Angular 4.x support has expired in September 23, 2018
* Angular 5.x long-term support expires on May 1, 2019

### Package Versions

* The major version of all packages will be incremented to indicate a breaking change.
* Projects depending on current versions of the packages will not be affected.

### Compatibility Tags

* The current versions of all packages will be tagged with `ng4` and `ng5` tags.
* The tags will always point to the latest patch release, compatible with the specified Angular version.
* Use the tags when adding packages to existing projects:

  `ng add @progress/kendo-angular-grid@ng5`

### Questions

Q: Will this change affect my existing project?
A: No, as long as you're referencing a particular major version in `package.json`, e.g. `"@progress/kendo-angular-grid": "^3.14.0"`

Q: Will you ship updates to applications using Angular 4.x or 5.x?
A: Only critical bug-fixes will be back-ported.

Q: What should I do to stay up-to-date?
A: Subscribe to this thread for notifications.

Ref https://github.com/telerik/kendo-angular/issues/1568

**Comment by massic80** [comment]
I just installed brand-new version 5.0.0 and I still got rxjs-compat: when is it planned to be dropped?

**Comment by tsvetomir** [comment]
The version bump in `@progress/kendo-angular-inputs` was due to the addition of new peer dependencies required by the new ColorPicker component, [see changelog](https://www.telerik.com/kendo-angular-ui-develop/components/inputs/changelog/#toc-breaking-changes).

We're still working on the removal of rxjs-compat and will follow-up in this thread.

**Comment by appeality** [comment]
Any eta on when rxjs-compat dependency will be removed? Thanks.

**Comment by tsvetomir** [comment]
This took a bit longer than expected, but we're on track for an official release next week.

The [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of all components are already updated and do not require rxjs-compat. You can give them a try by using "dev" as a version in `package.json`, for example:
```json
"dependencies": {
    "@progress/kendo-angular-buttons": "dev",
    "@progress/kendo-angular-dateinputs": "dev",
    "@progress/kendo-angular-dropdowns": "dev",
    "@progress/kendo-angular-excel-export": "dev",
    "@progress/kendo-angular-grid": "dev",
    "@progress/kendo-angular-inputs": "dev",
    "@progress/kendo-angular-intl": "dev",
    "@progress/kendo-angular-l10n": "dev",
    "@progress/kendo-angular-popup": "dev",
    "@progress/kendo-data-query": "dev",
    "@progress/kendo-drawing": "dev",
    ...
}
```

We're now moving on to some housekeeping tasks and validating the applied changes.

**Comment by tsvetomir** [comment]
The update is now released in the official channel, enjoy!

* Adding new components using `ng add` will no longer install `rxjs-compat`.
* Review the update instructions for existing projects in [Release History](https://www.telerik.com/kendo-angular-ui/release-history/#toc-rxjs-6x-update).
