### ISSUE TITLE
Editor bug - html5 video tag 

### ISSUE THREAD

**Issue by arthurtu6153** [telerik/kendo-angular#2237]
**Describe the bug**
The Editor is not able to keep "video" tag when I input the "video" element upon kendoEditorViewSourceButton dialog and click update button.
the whole video html is gone.

please let me save that tag.

**Comment by valchev** [comment]
Hi @arthurtu6153,

currently, the Editor does not support parsing and rendering of `video` tag. I will label this issue as an `enhancement` and it will get into the list of enhancements for the official release.

**Comment by siyka-marinova** [comment]
Fix is available in the [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official package `kendo-angular-editor v0.10.3`
