### ISSUE TITLE
Notifications not hiding if closable

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#2238]
**Describe the bug**

If closable is set, hideAfter setting will be ignored and notifications will never hide. (until manually closed)

        this._showNotification({
            closable: true,
            hideAfter: 5000,
            content: 'my message'
        });

**To Reproduce**
https://angular-w5ffsr.stackblitz.io, https://stackblitz.com/edit/angular-w5ffsr?file=app/app.component.ts

**Expected behavior**
if `hideAfter` is set notification should hide after specified time.

**Browser**
Tested in Edge

**Comment by danielkaradachki** [comment]
The behavior is described in the [documentation](https://www.telerik.com/kendo-angular-ui/components/notification/hiding-notifications/#toc-defining-a-delay-before-hiding). hideAfter is ignored if closable is true and the notifications.

**Comment by cluetjen** [comment]
Oh, I see - sorry. Thanks.

**Comment by pk-techie** [comment]
> The behavior is described in the [documentation](https://www.telerik.com/kendo-angular-ui/components/notification/hiding-notifications/#toc-defining-a-delay-before-hiding). hideAfter is ignored if closable is true and the notification is hidden only on the close button click.

Is it implemented now? if we observe your comment it was from 2019, i think this must be implemented now, but i am not able find it. could you plz help me here...
