### ISSUE TITLE
Grid Pageinfo configuration

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#224]
Is there a way to set configuration for the info-text's in the Grid?

For example:
`<kendo-grid
     [data]=".."
     [pageable]="{
        buttonCount: 5,
        info: true,
        type: 'input',
        previousNext: true,
        siteInfoText: ['Seite', 'von'],
        countInfoText: ['von', 'Einträge']
    }"`
 

I want to replace 'Site 1 of 10' with 'Seite 1 von 10' at site input and '27 of 130 item' with '27 von 130 Einträge' at count information.

**Comment by rusev** [comment]
No, currently there isn't option for changing the text in the pager. It something that should be possible in the feature versions.
