### ISSUE TITLE
[Scheduler] Month view not rendered when scheduler is content projected into another component that is not initially visible

### ISSUE THREAD

**Issue by dhilgarth** [telerik/kendo-angular#2240]
**Describe the bug**
The grid with the days in the month view is not rendered when the Scheduler component is content projected into another component that is not initially visible.

**To Reproduce**
https://stackblitz.com/edit/angular-hoynfz?file=src%2Fapp%2Fapp.component.ts
Click on "Show scheduler": Scheduler will show but not render the days grid.

**Expected behavior**
The days are always displayed.

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 73.0.3683.103

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-scheduler`.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-scheduler v.1.2.0`
