### ISSUE TITLE
Kendo Chat not displaying messages after introducing a long message in IE11

### ISSUE THREAD

**Issue by AnitaMihai** [telerik/kendo-angular#2242]
**Describe the bug**
After introducing a long message into the kendo chat component , the messages are not longer displayed.

**To Reproduce**

1. Using the demo code from the official documentation page for the chat component:
https://www.telerik.com/kendo-angular-ui/components/conversationalui/
open it into IE11
2.  Write something into the input message box: for example "Hi"
![image](https://user-images.githubusercontent.com/24227300/57076910-5d51b780-6cf3-11e9-8110-18bd2bc05488.png)

3. Write a bigger text into the input message box: for example  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
![image](https://user-images.githubusercontent.com/24227300/57076948-778b9580-6cf3-11e9-81e8-98d2186a5484.png)

**Expected behavior**
All the messages from the conversation should display like it is behaving into Chrome. See screenshot:
![image](https://user-images.githubusercontent.com/24227300/57077183-0bf5f800-6cf4-11e9-93ff-475e6dad18a7.png)

**Browser**

 - Browser: Internet Explorer 
 - Version: 11

**Comment by tsvetomir** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v2.0.0
