### ISSUE TITLE
[Column Menu] options does not toggle in IE11

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2243]
**Describe the bug**
Column Menu options ('Filter' and 'Columns') does not toggle in IE11. Sorting functionality behaves as expected.

**To Reproduce**
[https://stackblitz.com/edit/angular-bs6wpk?file=app%2Fapp.module.ts](https://stackblitz.com/edit/angular-bs6wpk?file=app%2Fapp.module.ts)

**Browser**
 - Browser [IE]
 - Version [11]

**Additional context**
Everything works properly if _@angular/animations_ version is 7.2.7 (or below). 
Angular Change Log for v7.2.8 - [https://github.com/angular/angular/blob/master/CHANGELOG.md#728-2019-03-06](https://github.com/angular/angular/blob/master/CHANGELOG.md#728-2019-03-06)

**Comment by danielkaradachki** [comment]
Should be fixed in 4.1.1

https://stackblitz.com/edit/angular-5mwgv7?file=app/app.component.ts
