### ISSUE TITLE
AutoComplete: add option to configure whether the first match should be focused

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#2244]
Currently, when the user types in the AutoComplete, the first match is focused. When filtering is enabled, the first item on the list is focused. This behavior cannot be configured.

It would be a nice enhancement to allow this behavior to be configured - i.e. whether automatic focus should occur. Similar to the AutoComplete's [`highlightFirst`](https://docs.telerik.com/kendo-ui/api/javascript/ui/autocomplete/configuration/highlightfirst) in the jQuery counterpart.

**Comment by dimitar-pechev** [comment]
The `highlightFirst` input property is added in the latest dev version of the `@progress/kendo-angular-dropdowns` package (**v4.0.0-dev.201906111118**). When set to false, the first match on the list during user input won't be automatically focused.

```html
<kendo-autocomplete
    [highlightFirst]="false"
>
</kendo-autocomplete>
```

**Comment by ipeshev** [comment]
Will try do add some automatic tests before closing, this issue.

**Comment by dimitar-pechev** [comment]
Shipped with `@progress/kendo-angular-dropdowns@4.0.0`. [Docs article](https://www.telerik.com/kendo-angular-ui/components/dropdowns/autocomplete/suggestions/#toc-avoiding-the-focus-on-the-first-available-match).
