### ISSUE TITLE
Multiselect with hidden searchbar and autoClose=false not closing when clicked outside dropdown

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2245]
**Describe the bug**
I am using a multiselect with its searchbar hidden (by css), because it causes some unnecessary wrapping if the width is too small.
Here is discussion about it: https://www.telerik.com/forums/remove-typing-box-from-multiselect-component
Unfortunately it is not working properly when the multiselect has autoClose="false". If I click somewhere outside dropdown, it keeps opened.
The only way how to close the dropdown is to click the multiselect input.

**To Reproduce**
https://stackblitz.com/edit/angular-kufjvb
1) click the multiselect and select required items
2) click outside the multiselect and its dropdown
3) the dropdown is still open.

**Expected behavior**
I would expect that click outside the dropdown makes it close.

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.131

**Comment by ipeshev** [comment]
@kunajs KendoMultiSelect is not meant to work this way, but you can try [following workaround](https://stackblitz.com/edit/angular-kufjvb-y8jeqn?file=app/app.component.ts). Instead of using display:none just set width and height of input to 0, which may cause other undesired effects.

**Comment by kunajs** [comment]
ok, thanks, this seems to be working. But question: what is the purpose of the search bar? I think this should be visible only for filter functionality or custom value. But if allowCustom="false" and filterable="false", searchbar makes no sense to me.

**Comment by ipeshev** [comment]
In the case of multiselect it suggest you value for choosing ( by focusing it ).
