### ISSUE TITLE
Uncaught Error: Template parse errors when added kendo-angular-scheduler into app.module

### ISSUE THREAD

**Issue by vahidsamimi** [telerik/kendo-angular#2246]
Hi guys,

I've added kendo-angular-scheduler into my angular app with this command:

`ng add @progress/kendo-angular-scheduler`
After compiling code, I get the following error message in chrome console:

> `Uncaught Error: Template parse errors:
> Can't bind to 'toggleable' since it isn't a known property of 'button'. (" day of weekDays' kendoButton
>                         [style.width.px]="75"
>                         [ERROR ->][toggleable]="true"
>                         [selected]="isSelected(day)"
>                         (sel"): ng:///SchedulerModule/RecurrenceWeekdayRuleEditorComponent.html@8:24
>     at syntaxError (compiler.js:215)`

How can I fix this issue?
Thx

**Comment by ipeshev** [comment]
@vahidsamimi could you give us a bit more code, probably something is not imported properly

**Comment by vahidsamimi** [comment]
Here is my app.module.ts
but I have two other modules(dashboard.module and hub-administration-tool.module.

`/*angular modules*/
import { BrowserModule } from '@angular/platform-browser';
import { LOCALE_ID, NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms'
import { JwtHelperService } from '@auth0/angular-jwt';

/*custom modules*/
import { HubAdministrationToolModule } from './modules/hub-administration-tool/hub-administration-tool.module';
import { DashboardModule } from './modules/dashboard/dashboard.module';

/* custom routing modules*/
import { AppRoutingModule } from './app.routing.module';


/* library modules*/
import { GridModule } from '@progress/kendo-angular-grid';
import { DateInputsModule } from '@progress/kendo-angular-dateinputs';
import { UploadModule } from '@progress/kendo-angular-upload';
import { PopupModule } from '@progress/kendo-angular-popup';
import { SchedulerModule } from '@progress/kendo-angular-scheduler';



/*custom components*/
import { AppComponent } from './app.component';

/* Services */
//import { JWTService } from './authentication/jwt.service';
import { UtilsService } from './services/utils.service';

/* Custom Classes*/
import { ChartsModule } from '@progress/kendo-angular-charts';
import { IntlModule } from '@progress/kendo-angular-intl';


import '@progress/kendo-angular-intl/locales/de/all';
import { LoginComponent } from './login/login.component';
import {AuthenticationService} from './services/authentication.service'
import { AuthService } from './authentication/auth.service';
import { HomeComponent } from './home/home.component';

import { AuthGuardService } from './authentication/auth-guard.service';


@NgModule({
  declarations: [
    AppComponent, AccessDeniedComponent, BadRouteComponent, RedirectComponent, LoginComponent, HomeComponent
  ],
  imports: [
    /*jwtConfig,*/
    BrowserModule,
    FormsModule,
    HubAdministrationToolModule,
    DashboardModule,
    HttpClientModule,
    AppRoutingModule,
    GridModule,
    BrowserAnimationsModule,
    DateInputsModule,
    UploadModule,
    PopupModule,
    ChartsModule,
    IntlModule,
    SchedulerModule,


  ],
  providers: [{ provide: LOCALE_ID, useValue: 'de-DE' }, /*JWTService,*/ 
    UtilsService,
    AuthenticationService,
    AuthService,
    JwtHelperService, 
    AuthGuardService],
    bootstrap: [AppComponent]
})
export class AppModule { }`

**Comment by ipeshev** [comment]
Ok, thank you we will investigate it further.

**Comment by ipeshev** [comment]
@vahidsamimi could you try to update @progress/kendo-angular-buttons package ?

**Comment by vahidsamimi** [comment]
yeah!!!! it works! Many Thanks! I run this command in cmd : 
`npm i @progress/kendo-angular-buttons`
