### ISSUE TITLE
PopupSettings for Dropdowns not respecting width: auto

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2247]
**Describe the bug**
In the [documentation](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/PopupSettings/#toc-width) there is written: If set to **auto**, the component automatically adjusts the width of the popup, so that the item labels are not wrapped.
But this is not true - long items are wrapped, because the kendo-popup element has the width of the dropdown component set:
![image](https://user-images.githubusercontent.com/39991506/57228418-0eb65d00-7014-11e9-86f6-12e29bed1f37.png)

**To Reproduce**
https://stackblitz.com/edit/angular-ejzejw
1) open some of the dropdown
2) you can see that some of the items are wrapped to more than 1 line

**Expected behavior**
The kendo-popup should not have width set and the popup should look like on 2nd screenshot.

**Screenshots**
current behavior:
![image](https://user-images.githubusercontent.com/39991506/57228258-a49db800-7013-11e9-86ff-ef034430b13b.png)

expected behavior:
![image](https://user-images.githubusercontent.com/39991506/57228188-7ddf8180-7013-11e9-896d-b234015ffa03.png)

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.131

**Comment by ipeshev** [comment]
@kunajs thank you for the bug report, we can reproduce it only for DroddownList !

**Comment by dimitar-pechev** [comment]
@kunajs, after reviewing the example again, we noticed that it's actually a problem with the configuration. The component sets the item width automatically when its value is set to `'auto'` (string). Setting it to `auto` when no property with the same name is defined is the same as setting it to `undefined`. The code would also probably fail to compile in production build by the way. 

Refer to this working [example](https://stackblitz.com/edit/angular-ejzejw-vmrdj6).

If I'm missing something, don't hesitate to write back and we could reopen the issue if necessary.
