### ISSUE TITLE
Shared tooltip disappears on click

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2248]
**Describe the bug**
The Tooltip item of chart series disappears on click, in case of :
``` 
<kendo-chart-tooltip [shared]="true">
      </kendo-chart-tooltip>
```

**To Reproduce**
Try hover and click on [this samples's](https://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/tooltips/#toc-shared-tooltip) series.

**Expected behavior**
It should not hide series tooltip like in case of [shared]=false

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**
``` 
(seriesClick)="onSeriesClick($event)" 
... $event.originalEvent.preventDefault()
 ```
Doesn't work as a work around.

**Comment by danielkaradachki** [comment]
The behavior is by design. The shared tooltip is toggled on click.

**Comment by ipeshev** [comment]
Not sure why it should work different than shared=false from user perspective it should have same behavior on click , can we have some workaround that stops the click event in this case ?
