### ISSUE TITLE
Date disappears from datepicker

### ISSUE THREAD

**Issue by EleanorHughes** [telerik/kendo-angular#2249]
**Describe the bug**
I have a reactive form with a form control bound to the value of the kendo datepicker control. For some reason when this date is 2019-04-30 then this particular date disappears from the calendar inside the date picker control. The control seems to work correctly otherwise.

**To Reproduce**
Please see stackblitz:
https://stackblitz.com/edit/angular-mbcrze?file=app%2Fapp.component.ts

**Expected behavior**
This date should still be visible in the datepicker control

**Screenshots**
![image](https://user-images.githubusercontent.com/31129782/57313875-5f978580-70e8-11e9-815b-443fe9d8281b.png)

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version  73.0.3683.103

**Comment by DanielHTpg** [comment]
I was just browsing the issues and checked this one just now. The component renders correctly for me:
![image](https://user-images.githubusercontent.com/24475714/57319094-1cdfa880-70fc-11e9-9816-62869d5e7e49.png)
Navigating around also didn't cause the described issue.

Maybe this info helps.

Tested with the collowing Chrome versions:
72.0.3626.81
73.0.3683.86
74.0.3729.131

**Comment by EleanorHughes** [comment]
Thanks for the quick response - the date format was 2019-4-30 and it was working correctly. 
I've updated the stackblitz to 2019-04-30 and hopefully you should be able to see the issue now?

**Comment by danielkaradachki** [comment]
The fix was released in 3.7.4
