### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using NotificationService in ngOnInit or ngAfterViewInit

### ISSUE THREAD

**Issue by rolandschuster** [telerik/kendo-angular#2251]
**Describe the bug**
I get an ExpressionChangedAfterItHasBeenCheckedError when using the NotificationService with a TemplateRef as content inside a ngOnInit or ngAfterViewInit Hook.

**To Reproduce**
[https://stackblitz.com/edit/angular-rn7gsi?file=app/app.component.ts](https://stackblitz.com/edit/angular-rn7gsi?file=app/app.component.ts)

**Comment by elena-gancheva** [comment]
Hi @rolandschuster, thank you for submitting this. I have prepared an example with a temporary workaround of the problem:  https://stackblitz.com/edit/angular-rn7gsi-1l1nmd?file=app/app.component.ts

When the fix is available, we will update this issue.

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by dimitar-pechev** [comment]
Included in **v1.3.0**
