### ISSUE TITLE
[Scheduler] [MultiDayView] numberOfDays option does not update the view.

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2252]
**Describe the bug**
Setting the numberOfDays option of the kendo-scheduler-multi-day-view is not respected. The number of days in Multi-Day view is always 3.

**To Reproduce**
Observable in the online demos.

**Comment by dtopalov** [comment]
The fix is available in the [latest dev build (0.12.0-dev.201905141022)](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v0.12
