### ISSUE TITLE
create list of absences with kendo-schluder 

### ISSUE THREAD

**Issue by vahidsamimi** [telerik/kendo-angular#2253]
Hi, 

I want to create a list of absences with angular 6 and kendo-schduler.
here is my mock-up:
Personal view:
https://i.imgur.com/hV0Sa0w.png
Team view:
https://i.imgur.com/EnG4W8c.png

I would ask if it is possible with kendo scheduler to realize these mockups or not!

**Comment by tsvetomir** [comment]
@vahidsamimi this issue tracker is for bug reports only. Please, open a [support ticket](https://admin.telerik.com/support/my-threads) for assistance with implementing application scenarios.
