### ISSUE TITLE
[Scheduler] Agenda view height not recalculated when browsing dates

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2256]
**Describe the bug**
If the kendo-scheduler has no height set by css height property or is set to 100%, height of agenda view is not recalculated when browsing previous/next in agenda view. This causes 3 problems:
A) the height is unnecessarily big, so the white space below the items is present (if the height of displayed items is less than height of previously displayed items)
B) the vertical scrollbar is visible which is not required  (if the height of displayed items is greater than height of previously displayed items).
C) no items are visible (if the count of displayed items is greater than 0 and previously displayed items count was 0)
But if you switch to week view and then switch back to agenda view, height is recalculated fine.

**To Reproduce**
https://stackblitz.com/edit/angular-kdxjjl
problem A)
1) week 6/23/2019 - 6/29/2019 is selected
2) switch to agenda view (you can see a lot of items)
3) browse dates in agenda view by clicking on Previous/Next - the whitespace below items is useless, because height of scheduler keeps the same
4) switch to week view and then back to agenda view - items are displayed without whitespace

problem B)
1) select week 6/16/2019 - 6/22/2019 (previous week of selected default)
2) switch to agenda view (you can see few items)
3) browse dates in agenda view by clicking on Previous/Next - the scrollbars are visible if the items height is larger than before.
4) switch to week view and then back to agenda view - items are displayed without scrollbar

problem C)
1) select week 5/26/2019 - 6/1/2019
2) switch to agenda view (you can see no items)
3) browse dates in agenda view by clicking on Previous/Next - no items are visible even if they exist.
4) switch to week view and then back to agenda view - items are displayed properly

**Expected behavior**
The height should be recalculated, so no whitespace or scrollbars are visible.

**Screenshots**
problem A):
![image](https://user-images.githubusercontent.com/39991506/57436786-b6b06e00-7240-11e9-9f15-cf828130051c.png)

problem B):
![image](https://user-images.githubusercontent.com/39991506/57436843-db0c4a80-7240-11e9-998d-6fc6ccfee60e.png)

problem C):
![image](https://user-images.githubusercontent.com/39991506/57437800-d052b500-7242-11e9-8d19-9c98516649b9.png)

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.131

**Comment by ipeshev** [comment]
![Screenshot from 2019-05-27 12-51-21](https://user-images.githubusercontent.com/4143177/58412001-3ed6a600-807e-11e9-9525-00cd400a8333.png)

**Comment by ipeshev** [comment]
Still having some problem in case of no items.

**Comment by kunajs** [comment]
any progress?

**Comment by danielkaradachki** [comment]
Should be fixed in 0.14.0

https://stackblitz.com/edit/angular-wxt4hv?file=app/app.component.ts
