### ISSUE TITLE
[Grid] Filter menu does not open in FireFox when content is scrolled

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2257]
The Grid Filter Menu is not opening as expected when the Grid table is scrolled. The issue is observable in FireFox only, and only when the component where the Popup is attached to (typically the app root component) is not a block element:

https://stackblitz.com/edit/angular-vskmo1-9s8ajp?file=index.html

As a workaround, set the root element's display to `block`:

https://stackblitz.com/edit/angular-vskmo1-nnx5ju?file=index.html

**Comment by svetq** [comment]
seems related to https://github.com/angular/angular/pull/28911

**Comment by josefkoller** [comment]
try to set block-style at your root-component (that really worked for us) 

;)

**Comment by tsvetomir** [comment]
Fixed in v4.0.0
