### ISSUE TITLE
Callout is not positioned properly

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2258]
**Describe the bug**
The callout of the Tooltip is not aligned properly when positioned on the left of a target element that is placed inside a div with margin-left: auto.

**To Reproduce**
Check the following example:
[https://stackblitz.com/edit/angular-w9vatm-gzzecq?file=app/app.component.ts](https://stackblitz.com/edit/angular-w9vatm-gzzecq?file=app/app.component.ts)

**Comment by bartduisters** [comment]
The callout is also not properly aligned when positioned on the top with a specific width.
![image](https://user-images.githubusercontent.com/43420049/61060485-e58ec000-a3fa-11e9-85c1-08d572201a41.png)

**Comment by inikolova** [comment]
The issue cannot be reproduced anymore - tested with:
@progress/kendo-angular-tooltip: 3.0.0
@progress/kendo-theme-default: 4.32.0

https://stackblitz.com/edit/angular-rwz3sr-7ctada?file=app/app.component.ts
