### ISSUE TITLE
Selection disappears when any of the drop-down tools is focused

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular#2259]
**Describe the bug**
Text selection *visually* disappears while any of the drop-down tools is focused.

**To Reproduce**
1. Open the this demo: https://www.telerik.com/kendo-angular-ui/components/editor/tools/
2. Make a text selection with the mouse
3. Try to change the font size through the corresponding drop-down tool
4. Notice that as soon as the drop-down tool is active, the text selection disappears

The issue can be reproduced with any of the drop-down tools. The functionality of the tools is not affected. The selection is back as soon as the drop-down closes.

**Expected behavior**
The text selection should not disappear. In this way, the user will be able to see the text portion where the command will be applied.

**Comment by valchev** [comment]
Partially fixed with the introduction of the `iframe` mode.

Since v0.8.0 the behaviour can be observed only when `iframe` is set to `false`.

**Comment by dtopalov** [comment]
Fix is available in v.2.3.0 of the `@progress/kendo-angular-editor` package.
