### ISSUE TITLE
gsw-CH locale is missing

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2260]
**Describe the bug**
gsw-CH locale is missing from the kendo-angular-intl repository.

**Comment by tsvetomir** [comment]
The [gsw locale](http://www.unicode.org/cldr/charts/24/summary/gsw.html) is not included in the "core" CLDR dataset for some reason. We'll investigate if it's possible to ship it as part of the pre-built locales.

**Comment by tsvetomir** [comment]
The **gsw locale** is included in `@progress/kendo-angular-intl` v2.0.0
