### ISSUE TITLE
Provide a way to translate the "Today" message inside the DatePicker

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2262]
**Describe the bug**
Currently there is no way to translate the "Today" message located inside the DatePicker, that is in the header of the Scheduler component. There should be a property in the [kendo-scheduler-messages](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerCustomMessagesComponent/) component that allows to change the "Today" message.

**Comment by danielkaradachki** [comment]
Available as `calendarToday` in the latest dev version.

**Comment by danielkaradachki** [comment]
Released in 0.15.0

https://stackblitz.com/edit/angular-52a2uf?file=app/app.component.ts
