### ISSUE TITLE
[DropDownList] - Dropdown does not open on enter when focused

### ISSUE THREAD

**Issue by MelvilQ** [telerik/kendo-angular#2263]
**Describe the bug**
A focused DropDownList is not opened when the enter key is pressed.

**Expected behavior**
The dropdown opens on enter (like a normal HTML select element does).

**Browser**
All Browsers on Desktop

**Comment by ipeshev** [comment]
@MelvilQ according to [our docs](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/keyboard-navigation/) DropDownList should be opened when Alt+Arrow down is pressed , with Enter focused item is highlighted.

**Comment by tsvetomir** [comment]
@MelvilQ we're considering adding such shortcut to improve the compatibility with the native select element.

What has kept us from adding it is that it would not be consistent with the other drop-down components. They open automatically when typing and Enter is reserved for selecting the focused item. Do you find this difference in behavior concerning for your use cases?

**Comment by MelvilQ** [comment]
I agree that it makes totally sense to reserve the enter for selecting the currently selected item as long as there is one. A non-filterable DropDownList has no selected item when closed, so the enter key would be free for this functionality. Many of our users use the keyboard as much as they can and for them we would like to offer an experience which is as close to native select elements as possible.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
The new behavior is available in **v4.2.0**. The **DropDownList** can now also be opened with the enter key ([example](https://stackblitz.com/edit/angular-5y2pus)).
