### ISSUE TITLE
Dropdown virtualization?

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#2264]
**Describe the issue**
 A clear and concise description of the issue and a link to the affected page.

I found that you had released angular 2019 R2 which contains 'virtualization' of Drop Down components. But I did not find any changes in documents ??

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by jiangyh1024** [comment]
oh my god, i am wrong, it seems that angular r2 is not releasaed

**Comment by tapopov** [comment]
Hi @jiangyh1024 
The [What's new](https://www.telerik.com/blogs/whats-new-in-r2-2019-for-kendo-ui) blog post mentions that the virtualization will be introduced shortly after the R2 release. Once the feature is released we will update the following GitHub issue:
[Virtual scrolling support #2195](https://github.com/telerik/kendo-angular/issues/2195)
