### ISSUE TITLE
'@progress/kendo-data-query' process does not handle immutability

### ISSUE THREAD

**Issue by Zaixu** [telerik/kendo-angular#2266]
**Describe the bug**
The process function from the @progress/kendo-data-query package changes the grid state object, meaning if reusing same state model, gives problems with immutability

**To Reproduce**
Deep freeze the state object, try to reuse it from state.

Can be seen here:
https://stackblitz.com/edit/angular-ogrpas

**Expected behavior**
For it to process the data and not change the given state model.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Fixes released in kendo-angular-grid 4.2.0 and kendo-data-query 1.5.2

https://stackblitz.com/edit/angular-gr1mpw?file=app/app.component.ts
