### ISSUE TITLE
pdf viewer angular

### ISSUE THREAD

**Issue by jaqbwilk** [telerik/kendo-angular#2267]
**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**

**Comment by jaqbwilk** [comment]
please let us know if you plan pdf viewer for angular, i saw version for jquery

**Comment by tsvetomir** [comment]
A PDF viewer is not currently on the Kendo UI for Angular roadmap. Please, cast your vote for it on our feedback portal so we can gauge the overall interest and prioritize.
