### ISSUE TITLE
[ScrollView] The selected page moves off screen

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2268]
**Describe the bug**
When passing a lot of items to the ScrollView the selected page is not properly demonstrated in the pagination. When navigating to the right the selected page will eventually move off screen. 

**To Reproduce**
Check the following example:
https://stackblitz.com/edit/angular-jyvts9?file=app/app.component.ts

1. Click the right arrow multiple times to change the picture and notice how the selected page in the pagination will eventually go off screen.

**Comment by Raisolution** [comment]
Our general recommendation in scenarios with so many ScrollView items is to set the pageable option to `false` and to rely on navigation using the side arrows and/or swiping instead:

https://www.telerik.com/kendo-angular-ui/components/scrollview/arrows/

https://www.telerik.com/kendo-angular-ui/components/scrollview/api/ScrollViewComponent/#toc-pageable

As part of our future development plans, we are considering the introduction of adaptive pager, which will not display all pager dots, but only a fraction at a time.
