### ISSUE TITLE
[Grid] invalid index of reorderable column

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2269]
**Describe the bug**
When using a Grid where the first column is not reorderable and locked, but all other columns are reorderable, then if we try to reorder a column its new index get incorrect after some interaction.

**To Reproduce**
Check the following example:
https://stackblitz.com/edit/grid-reorder-sample-bjgbh5?file=app/app.component.ts

![drag](https://user-images.githubusercontent.com/20015190/57921486-214b5480-78a6-11e9-8cae-e56395a5c6bf.gif)

**Comment by danielkaradachki** [comment]
Released in 3.14.4
