### ISSUE TITLE
Locked column content is shifted down

### ISSUE THREAD

**Issue by eugene-sinitsyn** [telerik/kendo-angular#2270]
Locked column rows aren't aligned with the rest of the rows at the bottom of the grid.
![image](https://user-images.githubusercontent.com/23496057/57926383-c6b8f500-78b3-11e9-92c4-c4a5474fcab9.png)
Grid has locked column and is resizable.

**To Reproduce**
1. Open ["Locked Columns" demo with [resizable]="true" added](https://stackblitz.com/edit/angular-vydfu7-xtgvh3);
2. Resize "Price" column until horizontal scroll disappears;
🐞 See white block left at the bottom of locked columns;
4. Resize "Name" column until white block at the bottom disappears;
5. Resize "Price" column until horizontal scroll appears;
6. Scroll to the bottom;
🐞 See rows misaligned.

![locked-columns-demo](https://user-images.githubusercontent.com/23496057/57926519-2c0ce600-78b4-11e9-9885-a941860f5ac7.gif)

**Expected behavior**
Rows are aligned.

**Browser**
Chrome 74.0.3729.157 on Windows 10

**Comment by danielkaradachki** [comment]
Should be fixed in the latest dev version:

https://stackblitz.com/edit/angular-vydfu7-df7kiq?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Released in 3.14.3
