### ISSUE TITLE
Align justify resets alignment instead of setting text-align: justify

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2271]
**Describe the bug**
Clicking the button for `Align Justify` removes alignment styles from the element

**To Reproduce**
1. Select text
2. Click `Center text` button
3. Inline style of the element is set to `text-align: center`
4. Click `Justify` button in the toolbar
5. Inline style is removed

 **Runnable snippet**
https://stackblitz.com/edit/angular-atrk2r?file=app/app.component.ts

**Expected behavior**
Clicking `Justify` should set `text-align: justify`

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-editor v0.11.0`
