### ISSUE TITLE
Kendo Angular Scheduler -  While using resource grouping, events still appear even if their assigned resource ID doesn't exist

### ISSUE THREAD

**Issue by shaizel** [telerik/kendo-angular#2272]
**Describe the bug**
When the scheduler is grouped by a Resource, events that are assigned a resource ID that doesn't exist on the Resource are still displayed, under the first existing resource.

**To Reproduce**
1. Create a Resource.
2. Create a Group using the Resource created above.
2. Create an event and assign it a resource ID that doesn't exist on the Resource created above.

[Demo snippet on StackBlitz](https://stackblitz.com/edit/angular-zrpg4z?file=app/app.component.ts)

* Tested in versions **0.11.1**, **0.12.1**, **0.13.0-dev.201905161238**.

**Expected behavior**
The Scheduler will not display the event with the illegal resource, like in the jQuery Kendo Scheduler.

**Comment by danielkaradachki** [comment]
Fix released in 0.15.0

https://stackblitz.com/edit/angular-wjkrta?file=app/app.component.ts
