### ISSUE TITLE
Scheduler - Resource grouping with template breaks alignment

### ISSUE THREAD

**Issue by Felx-B** [telerik/kendo-angular#2273]
**Describe the bug**
When defining a resource template (groupheadertemplate) with more than 1 line, scheduler alignment is no more consistent in timeline views

**To Reproduce**
Here is the stablitz reproduction https://stackblitz.com/edit/kendo-scheduler-resourcegroup

**Expected behavior**
Event lines should be aligned with resource headers

**Browser**
 - OS:  Windows 10
 - Browser Chome
 - Version 74

**Comment by ipeshev** [comment]
@Felx-B thank you for the bug report, we will investigate it further.

**Comment by ipeshev** [comment]
![Screenshot from 2019-07-08 16-15-21](https://user-images.githubusercontent.com/4143177/60813166-c7775480-a19b-11e9-9f96-5a54e6a5ec69.png)

**Comment by Felx-B** [comment]
Thank you for the update.
It seems to work on a static sample, but if resource template is dynamic the, view is not synchronized. 
After moving to another day, the view is well aligned.

Is there any method available to force alignment evaluation on the current view ?

I updated my sample with a toggle button.

**Comment by danielkaradachki** [comment]
Hi, changing any option should update the view:
https://stackblitz.com/edit/kendo-scheduler-resourcegroup-tcyjgj?file=app/app.component.ts

We will consider exposing dedicated API that does this.

**Comment by yanmariomenev** [comment]
Item was moved to our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1616961-provide-an-updateview-method-for-the-scheduler-component
