### ISSUE TITLE
Can't abstract kendo columns

### ISSUE THREAD

**Issue by juanslingerURUIT** [telerik/kendo-angular#2274]
**Describe the bug**
Creating a wrapper of the kendo-grid on my application, I want to have the availability of using kendo-grid-column-group and kendo-grid-column. To use kendo-grid-column-group I have to define which inputs it has and after use kendo-grid-column with its own inputs. If the column does not have column-group defined, I just use kendo-grid-column. I'm having trouble abstracting kendo-grid-column inside an ng-template to prevent duplicating code. It just shows all columns, as nothing is defined.

**To Reproduce**
* Have a list of columns defined.
* Create an ng-container with a ngFor to loop through all columns.
* If the column is a column-group, use kendo-grid-column-group and as a child node use ng-container with ngTemplateOutlet using an ng-template already defined. If the column is not a column-group just use ng-container with ngTemplateOutlet using ng-template already defined.
* Inside ng-template, just have kendo-grid-column with inputs.

**Expected behavior**
Expecting to show columns definition as expected, but the grid is rendering all columns depending on data pass as input and with no features (sort, filter, column reorder...).

**Screenshots**

**Browser**
 - OS: [iOS]
 - Browser [Chrome, Safari, IE, Edge, Firefox]
 - Version [for example, 22]

**Additional context**

Want to have code as this.

```
<kendo-grid
  [data]="gridData">
  <ng-container *ngFor="let column of columns">
      <ng-container *ngIf="column.isGroup">
          <kendo-grid-column-group [title]="column.groupTitle">
              <ng-container *ngTemplateOutlet="columnTemplate; context:column" >
              </ng-container>
          </kendo-grid-column-group>
      </ng-container>
      <ng-container *ngIf="!column.isGroup">
          <ng-container *ngTemplateOutlet="columnTemplate; context:column" >
          </ng-container>
      </ng-container>
  </ng-container>
</kendo-grid>

<ng-template #columnTemplate let-column="column">
    <kendo-grid-column [field]="column.field" [title]="column.title"></kendo-grid-column>
</ng-template>
```

But I have something like this

```
<kendo-grid
  [data]="gridData">
  <ng-container *ngFor="let column of columns">
        <ng-container *ngIf="column.isGroup">
            <kendo-grid-column-group [title]="column.groupTitle">
                <kendo-grid-column [field]="column.field" [title]="column.title"></kendo-grid-column>
            </kendo-grid-column-group>
        </ng-container>
        <ng-container *ngIf="!column.isGroup">
            <kendo-grid-column [field]="column.field" [title]="column.title"></kendo-grid-column>
        </ng-container>
  </ng-container>
</kendo-grid>
```

**Comment by ipeshev** [comment]
This repo is for Bug reports only , please open a support ticket on our [Support portal](https://www.telerik.com/account/support-tickets).
