### ISSUE TITLE
[Donut Chart] Labels outsideEnd overlap title

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2275]
**Describe the bug**
Sometimes instead of making the donut's circle small enough to fit the labels in the area below the title the donut decides to overlap the labels with the chart title. 

**To Reproduce**
Set the series labels to be shown `outsideEnd` and make the container of the chart small enough. 

https://stackblitz.com/edit/angular-uucnll?file=app/app.component.ts

**Expected behavior**
The chart should cope to modify the circles to be small enough so that the labels are not cut/overlap the title. Also the "call outs" of the labels can be make a bit smaller (you can see in the above example they are unreasonably big so eating space for the title/chart. 

**Screenshots**
Normal chart:
![image](https://user-images.githubusercontent.com/9464097/58102374-d99c3400-7be9-11e9-8cce-378e64867053.png)

Smaller chart:
![image](https://user-images.githubusercontent.com/9464097/58102516-0f411d00-7bea-11e9-82f4-418b66633489.png)
Labels are cut off at the bottom, overlap the title at the top, yet there are very long "call outs"

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 74

**Comment by danielkaradachki** [comment]
You can reduce the [distance](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesLabelsComponent/#toc-distance):
https://stackblitz.com/edit/angular-uucnll-iycqu4?file=app/app.component.ts

or use the [autoFit](https://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesItemComponent/#toc-autofit) option to avoid this:
https://stackblitz.com/edit/angular-uucnll-j5pyc9?file=app/app.component.ts

**Comment by PeterStaev** [comment]
Thanks @danielkaradachki ! Somehow I missed those settings in the docs 😅
