### ISSUE TITLE
[Button] Outline buttons are not getting parent colors

### ISSUE THREAD

**Issue by EyedealGraphics** [telerik/kendo-angular#2277]
**Current behavior**
Buttons with a look of "outline" are not inheriting the color from their parent, as suggested in the documentation.

>  Outline Button sets a transparent background and a solid border for its normal state and inherits all its color properties—for example, background-color, color, and border-color—from its parent element. To render an Outline Button, use the look="outline" configuration.

**To Reproduce**
StackBlitz (from documenation): [https://stackblitz.com/run](https://stackblitz.com/run)

**Expected behavior**
I would expect the colors of the button to be inherited from their parent declarations as stated in the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/47642232/58174301-92ef1e00-7c6b-11e9-90aa-0f3628ccb67a.png)

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.157 (64-bit)

**Comment by danielkaradachki** [comment]
The issue is with the documentation. We will update it as soon as possible.

**Comment by dtopalov** [comment]
The documentation is updated accordingly:

https://www.telerik.com/kendo-angular-ui-develop/components/buttons/button/styling/#toc-outline-button

https://www.telerik.com/kendo-angular-ui-develop/components/buttons/buttongroup/styling/#toc-outline-buttongroup
