### ISSUE TITLE
[Bug] Tree view with checkbox

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#2278]
**Describe the bug**
Tree view with checkbox bug.

If the disabled item is parent node, expanding functionality does not work anymore

**To Reproduce**
1. disable parent node
2. see that the expand icon is also disabled and can not be clicked

**Expected behavior**
If parent node is disabled, we can still expand it

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by danielkaradachki** [comment]
The behavior is by design. It should not be possible to interact with disabled nodes and their children in any way.
