### ISSUE TITLE
[Scheduler] Double tap on event on iOS does not trigger eventDblClick

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2279]
**Describe the bug**
Double tapping on an event on iOS Safari does not trigger the `eventDblClick`

**To Reproduce**
1. Add an `eventDblClick` binding to the scheduler
2. Double tap on an event

**Expected behavior**
Event should be triggered

**Browser**
 - OS: iOS 12.2
 - Browser: Safari
 - Version 12.2

**Comment by tsvetomir** [comment]
The `slotDblClick` and `eventClick` events also do not fire, preventing editing from working normally. Sample project build with the Angular CLI is available at https://github.com/tsvetomir/kendo-angular-2279

**Comment by tsvetomir** [comment]
Fixed in v0.13.3

**Comment by PeterStaev** [comment]
@tsvetomir , there seems to be some regression of this problem with iOS13 / iPadOS 13. 

Using Angular 8 and Scheduler 1.0 on iOS12 the event triggers fine, but when testing on iOS13.1/iPadOS seems the event is not triggered at all. This is for the `eventDblClick`, the `eventClick` event seems to be triggered correctly.

**Comment by tsvetomir** [comment]
I can confirm the issue with iOS 13. We'll investigate. Thanks!

**Comment by tsvetomir** [comment]
Sorry for the delay, should be fixed in the [latest development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fix released in v1.1.5
