### ISSUE TITLE
NumericTextBox - Doesn't work with reactive forms

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#228]
NumericTextBox (version 0.18.2) does not work with reactive forms. I get error message...

inline template:196:62 caused by: No value accessor for form control with name: 'sortOrder'

`<kendo-numerictextbox formControlName="sortOrder"
                                                              required
                                                              [format]="'n0'"
                                                              [step]="step">
                                        </kendo-numerictextbox>`

Also, your plunker example for reactive forms won't load either.

**Comment by rusev** [comment]
It seems to be working in the [examples](http://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/#toc-forms-support). 

Here is a runnable plnkr - http://plnkr.co/edit/FlTfasHq8wvRBzCsWbOK?p=preview
