### ISSUE TITLE
[Scheduler] Using midnight for scrollToTime does not scroll at the start

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2280]
**Describe the bug**
If you try to call `scrollToTime` with a midnight time, the scheduler does not scroll to the top. 

**To Reproduce**
https://stackblitz.com/edit/angular-w3qaw1?file=app/app.component.ts
Pressing the button for "Scroll to 00:00:00" has no effect. 

**Expected behavior**
The scheduler should scroll to the top

**Browser**
 - OS: Windows
 - Browser Chrom
 - Version 74

**Additional context**
Current workaround is to scroll to something like 00:00:01. Then the scheduler scrolls correctly to the top.

**Comment by danielkaradachki** [comment]
Fix released in 0.15.0

https://stackblitz.com/edit/angular-ejgbca?file=app/app.component.ts
