### ISSUE TITLE
[GRID] Editing multiple rows simultaneously leeds to “Maximum call stack size exceeded” error

### ISSUE THREAD

**Issue by proalphaDev** [telerik/kendo-angular#2281]
**Describe the bug**
Create a grid with >= 5 columns and EditTemplateDirectives, load multiple rows (say 100) and call editRow for each row to open all rows on startup.
--> Error in Chrome DevTools “Maximum call stack size exceeded”.

A short analysis showed that the error appears in "NavigationService.prototype.tryFocus", since a focusable child is searched recursively for each row.

**To Reproduce**
https://stackblitz.com/edit/angular-9ftv38
Click on "Open all"

**Expected behavior**
For the use case of editing mulitple rows simultaneously (e.g. to batch the updates), could you please do the focus of the row/input-widget only optional, i.e. make the focus configurable?

**Browser**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 74.0.3729.169 (64-Bit)

**Screenshot**
![grafik](https://user-images.githubusercontent.com/36737709/58321058-5ebb5f00-7e1d-11e9-98d4-51a2c1b2060c.png)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Fixed in 4.4.0

https://stackblitz.com/edit/angular-1ff5wd?file=app/app.module.ts
