### ISSUE TITLE
[ExcelComponent] fetchData is executed after every user interaction with the Grid

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular#2283]
**Describe the bug**
`fetchData` of `ExcelComponent` is executed numerous times - after initial load, after sorting, after group expands/collapses and etc.

**To Reproduce**

Example: https://stackblitz.com/edit/angular-gtpbeg?file=app/app.component.ts

1. Watch the console after the page is loaded
2. Try to sort or expand/collapse a group and watch the console
3. Click the 'Export to Excel' button and watch the console

**Expected behavior**
`fetchData` callback should be executed only after 'Export to Excel' button is clicked.

**Additional context**
Reported in ticket 1410184

**Comment by danielkaradachki** [comment]
Pass function reference instead of calling the funtion:
https://stackblitz.com/edit/angular-gtpbeg-snyusg?file=app/app.component.ts
