### ISSUE TITLE
Kendo UI for Angular - [Column Menu Component] - Column Chooser HELP!!

### ISSUE THREAD

**Issue by wenditurner** [telerik/kendo-angular#2284]
Kendo UI for Angular - [Column Menu Component] - Column Chooser
Angular v5.1.1 + Kendo Grid v3.14.2 

HELP!!  My grid component behaves beautifully UNTIL I try to add the feature of Column Menu / Chooser.  I have tried the below to methods, both error messages are below.   

app.component.html
(1)            <kendo-grid [data]="view | async"
                        [pageSize]="pageSize"
                        [skip]="skipRecord"
                        [filterable]="true"
                        [pageable]="true"
                        (pageChange)="pageChange($event)"
                        [scrollable]="'none'"
                        [sortable]="true"
                        [sort]="sort"
                        (sortChange)="sortChange($event)">
                <ng-template kendoGridToolbarTemplate>
                    <kendo-grid-column-chooser></kendo-grid-column-chooser>       
                </ng-template>
* ERROR (1) run-time browser console: 
	Uncaught Error: Template parse errors:
'kendo-grid-column-chooser' is not a known element:
1. If 'kendo-grid-column-chooser' is an Angular component, then verify that it is part of this module.
2. If 'kendo-grid-column-chooser' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

- OR -

(2)            <kendo-grid [data]="view | async"
                        [pageSize]="pageSize"
                        [skip]="skipRecord"
                        [filterable]="true"
                        [columnMenu]="{ columnChooser: true }"                   
                        [pageable]="true"
                        (pageChange)="pageChange($event)"
                        [scrollable]="'none'"
                        [sortable]="true"
                        [sort]="sort"
                        (sortChange)="sortChange($event)">

* ERROR (2) run-time browser console: Uncaught Error: Template parse errors:
Can't bind to 'columnMenu' since it isn't a known property of 'kendo-grid'.
1. If 'kendo-grid' is an Angular component and it has 'columnMenu' input, then verify that it is part of this module.
2. If 'kendo-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

* kendoGridExcelCommand works great later in template like below...
                <ng-template kendoGridToolbarTemplate>
                    <button kendoGridExcelCommand>Export to Excel</button>
                </ng-template>

** package.json

  "dependencies": {
    "@angular/animations": "^5.1.1",
    "@angular/common": "^5.1.1",
    "@angular/compiler": "^5.1.1",
    "@angular/compiler-cli": "^5.1.1",
    "@angular/core": "^5.1.1",
    "@angular/forms": "^5.1.1",
    "@angular/http": "^5.1.1",
    "@angular/platform-browser": "^5.1.1",
    "@angular/platform-browser-dynamic": "^5.1.1",
    "@angular/platform-server": "^5.1.1",
    "@angular/router": "^5.1.1",
    "@ngtools/webpack": "^1.9.1",
    "@progress/kendo-angular-buttons": "^4.0.0",
    "@progress/kendo-angular-dateinputs": "^2.2.0",
    "@progress/kendo-angular-dialog": "^3.4.0",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-grid": "^3.0.0",
    "@progress/kendo-angular-inputs": "^2.2.0",
    "@progress/kendo-angular-intl": "^1.4.0",
    "@progress/kendo-angular-l10n": "^1.1.0",
    "@progress/kendo-angular-layout": "^3.1.0",
    "@progress/kendo-angular-popup": "^2.2.0",
    "@progress/kendo-angular-tooltip": "^0.4.0",
    "@progress/kendo-data-query": "^1.2.2",
    "@progress/kendo-drawing": "^1.5.2",
    "@progress/kendo-theme-default": "^2.47.0",
...
    "angular2-template-loader": "0.6.2",
    "applicationinsights-js": "^1.0.14",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
...
    "jquery": "3.2.1",
...
    "rxjs": "^5.5.2",
    "typescript": "^2.5.3",
...
  },

**Comment by danielkaradachki** [comment]
Verify that you have installed version 3.3.0 or later of the grid package. If you have a later version, please open a  [support ticket](https://www.telerik.com/account/support-tickets) with runnable sample that demonstrates the problem.
