### ISSUE TITLE
Different background color for events in Kendo-Schduler Angular

### ISSUE THREAD

**Issue by vahidsamimi** [telerik/kendo-angular#2285]
Is there a way to style the background color of events depending on the type of event?
I know I can globally set the event background colors using css 

`.k-event{background-color: #000;}
` 

but this doesn't help me when I have different types of events with different colors. Is there any workaround for this?

**Comment by tsvetomir** [comment]
The only option at the moment is to assign resources, see [Resource Binding](https://www.telerik.com/kendo-angular-ui/components/scheduler/data-binding/#toc-resource-binding).
A future update will allow setting colors with a callback, see https://github.com/telerik/kendo-angular/issues/2095#issuecomment-494720239

**Comment by vahidsamimi** [comment]
thanks for your answer but I want to create a scheduler like this photo. It means that each event can have a different color.
[https://i.ibb.co/5LXnGcZ/sample.png](url)

**Comment by tsvetomir** [comment]
The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

**Comment by vahidsamimi** [comment]
but I have any access to post a new issue in the forum.

**Comment by joharzmn** [comment]
You can use this property `eventStyles` 
Defines a function that is executed for every event in the view. The function returns a value which is supported by ngStyle.

This is how you can create a function to use for `eventStyles` property.
```
// Use an arrow function to capture the 'this' execution context of the class.
  public getEventStyles = (args: EventStyleArgs) => {
    return { backgroundColor: args.event.dataItem.color };
  }
```
