### ISSUE TITLE
DateRangePopupComponent does not emit 'cancel' event but twice emits 'close' event

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#2288]
**Describe the bug**
Each time the DateRange Popup is closed the 'close' event fires twice but the 'cancel' event does not fire at all.

**To Reproduce**
[Here](https://stackblitz.com/edit/angular-dnmkze) is a link to the snippet on StackBlitz.

1. Open the [snippet](https://stackblitz.com/edit/angular-dnmkze)
2. Open and close DateRange Popup
3. Open console and notiсe that the 'close' event has been logged twice and the 'cancel' event hasn't been logged at all.

**Expected behavior**
Should work as described in the [documentation](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DateRangePopupComponent/#toc-events):
- 'cancel': Fires each time the Popup is closed either on ESC keypress or on leaving the viewport.
- 'close': Fires each time the popup is about to close.

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `@progress/kendo-angular-dateinputs` package (**v4.0.1-dev.201907021017**).

**Comment by dimitar-pechev** [comment]
Shipped with **v4.0.1**.
