### ISSUE TITLE
[Sortable] clearActiveItem does not work

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2289]
**Describe the bug**
Calling `clearActiveItem()` does not actually clear the active item. 

**To Reproduce**
https://stackblitz.com/edit/angular-kzc4zi?file=app/app.component.ts
1. In the first sortable drag the last item to the place of the first
2. On `dragEnd` the code calls `clearActiveItem()` but you will see that the active item is not actually cleared. 

The second sortable manually sets `activeIndex` to `-1` and works as expected. 

**Expected behavior**
Calling `clearActiveItem() should clear the active class/index of the item

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 74

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-sortable`

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-sortable v3.0.4`
