### ISSUE TITLE
Calendar : Is it collapsible?

### ISSUE THREAD

**Issue by pmangat** [telerik/kendo-angular#229]
http://www.telerik.com/kendo-angular-ui/components/dateinputs/api/CalendarComponent/

Is calendar control collapsible?

**Comment by KirilNN** [comment]
The calendar control is a block element that is not rendered inside a popup, so in its essence it is not collapsible. I believe that this is what you are looking for:

http://plnkr.co/edit/B68ZymlS2S4VoOV8GLr7?p=preview

**Comment by pmangat** [comment]
Thank you - it was answered before. 
Can i ask when will the date and time pickers be released?

**Comment by ggkrustev** [comment]
@pmangat, DateInput, DatePicker and TimePicker are in our roadmap and they definitely will be released in the official release planned for May this year.

I do believe, however, they will be out even earlier, but I wouldn't be able to provide a concrete date for that.
