### ISSUE TITLE
Error when using SCSS themes with Angular 8

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2292]
**Problem**
Importing the SCSS versions of the Kendo UI themes in an Angular 8 CLI project results in a compilation error:

```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--13-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

                @extend .k-button::before;
                       ^
      Compound selectors may no longer be extended.
Consider `@extend .k-button, ::before` instead.
See http://bit.ly/ExtendCompound for details.

    ╷
105 │                 @extend .k-button::before;
    │                         ^^^^^^^^^^^^^^^^^
    ╵
  node_modules/@progress/kendo-theme-default/scss/toolbar/_layout.scss 105:25  root stylesheet
      in /private/tmp/ng8-scss/node_modules/@progress/kendo-theme-default/scss/toolbar/_layout.scss (line 105, column 25)
```

**Workarounds**
* Install node-sass to revert back to the old compilation pipeline: 
  `npm install node-sass --save-dev`
* [Use Precompiled CSS](https://www.telerik.com/kendo-angular-ui/components/styling/#toc-including-themes-by-using-precompiled-css) when no customization is necessary.
* Customize themes [Using the Build Process of the Themes](https://www.telerik.com/kendo-angular-ui/components/styling/custom-themes/#toc-using-the-build-process-of-the-themes).

**See also**
* Related bug report in https://github.com/telerik/kendo-themes/issues/722

Apologies for the caused inconvenience.

**Comment by joneff** [comment]
telerik/kendo-themes#775 targets dart compilation.

**Comment by meriturva** [comment]
Any ETA here related to @progress/kendo-theme-default and @progress/kendo-theme-bootstrap package releases?

**Comment by joneff** [comment]
The themes are now in the dev channel:

* @progress/kendo-theme-default v3.8.0-dev.ee54ef17
* @progress/kendo-theme-bootstrap v3.5.0-dev.ee54ef17
* @progress/kendo-theme-material v2.6.0-dev.ee54ef17

Note that the next non dev release will bump the major version.

**Comment by tsvetomir** [comment]
Fix released in:
* @progress/kendo-theme-default v4.0.0
* @progress/kendo-theme-bootstrap v4.0.0
* @progress/kendo-theme-material v3.0.0

**Comment by jbennie** [comment]
how long until npm updates

**Comment by prabh-62** [comment]
> how long until npm updates

It's already available in NPM registry
```bash
> npm view @progress/kendo-theme-default

@progress/kendo-theme-default@4.0.0 | Apache-2.0 | deps: none | versions: 1075
SASS resources for the default Kendo UI theme
https://github.com/telerik/kendo-themes#readme
```

```bash
> npm install @progress/kendo-theme-default
# should install v4 in node_modules
```

**Comment by Dhruv-0987** [comment]
I have version 4 in my packages but It is still giving the exact same error.

<img width="1283" alt="image" src="https://github.com/telerik/kendo-angular/assets/69164713/bbeaf212-f216-49d0-b74d-a3642b37b87b">


this is how my package.json looks like:
<img width="484" alt="image" src="https://github.com/telerik/kendo-angular/assets/69164713/37a16168-f2d3-4295-8ef4-e825ed7874a1">
