### ISSUE TITLE
[Scheduler] Daylight-saving issue causes rendering problems in Month view

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2293]
A Scheduler with the following setup causes unexpected rendering of the Month view (November) when the autumn daylight-saving change is applied in an Israel time zone:

[https://stackblitz.com/edit/angular-mzagrq?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-mzagrq?file=app%2Fapp.component.ts)

![image](https://user-images.githubusercontent.com/7533599/58550651-e5ee4580-8216-11e9-8373-5dad332f31a3.png)

Seems related to the fact that the date of daylight-saving change from summer to standard time coincides with the first day in the month view:

[https://www.timeanddate.com/time/change/israel/jerusalem](https://www.timeanddate.com/time/change/israel/jerusalem)

The Scheduler is rendered as expected when another time zone with the same offset (e.g. EEST) is used:

![image](https://user-images.githubusercontent.com/7533599/58550745-22ba3c80-8217-11e9-8bc0-ced9dc49541c.png)

**Comment by danielkaradachki** [comment]
Fix released in 0.15.0

https://stackblitz.com/edit/angular-2v8gmn?file=app/events-utc.ts
