### ISSUE TITLE
Button icons

### ISSUE THREAD

**Issue by pmangat** [telerik/kendo-angular#230]
`<kendo-grid-column width="150">
      <template kendoGridCellTemplate let-dataItem>
        <button kendoButton (click)="onEdit(dataItem)" [icon]="'pencil'"></button>
        <button kendoButton (click)="onDelete(dataItem)" [icon]="'trash'"></button>
        <button kendoButton (click)="runJob(dataItem)" `[icon]="'play'"></button>`
      </template>
</kendo-grid-column>
`
When I try the Icons from http://docs.telerik.com/kendo-ui/styles-and-layout/icons-web, icons like pencil and trash does work but not icons like play. What am I missing?

Thanks.

**Comment by lucifercha** [comment]
i do not know whether the kendo-angular support the whole icon in [http://docs.telerik.com/kendo-ui/styles-and-layout/icons-web](url),you can upgrade your @progress/kendo-theme-default to try it again.

**Comment by KirilNN** [comment]
Seems to be working here - http://plnkr.co/edit/WVf1ijX1OjM6gOIkzxif?p=preview

**Comment by pmangat** [comment]
Thank you I was installed @telerik/kendo-theme-default instead of @progress/kendo-theme-default.
