### ISSUE TITLE
[TreeView] Template with an Input triggers the checkedChange event in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2301]
When an Input element is used in a checkable TreeView's template, after focusing in and out of the Input, and then back in, typing a space triggers the default keyboard navigation space bar behavior (the checkedChange event is triggered and the respective checkbox is toggled):

[https://stackblitz.com/edit/angular-jadvjf?file=app/app.component.ts](https://stackblitz.com/edit/angular-jadvjf?file=app/app.component.ts)

To reproduce, please follow these steps:

1. Go to single mode selection.
2. Click on any checkbox.
3. Click on any textbox.
4. Click on the screen area outside the textbox. (focus out)
5. Go to the textbox and press spacebar.

Then, the checkbox is checked on pressing spacebar.

This happens only in IE:

[https://www.screencast.com/t/J8qWeeA5aol3](https://www.screencast.com/t/J8qWeeA5aol3)

**Comment by stnikolova** [comment]
IE is no longer supported by Kendo UI for Angular.
