### ISSUE TITLE
[DatePicker] "min" date with a time portion causes a scroll position issue

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2302]
When the "min" option is set to a Date with a time portion, clicking on the next month in the month scroller renders an empty month:

[https://stackblitz.com/edit/angular-zzgbh9-s2pqxk?file=app/app.component.ts](https://stackblitz.com/edit/angular-zzgbh9-s2pqxk?file=app/app.component.ts)

1. Open the Calendar
2. Click June // scrolling works as expected

Works as expected when the min Date is created with no time portion.

**Comment by dimitar-pechev** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the **DateInputs** package (**v4.0.0-dev.201906181138**).

**Comment by dimitar-pechev** [comment]
The fix is included in the latest version of the `@progress/kendo-angular-dateinputs` package (**v4.0.0**).
