### ISSUE TITLE
[GRID, Virtual Scrolling] Grid does not jump to the starting point for skip greater than 0

### ISSUE THREAD

**Issue by proalphaDev** [telerik/kendo-angular#2307]
**Describe the bug**
If you activate virtual scrolling with asynchronous data and start with a skip value > 0, the grid does not jump to the right starting point. Instead, it jumps to the skip=0 starting point and fills white space between skip=0 and real skip starting point.

**To Reproduce**
https://stackblitz.com/edit/angular-1bbvpl

**Screenshot**
![grafik](https://user-images.githubusercontent.com/36737709/58887059-30733480-86e5-11e9-86bd-1120317be06e.png)

**Expected behavior**
Grid jumps to the starting point corresponding to the skip-value.

**Browser**
 - OS: Win 7, 64-Bit
 - Browser: Firefox, Chrome

**Comment by danielkaradachki** [comment]
Closing as duplicate of https://github.com/telerik/kendo-angular/issues/1980
