### ISSUE TITLE
[GRID, Virtual Scrolling] Grid jumps to old starting point after pageChange is emitted

### ISSUE THREAD

**Issue by proalphaDev** [telerik/kendo-angular#2308]
**Describe the bug**
If pageChange fires, the grid jumps to the starting point of the old batch until the next batch was loaded correctly.

**To Reproduce**
https://stackblitz.com/edit/angular-arvxdz
Added a delay time (setTimeout) to loadProducts.
Scroll until pageChagne fires (pageSize=50) --> Grid jumps to old starting point.

**Expected behavior**
Grid does not jump to old starting point.

**Browser**
 - OS: Win 7
 - Browser: Firefox, Chrome

**Comment by danielkaradachki** [comment]
Same as https://github.com/telerik/kendo-angular/issues/622

Use [loading indicator](https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/#toc-indicating-ongoing-data-operations) to hide the old data until the new data is rendered.

**Comment by proalphaDev** [comment]
We have no implemented the loading indicator, as you suggested. However, if the grid has a selection for instance at the starting point of the old batch, the jump looks very strange. The selection is also recognized with your (transparent!) loading indicator.
Hence, the loading indicator is no solution for this issue.
