### ISSUE TITLE
Label focus throw a exception when attached on KendoUpload

### ISSUE THREAD

**Issue by dnshiroma** [telerik/kendo-angular#2309]
**Describe the bug**
Label focus throw a exception when attached on a upload component.

**To Reproduce**
Using Label directive on a template reference of Kendo Upload Component throws an exception on console when clicked on label element.
<label [for]="file">File: </label>
<kendo-upload #file></kendo-upload>

https://stackblitz.com/edit/angular-4vjved?file=app/app.component.ts

**Screenshots**
![image](https://user-images.githubusercontent.com/12010663/58898777-b2f1f900-86d1-11e9-8307-6743382efdc0.png)

**Browser**
 - OS: Windows
 - Browser Chrome 
 - Version 74.0.3729.169

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.
