### ISSUE TITLE
[Excel Export] formatting the value in group header does not work

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2312]
**Describe the bug**
When using `groupHeaderCellOptions.format` to set the formatting of the value in the group header it has no effect. 

**To Reproduce**
https://stackblitz.com/edit/angular-l9g1k2?file=app/app.component.ts
the same `CellOptions` are applied both to the headers and the column, yet the header is not formatted. 

**Expected behavior**
The header should be formatted based on the value of `groupHeaderCellOptions.format`

**Comment by danielkaradachki** [comment]
The format will not work because the content of the group header is a string. You can use a group header template to format the value:

https://stackblitz.com/edit/angular-l9g1k2-xcccy7?file=app/app.component.ts
