### ISSUE TITLE
Kendo Grid clear filter button modifies input filter

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#2315]
All inputs should be considered immutable due to one-directional dataflow. It is common practice and it works correctly in most situations, for example - if you add filter via filter row, @Input filter / filters are not modified - changes are pushed via @Output()  filterChanges etc.

However - clear of the filters via Kendo grid "clear button" 
![image](https://user-images.githubusercontent.com/10418323/59041970-ea9ba500-8879-11e9-9af5-d83c7e59d3c8.png)

DOES change property Filters of @Input filter  (CompositeFilterDescriptor) .
![image](https://user-images.githubusercontent.com/10418323/59042182-436b3d80-887a-11e9-905c-9d04f8495885.png)

This is Input mutation and this violates uni-directional  dataflow and it will crash with things like  ngrx with strict immutability.

**Expected behavior**
None part of grid should mutate inputs.  

Version:
  version "3.14.1"

**Comment by kunajs** [comment]
I have a similar problem when using kendo-grid-string-filter-cell.

`<ng-template
	kendoGridFilterCellTemplate
	let-filter
	let-column="column"
>
	<kendo-grid-string-filter-cell
		[showOperators]="showOperators"
		[column]="column"
		[filter]="filter"
	>
	</kendo-grid-string-filter-cell>
</ng-template>`

@Input filter, which comes from "let-filter", is changed by this:
![image](https://user-images.githubusercontent.com/39991506/59086710-d059d980-8902-11e9-80b3-d22d93b2e8f4.png)

**Comment by kunajs** [comment]
any progress?

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by danielkaradachki** [comment]
Fixes released in kendo-angular-grid 4.2.0 and kendo-data-query 1.5.2
