### ISSUE TITLE
Screen reader do not read label attached on switch

### ISSUE THREAD

**Issue by dnshiroma** [telerik/kendo-angular#2316]
**Describe the bug**
When switch field receive focus by tab navigation using NVDA. The screen reader not read text on label.

**To Reproduce**
https://stackblitz.com/edit/angular-xfc5fv?file=app/app.component.ts

Just navigate on switch via tab

**Screenshots**
![image](https://user-images.githubusercontent.com/12010663/59054849-eddb6480-886a-11e9-9023-34472e883599.png)

The label 'Switch Label' not appear...
![image](https://user-images.githubusercontent.com/12010663/59054928-1b281280-886b-11e9-8e78-3e9ba353e871.png)

**Browser**
 - OS: Windows
 - Browser Chrome
- Version  74.0.3729.169 64 bits
- Screen Reader NVDA V 2019.1.1

**Comment by dnshiroma** [comment]
this issue is related to: [https://github.com/telerik/kendo-angular/issues/1690](https://github.com/telerik/kendo-angular/issues/1690), but is a different problem

**Comment by danielkaradachki** [comment]
Thank you for the bug report. We will track it in the other issue.
