### ISSUE TITLE
Kendo-Window does not overlap screen when launched from within child Kendo-Grid

### ISSUE THREAD

**Issue by kambbado** [telerik/kendo-angular#2318]
**Describe the bug**
When launching a Kendo-Windows from a child grid the window becomes a child of the grid and does not overlap the screen

**To Reproduce**
Please see [StackBlitz](https://stackblitz.com/edit/kendo-window-parent-issue) example
Clicking the edit on the first grid the window will display on top, but when clicking the edit on the 2nd grid the window will display inside the first grid,

**Expected behavior**
Expected window to be top most element overlapping all contents

**Browser**
 - OS:Windows 10
 - Browser Chrome
 - Version  75.0.3770.80 

**Additional context**
I'm not sure if I'm doing it wrong but what I want it to create a Modal window to overlap all contents.

**Comment by danielkaradachki** [comment]
You should use the [WindowService](https://www.telerik.com/kendo-angular-ui/components/dialogs/window/service/) to create the window outside of the grid content in order to avoid the problem.
