### ISSUE TITLE
Kendo chart series item can't be exploded

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2319]
**Describe the bug**
I've created a simple app with the kendo-chart component and would like to explode the sector when the user clicks on it. I've provided explodeField as an input parameter, but nothing happened.

**To Reproduce**

1. Open https://stackblitz.com/edit/angular-awz8ky?file=app/app.component.ts
2. Click on any sector and see that the sector is not exploded

**Expected behavior**
The sector should be exploded

**Browser**
 - OS: Windows 10, x64
 - Browser [for example, Chrome, Safari]: Chrome v 74
 - Version [for example, 22] The latest version of all packages

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

**Comment by destus90** [comment]
It was a local issue. Now everything works correctly https://stackblitz.com/edit/angular-awz8ky-jpkujf?file=app/app.component.ts
