### ISSUE TITLE
Multiselect: Better placeholder handling?

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#232]
```
  MultiSelectComponent.prototype.ngAfterViewInit = function () {
        var _this = this;
        this.searchbar.resizeInput(this.placeholder.length);
        this.observableSubscriptions.add(this.searchbar.onFocus.subscribe(function () { return _this.isFocused = true; }));
        this.observableSubscriptions.add(this.searchbar.onBlur.subscribe(function () { return _this.isFocused = false; }));
    };
```
When I bind the placeholder to a property, which isn't defined or initialized with null, an exception is thrown. Perhaps first check. if placeholder is defined?

**Comment by KirilNN** [comment]
What do you expect the placeholder to be, when you set it to an undefined variable? Empty string or undefined?

**Comment by KirilNN** [comment]
Will go ahead and set it to be an empty string. Please test it out with the 0.26.9 version of the package.

**Comment by EricSch** [comment]
Sorry for the late response. I would also suggest empty string. Would be the same behavior like no placeholder defined.
