### ISSUE TITLE
Incorrect imports for TemplateRef and ViewContainerRef after upgrading project to Angular 8

### ISSUE THREAD

**Issue by appeality** [telerik/kendo-angular#2320]
**Describe the bug**

After updating a project to Angular 8, the following build errors are thrown:

ERROR in node_modules/@progress/kendo-angular-dialog/dist/es2015/window/window-settings.d.ts(1,29): error TS2307: Cannot find module '@angular/core/src/linker/template_ref'.
node_modules/@progress/kendo-angular-dialog/dist/es2015/window/window-settings.d.ts(2,34): error TS2307: Cannot find module '@angular/core/src/linker/view_container_ref'.

**To Reproduce**

Install Kendo-angular-dialog in Angular 8+ project.

**Expected behavior**

I expected the upgrade to work without issue.

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

The issue is with the import of TemplateRef and ViewContainerRef in the aforementioned file. The fix is simple. Changing the imports as follows fixes the problem:

import { TemplateRef } from '@angular/core';
import { ViewContainerRef } from '@angular/core';

**Comment by tsvetomir** [comment]
I tried reproducing the issue in a new Angular CLI project - see https://github.com/tsvetomir/kendo-angular-2320

It seems to work fine both in development and production mode. Am I missing something?

**Comment by appeality** [comment]
I may have an outdated package, but the issue seems to be in the typings file. Its difficult to determine which of these packages is causing the problem.

    "@progress/kendo-angular-buttons": "^4.0.0",
    "@progress/kendo-angular-conversational-ui": "^1.1.1",
    "@progress/kendo-angular-dateinputs": "2 - 3",
    "@progress/kendo-angular-dialog": "^3.10.1",
    "@progress/kendo-angular-dropdowns": "2 - 3",
    "@progress/kendo-angular-excel-export": "1 - 2",
    "@progress/kendo-angular-grid": "^3.12.1",
    "@progress/kendo-angular-inputs": "2 - 4",
    "@progress/kendo-angular-intl": "^1.0.0",
    "@progress/kendo-angular-l10n": "^1.1.0",
    "@progress/kendo-angular-popup": "^2.0.0",
    "@progress/kendo-data-query": "^1.0.0",
    "@progress/kendo-drawing": "^1.0.0",

I will try updating all to the latest versions.

**Comment by tsvetomir** [comment]
The easiest option for bulk updates is to use `ncu`, see [Updating to Latest Versions](https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/#toc-updating-to-latest-versions).

**Comment by Raisolution** [comment]
Hi @appeality,

If further assistance is needed, please open a  [support ticket](https://www.telerik.com/account/support-tickets).
