### ISSUE TITLE
Can't use lazy load with kendo-angular-dialog

### ISSUE THREAD

**Issue by ngohungphuc** [telerik/kendo-angular#2327]
**Describe the bug**

So I'm using dynamic component in child module something like this
```
import {
    DialogService
} from "@progress/kendo-angular-dialog";

this.dialogService.show({
      content: AddDataComponent
});
```

I'm also add the component to entryComponents in the module
```
entryComponents: [AddDataComponent]
```

but when I try to lazy load the module everything is working well . But when I click on the button to display the popup I will have the error like this

```
UsersComponent.html:29 ERROR Error: No component factory found for AddDataComponent. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (core.js:12769)
    at CodegenComponentFactoryResolver.resolveComponentFactory (core.js:12820)
    at DialogService.contentFrom (index.js:742)
    at DialogService.initializeDialog (index.js:676)
    at DialogService.open (index.js:673)

```
 - Version "@progress/kendo-angular-dialog": "^3.11.0",

**Comment by dtopalov** [comment]
@ngohungphuc Indeed, we are aware of this limitation - the Dialog cannot bootstrap a dynamic component coming from a lazily loaded module. 

This is partially related to the specifics of the Angular framework, and also to the current Dialog service implementation. 

Further details and the Angular-related issues this limitation is related to are available in this feature request logged to our Feedback portal:

[https://feedback.telerik.com/kendo-angular-ui/1382331-allow-providing-components-from-lazy-loaded-modules-in-dialog-service?fbclid=IwAR16AOTE3PN3lNsTPCZS-Vn2bEZ0AqydERTReMxMv3MubHdgWQtRjV9nsWo](https://feedback.telerik.com/kendo-angular-ui/1382331-allow-providing-components-from-lazy-loaded-modules-in-dialog-service?fbclid=IwAR16AOTE3PN3lNsTPCZS-Vn2bEZ0AqydERTReMxMv3MubHdgWQtRjV9nsWo)

We are looking into possible solutions, but still have not found a viable one that can be seamlessly integrated in the current implementation.

You can support and follow the Feedback item at the link above - we will update it once we have further details to share.
