### ISSUE TITLE
Locked columns incorrect size after resize and hide of another locked column

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2328]
**Describe the bug**
By user ticket ... 
Resize and hide some locked column, causes the most right column incorrect size.

**To Reproduce**
1. Open this [stackblitz sample](https://stackblitz.com/edit/angular-ayaq9b-5m5ezb?file=app/app.component.ts).
2. Increase first locked column width and hide it , inspect last locked column 
3. It has width bigger than rendered.

**Expected behavior**
Last column should have correct size after resize and hide.

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by siyka-marinova** [comment]
The fix is now available also in the latest version: `@progress/kendo-angular-grid v4.4.0`
