### ISSUE TITLE
[Editor] Adding support to MutationObserver api

### ISSUE THREAD

**Issue by francisluz** [telerik/kendo-angular#2329]
**Describe the bug**
The component is using the[ MutationObserver api](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) method **takeRecords**, as this api is not supported for **IE < 11**, I've found a polyfill that helps me to fix it as I have to support IE10.

Polyfill:  https://github.com/megawac/MutationObserver.js

**To Reproduce**
Open the editor component in IE and emulate version 10.
https://www.telerik.com/kendo-angular-ui/components/editor/styling/
I was able to simulate here, when you try to type or delete the content.

**Comment by dtopalov** [comment]
IE 10 is not officially supported by Angular and the Kendo UI for Angular components:

https://www.telerik.com/kendo-angular-ui/components/installation/requirements/#toc-browsers

https://angular.io/guide/browser-support
