### ISSUE TITLE
Grid selection

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#233]
Hey,
could you please optimize the grid selection?

If i have 2 Grids (one Grid cascading to the other) and select a item in the cascaded grid, after that i change my "master grid" selection and the selected index don't change in the cascaded grid also there is no event emitting.

Plunkr:
http://plnkr.co/edit/rUxfeRqHBjky6Ni3o2Kl

**Comment by KirilNN** [comment]
Can you please provide steps to reproduce the issue? The event is emitting after every selection in your example. Thanks!

**Comment by simon11196** [comment]
Plunkr:
http://plnkr.co/edit/rUxfeRqHBjky6Ni3o2Kl?p=preview

When having a master grid and a detail grid, like in the example above, if you select something in the detail grid and change selection in the master grid, the value in the detail grid doesn't change and stays selected.

Is there a way to throw a selectionChange event or unselect the selected item in the detail grid, when the master grid selection changes and another value in the detail grid is "selected".

In the Codebehind, there is no binding at the detail grid selected item, when I change the mastergrid view. But in the GUI a new value is marked as selected at the detail grid.

Example:
First click on value 1 (master grid) then select 20 (detail grid)
After that click on value 2(master grid).
        => The selection(item focus) in detail grid hasn't changed and no selectionChange event was emitted.

**Comment by KirilNN** [comment]
Currently there is not API for clearing the selection. Improving the selection is in our plans for the next major release, so stay tuned.
