### ISSUE TITLE
[Editor] Dropdownlists valueChange event is not fired

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2330]
**Describe the bug**
According to the docs [EditorFontFamilyComponent](https://www.telerik.com/kendo-angular-ui/components/editor/api/EditorFontFamilyComponent/#toc-valuechange) [EditorFontSizeComponent](https://www.telerik.com/kendo-angular-ui/components/editor/api/EditorFontSizeComponent/#toc-valuechange) and [EditorFormatComponent](https://www.telerik.com/kendo-angular-ui/components/editor/api/EditorFormatComponent/#toc-events) should fire `(valueChange)` event when the user updates the value of the drop-down list but they don't.

**To Reproduce**
https://stackblitz.com/edit/angular-ey6165

**Expected behavior**
In the provided example when changing values in the dropdownlists, logs in the console should appear.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
