### ISSUE TITLE
[Grid] Column cell template with inner table not firing cellClick event

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2331]
**Describe the bug**
Having a column with cell template where html table is used. Also the grid handles cellClick event. In the cell with nested table the cellClick is not emitted.

**To Reproduce**
https://stackblitz.com/edit/angular-3ca7ek
1) click to first cell - cellClick is emitted
2) click to second cell with cell template containing table - cellClick is not emitted

**Expected behavior**
CellClick should be emitted.

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.80

**Comment by danielkaradachki** [comment]
Released in 4.1.0

https://stackblitz.com/edit/angular-kpewkj?file=app/app.component.ts
