### ISSUE TITLE
Grid norecord row is "squished"

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#2336]
**Describe the bug**
The "norecord" row is rendered with the width of the first grid column since 3.14.4 (which BTW is marked as dev but it is the latest version in NPM?!)

**To Reproduce**
https://stackblitz.com/edit/angular-4fua2j?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Tracking in https://github.com/telerik/kendo-themes/issues/781

The problem should be fixed in the latest dev version of the theme.

**Comment by joneff** [comment]
Using `https://unpkg.com/@progress/kendo-theme-default@dev/dist/all.css` for styles will resolve the issue.
