### ISSUE TITLE
[Editor] Disabling reactive form does not disable editor

### ISSUE THREAD

**Issue by AsifulNobel** [telerik/kendo-angular#2338]
**Describe the bug**
In angular, one can use reactive form with inputs to dynamically keep track of user input. By using reactive form controls, HTML input fields can also be disabled. But this is not working with Kendo Editor component. Even after disabling the form group or form control, editor is not disabled. 

**To Reproduce**
[This editable example](https://stackblitz.com/edit/angular-e8c7wy) can be used to reproduce this behavior. The button called click at the bottom of the page can be used to toggle the state of form group. The example is a fork of [reactive forms support example](https://www.telerik.com/kendo-angular-ui/components/editor/forms/#toc-reactive-forms).

**Expected behavior**
It is expected that after disabling the form control or group, the editor will also become disabled from receiving user input.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-editor`

**Comment by siyka-marinova** [comment]
Fix is now also available in the latest `kendo-angular-editor v1.0.0`
