### ISSUE TITLE
[Grid] activeCell/Row dataItem incorrect after data operations

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2339]
The dataItem, associated with the active cell/row in a navigable Grid is no longer correct after the Grid data is processed (e.g. - sorted) - the data item that was initially (correctly) associated with the active row remains the same in the activeCell object even after the data is sorted, and the data item, associated with the active row index is different:

[https://stackblitz.com/edit/angular-epmth2-azrvnr?file=app/app.component.ts](https://stackblitz.com/edit/angular-epmth2-azrvnr?file=app/app.component.ts)

1. Click on Anyseed Syrup // logs the correct item name
1. Sort the Grid
1. Click on in the third row again // still logs Anyseed Syrup

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://k2build.openstack.progress.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v4.0.0
