### ISSUE TITLE
Sortable="false" on grid column not working

### ISSUE THREAD

**Issue by sigVince** [telerik/kendo-angular#234]
See plunker : 
http://plnkr.co/edit/pxJZdaIwWdyq5SOIhBTl?p=preview

I want to enable sorting globally but to disable it on a few columns, but sortable="false" doesn't seem to have any effet.

API ref: http://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/#toc-sortable
supports boolean | ColumnSortSettings

Or am I missing something?

**Comment by rusev** [comment]
You should be using property binding `[sortable]="false"` instead. Otherwise the value set to the `sortable` property will be the string `"false"`.

Updated example - http://plnkr.co/edit/cu6f8SM7VERimJFhrkcz?p=preview

**Comment by sigVince** [comment]
Fuck me, was so obvious... Sorry for that.
