### ISSUE TITLE
Numeric text box

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#2340]
when focusing the box, the text inside it will be selected automatically, can it allow us not to select the text when focusing the box ?
do not select the text
![image](https://user-images.githubusercontent.com/34930870/59747299-30f5f880-92ab-11e9-812b-d14060498999.png)

instead
![image](https://user-images.githubusercontent.com/34930870/59747315-37847000-92ab-11e9-8c3f-4f65d4e54b24.png)

I think you can expose a property on kendo-combobox for user to decide it

**Comment by elena-gancheva** [comment]
Hi @jiangyh1024, the automatic selection on focus is our desired behavior. We will provide a "How to" topic which will demonstrate an option to remove the selection. Once published, i will update this issue.

**Comment by dtopalov** [comment]
We ended up deciding to provide the discussed functionality. It is available in the latest dev builds:

https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/

**Comment by siyka-marinova** [comment]
Now available also in the latest official `@progress/kendo-angular-inputs v6.3.0`
