### ISSUE TITLE
[Editor] OnPush ChangeDetectionStrategy does not change Format Dropdown

### ISSUE THREAD

**Issue by AsifulNobel** [telerik/kendo-angular#2341]
**Describe the bug**
While using the Editor component, if one changes the container component's ChangeDetectionStrategy to OnPush - **Format** dropdown does not update automatically anymore. Even if there is content inside the editor with multiple formats, placing cursor among the text will not update the Format dropdown. Although applying formatting on selected text does still work.

**To Reproduce**
StackBlitz link:
[https://stackblitz.com/edit/angular-6yngff](https://stackblitz.com/edit/angular-6yngff)

**Expected behavior**
It is expected that the dropdown will still update with OnPush change detection or emit events to manually detect changes.

**Comment by PetarMetodiev** [comment]
The reported issue is not reproducible with the latest Editor package versions. Please try updating the package and get back to us if the problem persists.
