### ISSUE TITLE
how to add the footer on all pdf pages

### ISSUE THREAD

**Issue by aravind-ui** [telerik/kendo-angular#2343]
Use this template for questions that are relevant to the community as a whole.

**If the issue is specific to your project, please open a [support ticket](https://www.telerik.com/account/support-tickets).**

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
