### ISSUE TITLE
Scheduler: Drag events into it

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#2344]
I believe the scheduler supports dragging existing events within it.

What if we want to drag unscheduled events into it?

Any advice on how this could be achieved?

**Comment by cheng93** [comment]
https://docs.telerik.com/kendo-ui/controls/scheduling/scheduler/how-to/interaction/drag_and_drop_grid_scheduler

This is similar to what I want to achieve

**Comment by tapopov** [comment]
The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
