### ISSUE TITLE
[Grid] Incorrect behavior when kendoGridGroupBinding is used

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2345]
When the kendoGridGroupBinding directive is used, the data is not grouped, the user scrolls down for the first time and reaches the first page change, the scroll position is moved up, and the items from a previous portion of the first page are displayed:

[https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-using-virtualization-with-grouping](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/#toc-using-virtualization-with-grouping)

[https://stackblitz.com/edit/angular-qtamea?file=app/app.component.ts](https://stackblitz.com/edit/angular-qtamea?file=app/app.component.ts)

To reproduce - scroll down to the ~80 item - the following portion of the data is displayed:

![image](https://user-images.githubusercontent.com/7533599/59848562-1e90c300-936e-11e9-8393-52daa0c33c1f.png)

Works as expected after scrolling up and down again.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-grid`

**Comment by Raisolution** [comment]
Available in `v4.7.1`
