### ISSUE TITLE
The Window demo example does not work on stackblitz 

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2347]
Seems not to be working in the sanbox.
https://www.telerik.com/kendo-angular-ui/components/dialogs/window/
in the given link I am trying to open into stackblitz. It gives me some weird errors in the browser console.

**Comment by tsvetomir** [comment]
We're in the process of updating the component packages as part of #2234. The error on StackBlitz is caused by the mix of incompatible versions.

It should clear out in few hours when we deploy the updated configuration.

**Comment by tsvetomir** [comment]
The problem should be solved now. You might need to clear the browser cache for the update to take effect immediately.

**Comment by destus90** [comment]
@tsvetomir 
it is working now. Thanks for reply.
