### ISSUE TITLE
Question, Chart-Donut label position

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#235]
Question,
Would is be possible to put a label in side the hole of the Donut, if so please assist by providing some examples. Thanks in advance.

eg,
![capture](https://cloud.githubusercontent.com/assets/22805288/22321617/3755144e-e3d1-11e6-990e-c62415349ed9.PNG)

**Comment by surajborra** [comment]
hi I have a same issue implementing the label inside and on the Donut as well. If you have found any solution for that please post some examples

**Comment by tsvetomir** [comment]
One way to get around this is to use CSS.

The Chart-specific solution would be to use the [Drawing package](http://www.telerik.com/kendo-angular-ui/components/drawing/) to pain on the chart drawing surface. I've prepared [a plunkr](http://plnkr.co/edit/Lyp2NYhr7LJH7l2kU83J?p=preview) to demonstrate. The main logic is in the onRender method:

```ts
public onRender(e: RenderEvent): void {
  // The center and radius are populated by now.
  // We can ask a circle geometry to calculate the bounding rectangle for us.
  //
  // http://www.telerik.com/kendo-angular-ui/components/drawing/api/geometry/Circle/
  var circleGeometry = new CircleGeometry(this.center, this.radius);
  var bbox = circleGeometry.bbox();

  // Render the text
  //
  // http://www.telerik.com/kendo-angular-ui/components/drawing/api/Text/
  var text = new Text("Foo & Bar", [0, 0], {
    font: "18px Verdana,Arial,sans-serif"
  });

  // Align the text in the bounding box
  //
  // http://www.telerik.com/kendo-angular-ui/components/drawing/api/align/
  // http://www.telerik.com/kendo-angular-ui/components/drawing/api/vAlign/
  align([text], bbox, "center");
  vAlign([text], bbox, "center");

  // Draw it on the Chart drawing surface
  //
  // http://www.telerik.com/kendo-angular-ui/components/charts/api/ChartComponent/#toc-surface
  e.sender.surface.draw(text);
}
```

This will get to the official documentation as well.

**Comment by tsvetomir** [comment]
We've added a new "donut center" template that is much easier to use.

```html
    <kendo-chart style="height: 450px;">
      <ng-template kendoChartDonutCenterTemplate>
        <h3>8%</h3>
        completion
      </ng-template>
      ...
```

See the [Displaying Information in the Center
](http://www.telerik.com/kendo-angular-ui/components/charts/series-types/donut/#toc-displaying-information-in-the-center) for details.
