### ISSUE TITLE
Roadmap needs update

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#2352]
[Roadmap](https://www.telerik.com/kendo-angular-ui/roadmap/) really needs update. It's more then a month since Q2 release.

**Comment by tsvetomir** [comment]
Thanks for noticing - updated!

**Comment by MaklaCof** [comment]
I hope some of the "bigger" component will see the world in release after October:
- spreadsheet
- pivot grid
- tree list
- diagram

Can you share some details about that: "Additional tools and features for the Editor".
[Image browser](https://demos.telerik.com/kendo-ui/editor/imagebrowser) perhaps? I don't want to start writing my own if it will be implemented in October.

**Comment by tsvetomir** [comment]
The [TreeList component](https://feedback.telerik.com/kendo-angular-ui/1360533-treelist-component) is high on the list and will likely make it's way into the roadmap. Please, cast your vote for the rest of the components so we can gauge the overall interest and prioritize accordingly.

An image browser for the Editor is not on our immediate plans, but it's an important feature and we're actively [collecting feedback](https://feedback.telerik.com/kendo-angular-ui/1383474-image-toolbar-for-editor-component). Do you consider a REST API, compatible with the one used for the jQuery Editor, sufficient for your needs?

/cc @valchev @Raisolution @bergenhem

**Comment by bergenhem** [comment]
Just to add in some additional notes here beyond what @tsvetomir brought up.

All of the mentioned components are certainly candidates to be included within the Angular components, but these are also all components that take quite some time to build out (similar to the Grid or Scheduler). While an original draft of the new roadmap page included a mention of these components we also realized that, just like the TreeList and Editor in earlier roadmaps, many users would expect those to be targeted in the immediate next couple of months, which is unfortunately not possible. So, to avoid confusion we limited the scope a little bit while still trying to provide some insight in to one of these larger components most likely to be targeted next.

Beyond the items mentioned here, if there are other components or features that you would like to see we certainly recommend working [within our feedback portal](https://feedback.telerik.com/kendo-angular-ui) to cast your vote, but as you've noticed we also try to pay attention to these issues and provide more insight where we can.

**Comment by MaklaCof** [comment]
Thank you both. 

@tsvetomir Yes that would be exactly what I need. Probably others too. You provide GUI and I will provide API-s.
If I may, I would suggest something like this:
- API for listing content must be set on editor component (it returns file type, file size, file name)
- API for uploading must be set on editor component
- API for renaming/deleting file must be set on editor component
- API for creating/deleting/renaming folder must be set on editor component
All APIs must have an callback with request to assign additional data, or at least option to set access token in authorization (Bearer) header.

I think I can build my own with [custom tools](https://www.telerik.com/kendo-angular-ui-develop/components/editor/tools/#toc-custom-tools) if this is definitely not coming on October release.

One more thing @tsvetomir Can my [post](https://feedback.telerik.com/kendo-angular-ui/1383474-image-toolbar-for-editor-component), that you mentioned, be renamed from `Image Toolbar...` to `ImageBrowser...`, since image toolbar is already implemented, but browser is not. Or feedback should be closed and I can open a new one.

**Comment by tsvetomir** [comment]
Thanks for the feedback @MaklaCof! I've renamed the feedback item to "Image Browser for Editor component".
