### ISSUE TITLE
Grid empty message not visible

### ISSUE THREAD

**Issue by Felx-B** [telerik/kendo-angular#2353]
**Describe the bug**
The empty grid message is not visible if first column has a small width

**To Reproduce**
https://stackblitz.com/edit/kendo-angular-grid-width

**Expected behavior**
The empty grid message should take all grid width 

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version 76

**Comment by danielkaradachki** [comment]
Fixed in the latest dev version of the theme:

https://stackblitz.com/edit/kendo-angular-grid-width-c8sj3r?file=index.html

Tracking in https://github.com/telerik/kendo-themes/issues/781
