### ISSUE TITLE
kendo-grid [pageSizes] assign object instead of number array

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2358]
I am trying to use 
import { Component } from '@angular/core';
import { products } from './products';
import { GridDataResult, PageChangeEvent } from '@progress/kendo-angular-grid';

@Component({
  selector: 'my-app',
  template: `
      <kendo-grid
          [kendoGridBinding]="data"
          [pageSize]="pageSize"
          [skip]="skip"
          [pageable]="true"
          [height]="200"
          (pageChange)="onPageChange($event)"
        >
         <kendo-grid-column field="ProductID" title="ID" width="40">
         </kendo-grid-column>
         <kendo-grid-column field="ProductName" title="Name" width="250">
         </kendo-grid-column>
         <kendo-grid-column field="UnitPrice" title="Price" width="80" format="{0:c}">
         </kendo-grid-column>

         <ng-template kendoPagerTemplate let-totalPages="totalPages" let-currentPage="currentPage">
            <kendo-pager-prev-buttons></kendo-pager-prev-buttons>
            <kendo-slider
                [showButtons]="false"
                [tickPlacement]="'none'"
                [max]="totalPages"
                [min]="1"
                (valueChange)="sliderChange($event)"
                [value]="currentPage">
            </kendo-slider>
            <kendo-pager-info></kendo-pager-info>
            <kendo-pager-next-buttons></kendo-pager-next-buttons>
            <kendo-pager-page-sizes [pageSizes]="[
      {text: 'Five', value: 5},
      {text: 'Ten', value: 10},
      {text: 'All', value: data.length}]"></kendo-pager-page-sizes>
         </ng-template>
      </kendo-grid>
  `
})
export class AppComponent {
    public data: any[] = products;
    public pageSize = 10;
    public skip = 0;
    public pageSizes : Array<{text: string, value: number}>;
    public sliderChange(pageIndex: number): void {
        this.skip = (pageIndex - 1) * this.pageSize;
    }

    public onPageChange(state: any): void {
        this.pageSize = state.take;
    }
}

in kendo-grid. and passing array of objects. instead of array of number as it expects to receive. 
and now dropdown for items per page shows NaN and [object Object] instead of expected dropdown.  Generated output->
<kendo-pager-page-sizes ng-reflect-page-sizes="[object Object],[object Object" class="k-pager-sizes k-label">
        <select aria-label="items per page">
            <option value="NaN">NaN</option>
            <option value="[object Object]">
                [object Object]
            </option><option value="[object Object]">
                [object Object]
            </option><option value="[object Object]">
                [object Object]
            </option>
        </select>
        items per page
    </kendo-pager-page-sizes>

so, is there any way where object can be passed. as support for 'all' happens to be implemented for kendo jquery but not in Angular(at least i have not found it.)
Please can you help or guide me on this. Thanks.

**Comment by danielkaradachki** [comment]
You could use any element in the template:

https://stackblitz.com/edit/angular-sflcej?file=app/app.component.ts

We will consider adding built-in support for defining the text for future versions.

**Comment by siyka-marinova** [comment]
This functionality is available in `kendo-angular-grid v4.5.0`
