### ISSUE TITLE
Merge Dialog and Window

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#2359]
Could you please merge dialog and window to be just 'dialog', and can be dragged. 
use a [Modal] property (true or false) to decide if there is a overlay mask

just like https://www.primefaces.org/primeng/#/dialog does

**Comment by Raisolution** [comment]
Hi @jiangyh1024,

We don't have plans to merge the two components. In order to add modality to the Window component, you could use the approach demonstrated in the following [How To example](https://www.telerik.com/kendo-angular-ui/components/dialogs/window/how-to/add-modality-to-window/).
