### ISSUE TITLE
The Calendar does not scroll to the correct view in Internet Explorer 11.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-angular#236]
The Calendar does not scroll to the correct view in Internet Explorer 11.

The issue can be reproduced on our demo page: http://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/

If the user scrolls down, the Calendar goes to the year 1900.

In the ticket: 1086282 there is a video demonstrating how the Calendar jumps to the year 2099 when scrolled up.

**Comment by billyjacobs2014** [comment]
Just checking on the status of this bug or whether there is a work around? Thanks.

**Comment by ggkrustev** [comment]
We'll research the case more thoroughly next week. Once we have more details about the issue, we will update the thread.

**Comment by billyjacobs2014** [comment]
What is the priority on this. Should I switch calendar controls for now?

**Comment by ggkrustev** [comment]
@billyjacobs2014, this is a known issue which is already addressed in `@progress/kendo-angular-date-inputs package@0.2.0`. The site is still not updated, but will be soon.

As to the IE11, we are working on the issue and will update the thread once we have more details about the case.

**Comment by billyjacobs2014** [comment]
Any update? I have a  code freeze tomorrow morning?

**Comment by ggkrustev** [comment]
The next release of the package, `kendo-angular-dateinputs@0.3.0`, will include the required fix. You can try it once it is released (Travis CI is still running).
