### ISSUE TITLE
'No Records Available' Message not display properly

### ISSUE THREAD

**Issue by DnyaneshBaravkar** [telerik/kendo-angular#2360]
When grid was empty the **no records found** text not display properly, its look like below image.

**Browser**
Google Chrome

![image](https://user-images.githubusercontent.com/44089859/60329153-68505d80-99ad-11e9-9072-4fcba68e38ba.png)

**Comment by dimitar-pechev** [comment]
@DnyaneshBaravkar, this problem is related to the themes ([#781](https://github.com/telerik/kendo-themes/issues/781)).

The fix is already included in the latest dev version of the default theme - `@progress/kendo-theme-default@dev`.
