### ISSUE TITLE
[Grid] The horizontal scrollbar disappears

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2363]
**Describe the bug**
When changing the height of the Grid on window.resize event the horizontal scrollbar disappears. The undesired behavior occurs only in Google Chrome. 

**To Reproduce**
https://stackblitz.com/edit/angular-bx2s53-fskqxh?file=app/app.component.ts

1. Resize the browser window by clicking the "Restore Down" button.
2. Resize the browser window by clicking the "Maximize" button.
3. The horizontal scrollbar of the Grid is missing.
![image](https://user-images.githubusercontent.com/20015190/60505627-c9897100-9ccc-11e9-9e58-e915d04dca44.png)

**Comment by liuydyyy** [comment]
have u solve this problem,through my test,it appears while use chrome 70&75,but it is ok while use chrome 60

**Comment by Raisolution** [comment]
The issue is no longer reproducible with kendo-angular-grid `v5.4.0` and latest Chrome.
