### ISSUE TITLE
[kendo-scheduler] change month in Kendo Scheduler in kendo-scheduler-timeline-month-view

### ISSUE THREAD

**Issue by vahidsamimi** [telerik/kendo-angular#2366]
**Describe the bug**
Hi, 
when I change the month in Kendo-schedular  in kendo-scheduler-timeline-month-view, this error appears:
`Cannot read property 'slots' of undefined.
`
here is an example in StackBlitz ;
https://stackblitz.com/edit/angular-mwuxz2

as an example in this code when you change the month (first next month, then previous month) you get the error.

**Comment by vahidsamimi** [comment]
no any idea?

**Comment by danielkaradachki** [comment]
It's a bug that should be fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/) version:

https://stackblitz.com/edit/angular-dadf7x?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Fix released in 0.15.0

https://stackblitz.com/edit/angular-pr5pkf?file=app/app.component.ts
