### ISSUE TITLE
[Scheduler] Agenda view with no items not showing whole views dropdown

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#2367]
**Describe the bug**
If showing dropdown list for view selection instead of buttons and agenda view has no items, the dropdown options are partially hidden.

**To Reproduce**
1) https://stackblitz.com/edit/angular-hx3k8q
2) reduce width of browser, so views dropdown list is displayed instead of buttons:
![image](https://user-images.githubusercontent.com/39991506/60667110-ff635c80-9e68-11e9-931b-e9a2fe7e1537.png)
3) open dropdown options
![image](https://user-images.githubusercontent.com/39991506/60667157-1bff9480-9e69-11e9-911f-ce92f116275e.png)
Check the dropdown options Month, Timeline and Agenda.

**Expected behavior**
All dropdown options should be visible.

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.100

**Comment by kunajs** [comment]
what is the status of this issue, please?

**Comment by BTEric** [comment]
Also concerned with this issue, its present in the material theme too!

**Comment by danielkaradachki** [comment]
We haven't had the time to work on this issue yet. A possible workaround for the moment is to override the scheduler overflow style:

https://stackblitz.com/edit/angular-hx3k8q-jrpm7w?file=index.html

**Comment by svetq** [comment]
Closing this as it is no longer reproducible: https://www.telerik.com/kendo-angular-ui/components/scheduler/
