### ISSUE TITLE
When set grid row filter operator are (Is Null, Is Not Null, Is Empty, Is Not Empty) the input is shown

### ISSUE THREAD

**Issue by mariyaBilykJSP** [telerik/kendo-angular#2368]
When setting grid row filter operator is (Is Null, Is Not Null, Is Empty, Is Not Empty) the unnecessary input is shown.

**To Reproduce**
1. Implement FIlter menu or in-cell filter with next operations allowed: (Is Null, Is Not Null, Is Empty, Is Not Empty).
2. Open filter (if it is a filter menu).
3. Select one of the mentioned options from operations dropdown.
4. The input is visible.

**Expected behaviour**
The input is supposed to be hidden if any of the next operators (Is Null, Is Not Null, Is Empty, Is Not Empty) is selected. It's unnecessarily to provide a filter keyword for these operators.

**Screenshots**
![image](https://user-images.githubusercontent.com/52541010/60676796-778d4a80-9e88-11e9-87b2-ee8f0cddbb9d.png)

**Browser**
 - OS: Windows
 - Chrome

**Comment by siyka-marinova** [comment]
Fix is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `@progress/kendo-angular-grid` package

**Comment by molequetu** [comment]
Can you port this fix to kendo-ui core  / kendo ui aspnet mvc;
