### ISSUE TITLE
[ColorPicker] popup should support multiple views.

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2369]
The ColorPicker [[view]](https://www.telerik.com/kendo-angular-ui/components/inputs/api/ColorPickerComponent/#toc-view) option allows us to set one [ColorPickerView](https://www.telerik.com/kendo-angular-ui/components/inputs/api/ColorPickerView/) only ('palette' or 'gradient'). Provide an option to set multiple views ('gradient' and 'palette'): 

![screenshot](https://user-images.githubusercontent.com/33104481/60710361-3003ce80-9f1b-11e9-8d49-e3a09e768293.png)

**Based on a private support thread - Ticket ID: 1416976**

**Comment by elena-gancheva** [comment]
The feature is available in the latest version of the package.
