### ISSUE TITLE
Window dragging over iFrame

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#2370]
**Describe the bug**

When dragging a window over an iframe, the window stops moving before the dragging ends.

**To Reproduce**

Here is a minimal demo of the problem:
https://stackblitz.com/edit/angular-window-iframe?file=app/app.component.ts

 * Drag the window over the iframe (a little bit faster) down and then up.
* The window stops dragging after changing the direction from down to up.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75

**Additional context**

Is it possible to solve that issue, or is that an iframe problem, that can't be fix?

**Comment by Raisolution** [comment]
This is a limitation related to the ability to detect mouse movement over iframes. As a workaround the developer could apply the `pointer-events: none` CSS attribute to the iframe while the Window is dragged.

The following events of the Window component could be used for applying the custom logic:

https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowComponent/#toc-dragstart

https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowComponent/#toc-dragend
