### ISSUE TITLE
Merge request - dialog width (feature request)

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#2371]
I would like to see support for (at least) width defined in % in dialog component. 
I added [feature request](https://feedback.telerik.com/kendo-angular-ui/1363507-support-em-and-for-kendo-dialog-width-height), but apparently there is no big interest in this.

Since this feature would need 2-3 lines code changes I would like to add it myself. It would be nice, if users that has access to source code could submit merge request. Is this possible?

This feature would need to changes in `dialog.component.ts`:
```
//@Input() public width: number;              //OUT
@Input() public width: number | string;     //IN

  public get styles(): any {
    const styles: any = {};

    if (this.width) {
//      styles.width = this.width + 'px';              //OUT
         styles.width = this.width + (typeof styles.width === "number" ? 'px' : '');    //IN
    }

    if (this.height) {
      styles.height = this.height + 'px';
    }

    if (this.minWidth) {
      styles.minWidth = this.minWidth + 'px';
    }

    return styles;
  }
```
That's it. In some scenarios user could help you expand kendo functionality. I bet there are users who would like to contribute. If you wish, you could award them with Telerik points.  

This could work something like that:
- User propose merge request and describe how it would do it.
- Kendo team approve (or denied) idea.
- User create merge request
- Kendo team confirm and merge code into master.

I don't think it is necessary to say that user contributions work, but I will say it anyway:
This could work. GitHub projects are full of contributors:
- Angular source code almost 1000
- One of my favourites where this really works:  [Entity framework Core](https://github.com/aspnet/EntityFrameworkCore) - 150 contributors

**Comment by Raisolution** [comment]
The feature is available in `v4.1.0-dev.201907230807` and will soon be released in the next official version too.
