### ISSUE TITLE
ContextMenu renders icons if icon property is in data even if custom item template is used

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#2373]
**Describe the bug**
I am using custom item template, because I want to display some font-awesome 5 icons, and some custom template...
Problem is that even if I write custom item template, icons are still rendered.

**To Reproduce**
[StackBlitz](https://stackblitz.com/edit/angular-gnmw1n?file=app/files.ts).

**Expected behavior**
If `kendoMenuItemTemplate` is used, there shouldn't be any content (like icons).

**Screenshots**
![image](https://user-images.githubusercontent.com/1589573/60756355-c2c86a00-9ffc-11e9-93b0-61afbc1c5886.png)

**Comment by danielkaradachki** [comment]
The item template overrides only the default text. You can use [link template](https://www.telerik.com/kendo-angular-ui/components/menus/menu/templates/#toc-link-template) to also override the icon.
