### ISSUE TITLE
Question: Dynamically customize grid columns template

### ISSUE THREAD

**Issue by ronyf** [telerik/kendo-angular#2374]
Hi,

How can I pass the template that will be used for columns dynamically from the angular code?
I didn't find any examples for that.. In all of the examples, the template is defined inside the grid definition.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
