### ISSUE TITLE
Grid: Paging doesn't work properly

### ISSUE THREAD

**Issue by okinookino** [telerik/kendo-angular#2378]
**Describe the bug**
Component: grid
config: [navigatable]="true"
When value of [pageSize] and number of display grid rows are the same, press "PageDown" key on the grid. Then, it brings next grid page with no data.

**To Reproduce**
Press "PageDown" key on the grid.
Then, it shows empty grid page.
[StackBlitz](https://stackblitz.com/edit/angular-kjebv4)

**Expected behavior**
There should not be next page.

**Browser**
  - OS:Windows7
  - Browser :Chrome
  - Version :75.0.3770.100

**Comment by okinookino** [comment]
in the case url above is not the correct url...
[stackblitz](https://angular-kjebv4.stackblitz.io/)

**Comment by ipeshev** [comment]
@okinookino thank you for the bug report, we will investigate it further !

**Comment by Raisolution** [comment]
Fixed in `v4.8.3` of the `kendo-angular-grid` package.
