### ISSUE TITLE
Dialog : Big content / Classname

### ISSUE THREAD

**Issue by nlgi** [telerik/kendo-angular#238]
1- Big content
Dialog is growing without a "window max-height" and scroll on content : 
[http://plnkr.co/edit/IGeW2VNMn08AlrizZKNz?p=preview](url)

2- Class
I tried to add a classname to work around this issue : Cannot set a class on kendo-dialog component

Many thanks,

**Comment by gyoshev** [comment]
@nlgi the issue with the dialog going outside the viewport bounds has been fixed in version 2.11.13 of the kendo-theme-default package. As for adding classes to the kendo-dialog element, this was already fixed in version 0.14.1.

**Comment by nlgi** [comment]
Coooool
Many thanks
