### ISSUE TITLE
Accessing child grids from different components in Master to use multiple grid print functionality 

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2380]
As in the demo https://www.telerik.com/kendo-angular-ui/components/grid/export/pdf-export/#toc-exporting-multiple-grids-to-the-same-pdf
Everything works perfectly. but if grids are in separate components (suppose 5-6 separate grids in separate component), and in the parent component if we have a print button. (suppose on a master page). Do we have any example to achieve this? As currently I get blank pdf. The same example if I have on my master with the same demo it works.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
