### ISSUE TITLE
[AutoComplete] The Popup is misaligned in RTL mode when set custom width

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2381]
**Describe the bug**
When using the AutoComplete in RTL mode and set a custom width of the Popup through the popupSettings, then the position of the Popup is misaligned.

**To Reproduce**
Check the following example:
https://stackblitz.com/edit/angular-cuwubk-8sopxy?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
The fix is included in **v4.2.0**.
