### ISSUE TITLE
Popup stays open when toolbar is destroyed

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2382]
**Describe the bug**
Toolbar popup stays open when toolbar component disappears on template change.

**To Reproduce**
1.Open this demo [https://stackblitz.com/edit/angular-yhlqrr?file=app/app.component.ts](https://stackblitz.com/edit/angular-yhlqrr?file=app/app.component.ts)
2.Click on the three dots
3.Click Reset button.

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by siyka-marinova** [comment]
Fix is available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by siyka-marinova** [comment]
Fix is now available in the official package `kendo-angular-toolbar v2.2.1`
