### ISSUE TITLE
Sortable item flickers when only clicked

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2384]
**Describe the bug**
Sortable item flickers when only clicked on Chrome 75 on Windows and has title attribute !

**To Reproduce**
1.Open this [demo](https://stackblitz.com/edit/angular-dodmlx-n3xukh).
2.Click on some of sortable items.

**Expected behavior**
It is expected not to flicker !

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 75

**Comment by JoomFX** [comment]
No longer reproducible.
