### ISSUE TITLE
[multiselect] Splicing the ngModel doesn't update the dropdown selection

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#2385]
**Describe the bug**
When you splice the array of the ngModel used in the multiSelect, the items are still considered "selected" by the component, even if not in the model anymore.

**To Reproduce**

https://angular-ctf4pv.stackblitz.io

1- Click on the button
2- Click on the multiselect, medium is still selected,
3- To re add medium, you need to click it twice.

**Expected behavior**
The popup should be updated with the model.

**Screenshots**
https://i.imgur.com/f8BuUk9.png

**Browser**
 - windows 10
 - Chrome

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released in **v4.4.0.**
