### ISSUE TITLE
Enter key to fire filter event in Kendo angular UI grid

### ISSUE THREAD

**Issue by unosbaghaie** [telerik/kendo-angular#2386]
How can I use enter key to fire filter event in Kendo angular UI grid? 
Currently it fires after stopping typeing but I want to fire it by Enter key.

Thanks

**Comment by tapopov** [comment]
The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
