### ISSUE TITLE
Popup wrong position in container with perspective style.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2388]
**Describe the bug**
Grid ContextMenu is misaligned when grid is in div with perspective style

**To Reproduce**
1.Open this [stackblitz sample](https://stackblitz.com/edit/angular-8l59mu-od3u2g).
2. Try to right click on a cell

**Expected behavior**
It should not show misaligned context menu !

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Comment by stnikolova** [comment]
Positioning of elements when `perspective` is applied is handled by the browser and the same misalignment behavior is observed for native HTML elements as demonstrated in [this example](https://stackblitz.com/edit/angular-xwnoyz?file=src%2Fapp%2Fapp.component.ts). A workaround is to enable hardware acceleration by adding `transform: translate(0);` to the element with applied perspective.
