### ISSUE TITLE
DateRange component not responsive

### ISSUE THREAD

**Issue by AE1NS** [telerik/kendo-angular#2389]
The DateRange component is not responsive.
https://www.telerik.com/kendo-angular-ui/components/dateinputs/daterange/
https://equj3h.run.stackblitz.io
Shrink down the browser and open the picker => the sides are cut off.

The jQuery version is working great and breaks down to 1 column.
https://demos.telerik.com/kendo-ui/daterangepicker/index

**Comment by kunajs** [comment]
Hi,
any news on this?

**Comment by dimitar-pechev** [comment]
@kunajs, no solution is available out-of-the-box yet.

As a workaround, you can set the the number of `views` of the popup calendar to 1 when the screen resolution is lower than the popup width on popup open. [Here's an example](https://stackblitz.com/edit/angular-y54qbx).

**Comment by stnikolova** [comment]
Adaptive mode of all date pickers is available since v11.4.0 of @progress/kendo-angular-dateinputs. More details can be found in the following documentation article: https://www.telerik.com/kendo-angular-ui/components/dateinputs/daterange/adaptive/
