### ISSUE TITLE
MultiSelect - Two-way Binding in Setter variable already has new value

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#239]
If you setup the property the MultiSelect's [(ngModel)] directive is binded two as a getter/setter, in the setter method the private variable you use to store the variable always already has the new value. I've tested this with a basic input and with your DropDownList and they work correctly. Just the MultiSelect has this weird issue. Below is a screen shot of runtime values when debug is stopped inside the setter.

![image](https://cloud.githubusercontent.com/assets/671093/22388139/06410d04-e4ad-11e6-80ce-239e2631a6cc.png)

**Comment by KirilNN** [comment]
Would it be possible to provide a plunkr where the problem can be reproduced, so we can see the setup and problematic behavior? Thanks

**Comment by djarekg** [comment]
Here is a plunker example.

http://plnkr.co/edit/dfxhEaCZoTLLGssWSsT3?p=preview

**Comment by djarekg** [comment]
If you remove "this._value = e" from the setter, strangely the private variable _value gets updated some how.

i.e.

`public get value(): any { return this._value; }
    public set value(e: any) {
      alert('_value = ' + this._value + '     e = ' + e);
    }`

**Comment by rusev** [comment]
@djarekg I suspect that the behavior is due to the fact that array is used by reference. `[(ngModel)]`  effectively assigns the same array reference from `_value` field to the MultiSelect `value` property.

Do you think we should change this behavior and make the MultiSelect component producing new array instance on every change?

**Comment by djarekg** [comment]
If you do the same concept with your DropDownList component it works as its supposed to. Why is the multiselect any different?

**Comment by djarekg** [comment]
It also works as expected on a simple input (text). Angular's documentation also mentions this way of doing things. Sounds to me like there is an issue with how the MultiSelect implements binding.

https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-to-child-setter

**Comment by djarekg** [comment]
@rusev I think i understand what you are saying now. So, yes I think you should just pass a copy of the array to the setter... i.e. value.slice(0)

**Comment by KirilNN** [comment]
In the `v0.27.1` version of the package the value will be a new instance of the array every time it is changed.

**Comment by djarekg** [comment]
Thank you for your help with this issue.
