### ISSUE TITLE
dropdownlist's selected long word got truncated 

### ISSUE THREAD

**Issue by zzs1020** [telerik/kendo-angular#2390]
**Describe the bug**
when you select a long word from dropdownlist, this word looks like get truncated becasue background color doesn't apply to overflow text. Text looks fine if don't select it.

Please provide a simple solution just for now if possible, thanks

**To Reproduce**
just use your official website example, and give a long word option to dropdownlist component, and select it, then open dropdown and scroll to the right to see.

long word should be something like asdfasdfasdfasdfasasdfasdfsdfasdfasdfgdfg (no '-' or ' ' to break it)

**Expected behavior**
background color should apply to the whole word.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23032993/61297984-6bb85700-a7ab-11e9-9a12-d33e74c4d0a4.JPG)

**Browser**
 - OS: win8
 - Browser Chrome
 - Version latest

**Additional context**
no

**Comment by ipeshev** [comment]
@zzs1020 this is [known issue](https://github.com/telerik/kendo-angular/issues/2136) in @progress/kendo-themes repo

**Comment by ipeshev** [comment]
Please use [this workaround](https://stackblitz.com/edit/angular-fv5vxi?file=app/app.component.ts) for now .

**Comment by dimitar-pechev** [comment]
Closing in favor of https://github.com/telerik/kendo-angular/issues/2136.
