### ISSUE TITLE
Line / Scatter Chart: Zoom raises error for negative values and labels.position = start 

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#2391]
**Describe the bug**
An error 'Cannot set property 'min' of undefined' is raised when the chart is configured to set the labels.position to start and the chart displays negative values, when the chart getting zoomed.

**To Reproduce**
Try this https://stackblitz.com/edit/angular-zoom-bug StackBlitz.
Open the chart and zoom (shift + mouse) and the error appears.

**Expected behavior**
Zoom should work with neg. values.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.142

**Comment by antonin123** [comment]
save issue

**Comment by danielkaradachki** [comment]
Fix released in 4.0.1

https://stackblitz.com/edit/angular-hqfxnk?file=app/app.component.ts
