### ISSUE TITLE
[Scheduler] Provide a way to customize the inputs within the RecurrenceEditorComponent 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2392]
Within the following example:
https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/custom-reactive-editing/

we should be able to apply different options to the inputs of the [RecurrenceEditorComponent](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/RecurrenceEditorComponent/). For example, we should be able to set a custom format for the following DatePicker:
![image](https://user-images.githubusercontent.com/20015190/61373520-b7016100-a8a2-11e9-84f1-5da1e35abb47.png)

@Raisolution @tsvetomir

**Comment by siyka-marinova** [comment]
This functionality is available in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-scheduler`.

**Comment by tsvetomir** [comment]
See the [RecurrenceEditorComponent](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/RecurrenceEditorComponent/#toc-inputs) API reference for a list of the available options.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-scheduler v.1.2.0`
