### ISSUE TITLE
[Excel Export] The names of the sheets of a new WorkBook should allow spaces

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2395]
**Describe the bug**
When creating a new WorkBook which sheet name contains spaces (for example: "Customers a b c d"), the created file will through a warning message upon opening it in Excel. 

**To Reproduce**
Check the following example:
https://stackblitz.com/edit/angular-kvtce7-696hen?file=app/app.component.ts

1. Export the file
2. Open the exported file in Excel

**Comment by thinw002** [comment]
To further clarify:

- A single space will not trigger bug
- Bug only triggered in combination with setting a range

Kendo defines the filter in the exported spreadsheet as follows:
`<definedName name="_xlnm._FilterDatabase" hidden="1" localSheetId="0">Customers a b c d!$A$1:$B$1</definedName>`

However, when filtering worksheets with complex sheet names Microsoft Excel quotes the sheet name as follows:
`<definedName name="_xlnm._FilterDatabase" localSheetId="0" hidden="1">'Customers a b c d'!$A$1:$B$1</definedName>`

**Comment by danielkaradachki** [comment]
Fix released in 3.0.1

https://stackblitz.com/edit/angular-t136se?file=app/app.component.ts
