### ISSUE TITLE
how to display total number of records based on external search in kendo grid in angular without pagination

### ISSUE THREAD

**Issue by UshaAiluri** [telerik/kendo-angular#2396]
Use this template for questions that are relevant to the community as a whole.

**If the issue is specific to your project, please open a [support ticket](https://www.telerik.com/account/support-tickets).**

**Comment by tapopov** [comment]
The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
