### ISSUE TITLE
[Grid] ExpressionChangedAfterItHasBeenCheckedError when master row is expanded and no pageSize is set

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2397]
An ExpressionChangedAfterItHasBeenCheckedError is thrown when a master Grid row is expanded, and there is no pageSize set. No error is observed when pageSize is set even if the Grid is not pageable:

https://stackblitz.com/edit/angular-kavcuq-qhtxkz?file=app/app.component.ts // error

https://stackblitz.com/edit/angular-kavcuq-3t1enu?file=app/app.component.ts // no error

**Comment by danielkaradachki** [comment]
Released in 4.1.0

https://stackblitz.com/edit/angular-hcvqel?file=app/app.component.ts
