### ISSUE TITLE
[DropDownList] A "readonly" component allows changing the value via the keyboard 

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2398]
When the `readonly` option is set to `true` the user is still able to change the value of the focused component by typing the first letter of an existing list option:

https://stackblitz.com/edit/angular-47brwa-plchkd?file=app/app.component.ts

1. Focus the component
2. Type "x" (for example)

**Comment by valchev** [comment]
The same problem occurs with disabled items. Can be reproduced in this demo:

https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/disabled-items/

1. Focus the component (don't open it)
2. Type "i" until you reach "Item 3" which is disabled.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
Both fixes are available in **v4.2.0**.
