### ISSUE TITLE
Kendo GRIDVIEW scrolling issue

### ISSUE THREAD

**Issue by oleksandrmelnychenko** [telerik/kendo-angular#240]
When i use 'virtual' scroll mode and scroll down near 100 elements ( doesn't meter ), after i change the DataSource for example  20 elements, The grid doesn't scroll to the TOP i have white screen, In css it's controlled by "table ng-reflect-ng-style="[object Object]" style="transform: translateY(0px);".

But via javascript if i set 0px and recalculate height it doesn't help. So any ideas how to scroll to the top automatically ?

**Comment by rkonstantinov** [comment]
Could you please elaborate a bit more on how to recreate this behavior locally.
Take a look at the the following plunkr http://plnkr.co/edit/PkymhkyVYmdrwi6oICzx?p=preview, maybe I'm missing something obvious.

**Comment by oleksandrmelnychenko** [comment]
Hi, 
Thanks for your response, I'm using complicated scenarios with Filtering, Sorting and GET. 
In your link, rebinding reduce the data, but scroll bar in the bottom, it should be on top, not bottom.
In my cases, i have white screen need to do scroll up and after data shows up. But it's not a correct behavior.
I did some 'stupid scenarios'  like:

 const gridContent = document.getElementsByClassName('k-grid-content k-virtual-content')[0];
  gridContent.scrollTop = 0;
              
 let table = gridContent.children[0];
 <any>table).style.transform = 'translateY(0px)';

But also in some cases it helps, but it's not a programming style
