### ISSUE TITLE
Tooltip RTL support

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-angular#2400]
The current implementation of the Tooltip has a partial support for the `RTL` mode.

It has to provide all the styles needed for `RTL` and a direction `class`/`attribute` in its rendering, depending on whether the user provided RTL or not.

**Comment by elena-gancheva** [comment]
Available in the latest `dev` channel version of the package.

**Comment by Raisolution** [comment]
Released in `v2.1.0`
