### ISSUE TITLE
[ComboBox] when filtering, the focused item is inconsistent

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2401]
**Describe the bug**

When filtering the ComboBox, the first item should be always focused. Currently the focused item is any. 

**To Reproduce**
Check the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/filtering/

1. Enter "m" in the ComboBox and observe the focused item:
2. Enter "a" in the ComboBox and observe the focused item:

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dropdowns`

**Comment by dimitar-pechev** [comment]
Released in **v4.2.4**.
