### ISSUE TITLE
Dialog Service does not use the close event with escape key

### ISSUE THREAD

**Issue by jamierytlewski** [telerik/kendo-angular#2402]
**Describe the bug**
When using the Dialog Service and using the escape key, it does not use 
**To Reproduce**

https://stackblitz.com/edit/angular-bhjidu?file=app/user-info.component.ts

When you hit the escape key, which closes the window, the close event is not run. This works when the Dialog is not used as a service.

1. Click on User Form
2. Hit the escape key
3. Notice the console does not show 'here'

**Expected behavior**
I expect that when then escape key is hit, that the close event is run. 

**Browser**
Doesn't matter

**Comment by svetq** [comment]
The close event can be further updated to provide the initial KeyboardEvent/MouseEvent that triggered the close of the Dialog. That will help to differentiate how the Dialog is closed.

**Comment by dtopalov** [comment]
@jamierytlewski the `TitleBarComponent`'s `close` event is fired when the end user clicks the close button:

https://www.telerik.com/kendo-angular-ui/components/dialogs/api/DialogTitleBarComponent/#toc-close

When the Dialog is closed by pressing the `Escape` key, the `DialogComponent`'s close event is fired.

A `preventAction` callback was introduced as a part of the DialogSettings when the Dialog is opened via the service in v. 5.1.0 of the package:

https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/#toc-dialog-close-prevention

This allows the developer to prevent the closing of the Dialog conditionally in all scenarios, involving creating the component using the service.

I apologize for any confusion that our current documentation demos might have caused. We will update our documentation accordingly to avoid future potential misunderstanding.
