### ISSUE TITLE
@progress/kendo-angular-tslint-rules

### ISSUE THREAD

**Issue by JWess** [telerik/kendo-angular#2408]
I noticed that there is an npm package, for kendo angular tslint rules here:

https://www.npmjs.com/package/@progress/kendo-angular-tslint-rules

This could be very useful. Are there plans to add something like this?

**Comment by danielkaradachki** [comment]
Not sure if the rules will be very useful in the general case. The package contains rules that are shared between our packages. For example that the component selector should be prefixed with 'kendo'. The package is public so you could still install it and try it.
