### ISSUE TITLE
[Editor] Paste cleanup

### ISSUE THREAD

**Issue by ZbigniewKrzystanek** [telerik/kendo-angular#2410]
Hi, is there any chance to see Paste clenup in 1.0 version of an Editor?

Functionality for jQuery can be found here: 
https://demos.telerik.com/kendo-ui/editor/paste-cleanup

It would be great to have that. 
Best regards.

**Comment by Raisolution** [comment]
Hi @ZbigniewKrzystanek ,

Adding "Paste clean up" to the Editor component is part of our future development plans, however most probably it won't be part of our R3 2019 release in mid September.

**Comment by ketanISM** [comment]
Hi is this available in current version of Angular Kendo Editor?

**Comment by siyka-marinova** [comment]
The feature is now available in the latest official version `kendo-angular-editor v1.2.0`

**Comment by dummdidumm** [comment]
I'm missing the `custom` option of the the [jQuery implementation](https://docs.telerik.com/kendo-ui/api/javascript/ui/editor/configuration/pastecleanup#pastecleanupcustom). It would be great to have this, too (called last after Kendo has done its part of the cleanup), to implement custom needs.

**Comment by PetarMetodiev** [comment]
Hi Simon,

Indeed the Angular version of the editor does not implement all the features from the jQuery one. With that in mind we try to focus our development efforts towards the most needed functionalities first. 
If having the option to manipulate pasted content is important for you, please submit a feature request on our [feedback portal](https://feedback.telerik.com/kendo-angular-ui). We keep a close eye on the portal as it is one of our main ways of keeping up with user demand.
