### ISSUE TITLE
Comboxbox selection with dynamic textField binding not working

### ISSUE THREAD

**Issue by VasuBalakrishnan** [telerik/kendo-angular#2411]
Kendo angular combobox selection doesnt seem to work if the textField, valueField properties are dynamically bound and are not available at startup. In this example, setTimeout is to simulate a remote call.

![image](https://user-images.githubusercontent.com/4176553/62074363-9a551980-b210-11e9-812a-262260cb7fbd.png)

## Current behavior

The item selection doesnt work. There is no error / exception

## Expected behavior

The item selection should work as in the default.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-9vkcdj-qjwmju?file=app/app.component.ts

## Environment

Package versions:
```
@progress/kendo-angular-dropdowns: "^4.0.0"
```

Browser:

- Chrome (desktop) version 75.0.3770.142

System:
- Platform:  Windows

**Comment by dimitar-pechev** [comment]
Fixed in **v4.2.1**.
