### ISSUE TITLE
How to add holidays to kendo scheduler? 

### ISSUE THREAD

**Issue by vahidsamimi** [telerik/kendo-angular#2412]
Hi
Is anybody know how to add holidays to kendo scheduler?
I mean in a holiday user shouldn't be able to add any events. and change the bg-color for this day.

**Comment by Raisolution** [comment]
Hi @vahidsamimi ,

The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

As a quick start with the implementation of this scenario, check the [Scheduler Restrictions](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/restrictions/) section of the documentation.
