### ISSUE TITLE
collapse all parent nodes when current parent node is expanded in kendo-angular treeview

### ISSUE THREAD

**Issue by shaikyunus** [telerik/kendo-angular#2415]
<kendo-treeview  
        id="treeView"
        [nodes]="appVitalizeList | async"
        textField="name"
        kendoTreeViewExpandable
   
        kendoTreeViewHierarchyBinding
        [children]="fetchChildren"
        [hasChildren]="hasChildren"
        (collapse)="handleCollapse($event)" 
       (expand)="onExpand($event)"
                    [isSelected]="isItemSelected"
(selectionChange)="handleSelection($event)"
(mouseover) ="toolTip($event, dataItem)"
        >

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
