### ISSUE TITLE
No Documentation on How to Color Background for Kendo Scheduler Event

### ISSUE THREAD

**Issue by jaystubbs** [telerik/kendo-angular#2416]
**Describe the issue**
For Kendo Angular, there is a section for how to create templates within a scheduler event, but it says nothing about how to color the event's background. Your stackblitz shows that the background can be colored [at this demo](https://4dai7y.run.stackblitz.io/), but it's impossible to tell how (style is being added inline to the elements, as opposed to a class being added, etc.)

**Screenshots**
Screenshot of demo, and injected/inline style:
![image](https://user-images.githubusercontent.com/25492402/62240725-33b13680-b39d-11e9-8acf-d6fdbdb0ed0d.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.142

**Additional context**

**Comment by tsvetomir** [comment]
The [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) include two new callbacks - [eventClass](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/SchedulerComponent/#toc-eventclass) and [eventStyles](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/SchedulerComponent/#toc-eventstyles) for customizing event appearance.

You can refer to the examples in the API reference for the moment.

**Comment by tsvetomir** [comment]
Published in v0.16
