### ISSUE TITLE
Date range navigational buttons trigger postback when used inside .NET applications

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#2421]
The template for the date range component's navigational buttons (left and right) do not have 'type="button"' set to each button, so if used inside a .NET form, clicking it triggers a postback and causes the page to reload.

**To Reproduce**
1. Open a [date range component](https://www.telerik.com/kendo-angular-ui/components/dateinputs/daterange/) popup
2. Select the "left" or "right" arrow buttons to change the months displayed

**Comment by ipeshev** [comment]
fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
Shipped with **v4.1.0**.
