### ISSUE TITLE
Hidden columns cannot be made visible after column resizing

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2423]
**Describe the bug**
Resizing any of the columns while a column is hidden makes it impossible to show it.

**To Reproduce**
1. Open the example at https://stackblitz.com/edit/angular-lfrg3m
1. Check the "Hide Price" checkbox
1. Resize the ID column
1. Uncheck the "Hide Price" checkbox

**Expected behavior**
The Price column should become visible, but it remains hidden.

**Browser**
 - OS: OSX
 - Browser: Firefox 69

**Additional context**
Support ticker ref 1418908

**Comment by dtopalov** [comment]
Workaround - set the `width` of the dynamic column:

https://stackblitz.com/edit/angular-r8jfqc?file=app%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fix is available in `v6.1.2` of the Grid package.
