### ISSUE TITLE
Legends on Stock Chart Still not Working.

### ISSUE THREAD

**Issue by Praxsr014** [telerik/kendo-angular#2426]
Hi, I am trying to use Legends on the Stock Chart but I'm not able to see the legend. 
It was an issue before and was closed saying it's working but it's not. [](https://github.com/telerik/kendo-angular/issues/694)
I have updated @progress/kendo-charts to 1.13.1 and @progress/kendo-angular-charts to 4.0.1
The Legend is not showing up even on the Examples on the Telerik website.

**Comment by danielkaradachki** [comment]
Seems to be working here:

https://stackblitz.com/edit/angular-nv1rnq?file=app/app.component.ts

Note that you should set series name and the legend visible option or add the legend component in order for the [legend](https://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/legend/) to be shown.
