### ISSUE TITLE
Grid: Column Menu not completely visible

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#2427]
**Describe the bug**
The column Menu / Selection of Columns is not working on Devices with small resolutions like Tablets if the grid is placed nearly the bottom of the screen. The column menu button are not visible, getting clipped by the bottom of the screen.

**To Reproduce**

1) Open this stackblitz sample: https://stackblitz.com/edit/angular-jyjsbx
2) Open the browser sreen in a new window by clicking the Open New Window (live) link
2) Open the dev-tools of the browser
3) Show the device toolbar and select IPad in landscape mode
4) Open the Column Menu of the grid
5) Click Columns Reset/Apply button is not visible

The Reset/Apply Buttons are not visible
![image](https://user-images.githubusercontent.com/40692513/62600939-7b314880-b8f0-11e9-91ad-495996c4473f.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809.100

**Comment by danielkaradachki** [comment]
Seems to be the same as https://github.com/telerik/kendo-angular/issues/2031? They are not visible because the popup is not repositioned after the item is expanded. Am I missing something?

**Comment by Raisolution** [comment]
Fixed as part of #2031
