### ISSUE TITLE
[ComboBox] virtualization with filtering sometimes yields an empty list

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2428]
When the virtualization and filtering are enabled, sometimes the filtered list is not rendered properly (item(s) seem empty) - after pressing a key or clicking on an item, the item is visualized properly:

https://stackblitz.com/edit/angular-awjrzi?file=app/app.component.ts

Search for "un" - the result should be "Unique", but the item name is not shown.

**Comment by jiangyh1024** [comment]
@dtopalov Hi, does combobox support virtualisatio now??? I saw the demo you provided and found that there is a 'virtual' property on combobox.

**Comment by dtopalov** [comment]
@jiangyh1024 Yes, still in the [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) only:

https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/combobox/virtualization/

**Comment by siyka-marinova** [comment]
Available now also in `@progress//kendo-angular-dropdowns v4.2.3`
