### ISSUE TITLE
[PdfExport] Polish characters not exported as expected in Edge v.44.x

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2429]
Polish characters are exported as expected in Chrome and FireFox, but the bold text is not exported properly in Edge v.44 while the normal text is exported as italic.

Tested on:

Microsoft Edge 44.17763.1.0 and 42.17134

Microsoft EdgeHTML 18.17763 and 17.17134

Also tested on older Edge 40.x where the document was exported as expected.

[kendo-pdfexport-error.zip](https://github.com/telerik/kendo-angular/files/3481910/kendo-pdfexport-error.zip)

**Comment by mbechev** [comment]
It isn't present in the latest versions of Edge v82 or v83. I am closing this issue as the Angular supports the 2 most recent major Edge versions:
[https://angular.io/guide/browser-support](https://angular.io/guide/browser-support)
