### ISSUE TITLE
kendo-file-saver: saveAs wrong documentation

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#243]
On documentation http://www.telerik.com/kendo-angular-ui/components/filesaver/ there is just:

`saveAs(dataURI, "fileName.txt");`

without any SaveOptions parameter but method with two parameters doesn't exist.
So we have always to call as:

`saveAs(dataURI, "fileName.txt", {});`

Or issue is on documentation or on class.
Thanks!

**Comment by tsvetomir** [comment]
Thanks for reporting this issue. It should be fixed in version 0.1.1 that we just published.

**Comment by meriturva** [comment]
So thanks but now on version 0.1.1 dist/cdn folder and bundle is missing!

**Comment by tsvetomir** [comment]
Sorry, will fix this right away. Version 0.1.2 is on its way.

The CDN bundle is not an official feature by the way. We kind of assumed everyone is using a bundler. Perhaps this assumption is not correct for the smaller, helper components that can be used outside Angular.

**Comment by meriturva** [comment]
So thanks! i think that CDN bundle could be really important for plunker and small support request. Don't you think?

**Comment by tsvetomir** [comment]
Plunkr w/SystemJS can function with CJS and ES module bundles as well. The CDN bundle does save us a few requests though. For large components that can be _quite a few_. So it's here to stay.

**Comment by meriturva** [comment]
Perfect and thanks!
