### ISSUE TITLE
"Reset" button for kendoGridColumnChooser triggers postback when used inside .NET applications

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#2431]
The template for kendoGridColumnChooser's "Reset" button does not have 'type="button"' set to it, so if used inside a .NET form, clicking it triggers a postback and causes the page to reload.

**To Reproduce**
Open a kendoGridColumnChooser
Select "Reset" button

**Additional Notes**
The "Apply" button works fine.

**Comment by danielkaradachki** [comment]
Fix released in 4.2.0
