### ISSUE TITLE
Add expanded state to group header template context

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2432]
**Current behavior**
The expanded state of the group is not available in the header template.

**Expected behavior**
The expanded state should be included to the template context in order to allow customization of each state.

```html
<kendo-grid #grid>
   <kendo-grid-column>
     <ng-template kendoGridGroupHeaderTemplate let-expanded="expanded">
       ...
     </ng-template>
   </kendo-grid-column>
</kendo-grid>
```

**Comment by danielkaradachki** [comment]
Released in 4.2.0

https://stackblitz.com/edit/angular-uba4me?file=app/app.component.ts
