### ISSUE TITLE
[Scheduler] Overlapping event tiles in specific cases

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2433]
**Describe the bug**
In some specific cases we are experiencing a strange overlapping:

**To Reproduce**
https://stackblitz.com/edit/angular-fb5szf?file=app/events-utc.ts
Look at the 12PM slot as well as the 5:30PM slot

**Expected behavior**
Events should not overlap

**Screenshots**
![image](https://user-images.githubusercontent.com/9464097/62862676-39007080-bd0f-11e9-9a40-be58651d44f5.png)
![image](https://user-images.githubusercontent.com/9464097/62862694-47e72300-bd0f-11e9-8858-a8c27a097417.png)

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 76

**Additional context**

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Released in v0.16
