### ISSUE TITLE
[AutoComplete] does not highlight a predefined value

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2434]
**Describe the bug**
When an AutoComplete component has a predefined value and its popup is opened when is focused (using [toggle ](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/AutoCompleteComponent/#toc-toggle)method), the item is not highlighted.

**To Reproduce**
https://stackblitz.com/edit/angular-6lkuri-hdugwq?file=app/app.component.ts

**Comment by svn120** [comment]
After team discussion and comparison with other Angular components libraries, we agreed that the default behaviour for the AutoComplete component should not be changed, but it can be enhanced - see issue #3081.
 
That is why I am closing this issue. As an addition, the desired behaviour can be achieved with the ComboBox component:
https://stackblitz.com/edit/angular-vw33oo
