### ISSUE TITLE
[AutoComplete] Enhancement - capitalize matched item when tabbing out 

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2437]
When the AutoComplete `suggest` option is set to `true`, and the user input is autocompleted with the suggestion, tabbing out of the component results in selecting the lower-case value, while pressing enter selects the capitalized version from the list of options.

Perhaps the more intuitive user experience would be the value to be capitalized (or otherwise adjusted) to match the respective item from the list both on Tab and on Enter.

**Comment by stnikolova** [comment]
After a discussion with the UX team, we agreed that this is the expected behavior.
