### ISSUE TITLE
how to get kendo generated  node list in kendo-treeview 

### ISSUE THREAD

**Issue by Sudhanshu-Evince** [telerik/kendo-angular#2438]
how we can get list like ["0","0_1","0_2","0_1_1"] with their respective item detail in .ts file after rendreing kendo tree view component.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
