### ISSUE TITLE
[AutoComplete] Wrong behavior while typing in Japanese in Safari

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2439]
When typing in the Input with a Japanese keyboard input source on a Mac in Safari, the cursor stays in the beginning instead of after the typed character. 

Also, characters cannot be deleted with backspace, other unexpected character appear when pressing backspace and/or the arrow keys.

Detailed reproduction steps and the observed problems after each step are available in the following private support thread:

Ticket ID: 1425529

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
The fix is available in **v7.2.1** of @progress/kendo-angular-dropdowns
