### ISSUE TITLE
Filtering in DropDownList doesn't allow "space" character

### ISSUE THREAD

**Issue by vladislavsadovski** [telerik/kendo-angular#244]
Hello,

The filter input of the DropDownList component doesn't allow to type in "space" character.
Reproduced on http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/#toc-filtering in multiple browsers

**Comment by valchev** [comment]
@vladislavsadovski thank you for bringing this to our attention.

The issue will be fixed in a few days.

**Comment by jmaronge** [comment]
Still does not work.  It will allow 1 space between words but if you put more than one it won't.

http://embed.plnkr.co/HOcq59JGKSakzRW20Ejr/

See the array:

     public dataCategory: Array<{ categoryName: string, categoryId: number }> = [
        { categoryName: "Beverages     (3)", categoryId: 1 },
        { categoryName: "Condiments    (4)", categoryId: 2 },
        { categoryName: "Seafood       (9)", categoryId: 3 }
    ];
