### ISSUE TITLE
Throw warning when duplicated dialog/window containers directives are used

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2440]
It is good to notify user when he uses duplicated dialog/window container, since in this case those are not working correctly without any notification.

**Comment by Raisolution** [comment]
Documented as part of the Dialog and Window Angular service articles

https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/#toc-specifying-the-dialog-container

https://www.telerik.com/kendo-angular-ui/components/dialogs/window/service/#toc-specifying-the-window-container
