### ISSUE TITLE
Editor code tag support

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#2443]
I already post question how to insert `<code>` tag into editor with custom command and the answer was it's not possible, but idea is great and I should open feature request which I did, and there I receive that this will probably not get into version before May!

Since I get message on private and feedback portal that the team are currently adding additional html tags and there is no other work around, I don't have any chose as to write here and hope someone with source code knowledge will agree this is really minor change.

I dig into source code and I think files that needs to be fixed are the same as for using 'blockquote'. Entire functionality could be copied from `blockquote`.  
From [docs](https://www.telerik.com/kendo-angular-ui/components/editor/api/EditorComponent/#toc-exec): `editor.exec('format', { tag: 'blockquote' });`

I would happy to accept any work-around (how to insert custom html to editor cursor position).

**Comment by valchev** [comment]
Hi @MaklaCof 

If a workaround for this scenario was technically possible, I or one of my colleagues would certainly share it in the support thread that you've opened.

I would agree that the implementation of this feature is not very complex, but still it requires updates in the themes, updates in the user interface (toolbar tools), updates in the API, review and QA tests. 

The change in the API might be a minor change, but the whole process requires some time. We don't evaluate the new feature ideas only on the number of votes, so be sure that your request will be taken into account as soon as possible.

**Comment by Raisolution** [comment]
Closing this issue, as the demand for the feature is tracked in the respective feedback portal item here

https://feedback.telerik.com/kendo-angular-ui/1425386-add-support-to-insert-custom-html-through-method-to-editor-component-code-tag-support
