### ISSUE TITLE
[Editor] Hyperlinks do not behave as expected

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2445]
When the Toolbar LINK menu is used to create a hyperlink from the selected text, clicking on this text does not open the specified URL (neither does ctrl + click or other key + click combinations):

![image](https://user-images.githubusercontent.com/7533599/63686238-0aec5780-c80a-11e9-9b01-0a2607129d51.png)
![image](https://user-images.githubusercontent.com/7533599/63686269-22c3db80-c80a-11e9-9dac-a22a64d47860.png)

**Comment by srini1978** [comment]
Is there an ETA for this issue ?

**Comment by dtopalov** [comment]
Hi @srini1978,

Unfortunately, there is still no ETA we can commit to. This thread will be updated accordingly once a fix is available in the dev version of the package.

**Comment by dtopalov** [comment]
The behavior is expected in a content editable DIV element such as the one used internally by the Editor.

Links in such elements are not clickable, and this is a DOM-specific behavior that is not related to the Kendo UI for Angular Editor component:

https://stackblitz.com/edit/angular-ivy-cjqxkf?file=src%2Fapp%2Fapp.component.html
