### ISSUE TITLE
After Tooltip implementation on Grid Title some unexpected behavior when sorting 

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2446]
**Describe the bug**
When we implement kendo tooltip on the grid it works as expected. but when we have multiple sort enabled then sort column value also gets appended to it which is not expected.

**To Reproduce**
import { Component, ViewEncapsulation, ViewChild } from '@angular/core';
import { products } from './products';

import { TooltipDirective } from '@progress/kendo-angular-tooltip';
const matches = (el, selector) => (el.matches || el.msMatchesSelector).call(el, selector);

@Component({
  selector: 'my-app',
  template: `
    <ng-template #tooltipgrid let-anchor>
      <span>{{ anchor.nativeElement.innerText }}</span>
    </ng-template>
   <div kendoTooltip
      [tooltipTemplate]="tooltipgrid"
      filter="th.tooLong, td.tooLong, a.tooLong"
      (mouseover)="onGridMouseOver($event)">
    <kendo-grid [kendoGridBinding]="gridData" [pageSize]="5" [pageable]="true" [resizable]="true"
    [sortable]="{
                    allowUnsort: allowUnsort,
                    mode:  'multiple' 
                    }"
                    [sort]="sort"
                    [resizable]="true">
        <kendo-grid-column field="ProductID" title="ID" width="40">
        </kendo-grid-column>
        <kendo-grid-column field="ProductName" title="Name" width="150">
        </kendo-grid-column>
        <kendo-grid-column field="Category.CategoryName" title="Category">
        </kendo-grid-column>
        <kendo-grid-column field="UnitPrice" title="Price" width="80">
        </kendo-grid-column>
        <kendo-grid-column field="UnitsInStock" title="In stock" width="80">
        </kendo-grid-column>
        <kendo-grid-column field="Discontinued" title="Discontinued" width="120">
            <ng-template kendoGridCellTemplate let-dataItem>
                <input type="checkbox" [checked]="dataItem.Discontinued" disabled/>
            </ng-template>
        </kendo-grid-column>
    </kendo-grid>
    </div>
  `,
  encapsulation: ViewEncapsulation.None,
  styles: [`
    .k-grid .k-grid-content td {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
  `]
})
export class AppComponent {
    @ViewChild(TooltipDirective) public tooltipDir: TooltipDirective;
    public gridData: any[] = products;

     onGridMouseOver(e) {

    const element = e.target;
    var str = element.innerText.replace(/\s/g, '');
    if (element.nodeName == "TD" && element.matches(".k-grid-content td") || element.nodeName == "TH" && element.matches(".k-grid-header th") || element.nodeName == "A" && element.matches(".k-grid-header th a")) {
      if ((str.length > 0 && !(element.matches("td.k-command-cell")) && !(element.matches("td input")) && !(element.matches("th .k-sort-order")))) {
        element.classList.add('tooLong');
      } else {
        element.classList.remove('tooLong');
      }
    }
  }
}

// JSON Data

export const products = [{
    'ProductID': 1,
    'ProductName': 'Chai',
    'SupplierID': 1,
    'CategoryID': 1,
    'QuantityPerUnit': '10 boxes x 20 bags',
    'UnitPrice': 18.0000,
    'UnitsInStock': 39,
    'UnitsOnOrder': 0,
    'ReorderLevel': 10,
    'Discontinued': false,
    'Category': {
        'CategoryID': 1,
        'CategoryName': 'Beverages',
        'Description': 'Soft drinks, coffees, teas, beers, and ales'
    }
}, {
    'ProductID': 2,
    'ProductName': 'Chang',
    'SupplierID': 1,
    'CategoryID': 1,
    'QuantityPerUnit': '24 - 12 oz bottles',
    'UnitPrice': 19.0000,
    'UnitsInStock': 17,
    'UnitsOnOrder': 40,
    'ReorderLevel': 25,
    'Discontinued': false,
    'Category': {
        'CategoryID': 1,
        'CategoryName': 'Beverages',
        'Description': 'Soft drinks, coffees, teas, beers, and ales'
    }
}, {
    'ProductID': 3,
    'ProductName': 'Aniseed Syrup',
    'SupplierID': 1,
    'CategoryID': 2,
    'QuantityPerUnit': '12 - 550 ml bottles',
    'UnitPrice': 10.0000,
    'UnitsInStock': 13,
    'UnitsOnOrder': 70,
    'ReorderLevel': 25,
    'Discontinued': false,
    'Category': {
        'CategoryID': 2,
        'CategoryName': 'Condiments',
        'Description': 'Sweet and savory sauces, relishes, spreads, and seasonings'
    }
}, {
    'ProductID': 4,
    'ProductName': 'Chef Anton Cajun Seasoning',
    'SupplierID': 2,
    'CategoryID': 2,
    'QuantityPerUnit': '48 - 6 oz jars',
    'UnitPrice': 22.0000,
    'UnitsInStock': 53,
    'UnitsOnOrder': 0,
    'ReorderLevel': 0,
    'Discontinued': false,
    'Category': {
        'CategoryID': 2,
        'CategoryName': 'Condiments',
        'Description': 'Sweet and savory sauces, relishes, spreads, and seasonings'
    }
}, {
    'ProductID': 5,
    'ProductName': 'Chef Anton Gumbo Mix',
    'SupplierID': 2,
    'CategoryID': 2,
    'QuantityPerUnit': '36 boxes',
    'UnitPrice': 21.3500,
    'UnitsInStock': 0,
    'UnitsOnOrder': 0,
    'ReorderLevel': 0,
    'Discontinued': true,
    'Category': {
        'CategoryID': 2,
        'CategoryName': 'Condiments',
        'Description': 'Sweet and savory sauces, relishes, spreads, and seasonings'
    }
}, {
    'ProductID': 6,
    'ProductName': 'Grandma Boysenberry Spread',
    'SupplierID': 3,
    'CategoryID': 2,
    'QuantityPerUnit': '12 - 8 oz jars',
    'UnitPrice': 25.0000,
    'UnitsInStock': 120,
    'UnitsOnOrder': 0,
    'ReorderLevel': 25,
    'Discontinued': false,
    'Category': {
        'CategoryID': 2,
        'CategoryName': 'Condiments',
        'Description': 'Sweet and savory sauces, relishes, spreads, and seasonings'
    }
}, {
    'ProductID': 7,
    'ProductName': 'Uncle Bob Organic Dried Pears',
    'SupplierID': 3,
    'CategoryID': 7,
    'QuantityPerUnit': '12 - 1 lb pkgs.',
    'UnitPrice': 30.0000,
    'UnitsInStock': 15,
    'UnitsOnOrder': 0,
    'ReorderLevel': 10,
    'Discontinued': false,
    'Category': {
        'CategoryID': 7,
        'CategoryName': 'Produce',
        'Description': 'Dried fruit and bean curd'
    }
}, {
    'ProductID': 8,
    'ProductName': 'Northwoods Cranberry Sauce',
    'SupplierID': 3,
    'CategoryID': 2,
    'QuantityPerUnit': '12 - 12 oz jars',
    'UnitPrice': 40.0000,
    'UnitsInStock': 6,
    'UnitsOnOrder': 0,
    'ReorderLevel': 0,
    'Discontinued': false,
    'Category': {
        'CategoryID': 2,
        'CategoryName': 'Condiments',
        'Description': 'Sweet and savory sauces, relishes, spreads, and seasonings'
    }
}, {
    'ProductID': 9,
    'ProductName': 'Mishi Kobe Niku',
    'SupplierID': 4,
    'CategoryID': 6,
    'QuantityPerUnit': '18 - 500 g pkgs.',
    'UnitPrice': 97.0000,
    'UnitsInStock': 29,
    'UnitsOnOrder': 0,
    'ReorderLevel': 0,
    'Discontinued': true,
    'Category': {
        'CategoryID': 6,
        'CategoryName': 'Meat/Poultry',
        'Description': 'Prepared meats'
    }
}, {
    'ProductID': 10,
    'ProductName': 'Ikura',
    'SupplierID': 4,
    'CategoryID': 8,
    'QuantityPerUnit': '12 - 200 ml jars',
    'UnitPrice': 31.0000,
    'UnitsInStock': 31,
    'UnitsOnOrder': 0,
    'ReorderLevel': 0,
    'Discontinued': false,
    'Category': {
        'CategoryID': 8,
        'CategoryName': 'Seafood',
        'Description': 'Seaweed and fish'
    }
}];

**Expected behavior**
The numbers appended in Title should not be there. Plane title to be shown even after sort.

**Screenshots**
![table-hover-header-issue](https://user-images.githubusercontent.com/5736855/63690646-dccb3f80-c82a-11e9-83b7-6151c36f726a.png)

*In price Columen(3) should not get appended. 

**Browser**
All
and in IE this grid tooltips do not work properly unless I put
if (!Element.prototype.matches) {
  Element.prototype.matches = Element.prototype.msMatchesSelector;
}
in pollyfill.ts

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
