### ISSUE TITLE
[Editor] Issue with Internet Explorer and Skype for Business Browser Helper

### ISSUE THREAD

**Issue by jdornan26** [telerik/kendo-angular#2449]
**Describe the bug**
When using the Kendo Editor and you have phone number in the text the Skype for Business Browser Helper Plugin for IE keeps adding additional icons at the end of the phone number.

**To Reproduce**

1. Navigate to https://www.telerik.com/kendo-angular-ui/components/editor/ using Internet Explorer 11
2. Add a bullet item in phone number format

**Expected behavior**
Since this is an editor no icons should be added to the end of the phone number as it will be saved to the database.

**Browser**
 - OS: Windows 10
 - Browser IE
 - Version 11

![image](https://user-images.githubusercontent.com/54586181/63775266-f90fc080-c8ac-11e9-828d-2b3019b3a7ef.png)

**Comment by dtopalov** [comment]
The issue does not seem to be caused by the Kendo UI for Angular Editor component.
