### ISSUE TITLE
kendo-grid-command-column error

### ISSUE THREAD

**Issue by tejasdhimmar** [telerik/kendo-angular#245]
We are working with external edit grid form. During this implementation we found this issue. Install all the packages which are described below.

      1. npm install --save @progress/kendo-angular-grid 
      2. npm install --save @progress/kendo-data-query 
      3. npm install --save @progress/kendo-angular-intl

but still we get following error.

Unhandled Promise rejection: Template parse errors:
'kendo-grid-command-column' is not a known element:
1. If 'kendo-grid-command-column' is an Angular component, then verify that it is part of this module.
2. If 'kendo-grid-command-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("        <kendo-grid-column field="UnitsInStock" title="Units In Stock"></kendo-grid-column>
        [ERROR ->]<kendo-grid-command-column title="command" width="220">
            <template>
                <butto"): AppComponent@17:8 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
'kendo-grid-command-column' is not a known element:

**Comment by rusev** [comment]
Can provide runnable example demonstrating the error? All seems to be working in the [Editing article](http://www.telerik.com/kendo-angular-ui/components/grid/editing/).

**Comment by askaliate** [comment]
Hello,

I am running into this issue as well, these are the packages being used:

    "@progress/kendo-angular-buttons": "0.14.0",
    "@progress/kendo-angular-dialog": "0.14.1",
    "@progress/kendo-angular-dropdowns": "0.24.4",
    "@progress/kendo-angular-intl": "0.9.0",
    "@progress/kendo-angular-grid": "0.7.0",
    "@progress/kendo-angular-popup": "0.15.0",
    "@progress/kendo-angular-upload": "0.12.0",
    "@progress/kendo-data-query": "0.2.0",
    "@progress/kendo-popup-common": "0.3.0",
    "@progress/kendo-angular-inputs": "0.18.2",
    "@progress/kendo-theme-default": "2.11.4",
    "@telerik/kendo-dropdowns-common": "0.2.0",
    "@telerik/kendo-intl": "0.12.0",
    "@telerik/kendo-theme-default": "1.32.0",
    "@telerik/kendo-draggable": "1.5.1",
    "@telerik/kendo-inputs-common": "2.1.0"

**Comment by rusev** [comment]
@askaliate can you provide a runnable example for the issue? We are not sure how to replicate the behavior.
