### ISSUE TITLE
[TabStrip] Up/Down Arrow navigates between the tabs

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2450]
**Describe the bug**
When using a horizontal TabStrip we can navigate between the tabs by pressing the Up/Down Arrow keys as demonstrated in our documentation:
https://www.telerik.com/kendo-angular-ui/components/layout/tabstrip/keyboard-navigation/

However, this should not be the case according to the W3C specification. Please check point 3 in the Note at the following link: https://www.w3.org/TR/wai-aria-practices/#tabpanel

Instead, when using a horizontal TabStrip and we press the Up/Down Arrow keys the page should be scrolled.

**Comment by siyka-marinova** [comment]
The fix is available in `@progress/kendo-angular-layout v4.1.4`
