### ISSUE TITLE
[DatePicker] Enhancement - return focus to the component when Popup is closed

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2451]
Currently the Popup is appended to the root component, and thus when tabbing out of the opened Calendar, the focus does not go to the next focusable element (next to the DatePicker) on the page.

Setting the `popupSettings` **appendTo** option to "component" yields the expected behavior:

https://stackblitz.com/edit/angular-vjs4kp-nepp5y?file=app/app.component.ts

However it would be nice to provide this behavior out-of-the-box so the developer would need to explicitly configure the popup settings for every DatePicker on the page.

**Comment by dimitar-pechev** [comment]
Shipped in **v4.2.0**.
