### ISSUE TITLE
TabStrip tab titles not truncated

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#2452]
**Describe the bug**

When in the tabstrip component are many tabs with longer titles, the text are not truncated on small browser windows.
It will display a scrollbar at the bottom of the page, which breaks our responsive layout for smaller desktop screens.

**To Reproduce**

Here is a small sample of the problem:
https://stackblitz.com/edit/angular-tabstrip-long-tab-title

**Expected behavior**

The too long text should not be displayed or truncated (text-overflow: ellipsis).

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809.132

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/63998873-ba8c3700-cb34-11e9-9fc2-51e92df58670.png)
@andrpelz 
set overflow to 'auto' will solve your issue

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/63998922-dc85b980-cb34-11e9-9953-061bbd3707ef.png)

@andrpelz 
setting overflow to auto will solve your problem

**Comment by andrpelz** [comment]
Thanks for your answer, this makes it a little better. But I do not want a scrollbar, it should truncated the text.

**Comment by ipeshev** [comment]
@andrpelz we researched different workarounds and it is not so easy this to be achieved, code fix or enhancement is needed.

**Comment by andrpelz** [comment]
Many thanks for your work and the info!

**Comment by Raisolution** [comment]
By default, the TabStrip component does not truncate long tab titles as they don't have a fixed width. They can be truncated by using some custom CSS styling. Here is an example that demonstrates this in action:

https://stackblitz.com/edit/angular-j95s6t?file=app/app.component.ts

This example will also be available as a[ Knowledge Base article on our documentation](https://www.telerik.com/kendo-angular-ui-develop/components/knowledge-base/).
