### ISSUE TITLE
Kendo Muilt Select - group template bugs

### ISSUE THREAD

**Issue by jiangyh1024** [telerik/kendo-angular#2454]
![image](https://user-images.githubusercontent.com/34930870/63915784-75e79980-ca69-11e9-8258-5b3e5d2bf43d.png)

as you can see, I used 'kendoMultiSelectGroupTemplate ' directive, but the first group did not use the template

import { groupBy } from '@progress/kendo-data-query';
```
@Component({
selector: 'my-app',
template: `
 <kendo-multiselect [data]="groupedData" [textField]="'name'" [valueField]="'name'">
   <ng-template kendoMultiSelectGroupTemplate let-groupName>
     <span>Food type: {{groupName}} option</span>
   </ng-template>
 </kendo-multiselect>
`
})
class AppComponent {
  public data = [
      { name: "Pork", category: "Food", subcategory: "Meat" },
      { name: "Pepper", category: "Food", subcategory: "Vegetables" },
      { name: "Beef", category: "Food", subcategory: "Meat" }
  ];
  public groupedData = groupBy(this.data, [{field: "subcategory"}]);
}
```

**Comment by dimitar-pechev** [comment]
To modify the fixed group label (the first one that stays top during scrolling) you need to specify a `kendoMultiSelectFixedGroupTemplate`. The `kendoMultiSelectGroupTemplate` applies for the rest of the groups as you've already pointed out. Refer to [this example](https://stackblitz.com/edit/angular-3vj1qb). And here's a [ref from the docs](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/FixedGroupTemplateDirective/).

Although a bit more verbose, the two labels suit a different purpose, so we've decided to provide separate template options for them.
