### ISSUE TITLE
ComboBox - floatingLabel not working as expected

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#2456]
**Describe the bug**
The floatingLabel is overlapping with the text in the ComboBox when the value of that text is an empty string and the valuePrimitive is set to true.

**To Reproduce**
Here is a StackBlitz sample of the issue:
[https://stackblitz.com/edit/angular-fueyjz-jyjdvb](https://stackblitz.com/edit/angular-fueyjz-jyjdvb)

When you select the option 'Small' whose value is an empty string, the floatingLabel overlaps with the text 'Small'.

**Expected behavior**
The floatingLabel should not overlap with the text even if the value of the text is an empty string.

**Screenshots**
![image](https://user-images.githubusercontent.com/25337886/63967599-c2cc6f80-ca6b-11e9-8627-ba061aa88d21.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809.132

**Comment by dimitar-pechev** [comment]
Fixed in **v4.2.1**.
