### ISSUE TITLE
Clicking on a Dropdownlist inside a <label> triggers buttons inside that same <label>

### ISSUE THREAD

**Issue by Neaco** [telerik/kendo-angular#2458]
**Describe the bug**
If you put both a dropdownlist and a button inside the same label tag (as described in the forms documentation), clicking on the dropdownlist will also trigger the buttons. 
Same behavior is not observed with the combobox.

**To Reproduce**
https://stackblitz.com/edit/angular-uttubc

Click on the dropdownList, it will trigger the button.
Click on the combobox, nothing happens.

**Expected behavior**
DropdownList shouldn't trigger other buttons.

**Browser**
Chrome 76

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released in **v4.4.0.**
