### ISSUE TITLE
Kendo Chart -> Base Unit: weeks -> doesn't respect locale

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2459]
**Describe the bug**
If you set a `kendo-chart-x-axis-item` with base unit 'week' -> locale used is always 'en-US'

**To Reproduce**
Just see:
https://stackblitz.com/edit/angular-3m7y79?file=src%2Fapp%2Fapp.module.ts

with locale 'en-GB' we have only weeks starting on Sunday (as usual in en-US).

**Expected behavior**
Start day of the week using baseUnit=weeks has to respect locale settings.

**Comment by meriturva** [comment]
Hi @tsvetomir , just to know...is it fixed on dev channel? we have to give it a try on our side.

**Comment by tsvetomir** [comment]
Yes, it's now in the development channel. Apologies for the delay.

**Comment by meriturva** [comment]
Fixed...thanks: https://stackblitz.com/edit/angular-e6hkad
i'm just waiting for stable release

**Comment by danielkaradachki** [comment]
Released in 4.1.1

https://stackblitz.com/edit/angular-sbcf97?file=app/app.component.ts
