### ISSUE TITLE
Scheduler - TimeSlotTemplate interfere with Editing

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#2460]
**Describe the bug**
When using a TimeSlotTemplate with a block element, clicking inside that block element does not trigger an add event.

**To Reproduce**

https://stackblitz.com/edit/angular-9bxjby?file=app/app.component.ts

Clicking in the middle of an empty slot does nothing.
But clicking on the edge, brings up the create dialog

**Expected behavior**
Create dialog shows up clicking anywhere in the timeslot

**Screenshots**
![image](https://user-images.githubusercontent.com/13205912/64122431-89f90700-cd99-11e9-9b46-9ed436aed8b0.png)

**Additional context**
It's not necessary a div, in fact, in clicking in the middle of an inline element doesnt work.

**Comment by danielkaradachki** [comment]
Fixed in 1.0.1

https://stackblitz.com/edit/angular-1zzsnu?file=app/app.module.ts
