### ISSUE TITLE
Kendo Chart - series is not painted when ng-content is used

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#2462]
**Describe the bug**
The chart serie will not draw correctly if the chart is used into a component that use ng-content (transclusion).

**To Reproduce**
1) open StackBlitz example: https://stackblitz.com/edit/kendo-chart-refresh-error
2) Click the "Load" Button -> Chart is painted correctly
3) Click the "Load" Button again -> Chart is hided by the parent component (No data)
4) Click the "Load" Button again -> Chart is painted but no series are visible

When the browser is resized (chart refresh) the serie is getting painted.

**Expected behavior**
Chart should always paint the series if data is available.

**Screenshots**
Step 2:
![image](https://user-images.githubusercontent.com/40692513/64158825-77360f00-ce39-11e9-99dd-e5c7429ae679.png)

Step 3: 
![image](https://user-images.githubusercontent.com/40692513/64158870-8a48df00-ce39-11e9-8917-ecfede55c299.png)

Step 4 (Error, series not visible):
![image](https://user-images.githubusercontent.com/40692513/64158911-9df44580-ce39-11e9-90bf-a95511cd9369.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  76.0.3809.132

**Comment by danielkaradachki** [comment]
The chart seems to work correctly without the custom axis directive:

https://stackblitz.com/edit/kendo-chart-refresh-error-hzrdpc?file=app/app.component.ts

At first look, the problem occurs because the code measures the size before the element is visible after the content is shown again:

    public __buildAxisConfiguration(timeRangeChanged: boolean = false): void {
        const width = this.getCanvasWidth();
        if (!!this.timeRange && width && (this.cachedWidth !== width || timeRangeChanged)) {
