### ISSUE TITLE
[Scheduler] reassingning resources input array

### ISSUE THREAD

**Issue by stan-infosystem** [telerik/kendo-angular#2464]
**Describe the bug**

I created the angular scheduler UI gruped by resource. When afterwards the initial resource array is reassigned, an exception is thrown.

**To Reproduce**
see stackbliz code and click on the button "**Reset Resources**":

https://stackblitz.com/edit/angular-zqqav1?embed=1&file=app/app.component.ts

**Expected behavior**
The resource list should be refreshed without any error.

**Comment by danielkaradachki** [comment]
Fixed in 1.0.1

https://stackblitz.com/edit/angular-bimgdk?file=app/app.component.ts
