### ISSUE TITLE
Scheduler: Delete then Drag

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#2465]
**Describe the bug**
When you remove an item from the scheduler, then click and hold on the grid, the item you removed will be dragged around. Duplicating an item!

**To Reproduce**
https://stackblitz.com/edit/angular-6ksxwz?file=app/app.component.ts

* Add an item onto the scheduler
* Remove it
* Click and hold (Drag) on grid - You will see the deleted event

**Expected behavior**
The removed event shouldn't be dragged

**Screenshots**
![image](https://user-images.githubusercontent.com/13205912/64246104-18899780-cf04-11e9-891c-ee986473486a.png)

**Comment by danielkaradachki** [comment]
Fixed in 1.0.1


https://stackblitz.com/edit/angular-dp5sxq?file=app/app.component.ts
