### ISSUE TITLE
[Upload] File restrictions validation not triggered for ngModel bound collection

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2467]
When the Upload is bound via **ngModel** to a collection of initial files, the file restrictions are not applied:

https://stackblitz.com/edit/angular-cqjhh3-pr3epp?file=app/upload.component.ts

**Comment by Raisolution** [comment]
The current behavior is by design. Binding to the `ngModel` collection is initiated on successful upload/remove operation only. Initially bound files are always treated as "successfully uploaded" by the Upload component. This is why they are displayed in green and the restrictions are not applied.
