### ISSUE TITLE
[Grid] Grouped Grid with a locked column rows misaligned

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2469]
When the Grid is grouped by several fields, and a focusable element in a locked column template is tabbed into, the locked and unlocked table rows get misaligned:

![image](https://user-images.githubusercontent.com/7533599/64347643-ec9e0d00-cffc-11e9-88ed-b6b5de6b7f1b.png)

https://stackblitz.com/edit/angular-38yktk-j33riz?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix is available in `@progress/kendo-angular-grid v.4.4.0`
