### ISSUE TITLE
Different currency than locale one

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#247]
How can I use different than locale currency in ColumnComponent.format input or NumericTextBox?

For example I need to edit and show price in euro, dollars and british pounds. How can I achieve this?

**Comment by ggkrustev** [comment]
Hi @ilianiv,
could you clarify a bit the functionality you would like to achieve? 

Do you need to display en-US internationalized number with euro symbol or your goal is to display, for instance, German internationalized number with euro symbol? In other words, do you need:
- 10,000.12 € (en-US i18n with euro sign)
or
- 10.000,12 € (de-DE i18n with euro sign)

**Comment by ilianiv** [comment]
Hi,
I don't want to change the locale but only show a product price in different currencies. 
Let say we have car product page for Honda Accord and we want to show 3 offers:
- 52 000 лв.
- 29 000 $
- 27 000 €

**Comment by ggkrustev** [comment]
Currently, the component doesn't accept a complex format options where you can define the currency display value ([link to the options](https://github.com/telerik/kendo-intl/blob/39c50b941badcf00a0c75be0c8aa5f1bde0fd681/src/numbers.d.ts)). 

*We do have plans to add support for that functionality in the next releases of `kendo-angular-inputs` package.*

For now you can achieve your goal using custom numeric format, where the currency sign is defined manually - `[format]="'#.# лв.'"`. For the grid, you can use custom template to resolve the issue.

**Comment by ilianiv** [comment]
OK thank you will wait for next releases.

**Comment by ggkrustev** [comment]
I'll close this issue for now. It was referenced in the issue opened in our internal product backlog.
I will update the thread here, once the feature is public.

**Comment by ilianiv** [comment]
Ok thank you

Илиян Иванов
---
Iliyan Ivanov

**Comment by danielkaradachki** [comment]
The latest version supports setting [NumberFormatOptions](http://www.telerik.com/kendo-angular-ui/components/internationalization/api/NumberFormatOptions/) and thus specifying different currency:

http://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/formats/
