### ISSUE TITLE
The notification "Close" button title cannot be localized

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2471]
**Describe the bug**
The close button title of the Notification component cannot be translated.

**Expected behavior**
* The text for the close button should be read from the [translation messages](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/).
* The [notification settings](https://www.telerik.com/kendo-angular-ui/components/notification/api/NotificationSettings/) should accept overriding the close button text.

**Comment by elena-gancheva** [comment]
The fix is available in the official [v2.0.2](https://github.com/telerik/kendo-angular-notification/releases/tag/v2.0.2) version of the package.
