### ISSUE TITLE
The dialog "Close" button title cannot be localized

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2472]
**Describe the bug**
The close button title of the Dialog component cannot be translated.

**Expected behavior**
* The text for the close button should be read from the [translation messages](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/).
* The [dialog settings](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/DialogSettings/) should accept overriding the close button text.
* A [custom messages](https://www.telerik.com/kendo-angular-ui/components/grid/globalization/#toc-custom-messages) component should be provided for overriding the close message through the Angular i18n framework.

Related to #2471

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dialog` and `kendo-angular-messages`

**Comment by Raisolution** [comment]
Fix is available in `v4.1.2`
