### ISSUE TITLE
Kendo Treeview cannot unset 'Indeterminate' state

### ISSUE THREAD

**Issue by g4b0-88** [telerik/kendo-angular#2473]
I'm working with Kendo Treeview for Angular, this component is binding children ondemand so I have a parameter which tells me if the node has children and another to know if is 'checked' or 'indeterminate' or 'none'.

Actually it marks correctly the initial state of each node, the problem is when I try to unset the 'indeterminate' state, if I click the node it goes from 'indeterminate' to 'check' and viceversa, but never gets 'unchecked'.

Here a Blitz where you can see this behavior, try to 'uncheck' the indeterminate nodes:

https://stackblitz.com/edit/angular-kendo-treeview-local-data

**Comment by ipeshev** [comment]
@g4b0-88 if you delete your implementation of isChecked callback treeview will work correctly, it is up to the user to provide correct logic when custom isChecked callback is implemented.
