### ISSUE TITLE
Customize the kendoGridSelectionCheckbox

### ISSUE THREAD

**Issue by zhshqzyc** [telerik/kendo-angular#2474]
I want to use kendoGridSelectionCheckbox. The [https://www.telerik.com/kendo-angular-ui/components/grid/api/CheckboxColumnComponent/](link) uses hard code string. But I want to use a value passed in.

See the [https://stackoverflow.com/questions/57797124/how-to-customize-kendo-grid-checkbox-column](url)

**Comment by Raisolution** [comment]
Hi @zhshqzyc,

The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

Regarding the question, the `dataItem` associated to the current row could be accessed in the template as demonstrated in our [documentation](https://www.telerik.com/kendo-angular-ui/components/grid/columns/templates/#toc-cell-template).
