### ISSUE TITLE
Grid Column Menu causes unwanted scroll-down on clicking a checkbox in 'Columns' list

### ISSUE THREAD

**Issue by Vladimir-Pavelka** [telerik/kendo-angular#2476]
## I'm submitting a...
* Bug report 

## Minimal reproduction of the problem with instructions
 **MINIMAL DEMO**: https://stackblitz.com/edit/angular-viz6ga

**STEPS TO REPRODUCE**
1. in the demo, click the 'three dots' of any column to open the 'Column Menu' popup
2. scroll down to the bottom of the 'Columns' checkbox list
3. click the 'Category' or 'Name' checkbox at the bottom of the list

- Expected: the checkbox is toggled
- Actual: the checkbox is toggled + window is scrolled down, such that the 'Column Menu' is no longer visible to the user

**Additional info**: The issue seems to be related to the columns count, it appears when having ~30+ columns in the Grid. Also note, the unwanted scroll is triggered by the checkbox receiving focus (tab, shift+tab), not by the value being toggled (spacebar while having focus).

**Browser:**
- Chrome (desktop) version 77.0.3865.75 (Official Build) (64-bit)
- Firefox Quantum version 69.0 (64-bit)

## Severity
We are developing a business application, where we commonly display grids with ~30+ columns. The reported behavior is very disturbing to the user, when he tries to enable/disable multiple columns.

**Comment by danielkaradachki** [comment]
Fixed in the latest versions of the themes:
https://stackblitz.com/edit/angular-viz6ga?file=index.html
