### ISSUE TITLE
Arc Gauge: Add an option to customize the arc border 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2478]
Currently, the Arc Gauge component does not allow us to customize the arc border. 

**Desired appearance**

![screenshot](https://user-images.githubusercontent.com/33104481/64764025-e7374a00-d549-11e9-952f-6b9a11b9ab43.png)

**Comment by yanmariomenev** [comment]
Moved to the following feature request - https://feedback.telerik.com/kendo-angular-ui/1546747-add-an-option-to-customize-the-border-of-the-gauges
