### ISSUE TITLE
Scheduler: Show one single day on Agenda view

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2479]
Currently, the Scheduler Agenda view shows only 7 days without an option to customize the number of the rendered days.

**Comment by danielkaradachki** [comment]
Available as [numberOfDays](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/AgendaViewComponent/#toc-numberofdays) input in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:

https://stackblitz.com/edit/angular-q6n1yn?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Available now in the official package `kendo-angular-scheduler v1.1.0`
