### ISSUE TITLE
'kendo-grid-command-column' is not a known element

### ISSUE THREAD

**Issue by chavda141286atul** [telerik/kendo-angular#248]
Hi,

I am try to use kendo edit form example from bellow url.
http://www.telerik.com/kendo-angular-ui/components/grid/editing/external-editing/

Try to same example in my local but getting error as per bellow.

Template parse errors:
'kendo-grid-command-column' is not a known element:
1. If 'kendo-grid-command-column' is an Angular component, then verify that it is part of this module.
2. If 'kendo-grid-command-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("        <kendo-grid-column field="UnitsInStock" title="Units In Stock"></kendo-grid-column>
        [ERROR ->]<kendo-grid-command-column title="command" width="220">
            <template>
                <butto"): AppComponent@17:8 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
'kendo-grid-command-column' is not a known element:

**Comment by rusev** [comment]
Closing this in favor of this https://github.com/telerik/kendo-angular/issues/245.

Please make sure that you are using the latest version of `@progress/kendo-angular-grid` package.

**Comment by chavda141286atul** [comment]
Thanks for your quick reply.

I am try it in my existing project. How can I update my @progress/kendo-angular-grid package?

Thanks

**Comment by KirilNN** [comment]
Check this out: http://stackoverflow.com/questions/16525430/npm-check-and-update-package-if-needed

**Comment by KirilNN** [comment]
Check this out http://stackoverflow.com/questions/16525430/npm-check-and-update-package-if-needed

**Comment by chavda141286atul** [comment]
Hi KiriNN,

I am try to update @progress/kendo-angular-grid Using with command : npm update @progress/kendo-angular-grid
Its show me error like bellow.
npm ERR! registry error parsing json.

Thanks

**Comment by askaliate** [comment]
Hello,

I am running into this issue as well, these are the packages being used:

"@progress/kendo-angular-buttons": "0.14.0",
"@progress/kendo-angular-dialog": "0.14.1",
"@progress/kendo-angular-dropdowns": "0.24.4",
"@progress/kendo-angular-intl": "0.9.0",
"@progress/kendo-angular-grid": "0.7.0",
"@progress/kendo-angular-popup": "0.15.0",
"@progress/kendo-angular-upload": "0.12.0",
"@progress/kendo-data-query": "0.2.0",
"@progress/kendo-popup-common": "0.3.0",
"@progress/kendo-angular-inputs": "0.18.2",
"@progress/kendo-theme-default": "2.11.4",
"@telerik/kendo-dropdowns-common": "0.2.0",
"@telerik/kendo-intl": "0.12.0",
"@telerik/kendo-theme-default": "1.32.0",
"@telerik/kendo-draggable": "1.5.1",
"@telerik/kendo-inputs-common": "2.1.0"

**Comment by supriyasureshg** [comment]
npm view @progress/kendo-angular-grid versions this command not working its showing error
![untitled](https://cloud.githubusercontent.com/assets/13777835/24187430/e8791d86-0f02-11e7-9183-ef45b49feb76.png)

**Comment by tsvetomir** [comment]
@supriyasureshg please open a ticket in our support system so we can track the issue down.
