### ISSUE TITLE
[Grid] [kendoGridGroupBinding] directive causes unexpected behavior

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2480]
**Describe the bug**

When using the [kendoGridGroupBinding] directive and all groups are programmatically collapsed, then if we try to expand a single group other groups will be expanded as well.

**To Reproduce**
https://stackblitz.com/edit/angular-xsrbcd?file=app/app.component.ts

1. Group by "Unit Price" column,
2. Click the "Collapse Groups" button.
3. Try to expand just the first group.

**Comment by tsvetomir** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-grid`

**Comment by Raisolution** [comment]
Available in `v4.7.0`
