### ISSUE TITLE
[Grid] dblclick between resizable columns does not autofit the content in IE 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2482]
**Describe the bug**
In [resizable] Grid when we double click between columns in order to autofit the content, in IE the Grid sets the filter <input/> to the default width and makes the column width bigger.

**To Reproduce**
Open in IE:
https://stackblitz.com/edit/angular-kendo-resize-filterable-column-wghdas?file=app/app.component.ts

**Screenshots**
In comparison with the default `<input />` HTML element
IE:
![IE](https://user-images.githubusercontent.com/33104481/65032458-df154b00-d94b-11e9-8daa-3f73d251b5bd.png)

Chrome:
![Chrome](https://user-images.githubusercontent.com/33104481/65032459-df154b00-d94b-11e9-8a82-ca81e52cf416.png)

For internal use: reported in a private support thread - Ticket ID: **1429790**

**Comment by tsvetomir** [comment]
Can be worked around by adding the following style, see [updated demo](https://stackblitz.com/edit/angular-kendo-resize-filterable-column-utcgv5?file=app/app.component.ts):

```css
    .k-autofitting input {
        width: 0px !important;
    }
```

@joneff is there anything better we can do to fix this in the themes?

**Comment by joneff** [comment]
I don't think we have such a thing, but surely we could add it

**Comment by Raisolution** [comment]
Fix available in latest themes versions.
