### ISSUE TITLE
autoFitColumns not working for locked column(s)

### ISSUE THREAD

**Issue by RogierKonings** [telerik/kendo-angular#2483]
**Describe the bug**
When using autoFitColumns together with a locked column, the size of the first not-locked column will take the size of the locked column.

**To Reproduce**
Steps to reproduce the behaviour:
- create grid with with a locked column, and call the autoFitColumns function from the Javascript.
- check sizes of the columns

**Expected behaviour**
I expect the columns to autofit to the content properly

**Browser**
- all browsers

**Comment by ipeshev** [comment]
Reproducible [here](https://stackblitz.com/edit/angular-adg87b?file=app/app.component.ts).

**Comment by dougludlow** [comment]
We're running into this as well, makes using autoFitColumns completely unusable, unfortunately.

**Comment by eitacode** [comment]
Running into the same issue here

**Comment by RogierKonings** [comment]
We 'fixed' the problem by not using the build in column fix, but instead go for a sticky side column.

**Comment by tsvetomir** [comment]
Fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). Performance is improved quite a bit too.

**Comment by tsvetomir** [comment]
Released in v4.6.2
