### ISSUE TITLE
[Scheduler] workWeekStart and workWeekEnd inputs not applied in TimelineWeekView

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2485]
https://stackblitz.com/edit/angular-cj6n1e-nuz8xr?file=app/app.component.ts

The options are working as expected in a WorkWeekView but not in TimelineWeekView.

**Comment by danielkaradachki** [comment]
They are not supposed to. The workWeekStart and workWeekEnd will change the days only for the workWeekView. For the other views, the options are used just for the slots highlight. We will consider exposing timeline work week view.
