### ISSUE TITLE
[Scheduler] cannot programatically change the grouping resource

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2486]
**Describe the bug**
When we try to change programmatically the grouping resource the following error appears in the console:
`Cannot read property 'firstSlot' of undefined`

**To Reproduce**
Click the following buttons to change the number of grouping resource:
- _Multiple_
- _Single_

https://stackblitz.com/edit/angular-qxx1ez?file=app%2Fapp.component.ts

**Comment by danielkaradachki** [comment]
Fixed in 1.0.1

https://stackblitz.com/edit/angular-bimgdk?file=app/app.component.ts
