### ISSUE TITLE
Virtual Scrolling not working when binding data with kendoGridBinding

### ISSUE THREAD

**Issue by MarwanTushyeh90** [telerik/kendo-angular#2489]
**Describe the bug**

The kendo article for virtual scrolling describes how to implement virtual scrolling while using [data] binding for the grid.

If you change it to [kendoGridBinding] to enable sorting and filtering, when the pagechanged event is called, 

**To Reproduce**

https://angular-wqddis.stackblitz.io

**Expected behavior**
Virtual scrolling should work normally similar to when using data binding.
**Screenshots**

**Browser**
 - OS: MacOS
 - Browser Chrome
 - Version  76

**Comment by ipeshev** [comment]
@MarwanTushyeh90 [kendoGridBinding] works only with local data, and virtual scrolling is working as expected please check on this [stackblitz sample](https://stackblitz.com/edit/angular-wqddis-uvbxma?file=app/app.component.ts).
