### ISSUE TITLE
NumericTextBox not showing updated value till it is focused

### ISSUE THREAD

**Issue by avitiw** [telerik/kendo-angular#249]
In Kendo NumericTextBox if the value is updated on the component for e.x. in the Plunkr I have a interval trigger to increase value every 2 seconds, the updated value is visible on NumericTextBox only when the textbox is in focus. As per Angular2 data-binding any expression like [value]="numberValue" should hook for changes to "numberValue" and update it's value.

[Plunkr for issue][1]
`http://plnkr.co/edit/omlefk6zfhHc4lB3yXzt?p=preview`

[1]: http://plnkr.co/edit/omlefk6zfhHc4lB3yXzt?p=preview

**Comment by avitiw** [comment]
Any updates on it? Can we expect any release or patch to fix this issue? 

We need this fix as with this issue we won't be able to use NumericTextBox.

**Comment by Xizario** [comment]
@avitiw what should happen if the user is currently editing the value, when the timer change the model?
Same apply if you are having multiple editors, and you want to edit them and submit the changes.  
I would not expect the editor to change itself without my interaction as user.

**Comment by avitiw** [comment]
The timer is used just to demonstrate the issue that value updated programatically is not updatding UI. My use case is that on update of value of let say control1, I do ajax request that send updated value for control2 ( a numeric textbox) the model for control2 is updated but is not updated in UI.

**Comment by NGastaGasta** [comment]
I have the same issue
It's a major bug, for now we can't update NumericTextbox programmaticaly
http://plnkr.co/edit/M0sjc0SOCmzRnmsT9tvY?p=preview

**Comment by Xizario** [comment]
It works if you really bind to model:
http://plnkr.co/edit/aiTv0OIhVA04nJvj3xjt?p=preview
Or you can explicitly change the value using writeValue method from ControlValueAccessor interface.
http://plnkr.co/edit/Gjpwj3U229V0zdnxlmvJ?p=preview

**Comment by NGastaGasta** [comment]
thanks, it works with ngModel binding
but i still can't reset value
http://plnkr.co/edit/M0sjc0SOCmzRnmsT9tvY?p=preview

**Comment by Xizario** [comment]
@NGastaGasta, thanks for the further info, we will fix the null issue.

**Comment by rohit-b** [comment]
@NGastaGasta, reset works but its not reflected. after reset if you increment it starts from 1 and same if you do after setting it to 10 it changes to 11. after reset if you focus then too it is not showing correct value

**Comment by tsvetomir** [comment]
This appears to be fixed in the latest version, [see plunkr](http://plnkr.co/edit/rL39DUZQE8nka8Fczmv7?p=preview).

**Comment by RaduTudorIon** [comment]
Still not fixed - 14.11.2019
