### ISSUE TITLE
Chart category axis selection border is visible when the chart is hidden

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#2492]
**Describe the bug**
When there is a selection in a chart and the chart has zero height the selection border is visible anyway.

**To Reproduce**
Here is a [link](https://stackblitz.com/edit/angular-bs6jhu?file=app/app.component.ts) to StackBlitz. Click the "Collapse" button to reproduce the issue.

**Expected behavior**
Selection in the chart should be only visible inside the chart.

**Screenshots**
Grid height: 400px
![image](https://user-images.githubusercontent.com/33227044/65441185-9946ff80-ddef-11e9-8208-8eb4d3260abc.png)

Grid height: 0px
![image](https://user-images.githubusercontent.com/33227044/65441220-a532c180-ddef-11e9-96e5-cfd03bd97134.png)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by siyka-marinova** [comment]
Fix is now available also in the latest package `@progress/kendo-charts v1.13.3`
