### ISSUE TITLE
Scheduler - Highlighting event

### ISSUE THREAD

**Issue by psiva893** [telerik/kendo-angular#2493]
I have month long event , when i select that event it highlights only for that week. It should highlight across the month.

In the attached screen shot, 'Bowling tournament' event is for full month, but it is highlighted only for the week i selected. Expected behaviour it should hightlight across the month.

https://stackblitz.com/edit/angular-mmvzkk?file=src%2Fapp%2Fevents-utc.ts

![Schedular_Issue](https://user-images.githubusercontent.com/21230585/65449537-31051780-de09-11e9-9f9c-76491cecdc34.png)

**Comment by yanmariomenev** [comment]
Fixed in version 16.4.0.
