### ISSUE TITLE
[Upload] the files list is not displayed when using ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2497]
**Describe the bug**
When using ChangeDetectionStrategy.OnPush the files list is not rendered.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-fzx9et-w7ix51?file=app/upload.component.ts

**Comment by Raisolution** [comment]
Fixed in the latest dev version of the `kendo-angular-upload` package.

**Comment by Raisolution** [comment]
Fix is available in `v5.2.1`
