### ISSUE TITLE
Having issue only in AOT build

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2499]
I am using below packages in my angular project:-
  
"dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "5.2.3",
    "@angular/compiler": "5.2.11",
    "@angular/core": "5.2.3",
    "@angular/forms": "5.2.3",
    "@angular/http": "5.2.3",
    "@angular/platform-browser": "5.2.3",
    "@angular/platform-browser-dynamic": "5.2.3",
    "@angular/platform-server": "5.2.3",
    "@angular/router": "5.2.3",
    "@angular/upgrade": "5.2.3",
    "@ngx-translate/core": "^9.0.2",
    "@ngx-translate/http-loader": "^2.0.1",
    "@progress/kendo-angular-buttons": "^3.0.4",
    "@progress/kendo-angular-charts": "^2.0.3",
    "@progress/kendo-angular-dateinputs": "^2.2.0",
    "@progress/kendo-angular-dialog": "^3.6.2",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-grid": "3.6.1",
    "@progress/kendo-angular-inputs": "^2.2.0",
    "@progress/kendo-angular-intl": "^1.5.0",
    "@progress/kendo-angular-l10n": "^1.2.0",
    "@progress/kendo-angular-layout": "^2.2.1",
    "@progress/kendo-angular-pdf-export": "^1.2.0",
    "@progress/kendo-angular-popup": "^2.4.2",
    "@progress/kendo-angular-tooltip": "^1.0.0",
    "@progress/kendo-angular-upload": "^3.0.3",
    "@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-drawing": "^1.5.7",
    "@progress/kendo-theme-default": "^2.47.7",
    "@tinymce/tinymce-angular": "^2.3.1",
    "angular-file-saver": "^1.1.3",
    "angular2-jwt": "^0.2.3",
    "bootstrap": "4.0.0",
    "chart.js": "2.7.1",
    "core-js": "2.5.3",
    "flag-icon-css": "2.9.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "html2canvas": "^1.0.0-alpha.12",
    "ie-shim": "0.1.0",
    "lodash": "^4.17.10",
    "moment": "2.20.1",
    "moment-timezone": "0.5.26",
    "ng-click-outside": "^4.0.0",
    "ng2-charts": "1.6.0",
    "ngx-bootstrap": "2.0.2",
    "ngx-cookie-service": "^1.0.10",
    "ngx-toastr": "^8.8.0",
    "ngx-ui-loader": "^1.2.5",
    "rxjs": "^5.5.12",
    "rxjs-compat": "^6.3.2",
    "simple-line-icons": "^2.4.1",
    "systemjs": "0.19.40",
    "ts-helpers": "1.1.2",
    "zone.js": "0.8.25"
  },
  "devDependencies": {
    "@angular-devkit/core": "^0.8.2",
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "5.2.11",
    "@types/jasmine": "2.8.0",
    "@types/lodash": "^4.14.116",
    "@types/node": "^9.6.6",
    "autoprefixer": "^6.5.3",
    "css-loader": "^0.28.1",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.29.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-spec-reporter": "^0.0.32",
    "karma-webpack": "^2.0.9",
    "less-loader": "^4.0.5",
    "node-sass": "^4.5.3",
    "postcss-loader": "^1.3.3",
    "postcss-url": "^5.1.2",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "source-map-loader": "^0.2.0",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "^2.4.0",
    "url-loader": "^0.5.7"
  }

I am not having any issue in ng serve but when I try to deploy it on server with ng build I get errors as in attachment
![error](https://user-images.githubusercontent.com/5736855/65623796-366b8900-dfe6-11e9-9260-bf7742f6a68e.PNG)

I am using chart as well as grid of kendo. any clue of what went wrong as ng serve is workin but ng build failed. Thanks in advance.

**Comment by TUSHARDM** [comment]
![Capture2](https://user-images.githubusercontent.com/5736855/65624252-112b4a80-dfe7-11e9-909d-4544e4bebabe.PNG)

Errors on command ng build --aot

**Comment by TUSHARDM** [comment]
Simple code I am using is like:-
<kendo-chart>
        <kendo-chart-axis-defaults [background]="background"
                                   [color]="color"
                                   [crosshair]="crosshair"
                                   [labels]="labels"
                                   [line]="line"
                                   [visible]="'false'"
                                   [title]="kendoGridTitle"></kendo-chart-axis-defaults>
        <kendo-chart-title text="Check List Execution"></kendo-chart-title>
        <kendo-chart-category-axis>
          <kendo-chart-category-axis-item [categories]="['Q1', 'Q2', 'Q3', 'Q4']" [title]="{ text: 'Check List' }">
          </kendo-chart-category-axis-item>
        </kendo-chart-category-axis>
        <kendo-chart-series>
          <kendo-chart-series-item
                                   type="column"
                                   [gap]="2"
                                   [spacing]=".25"
                                   [data]="[5, 10, 15, 20]"
                                   [color]="'#84bfab'">
          </kendo-chart-series-item>
        </kendo-chart-series>
      </kendo-chart>

**Comment by danielkaradachki** [comment]
The repository is for bug reports only and the issue does not seem related to the Kendo Angular components but rather to the component configuration. Similar errors are thrown if the component does not declare the properties used in the template or the properties are not public. I hope this helps. If you need any further assistance please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

**Comment by TUSHARDM** [comment]
Thank you Your comment helped to solve build issue. It was necessary to declare all associated names in .ts file of the respective component even though package was already in place. :-)
