### ISSUE TITLE
NumericTextBox with ReactiveForms disabled not working

### ISSUE THREAD

**Issue by rstabenow** [telerik/kendo-angular#250]
If the disabled state is set for the FormControl or parent, the NumericTextBox remains editable, without writing to the model or validation.

[http://plnkr.co/edit/F2iXnviRyi3DuPnZFPFQ?p=preview](http://plnkr.co/edit/F2iXnviRyi3DuPnZFPFQ?p=preview)

**Comment by KirilNN** [comment]
Probably related to https://github.com/telerik/kendo-angular/issues/120

**Comment by rohit-b** [comment]
even in dynamic forms does not work

**Comment by tsvetomir** [comment]
It appears to be working with the latest version, [see plunkr](http://plnkr.co/edit/89GxRAtKyHKDbL8opL10?p=preview).
