### ISSUE TITLE
[Editor] The value is not properly updated

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2500]
**Describe the bug**
When using double binding for the [(value)] input property the value is not updated until a button from the toolbar is clicked. The (valueChange) is also fired only after a button from the toolbar is clicked.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-ty8dp1?file=app/app.component.ts

**Comment by svetq** [comment]
seems related to #2496

**Comment by valchev** [comment]
The issue is fixed in v0.9.0. For more information please follow the discussion in telerik/kendo-angular#2346
