### ISSUE TITLE
DialogService.open with height and width options set renders corrupted style attribute

### ISSUE THREAD

**Issue by IT-CASADO** [telerik/kendo-angular#2502]
**Describe the bug**
DialogService.open with height and width options set renders corrupted style attribute

**To Reproduce**
Open this [snippet](https://stackblitz.com/edit/angular-r458rd)
Open the dialog
Inspect the dialog div container with class="k-dialog"

**Expected behavior**

Instead of **style="height:200px;width:200px;0:height;1:width;height:200px;width:200px;"**

I'm expecting this: **style="height:200px;width:200px;"**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [Chrome]
 - Version [Version 77.0.3865.90]

**Comment by Raisolution** [comment]
Hi @IT-CASADO ,

We inspected the problem and it is related to an issue in the angular animations package. Here is a [reference to the issue](https://github.com/angular/angular/issues/27958) so you could follow it's progress.
