### ISSUE TITLE
[DateInput/Picker] Clicking in field when using placeholder selects wrong segment

### ISSUE THREAD

**Issue by davidda** [telerik/kendo-angular#2503]
**Describe the bug**
When you use a date imput with a placeholder, e.g. "enter a date" and then click with the mouse on this field it will not select the first format segment but select the invisible, underlying format segment at cursor position. Often, it also just selects the last segment.

**To Reproduce**
Go to the documentation webseite: https://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/placeholders/

Click into the field and out of it a few times at different positions within the field and observe the erratic behaviour.

**Expected behavior**
When no date is present and a custom placeholder is set, clicking into the field must position the focus on the first date segment so the user can begin entering the date.

**Browser**
 - Tried in Firefox 68

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-dateinputs`

**Comment by dimitar-pechev** [comment]
Released in **v4.3.0**.

**Comment by mbechev** [comment]
I am reopening this issue, as the described behavior is still reproducing in Firefox `v120.0`.
Regardless of where the user clicks the placeholder, the last segment is focused:

https://stackblitz.com/edit/angular-5b5plb-qowecl

In Chrome the segments are focused depending on where the pointer is.

**Comment by tswetti** [comment]
Fixed in [v15.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.0.0)

**Comment by destus90** [comment]
@tswetti @mbechev @svetq 

Still couldn't focus on a month in Firefox 120+ when datepicker`s format is set.

https://stackblitz.com/edit/angular-3plajd-tnclei?file=src%2Fapp%2Fapp.component.ts

**Comment by tswetti** [comment]
Hi, @destus90. This issue is related to the [`placeholder`](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DatePickerComponent/#toc-placeholder) property. If you need assistance with the [`format`](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DatePickerComponent/#toc-format) property, please open a ticket in our [support system](https://www.telerik.com/account/support-tickets).
