### ISSUE TITLE
KendoEditor -> new iframe mode -> value not update on ngModel

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2504]
**Describe the bug**
New kendo editor enables new iframe mode (default enabled) but with ngModel there is no way to get back model value.

**To Reproduce**
Just see:
https://stackblitz.com/edit/angular-1nsqz1

content1 value is not update

**Expected behavior**
Just it works as content2 (iframe disabled)

**Comment by danielkaradachki** [comment]
Related to: 
https://github.com/telerik/kendo-angular/issues/2500
https://github.com/telerik/kendo-angular/issues/2496

**Comment by valchev** [comment]
Hi @meriturva 

Thank you for bringing this to our attention, we'll do our best to provide a fix in a short period of time.

**Comment by valchev** [comment]
The issue is fixed in v0.9.0. For more information please follow the discussion in telerik/kendo-angular#2346
