### ISSUE TITLE
[DateInputs] Changing the value 'max' is bound to does not update the validity

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2505]
When the `max` input is used, and an invalid date is entered in the DateInput, the control is correctly invalidated. However, when the value the `max` input is bound to is updated so that the control should become valid again, it does not:

https://stackblitz.com/edit/angular-z2dv2p-38vjhg?file=app/app.component.ts

1. Enter an out-of-range date (e.g. 4/10/2001) in the left-hand side DatePicker // becomes invalid
2. Enter a new date in the right-hand side DatePicker so that the value, entered in the other DatePicker should become valid (e.g. 6/10/2001)

As a workaround, the value the first DatePicker is bound to can be reset to a new Date instance when the value of the second DatePicker is changed:

https://stackblitz.com/edit/angular-z2dv2p-gvsfvr?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
Shipped with **v4.2.0**.
