### ISSUE TITLE
Toolbar [resizable]="true" renders incorrectly with custom toolbar button

### ISSUE THREAD

**Issue by lucasheight** [telerik/kendo-angular#2507]
**Describe the bug**
When using the toobar with custom toolbar buttons the popup appears hidden.

**To Reproduce**
1. Create a custom toolbar as per the [Sample Documentation](https://www.telerik.com/kendo-angular-ui/components/toolbar/control-types/#toc-custom-control-types):
1. Add the control to the toolbar
`    <kendo-toolbar [resizable]="true">
        <custom-tool [text]="'Search'"></custom-tool>
        <custom-tool [text]="'Search'"></custom-tool>
        <custom-tool [text]="'Search'"></custom-tool>
        <custom-tool [text]="'Search'"></custom-tool>
    </kendo-toolbar>
`
1. Make the toolbar resizable `[resizable]="true"`
1. Change browser window size to force the toolbar to be responsive.
1. Click the ... button on the right.

Here's a fork from the sample:
https://stackblitz.com/edit/angular-veercb?file=app/app.component.ts

**Expected behavior**
Expected that the popup would function the same as when using a standard toolbar button

**Screenshots**

**Browser**
 - OS: Win10
 - Browser Chrome
 - Version [for example, 22]

**Additional context**

**Comment by PetarMetodiev** [comment]
Hey Lynden ,
I have answered to this question through our support system, but will post my answer here as well so people who face the same issue will know what to do:

> The issue here is that the toolbar does not know how to render a custom tool in the overflow popup. We have an example on how to add custom tools to the overflow popup in our development site here(the last example on the page) - https://www.telerik.com/kendo-angular-ui-develop/components/toolbar/control-types/#toc-custom-control-types. We had some issues with our demos which prevented us from uploading the updated docs on the toolbar. Sorry for that. We will have the docs on the site updated until the end of the week.

**Comment by lucasheight** [comment]
Thanks, works great.
