### ISSUE TITLE
TreeView parent checkbox doesn't uncheck children in collapsed state

### ISSUE THREAD

**Issue by amelyanenka** [telerik/kendo-angular#2509]
**Description**
When clicking a checkbox with child nodes in collapsed state, it doesn't uncheck itself and doesn't uncheck it's child nodes.

**Steps to Reproduce**
Example: https://stackblitz.com/edit/angular-wuhq3w

 1. Expand the Furniture node
 2. Check any child nodes (eg. Sofas)
 3. Collapse the Furniture node - it's in indeterminate state and collapsed.
 4. Click the Furniture node
 5. Instead of clearing the checkbox, it's in checked state.
 6. Not expanding, uncheck  the Furniture node 
 7. Instead of clearing the checkbox, it's in indeterminate state.
 9. Expand the Furniture node - checked child still persists. 

**Expected behavior**
If collapsed parent node in indeterminate state is clicked, it should be unchecked, and all it's child nodes should be unchecked. 
*As an example of desired checkbox behavior you may look in Windows in "Turn Windows features on or off"*

**Screenshots**
![image](https://user-images.githubusercontent.com/46417521/66046268-167c1e00-e52e-11e9-9782-4306b8ac022c.png)

> *Collapse*

![image](https://user-images.githubusercontent.com/46417521/66046585-c18cd780-e52e-11e9-8b22-68745f259824.png)

> *Click*

![image](https://user-images.githubusercontent.com/46417521/66046616-cea9c680-e52e-11e9-9650-58cf3aa9e11b.png)

> *Another Click*

![image](https://user-images.githubusercontent.com/46417521/66046652-e1240000-e52e-11e9-9eaf-b3f42c354c82.png)

**Browser**
 - OS: Win 10
 - Browser: Chrome

**Comment by amelyanenka** [comment]
There is a similar ticket #2387

**Comment by tsvetomir** [comment]
Indeed, this seems to be the same issue as #2387, closing as duplicate.
