### ISSUE TITLE
MultiSelect - If source changes you can't remove selected item(s)

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#251]
If have a selected item in the multiselect, change the source and then try to remove an item that was from the previous source you can't remove it. In the plunker example i just modified your example for binding. When example loads, just click the change source button and then try to remove baseball from the multiselect. It wont let you.

http://plnkr.co/edit/eJPLnQQ121rQ9LCHooKe?p=preview

**Comment by djarekg** [comment]
Do you know what package version this will be available in?

**Comment by KirilNN** [comment]
The latest version.
