### ISSUE TITLE
NumericTextBox Percentage Input Displays correct value, but is inputted as 0.xx

### ISSUE THREAD

**Issue by PjMitchell** [telerik/kendo-angular#2511]
NumericTextBox for the percentage format looses the percentage format as soon as you edit or use the step button.
This is not a good ui experience and the lay user may not understand why 100% has become 1, and why they must enter 0.5 to get 50%.
To enter 50% the user should just be able to type 50

**Comment by dtopalov** [comment]
Hi @PjMitchell,

This is the expected and default behavior of the percentage ('p') number format:

"The "%" specifier—A percentage placeholder. It multiplies a number by 100 and inserts a localized percentage symbol in the result string.

The % symbol is interpreted as a format specifier in the format string. To prevent this, precede the % symbol with a double backslash—formatNumber(12, "# \\\\%") resulting in 12 %."

https://github.com/telerik/kendo-intl/blob/master/docs/num-formatting/index.md

The same custom format can be provided to the NumericTextBox too, e.g.:

`<kendo-numerictextbox
            format="#\\%"
            [value]="value"
            [min]="0"
        ></kendo-numerictextbox>`

https://stackblitz.com/edit/angular-vwuupm?file=app/app.component.ts

**Comment by PjMitchell** [comment]
Hi @dtopalov 
I do not think I explained the issue well enough.
I understand how the percentage number format works and this is why I do not consider this issue a bug, but a feature request.
My issue is that the user experience is terrible for this control while using the percentage number format.
The user will see 50% in the user control then as soon as they start editing it, it will be 0.5.
While programmers who understand the percentage format will understand what is going on, lay users, the people who will actually use the app will be confused.

The solution given is not ideal as it requires having a display value, and an actual value in code and having to keep them in sync.
As it stands that may be the only way to use this control, but it does also mean that there is no reason why any developer wanting a good UX would use the NumericTextBox with percentage format.

**Comment by dtopalov** [comment]
@PjMitchell indeed, I understand your concerns, and that the current behavior might seem unexpected to unaware users, but the component is designed to display the formatted value when not focused/edited, and the real underlying value/model when focused. As the real numeric value behind 50% is 0.5, this is displayed when the component is focused.

As this repository is for bug reports only, please open a ticket in our [support system](https://www.telerik.com/account/support-tickets/my-support-tickets) if you have further questions about using our components or adapting them to various scenarios and use cases. Also, feel free to submit any feature requests to our dedicated [Feedback portal](https://feedback.telerik.com/kendo-angular-ui).

**Comment by Habeeb57** [comment]
Why ,when i enter 1 , it is showing 100%, what is this logic, how to set 1 means 1, 20 means 20...etc ?
