### ISSUE TITLE
Dropdownlist changes original primitive value if value is not found in list items

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#2514]
**Describe the bug**
When using a primitive value in a list of objects, if a value passed in is not found in the list, that value is changed to null.

**To Reproduce**
In the following Stackblitz:
1. Change the selected value from 3 to 4.
2. Open and close the dropdown. 
Result: You'll notice in the HTML that the {{ selectedValue }} is now null/blank.
https://stackblitz.com/edit/angular-xmdzfg?file=app/app.component.ts

**Expected behavior**
The dropdown should not affect the original value passed in. This causes issues in my code.

@progress/kendo-dropdownlist: 3.4.0

**Comment by LaniMoo** [comment]
Just a note: I edited the original post to make the steps more clear.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
Available in **v4.2.7**.
