### ISSUE TITLE
[Grid] Pager Input allows non-numeric values and has no validation

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2515]
The built-in Grid Pager Input (when the pager type is 'input' or used as a [standalone component](https://www.telerik.com/kendo-angular-ui/components/grid/api/PagerInputComponent/) in the UI) allows non-numeric characters and also does not limit the value to the possible number of pages. Also, negative numbers are allowed.

It would make much more sense the input to be either of type number, or a NumericTextBox with the respective min/max restrictions.

**Comment by siyka-marinova** [comment]
Fix is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `@progress/kendo-angular-grid` package
