### ISSUE TITLE
Upload and initial file list inside ngForm -> no file shown

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2518]
When Upload component with ngModel for the initial file list is composed inside a ngForm no files are shown.

https://stackblitz.com/edit/angular-iyad7t

**Comment by Raisolution** [comment]
Hi @meriturva,

The reason for the observed behavior is that the component is missing a `name` attribute. The resolutions are described in the console error.

**Comment by meriturva** [comment]
It's really too late to develop! Thanks again and sorry!
