### ISSUE TITLE
Filter button on multicheck filter example for grid remains disabled when selecting a null item

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#2519]
**Describe the bug**
I'm using the multicheck filter as seen in this example [here](https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-multi-checkbox-menu-filtering). I'm trying to add a null (displayed as "None") option to the multicheck filter, but when I select that option, the "Filter" button remains disabled.

**To Reproduce**
Select the filter for the Category column and select "None".
https://stackblitz.com/edit/angular-wxukcr?file=app%2Fapp.component.ts

@progress/kendo-angular-grid: 3.14.0

**Comment by LaniMoo** [comment]
Please let me know if there is a workaround for this. Thank you!

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

**Comment by LaniMoo** [comment]
I was certain that the fact that the filter button remains disabled is a bug? Please let me know if I’m mistaken. Thank you!

On Oct 7, 2019, at 11:51 PM, Daniel Karadachki <notifications@github.com> wrote:

﻿

The repository is for bug reports only. Please open a support ticket<https://www.telerik.com/account/support-tickets> for assistance with implementing specific scenarios or configuration.

**Comment by LaniMoo** [comment]
@danielkaradachki Please confirm.

**Comment by danielkaradachki** [comment]
The behavior expected filter descriptors with null or empty value are ignored. To apply null filter change the [operator](https://www.telerik.com/kendo-angular-ui/components/dataquery/api/FilterDescriptor/#toc-operator).
