### ISSUE TITLE
MultiSelect - kendo-searchbar is too wide and causes uneccessary wrapping

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#252]
The kendo-seachbar is to wide and causes the multiselect to wrap it to a second line with the selected item is not that wide. It makes the UI look weird.

![image](https://cloud.githubusercontent.com/assets/671093/22478551/62a4a566-e7b8-11e6-9319-cb5f5673cf35.png)

**Comment by KirilNN** [comment]
This is a side effect of using the input size [attribute](https://developer.mozilla.org/en/docs/Web/HTML/Element/input) for resizing the searchbar as you type. The browser always leaves padding, that grows depending on the width of the text.

We will try to push a fix, that should better accommodate this behavior.

**Comment by djarekg** [comment]
Can you let me jnow when ut is available and what package version?

**Comment by KirilNN** [comment]
The issue will be updated with more information as it becomes available.

**Comment by KirilNN** [comment]
Please test with latest version - `0.27.3`
