### ISSUE TITLE
Virtual scrolling PageChangeEvent not triggering when scrolling

### ISSUE THREAD

**Issue by PraisyA** [telerik/kendo-angular#2523]
I just try with sample which is provided by Telerik example for Grid virtualization , Data was binding correctly but when i scroll down nothing is happening . 
i tested this with fallowing dependencies
**Angular 8 
Typescript** 

 "dependencies": {
    "@angular/animations": "^8.2.1",
    "@angular/common": "^8.2.1",
    "@angular/compiler": "^8.2.1",
    "@angular/core": "^8.2.1",
    "@angular/forms": "^8.2.1",
    "@angular/http": "7.2.15",
    "@angular/platform-browser": "^8.2.1",
    "@angular/platform-browser-dynamic": "^8.2.1",
    "@angular/platform-server": "^8.2.1",
    "@angular/router": "^8.2.1",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "@progress/kendo-angular-buttons": "^5.0.0",
    "@progress/kendo-angular-common": "^1.1.0",
    "@progress/kendo-angular-dateinputs": "^4.1.0",
    "@progress/kendo-angular-dropdowns": "^4.2.0",
    "@progress/kendo-angular-excel-export": "^3.0.1",
    "@progress/kendo-angular-grid": "^4.3.0",
    "@progress/kendo-angular-inputs": "^6.3.0",
    "@progress/kendo-angular-intl": "^2.0.0",
    "@progress/kendo-angular-l10n": "^2.0.0",
    "@progress/kendo-angular-pdf-export": "^2.0.0",
    "@progress/kendo-angular-popup": "^3.0.1",
    "@progress/kendo-data-query": "^1.5.2",
    "@progress/kendo-drawing": "^1.6.0",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^3.4.1",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },

did i miss anything ..?

Thanks

**Comment by danielkaradachki** [comment]
Could you clarify which example? The [virtual scrolling demo](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/) utilizes the pageChange event and works as expected.

**Comment by PraisyA** [comment]
Danielkaradachki Thank you for responding .
I just use telerik site live example , [here ](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/)is the link which i tested .


Thanks.

**Comment by danielkaradachki** [comment]
Hi, 

I was testing with the same demo but it seems to work as expected. I created an example from the demo which logs the pageChange event:

https://stackblitz.com/edit/angular-tbbi2n?file=app/app.component.ts

and recorded a [screen cast](https://www.screencast.com/t/PxftsNCNH) that demonstrates the behavior on my side. Am I missing something? Also, does the problem occur in specific browser?

**Comment by PraisyA** [comment]
Danielkaradachki ,
 I just create a new project in Angular and install all Kendo Components **@progress/ Kenod- component name**  then i just copy and paste  the sample into newly created project in  app.component.ts file , then run the ng server command from pwoershell window . 
project launched in Chrome  ( Version 77.0.3865.90 (Official Build) (64-bit)) .
see attached  file.
![KendoVirtualization](https://user-images.githubusercontent.com/30825040/66634323-73608e00-ec2a-11e9-8c4b-1f71915ae8e7.PNG)

 should i install any special components ...?

Thanks

**Comment by PraisyA** [comment]
Danielkaradachki ,
I have attached node_modules which i install in @progress folder . did i miss any components .
please check below picture 
![Node_modules](https://user-images.githubusercontent.com/30825040/66634650-216c3800-ec2b-11e9-9b7c-1a9c02fa0fd1.PNG)


Thanks

**Comment by PraisyA** [comment]
Danielkaradachki ,
I created an example and here also i got same exception ( not triggering the  pageChange event ), Can you please check below link in stackblitz.

https://stackblitz.com/edit/angular-dgn6cm

Thanks

**Comment by danielkaradachki** [comment]
It seems that you have not loaded the theme:
https://www.telerik.com/kendo-angular-ui/components/styling/

which is required in order for the components to work correctly. Once the theme is included, the grid seems to function as expected:

https://stackblitz.com/edit/angular-u8qjz4?file=src/index.html

**Comment by PraisyA** [comment]
Danielkaradachki ,
 After adding the theme it is working , thanks for supporting to solve this issue .



Thanks.

**Comment by PraisyA** [comment]
Hello Danielkaradachki,
I got an issue after use loading the Theme , my custom UI totally break with latest Theme , how should i use theme with out break my custom UI .  Below one is the Kendo theme 
![VirtualizationMessupic](https://user-images.githubusercontent.com/30825040/67461279-93e10d00-f65a-11e9-96b7-d1fe184e184f.PNG)

Here is my Custom theme pic.
![MyCustomTheme](https://user-images.githubusercontent.com/30825040/67461488-18cc2680-f65b-11e9-80d1-57f0868e7283.PNG)

Please suggest me , what is the best way to use Kendo theme for Virtualization without break my Custom theme .



Thanks in Advance
