### ISSUE TITLE
[Grid] keyboard navigation doesn't allow entering footer cells

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2525]
**Describe the bug**
When adding a footer template to a navigable Grid, it isn't possible to focus the cells within the footer template by using the arrow keys. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-57q3o3?file=app/app.component.ts

1. Try to navigate to the footer cells using the keyboard.

**Comment by dtopalov** [comment]
Fix is available in the [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the @progress/kendo-angular-grid package.

**Comment by Raisolution** [comment]
Fix available in `v4.8.3` of the `kendo-angular-grid` package.

**Comment by ukholic** [comment]
@Raisolution @dtopalov 
The same issue is present in the Kendo UI jQuery Grid component.

Example:
https://dojo.telerik.com/@urvashi_parmar/azEfuqUK

1. Try using the keyboard to navigate to the cells in the footer.
2. The screen reader(JAWS) does not recognize the content in the grid's footer.
