### ISSUE TITLE
[Grid] Horizontal scrollbar does not appear when resizing window even if all columns have set width

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#2526]
**Describe the bug**
According to the [documentation](https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/), "to enable horizontal scrolling, set the width of all columns." and "When all column widths are explicitly set and the cumulative column width is greater than the available Grid width, a horizontal scrollbar appears and all set column widths are respected."

In the very example provided by Kendo, resizing the window does not make the horizontal scrollbar appear.

**To Reproduce**
Resize frame until grid width is wider than frame width:
https://stackblitz.com/edit/angular-bk4b1e?file=app/app.component.ts

Browser: Chrome version 77.0.3865.90

**Comment by dtopalov** [comment]
@LaniMoo Both horizontal and vertical scrollbars appear as expected except on Mac OS/iOS devices - this is an OS-specific design according to which the scrollbars are visible only during scrolling (you can observe the same behavior and layout with any scrollable element, e.g. - a regular DIV).
