### ISSUE TITLE
Wrong tooltip position in chart component

### ISSUE THREAD

**Issue by kevel** [telerik/kendo-angular#253]
I have created kendo angular 2 grid with charts inside cells. And It seems that @Input  [pageSize]="pageSize" affects on chart tooltip position. Just compare:
http://plnkr.co/edit/FMawelhvqPSTGRy5eZDp?p=preview
http://plnkr.co/edit/crUYIZ5tmZNMmsovrVGF?p=preview

There is more real example:
![wrong_tooltip](https://cloud.githubusercontent.com/assets/413581/22480028/0a5444f4-e801-11e6-938a-90e36cb8f69f.png)

**Comment by danielkaradachki** [comment]
Thank you for pointing out this issue. Seems to be caused by the transform style on the grid table. We will look into it and I will follow up once there is more info.

**Comment by danielkaradachki** [comment]
The problem should now be fixed. Please try with the latest version.

**Comment by kevel** [comment]
Yes, all works fine, thanks. Issue can be closed.
