### ISSUE TITLE
PDF Export: Exporting hidden elements sometimes results in incorrect page breaks, and all but the first page of elements being cut off

### ISSUE THREAD

**Issue by dannymcgee** [telerik/kendo-angular#2530]
**Describe the bug**
When attempting to switch elements from hidden (by default) to visible (for export), via a variety of different methods, the resulting PDF only has one page, with no bottom margin, and all elements that should have been broken onto additional pages are missing from the document.

**To Reproduce**
1. See the example here: https://stackblitz.com/edit/angular-nwvumi
2. Try removing the conditional `hidden` class from the `article` — the PDF export now works as expected
3. Try using different CSS rules for hiding/showing the additional articles, such as `visibility: hidden`, `position: absolute` with an extreme offset, etc. It appears that only rule changes that would require re-calculating the height of the content cause the issue to occur.

**Expected behavior**
See step 2. in the "To Reproduce" section.

**Screenshots**
![PDF Export Issue](https://i.imgur.com/KrWwXQx.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome 77
 - Version: `"@progress/kendo-angular-pdf-export": "^1.3.0"` (also reproducible in Stackblitz demo with version 2.0.0)

**Comment by danielkaradachki** [comment]
You should use the [kendo-pdf-document](https://www.telerik.com/kendo-angular-ui/components/pdfexport/content-styling/#toc-using-the-pdf-document-element) selector for multi-page output:
https://stackblitz.com/edit/angular-nwvumi-1snnia?file=app/app.component.ts

**Comment by dannymcgee** [comment]
Thanks @danielkaradachki ! That plus disabling view encapsulation (instead of just using `::ng-deep` on the single selector) fixed it for us. I missed the distinction between the `kendo-pdf-document` and `.k-pdf-export` selectors in the documentation, sorry for the oversight.
