### ISSUE TITLE
Incorrect Date calculation and view in IE and Chrome

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2531]
**Describe the bug**
When we set max value for a date range in code the chrome browser opens in the usual way for second date popup whereas in IE the same popup opens for July month but without a date selected. Something unusual in the behavior of calender popup. 

**To Reproduce**
Use code below to reproduce with regular packages of kendo angular ui.

import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    template: `
        <div class="example-config">
            Selected value is: {{value | kendoDate:'MM/dd/yyyy'}}
        </div>
        <div class="example-wrapper" style="min-height: 100px">
            <p>Select a date:</p>
            <kendo-datepicker
                [(value)]="value"
            ></kendo-datepicker>
            <p>(use Alt+↓ to open the calendar, ← and →  to navigate, ↑ to increment and ↓ to decrement the value)</p>
        </div>
        

            <p>Select a date:</p>
            <kendo-datepicker
            [(value)]="value"
                [min]="min"
                [max]="max"
            ></kendo-datepicker>
    `
})
export class AppComponent {
   public min: Date = new Date(2000, 2, 10);
    public max: Date = new Date(9999, 11, 31);
    public value: Date = new Date(9999, 11, 31);
}

**Expected behavior**
The Selected Date should behave as in second date popup in chrome i.e. with popup opening with december date selected and a exact year. And for the first date popup if date could be corrected.

**Screenshots**

**Browser**
 - OS: Windows
 - Browser IE 11.1006.17134.0 ----> Wrong behaviour for second popup
 - Browser Chrome Version 77.0.3865.90 (Official Build) (64-bit) ----> Correct behaviour for second popup
 - Browser IE, and chrome first popup date shows wrong. (May be a default date sequence problem in my case.(Correct me if i am wrong.))

**Additional context**
![correct-behaviour-for-chrome-date-in-second-popup](https://user-images.githubusercontent.com/5736855/66806152-6d2d2300-ef44-11e9-91bc-180333459457.PNG)
![wrong-behaviour-of-date-popup-in-ie-11](https://user-images.githubusercontent.com/5736855/66806162-74543100-ef44-11e9-9dff-b4d51bb4f2cf.PNG)

**Comment by danielkaradachki** [comment]
There doesn't seem to be much we can do about this. Due to the large range, the calendar hits the IE max scroll limit:
https://stackoverflow.com/questions/34931732/height-limitations-for-browser-vertical-scroll-bar

**Comment by TUSHARDM** [comment]
The same behavior appears In Edge as well as firefox and safari. Just works in chrome. is it kendo calendar control limitation or browser compatibility issue. can it be removed by writing custom code for other browsers in javascript or using css.

**Comment by danielkaradachki** [comment]
Chrome has the biggest limit. That is why the issue is not visible there. We are not aware of any way to overcome this browser limitation. The only option that I can suggest is to narrow the range.

**Comment by TUSHARDM** [comment]
ok, Thanks for reply :-)
