### ISSUE TITLE
[Multiselect] Cursor goes on new line inconsistently

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2533]
**Describe the bug**
When some value is type within the input of the Multiselect component and an item is selected, then the cursor sometimes goes on a new line depending on the length of the initially typed text within the input. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-z9cosc-wylvjr?file=app/app.component.ts
1. Copy "QATestAu" and paste it within the input.
2. Press "Enter".
3. Remove the selected item.
4. Copy "QATestAut" and paste it within the input.
5. Press "Enter" and observe how the cursor goes on a new line.

**Comment by dimitar-pechev** [comment]
Fixed in **v4.2.1**.
