### ISSUE TITLE
PopupSettings are not respected for ToolbarDropDownButtonComponent and ToolbarSplitButtonButtonComponent 

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2536]
**To Reproduce**
Example:
https://stackblitz.com/edit/angular-1r7zgy

**Expected behavior**
When clicked, the dropdown button in the toolbar should open a popup without animations and with custom popup class, similarly to the regular DropDownButton and SplitButton.

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-toolbar` v.2.2.1
