### ISSUE TITLE
ToolbarDropDownButtonComponent and ToolbarSplitButtonComponent are not disabled in the overflow popup

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2537]
**To Reproduce**
https://stackblitz.com/edit/angular-5qfvvg

For the ToolbarSplitButtonComponent:
https://stackblitz.com/edit/angular-omqp19

**Expected behavior**
The ToolbarDropDownButtonComponent should be disabled both in the toolbar and in the overflow popup when set.
The items in the ToolbarSplitButton should be disabled in the overflow popup when set.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-toolbar`

**Comment by siyka-marinova** [comment]
Fix is now also available in `kendo-angular-toolbar v3.0.0`
