### ISSUE TITLE
Accessibility issues with ToolbarDropDownButtonComponent in overflow popup

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2538]
**Describe the bug**
When the ToolbarDropDownButtonComponent has disabled items, they receive `aria-disabled="true"` attribute in the toolbar, but not in the overflow popup.

**To Reproduce**
https://stackblitz.com/edit/angular-5qfvvg-grs5p3

**Expected behavior**
Disabled items in a ToolbarDropDownButtonComponent should receive `aria-disabled="true"` both in the toolbar and the overflow popup.

related to https://github.com/telerik/kendo-angular/issues/2537

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).

**Comment by Raisolution** [comment]
Fix has been released in `v3.1.1`
