### ISSUE TITLE
[Grid] activeCell rowIndex is inconsistent when using kendoGridDetailTemplateShowIf directive

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2539]
**Describe the bug**
When using the kendoGridDetailTemplateShowIf directive in order to add dynamically a detail template then even if the detail row is not displayed, it will be counted towards the rowIndex property of the activeCell.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-pspfyv?file=app/app.component.ts

1. Click the third row and check the value of activeCell.rowIndex.

**Comment by Raisolution** [comment]
The behaviour is expected and is related to the internal implementation of the Grid keyboard navigation.
