### ISSUE TITLE
ComboBox allowCustom with complex data

### ISSUE THREAD

**Issue by aarmora** [telerik/kendo-angular#254]
```
 public departments: any = [
        {
            id: "1a",
            name: "Maths"
        },
        {
            id: "1b",
            name: "Keyboarding"
        }
    ];

<kendo-combobox [data]="departments" 
        [textField]="'name'"
        [valueField]="'id'"
		[value]="selectedDepartment" 
		[(ngModel)]="selectedDepartment"
		[allowCustom]="true">
    </kendo-combobox>
```

Maybe I am not implementing this correctly, but it seems that complex data cannot be used with allowCustom. When a custom option is added, nothing shows up (which makes sense because there is no value with the newly create custom option). If you select one of the normal options and then choose a custom option then the follow exception is thrown:

` Expected initial value of type Object`

Are custom values currently implemented with complex data?

A workaround that I can use is just strip the names from the array of objects and build a simple array and then match it to the correct object once the option is selected. This seems pretty clunky and I hope will not be necessary.

Thanks in advance!

**Comment by tapopov** [comment]
Hello @aarmora,

Custom values are supported, however we are still working on the documentation, which is a bit lacking at this point. Basically, working with objects creates the following problem - what the component's value should be? The text? What if the `valueField` is expected to be a number? This is where the [valueNormalizer](http://www.telerik.com/kendo-angular-ui/components/dropdowns/api/ComboBoxComponent/#toc-valuenormalizer) comes into play. It's a user-defined function which is responsible for generating a value that is expected with the current component configuration. [Here](http://plnkr.co/edit/CwZo5dlYtb4hX0zUxMXs?p=preview) is a very simple example illustrating the approach.

**Comment by aarmora** [comment]
@tapopov Thanks for the response. This works perfectly!
