### ISSUE TITLE
[NumericTextbox] null max value set the FormControl in error

### ISSUE THREAD

**Issue by Felx-B** [telerik/kendo-angular#2540]
**Describe the bug**
When max value is bound with a `null` value on init, NumericTextBox component set the controlform in error

This is not the case if we set the max value to `undefined`

**To Reproduce**
A stackblitz link worth a thousand words :) 
https://stackblitz.com/edit/angular-numericmaxvalue

**Expected behavior**
`null` max value should be ignored in validation, like the `undefined` value

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 77

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-inputs`.

**Comment by dtopalov** [comment]
Available in v.6.7.0
