### ISSUE TITLE
Missing package in editor docs

### ISSUE THREAD

**Issue by Eastrall** [telerik/kendo-angular#2541]
Hello Telerik team,

I tried to install the Kendo UI Angular Editor (Beta) and tried to install it manually via the `npm` command as suggested in the documentation: https://www.telerik.com/kendo-angular-ui/components/editor/#toc-manual-setup

I believe there is a missing package in the documentation which is: `@progress/kendo-angular-layout@^4.0.0` , because `npm` displays this warning:

> npm WARN @progress/kendo-angular-editor@0.9.0 requires a peer of @progress/kendo-angular-layout@^4.0.0 but none is installed. You must install peer dependencies yourself.

Is there any repository for Kendo UI Angular docs to contribute and fix the editor doc?

Thank you.

**Comment by valchev** [comment]
Hi @Eastrall 

Thank you for bringing this to our attention! The kendo-angular-editor repo is private, which is why the PR won't be possible.

I've updated the list of peer dependencies in the docs. The change will be available after the website is re-uploaded, most probably in a week.

**Comment by Eastrall** [comment]
Ok, I thought there might be an open-source repository **only** for documentation and once you push a change it automatically deploys the documentation with the changes. (Like a Markdown documentation for instance.)

**Comment by valchev** [comment]
@Eastrall after further investigation, it turned out that the `kendo-angular-layout` dependency is not used anymore in the editor package. I updated the `package.json` file and removed the obsolete dependency.

The fix is available in v0.10.1
