### ISSUE TITLE
[ScrollView] setting the width to a percentage value behaves inconsistently

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2548]
**Describe the bug**
When setting the width of the ScrollView to a percentage value, it is applied to the ScrollView container as well as to the <li> elements representing each image.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-jbunzx?file=app/app.component.ts

**Workaround**
Add the following custom CSS:

>     .k-scrollview li {
>      width: 100% !important;
>    }

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-scrollview`.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-scrollview v3.0.2`
