### ISSUE TITLE
Chart exportVisual() method options parameter

### ISSUE THREAD

**Issue by maciej-karpus** [telerik/kendo-angular#2552]
Referring to [this](https://www.telerik.com/forums/chart-colors-on-pdf-export#6jXkmBewQUa18kzemHloHw) answer exported chart content style can be customized using options object. I am able to change title color, chartArea color as well, but I am not able to change categoryAxis color.
I was trying something like this below:
```typescript
const visual = this.chart.exportVisual({
    options: {
        chartArea: {
            background: '#FFFFFF'
        },
        title: {
            color: '#656565'
        },
        categoryAxis: {
            labels: {
                color: '#656565'
            }
        }
    }
});
```

Help, please.

**Comment by danielkaradachki** [comment]
Could you provide the chart configuration? Changing the labels color seems to work here:

https://stackblitz.com/edit/angular-rf8ipn?file=app/app.component.ts

**Comment by maciej-karpus** [comment]
@danielkaradachki 
Thank you for such a quick response. It can be matter of using kendo-chart-category-axis inside kendo-chart to provide inline options to category axis. Without it, the styles are working.
```html
<kendo-chart-category-axis>
	<kendo-chart-category-axis-item type="date" [maxDivisions]="30">
		<kendo-chart-category-axis-item-labels rotation="auto" [format]="dateFormat">
		</kendo-chart-category-axis-item-labels>
	</kendo-chart-category-axis-item>
</kendo-chart-category-axis>
```

**Comment by danielkaradachki** [comment]
Right, the component creates array for the categoryAxis configuration so an array should be passed in order to change the options:
https://stackblitz.com/edit/angular-rf8ipn-blqwlv?file=app/app.component.ts

**Comment by maciej-karpus** [comment]
@danielkaradachki 
It works! You made (and saved) my day. Thank you so much!
