### ISSUE TITLE
grid horizontal scroll bar disappears in different chrome version

### ISSUE THREAD

**Issue by liuydyyy** [telerik/kendo-angular#2556]
**Describe the bug**
When changing the height of the Grid .the horizontal scrollbar disappears. The undesired behavior occurs only in some Google Chrome version，i test 4 version，chrome 60 or 77 is normal，but it is unnormal in chrome 70 or 73 version.

**To Reproduce**
https://stackblitz.com/run?embed=1&file=app/app.component.ts

to recurrence the problem，please use chrome version 73

**Comment by danielkaradachki** [comment]
Kendo Angular supports the same browser versions as [Angular](https://angular.io/guide/browser-support). For Chrome, this is the latest version and the issue seems like something that is already fixed by the browser.

**Comment by liuydyyy** [comment]
Since the project still uses version 73 of chrome, is there any way to avoid this problem on this version of Chrome?

**Comment by danielkaradachki** [comment]
We are not aware of any workarounds for the problem.
