### ISSUE TITLE
PopupService -> TemplateRef -> No way to pass context

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2557]
Hi to all,
we are working hard now to use a common and centralized approach to handle `contextMenu` on a big enterprise app.

Something related and already proposed on:
https://github.com/telerik/kendo-angular/issues/733

Now we are moving to a `templateRef` approach but the main problem is that `templateRef` is created by `popupService` with null context.

https://www.telerik.com/kendo-angular-ui/components/popup/api/PopupSettings/#toc-content

is it possible to have a way to pass a context with `templateRef` during the popup creation phase?

what do you think?

**Comment by danielkaradachki** [comment]
I am not sure if I understand the exact scenario but template can access the context of the component in which it is created. We haven't considered adding the possibility to pass template context so far. Please open a feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui) so we can track the interest in such feature.

**Comment by meriturva** [comment]
We just would like to use `templateRef` with customization based on row `dataitem`, not a Component class with `instance` property access after creation to set few properties.
