### ISSUE TITLE
[PDF export] Images with SVG content don't export in Internet Explorer

### ISSUE THREAD

**Issue by uranium62** [telerik/kendo-angular#2562]
Hi guys,
We have a problem with the export of images with SVG content in IE. If the document has such image in the IE the image doesn't export. In all other browsers, it works fine.

```
<img src="data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjE4IiBoZWlnaHQ9IjE4IiB2aWV3Qm94PSIwIDAgMjQgMjQiIGZpbGw9IiM4ZDhkOTciPgo8cGF0aCBkPSJNMTYgN3Y3LjU4NmwtOC4yOTMtOC4yOTNjLTAuMzkxLTAuMzkxLTEuMDI0LTAuMzkxLTEuNDE0IDBzLTAuMzkxIDEuMDI0IDAgMS40MTRsOC4yOTMgOC4yOTNoLTcuNTg2Yy0wLjU1MiAwLTEgMC40NDgtMSAxczAuNDQ4IDEgMSAxaDEwYzAuMTM2IDAgMC4yNjUtMC4wMjcgMC4zODMtMC4wNzZzMC4yMjgtMC4xMjEgMC4zMjQtMC4yMTdjMC4wOTItMC4wOTIgMC4xNjYtMC4yMDIgMC4yMTctMC4zMjQgMC4wNDktMC4xMTggMC4wNzYtMC4yNDcgMC4wNzYtMC4zODN2LTEwYzAtMC41NTItMC40NDgtMS0xLTFzLTEgMC40NDgtMSAxeiI+PC9wYXRoPgo8L3N2Zz4K" />
```

**Steps to reproduce:**
1. Create a simple HTML document for pdf export
2. Add to the document image with SVG content.
3. Try to export it in Internet Explorer

**Example:**
https://stackblitz.com/edit/angular-8qxdbd

**Expected behavior:**
We expect what the image will export in IE, like other browsers.

**Browser**
 - OS: Windows 10
 - Browser: IE
 - Version: 11.805.17763.0

**Comment by tsvetomir** [comment]
The browser does not allow reading the image data, hence the blank output. This is a [known limitation](https://www.telerik.com/kendo-angular-ui/components/drawing/limitations-browser-support/#toc-general-behavior) of the PDF Export module:
> * Internet Explorer does not support the PDF export of .svg source files.

We'll edit the sentence to make it less ambiguous:
> * Internet Explorer does not support the PDF export of images loaded from SVG documents.

**Comment by uranium62** [comment]
Thanks, @tapopov.
We'll use another format of icons for pdf export.
