### ISSUE TITLE
Underline not continuing after SPACE on MS Edge

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2563]
**Describe the bug**
Underline modifier not continuing after SPACE entered

**To Reproduce**
1. Open https://www.telerik.com/kendo-angular-ui/components/editor/ in MS Edge
2. Clear all text
3. Click Underline modifier from toolbar 
4. Enter word ( it is underlined )
5. Press SPACE and continue with other word - it is not underlined

**Expected behavior**
Underline modifier should continue after SPACE

**Browser**
 - Windows
 - MS Edge

By user ticket

**Comment by dtopalov** [comment]
The problem is not reproducible with the more recent versions of the MS Edge browser (tested with Microsoft EdgeVersion 91.0.864.59 (Official build) (64-bit)).
