### ISSUE TITLE
Typing space inside Editor is not respected in Firefox

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-angular#2564]
**Describe the bug**
After typing space inside the editor, the text is appended and space is not added between the words.

**To Reproduce**

1. Open https://www.telerik.com/kendo-angular-ui/components/editor/ in Mozilla Firefox.
2. Clear all text.
3. Type some word and press space.
4. Type another word.
Result: The second word is appended to the first one without space in between.

**Expected behavior**
Space should be added when pressed.

**Screenshots**
https://www.screencast.com/t/cMgh6Rdq

**Browser**
 - Windows
 - Mozilla Firefox
 - Version 69.0.3

**Comment by valchev** [comment]
Duplicates telerik/kendo-angular#2227
