### ISSUE TITLE
A JavaScript error is thrown when using custom editor template

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#2565]
Can be seen in the demo:
https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/custom-reactive-editing/

Double click on any event or slot to replicate.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by siyka-marinova** [comment]
Fix is now available in the official package `kendo-angular-scheduler v1.1.0`
