### ISSUE TITLE
[Grid] Select-All feature does not work properly in IE 11

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2566]
**Describe the bug**
If there are any selected rows, clicking the select all checkbox in the header, uncheck all rows on the page instead of selecting them all (including the previously selected).

**To Reproduce**
Check the select all checkbox.
https://stackblitz.com/edit/angular-jvluev?file=app/app.component.ts

**Comment by dtopalov** [comment]
The fix is available in the [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the **kendo-angular-grid** package.

**Comment by Raisolution** [comment]
Available in `v4.8.3`
