### ISSUE TITLE
Timepicker is localized only partially

### ISSUE THREAD

**Issue by oliverhanappi** [telerik/kendo-angular#2567]
**Describe the bug**
Timepicker is localized only partially by default even though the localizations are present in the [GitHub repo](https://github.com/telerik/kendo-angular-messages/blob/develop/messages/timepicker/timepicker.de-AT.yml). It is necessary to use `<kendo-timepicker-messages>` for now, nowLabel, cancel, cancelLabel, accept and acceptLabel.

**To Reproduce**

1. Navigate to https://stackblitz.com/edit/angular-xbdnty
2. Open the timepicker popup
3. Observe that only the labels for Hour and Minute are localized, but neither Now, Cancel nor Set.

```ts
import { Component, Inject } from '@angular/core';
import { CldrIntlService, IntlService } from '@progress/kendo-angular-intl';
import "@progress/kendo-angular-intl/locales/de/all";

@Component({
    selector: 'my-app',
    template: `
        <kendo-timepicker></kendo-timepicker>
    `
})
export class AppComponent {
    constructor(@Inject(IntlService) intlService: CldrIntlService) {
      intlService.localeId = 'de';
    }
}
```

**Expected behavior**
The timepicker should be fully localized.

**Screenshots**
![timepicker](https://user-images.githubusercontent.com/401938/67597340-3e485580-f76b-11e9-9ecc-5fa4b628e05a.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 77

**Comment by danielkaradachki** [comment]
The Hours and Minutes are localized as part of the component formats loaded from kendo-angular-int. Check [this](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/) documentation topic for information on how to localize the components messages.
