### ISSUE TITLE
[Inputs] Incorrect position of the floating label on initialization

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2568]
**Describe the bug**
The floating label is placed on top when the component is initialized, the ._k-state-empty_ class is missing. If a value is entered and deleted afterward the floating label behaves as expected and the _.k-state-empty_ class is added.

**To Reproduce**
1. Enter a value in the input and blur.
2. Delete the value and blur.
The  _.k-state-empty_  class is added and the label is placed correctly

https://stackblitz.com/edit/angular-9grwak?file=app/app.component.ts

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by elena-gancheva** [comment]
Available in latest version of the package.
