### ISSUE TITLE
Odata support for DropDownList

### ISSUE THREAD

**Issue by CptArn** [telerik/kendo-angular#2569]
I'm submitting a...
Suggestion for improvement
Current behavior
https://www.telerik.com/kendo-angular-ui/components/faq/#toc-does-the-dropdownlist-support-odata
https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/data-binding/

The links above show we can use subset of Odata features with the dropdownlist.

What would be great if we could paging on the dropdownlist.

Expected behavior
We load a subset of items, (30), when we scroll to the bottom, we fetch another 30.

I believe this was possible in Kendo-UI

Minimal reproduction of the problem with instructions
The links provided above, should work. #odata #

**Comment by danielkaradachki** [comment]
Adding support for data virtualization is not currently planned. Please create a feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui) so we track the interest in such feature.
