### ISSUE TITLE
[Toolbar] Unable to add a class via the popupSettings of a ToolBarDropDownButtonComponent

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2570]
**Describe the bug**
Currently it is unable to add a custom class via the popupSettings of a ToolBarDropDownButtonComponent.

**To Reproduce**
Please check the following example and inspect the DOM:
https://stackblitz.com/edit/angular-kta74t-tivwdr?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-toolbar v2.2.1`
