### ISSUE TITLE
Combobox options remain filtered after selecting an option and leaving control

### ISSUE THREAD

**Issue by ksCookj** [telerik/kendo-angular#2572]
**Describe the bug**
When you select a value of the combobox via filtering. Once you tab off the control or leave focus, coming back and clicking the expand arrow still shows all options as filtered. 

**To Reproduce**
Use first example here: https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/filtering/

1. filter for "small" and tab off, selecting a value in the process
2. go back and expand combobox by clicking the expand arrow
3. All options are still filtered

**Expected behavior**
After filtering and leaving control (selecting a value in the process), going back and clicking the arrow to expand combo box should display all options.

**Comment by ipeshev** [comment]
Fix available in latest dev version.

**Comment by dimitar-pechev** [comment]
Released in **v4.2.6**.
