### ISSUE TITLE
Ivy support

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#2573]
Hi!
Can you please share some information how far is the Ivy support for Kendo-UI for Angular.

_There is already a [thread](https://github.com/telerik/kendo-angular/issues/2321), but is concentrate on Grid._

**Comment by tsvetomir** [comment]
The original issue was indeed opened for the Grid, but we're validating all components. See https://github.com/telerik/kendo-angular/issues/2321#issuecomment-547282939 for the latest status.

I'll update the issue title to reflect the scope.
