### ISSUE TITLE
[Scheduler] Agenda view displays one additional day

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2574]
**Describe the bug**
The Agenda view displays one additional day in the header of the Scheduler.

![image](https://user-images.githubusercontent.com/20015190/67842486-edd24e80-fb02-11e9-9819-1a88a0e75c5e.png)

**To Reproduce**
Please check the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/scheduler/views/agenda/

The end date should be 6/30/2019

**Comment by danielkaradachki** [comment]
Fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:

https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/views/agenda/

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-scheduler v1.1.0`
