### ISSUE TITLE
[Dropdowns] Virtual Scrolling Scrollbar always visible

### ISSUE THREAD

**Issue by dummdidumm** [telerik/kendo-angular#2576]
**Describe the bug**
The scrollbar is always visible in virtual scrolling mode, even if there is nothing overflowing the container.

**To Reproduce**
See this stackblitz https://stackblitz.com/edit/angular-vspuwh 
Do some filtering to get the list small enough, scrollbar stays.

**Expected behavior**
Scrollbar disappears when there is no overflow. Setting `overflow-y: auto` might be enough, or is there a reason this is not done?

**Browser**
Browser independent.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by tapopov** [comment]
Fix available in `kendo-angular-dropdowns` v5.3.0
