### ISSUE TITLE
Treeview checkedkeys value not correct when accessed from events like nodeclick

### ISSUE THREAD

**Issue by aj33sh** [telerik/kendo-angular#2577]
**Describe the bug**
Treeview checkedkeys value not correct when accessed from events like nodeclick via this.checkedkeys

**To Reproduce**
1. Run the provided Stackblitz app
2. click on any of the nodes
3. Compare the values showing up in the screen; CheckedKeys via angular interpolation {{...}} showing correct values but the values via events are not correct (values from previous selection gets updated after next selection change)

https://stackblitz.com/edit/angular-prwvqu

**Expected behavior**
should be able to get correct checked keys via events

**Screenshots**
![image](https://user-images.githubusercontent.com/56186089/67904675-5255d380-fb2c-11e9-8594-85ac19387b8c.png)

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by danielkaradachki** [comment]
The behavior is expected. Use the [checkedKeysChange](https://www.telerik.com/kendo-angular-ui/components/treeview/api/CheckDirective/#toc-checkedkeyschange) event to perform some action when the checked keys are changed.
