### ISSUE TITLE
How to: check all nodes and expand all nodes of a treeview with level/depth more than 2

### ISSUE THREAD

**Issue by aj33sh** [telerik/kendo-angular#2579]
I would like to check all nodes of the treeview with depth/level more than 2. I tried to use kendoTreeViewExpandable directive but is not expanding all the nodes by default.

to reproduce, please run this sample app, https://stackblitz.com/edit/angular-prwvqu-yqd3rz

**screen shot 1 (how to check all nodes programmatically)**
![image](https://user-images.githubusercontent.com/56186089/67990352-e2f6e700-fbf2-11e9-8a7e-e86749ffbb73.png)
**screen shot 2 (how to expand all nodes programmatically when using kendoTreeViewExpandable to get all checked values)**
![image](https://user-images.githubusercontent.com/56186089/67990574-8b0cb000-fbf3-11e9-886d-11fad1bb4e5f.png)

**Comment by dtopalov** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
