### ISSUE TITLE
[Grid] kendoGridInCellEditing directive with navigable Grid causes unexpected behavior

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2581]
**Describe the bug**
In order to observe the unexpected behavior, the Grid should use the kendoGridInCellEditing directive. It should be navigable and there should be a DropDownList component in the first column when in edit mode. When a new row is about to be created and a value is entered for the DropDownList using the keyboard, then the formGroup pristine property remains true. Which doesn't allow the "Add" button to change its state from disabled to enabled when the FormGroup is valid.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-r71y1u-gznvgz?file=app/app.component.ts

1. Click "Add New"
2. Use the arrow keys and Enter to select a value for the DropDownList.
3. Notice how formGroup.pristine remains true (below the Grid).
4. Now if the required form controls - "ProductName" and "UnitsInStock" are filled in, then the "Add" button would still be disabled. 

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-grid v4.5.0`
