### ISSUE TITLE
namedColors not founded kendo-drawing

### ISSUE THREAD

**Issue by Alyyc85** [telerik/kendo-angular#2582]
Some warnings while compiling.

```
 ./node_modules/@progress/kendo-angular-inputs/dist/fesm5/index.js 4613:18-29
"export 'namedColors' was not found in '@progress/kendo-drawing'

./node_modules/@progress/kendo-angular-inputs/dist/fesm5/index.js 4619:26-37
"export 'namedColors' was not found in '@progress/kendo-drawing'

client:154 ./node_modules/@progress/kendo-angular-inputs/dist/fesm5/index.js 4619:68-79
"export 'namedColors' was not found in '@progress/kendo-drawing'
```
Package config:

```
"dependencies": {
    "@angular/animations": "7.2.10",
    "@angular/cdk": "7.3.6",
    "@angular/common": "7.2.10",
    "@angular/compiler": "7.2.10",
    "@angular/core": "7.2.10",
    "@angular/forms": "7.2.10",
    "@angular/platform-browser": "7.2.10",
    "@angular/platform-browser-dynamic": "7.2.10",
    "@angular/router": "7.2.10",
    "@ng-idle/core": "6.0.0-beta.4",
    "@ngrx/router-store": "6.1.0",
    "@ngrx/store": "6.1.0",
    "@progress/kendo-angular-buttons": "5.0.0",
    "@progress/kendo-angular-charts": "4.1.1",
    "@progress/kendo-angular-common": "1.1.0",
    "@progress/kendo-angular-dateinputs": "4.1.0",
    "@progress/kendo-angular-dialog": "4.1.0",
    "@progress/kendo-angular-dropdowns": "4.2.0",
    "@progress/kendo-angular-excel-export": "3.0.0",
    "@progress/kendo-angular-grid": "4.4.0",
    "@progress/kendo-angular-inputs": "6.3.0",
    "@progress/kendo-angular-intl": "2.0.0",
    "@progress/kendo-angular-l10n": "2.0.0",
    "@progress/kendo-angular-layout": "4.1.4",
    "@progress/kendo-angular-notification": "2.0.0",
    "@progress/kendo-angular-pdf-export": "2.0.0",
    "@progress/kendo-angular-popup": "3.0.1",
    "@progress/kendo-angular-scheduler": "1.0.1",
    "@progress/kendo-angular-tooltip": "2.1.0",
    "@progress/kendo-angular-treeview": "4.0.1",
    "@progress/kendo-data-query": "1.5.2",
    "@progress/kendo-drawing": "1.5.9",
    "@progress/kendo-recurrence": "^1.0.0",
    "@progress/kendo-theme-default": "3.4.0",
    "@telerik/kendo-intl": "2.0.0",
    "core-js": "2.5.7",
    "file-saver": "2.0.1",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "iv-viewer": "2.0.0",
    "moment": "2.24.0",
    "ng2-image-viewer": "3.0.1",
    "ngx-drag-drop": "1.1.0",
    "ngx-image-cropper": "1.3.8",
    "ngx-markdown": "8.1.0",
    "primeng": "7.1.0",
    "quill": "1.3.7",
    "rxjs": "6.4.0",
    "rxjs-compat": "^6.5.3",
    "zone.js": "0.8.29"
  },
```

Already deleted package-lock.json, node_modules and reinstalled it

**Comment by danielkaradachki** [comment]
The inputs package requires @progress/kendo-drawing 1.5.12 or later.

**Comment by pcouas** [comment]
Yes
{
  "name": "front2021",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "11.2.10",
    "@angular/common": "11.2.10",
    "@angular/compiler": "11.2.10",
    "@angular/core": "11.2.10",
    "@angular/forms": "11.2.10",
    "@angular/localize": "11.2.10",
    "@angular/platform-browser": "11.2.10",
    "@angular/platform-browser-dynamic": "11.2.10",
    "@angular/router": "11.2.10",
    "@progress/kendo-angular-buttons": "6.1.0",
    "@progress/kendo-angular-charts": "5.1.0",
    "@progress/kendo-angular-common": "2.0.0",
    "@progress/kendo-angular-dateinputs": "5.1.0",
    "@progress/kendo-angular-dialog": "5.0.0",
    "@progress/kendo-angular-dropdowns": "5.2.0",
    "@progress/kendo-angular-excel-export": "4.0.0",
    "@progress/kendo-angular-grid": "5.0.3",
    "@progress/kendo-angular-icons": "0.4.2",
    "@progress/kendo-angular-inputs": "7.2.0",
    "@progress/kendo-angular-intl": "3.1.0",
    "@progress/kendo-angular-l10n": "3.0.0",
    "@progress/kendo-angular-label": "3.0.2",
    "@progress/kendo-angular-layout": "6.1.4",
    "@progress/kendo-angular-listview": "2.0.0",
    "@progress/kendo-angular-menu": "3.0.1",
    "@progress/kendo-angular-pager": "2.0.0",
    "@progress/kendo-angular-pdf-export": "3.0.0",
    "@progress/kendo-angular-popup": "4.0.0",
    "@progress/kendo-angular-progressbar": "2.0.0",
    "@progress/kendo-angular-toolbar": "4.0.0",
    "@progress/kendo-angular-treeview": "5.1.1",
    "@progress/kendo-angular-upload": "7.1.0",
    "@progress/kendo-data-query": "1.5.4",
    "@progress/kendo-drawing": "1.10.0",
    "@progress/kendo-licensing": "1.1.4",
    "@progress/kendo-svg-icons": "0.1.2",
    "@progress/kendo-theme-default": "latest",
    "dwt": "16.2.4",
    "hammerjs": "2.0.0",
    "rxjs": "6.6.7",
    "tslib": "2.2.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1102.9",
    "@angular/cli": "11.2.9",
    "@angular/compiler-cli": "11.2.10",
    "@types/jasmine": "3.6.0",
    "@types/node": "12.11.1",
    "codelyzer": "6.0.0",
    "cypress": "6.8.0",
    "jasmine-core": "3.6.0",
    "jasmine-spec-reporter": "5.0.0",
    "karma": "6.1.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage": "2.0.3",
    "karma-jasmine": "4.0.0",
    "karma-jasmine-html-reporter": "1.5.0",
    "protractor": "7.0.0",
    "ts-node": "8.3.0",
    "tslint": "6.1.3",
    "typescript": "4.1.5"
  }
}
