### ISSUE TITLE
Locked column in kendo grid visually out of sync from the rest of the data row when zooming out in Chrome Browser

### ISSUE THREAD

**Issue by rdelosh** [telerik/kendo-angular#2587]
## I'm submitting a...

* Bug report 

## Current behavior
In Chrome Browser, when I am using zoom out to less than 100% and I use a kendo-grid with at least one locked column and I scroll all the way to the bottom of the grid, the locked columns become visually out of sync from the rest of the data row.
## Expected behavior
The locked columns are in sync with the rest of the data row all the time regardless of browser zoom.

## Minimal reproduction of the problem with instructions
1. In Chrome Browser  Go to https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/
2.  Zoom out to 50%
3. Scroll all the way to the bottom of the kendo grid
4. See locked column visually out of sync from the rest of the data row

Browser:
- Chrome (desktop) version XX

System:
-
- TypeScript version: 2.7.2
- Node version: 5.6.0
- Platform:  Windows

**Comment by danielkaradachki** [comment]
Seems similar to: https://github.com/telerik/kendo-angular/issues/2501

**Comment by rdelosh** [comment]
any updates on this?

**Comment by siyka-marinova** [comment]
@rdelosh The issue is fixed in `kendo-angular-grid v4.5.0`
