### ISSUE TITLE
[Buttons] DropDownButton and SplitButton don't fully support RTL

### ISSUE THREAD

**Issue by ItielBeeri** [telerik/kendo-angular#2588]
**Describe the bug**
When using DropDownButton or SplitButton, and the app is configured with `{ provide: RTL, useValue: true }`, the elements in the buttons themselves are correctly directed from right to left and their popup is correctly positioned in accordance with the right edge of the button, but the content within the popup is incorrectly directed from left to right.

**To Reproduce**
1. Add DropDownButton or Split button
2. Provide them with data whose items contain both `text` and `icon`
3. Define `{ provide: RTL, useValue: true }` in the module's providers
4. Click the button and see how everything within the popup is aligned to left and directed from left to right

[StackBlitz](https://stackblitz.com/edit/angular-7eusyn-uzhr3f)

**Expected behavior**
When RTL is configured, the content in the popup should be arranged from right to left - the icons should be aligned to the right, then the text aligned to them.

**Screenshots**
![image](https://user-images.githubusercontent.com/13517482/68330515-11d1f900-00dc-11ea-9800-9fab6404f94b.png) ![image](https://user-images.githubusercontent.com/13517482/68330520-15fe1680-00dc-11ea-946d-0330399a994b.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78

**Comment by preslavapetrova1** [comment]
Fix for this issue is available in v5.5.0 of the Buttons package.
