### ISSUE TITLE
[Editor] Popup stays open when the responsive toolbar is destroyed

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-angular#2589]
Describe the bug
The overflow popup stays open when the responsive toolbar component disappears (is destroyed).

To Reproduce:
1.Open the [responsive toolbar demo](https://www.telerik.com/kendo-angular-ui/components/editor/responsive-toolbar/#toc-responsive-toolbar)
2.Click on the three dots to open the popup.
3.Click Cancel button to close the window.

Expected behavior:
The popup is closed.

**Comment by Raisolution** [comment]
Not reproducing in the latest version of the component. Demo is available [here](https://www.telerik.com/kendo-angular-ui/components/editor/responsive-toolbar/#toc-responsive-toolbar).
