### ISSUE TITLE
Dropdown autofit forms width

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#259]
I am using bootstrap 4 with kendo ui default theme. It would be nice if there would be a easy way to make all kendo ui Inputs not only the Dropdownlist to autofit like the default input in bootstrap 4.

![autofit](https://cloud.githubusercontent.com/assets/1572878/22524742/c5e27f24-e8c4-11e6-904b-e5924cf2d652.png)

    <div class="row">
        <div class="col-md-6">
            <div class="row form-group">
                <label class="col-md-2 col-form-label col-form-label-sm">Filter</label>
                <div class="col-md-10">
                    <input class="form-control form-control-sm"/>
                </div>
            </div>
        </div>
    </div>

     <div class="col-md-6 ">
          <div class="row form-group">
              <label class="col-md-2 col-form-label col-form-label-sm">Zeitraum</label>
              <div class="col-md-10">
                 <kendo-dropdownlist [data]="getZeitraeumeList"
                                        [(value)]="searchModel?.LogSearchModel.ZeitraumId"
                                        [textField]="'Text'"
                                        [valueField]="'Value'"
                                        [valuePrimitive]="true">
                    </kendo-dropdownlist>
                </div>
            </div>
        </div>
      </div>

**Comment by ggkrustev** [comment]
@squadwuschel, the dropdownlist component has a default width. If you would like to occupy the whole available space, just set its width to 100%:

http://plnkr.co/edit/cZne50Qgr8ILwjzwwOfH?p=preview

**Comment by ggkrustev** [comment]
@squadwuschel if you would like to make all dropdowns in the component 100% wide, then you can override their CSS class, e.g. k-autocomplete, k-combobox and etc, setting the width to 100%:

http://plnkr.co/edit/OXoXD2dlVnl9Piihddyl?p=preview

I will close the issue with this reply. If you have any issues, please do no hesitate to post here.
