### ISSUE TITLE
[Editor] The form control value is not updated with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2590]
When the user is typing in the Editor or otherwise changes the value (e.g. via applying some formatting), the form control value is not updated accordingly when ChangeDetectionStrategy.OnPush is used.

If the Change Detection is triggered by clicking a button or manually, the form control is updated as expected:

https://stackblitz.com/edit/angular-dmpdzy-ckbeus?file=app/app.component.ts

At the same time, changing the value of other form elements like a regular Input or a DropDownList, is reflected accordingly in the bound form control value.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-editor`

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-editor v1.0.1`
