### ISSUE TITLE
[Inputs] Switch triggered animation at initialize value to 'true' with kendo-grid component.

### ISSUE THREAD

**Issue by jinhoyim** [telerik/kendo-angular#2591]
## Minimal reproduction of the problem with instructions
1. Add `kendo-switch` component and set `ngModel` to `true`.
2. Add `kendo-grid` component at same component.
3. You can see animated to on.
[https://stackblitz.com/edit/angular-g7h3iz](https://stackblitz.com/edit/angular-g7h3iz)

**Sometime, you can't see it, because fast. please, reproduce your local computer and use dev environment.

Browser:
- Chrome (desktop) version XX

System:
- Angular 8

**Comment by Raisolution** [comment]
Fix available in `v7.3.1`
