### ISSUE TITLE
How to use two different css styles to display the tooltip ?

### ISSUE THREAD

**Issue by HuAlex007** [telerik/kendo-angular#2592]
This is the link to my demo:
**https://stackblitz.com/edit/kendo-customize-tooltip-styling**

1. The First button use ".my-class" css style to show tooltip, it's default and it's good.

2. When I use two different ways to set the Second button and the Third button to use ".my-class1" 
  css style to show tooltip. But both of them didn't work( background-color should be red ), I think my methods are not correct.

3. What should I do when I want to set  my button's tooltip to use ".my-class1" css style? Thanks a lot.

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
