### ISSUE TITLE
Kendo Grid don't accept dots in data.

### ISSUE THREAD

**Issue by Monali-ITT** [telerik/kendo-angular#2593]
## I'm submitting a...
 - Bug Report

## Current behavior
- If the return result contains "dot" i.e : "."  in data then headers and data not get matched and output is not displayed.
Like. If my headers and  result is in following format: 
this.headers = [
            {
                'field': 'g.UID',
                'title': 'g.UID',
                'editor': 'text',
                'width': 200
            }
            {
                'field': 'g.Name',
                'title': 'g.Name',
                'editor': 'text',
                'width': 200
            }
         ]

 data:{
     g.UID: "12344",
     g.Name:"xyz"}.
 
- Even if field of headers and result data is match , output not displayed.

- If I modify data and headers like:
 this.headers = [
            {
                'field': 'UID',
                'title': 'UID',
                'editor': 'text',
                'width': 200
            }
            {
                'field': 'Name',
                'title': 'Name',
                'editor': 'text',
                'width': 200
            }
           
        ]

 data:{
     UID: "12344",
     Name:"xyz"}

- Then it displayed data in grid.

## Expected behavior
- It should display result in grid when header and data contains "." [DOT] .

## Minimal reproduction of the problem with instructions
- Attached zip file of project.
- [quwkuy.run.zip](https://github.com/telerik/kendo-angular/files/3836032/quwkuy.run.zip)
- Please look for ID column..I have added Product.ID in data and in headers also I have same but still not displayed data.

## Environment
- Linux.

Browser:

- Chrome (desktop) Version 75.0.3770.142 (Official Build) (64-bit)

System:
- TypeScript version: 3.5.3
- Node version: v10.16.0
- Platform: Linux mint

**Comment by ipeshev** [comment]
Can be reproduced [here](https://stackblitz.com/edit/angular-itr3zw?file=app/app.component.ts)

**Comment by Monali-ITT** [comment]
yes

**Comment by danielkaradachki** [comment]
Dot is used to access nested a field e.g.

    g: {
        UID: VALUE
    }

Use bracket notation to show the field if it's not a nested one:

https://stackblitz.com/edit/angular-itr3zw-fifilr?file=app/app.component.ts
