### ISSUE TITLE
Kendo Grid changes columns title when dynamically loading columns.

### ISSUE THREAD

**Issue by Monali-ITT** [telerik/kendo-angular#2594]
## I'm submitting a...
Bug Report
## Current behavior:
 If my headers and result is in following format:
this.headers = [
{
'field': "['g.UID']",
'title': 'g.UID',
'editor': 'text',
'width': 200
}
{
'field': "['g.Name']",
'title': 'g.Name',
'editor': 'text',
'width': 200
}
]
data:{
'g.UID': "12344",
'g.Name':"xyz"}.

And template is: 
template: `
  
       <kendo-grid
          [data]="gridData"
          [height]="410"
          [loading]="view.loading"
          >
            <kendo-grid-column *ngFor="let col of headers" [title]="col.title" [field]="col.field"></kendo-grid-column>
        </kendo-grid>

- Field of headers and result data is match , output is  displayed. But on output column titles are changing..it takes the value of field.
- IT SHOULD DISPLAY  g.UID OR g.Name AS COLUMN TITLE . BUT ITS DISPLAYED  ['g.UID'] ,['g.Name']

## Expected behavior
It should display correct columns.

## Minimal reproduction of the problem with instructions:
please see the demo: 

https://stackblitz.com/edit/angular-khcbr3?file=app/app.component.ts

## Environment
- Linux
Browser:
- Chrome (desktop) Version 75.0.3770.142 (Official Build) (64-bit)

System:
- TypeScript version: 3.5.3
- Node version: v10.16.0
- Platform: Linux mint

**Comment by danielkaradachki** [comment]
Not sure if I understand the issue but the bound columns title is not set:

    [{field: "['Product.ID']"}, {field: "ProductName"}, {field: "QuantityPerUnit"}];

If I call changeBinding type or add title to the initially set columns, the specified title is displayed:

https://stackblitz.com/edit/angular-khcbr3-6uhwpy?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Closing until additional information is available.
