### ISSUE TITLE
[DateRange] misses a CustomMessagesComponent allowing to translate "Today"

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2596]
**Describe the bug**
Currently the DateRange component misses a CustomMessagesComponent that allows to translate its "Today" message.

**Workaround**
Please check the following example demonstrating how that limitation could be currently avoided:
https://stackblitz.com/edit/angular-ssaods-rhpn9b?file=app/app.component.ts

**Comment by dimitar-pechev** [comment]
After some further consideration, we are not going to introduce changes to the current setup. 

The messages are specific to the **MultiViewCalendar**, so their setup should be applied to the calendar itself, as the referenced example demonstrates.

Providing a mechanism to set the calendar messages through the **DateRange** or **DateRangePopup** components would mean we should also proxy all other calendar config options (e.g. `focusedDate`, `disabledDates`, `activeView`,  etc.), which would only contribute to more complicated component API. Considering that the **MultiViewCalendar** can be easily configured as demonstrated above, this would be counter productive.
