### ISSUE TITLE
Incorrect date formatting for "d. MMM yyyy" format and "de-DE" locale

### ISSUE THREAD

**Issue by orlov11111** [telerik/kendo-angular#2597]
**Describe the bug**
Incorrect date formatting for "d. MMM yyyy" format and"de-DE" locale.
This bug is related with IntlService formatDate method.

**To Reproduce**
1. Use "d. MMM yyyy" format 
2. Use "de-DE" locale 
3. Try to format any date (for example "2019-09-02T00:00:00.000") with IntlService formatDate method
4. Formatted date has wrong format ("2. Sept. 2019")

Example: https://stackblitz.com/edit/angular-ppjczt

**Expected behavior**
"d. MMM yyyy" format should be applied correctly and formatted date should be "2. Sep 2019"

**Screenshots**
![image](https://user-images.githubusercontent.com/47855982/68937746-0357a180-07ae-11ea-996a-03d32a428e80.png)

**Comment by danielkaradachki** [comment]
This is the value provided by CLDR for abbreviated month name:
https://github.com/unicode-cldr/cldr-dates-modern/blob/master/main/de/ca-gregorian.json#L24

You could [modify the loaded data](https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/loading-data/#toc-modifying-the-locale-data) or submit a bug report in the [CLDR repo](http://cldr.unicode.org/index/bug-reports) if it is incorrect.
