### ISSUE TITLE
How to change a Format of the NumericTextbox number in 12,12,122.25?

### ISSUE THREAD

**Issue by santosTT** [telerik/kendo-angular#2599]
Use this template for questions that are relevant to the community as a whole.

**If the issue is specific to your project, please open a [support ticket](https://www.telerik.com/account/support-tickets).**

**Comment by danielkaradachki** [comment]
The repository is for bug reports only. Please open a  [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
