### ISSUE TITLE
[Grid] incorrect rendering when hiding a column via the ColumnChooser

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2601]
**Describe the bug**
When grouping the Grid data in order to display some aggregates and a column is hidden through the ColumnChooser component, then the Grid layout becomes incorrect.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-cnuxtm?file=app/app.component.ts

1. Open the ColumnMenu from the button located in the GridToolbar.
2. Unckeck the "UnitPrice" column and click "Apply".
3. Observe the rendered HTML. The columns are positioned improperly.

**Comment by ctaleck** [comment]
By way of comparison, if you following these steps, the HTML is rendered correctly:

1. Remove the "Discontinued" column from the group header.
1. Open the ColumnMenu from the button located in the GridToolbar.
1. Un-check the "UnitPrice" column and click "Apply".
1. Drag the "Discontinued" column header to the group header.

The HTML is rendered correctly in this scenario. Now we just need the first scenario to behave like the second.

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-grid v4.5.0`
