### ISSUE TITLE
[Editor] breaks in IE 11

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2603]
**Describe the bug**

Once the Editor Module is imported in the app.module of an Angular 8 application, then the application cannot be run for production using IE 11. 

**To Reproduce**
1. Create a new Angular 8 project using **ng new**.
2. Install the Editor package and add it to the app.module by running **ng add @progress/kendo-angular-editor**
3. Configure the project to be compatible with IE 11.
4. Run **ng serve --prod**
5. Naviagte to http://localhost:4200/ using IE 11.

**Comment by valchev** [comment]
The bug is caused by a 3rd party package that the Editor Component uses.
See https://github.com/ProseMirror/prosemirror/issues/1003#issuecomment-555992364 for more details.

As soon as the issue is fixed in the external package, we will update the dependencies and close the issue.

**Comment by valchev** [comment]
The issue is fixed in v0.10.3
