### ISSUE TITLE
Angular 9 support and/or roadmap

### ISSUE THREAD

**Issue by miguellira** [telerik/kendo-angular#2604]
**Describe the bug**
Can you provide the current state of support for Angular 9 across your component suite?

**To Reproduce**
1. Create a new Angular 9 app using the CLI (version 9.0.0-rc.2 as of this post)
2. Run `ng add @progress/kendo-angular-dateinputs` to add all Kendo Date Input dependencies
3. Add the "Basic Usage" example of the [DatePicker](https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/)
4. Notice the following error written to the browser console:
```
ERROR TypeError: Cannot set property 'value' of null
    at DefaultDomRenderer2.setProperty (dom_renderer.ts:227)
    at DebugRenderer2.setProperty (services.ts:825)
    at e.updateElementValue (main.js:5)
    at e.ngOnChanges (main.js:5)
    at checkAndUpdateDirectiveDynamic (provider.ts:232)
    at checkAndUpdateNodeDynamic (view.ts:447)
    at checkAndUpdateNode (view.ts:391)
    at debugCheckAndUpdateNode (services.ts:431)
    at debugCheckDirectivesFn (services.ts:392)
    at Object.eval [as updateDirectives] (e.html:23)
    ...
```
or run the following [StackBlitz](https://angular-vi6wtu.stackblitz.io/) example.

**Expected behavior**
A working Kendo UI DatePicker is displayed.

**Additional Comments**
I'm sure there is a lot of work left to properly support ivy let alone Angular 9, however, I find it strange that there is plenty of writes up regarding Angular 8 support but no mention of Angular 9 in the [roadmap](https://www.telerik.com/kendo-angular-ui/roadmap/). Is there a set of components that support **Angular 9 + ivy** and if so, is there a specific combination of npm tags/versions one should reference? Thanks!

**Comment by danielkaradachki** [comment]
We are currently working on support for Angular 9 and ivy. You can follow the progress in [this](https://github.com/telerik/kendo-angular/issues/2321) issue.
