### ISSUE TITLE
[Toolbar] clicking the overflow button refreshes the page

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2605]
**Describe the bug**
When the Toolbar is placed inside a form and the overflow button is clicked it refreshes the page. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-2pfqpa?file=app/app.component.ts

1. Click the overflow button.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `@progress/kendo-angular-toolbar` package

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-toolbar v3.0.0`
