### ISSUE TITLE
[Scheduler] Agenda view dos not trigger eventDblClick when also listening to eventClick 

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#2608]
**Describe the bug**
If you handle both `eventDblClick` and `eventClick` on the scheduler, the Agenda View does not always trigger the double click event. 

**To Reproduce**
https://stackblitz.com/edit/angular-srt7vy?file=app/app.component.ts
if you double click on the first event you will see that double click it is never triggered. 

**Expected behavior**
Double click to be always triggered

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 78

**Comment by danielkaradachki** [comment]
I was able to replicate the problem with the first item.  Seems that the rows for the first item in a day are recreated on click and the so the DOM event is never triggered. Is the event not triggered on your side only for the first item in each day or the problem also occurs for other items?

**Comment by PeterStaev** [comment]
Indeed, happens only for the first item. Adjusted description.

**Comment by danielkaradachki** [comment]
Should be fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:

https://stackblitz.com/edit/angular-tjwdef?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Fix released in 1.1.1

https://stackblitz.com/edit/angular-srt7vy-fcoayk?file=app/app.component.ts
