### ISSUE TITLE
[Scheduler] "Show full day" button doesn't display all events in the view

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2609]
**Describe the bug**
When clicking the "Show full day" button, the view isn't updated to contain the events for the hours which are outside of business hours.
 
**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-v6ymx4?file=app/events-utc.ts

1. Click "Show full day". 
2. No more events are displayed even though they are present in the data of the Scheduler.
3. Navigate to the next day and back to the same one using the previous/next buttons.
4. The events outside of business hours are now displayed.

**Comment by danielkaradachki** [comment]
Fixed in the latest [dev](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) version:

https://stackblitz.com/edit/angular-sj4bpr?file=app/app.component.ts

**Comment by danielkaradachki** [comment]
Fix released in 1.1.1

https://stackblitz.com/edit/angular-sbz9or?file=app/app.component.ts

**Comment by SumekQQ** [comment]
I found the same issue on version 4.3.7 but in scheduler views with timeline (day or week).

To reproduce please check the following example:
[https://stackblitz-starters-9jaj2k.stackblitz.io](https://stackblitz-starters-9jaj2k.stackblitz.io)

1. Click 'Timeline' button
2. You should see event outside business hours
3. Switch to business hours, then switch to full day.
4. The events outside the events are not visible.
