### ISSUE TITLE
[Charts] Donut/Pie chart series labels are sometimes cut off even with "autoFit"

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2611]
Under specific circumstances when there is not enough space, and the series labels' position is "outsideEnd", some of the labels get cut off when there is not enough space even if "autoFit" is set to **_true_**:

https://stackblitz.com/edit/angular-vebyme?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in `kendo-angular-charts v4.1.3`
