### ISSUE TITLE
how can i read the Previous version document ?

### ISSUE THREAD

**Issue by zqfcoder** [telerik/kendo-angular#2612]
**Describe the issue**
how can i read the Previous version document ?because i use the ord version of the kendo-angular

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by Raisolution** [comment]
Hi @zqfcoder,

Our documentation is relevant to the latest version of each package. Information about what functionality is added in each version is available in the corresponding `Change Log` section of the component.
E.g. https://www.telerik.com/kendo-angular-ui/components/grid/changelog/

**Comment by zqfcoder** [comment]
but some example is not suitable [cry]

**Comment by zqfcoder** [comment]
i mean that version i used is too ord...

**Comment by Raisolution** [comment]
Hi @zqfcoder,

Indeed our examples use the latest version of each package. If further information or specific assistance is required, do not hesitate to contact us via our [support system](https://www.telerik.com/account/support-tickets).
