### ISSUE TITLE
Editor paste content from MS Word/Excel

### ISSUE THREAD

**Issue by Eastrall** [telerik/kendo-angular#2614]
Hello,

Is this feature available on the Kendo Angular Editor ?
When I copy content from MS Word or Excel, and paste it in the editor, the pasted content has no style and results in words/style loss.

**Comment by valchev** [comment]
Hi @Eastrall 

The paste from MS Word / Excel is a feature that we will definitely add in future package updates, however, at present, I cannot commit an exact timeframe.

**Comment by Eastrall** [comment]
Thank you for the information. We have found an alternative solution which is using the Kendo UI editor wrapped in an Angular directive and wait for the support of this feature in Kendo UI Angular.
