### ISSUE TITLE
[Buttons] ButtonGroup tabbing does not function properly

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2615]
**Describe the bug**
When `<kendo-buttongroup>` has `[selection]="'single'"`, the first and last button in the button group have their `tabindex` set to 0.

**To Reproduce**
https://stackblitz.com/edit/angular-ef5for
1. Click on the first input.
2. Press Tab key on the keyboard - `<kendo-buttongroup>` receives the focus.
3. Press Tab key again - the first button receives the focus.
4. Press Tab key again - the last button receives the focus.
5. Press Tab key again - the second input receives the focus.

**Expected behavior**
The first and last buttons should not be focused when pressing Tab key. 

**Additional context**
This is only observed when `[selection]` is set to `"'single'"`. If it is not set at all - the issue is not present.

**Comment by Raisolution** [comment]
Fixed in `v5.1.0` of the Buttons package.
