### ISSUE TITLE
Scheduler event docs

### ISSUE THREAD

**Issue by lucasheight** [telerik/kendo-angular#2616]
**Describe the issue**
Events "Cancel" and "Create" Have the same description.

cancel EventEmitter<CancelEvent>
Fires when the user cancels the editing by clicking the Cancel command button.

create EventEmitter<CreateEvent>
Fires when the user cancels the editing by clicking the Cancel command button.

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**
https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerComponent/

**Comment by danielkaradachki** [comment]
Thanks, fixed in the dev version:

https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/api/SchedulerComponent/#toc-create
