### ISSUE TITLE
Change detection does not update Editor's buttons tittles

### ISSUE THREAD

**Issue by rkirilov** [telerik/kendo-angular#2617]
**Describe the bug**
When we have translation functionality implemented via [ngx-translate](https://github.com/ngx-translate/core) for the Editor's buttons _titles_ and drop down components default items _text_ cannot be changed when language is changed and new detection change mechanism is started

**To Reproduce**

Attached is a sample application:[app.zip](https://github.com/telerik/kendo-angular/files/3892667/app.zip)

1. Open app and install npm modules
2. Run application
3. Change language via language dropdown on the top right corner

**Expected behavior**
Editor's buttons titles and drop downs default item text to be changed with new values coming from translation service.

**Screenshots**
<img width="803" alt="Screen Shot 2019-11-26 at 5 45 09 PM" src="https://user-images.githubusercontent.com/11816095/69648779-9f1dc300-1074-11ea-881b-9dfda6fd4364.png">

**Browser**
 - OS: MAC OS
 - Browser Chrome, Safari
 - Version 0.10.2

**Additional context**
The problem comes from creation of the components inside Editor and adding values to their properties.  _Title_ property of all buttons are not exposed as component public property instead it is added in the _Init_ event after a timeout: https://github.com/telerik/kendo-angular-editor/blob/develop/src/tools/shared/editor-command-base.ts#L28
For reference all properties should be defined as public properties like in following component: https://github.com/telerik/kendo-angular-editor/blob/develop/src/tools/tables/editor-insert-table-button.component.ts#L94

**Comment by dtopalov** [comment]
We suggest using the documented approaches for translating and/or customizing the Editor messages:

https://www.telerik.com/kendo-angular-ui-develop/components/editor/globalization/#toc-internationalization

We are also working on changing the mechanics for setting the button properties, but still cannot guarantee full compatibility with third-party libraries.
