### ISSUE TITLE
Kendo Angular UI Scheduler ReactiveEditingDirective modal.

### ISSUE THREAD

**Issue by abhishek0196** [telerik/kendo-angular#2618]
**Describe the issue**
I am trying with the preview of kendo ui angular scheduler ReactiveEditingDirective when I tried to add multiple options in the modal which opens while editing it is not responsive which makes the save and cancel button unreachable.

**Screenshots**

![1](https://user-images.githubusercontent.com/13505029/69849972-2a30d000-12a4-11ea-84ed-fa2e846f1d02.PNG)
![2](https://user-images.githubusercontent.com/13505029/69849974-2ac96680-12a4-11ea-8a0a-7280910b5682.PNG)
![3](https://user-images.githubusercontent.com/13505029/69849982-30bf4780-12a4-11ea-8e79-ae1d4de7aea1.PNG)
![4](https://user-images.githubusercontent.com/13505029/69849984-30bf4780-12a4-11ea-82fc-9eb2cc1ce8af.PNG)

**Browser**
 - OS:Win 10
 - Browser  Chrome
 - Version 78.0.3904.108

**Comment by danielkaradachki** [comment]
The problem should be fixed in the latest dev version of the themes:
https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/editing/editing-directives/

**Comment by abhishek0196** [comment]
Thanks for the reply it is working great on stackblitz , not on my local system even after  adding 
`"@progress/kendo-angular-scheduler": "1.1.1-dev.201911251406",` the modal opening is not reponsive. Also here I am attaching the package.json for  my local project.

`{
  "name": "first",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@progress/kendo-angular-buttons": "^5.0.0",
    "@progress/kendo-angular-common": "^1.0.0",
    "@progress/kendo-angular-dateinputs": "^4.0.0",
    "@progress/kendo-angular-dialog": "^4.0.0",
    "@progress/kendo-angular-dropdowns": "^4.0.0",
    "@progress/kendo-angular-excel-export": "^3.0.0",
    "@progress/kendo-angular-grid": "^4.4.0",
    "@progress/kendo-angular-inputs": "^6.0.0",
    "@progress/kendo-angular-intl": "^2.0.0",
    "@progress/kendo-angular-l10n": "^2.0.0",
    "@progress/kendo-angular-pdf-export": "^2.0.0",
    "@progress/kendo-angular-popup": "^3.0.0",
    "@progress/kendo-angular-scheduler": "1.1.1-dev.201911251406",
    "@progress/kendo-data-query": "^1.0.0",
    "@progress/kendo-drawing": "^1.5.8",
    "@progress/kendo-theme-material": "^3.5.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1",
    "@progress/kendo-date-math": "^1.3.2",
    "@progress/kendo-recurrence": "^1.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.19",
    "@angular/cli": "~8.3.19",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "bootstrap": "^4.4.0",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
`

**Comment by danielkaradachki** [comment]
The fix is in the themes. An official version with the fix included has already been published so try updating to `@progress/kendo-theme-material` 3.6.0

**Comment by abhishek0196** [comment]
Thanks it worked like charm.
