### ISSUE TITLE
CSS k-selected does not work correctly with k-alt in @progress/kendo-theme-bootstrap

### ISSUE THREAD

**Issue by filiphr** [telerik/kendo-angular#262]
I am not sure if this is the correct place for this issue. 

The problem is that the k-selected background color is not applied correctly. The `.k-grid .k-alt` and the `.k-alt` are applied instead.

**Comment by gyoshev** [comment]
Thank you for the feedback. As noted in the other issue, the bootstrap theme is still under heavy development, and is not documented. For now, use the default theme and [subscribe to this issue](https://github.com/telerik/kendo-angular/issues/266) to get a notification when a more stable release is shipped.
