### ISSUE TITLE
Populate nested JSON data into multilevel KendoTreeView.

### ISSUE THREAD

**Issue by shubhangi-panwar27** [telerik/kendo-angular#2621]
I am trying to create **Multilevel KendoTreeView** with this JSON data.

So far I could populate the tree with Module-> Feature->SubFeature.
But Would like to have Module->Feature->SubFeature and Privilage.
Here is the short demo of what I did so far.
[https://stackblitz.com/edit/angular-hbjccw]

Can anybody help me with how to sort this issue?

**Comment by dimitar-pechev** [comment]
From the shared demo it seems that the data does not follow the descibed **Module->Feature->SubFeature and Privilage** schema. Nonetheless, the **hasChildren** and **children** functions can be configured to return whatever you please.

To achieve the desired behavior, it's enough to merge all child arrays, and check for the existence of the child nodes on each level. Refer to [this example](https://stackblitz.com/edit/angular-hbjccw-gxqtne). 

For any further questions you have on the topic or any other related to implementing a custom scenario, I'd ask you to [open a support ticket](https://www.telerik.com/account/support-tickets). This repository is for bug reports only.
