### ISSUE TITLE
Dropdown with grouping doesn't open on selected item.

### ISSUE THREAD

**Issue by stansamyn** [telerik/kendo-angular#2622]
**Describe the bug**
Dropdown with grouping doesn't scroll down to show selected item.

**To Reproduce**
Steps to reproduce the behavior, with this [Stackblitz](https://stackblitz.com/edit/angular-fzk9l5?file=app/app.component.ts):
- Open dropdown and **select** the **last element** 'Pepper'
- Open dropdown again 

**Expected behavior**
Dropdown scrolls down until selected item is completely visible, like is does when no grouping.

**Comment by dimitar-pechev** [comment]
The fix for this has been released in **v4.2.6** of the DropDowns package.
