### ISSUE TITLE
[Editor] Text labels in insert image dialog are not clickable

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2623]
**Describe the bug**
When clicking a label in the insert image popup, the corresponding input field is not focused.

**To Reproduce**
https://stackblitz.com/edit/angular-6bxeqc
1. Click on the Insert Image button
2. In the opened dialog, click on any of the labels(for example "Web address")
3. Corresponding input field is not focused

**Expected behavior**
The input field next to the clicked label should be focused.

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-editor`.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-editor v.1.2.0`
