### ISSUE TITLE
[DropDowns] itemDisabled function is called 5 times per item

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2624]
**Describe the bug**
The **itemDisabled** function is called 5 times per item when the popup is open. It should be called only once per item.

**To Reproduce**
https://stackblitz.com/edit/angular-h61mtn?file=app/app.component.ts

**Comment by yanmariomenev** [comment]
Moved to our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1619292-dropdowns-itemdisabled-performance-optimization
