### ISSUE TITLE
[Editor] remove link button is always active after any input

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2625]
**Describe the bug**
When changing the value of the editor, the **Remove link** button becomes active event though there is no link under the cursor.

**To Reproduce**
https://stackblitz.com/edit/angular-gw3jjg

1. Click in the editing area.
2. Enter some text
3. The **Remove link** button becomes enabled.

**Expected behavior**
**Remove link** button should be active only when the cursor is on a link.

**Comment by Raisolution** [comment]
Fix available in latest Editor version.
