### ISSUE TITLE
[Toolbar] button.selected works only in buttongroup

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2627]
**Describe the bug**
When manually setting `[selected]` of a `<kendo-toolbar-button>`, the change is only visible when the button is placed inside a `<kendo-toolbar-buttongroup>`

**To Reproduce**
https://stackblitz.com/edit/angular-gvyddx

1. Click on the first button(inside the `<kendo-toolbar-buttongroup>`) and see in the DOM that it receives `.k-state-active`.
2. Click on the second button(not in a `<kendo-toolbar-buttongroup>`) and see in the DOM that it *does not* receive `.k-state-active`.

**Expected behavior**
The second button should also receive `.k-state-active`

**Additional context**
The issue is not reproducible for regular buttons(i.e. not in `<kendo-toolbar>`)

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-toolbar`

**Comment by siyka-marinova** [comment]
The fix is now available in the latest `kendo-angular-toolbar v3.1.0`
