### ISSUE TITLE
[MaskedTextbox] improper behavior when using IME mode

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2629]
**Describe the bug**
A MaskedTexbox doesn't behave properly when the user inputs the value of the input using IME mode for languages such as Chinese, Japanese, Korean, and Taiwan.

**To Reproduce**

1. Open the first example at the following article:
https://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/masks/#toc-mask-rules
2. Using Japanese keyboard with IME mode, enter "12345".
3. The value of the input becomes "1212-3123-4123-4512" instead of "1234-5"

**Comment by Raisolution** [comment]
The issue is not reproducing when using the num lock buttons on a Japanese IME keyboard.
