### ISSUE TITLE
When can we expect date input controls?

### ISSUE THREAD

**Issue by pkoecker** [telerik/kendo-angular#263]
#200 says "in a few days", but that was 13 days ago. 

Is there any new information available when those will be published? 
We really would like to use them but cannot efford to wait much longer 😟

**Comment by gyoshev** [comment]
The first version of the date inputs package is published. It contains only the [calendar component](http://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/) at this time, and the release date for the date input is not currently set. To get a picker-like component, see [the plunkr snippet](http://plnkr.co/edit/B68ZymlS2S4VoOV8GLr7?p=preview) from [this answer](https://github.com/telerik/kendo-angular/issues/200#issuecomment-274448059) in the mentioned thread.

**Comment by squadwuschel** [comment]
are the datepicker Components planned to be released in the May Release?
The Date- and Timepicker components are the most usefull components.

**Comment by gyoshev** [comment]
In general, the Date- and TimePickers are scheduled for the May release. It is likely that the DatePicker will be published sooner, though we don't have a specific date for that.

**Comment by tsvetomir** [comment]
We just shipped a basic [DateInput component](http://www.telerik.com/kendo-angular-ui/components/dateinputs/). The Date and Time pickers will follow soon.

**Comment by gyoshev** [comment]
Version **0.7** of the DateInputs package ships with a [DatePicker component](http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/).

**Comment by squadwuschel** [comment]
will the TimePicker be released with the May Release?

**Comment by gyoshev** [comment]
I am afraid not. At this time, you can [use the DropDownList as a TimePicker](http://plnkr.co/edit/H3EbGbmkYqd3ERE9UemQ?p=preview). Shipping the TimePicker is currently with a high priority, but we do not have an exact timeline when this will happen.

**Comment by harsha89vyas** [comment]
Date picket components are not working when using them in a Kendo Dialog. Is the issue known?

**Comment by gyoshev** [comment]
@harsha89vyas we are aware of the problem that popups are hidden behind the dialog overlay, see #641. If this is not the described problem, open a new issue and provide a way for us to reproduce the problem. Either way, please do not post in threads that are not discussing the issue at hand -- this one tracks the release status of the date inputs.

**Comment by ChrisProlls** [comment]
Any news about the TimePicker ?

**Comment by rvovard** [comment]
Will the next release of the DatePicker component include the fast navigation functionnality and other selection mode as [suggested on UserVoice](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18990187-calendar-picker-component-fast-navigation)?

What is needed already exists in Kendo UI, for example:

- [Start view and Navigation depth](http://docs.telerik.com/kendo-ui/controls/editors/datepicker/overview#configuration-Start)
- [Selectable Month DatePicker](http://docs.telerik.com/kendo-ui/controls/editors/datepicker/overview#configuration-Selectable)

Thanks for all the great work :)

**Comment by ggkrustev** [comment]
@ChrisProlls, a TimePicker preview (beta) was released under the `dev` tag and is available for testing. You can review it installing the `@dev` version of the package.
```
npm install @progress/kendo-angular-dateinputs@dev
```

@rvovard, the fast navigation is planned and should be included in some of the next official releases of DateInputs packages. I am afraid that I wouldn't be able to provide specific time frame, but I can assure you that we will work on the `fast navigation` feature with a high priority.
I will update the thread once it is available as a preview in the `@dev` branch.

**Comment by tsvetomir** [comment]
Here's [a plunkr](http://plnkr.co/edit/9dmi11E9jmLcy49JVYVi?p=preview) running off the [development channel](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by MaklaCof** [comment]
Looks great. 
@tsvetomir I take it that in my culture (with 24 hour format) AM/PM column is hidden and you can scroll hours from 0 to 23?

**Comment by ggkrustev** [comment]
@MaklaCof, absolutely. Check the updated plunkr:

http://plnkr.co/edit/GuyZ8ZBnO3ptlJdrW7jC?p=preview

The 24hour format will come for free when the specific culture is loaded.

**Comment by ggkrustev** [comment]
The TimePicker is official released in `@progress/kendo-angular-dateinputs@1.1.0`. Check the updated plunkr demo:

http://plnkr.co/edit/GuyZ8ZBnO3ptlJdrW7jC?p=preview

Will close the thread as both DatePicker and TimePicker are official available.
