### ISSUE TITLE
DialogServer -> ad DialogClass

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2630]
As already present on popupService -> https://www.telerik.com/kendo-angular-ui/components/popup/api/PopupSettings/#toc-popupclass

is it possible to have also dialogClass when dialogService is used?

Thanks.

**Comment by dtopalov** [comment]
Hi @meriturva,

Thank you for suggesting this enhancement. We believe it will indeed be a nice setting to have when creating the Dialog via the service. However, this issue tracker is for bug reports only, so could you please submit a feature request to our Feedback portal instead:

https://feedback.telerik.com/kendo-angular-ui

This helps us to estimate the customer demand for certain features and enhancements, and to prioritize accordingly based on the interest and perceived business value. Thank you in advance.

**Comment by meriturva** [comment]
Thanks...done.

https://feedback.telerik.com/kendo-angular-ui/1444953-dialogserver-add-dialogclass
