### ISSUE TITLE
Vertical Lines between columns of the grid.

### ISSUE THREAD

**Issue by abhishek0196** [telerik/kendo-angular#2631]
All the examples I'm trying over stackblitz for [example](https://rwkuk7.run.stackblitz.io) has vertical lines after each column but I am trying that on my local system it is not showing up.

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/13505029/70120729-3e554280-1693-11ea-8334-90498f80415f.png)
![Capture](https://user-images.githubusercontent.com/13505029/70120801-5cbb3e00-1693-11ea-904c-ac2192c45527.PNG)

**Browser**
 - OS:Win 10
 - Browser  Chrome
 - Version 78.0.3904.108

**Comment by inikolova** [comment]
The screenshot taken from the stackblitz example uses the **Default** theme; while the second one uses the **Material** theme, where the grid cells don't have borders. 

https://www.telerik.com/kendo-angular-ui/components/styling/

Keep in mind that this repository is for _bug reports only_. Please [open a support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations, or submit a new feature request in our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui) for any desired new enhancements.
