### ISSUE TITLE
kendoChartDonutCenterTemplate doesn't centered after kendo-angular-common@1.2.1

### ISSUE THREAD

**Issue by zulfu** [telerik/kendo-angular#2633]
**Describe the bug**
kendoChartDonutCenterTemplate doesn't centered after kendo-angular-common@1.2.1

**To Reproduce**
https://zqmfvp.run.stackblitz.io/ not centered with kendo-angular-common@1.2.1

**Expected behavior**
It should be centered https://d1syxf.run.stackblitz.io/ like this. When I downgrade kendo-angular-common@1.1.0 it works.

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 78.0.3904.108

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-charts`

**Comment by siyka-marinova** [comment]
Fix for this issue is now also available in `kendo-angular-charts v4.1.3`
