### ISSUE TITLE
[Editor] Is it possible to have both: value change emitted on each keystroke and onblur of TextArea as it was with version 0.8?

### ISSUE THREAD

**Issue by ZbigniewKrzystanek** [telerik/kendo-angular#2635]
Is it possible to handle value change both way or introduce new event, I mean 
a)value change is emitted on each keystroke
b)value change or other event is emitted when HTML text area is blurred.
I have some logic on old value change that requires reassign value after some enchantments but currently there is no hook for that, if you try assign it on new value change, cursor will be moved to an end of text.

**Comment by dtopalov** [comment]
Hello @ZbigniewKrzystanek,

The latest (2.2.0) version of the `@progress/kendo-angular-editor` package introduces the following enhancements:

- `focus` event - fires each time the content area is focused
- `blur` event - fires each time the content area is blurred

Depending on the user interaction with the content area and the toolbar, the behavior varies based on whether the focus is returned to the Editor immediately after clicking a Toolbar tool. For example, if the "Bold" tool is clicked, the `blur` event is not emitted as the focus remains in the content area, but when a tool which opens a Dialog is clicked, the `blur` event is emitted. When after interacting with such tool, the focus is returned to the content area, the `focus` event is emitted.

The developer can handle the `blur` event, obtain the current Editor value, and proceed as necessary.
