### ISSUE TITLE
[TabStrip] The focus is stolen from an input located in a kendoTabTitle template

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2638]
**Describe the bug**
When using an input inside a template with kendoTabTitle directive and trying to focus that input, then the focus is stolen from the input.

The issue doesn't occur if using version 4.1.4 of the Layout package.

**To Reproduce**
Please check the following example:

https://stackblitz.com/edit/angular-vt4gk4-hkitws?file=app%2Fapp.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-layout`

**Comment by Raisolution** [comment]
Released in `v4.2.1`
