### ISSUE TITLE
Jumping to the next NumericTextBox takes two tab clicks

### ISSUE THREAD

**Issue by JBildstein** [telerik/kendo-angular#264]
Having two or more NumericTextBoxes you have to press Tab twice to get into the next input field.
How to reproduce:
- Click into the input field of the first box
- Press tab -> next control has focus but not the input
- Press tab again -> now input is focused

It can be reproduced with an example from the documentation:
http://plnkr.co/edit/z3hzVSy1jJ0nZTo2b3uK?p=preview

What I would expect is to jump to the input immediately after pressing Tab once.

**Comment by tsvetomir** [comment]
The latest version behaves as expected, [see plunkr](http://plnkr.co/edit/AJrYLDbSFcIF8ehEHWXN?p=preview).

Please note that `round` [has been removed](https://github.com/telerik/kendo-angular/issues/463).
