### ISSUE TITLE
[ToolBar] Overflow popup opening animation starts from incorrect position

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2640]
**Describe the bug**
When clicking on the button for the overflow popup, the popup animation does not start from the edge of the toolbar.

**To Reproduce**
https://stackblitz.com/edit/angular-zwh1lz

1. Shrink the toolbar so the overflow popup button is visible.
2. Click on the overflow popup button.
3. The popup animation starts outside the toolbar.

**Expected behavior**
The popup animation should start from the edge of the toolbar.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-toolbar`

**Comment by siyka-marinova** [comment]
The fix is now available in the latest `kendo-angular-toolbar v3.1.0`
