### ISSUE TITLE
[Scheduler] DatePicker popup and View list do not close on blur

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2641]
The DatePicker popup and view list do not close on blur, which causes the options to overlapped on mobile devices. 

Check the screencast:
https://www.screencast.com/t/ivkKlvUVyNj

![2019-12-10_1034](https://user-images.githubusercontent.com/33104481/70514040-79e08880-1b3b-11ea-8f63-351ff058a94d.png)

Steps to reproduce:
1. Open the DatePicker popup
1.  Click outside the calendar (the popup remains opened)
1.  Open the View list
1.  Click outside the list (it remains opened)

https://stackblitz.com/edit/angular-mlrffw?file=app/app.component.ts

**Comment by MrSatyam77** [comment]
I am facing same problem what is the solution ???

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-scheduler`.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-scheduler v.1.2.0`
