### ISSUE TITLE
Selection for Scheduler event tiles

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2644]
Feature requirements:

**1. Time Slot Selection**
 - Mouse Click (or Click & Drag)
 - Controllable programmatically through API
 - Preventable

**2. Event Creation**
 - From Selected Time Slots on `Enter` keypress

**Comment by gkarapeev** [comment]
Closing this epic as it ended up containing only one issue in it - https://github.com/telerik/kendo-angular-scheduler/issues/326. [Issue 326](https://github.com/telerik/kendo-angular-scheduler/issues/326) will be the only official record of this feature.
