### ISSUE TITLE
Changing the font size, browser or machine scale zoom breaks the TimePicker and DateTimePicker layout

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2646]
The time list (hours and minutes) alignment gets worse when is scrolled to the bottom This behavior appears when the browser zoom is:
* \>100%
* <100%
* when is 100% and the machine display scale is changed (e.g. 125%)

**To Reproduce**
https://stackblitz.com/edit/angular-e4dink?file=app%2Fapp.component.ts

**Screenshots**
![2019-12-13_1335](https://user-images.githubusercontent.com/33104481/70797571-73594780-1dad-11ea-8b60-d63659352fdc.png)

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dateinputs`

**Comment by dimitar-pechev** [comment]
Released in **v4.2.2**.
