### ISSUE TITLE
ASP.NET Web API example with server-side paging, filtering and sorting

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2647]
**Describe the issue**
The documentation lacks an example for implementing server-side operations with ASP.NET Web API. This is a supported platform that sees [substantial use](https://insights.stackoverflow.com/trends?tags=asp.net-web-api%2Casp.net-core) today.

**Additional context**
* The scenario is covered in the UI for ASP.NET MVC [documentation](https://docs.telerik.com/aspnet-mvc/helpers/data-management/grid/editing/webapi-editing) and [examples](https://demos.telerik.com/aspnet-mvc/grid/webapi).
* The documentation includes a sample for server-side operations with ASP.NET Core - [Integration with UI for ASP.NET Core](https://www.telerik.com/kendo-angular-ui/components/dataquery/mvc-integration/).

**Comment by svetq** [comment]
the project is available here: https://github.com/telerik/kendo-angular/tree/master/examples-standalone/aspnetwebapi-data
