### ISSUE TITLE
[Inputs] Autofill suggestions break floating label behavior

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2648]
When the browser autofill suggestion popup is opened for an input element and the user hovers some suggestion, then do not choose it, and leaves the input blank, the floating label stays on top of the input even though the input is empty:

https://stackblitz.com/edit/angular-dczboh-rmwyob?file=index.html

Possibly related to:

https://github.com/telerik/kendo-angular/issues/2568

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by elena-gancheva** [comment]
Available in latest version of the package.
