### ISSUE TITLE
NodeTemplateDirective index variable information

### ISSUE THREAD

**Issue by Binek115** [telerik/kendo-angular#2649]
**Describe the issue**
Documentation does not mention about `index` variable which can be accessed inside `kendoTreeViewNodeTemplate`

 https://www.telerik.com/kendo-angular-ui/components/treeview/api/NodeTemplateDirective/

**Example**
https://stackblitz.com/edit/angular-4xuawv

**Comment by dimitar-pechev** [comment]
@Binek115, thanks for pointing our attention to this, we'll update the API page to include info about the two context variables passed to the template.

**Comment by dimitar-pechev** [comment]
The issue has been addressed. https://www.telerik.com/kendo-angular-ui/components/treeview/api/NodeTemplateDirective/
