### ISSUE TITLE
Problems when importing @progress/kendo-theme-bootstrap/scss/all.scss

### ISSUE THREAD

**Issue by filiphr** [telerik/kendo-angular#265]
When I try to import @progress/kendo-theme-bootstrap/scss/all.scss I am getting multiple "File to import not found or unreadable" 

For example:
* File to import not found or unreadable: ../../node_modules/@progress/kendo-theme-default/scss/mixins/all in  @progress\kendo-theme-bootstrap\scss\mixins\_all.scss (line 2, column 1)

I think that the paths you have there for the other packages are wrong.

I think that instead of doing: 
`@import "../../node_modules/@progress/kendo-theme-default/scss/mixins/all";`
you should do 
`@import "~@progress/kendo-theme-default/scss/mixins/all";`

**Comment by gyoshev** [comment]
Thank you for the feedback. The bootstrap theme is still under heavy development, and is not documented. For now, use the default theme and [subscribe to this issue](https://github.com/telerik/kendo-angular/issues/266) to get a notification when a more stable release is shipped.
