### ISSUE TITLE
[Scheduler] radio buttons have same id's when two Recurrence editors are defined in a component

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2651]
**Describe the bug**
Defining two or more Recurrence Editors in the same component, add the same ids to the radio buttons, which makes the radio buttons of the first defined editors to work incorrectly.

**To Reproduce**
1. Click '_Daily_' button on both editors
2. Click '_After_' radio button of the first editor

https://stackblitz.com/edit/angular-worf8b-27hfa5?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-scheduler`.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-scheduler v.1.2.0`
