### ISSUE TITLE
[Notification] Allow close notification subscription

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2653]
Currently, there is no subscription when a notification is closed by the 'close' button (_closable: true_).

![2019-12-19_1700](https://user-images.githubusercontent.com/33104481/71183953-98542b80-2281-11ea-8647-be5671a30d9c.png)

https://stackblitz.com/edit/angular-uptk2w?file=app%2Fapp.component.ts

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by elena-gancheva** [comment]
Available in the official [`v2.1.0`](https://github.com/telerik/kendo-angular-notification/releases/tag/v2.1.0) version of the package.
