### ISSUE TITLE
Grouped dropdown selected value position issue

### ISSUE THREAD

**Issue by baltyan** [telerik/kendo-angular#2654]
**Describe the bug**
The selected value not shown in grouped dropdown popup.

https://angular-iwq2n3.stackblitz.io

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 79.0.3945.88
![Kendo_grouped_dropdown_issue](https://user-images.githubusercontent.com/9678938/71350415-b7f19980-258a-11ea-9db5-094ba7f4962d.gif)

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dropdowns`

**Comment by dimitar-pechev** [comment]
Released in **v4.2.6**.
