### ISSUE TITLE
Multiselect typing issue

### ISSUE THREAD

**Issue by baltyan** [telerik/kendo-angular#2655]
**Describe the bug**
The input area length changes when typing

https://angular-rs37jz.stackblitz.io/

**Browser**
OS: Windows
Browser: Chrome
Version: 79.0.3945.88
![2019-12-23_13-52-51](https://user-images.githubusercontent.com/9678938/71351262-add09a80-258c-11ea-89be-1797595667ae.gif)

**Comment by dimitar-pechev** [comment]
Duplicate of #1988.
