### ISSUE TITLE
[MaskedTextBox] the focus method behaves inconsistently

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2657]
**Describe the bug**
When using the focus() method of the MaskedTextBox to focus it manually the cursor goes to the end of the input. That is inconsistent to the behavior when the MaskedTextBox is focused with a click - the cursor goes to the beginning of the input.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-s92sdq-homszz?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-inputs`

**Comment by siyka-marinova** [comment]
Fix is now also available in `kendo-angular-inputs v6.4.2`
