### ISSUE TITLE
Kendo Grid Virtual Columns Resizing is broken

### ISSUE THREAD

**Issue by ksharm-02** [telerik/kendo-angular#2659]
In a kendo grid, enable virtual columns and column resizing. Scroll to a middle columns and resize a column. Notice size of previous columns changes unexpectedly.

**Comment by ipeshev** [comment]
Reproducible here - https://stackblitz.com/edit/angular-jeakqc?file=app/app.component.ts, initial problem fixed.
Try to scroll to Customers column and drag it to left - major flickering appears

**Comment by ipeshev** [comment]
![captured](https://user-images.githubusercontent.com/4143177/71898027-eb265200-3160-11ea-8d64-0ae36311350b.gif)

**Comment by ksharm-02** [comment]
Hi, can we get an estimated ETA for the fix?

**Comment by tsvetomir** [comment]
Should be fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), see [updated demo](https://stackblitz.com/edit/angular-jeakqc-tjuine).
