### ISSUE TITLE
Bootstrap theme

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#266]
Currently the undocumented package `@progress/kendo-theme-bootstrap` is under heavy development, and is not intended to be used. **Use the `@progress/kendo-theme-default` package instead.**

As we progress towards a more stable release, the theme will be included in the Kendo UI for Angular site, and this issue will be closed. To receive a notification when the theme is shipped, subscribe to this thread.

**Comment by moyzes** [comment]
The closed tickets mean the theme is ready for use?

**Comment by gyoshev** [comment]
@moyzes the closed issues are duplicates. We have shipped a beta version of the Bootstrap theme, which can be seen in action [on the site](http://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/). Details on how to use the theme will be available with the next website upload, later today, and this issue will be closed.

**Comment by gyoshev** [comment]
The **2.0.0-beta.4** version of the Bootstrap theme is now released, and the [styling information](http://www.telerik.com/kendo-angular-ui/components/styling/) has been updated. You can see the theme in action on [the preview page](http://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/).

**Comment by EricSch** [comment]
Can't build the theme @progress/kendo-theme-bootstrap@2.0.0-beta.4.

When I call "npm run build", there is a webpack error: `webpack --optimize-minimize --bail` --> Output filename not configured.

**Comment by gyoshev** [comment]
@EricSch the current implementation of the Bootstrap theme is in the **v2** branch, so the build process is there, too. Once the version hits 2.0, it will be merged to the master branch.

**Comment by EricSch** [comment]
This means? 
- For customizing I clone the v2 repository (https://github.com/telerik/kendo-theme-bootstrap/tree/v2)?
- For just using it, I include the `@progress/kendo-theme-bootstrap@2.0.0-beta.4` package?

Txs

**Comment by gyoshev** [comment]
Yes, with a side-note that if you are using angular-cli or a Webpack build, you can use or customize the theme without cloning the repository. Just redefine one of the [available variables](http://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/customization/) and include the SCSS from the package.

Since you reported having problems with building the theme through `npm run build`, the build process is available only when you clone the repository.

All available styling options are [documented in the styling overview](http://www.telerik.com/kendo-angular-ui/components/styling/) topic.

**Comment by rstabenow** [comment]
I tried to install the new version, but can not find any newer than 0.11.0 via npm:

npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! No compatible version found: @progress/kendo-theme-bootstrap@2.0.0-beta.4
npm ERR! Valid install targets:
npm ERR! ["0.11.0"]

Is version 2.0.0-beta.4 really released?

**Comment by isatemple** [comment]
@gyoshev I am able to customize using `$button-bg: #818181;` while placed before the import of the default theme, but as soon as I change the import to the bootstrap theme, I get nothing. I see the bootstrap theme, but no custom colors. Any ideas would be greatly appreciated.

`@import "~@progress/kendo-theme-default/scss/all";`
   vs
`@import "~@progress/kendo-theme-bootstrap/dist/all";`

From my package.json     
`"@progress/kendo-theme-bootstrap": "^2.4.0",`
`"@progress/kendo-theme-default": "^2.37.0",`

**Comment by gyoshev** [comment]
@isatemple to modify a theme, refer to its `scss/all` file -- it contains the theme source. The `dist/all` file contains the compiled CSS, which does not use the variables.
