### ISSUE TITLE
Font icons not exported correctly

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2661]
**Describe the bug**
Font icons are exported correctly 

**To Reproduce**
Export [this content](https://stackblitz.com/edit/angular-nzmeny?file=app/app.component.ts) and inspect gear icon

**Expected behavior**
Font icons should export correctly

**Comment by dtopalov** [comment]
Seems similar to https://github.com/telerik/kendo-angular/issues/1317#issuecomment-385956724

When "crossorigin" attribute is set, the icon is exported as expected:
https://stackblitz.com/edit/angular-nzmeny-gldmtk?file=index.html
