### ISSUE TITLE
[TreeView] Clicking on indeterminate checkboxes does not trigger the checkedChange event

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2662]
When clicking on an indeterminate parent node, the behavior is different in Chrome and Edge. 

The **checkedChange** event is fired as expected in Chrome and the node and all children are selected, while in Edge the event is not fired, the parent node gets unchecked, and the child nodes checked state is not changed:

https://stackblitz.com/edit/angular-7erevf-pfdwzt?file=app/app.component.ts // click the "Furniture" checkbox

**Comment by dimitar-pechev** [comment]
Works as expected in the latest version of Edge (Chromium).
