### ISSUE TITLE
Virtual scroll with grouping not working correctly

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2664]
**Describe the bug**
If collapse all rows in grouped grid with virtual scroll only one row is displayed and grid scroll is not updated according to new data height.
**To Reproduce**
1. Open this [stackblitz sample](https://stackblitz.com/edit/angular-4vtgqk-xukmhq?file=app/app.component.ts).
2. Group by City
3. Click Collapse all button
4. Try to collapse/expand some groups.

**Expected behavior**
It should adjust scroll according to new height of data.
It should show all groups.

**Broken in**
  ```
 v4.6.0
  ```

**Comment by dimitar-pechev** [comment]
Closing in favor of #2677 - demo working better there.

**Comment by ipeshev** [comment]
The demos are working in same way, there is duplicate tag for this case.

**Comment by dtopalov** [comment]
The collapseGroup and expandGroup methods are not supported in scenarios, involving the kendoGridGroupBinding directive - this is a documented limitation:

https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-collapsegroup

Leaving this one open as a possible enhancement, and closing the duplicate one.

**Comment by Raisolution** [comment]
Closing this in favor of tracking demand for such enhancements in the feedback portal.
