### ISSUE TITLE
[Grid] DateFilterMenu misses a CustomMessagesComponent allowing to translate "Today"

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2670]
**Describe the bug**
The [DateFilterMenu ](https://www.telerik.com/kendo-angular-ui/components/grid/api/DateFilterMenuComponent/)component misses a CustomMessagesComponent that allows to translate its "Today" message.

**To Reproduce**
Please check the following example demonstrating the use of the DateFilterMenu component:
https://stackblitz.com/edit/angular-ogsmjc-qtsnce?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-grid`.

**Comment by dimitar-pechev** [comment]
The messages can be configured through the [CustomMessagesComponent's](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/CustomMessagesComponent/) `filterDateToggle` and `filterDateToday` properties. [Here's an example](https://stackblitz.com/edit/angular-ybuy7x).

**Comment by dtopalov** [comment]
Available in v.4.7.4
