### ISSUE TITLE
[Grid] [kendoGridGroupBinding] is not working correctly with collapseGroup()

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2677]
**Describe the bug**
When `[kendoGridGroupBinding]` is used and group(s) are collapsed using [`collapseGroup()`](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/GridComponent/#toc-collapsegroup), all but the first group are shown.

**To Reproduce**
https://stackblitz.com/edit/angular-4vtgqk-epxdrq

1. Group the entries by City by dragging the column header.
2. Click `Collapse all`.
3. All groups except the first one are not visible.

**Expected behavior**
All groups should be collapsed and visible.

**Comment by dtopalov** [comment]
Closing this as a duplicate; the original enhancement item can be tracked here:

https://github.com/telerik/kendo-angular/issues/2664
