### ISSUE TITLE
[TimePicker] focus state is not removed on mobile browsers

### ISSUE THREAD

**Issue by MelvilQ** [telerik/kendo-angular#2678]
**Describe the bug**
The focus state is not correctly removed on mobile browsers if the user opens and closes the picker by clicking on the clock button and then clicks to some other input on the same page. No (blur)-event is fired and the class .k-state-focused is not removed.

**To Reproduce**
1. Open [this example](https://angular-iyejht.stackblitz.io/) with a mobile browser (or use the responsive view in Chrome dev tools)
2. Click on the clock button to open the picker
3. Click on the clock button again to close the picker
4. Focus the input on the bottom or click somewhere else to remove the focus from the picker.

**Expected behavior**
A (blur)-event is fired and .k-state-focused is removed

**Browser**
All mobile browsers (including responsive view in Chrome dev tools). On desktop browsers the behavior is as expected.

**Comment by dimitar-pechev** [comment]
Also reproduced with the **DatePicker**.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dateinputs`

**Comment by dimitar-pechev** [comment]
Released in **v4.2.2**.
