### ISSUE TITLE
[Button] [tabIndex] does not set tabindex attribute

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2679]
**Describe the bug**
`[tabIndex]`(note the capital **I**) does not set the `tabIndex` attribute of the button.

**To Reproduce**
https://stackblitz.com/edit/angular-pxqiwf

1. Right click on the button and click inspect.
2. The inspected button does not have a `tabindex` attribute set.

**Expected behavior**
`tabindex` should be set.

**Additional notes**
This input has to be deprecated in favor of the native `[tabindex]`(not the lowercase **i**)

**Comment by Raisolution** [comment]
Fixed in `v5.2.1`.
