### ISSUE TITLE
[DropDowns] Upon selection the options list is automatically scrolled up

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2680]
**Describe the bug**
Using grouped data and [autoClose]="false" for a MultiSelect then selecting any of the last items from the options list, will cause the list to be scrolled up and the selected item is no longer visible.
The same applies for a DropDownList where the (close) event is prevented. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-qpbow1-zmnjuj?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dropdowns`

**Comment by dimitar-pechev** [comment]
Released in **v4.2.6**.
