### ISSUE TITLE
[Grid] the [hidden] property of the columns causes some unexpected behavior

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2681]
**Describe the bug**
Setting the [hidden] property of any Grid column to false, doesn't allow the Grid to automatically calculate the widths of the columns. With that setup, the autoFitColumns() method doesn't function as expected either.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-ijs9xm-tne5s3?file=app%2Fapp.component.ts

**Comment by tsvetomir** [comment]
Fixed in the latest [development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), [see demo](https://stackblitz.com/edit/angular-ijs9xm-y7sgg6?file=app%2Fremote-binding.directive.ts).
