### ISSUE TITLE
[Window] missing a .k-window-actions class

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2683]
**Describe the bug**
The rendered DOM of the Window is missing a div with **.k-window-actions** class that should wrap the action buttons in the TitleBar. The Dialog has the proper structure. Thus, when using the SCSS variables to customize the appearance of the TitileBar the proper styles are applied only to the Dialog.

**To Reproduce**
Please run the following project in order to observe the issue:

[dialogs-titles.zip](https://github.com/telerik/kendo-angular/files/4071873/dialogs-titles.zip)

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dialog`

**Comment by siyka-marinova** [comment]
Fix is now also available in `kendo-angular-dialog v4.1.2`
