### ISSUE TITLE
[ToolBarButtonGroup] Inverted navigation in RTL

### ISSUE THREAD

**Issue by Raisolution** [telerik/kendo-angular#2684]
**Describe the bug**
When in RTL mode, arrow right moves the focus to the left inside a `<kendo-toolbar-buttongroup>`.

**To Reproduce**
https://stackblitz.com/edit/angular-9uauhw

1. Focus the toolbar without clicking on any tool.
2. Press arrow right until the button group is focused.
3. Press arrow left.
4. Focus moves back in the button group.

**Expected behavior**
Focus should not move back in the button group.

**Screenshots**

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-toolbar`

**Comment by siyka-marinova** [comment]
The fix is now available in the latest `kendo-angular-toolbar v3.1.0`
