### ISSUE TITLE
[Editor] inserting a link causes some issues

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2686]
**Describe the bug**
Inserting a link doesn't seem to work as expected. The action buttons of the Dialog are improperly disabled unless the "Open link in new window" checkbox is checked/uncheked.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-hf7nfk-mkke3a?file=app/app.component.ts

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by valchev** [comment]
Cannot reproduce with v1

Example: https://stackblitz.com/edit/angular-64gzgn?file=app%2Fapp.component.ts
