### ISSUE TITLE
[Sortable] cannot drop to the last position in list immediately

### ISSUE THREAD

**Issue by GitJacek** [telerik/kendo-angular#2690]
**Describe the bug**
When you have multiple sortable list, and you move item across them you cannot drop item to the last position. You have to drag over last position - 1, and then you are able to drop it on last position. It also exsist in Templates example.
**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/sortable/templates/
1. Drag 'Magenta'.
2. Try to place it at the end of Pallete D, after 'FireBrick'(but don't drag over other items before).

**Expected behavior**
'Magenta' should be placed after 'FireBrick' without need to temporary draf over between 'IndianRed' and 'FireBrick'

**Browser**
 - Browser Chrome
 - Version 79

**Additional context**
I've noticed that when i finally drop 'Magenta' at the last position, and it is active(it has dotted border) then i'm able to drag and drop item from another list at the last position immediately, but only if last item in destination list has this broder.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/). With known glitch - https://github.com/telerik/kendo-angular/issues/2405

**Comment by tapopov** [comment]
Available in 3.0.6
