### ISSUE TITLE
The widndow titlebar buttons titles cannot be localized

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-angular#2693]
**Describe the bug**
The titlebar buttons titles of the Window component cannot be translated.

**Expected behavior**
* The text for the close button should be read from the [translation messages](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/).
* The [dialog settings](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowSettings/) should accept overriding the close button text.
* A [custom messages](https://www.telerik.com/kendo-angular-ui/components/grid/globalization/#toc-custom-messages) component should be provided for overriding the close message through the Angular i18n framework.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-messages`

**Comment by Raisolution** [comment]
Fix is live in `v4.1.2`
