### ISSUE TITLE
Treeview: CheckableSettings: show or hide checkboxes by tier

### ISSUE THREAD

**Issue by Justuceh** [telerik/kendo-angular#2694]
Hello support team,

Currently there is no way of showing or hiding checkboxes in the treeview unless you either use them or don't use them.  It would be beneficial if a feature was added that allowed configuration of what tier's in the treeview got checkboxes.  Even adding the ability to enable or disable them by tier only would be great.

Thank you!
Justuce

**Comment by gkarapeev** [comment]
Hi @Justuceh, and thank you for submitting this request. May I ask you if I've understood it correctly?

By "tier", do you mean the level/depth of the TreeView data?

So for example in the screenshot below, you would like to be able to disable e.g. tier 3 and have no checkbox there, but still have checkboxes on the other tiers - both higher and lower levels:
![Screenshot 2022-05-18 at 11 42 39](https://user-images.githubusercontent.com/45083324/168998487-f76c68a3-a316-4cd1-a539-8f1ee779b538.png)

**Comment by yanmariomenev** [comment]
I am happy to say that conditional checkboxes are available in version 13.2.0:

https://www.telerik.com/kendo-angular-ui/components/treeview/checkboxes/#toc-conditional-checkboxes
