### ISSUE TITLE
[ChipList] dynamic chips cause chips to be unselectable

### ISSUE THREAD

**Issue by pabloxn** [telerik/kendo-angular#2695]
**Describe the bug**
If you change the chips within the chiplist the chips become unselectable in single mode.

**To Reproduce**
1. create an empty set of chips
2. then add a new set of chips

**Expected behavior**
I expect the chips to be selectable if i change the chips

**Comment by Raisolution** [comment]
Hi @pabloxn,

Thank you for reporting this issue. I managed to reproduce it in [the following example](https://stackblitz.com/edit/angular-ljk2si?file=app/app.component.ts). We'll publish a fix as soon as possible.

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by pabloxn** [comment]
thanks  - that is brilliant

**Comment by tsvetomir** [comment]
Fix published in v5.2.2
