### ISSUE TITLE
[MultiSelect] selected tags are cleared when filter is applied

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2698]
When **valuePrimitive** option is set to false and the MutliSelect is filtered by any string, clicking the 'x' on a selected tag clears all the tags.

**To Reproduce**
1. Select two items.
2. Filter by any string to return 'no data found'.
3. Click on the 'x' of any of the selected option.
4. Expect only the option with pressed 'x' to be deleted.

https://stackblitz.com/edit/angular-fjkggo-r5ri4f?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dropdowns`

**Comment by dimitar-pechev** [comment]
Released in **v4.2.6**.
