### ISSUE TITLE
Template parse errors: 'kendo-dialog-actions' is not a known element

### ISSUE THREAD

**Issue by chavda141286atul** [telerik/kendo-angular#270]
Hi, 

I have kendo-dialog-actions and already i have updated package and also install kendo-dialog-actions but still have problem as per bellow.

Template parse errors:
'kendo-dialog-actions' is not a known element:
1. If 'kendo-dialog-actions' is an Angular component, then verify that it is part of this module.
2. If 'kendo-dialog-actions' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    </form>-->

    [ERROR ->]<kendo-dialog-actions>
        <button type="button" class="k-button" (click)="onCustomersContactCan"): CustomersContactComponent@32:4
'kendo-dialog' is not a known element:
1. If 'kendo-dialog' is an Angular component, then verify that it is part of this module.
2. If 'kendo-dialog' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<kendo-dialog *ngIf="active" title="Customer Contacts" (close)="closeCustomersContactForm()">    
  "): CustomersContactComponent@0:0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:
'kendo-dialog-actions' is not a known element:
1. If 'kendo-dialog-actions' is an Angular component, then verify that it is part of this module.
2. If 'kendo-dialog-actions' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    </form>-->

Can you please suggest me if you have any idea about this error.

Thanks
Atul

**Comment by tsvetomir** [comment]
Please check that you're registering the DialogModule in your application module.
See the [Installation](http://www.telerik.com/kendo-angular-ui/components/dialog/#toc-installation) instructions.

**Comment by chavda141286atul** [comment]
Hi,

Thanks for reply its was not registered DilogModule in the application module because of Kendo-Dilog not work...

Thanks you much for your quick reply.

**Comment by markzolotoy** [comment]
where on that link http://www.telerik.com/kendo-angular-ui/components/dialog/#toc-installation are the installation instructions?

**Comment by Raisolution** [comment]
Hi @markzolotoy 

The installation instructions are available here:

https://www.telerik.com/kendo-angular-ui/components/dialogs/#toc-installation

**Comment by MikeOtown** [comment]
I'm getting this error.  I have:

`import { DialogsModule, WindowModule } from "@progress/kendo-angular-dialog";`

in app.module.ts.

Above installation instruction links don't seem to work anymore.

**Comment by MikeOtown** [comment]
My error was fixed by adding the module with the error to app.module.ts @NgModule({
   declarations
