### ISSUE TITLE
[TreeView] .k-state-focused class is not added on selected item when using Keyboard navigation

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2701]
Using Keyboard navigation, when opening a parent node with the right arrow, the first child is not focused if the same is selected (the _.k-state-focused_ class is not added). 

However, if we expand its children and get back to the same selected node, the class is added properly.

Here is a screencast of the issue:
https://screencast-o-matic.com/watch/cYVYoIvKPN

**To Reproduce**
https://stackblitz.com/edit/angular-em7xb4-ctbwbt?file=app%2Fapp.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds) in kendo-angular-treeview.

**Comment by dimitar-pechev** [comment]
Shipped with **v5.0.0** of the TreeView package.
