### ISSUE TITLE
[ComboBox] The (filterChange) event doesn't fire when removing the last input character

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2703]
**Describe the bug**
When a filterable ComboBox is bound to a formControl and the value of the frmControl is updated on (filterChange) event, then when using the backspace to clear the input values the (filterChange) will not fire for the last available character.

**To Reproduce**
Please check the following example demonstrating that behavior:
https://stackblitz.com/edit/angular-uvqehc-kdkszx?file=app/app.component.ts

1. Type in '123'
2. Use backspace to remove the input text.
3. Notice that the (filterChange) event isn't fired when removing the last left character within the input.

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released in **v4.4.0**.
