### ISSUE TITLE
Grid incompatibility with Angular 9 (rc.9)

### ISSUE THREAD

**Issue by elca-lan** [telerik/kendo-angular#2705]
I am aware that Angular 9 isn't even out yet. But I have been experimenting with the release candidates since they started arriving and it seems that with the latest release of the Kendo UI Framework you have made some significant improvements with regards to Angular 9 compatibility, so I figured you would be interested in this bug that I have found.

**Describe the bug**
When using column groups (or [Multi-Column Headers](https://www.telerik.com/kendo-angular-ui/components/grid/columns/headers/)) with an Angular 9 (rc.9) project, the _first_ column of a group simply disappears.

This seems to be caused by a combination of a change in the way that `ContentChildren` queries work in Angular 9 and a workaround in the Kendo `ColumnList` that tries to deal with the weird behavior of Angular 8. To be more precise, the workaround in question can be found in `column-list.js` in the `filterHierarchy` method where we can find the code `column.children.toArray().slice(1)` which _removes_ the first element of the children collection. In Angular 8, this first child is the column group itself - which is odd since this is the result of a query for children _on_ that column group. In Angular 9 this behavior has changed so that the parent column group is no longer part of the query result and therefore, the workaround just removes the first _actual_ column.

**To Reproduce**
1. Start with the sample for [Multi-Column Headers](https://www.telerik.com/kendo-angular-ui/components/grid/columns/headers/)
2. Upgrade the project to Angular 9 (rc.9)
3. Run the project

You will see that the "UnitsInStock" column is missing in the result.

**Expected behavior**
Of course, all columns should be shown in the grid, including the first one of each (possibly nested) column group.

**Screenshots**
This is what the multi-column headers example looks like when running in an Angular 9 context.

![image](https://user-images.githubusercontent.com/43171533/72964566-8d2d7780-3dba-11ea-9da5-5540f53ff0ff.png)

**Browser**
Irrelevant

**Additional context**
An alternate solution to the currently implemented `.slice(1)` workaround would be to just filter out the parent column group itself: `column.children.toArray().filter(child => child !== column)`.

This should work in Angular 8 and not break with Angular 9 since it is a more targeted solution to the weird Angular 8 behavior.

**Comment by tsvetomir** [comment]
Thanks for the detailed bug report! The problem should be fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by lord-executor** [comment]
I have just tested this in my application with `@progress/kendo-angular-grid@4.6.3-dev.202001240954` and can confirm that this works.

Thanks a lot for the quick fix!

**Comment by vitalynechaev** [comment]
is the grid compatible with Angular 9? I am getting this after the upgrade.
npm WARN @progress/kendo-angular-excel-export@3.1.2 requires a peer of @angular/common@6 - 8 but none is installed. You must install peer dependencies yourself.                                                                                                                                                          npm WARN @progress/kendo-angular-excel-export@3.1.2 requires a peer of @angular/core@6 - 8 but none is installed. You must install peer dependencies yourself.                                                                                                                                                            npm WARN @progress/kendo-angular-pdf-export@2.0.2 requires a peer of @angular/common@6 - 8 but none is installed. You must install peer dependencies yourself.                                                                                                                                                            npm WARN @progress/kendo-angular-pdf-export@2.0.2 requires a peer of @angular/core@6 - 8 but none is installed. You must install peer dependencies yourself.

**Comment by tsvetomir** [comment]
Fixed in the latest stable versions:
* `@progress/kendo-angular-excel-export@3.1.3`
* `@progress/kendo-angular-pdf-export@2.0.2`
* `@progress/kendo-angular-grid@4.6.3`
