### ISSUE TITLE
Tooltip 'anchor elements' implementation doesn't set undefined, null and '' value

### ISSUE THREAD

**Issue by tipag** [telerik/kendo-angular#2709]
**Describe the bug**
If using kendo tooltips with "anchor elements", undefined, null and "" don't impact the shown tooltiptext.

**To Reproduce**
I simplified the "anchor elements" sample of the documentation site (https://www.telerik.com/kendo-angular-ui/components/tooltip/anchor-elements/) to visualize the problem:
https://stackblitz.com/edit/angular-q7ehbe

hover over the Tango button -> tooltip is shown, click on the button -> variable is set to undefined -> tooltiptext is still the same
mouse leave button -> hover over button again -> tooltiptext is still the same
The same happens if the value is set to null or "".

**Expected behavior**
The standard browser tooltip shows a tooltip with undefined for undefined, a tooltip with null for null and no tooltip if "" is set.

In my case I need to show a tooltip if a text is set and no tooltip if either undefined, null or "" is set.

**Additional Information**
The issue described here [2708](https://github.com/telerik/kendo-angular/issues/2708) seems to also effect "anchor elements" tooltips.
In this case however, additionally to the browser tooltip shown with the correct text, the "anchor element" tooltip is also shown without content.
https://stackblitz.com/edit/angular-q7ehbe-dtyt3b

**Browser**
 - OS: Windows 10
 - Browser
 -- Chrome: 79.0.3945.117
 -- Firefox: 68.4.1esr

**Comment by svetq** [comment]
also requested in private support thread 1451983

**Comment by inikolova** [comment]
The current implementation of the Kendo UI for Angular Tooltip relies on the following approach to prevent displaying the default browser tooltip:

- When the Tooltip is open:

-- Тhe value of its anchor element's `title` attribute is assigned to a `data-title` attribute;

-- The value of its anchor element's `title` attribute is set to empty sting.

- When the Tooltip is closed, the current value of the `data-title` attribute is set back to the `title` attribute. 

Angular has a specific behaviour when `title` / `attr.title` values are set to `null` / `undefined`:

- `attr.title` binding -> setting the value to `null` / `undefined` removes the `title` attribute from the DOM element;

- `title` binding -> setting the value to `null` / `undefined` changes the value of the `title` attribute to the string `null` / `undefined`.

However, the case with empty string differs - in this case no actual value is assigned to the `title` attribute. When the value of the `title` attribute of an element with an opened Tooltip is changed dynamically, we cannot check whether the `title` attribute value is set to an empty string by the developer, or through our internal logic.

Based on the info above, dynamically changing the value of the `title` attribute of an element to an empty string, while its Tooltip is open, is not supported, and can be considered a limitation.

**Comment by Raisolution** [comment]
Fix is available in the latest version of the package `3.0.2`
