### ISSUE TITLE
Kendo-angular-grid cell template problem

### ISSUE THREAD

**Issue by tejasdhimmar** [telerik/kendo-angular#271]
We remove old node modules folder and take latest version of Kendo-angular with "npm install" command. In old version we are working with  "@progress/kendo-angular-grid": "0.3.3", now it is changed to "@progress/kendo-angular-grid": "^0.14.1".  In old version we generate link drop down button in grid cell template using following code. 

 <kendo-grid-column [sortable]="false" width="400">
                <template kendoHeaderTemplate let-column>
                </template>
                <template kendoCellTemplate let-dataItem>
                    <div>
                        
                        <a materialize="dropdown" [materializeParams]="[{}]" class='dropdown-button btn orange darken-2' (click)="selectSupplier(dataItem)">
                            <div>
                                <i class="material-icons right">mode_edit</i>actions
                            </div>
                        </a>
                        
                        <ul [attr.id]="'action-menu' + dataItem.id" class="dropdown-content">
                            <li>
                                <a materialize="modal" [materializeParams]="[{dismissible: false}]" class="waves-effect waves-light modal-trigger orange-text darken-2" (click)="openEditModal()">
                                    <i class="tiny material-icons left">visibility</i>Quick View
                                </a>
                            </li>
                            <li>
                                <a [routerLink]="['/supplier-details', dataItem.id]" class="orange-text darken-2">
                                    <i class="tiny material-icons left">mode_edit</i>Edit
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a class="red-text text-darken-2 waves-effect waves-light modal-trigger" (click)="openDeleteModal()">
                                    <i class="tiny material-icons left">delete</i>Delete
                                </a>
                            </li>
                        </ul>
                    </div>
                </template>
            </kendo-grid-column>

Now it is not working. It not generates link button and doesn't give any error in console window. Now what I have to do this problem

**Comment by rkonstantinov** [comment]
I guess you have wrapped the links inside a ```<template>``` tag and have used the grid header directive?
If so you should make sure you have updated the naming of the directives as described in [this issue](https://github.com/telerik/kendo-angular/issues/205).

**Comment by tejasdhimmar** [comment]
Now link button is visible in Grid cell template but still on click event of the "Action" button hidden menu not open but typescript function "selectSupplier(dataItem)" function is calling.

**Comment by rkonstantinov** [comment]
Please provide a [plnkr](https://plnkr.co/) which demonstrates the issue in question.
