### ISSUE TITLE
[Grid] updating the columns don't trigger a changedetection

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2711]
**Describe the bug**
When using virtual columns for the Grid or TreeList and the initially passed columns array is updated to contain the same number of columns, but different data objects, then the Grid doesn't re-render its columns to display them properly.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-yligux?file=app/app.component.ts

**Comment by tsvetomir** [comment]
Can be worked around by adding a trackBy function, see [updated demo](https://github.com/telerik/kendo-angular/issues/2711).

```html
<kendo-grid-column
  *ngFor="let col of dataCols; trackBy: trackFn"
  [field]="col.field"
  [width]="col.width">
</kendo-grid-column>
```

```ts
trackFn(column: any) {
  return column.field;
}
```

**Comment by billdwhite** [comment]
Unfortunately, for those of us with more complex data, this does not work.  In our particular situation, we are working with dynamically configured columns.  Some of the columns are regular and some are grouped columns with sub columns.  In that case, we have to use the wrap the columns in an `ng-template` with an ngIf statement.  For that situation the `ngFor` with the `trackBy` you suggested is not applicable.  Instead, we have to use the `[ngForTrackBy]` which does not fix the problem.

See here or look at snippet below
https://stackblitz.com/edit/angular-grid-refresh-bug-2

```
<kendo-grid 
  [kendoGridBinding]="gridData" 
  [scrollable]="'virtual'" 
  [pageSize]="pageSize$ | async"
  [height]="gridHeight$ | async" 
  [sortable]="true" 
  [virtualColumns]="true" 
  [rowHeight]="rowHeight"
  [filterable]="false">

  <ng-template ngFor let-column [ngForOf]="columnsSubject$ | async" [ngForTrackBy]="trackFn">

    <kendo-grid-column *ngIf="column.type === 'single'" [field]="column.field" [width]="column.width"[title]="column.name">
      <ng-template *ngIf="column.field === 'name'" kendoGridCellTemplate let-dataItem="dataItem" let-rowIndex="rowIndex">
        <custom-cell-renderer [data]="dataItem"></custom-cell-renderer>
      </ng-template>
    </kendo-grid-column>

    <kendo-grid-column-group *ngIf="column.type === 'multi'" [title]="column.name">
      <ng-template ngFor let-subColumn [ngForOf]="column.childColumns">
        <kendo-grid-column *ngIf="subColumn.type === 'single'" [field]="subColumn.field [width]="subColumn.width" [title]="subColumn.name">
        </kendo-grid-column>
      </ng-template>

    </kendo-grid-column-group>
  </ng-template>

</kendo-grid>
```

**Comment by tsvetomir** [comment]
I've messed up the example above, the trackBy function should should return the index. I've updated it to match the example and fixed the link.

This is the [updated version](https://stackblitz.com/edit/angular-grid-refresh-bug-2-eyjzuq?file=app%2Fapp.component.ts) of your example with the workaround applied.

**Comment by billdwhite** [comment]
@tsvetomir Thanks. That seems work now.
