### ISSUE TITLE
Calendar Component issue resizing width

### ISSUE THREAD

**Issue by kotva006** [telerik/kendo-angular#2712]
**Describe the bug**
Changing the width of the calendar component to anything larger than 342px causes the day of week headers of the calendar component to no longer line up with their columns.
**To Reproduce**
https://stackblitz.com/edit/angular-jersjz

It renders 2 different calendars with the default width and one larger causing the larger withs day of the week headers to not be aligned.

**Expected behavior**
I would expect the whole date table to expand with the rest of the calendar not just the day of week headers.

**Browser**
 - OS: Windows
 - Browser [Firefox, Edge, Chrome]
 - Version [72.0.2, 79.0.309, 79.0.3945]

**Comment by dimitar-pechev** [comment]
@kotva006, the problem is related to the rendering and styles of the widget - not the angular component functionality. I'd ask you to raise this issue in the dedicated [themes repo](https://github.com/telerik/kendo-themes) as it affects all Kendo suites using this **Calendar** rendering.
