### ISSUE TITLE
[ToolBar] Error is thrown when disabled button in button group is clicked

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2713]
**Describe the bug**
If a buttongroup consists only of disabled buttons, when one of the buttons is clicked an error is thrown.

**To Reproduce**
https://stackblitz.com/edit/angular-psxgnz-d6l6xe

1. Click on any of the buttons inside the `<kendo-toolbar-buttongroup>`.
2. Error is thrown.

**Expected behavior**
An error should not be thrown.

**Additional context**
This is only reproducible if all the buttons in the button group are disabled.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-toolbar`

**Comment by siyka-marinova** [comment]
The fix is now available in the latest `kendo-angular-toolbar v3.1.0`
