### ISSUE TITLE
[Editor] unable to change the value programmatically when component is disabled

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2714]
**Describe the bug**
Currently it is unable to change the value of the Editor programmatically when the Editor is disabled.

**To Reproduce**
https://stackblitz.com/edit/angular-dn5ouy-xngtjq?file=app/app.component.ts

**Comment by ggegelya** [comment]
Hello! i've got the same error on the editor

Is there any updates on it?

**Comment by Raisolution** [comment]
Available in `v3.0.1` of the Editor.
