### ISSUE TITLE
[GRID] grid template column not refreshed once grid data property is updated

### ISSUE THREAD

**Issue by btaymaz** [telerik/kendo-angular#2715]
**Describe the bug**
grid template column not refreshed once grid data property is updated

**To Reproduce**
When I filter data everything updated but this column:

<kendo-grid-column media="" [width]="'2'" [title]="''" [headerClass]="'k-header-custom'" [class]="'k-column k-column-centered'">
    <ng-template kendoGridCellTemplate let-dataItem>
      <i [ngClass]="dataItem.listClass == 'Campaign' ? 'fal fa-at' : dataItem.listClass == 'List' ? 'fal fa-user-friends' : dataItem.listClass == 'Query' ? 'fal fa-bullseye-pointer' : ''"></i>
    </ng-template>
  </kendo-grid-column>

I tried suggestions from this post but no luck.

https://github.com/telerik/kendo-angular/issues/743

**Comment by dtopalov** [comment]
Hi @btaymaz,

I could not reproduce the described behavior - the templates in all columns seem to be working as expected:

https://stackblitz.com/edit/angular-9n91fo-pv8oca?file=app/app.component.ts

Can you please update the example above, or provide a similar one where the issue can be observed?

**Comment by btaymaz** [comment]
Hi Dimiter,
I think you are right, my app is smilar to this one:

https://stackblitz.com/edit/angular-9n91fo-buhgvm

If I use kendo icons works perfectly. If I use fontawesome icons it doesn't
work. I think it is something about fontawesome.

Thanks

bulent

**Comment by tsvetomir** [comment]
I tried reproducing the issue in a local project, but without success. I'm attaching it here for reference: [grid-font-awesome.zip](https://github.com/telerik/kendo-angular/files/4752025/grid-font-awesome.zip).

This issue doesn't seem to be a bug in the component itself, so I'd like to ask you to open a [support ticket](https://www.telerik.com/account/support-tickets) for further assistance.
