### ISSUE TITLE
Cannot scroll when panning or zooming is enabled on the chart

### ISSUE THREAD

**Issue by ujjwal1801** [telerik/kendo-angular#2718]
My webpage on mobile has multiple kendo charts acquiring the full width of the page on mobile and also, panning is enabled. Now I'm unable to scroll my page on mobile if the event fires from the chart. A suggestion from my side would be to enable scrolling if the event fires from anywhere except the chart area such as the space after the category axis or legends. As shown in the image, the scrolling should be enabled as long as the event doesn't fire from the highlighted area since the panning and zooming is functional for that area only.

**Comment by Raisolution** [comment]
Hello @ujjwal1801 

Please log the feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui), so we can track the respective customer demand for implementing it.
