### ISSUE TITLE
[Combobox, Autocomplete] Floating label is overlapping the input text when escape key is pressed

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-angular#2720]
**Describe the bug**
Floating Label is overlapping input's value when the esc key is pressed and the user is typing an actual value.

**To Reproduce**
https://stackblitz.com/edit/angular-hmjoew?file=app/app.module.ts

1. Focus the input
2. Press esc key
3. Start typing in the input

**Expected behavior**
When esc key is pressed and the user starts typing again, the floating label should not overlap the input's value.

**Screenshots**
![image](https://user-images.githubusercontent.com/8842674/73534435-cd7b9e00-4429-11ea-900b-e6d101ffe6ad.png)

**Additional context**
Тhe bug is reproducible for both Floating Label component and TextBoxContainer with ComboBox and Autocomplete components.

**Comment by ipeshev** [comment]
Fixed in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds)

**Comment by dimitar-pechev** [comment]
Released in **v4.2.5** of `@progress/kendo-angular-dropdowns`.
