### ISSUE TITLE
Dragged item not positioned correctly when in dialog

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2721]
**Describe the bug**
Dragged item is not positioned correctly when treeview is used inside dialog

**To Reproduce**
https://stackblitz.com/edit/angular-qvdafh

**Expected behavior**
It should show dragged element correctly

**Comment by lon-yang** [comment]
When using treeview inside `kendo-splitter`, dragged items are not positioned correctly too
https://stackblitz.com/edit/angular-7vj39g

**Comment by dimitar-pechev** [comment]
We've released a fix for the issue in our [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) (**v4.1.1-dev.202002201511**). [Here's your example](https://stackblitz.com/edit/angular-7vj39g-gytrt4) with the updated package version. 

After some additional testing on our side is done, we'll release the fix in the official channel, but you can still use it even now.

**Comment by ipeshev** [comment]
@lon-yang this fix works in KendoSplitter as well.

**Comment by lon-yang** [comment]
@dimitar-pechev , @ipeshev  Thanks.

**Comment by dimitar-pechev** [comment]
Released in **v4.1.1**.
