### ISSUE TITLE
Kendo grid table filter is not working for all fields

### ISSUE THREAD

**Issue by codelerner** [telerik/kendo-angular#2723]
I used kendo grid filter for a table but it is not working for some fields in the same table having array data. Can any one help with better idea.

**Comment by codelerner** [comment]
> I used kendo grid filter for a table but it is not working for some fields in the same table having array data. filter option is not working for itOwner and businessOwner fields. can any one help with better idea.
> 
> <kendo-grid [data]="gridData" [pageSize]="state.take" [skip]="state.skip" [sort]="state.sort" [filter]="state.filter"
> [filterable]="true" [sortable]="true" [columnMenu]="{ sort: true, filter: true, lock: false, columnChooser: true }"
> [pageable]="{
> buttonCount: buttonCount,
> info: info,
> type: type,
> pageSizes: pageSizes,
> previousNext: previousNext
> }" (dataStateChange)="dataStateChange($event)">
> 
> 
> <kendo-grid-boolean-filter-cell [column]="column" [filter]="filter">
> 
> 
> 
> 
> 
> <kendo-switch class="opt-switch" [(ngModel)]="dataItem.optIn" [onLabel]="'OPTED OUT'" [offLabel]="'OPT OUT'"
> (valueChange)="applicationOPTChanged(dataItem)" [placement]="'top'" container='body'
> ngbTooltip={{dataItem.optIn}} [disabled]="statusCode > 2 || !hasEditPermissions">
> ```
> </ng-template>
> ```
> 
>      {{dataItem?.applicationName}}
> {{item?.key | titlecase}}: {{item.value}}
> {{item?.key | titlecase}}: {{item.value}}
> and the data is like
> 
> [
> {
> "applicationId": 2668,
> "applicationName": "Active",
> "itOwner": {
> "contactName": "Travis Quella",
> "contactEmail": "[Travis.Quella@Thrivent.com](mailto:Travis.Quella@Thrivent.com)"
> },
> "businessOwner": {
> "contactName": "Quella, Travis",
> "contactEmail": null
> },
> },
> {
> "applicationId": 2669,
> "applicationName": "AFP - Iconvert server",
> "itOwner": {
> "contactName": "Travis Quella",
> "contactEmail": "[Travis.Quella@Thrivent.com](mailto:Travis.Quella@Thrivent.com)"
> },
> "businessOwner": {
> "contactName": "Quella, Travis",
> "contactEmail": null
> },
> },

**Comment by mbechev** [comment]
Hi @codelerner 

The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
