### ISSUE TITLE
[Editor] Different height with iframe

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2726]
**Describe the bug**
Setting height for the editor through css does not work properly when an iframe is used.

**To Reproduce**
https://stackblitz.com/edit/angular-tvpyeu

**Expected behavior**
Both configurations should behave have the same height.

**Comment by inikolova** [comment]
It appears this is a Chromium issue - I logged a bug to the Chromium team members

https://bugs.chromium.org/p/chromium/issues/detail?id=1051457&can=2&q=iframe%20height%3A%20100%25

**Comment by Raisolution** [comment]
We need to come up with a (temporary) workaround for this

**Comment by Raisolution** [comment]
Fixed in `v1.0.4`
