### ISSUE TITLE
Multiselect loss of focus with allowCustom and autoClose

### ISSUE THREAD

**Issue by blemaire** [telerik/kendo-angular#2728]
**Describe the bug**
Not able to add 2 custom values in a row in multiselect.

**To Reproduce**
- set `autoClose=true`
- set `allowCustom=true`
- add a custom value by typing the combobox search bar and pressing enter
- I cannot add a second custom value without clicking in the search bar again.

The issue is visible in the below GIF and testable in the following stackblitz: https://stackblitz.com/edit/angular-mhe7k7?file=app/app.component.ts

![kendo multiselect bug](https://user-images.githubusercontent.com/7140322/73830659-4f424180-4805-11ea-9825-2d364c1e79cc.gif)

Because the search bar does not have the focus, we are also unable to close the popover without regaining focus on the search bar first

**Expected behavior**
After adding a custom value, I should be able to carry on typing to add a new one or close the popover by clicking outside of the component.

**Screenshots**
N/A

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 79.0.3945.130

**Additional context**

**Comment by ipeshev** [comment]
Currently, when custom entry is added by pressing enter, input is not cleared but keeps previously added custom entry.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released in v4.4.0.
