### ISSUE TITLE
[Grid] Incorrect layout when using group header column template with detail template

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2730]
The Gris has incorrect layout when using **kendoGridGroupHeaderColumnTemplate** in combination with **kendoGridDetailTemplate**, which causes the group header column template to move with one cell to the left. 
![2020-02-06_1417](https://user-images.githubusercontent.com/33104481/73936440-8723b480-48eb-11ea-8fad-563851d57bd5.png)
The **Average: 19.47** aggregate should be under Unit Price column

**To Reproduce**
https://stackblitz.com/edit/angular-rpvoq5?file=app%2Fapp.component.ts

**Comment by tsvetomir** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fix released in v4.6.4
