### ISSUE TITLE
[Notification] Animation delays the opening of the notification when slide animation is selected

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#2732]
**Describe the bug**
When the slide animation is selected, the opening of the notification is delayed, instead of being animated. The animation works fine when the fade option is chosen, and there is no delay.

**To Reproduce**
The issue is illustrated in the following stackblitz example:
https://stackblitz.com/edit/angular-sraqg2

**Expected behavior**
The notification should have an animation on opening and closing, without delay.

**Browser**
-Chrome

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by elena-gancheva** [comment]
Available in the official [`v2.1.0`](https://github.com/telerik/kendo-angular-notification/releases/tag/v2.1.0) version of the package.
