### ISSUE TITLE
[Grid] Locked columns cannot be scrolled vertically when "locked" is toggled dynamically

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2733]
When the "locked" state of Grid columns is toggled dynamically, the locked table cannot be scrolled vertically anymore:

https://stackblitz.com/edit/angular-baaxta-mu1hvr?file=app/app.component.ts

**Comment by tsvetomir** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fix released in v4.6.4
