### ISSUE TITLE
Editor 1.0.2 requires a peer of @angular/forms@4-8

### ISSUE THREAD

**Issue by sehaxx** [telerik/kendo-angular#2734]
**Describe the bug**
After update to Angular 9
npm WARN @progress/kendo-angular-editor@1.0.2 requires a peer of @angular/forms@4 - 8 but none is installed. You must install peer dependencies yourself.

**To Reproduce**
 "@angular/animations": "~9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/localize": "^9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "@ng-bootstrap/ng-bootstrap": "^5.2.1",
    "@ngtools/webpack": "^9.0.1",
    "@progress/kendo-angular-buttons": "^5.2.3",
    "@progress/kendo-angular-common": "^1.2.1",
    "@progress/kendo-angular-dateinputs": "4.2.1",
    "@progress/kendo-angular-dialog": "^4.1.2",
    "@progress/kendo-angular-dropdowns": "^4.2.4",
    "@progress/kendo-angular-editor": "1.0.2",
    "@progress/kendo-angular-inputs": "^6.4.2",
    "@progress/kendo-angular-intl": "^2.0.1",
    "@progress/kendo-angular-l10n": "^2.0.1",
    "@progress/kendo-angular-layout": "^4.2.1",
    "@progress/kendo-angular-messages": "^1.18.0",
    "@progress/kendo-angular-popup": "^3.0.5",
    "@progress/kendo-angular-toolbar": "^3.0.3",
    "@progress/kendo-angular-upload": "^5.2.0",
    "@progress/kendo-drawing": "^1.6.0",

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by Raisolution** [comment]
Hi @sehaxx

Thank you for noticing the wrong dependency. It is fixed `v1.0.3` of the Editor package.
