### ISSUE TITLE
Alignment of Time in Day/Multiday/Week-View is destroyed when navigate to another date or view

### ISSUE THREAD

**Issue by BeniFreitag** [telerik/kendo-angular#2735]
**Describe the bug**
Times on the left are wrong, when the date is changed, unless you scroll once in the appoinments-area.

**To Reproduce**
1. Open https://www.telerik.com/kendo-angular-ui/components/scheduler/#toc-basic-usage respectively https://5yr2zk.run.stackblitz.io. You see appointments with correct times on the left, starting at 8am.
2. Navigate one day forward. You'll see the times on the left at 12AM, but the appointments at 8AM. Scroll a little and times are immediately aligned correctly again. This happens on every date-change and view-changes.

**Expected behavior**
Times on the left must be always aligned correctly with appointments shown in the main-view.

**Screenshots**
![2020-02-07_17-14-58](https://user-images.githubusercontent.com/6669093/74045850-cc201780-49cd-11ea-924d-ee211b5a95c4.gif)

**Browser**
 - OS: Windows 10
 - Browser: Chrome 80

**Comment by shaizel** [comment]
Also reproduces when adding and editing events.
Started happening after updating to Chrome v80.

**Comment by tsvetomir** [comment]
Fixed in v1.1.4
