### ISSUE TITLE
Unnecessary change detection is triggered on every click if upload is added to the page

### ISSUE THREAD

**Issue by mark-kaleidoscope** [telerik/kendo-angular#2736]
I have created a minimal example:
App URL: https://kendo-uye53v.stackblitz.io
Editor URL: https://stackblitz.com/edit/kendo-uye53v

Open the console the click with the mouse on any place on the page. You can see that the change detection cycle of angular runs on every click. (The change detection is logged to the console using the getter changeDetectionCheck in AppComponent.)

I have checked the javascript code and the following part seems suspicious for me. It seems that the subscription to the document click event will always cause a change detection, because it is wrapped by NgZone.run(...)

 subscribeBlur() {
        if (!isDocumentAvailable()) {
            return;
        }
        this._ngZone.runOutsideAngular(() => {
            this.documentClick = fromEvent(document, 'click').pipe(filter((event) => {
                return !(this.wrapper !== event.target && this.wrapper.contains(event.target));
            }));
            this.blurSubscription = merge(this.documentClick, this.navigation.onTab).subscribe(() => this._ngZone.run(() => {
                if (this.navigation.focused) {
                    this.navigation.focused = false;
                    this.onTouchedCallback();
                    this.onBlur.emit();
                }
            }));
        });
    }

**Comment by Raisolution** [comment]
Fixed in the latest dev version of the `kendo-angular-upload` package.

**Comment by Raisolution** [comment]
Fix is available in `v5.2.1`
