### ISSUE TITLE
Unnecessary change detection is triggered on every keypress if dialog is on page

### ISSUE THREAD

**Issue by mark-kaleidoscope** [telerik/kendo-angular#2739]
I have created a minimal example:
App URL: https://angular-n4wles.stackblitz.io
Editor URL:  https://stackblitz.com/edit/angular-n4wles

Open the console the press any key. You can see that the change detection cycle of angular runs on every keypress. (The change detection is logged to the console using the getter changeDetectionCheck in AppComponent.)

Note: I believe that the method below should trigger change detection only if specific keys are pressed and not always. 

DialogComponent.prototype.onComponentKeydown = function (event) {
        var target = event.target;
        var parent = target.parentElement;
        if (hasClasses(target, DIALOG_ELEMENTS_HANDLING_ESC_KEY) ||
            hasClasses(parent, DIALOG_ELEMENTS_HANDLING_ESC_KEY)) {
            if (event.keyCode === Keys.esc) {
                this.close.emit();
            }
        }
        if (hasClasses(target, 'k-button') &&
            hasClasses(parent, DIALOG_ELEMENTS_HANDLING_ARROWS) &&
            (event.keyCode === Keys.left || event.keyCode === Keys.right)) {
            this.handleActionButtonFocus(parent, event.keyCode);
        }
        if (event.keyCode === Keys.tab) {
            this.keepFocusWithinComponent(target, event);
        }
    };

**Comment by Raisolution** [comment]
Thank you for reporting the problem. The same issue was reproducing in the Window component too.

Fixes for both are available in version `5.2.2` of the `kendo-angular-dialog` package.
