### ISSUE TITLE
NumericTextBox spin button shifted on IE10 (and possibly iPad/Phone)

### ISSUE THREAD

**Issue by JBildstein** [telerik/kendo-angular#274]
See image: 
![numerictextbox-ie10](https://cloud.githubusercontent.com/assets/12777835/22614997/b083ce62-ea8b-11e6-97be-9d1644f51e78.png)

Plunkr from the official documentation: http://plnkr.co/edit/Uc4iJmugI8h3ddtWlQu7?p=preview

**Comment by joneff** [comment]
A slight note on IE10 -- it's bundled only with pure Windows 8 (not 8.1), which was superseded by Windows 8.1 (that comes with IE11) and the support for Windows 8 has ended on January 12th 2016 (https://support.microsoft.com/en-us/lifecycle/search/?c2=16796).

That being said, considering IE 10 only supports the so called hybrid flexbox syntax, and we rely heavily on flexbox for the kendo-angular themes, issues related to IE10 will be given a lower priority than say iOS issues.

**Comment by inikolova** [comment]
Commit: https://github.com/telerik/kendo-theme-default/commit/62230eb8f4cab1ebb3f6f16e4a9d0de57510042b
