### ISSUE TITLE
[Toolbar] nesting a <kendo-toolbar-button> inside ng-container isn't possible

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2743]
**Describe the bug**
Currently using Angular 9 if a` <kendo-toolbar-button>` is nested within an ng-container then the button isn't rendered. There are no errors in the browser console and the application compiles successfully.
[toolbar.zip](https://github.com/telerik/kendo-angular/files/4185900/toolbar.zip)

**To Reproduce**
Please create an Angular 9 project or download the attached one and use the following markup:
```
<kendo-toolbar [overflow]="true">
	<ng-container>
		<kendo-toolbar-button [text]="'foo'">
		</kendo-toolbar-button>
	</ng-container>
</kendo-toolbar>
```

**Comment by ncrawlins** [comment]
I don't know if this needs to be a separate issue, but in a grid, grid-columns that are in an ng-container don't render either.  this was working in angular 8.

**Comment by svetq** [comment]
also reported in 1453814

**Comment by tsvetomir** [comment]
Seems to be caused by https://github.com/angular/angular/issues/34768. The fix seems to be on the way.

Can be worked around by adding `{ descendants: true }` to the `ToolBarComponent.allChildren` field, but there may be other instances of the same problem.

**Comment by svetq** [comment]
also reported in 1453886 regarding the Charts

**Comment by urdeveloper** [comment]
Had the same problem with toolbar using Angular 9.0.1. Just updated to 9.0.2, seems to be working now.
