### ISSUE TITLE
[Grid] the select all checkbox cell traps the focus

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2744]
**Describe the bug**
When using a navigable Grid and <kendo-grid-checkbox-column **[showSelectAll]="true"** ></kendo-grid-checkbox-column>

then when navigating with "Tab" and/or "Tab + Shift" to enter the cell with the select all checkbox makes the focus impossible to escape that cell.

**To Reproduce**
Please check the following screen recording:
https://screencast-o-matic.com/watch/cYnX2jwtcC

and example:
https://stackblitz.com/edit/angular-3ky4gj-usxvfu?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by Raisolution** [comment]
Available in `v4.6.4`
