### ISSUE TITLE
[Menu] First nested menu item does not show

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#2748]
**Describe the bug**
When using the Menu in Angular 9 the first nested menu item is not shown. 

**To Reproduce**
Use the Angular 9 and nest menu items inside menu items. The first nested menu item will not show.

Visible in the following screenshot:

![image](https://user-images.githubusercontent.com/52581229/74420337-ed608800-4e53-11ea-9808-970b96c5c258.png)

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-menu`

**Comment by siyka-marinova** [comment]
The fix is now available in the latest `kendo-angular-menu v2.0.2`
