### ISSUE TITLE
[Editor] Cannot set inline styles for <tr> and <td>

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2749]
**Describe the bug**
Cannot set inline styles for `<tr>` and `<td>` using `style` attribute

**To Reproduce**
https://stackblitz.com/edit/angular-eq93ye

**Expected behavior**
The inline styles in the `value` of the Editor should be respected.

**Comment by squadwuschel** [comment]
Yes we are not able to edit some EMail Templates inside the editor they are completly HTML Tables with inline styles

**Comment by dtopalov** [comment]
Fixed in the latest version of the @progress/kendo-angular-editor package:

https://stackblitz.com/edit/angular-rrbdny-mecq7s?file=app/app.component.ts
