### ISSUE TITLE
MultiSelect loses focus when you add custom value while [autoClose] is set to false

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#2753]
**Describe the bug**
The MultiSelect input whose autoClose property is set to false loses focus when you add custom values but it does not lose focus when values from the data is selected. When autoClose is set to true, the input does not lose focus in both the cases, i.e. adding custom values or adding values from the data

**To Reproduce**

The issue can be seen in the following StackBlitz example:

https://stackblitz.com/edit/angular-5je2mn-lkgjvd

1. Click into the drop down component. (drop down window opens)
2. Start typing 'Sma' then press Enter. (Small is selected and populated in the input area, the dropdown remains open, and the cursor is still present in the input area)
3. Type in 'X-Large' then press Enter. The input loses focus.

**Expected behavior**
The MultiSelect input whose autoClose property is set to false should not lose focus when you add custom values.

**Comment by dimitar-pechev** [comment]
Already tracking in #2728.
