### ISSUE TITLE
Avatar does not render properly when changing imageSrc or initials after intialization

### ISSUE THREAD

**Issue by geo242** [telerik/kendo-angular#2754]
**Describe the bug**
The avatar does not render the image or initial correctly if the initial value for the image or initials is not immediately available. 

**To Reproduce**
https://stackblitz.com/edit/angular-avatar-bug

**Expected behavior**
When the imageSrc or initials value changes, the avatar should render correctly

**Comment by elena-gancheva** [comment]
The fix is available in the latest `dev` version of the package.

**Comment by siyka-marinova** [comment]
Fix is now available in the latest `kendo-angular-layout v.4.2.2`
