### ISSUE TITLE
ng9: WindowService in lazy loaded module > LocalizationService not found

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#2755]
When trying to open a dialog from a component inside of a lazy loaded module dialog initialization fails with exception

```
ERROR NullInjectorError: R3InjectorError(LazyLoadedModuleName)[LocalizationService -> LocalizationService -> LocalizationService -> LocalizationService]: 
  NullInjectorError: No provider for LocalizationService!
```

if 

* kendoDialogContainer directive is placed in a component in AppModule (and so outside of lazy loaded module
* dialog uses a component that contains kendo-dialog-titlebar
* Angular 9 only, worked with Angular 8.

**To Reproduce**

```
AppComponent.html

<div kendoDialogContainer></div>
```   

```   
ComponentInLazyLoadedModule.ts

this.kendoDialogService.open({
   content: MyDialogComponent
});
```   
```   
MyDialogComponent.html

<kendo-dialog-titlebar>My Title</kendo-dialog-titlebar>
```   

**Expected behavior**
Dialog should open

**Browser**
 - Chrome

**Additional context**
It seems to be the kendo dialog titlebar component that throws the error because LocalizationService provided in kendo dialog component cannot be injected. It works if i apply dialog to view container ref inside of module, but that would also limit the area where users can move the dialog.

**Comment by siyka-marinova** [comment]
Fixed in the latest version of `kendo-angular-dialog`
