### ISSUE TITLE
@progress/kendo-angular-resize-sensor and @progress/kendo-recurrence no support Angular 9

### ISSUE THREAD

**Issue by pabloxn** [telerik/kendo-angular#2756]
**Describe the bug**
I am getting a warning for both @progress/kendo-angular-resize-sensor and @progress/kendo-recurrence.
`npm WARN @progress/kendo-angular-resize-sensor@3.2.0 requires a peer of @angular/common@4 - 8 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-resize-sensor@3.2.0 requires a peer of @angular/core@4 - 8 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-recurrence@1.0.0 requires a peer of @telerik/kendo-intl@^1.4.4 but none is installed. You must install peer dependencies yourself.`

The kendo-recurrence has been a warning for a while - is this no longer needed?

**Comment by Raisolution** [comment]
Hi @pabloxn,

The [kendo-angular-resize-senzor package](https://www.npmjs.com/package/@progress/kendo-angular-resize-sensor) is no longer maintained as it has been merged with the `kendo-angular-common` package.

The `kendo-recurrence` package `v1.0.0` requires a dependency of `kendo-intl@^2.0.0`.

**Comment by pabloxn** [comment]
Thanks for the information about the resize sensor.

I tried to uninstall kendo-recurrence and reinstalling it - however, I still get:

`npm WARN @progress/kendo-recurrence@1.0.0 requires a peer of @telerik/kendo-intl@^1.4.4 but none is installed. You must install peer dependencies yourself.`

any ideas how I can get rid of this message?

**Comment by Raisolution** [comment]
Hi @pabloxn ,

`kendo-recurrence@1.0.0` indeed has a peer dependency of `kendo-intl`. We dived into this, reevaluated the dependencies and published `v1.0.1`, which requires a dependency of `kendo-intl` and a peer dependency of `kendo-date-math` to be installed.

**Comment by VictorSholomickiy** [comment]
@Raisolution Hi, have the same issue, what exactly I should do to fix this warning?

**Comment by tsvetomir** [comment]
1. Remove `@progress/kendo-angular-resize-sensor` from the dependencies in `package.json`.
1. Follow the instructions in [Updating to Latest Versions](https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/#toc-updating-to-latest-versions) to update the rest of the packages to maintained versions.
