### ISSUE TITLE
[PanelBar] [Angular 9] panelbar items are not shown when using *ngFor

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2757]
When using *ngFor to create nested panelbar items, and the array contains **only one** object, the parent panelbar item does not expand its item. This behavior is observed only in **Angular 9**. The same configuration works as expected in v. 8:

https://stackblitz.com/edit/angular-sxakfx?file=app%2Fapp.component.ts

**Note**
The PanelBar works as expected in **Angular 9** if the panelbar items are bound through the [[items](https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/data-binding/#toc-binding-to-local-data)] property.

**Comment by Jahrenski** [comment]
I noticed the same behavior. Had to use this workaround in the meantime using templates.

`
<kendo-panelbar>
    <kendo-panelbar-item  [title]="region.name" *ngFor="let region of regions">
      <ng-template kendoPanelBarContent>
        <div class="item" *ngFor="let item of region.items">{{ item.name}}</div>
      </ng-template>    
    </kendo-panelbar-item>
  </kendo-panelbar>
`

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-layout`

**Comment by Raisolution** [comment]
Fix is available in `v4.2.3`
