### ISSUE TITLE
[dialog] Angular 9 dialog won't open

### ISSUE THREAD

**Issue by pabloxn** [telerik/kendo-angular#2758]
**Describe the bug**
In Angular 9 the dialog won't open. Browser shows error
`NullInjectorError: R3InjectorError(AppModule)[LocalizationService -> LocalizationService -> LocalizationService]: 
  NullInjectorError: No provider for LocalizationService!`

**To Reproduce**
```
const dialogRef: any = this.dialog.open({
          content: WordTemplateDialogComponent,
          width: 400,
        });
        if (cases) {
          this.dataSet.buildCaseDataSet(cases[0]);
        }
```

It was working fine before installing Angular 9.

https://stackblitz.com/edit/angular-8hevga

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-dialog v4.1.3`
