### ISSUE TITLE
[Editor] Error when used in <ng-content>

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2765]
**Describe the bug**
An  error is thrown when the `<kendo-editor>` is placed inside an `<ng-content>`.

**To Reproduce**
https://stackblitz.com/edit/angular-e9zdum

> NOTE: The wrapping `<div>` of `<ng-content>` has `ngIf="false"`.

**Expected behavior**
No error should be thrown

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-editor`

**Comment by Raisolution** [comment]
Fix is available in `v1.0.6`
