### ISSUE TITLE
dropdown binding problem in ngFor

### ISSUE THREAD

**Issue by behnam7171** [telerik/kendo-angular#2768]
**Describe the bug**
problem in binding when using dropdown in ngFor.
even if change the [(ngModel)]="selectedItem[i]" in the stackblitz to [(ngModel)]="item", the array will not be updated but the value of second dropdown will not change in UI.

**To Reproduce**
select first item in dropdown. the initial array will be changed but the value of second dropdown in UI will be changed but the curresponding item in selectedItem will not change.

https://stackblitz.com/edit/angular-afsdsx

**Expected behavior**
Only the first dropdown should be changed, not the second one.

**Screenshots**
https://imgur.com/4La8jPM

**Browser**
edge chromium 80

**Comment by dimitar-pechev** [comment]
The observed issue is not Kendo specific. The same behavior is reproduced with native input elements bound in the same way - [example](https://stackblitz.com/edit/angular-afsdsx-sgu8yw). Probably the references and the indices get messed up when updating the null values. 

Closing this thread as it's not a problem with the Kendo components. If you need assistance with your implementation, please [open a support ticket](https://www.telerik.com/account/support-tickets).
