### ISSUE TITLE
CldrIntlService: date check

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#277]
When using date formatting, for example in a grid column, date will only formatted when date is from type Date. As JSON doesn't know the type Date, the date is returned as string, for example like "2016-10-20T13:45:53.59+02:00". 
So it would preferable when the service tries to parse the date in some formats, like ISO/ISO-8601 format. 
I also know, parsing a date string is somewhat erroneous. What are your thoughts about that?

**Comment by ggkrustev** [comment]
@EricSch, indeed the service will format only Date instances, as this is the intended behavior.
In the case with the JSON values, it will be best if you parse the date strings into Date objects and then feed the Grid with the normalized data. This definitely will be faster than a really error-prone and time consuming 'guessing mechanism' that could be implemented in the service.

The best solution will be to just normalize the date strings, using the CldrIntlService parsing functionality, and then bind the Grid with objects that already contain Date instances.

**Comment by EricSch** [comment]
@ggkrustev Thanks for your answer.
So I will to try to intercept the data between the binding and data service call.

**Comment by ggkrustev** [comment]
@EricSch, I'll close the thread for now. If you want to comment about the case, please do so here.
