### ISSUE TITLE
[Editor] is scrolled when start typing at the bottom of a scrollable content

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2771]
When the Editor has scrollable content, typing at the bottom scrolls the Editor content. Check the screencast:
[http://somup.com/cYnZIsh04F](http://somup.com/cYnZIsh04F)

**To Reproduce**
1. Scroll to the bottom
2. Start typing
3. The Editor content is scrolled
https://stackblitz.com/edit/angular-sfhmjh-hbdabw?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-editor`

**Comment by Raisolution** [comment]
Fix is available in `v1.0.5`
