### ISSUE TITLE
[Grid] Checkbox in a sortable column triggers navigation in FireFox

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2773]
When the HeaderTemplate is used to add a checkbox in a sortable column header, clicking the checkbox triggers page navigation to /# due to the anchor tag the whole header is wrapped in:

https://stackblitz.com/edit/angular-9u4fb1-xte4dk?file=app/app.component.ts

This does not happen in Chrome and Edge. Seems related to:
https://bugzilla.mozilla.org/show_bug.cgi?id=62151

**Comment by tsvetomir** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by Raisolution** [comment]
Available in `v4.7.0`
