### ISSUE TITLE
[Drawing] Not working with es2015 builds

### ISSUE THREAD

**Issue by mortenamby** [telerik/kendo-angular#2776]
**Describe the bug**
With Angular 8 the option to do differential loading has becoome available.
When setting up differential loading as documented by Angular [here](https://angular.io/guide/deployment#differential-loading) the drawing API seems to break on es2015 builds

**To Reproduce**
As I'm not sure if you can enable differential builds on a plunkter/stackblitz I cannot create a demo.

I have encountered this bug when trying to add custom lines on a chart and when creating a custom legend visual using the visual option of a kendo-chart-legend.

When using insert() method on ChartPanes visual property (chartPane.visual.insert())
A script error occurs (see screenshot below) and the inserted group is misplaced on the chart.

![chart-render-script-error](https://user-images.githubusercontent.com/7424333/75366656-5bc73080-58bf-11ea-97e0-843bbea7682f.jpg)

On the legend it seems to render without errors but the rendered output is completely messed up compared to a standard es5 build (see screenshot below)

![legend-render-errorJPG](https://user-images.githubusercontent.com/7424333/75366659-5c5fc700-58bf-11ea-852e-30d3be0446f2.JPG)

**Expected behavior**
Drawing and rendering of custom visuals should work correctly in both es5 and es2015 builds

**Screenshots**
See above

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

**Additional context**
es2015 tsconfig.json

```
"compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "paths": {
      "@app/*": [
        "app/*"
      ],
      "@fe-shared/*": [
        "fe-shared/*"
      ]
    }
  }
```

es5 tsconfig.json

```
"compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "paths": {
      "@app/*": [
        "app/*"
      ],
      "@fe-shared/*": [
        "fe-shared/*"
      ]
    }
  }
```
**Environment**
  ```
 +-- @angular-devkit/build-angular@0.803.8
+-- @angular-devkit/build-optimizer@0.803.8
+-- @angular-redux/store@10.0.0
+-- @angular/animations@8.2.9
+-- @angular/cdk@8.1.4
+-- @angular/cli@8.3.3
+-- @angular/common@8.2.9
+-- UNMET PEER DEPENDENCY @angular/compiler@8.2.9
+-- @angular/compiler-cli@8.2.9
+-- UNMET PEER DEPENDENCY @angular/core@8.2.9
+-- @angular/flex-layout@8.0.0-beta.27
+-- @angular/forms@8.2.9
+-- @angular/http@7.1.3
+-- @angular/language-service@8.2.9
+-- UNMET PEER DEPENDENCY @angular/material@8.1.4
+-- @angular/material-moment-adapter@8.1.4
+-- UNMET PEER DEPENDENCY @angular/platform-browser@8.2.9
+-- @angular/platform-browser-dynamic@8.2.9
+-- @angular/platform-server@8.2.9
+-- @angular/pwa@0.11.3
+-- @angular/router@8.2.9
+-- @angular/service-worker@8.2.9
+-- @angularclass/hmr@2.1.3
+-- @commitlint/cli@7.2.1
+-- @commitlint/config-conventional@7.1.2
+-- @hanreev/types-ol@3.0.0
+-- @material2-extra/calendar@0.1.1
+-- @ngx-translate/core@10.0.2
+-- @ngx-translate/http-loader@3.0.1
+-- @politie/angular-testcafe-builder@2.0.2
+-- @progress/kendo-angular-charts@4.1.0
+-- @progress/kendo-angular-common@1.1.0
+-- @progress/kendo-angular-dropdowns@4.0.0
+-- @progress/kendo-angular-inputs@6.1.1
+-- @progress/kendo-angular-intl@2.0.0
+-- @progress/kendo-angular-l10n@2.0.0
+-- @progress/kendo-angular-popup@3.0.1
+-- @progress/kendo-drawing@1.5.12
+-- @progress/kendo-theme-default@4.2.0
+-- @types/elasticsearch@5.0.29
+-- @types/google.analytics@0.0.34
+-- @types/jasmine@3.3.2
+-- @types/jquery@3.3.27
+-- @types/lodash-es@4.17.3
+-- @types/node@10.12.15
+-- @types/ol@5.3.6
+-- @types/selenium-webdriver@4.0.2
+-- blue-harvest@0.3.1
+-- bower@1.8.4
+-- classlist.js@1.1.20150312
+-- codelyzer@4.5.0
+-- core-js@2.6.0
+-- gulp@4.0.2
+-- gulp-json-modify@1.0.2
+-- hammerjs@2.0.8
+-- http-server@0.11.1
+-- husky@1.2.1
+-- intl@1.2.5
+-- jasmine-bail-fast@0.0.1
+-- jasmine-core@3.3.0
+-- jasmine-reporters@2.3.2
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.4.1
+-- karma@3.1.3
+-- karma-chrome-launcher@3.1.0
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@2.0.5
+-- karma-edge-launcher@0.4.2
+-- karma-firefox-launcher@1.1.0
+-- karma-ie-launcher@1.0.0
+-- karma-jasmine@2.0.1
+-- karma-jasmine-html-reporter@1.4.2
+-- karma-spec-reporter@0.0.32
+-- karma-teamcity-reporter@1.0.1
+-- karma-verbose-reporter@0.0.6
+-- ldclient-js@2.8.0
+-- lodash-es@4.17.11
+-- moment@2.24.0
+-- ng-click-outside@2.4.1
+-- ng2-date-picker@2.11.0
+-- nodemon@1.18.9
+-- npm@6.5.0
+-- ol@6.1.1
+-- powerbi-client@2.8.0
+-- precise-commits@1.0.2
+-- prettier@1.15.3
+-- protractor@5.4.2
+-- protractor-fail-fast@3.1.0
+-- redux@4.0.1
+-- redux-devtools-extension@2.13.8
+-- replace@1.0.0
+-- rimraf@3.0.0
+-- rxjs@6.5.3
+-- stacktrace-js@2.0.0
+-- standard-version@4.4.0
+-- testcafe@1.5.0
+-- testcafe-hammerhead@14.9.2
+-- testcafe-reporter-teamcity@1.0.10
+-- testcafe-reporter-xunit@2.1.0
+-- ts-node@4.1.0
+-- tslint@5.11.0
+-- tslint-jasmine-rules@1.3.0
+-- typescript@3.5.3
+-- web-animations-js@2.3.1
+-- webpack-bundle-analyzer@3.6.0
+-- whatwg-fetch@2.0.4
`-- UNMET PEER DEPENDENCY zone.js@0.10.2

npm ERR! peer dep missing: @angular/compiler@>=2.3.1 <8.0.0 || >7.0.0-beta <8.0.0, required by codelyzer@4.5.0
npm ERR! peer dep missing: @angular/core@^7.0.0, required by @angular-redux/store@10.0.0
npm ERR! peer dep missing: @angular/core@7.1.3, required by @angular/http@7.1.3
npm ERR! peer dep missing: @angular/core@>=2.3.1 <8.0.0 || >7.0.0-beta <8.0.0, required by codelyzer@4.5.0
npm ERR! peer dep missing: @angular/material@^2.0.0-beta.5, required by @material2-extra/calendar@0.1.1
npm ERR! peer dep missing: @angular/platform-browser@7.1.3, required by @angular/http@7.1.3
npm ERR! peer dep missing: zone.js@~0.9.1, required by @angular/core@8.2.9
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.1
  ```

**Comment by tsvetomir** [comment]
I couldn't reproduce this error in my test. Can you spot any significant differences with the attached test project?

[drawing-es2015.zip](https://github.com/telerik/kendo-angular/files/4267068/drawing-es2015.zip)

**Comment by mortenamby** [comment]
@tsvetomir 
I have updated my own tsconfig with the differences from yours, but the problem persists.

I will try to replicate my code in your project to see if I can reproduce the errors

**Comment by mortenamby** [comment]
I have investigated the legend error a bit further.

In my visual method I was creating a text like this:

`new Text(args.series.name, new Point(0, 25), {
      cursor: "pointer",
      font: '14px "LFPressSans", Arial, Verdana, sans-serif',
      fill: {
        color: "rgb(101, 101, 101)"
      }
    });
`
Here it was the new Point() argument causing problems. Apparently the first letter of the legend name is not considered by the Point, how ever the remaining letters of the name was placed accoring to the Point.

I replaced the Point with an empty array like so:

`
new Text(args.series.name, [], {
      cursor: "pointer",
      font: '14px "LFPressSans", Arial, Verdana, sans-serif',
      fill: {
        color: "rgb(101, 101, 101)"
      }
    });
`
And the legend seems to be working as it should.

I still have to investgate the first error as it is more complex requiring a pane and inserting custom lines in the chart.

I will keep you posted.

**Comment by tsvetomir** [comment]
How is `Point` imported in the last example? Using a deep import instead of the package name can result in loading a different instance under the same name. This will lead to `x instanceof Point` checks failing in the Drawing library code.

The array works around this problem, but the root issue might still be unresolved.

**Comment by mortenamby** [comment]
It is imported like this:
`import { Point } from '@progress/kendo-drawing/geometry';`

**Comment by tsvetomir** [comment]
Try changing the import to the module root:

```ts
import { geometry } from '@progress/kendo-drawing';

const { Point } = geometry;
```

**Comment by mortenamby** [comment]
That seems to be working as well

**Comment by mortenamby** [comment]
I have investigated the other problem that was causing a script error.
Since I am also using the Point class to render the custom chart lines, it seems to be the same issue with a 'bad' import of the Point class.

Is it intentional that Point must be imported as you describe?

**Comment by tsvetomir** [comment]
It's more of a unwanted side effect of how module imports work in modern web apps.

Root-level imports will resolve based on the compilation target. For example `import { x } from '@progress/kendo-drawing';` could resolve to either:
* `/dist/es/index.js` (ESM5)
* `/dist/es2015/index.js` (ESM2015)
* `/dist/npm/index.js` (CommonJS)

On the other hand `import { x } from '@progress/kendo-drawing/geometry';` always resolves to `/geometry.js` which re-exports the CommonJS modules. This is fine in the context of NodeJS, but almost always the wrong thing in the context of an Angular app.
