### ISSUE TITLE
[DropDownList] setting kendoDropDownFilter option overwrites the filterable option to true

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2778]
When the filtering feature needs to be hidden initially, setting the **kendoDropDownFilter** option overwrites the filterable option to be always true.

**To Reproduce**
1. Open the dropdown
2. The filter input needs to be hidden as the **filterable** option is set to false initially

https://stackblitz.com/edit/angular-1jsknx-tkamtm?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dropdowns `

**Comment by dimitar-pechev** [comment]
Released in **v4.2.6**.
