### ISSUE TITLE
[DateInput] Subtracts 1 day when typing in leap day

### ISSUE THREAD

**Issue by bsokolslalom** [telerik/kendo-angular#2779]
**Describe the bug**
When you type the leap day into a date input like the date picker, using a format where the year is entered after the month and day, it will automatically move the date back 1 day.

**To Reproduce**
1. Go to this Stackblitz: https://stackblitz.com/edit/angular-8uyzbz
2. Type in the date 02/29/2020 (February 29, 2020)
    - This works as you enter 0229, but once you type the first 2 of 2020, it validates the date as if it's the non-leap year 0002. The date moves back a day to February 28.
    - This is not an issue if you enter the year first.
3. The date entered will be 02/28/2020 (February 28, 2020)

**Expected behavior**
The date entered will be 02/29/2020, not 02/28/2020.

**Browser**
 - OS: Mac, Windows
 - Browser: Safari / Chrome / Firefox
 - Version: 13.0.5 / 80.0.3987.122 / 72.0.2

**Comment by dimitar-pechev** [comment]
Already tracking in https://github.com/telerik/kendo-angular/issues/2008.
