### ISSUE TITLE
ngAfterViewInit on Components in TabStripTabs gets called before the View is actually initialized

### ISSUE THREAD

**Issue by Delta388** [telerik/kendo-angular#278]
In my app, I have a Tabstrip with several Tabs, each of which contains a separate Component

    <kendo-tabstrip>
      <kendo-tabstrip-tab [title]="'Information'" [selected]="true">
           <template kendoTabContent>
               <customer-info>
               </customer-info>
           </template>
       </kendo-tabstrip-tab>
       <kendo-tabstrip-tab [title]="'Comments'">
           <template kendoTabContent>
               <customer-comment>
               </customer-comment>
           </template>
       </kendo-tabstrip-tab>
    </kendo-tabstrip>

In the "customer-comment" Component, I call some resizing function in ngAfterViewInit to make the content the right size relative to the amount of space available on the screen. This worked perfectly fine before I used the Tabstrip and directly routed between the two components.

But now, when I switch the active tab from "customer-info" to "customer-comment", the Component gets loaded just fine, but ngAfterViewInit on the CustomerCommentComponent gets called before the view actually changes, so I don't have access to the sizes of the contained elements since they haven't been rendered yet.

Is this behavior intentional, and if so, is there some way to avoid it? I had been under the impression that AfterViewInit should obviously only get called after the View has been initialized.

**Comment by KirilNN** [comment]
The component itself, does not do anything specific in order to change the order of the Angular lifecycle events. Is the behavior the same with other Angular nested components? How do you do the resizing?

A runnable plunkr will really help!

**Comment by Delta388** [comment]
Tried to reproduce the issue as simply as possible

http://plnkr.co/edit/WZ16oTlHrsGA6fLUiA0g

From what I gather, what happens when I switch from TabOne to TabTwo is that the content of TabTwo gets placed below the content of TabOne, then ngAfterViewInit gets called (so the offsetTop of the div is 374 at this point, which is exactly the correct offset of 66 plus the 300 height of TabOne + 8 pixels of padding on the tabstrip Element) and only then does the content of TabOne get removed and TabTwo placed at the right spot.

**Comment by KirilNN** [comment]
@Delta388 you can try setting the `keepTabContent` option to true, this will render all the content elements and will not be recreating them. 

[Docs](http://www.telerik.com/kendo-angular-ui/components/layout/api/TabstripComponent/#toc-keeptabcontent)

Will this help?
