### ISSUE TITLE
Can't insert new row in textarea 

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2784]
**Describe the bug**
In case of navigable, in-cell editable grid new row can't be inserted in textarea

**To Reproduce**
1.Open [this sample](https://stackblitz.com/edit/angular-vq7bcv?file=app/app.component.ts).
2.Try to insert new row in first column ( it uses textarea )

**Expected behavior**
Maybe we should consider button other than ENTER, to switch on/off cell editing.

**Comment by dtopalov** [comment]
This behavior is expected as the keyevents propagate from the custom template to the Grid cell and trigger the built-in KB Navigation functionality. As developers have full control over the EditTemplate content, they can stop the keyboard events propagation in their custom code, and avoid triggering the built-in Grid behavior, e.g.:

https://stackblitz.com/edit/angular-vq7bcv-yv5r4m?file=app/app.component.ts

We will add KB or How-to example that demonstrates how to handle this scenario.

**Comment by Raisolution** [comment]
Documented as a How-To for the Grid at

https://www.telerik.com/kendo-angular-ui-develop/components/grid/how-to/insert-textarea-row/
