### ISSUE TITLE
I don't know  how to verify module and also don't know what is that module.

### ISSUE THREAD

**Issue by Nyan16** [telerik/kendo-angular#2787]
'kendo-switch' is not a known element:
1. If 'kendo-switch' is an Angular component, then verify that it is part of this module.
2. If 'kendo-switch' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </div>
    <div class="form-group">
      [ERROR ->]<kendo-switch [(ngModel)]="checked" formControlName="Inactive" onLabel="Yes" offLabel="No"></kendo-sw"): ng:///AppModule/ExtuserComponent.html@38:6

**Comment by mbechev** [comment]
Hi @Nyan16,

This is a common error when the **InputsModule** is not imported in your application root or feature module. Please check the following article from our documentation (2 point):
https://www.telerik.com/kendo-angular-ui-develop/components/inputs/#toc-manual-setup

As a side note, the repository is for bug reports only. Please next time open a support ticket for assistance.

**Comment by Nyan16** [comment]
Can't bind to 'ngModel' since it isn't a known property of 'kendo-switch'.
1. If 'kendo-switch' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'kendo-switch' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      </div>
      <div class="form-group">
        <kendo-switch [ERROR ->][(ngModel)]="checked" formControlName="Inactive" onLabel="Yes" offLabel="No"></kendo-switch>
        "): ng:///AppModule/ExtuserComponent.html@38:22
'kendo-switch' is not a known element:

Error is that. How to verify 'kendo-switch'? .
Thanks for your help. It gives me a great help. And I ask for more helps from you, please.

**Comment by Raisolution** [comment]
Hi @Nyan16,

The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
