### ISSUE TITLE
[panelbar]: missing content when clicking multiple times with expandMode=single

### ISSUE THREAD

**Issue by nodejayes** [telerik/kendo-angular#2789]
**Describe the bug**
Content Item 1.1 and Item 2.1 not shown after switch between the 2 PanelBars after 2 times

**To Reproduce**
[Stackblitz Example](https://stackblitz.com/edit/angular-yaygkv?file=app/app.component.ts)

Item 1 Title Click -> Item 1.1 Title Click
Item 2 Title Click -> Item 2.1 Title Click
Item 1 Title Click -> Item 2 Title Click -> Item 1 Title Click

**Expected behavior**
Content was shown everytime when i open the Panel Bar

**Comment by Raisolution** [comment]
Fixed in `v4.2.3`
