### ISSUE TITLE
DropDownList does not select items

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#279]
If DropDownList data is not populated from static field it doesn't work. I am trying to load items through method or services, but click on item (when popup is opened) does not add item to DropDownList.
[link](http://plnkr.co/edit/o8Xk95Zl9G7DvlO8lXKY?p=preview)
I am using Chrome Version 56.0.2924.87 (64-bit)
Code with services:
html:
```
<kendo-dropdownlist [data]="usersService.users"
                   [(ngModel)]="executors"
                   [textField]="'displayName'"
                   [valueField]="'id'"
                   [valuePrimitive]="true">
</kendo-dropdownlist>
```
code:
`constructor(private usersService: UsersService) { }`
services:
```
    get users(): LookupUser[]
    {
        return JSON.parse(localStorage.getItem("users")) as LookupUser[];  //it returns array not null!!
    }
```

**Comment by KirilNN** [comment]
The example uses a DropDownList, are you sure that the issue is MultiSelect related? If so can you please provide a plunkr with the MultiSelect issue?

**Comment by MaklaCof** [comment]
My apologise. I meant DropDownList.

**Comment by MaklaCof** [comment]
But same problem also exists on MultiSelect. Please let me know if plunkr is needed.

**Comment by KirilNN** [comment]
Yes can you please provide a plunkr for the MultiSelect as well.

**Comment by MaklaCof** [comment]
[Here it is](http://plnkr.co/edit/mpkDBc8S8uPQqOqiuYfm?p=preview).

**Comment by KirilNN** [comment]
The problem actually comes from the Angular change detection. In this case when you bind to a method, it will always return a new instance of the array, so the change detecting algorithm will not know what is changed, and therefore cancel the change. In the case with the DropDown/MultiSelect components - will not fire the click event on the element.

In your case you can change the method to always return the same instance of the array like [this](http://plnkr.co/edit/BsHiEvR0DL3GqVvQWU8k?p=preview). 

If you want to read more about it - here is the documentation article from the Angular site, where this side effect is explained:

https://angular.io/docs/ts/latest/guide/template-syntax.html#!#avoid-side-effects
