### ISSUE TITLE
i18n: new API

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2790]
Please update [your tutorial](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/#toc-initiating-the-application) about localization an application.[ i18n](https://github.com/angular/angular-cli/blob/f4bb020b94dab8bf440c7544bfb9788d92ff4b48/packages/angular_devkit/build_angular/src/utils/i18n-options.ts#L47) is now much simpler in Angular 9, which introduces this config in angular.json. In your pasted code you use some deprecated APIs: `i18nFormat`, `i18nLocale`. More information can be found [here](https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app)

**Comment by tsvetomir** [comment]
An updated version of the tutorial is available on the [development version](https://www.telerik.com/kendo-angular-ui-develop/components/globalization/localization/messages/#toc-initiating-the-application) of the site and will be published soon.

Thanks for pointing out the deprecated entries in `angular.json`, we'll remove the references to them.

**Comment by destus90** [comment]
As the tutorial has been updated I think we can close this issue. Thx for the quick response.
