### ISSUE TITLE
[Scheduler] Agenda view shows the time part incorrectly

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2792]
The **Agenda** view renders the time part of an event incorrectly. Note that the same events are displayed correclty in **Week** view.

**To Reproduce**
1. Agenda view displays (02:00:00).
1. Week view displays the time as it is.
https://stackblitz.com/edit/angular-ew89m9-n39r1x?file=app%2Fevents-utc.ts

Updated StackBlitz example: https://stackblitz.com/edit/angular-djau8d

**Comment by lenderby** [comment]
Hi, any news on when this will be fixed please? Also you said you would update my Telerik points and you haven't done.

**Comment by mbechev** [comment]
Hi @lenderby, 

Up to now, we are unable to provide a time frame as to when the issue will be fixed as there are multiple factors, that may influence the time for the release such as workload, the severity of the issue, availability of resources, etc.

Regarding the Telerik points, it seems that there was a mistake in updating them. Accept our apologies for that. Now they should be updated.

**Comment by gkarapeev** [comment]
Could be similar to https://github.com/telerik/kendo-angular/issues/3094

**Comment by dtopuzov** [comment]
Fix released with v13.5.0
