### ISSUE TITLE
[Chip] remove event should include browser event

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#2793]
Remove event just passes the ChipComponent itself. That makes it impossible to stop propagation of the underlaying click event.

**To Reproduce**

     <kendo-chip (remove)="console.log($event)"></kendo-chip>
     // logs: ChipComponent { element: … }

**Expected behavior**
As with other kendo components, I'd expect an object with an `originalEvent` property, where we have access to the click event.

**Browser**
 - Browser Chrome

**Comment by Raisolution** [comment]
Fix for this is available in the latest dev version of the `kendo-angular-buttons` package. We introduced a `ChipRemoveEvent`.

**Comment by Raisolution** [comment]
Fix is available in `v5.3.0`
