### ISSUE TITLE
While doing excel export on kendo grid, junk data included in excel file.

### ISSUE THREAD

**Issue by Monali-ITT** [telerik/kendo-angular#2796]
## I'm submitting a...
Bug report 

## Current behavior
While exporting excel file, junk data get included in downloaded file.

## Expected behavior
It should not include junk data.
It include "}"  in column.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gaj4vb-vpk7aa?file=app/app.component.ts

## Environment

Linux
Browser:
Chrome (desktop) Version 75.0.3770.142 (Official Build) (64-bit)
System:

TypeScript version: 3.5.3
Node version: v10.16.0
Platform: Linux mint

**Comment by Monali-ITT** [comment]
Please check this updated demo here:
https://stackblitz.com/edit/angular-gaj4vb-7nxci4?file=app/app.component.ts

**Comment by tsvetomir** [comment]
Thank you for the bug report. Switching to production mode seems to resolve the issue, see [updated demo](https://stackblitz.com/edit/angular-gaj4vb-l1abar?file=app/app.component.ts).

We'll investigate if this can be fixed for debug mode as well.

**Comment by Monali-ITT** [comment]
Checked the demo..Its reproduced. I downloaded file and checked,in productname its display "}" . When I double clicked on that:it display: 
bindings={
  "ng-reflect-ng-for-of": "Count,Sum,Average,Min,Max"
}

**Comment by tsvetomir** [comment]
Maybe I'm missing something, this is the exported file I get:
[Report-4.xlsx](https://github.com/telerik/kendo-angular/files/4316655/Report-4.xlsx)

**Comment by Monali-ITT** [comment]
Yes, in your file its correct.. Can you please add code here. or just create new demo and send me link.

**Comment by Monali-ITT** [comment]
You can add only changed code.

**Comment by tsvetomir** [comment]
The changes are in `main.ts` and in the component template:
```ts
import { enableProdMode } from '@angular/core';
enableProdMode();
```

(Excel Export component moved outside of *ngFor)
```html
     ...
      </kendo-grid-column>
      <kendo-grid-excel  fileName="Report.xlsx"></kendo-grid-excel>
    </kendo-grid>
```

See the updated [runnable demo](https://stackblitz.com/edit/angular-gaj4vb-l1abar?file=app%2Fapp.component.ts).

**Comment by dtopalov** [comment]
Closing this, as the functionality is working as expected in production mode.
