### ISSUE TITLE
[Grid] column width behavior is incorrect when columns are removed with reset method

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2799]
**Describe the bug**
When columns are generated dynamically with ***ngFor**, using **reset** method to remove columns except the first one, the remained column width gets the width of the removed columns. 

See the screencast demonstrating the behavior when:
- the columns are defined in the markup (works as expected)
- when they are generated dynamically
https://screencast-o-matic.com/watch/cYeX6ox3bt

**Steps to reproduce**
1. Download the project and install its dependencies
1. In the _app.component.ts_  file, both approaches are implemented
1. Click Reset button 
[grid-test-A9.zip](https://github.com/telerik/kendo-angular/files/4317501/grid-test-A9.zip)

**Note:** The issue is reproduced in Angular 8 and 9 version

**Comment by tsvetomir** [comment]
Not sure why [`QueryList.reset()`](https://angular.io/api/core/QueryList#reset) is being used here. The columns can be updated by modifying the columns collection referenced by `ngFor`.
