### ISSUE TITLE
Autocomplete list should filter by default

### ISSUE THREAD

**Issue by chriscurnow** [telerik/kendo-angular#280]
If we set "filterable" in the autocomplete component, we also have to create a listener for the "filterChange" event. We have to do this everywhere we want to use autocomplete.

Surely it would be better if autocomplete did this for us and we didn't have to write the code for it.

Autocomplete already does this for "suggest".

**Comment by tapopov** [comment]
@chriscurnow 

The AutoComplete does provide a built-in search functionality based on the `startsWith` operator as mentioned [here](http://www.telerik.com/kendo-angular-ui/components/dropdowns/autocomplete/#toc-filtering). The key difference is that the search functionality does not reduce the dataset, it only moves the focus to the matching item.
