### ISSUE TITLE
[DropDownList] using 'items' as a property name causes incorrect binding

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2801]
**Describe the bug**
Using _items_ as a property name in a complex array object tries to group the bound data because of the [groupBy ](https://www.telerik.com/kendo-angular-ui/components/dataquery/bulk-operations/#toc-grouping)method.

> public listItems = [
             { text: "Small", value: 1, **items**: [ '1', '2', '3'] },
             { text: "Medium", value: 2, **items**: [ '4', '5', '7'] },
             { text: "Large", value: 3, **items**: [ '7', '8', '9'] }
    ];
>
![2020-03-12_1656](https://user-images.githubusercontent.com/33104481/76534683-7fbf7000-6482-11ea-85cb-8cb9f2aef204.png)

**To Reproduce**
https://stackblitz.com/edit/angular-sp3vhi-uag1jv?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-dropdowns`

**Comment by dimitar-pechev** [comment]
Released in **v4.2.6**.
