### ISSUE TITLE
[Treelist] Excel export error when using [expandAll]="false"

### ISSUE THREAD

**Issue by GiampaoloGabba** [telerik/kendo-angular#2802]
When setting  `[expandAll]="false" `in the `kendo-treelist-excel` options, this error occour:

`Cannot read property 'isExpanded' of undefined`

**Steps to reproduce the behavior:**
[Stackblitz link, pointing directing to your demo...](https://stackblitz.com/edit/angular-aethm1)

**Expected behavior**
An excel file with only the collpased data

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.132

**Comment by tsvetomir** [comment]
Fixed in v0.3.0, see [updated demo](https://stackblitz.com/edit/angular-aethm1-pw7aa7?file=app/app.component.ts).
