### ISSUE TITLE
[ToolBar] Wrong keyboard navigation after overflow popup is focused

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2804]
**Describe the bug**
Clicking on the toolbar after the overflow popup button has been focused breaks keyboard navigation.

**To Reproduce**
https://stackblitz.com/edit/angular-rj91l6

1. Click on the `<input />` above the toolbar.
2. Press <kbd>TAB</kbd> to focus the toolbar.
3. Use the arrow keys to navigate to the overflow popup button.
4. Click on empty space inside the toolbar using the mouse.
5. Focus is moved to the first button of the last button group. Pressing <kbd>ARROW RIGHT</kbd> does nothing but pressing <kbd>ARROW LEFT</kbd> focuses the last button from the button group.

**Expected behavior**
Focus should remain on the overflow popup button and pressing <kbd>ARROW LEFT</kbd> should move the focus on the last button from the button group.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-toolbar`

**Comment by Raisolution** [comment]
Available in `v3.1.2`.
