### ISSUE TITLE
[Grid] Incorrect column order in column chooser list when reordering

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2810]
**Describe the bug**
Initially, when the last column is hidden, using column chooser list and then we reorder some columns ([reorderable]="_true_"), the hidden column appears as a second in the column chooser list.:
![2020-03-23_1042](https://user-images.githubusercontent.com/33104481/77298110-07af4080-6cf3-11ea-9858-e0ae7596b563.png)

Note that this behavior is not observed when we explicitly reorder a column as last:
**Screencast**
https://screencast-o-matic.com/watch/cYe0jbyFlH

**To Reproduce**
1. Hide the last column via column chooser list
1. Reorder columns
1. Open column chooser list
1. The hidden column appears on as a second

https://stackblitz.com/edit/angular-yqhoch?file=app/app.component.ts

**Comment by Fedefico** [comment]
Hi! I have the same problem, so is this confirmed as a Kendo Grid bug? Have you resolved?

**Comment by mbechev** [comment]
Hi @Fedefico,

It is a bug, but it is not included into our development tasks yet. As for now, I am unable to provide a time frame as to when the issue will be fixed as there are multiple factors, that may influence the time for the release such as workload, the severity of the issue, availability of resources, etc.

**Comment by gtona-mec** [comment]
Just a little update to point out that this bug affects also handling oReorder event. The argument passed to the handling event function holds the right column but newIndex and oldIndex properties are referred only to visible columns.

**Comment by papadi** [comment]
This has been open for more than a year. How many people need to suffer before it's addressed?

**Comment by dtopalov** [comment]
Fixed in v. 5.1.3 of the @progress/kendo-angular-grid package.
