### ISSUE TITLE
[TreeList] -> selection API

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2811]
am I missing something or there is no selection API for tree list row?

I know it is in beta but I think it is really important to add it or document it.

**Comment by tsvetomir** [comment]
The selection feature is currently in development and should be released soon. Thank you for your patience.

**Comment by tsvetomir** [comment]
Initial version of the [Selection](https://www.telerik.com/kendo-angular-ui/components/treelist/selection/) is available in v0.3.0
