### ISSUE TITLE
Angular kendo-grid-date-filter-cell localization 

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#2812]
HI,

I want to localize the kendo-grid-date-filter-cell Calender.
Provide the  Message for    Day, month, week, today, toggle Calender.

PFA. highlighted area want to localize.

![image](https://user-images.githubusercontent.com/15213587/77400255-e1f86900-6dd0-11ea-9578-3cca6326c8a8.png)

**Comment by dimitar-pechev** [comment]
Everything but the `toggle calendar` label and `today` button can be localized with the current setup. Refer to the [article on localization](https://www.telerik.com/kendo-angular-ui/components/grid/globalization/) and [this specific example](https://stackblitz.com/edit/angular-tukcrt?file=app%2Fapp.module.ts). If further help on the existing setup is required, please open a [support ticket](https://www.telerik.com/account/support-tickets).

Leaving the thread open for the label and button messages problem.

**Comment by svdeshmukh16** [comment]
Hi,
I have already used  kendo ( today, toggle) message it  was working for  normal  kendo date picker.
But it won't  work on  'kendo-grid-date-filter-cell'  kindly  provide the localize message for 'kendo-grid-date-filter-cell' 

Thank you.

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-grid`.

**Comment by dimitar-pechev** [comment]
The messages can be configured through the [CustomMessagesComponent's](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/CustomMessagesComponent/) `filterDateToggle` and `filterDateToday` properties. [Here's an example](https://stackblitz.com/edit/angular-ybuy7x).

**Comment by dtopalov** [comment]
Available in v.4.7.4
