### ISSUE TITLE
Grid -> trackBy -> detail rebuild every time

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2813]
We are using a lot of Grid and MasterDetail features, we just have a case where we use (for performance reason) `trackBy` function.

What we have found is that detail is recreated also when we have `trackBy` function present.

See simple plunker here: https://stackblitz.com/edit/angular-4fqbbu
open a row detail and see console, you will note that the detail component' s constructor is called every time data is refreshed.

I think that if `trackBy` function is used, also detail row has to respect that? am i wrong?
Any workaround in case?

**Comment by tsvetomir** [comment]
Should be fixed in the latest [development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by meriturva** [comment]
I'm really so happy! Reall really!

**Comment by Raisolution** [comment]
Available in `v4.7.2`
