### ISSUE TITLE
The server cannot receive the uploaded file collection

### ISSUE THREAD

**Issue by fengzhihenxs** [telerik/kendo-angular#2815]
Using the latest version of the upload on the angular9 project, when I upload a file, I can request the api interface of the server, but I cannot receive the uploaded file collection, but the previous lower version upload is OK, why?

Code show as below
Client:
html : 
<kendo-upload [saveUrl]="uploadSaveUrl">
    <kendo-upload-messages select="Upload">
    </kendo-upload-messages>
</kendo-upload>
ts:
uploadSaveUrl = '/api/upload';

Server:
 [HttpPost]
    public IHttpActionResult upload()
    {
      try
      {
        HttpFileCollection files = HttpContext.Current.Request.Files;
   
        }
        return Ok("success2");
      }
      catch (Exception)
      {

        return BadRequest();
      }
     
    }

**Comment by fengzhihenxs** [comment]
There are no files in the files object

**Comment by Raisolution** [comment]
Hi @fengzhihenxs 

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

**Comment by fengzhihenxs** [comment]
Has been resolved, thank you
