### ISSUE TITLE
Create a property to enable or disable mouse wheel support on numeric textbox (#881)

### ISSUE THREAD

**Issue by luizfbicalho** [telerik/kendo-angular#2816]
The feature created in #881 is very good, but in some cases it doesn't help the use of the page, só it would be nice to have the option to disable this feature.

**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**

**Comment by dtopalov** [comment]
Hello @luizfbicalho,

This repository is for bug reports only.

As seen in the bolded part of the initial post, to submit a feature request, please go to our Feedback Portal (also linked above), and add a new feature request accordingly:

https://feedback.telerik.com/kendo-angular-ui

![image](https://user-images.githubusercontent.com/7533599/77648130-53bae900-6f70-11ea-8982-d18ca44195b3.png)

Thank you in advance.
