### ISSUE TITLE
 kendo-grid-numeric-filter-cell  Localization message for  ' increment and decrement '

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#2819]
Hi,

I have already used kendo grid filter message but  "kendo-grid-numeric-filter-cell"  haven't localize.
Kindly provide the localize message for  "kendo-grid-numeric-filter-cell"  increment and decrement 

Thank you.

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-grid`.

**Comment by dimitar-pechev** [comment]
The messages can be configured through the [CustomMessagesComponent's](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/CustomMessagesComponent/) `filterNumericIncrement` and `filterNumericDecrement` properties. [Here's an example](https://stackblitz.com/edit/angular-ybuy7x-gpe9wf).

**Comment by dtopalov** [comment]
Available in v.4.7.4
