### ISSUE TITLE
Kendo-Grid data retrive one page to another page

### ISSUE THREAD

**Issue by chavda141286atul** [telerik/kendo-angular#282]
Hi,

I want Kendo-Grid data retrieve one page to another page. Its possible? main think is I have 2 page once is Customer list and second is division list while User enter data of customer and want to enter each customer division list then go to division page click on division button there I used External Form Editing Concept for Enter Multiple Division. when user back to customer details then again go to division its blank i want to fill previous data.

Thanks
Atul

**Comment by tsvetomir** [comment]
I can't determine what is the issue with the Grid based on the provided description.
In any case you should be able to set the Grid data at any moment via [data binding](http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/data-binding/).

I'm closing this for now, but feel free to reopen if you have a particular problem that is reproducible in a plunkr.
