### ISSUE TITLE
[Buttons]SplitButton/DropDownButton programmatically blurring issues

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2821]
**Describe the bug**
When a `<kenso-splitbutton>` or `<kendo-dropdownbutton>` focus is moved programmatically(not by clicking outside them), `.k-state-focused` is not removed.

**To Reproduce**
https://stackblitz.com/edit/angular-t4zygt-9x9olw
1. Click on `Start cycling focus`.
2. Observe how the focus is moved between different types of buttons.
3. `.k-state-active` is not removed from `<kendo-splitbutton>` and `<kendo-dropdownbutton>` and `(blur)` event is not emitted.

**Expected behavior**
`.k-state-focused` should be removed from `<kendo-splitbutton>`/`<kendo-dropdownbutton>` when they are not focused and `(blur)` event should be emitted when focus is moved away.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-buttons`

**Comment by Raisolution** [comment]
Available in `v5.4.2`
