### ISSUE TITLE
MMM date format doesn't handle number of month input properly

### ISSUE THREAD

**Issue by n304user11** [telerik/kendo-angular#2823]
## I'm submitting a...
* Bug report / Suggestion for improvement

## Current behavior
When kendo-datepicker is set to 'MMM-dd-yyyy' format, the initial date value is 31st of any month (ie 31st Mar 2020), and then try to manually input the month 2, 4, 6 or 9, the month will become invalid.

![image](https://user-images.githubusercontent.com/7085667/78082655-0b884480-7410-11ea-8af9-51b7ac5bcb67.png)

Here is the code I am using:
`<kendo-datepicker [format]="'MMM-dd-yyyy'" [(value)]="startDate (valueChange)="onDateChanged($event)"></kendo-datepicker>`

ValueChange doesn't detect the month is input.

PS. This is working if the datepicker format is set to 'MM-dd-yyyy'.

## Expected behavior
When kendo-datepicker format is set to 'MMM-dd-yyyy', manually input the number of month could be set correctly.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-56uuar-yk24yi?file=app/app.component.ts

## Environment

Package versions:

```
"@angular/animations": "^9.0.2",
"@angular/cdk": "^9.0.1",
"@angular/cli": "^9.0.3",
"@angular/common": "^9.0.2",
"@angular/compiler": "^9.0.2",
"@angular/compiler-cli": "^9.0.2",
"@angular/core": "^9.0.2",
"@angular/forms": "^9.0.2",
"@progress/kendo-angular-dateinputs": "^4.2.2",

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: "typescript": "3.7.5",
- Platform:  Windows

**Comment by JoomFX** [comment]
This is the expected behavior.
The DatePicker does not allow to enter a month which does not have 31 days.
[This Stackblitz example](https://stackblitz.com/edit/angular-4avyhq?file=src%2Fapp%2Fapp.component.ts) shows that all months can be manually changed via the keyboard, because all months have more than 20 days.
