### ISSUE TITLE
Angular formarray not able to show the calendar or datepicker.

### ISSUE THREAD

**Issue by Arios509** [telerik/kendo-angular#2825]
**Describe the bug**
Using the angular framework, and import all those require library inside the files. Before put into the formarray, everything is working fine. i am able to click on the calendar and show it down also able to set the default value.

But when clicked on the datepicker inside the formarray nothing shows up.

**To Reproduce**
This is my [stackblitz](https://stackblitz.com/edit/angular-zs6g4q).

**Expected behavior**
Inside the formarray able to click and show the datepicker.

**Screenshots**
![image](https://user-images.githubusercontent.com/14862187/78201722-ec97ba00-74c4-11ea-8f90-fdf9eb752406.png)

**Browser**
 - OS: [All]
 - Browser [All]
 - Version [All]

**Comment by dimitar-pechev** [comment]
Your form elements are being recreated on each change detection cycle as they are put in an *ngFor block. Notice that even the plain `textarea` from your example also loses focus every time you type something in it, as it's rerendered on every `keypress`. You can use the `trackBy` setting of the `ngFor` to avoid the undesired rerendering. [Here's an example](https://stackblitz.com/edit/angular-5vnymx).

If further assistance on the topic is required, please open a support ticket.

**Comment by Arios509** [comment]
Ok, i see. No wonder that happen like that, thanks for the input. @dimitar-pechev
