### ISSUE TITLE
Grid: cellClosed is not called when editing is canceled with ESC

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#2826]
**Describe the bug**
As stated in the grid documentation:
>cellClose EventEmitter<CellCloseEvent>
Fires when the user leaves an edited cell (see example).

But the cellClose event is not fired when editing is canceled by pressing the ESC Key

**To Reproduce**
Checkout the stackblizt Example: https://stackblitz.com/edit/angular-m2n4dr
Click in the first cell and press ESC -> cell close Event is not fired.

**Expected behavior**
Expect that the cellClose event is fired as soon as the cell editing is finished. In my case I like to cancel editing and reset the value. I need to notify my outer component that the edit action is finished, because I blocking the selection of a other cell if the edit value is invalid.
Also the keyDown event is prevented and it is not possible to write a custom behavior.

**Browser**
 - OS: [Windows]
 - Browser: Chrome
 - Version: 80.0.3987.149

**Comment by Raisolution** [comment]
The issue has been addressed in `v5.5.1` of the `kendo-angular-grid` package.
