### ISSUE TITLE
ToolBarSplitButton missing link to SplitButton

### ISSUE THREAD

**Issue by Domainv** [telerik/kendo-angular#2827]
**Describe the bug**
ToolBarSplitButton has field splitButton: ElementRef;
But it always undefined

**To Reproduce**
https://stackblitz.com/edit/angular-6kwgmx?file=src/app/app.component.ts

**Expected behavior**
splitButton fileld should leads to kendo-splitbutton component

For now as workaround used the link to get kendo-splitbutton instance:
toolbarSplitButton.toolbarTemplate['_projectedViews'][0].nodes[6].instance;

**Browser**
 - OS: MacOs
 - Browser: Chrome, Safari
 - Version @progress/kendo-angular-toolbar": "2.2.0",

**Comment by dimitar-pechev** [comment]
The `splitButton` property is for internal usage and it's not part of the [public API of the component](https://www.telerik.com/kendo-angular-ui/components/toolbar/api/ToolBarSplitButtonComponent/).

@Domainv, accessing the component's or angular's internal properties (`splitButton` and `_projectedViews`) is unrecommended. I'd encourage you to open [a support ticket](https://www.telerik.com/account/support-tickets), where you can provide more details what exactly are you trying to achieve, so we could work out a solution for your scenario.
