### ISSUE TITLE
Treeview node is expanded up when user is at the bottom of the screen

### ISSUE THREAD

**Issue by orlov11111** [telerik/kendo-angular#2828]
**Describe the bug**
Tree View node is expanded up when user is at the bottom of the screen.

**To Reproduce**

Precondition: Treeview with many nodes (https://angular-7ylot2.stackblitz.io)

1. Expand several nodes so that you can see the scroll for the screen and one more for future action
2. Scroll down
3. Collapse any node
4. Expand the node

**Actual behavior**
Treeview node is expanded up

**Expected behavior**
Treeview node is expanded down 

**Screenshots**
![TreeViewgif](https://user-images.githubusercontent.com/47855982/78424935-8e600800-7679-11ea-8c29-92377dea04ad.gif)

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.149

**Comment by dimitar-pechev** [comment]
The node is collapsed downwards, as you've reached the bottom of the page. There is no way to collapse it in the other direction, as that would mean to pull the content upwards when you've run out of content.

This is, by the way, solely handled by the browser. You can handle the `collapse` and `expand` event to adjust the scroll as you wish.
