### ISSUE TITLE
[Editor] Error when opening a dialog

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2831]
**Describe the bug**
When opening a dialog after another tool has been clicked an error is thrown:
```
Error: ExpressionChangedAfterItHasBeenCheckedError: 
Expression has changed after it was checked. 
Previous value: 'tabindex: -1'. 
Current value: 'tabindex: 0'.
```

**To Reproduce**
https://stackblitz.com/edit/angular-1tp68z?file=app/app.component.ts

1. Click on any tool in the toolbar(e.g. `Bold` button).
2. Click on any tool which opens a dialog(e.g. `Insert image`).
3. Error is thrown.

**Expected behavior**
No errors should be thrown

**Comment by souperk** [comment]
Hello, any changes on this? Any known work-arounds?

**Comment by PetarMetodiev** [comment]
Hi Kostas,

We typically abstain from giving exact timelines as we would not like to make promises we might not be able to hold. At this point I am unable to provide a time frame as to when a fix will be released as there are multiple factors, that may influence the time for the release of a fix such as work load, availability of resources etc.
Unfortunately there is no workaround with the current API.
However since the issue has a high priority, we have prioritized it over other issues related to the editor.

**Comment by dtopalov** [comment]
Fixed in the latest dev version of the **@progress/kendo-angular-toolbar package** (a dependency of the **@progress/kendo-angular-editor** package).

https://stackblitz.com/edit/angular-e2dlnf-2pxxnk?file=package.json

**Comment by dtopalov** [comment]
The fix is available in v.3.2.1 of the @progress/kendo-angular-toolbar package.
