### ISSUE TITLE
Kendo for Angular Grid column date format with variable

### ISSUE THREAD

**Issue by gtona-mec** [telerik/kendo-angular#2832]
Hi I' facing a problem trying to format a grid date column.
The problem arise if i try to set format by a variable in componet typescript.
I'm sure I'm missing something but cannot find what. 

[stackblitz example to reproduce](https://angular-s6xzee-3psfk2.stackblitz.io)

Help apricited
Thanks
Graziano

**Comment by dimitar-pechev** [comment]
@gtona-mec, the format value is invalid. Refer to [this article](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/#toc-format) in the Grid API page for general information on the topic, and to [this page](https://github.com/telerik/kendo-intl/blob/develop/docs/date-formatting/index.md) in the `intl` repo with the list of valid formats.

If further information is needed, please open a [support ticket](https://www.telerik.com/account/support-tickets). This repository is for bug reports only.
