### ISSUE TITLE
[DropDownList] changing pristine status

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2833]
**Describe the bug**
The `DropDownList` component changes the form control pristine status even though nothing has been selected.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-3ctvn1?file=src/app/app.component.ts
2. Click on the input bar and press `Esc` button or click somewhere outside the component
3. Pristine status of the form control has been changed

**Expected behavior**
Pristine status should not be changed if nothing has been selected

**Additional context**
The issue doesn't happen with `kendo-combobox` element or if the initial value is `null`

**Comment by dimitar-pechev** [comment]
This is a known issue on our side, which is yet to be resolved.

When using object data and primitive value, an unrecognized value is changed to null on blur/enter/escape. Thus the pristine state is lost. The work around for now is to add the custom value to the data set. We'll look to address the issue soon though.

Closing in favor of https://github.com/telerik/kendo-angular/issues/2514.
