### ISSUE TITLE
[Treelist] throws an error when using Pager Template in Grid 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2834]
**Describe the bug**
Importing the Treelist and Grid modules in the same feature/root module throw an error when using _Pager Template_ in Grid:

![2020-04-09_1426](https://user-images.githubusercontent.com/33104481/78891968-2478a180-7a71-11ea-8faa-79513117f40a.png)

**To Reproduce**
https://stackblitz.com/edit/angular-zbmw2b-a2rufx?file=app%2Fapp.component.ts

**Comment by tsvetomir** [comment]
Fixed in v0.3.0 build by prefixing the TreeList pager selectors, e.g. `<kendo-treelist-pager-info>`, see [Paging](https://www.telerik.com/kendo-angular-ui-develop/components/treelist/paging/).
