### ISSUE TITLE
Kendo Angular date picker  calendar months first character uppercase in es-ES

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#2835]
Hi,

I have used a  localization in my project on in es-ES language kendo calendar get localized but all months are in lower case character so here I want to first character of each month should be upper case.
i.e mar to Mar. and abr to  Abr
please find attachment.

Thank you.  
![calanderEs](https://user-images.githubusercontent.com/15213587/78960641-4a9f4f80-7b0c-11ea-8951-b328283c4f52.PNG)

**Comment by dimitar-pechev** [comment]
Month names are not capitalized in Spanish in principle.

To get help, implementing a custom scenario, please open a [support ticket](https://www.telerik.com/account/support-tickets). This repository is for bug reports only.
