### ISSUE TITLE
[Scheduler] virtualization for Timeline View

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2836]
**Describe the bug**
When there are multiple events and/or resources loaded by the Scheduler and it uses a Timeline View, then the browser may hang until the DOM is generated. Thus providing some sort of virtualization for the Timeline and Timeline Week views would be a nice enhancement feature.

**To Reproduce**
Please check the following example using ~250 resources:
https://stackblitz.com/edit/angular-vbjfuf?file=app/app.component.ts

**Comment by SimMue** [comment]
I'm experiencing the same behaviour.
Does anyone have a nice workaround for this?

I'm currently evaluating a solution, which allows pagination (example http://dojo.telerik.com/@mustafa_elhelbawy/uBigO/4).
But I'm not very happy with it.

Something better would be to support "endless scrolling", where the data is getting fetched while scrolling the page.

**Comment by yanmariomenev** [comment]
Closed in favor of the already existing feedback item: 

https://feedback.telerik.com/kendo-angular-ui/1459403-virtual-scrolling-and-paging-for-the-scheduler-resources

Feel free to cast your vote as our team constantly monitors the feedback portal.
