### ISSUE TITLE
[ContextMenu] throws an error when ngZone is disconnected from the app

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2837]
**Describe the bug**
 When the _zone.js_ import is commented and polyfills.js file and the ngZone is configured with 'NoopNgZone'

> platformBrowserDynamic()
  .bootstrapModule(AppModule, { ngZone: "**noop**" })
...

NgZone.isInAngularZone error is thrown when the component items are hovered or clicked::
https://screencast-o-matic.com/watch/cYf626agpx

![2020-04-10_1555](https://user-images.githubusercontent.com/33104481/78997345-113c0380-7b4f-11ea-9bd4-37910c4e9079.png)

**To Reproduce**
1. Right click the target
1. Hover or select an item
https://stackblitz.com/edit/angular-rdjt34?file=polyfills.ts

See a possible workaround:
[https://github.com/angular/angular/issues/23428#issuecomment-384812312](https://github.com/angular/angular/issues/23428#issuecomment-384812312)

**Comment by svetq** [comment]
No longer reproducible: https://stackblitz.com/edit/angular-kjm8kr?file=src%2Fmain.ts,src%2Fpolyfills.ts
