### ISSUE TITLE
Angular kendo date picker calendar set custom  localization

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#2839]
Hi,

Here I want to set custom week and month names in the kendo date picker calendar on the basis of language. could you please provide the solution for this.

 e.g. When  I set  language  en-EN it will  open an English custom  language calendar and  
When  I set language es-ES then it will open in custom  Spanish language calendar.

Thank you.

**Comment by dimitar-pechev** [comment]
@svdeshmukh16, this repository is set up to track the status of issues and certain planned enhancements.

As noted in #2835, the desired behavior is possible, but this is not the place to share code snippets with code customizations. Please, open a support ticket or submit your question in our public forums, where you can get suitable advice for your specific scenario.
