### ISSUE TITLE
MultiSelect - when removing items, last item (model) is not removed

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#284]
Title, [plunker](http://plnkr.co/edit/vKS0TTNk9T2kElTjtyMX?p=preview) and video should say everything.
Also when trying to remove all items ngModel is not updated correctly (items are not deleted). 

![2017-02-08_08-57-37](https://cloud.githubusercontent.com/assets/1589573/22728171/c44ab9e8-eddc-11e6-9155-e521f59e8a58.gif)

**Comment by KirilNN** [comment]
Should be fixed in the `v0.27.7` version of the package.
