### ISSUE TITLE
[Chart] Tooltip opacitiy option does not make the tooltip transparent

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2846]
**Describe the bug**
The <_kendo-chart-tooltip_> **opacity** option does not make the tooltip transparent as the ._k-popup-transparent_ class is missing in the _.k-popup_ class.

jQuery version:
https://dojo.telerik.com/aHusIGiw/3

**Screenshot**
![Screenshot (47)](https://user-images.githubusercontent.com/33104481/79334538-25a24680-7f29-11ea-9b5b-91829fc9ef03.png)

**To Reproduce**
1. Hover a chart series
https://stackblitz.com/edit/angular-qoofsz-474srg?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of kendo-angular-charts and kendo-themes.

**Comment by stnikolova** [comment]
Released in: 
 - @progress/kendo-theme-bootstrap@4.22.0
 - @progress/kendo-theme-default@4.24.0
 - @progress/kendo-theme-material@3.20.0
