### ISSUE TITLE
The 'color' property should be a string type in the Range interface used in Gauges

### ISSUE THREAD

**Issue by vbakavets** [telerik/kendo-angular#2847]
**Describe the bug**
The [documentation ](https://www.telerik.com/kendo-angular-ui/components/gauges/api/Range/) says that `color` property accepts valid CSS color strings, however, the actual type of the property is number:
![image](https://user-images.githubusercontent.com/33227044/79392249-c1f53900-7f7b-11ea-820c-9c6082c17f10.png)

**Expected behavior**
The `color` property should be `string` type instead of `number` in the Range interface used in Gauges.
Also, the type should be fixed in the documentation.

**Comment by mbechev** [comment]
Here is an example where the **color** property throws an error when a string is passed:
https://stackblitz.com/edit/angular-8xj57v?file=app/app.component.ts

**Comment by stnikolova** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released in **v3.0.3.**
