### ISSUE TITLE
DropDownButton accessibility error

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#2848]
**Describe the bug**
DropDownButton has an typo in role="menuItem" , which causes accessibility error being thrown

**To Reproduce**
Open https://stackblitz.com/edit/angular-xuezkg?file=app/app.component.ts
Inspect expanded popup of an DropDownButton

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/4143177/79420198-1d95e580-7fc1-11ea-8213-b78d3a8d9524.png)

**Browser**
- Not related

**Broken in **
```
@progress/kendo-angular-buttons@v5.4.1
```

**Comment by ipeshev** [comment]
https://github.com/telerik/kendo-angular-buttons/blob/f4e4b374448c8afa7b5cf35066b29a80dc8f76d0/test/list.test.ts#L275

**Comment by preslavapetrova1** [comment]
The fix is now available in the latest official version `kendo-angular-buttons v5.4.3`
