### ISSUE TITLE
[Inputs] Controls not marked as touched with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2849]
Components from the Inputs package like NumericTextBox and MaskedTextBox are not marked as touched when blurred, and the ChangeDetectionStrategy is set to "OnPush":

https://stackblitz.com/edit/angular-jsxudh-q57znv?file=app/app.component.ts

The components touched status should be updated appropriately like when regular HTML Input elements are used.

The existing workaround is to call the[ ChangeDetectorRef markforcheck](https://angular.io/api/core/ChangeDetectorRef#markForCheck) method in the blur event handler of the component:

https://stackblitz.com/edit/angular-jsxudh-aexvdt?file=app/app.component.ts

**Comment by PieterVanPoyer** [comment]
Hi

I think the DatePicker and maybe other components have the same (incorrect) behaviour.
You should check all your editors.

Kind regards
Pieter

**Comment by dtopalov** [comment]
Seems related to

https://github.com/angular/angular/issues/10887#issuecomment-357460303

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-dateinputs 4.3.0`, `kendo-angular-inputs 6.6.0`

**Comment by PieterVanPoyer** [comment]
Seems to work now. Thanks for the effort.

Kind regards
Pieter
