### ISSUE TITLE
Grid without Header (main k-grid-header div element)

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#285]
We would like to have a kendo grid without any header.

One solution is to customize every column header and set it invisible but we still have elements on dom.

I think best for performance is to don't have unused dom elements so i guess solution is to add a special input to enable or disable div element `k-grid-header` at all for grid without any header.

What do you think?

**Comment by rusev** [comment]
To be honest I don't see much value in Grid without header. Hiding the header element is valid approach in this case.

**Comment by meriturva** [comment]
It is a case when for example you want to align multiple Grids vertically but just the first has header. With flexibility about callback and sort capability implemented in `process` helper could be really cool to not have header. is it just my case?

**Comment by DydFreeman** [comment]
+1

**Comment by petejordan** [comment]
-- Angular 4 - Angular 4 - Angular 4 - Angular 4 - Angular 4 - Angular 4 - Angular 4 - Angular 4 --

Likewise need headless grid for the exact same reasons.
Will have total of 9 grids stacked and aligned on form NOT related functionally 
but providing related business information.

Currently have 2 grids in place with multiple rows.
Grids 3-9 will be a single row - almost as footers but req'ment is that they look like
panels on a background to match overall style of app.
There are 47 columns across the grid (yes this project is migrating Excel buiness
processes to web) and the only sane way to report all this information is within a
grid, but for compactness, grids with no header, no footer.

I'm sure the Telerik / Progress / Kendo team can come through once again with a 
great solution.

Thx,

**Comment by tsvetomir** [comment]
After a _slight_ delay, the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the Grid ship with a new [hideHeader](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/GridComponent/#toc-hideheader) setting.

**Comment by tsvetomir** [comment]
Available in `@progress/kendo-angular-grid` v3.6.0, see [docs](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-hideheader).
