### ISSUE TITLE
kendo-numerictextbox with spinner problem on Edge Browser

### ISSUE THREAD

**Issue by zulfu** [telerik/kendo-angular#2853]
**Describe the bug**
When kendo-numerictextbox with spinner is less than 200 px, spinners move out.

**To Reproduce**
https://mnxtkm.run.stackblitz.io in this stackblitz you can easily reproduce with changing the element width less than 200px on Edge Browser

**Expected behavior**
Spinner must stay inside the element

**Screenshots**
![kendo-numerictextbox](https://user-images.githubusercontent.com/4500888/79643542-17b02800-81ac-11ea-8e39-5b38e86cb6bb.gif)

**Browser**
 - OS: Windows 10, 1909
 - Browser Microsoft Edge 
 - Version 42.17134.1098.0

**Comment by dtopalov** [comment]
The NumericTextBox has a default width of 200px. To customize it, provide the desired width via CSS:

https://www.telerik.com/kendo-angular-ui/components/inputs/styling/
