### ISSUE TITLE
[Grid] - Links in grid content are not styled 

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#2854]
**Describe the bug**
When there are links inside a grid cell, the links are not styled so it is difficult to distinguish where the link is.

**To Reproduce**
https://stackblitz.com/edit/angular-xyhpo1?file=app/app.component.ts

**Expected behavior**
The default colors for links should not be changed

**Browsers**
Firefox

**Additional context**
I could use styles to set those but doing that will not allow firefox users to set custom link colors.

**Comment by inikolova** [comment]
This problem is related to the Grid styling. As the same issue is logged in the kendo-themes repo, I am closing the current item - you could track its progress here: 
https://github.com/telerik/kendo-themes/issues/1481
