### ISSUE TITLE
[Grid] - Group dates without time part

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#2856]
Currently when data is grouped by date fields, the entire date and time is used.
[example](https://stackblitz.com/edit/angular-nt6f15?file=app%2Fapp.component.ts)

![image](https://user-images.githubusercontent.com/12758783/79823117-a7bfbe80-83b2-11ea-8e63-e389c9726460.png)

In the image above, all 3 items are ordered on the same day but when grouped, the items are shown in different groups.

My current workaround is adding another field that contains just the date part but having to do that again and again for lots of grids feels error prone.

**Comment by mbechev** [comment]
Hi @vivek201,

This behavior is expected when the passed dates are not valid [JavaScript Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) objects. In the example above the passed dates are from type string. Map the data as the following article demonstrates:
https://www.telerik.com/kendo-angular-ui/components/grid/troubleshooting/

Here is an example:
https://stackblitz.com/edit/angular-nt6f15-v7s1wp?file=app/products.ts

**Comment by vivek201** [comment]
@mbechev 
Hi, I converted those string dates to Javascript Dates as follows:
```javascript
this.products = products.map((x: any) => {
          x.OrderedDate = new Date(x.OrderedOn);
          return x;
});
```
But doing that still groups the dates by using the Time part. [(updated code)](https://stackblitz.com/edit/angular-nt6f15?file=app%2Fapp.component.ts)

![image](https://user-images.githubusercontent.com/12758783/80228758-2a74a200-866f-11ea-8323-49a7aac287ca.png)

What I want to achieve is have the grouping done just by dates but display the full dates. This [code](https://stackblitz.com/edit/angular-nt6f15-knrkwc?file=app/app.component.ts) works for static data but this won't work with server-side sorting.

![image](https://user-images.githubusercontent.com/12758783/80229469-3319a800-8670-11ea-930f-dca675ab61a2.png)

**Comment by mbechev** [comment]
Hi @vivek201,

The repository is for bug reports only. Please [open a support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
