### ISSUE TITLE
File Selector displays apostrophes wrong

### ISSUE THREAD

**Issue by kotva006** [telerik/kendo-angular#2858]
**Describe the bug**
When a file containing an apostrophe in the name is uploaded the apostrophe is replaced with the code #&39;
This happens in both the file select and file upload component.

**To Reproduce**
https://stackblitz.com/edit/angular-3zq6tb

Select a file with an apostrophe in its name and notice the apostrophe gets replaced in the name.

**Expected behavior**
I expect the file name to contain the apostrophe.

**Screenshots**
![image](https://user-images.githubusercontent.com/2679229/79880043-1a319e00-83b5-11ea-83c9-d4cf073942fa.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome, Edge

**Comment by Raisolution** [comment]
Fix for this issue is available in `v6.0.2` of the Upload package.
