### ISSUE TITLE
[Scheduler] displaying recurrence exceptions for the series when editing occurrence

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2860]
**Describe the bug**
The single occurrences display recurrence exceptions for the series when editing a single occurrence.

**To Reproduce**
Please check the following example:

https://stackblitz.com/edit/angular-niog8n-zmhbw8?file=app%2Fapp.component.ts

1. Doubleclick any event item, select "Edit current occurrence" option.
    When editor open - check that no Recurrence Exceptions listed.
    Save event.

2. Open another item of the recurrent event, select "Edit current occurrence" option.

Current behavior: Recurrence Exception is listed for occurrence,  which means that 
   createFormGroup method is called with CreateFormGroupArgs having 
   dataItem.recurrenceExceptions same as in series.

Expected behavior: when editor opened for editing of not series but occurrence,
createFormGroup method is called with CreateFormGroupArgs having dataItem.recurrenceExceptions empty.

**Comment by gkarapeev** [comment]
After some discussion with team members, our conclusion is that the behaviour is expected.

When editing an occurrence, before it is _**actually saved as an exception**_, we are technically still interacting with the series, so having access to the series makes sense. Although you do have access to the exceptions when editing an occurrence, you are free not to use them.

At the end, when you confirm creating the exception, opening it no longer displays any exceptions, as that would be confusing.

@svetq @tsvetomir I'm closing the issue with this comment as everything seems like it is working okay.

**Comment by tsvetomir** [comment]
On a second look, the problem seems valid. The edit dialog should not receive the exceptions list in this case, even though they typically don't have an effect.

To account for this, we can modify the `createFormGroup` method:
```ts
public createFormGroup(args: CreateFormGroupArgs): FormGroup {
    const dataItem = args.dataItem;
    const isOccurrence = (<any> args).mode === EditMode.Occurrence;
    const exceptions = isOccurrence ? [] : dataItem.recurrenceExceptions;

    this.formGroup = this.formBuilder.group({
        'id': args.isNew ? this.getNextId() : dataItem.id,
        'start': [dataItem.start, Validators.required],
        'end': [dataItem.end, Validators.required],
        'startTimezone': [dataItem.startTimezone],
        'endTimezone': [dataItem.endTimezone],
        'isAllDay': dataItem.isAllDay,
        'title': dataItem.title,
        'description': dataItem.description,
        'recurrenceRule': dataItem.recurrenceRule,
        'recurrenceId': dataItem.recurrenceId,
        'recurrenceExceptions': exceptions
    });
    return this.formGroup;
}
```

See [live demo](https://stackblitz.com/edit/angular-niog8n-zmhbw8?file=app%2Fapp.component.ts).

Note that `CreateFormGroupArgs` already contains a `mode` field of type [EditMode](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/EditMode/). This is all we need to make the decision whether to expose the exceptions to the form.

The bad news is that this field is not public. I'm reopening the issue, as this is something that we need to fix.
The documentation should also be updated with the new `createFormGroup` method.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by tsvetomir** [comment]
The `mode` field was originally added to [CreateFormGroupArgs](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/CreateFormGroupArgs/) in v1.2.4
The [help topic](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-directives/) is updated with the recommendations above.
