### ISSUE TITLE
[Grid] ExcelExportEvent is not exported from the index

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2862]
When we want to customize generated workbooks there is no export statement for the ExcelExportEvent interface in the index file. This may be useful for TypeScript hintings. We can import that interface from `@progress/kendo-angular-grid/dist/es2015/excel/excel-export-event` what is a bit ugly.

**Expected behavior:**
The ExcelExportEvent interface can be imported from `@progress/kendo-angular-grid`.
https://stackblitz.com/edit/angular-12ars3?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-grid`

**Comment by dtopalov** [comment]
The fix is also available in the official 4.7.2 version.
