### ISSUE TITLE
[SplitButton] Stealing focus when closing popup

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2868]
**Describe the bug**
When the popup is closed with click outside the component, the button inside the splitbutton is focused.

**To Reproduce**
https://stackblitz.com/edit/angular-cehsof-hbvijr?file=app/app.component.ts

1. Open User Settings splitbutton.
2. Click outside the splitbutton.
3. Focus is set on the button inside the splitbutton.

**Expected behavior**
Focus should not be set on the button inside the splitbutton.

**Comment by siyka-marinova** [comment]
Fix for this issue is available in the [latest dev. version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/#toc-obtaining-development-builds) of `kendo-angular-buttons`

**Comment by Raisolution** [comment]
Available in `v5.4.2`
