### ISSUE TITLE
Grid keep selection in memory after item is deleted

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#287]
I have created a plunker to replicate issue: http://plnkr.co/edit/70WBJeQwt4IMMGPOnDG1?p=preview

Basically when you select an element and then delete all selection still in memory.
So when i add new elements i have already one selected.

I think selection has to be reset when item selected is deleted.
My two cents!

**Comment by rusev** [comment]
Indeed this is the case with current implementation. Selection feature is in process of development. We will have this report in mind.

If you may have any other suggestions/comments we will be more than happy to see them posted in [this issue](https://github.com/telerik/kendo-angular/issues/213).

**Comment by meriturva** [comment]
Perfect @rusev .

So thanks!
