### ISSUE TITLE
[TreeList]: selectionChange emits also when row is already selected 

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2874]
**Describe the bug**
SelectionChange output has to emit only when selection is changed.

**To Reproduce**
Just see grid example with selection api:
https://stackblitz.com/edit/angular-mw7gab?file=app/app.component.ts

And same example with new treeList:
https://stackblitz.com/edit/angular-k9xlvy?file=app/app.component.ts

To reproduce click multiple time to same row and see console.

**Comment by tsvetomir** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), see [demo](https://stackblitz.com/edit/angular-k9xlvy-cc9z41?file=app/app.component.ts).
