### ISSUE TITLE
What is change detection strategy of all kendo angular components ? 

### ISSUE THREAD

**Issue by balasherkar** [telerik/kendo-angular#2876]
Use this template for questions that are relevant to the community as a whole.

**If the issue is specific to your project, please open a [support ticket](https://www.telerik.com/account/support-tickets).**

**Comment by mbechev** [comment]
The Angular Change detection strategy can be set in the component metadata, through the [changeDetection ](https://angular.io/api/core/Component#options)option:
```ts
import { Component,ChangeDetectionStrategy} from '@angular/core';

@Component({
  selector: 'app-child',
  templateUrl: './test.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TestComponent {}
```
If its not set, the component will use the automatic change detection ([Default](https://angular.io/api/core/ChangeDetectionStrategy) value). The developer decide from which strategy would like to benefit from in the component, depend on the project requirements.

**Comment by tsvetomir** [comment]
To add to this answer, most components use the default change detection strategy. This is done mostly for convenience, as any changes to the data and settings will be reflected automatically.

Some notable exceptions that use `OnPush` are the Charts, Date Inputs, Scheduler and TreeList. Some internal components also use this setting, primarily for performance reasons.

As usual, it's best to consult the [source code](https://www.telerik.com/kendo-angular-ui/components/installation/source-code/) as the single source of truth.

**Comment by shultiaiev-tp** [comment]
To be honest, this does not look like a convenience to me. Things break in the apps that use `OnPush`, because the library cannot reflect changes when they originate from "inside", e.g. form state change, service call etc.
