### ISSUE TITLE
[ToolBar] [tabindex] does not set tabindex attribute on toolbar-button

### ISSUE THREAD

**Issue by myushchenko** [telerik/kendo-angular#2879]
**Describe the bug**
When try to set
` 
<kendo-toolbar>
     <kendo-toolbar-button [tabindex]="0" [text]="'Button'"></kendo-toolbar-button>
 </kendo-toolbar>
`
after inspect it shows tabindex="-1"

**To Reproduce**
https://stackblitz.com/edit/angular-kendo-toolbar-button-tabindex

1. Right click on the toolbar  button and click inspect.
2. The inspected button does not have a tabindex attribute set.

**Expected behavior**
**tabindex** should be set.

**Browser**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [81]

**Additional notes**
As I understand it works according to the logic of the [roving tabindex](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#kbd_roving_tabindex). But would be good to have ability to set tabindex.

**Comment by PetarMetodiev** [comment]
Hi Mykhailo,

Could you please some details on a possible use case scenario of such a feature?

**Comment by myushchenko** [comment]
Hi,
It's provide ability to implement Tab navigation on toolbar buttons as in JQuery Kendo UI (https://demos.telerik.com/kendo-ui/toolbar/index).

**Comment by PetarMetodiev** [comment]
Thanks for the clarification.

Indeed currently keyboard navigation follows the roving tabindex rules. If we were to allow setting a tabindex to a toolbar tool, this would mean that we have to turn off the current navigation logic and just rely on tabing for navigation.

I have to admit that we have not yet considered the described way of navigation. If having such behaviour is important for you please submit a [feature request](https://feedback.telerik.com/kendo-angular-ui) so we can track it. We keep a close eye on our feedback portal as it is one of our main ways of keeping up with user demand.
