### ISSUE TITLE
[TreeView] allow providing a trackBy function for the nodes

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#2881]
Currently the TreeView doesn't support passing a user-defined `trackBy` function for the nodes. If the component is used with remote data and the user wants to fetch the expanded nodes data anew from the server, the nested groups will be destroyed, removed from the DOM, and re-rendered once the new data arrives. If would be a nice enhancement if the user could pass his own `trackBy` function so that unchanged groups will remain visually untouched.

The undesired behavior can be observed [here](https://stackblitz.com/edit/angular-ttjbcn-qegarw). Tracking the nodes by data item ID would solve the issue.

Currently the problem can be worked-around by fetching the entire data collection at once, if that's an option for the specific scenario, and only then rebinding the TreeView.

**Comment by IvoDfs** [comment]
Can you please provide an update on the status of this request?

**Comment by dimitar-pechev** [comment]
@IvoDfs, the enhancement has been included in **v4.3.0** of the `@progress/kendo-angular-treeview` package. We haven't notified about it yet, as there are still some pending tests. You can of course give it a try already.

[Here's a ref](https://www.telerik.com/kendo-angular-ui/components/treeview/api/TreeViewComponent/#toc-trackby) to the description of the exposed `trackBy` input prop. We've also exposed a [`rebindChildren`](https://www.telerik.com/kendo-angular-ui/components/treeview/api/TreeViewComponent/#toc-rebindchildren) method. It forces all children to be rebound again (the children callback is called anew for each expanded node).

[Here's also the initial example](https://stackblitz.com/edit/angular-ttjbcn-n4ldnr), updated to use the `trackBy` and `rebindChildren`.
