### ISSUE TITLE
Can't bind to 'disabledDates' since it isn't a known property of 'kendo-datepicker'.

### ISSUE THREAD

**Issue by dnyaneshwar-surywanshi** [telerik/kendo-angular#2884]
**Describe the bug**
While using disabledDates property to kendo-datepicker in angular 7 it's throwing the error.

**To Reproduce**
https://tnwqxb.run.stackblitz.io

  1. Find an example in [the documentation](http://www.telerik.com/kendo-angular-ui/components/) that looks similar to your case.
  2. Open it in StackBlitz by using the **OPEN IN STACKBLITZ** button.
  3. Modify the snippet so that the issue is reproducible in it. Try to include the minimum amount of code possible.
  4. Save the snippet by using the blue **FORK** button at the top.
  5. Copy the link from the address bar of the browser.
-->

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome,]
 - Version [for example, 22]

**Additional context**

**Comment by dimitar-pechev** [comment]
The described error is usually thrown when either the **DateInputs** module is not imported, or when using a package version prior to the one where the specified feature has been introduced. Make sure the module is imported and upgrade to the last `@progress/kendo-angular-dateinputs` package.

As this is a configuration issue, I'm closing the thread. If further assistance is required, open a support ticket. This repository is for bug reports only.

**Comment by dnyaneshwar-surywanshi** [comment]
@dimitar-pechev  Thanks for the response 
in my module.ts i have import the dateinputmodule 

import { DateInputsModule} from '@progress/kendo-angular-dateinputs';


@NgModule({
  imports: [CommonModule, FormsModule, ManagePayrollDocumentRoutingModule, ReactiveFormsModule, SharedModule, DateInputsModule],

And my package.json 
"@progress/kendo-angular-dateinputs": "^3.7.1",

also i have ran the npm install @progress/kendo-angular-dateinputs  

in my html .
 <kendo-datepicker
              [disabledDates]="disabledDates"
              class="distribution-date-picker"
              id="distributionOn"
              formControlName="test"
              placeholder=""
              (valueChange)="distributionDateChange($event)"
              required
            >
            </kendo-datepicker>
  but still facing below error 
ERROR in : Can't bind to 'disabledDates' since it isn't a known property of 'kendo-datepicker'.
1. If 'kendo-datepicker' is an Angular component and it has 'disabledDates' input, then verify that it is part of this module.
2. If 'kendo-datepicker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            >Distribution Date *
            <kendo-datepicker
              [ERROR ->][disabledDates]="disabledDates"
              class="distribution-date-picker"
              id="di")

**Comment by dj-milenkovic** [comment]
> @dimitar-pechev Thanks for the response in my module.ts i have import the dateinputmodule
> 
> import { DateInputsModule} from '@progress/kendo-angular-dateinputs';
> 
> @NgModule({ imports: [CommonModule, FormsModule, ManagePayrollDocumentRoutingModule, ReactiveFormsModule, SharedModule, DateInputsModule],
> 
> And my package.json "@progress/kendo-angular-dateinputs": "^3.7.1",
> 
> also i have ran the npm install @progress/kendo-angular-dateinputs
> 
> in my html . <kendo-datepicker [disabledDates]="disabledDates" class="distribution-date-picker" id="distributionOn" formControlName="test" placeholder="" (valueChange)="distributionDateChange($event)" required > but still facing below error ERROR in : Can't bind to 'disabledDates' since it isn't a known property of 'kendo-datepicker'.
> 
> 1. If 'kendo-datepicker' is an Angular component and it has 'disabledDates' input, then verify that it is part of this module.
> 2. If 'kendo-datepicker' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
>    >Distribution Date *
>    <kendo-datepicker
>    [ERROR ->][disabledDates]="disabledDates"
>    class="distribution-date-picker"
>    id="di")

Have you resolved it?
