### ISSUE TITLE
[Scheduler] Tooltip isn't localized correctly

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#2885]
**Describe the bug**
The tooltip of an event (eventTitle) isn't localized correctly. The date part is still in English.
All other dates are translated correctly.
Seems the call to 'formatDate' in the function 'formatEventTime' doesn't pickup the correct local id.

**To Reproduce**
https://angular-hmy9vb.stackblitz.io

**Expected behavior**
The date part should be in German.

**Screenshots**
![image](https://user-images.githubusercontent.com/25437/81586045-4a1d0180-93b5-11ea-8d79-6e4c0b0f1f47.png)

**Browser**
 - OS: Windows
 - Browser: Chrome

**Comment by EricSch** [comment]
Possible to get an answer or feedback?

**Comment by dtopalov** [comment]
Hi @EricSch,

Thank you for bringing this issue to our attention. This is indeed an omission in our code - the current locale is not passed when formatting the date.

We will do our best to provide a fix as soon as possible.

This thread will be updated accordingly once a fix is released.

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-scheduler`.

**Comment by siyka-marinova** [comment]
The fix is now available in the latest official version `kendo-angular-scheduler v.1.2.0`
