### ISSUE TITLE
Tooltip style does not applied to dropdownbutton

### ISSUE THREAD

**Issue by yoyoyang123** [telerik/kendo-angular#2886]
Here is a demo I created for tooltip in dropdownbutton. 
[demo](https://stackblitz.com/edit/angular-test-dropdownbutton-tooltip-eqin-h1yvuc)

For the button tooltip, style works fine, but for the drop down items, the style does not work.

**Comment by PetarMetodiev** [comment]
Hi @yoyoyang123,

The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations, or submit a new feature request in our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui) for any desired new enhancements.
