### ISSUE TITLE
[Grid] column menu closes unexpectedly 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2888]
**Describe the bug**
When selecting a text within the column menu filter and the mouse click is released outside the column menu, then the column menu is closed.

**To Reproduce**
Please check the following video demonstrating that undesired behavior:
https://screencast-o-matic.com/watch/cYhl1QgJgu

**Comment by lexon0011** [comment]
Any updates for this issue?

**Comment by dtopalov** [comment]
The described behavior is related to browser-specific discrepancy in Chrome and FireFox, and their treatment of the `mouseup` and `click` events, and their respective targets.

Thus releasing the mouse button outside of the ColumnMenu in Chrome is treated as clicking outside of the menu, and closes the Popup, while in FireFox the ColumnMenu remains open.

We are closing this issue, as the behavior is browser-specific, and not directly related to the Grid ColumnMenu component.

**Comment by lexon0011** [comment]
It is NOT a browser specific behavior, because with the jQuery-grid it works as expected (also with Chrome). As changing to the angular-grid, the behavior changed!

**Comment by bberto** [comment]
Any update on this issue? It's very annoying...
