### ISSUE TITLE
'kendo-grid-command-column' is not a known element Angular 2 Kendo Grid Command Column Edit 

### ISSUE THREAD

**Issue by askaliate** [telerik/kendo-angular#289]
I am try to use the angular 2 grid command column edit (reactive forms) and I keep getting the following error message. 

All works as expected for kendo-grid-column but NOT for 'kendo-grid-command-column'

http://www.telerik.com/kendo-angular-ui/components/grid/editing/

Here are my packages:

"@progress/kendo-angular-buttons": "0.14.0",

"@progress/kendo-angular-dialog": "0.14.1",

"@progress/kendo-angular-dropdowns": "0.24.4",

"@progress/kendo-angular-intl": "0.9.0",

"@progress/kendo-angular-grid": "0.7.0",

"@progress/kendo-angular-popup": "0.15.0",

"@progress/kendo-angular-upload": "0.12.0",

"@progress/kendo-data-query": "0.2.0",

"@progress/kendo-popup-common": "0.3.0",

"@progress/kendo-angular-inputs": "0.18.2",

"@progress/kendo-theme-default": "2.11.4",

"@telerik/kendo-dropdowns-common": "0.2.0",

"@telerik/kendo-intl": "0.12.0",

"@telerik/kendo-theme-default": "1.32.0",

"@telerik/kendo-draggable": "1.5.1",

"@telerik/kendo-inputs-common": "2.1.0"

Here is the error:

Template parse errors:
'kendo-grid-command-column' is not a known element:
Unhandled Promise rejection: Template parse errors:
'kendo-grid-command-column' is not a known element:
1. If 'kendo-grid-command-column' is an Angular component, then verify that it is part of this module.
2. If 'kendo-grid-command-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. (">
        <kendo-grid-column title="Description" field="Description"></kendo-grid-column>
        [ERROR ->]<kendo-grid-command-column title="command" width="220">
            <template let-isNew="isNew">
  "): PlatformComponent@12:8 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
'kendo-grid-command-column' is not a known element:
1. If 'kendo-grid-command-column' is an Angular component, then verify that it is part of this module.
2. If 'kendo-grid-command-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. (">
        <kendo-grid-column t
Error: Uncaught (in promise): Error: Template parse errors:
'kendo-grid-command-column' is not a known element:
1. If 'kendo-grid-command-column' is an Angular component, then verify that it is part of this module.
2. If 'kendo-grid-command-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. (">
        <kendo-grid-column title="Description" field="Description"></kendo-grid-column>
        [ERROR ->]<kendo-grid-command-column title="command" width="220">
            <template let-isNew="isNew">
  "): PlatformComponent@12:8
Error: Template parse errors:
'kendo-grid-command-column' is not a known element:
1. If 'kendo-grid-command-column' is an Angular component, then verify that it is part of this module.
2. If 'kendo-grid-command-column' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. (">
        <kendo-grid-column title="Description" field="Description

**Comment by rusev** [comment]
I'm closing this one i favor to this thread - https://github.com/telerik/kendo-angular/issues/245.
