### ISSUE TITLE
[Scheduler] the end time of a multiday event is disregarded

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2890]
**Describe the bug**
The end time of an event that last for more than one day is set to midnight disregarding the actual end time.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-eqgyiy-rhthgx?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-scheduler`.

**Comment by lexon0011** [comment]
Thanks! I try it and can confirm that the bug is fixed in this dev version. When will the next official version of the scheduler be released?

**Comment by tsvetomir** [comment]
Published as v1.1.6
