### ISSUE TITLE
[Editor] Append forward slash on self closing tags

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2891]
**Describe the bug**
When the value of the `<kendo-editor>` contains `<link />` or `<meta />`, the slashes are removed from the DOM.

**To Reproduce**
https://stackblitz.com/edit/angular-tjobuq?file=app/app.component.ts
1. Inspect the contents of the `<kendo-editor>`.
2. Slashes(`/`) are removed

**Expected behavior**
Slashed should not be removed.

**Comment by dtopalov** [comment]
The behavior is standard for the ProseMirror library the Editor is based on.

The suggested workaround is to get the Editor value, and process it as necessary (for example add a forward slash '/' before the closing angle brackets in self-closing tags through a regex).
