### ISSUE TITLE
[MultiSelect] clicking the clear all X icon blurs the component

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2893]
**Describe the bug**
When clicking the X icon to clear all selected items then the blur event of the MutliSelect is triggered.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-17ekd5?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-dropdowns v4.3.0`
