### ISSUE TITLE
MultiSelect NgModel two-way binding not working correctly

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#290]
**Reproduce Steps**
1) Initialise variable 'selected' with item 'Baseball'
2) On valueChange set 'selected' = []  //(empty)

**Expected**
Clear all values selected
**Actual**
Value are still selected.

[Plunker link](http://plnkr.co/edit/J17tpj5g7PJ1vjDGiJtY?p=info)

**Possible use case for this issue**
Custom 'Select All' Function.
[Plunker link](http://plnkr.co/edit/DUp187P3wHeIzYsZUXQ2?p=preview)

**Comment by KirilNN** [comment]
Hi @skyfremen,

This behavior is expected, as you are mixing the concepts here. If you use `[value]` binding then you can handle the `valueChange`event and clear the selection. If you want to use `ngModel` then the `ngModelChange` event should be used.
