### ISSUE TITLE
Angular 9 install @progress/kendo-angular-treelist@1.0.0 wrong dependencies

### ISSUE THREAD

**Issue by alexfangmann** [telerik/kendo-angular#2901]
The installation in Angular 9 for the treelist has errors. 

**npm install @progress/kendo-angular-treelist@1.0.0**

**Angular: 9.1.7**

**npm Error:** 

> npm WARN @progress/kendo-angular-treelist@1.0.0 requires a peer of @angular/animations@6 - 8 but none is installed. You
> must install peer dependencies yourself.
> npm WARN @progress/kendo-angular-treelist@1.0.0 requires a peer of @angular/common@6 - 8 but none is installed. You must install peer dependencies yourself.
> npm WARN @progress/kendo-angular-treelist@1.0.0 requires a peer of @angular/core@6 - 8 but none is installed. You must install peer dependencies yourself.
> npm WARN @progress/kendo-angular-treelist@1.0.0 requires a peer of @angular/forms@6 - 8 but none is installed. You must
> install peer dependencies yourself.

**Comment by tsvetomir** [comment]
Missed that one, thanks! Fixed in v1.0.1
