### ISSUE TITLE
[TreeList] updating the expandedKeys collection doesn't re-render the TreeList

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2902]
**Describe the bug**
When passing a new array to the expandedKeys property of the ExpandableDirective the TreeList should be re-rendered to show the expanded nodes as per the array provided in the expandedKeys. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-k8b2vl-n4q6xu?file=app/app.component.ts

the issue is the same if using flat data or hierarchical data

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by tsvetomir** [comment]
Fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fix released in v1.0.2
