### ISSUE TITLE
TreeList Angular 9 compile error with ivy enabled

### ISSUE THREAD

**Issue by alexfangmann** [telerik/kendo-angular#2903]
When you install @progress/kendo-angular-treelist it produces a compile error.

**Angular 9.1.4**
**reproduce:** 
https://stackblitz.com/edit/kendo-treelist-error-ivy

**Compiler error:**

> Error in ~/src/main.ts
> ngcc failed to run on @progress/kendo-angular-treelist@1.0.1.

**Comment by tsvetomir** [comment]
There's [an issue](https://github.com/stackblitz/core/issues/1229) with StackBlitz that we're currently investigating, but it shouldn't affect offline projects. Do you get any errors when running the project locally?

**Comment by alexfangmann** [comment]
@tsvetomir you are right. It must be an issue in Stackblitz.
Offline I have no compile error
