### ISSUE TITLE
Angular 9 Kendo date math zoned date issue

### ISSUE THREAD

**Issue by aswanidutt93** [telerik/kendo-angular#2905]
**Describe the bug**
After upgrading to Angular 9 and updating kendo angular grid npm package,

I'm facing below error from kendo date math.

TS2416: Property 'addDays' in type 'ZonedDate' is not assignable to the same property in base type 'Date'.

Zoned Date is not assignable to type '(days:number)=>Date'.

Type Zoned Date is missing following properties from type 'Date': sameDate,sameMonthAndYear

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by tsvetomir** [comment]
This issue may be similar to #2706. Do you have an `addDays` method [augmenting](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#augmenting-globalmodule-scope-from-modules) the global Date object in the project or in an utility library?

**Comment by tsvetomir** [comment]
Ref #2852
