### ISSUE TITLE
Pager input is missing an accessible label

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2906]
**Describe the bug**
The numeric input of the pager is missing an accessible label.

**To Reproduce**

1. Open https://stackblitz.com/edit/angular-plepby
1. Inspect the pager input, an empty title is rendered.

**Expected behavior**
A default title of "Page number" or similar should be rendered based on the Grid localization messages.

**Screenshots**
Reference of the currently rendered markup:
```html
<input autocomplete="off" autocorrect="off" class="k-input k-formatted-value"
role="spinbutton" id="k-d0c7e05b-c8eb-493e-b5ee-b10c84abba0d"
aria-valuemin="1" aria-valuemax="9" aria-valuenow="1" title="" tabindex="0">
```

**Comment by dtopalov** [comment]
Fixed in v.0.2.2
