### ISSUE TITLE
Add option to set the label of inputs in the built-in editor templates

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2907]
Built-in [editors](https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-reactive-forms/) lack the option to set accessible labels. This can be worked around by declaring an [editor template](https://www.telerik.com/kendo-angular-ui/components/grid/editing/custom-reactive-editing/).

A built-in setting for the label would be nice to have. The column title can be used as a default.

**Comment by slavenai** [comment]
To be tracked in the Feedback Portal - [link](https://feedback.telerik.com/kendo-angular-ui/1609376-grid-treelist-add-option-to-set-the-label-of-inputs-in-the-built-in-editor-templates).
