### ISSUE TITLE
Popup of the ComboBox does not change its width when component is resized

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2909]
**Describe the bug**
When padding is applied (right or left) to the ComboBox the popup **width** is not calculated correctly and remains wider than the ComboBox. The DropDownList behaves as expected.
![2020-05-19_1826](https://user-images.githubusercontent.com/33104481/82345696-3b120100-99fe-11ea-8f4c-69877096fafb.png)

**To Reproduce**
1. Open the DropDownList and ComboBox popup.
https://stackblitz.com/edit/angular-scct12?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-dropdowns`.

**Comment by tapopov** [comment]
Fixed in v4.3.2
