### ISSUE TITLE
MultiSelect: valueChange event too early?

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#291]
I'm using now 0.27.7, subscribed to the valueChange event. In a earlier version (~0.26.6), the form control value was already updated, when valueChange has been triggered. Now the form control has still the old value.

I need to save the form data, when the value has changed. Is there a way to ensure that ng form _writeValue_  was called, before you emit the valueChange event (emit the event in writeValue)? 
or adding a new event valueChanged?

**Comment by KirilNN** [comment]
Can you please share a runnable sample of your setup? A plunkr maybe?

**Comment by EricSch** [comment]
@KirilNN  http://plnkr.co/edit/w2ryKxDhdZ95w5uhmh7x?p=preview
There you see, the form value isn't updated.

**Comment by KirilNN** [comment]
So in your case you need to use ngModelChange event, instead of valueChange, as the form will use ngModel binding for the components inside.

On a side note - you should be listening for `valueChanges` of the form, and perform your logic there, as this how the Angular Forms were designed. so it sho

**Comment by EricSch** [comment]
We don't use forms, only form controls, so this not an option
