### ISSUE TITLE
[TreeView] unexpected behavior when expanding

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2910]
**Describe the bug**
When using a TreeView that supports checking and expanding if the first parent node is checked and then all nodes are expanded the child nodes of the second parent node will be checked as well.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-stvclf-dx2xws?file=app/app.component.ts
1. Check the first parent node.
2. Click the Expand/Collapse button.

**Comment by dimitar-pechev** [comment]
Released in **v4.3.1**.
