### ISSUE TITLE
[Grid] Filter Menu does not work in ViewEncapsulation.ShadowDom.

### ISSUE THREAD

**Issue by myushchenko** [telerik/kendo-angular#2911]
**Describe the bug**
I have filterable="menu" options in Grid and root component with` encapsulation: ViewEncapsulation.ShadowDom`. When I click on filter menu button it doesn't open filter popup.

**To Reproduce**
Open https://stackblitz.com/edit/angular-kendo-grid-filter-menu
Try to filter on any column.

**Expected behavior**
Should open filter popup

**Browser**
 - Browser [Chrome]
 - Version [81]

**Additional context**
Issue looks related to attach modal to container. For ordinary popup I use custom `POPUP_CONTAINER `settings with `PopupService `class to change root container and it works in Shadow DOM, but this property doesn't help with grid-filter-menu popup.

**Comment by dtopalov** [comment]
Hi @myushchenko,

The shadowDom view encapsulation mode is not officially supported by the Kendo UI for Angular components, as it not only works to isolate the styles, but also to create a sub-tree with it's own document-like object (ShadowRoot). The latter causes a problem when the document object is used in the component code.

In general the shadowDom view encapsulation is to a large extent an unexplored area, as it's not supported by some legacy browsers like IE and due the styling issues it can cause - using it may force you to import the same styles in multiple places. That said it is rarely used.

Please support the following feature request in our Feedback portal to help us estimate the customer demand for such an enhancement:

[https://feedback.telerik.com/kendo-angular-ui/1466140-full-shadowdom-compatability-for-kendo-controls](https://feedback.telerik.com/kendo-angular-ui/1466140-full-shadowdom-compatability-for-kendo-controls)

For now, I can only advise not to use it with Kendo components as it could lead to unexpected behavior. Most of our components use the document object for some part of its internal workflow. So the caused issues might be minor or can cause a component not to work altogether.

Currently developers will have to stick to emulated view encapsulation when using our components.
