### ISSUE TITLE
Place image in kendo toolbar

### ISSUE THREAD

**Issue by jrichardsheritage** [telerik/kendo-angular#2912]
I want to use a toolbar for a header and place my image in the toolbar. Is this possible? I am running into issues. The below code will place the image above the toolbar.

<a [routerLink]="'/home'" >
        <img src="logo.PNG" alt="">
      </a>
      <kendo-toolbar>
        <kendo-toolbar-button [text]="'Home'"></kendo-toolbar-button>
        <kendo-toolbar-button [text]="'Second Tab'" [toggleable]="true"></kendo-toolbar-button>
        <kendo-toolbar-splitbutton
            [text]="'Split Button'"
            [data]="splitButtonData">
        </kendo-toolbar-splitbutton>
        <kendo-toolbar-dropdownbutton
            [text]="'DropDownButton'"
            [data]="dropdownButtonData">
        </kendo-toolbar-dropdownbutton>
        <kendo-toolbar-buttongroup [selection]="'single'">
            <kendo-toolbar-button [toggleable]="true" [icon]="'search'"></kendo-toolbar-button>
            <kendo-toolbar-button [toggleable]="true" [icon]="'user'"></kendo-toolbar-button>
        </kendo-toolbar-buttongroup>
      </kendo-toolbar>

**Comment by mbechev** [comment]
Hi @jrichardsheritage,

The repository is for bug reports only. Please open a[ support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
