### ISSUE TITLE
TreeList filtering does not work in Angular 9

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2914]
**Describe the bug**
When filtering a column, using Angular 9, the **filterChange** (and **dataStateChange**) is not triggered. If there is an initial filter the events are fired when it is cleared. 

Both events are emitted as expected if we filter a boolean, date, or numeric column.

Here is a screencast.
https://screencast-o-matic.com/watch/cYhrl8kKb9

**To Reproduce**
1. Download and extract the attached file
1. Execute **npm install** command (in root folder)
1. Execute **ng serve** command to run the app (in root folder)
[treelist-A9.zip](https://github.com/telerik/kendo-angular/files/4662498/treelist-A9.zip)

Reported in private support thread **1465054**

**Comment by tsvetomir** [comment]
Fixed in v1.0.3
