### ISSUE TITLE
grid-pagesize-relative-to-height in Angular

### ISSUE THREAD

**Issue by Rockesh786** [telerik/kendo-angular#2917]
Hi,
I am try to kendo angular with virtual scroll able based on the user device height actually i need to acheive this in angular https://docs.telerik.com/kendo-ui/knowledge-base/grid-pagesize-relative-to-height
Please solve it as soon as possiable

**Comment by dimitar-pechev** [comment]
To get help implementing a custom scenario, please open a support ticket. 

If you want to request an out-of-the-box feature, you can submit one on our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui).
