### ISSUE TITLE
[Multiselect] make `open` param optional in toggle method 

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2920]
The KendoMultiselect component has the following code
```
    public toggle(open: boolean): void {
        // The Promise is required for opening the popup on load.
        // Otherwise, the "Expression has changed..." type error will be thrown.
        Promise.resolve(null).then(() => {
            this._toggle((open === undefined) ? !this._open : open);
            this.cdr.markForCheck();
        });
    }
```
As per the posted code above, the `open` param could be omitted when calling that method. It would be nice if you added a question mark "?" at the end of paramter name to mark this parameter optional.

**Actual behavior**
When we want to toggle state, we should write a little cumbersome code like
```
this.kendoMultiselect.toggle(!this.kendoMultiselect.isOpen); or 
this.kendoMultiselect.toggle(undefined);
```
**Expected behavior**
```
this.kendoMultiselect.toggle()
```
should work properly and has no Typescript errors.

**Comment by ipeshev** [comment]
Available in v4.2.7 of @progress/kendo-angular-dropdowns
