### ISSUE TITLE
[ComboBox] filterChange fired with empty value after select

### ISSUE THREAD

**Issue by mrnetforge** [telerik/kendo-angular#2921]
**Describe the bug**
When value is selected,`filterChange` event fired with empty value.

**To Reproduce**

https://stackblitz.com/edit/angular-bhroqx

Type and select any of value. As you can see in console, filterChange fired with empty value, when value is selected, which is a bug

**Expected behavior**

filterChanged should fired only when you change filtering input, not when you select value

**Browser**
Chrome

**Comment by dimitar-pechev** [comment]
As the **ComboBox** popup can be opened after the user has selected a value, it should contain the full list of items. Similar to the **DropDownList** behavior. Therefore, it emits `filterChange` with an empty string on `valueChange`. If this is not the desired behavior in your specific use case, you can omit filtering the data set when the `filterChange` event value is an empty string and a selected value is present.

If you need help implementing this, please open a support ticket.
