### ISSUE TITLE
Enrich RowClassArgs with 'groupIndex'

### ISSUE THREAD

**Issue by Berezhnyk** [telerik/kendo-angular#2922]
Currently, RowClassArgs contains only an index and dataItem itself.
It would be great to have such property so it will help do styling by a group. 
Example of usage:

```
rowCallback(context: RowClassArgs): any {
    const isInEvenGroup = context.groupIndex % 2 === 0;
    return {
        even: isInEvenGroup ,
        odd: !isInEvenGroup 
    };
  }
```

**Comment by dtopalov** [comment]
Hi @Berezhnyk,

The repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations, or open a new feature request in our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui) for any desired new enhancements.
