### ISSUE TITLE
kendo-dropdownlist [data] source bug

### ISSUE THREAD

**Issue by eakoriakin** [telerik/kendo-angular#2923]
**Describe the bug**
When `[data]` source returns new array reference every time, it's not possible to select an item from the list.

**To Reproduce**
1. Open https://stackblitz.com/edit/angular-kendo-dropdown-data-bug
2. Click on dropdown list under "Broken" label.
3. Try to select an item.
4. Item won't select and list won't close.

**Expected behavior**
Item should be selected and list be closed.

**Additional context**
Same bug applies to `kendo-combobox`.

**Comment by dimitar-pechev** [comment]
The **DropDowns** are not designed to work with new `data` array instances on each change detection cycle. With larger data sets, this would lead to poor performance especially on slower browsers and computers. Therefore, this is not supported.

If you need to change the data set on certain user interaction, hook to one of the [component events](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/#toc-events) and substitute the data only on such occasions. 

If you need help implementing a custom scenario, please open a support ticket.
