### ISSUE TITLE
[MultiSelect] Poor performance when too many items are selected

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#2924]
**Describe the bug**
When too many items are selected, the browser hangs. The internal selection mechanism could be optimized to improve the performance.

**To Reproduce**
https://stackblitz.com/edit/angular-saa3kq-ak2hxf
Open the popup and click the select all checkbox in the header template. The browser hangs for 4-5 seconds.

**Expected behavior**
Multiple items selection shouldn't cause such hefty performance issues.

**Comment by yanmariomenev** [comment]
Moved to our Feedback Portal - https://feedback.telerik.com/kendo-angular-ui/1616825-improve-performance-in-scenarios-where-a-large-number-of-items-are-being-selected
