### ISSUE TITLE
[ComboBox] different behavior when clicking outside in Firefox

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2925]
Selecting a value that is longer than the available input width and clicking outside of the component results in different behavior in Chrome and Firefox.

In Chrome the ComboBox is blurred properly, and the long value is truncated with ellipsis, while in Firefox the end of the value is displayed (same as before clicking outside):
[https://stackblitz.com/edit/angular-yhwosz-ynpmqv?file=app/app.component.ts](https://stackblitz.com/edit/angular-yhwosz-ynpmqv?file=app/app.component.ts)

If another input is focused programmatically, or the ComboBox **blur()** method is called in the **valueChange** event handler, the behavior is correct (same as in Chrome):

[https://stackblitz.com/edit/angular-yhwosz-z4rywb?file=app/app.component.ts](https://stackblitz.com/edit/angular-yhwosz-z4rywb?file=app/app.component.ts)

**Comment by gkarapeev** [comment]
Fix available in release v4.3.1
