### ISSUE TITLE
Dev build and Prod Build have rendering Differences in HTML

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2926]
**Describe the bug**
In Dev build I can see ng-reflect-readonly="true" as a property for kendo-autocomplete but if i have prod build there i can not find ng-reflect-readonly="true" for the same control. I am not understanding why is this issue for same control. All ng-reflect attrubutes are missing.
I am having  "@progress/kendo-angular-dropdowns": "4.1.0",
My configuration setting is:-
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-prod": "ng build --aot --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },

**To Reproduce**
Build with dev or ng serve and then with prod build for autocomplete feature. There is rendering difference.

**Expected behavior**
Both should show same attributes and propertys and there should be no difference. as developer may like to know other propertys of a control as in my case i need to know ng-reflect-readonly="true" or ng-reflect-readonly="false".

**Screenshots**
![dev-build-autocomplete](https://user-images.githubusercontent.com/5736855/83007973-163b1080-a032-11ea-94a9-6db078a42b76.PNG)

![prod-build-autocomplete](https://user-images.githubusercontent.com/5736855/83007966-13d8b680-a032-11ea-9878-6f48bbb9b7ce.PNG)

**Browser**
All browsers same issue.

Please reply if its intentionally removed extra attributes in prod. so i will use another logic.

**Comment by PetarMetodiev** [comment]
Hi Tushar,
The described behaviour is specific to Angular and not related to Kendo UI for Angular. The `ng-reflect-*` attributes are used by the framework for debugging purposes in dev mode and are removed in production mode. More info on the topic can be found in this [StackOverflow question](https://stackoverflow.com/questions/43397839/what-does-the-ng-reflect-attribute-do-in-angular2-4).
