### ISSUE TITLE
Row UI virtualization

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#2929]
## I'm submitting a...
* Suggestion for improvement  

## Current behavior
Virtual scrolling is currently tied to the pageSize. This is not always desirable as page size can be much higher than the visible area to optimize for network latency.

For example if the pageSize is 200 rows and the grid is only 10 rows high we'll be rendering 190 more rows than needed at initialization time.

## Expected behavior
Virtual scrolling should include an option to render only the visible rows at any given time.

**Comment by Raisolution** [comment]
Transferred to the Kendo UI for Angular feedback portal to track customer demand for this feature
https://feedback.telerik.com/kendo-angular-ui/1566804-row-ui-virtualization
