### ISSUE TITLE
[Upload] the same file cannot be selected two consecutive times in Safari

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2930]
**Describe the bug**
When using the Kendo Uploud in Safari with the [autoUplod] option set to false then the same file cannot be selected two consecutive times.

**To Reproduce**
Please open the following example in Safari:

https://stackblitz.com/edit/angular-p7ykkk?file=app/upload.component.ts

1. Select a file.
2. Clear the file from the Upload file list.
3. Try to select the same file.

**Comment by Raisolution** [comment]
Fix is available in `v7.1.4` of the `kendo-angular-upload` package.
