### ISSUE TITLE
PanelBarItem click event doesn't work for remote data 

### ISSUE THREAD

**Issue by incilada** [telerik/kendo-angular#2931]
Hi,
I want to create a menu with `kendo-panelbar`. Menu has remote data and unknown depth level. When the leaf node is clicked, the page will open. It doesn't accept keys except 'title' when I make like this `<kendo-panelbar [items]="items"></kendo-panelbar> ` and I can't access click event for leaf node. Also, item template doesn't work for that.

Help me, please...

Sample Data;
```
items = [
        { description: 'First item'  },
        { description: 'Second item', children: [
                { description: 'Second item child item' }
            ]
        },
        { description: 'Third Item', children: [ 
                { description: 'Third item child item' , children: [
                    {
                        description: 'Child item'
                    }
                ]
                }
        ]
        }
    ];

```

**Comment by dimitar-pechev** [comment]
To acquire help implementing a custom scenario, either [open a support ticket](https://www.telerik.com/account/support-tickets) or a StackOverflow thread. This repository is for bug reports only.
