### ISSUE TITLE
Multiselect arrow keys do not focus the correct tag in RTL mode.

### ISSUE THREAD

**Issue by jtdremann** [telerik/kendo-angular#2932]
## I'm submitting a...
* Bug report

## Current behavior
In RTL mode, the <kendo-multiselect> left and right arrow keys do not function correctly. The right arrow key moves the focused tag to the left, and the left arrow key moves the focused tag to the right.
When no tag is focused, the right arrow key focuses rightmost tag
When the right most tag is focused, the left arrow key unfocuses the tag and does not focus a new one.

## Expected behavior
In RTL mode, the left arrow key should move the focus to the tag on the left, and the right arrow key should move the focus to the tag on the right.
When no tag is focused, the right arrow key should focus the leftmost tag.
When the rightmost tag is focused, the left arrow key should focus the tag to the left

## Minimal reproduction of the problem with instructions
Set Kendo's RTL mode by providing the RTL injection token with the value "true".
In any <kendo-multiselect> component, use the left and right arrow keys to focus tags.

## Environment

Package versions: demo site

Browser:
- Chrome Desktop 83.0.4103.61
- Firefox version 76.0.1

System:
- Platform:  Windows

**Comment by ipeshev** [comment]
Fix availbale in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by gkarapeev** [comment]
Fix available in release v4.3.1
