### ISSUE TITLE
Scroll Issue and triggering of Focus event On Inline Editable Template Grid

### ISSUE THREAD

**Issue by TUSHARDM** [telerik/kendo-angular#2933]
**Describe the bug**
In my project, I have used an inline template editable grid. In that I have added addRow() at component initilazation time. No issue happens (or appear to happen) when the grid is opened in upper part of screen i.e. Vieweable browser area on load. In order to avoid extra click our business team require to add first empty record at the top of every grid. which also work well but have following two issues.
You can have a look at my code at URL:-
https://stackblitz.com/edit/angular-kendo-edit-grid

1. If i have some other code and designs at top of my page, but when this page opens it automatically scroll my page down and put focus in first editable field even though I have removed focus related code from my editable row fields. So, In my case i **do not want** page to scroll even editable row event is fired on component initialization.
2. The first field shows red border even though I have not touched it yet which should not happen.

From this I want to ask 
1. Can we avoid scroll behavior not to happen.
2. Is This what i have done is wrong implementation.
3. Do we have defocus event as we are showing focused and with red line as that happens even at top part of the page also If grid is at top. 

**To Reproduce**
https://stackblitz.com/edit/angular-kendo-edit-grid
https://angular-kendo-edit-grid.stackblitz.io/

**Expected behavior**
1. Page should not scroll automatically. (Same page scroll issue happens on tab also when we trigger it through programetically i.e. open second tab programatically when tab is not in first view area of browser window as for grid issue here)
2. Should not auto select field as ng-touched gets fired automatically.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5736855/83604963-b2b26500-a594-11ea-8a5a-14e40479a01d.PNG)
**Browser**
Chrome and Internet Explorer recent versions.

**Comment by TUSHARDM** [comment]
![actual-look](https://user-images.githubusercontent.com/5736855/83607867-8ea55280-a599-11ea-98be-1343677351db.PNG)

This is how my grid looks in my project.

**Comment by dtopalov** [comment]
Hi @TUSHARDM, 

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations, or submit a new feature request in our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui) for any desired new enhancements.
