### ISSUE TITLE
[Multiselect] group name is not rendered in a template with kendoMultiSelectFixedGroupTemplate directive

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2935]
**Describe the bug**
I have a Multiselect with nested directives `kendoMultiSelectFixedGroupTemplate` and `kendoMultiSelectGroupTemplate`. I am not able to render group name inside the `kendoMultiSelectFixedGroupTemplate`  since the provided value for `groupName` is undefined.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-33m3p9-5wwuya?file=app/app.component.ts
2. Observe that the `Item 1` text is not displayed inside the template with `kendoMultiSelectFixedGroupTemplate`  directive.

**Expected behavior**
`groupName` variable should be available inside the template.

**Comment by dimitar-pechev** [comment]
Already tracking in https://github.com/telerik/kendo-angular/issues/2571. 

As the problem is with nested child properties, the work-around for now is to map you data and pull the group identifier property to the top level.
