### ISSUE TITLE
[ToolBar] Error when [popupSettings]="{ animate: false }"

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2939]
**Describe the bug**
An error is thrown when the animation for the popup settings is disabled like so:
```html
<kendo-toolbar [popupSettings]="{ animate: false }"></kendo-toolbar>
```

**To Reproduce**
https://stackblitz.com/edit/angular-9qhvrw?file=app/app.component.ts

1. Open the overflow popup.
2. An error is thrown.

**Expected behavior**
No error should be thrown when the overflow popup has been opened.

**Comment by Raisolution** [comment]
Fixed in `v4.1.1`
