### ISSUE TITLE
MultiSelect component supports multiple header?

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#294]
Recently I came across an issue, I was trying to add multiple headers in multiselect popup. 
See the screenshot below.
But the truth is I can only add one "Groups", so I am wondering whether it is possible to add multiple headers at this point of time ? If not, are there any workarounds ?

![image](https://cloud.githubusercontent.com/assets/15974161/22816579/d099cc9e-ef9d-11e6-9320-13a04a270057.png)

**Comment by KirilNN** [comment]
Currently the MultiSelect does not support grouping functionality, and this is a header template that you are using there. 

You can suggest this for future implementation here - kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback

**Comment by zhao125787935** [comment]
Hi Kendo Team,

I work out a way to add multiple headers in multiselect item template,  see the code snippet below,

`<kendo-multiselect #multiselect [data]="items" [textField]="'ReportingCode'" [valueField]="'ReportingCode'" [valuePrimitive]="false"
[filterable]="true" [suggest]="true" [placeholder]="'Select a portfolio'" [popupSettings]="{height: 270}"
(filterChange)="handleFilter($event)" (valueChange)="handleValueChange($event)" >
	
       <template kendoMultiSelectItemTemplate  let-dataItem>
		<div class="container-fluid">
			<strong class="group_name" disabled *ngIf="dataItem.GroupName">{{dataItem.GroupName}}</strong>
			<div class="col-xs-4">{{dataItem.ReportingCode}}</div>
			<div class="col-xs-8">{{dataItem.ReportHeading}}</div>
		</div>
	</template>
</kendo-multiselect>`
And this is the screenshot.
![image](https://cloud.githubusercontent.com/assets/15974161/23057654/155c92d8-f52c-11e6-8a6a-9f48995d0291.png)

But now I am encountering a selection issue,  **actually I don't want to the header rows of "Portfolios" or "Groups" to be selected, because they are headers and don't have values to show.** 
I tried with using CSS trick like "pointer-events: none", but it does not work for the items.

So would you please have a look at this issue and provide some workarounds ?

Thanks

**Comment by KirilNN** [comment]
The selection in the MultiSelect component is tightly coupled with the items and the respective itemTemplate - therefore when an item/template is clicked there is no filter for the target in order to distinguish whether you want to actually click the item or not. 

The click will be reflected in the rendering and the general state of the component, so there is no workaround for this, as it is indeed the desired behavior.
