### ISSUE TITLE
DropDownList: test and check k-popup

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#2940]
We just would like to test a component that uses DropDownList and we would like to open it and select one value. (i remember the first attempt here: https://github.com/telerik/kendo-angular/issues/1003)

I have a repo to reproduce the problem:
https://github.com/meriturva/kendo-dropdown-simple-test

We are able on test `should open a dropdown` to click on it and show kendo-popup but after we are unable to get it. I guess the main problem is related to POPUP_CONTAINER that it place .k-popup div outside app root div container.

We just would like to have an approach "easy to maintain" just to test value change on dropdown waiting for #2716

**Comment by svetq** [comment]
Hi @meriturva 

All Kendo UI for Angular components are internally tested. The implemented tests can be seen by [obtaining the source code of any package](https://www.telerik.com/kendo-angular-ui/components/installation/source-code/) - @progress/kendo-angular-dropdowns for example. Please check the test and e2e folders.

As the purpose of this is repository is to log issues related to Kendo UI for Angular, I will close this issue as it isn't related to a bug. I have further provided an answer within the private support thread where we can keep any further communication. Please open support tickets for such questions in the future. Thank you.
