### ISSUE TITLE
Text labels in <kendo-label> for nested component are not clickable

### ISSUE THREAD

**Issue by doctorssm** [telerik/kendo-angular#2949]
**Describe the bug**
When clicking a `<kendo-label>` the corresponding nested input field for nested component is not focused.

**To Reproduce**
https://stackblitz.com/edit/angular-6bxeqc-txnlkd?file=app%2Fapp.component.ts

- Click on the Input2/Input3 text labels
- Input field is not focused

**Expected behavior**
The input field next to the clicked label should be focused.

**Comment by dtopalov** [comment]
Hi @doctorssm,

Currently the KendoLabel component can be associated only with native HTML input, select, and textarea elements, and Kendo UI for Angular components (like NumericTextBox, DateInputs, DropDowns, etc.)

I apologize for the documentation indeed not being clear enough on this subject.

Providing an approach to associate custom Angular components with the KendoLabel will be a very nice enhancement, and this is why we will look for a viable approach to make this possible, and will update the documentation accordingly.

Meanwhile, I can suggest a possible workaround to associate the KendoLabel with a custom component via the "for" binding that is used for focusing the Kendo UI for Angular components - they all have a "focus" method that internally focuses the correct inner focusable element.

Implementing such method in the custom component code will enable focusing it when the label is clicked, for example:

https://stackblitz.com/edit/angular-6bxeqc-gmbx4y?file=app%2Fapp.component.ts

**Comment by doctorssm** [comment]
@dtopalov thank you for quick response and special thanks for nice workaround with focus method!

**Comment by dtopalov** [comment]
Hi @doctorssm 

The Label documentation was updated accordingly with the necessary requirements to associate an Angular component with the Kendo Label:

https://www.telerik.com/kendo-angular-ui/components/labels/label/#toc-other-angular-components

If you feel that a further enhancement on our end to provide other means for associating custom components with the Kendo Label is necessary, please open a new feature request in our Feeback portal briefly describing the use case demanding it:

https://feedback.telerik.com/kendo-angular-ui

We will track the customer demand there, and will consider adding such an enhancement to our future plans, based on the interest and estimated business value.
