### ISSUE TITLE
kendo grid after refresh can't get the sort and filter parameters.

### ISSUE THREAD

**Issue by lzr900515** [telerik/kendo-angular#295]
[stackOverFlow_Question_Link](http://stackoverflow.com/questions/42154175/kendo-grid-get-filter-and-sort-parameters#new-answer)
```
 //init a kendo grid table without datasource at first;
       $scope.mainGridOptions = {
        toolbar:[
            {
                template: "<button excel-export-btn kendo-grid-element='mainGridOptions' data = 'paramData()' down-url='kendoExcelUrl' class='k-button k-button-icontext'><span class='k-icon k-i-excel'></span>export</button>"
        ],
        sortable: true,
        resizable: true,
        pageable: _kendoConfigure.pageable,
        filterable:_kendoConfigure.filterable,
        noRecords: true,
        columnMenu: true,
        messages: _kendoConfigure.messages,
        columnMenuInit: _kendoConfigure.columnMenuInit,
        columns: columnConfig($rootScope.userData.role)
    };
    // use initGrid function i can add new parameters to get refresh data;
    function initGrid(begin,end,dateType,inviteCodeType,url){
        var dataSource = dataSourceInit(
            url,
            {
                'start_date':_dateToString(begin),
                'end_date':_dateToString(end),
                'type':dateType,
                'code_type':inviteCodeType,
                'enterprise_status':$scope.enterprise_status,
                'assign_status':$scope.assign_status
            }
        );
     $("#mainGridOptions").data("kendoGrid").setDataSource(dataSource);
        $("#mainGridOptions").data("kendoGrid").refresh();
    }
```
everything seem works fine, i can click the column menu to do sort and filter, but when i want to get the sort and filter parameters for another ajax request. like this: $scope.mainGridOptions.dataSource._filter or $scope.mainGridOptions.dataSource.filter() can get  #nothing(undefined); how can i solve the problem? thanks for help!!!

**Comment by rkonstantinov** [comment]
This repository is for Kendo UI for Angular (this is v2+) product. However, your questions seems to be related to Kendo UI for jQuery product's AngularJS integration.

If you are looking for direct support from our team, you can purchase a Kendo UI Professional license (or any other license that includes Kendo UI Professional). This will grant you read-write access to the Premium forums, the ability to submit tickets in our support system, and access to additional professional-grade widgets, charts and graphs.
