### ISSUE TITLE
[Buttons] Dynamically setting popup class does not work

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2951]
Currently changing dynamically the [PopupSettings](https://www.telerik.com/kendo-angular-ui/components/buttons/api/PopupSettings/) does not work when the popup is opened. 
Here is an example: 
https://stackblitz.com/edit/angular-jjzmad-wrfqag?file=app/app.component.ts
1. Open the dropdown button or the split button.
2. New class is not applied while the popup is opened.

Since changing property of an input object does not trigger Angular change detection mechanism, it would be nice to update the popup settings when the object reference for them has been changed.

**Comment by Raisolution** [comment]
Fix available in `v6.2.1`
