### ISSUE TITLE
[Stepper] Styling issue when used in IE11

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2952]
**Describe the bug**
There is a styling issue when using the Stepper in IE11:
![image](https://user-images.githubusercontent.com/20015190/84772485-ab06ad80-afe3-11ea-8366-5b8a9d620649.png)

**To Reproduce**
Please check the following article in IE11:
https://www.telerik.com/kendo-angular-ui/components/layout/stepper/

**Comment by mbechev** [comment]
The Stepper component is not supported in IE 11 and below - documented [here](https://www.telerik.com/kendo-angular-ui/components/layout/stepper/#toc-known-limitations).
