### ISSUE TITLE
Load Tabs on Demand example improvements

### ISSUE THREAD

**Issue by davidboothe** [telerik/kendo-angular#2953]
The example for [Load Tabs on Demand](https://www.telerik.com/kendo-angular-ui/components/layout/tabstrip/how-to/load-tabs-on-demand/#toc-load-tabs-on-demand) has code for a directive that uses optional parameters in the constructor that are not truly optional. 

```TS
@Optional() private tabStripComponent: TabStripComponent,
@Optional() private tabStripTabComponent: TabStripTabComponent,
```

```TS
// #1 Initialize only if it is inside of a kendo TabStrip component
if (!this.tabStripComponent || !tabStripTabComponent) {
  return;
}
```

If this example was for a more generic directive, I could see these being optional. However, this directive will not work without these components and the if statement swallows any errors I might be given.

I suggest removing the ```@Optional()``` and the whole if statement

**Comment by elena-gancheva** [comment]
Thanks for pointing this out, @davidboothe , we'll update the example demo in the docs as suggested.

**Comment by mbechev** [comment]
Example updated: https://www.telerik.com/kendo-angular-ui/components/layout/tabstrip/how-to/load-tabs-on-demand/#toc-load-tabs-on-demand
