### ISSUE TITLE
"Cannot set property 'forceExpand' of undefined" error with Kendo Splitter

### ISSUE THREAD

**Issue by aszalaid** [telerik/kendo-angular#2954]
## I'm submitting a...

* Bug report 

## Current behavior

When using horizontal `<kendo-splitter>` with two collapsible panes, having left pane is expanded and right pane collapsed, double-clicking the splitter bar (not the arrow) or hitting Enter on it throws JS error "Cannot set property 'forceExpand' of undefined".

## Expected behavior
No JS error should be thrown, the right pane should be expanded.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-d6je1o?file=app/app.component.ts

Double-click on the splitter with left arrow (don't click the arrow directly). The collapsed right pane should be expanded.

## Environment

Package versions:

latest

Browser:

- Chrome (desktop) latest
- Chrome (Android) latest
- Firefox latest
- Edge latest

System:
- TypeScript version: 3.7.4
- Node version: node v10.15.1, npm 6.4.1
- Platform: Windows

Additional information:
There is no check in SplitterService.tryToggle for the length of the notCollapsed array, and array index is out of range.

A suggested fix for avoiding the situation AND opening the right pane instead of the left (which is nearer to an user's expectation how this double-click should work) is to modify the tryToggleNearest() method as follows: If the left pane is collapsible and the right pane is not collapsed then try to toggle the collapsed state of the left pane. Otherwise if the right pane is collapsible and the left pane is not collapsed then try to toggle the collapsed state of the right pane.

**Comment by siyka-marinova** [comment]
Fixed in `kendo-angular-layout v5.0.3`
