### ISSUE TITLE
[FloatingLabel] throws error when used with an *ngIf inside Dialog

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2959]
**Describe the bug**

The FloatingLabel throws an error: _Cannot read property 'setAttribute' of null_, when used with an *ngIf directive inside a Dialog that is dynamically displayed based on *ngIf. If the FloatingLabel is used for a regular input then the error doesn't exist.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-4s7edn-dfjjzr?file=app/app.component.ts

**Workaround**

use a service to bring up the Dialog:
https://stackblitz.com/edit/angular-robwz8-geelsy?file=app/app.component.ts

**Comment by siyka-marinova** [comment]
Fixed in the latest [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-label`.

**Comment by dimitar-pechev** [comment]
Available in **v4.3.3**.
