### ISSUE TITLE
[Editor] cannot move cursor after a table

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2961]
**Describe the bug**
If there is a table added to the end of the content of the Editor, then it isn't possible to place the cursor after the table.

**To Reproduce**
Please check the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/editor/tools/#toc-built-in-tools

1. Add a table to the end of the Editor content.
2. Try to move the cursor after the table.

**Comment by dtopalov** [comment]
Fix is available in v.2.3.0 of the `@progress/kendo-angular-editor` package.
