### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2962]
The v.10 has been published, so it would be nice if all Kendo packages were compatible with version 10. At the moment some warnings are printed when you update your project to Angular 10.

**Comment by tsvetomir** [comment]
The [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) are updated to address compatibility issues with v10. We're currently checking for any pending issues and will publish official updates as soon as possible.

**Comment by tsvetomir** [comment]
The latest release of all packages should be fully compatible with Angular v10. See [Updating to Latest Versions](https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/#toc-updating-to-latest-versions).

This release also includes a set of fixes related to tree-shaking 🌴 . Depending on the packages in use, you should see reduction in the bundle size: 80-140kB for the Grid and 13kB for the Editor. See #2783
