### ISSUE TITLE
Error occurs k-state-focused when disabled comboBox after value change

### ISSUE THREAD

**Issue by nevraydin** [telerik/kendo-angular#2963]
When combobox is setted disabled after triggered valueChange event, throws ExpressionChangedAfterItHasBeenCheckedError for k-state-focused.

Here is an example
https://stackblitz.com/edit/angular-i5mo8n

![image](https://user-images.githubusercontent.com/946627/85684258-9e1a4600-b6d6-11ea-8aa2-cec222565a54.png)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
