### ISSUE TITLE
Unnecessary <ul> and <ol> tags are added when copy paste bullets

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2967]
**Describe the bug**
When copying bullets in Editor and after that pasted in place of existing bullets, creates an unnecessary bullet list as they are wrapped in <_ul_> tags:
https://screencast-o-matic.com/watch/cY1O1h51JT

**To Reproduce**
https://stackblitz.com/edit/angular-ogz1lq?file=app/app.component.ts

**Comment by Raisolution** [comment]
Issue is no longer reproducible in the latest Editor version
https://www.telerik.com/kendo-angular-ui/components/editor/
