### ISSUE TITLE
Using Enter key on select all checkbox, throws an error in navigable Grid

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2968]
When **navigable** option is enabled, and _kendo-grid-checkbox-column_ component is used with [select all](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-select-all-feature) option, clicking Enter key in the header, triggers the **sortChange** event:

![Capture](https://user-images.githubusercontent.com/33104481/85838167-dcc90280-b7a1-11ea-9897-14437ab7955b.PNG)

https://screencast-o-matic.com/watch/cY1OjH5in3

**To Reproduce**
1. Click Enter on Select All checkbox
https://stackblitz.com/edit/angular-2lmxqv?file=app/app.component.ts

**Comment by dtopalov** [comment]
Fix available in the [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dtopalov** [comment]
Fixed in v.4.8.1
