### ISSUE TITLE
Grid :: Expanding row programmatically doesn't emit detailExpand event

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#297]
Expanding grid row by GridComponent.expandRow(index) doesn't emit (detailExpand) event.

Here is a plunker:
http://plnkr.co/edit/ioHDtTW9KtjGKe1rqtYH
*Expanding a row by expander icon will alert 'Expanding' but won't if you use the button below table.*

**Comment by rkonstantinov** [comment]
Indeed, this is the designed behavior. 
The [detailExpand](http://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-detailexpand)/[detailCollapse](http://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-detailcollapse) events are there to signal when user expands/collapses a detail row via the UI.
