### ISSUE TITLE
Documentation issue with imported function name

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#2970]
**Describe the issue**
https://www.telerik.com/kendo-angular-ui/components/datemath/date-calculations/#toc-date-only-portions
There is a mismatch between the imported and utilized function name in the 'Date-Only Portions' section. It should have been 
```
import { isEqualDate} from '@progress/kendo-date-math';
```

**Comment by dtopalov** [comment]
Hi @destus90, 

Thank you for reporting this mismatch, we will update the documentation accordingly.

**Comment by dtopalov** [comment]
The documentation example is updated:

https://www.telerik.com/kendo-angular-ui/components/datemath/date-calculations/#toc-date-only-portions
