### ISSUE TITLE
[Slider] Screenreaders are not announcing the expected values

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2971]
When using a screen reader (such as JAWS), the user is not informed of the current value the slider holds neither does it announce to the user the updated value of the slider when moving the thumb.

Furthermore, it would be preferred that the slider’s min and max values be announced when initially tabbing onto the slider; currently all the tick labels are read in order instead when tabbing into the slider.

**Comment by Raisolution** [comment]
Implemented in `v7.3.0`
