### ISSUE TITLE
 [Grid Accessibility] aria-selected attributes of Grid cells not updated when the row is selected/deselected

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2973]
When the Grid is navigable and the selection is enabled, the aria-selected attribute values of the TD elements are not updated when their parent row's selected state is changed.

**Comment by dtopalov** [comment]
Fix available in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by Raisolution** [comment]
Fix available in `v4.8.3` of the `kendo-angular-grid` package.
