### ISSUE TITLE
[Editor] valueChange is not fired when space is inserted

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2975]
**Describe the bug**
When <kbd>Space</kbd> is pressed, `(valueChange)` does not emit the updated value.

**To Reproduce**
https://stackblitz.com/edit/angular-t9f8a8?file=app/app.component.ts

1. Click on content area.
2. Press <kbd>Space</kbd>.
3. `(valueChange)` does not emit.

**Expected behavior**
When <kbd>Space</kbd> is pressed, `(valueChange)` should emit the updated value.

**Additional context**
If space is inserted between adjacent characters, `(valueChange)` emits the updated value but only on the first press.

**Comment by Crossfir3** [comment]
:heavy_check_mark: Tested OK in the latest dev version.
