### ISSUE TITLE
[DatePicker] Not closing after using toggle(true)

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2976]
**Describe the bug**
When the `<kendo-datepicker>` is opened by calling `toggle(true)`, closed with a click outside of it and then opened again by clicking on the icon, it can't be closed with a click outside of it.

**To Reproduce**
https://stackblitz.com/edit/angular-tkyfzp?file=app/app.component.ts

1. Click inside the input to open the calendar.
2. Click outside the component to close the calendar.
3. Click on the icon to open the calendar again.
4. Click outside the component.
5. The calendar is not closed.

**Expected behavior**
The calendar should be closed when clicked outside the component.

**Comment by dimitar-pechev** [comment]
Released in **v4.3.2**.
