### ISSUE TITLE
[Grid] Non-navigable Grid multiple checkbox selection does not work when navigated to using the Router

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#2977]
The issue is quite obscure and reproducible under specific circumstances only.

Steps to reproduce:

1. Run the attached sample project
2. Click the "Grid1" link
3. Interact with the selection checkboxes
4. Click the button in the toolbar template or the Grid2 link
5. Grid2 treats clicking the selection checkboxes as double-clicks and a selected item cannot be deselected, also multiple items cannot be selected

Observations:

The described issue occurs only if the second Grid (Grid2) is non-navigable, and the user had interacted with the checkboxes of Grid1 before navigating to Grid2. If Grid2 is opened directly - opening localhost:4200/grid2, or Grid1 is opened, but not interacted with, then Grid2 is accessed via the button or the router link, checkbox selection is working as expected. If at this point we go back to Grid1, click a checbox, and return to Grid2 - the selection is again not working properly.

When setting **checkboxOnly** to true in the second Grid, the selection is again working as expected, suggesting that the main cause of the problem is the click bubbling from the checkbox to the Grid row.

Sample project:

[Archive.zip](https://github.com/telerik/kendo-angular/files/4852113/Archive.zip)

**Comment by dtopalov** [comment]
The same behavior is observed in a production build of an Angular 8 application too (tested with ng serve --prod). The selection is working as expected in development mode (ng serve).

**Comment by svetq** [comment]
requested in 1498075
