### ISSUE TITLE
[Grid] Custom drag & drop implementation for columns inside kendo grid

### ISSUE THREAD

**Issue by DeeJayElly** [telerik/kendo-angular#2979]
I am trying to implement a custom drag & drop implementation for columns inside kendo grid. Is it possible to add for example something like CDK Angular drag and drop -> https://material.angular.io/cdk/drag-drop/overview , because current drag & drop implementation for one of our projects doesnt include everything that we need.

Currently we are looking for a solution to override the behavior of drag of element, dropping of element, showing placeholder when the element is dragged and similar, and we can't achieve them with default kendo drag drop on grid tables.

**Comment by dtopalov** [comment]
Hello @DeeJayElly,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenario implementations or configurations, or submit feature requests to our [Feedback portal](https://feedback.telerik.com/kendo-angular-ui) for any desired enhancements and functionalities that are currently unavailable.
