### ISSUE TITLE
Dependencies are installed under "@telerik"

### ISSUE THREAD

**Issue by HolgerPersch** [telerik/kendo-angular#298]
Some components, e.g. kendo-angular-inputs, are installing dependencies under "@telerik". I guess it should be "@progress".

It's not a problem - just for your info.

![kendo dependencies](https://cloud.githubusercontent.com/assets/5908383/22886377/d5faf2dc-f1fd-11e6-9265-3b3885ebb829.PNG)

**Comment by tsvetomir** [comment]
We'll be moving some of those (*-common) to `@progress` at some point.
The rest are OSS projects that we maintain in their respective repos:
* [kendo-intl](https://github.com/telerik/kendo-intl)
* [kendo-draggable](https://github.com/telerik/kendo-draggable)
