### ISSUE TITLE
The Upload component displays HTML entities in uploaded file names

### ISSUE THREAD

**Issue by edubenetskiy** [telerik/kendo-angular#2981]
## I'm submitting a...

* Bug report

## Current behavior

The Upload component displays HTML entities (e.g. `&amp;` or `&#39;`) in the list of uploaded files 
when the name of an uploaded file contains special characters (like an ampersand `&` or apostrophe ```'```).

Moreover, the produces upload events have `file.name` containing these HTML entities instead of original filename’s characters.

## Expected behavior

The Upload component displays special characters (like `&` or ```'```) in the names of uploaded files properly.

Produced events have `file.name` containing the same characters as the uploaded file’s name.

## Minimal reproduction of the problem with instructions

It is reproducible in the component’s documentation.

1. Open the [page Upload → Getting started](https://www.telerik.com/kendo-angular-ui/components/uploads/upload/) of the documentation for the Uploads component.
1. Navigate to section “Basic Usage”.
1. Upload any file having an ampersand and/or an apostrophe in its name, e.g. `D'Artagnan & Three Musketeers.txt`.
1. See the filename in the list of uploaded files and in the event log.

See the screenshot below.

![image](https://user-images.githubusercontent.com/8538359/86289444-63437100-bbf4-11ea-89ec-5766596fd421.png)

## Environment

- Browser: Chrome (desktop) version 83.0.4103.116
- OS: Windows

**Comment by Raisolution** [comment]
Fix for this issue is available in `v6.0.2` of the Upload package.
