### ISSUE TITLE
kendo-angular-common with Angular 10

### ISSUE THREAD

**Issue by clabough** [telerik/kendo-angular#2982]
When using Angular 10, npm is displaying these warnings about kendo-angular-common.

> npm WARN @progress/kendo-angular-common@1.2.2 requires a peer of @angular/common@6 - 9 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-common@1.2.2 requires a peer of @angular/core@6 - 9 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-common@1.2.2 requires a peer of @angular/forms@6 - 9 but none is installed. You must install peer dependencies yourself.
npm WARN @progress/kendo-angular-common@1.2.2 requires a peer of @angular/animations@6 - 9 but none is installed. You must install peer dependencies yourself.

**Comment by tsvetomir** [comment]
Thanks! Fixed in v1.2.3
