### ISSUE TITLE
kendo-datepicker  Calander months  first character should be upper case. 

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#2984]
HI,

 I have used Spanish localization in my application.  when I  open my application in the Spanish language.  the calendar control open in Spanish but all months view in small latter. 
Here I want to show the fist latter of the month in UPPER case.  how can I show the latter?

please find attachment and see the highlighted area which I want to show in the upper case.

Thanks 

![image](https://user-images.githubusercontent.com/15213587/86465561-82a2e100-bd4f-11ea-8ce3-ddeddc1a4f40.png)

**Comment by dimitar-pechev** [comment]
Month names are not capitalized in Spanish in principle.

To get help implementing a custom scenario, please open a [support ticket](https://www.telerik.com/account/support-tickets). This repository is for bug reports only.

**Comment by svdeshmukh16** [comment]
As per localization can we set the custom months' name? If yes then kindly provide me the sample.
