### ISSUE TITLE
kendo-datepicker Calander set Custom months name

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#2985]
In  kendo-datepicker Calander. I won't set the customer names of month. How can we set the custom names  in kendo-datepicker Calander.  kindly provide me the sample.

**Comment by dimitar-pechev** [comment]
To get help implementing a custom scenario, please open a [support ticket](https://www.telerik.com/account/support-tickets). This repository is for bug reports only.
