### ISSUE TITLE
[MultiViewCalendar] the voice over doesn't read the proper information 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2986]
**Describe the bug**
Using the voice over functionality of an iOS device doesn't announce the dates when the finger focuses the dates. It reads just the displayed number for the date which doesn't make it clear what is selected.

**To Reproduce**
Please check the behavior of the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/dateinputs/multiviewcalendar/

**Browser**
 - OS: iOS
 - Browser: Safari

**Comment by tswetti** [comment]
The issue is no longer reproducible as of [v16.3.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.3.0)
