### ISSUE TITLE
kendo-datepicker Calander set Custom localization

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#2987]
Hi

How can we set the kendo-datepicker Calander Custom localization for months and weeks?
kindly provide a solution for this.

Thanks,

**Comment by mbechev** [comment]
Hi @svdeshmukh16,

This repository is for bug reports only. Please open a[ support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenario implementations or configurations, or submit feature requests to our [Feedback Portal ](https://feedback.telerik.com/kendo-angular-ui)for any desired enhancements and functionalities that are currently unavailable.
