### ISSUE TITLE
Checkbox column component sorting with ENTER key triggers sorting exception

### ISSUE THREAD

**Issue by elca-lan** [telerik/kendo-angular#2988]
**Describe the bug**
There is a bug in `@progress\kendo-angular-grid\dist\es2015\rendering\header\header.component.js` in the method `onHeaderKeydown`. When the ENTER key is pressed while the select-all checkbox of a `kendo-grid-checkbox-column` has the focus, the code will _sort_ by that checkbox column which does not have a field name and leads to downstream exceptions in the sorting code. The root of the problem is the check:

```
if (!this.sortable || args.defaultPrevented || column.sortable === false) {
    return;
}
```

which explicitly checks if the `column.sortable` property is `false`. This is an issue because the `CheckboxColumnComponent` does not have a `sortable` property and the value is therefore `undefined` which is **not** `false`.

**To Reproduce**

Demo on
https://stackblitz.com/edit/kendo-selectall-checkbox-sorting-repro-n748gb

1. Open the browser console in order to see the error later on
2. Click the select-all checkbox at the top of the grid
3. While the checkbox is still focused, press the ENTER key

**Expected behavior**
Pretty much nothing. Checkbox columns should not be sortable and therefore hitting the ENTER key should do nothing.

**Browser**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
The actual error trace that you can see in the browser console is

```
ERROR TypeError: Cannot read property 'replace' of undefined
    at Object.t.getter (main.js:1)
    at s (main.js:1)
    at eval (main.js:1)
    at Array.map (<anonymous>)
    at Object.t.composeSortDescriptors (main.js:1)
    at Object.t.orderBy (main.js:1)
    at AppComponent.loadProducts (VM1267 app.component.ts:35)
    at AppComponent.sortChange (VM1267 app.component.ts:31)
    at Object.eval [as handleEvent] (AppComponent.html:4)
    at handleEvent (view.ts:138)
```

but as described above, the actual issue happens before that.

**Comment by elca-lan** [comment]
Interesting that I didn't find that issue in my initial search... I should have searched for _symptoms_.

And I do feel like pointing out that my description might be a bit better ;)

**Comment by mbechev** [comment]
Yep, thank you for the time spent investigating the issue further. We will take both reports into account when fixing the issue.

**Comment by karthik2294** [comment]
Can we prevent the checkbox selection on enter key???

**Comment by mbechev** [comment]
Hi @karthik2294,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenario implementations or configurations.
