### ISSUE TITLE
Does Kendo Grid support beforeSelect  Event ?

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#299]
Hi kendo team,

I am running into an issue that I need to add a beforeSelect Event on Kendo Grid to do some form status detection, then set the selection to the grid.  So I am wondering whether kendo grid has this kind of interface? Can I use the SelectionService ? If sure, how to use it ? If not, are there any other workarounds?

**Comment by KirilNN** [comment]
Currently there is no such event. Note that the selection in Grid will go through major overhaul and the version should be ready for the next official release.

**Comment by zhao125787935** [comment]
Thanks Kiril for you very quick response.
Does that mean Grid selection functionality may change? BTW, when will the next version be available?

**Comment by KirilNN** [comment]
The selection functionality will change. The next big release should be ready by the middle of May.

**Comment by KirilNN** [comment]
We are working on it and as soon as it is ready it will be published as part of the Kendo UI Grid npm package.
