### ISSUE TITLE
[Toolbar] the more button has no discernible text

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#2991]
**Describe the bug**
The more button of a responsive Toolbar misses a discernible text.

**To Reproduce**
To see the accessibility issue, please check the example from the following article and use any accessibility tool:
https://www.telerik.com/kendo-angular-ui/components/toolbar/responsive-toolbar/

**Comment by Raisolution** [comment]
Fixed in `v3.2.0`
