### ISSUE TITLE
kendo PDF export Angular 10

### ISSUE THREAD

**Issue by RobertasM** [telerik/kendo-angular#2992]
Upgraded to newest Angular 10 version and now getting error: **ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'bbox' of undefined**. Does kendo PDF export support Angular 10?
Using toBlob function which throws this error.
```
 this.pdfExportComponent.export().then(group => {
     toBlob(group, data => {
         this.pdfData = data;
     });
}),
```

![image](https://user-images.githubusercontent.com/31724417/87067583-f005b480-c21c-11ea-98cd-6adf1394f3c4.png)

**Comment by RobertasM** [comment]
I see that **elementsBoundingBox** function returns undefined when passed elements list are empty and there is no check for returned value if this value is undefined, so it tries to call bbox for undefined returned value.

![image](https://user-images.githubusercontent.com/31724417/87069956-bcc52480-c220-11ea-8fa0-7b1576eb5522.png)
![image](https://user-images.githubusercontent.com/31724417/87070263-33fab880-c221-11ea-964e-6fe56c5c24c4.png)

**Comment by RobertasM** [comment]
I see that when I using newest"@angular-devkit/build-angular": "0.1000.2", it loads webpack:///./node_modules/@progress/kendo-drawing/dist/es2015/html/core.js and this version doesn't work for me.
And when I using older "@angular-devkit/build-angular": "~0.901.11", it loads webpack:///./node_modules/@progress/kendo-drawing/dist/es/html/core.js and this version works fine. 
So looks like it doesn't support newest Angular 10

**Comment by dtopalov** [comment]
Hi @RobertasM,

Both the Drawing and PDFExport packages are working as expected in an Angular 10 project. Based on the provided information it seems the toBlob function is not imported from the expected location. The following syntax is working as expected:

`import { pdf } from '@progress/kendo-drawing';
...
<div class="example-config">
  <button class="k-button" (click)="save(pdfComponent)">
    Save As PDF...
  </button>
</div>

<kendo-pdf-export #pdfComponent
...
save(pdfComponent) {
    pdfComponent.export().then(group => {
      pdf.toBlob(group, data => {
        console.log(data)
          this.data = data;
      });
    });
  }
`

Can you please make sure that you are using the latest versions of our packages, try this suggestion, and if the issue persists, send us an isolated runnable project where the issue can be observed, so we can inspect it further? Thank you in advance.

**Comment by RobertasM** [comment]
Hi @dtopalov 

I'm using latest version of packages and your suggestion for me works, thanks a lot :)

What I see the difference is that with older angular version I was using like this:
```
import { toBlob } from '@progress/kendo-drawing/pdf';

toBlob(group, data => {
     this.pdfData = data;
});
```

So looks like with newest angular version we should use pdf.toBlob() instead of toBlob().

**Comment by dtopalov** [comment]
Hi @RobertasM,

Indeed, nested imports are not working as expected, and instead the `pdf` object should be imported from the kendo-drawing package, and then its properties can be accessed accordingly, or the object can be further destructured like in the following documentation example:

https://www.telerik.com/kendo-angular-ui/components/drawing/pdf-output/
