### ISSUE TITLE
Pop scrolling issue with IE

### ISSUE THREAD

**Issue by hitasheth** [telerik/kendo-angular#2993]
I am using kendo angular popup (kendo-popup) which opens on clicking a div. When I scroll the div moves its position but the position of popup does not change in Internet explorer. It works properly in chrome.  

The popup of kendo dropdownlist works fine too in Internet explorer when scrolled. It is only when I have created a popup which opens on a div, when scrolling div moves but the popup position doesn't move.

Browser

OS: Windows 10
Browser Microsoft Edge
Version 44.18362.449.0
Additional context
"@progress/kendo-angular-buttons": "^5.1.1",
"@progress/kendo-angular-common": "^1.2.1",
"@progress/kendo-angular-dateinputs": "^4.2.2",
"@progress/kendo-angular-dialog": "^4.1.1",
"@progress/kendo-angular-dropdowns": "^4.2.4",
"@progress/kendo-angular-editor": "^1.0.6",
"@progress/kendo-angular-excel-export": "^3.1.3",
"@progress/kendo-angular-grid": "4.6.4",
"@progress/kendo-angular-inputs": "^6.4.0",
"@progress/kendo-angular-intl": "^2.0.0",
"@progress/kendo-angular-l10n": "^2.0.0",
"@progress/kendo-angular-label": "^2.2.0",
"@progress/kendo-angular-layout": "^4.1.5",
"@progress/kendo-angular-pdf-export": "^2.0.3",
"@progress/kendo-angular-popup": "^3.0.0",
"@progress/kendo-angular-progressbar": "0.2.1",
"@progress/kendo-angular-tooltip": "^2.1.2",
"@progress/kendo-angular-treeview": "^4.1.0",
"@progress/kendo-data-query": "^1.5.2",
"@progress/kendo-drawing": "^1.5.12",
"@progress/kendo-theme-bootstrap": "^4.11.0",
"@progress/kendo-theme-default": "4.12.2"

**Comment by mbechev** [comment]
Hi @hitasheth, 

I tried to reproduce the described error in both a Stackblitz demo, and a standalone Angular 10 project, but could not:

https://stackblitz.com/edit/angular-kprzmy?file=app%2Fapp.component.ts

[popup-A10.zip](https://github.com/telerik/kendo-angular/files/4919004/popup-A10.zip)

Can you please modify one of the sample apps above, or send us a similar one where the problem can be reproduced alongside the steps to trigger the error, so we can investigate this further? Thank you in advance.

**Comment by mbechev** [comment]
Hi @hitasheth, 

We are closing the issue due to inactivity, if you send us an isolated runnable project where the problem can be observed, we will inspect it further, and reopen the issue.
