### ISSUE TITLE
[ToolBar] ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#2994]
**Describe the bug**
When `<kendo-popup>` is opened from within `<kendo-toolbar>` and the closed asynchronously, `ExpressionChangedAfterItHasBeenCheckedError` is thrown.

**To Reproduce**
https://stackblitz.com/edit/angular-nyymqa-cwyffz?file=app%2Fcustom-tool.component.ts

1. Click delayed toggle inside the popup.
2. An error is thrown.

**Expected behavior**
The popup should be closed without any errors.

**Browser**
 - OS: all
 - Browser: Chrome

**Comment by dtopalov** [comment]
Fixed in the [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dtopalov** [comment]
The fix is available in v.3.2.1 of the @progress/kendo-angular-toolbar package.
