### ISSUE TITLE
The text cannot be selected (and copied) when readonly mode is enabled.

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#2996]
**Describe the bug**
When **readonly** mode of the Editor is enabled, the text inside cannot be selected and copied. 

The default ```<textarea>``` allows copying in a **readonly** state.

**To Reproduce**
https://stackblitz.com/edit/angular-mmc1fj-gkqyaa?file=app/app.component.ts

**Comment by lexon0011** [comment]
In which release is planed to solve this bug?

**Comment by lexon0011** [comment]
This bug exists now over 2 month. I need now a workaround or a solution!

**Comment by lexon0011** [comment]
Will that be fixed? Otherwise we have to look for an alternative! After waiting 4 months I'm slowly losing my patience!!

**Comment by PetarMetodiev** [comment]
Hi,
I understand this may be frustrating and I am sorry for the caused inconvenience.
The issue turned out to be more complex than initially expected and thus we needed more time to fix it. Nevertheless it is resolved and is in the process of testing. Expect it to be published soon.

**Comment by Raisolution** [comment]
The fix is available in the latest official version of the `kendo-angular-editor` package.
