### ISSUE TITLE
(Grid) Using custom directive to retrieve remote data does not allow to change total count

### ISSUE THREAD

**Issue by egorpavlikhin** [telerik/kendo-angular#2998]
**Describe the bug**
When using server-side data via the recommended method as described here https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/ the `this.grid.totalCount` field is readonly and the grid assumes that the total count is equal to the currently retrieved sets array length. This is obviously incorrect for remotly loaded data and makes custom `DataBindingDirective` or using the grid with remote data source impossible.

**To Reproduce**
Implement a custom directive using official documentation steps https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/ 
Load data from a server that allows pagination by providing `skip` and `take` parameters and returns `totalCount` or similar in reply.

**Expected behavior**
`this.grid.totalCount` should be writeable within a directive to provide accurate total item count as returned by an API.

**Comment by dtopalov** [comment]
Hi @egorpavlikhin,

The [GridDataResult object](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridDataResult/) is the type the Grid expects its data to conform to when the grid is pageable:

https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/#toc-getting-started
