### ISSUE TITLE
Guid util is not exported

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#300]
We are looking for a guid function already present on Kendo UI for JQuery. We have seen that guid function on util class is hidden:

```
/**
 * @hidden
 */
export var guid = function () {
```

Are you going to publish it (maybe on an util package) or we have to implement our guid function by our-self?
so thanks.

**Comment by KirilNN** [comment]
The hidden comment is for the jsDoc generation. The guid function is a standard implementation that you can modify for your requirements.

Currently we are not planing on releasing an util package

**Comment by tsvetomir** [comment]
I'd recommend using the NPM ecosystem for such utilities. For example, [node-uuid](https://www.npmjs.com/package/node-uuid).
Our internal implementations are not necessarily better and are not intended for general use.

**Comment by meriturva** [comment]
Perfect we will use a different implementation. I just asked before add another library. We are trying to decrease our app footprint.

Anyway thanks!
