### ISSUE TITLE
Grid: with, sorting + resize column enabled, sort indicator is hidden

### ISSUE THREAD

**Issue by prabh-62** [telerik/kendo-angular#3001]
**Describe the bug**
Sort indicator should always be visible on the grid
<img width="527" alt="sorting_kendo_arrow_1" src="https://user-images.githubusercontent.com/13006107/87481391-397b4880-c5fd-11ea-930c-640ce809fc41.png">

**To Reproduce**

1. Open the sorting example in stackblitz(https://www.telerik.com/kendo-angular-ui-develop/components/grid/sorting/#toc-setting-the-direction)
2. Add `[resizable]="true"` to the example code
3. Shrink the column until the sort indicator goes missing

**Expected behavior**
<img width="514" alt="sorting_kendo_arrow" src="https://user-images.githubusercontent.com/13006107/87481635-bb6b7180-c5fd-11ea-8195-af599acef4bc.png">

**Screenshots**
<img width="527" alt="sorting_kendo_arrow_1" src="https://user-images.githubusercontent.com/13006107/87481646-bf978f00-c5fd-11ea-934a-a55a39cd821b.png">

**Browser**
 - OS: macOS Catalina
 - Browser: Chrome 84
 - Version: 84

**Comment by dtopalov** [comment]
Hi @prabh-62,

Indeed, this is a known behavior, and an enhancement item is already available in our public Kendo Themes repository that you can track here:

https://github.com/telerik/kendo-themes/issues/410

There are also several CSS workarounds in the comments that might prove useful.
