### ISSUE TITLE
[DropDownButton] the button remains in active state

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3002]
**Describe the bug**
When using the space bar to open/close the DropDownButton then it remains in active state. The active state should be on only when the space bar is pressed, but not when it is released. The behavior should be just as when clicking the button. 

**To Reproduce**
Please check the following example:

https://stackblitz.com/edit/angular-ep9nc6-ingfo8?file=app%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fixed in `v5.5.2`
