### ISSUE TITLE
[Slider] setting the width of the Slider to percentages breaks the layout

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3003]
**Describe the bug**
When the width of the Slider is set to be some percentage value, then if the browser is zoomed or the viewport is resized, the last label will move to a new line.

**To Reproduce**
Please check the following exmaple:
https://stackblitz.com/edit/angular-jgjuah-zvudaj

resize the viewport or zoom the browser

**Comment by dtopalov** [comment]
Note: This happens only when the calculated width of the Slider wrapper happens to be a floating point value (like 229.5) pixels, while the sum of all internal tick (LI) widths exceeds this value due to internal rounding of their size, and the sum of the widths is for example 230px.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dtopalov** [comment]
Available in v.6.7.0
