### ISSUE TITLE
[DropDowns] itemDisabled not working with virtualization

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#3004]
**Describe the bug**
The disabled items functionality is not working correctly with virtualization enabled - the skipped items are not taken into account when evaluating if an item at a specific index should be disabled.

**To Reproduce**
https://stackblitz.com/edit/angular-zsbatd

Only the first five items should be disabled, instead the first five items of each virtual list get disabled.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by gkarapeev** [comment]
Fix available in release v4.3.1
