### ISSUE TITLE
[TreeList] Data property change has no effect

### ISSUE THREAD

**Issue by andrpelz** [telerik/kendo-angular#3008]
**Describe the bug**
I want to change the data list properties for the tree list in my code, but the change has no effect in the tree list view.

**To Reproduce**
Open this [stackblitz sample](https://stackblitz.com/edit/angular-treelist) and click in the 'Change' button.
The button changes the name property of the first item in the data list but not in the tree list view. If you expand or collapse one element in the tree list, the name of the first element is now changed.

**Expected behavior**
If the property name is changed, the changed value should immediately be displayed in the tree list.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

**Comment by dtopalov** [comment]
Hi @andrpelz,

As the data array is a reference type, it needs to be replaced with a new reference/instance for the Angular Change detection mechanism to be able to reflect the change, e.g.:

    this.data = [{...this.data[0], name: 'Change test'}, ...this.data.slice(1)];

https://stackblitz.com/edit/angular-treelist-mxjwpc

**Comment by tsvetomir** [comment]
Another option is to call the [updateView](https://www.telerik.com/kendo-angular-ui/components/treelist/api/TreeListComponent/#toc-updateview) method, [see example](https://stackblitz.com/edit/angular-treelist-au2nrt).

This method is exposed as the TreeList uses OnPush to reduce the number of change detection cycles.

**Comment by andrpelz** [comment]
Many thanks for the help! I will try out the two options.
