### ISSUE TITLE
Grid selection - programmatically select a row

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#301]
Currently there is no way to select a row in the grid programmatically but there should be a method to do that (e.g. keeping to grids in sync).

Also do you know when the multiselect will come out - this is really a basic feature for a grid and is really blocking at the moment.

**Comment by KirilNN** [comment]
The selection will go through a redesign and new more powerful version will be released, that should support multiple selection as well.

**Comment by moxival** [comment]
@KirilNN Do you have an ETA for this redesign, the May release maybe?

**Comment by KirilNN** [comment]
I cannot give you an ETA, but as soon as it is ready it will be released.
