### ISSUE TITLE
[Numeric Text Box] Change 'value' data type to hold big decimal numbers

### ISSUE THREAD

**Issue by krzysztof-zych** [telerik/kendo-angular#3010]
In the current implementation of `NumericTextBoxComponent`, `value` field that's specifying the value of `NumericTextBox` has a [Number](https://www.ecma-international.org/ecma-262/5.1/#sec-8.5) data type.
In our applications, we need to have bigger precision than that data type ensure (e.g. for currency exchange rates) and have to ability to localize (so formatting and parsing numbers) to different languages.
I know that you rejected similar issue #704 some time ago, but maybe after few years later, you changed your mind and now you can provide your implementation of new or changed component that can store very big numbers (e.g using https://github.com/MikeMcl/decimal.js under the hood or suchlike).

Thanks.

**Comment by tsvetomir** [comment]
Thank you for the suggestion. Can you please, add your vote & comments to the existing [feature request for BigInt](https://feedback.telerik.com/kendo-angular-ui/1452731-provide-support-for-bigint)?

It might make sense to merge both requests, provided we have an option to convert from decimal to BigInt.

There's also a [TC39 proposal](https://github.com/tc39/proposal-decimal) for Decimal/BigDecimal. Ideally, we should use a a polyfill based that could eventually be removed. See https://github.com/MikeMcl/bignumber.js/issues/256

**Comment by krzysztof-zych** [comment]
Hi @tsvetomir 
Could you give any estimation of that issue, please? Are you going to support big numbers in your controls in the near future?

Thanks

**Comment by Raisolution** [comment]
Hi @krzysztof-zych ,

at the moment the implementation of this enhancement has not been added to our short term development plans. We will keep tracking the demand for it in the related [feedback portal item](https://feedback.telerik.com/kendo-angular-ui/1452731-provide-support-for-bigint).

**Comment by Raisolution** [comment]
Closing this issue as demand is being tracked in the related [Feedback portal item](https://feedback.telerik.com/kendo-angular-ui/1452731-provide-support-for-bigint).
