### ISSUE TITLE
Angular kendo-excelexport  hide ng-template

### ISSUE THREAD

**Issue by svdeshmukh16** [telerik/kendo-angular#3011]
HI,

I am using the  'kendo-excelexport'  for export  the report.  here I am not able to handle  one scenario in  'kendo-excelexport'.
Please  provide me the  solution for below scenario.
In  'kendo-excelexport-column' I am using multiple 'ng-template'  but here I don't  want to export data form on 'ng-templete'  in some condition   How can we hide this 'ng-template' in kendo-excelexport.

Thanks,

**Comment by dtopalov** [comment]
Hi @svdeshmukh16,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenario implementations or configurations.
