### ISSUE TITLE
[MutliSelect] add an option to add a custom item programmatically

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3013]
**Describe the bug**
Currently there isn't an option that allows to select a custom item programmatically. The only option is to select the item by pressing the "Enter" key. Please provide an option that would allow to add the typed in custom item to the value of the MultiSelect manually. 

**To Reproduce**
https://stackblitz.com/edit/angular-qbbznj?file=app/app.component.ts

**Expected behavior**
A use case scenario would be to add the typed in custom value on blur.

**Comment by yanmariomenev** [comment]
Moved to ur feedback portal - https://feedback.telerik.com/kendo-angular-ui/1619294-introduce-a-feature-that-allows-for-the-programmatic-addition-of-custom-items
