### ISSUE TITLE
format option of the ColorGradient is ignored

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3014]
**Describe the bug**
When setting the [format ](https://www.telerik.com/kendo-angular-ui/components/inputs/api/ColorGradientComponent/#toc-format)option of the ColorGradient component to 'hex', the returned value is in **rgba** format which is the default value.

**To Reproduce**
1. Pick a color

https://stackblitz.com/edit/angular-nwzupq-jy2bzk

**Note**: when the color is changed through the input boxes, the value is returned in the right hex format:
https://screencast-o-matic.com/watch/cYitXYEzdE

**Comment by inikolova** [comment]
Related to https://github.com/telerik/kendo-angular-inputs/issues/378

**Comment by jcocca** [comment]
Still having this issue with "@progress/kendo-angular-inputs": "^7.0.0"

**Comment by Raisolution** [comment]
@jcocca 

we are in the process of redesigning the ColorPicker and ColorGradient components, which will include a fix for this issue too.

**Comment by Raisolution** [comment]
Fix available in `v8.0.0` of the `kendo-angular-inputs` package.
