### ISSUE TITLE
[Grid] it isn't possible to reach the Grid scrollable content with the keyboard

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3017]
**Describe the bug**
Currently, it isn't possible to reach the content of the Grid with the keyboard. That is required when the Grid content is wide enough to display a horizontal scrollbar.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-qutxr4?file=app%2Fproducts.ts

**Expected behavior**
It should be possible to reach the Grid content with the keyboard so that the users can scroll the content with the keyboard. 

**Screenshots**

![image](https://user-images.githubusercontent.com/20015190/88671380-e91ce400-d0ee-11ea-9086-8b7023c50e66.png)

**Comment by Raisolution** [comment]
The recommended solution for this scenario is to enable the `navigable` option of the Grid component.

https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/
