### ISSUE TITLE
[Dialog] The Dialog "X" button misses discernible text

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3019]
**Describe the bug**
In order to comply with the wai aria spec the "X" button of the Dialog should have a discernible text.

**To Reproduce**
Please check the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/

**Workaround**

What could be done in order to avoid this issue is to set a **closeTitle** via the CustomMessages component. Here is an example demonstrating such approach:

https://stackblitz.com/edit/angular-muhrod-umka2p

**Screenshots**
![image](https://user-images.githubusercontent.com/20015190/88673127-e9b67a00-d0f0-11ea-95aa-16a41e49dbe9.png)

**Comment by Raisolution** [comment]
Fix is available in the latest version of the `kendo-angular-dialog` package
https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/
