### ISSUE TITLE
space key can't be used in dropdownlist filter input

### ISSUE THREAD

**Issue by erezepaz** [telerik/kendo-angular#302]
space key can't be used in dropdownlist  filter input.
for example searching 'united states' in country list, is not possible.

http://plnkr.co/edit/zYv0Es5eX9QdjOgY8Oi9?p=preview

**Comment by KirilNN** [comment]
The problem should be fixed in the latest version. Try updating!

**Comment by erezepaz** [comment]
thanks,
just updated to 0.29, and it works like a charm.
looking forward for your complete sets of widgets.
