### ISSUE TITLE
check first parent node programmatically, checks all children nodes in TreeView

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3021]
**Describe the bug**
When checking first parent node programmatically, it checks all children nodes. 
This behavior is observed since [**v4.1.3**](https://www.telerik.com/kendo-angular-ui/components/treeview/changelog/) (_"nested expanded children not checked on parent node expand"_). 

![Capture](https://user-images.githubusercontent.com/33104481/88781833-8e8a9300-d195-11ea-833f-624da693d8a9.PNG)

Using version **4.1.2** works as expected.
![Capture](https://user-images.githubusercontent.com/33104481/88782116-e0cbb400-d195-11ea-859e-8efa5b8e3ee0.PNG)

**To Reproduce**
https://stackblitz.com/edit/angular-ycmxyv?file=app/app.component.ts

**Comment by dimitar-pechev** [comment]
After an internal discussion, we've decided not to change the current behavior. Although it does force a change in the user-defined setup, enabling just the parent to be checked when `checkChildren` is enabled would lead to inconsistent behavior between programmatically defined state and user-interaction state. Furthermore, checking just the parent without its children, when `checkChildren` is set to true, makes no sense from a UX point of view.
