### ISSUE TITLE
WorkbookSheet frozenRows not working when set to 0 or null

### ISSUE THREAD

**Issue by jshin-pdgc** [telerik/kendo-angular#3023]
## I'm submitting a...

* Bug report 

## Current behavior

Setting frozenRows = 0 still sets first row as frozen in the excel export.

## Expected behavior

No rows should be frozen.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-jzvjqb?file=app/app.component.ts

Browser:

- Chrome (desktop) Version 84.0.4147.89 (Official Build) (64-bit)

System:
- TypeScript version: 3.5.3
- Node version: 13.9.0
- Platform:  Windows

**Comment by mbechev** [comment]
Hi @jshin-pdgc,

The first row is frozen by default. Even if omit setting the ```workbook.sheets[0].frozenRows = 0;``` the first row will be pinned.

To unpin the header rows use the freezePane - ```workbook.sheets[0].freezePane = null;```

Here is the updated example:
https://stackblitz.com/edit/angular-jzvjqb-8v7pju?file=app/app.component.ts
