### ISSUE TITLE
[Splitter] keyboard navigation behaves incorrectly in RTL

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3024]
**Describe the bug**
When the split-bar is focused with Tab key, pressing the left arrow key moves the split-bar to the right. The same is valid for the right arrow key  - moves left the split-bar.

**To Reproduce**
1. Focus the split-bar
1. Press left or right arrow key
https://stackblitz.com/edit/angular-angve6?file=app%2Fapp.component.ts

**Comment by slavenai** [comment]
Fixed in `v16.4.0` of `kendo-angular-layout` package.
