### ISSUE TITLE
value is cleared when the Editor is disabled in Template driven form

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3026]
**Describe the bug**
When the Editor is disabled initially in Template-driven form the value is cleared:

![Capture](https://user-images.githubusercontent.com/33104481/89417784-d5e5c600-d737-11ea-932d-9d0024ebf7a6.PNG)

**Note**
The issue is reproduced in the latest Chrome version (84+) and when the **adBlocker** extension is **disabled**

**To Reproduce**
https://stackblitz.com/edit/angular-tcgb7r-d5v3hz?file=app%2Fapp.component.ts

The same scenario works properly in Reactive forms (when the Editor is disabled through the form):
https://stackblitz.com/edit/angular-tcgb7r-rcwkmh?file=app%2Fapp.component.ts

**Comment by Crossfir3** [comment]
:heavy_check_mark: Tested OK in the latest dev version.

**Comment by Raisolution** [comment]
Fix available in `v3.0.1` of the Editor.
