### ISSUE TITLE
'@progress/kendo-angular-pager@0.2.1' is not in the npm registry.

### ISSUE THREAD

**Issue by dvdgutzmann** [telerik/kendo-angular#3027]
When we run `npm install` the command fails with **'@progress/kendo-angular-pager@0.2.1' is not in the npm registry.**

> PS C:\Data2\synfoxx-4.2.11.x\WebApp> npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@progress/kendo-angular-pager/-/kendo-angular-pager-0.2.1.tgz
npm ERR! 404
npm ERR! 404  '@progress/kendo-angular-pager@0.2.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'WebApp'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Entry in package.json :
`"@progress/kendo-angular-pager": "^0.2.1"`

**Comment by tsafadi** [comment]
How can this happen. I have an issue with ```ng add @progress/kendo-angular-inputs```

**Comment by dtopalov** [comment]
There was a global issue with NPM that seems to be already resolved:

https://status.npmjs.org/#past-incidents

Kendo UI for Angular packages are installing as expected now.

**Comment by dvdgutzmann** [comment]
We are able to confirm, the reported issue seems to be resolved indeed.
