### ISSUE TITLE
npm and ng commands broken!!

### ISSUE THREAD

**Issue by tsafadi** [telerik/kendo-angular#3028]
**Describe the bug**
A lot of the npm or ng commands don't work anymore.

**To Reproduce**
ng add @progress/kendo-angular-inputs

**Expected behavior**
The packages should get added.

**Actual behavior**

```
Unable to fetch package metadata: 404 Not Found - GET https://registry.npmjs.org/@progress%2fkendo-angular-inputs - Not found
```

Please fix this bug ASAP, I can't add any packes anymore...

List of errors using npm:

> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@telerik%2fkendo-draggable - Not found
> npm ERR! 404 
> npm ERR! 404  '@telerik/kendo-draggable@^2.0.0' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of '@progress/kendo-angular-common'
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a

**Comment by dtopalov** [comment]
There was a global issue with NPM that seems to be already resolved:

https://status.npmjs.org/#past-incidents

Kendo UI for Angular packages are installing as expected now.
