### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by BhaskaranR** [telerik/kendo-angular#3029]
I am not able to pass kendoAutoCompleteItemTemplate as  [ngTemplateOutlet]. I would want the client to pass in the template and i can read as contentchild

```
<kendo-autocomplete [data]="list">
   <ng-container *ngIf="selectedTemplateRef"
        [ngTemplateOutlet]="selectedTemplateRef || defaultTemplate" 
        [ngTemplateOutletContext]="{ $implicit: let-dataItem }">
    </ng-container>
</kendo-autocomplete>
```
can you suggest if this is possible with an example please?

**Comment by mbechev** [comment]
Hi @BhaskaranR ,

This repository is for bug reports only. Please open a[ support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenario implementations or configurations, or submit feature requests to our [Feedback Portal ](https://feedback.telerik.com/kendo-angular-ui)for any desired enhancements and functionalities that are currently unavailable.
