### ISSUE TITLE
ItemChangedEvent interface of kendo-angular-scrollview package is not exported from the index

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3030]
There is no way to import ItemChangedEvent  interface from the index file. We can import this from `dist/es2015/change-event-args`, which is a bit cumbersome.

https://stackblitz.com/edit/angular-vxb5mx-tbeodl?file=app/app.component.ts

**Comment by Raisolution** [comment]
Released in `v4.0.2` of the `kendo-angular-scrollview` package.
