### ISSUE TITLE
Editor does not work in IE when value is not set

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3032]
**Describe the bug**
When the **value** of the Editor is an empty string (or an empty paragraph - e.g. ```<p></p>```), the component gets irresponsive in IE, throwing the following error:

![issue-editor](https://user-images.githubusercontent.com/33104481/90105305-587d0f80-dd4e-11ea-955d-d1feac905ea1.PNG)

Screencast:
https://screencast-o-matic.com/watch/cYjIitG44H

**To Reproduce**
[editor-issue-IE.zip](https://github.com/telerik/kendo-angular/files/5067671/editor-issue-IE.zip)

1. Run npm install command in the root folder
1. Run ng serve 
1. Open the project in IE browser

**Note**

Using Editor in a form, trying to delete the content we can notice that the value is not completely removed, check the screencast:

https://screenrec.com/share/souJ78t9Dz

**Comment by ABartkoviak** [comment]
Hi. 
I've run in same issue. Is there any updates or workarounds?

**Comment by mbechev** [comment]
The issue is fixed in the latest Editor version (v**2.0.1**)
