### ISSUE TITLE
[TreeList] Method scrollTo works only with virtual scrolling

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3035]
**Describe the bug**
KendoTreelist API method scrollTo is not working in case of non virtual scroll.  

**To Reproduce**
Please try it here https://stackblitz.com/edit/angular-vphzhf?file=app/app.component.ts
If [scrollable] is changed to "'virtual'" it works fine.

**Expected behavior**
It should work in case of non-virtual too..

**Additional context**

<!--
  For local projects, paste the output from `npm ls --depth 0` below.
  Omit this step if the problem is reproducible on our demo site.

  Be sure to wrap the output in a code block, for example:
  ```
broken in v1.0.5-dev.202007160924
  ```

**Comment by schmik** [comment]
We need this to be fixed. Not being able to scroll to items that are not rendered yet: made us consider switching to scrollable/non-virtual. We cannot. Please fix

**Comment by ywei390** [comment]
any update on this fix?

**Comment by slavenai** [comment]
Fixed in `v17.0.0`.
