### ISSUE TITLE
Browser freezes when opening k-dropdown inside k-dialog

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#304]
- Open **[Plunker](http://plnkr.co/edit/EcxcGuCQsLPrXICSjixZ?p=preview)**
- Resize your browser window, so that the DropDown-Popup would go outside the boundaries of the window when opened.
- Open the Popup
- Browser freezes (chrome + firefox)

**Tested on:**
- Chrome 56.0.2924.87 (freezes)
![plunkr_chrome](https://cloud.githubusercontent.com/assets/21359517/22966612/3dd4b3a0-f363-11e6-86fa-590995d5971b.png)

- Firefox 48.0.2 (script not responding)
![plunkr_firefox](https://cloud.githubusercontent.com/assets/21359517/22966709/ba734dd6-f363-11e6-9bfb-6d339093b11b.png)

- IE 11 (works fine)
![plunkr_ie](https://cloud.githubusercontent.com/assets/21359517/22966714/bf4b2680-f363-11e6-9152-166dc31e71ad.png)

**Comment by ggkrustev** [comment]
@simon11196, nice catch! This definitely is a bug in the Popup component. The component tries to reposition due to the boundary detection, but for some reason falls into infinite loop. 
Will investigate the case further and update the thread with more information.

**Comment by zhao125787935** [comment]
hi @ggkrustev 
I ran into the same issue, I wrapped a datepicker with kendo calendar and input box,  calendar is placed inside a popup. When I tried to open the calendar, it freezes.

**Comment by RobyCresta** [comment]
Hi! Do you know when the bug fix will be released? 
Thanks

**Comment by ggkrustev** [comment]
Hi @RobyCresta, the issue was closed 5days ago with a fix. The latest version of the pop up should be OK. 
Did you try to install v0.16.4?
