### ISSUE TITLE
[MultiSelect] setting placeholder broke filtering input in IE

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3040]
**Describe the bug**
Setting the [placeholder ](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/MultiSelectComponent/#toc-placeholder)property of the MultiSelect component causes issues when trying to filter the component items.

See screencast:
https://screencast-o-matic.com/watch/cYjYQDmh2B

**To Reproduce**
1. Click the MultiSelect input
1. The cursor should appear
[multiselect-IE.zip](https://github.com/telerik/kendo-angular/files/5101964/multiselect-IE.zip)

**Note:** often the cursor is out of the component (as shown in the screencast)

**Comment by juanslinger** [comment]
Hi!

Some days ago we migrated to Angular 10 along with the latest versions from the kendo libraries we are currently using. The migration went smoothly as expected, so thanks for all your work 👍 .

However, I'm still seeing the multiselect component with a placeholder in IE11 is not working properly.

Do you have any estimation of when are you going to be able to address that issue?

**Comment by prayinforsunshine** [comment]
> Hi!
> 
> Some days ago we migrated to Angular 10 along with the latest versions from the kendo libraries we are currently using. The migration went smoothly as expected, so thanks for all your work 👍 .
> 
> However, I'm still seeing the multiselect component with a placeholder in IE11 is not working properly.
> 
> Do you have any estimation of when are you going to be able to address that issue?

Thanks for bringing this up - this is impacting us also.

**Comment by svetq** [comment]
Closing this as IE is no longer supported by Kendo UI for Angular.
