### ISSUE TITLE
[Responsive Toolbar] Overflow popup button is not focusable when all tools are inside the overflow popup

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#3042]
**Describe the bug**
The overflow popup button(the three dots) cannot be focused with the keyboard when the width of the toolbar is short enough so all tools are inside the overflow popup.

**To Reproduce**
https://stackblitz.com/edit/angular-nwxqwo?file=app/app.component.ts

1. Click on the input.
2. Press <kbd>Tab</kbd>.
3. Focus is lost.

**Expected behavior**
The overflow popup button should receive focus.

**Comment by Raisolution** [comment]
The issue has been addressed in the latest `kendo-angular-editor` version.
