### ISSUE TITLE
[Fileselect] FormControl remains valid if one out of several files violates validation restrictions

### ISSUE THREAD

**Issue by gkarapeev** [telerik/kendo-angular#3044]
**Describe the bug**
If one **out of several** selected files violates the **restrictions** of a kendo-fileselect, the related formControl remains valid.

**To Reproduce**
1. Use a kendo-fileselect component in a form.
2. Set its [multiple] property to "true".
3. Set the kendo-fileselect [restrictions] property to the following object:
```
{
    allowedExtensions: [".jpg"],
    maxFileSize: 350000 // 350kb
}
```
4. As a first file, select an image which is valid.
5. Select a second file. This time pick an image which isn't **.jpg** or one that's above the maxFileSize.

**Current behavior**
The form remains valid although one of the selected files violates the restrictions.

**Stackblitz demo that reproduces the bug**
https://stackblitz.com/edit/angular-8xhk5e-l6nynk?file=app/app.component.ts (ctrl + click to open in new tab)

**Expected behavior**
The form and the control become invalid as soon as any of the selected files violates the restrictions.

**Screenshots**
<img width="514" alt="restrictions bug" src="https://user-images.githubusercontent.com/45083324/91161156-0c798580-e6d3-11ea-86c5-3be9bac81f56.png">

**Browser**
 - OS: macOS Mojave 10.14.6
 - Browser: Google Chrome
 - Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by Raisolution** [comment]
Current behavior is by design - the invalid file is not added to the form value. Only the first one is present there thus the required validation is passed and the form remains valid. Documentation on the topic is available here:
https://www.telerik.com/kendo-angular-ui/components/uploads/fileselect/restrictions/#toc-file-restrictions
