### ISSUE TITLE
Sum aggregate not working correctly when field value is undefined

### ISSUE THREAD

**Issue by jvalkeejarvi** [telerik/kendo-angular#3045]
When using `aggregateBy` function from `kendo-data-query` package, sum aggregate is left null with following data and aggregateDescriptors:
```typescript
const dataWithMissingChild = [
  { a: 1, b: 2 },
  { a: 1, b: 2 },
  { a: undefined, b: 2 },
  { a: 1, b: 2 },
];

const descriptors: AggregateDescriptor[] = [{ field: 'a', aggregate: 'sum' }];
```

If I change third data row so that, value of `a` is null, sum aggregate works. Shouldn't missing property/undefined value be treated similarly as null value?

**To Reproduce**
https://stackblitz.com/github/jvalkeejarvi/kendo-aggregate-repro

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of @progress/kendo-data-query.
