### ISSUE TITLE
Editor font size tool selection disappears

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3046]
**Describe the bug**
Selected font size disappears from the dropdown tool once the cursor selects another text. 

The functionality is not affected and the correct font size is applied.

**To Reproduce**
1. Select text
1. Open font size tool and select a size
1. Select another text
1. Notice that when the cursor is back to the text with the applied font size, the size is not shown in the dropdown
https://stackblitz.com/edit/angular-qjmisn-brvekf?file=app/app.component.ts

**Expected behavior**
To behave as the other dropdown tools (such as font-family tool.)

**Comment by MLefebvreICO** [comment]
We have the same issue on our side. This is a bit annoying considering it worked in kendo for jQuery and it seems to work also in the kendo for React codebase.

**Comment by Raisolution** [comment]
Fix available in `v4.1.0` of the Editor package.
