### ISSUE TITLE
[Responsive ToolBar]Overflow popup button is not focusable when all tools in the toolbar are disabled

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#3047]
**Describe the bug**
When all tools inside the toolbar are disabled and overflow popup button is visible, it is not possible to focus the overflow popup button with the keyboard.

**To Reproduce**
https://stackblitz.com/edit/angular-nwxqwo-xh6djt?file=app/app.component.ts
1. Click inside inside the input.
2. Press <kbd>Tab</kbd>.
3. Focus is lost.

**Expected behavior**
Overflow popup button should be focused.

**Comment by Raisolution** [comment]
FIx is available in `v4.1.2`
