### ISSUE TITLE
Keyboard remains opened on iOS devices

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3048]
**Describe the bug**
The keyboard of an iOS devices remains opened as:
- TextBox
- TextArea
- NumericTextBox
- MaskedTextBox

components are not blurred when the user clicks outside the component.

![tempsnip](https://user-images.githubusercontent.com/33104481/91431795-90657600-e869-11ea-91ea-2051dbf7c5a5.png)

**To Reproduce**
1. Click inside the input (keyboard is shown)
1. Click outside the input (the keyboard should be hidden)

https://stackblitz.com/edit/angular-wshs4a?file=app/app.component.ts

**Comment by Raisolution** [comment]
Not reproducible with the latest version of the Inputs package (currently v9.0.0).
