### ISSUE TITLE
unmet peer dependency problem after update kendo-angular package

### ISSUE THREAD

**Issue by tejasdhimmar** [telerik/kendo-angular#305]
Whenever I run the following command from command prompt in my project file location
npm install --save @progress/kendo-angular-inputs
it gives me the following error in command prompt

	unmet peer dependency @progress/kendo-angular-intl@0.7.4
	unmet peer dependency angular@1.6.2 extraneous
	unmet peer dependency angular-animate@1.6.2 extraneous
	unmet peer dependency angular-aria@>=1.3 <1.6
	unmet peer dependency rxjs@5.1.0
How can this remove?

**Comment by tsvetomir** [comment]
The **@progress/kendo-angular-intl** dependency should be fixed. Not sure about where the rest are coming from.
