### ISSUE TITLE
Cmd key cannot select multiple rows in TreeList using macOS

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3050]
**Describe the bug**
Holding the <kbd>Cmd</kbd> key on macOS does not add rows to the selected collection (comparing it to the Grid [selection functionality](https://stackblitz.com/edit/angular-mjbreu?file=app/app.component.ts)). Instead, it behaves as a single selection.

The <kbd>Ctrl</kbd> key works as expected. 

**To Reproduce**
1. Click any row
1. Hold the <kbd>Cmd</kbd> 
1. Select another row
https://stackblitz.com/edit/angular-5ktpa5?file=app/app.component.ts

**Comment by Raisolution** [comment]
Fix available in `v3.1.1`
