### ISSUE TITLE
Input in panelBar custom title template not keeping focus

### ISSUE THREAD

**Issue by sevspo** [telerik/kendo-angular#3051]
**Input in panelBar custom title template using the "kendoPanelBarItemTitle" directive is not keeping focus**
So the input is not editable for the user

**Stackblitz**
Check out this example on stackblitz
[Stackblitz](https://stackblitz.com/edit/angular-ymyzvy?file=app/app.component.ts)

**Screenshot**
![image](https://user-images.githubusercontent.com/17132540/91957022-c8573800-ed05-11ea-83f3-d551bc8f25a9.png)

**Expected behavior**
The Input should be editable to give the panel group a name

**Browser**
 Chrome 85

**Additional context**
"@angular/core": "~9.1.3"
"@progress/kendo-angular-layout": "^5.0.3"

**Comment by Raisolution** [comment]
Fix available in `v6.1.6`
