### ISSUE TITLE
[Editor] Error when using *ngIf and reactive forms

### ISSUE THREAD

**Issue by PetarMetodiev** [telerik/kendo-angular#3054]
**Describe the bug**
When the Editor is part of a reactive form and toggled using `*ngIf`, setting value through the Reactive Forms API throws an error.

**To Reproduce**
https://stackblitz.com/edit/angular-fuqbew-r7pauw?file=app/app.component.ts
1. Click "Switch editor visibility" twice.
2. Click "Set formControl value".
3. The Editor value is not updated and an error is thrown.

**Expected behavior**
The value of the Editor should be updated and no errors should be thrown.

**Comment by SuhasParameshwara** [comment]
Hi Team,
Any updates on this issue?
@PetarMetodiev Did you find any workaround to solve this issue?

**Comment by mbechev** [comment]
Hi @SuhasParameshwara,

Up to now, we haven't added this issue to our development plans.

**Comment by dtopalov** [comment]
Seems to be an issue related to iframes in Chrome - the error is not observed in FireFox. Setting `iframe` to `false` resolves the problem and can be used as a workaround until a fix is released.

Closing this as a duplicate of https://github.com/telerik/kendo-angular/issues/2908

**Comment by dtopalov** [comment]
Fixed in the latest dev version of the Editor package.
