### ISSUE TITLE
Dynamic add component on detail template of master-detail grid mode

### ISSUE THREAD

**Issue by laughinglee** [telerik/kendo-angular#3056]
**Describe the bug**
Need to present different components as a detail component in Kendo grid master-detail mode. However, the component factory provided by Angular does not display the components correctly(no errors and nothing are shown).

**To Reproduce**
https://stackblitz.com/edit/angular-fpjfsh

**Expected behavior**
Components can be present on expanded detail part.

**Browser**
 - OS: Windows 10
 - Browser Chrome

**Comment by dimitar-pechev** [comment]
The code doesn't throw as the `*kendoGridDetailTemplate` is missing the asterix prefix in your example. Not sure what you are trying to achieve by overriding the behavior of a structural directive but it could be expected that it won't work. Even if you capture the vcr reference correctly, you will be trying to add content to an existing template that is not yet rendered. 

Won't using ngIf-ed content inside the template work for you?

```
<ng-template *kendoGridDetailTemplate>
    <content *ngIf="condition"></content>
    <other-content *ngIf="!condition"></other-content>
</ng-template>
```

Closing the ticket as this looks like a misuse of the component. If I'm missing something, please do elaborate and we could reopen the thread if deemed necessary.

In any case, this looks more fitting for a [support ticket](https://www.telerik.com/account/support-tickets), where you can get help implementing your custom scenario. Thank you for your understanding.
