### ISSUE TITLE
[Editor] Shift+Enter does not move visually the cursor on the next line in FF

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#3057]
**Describe the bug**
When you use the Shift+Enter to add a simple new line (not paragraph) the cursor in FF (version 80) stays on the same line, but in fact in the HTML there is a new line added. If you start typing the newly typed text moves on to the next line. 

The same thing works fine in Chrome

**To Reproduce**
https://stackblitz.com/edit/angular-rn9ubr?file=app/app.component.ts
1. Enter "test" 
2. Press Shift+Enter -> Cursor remains on the test line

**Expected behavior**
The cursor should move on the next line, otherwise user is mislead that there is no new line and adds another one. 

**Browser**
 - OS: Windows 10
 - Browser FF
 - Version 80

**Additional context**
When I test the same thing on ProseMirror (what the editor uses in the back) it works as expected.

**Comment by dtopalov** [comment]
The issue is fixed in the latest versions of the **@progress/kendo-angular-editor** package.
