### ISSUE TITLE
Delay on DropDownList not working when filtering

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#306]
I do not know if this should work, but I set filterable to true and delay to 2000. I expect that filterChange is executed after 2000ms, but it executed immediately. 
I am trying to delay request to the server for new (filtered) items. I also try to find solution on [SO](http://stackoverflow.com/questions/42249771/delay-subscriptions-for-http-request-angular2) when I found [delay](http://www.telerik.com/kendo-angular-ui/components/dropdowns/api/DropDownListComponent/#toc-delay) property.

[Plunkr](http://plnkr.co/edit/DAbhTK79hHvnE1YThML0?p=preview).

**Comment by ggkrustev** [comment]
Hi @MaklaCof,
the `delay` property works only with the search functionality, which basically highlights an item based on typed text, e.g. 'c' highlights 'Chai'. The search functionality is pretty similar to the item loop in the HTML Select element. The `delay` option will reset the typed text after the defined milliseconds. If `[delay]="2000"`, then the user has 2 seconds, before its virtually typed text is cleared.

As to the specific question, the best place to implement filtration delay is the `filterChange` event callback. The concept is pretty simple:
- the user types something
- the event is raised
- the developer decides how and when to update the components data property

**Comment by KirilNN** [comment]
For filtering you can implement it by creating an Observable from the source data, that will handle the filtering of the values after the desired delay like this:

```
   Observable.from([this.source])
        .delay(2000)
        .map((data) =>  data.filter(s => s.text.toLowerCase().indexOf(value.toLowerCase()) !== -1)))
        .subscribe(x => this.data = x);
```

then you can convert the filter event to a stream, that you can `switchMap` to the filtering observable. This will give us the opportunity to cancel the previous filters within the delay and work with the latest one only.

Check [this](http://plnkr.co/edit/bX3kraSTl2DwLbgT2mta?p=preview) plunkr for a working demo.
