### ISSUE TITLE
noteTextField overlaps kendo-chart-title 

### ISSUE THREAD

**Issue by beyerl** [telerik/kendo-angular#3060]
## I'm submitting a...

* Bug report 

## Current behavior

When the noteTextField-property is used on a colum kendo-chart-series-item ina kendo-chart with a kendo-chart-title, the marker overlaps the title for some values. 

## Expected behavior

The y axis values should be expanded properly to keep the noteTextField from overlapping.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-49ldvu

## Environment

Browser:

- Chrome (desktop) version 85.0.4183.102
- Firefox version 80.0.1

System:
See Stackblitz

**Comment by mbechev** [comment]
Hi @beyerl,

The developer can change the Chart title position, by using [padding ](https://www.telerik.com/kendo-angular-ui/components/charts/api/TitleComponent/#toc-padding), [margin ](https://www.telerik.com/kendo-angular-ui/components/charts/api/TitleComponent/#toc-margin) or [position ](https://www.telerik.com/kendo-angular-ui/components/charts/api/TitleComponent/#toc-position)properties:

```html
  <kendo-chart>
      <kendo-chart-title
        text="Note Formating Bug with overlapping Title"
        [padding]="{ bottom: 25 }"
      ></kendo-chart-title>
       ...
    </kendo-chart>
```
Here is an updated example:
https://stackblitz.com/edit/angular-49ldvu-jbea9z

**Comment by beyerl** [comment]
Thank you for your help. But this would only work, if the date contained in the noteTextField are known. We are developing an analytics dashboard with date for various different customers retrieved from the server. There's quite a range of possible values, which need to be displayed in the chart. If we just add a margin, it will look problematic, if there are only zero values inside the chart: The margin will apear much to large. If we don't use a margin, the markers will overlap. We could of course calculate the margin dynamically, base on the data we provide. But that seems hacky. It's a lot cleaner, if the component properly calculates the needed length of the axis based on the data provided and just makes the axis longer so that the markers do not overlap in any case. I would like to request that feature.

**Comment by mbechev** [comment]
Hi @beyerl,

Indeed this repo is for bug reports only. I will recommend exploring our [Feedback Portal,](https://feedback.telerik.com/kendo-angular-ui) where users can log feature requests, and based on the demand (votes) we will prioritize our roadmap accordingly.

Meanwhile, adjust the margin/padding option value suggested above, according to the project requirements.
