### ISSUE TITLE
kendo-combobox input field still editable when set to allowCustom=false

### ISSUE THREAD

**Issue by beyerl** [telerik/kendo-angular#3061]
## I'm submitting a...

* Bug report 

## Current behavior

See minimal reproduction

## Expected behavior

I would expect the combobox not to be editable at all, if allowCustom is set to false. I've been able to implement this behavior with a js hack, but that's certainly not what I actually want to have in my codebase:

// Kendo Komboboxes no not disallow input of custom values, even if [allowCustom] ist set to false. If the Value typed in is not included int he dropdown, 
// the combobox is set to empty and returns undefined. To prevent, that the input bos is editable at all, the readonly attribute is set on it whith this js hack.
kendoComboboxBugfix() {
	const comboboxes = document.getElementsByClassName("k-combobox")
	for (const index in comboboxes) {
		// filter out value "length" for index, which is strangely returned when iterating over comboboxes
		if (!isNaN(Number(index))) {
			const inputs = comboboxes[index].getElementsByClassName("k-input");
			(inputs[0] as HTMLInputElement).readOnly = true
		}
	}
}

## Environment

Package versions:

```

```
See Stackblitz

Browser:

- Chrome (desktop) version 85.0.4183.102
- Firefox version 80.0.1

System:
- Windows 10

**Comment by dimitar-pechev** [comment]
The [`allowCustom`](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/) prop specifies whether the component will accept or reject custom values. If set to `false`, it will accept only values, specified in the data set. That said, it doesn't mean the input should not be editable - it still serves the purpose of a filter input.

Either set the [`readonly`](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/ComboBoxComponent/#toc-loading) prop of the **ComboBox** to `true` to fully prevent changes in value, or use a **DropDownList**, which works only with predefiend values and doesn't hold an input in its wrapper element.
