### ISSUE TITLE
[Scheduler] Recurrence "End On" date is a day after the selected date

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3063]
**Describe the bug**
When editing the event series Recurrence "End On" date to a specific day and save these changes. If any of the edited events is opened afterwards then the Recurrence  "End on" date will be a day later than the selected one. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-niog8n-eldomz?file=app%2Fapp.component.ts

1. Edit the series from the example and set Recurrence End date to Sep 9th.
2. Save the changes.
3. Edit the series again and see that the Recurrence End date is Sep 10th.

**Screenshots**

**Comment by tsvetomir** [comment]
To add, this also means that creating a new all-day event and setting it's recurrence end date to be the same as the start date results in an extra occurrence. This is the scenario from #2463, but can also be reproduced easily in the demos without involving any time zone magic:

1. Go to the [Editing example](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-directives/)
1. Create a new all-day event by double-clicking on the all-day row.
1. Set the event to repeat until a given date which the same as the start date (default).

The editor should look like this:
![image](https://user-images.githubusercontent.com/247917/94525619-011efa00-023d-11eb-82d9-1137108a09d7.png)

Notice that the event appears twice:
![image](https://user-images.githubusercontent.com/247917/94525803-4cd1a380-023d-11eb-907d-d03bf1e3ab2b.png)

The [KUI/jQuery Scheduler](https://demos.telerik.com/kendo-ui/scheduler/index) solves this by subtracting 1 second from the recurrence end date. We should consider our options here, but this seems like a viable solution. cc @Raisolution

**Comment by svetq** [comment]
also reported in private support thread 1552915

**Comment by JakubHolovsky** [comment]
I can confirm that this is still an issue.

**Comment by nileshzala005** [comment]
Facing the same issue with weekly recurrence events.

**Comment by yanmariomenev** [comment]
Recently reported in our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1657303-scheduler-some-events-are-incorrectly-duplicated-despite-the-rules-written-on-them
