### ISSUE TITLE
[Grid] v4.8.0 introduces a bug with row selection

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3064]
**Describe the bug**
Once I updated to `@progress/kendo-angular-grid@4.8.0` I noticed that my Grid selection feature stop working. I have created a simple repo demonstrates the issue. I found out that setting selectable option as an accessor property causes the issue. The workaround is to set your selectable settings as a data property in a component constructor. The issue doesn't present in version `~4.7.0`.

**To Reproduce**
1. Clone https://github.com/destus90/kendo-grid-issue or see online IDE https://stackblitz.com/edit/angular-qhr4za?file=app/app.component.ts
2. Run npm ci & ng serve
3. Try to select any row. Nothing happens.

**Expected behavior**
The selected row should display in the Grid.

**Comment by dtopalov** [comment]
Fixed in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the `kendo-angular-grid` package.

**Comment by dtopalov** [comment]
Fixed in v.4.8.1 of the @progress/kendo-angular-grid package.
