### ISSUE TITLE
[Grid] SelectAll checkbox not working beside an Angular Material CDK Overlay

### ISSUE THREAD

**Issue by gkarapeev** [telerik/kendo-angular#3065]
**Description**
SelectAll checkbox in a grid does not function when an Angular Material CDK Overlay is activated on the same page.
Behaviour is observed with **Angular 10.1.2**, **kendo-angular-grid 4.8.0**, & **Angular Material 10.2.1**.

Example: [StackBlitz demo](https://stackblitz.com/edit/angular-8n7ku2-gbvtqq?file=app/app.component.ts)

The overlay [attaches an event listener to **document.body**](https://github.com/angular/components/blob/c21c6f5d4dca49fc3c62daec726a7b9e64599b13/src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts#L42), which triggers change detection and prevents the checkbox from functioning correctly.

As demonstrated [in this example](https://stackblitz.com/edit/select-all-grid-rows-in-dialog?file=app/app.component.ts), opening the dialog outside the NgZone fixes the issue.

**To Reproduce**
1. Open the [demo](https://stackblitz.com/edit/angular-8n7ku2-gbvtqq?file=app/app.component.ts)
2. Click "open dialog"
3. Try using the SelectAll checkbox

Alternatively, download [this repo](https://github.com/telerik/kendo-angular/files/5246442/grid-selectall-checkbox-bug.zip) locally and run npm install.

**Expected behavior**
The SelectAll checkbox should always be able to select all rows.

**Screenshots**
![image](https://user-images.githubusercontent.com/45083324/93614297-9cf96c00-f9da-11ea-981c-59ab0ec37dd5.png)

**Related issue**: https://github.com/telerik/kendo-angular/issues/2883

**System details** (not essential, should be reproducible on any system)
 - OS: MacOs Mojave 10.14.6
 - Browser: Chrome
 - Version 85.0.4183.102

**Comment by Raisolution** [comment]
Documented as part of the [Grid Troubleshooting Article](https://www.telerik.com/kendo-angular-ui-develop/components/grid/troubleshooting/#toc-selectall-checkbox-is-not-working-beside-angular-material-cdk-overlay).
