### ISSUE TITLE
[TextBox] selectOnFocus is not working when TextBox is readonly

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3069]
The text in the TextBox component is not selected when the component is focused in **readonly** mode.

**To Reproduce**
1. Focus component
1. The text needs to be selected

https://stackblitz.com/edit/angular-g7vsra?file=app/app.component.ts

**Comment by preslavapetrova1** [comment]
Fixed in v6.7.3 of the @progress/kendo-angular-inputs package.
