### ISSUE TITLE
GroupHeaderTemplate styling does not get applied

### ISSUE THREAD

**Issue by CATltd** [telerik/kendo-angular#307]
Hi,
We've been trying to customise a Kendo Grid group header and it doesn't seem to get applied.  We've tried the example below with Plunker but it seems to always keep the default styling. 

http://www.telerik.com/kendo-angular-ui/components/grid/api/GroupHeaderTemplateDirective/#
http://plnkr.co/edit/OvqUT9Gk0f7ADGGrhTZI?p=preview

**Comment by rkonstantinov** [comment]
I agree that the example is not that appropriate as the font-weight is carried by the wrapper element. However, you should be able to apply other styling. For example ```<strong style="color: red">{{field}}</strong>: {{value}}``` should work.
