### ISSUE TITLE
Does Kendo Grid Detail Row Template support generic nesting?

### ISSUE THREAD

**Issue by asadw1** [telerik/kendo-angular#3072]
Is there any support for dynamically nesting multiple kendo grids within each other without hardcoding ng-template? Below is three levels of nesting and some bloat is already there. What if I want to go 10 levels deep? 

`
```
<kendo-grid>
  <kendo-grid-column field="ProductID" title="ID" width="40"></kendo-grid-column>
  <ng-template kendoGridDetailTemplate let-dataItem>
    <kendo-grid>
      <kendo-grid-column field="ProductID" title="ID" width="40"></kendo-grid-column>
      <ng-template kendoGridDetailTemplate let-dataItem>
        <kendo-grid>
          <kendo-grid-column field="ProductID" title="ID" width="40"></kendo-grid-column>
          <ng-template kendoGridDetailTemplate let-dataItem>
          </ng-template>
        </kendo-grid>
      </ng-template>
    </kendo-grid>
  </ng-template>
</kendo-grid>
```
`

**Comment by Raisolution** [comment]
Hi @asadw1 ,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
