### ISSUE TITLE
Make conversation ui buttons customizable

### ISSUE THREAD

**Issue by blakazulu** [telerik/kendo-angular#3074]
### I'm submitting a Suggestion for improvement

We have no way to add one or several buttons next to the send message button

### Expected behavior
Be able to customize the send message button group

### What is the motivation or use case for changing the behavior?
A conversation have more than just text message. We need a way to add buttons for file/image/video selection, emoji selection, restart conversation, like button, setting ... All those button should reside next to the send button.

**Comment by preslavapetrova1** [comment]
The demand for this enhancement will be tracked in the Feedback portal: https://feedback.telerik.com/kendo-angular-ui/1544217-conversational-ui-provide-option-for-adding-custom-buttons
