### ISSUE TITLE
Cannot replace penultimate item in sortable component

### ISSUE THREAD

**Issue by sodaDreamer** [telerik/kendo-angular#3075]
**Describe the bug**
I'm trying to replace items in a SortableComponent by removing with _removeDataItem_ and then re-adding via _addDataItem_ to the same item index. This is necessary for me because the performance impact of replacing the entire array is too high. This works for all cases except for when trying to replace the penultimate item. In this scenario the item ends up jumping to the end.

**To Reproduce**
https://stackblitz.com/edit/angular-cv337b

**Expected behavior**
In the example above, when clicking "Replace Item 7", "Item 7" should simply change to "New Item 7". Instead it jumps to the end of the list. This does not happen when adding/removing any other item.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85

**Comment by sodaDreamer** [comment]
I've just realised the problem can be simplified by taking removeDataItem out of the equation. The problem is simply that you cannot insert an item immediately before the last item - it gets placed after the last item instead.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by tapopov** [comment]
Fixed in `kendo-angular-sortable@v4.0.3`
