### ISSUE TITLE
[NumericTextBox] does not have an inputmode="numeric" attribute or support changing it

### ISSUE THREAD

**Issue by gkarapeev** [telerik/kendo-angular#3076]
The <input> element generated by the NumericTextBox component, does not include an **[inputmode](https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/)** attribute.

The attribute is useful for mobile views because it can invoke a numerical keyboard and make it easier for the user to interact.

A default value of "numeric" can be added if doesn't introduce any problems. Allowing our users to change it could also be a good option. Other possible values can be seen [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode).

Reported in support tickets: 1486073, 1493791

**Comment by yanmariomenev** [comment]
The feature request with the addition of other components is now logged in our Feedback Portal:

https://feedback.telerik.com/kendo-angular-ui/1541664-providing-an-option-to-set-inputmode-in-components-that-use-numeric-input-values
