### ISSUE TITLE
Grid paging breaks when no results are returned.

### ISSUE THREAD

**Issue by shammill-q** [telerik/kendo-angular#308]
If no result set is returned the next/last page buttons are still enabled. Additionally, the text reads "1 - 0 of 0 items" when it should perhaps display "0 - 0 of 0 items"
The user can still press the buttons, which in turn enables the previous/first page buttons as well.

If the user presses the last page button, they can press the previous page button an infinite number of times, sending the counter into the negatives (-149 - -140 of 0 items)

Here is a working reproduction:
http://plnkr.co/edit/whpxDhbz5T746CnQ9eJs?p=preview

**Comment by rkonstantinov** [comment]
This should be fixed with v0.16.2 of the kendo-angular-grid package
