### ISSUE TITLE
Select all checkbox does not behave correctly in TreeList

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3080]
**Describe the bug**

When _Select All_ checkbox is checked and all items are selected, deselecting a row does not update the state of the select all checkbox to **indeterminate** (or unchecked) state.

**To Reproduce**
1. Select all rows
1. Deselect a row
1. Checkbox header remain checked (it should be unchecked or indeterminate state)

https://stackblitz.com/edit/angular-hp972o?file=app/app.component.ts

Reported in a private support ticket: **1486730**

**Comment by DeepakMohanSingh** [comment]
Hi team. Any update on this?

**Comment by georgi-sla** [comment]
A similar issue is also observed in the [Checkbox Selection of Child Rows](https://www.telerik.com/kendo-angular-ui/components/treelist/selection/#toc-checkbox-selection-of-child-rows) functionality - when selecting the parent row, the children rows are being correctly selected; when deselecting one of the children rows, the state of the checkbox next to the parent row does not change.

**Comment by leopardy** [comment]
Are there updates on this? It appears to still be happening in the latest kendo angular treelist.

**Comment by slavenai** [comment]
Fixed in `v17.1.0`
