### ISSUE TITLE
[DropDowns] Allow user to focus an item programatically

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3081]
**Reported Bug**
When an AutoComplete component has a predefined value and its popup is opened when is focused (using toggle method), the item is not highlighted.

**To Reproduce**
https://stackblitz.com/edit/angular-6lkuri-hdugwq?file=app/app.component.ts

**Suggested Enhancement**
After team discussion and comparison with other Angular components libraries, we agreed that the default behaviour for the AutoComplete component should not be changed. However, since there have been other client requests for similar changes it might be a good idea to implement a more general solution for the entire dropdowns package by exposing a way for the user to be able to highlight an item programatically when desired.

**Components**
- [x] Autocomplete
- [x] Dropdownlist
- [x] Combobox/MCCB
- [x] Multiselect
- [x] DropDownTree

**Comment by ipeshev** [comment]
Feature available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by svetq** [comment]
Available in the official v`5.2.0` of the @progress/kendo-angular-dropdowns package.

The functionality should be implemented for the DropDownTree as well.

**Comment by ipeshev** [comment]
Feature available for DropDownTree in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).
