### ISSUE TITLE
Quick Question Regarding support of  Gantt component on angular 10

### ISSUE THREAD

**Issue by Dhananjay48** [telerik/kendo-angular#3082]
As i saw that in angular Js and in jquery there's a support of Gantt component. can you please tell me is there a support of it on angular 10.

**Comment by PetarMetodiev** [comment]
Hi,
Currently there is no Gantt component but there is an open feature request on our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1360534-gantt-chart-component
Please consider voting for it if it is important for you. We keep a close eye on the portal as it is one of our main metrics on what is really needed and helps us organize and prioritize our work accordingly.
