### ISSUE TITLE
Grid filter menu closes after selecting a date on mobile device

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3085]
**Describe the bug**
The issue appears on mobile devices only.

When using **kendoGridFilterCellTemplate** to create a [date range filter](https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-filtering-by-date-ranges), the filter menu is closed when a date is selected. The Grid is not filtered.
 
See this [forum thread](https://www.telerik.com/forums/mobile-only---grid---filter-menu-with-popup---custom-date-range---filter-menu-closes-after-click-any-date-on-date-popup).

**To Reproduce**
1. Open filter menu
2. Select a date

https://stackblitz.com/edit/angular-68qt3w?file=app/app.component.ts

**Comment by Raisolution** [comment]
Not reproducing with latest Grid version.

https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-filtering-by-date-ranges
