### ISSUE TITLE
[DatePicker] form is submitted when enter is pressed

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3093]
**Describe the bug**
When using keyboard shortcuts to navigate through the dates, hitting enter submits the form (using a Reactive form approach).

**To Reproduce**
1. Open the popup
2. Navigate with arrows and press enter to select a date
3. Form is submitted

https://stackblitz.com/edit/angular-s4d54g-okkzp4?file=app/app.component.ts

**Expected result**
The form should not be submitted.

**Comment by gkarapeev** [comment]
Just for reference, the [DateTimePicker](https://stackblitz.com/edit/angular-s4d54g-g5vnr2?file=app/app.component.ts) and the [DateRange](https://stackblitz.com/edit/angular-7qh7ti?file=app/app.component.ts) configuration do not have this issue.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by stnikolova** [comment]
Fix available in **v.6.0.0** of the Date Inputs package.
