### ISSUE TITLE
Scheduler: wrong date in kendoSchedulerTimeSlotTemplate for timeline views

### ISSUE THREAD

**Issue by Felx-B** [telerik/kendo-angular#3094]
Hi

**Describe the bug**
Date passed to `kendoSchedulerTimeSlotTemplate` have timezone offset in timelines view (timeline/timelineWeek/timelineMonth)

Here with UTC +1 clock in OS settings
![image](https://user-images.githubusercontent.com/18530681/96431015-38ad1080-1203-11eb-810b-e959478c671c.png)

Here with UTC -4 clock in OS settings
![image](https://user-images.githubusercontent.com/18530681/96431882-6fcff180-1204-11eb-8607-c61ed834c8cb.png)

Other views seem ok (day/week/workWeek)

![image](https://user-images.githubusercontent.com/18530681/96431209-790c8e80-1203-11eb-94f8-1bf1df394650.png)

**To Reproduce**
Here is the stackblitz : 
[https://stackblitz.com/edit/angular-scheduler-timeslot](https://stackblitz.com/edit/angular-scheduler-timeslot)

**Expected behavior**
Date passed to template should be the slot date

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 86

Thank you

**Comment by Felx-B** [comment]
I found the bug in your code : 
`src\views\timeline\timeline-multi-day-view.component.ts` line 141 :
```html
<ng-container *ngIf="timeSlotTemplateRef" [ngTemplateOutlet]="timeSlotTemplateRef"
    [ngTemplateOutletContext]="{ date: timeSlot.start, resources: resourcesByIndex(timeSlot.id.resourceIndex ) }">
</ng-container>
```

should be 
```html
<ng-container *ngIf="timeSlotTemplateRef" [ngTemplateOutlet]="timeSlotTemplateRef"
    [ngTemplateOutletContext]="{ date: timeSlot.startLocalTime, resources: resourcesByIndex(timeSlot.id.resourceIndex ) }">
</ng-container>
```

**Comment by PeterStaev** [comment]
So after almost 2 years, why they there is no fix for this, although flagged with high severity? @tapopov , @gkarapeev ?
