### ISSUE TITLE
[Context-Menu] some menu items aren't visible

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3095]
**Describe the bug**
It seems that when there isn't enough space for the menu to be rendered from top to bottom or from bottom to top then there are some menu items that cannot be scrolled to.

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-xsfm48?file=app/app.component.ts

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
