### ISSUE TITLE
[Sortable] Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3097]
**Describe the bug**
The Sortable throws an error:

_ERROR TypeError: Cannot read property 'item' of undefined_

when dragging an item from one Sortable to another one which is empty.

**To Reproduce**

Please check the following example:
https://stackblitz.com/edit/angular-fcwwry-yervbs?file=package.json

1. Drag all items from one collection to the other.
2. Drag an item to the empty collection.
3. Check the browser console for the error while dragging an item to the empty collection.

**Comment by jehell25** [comment]
seem it's still working without Errors in Version 3.0.4 [https://stackblitz.com/edit/angular-fcwwry-qzz5sa?file=package.json](https://stackblitz.com/edit/angular-fcwwry-qzz5sa?file=package.json)

**Comment by kanashiilove** [comment]
> 
> 
> seem it's still working without Errors in Version 3.0.4 https://stackblitz.com/edit/angular-fcwwry-qzz5sa?file=package.json

Version 3.0.4 has same error

**Comment by jehell25** [comment]
> > seem it's still working without Errors in Version 3.0.4 https://stackblitz.com/edit/angular-fcwwry-qzz5sa?file=package.json
> 
> Version 3.0.4 has same error

yes, you are right. I didn't notice the Error on Stackblitz after changing the package versionumber to 3.0.4, but after a reload I am getting the same error...

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by gkarapeev** [comment]
Fix available in version 4.0.1
