### ISSUE TITLE
[ComboBox] broken demo in StackBlitz

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3098]
**Describe the issue**
 There is a broken demo in StackBlitz service for chapter ["Grouping"](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/grouping/). Try to open the example into that service and observe the output error in the console. There is an error for binding input parameter valueField, it should be wrapped with a quote '.

**Comment by ipeshev** [comment]
Fix availlable in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
The demo is now fixed in the official documentation.
