### ISSUE TITLE
[Chart] zooming based on the cursor position

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3099]
**Describe the bug**
Currently the [zoom functionality](https://www.telerik.com/kendo-angular-ui/components/charts/chart/pan-zoom/) of the charts doesn't take into account the position of the cursor. It would be beneficial to provide an enhancement that allows to zoom the chart based on the cursor position.

**Comment by tsvetomir** [comment]
Starting with v5.4.0, the Chart takes the mouse cursor position when zooming in. See [updated demos](https://www.telerik.com/kendo-angular-ui/components/charts/chart/pan-zoom/) and [Changelog](https://www.telerik.com/kendo-angular-ui/components/charts/changelog/#b7fa8a62-1235-512e-9a56-17be190d1d1f).
