### ISSUE TITLE
[TreeList] Incorrect properties for CellClickEvent

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#3101]
**Describe the bug**
The typings of the CellClickEvent are incorrect. It is supposed to have a `rowIndex` property that should show the clicked row, but this is always `undefined`. Instead seems there is an `index` property that has the correct value. 

**To Reproduce**
https://stackblitz.com/edit/angular-75hdde?file=app/app.component.ts

Click on any row and see the logs. 

**Expected behavior**
The typings should be corrected to have the correct property or the even fired needs to be adjusted to use the rowIndex property instead of the current one. 

**Screenshots**

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 85

**Additional context**

**Comment by Raisolution** [comment]
Fix available in `v3.1.1`
