### ISSUE TITLE
Broken Icon docs

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3102]
**Describe the issue**
There is no way to see all supported icons by Kendo UI. All the demos are broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/17944366/96856341-3bb03700-1477-11eb-9c8d-880e3e86f5c3.png)

**Browser**
 - OS: Windows 10, 64.
 - Browser: Chrome.
 - Version: 86.0.4240.111

**Comment by mbechev** [comment]
Hi @destus90,

Thank you for the feedback.

We are aware of that issue and we are currently working on it. Meanwhile, you can refer to the **KendoReact** Icons page: https://www.telerik.com/kendo-react-ui/components/styling/icons/

**Comment by Raisolution** [comment]
The icons list is available on the dev site https://www.telerik.com/kendo-angular-ui-develop/components/styling/icons/#list-of-font-icons

It will soon be live on the official documentation too.
