### ISSUE TITLE
Invalid entry in page size dropdown when filter condition is applied

### ISSUE THREAD

**Issue by experion-jacksonalappatt** [telerik/kendo-angular#3103]
**Describe the bug**
If a filter condition is applied such that the number of results returned matches the selected page size. Then on clearing the filter, the page size drop down value is changed to the lowest value available in drop down but the page size still holds the last selected value. 
And if 'All' is selected as the page size and filter is applied, then total number of records gets added to page size dropdown

**To Reproduce**
https://stackblitz.com/edit/angular-rpyfix

Apply filter condition (contains 'key') to first column which returns only 10 records matching the current page size. Then on clearing the filter dropdown selection changes to 5 but page size is still 10

**Expected behaviour**
Page size dropdown should maintain the current page size when clearing filter

**Comment by Raisolution** [comment]
Fix is available in the latest development version of the Grid package. Will be released as part of the next official version in the upcoming week.
