### ISSUE TITLE
[Label] HTML Elements with no id are not associated properly

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-angular#3106]
**Describe the bug**
When using the Kendo Label component with a native HTML input (the input is placed outside the label component), the assistive technologies are giving a warning for missing associated label. The `for` attribute is not finding the **template reference variable** that points to the input element.

**To Reproduce**
Runnable example from the documentation 
https://www.telerik.com/kendo-angular-ui/components/labels/label/#html-inputs (open in Stackblitz)
https://stackblitz.com/edit/angular-tqxv6x?file=app/app.component.ts (test the first Input/Label pair in New Window mode)

Workaround:
- Association through the `for` property by providing the `id` value of the HTML input element
- Wrap the HTML input element within a `<kendo-label>` element 

Ticket Id: 1492721

**Comment by Raisolution** [comment]
Fixed in `v3.0.1` of the `kendo-angular-label` package.
