### ISSUE TITLE
Cannot type in footer input when navigation is enabled

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3108]
**Describe the bug**
Focused cell (in navigable Grid) is not blurred when the user tries to type in an _\<input />_ rendered in the footer template.

**To Reproduce**
1. Focus grid cell
1. Try to type in the footer input

https://stackblitz.com/edit/angular-xmcgze

Clicking outside the Grid and focusing directly the footer input seems to work as expected.

The issue might be related to #2525. Currently, the footer cells can't be focused, using the built-in keyboard navigation.
As the header cells can be focused, the _\<input />_ in the header template behaves correctly in all scenarios.

**Workaround**
Meanwhile you can remove the focus from the active Grid cell programmatically when focusing the HTML Input element in the footer cell, e.g.:
```ts
 <kendo-grid 
       #grid 
       [data]="gridData" 
       [navigable]="true">
      <kendo-grid-column field="ProductName" title="Name">
        <ng-template kendoGridFooterTemplate>
          <input class="k-textbox" (focus)="grid.focusCell(-1, -1)" />
        </ng-template>
      </kendo-grid-column>
       ...more columns
 </kendo-grid>

```
https://stackblitz.com/edit/angular-xmcgze-gd1pkl

**Comment by Raisolution** [comment]
Fixed in latest Grid version https://stackblitz.com/edit/angular-zzgefk?file=app%2Fapp.component.ts

`v6.1.1` as of mid March 2022
