### ISSUE TITLE
[DateRange] The input loses focus

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3109]
**Describe the bug**
When using ChangeDetectionStrategy.OnPush and typing in the start date of the input, then the input is blurred as soon as a single digit is entered.

**To Reproduce**
Please check the following example:

https://stackblitz.com/edit/angular-kendo-daterange-lwg9bi?file=app/app.component.ts

Enter 2/22/2 with the keyboard for the start input date and notice how the input is blurred.

**Comment by svetq** [comment]
also reported in 1496496

**Comment by ipeshev** [comment]
Same goes for datetimepicker, timepicker, datepicker.

**Comment by gkarapeev** [comment]
Fix available in [v5.0.0](https://www.telerik.com/kendo-angular-ui/components/dateinputs/changelog/#3783dad2-a552-5186-9f46-7d60da5399c2)
