### ISSUE TITLE
Wrong UI of table creator popup in KendoUI editor

### ISSUE THREAD

**Issue by mikykonst** [telerik/kendo-angular#3112]
Insert Kendo Editor in my application. When I try to create table there is an issue with cells in table popup as you can see on the screenshot.
![image](https://user-images.githubusercontent.com/17960435/97888535-e821d100-1d33-11eb-9ef0-3c415d2d12e0.png)

**Comment by Raisolution** [comment]
Hi @mikykonst ,

We were unable to reproduce the issue on our end. Please provide further details about the browser, OS used and a runnable example that demonstrates the problem, so we could tackle it further.

**Comment by mikykonst** [comment]
> Hi @mikykonst ,
> 
> We were unable to reproduce the issue on our end. Please provide further details about the browser, OS used and a runnable example that demonstrates the problem, so we could tackle it further.

Browser: Chrome latest
OS: Microsoft Windows Server 2019

**Comment by mikykonst** [comment]
Fixed. Styles confict. I imported styles for angular and jquery
