### ISSUE TITLE
Does it kendo UI for angular supports jasmine framework for unit testing?if supports then please let me know

### ISSUE THREAD

**Issue by piyushdp333** [telerik/kendo-angular#3114]
**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**

**Comment by Raisolution** [comment]
Hello,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
