### ISSUE TITLE
[DateRange] popup is not destroyed

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3115]
**Describe the bug**
The DateRangePopup is not destroyed on **ngOnDestroy** hook and remains opened when using routing.

Here is the scenario.
https://screencast-o-matic.com/watch/cYX16FMIjB 

**To Reproduce**
https://stackblitz.com/edit/angular-33rslp

Reported in [this forum thread](https://www.telerik.com/forums/the-calendar-popup-stays-open-after-changing-route).

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by dimitar-pechev** [comment]
Shipped with **@progress/kendo-angular-dateinputs@4.4.1**.
