### ISSUE TITLE
Inline editing on cell click does not save new row when clicking "Add" button

### ISSUE THREAD

**Issue by LaniMoo** [telerik/kendo-angular#3117]
**Describe the bug**
With inline editing on cell click enabled, if you add a new row, fill it out, and then click on the "Add" button again, the currently edited row does not save and disappears.

**To Reproduce**
https://stackblitz.com/edit/adnsfy--run?file=app/app.component.ts
1. Add a new row with "Add new" button
2. Fill out the row
3. Click "Add new" again

**Expected behavior**
Previously added row is saved and a new editable row is added.
I understand that the quickest "workaround" would be to just click anywhere outside of the button and THEN click the button, but it seems like a bug because it doesn't make sense to have to do this. This makes it especially tedious when a user is trying to add many rows in succession.

**Comment by dtopalov** [comment]
The described behavior is specific to the demo, and can be updated so that either the "Add" button is disabled while another row is being edited, or the currently edited row is saved before a new one is added.

**Comment by mbechev** [comment]
The [Inline Editing on Row Click](https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/) demos are fixed on site.
