### ISSUE TITLE
[Editor] patchValue() does not update value displayed in disabled state

### ISSUE THREAD

**Issue by m4cx** [telerik/kendo-angular#3119]
**Describe the bug**
The Kendo UI Editor is not capable of patching the value and showing the new form value in disabled state.

**To Reproduce**

https://angular-fchz1x.stackblitz.io

**Expected behavior**
Like all other input controls on call of the patchValue()-method on the FormControl or FormGroup the value displayed should be updated.

**Workaround**
Call enable() on the FormControl or FormGroup prior to patchValue()

**Comment by Crossfir3** [comment]
:heavy_check_mark: Tested OK in the latest dev version.

**Comment by Raisolution** [comment]
Fix available in `v3.0.1` of the Editor.
