### ISSUE TITLE
Numeric Textbox reset doesn't work (Reactive Forms)

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#312]
Plunkr:

http://plnkr.co/edit/pymcvhlB7vsHmbzmYt3k?p=info

**Comment by rohit-b** [comment]
any update on this? working version if available

**Comment by danielkaradachki** [comment]
Perhaps the plunker was update since it doesn't seem to contain numerictextbox or demonstrate reset issue? In any case, resetting the form should work correctly with the latest version:

http://plnkr.co/edit/40UuoVyktrGPg6spH91w?p=preview
