### ISSUE TITLE
[Docs] Outdated code in Localization guide

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3120]
**Describe the issue**
In Angular 11 the `ng xi18n` command is deprecated and we should use `ng extract-i18n`. See https://github.com/angular/angular-cli/pull/19132. 
Guide: https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/#extracting-the-messages

**Comment by mbechev** [comment]
The command is updated https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/#toc-extracting-the-messages
