### ISSUE TITLE
Receive TypeError: Class constructor EventEmitter_ cannot be invoked without 'new' after upgrading to angular 10

### ISSUE THREAD

**Issue by yinghuip** [telerik/kendo-angular#3122]
**Describe the bug**
After upgrading to angular 10, grid component throw TypeError.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36842365/99408042-bc553c80-292a-11eb-9516-e93d005d27d6.png)

**Additional context**

+-- @angular/animations@10.2.3
+-- @angular/cdk@10.2.7
+-- @angular/common@10.2.3
+-- @angular/compiler@10.2.3
+-- @angular/compiler-cli@10.2.3
+-- @angular/core@10.2.3
+-- @angular/forms@10.2.3
+-- @angular/localize@10.2.3
+-- @angular/material@10.2.7
+-- @angular/material-moment-adapter@10.2.7
+-- @angular/platform-browser@10.2.3
+-- @angular/platform-browser-dynamic@10.2.3
+-- @angular/platform-server@10.2.3
+-- @angular/router@10.2.3
+-- @fortawesome/fontawesome-pro@5.13.1
+-- @microsoft/applicationinsights-web@2.5.9
+-- @microsoft/signalr@3.1.9
+-- @ng-idle/core@10.0.0-beta.1
+-- @ngtools/webpack@10.2.0
+-- @progress/kendo-angular-buttons@5.5.2
+-- @progress/kendo-angular-charts@4.2.1
+-- @progress/kendo-angular-common@1.2.3
+-- @progress/kendo-angular-dateinputs@4.4.0
+-- @progress/kendo-angular-dialog@4.2.3
+-- @progress/kendo-angular-dropdowns@4.4.1
+-- @progress/kendo-angular-excel-export@3.1.6
+-- @progress/kendo-angular-grid@4.8.2
+-- @progress/kendo-angular-inputs@6.7.3
+-- @progress/kendo-angular-intl@2.0.4
+-- @progress/kendo-angular-l10n@2.0.3
+-- @progress/kendo-angular-pdf-export@2.1.0
+-- @progress/kendo-angular-popup@3.0.7
+-- @progress/kendo-angular-scrollview@3.0.4
+-- @progress/kendo-angular-sortable@3.0.6
+-- @progress/kendo-angular-upload@6.1.0
+-- @progress/kendo-data-query@1.5.4
+-- @progress/kendo-drawing@1.9.3
+-- @progress/kendo-file-saver@1.1.0
+-- @progress/kendo-theme-default@4.25.2
+-- @progress/kendo-theme-material@3.21.2
+-- @types/crypto-js@3.1.47
+-- @types/hammerjs@2.0.36
+-- @types/jquery@3.5.4
+-- @types/node@10.12.30
+-- @types/uglify-js@3.11.1
+-- @types/webpack@4.4.35
+-- ajv@6.12.6
+-- angular-l10n@10.1.2
+-- angular2-template-loader@0.6.2
+-- animate.css@3.7.2
+-- aspnet-prerendering@3.0.1
+-- aspnet-webpack@3.0.0
+-- awesome-typescript-loader@5.2.1
+-- bootstrap@3.3.7
+-- bootstrap-daterangepicker@3.0.5
+-- codelyzer@6.0.1
+-- copy-webpack-plugin@4.6.0
+-- core-js@2.6.11
+-- crypto-js@3.1.9-1
+-- css-loader@2.1.1
+-- fork-ts-checker-webpack-plugin@6.0.1
+-- hammerjs@2.0.8
+-- html-loader@0.5.5
+-- jquery@3.4.1
+-- jquery-ajax-unobtrusive@3.2.6
+-- json-loader@0.5.7
+-- mini-css-extract-plugin@0.5.0
+-- moment@2.29.1
+-- ng-busy@10.0.0
+-- ng-router-loader@2.1.0
+-- ngx-cookie-service@2.4.0
+-- ngx-virtual-scroller@4.0.3
+-- node-sass@4.12.0
+-- open-browser-webpack-plugin@0.0.5
+-- popper.js@1.14.7
+-- postinstall@0.7.0
+-- rimraf@2.6.3
+-- rxjs@6.6.3
+-- rxjs-compat@6.6.3
+-- sass-loader@7.1.0
+-- save@2.4.0
+-- style-loader@0.23.1
+-- svg-url-loader@2.3.3
+-- ts-loader@5.3.3
+-- tslib@1.14.1
+-- tslint@5.12.1
+-- typescript@3.9.7
+-- uglifyjs-webpack-plugin@2.1.3
+-- url-loader@1.1.2
+-- userpilot@1.1.8
+-- webpack@4.29.6
+-- webpack-cli@3.2.3
+-- webpack-dev-middleware@3.5.1
`-- zone.js@0.10.3

tsconfig.Json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "ClientApp",
    "sourceMap": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "importHelpers": true,
    "suppressImplicitAnyIndexErrors": true,
    "skipLibCheck": true,
    "target": "ES2015",
    "downlevelIteration": true,
    "module": "ESNext",
    "esModuleInterop": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
  },
  "angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": false
  },
  "exclude": [
    "bin",
    "node_modules",
    "dist",
    "compiled"
  ]
}

**Comment by dtopalov** [comment]
Hi @yinghuip, 

I tried to replicate the described problem, but could not:

[Archive.zip](https://github.com/telerik/kendo-angular/files/5554837/Archive.zip)

Can you please send us a similar isolated runnable project, where the issue can be observed, so we can inspect it further?

All of our components are tested against all supported versions of Angular, and we are not aware of any similar issues so far.

**Comment by yinghuip** [comment]
Hi @dtopalov 
I am unable to produce a similar runnable project due to the complexity of the project.
however I am to resolve the error after adding 
>  mainFields: ['es2015', 'browser', 'module', 'main'] in my webpack.config.js file. 
based on https://github.com/telerik/kendo-angular/issues/2103#issuecomment-468290367

**Comment by dtopalov** [comment]
Hi @yinghuip,

I am glad you found a solution, and shared it with the community. I will now close this thread, as it is for bug reports only. For any scenario-specific assistance, please use our [support service]((https://www.telerik.com/account/support-tickets)).

**Comment by GustavoCostaW** [comment]
For those who are just testing components that use the grid (instantiating), you can mock it!

jest.mock('@progress/kendo-angular-grid');
