### ISSUE TITLE
TreeList doesn't properly filter data with an empty 'or'

### ISSUE THREAD

**Issue by jquince** [telerik/kendo-angular#3123]
**Describe the bug**
Assigning the below filter to the TreeList results in the 'No records available' message being shown.
`public filter: CompositeFilterDescriptor = {
        logic: 'or',
        filters: []
    };`

**To Reproduce**
https://stackblitz.com/edit/angular-nb7haf?file=app/app.component.ts

**Expected behavior**
Tree list should show all available data.
The data grid showing all data with same filter: https://stackblitz.com/edit/angular-kmdx9j?file=app/app.component.ts

**Screenshots**

**Browser**
all

**Comment by Raisolution** [comment]
Fix available in `v4.0.6` of the `kendo-angular-treelist` package.
