### ISSUE TITLE
[FormField] Throws on init when the content consists of projected Kendo components

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#3124]
**Describe the bug**
When the FormField content consists of projected content with Kendo components, the internal mechanism for locating the focusable elements fails and an error is thrown. The components still work as expected but some of the the `aria-` attributes are not assigned.

**To Reproduce**
https://stackblitz.com/edit/angular-eccm46-1piapd

**Comment by Raisolution** [comment]
Fixed in `v7.1.0` of the `kendo-angular-inputs` package
