### ISSUE TITLE
Custom tool in editor for Horizontal line (<hr />)

### ISSUE THREAD

**Issue by mikykonst** [telerik/kendo-angular#3126]
**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**
I try to add custom tool for HR tag, I can use only setHTML exec command, that erase all content and put hr tag only

**Comment by dtopalov** [comment]
Hi @mikykonst,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
