### ISSUE TITLE
[Textbox] Hitting tab does not cause the textbox to lose focus state

### ISSUE THREAD

**Issue by tylerstacy2** [telerik/kendo-angular#3127]
**Describe the bug**
When textbox fields are in a form hitting tab to cycle through them you do not lose focus adding a box-shadow to all of the elements

**To Reproduce**
1)Go to provided stack blitz: https://stackblitz.com/edit/angular-3wv99p
2) Hit tab to move from textbox to textbox

**Expected behavior**
When you tab out of the first textbox it should lose its focused state and the box-shadow around the textbox

**Screenshots**
Image of what it looks like after tabbing
![image](https://user-images.githubusercontent.com/16674751/100145312-c1037e80-2e5d-11eb-94ee-7b8771965a1d.png)

**Browser**
 - OS: Windows 10
 - Chrome Version 87.0.4280.66

**Comment by Raisolution** [comment]
Hi @tylerstacy2 ,

A fix for this issue is available in `v6.7.4`. Here is the updated [stackblitz example](https://stackblitz.com/edit/angular-3wv99p-rvmsss).
