### ISSUE TITLE
Grid - Column not groupable -> kendo-grid-draggable present

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#313]
Hi to all,
i have a grid not groupable (default settings is false) but sortable. On DOM i see `ng-reflect-kendo-grid-draggable` object present. Why?

Right now i could see a drag object when we drag columns and it is not correct we think.
DOM has to be really small if we don't use drag capabilities at all.

So thanks.
![cattura](https://cloud.githubusercontent.com/assets/5664195/23123520/fd7d4ace-f768-11e6-97fe-9f9f741c1f2d.PNG)

**Comment by rkonstantinov** [comment]
The attributes you are seeing are artifacts of angular's development mode and they should be gone once set to production mode.
https://angular.io/docs/ts/latest/guide/deployment.html#!#enable-prod-mode

**Comment by meriturva** [comment]
@rkonstantinov I know that on production mode we don't have anymore `ng-reflect` attribute. Issue is related to the fact that a kendo draggable element is present even if it is disable (on sort there is no way to drag a column).
In fact when you try to drag a column only sortable it work!

**Comment by rkonstantinov** [comment]
Indeed, the draggable directive is always present. It is disabled if component is not groupable.
Are you facing any particular issue with this? Maybe you could provide a plnkr which demonstrates it.

**Comment by meriturva** [comment]
The only issue it is just related to UX. I mean looking plunker:

http://plnkr.co/edit/LEUAZgodgcm9mRIA0Et3?p=preview

why i could drag a column if it is not possible to drop in any place?

**Comment by rkonstantinov** [comment]
Do you mean that you could drag the anchor elements? If yes than this is browser behavior, it is not related to our component. You could try it outside of the component, you should get the same result.

**Comment by meriturva** [comment]
@rkonstantinov you are right it is browser related. my mistake....forgot it.
Anyway just think to avoid build draggable directive when unnecessary... my two cents!
So thanks...really.
