### ISSUE TITLE
kendo-combobox does not have the same height as the other kendo form fields

### ISSUE THREAD

**Issue by rakia** [telerik/kendo-angular#3131]
Hi guys,

we have a form with different kendo form controls with floatinglabels in an Angular project and we are using the material theme. We have noticed that the combobox fields have a different height than the other ones:

`<div fxLayout="row wrap" fxLayoutAlign="center start" fxFlex>

          <kendo-floatinglabel text="{{ 'stock.stockReceipt.Sube' | translate}}">
            <kendo-combobox formControlName="Sube"
                            [data]="ambarList"
                            [textField]="'label'"
                            [valueField]="'value'"
                            [valuePrimitive]="true"
                            [filterable]="true">
            </kendo-combobox>
          </kendo-floatinglabel>

          <kendo-floatinglabel *ngIf="form.get('IrsNo').value" [text]="'stock.stockReceipt.IrsNo' | translate">
            <input [formControl]="form.get('IrsNo')" name="IrsNo" kendoTextBox />
          </kendo-floatinglabel>

          <kendo-floatinglabel text="{{ 'stock.stockReceipt.FisType' | translate}}">
            <kendo-combobox formControlName="FisType"
                            [data]="entityTypes"
                            [textField]="'label'"
                            [valueField]="'value'"
                            [valuePrimitive]="true"
                            [filterable]="true">
            </kendo-combobox>
          </kendo-floatinglabel>

          <kendo-floatinglabel [text]="'stock.stockReceipt.Tarih' | translate">
            <kendo-datepicker #picker [formControl]="form.get('Tarih')" [format]="'dd.MM.yyyy'"></kendo-datepicker>
          </kendo-floatinglabel>

        </div>`

We are using:
    Angular 11, Angular Material 11
    "@progress/kendo-angular-common": "^1.0.0",
    "@progress/kendo-theme-material": "^3.19.2",
    "@progress/kendo-angular-dropdowns": "^4.0.0",
    "@progress/kendo-angular-inputs": "^6.7.2",
    "@progress/kendo-angular-intl": "^2.0.0",
    "@progress/kendo-angular-l10n": "^2.0.0",
    "@progress/kendo-angular-label": "^2.3.2",
    "@progress/kendo-angular-layout": "^5.0.3"

Could you please tell us how to adjust the combobox height to make the same as other fields?

Thank you!

**Comment by mbechev** [comment]
Hi @rakia,

I tested the latest **ComboBox** version in a Reactive form, along with **kendoTextBox** and **DatePicker** components, but their dimensions look the same:

https://stackblitz.com/edit/angular-ns4mt1

Please update the "@progress/kendo-angular-dropdowns" package version and check if the issue persists. 
https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/

Also make sure if there are any custom styling does might affect the default ComboBox height.
