### ISSUE TITLE
Editor - Icons in buttons inside custom toolbar are not displayed with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by RomanYablonski** [telerik/kendo-angular#3132]
* Bug report

## Steps to reproduce:
1) Create component with changeDetection: ChangeDetectionStrategy.OnPush
2) Add Kendo Editor with custom toolbar into this component

Demo: https://stackblitz.com/edit/angular-2vpn9j?file=app/app.component.ts

## Current behavior

Icons inside toolbar buttons are not displayed, buttons are empty.
![image](https://user-images.githubusercontent.com/25371316/100712678-30c8ba80-33c4-11eb-8e91-f799ffeea4d5.png)

## Expected behavior
Icons inside toolbar buttons are displayed correctly

Browser:
- Chrome (desktop) version 86
- Edge version 87

**Comment by dtopalov** [comment]
The issue seems to be coming from the built-in kendoEditorXXXButton directives. The icons are displayed as expected when using regular Kendo buttons with icons:

https://stackblitz.com/edit/angular-2vpn9j-yqvlpu?file=app/app.component.ts

**Comment by anfhcet** [comment]
This issue happened to me as well after upgrading Kendo-Editor version from @1.2.4 to @2.0.1. 

In my case the editor is an individual component, and this component is nested as child component in another parent component.

Icons only shows up after clicking the editor, the icons doesn't come when first landing the page. For version @1.2.4, it works fine.

I found the temporary solution is to assign icons manually by passing the [icon] properties to each directive, but for DropDownListComponent like [kendoEditorFormat], [kendoEditorFontSize], [kendoEditorFontFamily], I couldn't find a way to resolve it.

### Current behavior

![codewithouticons](https://user-images.githubusercontent.com/77863073/105558543-cace2480-5cdc-11eb-9f90-d11ff13c786f.JPG)
![withouticons](https://user-images.githubusercontent.com/77863073/105558638-07018500-5cdd-11eb-99ec-8a39b2727f53.JPG)

### Current behavior after passing [icon] properties
![codewithicons](https://user-images.githubusercontent.com/77863073/105558752-4af48a00-5cdd-11eb-9e8f-9ac8e78f06d9.JPG)
![withicons](https://user-images.githubusercontent.com/77863073/105558764-56e04c00-5cdd-11eb-9865-5a8304c47e9a.JPG)

### Expected

**Expecting icons show up normally when first landing on the page like how it behaves in version 1.2.4**
![Expected ](https://user-images.githubusercontent.com/77863073/105558810-7f684600-5cdd-11eb-9807-f222012ea7a9.JPG)

**Comment by dtopalov** [comment]
Hi @anfhcet,

A possible workaround that will cover both toolbar button icons, and the font-related dropdowns, being displayed correctly in an OnPush component is to manually call the **markForCheck()** method of the **ChangeDetectorRef** (once for each dropdown, in the example below - a total of 3 times in the **Zone.onStable** subscription):

https://stackblitz.com/edit/angular-2vpn9j-5htrvj?file=app/app.component.ts

As for displaying only the button icons, calling **markForCheck()** once in the AfterViewInit life-cycle hook should suffice:

https://stackblitz.com/edit/angular-2vpn9j-flytem?file=app/app.component.ts

**Comment by jrdutton** [comment]
We're seeing this same problem. and markForCheck() does not work for us. The component containing the Editor control has OnPush change detection turned on and is sitting inside a parent component that also has OnPush change detection turned on. Removing both OnPush options is the only way that we can get this working. Which is not ideal.

**Comment by boris01** [comment]
We are seeing this problem also. 
We must use the OnPush. 
Is there any news regarding this bug?

**Comment by Aravindudhay** [comment]
Hi @SherryT-dev pls install upgraded package of kendo-angular-toolbar . it works

**Comment by dtopalov** [comment]
Fix is available in the latest [development version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/) of the Editor package.

**Comment by dtopalov** [comment]
Fixed in v. 2.5.0 of the Editor package.
