### ISSUE TITLE
[ToolbarDropDownButton] Missing support for item template

### ISSUE THREAD

**Issue by geo242** [telerik/kendo-angular#3135]
**Describe the bug**
The `ToolbarDropDownButton` ignores item templates, even though the documentation says it has the same API as the `DropDownButton` component. No errors are produced, but the templates are not rendered.

**To Reproduce**
https://stackblitz.com/edit/angular-lj95ck

**Expected behavior**
Button templates are displayed correctly

**Comment by mbechev** [comment]
Hi @geo242,

Currently, the ToolBar tools do not support templates. 

As a workaround, I can suggest using [DropDownButton ](https://www.telerik.com/kendo-angular-ui/components/buttons/dropdownbutton/) component and the mentioned template, in ToolBar. Please check this article from our documentation where it is explained in details how to add custom control type:

https://www.telerik.com/kendo-angular-ui/components/toolbar/custom-control-types/

**Comment by mbechev** [comment]
Hi @geo242,

Currently, the ToolBar tools do not support templates. If you have the time please open a new feature request in our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui). We track the customer demand for such enhancements and prioritize our development tasks accordingly.

As a workaround, I can suggest using [DropDownButton ](https://www.telerik.com/kendo-angular-ui/components/buttons/dropdownbutton/) component and the mentioned template, in ToolBar. Please check this article from our documentation where it is explained in details how to add custom control type:

https://www.telerik.com/kendo-angular-ui/components/toolbar/custom-control-types/

Please could you point us out which documentation article could be updated to avoid such confusion in the future?

**Comment by geo242** [comment]
[This is the documentation](https://www.telerik.com/kendo-angular-ui/components/toolbar/control-types/#toc-drop-down-buttons). 

How could this be a feature request if your documentation already says that the component implements the same API as the DropDownButton? If it doesn't implement the same API, it seems lazy to just cross link to the underlying component that it wraps.

So, either support the same features and keep the current documentation, or add the missing features that the documentation says (or implies) exists.

**Comment by mbechev** [comment]
Hi @geo242, 

Indeed you are right. I checked the documentation article that you've referred and I noticed the ambiguous description of the Toolbar tool - mentioning the **DropDownButton API**, but linking the **ToolbarDropDownButton API.**

We will make sure to update those articles, to avoid any potential confusion in the future. Please accept our apologies for that.
