### ISSUE TITLE
Angular and jQuery charts use same SVG IDs

### ISSUE THREAD

**Issue by ovska** [telerik/kendo-angular#3138]
**Describe the bug**
jQuery Charts and Angular charts use same IDs when creating SVG elements. Differently sized charts create `clipPath`s using the same IDs which affects both charts. Both use the same ID names (`kdef1`, `kdef2` etc) but different counters. In this case they both create `<clipPath id="kdef1">`. This causes one of the carts to cut out some of its content due to it being larger than the other chart.

**To Reproduce**
Repo: https://github.com/ovska/kendo-chart-id-bug-repro
Run with `ng serve` and observe. It doesn't matter which chart is rendered first, the lower chart is always clipped if the browser window is large enough to show both charts.

**Expected behavior**
Charts should not influence each other and use unique IDs.

**Screenshots**
https://github.com/ovska/kendo-chart-id-bug-repro/blob/main/Untitled.png

**Browser**
OS: W10
Browser: Chrome, Firefox
Version: multiple

**Additional context**
Can be "fixed" by patching `node_modules/@progress/kendo-drawing/dist/es/util/definition-id.js` to use another ID prefix instead of `kdef`.

  ```
+-- @angular-devkit/build-angular@0.803.29
+-- @angular/animations@8.2.14
+-- @angular/cli@8.3.29
+-- @angular/common@8.2.14
+-- @angular/compiler@8.2.14
+-- @angular/compiler-cli@8.2.14
+-- @angular/core@8.2.14
+-- @angular/forms@8.2.14
+-- @angular/language-service@8.2.14
+-- @angular/platform-browser@8.2.14
+-- @angular/platform-browser-dynamic@8.2.14
+-- @angular/router@8.2.14
+-- @progress/kendo-angular-charts@4.2.1
+-- @progress/kendo-angular-common@1.2.3
+-- @progress/kendo-angular-intl@2.0.4
+-- @progress/kendo-angular-l10n@2.0.3
+-- @progress/kendo-angular-popup@3.0.7
+-- @progress/kendo-drawing@1.9.3
+-- @progress/kendo-theme-default@4.27.0
+-- @progress/kendo-ui@2020.3.1118
+-- @types/jasmine@3.3.16
+-- @types/jasminewd2@2.0.8
+-- @types/jquery@3.5.4
+-- @types/node@8.9.5
+-- codelyzer@5.2.2
+-- hammerjs@2.0.8
+-- UNMET PEER DEPENDENCY jasmine-core@3.4.0
+-- jasmine-spec-reporter@4.2.1
+-- jquery@3.5.1
+-- karma@4.1.0
+-- karma-chrome-launcher@2.2.0
+-- karma-coverage-istanbul-reporter@2.0.6
+-- karma-jasmine@2.0.1
+-- karma-jasmine-html-reporter@1.5.4
+-- protractor@5.4.4
+-- rxjs@6.4.0
+-- ts-node@7.0.1
+-- tslib@1.14.1
+-- tslint@5.15.0
+-- typescript@3.5.3
`-- zone.js@0.9.1
  ```

**Comment by jvalkeejarvi** [comment]
Is the severity of this issue really low? In my opinion this a major bug as it practically prevents using charts in Angular/angularjs hybrid application.

This might not reproduce every time but the fix should be really easy. Is there any reason why kendo-jquery and kendo-angular cannot use different ids for clipPaths?
