### ISSUE TITLE
[DropDowns] Add support for multiple group levels

### ISSUE THREAD

**Issue by w-komor** [telerik/kendo-angular#3139]
**Bug Description**
Wrong item is selected in DropDownList when data is grouped by two fields:
`groupedData: GroupResult[] = groupBy(this.data, [{field: 'category'}, {field: 'subcategory'}]);`

In the attached stackblitz example, items from the first category seem to always be selected correctly. The error occurs only after scrolling down to the second category.

Notice that 'First Category' is displayed in the fixed header even when scrolling within 'Second Category'.

**To Reproduce**
https://stackblitz.com/edit/angular-zmmhqi?file=app/app.component.ts

**Screenshots**
![dropdownlist-selection-error](https://user-images.githubusercontent.com/7305289/101287040-36703700-37ee-11eb-90a8-aa332ba22429.gif)

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 87.0.4280.88

**Comment by dimitar-pechev** [comment]
Currently the DropDowns support only one level of grouping. We will consider this as an enhancement request for adding multiple group levels support.

**Comment by stnikolova** [comment]
Also requested in ticket ref #1583806

**Comment by yanmariomenev** [comment]
Moved to our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1619290-dropdowns-add-support-for-multiple-group-levels
