### ISSUE TITLE
Grid: header sorted -> no style to set

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#314]
We just would like to make column header bold when user has selected it for sorting purpose.
On Kendo UI for Jquery we had "data-dir" attribute, we really don't find a way to do css styiling on header when it is sorted.

![sort](https://cloud.githubusercontent.com/assets/5664195/23127390/30a7ed48-f77b-11e6-9f77-4e3edf329669.PNG)

 We know that we could implement a `kendoGridHeaderTemplate` but we have to replicate a lot of logic kendo already has. We just would like to make header link bold!
Any advice?

**Comment by DydFreeman** [comment]
@meriturva i have the same problem. Have you find any solution?

**Comment by rkonstantinov** [comment]
Please be aware that this repo is for bug reports with the components. If you need technical support assistance you could:

- post your question on [SO](http://stackoverflow.com/questions/tagged/kendo-ui-angular2).
- we offer private support through Your Account on [telerik.com.](https://www.telerik.com/account/support-tickets)


A hint about how to implement such functionality will be to use [the sortChange event ](http://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-sortchange) and [headerClass](http://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/#toc-headerclass) to detect and apply the CSS class to the appropriate column.

**Comment by meriturva** [comment]
Thanks @rkonstantinov for advice.
What i have to say is that i cannot use private support (i have DevCraft Ultimate license actually) but from private support i already got answer like: 

> This is a new and separate product, currently in beta stage and free for use and community preview. We will release a commercial offering in 2017 and that will also include dedicated support service.

So just to know .. could i start to use private support right now? or is it too early?

**Comment by rkonstantinov** [comment]
yes, you can :wink:

**Comment by meriturva** [comment]
Anyway @rkonstantinov your solution doesn't fit my requirements. I have a lot of grid on my pages an i cannot duplicate sortChange event and headerCass for every single different column. It is not suitable on my side. I'm thinking on different solution right now.

**Comment by tsvetomir** [comment]
There's no need to handle the sortChange event if you're using the `[headerClass]` binding. This will allow you to reuse the code as well.

See [this plunkr](http://plnkr.co/edit/7k7ZRtozypVNjjFW88zK?p=preview) for a very simplified example for headerClass usage.

```html
    <kendo-grid-column 
      field="ContactName"
      title="Contact Name"
      [width]="150"
      [headerClass]="{ 'sorted': isSorted }">
```

**Comment by meriturva** [comment]
I have created a new plunker with my last implementation: http://plnkr.co/edit/YyWPHKkiPgHkQwd1CR8x

What i have to say is that it is really ugly (and it works just for `sorting mode == sigle`).

Just a comment, you have already a ngClass to handle sort icons near to column title, i think it is better to use same approach to add a class to whole th class instead replicate logic. For example if i have to implement same approach for multiple sort feature on few grids i guess it is not so convenient.

Secondly you have to add aria attribute `aria-sort` https://www.w3.org/WAI/PF/aria/states_and_properties#aria-sort

so you need to add something on th html element for sure!

**Comment by rkonstantinov** [comment]
Actually you could implement a directive which to do this in less than 20 lines. [Here](http://plnkr.co/edit/VTaIE5d4a6lrZRfyhQrD?p=preview) is a plunkr with basic implementation.

**Comment by meriturva** [comment]
Great @rkonstantinov !
So thanks...really....
you make me so happy regarding my choice of Kendo and Angular 2!

**Comment by meriturva** [comment]
@rkonstantinov last question, i promise! 

Are you going to implement `aria` standard on grid? i see on other elements as DropDown that `aria` is correctly implemented and i just would like to know your plan about grid!

Again thanks.

**Comment by rkonstantinov** [comment]
Yes, we will add accessibility support at some point this year.

**Comment by tsvetomir** [comment]
To confirm, Accessibility support is on top of our list and we'll start working on it soon.
We'll need few iterations to get it right and claim full support.
