### ISSUE TITLE
Editor throws an error when used with Formly

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3140]
When integrating the Editor component with Formly as demonstrated [here](https://www.telerik.com/kendo-angular-ui/components/forms/how-to/integration-with-formly/), the following error appears in the console:

![07 12 2020_13 37 04_REC](https://user-images.githubusercontent.com/33104481/101346502-5278e480-3891-11eb-9634-29d191f985c8.png)

It seems the same error appears with the TextBox component - #3134 

**To Reproduce**
https://stackblitz.com/edit/angular-bxavgl

**Workaround**

You can set *ngIf=true" to the _\<kendo-editor>_:

```html
 <kendo-editor *ngIf="true" [formControl]="formControl" [formlyAttributes]="field">
     ...
</kendo-editor>
```

**Comment by Raisolution** [comment]
The issue has been addressed in `v3.0.0` and later of the `kendo-angular-editor` package.

https://stackblitz.com/edit/angular-bxavgl-xwwaom?file=app%2Fapp.component.ts
