### ISSUE TITLE
Wrong CSS class .k-action-buttons => should be .k-actions

### ISSUE THREAD

**Issue by mdewree** [telerik/kendo-angular#3141]
**Describe the issue**
The CSS as shown in the Upload Files by Using External Button is outdated / wrong.
It should be .k-actions instead of .k-action-buttons.

Changed when updating from @progress/kendo-angular/upload 6.0.2 to 6.1.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/36478009/101363142-50b71d00-38a1-11eb-959b-d7f16d657aae.png)
![image](https://user-images.githubusercontent.com/36478009/101363618-e652ac80-38a1-11eb-8d65-990c7ae4428d.png)

**Comment by mbechev** [comment]
The changes are visible on site:
https://www.telerik.com/kendo-angular-ui/components/uploads/upload/how-to/external-btn-uploading/
