### ISSUE TITLE
Upcoming Breaking Changes: Dec 16, 2020

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#3144]
We'll release a **major update** to all Kendo UI for Angular packages with the following **breaking changes**:
1. A license file is required to use the components.

    * Make sure you have an active trial or commercial license.
    * See the [My License](https://www.telerik.com/kendo-angular-ui/my-license/) page for license activation instructions.
1. Components are no longer compatible with Angular 6 and 7.

    * Long-term support for Angular 7 has expired on Apr 18, 2020.
       * Legacy projects can reference the latest compatible packages by using the `ng6` and `ng7` tags.
    * Long-term support for Angular 8 has expired on Nov 28, 2020.
      * We plan to support it at least until mid-2021.
1. Component-specific breaking changes, see the list below.

## How To Upgrade

1. Upgrade your project to Angular v8 or later. See the [Angular Update Guide](https://update.angular.io/).
1. Follow the instructions on [My License](https://www.telerik.com/kendo-angular-ui/my-license/) to get your license.
1. Update all Kendo UI for Angular packages using the commands below:
    * `npx npm-check-updates --filter "/^@progress\/kendo-angular/" --upgrade`
    * `npm install`
1. Review Component Breaking Changes below and address them as necessary.
 
## Component Breaking Changes

* Dropdowns
  * Requires `@progress/kendo-angular-treeview` as peer dependency due to the upcoming DropDownTree component.
* Grid
  * The pager is now [responsive by default](https://www.telerik.com/kendo-angular-ui-develop/components/grid/paging/#toc-responsive-pager).
  * Requires `@progress/kendo-angular-label` as peer dependency.
* Icons
  * Requires @progress/kendo-svg-icons v0.1.2 or later
* PDF Export
  * Renamed classes (`PDFMargin -> PDFExportMargin`, `PDFTemplate -> PDFExportTemplate`).
    The selectors remain the same and existing code should not require changes.
* TreeView
  * Requires `@progress/kendo-angular-inputs` as peer dependency due to the upcoming filtering feature.

## Updated Package Versions

This is a list of all package versions that will be released as part of this update.

| Name | Ver. | Name | Ver. |
|---|---|---|---|
| kendo-angular-buttons           | 6.0.0 | kendo-angular-charts            | 5.0.0
| kendo-angular-common            | 2.0.0 | kendo-angular-component-base    | 1.0.0
| kendo-angular-conversational-ui | 3.0.0 | kendo-angular-dateinputs        | 5.0.0
| kendo-angular-dialog            | 5.0.0 | kendo-angular-dropdowns         | 5.0.0
| kendo-angular-editor            | 2.0.0 | kendo-angular-excel-export      | 4.0.0
| kendo-angular-gauges            | 4.0.0 | kendo-angular-grid              | 5.0.0
| kendo-angular-icons             | 0.4.0 | kendo-angular-indicators        | 1.0.0
| kendo-angular-inputs            | 7.0.0 | kendo-angular-intl              | 3.0.0
| kendo-angular-l10n              | 3.0.0 | kendo-angular-label             | 3.0.0
| kendo-angular-layout            | 6.0.0 | kendo-angular-listview          | 1.0.0
| kendo-angular-menu              | 3.0.0 | kendo-angular-navigation        | 1.0.0
| kendo-angular-notification      | 3.0.0 | kendo-angular-pager             | 2.0.0
| kendo-angular-pdf-export        | 3.0.0 | kendo-angular-popup             | 4.0.0
| kendo-angular-progressbar       | 2.0.0 | kendo-angular-ripple            | 3.0.0
| kendo-angular-scheduler         | 2.0.0 | kendo-angular-scrollview        | 4.0.0
| kendo-angular-sortable          | 4.0.0 | kendo-angular-toolbar           | 4.0.0
| kendo-angular-tooltip           | 3.0.0 | kendo-angular-treelist          | 3.0.0
| kendo-angular-treeview          | 5.0.0 | kendo-angular-upload            | 7.0.0

_Edit: Updated the launch date to Wed, Dec 16 to allow for additional testing._
_Edit: Revised list of component breaking changes._
_Edit: Update project upgrade instructions._

**Comment by tsvetomir** [comment]
All packages have been published. Let us know if you experience any issues.

**Comment by destus90** [comment]
Once we successfully run `npx kendo-ui-license activate` command, should we remove `kendo-ui-license.txt` from the project root?

**Comment by bvgheluwe** [comment]
Interesting question by @destus90 above. If I understand it correctly, the license file should remain available in the root of the project (otherwise a warning will appear in the browser's console, see FAQ "[Will the product function without a license key?](https://www.telerik.com/kendo-angular-ui/my-license/#toc-will-the-product-function-without-a-license-key)").
It is discouraged to store this file in source control, so each developer should have his/her copy of the license file. For build servers, consider applying the [environment variable approach](https://www.telerik.com/kendo-angular-ui/my-license/#toc-should-i-add-the-license-key-to-source-control).

Any confirmation of my understanding would be appreciated.

**Comment by ipeshev** [comment]
Really good question @destus90 , as @bvgheluwe correctly points it is best to use environment variable approach, without [adding license file to source control](https://www.telerik.com/kendo-angular-ui/my-license/#toc-should-i-add-the-license-key-to-source-control) ( same link as above ).

**Comment by tsvetomir** [comment]
Consider adding the license file to `.gitignore` instead of removing it. That said, using the environment variable could be more convenient, especially when working with multiple projects.
