### ISSUE TITLE
[Editor] Right-aligned text cannot be indented

### ISSUE THREAD

**Issue by tynan-dev** [telerik/kendo-angular#3147]
## I'm submitting a...
* Bug report

## Current behavior
* Text that is aligned right cannot be indented - neither the indent nor outdent buttons affect indentation

## Expected behavior
* Right-aligned text should receive indentation when the indent/outdent buttons are pressed

## To Reproduce
[https://stackblitz.com/edit/angular-6thppx](https://stackblitz.com/edit/angular-6thppx)

1. Enter text and right-align it
2. Click the Indent button
3. The text is not indented.

Additionally, this issue is present when the browser is set to an RTL locale, forcing the text to be right-aligned by default. 

## Environment
Browser:
- Chrome (desktop) version 86

**Comment by Raisolution** [comment]
The described behaviour is by design e.g. https://www.telerik.com/kendo-angular-ui-develop/components/editor/tools/
