### ISSUE TITLE
Grid data should allow Observable<GridDataResult> / Promise<GridDataResult>

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#315]
From what I see currently if you are using pageable grid, there is no way to set the data of grid directly to the Observable/Promise and use the async pipe.

**Comment by rusev** [comment]
What makes you think that you cannot use `Observable/Promise` with `async` pipe for populating the Grid component with data?

There are few examples for this:
 - http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/data-binding/
 - http://www.telerik.com/kendo-angular-ui/components/grid/editing/
 - http://www.telerik.com/kendo-angular-ui/components/grid/hierarchy/

**Comment by PeterStaev** [comment]
Thanks @rusev ! Had a small typo ;)
