### ISSUE TITLE
[Editor] Font Size, Family dropdown resets after line break, but selection persists

### ISSUE THREAD

**Issue by tynan-dev** [telerik/kendo-angular#3150]
**Describe the bug**
When the user selects a font size and/or family then inserts a line break, the selection in the dropdown is reset but the selection persists. This is inconsistent with what is displayed in the dropdowns, which should reflect the last selected option.

**To Reproduce**

https://stackblitz.com/edit/angular-vbnzs5-dmbdwn

1. In the middle of the paragraph text, select a new font size and font family. 
2. Enter some text. It should display with the selected size and family.
3. Press Enter to start a new line. The dropdowns are reset to "Select font size" and "Select font family."

**Expected behavior**
Instead of resetting to "Select font size/family," the dropdowns should continue to display the last selected item.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.198

**Comment by mbechev** [comment]
#3046 seems related

**Comment by Raisolution** [comment]
Not reproducing in latest Editor version `v3.1.2` e.g. https://stackblitz.com/edit/angular-zdoesv?file=app/app.component.ts
