### ISSUE TITLE
[MultiSelect] Update the value on blur

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3151]
**Describe the enhancement**
It would be nice to have an option for the MultiSelect component that allows to update the value on blur. An input property such as [resolveOnBlur] or something similar could be added. The following example demonstrates how the functionality could be achieved by manually handling the input event of the MultiSelect input element and updating the value of the MultiSelect on blur:

https://stackblitz.com/edit/angular-n2febh-nmqu8y?file=app/app.component.ts

**Comment by mbechev** [comment]
To be tracked in https://feedback.telerik.com/kendo-angular-ui/1629868-add-new-multiselect-value-on-blur
