### ISSUE TITLE
Using EditorInsertTableButton and overflow property with true value

### ISSUE THREAD

**Issue by nevraydin** [telerik/kendo-angular#3153]
**Describe the bug**
When using editor component with kendo-editor-insert-table-button and setting true value to overflow property, it gives an error below.

**Stackblitz link**
https://stackblitz.com/edit/angular-gzgc95-xg612x?file=app/app.component.ts

**Screenshots**
![image](https://user-images.githubusercontent.com/946627/102790110-0d3ad380-43b6-11eb-84a0-50a6803bcb5a.png)

![image](https://user-images.githubusercontent.com/946627/102790177-25aaee00-43b6-11eb-87e3-c446cfe2d6f4.png)

**Comment by Jahrenski** [comment]
I can attest to have the exact same issue. Does not seem to break anything

Here's the minimum reproduction code : 
```
<kendo-editor [(ngModel)]="value">
    <kendo-toolbar [overflow]="true">
      <kendo-editor-insert-table-button *ngIf="params.tables"></kendo-editor-insert-table-button>
    </kendo-toolbar>
  </kendo-editor>
```

Using these versions : 
```
"@angular/core": "10.0.14",
"@ionic-native/core": "^5.28.0",
"@ionic/angular": "^5.3.1",
"@progress/kendo-angular-buttons": "^5.5.0",
"@progress/kendo-angular-charts": "^4.1.6",
"@progress/kendo-angular-common": "^1.2.3",
"@progress/kendo-angular-dateinputs": "^4.3.1",
"@progress/kendo-angular-dialog": "^4.2.1",
"@progress/kendo-angular-dropdowns": "^4.3.0",
"@progress/kendo-angular-editor": "^1.2.4",
"@progress/kendo-angular-excel-export": "^3.1.4",
"@progress/kendo-angular-grid": "^4.8.0",
"@progress/kendo-angular-inputs": "^6.7.2",
"@progress/kendo-angular-intl": "^2.0.2",
"@progress/kendo-angular-l10n": "^2.0.2",
"@progress/kendo-angular-layout": "^5.0.3",
"@progress/kendo-angular-pdf-export": "^2.0.4",
"@progress/kendo-angular-popup": "^3.0.6",
"@progress/kendo-angular-progressbar": "^0.2.4",
"@progress/kendo-angular-scrollview": "^3.0.2",
"@progress/kendo-angular-toolbar": "^3.1.4",
"@progress/kendo-angular-upload": "^6.0.2",
"@progress/kendo-data-query": "^1.5.4",
"@progress/kendo-drawing": "^1.9.0",
"@progress/kendo-licensing": "^1.1.0",
"@progress/kendo-theme-default": "^4.21.0"
```

**Comment by RemigiuszWyciszkiewicz** [comment]
I have the same problem in my project.
I added  <kendo-editor-insert-table-button></kendo-editor-insert-table-button> to editor toolbar in example project avaiable in kendo docs and even there that problem occures: https://stackblitz.com/edit/angular-npxfdw?file=app/app.component.ts

**Comment by viperx77** [comment]
This issue is impacting our angular UI such that we cannot use the EditorInsertTableButton. This has been reported back in 2020. Can we get an update on progress, please?

**Comment by dtopalov** [comment]
Fix is available in the latest [development version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/) of the Editor package.

**Comment by dtopalov** [comment]
Fixed in v. 2.5.0 of the Editor package.
