### ISSUE TITLE
Added class is not removed, when [name] variable is changed.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3154]
Icon classes are just added, but not removed when [name] binding is changed through code.

**To Reproduce**
https://stackblitz.com/edit/angular-oljhx8?file=app/app.component.ts

**Expected behavior**
It should be changeable with variable from controller.

Broken in
  ```
  v0.4.0
  ```

**Comment by Raisolution** [comment]
Fixed in `v0.4.1` of the `kendo-angular-icons` package.
