### ISSUE TITLE
Add asterisk to floatinglabel with k-state-invalid

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3155]
**Describe the bug**
Currently it is not possible to add asterisk to kendo-floatinglabel with class k-state-invalid

**To Reproduce**
https://stackblitz.com/edit/angular-nh3lut?file=app/app.component.ts 
Maybe it should be added to the text, but then it should be settable via API option.

**Comment by dtopalov** [comment]
The "text" input of the FloatingLabel component can be bound to a dynamic value based on the "valid" and "touched" state of the respective form control, depending on the developer's preference, for example:

https://stackblitz.com/edit/angular-nh3lut-fakxbv?file=app/app.component.ts
