### ISSUE TITLE
Can't scroll to newly added row in grid with virtual scroll

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3156]
**Describe the bug**
If new row is added to grid data it is not possible to scrollTo it making it visible.

**To Reproduce**
Try adding new row in [this stackblitz sample](https://stackblitz.com/edit/angular-6xjcvz-4xveke?file=app/app.component.ts).
It is working after second, third attempt.

**Comment by Raisolution** [comment]
The reason for the observed behavior is wrong configuration of the `rowHeight` property, which should be `36`.

https://stackblitz.com/edit/angular-6xjcvz-13egir?file=app/app.component.ts
