### ISSUE TITLE
[Dialog] Page is scrollable while Dialog is opened #1000 

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-angular#3157]
Originally posted as https://github.com/telerik/kendo-themes/issues/1000 (which in terms was moved from this repo)

## I'm submitting an Enhancement

* Suggestion for improvement
Lock the vertical scrolling of the long content when you open the Dialog

## Current behavior
Preview the issue in [Themebuilder Kendo Angular UI](http://themebuilder.telerik.com/kendo-angular-ui)
When you open the Dialog button, you can scroll the main page as well. 

If the Dialog's height > viewport's height, the browser page will show up 2 scrollings: scroll of the main page (body element) and scroll of the dialog.

## Expected behavior

Hide the vertical scrolling of the main page while the Dialog is opened.

## Minimal reproduction of the problem with instructions
Add/Remove the below CSS lines when the dialog is opened/closed:
```
body {
 overflow: hidden;
}
```
Reference [Bootstrap Modal](http://getbootstrap.com/javascript/#modals)

We already have `k-overflow-hidden` which can be added to the body / html elements.

**Comment by Raisolution** [comment]
The approach has been demonstrated as a KB and will soon be live in the documentation.
