### ISSUE TITLE
radio button [disabled] not working

### ISSUE THREAD

**Issue by offwork** [telerik/kendo-angular#3159]
### Current behavior
The `[disabled]` attribute does not work in a form controller, so this attribute works when not inside a form object

### Expected/desired behavior
can't it be made to work as a form controller? please see [example](https://stackblitz.com/edit/angular-wxsaac?file=app/app.component.ts)

**Comment by mbechev** [comment]
Hi @offwork,

In Reactive Angular Forms, the [FormControl](https://angular.io/api/forms/FormControl) class is helping for tracking the value and the state of an individual form control defined in a [FormGroup](https://angular.io/api/forms/FormGroup). 

When providing a '_disabled_' attribute in the HTML, there is a warning message logged in the console that recommends changing the form control's state through the instantiated **FormControl** class.

![04 01 2021_09 26 01_REC](https://user-images.githubusercontent.com/33104481/103511012-e5944280-4e6e-11eb-8aa8-2adda77cd5ba.png)

By doing this, Angular will take care of adding/removing the '_disabled_' attribute from the DOM, depending on its value.

**Comment by dtopalov** [comment]
The discussed behavior is not related to Kendo UI for Angular, and is observed when the **kendoRadioButton** directive is not used too.

As this behavior is specific to the Angular framework, and this GitHub repo is for bug reports only, we are closing this thread.
