### ISSUE TITLE
Setting size for Donut Chart changes the chart to a square

### ISSUE THREAD

**Issue by jfongp** [telerik/kendo-angular#316]
Setting size for a donut chart somehow turns the donut chart into a square with an inner circle.
One can override the style by using the k-chart class however by setting the height and width.
`      
  <kendo-chart [seriesColors]="['#ffe', 'orange']">
            <kendo-chart-legend [visible]="false"></kendo-chart-legend>
            <kendo-chart-series>
                <kendo-chart-series-item type="donut"
                                         [data]="pieData"
                                         field="value"
                                         categoryField="category"
                                         [padding]=0
                                         [margin]=0
                                         [size]=30>
                </kendo-chart-series-item>
            </kendo-chart-series>`

**Comment by tsvetomir** [comment]
I couldn't reproduce the issue in [this plunkr](http://plnkr.co/edit/Uz29lsiNqcvcmxiwsPXm?p=preview). Can you spot any differences with your setup?
