### ISSUE TITLE
[DOCS] Hierarchical Drawer - View Source not loading / Stackblitz not available

### ISSUE THREAD

**Issue by mdewree** [telerik/kendo-angular#3160]
**Describe the issue**
https://www.telerik.com/kendo-angular-ui/components/layout/drawer/how-to/hierarchical-drawer/

View Source are not loading.
Stackblitz is not available.

**Screenshots**
![image](https://user-images.githubusercontent.com/36478009/103294520-4eecff00-49f2-11eb-9a42-0a478df25cfd.png)

**Comment by mbechev** [comment]
Hi @mdewree,

This is a known issue and it is currently fixed in our [dev channel](https://www.telerik.com/kendo-angular-ui-develop/components/layout/drawer/how-to/hierarchical-drawer/) of the site.
Soon it will be visible on the live site.

**Comment by Shiniray** [comment]
Is there any news about this fix ?

**Comment by Raisolution** [comment]
The fix is available on the develop version of the site
https://www.telerik.com/kendo-angular-ui-develop/components/layout/drawer/how-to/hierarchical-drawer/

**Comment by mbechev** [comment]
The demo is fixed on site:
https://www.telerik.com/kendo-angular-ui/components/layout/drawer/how-to/hierarchical-drawer/#toc-using-hierarchical-data
