### ISSUE TITLE
[MultiViewCalendar] Selecting a date in the second view incorrectly changes the month labels

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#3161]
**Describe the bug**
Notice the month labels are changed when a date in the second view is selected even though the views have not changed:

![mvc-month-labels-bug](https://user-images.githubusercontent.com/18740853/103618241-49cf0900-4f38-11eb-821c-af0f1260b9df.gif)

**To Reproduce**
https://stackblitz.com/edit/angular-6fnhch

**Expected behavior**
Selecting a date in the second view should not change the labels as the views have not changed.

**Additional context**
Regression in `@progress/kendo-angular-dateinputs@5.0.0`.

**Comment by seankupiec** [comment]
Is there an ETA on this fix?

**Comment by dimitar-pechev** [comment]
We cannot promise on a specific ETA, but we'll give this issue a higher priority in the upcoming weeks. We'll post an update here as soon as the fix is available in the dev channel of the dateinputs package.

**Comment by dimitar-pechev** [comment]
@seankupiec, we've released fix for this in the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the DateInputs package. It's still undergoing QA testing and it will take some time before it's released in the official channel, however, you can give it a try even now. It's available under `@progress/kendo-angular-dateinputs@v5.2.0-dev.202103251335`.

**Comment by seankupiec** [comment]
Thank you, I will try this fix out.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by dimitar-pechev** [comment]
Fix shipped in **v5.2.0**.
