### ISSUE TITLE
Grid - Responsive Pager

### ISSUE THREAD

**Issue by slewis30328** [telerik/kendo-angular#3162]
**Describe the bug**
Upgraded to V5 of the Grid and any grid that is embedded in a horizontal splitter pane automatically displays with the pager in responsive mode.  If you increase the width of the pane with mouse, the pager returns to the proper display.  At that point, if continue to decrease the width of pane, the grid will pop into responsive mode (which makes sense).  The issue is why it starts out collapsed and just by increasing the width a touch - it displays properly.  I have tried working with the new PagerSettings object and no luck.  Tried every possible config and does the same thing.

**To Reproduce**
Create Horizontal Splitter with 2 panes.  
Create a Grid in 1 of the Panes.
Set the Grid to Pageable = true
Create Dataset to activate the Pager

**Expected behavior**
The Pager bar should not show in responsive mode if the width of pane has not decreased to the point where it's necessary.

Package Config for App:
{
  "name": "smart",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "nx": "nx",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "nx workspace-lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "update:check": "ng update",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.0.5",
    "@angular/common": "^11.0.5",
    "@angular/compiler": "^11.0.5",
    "@angular/core": "^11.0.5",
    "@angular/forms": "^11.0.5",
    "@angular/localize": "^11.0.5",
    "@angular/platform-browser": "^11.0.5",
    "@angular/platform-browser-dynamic": "^11.0.5",
    "@angular/router": "^11.0.5",
    "@ckeditor/ckeditor5-angular": "^2.0.1",
    "@ckeditor/ckeditor5-build-decoupled-document": "^24.0.0",
    "@ngxs/logger-plugin": "^3.7.1",
    "@ngxs/storage-plugin": "^3.7.1",
    "@ngxs/store": "^3.7.1",
    "@progress/kendo-angular-buttons": "^6.0.0",
    "@progress/kendo-angular-charts": "^5.0.0",
    "@progress/kendo-angular-common": "^2.0.0",
    "@progress/kendo-angular-dateinputs": "^5.0.0",
    "@progress/kendo-angular-dialog": "^5.0.0",
    "@progress/kendo-angular-dropdowns": "^5.0.0",
    "@progress/kendo-angular-excel-export": "^4.0.0",
    "@progress/kendo-angular-grid": "^5.0.0",
    "@progress/kendo-angular-inputs": "^7.0.0",
    "@progress/kendo-angular-intl": "^3.0.0",
    "@progress/kendo-angular-l10n": "^3.0.0",
    "@progress/kendo-angular-label": "^3.0.0",
    "@progress/kendo-angular-layout": "^6.0.0",
    "@progress/kendo-angular-notification": "^3.0.0",
    "@progress/kendo-angular-pdf-export": "^3.0.0",
    "@progress/kendo-angular-popup": "^4.0.0",
    "@progress/kendo-angular-progressbar": "^2.0.0",
    "@progress/kendo-angular-sortable": "^4.0.0",
    "@progress/kendo-angular-toolbar": "^4.0.0",
    "@progress/kendo-angular-tooltip": "^3.0.0",
    "@progress/kendo-angular-treeview": "^5.0.0",
    "@progress/kendo-angular-upload": "^7.0.0",
    "@progress/kendo-data-query": "^1.5.4",
    "@progress/kendo-drawing": "^1.9.3",
    "@progress/kendo-licensing": "^1.1.3",
    "@progress/kendo-theme-bootstrap": "^4.28.0",
    "amqp-ts": "^1.8.0",
    "bootstrap": "^4.5.3",
    "canvas": "^2.6.1",
    "core-js": "^3.8.1",
    "easy-pdf-merge": "^0.2.5",
    "exceljs": "^4.2.0",
    "express": "4.17.1",
    "express-fileupload": "^1.2.0",
    "express-handlebars": "^5.2.0",
    "hammerjs": "^2.0.8",
    "html-to-pdfmake": "^2.1.2",
    "jquery": "^3.5.1",
    "jsbarcode": "^3.11.3",
    "jsdom": "^16.4.0",
    "ldapjs": "^2.2.3",
    "morgan": "^1.10.0",
    "ng-mocks": "^11.2.6",
    "nodemailer": "^6.4.17",
    "nodemailer-express-handlebars": "^4.0.0",
    "nodemailer-smtp-transport": "^2.7.4",
    "oracledb": "^5.1.0",
    "pdfmake": "^0.1.68",
    "pdfmake-unicode": "0.0.1",
    "popper.js": "^1.16.1",
    "request": "^2.88.2",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.3",
    "web-animations-js": "^2.3.2",
    "winston": "^3.3.3",
    "xss": "^1.0.8",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.5",
    "@angular/cli": "11.0.5",
    "@angular/compiler-cli": "^11.0.5",
    "@angular/language-service": "^11.0.5",
    "@fortawesome/fontawesome-pro": "^5.15.1",
    "@ngxs/devtools-plugin": "^3.7.1",
    "@nrwl/angular": "^11.0.18",
    "@nrwl/cypress": "11.0.18",
    "@nrwl/express": "^11.0.18",
    "@nrwl/jest": "11.0.18",
    "@nrwl/node": "^11.0.18",
    "@nrwl/workspace": "11.0.18",
    "@types/express": "4.17.9",
    "@types/jest": "26.0.19",
    "@types/node": "^14.14.16",
    "@types/pdfmake": "^0.1.16",
    "codelyzer": "^6.0.1",
    "cypress": "6.2.0",
    "dotenv": "8.2.0",
    "eslint": "7.16.0",
    "jest": "26.6.3",
    "jest-preset-angular": "8.3.2",
    "prettier": "2.2.1",
    "ts-jest": "26.4.4",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.3",
    "typescript": "4.0.5"
  }
}

**Comment by Raisolution** [comment]
Hi @slewis30328 

Could you please provide small runnable example in stackblitz that demonstrates the scenario?

**Comment by slewis30328** [comment]
We are having trouble replicating this in stackblitz.  We will keep trying.  The frustrating thing about this is even when we disable the new responsive feature, it still displays collapsed.  Isn't the idea if you set responsive to false in the new settings object, it should not alter the rendering of the bar based on available width - way the docs read it should display as prior version did?

[pageable]="{
    responsive: false,
    info: true,
    type: 'numeric',
    pageSizes: true,
    buttonCount: 5,
    previousNext: true
  }"

**Comment by Raisolution** [comment]
Thank you for the provided details, we managed to reproduce the problem. There is indeed an issue, when the initial width of a non-responsive Grid is too small. We will look into it.

**Comment by tsvetomir** [comment]
Fixed in v5.0.1
