### ISSUE TITLE
selectedKeys should have NOT mutate array

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#3165]
SelectedKeys of Grid and another components violates unidirectional dataflow - what is even worse it violates least surprise principle.

Input properties shoudl be never mutated, because it leads to several issues (problem with memoization, expressionhasbeenchangedaftercheck, etc..) and it is door closer - for example, it is not easy to use any  state-management system. You cannot do something like

[selectedKeys]="gridStateFromStore.selections"
(selectionChange)="store.dispatch(...)"

please reconsider your implementation.  

Mutating inputs is bad habit and should be avoided as much as possible.

**Comment by tsvetomir** [comment]
Seems like a valid concern. We emit `selectedKeysChange` so mutating the array is not expected.

It also applies to the `kendoGridExpandDetailsBy`, `kendoTreeViewExpandable` and `kendoTreeViewSelectable`.

**Comment by christianacca** [comment]
IF this is changed, then this must be flagged as a breaking change please!

**Comment by montella1507** [comment]
To be honest it must be changed, because this way, the behavior is considered as ,,undefined" in angular (mutating inputs). 

Kendo had several issues with mutanting inputs (hello grid filters), however, it was unintentionally there (bug).

**Comment by christianacca** [comment]
@montella1507 makes sense. Just asking that the kendo team to mark this as a breaking change as it is

**Comment by Raisolution** [comment]
Thank you for raising the concern around this item. We are still in the process of evaluating the most appropriate implementation and try to align the same behavior between the Grid and TreeList components. If the current behavior of any of those components is changed, it will be marked as a breaking change accordingly.

**Comment by titobf** [comment]
Has this already been changed on the latest version of kendo? I just had to do a search and replace of "[selectedKeys]" to "[(selectedKeys)]" to make selection work again, but I'm not totally sure if it's related to this (although it seems). Thanks

**Comment by tsvetomir** [comment]
It was fixed in v6.0.0, but we failed to add a note about one-way binding. Fixed in the [announcement issue](https://github.com/telerik/kendo-angular/issues/3557).
