### ISSUE TITLE
[ListView] aria-setsize attribute incorrectly assigned to the container element

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#3166]
**Describe the bug**
The `aria-setsize` attribute is incorrectly assigned to the container element. According to the wai-aria spec, the attribute is not allowed on a `listbox` and should instead be assigned to each item on the list ([ref](https://www.w3.org/TR/wai-aria-1.1/#aria-setsize)).

Nonetheless, with the current setup the whole list size is still correctly announced by screen readers and doesn't seem to cause issues. Should still be fixed to guarantee compliance with the specs and to satisfy testing tools.

**To Reproduce**
https://stackblitz.com/edit/angular-i4fyf7

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by dimitar-pechev** [comment]
Released in `@progress/kendo-angular-listview@v2.0.3`.
