### ISSUE TITLE
[Splitter] throws an ExpressionChange error when another Splitter is nested indirectly

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3170]
**Describe the bug**
Having a Splitter in TabStrip tab component causes an **ExpressionChange** error when the TabStrip is nested in a splitter pane:

![12 01 2021_13 13 59_REC](https://user-images.githubusercontent.com/33104481/104307581-0fd1aa00-54d8-11eb-9910-28bc47133903.png)

**To Reproduce**
https://stackblitz.com/edit/angular-8hjzhd

**Comment by Raisolution** [comment]
Fix available in `v6.1.8`
