### ISSUE TITLE
 How to switch dynamic RTL/LTR on  Kendo UI for Angular without reload page?

### ISSUE THREAD

**Issue by Omnia27** [telerik/kendo-angular#3172]
I've tried this in each module  but is not working
when reload page is working .
please provide me with the way of how to do it properly
![provider](https://user-images.githubusercontent.com/37214596/104312505-5d9de080-54df-11eb-8e03-64bdce754523.PNG)

**Comment by mbechev** [comment]
Hi @Omnia27,

This repository is for bug reports only. Please open a[ support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
