### ISSUE TITLE
[ComboBox] The X button shows on hover when using disabled state

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3173]
**Describe the bug**
When using a disabled ComboBox the X button is shown when hovering the component. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-sxi7pc-tp3zjv?file=app/app.component.ts

**Expected behavior**
The X button shouldn't be displayed when hovering a disabled ComboBox.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by svetq** [comment]
The fix is available in the official v`5.2.0` of the @progress/kendo-angular-dropdowns package.
