### ISSUE TITLE
[Editor] pasting an MS Word multilevel list causes an error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3175]
**Describe the bug**
When pasting an MS Word multilevel list to the Editor (using the [paste cleanup](https://www.telerik.com/kendo-angular-ui/components/editor/paste-cleanup/) option)  and the user tries to exit the list pressing "Enter" twice then the following error is thrown:
RangeError: Position 73 out of range

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-9nghac?file=app/app.component.ts

Copy the multilevel list from the attached MS Word file and paste it in the Editor. 
[MsWord list example.docx](https://github.com/telerik/kendo-angular/files/5814358/MsWord.list.example.docx)

Then go to the end of the list in the Editor and try to exit the list by pressing the "Enter" key twice.

**Comment by dtopalov** [comment]
Fixed in version 2.0.1 of the **@progress/kendo-angular-editor package** (requires version 1.1.3 of **@progress/kendo-editor-common**).
