### ISSUE TITLE
[ToolBar] updating the showText property value doesn't re-render the component

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3178]
**Describe the bug**
Changing the value passed to the [showText ](https://www.telerik.com/kendo-angular-ui/components/toolbar/api/ToolBarButtonComponent/#toc-showtext)property of a ToolBarButtonComponent doesn't have an effect on the button's display. 

**To Reproduce**
Please check the following example:
https://stackblitz.com/edit/angular-dqplxr-apyuts?file=app/app.component.ts

**Expected behavior**
Changing the value passed to the [showText] property should have an effect on when the button's text is displayed.

**Comment by slavenai** [comment]
Closing this as it is not reproducible with the latest `v11.2.0` of the `kendo-angular-toolbar` package:
https://stackblitz.com/edit/angular-lvrehu?file=src%2Fapp%2Fapp.component.ts
