### ISSUE TITLE
[TabStrip] The tab title is appended with the title from the next kendoTabTitle template text

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3179]
**Describe the bug**
When there are two TabStrips nested within each other and the first tab of the inner TabStrip uses a kendoTabTitle template text, then the first tab of the outer TabStrip is appended the text from the first Tab of the inner TabStrip. 

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-lwzvbp-jkhe5e?file=app/app.component.ts

**Comment by Raisolution** [comment]
Fix available in `v6.1.7`
