### ISSUE TITLE
Grid Localization 0.16.x

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#318]
Thank you for providing Grid Localization.

In my use case, I would like to localizes all my grids globally. 
Could you make the provider for CustomMessagesComponent globally? Best case would to use a global opaque token instead of the 'Messages' Class, and I would be able to replace it with my own Messages provider.

Thanks

**Comment by tsvetomir** [comment]
Are you implementing a custom localization mechanism?

Messages will be translated globally if you're using the Angular i18n framework.

**Comment by EricSch** [comment]
yes. We are using our own i18n mechanism. The Angular i18n framework is too bulky, full blown up for us. We only need a simple framework, without xlf files.

**Comment by tsvetomir** [comment]
Understood. Something we can do relatively easy is to allow the injection of a messages dictionary:

```ts
import { GridModule, GRID_MESSAGES } from '@progress/kendo-angular-grid';

const MY_GRID_MESSAGES = { 'noRecords': 'There are no items to display.' };

@NgModule({
  imports:      [ BrowserModule, GridModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ],
  providers:    [{ provide: GRID_MESSAGES, useValue: MY_GRID_MESSAGES }]
})
```

Do you think this will work for your scenario?

**Comment by EricSch** [comment]
We wouldn't use 'useValue', but yes, this would be great!

**Comment by tsvetomir** [comment]
The dictionary would have to be registered with DI, one way or another. What do you have in mind?

**Comment by tsvetomir** [comment]
One important note: messages will be looked-up in the following order:
Component message attributes -> GRID_MESSAGES dictionary -> Localization files (.xlf)

That is, message attributes have the highest priority and localization files have the lowest.

**Comment by EricSch** [comment]
Thank you. 
Thought of using a factory via 'useFactory' where I can get the string array dynamically.

**Comment by P-H-F** [comment]
Might be a little bit off-topic, but would it be possible to override the `CustomMessagesComponent` and use the overridden one instead?

**Comment by tsvetomir** [comment]
After giving this a bit more thought we decided that it's a better idea to inject a service instead of a dictionary:

```ts
abstract class KendoMessageService {
  get(key: string): string;
}
```

This allows for less restrictive implementations. Backing it with a dictionary is still a one-liner.

The abstract service class will be hosted in a `@progress/kendo-angular-l10n` packate along with some implementation helpers. The bad news is that package must be a peer dependency for all localizable packages. I don't think we can get around that.

**Comment by tsvetomir** [comment]
@P-H-F there would be no need to do that if we obtain the messages through an injectable service, correct?

**Comment by P-H-F** [comment]
Yes, correct.

The actual use-case we are trying to achieve is to allow the user to switch the localization at run-time.

**Comment by EricSch** [comment]
@tsvetomir  Either way works for me.
I think it's great, that you to support the whole Angular2 framework / ecosystem, but sometimes we need some easier ways. Gladly Angular is very pluggable and you are listening. 
Thanks again

**Comment by EricSch** [comment]
Isn't switching the localization at run-time problematic with Angular2? When I'm correct, you should also change the LOCALE_ID and this doesn't work at run-time?

**Comment by P-H-F** [comment]
@EricSch 
Well, we are currently not utilizing the angular i18n implementation. 
Basically what we are doing is:

* Input-wise (number-, date formatting, etc) we are using an extended version of the `CldrIntlService` 
 in conjunction with the KendoUI-Inputs.
* Translation-wise we are using [ngx-translate](https://github.com/ngx-translate/core), to do all our in-app-translations.

The second one is what I am currently trying to integrate with the Grid-Localization.

**Comment by EricSch** [comment]
@tsvetomir any news on that? 
I have seen the upload component has changed too, my actual localization method doesn't work anymore.

**Comment by tsvetomir** [comment]
We'll publish an updated implementation in the next few days. It **does include** an optional message service that can supply the messages in place of the message files.

The Upload localization follows the same approach as the Grid. We'll update the changelog and mark this as a breaking change.

**Comment by tsvetomir** [comment]
The update is now live and includes documentation for using the [message service](http://www.telerik.com/kendo-angular-ui/components/localization/messages/#toc-using-the-message-service).

**Comment by EricSch** [comment]
@tsvetomir Thank you very much. I assume that will be the same service for all your components?

**Comment by tsvetomir** [comment]
Yes, for the moment this is the Grid and the Upload. The rest of the components will be localized in the same way.

Thanks for your feedback!
