### ISSUE TITLE
[TextBox] associated label is not pronounced

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3181]
**Describe the bug**
When Kendo Label is associated with Kendo TextBox component, the label is not pronounced no matter which [association method](https://www.telerik.com/kendo-angular-ui/components/labels/label/#toc-html-inputs) is used.

**To Reproduce**
Here is an example where the generic `<input kendoTextBox />` is pronounced as expected with a screen reader, but the **TextBox** label is not read (tested with **NVDA**):

https://stackblitz.com/edit/angular-fqwjwx

**Expected behavior**
Labels should be pronounced.

**Comment by Raisolution** [comment]
Fix is available in `v7.1.1` of the `kendo-angular-inputs` package.
