### ISSUE TITLE
DropDownList - Where is placeholder property?

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#319]
There is no placeholder property for the DropDownList

**Comment by KirilNN** [comment]
@djarekg there is no placeholder concept in general when it comes to DropDownList/HTML select element. What you are looking for is the default Item documented here:

http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/#toc-set-the-default-item

**Comment by djarekg** [comment]
That's right...thank you.
