### ISSUE TITLE
[DropDowns] Remote Data Virtualization

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3192]
When there is a big load of data for a dropdown, the loading is slow and results in an unpleasant UX behavior. Hence, providing a remote data virtualization for the DropDowns would be a nice enhancement feature.

**Expected behavior**
Be able to fetch chunks of data from the server as the user scrolls or filters.

**Comment by tapopov** [comment]
[Example of remote data virtualization](https://www.telerik.com/kendo-angular-ui/components/knowledge-base/dropdowns-virtualization-with-remote-data/) using Kendo UI for Angular's DropDownList component.
