### ISSUE TITLE
PDF Export and images in svg format

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#3193]
**Describe the bug**
I want to export PDF from HTML containing some .svg images, but the result PDF image resolution is very bad (probably some poor conversion from vector graphics is performed)

**To Reproduce**
See this stackblitz example: https://stackblitz.com/edit/angular-ffupvu-ahsec7
Click on "Save as PDF" button and check the PDF file - the image is "rastered" like this:
![image](https://user-images.githubusercontent.com/39991506/106264726-54727a80-6226-11eb-8ec4-f29ef2633d60.png)

In [documentation](https://www.telerik.com/kendo-angular-ui/components/drawing/limitations-browser-support/) there is no mention about svg images limitations, only about svg tag.

**Expected behavior**
Exported svg images in result PDF should have smooth lines.

**Screenshots**

**Browser**
 - OS: Win 10
 - Browser: Chrome
 - Version: 88.0.4324.104

**Comment by svetq** [comment]
A fix has been released in v[1.9.4](https://www.npmjs.com/package/@progress/kendo-drawing/v/1.9.4) of the @progress/kendo-drawing package.
