### ISSUE TITLE
PDF Export vertically aligned elements

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#3194]
Hi,
in the [documentation](https://www.telerik.com/kendo-angular-ui/components/drawing/limitations-browser-support/) there is limitation "The PDF export of vertically aligned elements is not fully compatible with automatic page-breaking and might lead to undesired side effects."
What exactly does this mean? Does it include align using display: flex?

Can you give some examples of this limitation?

**Comment by svetq** [comment]
Closing this issue as the repo is for bug reports only. Let's continue any further discussion in the corresponding private support thread.
