### ISSUE TITLE
Please help to populate messages from Kendo UI components in Angular 10 or with --ivy flag 

### ISSUE THREAD

**Issue by romanKrds** [telerik/kendo-angular#3198]
Hi, thank you for Kendo UI for Angular, I'm sure this is a great library, however, I need help with it. I'm trying to introduce globalization in our app and follow [this](https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/#toc-using-the-angular-i18n-framework) guide. The problem is that Kendo UI messages are extracted only with the command `ng xi18n` which is deprecated in Angular 11. If I use the command `ng xi18n --ivy ` (with --ivy flag), it does not parse messages from Kendo UI components, so I can't populate translations with `npm install --save @progress/kendo-angular-messages` then. I need a way to populate text for translation from my .ts files, so I use this flag. Is there is a way to configure Kendo to support "ivy" messages extraction mode?

**Comment by mbechev** [comment]
Hi @romanKrds,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets
) for assistance with implementing specific scenarios or configurations.
