### ISSUE TITLE
[Window] WindowService custom messages

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3199]
**Describe the bug**
[Customizing the messages](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowMessages/) of the action buttons in the [WindowService](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowService/)

**To Reproduce**

https://stackblitz.com/edit/angular-8z7vou

**Expected behavior**
When you hover over the close and the maximize action buttons, the tooltip should show the custom text ("TEST" in the above case).

**Screenshots**
![image](https://user-images.githubusercontent.com/25337886/106953421-6067ac00-6700-11eb-9524-dc80fd057344.png)
![image](https://user-images.githubusercontent.com/25337886/106953512-7d03e400-6700-11eb-9db8-3253bd7b423e.png)

**Comment by Raisolution** [comment]
Implemented through the messages property of the WindowSettings object:
https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowSettings/#toc-messages
https://www.telerik.com/kendo-angular-ui/components/dialogs/api/WindowMessages/

**Comment by Raisolution** [comment]
Reopening as the issue is still reproducing

**Comment by Raisolution** [comment]
A fix for the issue is available in `v5.2.3` of the `kendo-angular-dialog` package.
