### ISSUE TITLE
Clear value will not respond when using Combobox Custom Values

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#320]
Hi Kendo team,

I am using combobox with  custom values, I define a valueNormalizer function just as the official demo. Before yesterday,  it worked fine. The valueNormalizer function just returns an object. 
Yesterday I updated the latest codes, and I find the normalizer function has been changed to an observable.
Then I find an issue, after I input something, then click clear button, then it  will keep spinning without a response.
![image](https://cloud.githubusercontent.com/assets/15974161/23196729/719133d8-f8f6-11e6-8370-de054f152dcd.png)

It seems like the issue is related to the observable, can anyone take a look at this issue?

**Comment by tapopov** [comment]
Thank you for reporting this @zhao125787935.

We will look into it. Indeed, we've changed to `valueNormalizer` in order to have support for asynchronous value normalization, which was not available previously.

**Comment by tapopov** [comment]
I investigated this, but did not manage to reproduce it with our demos. Would you mind sharing the exact steps taken to reproduce the issue and some code snippets, if different from ours?

**Comment by zhao125787935** [comment]
Hi @tapopov 
you can just reproduce from your demo, here is the link: http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/#toc-handle-custom-object-values

Steps to reproduce:
1. type some characters, like "test" whatever.
2. click enter key
3. click the clear button.
4. then you will see it keeps spinning and never stops.

My component is using combobox together with popup, calendar, it acts like the demo.

**Comment by tapopov** [comment]
Hi @zhao125787935 

We managed to reproduce the issue and we're working on resolving it. Stay tuned for updates.

**Comment by tapopov** [comment]
This should be fixed in v0.31.2
