### ISSUE TITLE
PDF export - image height is not respected for page breaking

### ISSUE THREAD

**Issue by kunajs** [telerik/kendo-angular#3200]
**Describe the bug**
Images from content of kendo-pdf-export component are displayed in browser/preview correctly, but when "saveAs" method is called, in certain circumstances their heights are ignored when calculating page breaks and component's page breaking is not working correctly.
This can happen when:
- the internet connection is too slow
- big amount of images are present in the HTML
- caching is disabled

My guess is that the images are loaded too late, while PDF rendering is already in progress. I suppose the export itself makes copy of the DOM and then processes it, but the copy doesn't guarantee that everything is loaded.
As a result, page breaking is incorrect, because I suppose the height of images is considered 0px.

**To Reproduce**

1. https://stackblitz.com/edit/angular-vgzpuo
2. open Chrome web tools (F12) - Network tab - uncheck Disable cache and set Throttling to "Online"
![image](https://user-images.githubusercontent.com/39991506/107037287-27d8d880-67bb-11eb-96d6-1b8b2ced58e2.png)

3. keep the Chrome web tools open and click to "Save as PDF" button
3. PDF is exported fine 
![image](https://user-images.githubusercontent.com/39991506/107037727-c7966680-67bb-11eb-8396-41ed2e346b67.png)

4. in Chrome web tools (F12) - Network tab - check Disable cache and set Throttling to "Slow" - so we simulate slow loading of assets
![image](https://user-images.githubusercontent.com/39991506/107037352-3fb05c80-67bb-11eb-8253-c4f576910b2c.png)
5. keep the Chrome web tools open and click to "Save as PDF" button again
6. PDF is exported as the height of images is zero - this causes wrong page breaking 
![image](https://user-images.githubusercontent.com/39991506/107037618-a03f9980-67bb-11eb-97e7-baa6cbc1b7d0.png)

**Expected behavior**
The images (and other assets) should be preloaded first and when all of them are ready, PDF creation can continue.

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.146

**Additional context**
Workaround would be to set height of images explicitly, but it is not ideal solution:
- the height could be unknown
- the height is proportionally scaled by width % value
- the height is set in % etc.

**Comment by svetq** [comment]
The PDF Export relies on the browser cache to get the images. Thus, please make sure to have the browser cache enabled in order to get the proper behavior when using automatic page breaking.

What else could be done is to set fixed heights to the images. That will allow for the PDF Export to allocate the required space for the exported images before they are downloaded.
