### ISSUE TITLE
[DateRange] Popup is not closed after range is selected

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#3202]
**Describe the bug**
When I select the start and then the end date, I expect the popup to close automatically (or at least an option to enable that).

**To Reproduce**
See https://www.telerik.com/kendo-angular-ui/components/dateinputs/daterange/popup/

**Expected behavior**
Close after selection of end date.
See also JQuery version: https://demos.telerik.com/kendo-ui/daterangepicker/api

**Comment by mbechev** [comment]
Hi @JaapMosselman,
 
DateRange component popup can be closed programmatically by using the [toggle ](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DateRangePopupComponent/#toc-toggle)method of the  ```<kendo-daterange-popup>```. The **toggle** method needs to be applied on [valueChange ](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DateInputComponent/#toc-valuechange)event of the ```<kendo-dateinput kendoDateRangeEndInput ...>```.

Please check the following example:

https://stackblitz.com/edit/angular-5jofqm
