### ISSUE TITLE
[SplitButton] look="flat" not supported

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#3203]
**Describe the bug**
Split button does not respect look="flat".

`<kendo-splitbutton look="flat"><kendo-splitbutton>`

**To Reproduce**
See https://www.telerik.com/kendo-angular-ui/components/buttons/splitbutton/ "Basic usage" example (Flat).

**Expected behavior**
Value "flat" is supported (docs: https://www.telerik.com/kendo-angular-ui/components/buttons/api/SplitButtonComponent/) and we can see what "flat" typically means for buttons here: https://www.telerik.com/kendo-angular-ui/components/buttons/button/

**Screenshots**
![image](https://user-images.githubusercontent.com/5447876/107243942-ccfae780-6a2d-11eb-932e-523a6586376f.png)

Compared to "normal" button:
![image](https://user-images.githubusercontent.com/5447876/107244063-ea2fb600-6a2d-11eb-8b02-109422aaea9f.png)

**Browser**
 - OS: Win 10
 - Browser Chrome

**Comment by inikolova** [comment]
This issue is due to a bug in the Material theme - I logged it in our themes repo for further investigation and fixing:

https://github.com/telerik/kendo-themes/issues/2293
