### ISSUE TITLE
[Chip] click event is triggered when chip is removed

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#3205]
**Describe the bug**
There's currently no easy way to listen for click events if chip is removable and click != remove. To be able to distinguish these two cases:
* User clicked chip content (but not remove icon)
* User clicked chip remove

... we need to check the event target for internals of chip component (css classes) because "remove" icon clicks will fire the "click" event too.

**To Reproduce**

https://www.telerik.com/kendo-angular-ui/components/buttons/chip/

* Click "remove" in example
* Check event log, there will be a click event

**Expected behavior**
A separate event like "contentClick" would allow developers to listen for "click but not remove" events without having to check for chip internals.

**Comment by Raisolution** [comment]
`contentClick` event has been introduced to the Chip component in `v6.3.0`.
