### ISSUE TITLE
@progress/kendo-angular-grid issue at upgrade

### ISSUE THREAD

**Issue by satish10105** [telerik/kendo-angular#3209]
after upgrade 8.2 to 9.1
I upgraded kendo gird library what are outdated 
then am getting error like  this.

![image](https://user-images.githubusercontent.com/31982941/108032575-b588b380-7058-11eb-824b-3812cfb44ce4.png)

![image](https://user-images.githubusercontent.com/31982941/108032726-ef59ba00-7058-11eb-88aa-752bf12b461a.png)

**Comment by mbechev** [comment]
Hi @satish10105,

It seems that the errors are not related to the built-in features of the Kendo Angular Grid component. Also, it is worth mentioning that the [editRow ](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-editrow
)Grid method, expects **[FormGroup](https://angular.io/api/forms/FormGroup
)** as a second argument.

Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations as this repository is for bug reports only.
