### ISSUE TITLE
[DropDowns] "itemClass" options for kendo-popup items.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3219]
**Describe the enhancement**
It would be nice to have "itemClass" options ( similar to rowClass in grid ) to set custom classes of kendo-popup items.

**Expected behavior**
It should be callback function that accepts dataItem object as argument and set class depending from returned result.

**Comment by yanmariomenev** [comment]
Item was transferred to our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1620976-dropdowns-itemclass-options-for-kendo-popup-items
