### ISSUE TITLE
Editable Grid selection triggered when clicking the "Edit" and "Remove" buttons in the command column

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#322]
The selectionChange event is triggered when the Edit, Remove, Update, and Cancel buttons are clicked in an editable Grid:

[http://plnkr.co/edit/CjXHwNeuWRVboWezW9IC?p=preview](http://plnkr.co/edit/CjXHwNeuWRVboWezW9IC?p=preview)

**Comment by rusev** [comment]
Grid package version `0.25.3` contains a fix for this.

**Comment by dtopalov** [comment]
The issue is still observable if Kendo button with icons is used, and the icon is the click target:

[http://plnkr.co/edit/5hJiMW4H51OuH2yrnO0J?p=preview](http://plnkr.co/edit/5hJiMW4H51OuH2yrnO0J?p=preview)

Workaround:

    >>> .k-button.k-button-icontext .k-icon {
      pointer-events: none;
    }

[http://plnkr.co/edit/8Ul37aJhNNsObkx0tygI?p=preview](http://plnkr.co/edit/8Ul37aJhNNsObkx0tygI?p=preview)

**Comment by tsvetomir** [comment]
Note reproducible with the current release, see [plunkr](http://plnkr.co/edit/gya6lWeDXwDFI5x70Fbj?p=preview).

**Comment by siyka-marinova** [comment]
The issue is still reproducible with the above plunker: when precicely the icon is clicked, the onSelectionChange event is triggered:
[https://www.screencast.com/t/cDUqhDIQ](https://www.screencast.com/t/cDUqhDIQ)

**Comment by tsvetomir** [comment]
Fix shipped in `@progress/kendo-angular-grid@1.4.0`
