### ISSUE TITLE
Drop down list virtualization does not allow picking an item with the mouse in legacy Edge browser

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3220]
**Describe the bug**
If you turn on virtualization and use a legacy Edge browser (non Chromium based) then you can't select an item from the list using the mouse.  The workaround is to turn off virtualization or use the keyboard to pick an item.

**To Reproduce**
https://stackblitz.com/edit/angular-liex2m?file=app/app.component.ts

**Expected behavior**
It should select items with mouse click as in other browsers.

**Screenshots**

**Browser**
 - Browser Edge legacy

**Comment by ipeshev** [comment]
It looks like all components with popup and virtual scroll are affected - https://stackblitz.com/edit/angular-j8mxkr?file=app/app.component.ts

**Comment by JoomFX** [comment]
This browser is no longer supported.

https://www.telerik.com/kendo-angular-ui/components/faq/#toc-what-browsers-do-the-kendo-ui-components-for-angular-support
