### ISSUE TITLE
TileLayout Component not providing an optional header / title results in classList null error 

### ISSUE THREAD

**Issue by wasdJens** [telerik/kendo-angular#3222]
**Describe the bug**
When using the `TileLayout` Component and not providing a `TileLayoutItemHeader ` component OR `title` input the following error is displayed in the developer console of the browser. 
![image](https://user-images.githubusercontent.com/24612796/109299205-0789c000-7835-11eb-987d-89748cde98c2.png)

**To Reproduce**
https://stackblitz.com/edit/angular-sqpkka-fzdsit?devtoolsheight=33&file=app/app.component.ts

**Expected behavior**
According to the official [documentation](https://www.telerik.com/kendo-angular-ui/components/layout/tilelayout/tiles-configuration/)  the header is optional. For me personally it would help to make it clear that in this case the `title` attribute is required or a better error message is shown to indicate that a configuration step for the tile layout is missing. 

> header(Optional) - Configured either by passing a string to the title configuration option of the TileLayoutItem or by nesting a <kendo-tilelayout-item-header> element of type TileLayoutItemHeader inside the tile. Both approaches will result in rendering a header section above the body.

Also the header is only required if used with the `reorderable` option (Which is disabled in my example above) 

> The header section of the tiles is required if the reorderable option of the TileLayout component is enabled. End-users will be able to drag the tiles through their headers.

**Screenshots**
See above.

**Browser**
 - OS: **Windows 10**
 - Browser **Microsoft Edge**
 - Version **Version 88.0.705.74 (Offizielles Build) (64-Bit)**

**Additional context**
Background: I wanted to create a tile without a title / header (Only a body) - I solved my problem by just using the header component since it was only a small text that was displayed.

**Comment by dtopalov** [comment]
The fix is available in the [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the **@progress/kendo-angular-layout** package.

**Comment by Raisolution** [comment]
An official version `6.1.3` of the package has been released.
