### ISSUE TITLE
[DropDowns] missing first group template

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3225]
**Describe the bug**
The first group template isn't applied for the DrodDowns.

**To Reproduce**
Please see the following example:

https://stackblitz.com/edit/angular-46t6pe?file=app/app.component.ts

**Comment by tapopov** [comment]
This behavior is expected, as in order to modify the first (fixed) group header, the [FixedGroupTemplateDirective](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/FixedGroupTemplateDirective/) should be used instead.
