### ISSUE TITLE
Building packages from source and Node 12

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#3226]
A while a go (perhaps already 1 or 2 years ago) it was not possible to build package from source (as described [here](https://www.telerik.com/kendo-angular-ui/components/installation/source-code/)) when Node 12 was installed on the machine.
With Node 10, it worked fine.
Instead of just upgrading my machine to Node 12, with the risk of still not working, I just wanted to ask if it should now work fine with Node 12?
(I have another lib which does not support Node 10 anymore, so I have now a conflict to solve 🤔)

**Comment by mbechev** [comment]
Hi @JaapMosselman,

There is no problem building a custom package with Node 12. Tested with **v12.18.3**.

In case any further questions come up, please[ open a support ticket](https://www.telerik.com/account/support-tickets
). This repository is for bug reports only.
