### ISSUE TITLE
Drag hint is not shown on Safari

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3228]
**Describe the bug**
When trying to reorder items with drag & drop , the drag hint is not visible, while it is selecting items text.

**To Reproduce**
Visible on our official demos - https://www.telerik.com/kendo-angular-ui/components/treeview/drag-and-drop/

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**
Client is using embedded iOS iPAD emulator where there is completely no sign of draging.

**Comment by ipeshev** [comment]
Feature available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds).

**Comment by dimitar-pechev** [comment]
Shipped with **v5.4.0**.
