### ISSUE TITLE
Upload widget initial files with reactive forms?

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#323]
Can you set currently set the initial files of the upload control with reactive forms? I've tried setting the value in the `FormGroup` for the control to an array of `FileInfo` but this has no effect on the upload widget.

**Comment by Raisolution** [comment]
Hi @PeterStaev,

I am unable to reproduce the problem [here](http://plnkr.co/edit/CXsrmvUcKeucOXWdK57m?p=preview). Is this what you are looking to achieve?

**Comment by PeterStaev** [comment]
Hey @Raisolution , when you put the files when you init the form it works, but in my case the files are being loaded from backend. So in this case I do not have the files when I create the form. Here is an example: http://plnkr.co/edit/Rrdz2kQriog6r9kWxQba?p=preview. In the handler for Change Files I use the `patchValue` of the form to change default form value to something else. This has no effect on the upload widget.

**Comment by Raisolution** [comment]
The `patchValue` method is working. The reason for the issue in the example is a typo in the method name `patchValues`.

Nevertheless we are currently considering changes in the widget behavior, when the initial files are set at a later stage. You could share your thoughts on that matter [here](https://github.com/telerik/kendo-angular/issues/292).

**Comment by PeterStaev** [comment]
👍  Now I have to see why it is not working in my scenario, may be because I'm not sending all properties and have custom properties. 

But even with the fixed sample, the control is behaving strange - i.e. it adds the files to the widget while actually the form value has only 2 items.
