### ISSUE TITLE
[Responsive ToolBar] Overflow Button Obscures Tools

### ISSUE THREAD

**Issue by allout58** [telerik/kendo-angular#3230]
**Describe the bug**
When shrinking a responsive toolbar, the overflow button can obscure a tool, and prevent it from being clickable.

**To Reproduce**

Start with the Responsive Toolbar sample and slowly shrink the width so tools start to overflow, then continue until the next tool would start to overflow.

**Expected behavior**
The overflow button should not cover up any part of a tool.

**Screenshots**
This is from the Responsive Toolbar sample, having shrunk past the first tool and starting into the second.
![image](https://user-images.githubusercontent.com/2939703/110386977-ff006900-802e-11eb-9bf9-27eb0cbcbd43.png)

**Browser**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: @progress/kendo-angular-toolbar:4.0.0

**Additional context**
My guess is that the width of the overflow button isn't being accounted for when deciding to move items to the overflow popup.

**Example**
https://www.telerik.com/kendo-angular-ui/components/toolbar/responsive-toolbar/

**Comment by Raisolution** [comment]
Fix is available in `v5.0.2` of the Toolbar package.
