### ISSUE TITLE
[MultiSelect] Missing role listbox on <ul> element

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3232]
**Describe the bug**
Following the **WAI-ARIA** specifications, an element with role='_listbox_' should contain children with role='_option_'

https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

and the same rule is followed with the MultiSelеct items:

![09 03 2021_10 40 29_REC](https://user-images.githubusercontent.com/33104481/110443306-6fa59500-80c4-11eb-845f-b3c992b1905f.png)

Тhe selected items are also having the role='_option_', but their parent \<ul> element doesn't have role='_listbox_' set, which causes some accessibility tools to throw warning messages:

![09 03 2021_10 49 59_REC](https://user-images.githubusercontent.com/33104481/110444070-476a6600-80c5-11eb-9fb2-2d24a386953d.png)

**To Reproduce**
https://stackblitz.com/edit/angular-pet9rx

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds) of @progress/kendo-angular-dropdowns.

**Comment by tapopov** [comment]
Shipped in v6.0.2
