### ISSUE TITLE
Provide more precise way to import @progress things

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#3235]
At  the moment you can import Modules from big bundles:

```
import { SwitchModule, TextBoxModule, RadioButtonModule, CheckBoxModule }   from '@progress/kendo-angular-inputs';
import { AutoCompleteModule, MultiSelectModule, DropDownsModule }               from '@progress/kendo-angular-dropdowns';

```
however, modules are not Treeshakeable without build-optimizer so even if you use only for example SwitchModule in your application:

`import { SwitchModule  }   from '@progress/kendo-angular-inputs';`

**all NgModules** and their dependencies (components, directives, pipes) that are exported in @progress/kendo-angular-inputs/index.js  are included in build.  This means:

- a lot bigger DEV build
- a way worse developer experience (bigger load time / rebuild times) 
- longer production builds (more work for  BuildOptimizer) 
- leading to "bad behave" of your users - developers (Importing more than used)

Please provide more entry points in your DIST to your library like:

import { AutoCompleteModule  }               from '@progress/kendo-angular-dropdowns/autocomplete';

etc.

**Comment by dtopalov** [comment]
The bundle, produced by Angular in dev (non-optimized) builds is indeed not treeshaken:

https://medium.com/@kavisha.talsania/angular-development-vs-production-build-671b7fd5dbf4

The Angular team is going in the direction of using optimized builds by default:

https://github.com/angular/angular-cli/pull/20128

We are trying to follow the best practices when configuring our packages and splitting our codebase in separate modules.

https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/mobilebasic

Providing multiple entry points seems to be reserved for specific scenarios like writing and running tests, which are not applicable to our packages.

However, I can assure you that we will keep tracking the ever growing opportunities, provided by the Angular framework, and will consider all possible ways to optimize our packages accordingly in the future too.
