### ISSUE TITLE
Grid/Treelist column filter dropdown has artifact in drop shadow with material theme

### ISSUE THREAD

**Issue by jquince** [telerik/kendo-angular#3238]
**Describe the bug**
There is a extra 'border' floating mid drop shadow on filter drop down.
See screen shot below.

**To Reproduce**
https://stackblitz.com/edit/angular-dqxgqq?file=index.html

**Expected behavior**
Should be smooth drop shadow

**Screenshots**
![image](https://user-images.githubusercontent.com/4357131/111500104-de0bd800-8700-11eb-8ea3-569d136ebce3.png)

**Browser**
tested on chrome, FF

**Comment by inikolova** [comment]
Hi and thank you for the bug report. This issue is styling related and has been logged in our themes repo. You could track its progress here: 
https://github.com/telerik/kendo-themes/issues/2374
