### ISSUE TITLE
Custom properties for initial files for Upload

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#324]
I need to have custom properties on top of the default ones in `FileInfo` (for example I need the file id that is stored on the backend so I can create a link to download the file). Seems any custom property I add is ignored and I cannot access it in the template. 

As a workaround I'm currently using the `uid` property of `FileInfo` and setting that one to the id i return from the backend.

**Comment by rusev** [comment]
We are not sure what you mean here? Which package/component you are using? Any runnable example?

**Comment by PeterStaev** [comment]
Hey @rusev , sorry adjusted the title - it is for the Upload widget

**Comment by Raisolution** [comment]
Hi @PeterStaev,

yes, we are currently considering changes in this direction. Discussion on the topic is available in #292.

**Comment by PeterStaev** [comment]
I've seen the referenced task, but there the problem seems different - it is more for change notification when items are being pushed to the model array.

**Comment by Raisolution** [comment]
Both issues are discussed in the other thread and are related to each other. I will close this for now as a duplicate, but if you have any thoughts or suggestions regarding the implementation, please share them in the other discussion.
