### ISSUE TITLE
[MultiSelect] clicking the input does not close the popup

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3240]
**Describe the bug**
Clicking in the input, next to the cursor does not close the items popup:

![image](https://user-images.githubusercontent.com/33104481/111761256-61b3f900-88a8-11eb-9f4f-d1852aa9f14d.png)

The popup is closed as expected if we clicked the area next to the rendered input:

![19 03 2021_11 46 25_REC](https://user-images.githubusercontent.com/33104481/111761626-c5d6bd00-88a8-11eb-94dc-b76bf8d893f6.png)

**To Reproduce**
https://stackblitz.com/edit/angular-rkpwpa

**Expected behavior**
The popup should be closed no matter where the user clicks.

**Comment by svetq** [comment]
The described behavior is by design.
