### ISSUE TITLE
[FAB] setting size and shape properties to string throws an error

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3241]
**Describe the bug**
Setting the size and shape properties of the FloatingActionButton to a string
```html
 <kendo-floatingactionbutton
        size="large"
        shape="circle"
      >
  </kendo-floatingactionbutton>
```

throws the following error in the console:

![19 03 2021_18 18 20_REC](https://user-images.githubusercontent.com/33104481/111811221-82e40c00-88df-11eb-8473-865a4f9e1317.png)

Data binding works as expected:

```html
 <kendo-floatingactionbutton
        [size]="'large'"
        [shape]="'circle'"
      >
  </kendo-floatingactionbutton>
```

**To Reproduce**
The issue is not reproduced in a StackBlitz demo (Ivy is disabled). 

1. Download and unzip the folder
2. Run **npm install**
3. Run **ng serve**
[fab-A11.zip](https://github.com/telerik/kendo-angular/files/6172679/fab-A11.zip)

**Comment by Raisolution** [comment]
Fix available in `v6.3.0`.
