### ISSUE TITLE
instanceof not working for preventAction of dialogs

### ISSUE THREAD

**Issue by Azer1652** [telerik/kendo-angular#3243]
## I'm submitting a...
* Bug report 

## Current behavior
When using the DialogResult in the preventAction callback of dialogs, instanceof cannot be used to check the type.
instanceof always returns false.

## Expected behavior
instanceof can be used to check whether the DialogResult is a DialogCloseResult or DialogAction.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ardbsw?file=app/app.component.ts

## Environment
latest

Package versions:
reproducible on demo site

Browser:

- Chrome (desktop) version 89.0.4389.90
- Firefox version 86.0
- Edge version 89.0.774.57

System:
reproducible on demo site

**Comment by Azer1652** [comment]
Additional info:
instanceof does work for 
`            preventAction: (ev) => {
                ...
            }`

But not for:
`preventAction: (ev, dialog) => {
                ...
            }`

**Comment by mbechev** [comment]
Hi @Azer1652.

The [actions ](https://www.telerik.com/kendo-angular-ui/components/dialogs/api/DialogSettings/#toc-actions) property of the DialogSettings, accepts _DialogActions[]_ , _any[]_ or _TemplateRef\<any>_ as value. That is why in this case, it is recommended to check if the received property is from type **DialogCloseResult** as described in the following section:

https://www.telerik.com/kendo-angular-ui/components/dialogs/dialog/service/#toc-dialog-close-prevention

https://stackblitz.com/edit/angular-ardbsw-aghr7u

In case any further questions come up, please [open a support ticket](https://www.telerik.com/account/support-tickets). This repository is for bug reports only.
