### ISSUE TITLE
[Grid] row selection checkboxes have no accessible name, associated <label>, or [title].

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3244]
**Describe the bug**
The default row selection checkbox of the Grid has no accessible name, associated <label>, or [title]. In fact there is a label but it is empty which causes the error.

**To Reproduce**
Please check the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/grid/selection/row-selection/#toc-select-all-checkbox
**Workaround**
Use the [SelectionCheckboxDirective](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionCheckboxDirective/). Such approach will allow to add a title or aria-label attribute to the input:
https://stackblitz.com/edit/angular-avezcw-ede393?file=app/app.component.ts

**Comment by Raisolution** [comment]
Available in `v5.1.2` of the Grid package.
