### ISSUE TITLE
Bulk Edit - Reactive Grid - Grouping on load - values not loaded 

### ISSUE THREAD

**Issue by ramafmgl** [telerik/kendo-angular#3246]
**Describe the bug**
Bulk Edit - Reactive forms - Grid - Grouping on load - values not loaded . if we do not group on load it works fine.

**To Reproduce**
Disable grouping on load in the given demo sample. it works fine. 
If if we have default groups on load values in grid are not loaded correctly.

Example running code below 
https://stackblitz.com/edit/kendo-angular-grouping-on-load-issue?file=app/app.component.ts
( Based  on https://www.telerik.com/kendo-angular-ui/components/grid/editing/custom-reactive-editing/#toc-rendering-editors-in-the-cell-templates )

**Expected behavior**
values should load by default even when grouping is enabled

![image](https://user-images.githubusercontent.com/68410801/112569788-c8449400-8e1f-11eb-8abb-98bb7327c5b0.png)

**Screenshots**
Error scenario 
![image](https://user-images.githubusercontent.com/68410801/112569708-a4814e00-8e1f-11eb-8f28-e8c791e59998.png)

Please suggest

**Comment by mbechev** [comment]
Hi @ramafmgl,

When grouping is applied the architecture of the Grid collection is changed. Each dataItem includes [GroupDescriptor ](https://www.telerik.com/kendo-angular-ui/components/data-query/api/GroupDescriptor/) properties which is not compatible with the current logic of assigning the form control values.

Here is the updated demo, consider the grouping functionality:
https://stackblitz.com/edit/kendo-angular-grouping-on-load-issue-lmwjrj
