### ISSUE TITLE
[TabStrip] Input in kendoTabTitle template on space bar key press not working.

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3247]
**Describe the bug**
When adding kendo-textbox aka input tag in **TabStrip** Title template the space bar input doesn't function correctly unless **stopPropagation()** is called on the event. 
Check whether the same problem occurs in a **PanelBar** title after https://github.com/telerik/kendo-angular/issues/3051 is fixed.

**To Reproduce**
https://stackblitz.com/edit/tab-title-with-input-oibseb?file=app/app.component.ts

**Expected behavior**
https://stackblitz.com/edit/tab-title-with-input

**Comment by Raisolution** [comment]
Fix available in `v6.1.6`
