### ISSUE TITLE
Accessibility issue with kendo-multiselect while checking with fastpass.

### ISSUE THREAD

**Issue by aasis21** [telerik/kendo-angular#3249]
**Describe the bug**
We are using the kendo-multiselect control in our application and we are trying to reconcile accessibility issues outlined by the FastPass tool (documented in this [blog post](https://www.telerik.com/blogs/the-need-for-automated-accessibility-testing)). Fastpass is finding many accessibility issues with kendo multiselect, I tried running fastpass on kendo multiselect getting started page and found similar issue. The one I am specifically looking is "Ensures that lists are structured correctly" and "Ensures elements with an ARIA role that require parent roles are contained by them"
![image](https://user-images.githubusercontent.com/25389384/112682577-86224f00-8e2d-11eb-94b3-a2fb475d4581.png)

![image](https://user-images.githubusercontent.com/25389384/113062721-0cf66500-9169-11eb-8f83-637cbd1d3cce.png)

**To Reproduce**

- Go to this kendo doc page: https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/
- Get accessibility insights extension for web and run fastpass on the above page https://accessibilityinsights.io/docs/en/web/overview/ 
- Do inspect element on getting started example.

**Expected behavior**
Fastpass should not find any accessibility issue with kendo-multiselect.

**Browser**
 - New edge, chrome

**Comment by mbechev** [comment]
The issue seems to be related to #3232

**Comment by ipeshev** [comment]
@aasis21  Kendo UI for Angular Multiselect is fully accessible only when used with the Label component, please refer  to [this updated example](https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/multiselect/).
