### ISSUE TITLE
No exported member "load"

### ISSUE THREAD

**Issue by chriscurnow** [telerik/kendo-angular#325]
I've been using the kendo angular grid component pretty well since it first came out.

I have just tried to implement internationalisation to display currencies and dates.

When I tried to use the code from here: http://www.telerik.com/kendo-angular-ui/components/internationalization/,

I got an error in the line 

`import { load, IntlModule } from '@progress/kendo-angular-intl';`

The error was:

`"@progress/kendo-angular-intl/dist/es/main has no exported member 'load'"`

I was able to get everything to work by replacing importing "load" using the following command:

`import { load } from '@telerik/kendo-intl';`

and removing all the 'require' statements. That is the load statement became:

`load(`
  `'json!cldr-data/main/bg/numbers.json'`,
  `'json!cldr-data/main/bg/currencies.json'`,
  `'json!cldr-data/main/bg/ca-gregorian.json'`,
  `'json!cldr-data/main/bg/timeZoneNames.json'`,
`...
);`

I am using Angular CLI

**Comment by tsvetomir** [comment]
The `load` method has been re-exported in version 0.10 for convenience.
Please check that you're using the correct version and update your Node modules if necessary:

`npm ls @progress/kendo-angular-intl`

**Comment by chriscurnow** [comment]
Hmmm, just installed 0.10 and still get the same error. It's not much of a problem for me as I've worked out a way around it. However it could be a problem for others.

**Comment by gyoshev** [comment]
Since we do not have a sample that shows the problem and [the online example runs correctly in plunkr](http://www.telerik.com/kendo-angular-ui/components/internationalization/), I'm closing this issue. Feel free to post more details if the problem persists.
