### ISSUE TITLE
[MaskedTextBox] disabled styles are not being applied after calling disable on FormControl

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3256]
**Describe the bug**
When we have OnPush detection strategy, MaskedTextBox looks like enabled even if you call `disable` method on a FormControl. You cannot input any value but for a user it looks like enabled control.

**To Reproduce**

1. Go to https://stackblitz.com/edit/angular-rqecst?file=app/app.component.ts
2. After 500ms, notice that input control looks as if it was not disabled.

**Expected behavior**
MaskedTextBox should have correct visual presentation.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89

**Additional context**
The issue doesn't happen with native HTML5 controls such as `<input type="text" />`.

**Comment by destus90** [comment]
It appears to happen with all kendo components from the Input module.

https://stackblitz.com/edit/angular-rqecst-okpstk?file=app%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fix is available in `v7.2.2` of the inputs package.
