### ISSUE TITLE
[FloatingLabel] FloatingLabel text overlapping the TextBox and TextBoxPrefixTemplate

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3263]
**Describe the bug**
Floating label text overlapping the TextBox and TextBoxPrefixTemplate demonstrated with kendo icon and button.

**To Reproduce**
https://stackblitz.com/edit/floatlabel-textbox-icon-workaround-qjkg7a?file=app/app.component.ts

**Expected behavior**
Label text to not overlap the TextBox content

**Workaround**
https://stackblitz.com/edit/floatlabel-textbox-icon-workaround

**Browser**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [89.0.4389.114]

**Comment by Raisolution** [comment]
Fix provided through the new `labelCssClass` and `labelCssStyle` options in `v3.1.0`.
