### ISSUE TITLE
[Grid] Sorting functionality not accessible with the keyboard in a non-navigable Grid

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#3267]
**Describe the bug**
When the Grid is not navigable the end user cannot use the sorting-related features through the keyboard. The header cell and its inner elements, related to sorting, are not focusable.

**Expected behavior**
The end user should be able to access the inner element, related to sorting in the Grid header cells, and trigger the sorting action through the keyboard.

**Comment by Raisolution** [comment]
The behaviour is expected in a non-navigable Grid.
