### ISSUE TITLE
[Calendar] activeViewChange event does not trigger in classic Calendar.

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3269]
**Describe the bug**
When the type of the Calendar is set to 'classic', the activeViewChange event does not trigger when the view is changed.

**To Reproduce**

[StackBlitz example](https://stackblitz.com/edit/angular-tcgydr-sjoi3y?file=app/app.component.ts)

**Expected behavior**
The activeViewChange event should be triggered and run the respective function.

**Comment by dimitar-pechev** [comment]
Not planning on introducing an `activeViewChange` event when in Classic mode. We are looking to add a `navigate` event for the Classic calendar and the MultiViewCalendar (https://github.com/telerik/kendo-angular/issues/2424), and a `scroll` event for the Infinite calendar (https://github.com/telerik/kendo-angular/issues/2663). The `activeViewChange` event will subsequently be deprecated.

**Comment by dimitar-pechev** [comment]
Misread the event name as `activeViewDateChange`, sorry. Reopening the thread, and we'll provide a fix for this soon.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by gkarapeev** [comment]
Fix available in version [5.2.0](https://www.telerik.com/kendo-angular-ui/components/dateinputs/changelog/#9835b6f2-36f0-5d16-b8ad-398e09b7bb03)
