### ISSUE TITLE
Grid: Paging doesn't refresh / reset?

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#327]
It's similar to the issue #308.

My issue is:
- Grid loads 80 records
- I navigate to the last page
- Grid loads new data with 14 records.
- Grid shows no data and pager shows

> 61 - 14 of 14 items
- I navigate to the first page -> pager is correct, data is shown

I'm not sure if this is an issue or do I have to handle that myself?
I'm using _@progress/kendo-angular-grid@^0.16.2_

**Comment by rkonstantinov** [comment]
Indeed, as you as developer is in charge for the skip/take state, it will be required to manually set/reset the skip in such situations.
