### ISSUE TITLE
[Splitter] uses role="splitter"

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3270]
**Describe the bug**
The Splitter component adds the role="splitter" attribute to \<kendo-splitter\>.

**To Reproduce**
Please see the example from the following article:
https://www.telerik.com/kendo-angular-ui/components/layout/splitter/

**Expected behavior**
The role="splitter" shouldn't be added.

**Workaround**
Use a custom directive with selector kendo-splitter to remove the role attribute:
https://stackblitz.com/edit/angular-quvr5h?file=app%2Fcustom.directive.ts

**Comment by mbechev** [comment]
Closing this as a duplicate of #3266
