### ISSUE TITLE
[DropDowns] RemoveTagEvent is missing from the exports

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3271]
**Describe the bug**
RemoveTagEvent is missing from the exports.

**Expected behavior**
To be able to import it from: import { RemoveTagEvent } from '@progress/kendo-angular-dropdowns';

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by gkarapeev** [comment]
Released with version [5.3.0](https://www.telerik.com/kendo-angular-ui/components/dropdowns/changelog/#1be0970a-a5e5-50dc-84e2-b0092d659a5e)
