### ISSUE TITLE
[DropDowns] Combobox suggests text from the options in the popup

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3272]
**Describe the bug**
Combobox suggests text from the options in the popup even if allowCustom is set to true

**To Reproduce**
Open it in StackBlitz https://stackblitz.com/edit/angular-rmhgft
Click on the dropdown arrow to see the unwanted behavior

**Expected behavior**
To not suggest new text unless the user starts typing.

**Comment by JoomFX** [comment]
It is the expected behavior.
Since the `LOREM` is part of the `LOREM-IPSUM` text, the later item is being auto suggested when the popup opens.
