### ISSUE TITLE
[Layout] StepperStepTemplate not working correctly with input element

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3273]
**Describe the bug**
The StepperStepTemplate content is wrapped in an anchor tag, which prevents the expected behavior of input elements, placed within the template
Worth mentioning Chrome and Firefox experience different default behaviors with this bug and they are not considered correct

**To Reproduce**
https://stackblitz.com/edit/angular-izukrf-thr8um?file=app%2Fapp.component.ts

**Expected behavior**
Input field to work properly in theStepperStepTemplate

**Comment by Raisolution** [comment]
Documented as part of the Stepper templates article.
