### ISSUE TITLE
[Scheduler] Agenda View shows an event as all day

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3274]
**Describe the bug**
When displaying an event that starts at 00:00 in one day and ends on 00:00 in the next day then the event in the second day is displayed as all day. That is inconsistent with the behavior of the other views like month and day.
Set the event `allDay` property to true to see the undesired behavior.

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-gyhn6r-tzduav?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The "Bowling Tournament" event in the Agenda view should be displayed as all day only for 10 Jun 2021.

**Comment by tswetti** [comment]
Fixed in [v15.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.0.0)
