### ISSUE TITLE
[Upload] error is thrown when concurrent is set to false and upload unallowed file

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3276]
**Describe the bug**
An error is thrown when the [concurrent ](https://www.telerik.com/kendo-angular-ui/components/uploads/upload/file-processing/#toc-sequential-upload) property is set to _false_ and an unallowed file is uploaded.

![image](https://user-images.githubusercontent.com/33104481/115369520-dbeddb00-a1d0-11eb-8c6d-dd7847376ed5.png)

**To Reproduce**
Upload an unallowed file and check the console.
https://stackblitz.com/edit/angular-zamg8k?file=app/upload.component.ts

**Comment by Raisolution** [comment]
Fix is available in `v7.1.4` of the `kendo-angular-upload` package.
