### ISSUE TITLE
[ComboBox] Custom value does not clear when allowCustom is set to false

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3278]
**Describe the bug**
Upon setting the allowCustom property to false, the custom value in the ComboBox does not clear when out of focus.

**To Reproduce**

[StackBlitz example](https://stackblitz.com/edit/angular-ho6ueq?file=app/app.component.ts)

1. Focus on the combobox
2. Press Alt + Arrow Down key to open the dropdown for selection
3. Press Arrow Down key to select "Small"
4. Press "a" key to change the value to "Smalla"
5. Press Tab key to move focus away

**Expected behavior**
The custom value should disappear once the ComboBox is out of focus

**Comment by JoomFX** [comment]
No longer reproducible.
