### ISSUE TITLE
Adding Active class to selected menu till Parent layer

### ISSUE THREAD

**Issue by niranjan1991** [telerik/kendo-angular#3279]
Hello Team,

I am trying to add an active class to the selected option till the parent Layer.
But I am failed to do that.
Requesting to find below link where you can find kendo menu with multiple layer menus.

https://stackblitz.com/run/?file=app%2Fmenu-items.ts

I hope I will get help add an active class from the support end.

Thanks
Niranjan Pawar

**Comment by mbechev** [comment]
Hi Niranjan,

This repository is for bug reports only. Please [_open a support ticket_](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
