### ISSUE TITLE
Setting data for Grid via forms

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#328]
From what I see currently using `formControlName="jobs"` is not supported by the grid. Using that for a grid inside a reactive form gives the following error:
```
No value accessor for form control with name: 'jobs'
```

**Comment by rusev** [comment]
Yes, using `formControlName` directive will not work as the edit template is processed as part of the application instead of the Grid edit form. 

This is one of the reasons for using `formControl` directive in the edit template in our examples.

You can read more on this here - https://github.com/angular/angular/issues/13761

**Comment by PeterStaev** [comment]
Hey @rusev , I'm not sure I understand your comment. Can you provide a working example where the grid items is set via forms?

**Comment by rusev** [comment]
What I meant is that you should be using `formControl` instead of `formControlName` in the column editor template:

```
<kendo-grid-column field="ProductName" title="Product Name">
    <ng-template kendoGridEditTemplate let-formGroup="formGroup">
       <input [formControl]="formGroup.get('ProductName')" class="k-textbox"/>
    </ng-template>
</kendo-grid-column>
```
Example - http://plnkr.co/edit/jPAqlUKpms1BI7p15szW?p=preview

Isn't that what you mean?

**Comment by rusev** [comment]
On second thought setting `formControlName="jobs"` directly on the Grid component, i.e:

```
<kendo-grid formControlName="jobs" ...>
  ...
</kendo-grid>
```
will not work as the Grid doesn't implement [ControlValueAccessor](https://angular.io/docs/ts/latest/api/forms/index/ControlValueAccessor-interface.html) interface.

**Comment by PeterStaev** [comment]
@rusev , to your last comment, this is exactly what I want to achieve - set the items in the grid with `formControlName`.

**Comment by rusev** [comment]
The Grid is not meant to be `ControlValueAccessor`. Binding the component should be implemented through the `data` property.
