### ISSUE TITLE
Provide a way to translate the "Today" message of the DatePicker inside Recurrence editor

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3286]
**Describe the bug**
Currently, there is no option in [kendo-scheduler-messages](https://www.telerik.com/kendo-angular-ui/components/scheduler/api/SchedulerCustomMessagesComponent/) to translate the **TODAY** message of the DatePicker rendered inside the Recurrence editor:

![image](https://user-images.githubusercontent.com/33104481/116360907-137c0900-a809-11eb-92a6-370c31253dde.png)

**To Reproduce**
https://stackblitz.com/edit/angular-tyyzyx

A similar issue was fixed in the past, but for **TODAY** message in Scheduler DatePicker [#2262](https://github.com/telerik/kendo-angular/issues/2262)

**Comment by mbechev** [comment]
The following messages couldn't be translated as well:

![image](https://user-images.githubusercontent.com/33104481/177955576-31c73c53-2ff0-493c-b256-eae5010acc9f.png)

And all tooltips of the input controls like:
![image](https://user-images.githubusercontent.com/33104481/177955739-605c5708-2eb3-4ba3-b1e0-2d21155277b0.png)

![image](https://user-images.githubusercontent.com/33104481/177955846-0c02ee59-94fa-4ca0-9c11-fb3de489deb2.png)

The standalone components provide the necessary properties to customize the **title** attribute:
- [`toggle`](https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DatePickerCustomMessagesComponent/#toc-toggle)  for the TimePicker and DatePicker.
- [`increment` and `decrement`](https://www.telerik.com/kendo-angular-ui/components/inputs/api/NumericTextBoxCustomMessagesComponent/#toc-inputs) to customize the NumericTextBox title attribute.

**Comment by tswetti** [comment]
Fixed in [v15.1.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.1.0)
