### ISSUE TITLE
[DateTimePicker] control size

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3288]
Currently there isn't an option that allows to change the size of the [DateTimePicker](https://www.telerik.com/kendo-angular-ui/components/dateinputs/datetimepicker/). The size could be changed when the component should be displayed on a smaller screen size. We could think of an enhancement that allows to control the size or a workaround based on CSS.

**Comment by iamfahimshahriar** [comment]
hello svetq, may i know if there is any update on this issue.
