### ISSUE TITLE
SeriesHoverEvent not emitting 'point' object

### ISSUE THREAD

**Issue by jiveshrelhan** [telerik/kendo-angular#329]
SeriedHoverEvent (kendo-angular-charts) on chart not emitting point object like before.
Release 0.5.3
![capture](https://cloud.githubusercontent.com/assets/8507036/23302481/dffdcab0-fab4-11e6-9fc2-4220021a767b.PNG)
Newer Release: 0.16.1
![capture3](https://cloud.githubusercontent.com/assets/8507036/23302678/beb8b710-fab5-11e6-8242-e6c92d0e626e.PNG)

Fix: 
**Change in series-hover-event.d.ts**
![image](https://cloud.githubusercontent.com/assets/8507036/23302747/1fa5502e-fab6-11e6-8e00-a43c3af56040.png)
**In Seres-hover-event.js**
![image](https://cloud.githubusercontent.com/assets/8507036/23302786/4cc712d6-fab6-11e6-9dec-007cd40d0a06.png)

Kindly merge fix into master.

**Comment by danielkaradachki** [comment]
Could you clarify which fields do you need from the point?

**Comment by jiveshrelhan** [comment]
I need "point.options.color" property to map in the application. I cannot find any other object property for color which is proving the same result.

**Comment by danielkaradachki** [comment]
Thanks for clarifying. We will add the point to the event argument in the next patch.
