### ISSUE TITLE
RTL direction not changed dynamically

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3293]
**Describe the bug**
When the direction is changed dynamically, if a component is not initialized at the time, its direction does not update.

**To Reproduce**
1. Click the "Change text direction" button. (We see that the initialized `ComboBox` changes its direction)
2. Click the "Show Popup" 

Example: https://stackblitz.com/edit/angular-ekxit4

**Expected behavior**
All Kendo components inside the popup should be initialized with the up-to-date direction.

**Actual behavior**

https://user-images.githubusercontent.com/18744873/117140682-5b290480-adb6-11eb-8d14-09bbe0569502.mov

**Comment by tsvetomir** [comment]
Fixed in the latest [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `@progress/kendo-angular-l10n`. See [updated snippet](https://stackblitz.com/edit/angular-ekxit4-qn1yqs).

**Comment by Raisolution** [comment]
Fix available in `v3.0.2`
