### ISSUE TITLE
Add option to disable node prefetching when paging is enabled

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#3296]
## I'm submitting a...
* Suggestion for improvement  

## Current behavior
The TreeList fetches all child nodes when [Paging](https://www.telerik.com/kendo-angular-ui/components/treelist/paging/) is enabled. This is needed to obtain the total items count, but is not strictly necessary for the pager to function.

## Expected behavior
The [pager settings](https://www.telerik.com/kendo-angular-ui/components/treelist/api/PagerSettings/) should provide an option to disable the counting of child nodes. For example:

```html
<kendo-treelist [pageable]="{ countChildren: false }">
</kendo-treelist>
```

**Comment by tsvetomir** [comment]
The [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the TreeList now include a `countChildren` setting for the pager. See [Pager Settings demo](https://www.telerik.com/kendo-angular-ui-develop/components/treelist/paging/#toc-pager-settings).

**Comment by Raisolution** [comment]
The feature is available in the latest official versions of the TreeList package.
