### ISSUE TITLE
[Datepicker] .k-state-disabled class is absent when calendar type is 'classic'

### ISSUE THREAD

**Issue by doctorssm** [telerik/kendo-angular#3298]
**Describe the bug**
.k-state-disabled class is absent on <kendo-datepicker> component with [calendarType]="'classic'"

**To Reproduce**

https://stackblitz.com/edit/angular-iqvuen-nsufpv?file=app/app.component.ts

**Expected behavior**
.k-state-disabled class should be present on disabled td elements

**Comment by gkarapeev** [comment]
Fix shipped with version 5.3.0.
