### ISSUE TITLE
[TextBox] Cursor jumps to the end of the input text on Safari

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3301]
**Describe the bug**
Cursor jumps to the end of the input text on Safari when additional text is typed in the beginning or in the middle of an existing text. 

**To Reproduce**

  1. Open this example in Safari https://stackblitz.com/edit/angular-2wyp8j?file=app/app.component.ts.
  3. Type something inside the input field of the TextBox.
  4. Place the cursor at the beginning or somewhere in the middle of the text you typed in.
  5. Type something again.
  6. Observe how the cursor jumps to the end of the input text.

**Expected behavior**
The cursor should stay at the specified place and not reposition itself.

**Browser**
 - Safari

**Comment by Raisolution** [comment]
Fix is available in `v8.0.8` of the `kendo-angular-inputs` package.
