### ISSUE TITLE
Angular 12

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3304]
When does Kendo plan to migrate to the newest version of the used framework? Angular 12 was released few days ago with lots of improvements. It would be nice to be modern.

**Comment by tsvetomir** [comment]
Do you have any specific problems with Angular v12? All components are tested and updated to support it.

**Comment by destus90** [comment]
@tsvetomir my kendo packages are a bit behind the new patch releases and when I had tried to run `ng update @angular/core` I encountered some peer deps errors. For the time being, I see that these errors should be resolved once I update Kendo packages first. I will test it on Monday.
