### ISSUE TITLE
Add option to set number format in pager

### ISSUE THREAD

**Issue by wkit23** [telerik/kendo-angular#3306]
## I'm submitting a...
Suggestion for improvement

## Current behavior
The pager shows the current page number and total number of pages as normal number. 

## Expected behavior
The pager should provide an option to set the number format, and in our case, we need the ability to set the thousand separator (e.g. 10,000 instead of the current 10000). Setting it to based on the localization should be also fine.

**Comment by preslavapetrova1** [comment]
Moved to the FB portal https://feedback.telerik.com/kendo-angular-ui/1557102-add-option-to-set-number-format-in-pager
