### ISSUE TITLE
Virtualization with Local Data

### ISSUE THREAD

**Issue by abercrombiefitch6** [telerik/kendo-angular#3308]
**Describe the issue**
Hi guys,

First of all, I'd like to thank you for the great product that you've created!
I wanted to ask you a question regarding the virtualization with local data. Ever since I have a problem with the mentioned feature when filtering and sorting are enabled (my grid hangs which causes the whole application to hang) as a first debugging step, I wanted to take the Stackblitz sample from the docs and eventually implement a similar behavior there. Sadly, I was unable to. The grid in the Stackblitz sample also seems to be hanging, although the locally hosted one works well.
Can you please give it a try and eventually share what causes the hanging (at least in Stackblitz), is it a bug or just something is misconfigured?

Thanks in advance,
David

**Screenshots**
A link to your topic:
https://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/virtual/
An illustration of the application that has already hanged:
![image](https://user-images.githubusercontent.com/84441903/118782068-62f8a680-b896-11eb-9eba-6fb5914e1309.png)

**Browser**
 - OS: [for example, iOS]
 - Browser Chrome
 - Version 5.0.3

**Additional context**

**Comment by mbechev** [comment]
Hi @abercrombiefitch6, 

Thank you for the provided feedback.

I checked the Grid virtual scrolling demo with local data, but there is no lagging during scroll or filtering. Here is a screencast:
https://screenrec.com/share/AiZeP2zlSL
https://stackblitz.com/edit/angular-vprw3f

This repository is for bug reports only. Please [open a support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
