### ISSUE TITLE
Chart size is not automatically determined when container was not visible during initialization

### ISSUE THREAD

**Issue by Yves-Be** [telerik/kendo-angular#331]
When I'm using a chart on a tab that is not visible (display: none;) when the chart is initialized, the chart size is not adjusted if the tab becomes active:

http://plnkr.co/edit/ur9jS3cUtFKfZXhOa4n3?p=preview

Setting the data again does force the chart to be updated, but I'm not sure if this is the best approach. This solutions as also not always available, as the component itself is agnostic about it's parent components.

**Comment by danielkaradachki** [comment]
Using `ngIf` instead of `display:none` style should fix the problem:

http://plnkr.co/edit/70dnQxkmZdYQSgXN25Z0?p=preview

Unfortunately, there isn't a way to detect that an element was shown or hidden without significant performance issues. 

We will also consider exposing a resize method.

**Comment by tsvetomir** [comment]
This should be fixed now. Please run `npm update` and give it a shot.

**Comment by Yves-Be** [comment]
It seems to be working, there's only a slight delay between making it visible and it resizing by itself.
However, updating the package did introduce a new problem. During compilation, I get the following error:
```
...\node_modules\@progress\kendo-charts\dist\es\chart.d.ts
(5,5): error TS7010: 'setOptions', which lacks return-type annotation, implicitly has an 'any' return type.
```
It compiles fine, but webpack prevents auto reload when there were compile errors.

**Comment by tsvetomir** [comment]
The resizing is intentionally throttled to keep the performance acceptable. Will look into the error, thanks.

**Comment by tsvetomir** [comment]
The type error should be fixed in the latest patch.

**Comment by Yves-Be** [comment]
Can confirm it's fixed
