### ISSUE TITLE
[TreeView] Add automatic scroll during drag-and-drop

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#3310]
Currently, the TreeView will not scroll the content during drag-and-drop when the end of the viewport is reached even if there are more items beneath or above the visible part of the TreeView. Especially a problem when using the feature on a mobile device, where you cannot scroll and drag at the same time. Would be a nice enhancement for both mobile and desktop devices.

In the below example, dragging an item to the bottom of the screen should automatically scroll the content:
https://stackblitz.com/edit/angular-ycujqt-rlpuz6

**Comment by ipeshev** [comment]
Feature available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by dimitar-pechev** [comment]
Shipped with **v5.4.0** and enabled by default. [Here's a docs article](https://www.telerik.com/kendo-angular-ui-develop/components/treeview/drag-and-drop/#toc-auto-scrolling) on the new feature.
