### ISSUE TITLE
[Dropdowns] ComboBox suggestion now working properly

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3311]
**Describe the bug**
When the first suggestion is highlighted and removed, thereafter if you type a single letter like "b", the suggestion autofill doesn't work.

**To Reproduce**
1. Type 'au' and you get Austria
2. Highlight and deleted it
3. type 'b' and the suggestion doesn't automatically fill. It only highlights the matched item
https://stackblitz.com/edit/angular-py1bnr?file=app/app.component.ts
This bug was also tested in a local project with Angular 11 and the latest package of the DropDowns

**Expected behavior**
When the user removes the first highlighted suggestion and types a letter after matching and suggesting the other item.

example with latest versions: https://stackblitz.com/edit/angular-rmhgft-3qv227?file=src%2Fapp%2Fapp.component.ts

**Screenshots**
https://imgur.com/a/7AlYdvf

**Comment by JoomFX** [comment]
No longer reproducible.
