### ISSUE TITLE
An error is thrown when ToolBar is destroyed with an opened overflow popup 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3315]
**Describe the bug**
The following error is thrown when the ToolBar overflow popup is opened and the component is destroyed:

![image](https://user-images.githubusercontent.com/33104481/119145924-cb8c8280-ba52-11eb-903c-350fb6a1223b.png)

### Destroying the ToolBar when using TabStrip

The issue occurs when the ToolBar is destroyed due to a tab change using TabStrip

https://screenrec.com/share/FiewpQrZ75

**To Reproduce**
https://stackblitz.com/edit/angular-n6hrmu-mczwfn

**Workaround**
Set [keepTabContent ](https://www.telerik.com/kendo-angular-ui/components/layout/api/TabStripComponent/#toc-keeptabcontent)option to _true_:

https://stackblitz.com/edit/angular-n6hrmu-rbdqb4

### Destroying the ToolBar on route change

**To Reproduce**
1. Click  _First_ button.
2. Resize the ToolBar until the "more options" button (three dots) appears.
3. Open the overflow popup.
4. Click on "_Second_" button to load a different module and component, without closing the popup.

https://stackblitz.com/edit/kendo-broken-toolbar-kcxnnj

**Comment by Raisolution** [comment]
Fix available in `v6.0.0` of the Toolbar package.
