### ISSUE TITLE
Provide all Kendo packages/libraries in partial-Ivy format

### ISSUE THREAD

**Issue by IT-CASADO** [telerik/kendo-angular#3317]
Please provide all Kendo packages/libraries in partial-Ivy format.

With this format we can use PNPM or YARN 2 in PnP mode.

See also:
- [ngcc throw error if I use KendoUI and pnpm](https://github.com/angular/angular/issues/41372)
- [Upcoming improvements to Angular library distribution](https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4)
- [Transitioning libraries to partial-Ivy format](https://angular.io/guide/creating-libraries#transitioning-libraries-to-partial-ivy-format)

**Comment by tsvetomir** [comment]
We plan to ship the libraries in the new Ivy format starting with Angular 13. We'll post a comment here when preview versions become available.

Please note that the new format is incompatible with Angular 11 and earlier. We'll open a new LTS distribution channel to publish updates compatible with these versions.

**Comment by tsvetomir** [comment]
Just a quick note that Angular v13 is fully supported via ngcc. We're also working on the transition to Ivy packages with more details to follow next week.

**Comment by tsvetomir** [comment]
Tracking the migration to Ivy in #3502.
