### ISSUE TITLE
[ Editor ] kendoEditorDeleteColumnButton does not correctly delete last table column

### ISSUE THREAD

**Issue by gkarapeev** [telerik/kendo-angular#3319]
**Summary:**
Attempt to delete last column of a table in the Editor component using the **kendoEditorDeleteColumnButton** directive, actually deletes the second-to-last column.

**Instructions to reproduce:**
- Make a 2x2 table in the Editor component
- Place your cursor in the last cell of any row
- Click the 'Delete Column' button

**Current behavior:**
- Column 1 is deleted

**Expected behavior:**
- Column 2 is deleted

**Stackblitz demo:**
https://stackblitz.com/edit/editor-table-column-delete-bug?file=app/app.component.ts

**Comment by gkarapeev** [comment]
Closed this and re-opened as public here: https://github.com/telerik/kendo-angular/issues/3319

**Comment by dtopalov** [comment]
fixed in v. `2.3.1` of the `@progress/kendo-angular-editor` package
