### ISSUE TITLE
DropDownList with complex values and default item does not select items when user types

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#332]
If you have a drop down with complex values and a default item if the user starts typing the widget selects the default item, instead of selecting the correct one in the drop down. If you remove the default item the widget correctly selects the items. 

Here is a [demo](http://plnkr.co/edit/aXtWUKeEJGIwMiTPrqeG?p=preview). Focus the drop down and type "l" to try and select "Large". The widget will select the default item.

**Comment by valchev** [comment]
@PeterStaev thanks for bringing this to our attention.

The issue occurs because when the defaultItem is set, the list items indexes are not calculated correctly. The issue will be fixed in a few days.
