### ISSUE TITLE
[TreeView] Expose drag-and-drop args as drop hint template variables

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#3320]
[**Drag-and-Drop**] Unlike the [drag clue](https://www.telerik.com/kendo-angular-ui/components/treeview/api/DragClueTemplateDirective/), the [drop hint](https://www.telerik.com/kendo-angular-ui/components/treeview/api/DropHintTemplateDirective/) template does not expose information about the current source and destination items.

Would be useful to expose this information if certain drop positions are prohibited by custom logic. If the source and destination items are available in the drop hint template as context variables, the user of the code will be able to control whether the drop hint gets rendered at certain positions or not.

**Comment by ipeshev** [comment]
Feature available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).
