### ISSUE TITLE
[Sortable] Dragging the last element from one pallet to another doesn't work properly 

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3321]
**Describe the bug**
If a pallet has one element inside (also happens if there are five elements you drag away 4 and leave one) and is being dragged to another pallet without dropping and dragged back to the original empty pallet in throws an error and breaks the UI. Also, duplicates the element as seen in the screenshots.

**To Reproduce**
Move FireBrick from palette D to any other, drop it, and move it back to palette D. Another way is to drag it to palette C without dropping it and move it back to palette D.
Left only one element in palette D for easy reproduction:
https://stackblitz.com/edit/angular-kw7iqr?file=app/app.component.ts

https://www.telerik.com/kendo-angular-ui/components/sortable/templates/

**Expected behavior**
The component to work properly in the template when dragging the last element around the other palettes and to return it without any issues

**Screenshots**
https://imgur.com/a/PZhkTeP

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by tapopov** [comment]
Fixed in `kendo-angular-sortable@v4.0.3`
