### ISSUE TITLE
[MultiColumnComboBox] Extra column added when dropdown size is greater then the width of the columns

### ISSUE THREAD

**Issue by mojo722** [telerik/kendo-angular#3326]
**Describe the bug**
When the width of the kendo-multicolumncombobox is set to a width greater than the total width of the kendo-combobox-columns, an extra column is added to the left of the first column.  The column header scale correctly.

**To Reproduce**

  If possible, share a runnable snippet on StackBlitz by following the steps below:

  1. Find an example in [the documentation](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multicolumncombobox/)
  2. Open the StackBlitz for the first example by clicking the **EDIT IN STACKBLITZ** button.
  3. Modify the snippet by updating the style for the kendo-multicolumncombobox and setting the width to greater than 600px.
  4. Open the MultiColumnComboBox and note that the extra column is present to the left and that the headers are scaled correctly

**Expected behavior**
Columns are scaled correctly, same as the header

**Browser**
 - OS: Windows 10 Pro x64
 - Browser: Chrome
 - Version: 90.0.4430.212

**Comment by Raisolution** [comment]
Issue seems to not be reproducible with the current version. Feel free to ping us, if the problem happens again.
