### ISSUE TITLE
[Grid] kendoGridSelectionCheckbox directive causes an error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3327]
**Describe the bug**
Using the kendoGridSelectionCheckbox directive causes the following error:
TypeError: Cannot read property 'view' of undefined

Removing the kendoGridSelectionCheckbox directive or setting the [cell ](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectableSettings/#toc-cell)property to false resolves the issue:

    <kendo-grid
      [selectable]="{
        enabled: true,
        mode: 'multiple',
        cell: false
      }"

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-zx7vdv-r3rget?file=app/app.component.ts

Try checking any checkbox to reproduce the error.

**Comment by Raisolution** [comment]
The described behaviour is expected, as checkbox selection should not be used along with cell selection.

Documentation is available at https://www.telerik.com/kendo-angular-ui/components/grid/selection/cell-selection/#toc-multiple-cells-selection
