### ISSUE TITLE
Scheduler Edit erroring in Telerik website examples

### ISSUE THREAD

**Issue by aa5252aa** [telerik/kendo-angular#3328]
**Describe the bug**
The Scheduler examples on the Telerik website appear to be erroring when I try to edit events...specifically when I double click on an existing event.  In the browser debug console, it says "EditMode not defined".

If I click "Edit in Stackblitz" on any of the examples, once it loads it does not recognize EditMode.  Was a library or version updated or missing?

**To Reproduce**
Navigate here:

https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-reactive-forms/

Then in any of the Scheduler examples, double click on an existing Event, then select an option from the Edit popup (does not matter which), then nothing will happen, and in the debug console, the following error appears:

ERROR ReferenceError: EditMode is not defined
    at AppComponent.createFormGroup (main.js:103)
    at ir.createModel (kendo-angular-scheduler.js:1)
    at b._next (kendo-angular-scheduler.js:1)
    at b.__tryOrUnsub (merge-b00f5bfe.js:1)
    at b.next (merge-b00f5bfe.js:1)
    at l._next (merge-b00f5bfe.js:1)
    at l.next (merge-b00f5bfe.js:1)
    at e.__tryOrUnsub (index-119cb89d.js:1)
    at e.next (index-119cb89d.js:1)
    at e._next (index-119cb89d.js:1)

**Expected behavior**
Shouldn't an Edit window open?

**Browser**
 - OS: Windows 10
 - Browser: Edge
 - Version 90.0.818.56 (Official build) (64-bit

**Comment by Raisolution** [comment]
Hello @aa5252aa ,

Thank you for reporting the problem. A fix is available in the develop version of the site and will soon be published live too
https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/editing/editing-reactive-forms/
