### ISSUE TITLE
[Grid][KB Navigation] Grid cell is not focused after filtering

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#3329]
**Describe the bug**
When a Grid cell is focused, and after this the data is filtered so that the data contains less items than the index of the row the last focused cell was in, the Grid table area does not receive focused when tabbed into.

**To Reproduce**

  1. Open https://stackblitz.com/edit/angular-xqswy5-zqeqkb?file=app/app.component.ts
  2. Click on row 5 (Ruthi Baldini)
  3. Click in the custom toolbar filtering input element
  4. Type "q" so that only 4 rows of data remain
  5. Tab 3 times - the focus goes through the toolbar buttons and the third tab is supposed to focus a cell in the Grid, but does not.

**Expected behavior**
A cell in the Grid is focused when tabbed into regardless of the currently rendered items.

**Possible workarounds**
- Create a custom directive that overwrites the current NavigationService behavior, e.g.:

https://stackblitz.com/edit/angular-xqswy5-6umdsz?file=app%2Fpatch.directive.ts

- Focus the desired available Grid cell manually after tabbing out of the last toolbar element, e.g.:

https://stackblitz.com/edit/angular-xqswy5-fhhtaw?file=app%2Fapp.component.ts

**Comment by dtopalov** [comment]
Fix is available in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the @progress/kendo-angular-grid package.

**Comment by Raisolution** [comment]
Fix available in `v5.2.0`
