### ISSUE TITLE
Null exception in utils.js

### ISSUE THREAD

**Issue by hansverriest** [telerik/kendo-angular#333]
I got a null reference exception on document.body in kendo-angular-popup/dist/es/utils.js line 69 👍     document.body.appendChild(parent);

I have a workaround by changing line 62 from 
    if (!isDocumentAvailable()) {
to
    if (!isDocumentAvailable() || !document.body) {

**Comment by ggkrustev** [comment]
Hi @hansverriest, could you share more details about the issue? For instance:
- what is the context where you observe this error - is it in browser or testing suite?
- could you provide a repro demo?

As a side note, the method is called only once after script evaluation to determine whether the popup should work with different stacking context. The information of this method is important and if it breaks in production then we will need to investigate the issue more thoroughly.

**Comment by hansverriest** [comment]
Hello,

 

The error I get is inside a big project so it’s a bit difficult to reproduce a simple example but the setup is as follows :

 

We use webpack, so this is the index.html (nothing special)

 

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" >

    <title><%= htmlWebpackPlugin.options.title %></title>

    <meta name="description" content="<%= htmlWebpackPlugin.options.title %>">

    <% if (webpackConfig.htmlElements.headTags) { %>

    

    <%= webpackConfig.htmlElements.headTags %>

    <% } %>

 

    

    <base href="<%= htmlWebpackPlugin.options.metadata.baseUrl %>"> 

    <link rel="stylesheet" type="text/css" href="./assets/css/bootstrap.min.css" />

    <link rel="stylesheet" type="text/css" href="./assets/css/theme.css" />

    <link rel="stylesheet" type="text/css" href="./assets/css/primeng.css" />

    <link rel="stylesheet" type="text/css" href="./assets/css/site.css" /> 

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet">

</head>

<body>

    <app>

        Loading...

    </app>

    <% if (htmlWebpackPlugin.options.metadata.isDevServer && htmlWebpackPlugin.options.metadata.HMR !== true) { %>

    

    <script src="/webpack-dev-server.js"></script>

    <% } %>

 

 

</body>

</html>

 

In my app.module I include the necessary kendo components :

 

//kendo 

import { ChartsModule } from '@progress/kendo-angular-charts';

import 'hammerjs';

 

In the html of my component I have this :

 

 

 

<div id="pieChartsContainer">

    <div class="row" style="height: 300px">

        <div class="col-xs-5">

            {{'MachineBreak' | translate}}

            <br />

            <button type="submit" class="btn red" (click)="onClickAddFaultButton('MB')"><span class="fa fa-plus"></span></button>

            <kendo-chart *ngIf="chartMBVisible" [seriesColors]="seriesColors" (seriesClick)="onSeriesClick($event)">

                <kendo-chart-legend [visible]="false"></kendo-chart-legend>

                <kendo-chart-series-defaults>

                    <kendo-chart-series-defaults-labels [visible]="true" [color]="seriesDefaultsLabelsColor" [content]="seriesDefaultsLabelsContent">

                    </kendo-chart-series-defaults-labels>

                </kendo-chart-series-defaults>

                <kendo-chart-series>

                    <kendo-chart-series-item type={{type}}

                                             [data]="data"

                                             field="value"

                                             categoryField="category">

                    </kendo-chart-series-item>

                </kendo-chart-series>

            </kendo-chart>

        </div>

 

And in my component there is nothing special but when I start it in the browser (chrome) I don’t even get tot he constructor in my component. It fails at startup :

 



 

 

Regards,

Hans.

 

 

 

 

 

Van: Georgi Krustev [mailto:notifications@github.com] 
Verzonden: maandag 27 februari 2017 13:42
Aan: telerik/kendo-angular <kendo-angular@noreply.github.com>
CC: hansverriest <hans.verriest@telenet.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [telerik/kendo-angular] Null exception in utils.js (#333)

 

Hi @hansverriest <https://github.com/hansverriest> , could you share more details about the issue? For instance:

*	what is the context where you observe this error - is it in browser or testing suite?
*	could you provide a repro demo?

As a side note, the method is called only once after script evaluation to determine whether the popup should work with different stacking context. The information of this method is important and if it breaks in production then we will need to investigate the issue more thoroughly.

**Comment by hansverriest** [comment]
![image](https://cloud.githubusercontent.com/assets/6664926/23363434/ebf69520-fcfa-11e6-91a2-7d53dfe00b61.png)
