### ISSUE TITLE
[TreeList] fetchExcelChildren throws error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3330]
**Describe the bug**
If `fetchExcelChildren` returns [] or null for a root data item there is no issue. However If `fetchExcelChildren` returns [] or null for a child item there is an error that is thrown:
`Cannot read property 'length' of null`

**To Reproduce**
Please see the following example and click the "Export" button:
https://stackblitz.com/edit/kendo-trelist-excel-export-issue

**Comment by Raisolution** [comment]
Fix available in `v5.0.2` of the Treelist package.
