### ISSUE TITLE
[Recurrence Editor] BYSETPOS=1 rule is not removed when switching Repeat On options

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3332]
**Describe the bug**
When selecting **Monthly** repeat, the recurrence rule looks like this:
```FREQ=MONTHLY;BYMONTHDAY=11``` (11 is the current day)

Choosing Repeat on **First** **Friday**, from the DropDownList options, creates:
```FREQ=MONTHLY;BYDAY=1FR```

![image](https://user-images.githubusercontent.com/33104481/121674722-17af6d80-cabb-11eb-858d-6439519c7b4e.png)

If we chose **Last Day** the recurrence rule gets:
```
FREQ=MONTHLY;BYDAY=-1FR
FREQ=MONTHLY;BYDAY=-1FR;BYSETPOS=-1
FREQ=MONTHLY;BYDAY=SU,MO,TU,WE,TH,FR,SA;BYSETPOS=-1
```
which is correct. However changing back to **First Friday**, does not remove the BYSETPOS=1 rule. Instead, the returned recurrence rule is:
```
FREQ=MONTHLY;BYDAY=SU,MO,TU,WE,TH,FR,SA;BYSETPOS=1
FREQ=MONTHLY;BYDAY=1FR;BYSETPOS=1
```

**To Reproduce**
1. Select **Monthly**.
2. Select the second _Repeat on_ radio button (First Friday is selected /the Friday is the current day/).
3. Choose **Last** from the first dropdown and **Day** from the second one.
4. Select First Friday again, the BYSETPOS=1 is not removed

https://stackblitz.com/edit/angular-qea1uc-v3xtxj

Additional example with screen recording:
https://stackblitz.com/edit/angular-b4dwhd-7ysbmo?file=src%2Fapp%2Fapp.component.ts
![chrome_yHdyAUqapc](https://github.com/telerik/kendo-angular/assets/49076727/1cf79224-10b5-4462-bf30-85838ddf03a9)

**Comment by Raisolution** [comment]
Fix available in `v.17.1.0`
