### ISSUE TITLE
[TreeView] using the async pipe causes an error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3338]
**Describe the bug**
When passing an Observable to the nodes property of the TreeView and resolving it with the async pipe:
```
    <kendo-treeview
      [nodes]="categories | async"
```
then the following error is thrown:
`ERROR TypeError: Cannot read property 'slice' of null`

**To Reproduce**
Please see the following example:

https://stackblitz.com/edit/angular-5tzopj-rgb76y?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by tapopov** [comment]
Fixed in v5.4.1
