### ISSUE TITLE
[TreeView] SelectionMode is missing from the imports

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3339]
**Describe the bug**
SelectionMode is missing from the imports

**Expected behavior**
To be able to import it from: import { SelectionMode} from '@progress/kendo-angular-treeview';

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by dimitar-pechev** [comment]
Released with `@progress/kendo-angular-treeview@5.4.0`.
