### ISSUE TITLE
[MultiSelectTree] Select/check all items functionality

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3340]
Would be useful to have an option to select/check all items in the MultiSelectTree similar to jQuery
https://demos.telerik.com/kendo-ui/dropdowntree/checkboxes

**Comment by Godrules500** [comment]
Any idea if this is being worked on and will be released in the near future?

**Comment by stnikolova** [comment]
@Godrules500 The implementation of this enhancement hasn't started yet, however it is part of our development plans for the next couple of months. Usually, we abstain from giving exact timelines, as our immediate development plans depend on various factors such as new components, features, and prioritizing bug fixes. Please keep tracking this issue for the latest updates.

**Comment by gkarapeev** [comment]
The feature is tested and available in the latest dev version - v5.5.0-dev.202111011140

**Comment by gkarapeev** [comment]
The feature is available in version 5.5.0
