### ISSUE TITLE
Column headers are not aligned when sorting

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3341]
**Describe the bug**
Aligning the column headers on the right, by setting the **headerStyle** property:
```html
<kendo-grid-column
        field="ProductName"
        title="Name"
        [headerStyle]="{ 'text-align': 'right' }"
      >
</kendo-grid-column>
```
is ignored when the sortable feature is enabled.

**To Reproduce**

https://stackblitz.com/edit/angular-gsbegq

**Workaround**
You can use the following CSS to align the title when sortable is enabled:
```css
.k-cell-inner .k-link {
  display: initial;
}
```
https://stackblitz.com/edit/angular-gsbegq-bsbarx

**Additional context**
KendoReact Grid works as expected in this scenario:

https://stackblitz.com/edit/react-h1kmww

**Comment by Raisolution** [comment]
The described behavior is expected due to the different rendering in the above scenario.
