### ISSUE TITLE
Unable to insert table when iframe is false

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3350]
**Describe the bug**
Setting the **iframe** option to _false_  affects the Insert Table feature of the Editor:

https://screenrec.com/share/urHK9ObFXW

**To Reproduce**
[editor-latest.zip](https://github.com/telerik/kendo-angular/files/6691997/editor-latest.zip)
1. Download and unzip the project.
2. Run **npm install**.
3. Execute **ng serve**.

**Comment by dtopalov** [comment]
In this case the Editor output is expected and correct. When the `iframe` mode is turned off, the developer has full control over the styling, applied to the Editor content. The default browser behavior when rendering an empty table is thus observed:

https://stackblitz.com/edit/angular-nnxvr6?file=app%2Fapp.component.ts

The table is inserted, but not visible, same as if identical HTML is placed somewhere on the page outside of the Editor.

If there is some styling applied to the Table elements (for example - visible borders of the TD elements), this is also correctly reflected in the Editor content area:

https://stackblitz.com/edit/angular-eab8cx?file=index.html
