### ISSUE TITLE
[Editor] Using shortcuts like Ctrl + b or Ctrl + i to trigger formatting throws an error

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3352]
**Describe the bug**
Using ctrl + b or ctrl + i to trigger formatting while writing throws an error (RangeError: Applying a mismatched transaction) and breaks the Editor's functionality. This only happens when using the shortcut button combination.

**To Reproduce**
Go to: https://stackblitz.com/edit/angular-be2sj4?file=app/app.component.ts
1. Press Ctrl + b -> space button -> Ctrl + b, and the error appears and breaks the application in StackBlitz.
2. Locally is almost the same behavior, but the application continues to run, and the formatting cannot be removed with the shortcut unless the text is selected.
Short video: http://somup.com/cr10X2q7HE

**Expected behavior**
The Editor to work without any issues like for example, the Kendo UI for React Editor.

**Comment by AmanGhatge** [comment]
Getting same error please help in finding the issue.

**Comment by yanmariomenev** [comment]
Fixed is available in the latest version of the Editor component.
