### ISSUE TITLE
[Grid] Detail row expand/collapse icon titles miss localization messages

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3354]
**Describe the bug**
In the messages repo there are no messages added for the detailCollapse and detailExpand titles.

These just need to be added here: 

https://github.com/telerik/kendo-angular-messages/tree/develop/messages/grid

**Comment by dlwhiteman5** [comment]
Is there any way to upvote this bug?

**Comment by Raisolution** [comment]
The localization messages have been added:

https://www.telerik.com/kendo-angular-ui/components/grid/api/CustomMessagesComponent/#toc-detailcollapse
https://www.telerik.com/kendo-angular-ui/components/grid/api/CustomMessagesComponent/#toc-detailexpand
