### ISSUE TITLE
[Grid] When reordering columns the set width is lost

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3357]
**Describe the bug**
When reordering columns the set width is lost. For example, if you set the width of three columns and leave one column without a set width and move that column around it will take the width of the column that was previously in that position.

**To Reproduce**
1. Open https://stackblitz.com/edit/angular-hzwrq2-geuqjh?file=app/app.component.ts
2. Move the "Product Name" column

**Available Workaround**
https://stackblitz.com/edit/grid-reorder-column-width-workaround?file=app/app.component.ts

**Expected behavior**
Persist the original set column width when reordering the columns in the Grid.

**Comment by Raisolution** [comment]
Fix is available in `v6.1.2` of the Grid package.
