### ISSUE TITLE
[Grid] Inconsistent behavior when dynamically changing the `sticky` input property

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3363]
**Describe the bug**
When the `sticky` input property of `<kendo-grid-column>` is changed dynamically, some visual defects appear:

1. Unnecessary empty space (column holder)
2. Column is not sticked

**To Reproduce**
https://stackblitz.com/edit/grid-dynamic-sticky-columns-5nbjcf

1. Stick "ID" column
2. Stick "Category" column
3. Stick "Name" column
4. Try to scroll
**Result**: "Name" column is not sticked.

5. Unstick "ID" column
6. Try to scroll

**Result**: Empty space appear on the left of the "Name" column

Second example - https://stackblitz.com/edit/angular-qy7trz-61zgaw?file=src%2Fapp%2Fapp.component.ts
1. Move supplier id to the first or second column position where the sticky functionality isn't being applied. If the column is moved to the third column then it works.

**Expected behavior**
Columns should be sticked properly.

**Screenshots**
![Screenshot 2021-06-29 at 11 45 01](https://user-images.githubusercontent.com/18744873/123766657-8cfaab00-d8cf-11eb-9ee0-b783bb9dd320.png)
![Screenshot 2021-06-29 at 11 45 22](https://user-images.githubusercontent.com/18744873/123766661-8d934180-d8cf-11eb-9b69-8e18f15950b1.png)

![kN1zrLAOA3](https://user-images.githubusercontent.com/49076727/225858215-39e554c6-ce6f-451f-86c4-51c941b1b299.gif)

**Comment by mbechev** [comment]
Also reported in this forum thread https://www.telerik.com/forums/column-kendo-grid-sticky-property-does-not-change-dynamically

Steps to reproduce the same issue with dynamically generated columns:

https://stackblitz.com/edit/angular-hjbr9g-6qdttz?file=src%2Fapp%2Fapp.component.ts

**ProductID** is sticky initially
1. Make the **ProductName** sticky through the button below the Grid
2. Make the **CategoryName** column sticky again with the respective button
3. Try scrolling the Grid horizontally and see how the sticky state of all three columns isn't persisted.

**Comment by marvhen** [comment]
Please fix this issue, our product really needs this functionality.

**Comment by slavenai** [comment]
Fixed in `v15.4.0` of `kendo-angular-grid` package.
