### ISSUE TITLE
Creating radio buttons with *ngFor, throws an error when using FormField component

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3365]
**Describe the bug**
Modifying [this demo](https://www.telerik.com/kendo-angular-ui/components/forms/forms-guideline/#toc-checkboxes--radiobuttons) from our docs, to create radio buttons dynamically with ***ngFor**, throws an error in Angular version 10-12:

![image](https://user-images.githubusercontent.com/33104481/123931516-3fe30b80-d999-11eb-9497-921b16e320d8.png)

**To Reproduce**
Run the following demo with at least Angular version 10:
https://stackblitz.com/edit/angular-4brxep

Note: The StackBlitz demo utilizes Angular 9, that is why this approach works without any issues.

**Comment by jrdutton** [comment]
Concerned that no one else has come across this issue in three major Angular versions?

**Comment by holger-at-schottel-de** [comment]
We experienced the same restriction when we tried to wrap the FormField component in a custom component using `<ng-content>`.

It would be an great enhancement if the FormField component could be used with `<ng-content>`.

**Comment by Raisolution** [comment]
@holger-at-schottel-de if possible, could you create a stackblitz example, in which the `ng-content` issue is reproducing?
It will help us to resolve the problem(s) faster, thank you in advance.

**Comment by holger-at-schottel-de** [comment]
@Raisolution This is a simplified example to demonstrate what we would like to do: [https://stackblitz.com/edit/custom-formfield?file=app/app.component.ts](https://stackblitz.com/edit/custom-formfield?file=app/app.component.ts)

**Comment by jrdutton** [comment]
That looks like something we could use too. Is the link between the kendo-label and the kendo-textbox not required?

**Comment by holger-at-schottel-de** [comment]
Yes, for full functionality is it required. But to keep it simple I left it out.

**Comment by Raisolution** [comment]
Thank you for the additional details. We will try to handle both problems at the same time, when we get to this issue in the development pipeline.

**Comment by jrdutton** [comment]
Hi @Raisolution, would you be able to give us any indication of timescales? Thank you

**Comment by ciiara** [comment]
The fix for the ngFor issue is available in the latest [dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the @progress/kendo-angular-inputs package

**Comment by Raisolution** [comment]
The fix was published in `v7.3.2`

**Comment by jrdutton** [comment]
Though this is definitely better, it still has a problem. If the radio buttons are dynamically created via an observable, the list that they relate to will initially be empty until such time that the observable returns a list of values from a call to an API (say). With an empty list, the isControlGroup(formControls) function returns false, and an exception is thrown.
