### ISSUE TITLE
[Grid] Provide support for sticky column groups

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3366]
The sticky columns functionality is not working properly when multiheader columns (kendo-grid-column-group) are involved. It would be a nice enhancement to provide support for such scenarios and perform the necessary internal calculations that will ensure locking a group column will be working as expected.

**Comment by dtopalov** [comment]
Reopening this after an internal discussion.

We are tracking a [logged private issue](https://github.com/telerik/kendo-angular-grid/issues/1097) for addressing this limitation of the current implementation, but will update this thread too once the enhancement is released.
