### ISSUE TITLE
[DropDownList/DropDownTree] - Display Checkbox in DropDownList and not display child nodes when clicking the DropDownTree root node in version 5.3.0

### ISSUE THREAD

**Issue by kil5152** [telerik/kendo-angular#3367]
**Describe the bug**

When using DropDownList and DropDownTree with version 5.3 in my Angular version 11.0.6 application, a checkbox is shown next to each drop-down item and drop-down tree's child nodes are not displaying. If I would downgrade to version 5.2, everything looks fine. Please see the screenshots. 

**Expected behavior**

Checkbox should not appear in each drop-down item and tree's child nodes should be expanded when clicking each root node. 

**Screenshots**
**@progress/kendo-angular-dropdowns": "5.3.0"
@progress/kendo-angular-treeview": "^5.3.0"**

![image](https://user-images.githubusercontent.com/5281535/124020768-b9d6bd00-d9b8-11eb-8b3f-23e76e85ecf6.png)

**@progress/kendo-angular-dropdowns": "5.2.0"**
**@progress/kendo-angular-treeview": "5.2.0"** or **@progress/kendo-angular-treeview": "^5.3.0"**

![image](https://user-images.githubusercontent.com/5281535/124021796-fb1b9c80-d9b9-11eb-958e-2a7db141e608.png)

Please advise.

**Comment by ipeshev** [comment]
Hi @kil5152 we wasn't able to reproduce this faulty behavior, would you send us component's code which is used, ideally would be a running code sample - stackblitz. You can [use this one](https://stackblitz.com/edit/angular-73glcj-swhfb8?file=app%2Fapp.component.ts) as a starter.

**Comment by kil5152** [comment]
> Hi @kil5152, we weren't able to reproduce this faulty behavior, would you send us the component's code that is used. Ideally would be a running code sample - StackBlitz. You can [use this one](https://stackblitz.com/edit/angular-73glcj-swhfb8?file=app%2Fapp.component.ts) as a starter.

For DropDownList's checkbox appears in each item, one different between version 5.2.0 and 5.3.0 is that 5.2.0 does not contains `<label>` element. The checkbox is appearing next to each item because of  `<label class="k-checkbox-label">` Please see below screenshot

![image](https://user-images.githubusercontent.com/5281535/125164532-c6010e00-e160-11eb-9946-a2a220a6f156.png)

For DropDownTree node's children not expanding, I observed that `k-display-none` class is added when clicking the root node. If I would remove `display:none !important`, it works fine. Please see blow screenshot.

![image](https://user-images.githubusercontent.com/5281535/125164659-5d666100-e161-11eb-92fd-9f69a21bedab.png)

**Comment by ipeshev** [comment]
Hi @kil5152 we tried to reproduce the issue [using this stackblitz sample](https://stackblitz.com/edit/angular-73glcj-roppc4?file=app%2Fapp.component.ts) , but with no success. We simply can't observe this faulty behavior, could you try reproducing it at your site using above mentioned stackblitz sample ?

**Comment by ipeshev** [comment]
@kil5152 it looks like some awkward style is causing this issue , what is the kendo-themes version used in your app and is there any additional styles loaded ?

**Comment by ipeshev** [comment]
@kil5152 although we were unable to reproduce the faulty behavior with the checkboxes. We managed to produce a fix which ensures, that no unwanted label elements are present in the DOM. As for the hidden children nodes, we are still unable to reproduce it on our site. Could you share with us your component's code in order to see kendo-treeview configuration ?

**Comment by kil5152** [comment]
Hi @ipeshev - Thank you for the updates. Our application is using precompiled CSS Default Theme with "Office 365" color swatch which complied back in 2019 or 2020. 

My superior submitted a support ticket (1527623) regarding the missing Office 365 color swatch in theme builder. I believe the faulty behavior with the checkboxes might be due to not having the latest "Office 365" CSS. We learned that updated Office 365 color swatch should be expected to be provided with next major release scheduled for September.

As for the hidden children nodes, I thought maybe also due to not having the latest CSS.  I manually copied "all.css" from your [demo](https://stackblitz.com/edit/angular-73glcj-swhfb8?file=app%2Fapp.component.ts) to my application. It still did not solve the hidden children nodes issue. I also confirmed my application's kendo packages are the same as below screenshot. Below is how I set up the dropdowntree. 

![image](https://user-images.githubusercontent.com/5281535/125976078-ad4ecd74-cf69-44d4-965a-1247ecfc451b.png)


 <kendo-dropdowntree
    [placeholder]="'Select'"
    formControlName="activityCode"
    kendoDropDownTreeExpandable
    [kendoDropDownTreeHierarchyBinding]="activityCodes"
    [textField]="'typeName'"
    [valueField]="'id'"
    [childrenField]="'items'"
    [valuePrimitive]="true"
    [dataItem]="activityCodeDataItem"
    class="dropdown-large"></kendo-dropdowntree>

Let me set up a new page with dropdowntree in my application and share the component with you. Please let me know if I need to provide any additional information.

**Comment by lilacdev** [comment]
Hi,

We are facing the exact same situation. Even if children are present in DOM tree, they are not visible. Any update on this ?

**Comment by lilacdev** [comment]
An ugly workarround is :
```ts
  fetchChildren = node => { 
    setTimeout(() => document.querySelectorAll('.k-display-none').forEach(e => e.classList.remove('k-display-none')), 500);
    return this.getData(node._id);
  }
```

**Comment by ipeshev** [comment]
@lilacdev could you provide some more details regarding the faulty implementation, stackblitz project would be fine.

**Comment by lilacdev** [comment]
No, I applied my "ugly fix". This would be to complicated to send an example from our sources, sorry for that. But our case is similar to the one described by @kil5152 .

**Comment by DanielTakev** [comment]
Cannot be reproduced in the latest version.
