### ISSUE TITLE
Grid: ng add @progress/kendo-angular-grid --project projectName fails

### ISSUE THREAD

**Issue by prabh-62** [telerik/kendo-angular#3369]
**Describe the bug**
When adding kendo grid to a specific project inside angular workspace with multiple applications, `ng add` errors out

**To Reproduce**
- `npx @angular/cli@12 new web-apps --create-application false`
- `cd web-apps`
- `yarn ng g app admin-dashboard --routing --style scss`
- `yarn ng g app it-helpdesk --routing --style scss`
- `yarn ng generate module tickets --route tickets --module app.module --project it-helpdesk`
- `yarn ng add @progress/kendo-angular-grid --project it-helpdesk --module tickets/tickets.module`
```
Unknown option: '--project'
Unknown option: 'it-heldesk'
Unknown option: '--module'
Unknown option: 'tickets/tickets.module'
error Command failed with exit code 1.
```

**Expected behavior**
- `ng add` command should take into account project name and add grid module to that specific project and specific module

**Screenshots**
<img width="881" alt="kendo_schematics_grid-workspace" src="https://user-images.githubusercontent.com/13006107/124411268-33a0da80-dd1a-11eb-9b7b-8316f42ea5f0.png">

**Browser**
 - OS: NA
 - Browser: NA
 - Version: NA

**Additional context**
No

**Comment by prabh-62** [comment]
Alongwith `--project` flag, developer should also be able to provide `--module` flag so kendo grid does not get added to root `app.module.ts`

**Comment by Raisolution** [comment]
The described behaviour is expected, as the `ng add` schematic automatically retrieves the project path depending on execution location.
