### ISSUE TITLE
Grid: Kendo grid `[data]` attribute does not accept `ReadonlyArray<someInterface>`

### ISSUE THREAD

**Issue by prabh-62** [telerik/kendo-angular#3370]
**Describe the bug**
Kendo grid `[data]` attribute does not accept `ReadonlyArray<someInterface>`.

**To Reproduce**
- `npx @angular/cli@12 new web-apps --create-application false`
- `cd web-apps && yarn ng g app admin-dashboard --routing --style scss`
- `yarn ng add @progress/kendo-angular-grid`
- Edit `projects/admin-dashboard/src/app/app.component.ts` and add this code snippet
	```ts
	  import { Component } from '@angular/core';
	  
	  export interface DynamicRow {
	    id: number;
	  }
	  
	  @Component({
	    selector: 'app-root',
	    templateUrl: './app.component.html',
	    styleUrls: ['./app.component.scss'],
	  })
	  export class AppComponent {
	    title = 'admin-dashboard';
	  
	    public gridRows: ReadonlyArray<DynamicRow> = [{ id: 3232 }];
	  }
	```
- Edit `projects/admin-dashboard/src/app/app.component.html` and add this code snippet
	```html
	<kendo-grid [data]="gridRows"></kendo-grid>
	```

**Expected behavior**
Kendo grid should accept `ReadonlyArray<someInterface>` for `[data]` attribute

**Screenshots**
<img width="779" alt="kendo_grid_data_readonly" src="https://user-images.githubusercontent.com/13006107/124364388-2fd46180-dc0f-11eb-9de5-86f30c05dd20.png">

**Browser**
 - OS: NA
 - Browser: NA
 - Version: NA

**Additional context**
NA

**Comment by mbechev** [comment]
Hi @prabh-62,

Indeed this is expected, as the data property of the Grid expects an array of items (**Array\<any>**) or [GridDataResult ](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridDataResult/)object. For more details check the following article from our documentation:

https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/

**Comment by prabh-62** [comment]
@mbechev Is the expectation that Kendo grid mutates array data sent by the consumer since type information says Array<any> (should be `unknown` actually)?

The intent with `ReadonlyArray<someInterface>` is that kendo grid won't mutate the array sent by consumer.

**Comment by cluetjen** [comment]
We have similar problems with some components. I think, Angular works best with immutable types and so we try to keep the data immutable. But now, it's not possible to use this data with many kendo components because mutable arrays are expected.

It would be great if components (grid, listview, ...) would accept immutable types too (while I'm aware of the problem that there are components that may mutate the input data).

**Comment by preslavapetrova1** [comment]
The demand for this enhancement will be tracked in the related FP item https://feedback.telerik.com/kendo-angular-ui/1567665-grid-allow-readonlyarray-binding-to-grid-data
