### ISSUE TITLE
Focusing elements on DropDownButton selection is not working

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3371]
**Describe the bug**
When the Dialog is opened through the selection of an item in the DropDownList, the focus stays on the DropDownButton.

**To Reproduce**

1. Open the DropDownButton popup
2. Select an item - the Dialog will open, but the primary action button will not be focused
3. Press enter - the focus is on the DropDownButton

https://stackblitz.com/edit/angular-etwq3a?file=app/app.component.ts

**Expected behavior**
When opened from the DropDownButton the Dialog should be focused:

https://stackblitz.com/edit/angular-ppwxdw?file=app/app.component.ts

**Comment by Raisolution** [comment]
Fix is available in `v8.1.0` of the Buttons package.
