### ISSUE TITLE
Outdated code in 'Activating Your License Key' article

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3373]
**Describe the issue**
https://www.telerik.com/kendo-angular-ui/components/my-license/

 There are some mentions about `--prod` flag in that article. That flag is deprecated and will be removed in the next major version. 

**Additional context**
https://github.com/angular/angular-cli/pull/20128

**Comment by destus90** [comment]
@tsvetomir 
Closing with no changes? 🤔

**Comment by tsvetomir** [comment]
The code is updated on the [staging site](https://www.telerik.com/kendo-angular-ui-develop/components/my-license/) and will go live in a few days.
