### ISSUE TITLE
[DropDownTree] - Throw ExpressionChangedAfterItHasBeenCheckedError with focusout event

### ISSUE THREAD

**Issue by kil5152** [telerik/kendo-angular#3374]
**Describe the bug**
For DropDownTree, the ExpressionChangedAfterItHasBeenCheckedError error is shown on the Console with the focusout event

**To Reproduce**
Please follow below steps on  StackBlitz to reproduce [Demo](https://stackblitz.com/edit/angular-73glcj-ydtn4s)

1. Clicks the "Drop Down Tree" field and clicks anywhere outside to lose focus
2. Clicks the "Drop Down Tree" field again and clicks anywhere outside to lose focus again
3. The ExpressionChangedAfterItHasBeenCheckedError error is shown on the Console
4. Clicks the "Drop Down List 1" field and clicks anywhere outside to lose focus
5. Clicks the "Drop Down List 1" field again and clicks anywhere outside to lose focus again
6. No error which I believe it is the correct behavior.

**Expected behavior**
The DropDownTree should not throw ExpressionChangedAfterItHasBeenCheckedError error when losing focus multiple times. It should have the same behavior just like the DropDownList as the DropDownList is not throwing any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/5281535/125187871-b4bb0e80-e1ff-11eb-973e-ec3d6b3d3704.png)

**Comment by svetq** [comment]
The issue is no longer reproducible with the latest version (currently 13.4.0): https://stackblitz.com/edit/angular-heixdo
