### ISSUE TITLE
[DropDownTree] - Prevent Selection of Root Nodes

### ISSUE THREAD

**Issue by kil5152** [telerik/kendo-angular#3375]
### Question
Is there a built-in feature to only allow children to be selectable for DropDownTree? In other words, to prevent root nodes to be selected. As of now, I am using the below workaround to solve the issue. I am hoping DropDownTree has the built-in feature.

### Workaround
![image](https://user-images.githubusercontent.com/5281535/125188684-a9b5ad80-e202-11eb-9362-b43e5a6297fb.png)

**Comment by mbechev** [comment]
Hi @kil5152,
 
This repository is for bug reports only. Please [_open a support ticket_](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
