### ISSUE TITLE
[TreeView] The browser scroll moves when dropping an item

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3376]
**Describe the bug**
Rearranging the items of a TreeView using its built - in drag and drop feature, causes the browser scroll to be moved. The issue occurs when dropping the dragged item. 

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-mwberw-7shgjr?file=app/app.component.ts

here is a screen cast video:
http://somup.com/crillQYlbJ

**Comment by yanmariomenev** [comment]
The following example can be used as a workaround:
https://stackblitz.com/edit/angular-mwberw-qzlfcb?file=app/app.component.ts
Further adjustments might be required.

**Comment by gkarapeev** [comment]
Related to https://github.com/telerik/kendo-angular/issues/3302

**Comment by yanmariomenev** [comment]
When the developer version is available with the fix, we need to update the client in the following private thread: [1525159](https://supportheroes.telerik.com/ticket/1525159)

**Comment by Raisolution** [comment]
Fix is available in the latest **dev** version of the `kendo-angular-treeview` package.

**Comment by gkarapeev** [comment]
Shipped with TreeView version 6.0.1
