### ISSUE TITLE
Is there any delclarative way to crate add row template in kendo grid without passing formgroup to addRow function

### ISSUE THREAD

**Issue by Sudiptoc-2020** [telerik/kendo-angular#3377]
Hi want to add row feature in kendo grid.I went through the kendo grid add row doccumentation. But the problem is that i am working on a project where we have nested components and the form is dynamically created so i can't create those dynamic form components as form controls.

  public addHandler({ sender }) {
    this.closeEditor(sender);

    this.formGroup = createFormGroup({
      ProductName: "",
      UnitPrice: 0,
      UnitsInStock: "",
      CategoryID: 1,
    });

    sender.addRow(this.formGroup);
  }
Is there any delclarative way to crate add row template in kendo grid. If any one knows any way to create a add row template pls help.

**Comment by mbechev** [comment]
Hi @Sudiptoc-2020,

This repository is for bug reports only. Please [_open a support ticket_](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
