### ISSUE TITLE
Kendo UI Chart causes protractor waiting on Angular timeout issue

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#338]
The following is a copy-paste from my question on [StackOverflow](http://stackoverflow.com/questions/42506766/kendo-ui-chart-causes-protractor-waiting-on-angular-timeout-issue):

I have a simple chart definition:

```
<kendo-chart>
  <kendo-chart-series>
    <kendo-chart-series-item *ngFor="let series of chartSeries"
      type="column" 
      field="amount" 
      categoryField="period"  
      [data]="series.dataPoints">
    </kendo-chart-series-item>
  </kendo-chart-series>
</kendo-chart>
```

Any protractor test running on the page with the chart fails with the typical:

`Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds.`

Replacing the chart definition with a nested `*ngFor` and spitting out the chart data to HTML allows the tests to run successfully.

Is it possible to run protractor tests with Kendo UI charts? The project is built with angular-cli and using `ng e2e` to run the tests.

**Comment by SeriousLemon** [comment]
@tsvetomir any word on this?

**Comment by tsvetomir** [comment]
Totally forgot about this issue, sorry!

I tried reproducing in [this repo](https://github.com/tsvetomir/kendo-angular-338), but without success. Perhaps something else is necessary to trigger the issue.

**Comment by SeriousLemon** [comment]
I see. I'll try narrow it down and get back to you.

**Comment by SeriousLemon** [comment]
@tsvetomir the issue is reproducible by navigating to the page with the charts, from another page (behind a login for instance) and then using `browser.waitForAngular()` to wait for the page.

However I've since discovered that setting `useAllAngular2AppRoots: true` in your protractor config resolves the issue.

Cheers.

**Comment by tsvetomir** [comment]
Seems related to angular/protractor#3611. Oddly enough the changelog for [Protractor 5.0.0](https://github.com/angular/protractor/blob/master/CHANGELOG.md#500) lists the `useAllAngular2AppRoots` flag as deprecated:

> Auto-detection of the root element. This is a breaking change because it changes the default root element behavior and removes the config.useAllAngular2AppRoots flag. Modern angular apps now default to using all app hooks, and ng1 apps now check several places, notably the element the app bootstraps to.

**Comment by SeriousLemon** [comment]
Right. In that case, I don't know. I added that option to the config and the tests started working. According to that changelog it seems it should be always "on" anyway. That's with Protractor `5.1.1`.

**Comment by tsvetomir** [comment]
It's definitely still in [the code](https://github.com/angular/protractor/blob/master/lib/browser.ts#L554-L563).

Thanks for your time! I hope this will help others as well.
