### ISSUE TITLE
Kendo Angular TreeList - Sorting with Filter Row not working together.

### ISSUE THREAD

**Issue by SBhatt20** [telerik/kendo-angular#3382]
**Describe the bug**
Kendo Angular TreeList - Sorting with Filter Row not working together.

**To Reproduce**
Apply Filter and Sort together. Sorting not working. Click on Column,  nothing will happen. Separately Filter and Sorting are working

Working Code
https://stackblitz.com/edit/angular-2n2mqk-xd5qfb?file=app/app.component.ts

**Comment by mbechev** [comment]
Hi @SBhatt20,

When using [data](https://www.telerik.com/kendo-angular-ui/components/treelist/api/TreeListComponent/#toc-data) property to bind the TreeList collection, the developer needs to handle manually all data-related operations like filtering, sorting and etc. using the respective built-in methods ([filterBy](https://www.telerik.com/kendo-angular-ui/components/data-query/api/filterBy/), [orderBy](https://www.telerik.com/kendo-angular-ui/components/data-query/api/orderBy/)). 

In the provided demo the data is not being ordered in the TS code. By default, the **orderBy** will sort only the root level of the TreeList. To sort all data, the developer needs to implement a recursive function, to sort each level of the TreeList.

As the TreeList component is more complicated than the Grid, we provide a built-in directive **kendoTreeListHierarchyBinding** that encapsulates the in-memory handling of data operations such as sorting and filtering:
https://www.telerik.com/kendo-angular-ui/components/treelist/data-binding/#toc-binding-to-hierarchical-data

If you have any additional questions, please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
