### ISSUE TITLE
How to use MaskedTextBoxComponent as standard input ?

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#339]
Hi Kendo team,

I am trying to create a commonly used maskedtextbox component based on Kendo MaskedTextBoxComponent ,  use case is we can pass different mask strings for different fields, even sometimes just use it as standard textbox.

I see there is one sentence saying "Represents the current mask. If no mask is set, the component behaves as a standard type="text" input." in the API documentation.BUT I don't know how to remove the mask from component, would you please kindly provide some proposals or workarounds ?

**Comment by zhao125787935** [comment]
Hi Kendo team,

Any updates on this issue ?

**Comment by KirilNN** [comment]
I can confirm it is a bug that will be addressed in future versions.

**Comment by rusev** [comment]
This issue is addressed in the `0.21.0` version of `kendo-angular-inputs` package.

Example - http://plnkr.co/edit/ZL4ab9UG8qkpyXlWsSDG?p=preview

**Comment by zhao125787935** [comment]
Thanks @rusev , I will update latest package, Thanks very much !
