### ISSUE TITLE
Kendo Upload: Upload file with 0 byte of size on Safari (iOS 14.1)

### ISSUE THREAD

**Issue by sonnguyent1** [telerik/kendo-angular#3393]
**Describe the bug**

The application has multiple upload controls 
File uploads are triggered programmatically on one button click event. 
Randomly some of the the files were found to upload with 0 byte of file size. 

**To Reproduce**
Access into the application's upload page 
The page contains 3 upload controls
Select about 6 files for each control
Click Button SAVE to upload all select files
Observe some of the file data are posted with 0 byte of file size. 

**Expected behavior**
All selected file are uploaded properly

**Browser**
 - OS: iOS 14.1
 - Browser: Safari 
 - Version: 14
- Version of @progress/kendo-angular-upload: 6.1.0

**Comment by Raisolution** [comment]
Hi @sonnguyent1 ,

It is not clear what is the exact bug in the described application scenario. Please open a support ticket in our [support channel](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
