### ISSUE TITLE
[Grid] Previous selection is not cleared when a new item is selected using kendoGridSelectBy directive

### ISSUE THREAD

**Issue by slavenai** [telerik/kendo-angular#3394]
**Describe the bug**
When using the kendoGridSelectBy directive, the previously selected items are not being cleared when a new item on a different page has been selected without pressing the Ctrl/Command keys.

**To Reproduce**
1.Open the following Stackblitz demo:
https://stackblitz.com/edit/angular-s6xpvv?file=app/app.component.ts
2.Select an item.
3.Change the page and select a new item without pressing Ctrl/Command key.
4.Observe the unwanted behaviour - the previously selected item is not removed from the collection.

**Expected behavior**
The previous item's selection should be cleared.

Workaround:
Binding to the cellClick event and manually update the collection.
https://stackblitz.com/edit/angular-hoznul-7duwwy?file=app/app.component.ts

**Comment by svetq** [comment]
Also reported in 1547727
