### ISSUE TITLE
[MultiselectTree] Checkbox state for a root item

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3395]
**Describe the bug**
Checkbox state for a root item is not changed when clearing a children item from the input element.

**To Reproduce**

1. Go to https://stackblitz.com/edit/angular-k9rtas?file=app/app.component.ts
2. Select all items clicking on a root checkbox element
3. Remove children item from the input clicking on the `X` button

**Expected behavior**
Checkbox state of the root element should be changed to `-`

**Screenshots**
![image](https://user-images.githubusercontent.com/17944366/127108713-50a69a61-d07a-44ca-a36a-b5c70698477b.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 92.0.4515.107

**Comment by dtopuzov** [comment]
The fix is released with @progress/kendo-angular-dropdowns@7.0.3
