### ISSUE TITLE
[DropDowns] ExpressionChange error is thrown when using filtering and virtual scroll in v5.3.0 and above

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3396]
**Describe the bug**
Using filtering with  virtual scroll, throws and ExpressionChange error when the user tries to filter the data with a value that does not exist in the list:
https://screenrec.com/share/WDFXGVQMfZ

![image](https://user-images.githubusercontent.com/33104481/127274414-b6a370f6-e44b-4dcc-948f-20bad8a71b52.png)

The issue affects all components from the package.

**To Reproduce**
The issue is reproduced with:
* Angular 10 and above 
* DropDowns package version **5.3.0** and above

1. Download and unzip.
2. Run **npm install** command.
3. Run **ng serve** command.

[dropdowns-A11.zip](https://github.com/telerik/kendo-angular/files/6890934/dropdowns-A11.zip)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds) of kendo-angular-dropdowns.

**Comment by stnikolova** [comment]
Fix available in **v.5.5.1** of the DropDowns package.
