### ISSUE TITLE
Problem with combobox text field

### ISSUE THREAD

**Issue by bond-igor** [telerik/kendo-angular#3397]
**Describe the bug**
If combobox data text contains specific symbols, it can't store value in a reactive form.
After blur, text field data will reset.
Problem data example:
`public data: Array<{ name: string; id: number }> = [
    {
      name: '46 25-03-2021, \r\nScope Changeable: No',
      id: 1
    },
    {
      name: '46 25-03-2021, \r\nScope Changeable: No',
      id: 2
    },
    {
      name: '46 25-03-2021, \r\nScope Changeable: No',
      id: 3
    }
  ];`

**To Reproduce**
Try to change the value in the combobox and change focus
https://stackblitz.com/edit/angular-gjk9g7-k1ywtp?file=app/app.component.ts

**Expected behavior**
Not to reset value after selection

**Browser**
 - OS: Win 10
 - Browser: Chrome
 - Version leatest

**Comment by dimitar-pechev** [comment]
@bond-igor, this behavior is expected and documented [in our docs](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/value-binding/). The native input element treats the `\n` line-breaking character as a single white-space. Thus, when you select a value, have it resolved by the input element, and blur the component, the ComboBox tries to resolve the parsed value in the input and as all line-breaking symbols are replaced with white-spaces, it no longer acknowledges the current value as a known one (it doesn't match any value on the list) and it discards it. As the ComboBox uses internally an input element, it  also inherits all input element limitations as well. 

In such cases we advise to map your data to exclude such symbols.

If I'm missing something, do let me know. We could reopen the issue if we establish there's an issue at hand we could tackle.
