### ISSUE TITLE
RTL mode is now toggled with a token instead a string

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#340]
The string token has been replaced with a strongly typed OpaqueToken from the new `@progress/kendo-angular-l10n` package.

Current syntax:

```ts
@NgModule({
    providers: [{ provide: 'kendo-direction', useValue: 'rtl' }]
})
```

New syntax:

```ts
import { RTL } from '@progress/kendo-angular-l10n';

@NgModule({
    providers: [{ provide: RTL, useValue: true }]
})
```

**Comment by tsvetomir** [comment]
Main issue for RTL is #96

**Comment by afsalcodehack** [comment]
How to change RTL useValue dynamically instead of  static 'true'
