### ISSUE TITLE
[NumericTextBox] Spin buttons do not have suitable role attribute and cause an accessibility issue

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#3400]
**Describe the bug**
The NumericTextBox spin buttons are span elements with an **aria-label** attribute, which causes accessibility errors reported by AXE.

Only certain elements can have this attribute:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute#support

The interactive SPAN elements need to be marked with a suitable role (e.g. button).

**Comment by Raisolution** [comment]
Fixed in `v7.4.0`
