### ISSUE TITLE
[Grid] Detail expansion icon is not visible

### ISSUE THREAD

**Issue by robmass94** [telerik/kendo-angular#3401]
## Current behavior
Grid detail expansion icon is not visible. Class is "k-plus" but there is no associated CSS rule; closest rule is for "k-i-plus."

## Expected behavior
Grid detail expansion icon should be visible.

## Reproduction of the problem
Detail expansion icon is not visible in [the master-detail demo](https://www.telerik.com/kendo-angular-ui/components/grid/master-detail/) or in my personal project

Browser: Chrome (desktop) version 91.0.4472

**Comment by Raisolution** [comment]
Hi @robmass94 

Please excuse us for the inconvenient and thanks for reporting this issue.

We are aware of the problem and a fix is released in version `5.3.1` of the Grid package.
