### ISSUE TITLE
[DropDowns] Manual filtering doesn't work as expected in DropDownTree and MultiSelectTree

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3412]
**Describe the bug**

The manual filtering feature in DropDownTree and MultiSelectTree is not functioning as anticipated. It displays both the filtered items and the no-data template, whereas in the initial issue, it only showed the no-data template.

**To Reproduce**
1. open the following demos: 
(DropDownTree) https://stackblitz.com/edit/angular-ftnxmb-ipns43?file=app/app.component.ts
(MultiSelectTree) https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/multiselecttree/filtering/#toc-manual-filtering
2. Type "tab"(shows result) then add "2" <strike>it will show that there isn't any data available.</strike> the items are updated, but the no data template is still present in the DOM. In the original issue, the items weren't updated and the no data template was shown instead.
3. Remove the "2" so it goes back to the original input  "tab" but now the result isn't shown. It seems that the view of the component isn't getting updated.

**Expected behavior**
Manual filtering to work and return the correct results.

**Workaround**
A possible workaround is to call the ChangeDetectorRef -> detectChanges:
https://stackblitz.com/edit/angular-n5jh3x-mt9hoo
Using DropDownTree data:
https://stackblitz.com/edit/angular-n5jh3x

**Comment by yanmariomenev** [comment]
I just wanted to add one more possible workaround using the DropDownTree data:
https://stackblitz.com/edit/angular-ftnxmb-2ycaoi?file=app/app.component.ts

**Comment by JoomFX** [comment]
The issue seems to be in the demo implementation (the logic in the `search` method).

**Comment by erothfield** [comment]
>Workaround
>A possible workaround is to call the ChangeDetectorRef -> detectChanges:
>https://stackblitz.com/edit/angular-n5jh3x-mt9hoo

If the search handler has a delay (which I have by calling a rest api), the workaround does not seem to work.
e.g. add setTimeout() around the handleFilter logic.

Any ideas?

**Comment by svetq** [comment]
A fix is available in `@progress/kendo-angular-dropdowns` version 15.0.2-develop.11
