### ISSUE TITLE
Notification service cannot show different info with same template when showing multiple items

### ISSUE THREAD

**Issue by RonnyRen** [telerik/kendo-angular#3415]
Hi All,
We want to use template to show some info through notification service. For example: when user click button, we need to show an error, after user changed something and click button again, another error should display, but I found that the error info previous showed was also updated to the new one. How can I implement this function?
There is an example below to show my problem.
https://stackblitz.com/edit/angular-y58eqt?file=app/app.component.ts
1: Click 'show' button, it is correct as below.
![image](https://user-images.githubusercontent.com/33855404/130748023-f77dd375-122c-44d2-a42a-f3fd6a2bceca.png)
2. Click 'show' button again, the two notifications display the same thing. The first one was updated to new one instead of keeping old info.
![image](https://user-images.githubusercontent.com/33855404/130748251-d7d789d1-2d1b-4545-8730-956824771c10.png)

Thanks,
Ronny

**Comment by dtopalov** [comment]
Hello @RonnyRen,

The observed behavior is actually expected, as the `ng-template` content uses binding to a component field, and the same template instance is rendered within all Notification components. Thus when the template content is changed through the Angular text interpolation mechanism, the change is reflected across all Notification instances.

To display dynamic content in multiple Notification instances, the developer can [render a custom component](https://www.telerik.com/kendo-angular-ui/components/notification/content/#toc-rendering-a-component) in the Notification, and change its respective properties as necessary, e.g.:

https://stackblitz.com/edit/angular-z2s1rg?file=app/app.component.ts
