### ISSUE TITLE
[DateInputs] TimePicker and DateTimePicker popup displays the time separator in apostrophes (fr-CA locale)

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3416]
**Describe the bug**
TimePicker and DateTimePicker popup displays the time separator in apostrophes when using the fr-CA locale. The input field displays the correct format without the apostrophes.

**To Reproduce**
Open the popup of ether components in the following example: https://stackblitz.com/edit/angular-nvadct-sxxmvd?file=app%2Fapp.component.ts

**Expected behavior**
To display the separator correctly without apostrophes.

**Screenshots**
https://imgur.com/a/dQeVJo2

**Comment by stnikolova** [comment]
No longer reproducible with v13.5.0 of @progress/kendo-angular-dateinputs. See example https://stackblitz.com/edit/angular-9266mk
