### ISSUE TITLE
Scroll position changed when kendo-textarea blurred

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3417]
**Describe the bug**
Scroll jumps up when long text is pasted in kendo-textarea 

**To Reproduce**

1. Open [this stackblitz sample](https://stackblitz.com/edit/angular-egmncn?file=app/app.component.ts).
2. Paste some long text and blur the kendo-textarea.

**Expected behavior**
Scroll should not jump up when component is blurred.

**Comment by Raisolution** [comment]
Issue has been addressed in `v8.0.8` https://www.telerik.com/kendo-angular-ui-develop/components/inputs/textarea/sizing/#toc-setting-the-resize-directions
