### ISSUE TITLE
`+` and `-` Icons disappeared when using Row Details Grid Template

### ISSUE THREAD

**Issue by joharzmn** [telerik/kendo-angular#3418]
**Describe the bug**
`+` and `-` Icons disappeared when using Row Details Grid Template.

**To Reproduce**
- Use Kendo Grid with Row Detail Template.
- `+` and `-` Icons will not show to expand or collapse details.

**Expected behavior**
- Icons should appear to collapse and expand the details.

**Screenshots**
![image](https://user-images.githubusercontent.com/16515522/131054990-4610a70b-7fd6-4f64-981b-8aebf04cfc74.png)

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version: Version 92.0.4515.159 (Official Build) (64-bit)

**Additional context**
These icons were showing before, it started happening recently.
You can see this issue in the demo: https://www.telerik.com/kendo-angular-ui/components/grid/master-detail/detail-template/

**Comment by nithin-bg** [comment]
how can I check the grid package version in angular @joharzmn
