### ISSUE TITLE
Kendo datepicker broken after updating to Angular 12

### ISSUE THREAD

**Issue by robertd77** [telerik/kendo-angular#3419]
The datepicker is freezing and not closing after being opened. I am getting the following error in the console when trying to open the calendar:  'Uncaught TypeError: Cannot read property 'add' of undefined
    at HeaderComponent.ngOnInit'

Package.Json: 
"dependencies": {
    "@angular/animations": "~12.1.2",
    "@angular/common": "~12.1.2",
    "@angular/compiler": "~12.1.2",
    "@angular/core": "~12.1.2",
    "@angular/forms": "~12.1.2",
    "@angular/localize": "^12.1.2",
    "@angular/platform-browser": "~12.1.2",
    "@angular/platform-browser-dynamic": "~12.1.2",
    "@angular/router": "~12.1.2",
    "@ngneat/transloco": "^2.22.0",
    "@progress/kendo-angular-buttons": "^6.2.0",
    "@progress/kendo-angular-common": "^2.0.1",
    "@progress/kendo-angular-dateinputs": "^5.2.0",
    "@progress/kendo-angular-dialog": "^5.0.1",
    "@progress/kendo-angular-inputs": "^7.3.1",
    "@progress/kendo-angular-intl": "^3.1.1",
    "@progress/kendo-angular-l10n": "^3.0.2",
    "@progress/kendo-angular-label": "^3.1.0",
    "@progress/kendo-angular-layout": "^6.1.7",
    "@progress/kendo-angular-popup": "^4.0.1",
    "@progress/kendo-angular-progressbar": "^2.0.1",
    "@progress/kendo-angular-upload": "^7.1.1",
    "@progress/kendo-drawing": "^1.10.1",
    "@progress/kendo-licensing": "^1.2.0",
    "@progress/kendo-theme-bootstrap": "^4.36.0",
    "bootstrap": "^4.6.0",
    "font-awesome": "4.7.0",
    "is-url-external": "1.0.3",
    "lodash-es": "^4.17.21",
    "ngx-bootstrap": "^6.2.0",
    "ngx-take-until-destroy": "^5.4.0",
    "ngx-toastr": "^14.0.0",
    "rxjs": "^7.2.0",
    "simple-line-icons": "2.5.5",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.2",
    "@angular/cli": "~12.1.2",
    "@angular/compiler-cli": "~12.1.2",
    "@angular/language-service": "~12.1.2",
    "@types/jasmine": "^3.8.1",
    "@types/jasminewd2": "^2.0.10",
    "@types/lodash-es": "^4.17.4",
    "@types/node": "^16.3.3",
    "codelyzer": "^6.0.2",
    "jasmine-core": "^3.8.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "^4.0.1",
    "karma-jasmine-html-reporter": "^1.7.0",
    "protractor": "~7.0.0",
    "ts-node": "~10.1.0",
    "tslint": "~6.1.0",
    "typescript": "~4.3.5"
  },
  "engines": {
    "node": "14.17.3",
    "npm": "6.14.11"
  }

**Comment by areed829** [comment]
We are having the same issue but with the grid.

**Comment by robertd77** [comment]
I managed to fix the issue by rolling back rxjs from 7.2 to 6.6.7. Apparently Angular 12 does not fully support the new major version of rxjs and this was breaking the datepicker.

**Comment by AdonousTech** [comment]
I faced the same issue with the date picker. The error is weird and specifically refers to a long chain of subscriptions on one instantiated `Subscription` object. The `Subscription` get instantiated in the constructor, and child subscriptions are added in ngOnInit. 

The devs used the pattern referenced in the SO post: https://stackoverflow.com/questions/54668110/cannot-read-property-add-rxjs-subscription, but apparently that pattern is valid. 

Anyhow, @robertd77  solution works to temporarily work around the issue.

**Comment by stnikolova** [comment]
Related to https://github.com/telerik/kendo-angular/issues/3314
> The Kendo UI for Angular components are not yet compatible with RxJS 7. 

> The number of breaking changes in RxJS 7 is significant and we can't commit to a specific timeline at the moment.
