### ISSUE TITLE
Kendo slider tic marks squished together until clicked

### ISSUE THREAD

**Issue by aarmora** [telerik/kendo-angular#342]
We've been using the kendo slider since a few weeks after it first came out and just within the last month or so it's been doing this.

The slider is squished on page load until it's touched. As soon as it is touched, the slider expands to full size.

Squished:
![slider_squished](https://cloud.githubusercontent.com/assets/6865538/23480999/2c44c86c-fe87-11e6-8289-999fa985fe42.PNG)

Full size:
![slider_full](https://cloud.githubusercontent.com/assets/6865538/23480992/25300870-fe87-11e6-8534-528d98b17e2f.PNG)

I'm going to work on steps to see if I can reproduce this in a different environment.

**Update**
It appears to be a conflict with Google Material Icons. When I remove this import it works fine:
`@import url(https://fonts.googleapis.com/icon?family=Material+Icons);`

**Second Update**
If I reference google material icons in the `index.html` file this conflict no longer happens.
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by tsvetomir** [comment]
We fixed this problem in v0.19.1, also the Slider will now resize automatically.

Thanks for your bug report!

**Comment by aarmora** [comment]
@tsvetomir Is that in `kendo-angular-inputs`?
