### ISSUE TITLE
[Grid] Can't work on Angular  v12.2.4 with grid version 5.4.0

### ISSUE THREAD

**Issue by hizliemre** [telerik/kendo-angular#3427]
**Describe the bug**
Its seems ListComponent subscripsions field is coming undefined from detailService.

**To Reproduce**
1 - Create a new angular project and use latest version
2 - Install GridComponent
3 - use `<kendo-grid></kendo-grid>` on app.component

**Expected behavior**
Just work

**Screenshots**
[https://imgur.com/a/M0WoUek](https://imgur.com/a/M0WoUek)
[https://imgur.com/EZZg5HD](https://imgur.com/EZZg5HD)

**Browser**
 - OS: Ubuntu 20.04.2
 - Chrome
 - Version 93.0.4577.63 (Official Build) (64-bit)

-- package.json

"dependencies": {
    "@angular/animations": "~12.2.4",
    "@angular/common": "~12.2.4",
    "@angular/compiler": "~12.2.4",
    "@angular/core": "~12.2.4",
    "@angular/forms": "~12.2.4",
    "@angular/platform-browser": "~12.2.4",
    "@angular/platform-browser-dynamic": "~12.2.4",
    "@angular/router": "~12.2.4",
    "@progress/kendo-angular-buttons": "^6.3.0",
    "@progress/kendo-angular-common": "^2.0.1",
    "@progress/kendo-angular-dateinputs": "^5.2.2",
    "@progress/kendo-angular-dropdowns": "^5.3.0",
    "@progress/kendo-angular-excel-export": "^4.0.1",
    "@progress/kendo-angular-grid": "^5.4.0",
    "@progress/kendo-angular-inputs": "^7.4.0",
    "@progress/kendo-angular-intl": "^3.1.1",
    "@progress/kendo-angular-l10n": "^3.0.2",
    "@progress/kendo-angular-label": "^3.1.0",
    "@progress/kendo-angular-pdf-export": "^3.0.1",
    "@progress/kendo-angular-popup": "^4.0.1",
    "@progress/kendo-angular-treeview": "^5.4.0",
    "@progress/kendo-data-query": "^1.5.5",
    "@progress/kendo-drawing": "^1.11.0",
    "@progress/kendo-licensing": "^1.2.0",
    "rxjs": "~7.3.0",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.4",
    "@angular/cli": "~12.2.4",
    "@angular/compiler-cli": "~12.2.4",
    "@angular/localize": "^12.2.4",
    "@types/jasmine": "~3.9.0",
    "@types/node": "^16.7.10",
    "jasmine-core": "~3.9.0",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.7.0",
    "typescript": "^4.3.5"
  }

**Comment by meriturva** [comment]
Just use rxjs 6.x

**Comment by hizliemre** [comment]
> Just use rxjs 6.x

Yes, this solved problem. RxJS 7 not supported yet.

**Comment by meriturva** [comment]
Here main issue related to rxjs update: https://github.com/telerik/kendo-angular/issues/3314
