### ISSUE TITLE
How to add id  to header  of kendo grid cclumns 

### ISSUE THREAD

**Issue by sagarloona4180** [telerik/kendo-angular#3428]
**To submit requests for new components and features, please use our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui).**
![image](https://user-images.githubusercontent.com/29095795/132447522-34824ef4-a933-4b9b-9c0e-dc86f03408eb.png)

**Comment by Raisolution** [comment]
Hi @sagarloona4180 

This repository is for bug reports only.  Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
