### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by oleksandrmelnychenko** [telerik/kendo-angular#343]
Good day.
I have installed laters angular2 cli version. Added GridView Module. This module should have "@progress/kendo-angular-intl": "^0.10.0", - 0.10.0 version. But after i have installed "@progress/kendo-angular-dateinputs": "^0.3.6",  But for DateInputs it tells me that i should have  "@progress/kendo-angular-intl": "^0.9.0", any there are not working together ? 

Any fixes? How to resolve it ?

**Comment by tsvetomir** [comment]
Thanks for reporting this. We'll publish an update to the date inputs package shortly.

**Comment by oleksandrmelnychenko** [comment]
Please, need to work with that really now, Thanks

**Comment by tsvetomir** [comment]
You can ignore the error for the moment. There are no breaking changes in the intl package between 0.9 and 0.10

**Comment by oleksandrmelnychenko** [comment]
angular cli not working with this error

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/23504736/712b7c2e-ff49-11e6-9a51-ff077059e370.png)

**Comment by oleksandrmelnychenko** [comment]
Properties are not working

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/23504815/b0c03640-ff49-11e6-846c-7ee58693284f.png)

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/23504917/13084a2c-ff4a-11e6-8c3d-ebb9eaa25724.png)

**Comment by tsvetomir** [comment]
Perhaps the package installation failed then.

Please upgrade to kendo-angular-date-inputs@0.3.7 to fix this.

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/23505108/ef695632-ff4a-11e6-8bfd-883c05174a29.png)

**Comment by oleksandrmelnychenko** [comment]
can you tell me the correct versions for GrIDVIEW and DateInputs, intl,l10n, and Data-Query,

**Comment by oleksandrmelnychenko** [comment]
i mean working versions for now

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/23511064/9dd2325c-ff64-11e6-9263-f280ca73f65d.png)

**Comment by oleksandrmelnychenko** [comment]
Check please, compilation is success, but can't open screen with GRIDVIEW. i think with dateinputs the same

**Comment by gayan1991** [comment]
I have a problem with kendo-angular-date-inputs@0.3.7. I have scroll down then up again to view the dates inside the date (numbers..etc). And it scrolled down to the minimum date. Once i can view the numbers, if I select week, it will be scrolled to focus date. Then if i scroll up, high chance of going to minimum date (probably scroll faster or further).

**Comment by tsvetomir** [comment]
Can you please open a new issue as this is not related to the package installation?
