### ISSUE TITLE
[TreeView] ExpandDirective not expanding the parent node when a new key is added to expandedKeys array

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3430]
**Describe the bug**
ExpandDirective not expanding the parent node when a new key is added to expandedKeys array.  This bug is introduced in TreeView version 5.4.0 and isn't present in v5.3.1

**To Reproduce**
https://stackblitz.com/edit/angular-krk6qq-hkmaw7

**Workaround**
https://stackblitz.com/edit/angular-krk6qq-dgrxml
` public expand = () => {
    this.expandedKeys.push('Decor');
    this.expandedKeys = [...this.expandedKeys]
  };`

**Comment by gkarapeev** [comment]
[Shipped](https://stackblitz.com/edit/angular-geaw3x?file=app/app.component.ts) with TreeView 5.4.2
