### ISSUE TITLE
Grid pager displaying dropdown and buttons

### ISSUE THREAD

**Issue by Albhaku** [telerik/kendo-angular#3431]
**Describe the bug**
In kendo-angular-grid@5.4.0 and kendo-angular-dropdowns@5.3.1, a dropdown with the amount of "pages" is displayed before the pages buttons.

**To Reproduce**
Just create a simple grid
- 1 column
- [pageble]="true"
- Customer pager template
- 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15705961/133001237-44f05e0c-0c0d-4f56-bfb0-fea2180753af.png)
You can see both elements at the bottom

![image](https://user-images.githubusercontent.com/15705961/133001247-ac69bc6d-f16f-4922-a74b-9d62ee7b73d3.png)
And this is the customer template

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 93.0.4577.63

**Additional context**
We migrated from some old packages (2 years with no upgrades) and it was working fine, but I'm having a lot of issues right now with the new versions. This is something can be fixed with CSS, but, element would still be loaded and that's not right. I have another issue, related to dropdowns lists and label /checkboxes being displayed nex to dropdown items, so, I'll submit 2 issues, by now.

Thanks.

**Comment by gkarapeev** [comment]
Hi Albhaku,

Thank you for reporting this. So far we have not been able to reproduce it.

Could you please fork [this demo](https://stackblitz.com/edit/angular-wd4tra?file=app/app.component.ts) and make any necessary changes to reproduce the issue?

Also which version of a theme package are you using?

Looking forward to hearing from you.

Regards,
Georgi

**Comment by Albhaku** [comment]
I'll do it, cause we're facing multiple visual issues, just give me a few days. Too much work to do and I want to make sure to give you the most accurated demo, according to our implementation.

Thank you.
