### ISSUE TITLE
How to make `kendo-toolbar-dropdownbutton` scrollable?

### ISSUE THREAD

**Issue by joharzmn** [telerik/kendo-angular#3434]
I tried using popupSettings and adding custom styles but nothing is working for me. 

Here is the demo:
[Reproduced in Stackbiltz](https://stackblitz.com/edit/angular-3z2hau?file=app/app.component.ts)

**Comment by Raisolution** [comment]
Hi @joharzmn 

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.

**Comment by joharzmn** [comment]
@Raisolution This was a bug, the link I sent was from Kendo Demos. PopupSettings is not working.

**Comment by Raisolution** [comment]
@joharzmn Currently the `popupSettings` option of the `ToolBarDropDownButtonComponent` does not support specifying height. The supported options can be found in the corresponding API section:
https://www.telerik.com/kendo-angular-ui-develop/components/toolbar/api/ToolBarDropDownButtonComponent/#toc-popupsettings
