### ISSUE TITLE
CSS Class in popupSettings of ToolBar not working

### ISSUE THREAD

**Issue by joharzmn** [telerik/kendo-angular#3438]
**Describe the bug**
CSS Classes in popupSettings of ToolBar not getting applied to `kendo-toolbar-dropdownbutton`

**To Reproduce**

Here you can see it not working:
https://stackblitz.com/edit/angular-3z2hau?file=app/app.component.ts

**Expected behavior**
Css Classes should be applied to the popup

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version Latest

**Comment by Raisolution** [comment]
Hi @joharzmn 

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
