### ISSUE TITLE
Add @progress/kendo-angular-l10n peer dependency

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#344]
Localization is now handled by a dedicated [Localization](http://www.telerik.com/kendo-angular-ui/components/localization/) package: **@progress/kendo-angular-l10n**

This is a **breaking change** that affects the following packages:

* kendo-angular-grid
* kendo-angular-upload

The getting started articles of each component will be updated to reflect the change.
Existing users should execute the following command to install the new dependency:

```sh
npm install --save @progress/kendo-angular-l10n
```

**Comment by EricSch** [comment]
txs

Btw the external link would be: [Localization](http://www.telerik.com/kendo-angular-ui/components/localization/)

**Comment by tsvetomir** [comment]
Oopsie, daisy! Fixed, thanks!

**Comment by yasiryc** [comment]
The breaking change also affects kendo-angular-buttons package. Please add new dependency in the getting started article of the package.

**Comment by tsvetomir** [comment]
@yasiryc it's actually a different breaking change that adds support for RTL, see #340

**Comment by tsvetomir** [comment]
I've updated the list of packages that require l10n - it's pretty much all of the major components.
