### ISSUE TITLE
[DropDownList] Empty string does not update the value

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3440]
**Describe the bug**
The DropDownList component does not update the value's display text if the newly provided value is an empty string (' '). It only updates the selection (no item appears to be selected when opening the dropdown)
**To Reproduce**

1. Open the StackBlitz example: https://stackblitz.com/edit/angular-3maxmx?file=app%2Fapp.component.ts
2. Click the "Set value to ''" button
3. Open the DropDown => selection is updated, but the value is not updated:
<img width="237" alt="Screenshot 2021-09-20 at 15 54 25" src="https://user-images.githubusercontent.com/18744873/134005635-a1aeb95a-4125-491f-81f8-92592ade904b.png">

**Expected behavior**
DropDownList should clear the value.

**Comment by JoomFX** [comment]
Setting the value to empty string is not a valid configuration in this setup.
The value can be set to `null` in order to reset the selected value or the `reset` method of the component can be used.

https://stackblitz.com/edit/angular-afaauc?file=src%2Fapp%2Fapp.component.ts
