### ISSUE TITLE
Angular 12 and kendo-angular-layout

### ISSUE THREAD

**Issue by xinthose** [telerik/kendo-angular#3442]
**Describe the bug**
```
error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@progress/kendo-angular-layout) which declares LayoutModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

41 export declare class LayoutModule {
```
```
ng add @progress/kendo-angular-layout
Skipping installation: Package already installed
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

**To Reproduce**
Run `ng add @progress/kendo-angular-layout` on an Angular 12 project

**Expected behavior**
I should be able to use Layout Components in an Angular 12 project

**Additional context**
`ng --version`

> Angular CLI: 12.2.5
> Node: 14.17.3
> Package Manager: npm 6.14.13
> OS: win32 x64
> 
> Angular: 12.2.6
> ... animations, common, compiler, core, forms, localize
> ... platform-browser, platform-browser-dynamic, router
> 
> Package                         Version
> ---------------------------------------------------------
> @angular-devkit/architect       0.1202.5
> @angular-devkit/build-angular   12.2.5
> @angular-devkit/core            12.2.5
> @angular-devkit/schematics      12.2.5
> @angular/cdk                    9.2.4
> @angular/cli                    12.2.5
> @angular/compiler-cli           12.2.5
> @angular/language-service       12.2.5
> @schematics/angular             9.1.15
> rxjs                            6.6.7
> typescript                      4.3.5

- Node.js version: 14.17.3

**Comment by dtopalov** [comment]
Hello @xinthose,

I tried to replicate the described issue, but could not. After creating a new Angular 12 application using the Angular CLI, and running the `ng add @progress/kendo-angular-layout` command, I added a TabStrip component to the page, and run the application:

![image](https://user-images.githubusercontent.com/7533599/134502685-b642d08c-f28c-410c-8b72-fab2a917b78d.png)

Please find attached the sample project, compare it to yours and apply the necessary adjustments. If you experience further issues using the Layout package, please open a [support ticket](https://www.telerik.com/account/support-tickets).

[Archive.zip](https://github.com/telerik/kendo-angular/files/7217365/Archive.zip)

On a side note, I see that rxjs 6.6.7 is listed in the Package Versions, but please make sure that RxJS 7 is not somehow installed in the project instead - this might lead to errors, similar to the described one.

**Comment by xinthose** [comment]
I see.  Thank you.  My `@angular/cdk` and `@schematics/angular` were still on version 9, giving me the error.

**Comment by xinthose** [comment]
For some reason, calling `ng add @progress/kendo-angular-layout` tried to install version `0.10.0` of the package, so I ran `ng add @progress/kendo-angular-layout@latest` and it installed version `^6.3.0` like your supplied Archive project had.  Thank you.
