### ISSUE TITLE
[Date Math] Add durationInDays method

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3443]
**Describe the bug**
Be able to get the calculation in number of days between two dates in a similar manner as `durationInMonths`, `durationInYears`, `durationInDecades`, and `durationInCenturies`. 

Reference Ticket #1535911

**Comment by yanmariomenev** [comment]
The item was moved to our feedback portal - https://feedback.telerik.com/kendo-angular-ui/1620974-datemath-add-durationindays-method
