### ISSUE TITLE
Scheduler.slotByPosition method : pointing a line fails and generates an non catchable error

### ISSUE THREAD

**Issue by ckiffel** [telerik/kendo-angular#3444]
## Current behavior
When using the scheduler.slotByPosition method, some specific values seems not to return a slot, for exemple when pointing a line separating 2 cells. An uncatchable error is thrown. In my angular app, i have a global error handler that displays an error to the user.

## Expected behavior
Every point in the scheduler content should match a slot. Define a rule when pointing lines.
At least, i'd like to try - catch the error to handle it propertly.

## Minimal reproduction of the problem with instructions

Here is the stackblitz to reproduce : https://stackblitz.com/edit/angular-gwmlvw?file=app/app.component.ts. Just click on the test button, and see the error in the console. Notice that try catch doesn't catch anything.

## Environment

Scheduler 2.1.5, angular 9+

```

Browser:
Any browser, any version

System:
TypeScript

**Comment by stnikolova** [comment]
No longer reproducible with the latest version of `@progress/kendo-angular-scheduler`: https://stackblitz.com/edit/angular-bjc9xb
