### ISSUE TITLE
floating label sometimes overlap placeholder for kendo-datepicker

### ISSUE THREAD

**Issue by rosh2004** [telerik/kendo-angular#3445]
**Describe the bug**
There is a glitchy behaviour where when I use kendo-floatinglabel with kendo-datepicker, the label overlaps with the placeholder value for the date picker, sometimes it works fine when and the label floats automatically, Other times it doesn't and Overlaps the placeholder.

**To Reproduce**
inside kendo-formfield add a floating label and then add kendo-datepicker inside it. Create the reactive form dynamically, at some point the label will overlap the placeholder

**Expected behavior**
When the datepicker shows the floating label should automatically go above it so the values don't overlap
**Screenshots**
![image](https://user-images.githubusercontent.com/42322609/134476147-ecec170f-1992-47d5-a817-73cec6d97595.png)

**Browser**
 - OS: Windows 10
 - Browser Crome
 - Version latest

**Additional context**

**Comment by Raisolution** [comment]
Hi @rosh2004 ,

We were not able to reproduce the described behavior on our end. Please send us a runnable stackblitz example that demonstrates the current scenario.
