### ISSUE TITLE
[dropdownbutton] popupSettings.animate required

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#3446]
**Describe the bug**
Property `animate` of class PopupSettings is required but should be optional.
https://www.telerik.com/kendo-angular-ui/components/buttons/api/PopupSettings/

This makes it impossible to set any other property of `popupSettings` w/o specifying the `animate` property too. In most cases we don't want to set the animation behavior and due to the fact that this is part is undefined in most concepts, developers may set it to true or false which leads to an inconsistent app look and feel.

**To Reproduce**

                <kendo-dropdownbutton
                    [popupSettings]="{ popupClass: 'header-menu-list'}"
                >
                    [...]
                </kendo-dropdownbutton>

Typescript error: 
Property 'animate' is missing in type '{ popupClass: string; }' but required in type 'PopupSettings'.ngtsc(2741)

**Expected behavior**
According to the text part of the docs, this property has a default value "By default, the open and close animation are enabled"
Ref.: https://www.telerik.com/kendo-angular-ui/components/buttons/api/PopupSettings/#toc-animate

Expected: `animate` should be optional und the default value should be used if property is not specified.

**Comment by Raisolution** [comment]
The issue has been addressed in the latest version `6.3.1`
