### ISSUE TITLE
[DropDownTree] doesn't display a loading spinner

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3447]
**Describe the bug**
Setting the [loading] input property to true doesn't display a loading spinner for the DropDownTree component.

**To Reproduce**
https://stackblitz.com/edit/angular-jmvznb-jvtt1f?file=app/app.component.ts

**Comment by gkarapeev** [comment]
Fix available in the latest dev version - v5.5.0-dev.202111011140

**Comment by gkarapeev** [comment]
Fix shipped with version 5.5.0
