### ISSUE TITLE
Is Kendo for Angular UI is licensed now after 2020

### ISSUE THREAD

**Issue by samkuls** [telerik/kendo-angular#3448]
Hi Team,

We are leavraging the kendo for Angular UI grid component. i can see some error coming up regarding license.
Is kendo for Angular UI is now licensed one. I need to use Kendo Grid for commercial purpose.

Thanks

**Comment by mbechev** [comment]
Hi @samkuls,

The Kendo UI for Angular suite is a commercial library. Starting from December 2020, using any of the UI components from the library requires either a commercial license key or an active trial license key. For more details please check this article:
https://www.telerik.com/kendo-angular-ui/components/my-license/

In case any further questions come up, you can [activate a trial license](https://www.telerik.com/kendo-angular-ui) and open a [support ticket](https://www.telerik.com/account/support-tickets), as this repository is for bug reports only.
