### ISSUE TITLE
[Combobox] ExpressionChangedAfterItHasBeenCheckedError when filter data

### ISSUE THREAD

**Issue by hizliemre** [telerik/kendo-angular#3450]
**Describe the bug**
When combobox data is loaded click on it and open the data popup. First look we have a vertical scroll. But if we filter our data and if filtered data items height less than the popup height scroll is gone. That is the point, when the scroll is gone we got this error. 

**To Reproduce**
- Use ComboboxComponent
-  Enable filter
- Load a lot of data
- Open combobox popup and filter

**Screenshots**
![err](https://user-images.githubusercontent.com/8426937/135254211-03694273-8ab2-4306-aa7a-499264fc49ff.jpg)

**Browser**
 - OS: [Ubuntu 20.04.3]
 - Browser [Chrome]
 - Version [94.0.4606.54 (Official Build) (64-bit)]

**Comment by PhOder** [comment]
I'm having the same issue.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds) of kendo-angular-dropdowns.

**Comment by stnikolova** [comment]
Fix available in **v.5.5.1** of the DropDowns package.
