### ISSUE TITLE
[TabStrip][Scrollable] Selected tab is not scrolled into view when there is a title template

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#3457]
**Describe the bug**
When we select a tab programmatically through the `selectTab` method, the respective tab is selected, but not scrolled into view if there is a title template which contains multiple elements or content which alters the tab header width.

**To Reproduce**

https://stackblitz.com/edit/angular-cboqfv?file=app/app.component.ts

https://stackblitz.com/edit/angular-cboqfv-dfrcuy?file=app/app.component.ts

**Expected behavior**
The tabs are scrolled so that the programmatically selected tab becomes visible.

** Workarounds
- Use the tab `title` input instead of the template or do not use elements which alter the header width in the template:

https://stackblitz.com/edit/angular-cboqfv-hsv2xx?file=app/app.component.ts

https://stackblitz.com/edit/angular-cboqfv-c9t6yt?file=app/app.component.ts

**Comment by Raisolution** [comment]
Fix is available in `v6.3.3`
