### ISSUE TITLE
Angular 4.0.0-rc.x Support?

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular#346]
I haven't had any issues using Kendo for Angular with Angular 4.0.0-rc.x, but is there a time line for when Kendo will officially support Angular 4.0.0?

**Comment by tsvetomir** [comment]
We plan to ship support for 4.0 soon after its official release. We don't have technical issues at the moment, but we have to decide:

- Whether to support Angular 2.x officially after the 4.0 release?
- How to version our packages? We'll likely ship 4.x of our packages to make it easier to match versions.

**Comment by djarekg** [comment]
Makes sense. Thank you for the response.

**Comment by meriturva** [comment]
If angular 2.x is not an LTS version i think you have just to support only 4.x version.

**Comment by anj01** [comment]
When can we expect the support for 4.0? Thanks for a briefly info!

**Comment by tsvetomir** [comment]
We'll start upgrading the components to 4.0 next week. Our plans are to support **only Angular 4.x** for the official release in May.

**Comment by djarekg** [comment]
Angular will be well on they're  to v5 by then. With angular's fast release cycle you need to support new major releases faster than that. Your road map says may. That could be 8 weeks from now potentially.

**Comment by djarekg** [comment]
I didn't mean to post my last comment. I re - read @tsvetomir comment that "only" v4 Will be supported in may. Not that's when support starts.  Sorry

**Comment by tsvetomir** [comment]
I've updated the comment to state 4+ for clarity.

**Comment by rohit-b** [comment]
from next week if all the components are moved to 4.0 then will it mean that no more support for 2.x from next week?

**Comment by tsvetomir** [comment]
More or less - although existing versions will continue to work with 2.x

This is based on the assumption that the migration to 4.x will be painless for the majority of customers. We can reconsider if this is not the case and 2.x stays around for longer.

**Comment by tsvetomir** [comment]
We'll be rolling out Angular 4.x support across all packages later this week.
This will not be an official release yet, so we'll continue with the 0.x versioning.

This is a list of the latest package versions that are compatible with Angular 2.x

    "@progress/kendo-angular-buttons": "^0.23.0",
    "@progress/kendo-angular-charts": "^0.20.3",
    "@progress/kendo-angular-dateinputs": "^0.5.1",
    "@progress/kendo-angular-dialog": "^0.18.1",
    "@progress/kendo-angular-dropdowns": "^0.37.3",
    "@progress/kendo-angular-grid": "^0.22.3",
    "@progress/kendo-angular-inputs": "^0.21.4",
    "@progress/kendo-angular-intl": "^0.11.1",
    "@progress/kendo-angular-l10n": "^0.2.1",
    "@progress/kendo-angular-layout": "^0.23.0",
    "@progress/kendo-angular-scrollview": "^0.9.0",
    "@progress/kendo-angular-sortable": "^0.9.1",
    "@progress/kendo-angular-upload": "^0.19.0",
    "@progress/kendo-data-query": "^0.5.0",
    "@progress/kendo-drawing": "^0.15.4"

**Comment by narendra-agashe** [comment]
@tsvetomir Fantastic news, looking forward to it. Thanks!

**Comment by tsvetomir** [comment]
All packages have been updated to Angular 4 and are now live on http://www.telerik.com/kendo-angular-ui

**Comment by meriturva** [comment]
@tsvetomir just to know....did you notice performance improvements moving to Angular 4?

**Comment by tsvetomir** [comment]
Build times, AoT compilation included, seem to be improved. At run-time it _feels_ a bit snappier.

That said, we're investigating an odd performance regression in IE11.

**Comment by rohit-b** [comment]
thanks for the updates

**Comment by tsvetomir** [comment]
We tagged the Angualr 2 - compatible packages with `ng2` for convenience. See #469
