### ISSUE TITLE
CommonJS Warning for Import '@progress/kendo-ui'

### ISSUE THREAD

**Issue by akshit0614** [telerik/kendo-angular#3460]
After Upgrade Angular from 9 to 12 the below mentioned warning is appered

Warning: C:\Users\akshi\source\repos\MyApp\src\app\Core\pipes\sanitizerPipe.ts depends on '@progress/kendo-ui'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by Raisolution** [comment]
Hello @akshit0614 

This repository is the bug tracker for Kendo UI for Angular. For bug reports related to Kendo UI for jQuery please use the [following bug tracker](https://github.com/telerik/kendo-ui-core/issues/). For assistance with implementing specific scenarios or configurations, please open a [support ticket](https://www.telerik.com/account/support-tickets).
