### ISSUE TITLE
[DropDowns] ExpressionChange error is being thrown when data is assigned in open event

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3461]
**Describe the bug**
Passing an async data to the dropdowns in **open** event handler throws the following error in the console:

![image](https://user-images.githubusercontent.com/33104481/136159071-b6a5c18e-593b-4b7f-a8e3-d707b048bfa1.png)

The error is thrown only when virtual scrolling is enabled with Angular 10+. 

**To Reproduce**
Run the following markup in Angular 10 project (or higher version):
https://stackblitz.com/edit/angular-9kzxry

Attaching an Angular 12 project:
[multiselect-A12.zip](https://github.com/telerik/kendo-angular/files/7291793/multiselect-A12.zip)

1. Run **npm install**.
2. Execute **ng serve**.
3. Open MultiSelect popup.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds) of kendo-angular-dropdowns.

**Comment by stnikolova** [comment]
Fix available in **v.5.5.1** of the DropDowns package.
