### ISSUE TITLE
[Grid] Add an optional, generic type parameter for the data item of the Grid and its templates

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3463]
It will be a nice improvement if there is an option to set a specific type for the Grid data item and the templates. This will allow checking the types inside the templates when **fullTemplateTypeCheck** is on.

**Comment by Raisolution** [comment]
Demand to be tracked in the dedicated FP item:
https://feedback.telerik.com/kendo-angular-ui/1538528-add-an-optional-generic-type-parameter-for-the-data-item-of-the-grid-and-its-templates
