### ISSUE TITLE
[Upload][FileSelect][A11y] Improve accessibility in Upload and FileSelect components

### ISSUE THREAD

**Issue by ciiara** [telerik/kendo-angular#3464]
In the Select File button's implementation there are nested elements, which goes against the following:
https://dequeuniversity.com/rules/axe/4.2/nested-interactive
This includes an <input> element which has an aria-hidden="true" label, which is not considered best practice.
For reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute#description

Example:
https://stackblitz.com/edit/angular-ivy-x2ya11?file=src%2Fapp%2Fapp.module.ts

**Comment by Raisolution** [comment]
The linked WCAG criteria refers to nested _interactive_ elements. This is not the case in the current implementation.

The `Select Files` button wraps the `<input type="file" />` element for styling purposes. The input element itself is hidden and has `tabindex` of `-1` thus it is not interactive. It is only used to hold the file selected by the user.
