### ISSUE TITLE
saveAsPDF() causes a memory leak

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3465]
**Describe the bug**
Calling the saveAsPDF() function of the Grid causes a memory leak. The created PDFName object increases its instances when calling the saveAsPDF() function. That is observable when taking a snapshot in developer tools console.

**To Reproduce**
Please run the following project and create a few snapshots after calling the saveAsPDF() function:
[pdf-export.zip](https://github.com/telerik/kendo-angular/files/7336980/pdf-export.zip)
![Capture](https://user-images.githubusercontent.com/20015190/137109797-2bac1291-e691-401a-91fa-e5ecc7f2ff22.PNG)

**Additional context**
It looks like the PDFName_cache variable from kendo-drawing/src/pdf/core.js should be cleared at some point.

**Comment by sherajuser** [comment]
Similar issue, following this thread....

**Comment by tswetti** [comment]
Fixed in [v15.3.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.3.0)
