### ISSUE TITLE
Package kendo-charts-1.19.1.tgz is missing from the yarn registry

### ISSUE THREAD

**Issue by dropandfly23** [telerik/kendo-angular#3468]
In my Angular project , i am Using "@progress/kendo-angular-charts": "^5.2.1" dependency that requires a dependency kendo-charts-1.19.1.tgz.
While building my project package,json tries to download from the yarn registry "https://registry.npmjs.org/@progress/kendo-charts/-/kendo-charts-1.19.1.tgz" but i get an answer that this dependency is not found.

Is it possible that this version was deleted or is it just not available anymore?

**Comment by montella1507** [comment]
Duplicit to https://github.com/telerik/kendo-angular/issues/3467
