### ISSUE TITLE
[TabStrip] Scroll buttons not handled correctly when adding/removing tabs

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3469]
**Describe the bug**
When the TabStrip is set to `scrollable`, the scroll buttons are not correctly enabled/disabled when tabs are dynamically added or removed. Also, if the tabs are restored programatically the scroll buttons will not appear.

**To Reproduce**
  1. Run this example https://stackblitz.com/edit/angular-83ccko-rk2k9z?file=app/app.component.ts
  2. Reduce the width of the example, so that the scroll buttons appear.
  3. Remove tabs from the close button.
  4. Resize the example.
  4. Observe the buttons.
  5. Restore the tabs - no scroll buttons will appear.

**Expected behavior**
When `scrollable` is set to `true`, the `scrollButtons` will have the `auto` mode enabled. Thus, they should appear/disappear when tabs are added/removed programatically. Also, the `scrollButtons` should toggle the enabled/disabled look.

**Workaround**

https://stackblitz.com/edit/angular-83ccko-jcspb9?file=app%2Fapp.component.ts (based on [comment](https://github.com/telerik/kendo-angular/issues/3469#issuecomment-972610385))

https://stackblitz.com/edit/angular-bqumjn?file=src%2Fapp%2Fapp.component.ts (based on [comment](https://github.com/telerik/kendo-angular/issues/3469#issuecomment-1422940693))

**Comment by dtopalov** [comment]
Recreating the TabStrip with the current tabs collection after adding/removing a tab seems to resolve the problem and can be used as a workaround until a fix becomes available:

https://stackblitz.com/edit/angular-83ccko-jcspb9?file=app/app.component.ts

**Comment by subikshajaya** [comment]
> Recreating the TabStrip with the current tabs collection after adding/removing a tab seems to resolve the problem and can be used as a workaround until a fix becomes available:
> 
> https://stackblitz.com/edit/angular-83ccko-jcspb9?file=app/app.component.ts

In my case it's working as expected for dynamically added tabs, Thanks for the workaround

**Comment by bartoszbenna** [comment]
@dtopalov Your workaround will not work in all cases, since the `ngIf` will destroy the components that are already rendered inside the tabStrip with `keepTabContent` enabled. Any chance this issue will be fixed soon?

**Comment by AKrasovski** [comment]
This issue should definetely be fixed - it is very common to add/rempove tabs dynamically and we need the scrolling capability. I used another workaround. If you have scrollable set to "auto", then after adding or removing tabs reassign scrollable property linked to your markup.
        scrollable = { scrollButtons: 'visible' };
        setTimeout(() => {
          scrollable = { scrollButtons: 'auto' };
        });

**Comment by elca-lan** [comment]
I have also been running into that issue. From a design / UX perspective, I would argue that the main point of having scrollable tabs is for cases where tabs can be added or removed. In any other case, if there is not enough room for the tabs, maybe for responsiveness reasons, using a tab strip is not a good option anyway.

Also... looking into the source code a bit... shouldn't that be _relatively_ easy to fix?

**Comment by slavenai** [comment]
Fixed in `v16.0.0` of `kendo-angular-layout` package.
