### ISSUE TITLE
[Upload] clicking the action buttons blurs the component

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3472]
**Describe the bug**
When using [autoUpload]="false", select a file to upload and click one of the action buttons "Cancel" or "Upload" the component fires a blur event.

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-rkrb6m?file=app%2Fupload.component.ts

**Expected behavior**
Clicking the action buttons shouldn't emit a blur event. Instead, the "Select files" button should be focused.

**Comment by Raisolution** [comment]
The issue has been addressed in `v7.1.5` of the `kendo-angular-upload` package.
