### ISSUE TITLE
The Scheduler toolbar items cannot be reached with the keyboard

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#3473]
**Describe the bug**
The Scheduler toolbar can't be focused using the keyboard. The built-in actions can still be operated using dedicated shortcuts, as described in the [Keyboard Navigation](https://www.telerik.com/kendo-angular-ui/components/scheduler/keyboard-navigation/) help article.

The same is true for the footer as well, see https://github.com/telerik/kendo-angular/issues/3268.

**To Reproduce**

1. Open the [KB navigation demo](https://www.telerik.com/kendo-angular-ui/components/scheduler/keyboard-navigation/).
2. Press Tab to focus the component.
3. Use the arrow keys to navigate inside the component.
4. Notice that the focus never reaches the toolbar.

**Expected behavior**
The toolbar should be able to receive focus, either as a separate tab stop or as part of the Scheduler built-in navigation.

**Additional context**
See rationale in [6.9.1.1 Ensure Basic Access Via Navigation ](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_shortcuts_design_basic).

**Comment by tsvetomir** [comment]
Fixed in the [development builds](https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/).

**Comment by Raisolution** [comment]
Fix is available the latest official version of the Scheduler package `v2.1.6`.
