### ISSUE TITLE
[TextBox] Value is duplicated when input is Japanese IME in Safari

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3474]
When a Japanee IME character is typed into the TextBox input, all characters that have been typed so far are added again.

For example, if "あかさか" is typed, the output will be the following: 

ああ after typing あ

あああか after typing か

あああかあかさあかさ after typing さ

あああかあかさあかさあかさかあかさか after typing the last か

https://user-images.githubusercontent.com/52581229/137705125-f364dae7-34d6-4238-879e-e5059594232b.MP4

**To Reproduce**

  1. Open this [example](https://stackblitz.com/edit/angular-vte7vw?file=app/app.component.ts) in Safari.
  2. Change the input language to Japanese.
  3. Start typing and observe the mentioned behavior.

**Browser**
 - Safari

**Comment by Raisolution** [comment]
The issue has been addressed in `v7.5.2` of the `kendo-angular-inputs` package.
