### ISSUE TITLE
 TabStripComponent overlaps Dialog component

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#3475]
**Describe the bug**
When we have a tab component and some dialog component inside it, that tab overlaps the dialog component.

**To Reproduce**
Go to https://stackblitz.com/edit/angular-nucgh9?file=app%2Fapp.component.ts

**Expected behavior**
Dialog should overlap the tab.

**Comment by spierala** [comment]
It would be great if Kendo-Angular could provide a similar approach like in Taiga UI: https://taiga-ui.dev/components/dialog#directive

There it is possible to create the dialog in the template with a Directive. 
The dialog is inserted on top level in the DOM, so no overlap issues can happen:

![image](https://user-images.githubusercontent.com/1272446/198253472-f71ae707-863d-4bf7-9a31-cfdaf8e5cb81.png)
