### ISSUE TITLE
[DropDownTree] bounding to a FormControl triggers an error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3478]
**Describe the bug**
When the DropDownTree is bound to a FormControl which has an initial value then the `Error: Expected valueDepth to be set.` is thrown even though the valueDepth property is set.

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-kauvjd-thkzky

**Comment by gkarapeev** [comment]
Fix shipped with version 5.5.0
