### ISSUE TITLE
[Bug] DropDownTree - Filter input looses focus while typing

### ISSUE THREAD

**Issue by ntziolis** [telerik/kendo-angular#3479]
When using the DropDownTree component with `[filterable]=true` the filter input field looses focus while the user is typing in some situations. 

Please note:
- This issue can be observed happens in the **official Kendo Demos** for filtering for DropDownTree
   -  This means user config error can be excluded as a root cause 
- The problem does not always appear, but seems to happen only in some circumstances
  - The repro below seems to trigger it each time, but if not try selecting / clearing / searching  in different order
  - It will fail at some point
- It does seem to have something todo with adding a character that results in no search results (but this is only an high level observation)
- The issue also appears in the latest version of the packages

**To Reproduce**
- Visit the Kendo demo site:  
   https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdowntree/filtering/#toc-filtering-with-the-hierarchy-binding-directive
- Select "Tables & Chairs" without searching
- Click on the control again and type 'chat' in the filter input (which will result in zero results)
- Now the filter input should have lost its focus

**Expected behavior**
The filter input should not loose its focus while the user is typing.

**Screenshots**

**Browser**
 - OS: Windows 10 (latest)
 - Browser: Chrome / Edge
 - Version: latest

**Comment by jswm-pfr** [comment]
Bump

Have any of you stumbled upon a workaround while we wait for the fix? 🤔

We currently avoid using the kendoDropDownTreeFlatBinding and instead have implemented our own recursive search method, hasChildren and fetchChrildren. The code would just be so much simpler if it worked 🤩

**Comment by jellehellmann** [comment]
Any update on this issue ?

**Comment by KimBum** [comment]
Update: As per #3644, in version **16.2.0** this should have been addressed, but only the error got hidden. Is there any timeframe for when we can expect the filtering to finally work with selected values?

**Comment by stnikolova** [comment]
@KimBum The team has committed to resolving the issue and is included in our development plans. However, its delivery depends on internal prioritization and available capacity. We'll be updating the issue accordingly once the fix has been released as part of a `develop` version.

**Comment by slavenai** [comment]
Fixed in `v16.4.0` of `kendo-angular-dropdowns` package.
