### ISSUE TITLE
Certain data sets cause chart to crash browser page

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-angular#348]
Creating a multi series column chart with date category axis.  With certain data sets, something gets stuck in a loop or something.  It chews up memory until it crashes the browser page.  Only tried in chrome.

The plunker linked here will work, but if you remove the comment from the one line of the seed data that is commented out, the page will crash.

`{ 'amount': 100, 'liftDate': new Date('2017-01-24T19:48:36.000Z'), 'max': 105, 'reps': 3 },`
is commented out in app.component.ts  uncomment that line and the crash happens

[plunker](http://plnkr.co/edit/6oRowftK06p2rTBwz0u4?p=preview)

**Comment by danielkaradachki** [comment]
The default baseUnit is determined based on the minimum difference between subsequent categories, so a category for each minute in a period of one month will be generated if the specified item is added. You can avoid the problem by setting big enough specific [baseUnit](http://www.telerik.com/kendo-angular-ui/components/charts/api/CategoryAxisItemComponent/#toc-baseunit) or by setting the `baseUnit` to `"fit"`.

**Comment by ncrawlins** [comment]
thanks, that prevents the issue.
