### ISSUE TITLE
Start drag selection below the last row throws an error

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3480]
**Describe the bug**
When drag selection of the Grid is enabled and start dragging below the last row to any row:

![image](https://user-images.githubusercontent.com/33104481/138681320-85c0abd8-1ef1-4551-9847-cc2a9221ab78.png)

the following error has been thrown:

```TypeError: Cannot read properties of null (reading 'rowIndex')```

**To Reproduce**
https://stackblitz.com/edit/angular-6ah6f4-bscave
1. Start dragging below the last row
2. Release the mouse on any row and see the error.

**Workaround**

As a workaround create a custom **pointerdown** event listener to the Grid content and if the clicked element is not TD, stop its propagation e.g.:

```ts
  ngAfterViewInit() {
    const el = document.querySelector('.k-grid-content');
    this.listener = this.renderer.listen(el, 'pointerdown', (e) => {
      if (e.target.tagName !== 'TD') {
        e.stopImmediatePropagation();
      }
    });
  }
```

Here is an example demonstrating the workaround:
https://stackblitz.com/edit/angular-6ah6f4-d8sqxa

**Comment by slavenai** [comment]
Fixed in `v7.2.4` of the Grid package.
