### ISSUE TITLE
[Grid] Resizing the Grid column using the keyboard

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3485]
Currently, keyboard navigation makes the Grid WCAG 2.1 compliant by meeting most of the requirements. It would be nice to have the option to resize the Grid column using the keyboard.

**Comment by sherajuser** [comment]
Similar issue, Keys were working sometimes, and sometimes not, is there any specific reason.

**Comment by mbechev** [comment]
The feature request is now logged in our **Feedback Portal**:

https://feedback.telerik.com/kendo-angular-ui/1541347-column-resizing-reordering-through-keyboard
