### ISSUE TITLE
Angular application not showing the dropdownlist. Other Angular applications are showing.

### ISSUE THREAD

**Issue by jitheshkramesh** [telerik/kendo-angular#3486]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by jitheshkramesh** [comment]
Project reference : https://github.com/jitheshkramesh/Angular-Report-Module/

**Comment by Raisolution** [comment]
Hi @jitheshkramesh 

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.
