### ISSUE TITLE
DropDownTree forces all parent items to be selectable

### ISSUE THREAD

**Issue by geo242** [telerik/kendo-angular#3488]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
All parent items are available for selection unless they are disabled.

## Expected behavior
Items that are parents should have a third state that allows them to be expanded but not selected. 

In many real world use cases, parents are categories that are not supposed to be selected and only exist to categorize the child options.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/ny1rsb--run?file=app/app.component.ts

## Environment
All

Browser:
All

System:
All

**Comment by yanmariomenev** [comment]
Thread is moved to our Feedback Portal - https://feedback.telerik.com/kendo-angular-ui/1612172-enhancement-force-all-parent-items-to-be-selectable
