### ISSUE TITLE
Do we have a Row changed event for Grid?

### ISSUE THREAD

**Issue by raghuSanapathi** [telerik/kendo-angular#349]
I worked with telerik silverlight grid control .there we are having column changed event and rowchanged event which are helpful for inline editing .here in kendoangular2 we dont have those events can we get those events so that i can implement my logic like silverlight telrik grid.

**Comment by KirilNN** [comment]
Can you please elaborate what exactly do you want to achieve?

**Comment by tsvetomir** [comment]
I assume that you mean in-cell editing where you can edit the value of each cell individually. This is not yet supported, but is on our roadmap for our autumn release.

The Grid currently supports [inline editing](http://www.telerik.com/kendo-angular-ui/components/grid/editing/) and external forms.
