### ISSUE TITLE
Some component templates don't work with *ngIf directive in Angular v12

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3491]
**Describe the bug**
The ngIf structural directive doesn't work with the templates listed below in Angular v12.
List of components and templates:

- [x] 1. BreadCrumb

BreadCrumbItemTemplateDirective - https://www.telerik.com/kendo-angular-ui/components/navigation/api/BreadCrumbItemTemplateDirective/

- [x] 2. Calendar & MultiViewCalendar

 
CellTemplateDirective - https://www.telerik.com/kendo-angular-ui/components/dateinputs/api/CellTemplateDirective/

- [x] 3. Pager

~~PagerTemplateDirective - https://www.telerik.com/kendo-angular-ui/components/grid/api/PagerTemplateDirective/~~
PagerTemplateDirective - https://www.telerik.com/kendo-angular-ui/components/pager/template/

- [x] 4. Gantt

GanttTaskContentTemplateDirective - https://www.telerik.com/kendo-angular-ui/components/gantt/api/GanttTaskContentTemplateDirective/

- [x] 5. FloatingActionButton

DialItemTemplateDirective - https://www.telerik.com/kendo-angular-ui/components/buttons/api/DialItemTemplateDirective/

- [x] 6. TreeView
kendoTreeViewNodeTemplate  - https://www.telerik.com/kendo-angular-ui/components/treeview/api/NodeTemplateDirective/

- [x] 7. Stepper
kendoStepperStepTemplate -https://www.telerik.com/kendo-angular-ui/components/layout/api/StepperStepTemplateDirective/

**To Reproduce**
[treeview-t.zip](https://github.com/telerik/kendo-angular/files/7481594/treeview-t.zip)
Run the project and set the condition to true or false.
This also applies to the other component templates listed above.

**Comment by Raisolution** [comment]
All problematic packages have been released with the corresponding fixes available.
