### ISSUE TITLE
How to perform server side paging/sorting/filtering in .NET Core 3.1 + Kendo angular grid?

### ISSUE THREAD

**Issue by sayedgt** [telerik/kendo-angular#3494]
Please provide a working example to achieve server side paging, filtering and sorting. I am using kendo angular and **asp.net core 3.1** rest api.

**Comment by Raisolution** [comment]
Hi @sayedgt ,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configurations.

**Comment by sayedgt** [comment]
That's why I have submitted this under documentation improvement category. Current documents are out of data in almost every scenario. Could you provide a updated document for this scenario please. I am performing initial r&d to identify if your product can meet my requirements before paying.

**Comment by Raisolution** [comment]
We would gladly help with the evaluation of the Kendo UI for Angular product. To be able to assist, please [start a trial](https://www.telerik.com/login/kendo-angular-ui) and open a [support ticket](https://www.telerik.com/account/support-tickets) in our system.
