### ISSUE TITLE
[Scheduler] Screen readers don't read day cell information properly

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3495]
**Describe the bug**
Screen readers like Mac VoiceOver don't read day cell information properly.

**To Reproduce**
Go to any of our scheduler demos and enable VoiceOver it will announce the day cell as numbers.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds) of kendo-angular-scheduler.
