### ISSUE TITLE
[ColorPicker] valueChange fired twice on color selection

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3497]
**Describe the bug**
The `valueChange` event is fired twice when the `ColorPicker` is displaying the `gradient` view and there is no color selected.

**To Reproduce**
1. Open the ColorPicker
2. Select a color
3. See the log => `valueChange` is fired twice

The behavior repeats if consequently the value is cleared and then new color is selected again.

https://stackblitz.com/edit/angular-n86fmr-trnko4?file=app/app.component.ts

**Comment by Raisolution** [comment]
FIx is available in `v8.0.0` of the `kendo-angular-inputs` package.
