### ISSUE TITLE
Missing cdn bundles on kendo-drawing kendo-charts packages

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#350]
Actually kendo deploys cdn package for all angular 2 components but now we are starting using kendo-chart (to give it a try). kendo-angular-charts has dependency to kendo-charts and kendo-drawing but they don't have any "bundle" ready. I think you have to share same approach, so publish also "cdn/js" file.

What do you think?

**Comment by tsvetomir** [comment]
The `kendo-drawing` and `kendo-charts` packages ship a CJS bundle in `dist/npm/main.js`. The kendo-angular packages ship an UMD bundle in `dist/cdn/[package-name].js`.

Do you need the UMD bundle in your scenario? The CJS bundle is still a single file.

**Comment by meriturva** [comment]
When i use @progress/kendo-angular-charts i need to include also package: @progress/kendo-drawing and @progress/kendo-charts

problems are:
- main.js is a name (same of kendo-charts) that i cannot copy on dist/lib folder, i have to rename it or put in a different sub folder
- CJS is another bundle format so we have all angular 2 packages in UMD format other in CJS

I know that final solution is to build dist with one single vendor bundle file with treeshake approach but you have also situation where you need a quick solution just with UMD bundles. So i think that an uniform approach has to be released.

**Comment by meriturva** [comment]
Hi @tsvetomir ...i have seen that` kendo-drawing` has now cdn folder with bundle. Are you going to do the same with` kendo-charts`? I hope yes!

So thanks.

**Comment by tsvetomir** [comment]
Right, we added a bundle for the drawing package due to an unrelated issue with the demo site. Sorry for not letting you know right away.

The `kendo-charts` package is included in the CDN bundle of the `kendo-angular-charts` package. You shouldn't need to reference it directly.

**Comment by meriturva** [comment]
Perfect!
So thanks.
