### ISSUE TITLE
Event which have multiple resourceIds not show if 1 Resource is selected for Calendar

### ISSUE THREAD

**Issue by joharzmn** [telerik/kendo-angular#3500]
**Describe the bug**
If an event has an array of multiple resource Ids e.g [1,2] and the calendar is set to show only one Resource with Id 1 or 2 then the calendar will not show events for that resource.

**To Reproduce**
- Create an event with an array of multiple resource ids. 
- Set calendar to show only 1 resource for the time being.
- We will see that calendar for 1 selected resource won't show any event even resourceId is in the array.

Here is the stackbiltz link for the issue: 
[Stackbiltz Project for Issue](https://stackblitz.com/edit/angular-gr5jxj-qtpob9-z348tq?file=app%2Fapp.component.ts)

**Expected behavior**
If we set an array of multiple resource ids, the calendar should show an event for resource independent of the other resource.

**Browser**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 95.0.4638.54 (Official Build) (64-bit) 

**Additional context**
Video of the issue(without audio): https://watch.screencastify.com/v/YECkPsaxmXGngh8XMd8B

**Comment by mbechev** [comment]
Duplicate https://github.com/telerik/kendo-angular/issues/3501
