### ISSUE TITLE
Announcement: Switching to the Ivy library format

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#3502]
We're hard at work on a **major update** to all _Kendo UI for Angular_ packages with the following **breaking changes**:
1. Packages will be shipped as Ivy libraries compatible with Angular 12 and 13.
2. The package structure is changed to match the [APF v12](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) specification.
3. ⚠ This and future versions of the packages will not be compatible with Angular 11 and below. ⚠

This is an important milestone for the _Kendo UI for Angular_ and will be our first release with native Ivy support. So far we've relied on the Angular Compatibility Compiler (ngcc) to support Ivy projects. While this approach works, it's far from optimal and leads to longer build times.

With Angular v11 dropping out of [LTS](https://angular.io/guide/releases#support-policy-and-schedule) in May 2022, we're finally able to upgrade our code base and packages to Ivy. This is the last version of Angular that does not support Ivy libraries.

**The time frame for the official release is set for May (R2 2022).**

_Development builds are already available for some of the components, see "Preview Builds" below._

## Support for Angular 8–11
Existing package versions will be tagged with "ng8" through "ng11" on npm. These tags can substitute regular version numbers in both command-line `npm` usage and `package.json`, for example:
```
ng add @progress/kendo-angular-grid@ng11
```

We plan to ship only very limited updates on these channels, like high severity security fixes. For regular updates, you'll need to grab the latest versions and upgrade to Angular v12 or later.

## Preview Builds
A dedicated "next" distribution tag will be gradually populated with the updated versions for you to try out. For example:

```sh
ng add @progress/kendo-angular-buttons@next
```

See the list below for availability of the preview builds for each component.

## Updated Package Versions
| Package name                    | Available in "next" | Official version |
| ---                             | :---:               | ---              |
| kendo-angular-barcodes          | ✅                  | 2.x |
| kendo-angular-buttons           | ✅                  | 8.x |
| kendo-angular-charts            | ✅                  | 7.x |
| kendo-angular-common            | ✅                  | 3.x |
| kendo-angular-conversational-ui | ✅                  | 5.x |
| kendo-angular-dateinputs        | ✅                  | 7.x |
| kendo-angular-dialog            | ✅                  | 7.x |
| kendo-angular-dropdowns         | ✅                  | 7.x |
| kendo-angular-editor            | ✅                  | 4.x |
| kendo-angular-excel-export      | ✅                  | 5.x |
| kendo-angular-gantt          | ✅                  | 2.x |
| kendo-angular-gauges            | ✅                  | 5.x |
| kendo-angular-grid              | ✅                  | 7.x |
| kendo-angular-icons             | ✅                  | 2.x |
| kendo-angular-indicators        | ✅                  | 2.x |
| kendo-angular-inputs            | ✅                  | 9.x |
| kendo-angular-intl              | ✅                  | 4.x |
| kendo-angular-l10n              | ✅                  | 4.x |
| kendo-angular-label             | ✅                  | 4.x |
| kendo-angular-layout            | ✅                  | 7.x |
| kendo-angular-listbox          | ✅                  | 1.x |
| kendo-angular-listview          | ✅                  | 4.x |
| kendo-angular-menu              | ✅                  | 4.x |
| kendo-angular-navigation        | ✅                  | 2.x |
| kendo-angular-notification      | ✅                  | 4.x |
| kendo-angular-pager             | ✅                  | 4.x |
| kendo-angular-pdf-export        | ✅                  | 4.x |
| kendo-angular-popup             | ✅                  | 5.x |
| kendo-angular-progressbar       | ✅                  | 3.x |
| kendo-angular-ripple            | ✅                  | 4.x |
| kendo-angular-scheduler         | ✅                  | 4.x |
| kendo-angular-scrollview        | ✅                  | 5.x |
| kendo-angular-sortable          | ✅                  | 5.x |
| kendo-angular-toolbar           | ✅                  | 6.x |
| kendo-angular-tooltip           | ✅                  | 4.x |
| kendo-angular-treelist          | ✅                  | 5.x |
| kendo-angular-treeview          | ✅                  | 7.x |
| kendo-angular-typography        | ✅                  | 2.x |
| kendo-angular-upload            | ✅                  | 9.x |

## How To Upgrade
Follow the instructions at [Keeping Up to Date](https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/#toc-updating-to-latest-versions) to get the latest versions of all packages.

## Component Breaking Changes
* Buttons
  * The `shape` property in `Button`, `DropDownButton` and `FloatingActionButton` is not available anymore.
* Dropdowns
  * The `fillMode`, `rounded` and `size` options of the `AutoComplete` no longer support `null`. Use `'none'` instead.
  * The `fillMode`, `rounded` and `size` options of the `ComboBox` no longer support `null`. Use `'none'` instead.
  * The `fillMode`, `rounded` and `size` options of the `DropDownList` no longer support `null`. Use `'none'` instead.
  * The `fillMode`, `rounded` and `size` options of the `DropDownTree` no longer support `null`. Use `'none'` instead.
  * The `fillMode`, `rounded` and `size` options of the `MultiColumnComboBox` no longer support `null`. Use `'none'` instead.
  * The `fillMode`, `rounded` and `size` options of the `MultiSelect` no longer support `null`. Use `'none'` instead.
  * The `fillMode`, `rounded` and `size` options of the `MultiSelectTree` no longer support `null`. Use `'none'` instead.
* Layout
  * The `fillMode`, `rounded`, `size` and `themeColor` options of the `Avatar` no longer support `null`. Use `'none'` instead.

**Comment by labeled** [comment]
What's the status on having all these available in a release version? (not next)

**Comment by tsvetomir** [comment]
We're aiming to wrap this up by the end of the month, as originally planned. Maybe a week earlier if all goes well.

**Comment by JamesKnippel** [comment]
Looking forward to this.

**Comment by steve3d** [comment]
finally we can have tree-shakeable, thanks for the effort!

**Comment by kasual1** [comment]
Thanks a lot to the team! Really appreciate how well this effort has been planned. Looking forward to this for getting even faster build times :)

**Comment by steve3d** [comment]
when release `R2 2022` version, can we expect all component to be Ivy libraries? 

for me, the treelist and treeview are most important libraries .

**Comment by tsvetomir** [comment]
All Ivy packages are released and the web site will be updated shortly. Enjoy!

Please, open new issues or support tickets if you experience any problems.

**Comment by digeomel** [comment]
Can you please update some of the sample code in your public github repo (e.g. the coffee-warehouse stand-alone project) to the new Ivy components? Thank you.

**Comment by tsvetomir** [comment]
@digeomel We've updated the shared `/examples` project and we'll address the standalone examples next.

The coffee-warehouse demo is updated in https://github.com/telerik/kendo-angular/pull/3687.
