### ISSUE TITLE
[Calendar] Redundant aria roles rendered on calendar host element when in classic mode

### ISSUE THREAD

**Issue by dimitar-pechev** [telerik/kendo-angular#3504]
When in classic mode, an inner element of the calendar handles the focus and is assigned the corresponding aria roles. The host element, however, incorrectly still has some aria attributes which are redundant and can lead to misleading announcements. Additionally, the `role="grid"` attribute is incorrectly assigned to the focusable element which is not the actual table element, containing the `rowgroup`s. In VoiceOver this results in reading `table with 0 rows, 0 columns` when the focus moves to the navigation buttons.

![image](https://user-images.githubusercontent.com/18740853/141805938-f9020ed4-9657-4d76-8cd4-55757ce52782.png)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by stnikolova** [comment]
Fix available in **v.6.0.0** of the Date Inputs package.
