### ISSUE TITLE
[Splitter] sizeChange event is triggered inconsistently

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3509]
**Describe the bug**
When а common splitter is dragged to resize the two adjacent panes, the **sizeChange** event is triggered differently depending on where the **size** option is set. 

- having the following Splitter configuration, the event is triggered for both panes, returning a percentage value for the pane which has set **size** property and in pixels for _Pane 2_  (no size option):

```html
<kendo-splitter-pane 
          [collapsible]="true" 
          [scrollable]="false"
          size="50%"
          (sizeChange)="firstPane($event)"
      >
      Pane 1
      </kendo-splitter-pane>
      <kendo-splitter-pane 
          [collapsible]="true" 
          [scrollable]="false" 
          (sizeChange)="secondPane($event)"
        >
        Pane 2
</kendo-splitter-pane>
```
#### Example
Check the console:
https://stackblitz.com/edit/angular-6sxnr9-flsuan

- having the following Splitter configuration, the event is triggered for _Pane 2_ only (where the size property is set), returning a percentage value:
```html
<kendo-splitter-pane 
          [collapsible]="true" 
          [scrollable]="false"
          (sizeChange)="firstPane($event)"
      >
      Pane 1
      </kendo-splitter-pane>
      <kendo-splitter-pane 
          [collapsible]="true" 
          [scrollable]="false" 
          size="50%"
          (sizeChange)="secondPane($event)"
        >
        Pane 2
</kendo-splitter-pane>
```

#### Example
Check the console:
https://stackblitz.com/edit/angular-6sxnr9-6l164b

**Expected behavior**
Triggering the **sizeChange** event should be consistent, regardless of the **size** option.

**Comment by Raisolution** [comment]
Fixed in v17.0.0
