### ISSUE TITLE
Dialog and DialogService

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#351]
I can't use the DialogService like mentioned here: http://www.telerik.com/kendo-angular-ui/components/dialog/service/

via `DialogModule.forRoot()`

With AoT compiling, I'm getting an error:

> Error encountered resolving symbol values statically. Calling function 'DialogModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

I'm trying to register the service in my module directly via providers:
```
    providers: [
        DialogService
    ]
```

Not tested yet :)

**Comment by gyoshev** [comment]
This seems to be a problem related to [this issue](https://github.com/angular/angular-cli/issues/3674).

We have managed to workaround this by registering the service provider directly, as you have mentioned:

    import { NgModule } from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';
    import { AppComponent } from './app.component';
    import { DialogModule, DialogService } from '@progress/kendo-angular-dialog';

    @NgModule({
        bootstrap:    [ AppComponent ],
        declarations: [ AppComponent ],
        imports: [
          DialogModule,
          BrowserModule
        ],
        providers: [
          DialogService
        ]
    })
    export class AppModule {}

The above seems to be working in AoT builds as well. Any dynamically loaded components need to be registered in the module `entryComponents`.

**Comment by on3al** [comment]
This is a problem again in Angular 6.0.

**Comment by gyoshev** [comment]
@on3al The Dialog can be used with Angular 6 in the same way as described in the article. Make sure you `npm install rxjs-compat@6` and use the latest versions of the packages. The `forRoot()` method is deprecated and removed from the documentation. The DialogModule needs to be imported to use the `kendoDialogContainer` directive, and any dynamically created components in the Dialog need to be added to `entryComponents`.

If the problem persists, please provide more details on how to reproduce the issue.
