### ISSUE TITLE
[Chart] Shared tooltip doesn't highlight Line Chart points correctly

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3512]
**Describe the bug**
The shared tooltip doesn't highlight Line Chart points correctly(in most cases they are not highlighted). If the tooltip isn't shared, then the series is highlighted correctly.

**To Reproduce**
Hover over the series in the following demo:
https://stackblitz.com/edit/angular-h1hcav-wsu8ca?file=app/app.component.ts
Screen recording:
http://somup.com/crX36H0Dgz

**Comment by svetq** [comment]
This is no longer reproducible with v 14.1.0:
https://stackblitz.com/edit/angular-ys2vk3
