### ISSUE TITLE
[Scheduler] Missing role attribute for toolbar buttons

### ISSUE THREAD

**Issue by ciiara** [telerik/kendo-angular#3515]
**Describe the bug**
The buttons in the view selector toolbar for the scheduler are missing a role attribute.
As a result, whenever a scheduler is nested inside a form element and the view of the scheduler is changed, the form gets submitted.

**To Reproduce**
1. Make sure that the code example shared below has enough room to display the view buttons as toolbar buttons instead of overflow buttons.
1. Click on any of the scheduler's views.

<img width="410" alt="Screenshot 2021-11-25 at 15 54 01" src="https://user-images.githubusercontent.com/25002257/143454838-83f247ed-9690-4cbd-a907-4a8cb99ad1f3.png">

https://stackblitz.com/edit/angular-mcbzjm-nphtgd?file=app/app.component.ts

**Expected behavior**
The change of the scheduler's view should not result in the submitting of a form.

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds).

**Comment by stnikolova** [comment]
Fix available in **v.3.0.0** of the Scheduler package.
