### ISSUE TITLE
[TreeList] FlatBindingDirective.data

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#3516]
**Describe the bug**

For `FlatBindingDirective` and I assume `HierarchyBindingDirective`, the `data` property returns undefined.

**To Reproduce**

https://stackblitz.com/edit/angular-bx8rkd?file=app%2Fname.component.ts

Click on the name column to see a console log 

![image](https://user-images.githubusercontent.com/13205912/143608018-58bad0b1-2897-4ad7-b3fa-ab3c1a5705de.png)

Uncomment the line in name.component to see a red swiggle for originalData

![image](https://user-images.githubusercontent.com/13205912/143607731-62cbdd2d-24f4-4a3f-9609-64719f638a4f.png)

**Expected behavior**

A way to access the data associated with the directive, either via `data` or `originalData` property

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by slavenai** [comment]
Hi @cheng93 ,
As this repository is for bug reports only, if you need help with a specific use-case or configuration, please use our [support system](https://www.telerik.com/account/support-tickets).
