### ISSUE TITLE
[TreeList] Virtual scrolling with locked column

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#3518]
**Describe the bug**
 Virtual scrolling with locked column breaks conditional rendering.
There are a lot of whitespace below the last row.

**To Reproduce**

https://stackblitz.com/edit/angular-en3hsl?file=app/app.component.ts

![image](https://user-images.githubusercontent.com/13205912/143862393-e530ac83-ea1b-4724-bbff-60e281dc8e0e.png)

**Expected behavior**
No whitespace with locked columns

If you change the first column to be unlocked, you'll notice the conditional rendering kicks in.

![image](https://user-images.githubusercontent.com/13205912/143862478-6809f3b2-34fa-4155-a9ed-44cdb9567cbf.png)

**Screenshots**

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by dtopalov** [comment]
Hello @cheng93,

Both the Locked Columns and Virtual Scrolling functionalities require the TreeList height to be set explicitly. Dynamic height based solely on the content is not supported when either Locked Columns or scrolling are enabled.
