### ISSUE TITLE
[Grid] keydown event doesn't fire on locked columns

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3521]
**Describe the bug**
The keydown event doesn't fire on the locked column inside Grid, but the non-locked columns fire the event as expected. Sticky columns also fire the event.

**To Reproduce**
https://stackblitz.com/edit/angular-czhqyf-9gevy9?file=app/app.component.ts
Click on the locked column and press any key -> event doesn't fire
Click on non-locked column and press any key -> event fires
screen recording - http://somup.com/crlnIP0waf

**Comment by PaskalevStoyan** [comment]
Fix available in `v6.1.0` of the `@progress/kendo-angular-grid` package
