### ISSUE TITLE
[Gantt] Loading Indicator missing when fetching root nodes (observable) and binding them as data

### ISSUE THREAD

**Issue by yousafnawaz** [telerik/kendo-angular#3527]
Describe the bug
If I set **data** as an observable, loading indicator is missing to inform user about data is loading.

Given sample code by kendo, I added delay to data observable e.g.  this.data = of(tasks).pipe(delay(5000));
[https://stackblitz.com/edit/angular-bekehl?file=app/app.component.ts](https://stackblitz.com/edit/angular-bekehl?file=app/app.component.ts)

**Comment by stnikolova** [comment]
Hi @yousafnawaz 

This repository is for bug reports only. Displaying a loading indicator is currently not part of the Gantt component's features and is considered an enhancement. Please submit a feature request in our [Feedback Portal](https://feedback.telerik.com/kendo-angular-ui) about adding missing functionalities. This will allow us to monitor the demand for it and include it in our development plans accordingly.
