### ISSUE TITLE
Can't bind to 'routerLink' since it isn't a known property of 'kendo-panelbar-item'

### ISSUE THREAD

**Issue by lucifercha** [telerik/kendo-angular#353]
Can't bind to 'routerLink' since it isn't a known property of 'kendo-panelbar-item'

my angular2 version is 2.4.8，and the @progress/kendo-angular-layout version is 0.21.5，why？

**Comment by rusev** [comment]
It seems to be working in [this example](http://www.telerik.com/kendo-angular-ui/components/layout/panelbar/routing/). 

Usually this error means that the `LayoutModule` is not imported in the app module.

Can you provide a plnkr which demonstrates the error?

**Comment by tsvetomir** [comment]
Seems like a duplicate of #54

**Comment by lucifercha** [comment]
@rusev  I am sure that i imported the `LayoutModule ` to the app module,because if i remove the `[routerLink]` attribute to `kendo-panelbar-item` it works

**Comment by tsvetomir** [comment]
Please see [the Routing demo](http://www.telerik.com/kendo-angular-ui/components/layout/panelbar/routing/) for reference.

**Comment by ORESoftware** [comment]
Looks like router-link became routerLink:
https://coursetro.com/posts/code/111/Using-the-Angular-5-Router-%28Tutorial

**Comment by scheltwort-its** [comment]
I solved the same issue by adding the RouterModule to the Module that contained the component.

**Comment by orinwalker** [comment]
@ORESoftware Good catch: Also note, for anyone coming across this thread, that it is case sensitive: So you would want to use [routerLink] rather than [routerlink]
