### ISSUE TITLE
Items in kendo-multiselect cannot be selected after scrolling when data is provided by function

### ISSUE THREAD

**Issue by patekfilip** [telerik/kendo-angular#3530]
**Describe the bug**
If you have a `kendo-multiselect` in a `kendoGridFilterMenuTemplate` for filtering a text column in a grid and you give the `kendo-multiselect` a function as the datasource `[data]="columnValues(column)"`, you cannot select the items in the multiselect after scrolling. It seems like the `ClickEvent` of an item further down the list is not properly registered and that is why it does not get selected. Same poblem occurs when you try to provide the data with a pipe instead of a function.

**To reproduce**
1. Go to https://stackblitz.com/edit/angular-ilxjzo?file=src%2Fapp%2Fapp.component.ts
2. click the multiselect input above
3. scroll down in the popup to reveal more items
4. click one of the items that are displayed after scrolling down in the popup
 -> item will not be selected and the popup scrolls up again

**Expected behavior**
The clicked item after scrolling down the popup shows itself as a selected item in the multiselect and the `valueChangeEvent` is fired.

**Workaround**
In User perspective:
1. First select an item which is visible from the start of opening the popup
2. Then open the popup again and select the item further down the list (now it is selectable)
3. Remove the first selected item in the list of selected values

**Comment by svetq** [comment]
The demonstrated behavior is caused due to the function returning new instances of the array each time it is called. (Using a function in an Angular template is not a recommended approach, indeed). Still, returning the same array instance from the function yields the expected behavior: https://stackblitz.com/edit/angular-ilxjzo-agadqo
