### ISSUE TITLE
[TextArea] automatic height adjustment behaves inconsistently

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3531]
**Describe the bug**
When setting the textarea to be 100% wide and its value via the [value] input property, then the automatic height sizing isn't behaving properly. If the value is set via the [ngModel] binding then the height is properly set.

**To Reproduce**
Please see the difference between the two approaches in the following project (in StackBlitz the issue isn't reproducible):
 
[kendo-textarea.zip](https://github.com/telerik/kendo-angular/files/7726380/kendo-textarea.zip)

**Comment by Raisolution** [comment]
Fix available in `v8.0.3` of the `kendo-angular-inputs` package.
