### ISSUE TITLE
[Tooltip] the display of the tooltip is improper when having a large tooltip text

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3534]
**Describe the bug**
When the tooltip text is quite large then the display and position of the tooltip are improper. The text is cut off, the positioning isn't proper as well.

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-yhx5jv?file=app/app.component.ts

**Comment by Raisolution** [comment]
The Tooltip component is generally intended for simpler and shorter content e.g. a `title` attribute.

For larger and more complex content we recommend using the new Popover component instead.

https://www.telerik.com/kendo-angular-ui/components/tooltips/popover/
