### ISSUE TITLE
License not recognized

### ISSUE THREAD

**Issue by eluchsinger** [telerik/kendo-angular#3538]
During development of my Angular application, I import a license using the `npx kendo-ui-license activate` command.

The output is the following (I've tried both using the file and assigning the environment variable):
```
(INFO) Kendo UI: Reading license from KENDO_UI_LICENSE environment variable...
(INFO) Kendo UI: License imported successfully.
```

When I start my application, I get list of warnings output in the console, like this one:

```
License activation failed for @progress/kendo-angular-grid
No license found.
```

What am I missing?

### Deps

Angular 13.1

All kendo-ui dependencies are up to date.

- @progress/kendo-licensing": "^1.2.1"
- @progress/kendo-angular-grid": "^5.5.1"

**Comment by squaretabledev** [comment]
Hi

For me deleting the node_modules wasn't enough. I had to do the following to get it to work

delete node_modules
npm cache clear --force
npm install

**Comment by eluchsinger** [comment]
I could solve this issue by deleting everything related to node_modules, clearing the cache and installing everything again. Not sure what exactly helped.

**Comment by zachCatalyst** [comment]
I had to make sure to use cmd, i was using mingw64 (gitbash) and then tried with powershell and the license activation wouldn't work (`npx kendo-ui-license activate`). But it worked fine with cmd.

**Comment by fulutas** [comment]
Hi, make sure you are using cmd. 

Command:
```yarn run kendo-ui-license activate```
