### ISSUE TITLE
Kendo Angular Chart ShadowDom SVG not sizing correctly

### ISSUE THREAD

**Issue by b4cktr4ck5r3** [telerik/kendo-angular#3539]
**Describe the bug**
Kendo Angular UI Chart SVG do not size correctly with encapsulation : ViewEncapsulation.ShadowDom

**To Reproduce**
Set inline style property "height" to 500px on the kendo-chart template.
Set Component encapsulation to : ViewEncapsulation.ShadowDom

Find an example at : https://stackblitz.com/edit/angular-hcycgp?file=app/app.component.ts

**Expected behavior**
The height of the chart is equal to the value of "height"

**Screenshots**
With ShadowDom encapsulation :
![image](https://user-images.githubusercontent.com/59377281/148250104-8de501cc-5efa-4203-812c-d19f2e0cc53c.png)

With None encapsulation :
![image](https://user-images.githubusercontent.com/59377281/148250163-b7f68777-cabb-4fec-ae8d-81d7ee58acef.png)

**Browser**
 - OS: Windows
 - Browser: Tested on Chrome and FireFox Dev Edition

**Comment by mbechev** [comment]
Hi @b4cktr4ck5r3,

The **shadowDom** view encapsulation mode is not officially supported by the Kendo UI for Angular components. For more details please check the following Knowledge Base article which covers that topic:

https://www.telerik.com/kendo-angular-ui/components/knowledge-base/shadow-dom/
