### ISSUE TITLE
Scrolling locked columns does not work on a mobile device

### ISSUE THREAD

**Issue by do-nat** [telerik/kendo-angular#3541]
**Describe the bug**
On mobile devices, the locked columns cannot be scrolled vertically. It was fixed for desktop in v3.7.0 (as mentioned [here](https://github.com/telerik/kendo-angular/issues/1566)), but still does not work on a mobile device.

**To Reproduce**

Use the [example](https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/) provided on your home page to reproduce the issue. If opened on desktop, it works, but not on mobile.

**Expected behavior**
Vertical scrolling should be possible on locked columns as it is on a desktop browser.

**Screenshots**
No screenshots possible.

**Browser**
 - OS: Android
 - Browser: Chrome, Firefox
 - Version: Firefox 95.2.0, Chrome 96.0.4664.104

**Additional context**
No additional context.

**Comment by mbechev** [comment]
Hi @do-nat,

Indeed this is a known limitation of the locked columns feature of the Grid documented here:

https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/#toc-known-limitations
