### ISSUE TITLE
[ColorPalette] Initial value is not being selected

### ISSUE THREAD

**Issue by kkopec** [telerik/kendo-angular#3545]
**Describe the bug**
Passing an initial value (either by value property or via form) to a ColorPalette component does not result in this value being selected.
An item is selected only after one manually interacts with the component.

**To Reproduce**
Set initial value for the palette in the code. Don't pick one using UI.
[Stackblitz example with reactive forms](https://stackblitz.com/edit/angular-yusuvi?file=app/app.component.ts)

**Expected behavior**
An item corresponding to initially selected value should have proper markup indicating that it's actually selected.

**Screenshots**
Initial value (no indication of selection):
![image](https://user-images.githubusercontent.com/7479970/149515736-72adac90-2994-4864-8e0e-2367ced28d23.png)
After manual selection (all classes and attributes set properly):
![image](https://user-images.githubusercontent.com/7479970/149515786-92708079-527e-4e6d-8050-b97e72491aad.png)

**Comment by Raisolution** [comment]
Fix available in `v8.0.4` of the `kendo-angular-inputs` package.
