### ISSUE TITLE
[ExpansionPanel] Unnecessary title attribute is attached to the component

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3546]
**Describe the bug**
The browser tooltip is shown when the ExpansionPanel is hovered. This is caused by the **title** attribute attached to the component:

![image](https://user-images.githubusercontent.com/33104481/149754143-c4e057e2-6512-4a0f-aab1-4e8da164d9e6.png)

![Capture](https://user-images.githubusercontent.com/33104481/149753863-575070da-6ec3-44eb-88f6-825426a33481.PNG)

**To Reproduce**
Check the demo from this article:
https://www.telerik.com/kendo-angular-ui/components/layout/expansionpanel/title/#toc-titles-and-subtitles

**Expected behavior**
The browser tooltip should not appear in this case.

**Comment by Raisolution** [comment]
Fix available in `v6.4.2` of the `kendo-angular-layout` package.
