### ISSUE TITLE
[ColorPicker] Dropdown button is missing type="button"

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3550]
**Describe the bug**
The dropdown arrow button of the ColorPicker component is missing type="button". Thus, it acts as a `submit` button when the component is in a form.

**To Reproduce**

1. Open the overview example under this link https://www.telerik.com/kendo-angular-ui/components/inputs/colorpicker/.
2. Inspect the button element.

**Comment by Raisolution** [comment]
Fix available in `v8.0.2` of the `kendo-angular-inputs` package.
