### ISSUE TITLE
[TimePicker] Time lists are not properly aligned when using the Kendo Material theme

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-angular#3553]
**Describe the bug**
Time lists are not properly aligned when using the Kendo Material theme.

**To Reproduce**

1. Go to the [TimePicker demo](https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/)
2. Choose Material Main theme
3. Open the TimePicker popup

**Expected behavior**
Time lists should be align properly as in the Default and Bootstrap themes.

**Screenshots**
![alignment](https://user-images.githubusercontent.com/7753940/150793704-a01b3744-d00a-44d3-a7fc-a6d379d79d2d.png)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds).

**Comment by gkarapeev** [comment]
Fix available in version 6.0.1
