### ISSUE TITLE
Packages compatibility - locked update path 

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#3554]
HI, i wanted to update all @progress/kendo packages to the latest versions, however i have encountered imcompatibility between them:
-  "@progress/kendo-angular-dateinputs": "^6.0.0",
-  "@progress/kendo-angular-treelist": "^4.0.2",  - required -inputs@5.0.0, but newer treelist is not released / published

**Comment by Raisolution** [comment]
Hi @montella1507 ,

Thank you for reporting the problem. Please excuse us for this discrepancy, the Treelist had a wrong DateInputs peer dependency in its latest major version.

We have published `v4.0.3` of the `kendo-angular-treelist` package which contains the fix.

**Comment by montella1507** [comment]
Thank you very much!
