### ISSUE TITLE
Kendo Chart not working properly with ng-content

### ISSUE THREAD

**Issue by dydFreeman** [telerik/kendo-angular#356]
It seems to be some problem in using kendoChart with ng-content and ng-if.
Two different scenarios:

 - ng-content **WITHOUT** ng-if
_Chart is shown correctly._

``` html
<div>
   <ng-content select="ng-chart-content"></ng-content>
</div>
```

http://plnkr.co/edit/r2Zl0qDjlE3j2UUR9on4?p=preview

![withstroke](https://cloud.githubusercontent.com/assets/2900220/23658244/021a2284-0342-11e7-8d7a-a2d2e2f42ff9.PNG)

 - ng-content **WITH** ng-if
_Chart is not shown correctly._
``` html
<div *ngIf="true">
   <ng-content select="ng-chart-content"></ng-content>
</div>
```

http://plnkr.co/edit/8pQgX28PFaZh4zVuvJd3?p=preview

![withoutstroke](https://cloud.githubusercontent.com/assets/2900220/23658245/021ba0f0-0342-11e7-90eb-a758f31eebc9.PNG)

**Comment by danielkaradachki** [comment]
Thank you for the examples. We will look into it.

**Comment by danielkaradachki** [comment]
The problem should be fixed. Please try with the latest version.

**Comment by DydFreeman** [comment]
It works, thanks!

**Comment by DydFreeman** [comment]
Just one question: do we need to update both kendo-angular-chart and kendo-drawing or only chart?

**Comment by danielkaradachki** [comment]
Updating the kendo-angular-charts package should be sufficient.

**Comment by tzmanics** [comment]
Hi @danielkaradachki, is there a chance the same problem is persisting with `*ngFor`?
Column:
https://github.com/jlooper/emoting/blob/master/web/src/app/app.component.html
![screen shot 2017-03-20 at 09 21 18 2](https://cloud.githubusercontent.com/assets/3611928/24101627/744f85ee-0d4f-11e7-862a-3a549611142b.png)
Line:
https://github.com/tzmanics/fill-up-my-chart/blob/master/src/app/app.component.html#L9
![screen shot 2017-03-20 at 09 16 43 2](https://cloud.githubusercontent.com/assets/3611928/24101796/0c363128-0d50-11e7-986d-889518735817.png)

Let me know if you need more info. Thanks!
