### ISSUE TITLE
Wrong styling with selected page-numbers

### ISSUE THREAD

**Issue by ValentinGeorgiev00** [telerik/kendo-angular#3562]
There are is an issue with the **page-numbers** if they are clicked.

![image](https://user-images.githubusercontent.com/87369850/151564469-8c98c5e1-2113-49bf-ae48-9b917b7082c1.png)

The issue appears after **v5** of the theme. The **.k-selected** CSS class needs to be changed to **.k-state-selected.**

**Steps to reproduce**

https://stackblitz.com/edit/angular-q3h8wh?file=app/app.component.ts

**Expected behavior**

![image](https://user-images.githubusercontent.com/87369850/151564701-84942f73-261a-40cd-9ae2-377a9a321cb3.png)

**Comment by Raisolution** [comment]
Fix is available in `v3.0.1` of the Pager package.
