### ISSUE TITLE
[Editor] Scrollbar is always shown when iframe is enabled

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3563]
**Describe the bug**
The Editor component displays a scrollbar ignoring if the value is empty. This behavior is present only with our latest versions of the component and themes.

**To Reproduce**
Open any of our demos - https://www.telerik.com/kendo-angular-ui/components/editor/get-started/

**Comment by Raisolution** [comment]
Fix is available in `v3.0.4` of the Editor package.
