### ISSUE TITLE
docs: kendo-textbox-container removed but not mentioned in docs

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#3565]
Looks like `kendo-textbox-container` was removed in current release.

Expected:
Some notes here https://github.com/telerik/kendo-angular/issues/3557 or here https://www.telerik.com/kendo-angular-ui/components/inputs/changelog/

**Comment by Raisolution** [comment]
Thank you for noticing this discrepancy @cluetjen

I have updated the list of breaking changes in the issue and in the `v8.0.0` changelog (it will be live on the website soon). Please excuse us for the inconvenience.

To provide some additional context - The main purpose of the TextBoxContainer has been providing a floating label functionality. Thus, it has been replaced by the [FloatingLabel](https://www.telerik.com/kendo-angular-ui/components/labels/floatinglabel/) component.
