### ISSUE TITLE
FloatingLabel - wrong label position if empty (material theme)

### ISSUE THREAD

**Issue by cluetjen** [telerik/kendo-angular#3568]
Positioning of the label looks wrong if field is empty.

See example here:
https://www.telerik.com/kendo-angular-ui/components/labels/floatinglabel/

Wrong: No space on the left side of text
![image](https://user-images.githubusercontent.com/5447876/152047287-96a7438b-7103-4384-8d5f-9c0487b5efd4.png)

Epected: Same padding left as the user input would have
![image](https://user-images.githubusercontent.com/5447876/152047194-7613add4-e917-4202-939c-3d3afbefab33.png)

**Comment by yanmariomenev** [comment]
Hi Cluetjen,
Thank you for the provided feedback.

I am closing the issue as a duplicate to [#3352](https://github.com/telerik/kendo-themes/issues/3352) in our Kendo Themes repository. Please subscribe to the [issue ](https://github.com/telerik/kendo-themes/issues/3352)for further updates.

**Comment by cluetjen** [comment]
oh, didn't realize that there's a separate project. Thanks.
