### ISSUE TITLE
Enter key is not working for kendo-upload button with JAWS tool 

### ISSUE THREAD

**Issue by revathichevuri** [telerik/kendo-angular#3569]
Describe the bug
Enter key press is not working for kendo-upload button with JAWS tool.
Alt+Enter alone working but screen reader reading like Press Enter to activate.
I guess tabindex="-1" is there for input tag. This is causing the issue. I inspected in console and tried to change tabindex to 0 then it is working.

To Reproduce
1.open JAWS tool
2.try to access the kendo-upload button through keyboard.

Runnable snippet ::
https://www.telerik.com/kendo-angular-ui/components/uploads/upload/keyboard-navigation/

Expected behavior:
Enter key press should work with JAWS tool or
Screen reader should read press alt+enter instead of enter.

Screenshots

Browser
OS: [for example, iOS]
Browser Chrome
Version [for example, 22]

Additional context
Tried role="application" enter key press is working but up/down arrow buttons are effecting

**Comment by mbechev** [comment]
Hi @revathichevuri ,

The cause of the described issue is that screen readers provide keyboard navigation themselves, which overrides the keyboard navigation of the components. 

To avoid this behavior, add a **role="application"** to the Upload component:

```html
<kendo-upload
    role="application"
    [saveUrl]="uploadSaveUrl"
    [removeUrl]="uploadRemoveUrl"
    [autoUpload]="false">
</kendo-upload>
```
For more information please check this Knowledge Base article:
https://www.telerik.com/kendo-angular-ui/components/knowledge-base/general-keyboard-navigation-screenreaders/

**Comment by revathichevuri** [comment]
Hi @mbechev Thanks for the quick reply.
I've already tried giving role="application". Enter key is working But this affects the up/down arrow buttons in keyboard. The goal is to make kendo upload button work in Jaws by pressing enter key without affecting up/down arrow keys. Is there any alternative to solve this issue??
Like changing the tabindex from - 1 to 0 in inputs tag.

![IMG_20220202_013132](https://user-images.githubusercontent.com/83636556/152108865-c6aabe03-59ea-41a2-90b6-a3b1773a278c.jpg)
When I inspected the kendo-upload button am seeing the above code in console

**Comment by revathichevuri** [comment]
Hi @mbechev issue closed???

**Comment by revathichevuri** [comment]
# Change the tabindex of input tag from - 1 to 0

**Comment by mbechev** [comment]
Hi @revathichevuri,

I tested the Upload component with JAWS, but the arrow keys seem to work as expected, according to the documentation:

https://www.telerik.com/kendo-angular-ui-develop/components/uploads/upload/keyboard-navigation/ 

Here is a screen recording:

https://screenrec.com/share/0rQ3HjzKCv

If any further questions come up regarding this case, I want to encourage you to open a [support ticket](https://www.telerik.com/account/support-tickets) as this repository is for bug reports only.
