### ISSUE TITLE
R1 2022 packages

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#3573]
Hi,
I upgraded to the latest version. Allow me to give some feedback:

- Please upgrade to the latest tslib. It seems you are still using V1.14.1, the latest version is 2.3.1 and should be used with TS >3.9.2 (https://github.com/Microsoft/tslib#installing). Now there are many child "node_modules" installation
- I can't install all the latest versions/packages because there is a strict dependency to "@progress/kendo-angular-inputs": "8.0.0" in the scheduler package. Actual version of "@progress/kendo-angular-inputs" is "8.0.2".

Thank you

**Comment by tsvetomir** [comment]
Thanks for reporting! The peer dependencies are fixed in `@progress/kendo-angular-scheduler@3.0.1`.

The `tslib` dependency will be updated to v2.3.1 as part of #3502.
