### ISSUE TITLE
[Grid] The filter popup is scrolled when last item is clicked

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#3575]
**Describe the bug**
The filter popup scrolls when the checkbox of the last item is clicked, making the selection to fail.

**To Reproduce**

  1. Open [https://stackblitz.com/edit/angular-ak6ala?file=index.html](https://stackblitz.com/edit/angular-ak6ala?file=index.html)
  2. Open Category column filter menu
  3. Try to select 'Meat/Poultry' 
  4. The popup is scrolled so the item does not get selected.

**Expected behavior**
  The popup should not scroll its content, so the last item should be selectable from the first try.

**Browser**
 - Browser  Chrome

**Comment by ipeshev** [comment]
It is mostly problem with the examples, fix in our documentation will follow swiftly!

**Comment by svetq** [comment]
The example has been updated: https://www.telerik.com/kendo-angular-ui-develop/components/grid/filtering/reusable-filter/#toc-multi-checkbox-menu-filtering
