### ISSUE TITLE
Master-Detail Grid accessibility issue

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3577]
**Describe the bug**
The hierarchy cells do not have a **role"** attribute set. This causes some accessibility tools to throw a warning message because **[aria-selected](https://www.w3.org/TR/wai-aria-1.1/#aria-selected)** attribute is set on an element without a role:

![image](https://user-images.githubusercontent.com/33104481/152544178-2160c60b-ba9a-43dd-be32-4e08cd76df17.png)

**To Reproduce**
https://stackblitz.com/edit/angular-shyg69-w88q5a

**Comment by Raisolution** [comment]
Fixed in `v7.2.2` of the Grid package.
