### ISSUE TITLE
Enter key in Grid in edit mode invokes add command

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#358]
If you try on http://plnkr.co/edit/XqOywZ8qaCcEYoarkPDu, press edit on a row, make a change and press <kbd>ENTER</kbd>. Looks like this invokes the `add` command as it cancels your changes and adds a blank row in the grid. I think it makes more sense to invoke the `save` command, accepting your changes.

**Comment by rusev** [comment]
This behavior is typical for HTML form with a button. See the following example - http://plnkr.co/edit/v87Gvbq7P1XhT0ZmMlp8?p=preview

In the context of the Grid you can prevent the `keydown` event when <kbd>ENTER</kbd> is pressed. See the updated the example - http://plnkr.co/edit/gHsQREq5z5VtTxd73EY5?p=preview

**Comment by PeterStaev** [comment]
Yes, I know of the default form behavior, but this does not add up for the grid in row edit mode. Basically the form in this case should be the row in the grid which would then trigger the first action which is update. 

Is there a method of the grid, that I can call for the grid to trigger the `save` event (something like `saveRow`)? Or may be I should just work with the `form.value`?

**Comment by rusev** [comment]
@PeterStaev  sorry for the late reply. 

This behavior seems like something that will be addressed once keyboard navigation support is added. On <kbd>ENTER</kbd> key the row state will be toggled `edit/save` current row.
