### ISSUE TITLE
[Gantt] The timeline period is not full

### ISSUE THREAD

**Issue by ciiara** [telerik/kendo-angular#3582]
**Describe the bug**
The header with the timeline period does not include all the days in a given period in the month/week view.

In the screenshot below the period should start on Sunday and end on Saturday.
![Screenshot 2022-02-09 at 12 09 11](https://user-images.githubusercontent.com/25002257/153176834-f14bb2a7-b2c0-4b15-b097-34dd7d952fe5.png)

The issue can be seen here:
[StackBlitz
](https://stackblitz.com/run/?file=app/app.component.ts)

**Expected behavior**
The period in the header should include all relevant days.

**Comment by dtopalov** [comment]
Fixed in v.2.0.2 of the @progress/kendo-angular-gantt package.
