### ISSUE TITLE
[DatePicker] Infinite Calendar displayed default month not affected by min/max

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3588]
**Describe the bug**
When using the Kendo Angular Datepicker in Infinite mode, if a min or max date would change the default displayed month it still shows the current month in the upper left when opening the picker instead of whatever the visible month is.

The issue starts occurring with v5.2.0 of the DateInputs package. 

**To Reproduce**
https://stackblitz.com/edit/angular-hnzkba-vyxhvw?file=app/app.component.ts

**Expected behavior**
Calendar should display the month according to the set min/max value.

**Comment by flobacher** [comment]
I face the same issue. I thought I could work around it by setting the `[focusedDate]` but that somehow stops the user from selecting any other month, than the current one. my fix currently is to set the `[value]` to  `[max]` upon the `open` event, but that should not be necessary.
Please fix 🙏🙏🙏
Thank you!

**Comment by Pnayak10** [comment]
@tswetti  I am still facing the issue, Is this issue Fixed by Kendo Team, or it is yet to be resolved ? 
or is there any alternate solution for this ?

**Comment by tswetti** [comment]
Fixed in [v15.3.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.3.0)
