### ISSUE TITLE
Can't NPM install, JSON parse and 403 error

### ISSUE THREAD

**Issue by wkpablo** [telerik/kendo-angular#359]
Prior to yesterday, I was able to install Kendo NG2 Components without a problem. I am now getting errors:

1. npm ERR! Unexpected token < in JSON at position 0
2. 403 error

I have logged into the Telerik and Progress scopes successfully, but I can not npm install any package.

I am not the only one experiencing this issue: https://github.com/npm/npm/issues/14197

**Comment by hem19** [comment]
I am also facing same issue. It was working fine before. But now keep on getting 403 Forbidden : Access is denied error. Initially it gives error "npm ERR! registry error parsing json", followed with 403 error.
[npm-debug.zip](https://github.com/telerik/kendo-angular/files/827335/npm-debug.zip)

**Comment by tsvetomir** [comment]
Please note that to install packages, you need to have an active trial or licensed commercial version of Kendo UI. See [Get Started](http://www.telerik.com/kendo-angular-ui/getting-started/) for details.

**Comment by hem19** [comment]
@tsvetomir I have followed the steps mentioned in the Get Started. While running this command 'npm view @progress/kendo-angular-grid versions' I am getting 'Access is Denied' error.

Does this means my trial license is over?

**Comment by JanJordan** [comment]
i do not think so, because we tested this an hour ago with a new created trial account - even then "access denied"

**Comment by wkpablo** [comment]
@tsvetomir I have an active account, I have tested that my credentials work by logging into the http://www.telerik.com/ website, and I have set both the @progress and @telerik scopes using the related commands (i.e. npm login --registry=https://registry.npm.telerik.com/ --scope=@progress). I am still facing the errors mentioned on this thread.

**Comment by nesshoever** [comment]
Seems like when you now remove the @telerik part again, it seems to work...
My .npmrc now looks like that and I was able to run npm install with this local .npmrc:
```
@progress:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken={my token string}
```

**Comment by tsvetomir** [comment]
@wkpablo the @telerik scope should remain pointing to the default registry. That's a bit confusing and is due to historical reasons. The `.npmrc` file posted by @nesshoever shows the correct configuration.

**Comment by hem19** [comment]
@tsvetomir I have similar .npmrc file as @wkpablo has. Yesterday it was throwing errors mentioned above, but today when I ran npm install command it works fine. 
My .npmrc file is as follows:
@progress:registry=https://registry.npm.telerik.com/
@telerik:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken={my_auth_token}

**Comment by wkpablo** [comment]
With or without the @telerik:registry=https://registry.npm.telerik.com/ reference in the .npmrc file I am still getting the same parsing json and 403 errors.

**Comment by tsvetomir** [comment]
It appears that there was an issue with a stale cache that caused valid users to be denied access.

This should be resolved now. Let me know if you're still experiencing issues.

**Comment by brythomas** [comment]
I'm still having the issue. It appears that I have a valid authtoken but I get a 403 whenever I try to access anything in that scope.

@progress:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken=yMYb/vex7+[SNIP]

**Comment by wlngwang** [comment]
@tsvetomir I'm still having the same problem. Logged in successfully and I can see my token in .npmrc file. Still get 403 forbidden.

**Comment by kianmeng-aft** [comment]
i am also facing the same issue

**Comment by wkpablo** [comment]
@tsvetomir thank you for the update and addressing the issue. The clearing/updating of the cache seems to have fixed the issue for me.

**Comment by dyzy** [comment]
Have the same issue for Dropdowns package and many others.
Cache clearing doesn't solved my issue. Any news?

Executing
`npm install --save @progress/kendo-angular-dropdowns`
 gives me next error:

```
C:\Projects\SweetHome.Net\Web\SweetHome.Net.Web.UI>npm install --save @progress/kendo-angular-dropdowns
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@progress/kendo-angular-dropdowns"
npm ERR! node v6.9.1
npm ERR! npm  v4.3.0

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
npm ERR! <title>403 - Forbidden: Access is denied.</title>
npm ERR! <style type="text/css">
npm ERR! <!--
npm ERR! body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
npm ERR! fieldset{padding:0 15px 10px 15px;}
npm ERR! h1{font-size:2.4em;margin:0;color:#FFF;}
npm ERR! h2{font-size:1.7em;margin:0;color:#CC0000;}
npm ERR! h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
npm ERR! #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
npm ERR! background-color:#555555;}
npm ERR! #content{margin:0 0 0 2%;position:relative;}
npm ERR! .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
npm ERR! -->
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>403 - Forbidden: Access is denied.</h2>
npm ERR!   <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Dy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@progress/kendo-angular-dropdowns' ]
2 info using npm@4.3.0
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @progress/kendo-angular-dropdowns
8 silly fetchNamedPackageData @progress/kendo-angular-dropdowns
9 silly mapToRegistry name @progress/kendo-angular-dropdowns
10 silly mapToRegistry scope (from package name) @progress
11 silly mapToRegistry registry https://registry.npm.telerik.com/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: '@progress/kendo-angular-dropdowns',
12 silly mapToRegistry   scope: '@progress',
12 silly mapToRegistry   escapedName: '@progress%2fkendo-angular-dropdowns',
12 silly mapToRegistry   name: '@progress/kendo-angular-dropdowns',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns
14 verbose request uri https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:48:54 PM
17 verbose request using bearer token for auth
18 verbose request id c7b68e2f3a10d999
19 http request GET https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns
20 http 403 https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns
21 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
21 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
21 verbose bad json <head>
21 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
21 verbose bad json <title>403 - Forbidden: Access is denied.</title>
21 verbose bad json <style type="text/css">
.....
```

.npmrc has credentials and working fine for other packages just few days ago;

Also I can't get versions for dropdowns:
`npm show @telerik/kendo-dropdowns-common@* version`
shows same error.

After clearing cache i have issues with installing any other packages in progress feed

**Comment by petyosi** [comment]
@dyzy - make sure that you follow the steps from this comment: 

https://github.com/telerik/kendo-angular/issues/359#issuecomment-285020021

**Comment by wlngwang** [comment]
@petyosi Thanks for your response. I followed the steps but still have the same `Permission Denied` issue. Hope this gets resolved soon, otherwise we'll have to give up kendo ui for angular 2.

**Comment by ramon26cruz** [comment]
+1

**Comment by lnu** [comment]
I'm facing the same issue. I can list the versions but I always get a 403 when I try to install something...

**Comment by tsvetomir** [comment]
I'd like to ask everyone who is unable to download packages to [submit a support ticket](https://www.telerik.com/account/support-tickets/contact-support-team?pid=1800). Include your **npm-debug.log** file as attachment.

We'll do everything within our power to resolve the issue for the affected accounts.

**Comment by diogobas** [comment]
+1

**Comment by tsvetomir** [comment]
I'm going to close this issue as we can't provide much of assistance without having the full account details and npm debug log. Please, submit support tickets if you still experience this issue.

We're also working to improve the error messages and make them more helpful.

**Comment by Neutrino-Sunset** [comment]
The Getting Started page doesn't even seem to do anything. I click 'Register for a trial', it takes me to a page that states 'A trial has been created' which then just redirects me back to the orginal 'Getting Started' page. It doesn't prompt for or give you a username with which to log in.

I already have a Telerik account but no trial appears on that account and that accounts credentials do not work either.

It doesn't make sense to say that you can't do anything to fix the problems without full account details if the 'Register for a trial' button doesn't even provide the ability to create an account in the first place.

**Comment by tsvetomir** [comment]
@Neutrino-Sunset can you try activating a trial in a "Incognito Window"? Perhaps you're still logged in with your existing account.

**Comment by mragansh** [comment]
Same Issue, Created new issue also. None Repling Can some look into this, facing this from 2 days.

C:\Users\mragansh.tomar\Desktop\HITLI\24-3-17-HVP-WEB\hvb-web\hvb-app>npm login
--registry=https://registry.npm.telerik.com/ --scope=@progress
Username: mragansh
Password:
Email: (this IS public) mragansh.tomar@globallogic.com
Logged in as mragansh to scope @progress on https://registry.npm.telerik.com/.

C:\Users\mragansh.tomar\Desktop\HITLI\24-3-17-HVP-WEB\hvb-web\hvb-app>npm view @
progress/kendo-angular-grid versions
npm ERR! registry error parsing json
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3
.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"
/>
npm ERR! <title>403 - Forbidden: Access is denied.</title>
npm ERR! <style type="text/css">
npm ERR! 
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>403 - Forbidden: Access is denied.</h2>
npm ERR!   <h3>You do not have permission to view this directory or page using t
he credentials that you supplied.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mragansh.tomar\AppData\Roaming\npm-cache\_logs\2017-03-27T
09_56_13_631Z-debug.log
