### ISSUE TITLE
Popup flickers in menu components

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3592]
### The issue is not reproduced in version **4.0.2** of the Popup component.

**Describe the bug**
When the menu/context-menu sub-items are opened and the popup doesn't fit, it starts flickering:

Menu screencast:
https://screenrec.com/share/LRftSWiqh4

ContextMenu screencast:
https://screenrec.com/share/GEQK9bIns1

It looks like the popup is always trying to open on the right side, but when a collision appears it reposition.

**To Reproduce**
Menu demo:
https://stackblitz.com/edit/angular-pnncmp

ContextMenu demo:
https://stackblitz.com/edit/angular-ogfzrr-aknpuf

**Comment by mbechev** [comment]
Similar behavior is reported for the ColorPicker component. 

The Popup is always opened on the right side, causing elements to reposition, while there is space on the left:
https://screenrec.com/share/LBFabNXwlu

**To Reproduce**
https://stackblitz.com/edit/angular-itnxyg-pvt2r3?file=app/app.component.ts

Reported in private support thread: **1559325**

**Comment by hetalishah** [comment]
In addition to the ColorPicker popup behavior mentioned by Martin, the popup opens on the left side when the colorpicker draghandle is on the first vertical half side as seen in [this screen recording](https://www.screencast.com/t/kJ9yH9wvLjv8).

**Comment by yanmariomenev** [comment]
A possible workaround would be to set the [animate ](https://www.telerik.com/kendo-angular-ui/components/menus/api/MenuComponent/#toc-animate)property of the Menu component:

https://stackblitz.com/edit/angular-pnncmp-tnduaw?file=app%2Fapp.component.ts

**Comment by JoomFX** [comment]
The issue is no longer reproducible with v13.5.0.

https://stackblitz.com/edit/angular-vcmmru?file=src%2Fapp%2Fapp.component.ts
