### ISSUE TITLE
[Menu] The expand arrows are not aligned

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3594]
**Describe the bug**
In older versions, the expand arrow was aligned, but the arrows are not aligned in the current versions of the component and Kendo Themes. This is due to missing class and span element from the following screenshot:
![287b445c-223e-4b90-9153-d4bce60ea6ee](https://user-images.githubusercontent.com/49076727/154954175-1feb5dbf-10f8-4049-83bf-6d8c0b8daf8d.jpg)

**To Reproduce**
Open - https://stackblitz.com/edit/angular-ftenow-elstxk?file=app%2Fapp.component.ts
Hover over Item1 to see the misaligned arrows.

**Screenshots**
Current version issue:
![chrome_twR61vpGPm](https://user-images.githubusercontent.com/49076727/154953897-26d45748-452d-4425-b643-5a46e36491f3.png)
Old version proper displayed arrows:
![chrome_sS53UltJSC](https://user-images.githubusercontent.com/49076727/154953964-3169895e-14ee-4871-a14e-3945c663c5a1.png)

**Workaround**
https://stackblitz.com/edit/angular-ftenow?file=app%2Fapp.component.ts

**Comment by gkarapeev** [comment]
Issue moved to [telerik/kendo-themes #3431](https://github.com/telerik/kendo-themes/issues/3431) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gkarapeev** [comment]
[Moved to the themes repo](https://github.com/telerik/kendo-themes/issues/3431)
