### ISSUE TITLE
[Dropdowns] Missing proper group styling and empty item text handling.

### ISSUE THREAD

**Issue by Zaixu** [telerik/kendo-angular#3595]
**Describe the bug**
Older version of dropdowns was able to handle empty value due to height and line height set, in current version it now collapses on itself when empty.

Older version also had strong html tag around group header with a inset, this is now gone aswell.

**To Reproduce**

Item text can be seen here:
https://stackblitz.com/edit/angular-4s2oss?file=app/app.component.ts (forked from official example and changed its text)

Group header can be seen on official example:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/grouping/
(Note, only bootstrap theme actually works correct here)

**Expected behavior**

To handle empty item text and have distinct group header styling

**Screenshots**
![image](https://user-images.githubusercontent.com/763173/154958317-89ce0ac1-f8c5-408d-ad2b-e579e6fd7746.png)

![image](https://user-images.githubusercontent.com/763173/154958413-1e9be189-b497-40b5-8a67-950cde50d8f7.png)

**Comment by gkarapeev** [comment]
@Zaixu thank you for submitting these issues.

I managed to reproduce the one with the DropDownList.

I was not able to find an old version of the package where having an empty string as an item text, retains the normal item height. I tried all the way back to [dropdowns v4](https://stackblitz.com/edit/angular-4s2oss-uddtfv?file=app/app.component.ts). Do you know in which version the empty string item was rendered properly?

**Comment by Zaixu** [comment]
@gkarapeev I tried to look a bit further into it.

It seems to be a change from theme version 4.43 to 4.44 just before 5.
Have a look here: https://stackblitz.com/edit/angular-4s2oss-w2vwek?file=app/app.component.ts

There is ofcourse a class on defaultitem that i could style to get back to how it was, but thats another thing to keep maintained.

**Comment by clintsinger** [comment]
Any chance this will see a fix anytime soon?  

I noticed that you can't customize the grouping header style in the new ThemeBuilder either.   That would be a great addition.

**Comment by JoomFX** [comment]
The issue with the incorrect height of an item with empty text was fixed more than an year ago with [this PR](https://github.com/telerik/kendo-themes/issues/3388).
The fix can be seen in [this Stackblitz example](https://stackblitz.com/edit/angular-4s2oss-75mc1e?file=app%2Fapp.component.ts).

Regarding the Group Header styling - it is indeed a bug.
I just opened [a new PR](https://github.com/telerik/kendo-themes/pull/4541) in Kendo Themes. The fix should be available in the next Kendo Themes release.

**Comment by dtopuzov** [comment]
Group Header styling looks broken with kendo themes 6.4.0:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/examples/dropdownlist/grouping/?theme=default-main&themeVersion=6.4.0

It looks fixed with 6.5.0 or above:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/examples/dropdownlist/grouping/?theme=default-main&themeVersion=6.5.0
