### ISSUE TITLE
kendoTextBox directive does not add k-disabled class

### ISSUE THREAD

**Issue by jvalkeejarvi** [telerik/kendo-angular#3597]
**Describe the bug**
kendoTextBox directive does not add k-disabled class when used with formControl.

**To Reproduce**
https://github.com/jvalkeejarvi/kendo-textbox-disabled-bug

**Expected behavior**
Disabled styling is applied to input element

**Screenshots**
![image](https://user-images.githubusercontent.com/3441271/155137621-653d8d7c-c162-446b-babd-623d06110244.png)

**Comment by Raisolution** [comment]
Hi @jvalkeejarvi 

The `kendoTextBox` directive serves as a styled version of an input element and does not provide any functionality (e.g. form support). 

To implement fully functional inputs, use the `TextBox` component instead

https://www.telerik.com/kendo-angular-ui-develop/components/inputs/textbox/forms/

**Comment by jvalkeejarvi** [comment]
You are correct, kendoTextBox has never added the `k-disabled`class. I guess that there's a bug `kendo-theme-default`. With version 4.33.0 `kendoTextBox` directives are styled correctly but with 5.2.0 disabled styles are not applied. Should I make a new issue for that?

**Comment by Raisolution** [comment]
Thank you for this remark and the attached project. Indeed there seems to be a difference with the latest major version of the theme, which we will investigate further.

For the time being, we recommend using the TextBox component, which is styled accordingly.
