### ISSUE TITLE
[DropDownList] Keeps its selected value that is no longer existing in the data collection

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3598]
**Describe the bug**
The DropDownList component doesn't update when the selected value is no longer present in the data collection used by the component. For example, if the collection is updated and the item no longer exists, the DropDownList still holds it in its value. This is also observed in other Dropdowns package components. This behavior can also be observed in the following streaming of data demo:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/data-binding/#toc-streaming-of-data
The DropDownList still persists a non-existing value when the data is being changed.

**To Reproduce**
Open and remove the last item from the list - https://stackblitz.com/edit/angular-ok46qq-hestcs?file=app/app.component.ts

https://user-images.githubusercontent.com/49076727/155324554-4f3bf7c1-f81e-47ce-94b1-bd42c887bd7a.mp4

**Expected behavior**
If the collection is updated and the selected item is no longer available, the component should update its value.

**Workaround**
https://stackblitz.com/edit/angular-ok46qq?file=app/app.component.ts

**Comment by svetq** [comment]
The described behavior is by design. The DropDownList allows setting a value that is not a part of its data.
