### ISSUE TITLE
Grid: Add ability to specify icons for kendoGrid*Command buttons with iconClass

### ISSUE THREAD

**Issue by PeterStaev** [telerik/kendo-angular#360]
From what I see currently if you specify `iconClass` for `kendoGrid*Command` buttons it has no effect. If you want to add some icon in front you should either use a nested span for the icon or use a normal `kendoButton`. It will be really nice if you could specify the icons similar to how you specify them for normal `kendoButton` widget.

**Comment by rusev** [comment]
Currently the command buttons does not have such properties. However we are considering alternative approach of implementing them, by extending the `kendoButton`. This will enable all `kendoButton` feature to command directives.

**Comment by P-H-F** [comment]
I would like to bring another option/proposal to discussion:

When you add the  `kendoGrid*Command` directive to a button,  it should not add the `k-button` 
and `k-grid-*-command` classes, instead it should only manage/call the grid events.

This way the developer would have the possibility to control how the button would look like.
He could decide to use use a default kendo button like this:
````
<button kendoButton kendoGridAddCommand [icon]="'plus'">Add</button>
````
Or even use custom styling / directives: (I used bootstrap just as an example)
````
<button kendoGridAddCommand type="button" class="btn btn-primary">
    <span class="fa fa-pencil"></span>Add
</button>
````

Looking forward to hear your opinions on this.

**Comment by rusev** [comment]
@pfoedermayr  You may use our [bootstrap theme](https://www.telerik.com/kendo-angular-ui/components/styling/theme-bootstrap/) for the purpose with the built-in button components.  Example - https://plnkr.co/edit/aK0YABBfyvmK0mKPL24P?p=preview

Other option could be a custom directive that removes `k-button` class from elements:
```
@Directive({
  selector: '[kendoCleanClass]'
})
export class CleanClass {
  constructor(
    private renderer: Renderer2,
    private element: ElementRef
  ) { }
  
  public ngAfterViewInit(): void {
    this.renderer.removeClass(this.element.nativeElement, 'k-button');
  }
}
```
A runnable example for the above - https://plnkr.co/edit/cBRsvI1Ti6awh5hV6jpK?p=preview

**Comment by pfoedermayr** [comment]
@rusev Thanks for your response.

We are using the bootstrap theme, but as you can see in the example linked, a button with the class `k-button` still looks different than the default bootstrap button.
(Back when I wrote the original response the difference in style was way more noticeable)

Example: https://plnkr.co/edit/1bZ1VWKs8VZTCCEwefLE?p=preview

Back then we evaluated 3 scenarios:
* Add the class `k-button` to every button
* Remove the class `k-button` from the command-buttons
   * similar to your `kendoCleanClass` directive
* Manually override the styles of `k-button` so they match the bootstrap buttons
 
As we are using a custom component which renders our buttons we are removing the `k-button` class via `Renderer2`.
IMHO while this works perfectly fine it feels a bit 'hacky'.

**Comment by rusev** [comment]
I see what you mean.

Removing the class names from the built-in directives will be a breaking change in our code base. This is something that we want to avoid. Also we want to encourage you to use the built-in button components with our implementation of the bootstrap theme. If you find something you do not like or you think is a wrong implementation in the theme part please file an issue. We will be glad to hear your opinion on it.

**Comment by pfoedermayr** [comment]
I do absolutely understand your point of view.

We're absolutely find with removing the `k-button` class via `Renderer2`. 
At the point when this issue was filed, we just wanted to show the use-case we were facing at the time, and the fact that the `kendoGrid*Command` directives acted as some kind of a button (but not a full-featured `kendoButton`)

### Example of our internal use-case

We have a component, lets call it `customButton`, which specifies how a button is rendered based on a key. The markup looks like this:

    <button customButton="edit"></button>

Then we have a configuration for the `edit` preset, which specifies what color, icon, text, etc. this button is going have, so that all these 'common' buttons look the same (and to get rid some boilerplate-code).

**Comment by rusev** [comment]
I see.

Thank you for the feedback.

Currently version 2.0 of the Grid package requires Buttons v2.0 or later to be installed. This is a result of making the built-in command buttons fully-featured Kendo Buttons.
