### ISSUE TITLE
ChartSeries not working when using deep templaes

### ISSUE THREAD

**Issue by sidney-pauly** [telerik/kendo-angular#3600]
# What we want to do
[stackblitz](https://stackblitz.com/edit/angular-gmv9vx?file=app/app.component.html) 

We want to define a kendo graph similar to this (simplified example with no attributes set, etc.):
```html
<kendo-chart>
    <kendo-chart-series>
          <kendo-chart-series-item>
          </kendo-chart-series-item>
    </kendo-chart-series>
<kendo-chart>
```

Instead of defining the `<kendo-chart-series>` inside my original component we would like to define it in another component:

```html
<kendo-chart>
    <kendo-chart-series>
          <my-predefined-series-definition></my-predefined-series-definition>
    </kendo-chart-series>
<kendo-chart>
```
MyPredefinedSeriesDefinition component: 
```typescript
@Component({
    selector: 'my-predefined-series-definition'
    template `
        <kendo-chart-series-item>
        </kendo-chart-series-item>
`
})
export class MyPredefinedSeriesDefinition  {

}
```

When setting up the chart in this 2nd way nothing is shown on the graph.

# Why we need it
This might at first glance be a weird setup and you might ask why we need to define our `<kendo-series-item>` elsewhere. The reason is that our goal is to create one or more re-usable libraries, we can put these definitions in and re-use them at different places. We want to put our data binding logic and other common functionality (appearance, filtering, trendlines, etc.) in such common libraries.

# Other approaches
## Doing it in typescript
I'm aware that something like this can be achieved by querying for the ChartComponent with `@ContentChild(ChartComponent)` and then modifying the values in code. This solution is less desirable though as doing this stuff in code is less concise, more error prone and harder to read. 
## Putting the entire `SeriesComponent` (`<kendo-chart-series>`) into the `MyPredefinedSeriesDefinition` component
This approach does not work either, nothing is shown in the graph. We also tried a more "hacky" approach where we defined the component as an attribute:
```typescript
@Component({
    selector: '[my-predefined-series-definition]'
    template `
        <kendo-chart-series-item>
        </kendo-chart-series-item>
`
})
export class MyPredefinedSeriesDefinition  {

}
```
and then injected it as a span:
```html
<kendo-chart>
    <span my-predefined-series-definition>
    </span>
<kendo-chart>
```

this way surprisingly works. Though it does not really help our situation as we can only have one of these at a time. If we try to add a second series like this only the latter one is shown as kendo seemingly only supports one `<kendo-chart-series>` at a time. The whole point in us defining the series in libraries is to be able to just combine various different ones "on the fly" to quickly build up complex charts.

# Working example
You can find all that I described in this [stackblitz example](https://stackblitz.com/edit/angular-gmv9vx?file=app/app.component.html) 

# Possible solutions
## Supporting deep `SeriesItemComponent`
While I don't know the exact code being utilized under the hood, I imagine it might be possible to just change the way `@ViewChildren()` is set up on the `SeriesComponent` in such a way that nested components are also returned.
If such a fix gets applied, we would appreciate it if it was extended to the other chart components (e.g `kendo-chart-y-axis` and `kendo-chart-y-axis-item`)

## Supporting multiple `SeriesComponent`
As can be seen in the "hacky" solution such a setup is possible for a single chart. If  `SeriesItemComponent` was extended such that it could be present multiple times on a `ChartComponent` then this would also resolve our issue.
Here as well we would appreciate it such support would also be extended to other components

**Comment by Raisolution** [comment]
Hi @sidney-pauly

This repository is aimed for bug reports only. Please log a feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui) where we could track the demand for this feature more accurately.
