### ISSUE TITLE
Datepicker getting shown value

### ISSUE THREAD

**Issue by elipongr** [telerik/kendo-angular#3611]
So for example if I delete the year of the button while being subscribed on the datepicker the shown value is 09-20-year but the value in the FormControl is null.
 
Are there any ways to access the shown value?

**Comment by preslavapetrova1** [comment]
Hi @elipongr,

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios or configurations.
