### ISSUE TITLE
Unable to set the focus to kendo-dropdownlist

### ISSUE THREAD

**Issue by revathichevuri** [telerik/kendo-angular#3612]
**Describe the bug**
Unable to set the focus to kendo-dropdownlist.

**To Reproduce**
1. When page load first component should be on auto focus. (Here the first component is kendo-dropdownlist)
Or
2. After clicking ok button of confirmation dialog focus should set to kendo-dropdownlist.

**Expected behavior**
Focus should able to set After clicking ok button of confirmation dialog focus should set to kendo-dropdownlist.

**Browser**
 Windows 10 Chrome browser.

**Additional context**
I have tried below code 
<kendo-dropdownlist #dropdown></kendo-dropdownlist>
@ViewChild() dropdown: ElementRef;
this.dropdown.nativeElement.focus();

And

document.getElementbyId('dropdown').focus()

But Both are not working.
Please let me know where am doing mistake.
Thank you.

**Comment by revathichevuri** [comment]
I have tried below code 
<kendo-dropdownlist #dropdown></kendo-dropdownlist>
@ViewChild() dropdown: ElementRef;
this.dropdown.nativeElement.focus();

And

document.getElementbyId('dropdown').focus()

But Both are not working.
Please let me know where am doing mistake.
Thank you.

**Comment by Raisolution** [comment]
Hi @revathichevuri 

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios or configuration.
