### ISSUE TITLE
[kendo-multiviewcalendar] with directive kendoDateRangeSelection - behavior issue  on  date selection 

### ISSUE THREAD

**Issue by GeoffroyDlg** [telerik/kendo-angular#3613]
**Describe the bug**
if you select the same start date as previously selected. the selection is not taken into account

**To Reproduce**
 1. select a range dates like 3/8/2022 to 3/25/2022
 2. Then I want to select a new range date like 3/8/2022 to 3/8/2022 
  Your selection is not take in account.

**Expected behavior**
First click (selection) I want override the start date and second click i want override the end date.
Same behavior from jquery kendo datepicker demo: 
[ kendo datepicker demo](https://demos.telerik.com/kendo-ui/daterangepicker/appearance)

[https://stackblitz.com/edit/angular-wizrh9?file=app/app.component.ts](https://stackblitz.com/edit/angular-wizrh9?file=app/app.component.ts)

**Comment by JoomFX** [comment]
The behavior in the Angular suite is expected as per the design specification.
