### ISSUE TITLE
DateInputs min max value validation only through the calendar

### ISSUE THREAD

**Issue by seb9465** [telerik/kendo-angular#3616]
**Describe the bug**
I am using date inputs with min and max values. Typing an out of range value won't fire an error. According to the documentation, it seems like its the desired behaviour and to prevent this, I should put the date component in read-only state. Am I correct ? If so, why is it that way ? I'd really love it if by typing an out of range value, it fires an error instead of preventing the user of typing values by making him go through the calendar.

**Expected behavior**
When typing an out of range value (when not going through the calendar), a min-max value validation is made and an error is fired.

Thanks !

**Comment by georgi-sla** [comment]
I tested this behavior in a DatePicker component and it seems to fire an error when the user changes the date with one that is outside the predetermined range. When the developer enters a date in the code, the component fires an error and does not show the date, but instead shows an empty calendar: 

![image](https://user-images.githubusercontent.com/108671673/209169447-1e3969ea-ea79-46fb-876c-837f09ca3e5d.png)


However, when null is set as default value the component does not throw an error but is also not displaying the calendar properly as null is out of the predetermined range: 

![image](https://user-images.githubusercontent.com/108671673/209168584-fb560cb9-cea6-4cff-9925-849213a14781.png)

Link to demo: https://stackblitz.com/edit/angular-rzifpg?file=src%2Fapp%2Fapp.component.ts

**Comment by svetq** [comment]
The demonstrated behavior is indeed by the design of the DatePicler component. The desired behavior could be implemented as an additional feature of the component or the current behavior could be updated. For the purpose, I have logged a new feature request asking for this behavior: https://feedback.telerik.com/kendo-angular-ui/1595765-datepicler-fires-an-error-instead-of-preventing-the-user-of-typing-values
