### ISSUE TITLE
[TileLayout] Allows dropping an tile item even if there isn't space in the grid layout

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3620]
**Describe the bug**
The component allows dropping an element even when there is not enough available space to fit the item. This leads to an invalid rendering of the tile item and TileLayout component.
Ticket ref containing screen recording - 1556891

**To Reproduce**
https://stackblitz.com/edit/angular-ygzeht-z2wqxt?file=app%2Fapp.component.ts

**Comment by Raisolution** [comment]
Issue seems to not be reproducible anymore in latest version -
https://stackblitz.com/edit/angular-4pe8pb-rw4t1d?file=src%2Fapp%2Fapp.component.ts
