### ISSUE TITLE
Millisecond segment is not localized 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3623]
**Describe the bug**
The millisecond segment is not localized - undefined is rendered instead:

![image](https://user-images.githubusercontent.com/33104481/158819271-41b0ed26-cb8c-46a4-aa4a-7cc2df4e09af.png)

Used format _MM/dd/yyyy HH:mm:ss:SS_ 

**To Reproduce**
https://stackblitz.com/edit/angular-gcwrkw?file=app%2Fapp.component.ts

When there is no loaded locale the millisecond text is shown as expected:
https://stackblitz.com/edit/angular-evt3k8?file=app/app.component.ts

After some investigation, we noticed that in _kendo-angular-intl_ package, there is no dedicated object for milliseconds.

**Comment by gkarapeev** [comment]
Further info:
- Locales are auto-generated in `intl/build-locales.js#L122`.
- Translations are available [here](https://unicode-org.github.io/cldr-staging/charts/latest/by_type/units.duration.html#millisecond).

**Comment by svetq** [comment]
This is no longer reproducible with the latest version 14.0.0:

https://stackblitz.com/edit/angular-rb5nrk
