### ISSUE TITLE
[DropDownButton] Updating imageURL doesn't remove the span element that was holding the image

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3626]
**Describe the bug**
Updating imageURL doesn't remove the span element that was holding the image. This will stack span elements and break the UI. It seems to be related to the new rendering as in older versions this behavior isn't exhibited.

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-xngr8f-pkoxlf?file=app%2Fapp.component.ts
2. Choose different items from the popup.

**Screenshots**
![chrome_p3cz1lnHfR](https://user-images.githubusercontent.com/49076727/159444498-00c571c8-4e65-47d3-8cf7-f90250c224e6.png)
![chrome_sjx7sa4W7u](https://user-images.githubusercontent.com/49076727/159444555-bfbc52c2-812b-467c-a83a-5d834303b3ed.png)

**Workaround**
DropDownButton - https://stackblitz.com/edit/angular-xngr8f-wgow34?file=app%2Fapp.component.ts
Toolbar - https://stackblitz.com/edit/angular-xngr8f-etfd4n?file=app%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fix is available in `v7.0.5` of the Buttons package.
