### ISSUE TITLE
ComboBox is focused with Tab when is disabled

### ISSUE THREAD

**Issue by stedice** [telerik/kendo-angular#3627]
**Describe the bug**
The button to open the dropdown window inside the kendo-combobox component should have `tabindex="-1"`, at least when the component is disabled. The behavior is correct for the kendo-dropdownlist

**To Reproduce**
https://stackblitz.com/edit/angular-vefrfj

**Expected behavior**
The button inside the component kendo-combobox should not be in tab order.

**Comment by JoomFX** [comment]
Fixed in v13.3
