### ISSUE TITLE
How to display the title/tooltip on tab focus/focus for kendoButton in agular

### ISSUE THREAD

**Issue by revathichevuri** [telerik/kendo-angular#3628]
How to display the title/tooltip on tab focus/focus for kendoButton in angular.

I have tried data-title but it is working only for anchor tag not for buttons. Please suggest the way of implementation.
Thank you.
**If the issue is specific to your project, please open a [support ticket](https://www.telerik.com/account/support-tickets).**

**Comment by preslavapetrova1** [comment]
Hi @[revathichevuri](https://github.com/revathichevuri)

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios or configuration.
