### ISSUE TITLE
[Editor] - Expose input to set NodeViews option

### ISSUE THREAD

**Issue by nadavsinai-philips** [telerik/kendo-angular#3630]
The [nodeViews feature of proseMirror](https://prosemirror.net/docs/ref/#view.EditorProps.nodeViews)  can't be used if not exposed as an input as it should be set in construction of the EditorView which is done internally the component.

We would like to supply it as an input to your component

**Comment by Raisolution** [comment]
Hi @nadavsinai-philips 

Please log the feature in question in our Feedback portal, so we could track the customer demand for it:
https://feedback.telerik.com/kendo-angular-ui
