### ISSUE TITLE
Programmatically Selecting tab not firing tabSelect event (Angular)

### ISSUE THREAD

**Issue by zaryab91** [telerik/kendo-angular#3632]
**Describe the bug**
When the tab is selected programmatically using the ViewChild directive with TabstripComponent. The tabselect event of the tabstrip is not fired, it used to work in versions < **@progress/kendo-angular-layout: 6.2.0**

**To Reproduce**
Kindly click on the Button it will switch to tab index 2 programmatically

The event is not firing
https://stackblitz.com/edit/angular-zlzqxs?file=app%2Fapp.component.ts  **with @progress/kendo-angular-layout: 6.5.2** 
The event is firing ("alert popup is displayed")
https://stackblitz.com/edit/angular-nre59k?file=app%2Fapp.component.ts **with @progress/kendo-angular-layout: 6.1.8** 

**Expected behavior**
Upon changing the tab programmatically the tab select event should be fired because the content of the tab may be loaded from the backend.

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 99

**Comment by Raisolution** [comment]
Hi @zaryab91 

The previous behaviour is considered a bug and was fixed in `v6.2.0` of the layout package.

Detailed explanation is available in #3503
