### ISSUE TITLE
[Editor] Paste event not triggered when the pasted content is plain text

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#3633]
**Describe the bug**
The Editor `paste` event is not triggered when the content is plain text.

**To Reproduce**

Reproducible in the documentation example:

[https://www.telerik.com/kendo-angular-ui/components/editor/events/#toc-customizing-pasted-content](https://www.telerik.com/kendo-angular-ui/components/editor/events/#toc-customizing-pasted-content)

**Expected behavior**
The event is triggered allowing the developer to prevent it and/or replace the pasted content regardless of the pasted content - whether it is html or plain text.

**Comment by Raisolution** [comment]
Fix available in `v4.0.0` of the Editor package.
