### ISSUE TITLE
[TileLayout] Focusable elements cannot be focused inside the TileLayoutItemHeader when reorderable is enabled

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3635]
**Describe the bug**

Focusable elements cannot be focused inside the TileLayoutItemHeader when reorderable is enabled.
For example, if there is an input element inside the item header, it cannot be focused by the user. Another issue is if the item header has a button inside, the user can click it but if he clicks and drags the tile reorders.

Screen recording of both issues:

https://user-images.githubusercontent.com/49076727/160830957-9e803882-c7b0-44a2-94a7-e7df68725057.mp4

**To Reproduce**

1. open - https://stackblitz.com/edit/angular-ccdkpd-nzgjsg?file=app%2Fapp.component.ts
2. Try to focus the input field or click and drag the button.

**Workaround**
https://stackblitz.com/edit/angular-ccdkpd-h9sycv?file=app%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fix is available in `v7.1.0` of the Layout package.
