### ISSUE TITLE
Make Kendo-intl optional  / make them loadable on demand

### ISSUE THREAD

**Issue by montella1507** [telerik/kendo-angular#3639]
Nowadays, INTL api is supported in all browsers alive:
https://caniuse.com/?search=Intl

Every Kendo locale takes 70-80kb not-minified. I think it should be definitely possible just left custom INTL files and use provided by the browser itself. 

We dont need things like:
       decimal: ",",
            group: " ",
            list: ";",
            percentSign: "%",
            plusSign: "+",
            minusSign: "-",
            exponential: "E",
            superscriptingExponent: "×",
            perMille: "‰",
            infinity: "∞",
            nan: "NaN",
            timeSeparator: ":"
        },

We can just use Intl.NumberFormat.Format(). 

Same for Numbers, Dates, Currencies. It is really bigger issue as far as:
- you havent provided any way how to load locales lazily (i tried to load them dynamically without succes)
- it can lead to +500 - 1000kB initial chunk easily ( average apps usually support 10 and even more locales)

**Comment by Raisolution** [comment]
Hi @montella1507 

Please log this feature request in our [feedback portal](https://feedback.telerik.com/kendo-angular-ui), so we could more accurately track the demand for it.

Thank you in advance.
