### ISSUE TITLE
kendoButton with icon and dynamic text raise error when promise or timeout resolves

### ISSUE THREAD

**Issue by lucasmartinez** [telerik/kendo-angular#364]
When icon property is used in a kendoButton and button text is resolved by a promise, button width is not adjusted. Please see following example: 

http://plnkr.co/edit/Ykho0sQfd1ZvIhL6Pl4M?p=preview

You will see "Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'." in console.

**Comment by valchev** [comment]
Thank you for bringing this to our attention. I will examine the case further and write back as soon as I have more information.

**Comment by valchev** [comment]
The issue should be fixed in the latest version ([updated plunker](http://plnkr.co/edit/N6tLhLabgcey3GxMEFAw?p=preview)).

**Comment by siyka-marinova** [comment]
Fixed in kendo-angular-buttons v.1.0.3
