### ISSUE TITLE
Unexpected behavior when the field is set to "is null" in filter component

### ISSUE THREAD

**Issue by stellagusmini** [telerik/kendo-angular#3640]
I use new components filter, when I set a filter element to “is null”, its field value is disabled. But all other filter field value is reset and disabled after that.
You can easily reproduce on demo : https://www.telerik.com/kendo-angular-ui/components/filter/
Set a value for "country" filter, then change "budget" to "is zero", then "country" value is disabled and reset.

**Comment by svetq** [comment]
fix available in latest dev version: [2.0.1-dev.202205171507](https://www.telerik.com/kendo-angular-ui-develop/components/filter/changelog/#35b91178-ade0-5408-b258-dd7ad22d2f12)

**Comment by svetq** [comment]
fix available in official versions: [2.1.0](https://www.telerik.com/kendo-angular-ui-develop/components/filter/changelog/#38653d5c-4f00-5d95-9625-b60d8bff9448)
