### ISSUE TITLE
Localization Bug in Filter Component

### ISSUE THREAD

**Issue by kutkovav** [telerik/kendo-angular#3643]
While trying to localize the new Filter Component into Czech via [CustomMessagesComponent](https://www.telerik.com/kendo-angular-ui/components/filter/api/CustomMessagesComponent/), I ran into following issue.

The localization of `filterAndLogic` and `filterOrLogic` does not work. It only works if I add a new filter group - then I have a Czech translation for the operators of the group, but the operators that were there while initializing the component are still English. 
The same problem occurs with the operators localization, e.g. filterGtOperator. Only works for newly added filter.

You can see it in a demo: https://stackblitz.com/edit/angular-hmvskt?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by svetq** [comment]
fix available in official version: [2.1.0](https://www.telerik.com/kendo-angular-ui-develop/components/filter/changelog/#38653d5c-4f00-5d95-9625-b60d8bff9448)
