### ISSUE TITLE
[Dropdowns] FilterableComponent

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#3649]
**Describe the bug**
`FilterableComponent` has been removed from the public API

This gave us a common API for our directive to access the `filterChange` and `data` properties.

_It was not listed in the changelog, nor was there any suggestions of a workaround_

**To Reproduce**
Upgraded package from `6.0.2` to `7.0.0`

**Comment by stnikolova** [comment]
Hi @cheng93

The `FilterableComponent` has never been included or intended to be included as part of our public API for the `DropDowns` package. It seems that until v.7.0.0, the Angular and TypeScript versions wrongly allowed for importing the `FilterableComponent` without indication that no such member is exported.

`v.7.0.0` of the `DropDowns` is shipped as an Ivy library compatible with Angular 12 and 13 and produces the correct import behavior. 

For future public API usage, please refer to the [Kendo Angular UI Documentation](https://www.telerik.com/kendo-angular-ui/components/dropdowns/api/) where all available members are listed and any changes are reflected in the changelog.

As this repository is for bug reports only, please open a [support ticket](https://www.telerik.com/account/support-tickets) if further assistance is needed regarding implementation.
