### ISSUE TITLE
[Filter] adding [value] before [filters] triggers an error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3652]
**Describe the bug**
When adding the [value] input property before [filters] an error is triggered.

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-3f6tzy?file=app/app.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by svetq** [comment]
fix available in official version: [2.1.0](https://www.telerik.com/kendo-angular-ui-develop/components/filter/changelog/#38653d5c-4f00-5d95-9625-b60d8bff9448)
