### ISSUE TITLE
[DatePicker] Misaligned date numbers in calendar when weekNumbers are displayed

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3653]
**Describe the bug**
When `weekNumbers`  to `true`, the date numbers in the calendar are misaligned.

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/calendar-type/#toc-week-number-column/

**Expected behavior**
All dates should be properly aligned.

**Screenshots**
![30f9b53a-c6c1-43e7-9a12-4c5189c56026_kendo-picker-weeknumber-bug](https://user-images.githubusercontent.com/18744873/164711258-f89bb9b9-4c31-4c83-b7d2-182eb4ca9ffb.png)

**Comment by svetq** [comment]
This is no longer reproducible in the latest version 14.0.0:
https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/calendar-type/#toc-week-number-column
