### ISSUE TITLE
[MultiColumnComboBox] Headers aren't synchronized when horizontally scrolling the component

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3656]
**Describe the bug**
Headers aren't synchronized when horizontally scrolling the component.
Screen recording - https://screencast-o-matic.com/watch/c3fXioVqdB8

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-44tpe5?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fcontacts.ts
2. Scroll the content horizontally.

**Expected behavior**
Headers to be in synch with the horizontal scrolling.

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
