### ISSUE TITLE
[Grid][Demo] Filtering

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#3658]
**Describe the bug**
The demos on this page are broke https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-multi-checkbox-menu-filtering

**Screenshots**
![image](https://user-images.githubusercontent.com/13205912/165472190-600eff08-53c8-448e-af80-cdeaf9871226.png)

**Comment by ciiara** [comment]
Thank you for the feedback. Indeed, we are experiencing issues with some of our demos. We are going through all the examples and applying fixes where such are needed.

**Comment by siyka-marinova** [comment]
The demo is now fixed.
