### ISSUE TITLE
installed @latest and dropdowns didn't install a dependency of @progress/kendo-angular-treeview

### ISSUE THREAD

**Issue by webmandman** [telerik/kendo-angular#3662]
**Describe the bug**
This is the error I get when my angular app attempts to compile:
./node_modules/@progress/kendo-angular-dropdowns/fesm2015/kendo-angular-dropdowns.js:22:0-57 - Error: Module not found: Error: Can't resolve '@progress/kendo-angular-treeview' in 'C:\Development\sites\intra\angularworkspace\node_modules\@progress\kendo-angular-dropdowns\fesm2015'

When I installed dropdowns it should have also installed this treeview dependency.

**Comment by tsvetomir** [comment]
The TreeView has been added as a peer dependency in DropDowns [v5.0.0](https://www.telerik.com/kendo-angular-ui/components/dropdowns/changelog/#5eb71531-d55f-5381-8e1e-377fa18d7675). Depending on the npm version, the dependency may be installed automatically, but in general it should be added to your project dependencies:

`npm install --save @progress/kendo-angular-treeview`.
