### ISSUE TITLE
[Scheduler] k-middle-row

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#3665]
**Describe the bug**
`k-middle-row` is used to lighten the slots in between major times, however the class is only on the first row

**To Reproduce**

https://stackblitz.com/edit/angular-8ynm8b?file=src/app/app.component.ts

**Expected behavior**
`k-middle-row` class is rendered on all the middle rows

**Screenshots**
![image](https://user-images.githubusercontent.com/13205912/165971209-e20c93c0-5765-44b4-b6c0-754ba9fa3d17.png)

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by cheng93** [comment]
looks likes this issue was present in the jQuery version and resolved

https://github.com/telerik/kendo-ui-core/issues/2671

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
