### ISSUE TITLE
right-to-left-support kendo-grid problem

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#367]
it doesnt work
[right-to-left grid problem](http://plnkr.co/edit/2UxiUZVeb69ALAPBVwHF?p=preview)

**Comment by rkonstantinov** [comment]
The Grid component does not have RTL support yet. Please refer to [this issue](https://github.com/telerik/kendo-angular/issues/96) for more details.

**Comment by gilior** [comment]
tnx. I guess i'll wait a future version with full  rtl support.
