### ISSUE TITLE
ComboBox: Clear value doesn't work on Firefox

### ISSUE THREAD

**Issue by sigVince** [telerik/kendo-angular#368]
Example on the official demo:
http://www.telerik.com/kendo-angular-ui/components/dropdowns/

No errors in console on the official demo though. I have the same behavior on my app, but with the following error :
`EXCEPTION: Error in ./ComboBoxComponent class ComboBoxComponent - inline template:12:12 caused by: event is not defined`

**Comment by tapopov** [comment]
Thank for reporting this @sigVince 
It's fixed in v0.33.1

**Comment by sigVince** [comment]
Much better, thanks :)
