### ISSUE TITLE
[Editor] Toolbar ButtonGroup buttons not rendering

### ISSUE THREAD

**Issue by chakshutadesai** [telerik/kendo-angular#3680]
**Describe the bug**
The Editor Toolbar has issues rendering Buttons inside ButtonGroup.

**To Reproduce**
1. Place  editor with basic toolbar as following,
2. Code
```
<kendo-editor style="height: 450px;">
  <kendo-toolbar>
    <kendo-toolbar-buttongroup>
      <kendo-toolbar-button kendoEditorBoldButton></kendo-toolbar-button>
      <kendo-toolbar-button kendoEditorItalicButton></kendo-toolbar-button>
      <kendo-toolbar-button kendoEditorUnderlineButton></kendo-toolbar-button>
      <kendo-toolbar-button kendoEditorStrikethroughButton></kendo-toolbar-button>
    </kendo-toolbar-buttongroup>
    <kendo-toolbar-dropdownlist kendoEditorFormat></kendo-toolbar-dropdownlist>
    <kendo-toolbar-dropdownlist kendoEditorFontSize></kendo-toolbar-dropdownlist>
  </kendo-toolbar>
</kendo-editor>
```

**Expected behavior**
ButtonGroup with Bold, Italic etc button should be rendered correctly with correct HTML.

**Screenshots**
 As shown in screenshot, Buttons inside ButtonGroup is not rendered. Other toolbar like dropdown works correctly.
![image](https://user-images.githubusercontent.com/46338853/169790380-71cce965-c6fd-4408-8986-e173b8084338.png)

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**

**Comment by yanmariomenev** [comment]
Closing the issue as it seems to be related to configuration and will be further discussed in the private ticket(**1566191**) where more details would need to be provided.
