### ISSUE TITLE
[Feature request] Export ColumnInfoService from Grid and TreeList

### ISSUE THREAD

**Issue by ovska** [telerik/kendo-angular#3681]
This is a minor ask, but we rely on `ColumnInfoService` from `kendo-angular-grid` and `kendo-angular-treelist` in a custom column visibility picker. Namely, the `columnsContainer`, `leafNamedColumns` and `changeVisibility()` apis.

After Ivy changes, this service is no longer exported. It can still be resolved by casting injected `GridComponent`/`TreeListComponent` to `any`, but DI no longer works for it.

We understand it's a non-public API that has no guarantees in how it works, but #3502 suggested to ask if any internal apis were used that are no longer available.

Feel free to use your discretion on this, as I said we can get by with working around the issue for now.

**Comment by Raisolution** [comment]
Hi @ovska ,

Thank you for the suggestion.
The ColumnInfoService has been exported in `v5.0.2` of the Treelist package and the latest dev version of the Grid package.

We will publish an official version of the Grid in the upcoming days.
