### ISSUE TITLE
[Grid] Incorrect layout when using nested group header column

### ISSUE THREAD

**Issue by SpaceMalamute** [telerik/kendo-angular#3682]
**Describe the bug**
The Grid has incorrect layout when using nested kendo-grid-column-group with same count of nested column

**To Reproduce**
https://stackblitz.com/edit/angular-swbco7

**Screenshots**
![image](https://user-images.githubusercontent.com/33428024/171018707-3f1b0f62-8bfe-4f8e-b08c-dba4362478d8.png)
![kerhV09r0i](https://user-images.githubusercontent.com/49076727/171381281-eaf4b21f-cfca-4da6-a185-7052bddf44ea.png)

**Comment by SpaceMalamute** [comment]
#2769

**Comment by SpaceMalamute** [comment]
When this issue will be fix ?

**Comment by yantotvs** [comment]
When this issue will be fix ?²

**Comment by Raisolution** [comment]
Fix is available in `v11.1.0` of the Grid package.

**Comment by yanric2000** [comment]
The bug was fixed only in the Grid package? the treelist package seems to have the same issue
