### ISSUE TITLE
[RangeSlider] z-index

### ISSUE THREAD

**Issue by matteo2437** [telerik/kendo-angular#3685]
**Describe the bug**

While sliding a dot the z-index increases.

**To Reproduce**
Move the element with this class k-draghandle and check the z-index.
[](https://www.telerik.com/kendo-angular-ui/components/inputs/rangeslider/)

**Expected behavior**
Z-index shouldn't change.

**Screenshots**
![image](https://user-images.githubusercontent.com/68251639/171894277-c7db704b-2c49-4118-957d-788b5afb8112.png)
![image](https://user-images.githubusercontent.com/68251639/171894609-c453a9ba-96b9-43e6-9ba7-fcbf02579bb7.png)

**Browser**
 - OS: ALL
 - Browser ALL
 - Version Latest

**Comment by dtopalov** [comment]
Fixed in v. 10.1.0 of the **@progress/kendo-angular-inputs** package.
