### ISSUE TITLE
Kendo-combobox valueChange event will trigger twice if toggling *ngIf in valueChange event.

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#369]
In kendo-combobox, the valueChange event will trigger twice if toggling *ngIf within valueChange event. 

Link: [Plunker] (http://plnkr.co/edit/MCw352Nrd9FhrTcsVQQD?p=preview)

Steps:
1) Select an item (Noted that the emitted value is the valueField) 
2) Select another item - this will toogle the *ngIf within valueChange event (if(this.num > 1) { this.hide = true; } )

3) Bug 1 - The valueChange event will trigger twice.
4) Bug 2 - Note that the value emitted is the textField.

Kindly look at the Plunker more info

**Comment by tsvetomir** [comment]
Seems to be fixed in the latest version. See [plnkr](http://plnkr.co/edit/ddLe4KQQgIe59zT8Ljwj?p=preview).

**Comment by ipeshev** [comment]
We can think for some test of it. Will test it as soon as plunker stops complaining for not loading google scripts.
