### ISSUE TITLE
[Calendar] Week Selection in the Calendar not working as expected

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3690]
**Describe the bug**
When you click on the week number to select the week, it scrolls and selects a random week instead.

**To Reproduce**

1. Open the example in the [Selection Modes page](https://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/multiple-selection/). 
2. Scroll by 4-5 months from the active month and select a week by clicking on the week number.

**Expected behavior**
Irrespective of how many months you scroll, the desired week should be selected.

**Comment by hetalishah** [comment]
This behavior can be observed in the [Multiple Selection](https://www.telerik.com/kendo-angular-ui/components/dateinputs/multiviewcalendar/multiple-selection/) of the MultiViewCalendar as well.

**Comment by stnikolova** [comment]
The fix is available in **v15.4.0** of @progress/kendo-angular-dateinputs.
