### ISSUE TITLE
[Editor] Responsive toolbar does not work properly

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-angular#3692]
**Describe the bug**
The responsive toolbar in the Editor does not work properly on the initial page load. Once the user starts decreasing/increasing the window size, the responsive toolbar starts working properly.
The issue can be seen in the [Editor documentation](https://www.telerik.com/kendo-angular-ui/components/editor/responsive-toolbar/) as well.
It can also be seen in [this Stackblitz example](https://stackblitz.com/edit/angular-s9mzgj?file=src/app/app.component.ts) (related to ticket 1568221).
I wasn't able to reproduce the issue with the standalone Toolbar component.

**To Reproduce**

1. Open the [Editor documentation](https://www.telerik.com/kendo-angular-ui/components/editor/responsive-toolbar/) and look at the example there.
2. Change the window width and notice how the responsive toolbar starts working properly.

**Expected behavior**
The responsive toolbar in the Editor should work properly on initial page load.

**Screenshots**
![editor](https://user-images.githubusercontent.com/7753940/172795768-a030be3e-fa58-4d5e-a623-82fb42ad4e90.png)

**Browser**
N/A

**Additional context**
N/A

**Comment by dtopalov** [comment]
Fixed in v. 4.1.6 of the **@progress/kendo-angular-editor** package **and** v. 6.0.3 of the **@progress/kendo-angular-toolbar** package.
