### ISSUE TITLE
[Drawer] Drawer item has aria-selected attribute and no role

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3693]
**Describe the bug**
The item of the Drawer has aria-selected attribute, but no role, which causes accessibility issues:

**To Reproduce**

1. Open this page https://www.telerik.com/kendo-angular-ui/components/layout/examples/drawer/basic_usage/?theme=default-ocean-blue&themeVersion=5.3.1
2. Run Axe tool.
3. The following error is observed:
<img width="1112" alt="Screenshot 2022-06-10 at 10 54 51" src="https://user-images.githubusercontent.com/52581229/173018667-b138959d-116e-4f65-8408-ae79461d28ab.png">

**Expected behavior**
No errors should be reported by Axe.

**Comment by Raisolution** [comment]
Fixed in the latest dev version of the Layout package.

**Comment by Raisolution** [comment]
The fix is available in `v7.1.0` of the Layout package.
