### ISSUE TITLE
[TimePicker] Accessibility issue with aria-expanded and spinbutton role

### ISSUE THREAD

**Issue by preslavapetrova1** [telerik/kendo-angular#3694]
**Describe the bug**
Currently, the TimePicker component has a 'spinbutton' role and aria-expanded attribute which are incompatible. The aria-expanded attribute requires a different role.

**To Reproduce**

1. Open the TimePicker component
2. Run the Axe tool
3. The following accessibility issue is reported:

ARIA attribute is not allowed: aria-expanded="false"

**Comment by ipeshev** [comment]
Fixed in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Released with **v7.1.3** of `@progress/kendo-angular-dateinputs`.
