### ISSUE TITLE
[Editor] Table resizing not update value

### ISSUE THREAD

**Issue by quangtranacs** [telerik/kendo-angular#3696]
**Issue**
When resizing table in Kendo Editor, the value, valueChange and valueModifier doesn't update the width, height of the table to value field.

**Reproduce**
https://stackblitz.com/edit/angular-9zsbzh?file=src%2Fapp%2Fapp.component.ts

**Comment by dtopalov** [comment]
Fix is available in v. 4.1.11 of the **@progress/kendo-angular-editor package**.
