### ISSUE TITLE
[Scheduler] Doesn't convert time correctly when dragging an event

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3698]
**Describe the bug**
When creating and dragging an event in the Scheduler it doesn't convert the time correctly as demonstrated in the following recording:

https://user-images.githubusercontent.com/49076727/174081210-304ed36a-24fc-4d8e-b03e-be4b865458d5.mp4

**To Reproduce**
Open the following example - https://stackblitz.com/edit/angular-rclh8x?file=src%2Fapp%2Fapp.component.ts
Create an event and depending on the timezone difference dragging it will show a different date than the created one. This can especially be observed when moving it to `all day` slot.

**Comment by svetq** [comment]
The demonstrated behavior is expected. The logged date doesn't take into account the local time zone, hence the difference. Dragging an event to the all day template toggles the isAllDay property, but doesn't change the event start and end.
