### ISSUE TITLE
AutoComplete doesn't reselect value

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#370]
http://plnkr.co/edit/HokdD3BMhLVXYhBtSCj0?p=preview
1. Type 'male' and select it.
2. Click clear button.
3. If now try to selct 'male' again, it is not happen.

**Comment by tapopov** [comment]
Hey @destus90 

I could not reproduce this with the latest version. Can you check [this example](http://plnkr.co/edit/rpSwoIGuWDc3I6rRJ2Yq?p=preview) and confirm?

**Comment by destus90** [comment]
@tapopov
thx. its works.
