### ISSUE TITLE
[Tooltip] Tooltips showing at wrong time and sticking when using multiple Tooltips

### ISSUE THREAD

**Issue by PaskalevStoyan** [telerik/kendo-angular#3702]
**Describe the bug**
Using multiple Tooltips, the text shows but doesnt hide until the Tooltip is hovered again. This happens only the first time and afterwards the Tooltip behaves as it should.

**To Reproduce**
1. Open the [StackBlitz demo](https://stackblitz.com/edit/angular-mvdc1u-6saeyj?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts) 
2. Hover over the names in the first column (**Contact Name**). The Tooltip will show but not hide.
3. Hover again over the names and the Tooltip will hide.
4. Hover again over the names and the second time, the Tooltip will behave as it should be.

**Expected behavior**
The Tooltip should show when an item is hovered and should hide when the mouse is out of the items boundaries.

**Comment by aldrashan** [comment]
Any progress on this issue? It's been a few months now...

**Comment by metealikalfa** [comment]
v3.x works fine
v4.x still has this bug

**Comment by siyka-marinova** [comment]
Fix is now available in the [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of `kendo-angular-tooltip`

**Comment by Raisolution** [comment]
Fix is published in `v4.0.3` of the Tooltip package.
