### ISSUE TITLE
[Gantt] endDate not calculated as expected

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3703]
**Describe the bug**
When there is a task which `endDate` is a Sunday date in the week view, the data is not represented in the right way on the Gantt timeline. The task spans beyond the expected end date.

**To Reproduce**
https://stackblitz.com/edit/angular-abkbyk?file=src%2Fapp%2Fapp.component.ts

**Screenshots**
![Screenshot 2022-06-28 at 15 29 10](https://user-images.githubusercontent.com/18744873/176179072-4ec7dabf-ec3a-47e9-9d27-3de43aad6eb7.png)
![Screenshot 2022-06-28 at 15 30 20](https://user-images.githubusercontent.com/18744873/176179084-48b42cbc-ff23-4d8f-b806-19175216d0fe.png)

If the date is changed to be a non-Sunday day it renders as expected.

Support ref item: #1570591

**Comment by dtopalov** [comment]
Fixed in v.2.0.2 of the @progress/kendo-angular-gantt package.
