### ISSUE TITLE
[Dropdowns] Japanese text duplicated in Safari browser

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#3704]
**Describe the bug**
In the ComboBox and AutoComplete (DropDowns package), the Japanese characters are repeated/duplicated when you type in the input box in the Safari browser. Additionally, the cursor remains on the left side.

**To Reproduce**
Run the [AutoComplete example](https://www.telerik.com/kendo-angular-ui/components/dropdowns/autocomplete/) and the [ComboBox example](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/) in Safari and use the Japanese keyboard to type.

**Expected behavior**
The characters should not be duplicated and the cursor should move to the right of the character as you type.

**Screenshots**
The issue can be seen in [this screen recording](https://www.screencast.com/t/vlBjNKfHyTv). Please refer private ticket: 1570128

**Browser**
 - OS:  iOS, macOS, iPadOS
 - Browser: Safari

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)!
