### ISSUE TITLE
[PivotGrid] Excel Export

### ISSUE THREAD

**Issue by LanceMcCarthy** [telerik/kendo-angular#3707]
This is the GitHub tracking item for [https://feedback.telerik.com/kendo-angular-ui/1571455-pivot-grid-excel-export](https://feedback.telerik.com/kendo-angular-ui/1571455-pivot-grid-excel-export).

**Comment by dtopalov** [comment]
To be tracked in the public Feedback Portal:

https://feedback.telerik.com/kendo-angular-ui/1571455-pivot-grid-excel-export

**Comment by dtopalov** [comment]
Will be tracked in the Feedback Portal.
