### ISSUE TITLE
[Editor] Title attribute is missing for Split and Merge cells tools

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3709]
**Describe the bug**

The split and merge table cells tools don't have **title** attribute set. 

Localized messages should also be added alongside with the **title** attribute.

**To Reproduce**
Hover the last two tools. There is no tooltip:
https://stackblitz.com/edit/angular-qdkbxz

**Comment by Raisolution** [comment]
Fix is available in `v4.1.10` of the Editor package.
