### ISSUE TITLE
Extending MessageService fails when using strictNullChecks

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular#371]
As stated in the documentation `MessageService.get` returns `'The localized message for this key or 'undefined' if not found.'`

When I extend `MessageService` and return undefined (or use a function which potentially returns undefined), the typescript compilation (strictNullChecks enabled) will fail: `Class 'MyMessageService' incorrectly extends base class 'MessageService'.`

Sample Code ([TypeScript-Playground](http://www.typescriptlang.org/play/index.html#src=declare%20abstract%20class%20MessageService%20%7B%0D%0A%20%20%20%20abstract%20get(key%3A%20string)%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aclass%20MyMessageService%20extends%20MessageService%20%7B%0D%0A%20%20%20%20get(key%3A%20string)%20%7B%0D%0A%09%09return%20undefined%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)):
````
export class MyMessageService extends MessageService {
    get(key: string) {
        return undefined;
    }
}
````

**Comment by tsvetomir** [comment]
Good point, will extend the method to return `string | undefined`.
