### ISSUE TITLE
Component in Dialog seems not to be properly in lifecycle

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#372]
We are using the DialogService in combination with an own component which is displayed withing it:
```
    const modalDialog: DialogRef = this.dialogService.open({
      title: "My Dialog",

      // show component
      content: MyContentComponent,

      actions: [
        {text: "Save", id: DialogActionIdentifier.save, primary: true},
        {text: "Cancel", id: DialogActionIdentifier.cancel}
      ]
    });
```

The MyContentComopnent implements the both interface OnInit and OnDestroy. We would expect the dialog to invoke both of the **lifecycle events** of the MyComponentContent properly. For the **ngOnInit** method this is the case however the **ngOnDestroy** is never invoked.

**Comment by rdnscr** [comment]
Hi gyoshev can you tell me what this means? Was it a Bug and is fixed? Are we doing something wrong?
Thanks for your heads up :)

**Comment by gyoshev** [comment]
@rdnscr oh, sorry -- the issue has been closed through a commit in an internal repo. Upgrade to version `0.18.1` to get hold of the fix. Thank you for reporting it, good catch!
