### ISSUE TITLE
[DropDownTree] Value does not get properly updated programmatically

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3721]
**Describe the bug**
Value does not get properly updated programmatically. The proper value is not displayed when the field associated with the [value] binding is updated programmatically after a selection has already been manually made by the user. 

**To Reproduce**
https://codesandbox.io/s/jovial-glitter-cwq1cg
(updated) - https://stackblitz.com/edit/angular-lljy72?file=src%2Fapp%2Fapp.component.ts

1. Click on Set Value.  Notice that the value of each dropdown is set to the 2nd item (Decor).  This is correct.
2. Change the value of each dropdown to the first item (Furniture).
3. Click on Set Value.  Notice that the value of the first dropdown is set to Decor but the value of the second dropdown still shows Furniture.  This is NOT correct.
4. Click on Clear Value.  Notice that the values of both dropdowns are cleared (correct).
5. Click on Set Value.  Notice that the value of the first dropdown is set to Decor but the value of the second dropdown shows Furniture again.  This is NOT correct.

Ticket ref: 1573325

**Comment by tswetti** [comment]
Also reported in private support thread: 1619550

**Comment by demarchenac** [comment]
Hi, is the Kendo-UI Angular team planning on fixing this issue? 😢

**Comment by tswetti** [comment]
Fixed in [v15.2.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.2.0)
