### ISSUE TITLE
[Filter] Editor template does not get updated on filter type change

### ISSUE THREAD

**Issue by stnikolova** [telerik/kendo-angular#3722]
**Describe the bug**
Editor template does not get updated on filter type change

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/filter/expression-value-template/

1. Open the page - notice that budget has number editor
![download](https://user-images.githubusercontent.com/18744873/180436164-a1f4d6d9-7821-4b86-bced-4e639fb6bcb0.png)

2. Change budget field to Country notice it has a dropdown editor set from template
![download (1)](https://user-images.githubusercontent.com/18744873/180436198-bf4a868c-f480-47bf-9ad2-f520a7b04898.png)

3. Change the field back to budget notice that editor is still the one that was set up for Country field 

![download (2)](https://user-images.githubusercontent.com/18744873/180436206-5d55ee7c-aff7-4b7b-8d3c-81d18407bbf2.png)

Ticket ref: 1573420

**Comment by ipeshev** [comment]
The main issue is fixed but still there are some problems with the demo, like if on select value for second filter field ( country ) an error is thrown in the console and the demo it self is quite noisy in the console, it throws to much warnings ( from our code ) without any interaction from the user.

**Comment by svetq** [comment]
fix available in v2.2.0
