### ISSUE TITLE
Error was thrown when elements are dragged and dropped too fast

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3727]
The following error was thrown, when the items are dragged and dropped too fast:
![image](https://user-images.githubusercontent.com/33104481/182379946-92b02b9d-8b16-4c2d-9ca0-9d58e1f960f1.png)

To reproduce the issue slowdown the CPU performance through the DevTools console and check this example:
https://stackblitz.com/edit/angular-wgxtch?file=src%2Fapp%2Fapp.component.ts

Check the screencast for more details on how to reproduce the issue.

https://user-images.githubusercontent.com/33104481/182383974-62993bca-df20-40b5-be93-c4af03626ef6.mov

**Comment by svetq** [comment]
This is no longer reproducible.
