### ISSUE TITLE
[DropDowns] Group Header Template doesn't apply to the first element inside the list

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3731]
**Describe the bug**
The kendoDropDownListGroupTemplate doesn't apply to the first element inside the popup list. Seems to be related to - https://github.com/telerik/kendo-angular/issues/2529

This also applies to other DropDowns package components that have Group Header Template.

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/templates/#toc-group-header-template

![chrome_zFpqC4MPBY](https://user-images.githubusercontent.com/49076727/183676709-02d2d84f-3cb4-4f18-9e12-46cedf3aef57.png)

**Workaround**
A possible workaround could be to add a dummy object to the first index of the collection and hide it inside the DropDownList:

https://stackblitz.com/edit/angular-n566co?file=src%2Fapp%2Fapp.component.ts

**Comment by aldrashan** [comment]
Can I get a status update on this? I've had to tell several users now that there's nothing we can do to fix the issue on our end when they report this bug to us.

**Comment by dtopuzov** [comment]
Looks ok with v13.4.0 and above.
