### ISSUE TITLE
[DatePicker] Appearance issue

### ISSUE THREAD

**Issue by slewis30328** [telerik/kendo-angular#3732]
Upgraded kendo-angular-dateinputs to 7.1.0 and the days of the week, on the DatePicker, do not expand to align with the days. Values are centered to panel.  Using the Bootstrap theme.  Attached is a snapshot from your doc site that illustrates issue.

![image](https://user-images.githubusercontent.com/5197299/183939477-fe7b7839-3113-4909-9bfa-dada76dc4602.png)

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).
