### ISSUE TITLE
File select with multiple=false allows multiple files to be drag and dropped

### ISSUE THREAD

**Issue by AndrewJohnWalker** [telerik/kendo-angular#3733]
**Describe the bug**
A file select component allows the user to drag and drop multiple files, and will select the final file of the files dropped by the user.

A similar issue was raised and fixed for react, I am unsure if the fix was to simply select the last file, or if this is not fixed in the angular version. https://github.com/telerik/kendo-react/issues/585

**To Reproduce**
Set [multiple]="false" on the file select component, attempt to drag multiple files

https://stackblitz.com/edit/angular-n3dtfi?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Either user cannot drop multiple files, or user is told after dropping multiple files that they can't drop multiple files.

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 
 **Additional context**
 The button on the file select also instructs users to select "files", if multiple="false" I would probably expect this to say file singular.

**Comment by Raisolution** [comment]
Hi @AndrewJohnWalker 

The described behavior is expected from the component - only a single file can be selected at a time, but the user is not restricted to change the selected one. Our Upload component behaves in the same way.

The desired behavior can be implemented by attaching a handler to the [select event](https://www.telerik.com/kendo-angular-ui/components/uploads/api/FileSelectComponent/#toc-select) of the component and prevent any subsequent file selections after a file is already present.
