### ISSUE TITLE
[ColorPicker] ExpressionChanged error is being thrown when associating a Kendo Label

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3736]
**Describe the bug**
Associating the ColorPicker with the Kendo Label component throws an _ExpressionChanged_ error about changing the `attr.for` attribute value:

![image](https://user-images.githubusercontent.com/33104481/184159227-58d6746e-f72f-45f7-b195-daa12bba60ff.png)

**To Reproduce**
https://stackblitz.com/edit/angular-vxht1c

**Comment by dtopalov** [comment]
Fixed in v. 10.1.0 of the **@progress/kendo-angular-inputs** package.
