### ISSUE TITLE
Double click on a tree node opens the Browser menu

### ISSUE THREAD

**Issue by sgampe** [telerik/kendo-angular#3737]
**Describe the bug**
Edge (v 104.0.1293.54): Double clicking on a tree node in the "treeview" component opens the  Browser's context menu ("...")

**To Reproduce**
Double click on any tree node here: https://www.telerik.com/kendo-angular-ui/components/treeview/selection/

**Browser**
 - OS: Windows 10 21H2
 - Browser: Edge 104.0.1293.54

**Comment by svetq** [comment]
The described behavior is a feature of Edge. You can check the following article in order to disable the menu from opening on double click: https://www.reddit.com/r/edge/comments/r6xiwy/doubleclick_three_dots_be_gone/
