### ISSUE TITLE
[DropDowns] popupSettings appendTo 'component' breaks the component functionality making them unusable

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3738]
**Describe the bug**
Affected components list and the behavior when using appendTo 'component':

1.DropDownTree - Upon selection, the popup closes for a short time and reopens.
![chrome_YBybXlF3Kb](https://user-images.githubusercontent.com/49076727/184594097-128c0e48-d644-4ff7-958f-96d32d49698d.gif)

2. MultiSelectTree - Expanding or selecting a checkbox closes the popup.
![chrome_yFiWsHEcPx](https://user-images.githubusercontent.com/49076727/184594287-c2378ec2-55aa-4de7-8f2e-4a5dbe11649e.gif)

3. MultiSelect - Items cannot be selected and the valueChange event isn't fired.
![chrome_Ms0FGBSP6e](https://user-images.githubusercontent.com/49076727/184594522-956d8267-3915-4f9b-86f5-740fa376b25e.gif)

4. DropDownList - The popup doesn't open upon focusing the component.
![chrome_EH13NSuQ7I](https://user-images.githubusercontent.com/49076727/184594662-38fbe94c-04a5-4aca-905f-956b3855adb5.gif)

**To Reproduce**
Open an example from any of the mentioned components and set the popupSettings appendTo property to 'component'.
`[popupSettings]="{appendTo: 'component' }"`

**Comment by dtopuzov** [comment]
The fix is available in @progress/kendo-angular-dropdowns@11.0.0
