### ISSUE TITLE
Grid header line and the row line does not match up when scrollable

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#374]
The grid header line and the row line does not match up when there is a vertical scroll bar in the grid.
However when it is set to [scrollable]="'none'" the line will be aligned. 

[Plunker - Scrollable](http://plnkr.co/edit/FWBywF0J2o74YK2z3iDj?p=preview)
[Plunker - Not Scrollable](http://plnkr.co/edit/LVrIiMJl6u14XDxNcMH1?p=preview)

![grid_header](https://cloud.githubusercontent.com/assets/22805288/23889797/cabf5a6a-08c9-11e7-8904-5d0d52bdd803.jpg)

**Comment by skyfremen** [comment]
Sorry is this related to https://github.com/telerik/kendo-theme-default/issues/284?

**Comment by inikolova** [comment]
This is a known issue, however it has been already addressed. Please check the corresponding issue: 

https://github.com/telerik/kendo-theme-default/issues/285
