### ISSUE TITLE
clash when trying to use jest-prosemirror testing lib

### ISSUE THREAD

**Issue by nadavsinai-philips** [telerik/kendo-angular#3742]
We want to use the very common and very useful `jest-prosemirror` testing library to test plugins we develop
this allows to quickly create editors  and use custom matchers which compare documents etc.

Due to your modified prosemirror-tables package - prosemirror-tables-ts - which is used by `@progres/kendo-angular-editor` inplace of `prosemirror-tables` a fatal error is thrown just by importing your lib and `jest-prosemirror` in the same file 

```
    RangeError: Duplicate use of selection JSON ID cell
```
the reason is that in line 283 of prosemirror-tables there is the following side-effect
```
Selection.jsonID('cell', CellSelection);
```
this modified the state of the (shared) prosemirror-state Selection class which throws when the 2nd call arrives on the same ID

**To Reproduce**
```

import {schema} from @progres/kendo-angular-editor'
import {doc,p,createEditor} from 'jest-prosemirror'


```
(really any code that imports from both libraries)

**Expected behavior**
ability to test with jest-prosemirror as the rest of the community

**Browser**
 - OS: Windows
 - Browser :JSDOM (jest)
 - Version : 27

**Comment by dtopalov** [comment]
This repository is for bug reports only, we will track the demand for this request in our public Feedback portal:

https://feedback.telerik.com/kendo-angular-ui/1582429-editor-please-modify-tables-logic-so-we-can-test-with-jest-prosemirror
