### ISSUE TITLE
Incomplete German, French etc localizations

### ISSUE THREAD

**Issue by mesztam** [telerik/kendo-angular#3744]
When generating i18n xlf localization for an app with e.g. the grid component (7.2.4), and populating it with "npx kendo-translate src/locale/messages.xlf --locale de-DE" the result xlf file is only partially translated. Some texts remain English. E.g.:

```
 <trans-unit id="7607456189720144875" datatype="html">
        <source>Select</source>
        <target>Select</target>
        <context-group purpose="location">
          <context context-type="sourcefile">node_modules/@progress/kendo-angular-dropdowns/fesm2015/kendo-angular-dropdowns.js</context>

```
or

 ```
 <trans-unit id="6176055232586065404" datatype="html">
        <source>Navigate to previous view</source>
        <target>Navigate to previous view</target>
        <context-group purpose="location">
          <context context-type="sourcefile">node_modules/@progress/kendo-angular-dateinputs/fesm2015/kendo-angular-dateinputs.js</context>
```

or

```
  <trans-unit id="8009801217904632250" datatype="html">
        <source><x id="INTERPOLATION" equiv-text="&quot;"/></source>
        <target>Page navigation, page {currentPage} of {totalPages}</target>
        <context-group purpose="location">
          <context context-type="sourcefile">node_modules/@progress/kendo-angular-grid/fesm2015/kendo-angular-grid.js</context>
```

The same applies to French and e.g. Spanish translations.

**Expected behavior**
The translated xlf file should contain the complete translation

**Comment by yanmariomenev** [comment]
Some messages might be missing translation as we provide only the English and Bulgarian translations. The rest of the languages are a community effort to help us translate the messages of our components into different languages. Feel free to open a pull request if you decided to translate some of the messages into a different language.
