### ISSUE TITLE
Incorrect behavior when resizing nested tables

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3747]
**Describe the bug**
### Case 1
Resizing nested cell tables width prevents them from auto-resize when the parent cell width is reduced. This breaks the layout:
![image](https://user-images.githubusercontent.com/33104481/186613774-a855ff1c-844d-46b0-83ed-8b15a20ca3a6.png)

### Case 2

Having a single parent cell and displaying a table inside it. Resizing the inner table width and then the its parent cell, produces this layout:

![image](https://user-images.githubusercontent.com/33104481/186617611-c0253ee4-a8f0-4296-b73f-f56743d2be8a.png)

Attaching screencast of how to reproduce the issues:
[editor-table-resize.mov.zip](https://github.com/telerik/kendo-angular/files/9423033/editor-table-resize.mov.zip)

**To Reproduce**
https://stackblitz.com/edit/angular-lzhcb8

**Comment by mbechev** [comment]
### Case 1
Expected behavior with the current built-in ProseMirror styles. A possible solution is to set `table-layout:auto` on the `<table>` elements:

https://stackblitz.com/edit/angular-lc1a7z-kvtt4c

We are still considering our options to provide a built-in solution to this scenario.

### Case 2

Fixed in `v4.1.11` of the Editor.

**Comment by dtopalov** [comment]
After discussing the case internally, we decided that we will not be changing the default internal tables layout. Applying the styling, suggested in the workaround, linked above, is in the hands of the developer - they can either customize the Editor value accordingly, or set the Editor internal styling of their preference (such option is already available for non-iframe mode, and is soon coming as a built-in feature for the default iframe mode too).
