### ISSUE TITLE
Setting width in kendo-grid-column doesn't work for angular 2.2.1

### ISSUE THREAD

**Issue by BartoszBaczek** [telerik/kendo-angular#375]
How to reproduce:

In example below you can see, that width parameter for kendo-grid-column doesn' t work (it always makes column 100% width). If you change it back to newest angular version (2.4.8), everything seems ok.

http://plnkr.co/edit/VhhH1eOFYB5B5V5l0mCL?p=preview

I realize that is not exactly your issue, but I am looking for last version of kendo-angluar that was compatible with angular 2.2.1. Your changelog doesn't mention suiting angular version, so I could temporary (until we upgrade our angular version) go back to older kendo-angular.

http://www.telerik.com/kendo-angular-ui/components/grid/changelog/

**Comment by tsvetomir** [comment]
The reason for the breaking change is the new component metadata version in Angular 2.4. See #175 

Try version 0.10, it should work with Angular 2.2

> ## 0.11.0 (2017-01-10)
> ### Features
> * upgrade to angular 2.4

**Comment by BartoszBaczek** [comment]
Yup, works great, thank you very much.
