### ISSUE TITLE
Inconsistent behavior when resizing Splitter panes without set size

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3752]
**Describe the bug**
The **flex-basis** CSS property is added dynamically on different panes, depending on which resize bar is dragged first. This causes inconsistent behavior in how the panes are resized.

**To Reproduce**
Here is the demo
https://stackblitz.com/edit/angular-jb1nxb-r1bxrn

Case 1:
1. Drag the first resize bar (between the left and middle pane).
2. The left and middle pane are resized accordingly while the right pane is slightly changed, but shouldn't.
3. Drag the second resize bar between the middle and right pane. 
4. Notice how the panes are individually resized now, which looks like correct and expected behavior. 

Case 2:
1. Drag the second resize bar first (between the middle and right pane).
2. All panes are resized oddly nevertheless of the dragged resize bar.

**Expected behavior**
When there is no set size, the panes should be resized individually. There should be no effect on the other panes which are not next to each other with the resized pane.

The workaround is to set the **size** property to the panes.

> The same behavior is reproduced with the KendoReact Splitter: https://stackblitz.com/edit/react-chycfv

**Comment by slavenai** [comment]
Fixed in `v16.4.0` of `kendo-angular-layout` package.
