### ISSUE TITLE
Update of "class" of ComboBox when is not necessary could decrease the performance?

### ISSUE THREAD

**Issue by qina83** [telerik/kendo-angular#376]
in this example http://plnkr.co/edit/G6O4Vnww1BE085gSLCX7?p=preview
- select a item of combobox
- click the button

If you check the debug tool of Chrome you can see that after every click the class="k-dropdown-wrap k-state-default" of span inside kendo-combobox is refreshed.

Could this decrease the performance? why is it refreshed?

**Comment by KirilNN** [comment]
Thanks for noticing. This can be addressed, so stay tuned :)
