### ISSUE TITLE
[Editor] First rendering does not apply overflow correctly

### ISSUE THREAD

**Issue by Jahrenski** [telerik/kendo-angular#3760]
**Describe the bug**
The first rendering of the tool does not apply the toolbar overflow properly until the window is resized.
It makes the overflow 3 vertical dots overlap with the last toolbar item.

**To Reproduce**
[https://stackblitz.com/edit/angular-b9qipy?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-b9qipy?file=src/app/app.component.ts)

**Screenshots**
Before resize
![image](https://user-images.githubusercontent.com/3932920/187950154-147120db-f175-4f10-9eab-6e99a4b90f89.png)
After resize
![image](https://user-images.githubusercontent.com/3932920/187950805-edc0b103-8054-4da0-bdb7-7464ecdc0faf.png)

**Comment by hetalishah** [comment]
The overflow issue can also be seen in the ToolBar component: [StackBlitz example](https://stackblitz.com/edit/angular-knafb7-h3acfb?file=src/app/app.component.ts)

**Comment by yanmariomenev** [comment]
I will also add in newer versions that the behavior doesn't render the overflow button and hides part of the tools UI:

https://user-images.githubusercontent.com/49076727/230016038-c533d9db-cba2-40b9-9741-e994bc7ec08f.mp4

As the behavior was updated a few times the initial description might not be valid anymore, but the overflow behavior is still wrong.

https://stackblitz.com/edit/angular-x7qhgr?file=src%2Fapp%2Fapp.component.ts

**Comment by slavenai** [comment]
Fix available in `v15.2.0` of `@progress/kendo-angular-editor` package.
