### ISSUE TITLE
[DatePicker] Days of week are not aligned inside the calendar

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-angular#3763]
## I'm submitting a...
* Bug report

## Current behavior
Days of week are not aligned inside the calendar. This could be related to styles not properly applied:

![Untitled](https://user-images.githubusercontent.com/2890242/188424325-54fe527d-19a1-4656-976a-6fbb9a816f0a.png)

## Minimal reproduction of the problem with instructions
The bug can be observed in the DatePicker demos, for example: https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/

## Environment

Package versions:
v7.1.0

Browser:
- Chrome (desktop) version 103.0.5060.114 (Official Build) (64-bit)
- Firefox version 104.0.1 (64-bit
- Edge version 105.0.1343.27 (Official build) (64-bit)

System:
- Platform: Windows

**Comment by PaskalevStoyan** [comment]
This bug is fixed and is live in the dev version of the Date Inputs Package. The issue will be closed when a stable version is released.

**Comment by Raisolution** [comment]
Fixed in `v7.1.1` of the DateInputs package.
