### ISSUE TITLE
[KendoGrid] Is ColumnMenuService a public API?

### ISSUE THREAD

**Issue by gy-soft** [telerik/kendo-angular#3765]
I am upgrading my code base to the latest kendo version. We have some components and directives to add custom functionality to the column menu. This code depends on the ColumnMenuService that used to be available at progess/kendo-angular-grid. After upgrading from version 6.1.3 to 7.2.4 the imports broke and now I have to use the full path.
`
import { ColumnMenuService } from '@progress/kendo-angular-grid/column-menu/column-menu.service'
`
Should I stop using this class?

**If the issue is specific to your project, please open a [support ticket](https://www.telerik.com/account/support-tickets).**

**Comment by dtopalov** [comment]
Hello @gy-soft,

The [ColumnMenuService](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnMenuService/) is indeed a part of the public API of the Grid package, and we will do our best to export it in the next patch version.

**Comment by PaskalevStoyan** [comment]
The `columnMenuService` is released in the latest `v7.3.2` version of the Grid
