### ISSUE TITLE
MultiSelectTree:  itemDisabled callback blocks access to parent component's data

### ISSUE THREAD

**Issue by theremon** [telerik/kendo-angular#3766]
Within the function that is set for the itemDisabled callback, the scope is changed to the TreeViewGroupComponent, blocking any access to the main component's variables. Any calls to 'this' have only access to the TreeViewGroupComponent's properties and events.
This blocks the developer from setting the disabled property dynamically based on other data from the form.

**To Reproduce**
Try accessing 'this' from within the callback.

StackBlitz example:
https://stackblitz.com/edit/angular-7wfhla
In this very simple example, trying to console.log the 'abc' variable, returns 'undefined'

**Expected behavior**
The developer should be able to access data from the parent component.

**Comment by svetq** [comment]
That is the default behavior of JavaScript indeed. You can use an [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) or the generic [bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) function to keep or modify the context of a specific function. Here is an example using an arrow function: 

```
  public itemDisabled = (dataItem: any, index: string) => {
    console.log(this.abc);
    return dataItem.id === 5; // disable the 2nd root item
  }
```
