### ISSUE TITLE
[DateInputs] Calendar popup navigation bug

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3769]
**Describe the bug**
There is a specific invisible vertical line inside the calendar popup of the DateInputs which uses the navigator and when clicking on the line it triggers the navigator to scroll the months. If the line falls over a specific date of the week it prevents it from being selected.
This is also valid for the month/year view.

This issue seems to be related to the latest version of Chrome as Firefox doesn't have the issue.

![chrome_n8VS4JrSSw](https://user-images.githubusercontent.com/49076727/189636040-9721b0e7-bbe2-477f-846c-9f35966da738.gif)

**To Reproduce**
Open the following demo:
https://stackblitz.com/edit/angular-putshj?file=src%2Fapp%2Fapp.component.ts
Or any DateInputs demo that utilizes the calendar plus the navigator.

**Comment by joshlupo** [comment]
Just to add a bit.  This problem is worse when the line falls directly over the center of dates, and it does that in certain themes.
![calendar-clicking](https://user-images.githubusercontent.com/93222645/190442528-31e7129e-dd51-4b0d-b39c-a4d12791e863.gif)

**Comment by tbaldwinups** [comment]
It does seem like the browser has changed how CSS is being applied since it worked in a previous version of Chrome.

**Comment by EZman1** [comment]
Are there any work arounds for now? We found this one in our regression testing.

**Comment by matthewmacbeth01** [comment]
We found disabling fastNavigation or setting the calendarType to "classic" both resolved it, if you can afford to loose the fast navigation functionality of course.

**Comment by JoomFX** [comment]
It seems that the latest Chrome version does not handle elements with `overflow: hidden;` properly.
What currently happens is that Chrome thinks that the user clicks on the scrollbar of the `.k-calendar-navigation` element... scrollbar that shouldn't be accessible at all as it is a hidden element:

![calendar-bug](https://user-images.githubusercontent.com/7753940/191045578-929e607e-1b52-4b31-b563-bd02e0121f16.png)

A temporary workaround (until we fix it officially in our Kendo Themes) is to use the following CSS code (can be seen in action in [this Stackblitz example](https://stackblitz.com/edit/angular-czat7p?file=src%2Fapp%2Fapp.component.ts)):

```
.k-calendar-navigation {
    z-index: 1;
}
```

**Comment by JoomFX** [comment]
The issue is [fixed in Kendo Themes](https://github.com/telerik/kendo-themes/pull/3980).

**Comment by destus90** [comment]
@JoomFX

how long until npm release?

**Comment by JoomFX** [comment]
The fix is already available in the [dev version](https://www.npmjs.com/package/@progress/kendo-theme-default/v/5.8.2-dev.2).
The next official version will be released on 17th of October.

**Comment by yanmariomenev** [comment]
Fix is available in Kendo Theme version 5.9.0 - https://github.com/telerik/kendo-themes/releases/tag/v5.9.0
