### ISSUE TITLE
Modify chart title on export

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#377]
Is it possible to modify the chart before exporting as an image?

For instance, I want to modify (or add) a title to the chart on export only.

Something like this:

```
exportChart(): void {
  this.chart.title = 'New title on export';

  this.chart.exportImage({
    width: 1440
  }).then((dataURI) => {
    saveAs(dataURI, 'chart.png');
  });
}
```

**Comment by danielkaradachki** [comment]
You need to wait for the change to take effect in order to change the title in the exported image:
http://plnkr.co/edit/RQl2BYcSf3bgejAWK68N?p=preview

**Comment by SeriousLemon** [comment]
@danielkaradachki didn't realise there was a render function on the chart -- good to know, thanks.

**Comment by danielkaradachki** [comment]
The latest version includes support for specifying options for the exported chart so overriding the title can also be achieved as in the following example:
http://plnkr.co/edit/MVCsLCIKkZ5LDSXnpEAO?p=preview
