### ISSUE TITLE
[MultiSelectTree] Loading data after component rendering causes issue with removing the selected item/items

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3770]
**Describe the bug**
Loading data after the component initialization causes an issue when trying to remove the selected items using both directives. this behavior can be observed visually in the following recording:

![chrome_hugC8Aw7U4](https://user-images.githubusercontent.com/49076727/190148791-38b251d5-481e-4da1-9849-6a0ae56c32ed.gif)

If the data is loaded asynchronously the issue would also appear.

**To Reproduce**
Open the following example and load the data from the button click:
https://stackblitz.com/edit/angular-7dngzy?file=src%2Fapp%2Fapp.component.ts

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Release with **v7.2.2** of `@progress/kendo-angular-dropdowns`.
