### ISSUE TITLE
White space displayed in virtual scroll unlocked content section on every page change event

### ISSUE THREAD

**Issue by notetosiraj** [telerik/kendo-angular#3772]
**Describe the bug**
Kendo Grid with virtual scroll displayed white space in every page change event when scroll over unlocked content section and same time locked section get freeze.
while scroll in locked section no such issue freeze or white space issue .

**To Reproduce**
place a mouse pointer anywhere in unlocked content section and scroll down. notice when it try to fetch data ,it display white space.

reproduceable url :
https://stackblitz.com/edit/angular-qtyeaz-5pm4ad?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
when scroll in unlocked content screen ,it should not display white space.

**Screenshots**
![image](https://user-images.githubusercontent.com/51027104/190603242-ef043aad-7c99-4d7c-9b93-bb18cc13d97b.png)

**Browser**
 - OS: Win 10
 - Browser [Chrome]
 - Version [Version 105.0.5195.102
<img width="546" alt="whiteissuefix" src="https://user-images.githubusercontent.com/51027104/190603770-ddaf0943-b17e-4e05-b3e0-ddf91bcb30bd.PNG">
]

**Comment by slavenai** [comment]
The observed issue seems related to both incomplete Grid configuration and specifics of the used remote service (similar to https://github.com/telerik/kendo-angular/issues/3773). The set rowHeight is off by 1px, the pageSize exceeds the actual number of records returned by the remote service and the Grid `loading` input is not set. Here is the [updated demo](https://stackblitz.com/edit/angular-xysjuu-fkbkrr?file=src%2Fapp%2Fapp.component.ts).
