### ISSUE TITLE
[MultiSelect] `Ctrl + A`(pc) and `cmd + a`(mac) navigation doesn't work properly

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3774]
**Describe the bug**
`Ctrl + A` - The component selects all the items when it is out of focus. For example, if there is another input element on the page and you would like to select all of the text using ctrl+a, then all of the text isn't being selected and the MultiSelect takes the event and selects all of its items which is incorrect behavior. This should only happen when the component is focused and the popup opened.

![chrome_W7Ivv1PEGr](https://user-images.githubusercontent.com/49076727/190970299-b85587b8-b996-4ff1-bb28-6c5e370875dc.gif)

`cmd + a` - The selection of all items doesn't work.

**To Reproduce**
Focus on the input element and press ctrl + a on the following demo:
https://stackblitz.com/edit/kendo-angular-multi-select-keyboard-nav-issue-s4gmfu?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Not to select all items when the focus is on another element.

**Comment by svetq** [comment]
fix available in the latest dev version [7.2.1-dev.202209201351](https://www.npmjs.com/package/@progress/kendo-angular-dropdowns/v/7.2.1-dev.202209201351)

**Comment by stnikolova** [comment]
The fix is available in **v7.2.1** of @progress/kendo-angular-dropdowns
