### ISSUE TITLE
[MultiSelectTree] Sorting tags with tagMapper breaks the selection

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3776]
**Describe the bug**
Sorting the selected tags using the **tagMapper** callback breaks the selection. Removing a selected parent tag through its close icon ('X') doesn't remove all corresponding children tags from the input.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/33104481/191003442-c10b9893-a3f9-418d-9aec-e82abdea989f.gif)

**To Reproduce**
1. Select all children.
2. Deselect the Furniture node through the tag remove icon.
3. Some of the children nodes are still selected.
https://stackblitz.com/edit/angular-xfo2qr

Example with data binding: https://stackblitz.com/edit/angular-xfo2qr-ru1nko

One more example: https://stackblitz.com/edit/angular-riqed4-gizup3

[The demo ](https://www.telerik.com/kendo-angular-ui-develop/components/dropdowns/multiselecttree/summary-tag-mode/#toc-displaying-the-selected-tags-in-alphabetical-order) was also available in the docs.

**Comment by yanmariomenev** [comment]
Adding one more scenario with an example. The wrong child item is removed when the parent is hidden with tagMapper.

https://stackblitz.com/edit/angular-riqed4?file=src%2Fapp%2Fapp.component.ts

![chrome_2WFQIYcdAZ](https://user-images.githubusercontent.com/49076727/207807280-5e9b8ab3-d755-400f-87d1-e31400c93b74.gif)

**Comment by svetq** [comment]
Fixed in v 14.0.0
