### ISSUE TITLE
[Scheduler] MonthView events text not displayed when using the fluent theme

### ISSUE THREAD

**Issue by PaskalevStoyan** [telerik/kendo-angular#3780]
**Describe the bug**
Switching to Fluent Theme, the text of the events when looking the Scheduler in month view is not displayed.

**To Reproduce**
1. Go to: https://www.telerik.com/kendo-angular-ui/components/scheduler/
2. Switch to Fluent theme
3. Switch to Month View
4. Observe the missing text in the events

**Expected behavior**
The text in the events in Month View when using the Fluent theme should be visible

**Comment by PaskalevStoyan** [comment]
The fix is available in the `develop` version of the package.

**Comment by dtopalov** [comment]
Fixed in v. 4.3.4 of **@progress/kendo-angular-scheduler**.
