### ISSUE TITLE
Change label -> 'Select font size' in kendoEditorFontSize 

### ISSUE THREAD

**Issue by NikicaAsanin** [telerik/kendo-angular#3782]
I am trying to change label value in Kedno Editor. 
Example: 
```
<kendo-toolbar-dropdownlist
        kendoEditorFontSize
        [data]="valueText"
        (valueChange)="textChange()"
      ></kendo-toolbar-dropdownlist>
```

Is there anyway I can change "Select font size" text to something custom?
![image](https://user-images.githubusercontent.com/5645255/191706524-c25226ab-4951-4dc9-98d8-fc6f857de6e5.png)

**Comment by PaskalevStoyan** [comment]
Hi @NikicaAsanin 
This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios or configuration.
