### ISSUE TITLE
Enabling a disabled DropDownList in a FormField throws ExpressionChange error

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3783]
**Describe the bug**
When a disabled DropDownList is used within a FormField, enabling it programmatically throws an `ExpressionChanged` error:

![chrome_mQktgWWgic](https://user-images.githubusercontent.com/49076727/191764909-b5124e65-4932-4c35-bc8c-63431f40799e.png)

It seems that this issue is present in recent versions of the DropDowns package `7.2.0` and only when FormField is being used.

**To Reproduce**
Click on the enable button.
https://stackblitz.com/edit/angular-an1gge-u3i4da

**Comment by michaelmarcuccio** [comment]
I want to point out this is specifically an issue with the dropdownlist component as it doesn't seem to affect other kendo components. 

Workaround:
`this.claimForm.enable();
this.cdr.markForCheck();
`

**Comment by michaelmarcuccio** [comment]
This problem is specifically caused by the following: `<kendo-formfield>`

**Comment by Raisolution** [comment]
Fixed in `v16.11.0`
