### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'kendo')

### ISSUE THREAD

**Issue by jogoertzen-stantec** [telerik/kendo-angular#3786]
**Describe the bug**

The error in the title is logged in the browser console and the application does not load when `@progress/kendo-ui` version `2022.3.913` is listed as a dependency in package.json.

The error does not occur after downgrading `@progress/kendo-ui` to `2022.2.802`.

**To Reproduce**

1. Follow the steps [here](https://github.com/telerik/kendo-angular/tree/master/examples/projects/integration-jquery), but set `@progress/kendo-ui` to version `2022.3.913` before running `npm install`.
2. Browse to `http://localhost:4200` in Chrome
3. Open dev tools and observe the error

**Expected behavior**

I expect the application to load without errors.

**Browser**
 - OS: Windows 10
 - Browser: Chrome 105.0.5195.127 (Official Build) (64-bit)

**Comment by mbechev** [comment]
Hi @jogoertzen-stantec,

It looks like the latest release of the Kendo jQuery suite experience some trouble loading it in the _app.module_ file:
https://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/#toc-setting-up-the-project
We will update our documentation and README.md file to announce that.

As an alternative approach add the package file to the `scripts` array of the _angular.json_ file, like:
https://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/#toc-adding-downloaded-custom-package-files-and-jquery

**Comment by jogoertzen-stantec** [comment]
Thanks, @mbechev. That worked great!

I went with the custom package option, so does that mean I no longer require the `@progress/kendo-ui` dependency in my `package.json`?

**Comment by yanmariomenev** [comment]
Hi @jogoertzen-stantec ,

This is related to the following issue - https://github.com/telerik/kendo-ui-core/issues/7012. This will be fixed in the next jQuery version. What else can be done is to use Webpack v5 in the application which will avoid the mentioned error. Please subscribe to the mentioned issue for further updates on this matter.
