### ISSUE TITLE
[Ripple] Ripple UI breaks with kendoRadioButton

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3787]
**Describe the bug**
The Ripple UI breaks when a [kendoRadioButton ](https://www.telerik.com/kendo-angular-ui/components/inputs/radiobutton/)button is used inside the container.

![chrome_e4cwf3ra4M](https://user-images.githubusercontent.com/49076727/192208037-cdf0a094-5a6f-465c-a091-627fce07e3fd.gif)

**To Reproduce**

This can be reproduced in the following demo from our website:
https://www.telerik.com/kendo-angular-ui/components/ripple/

**Comment by siyka-marinova** [comment]
Same as https://github.com/telerik/k2/issues/839

**Comment by Raisolution** [comment]
Fixed in the latest Themes version `5.9.0`
