### ISSUE TITLE
[MultiSelectTree] Value binding doesn't work properly

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3789]
**Describe the bug**
Value binding the component doesn't work properly as it doesn't reflect the selection and items can be selected two times:
![chrome_WmKqYV1UTs](https://user-images.githubusercontent.com/49076727/192263032-92197794-145b-45b2-9580-3cfa49478ab9.gif) 

**To Reproduce**
This can be observed in the following two demos:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselecttree/value-binding/#toc-primitive-values
https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselecttree/value-binding/#toc-heterogenous-data-type

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by stnikolova** [comment]
Release with **v7.2.2** of `@progress/kendo-angular-dropdowns`.
