### ISSUE TITLE
Kendo External Filter 2.2.2 . A Couple of Hidden (and funny) Bugs

### ISSUE THREAD

**Issue by cvivasf** [telerik/kendo-angular#3798]
Active Bugs On version 2.2.2 and previous.

I'm submitting 2 bug reports. These couple of bugs are (imo) really easy to solve and they are really game-breaking.

BUG 1:

For Numeric operators inside a filter on the Kendo External Filter Component:

 (LESS THAN OPERATOR) The lt operator has "Less or equal than" text in Kendo External Filter Component HTML UI
 (LESS THAN OR EQUAL) The lte operator has "Less than" text in Kendo External Filter Component HTML UI

WORKAROUND FIX: On your backend logic just change "less than" logic to "less or equal than" and viceversa.

BUG 2:

The FilterExpression interface has a funny bug. The "startswith" operator is wrongly typed to "startswidth". That causes to be impossible to use a custom FilterExpression object with a startswith operator because the typescript compiler launches a typing problem.

WORKAROUND FIX: Use Interface "any" instead of FilterExpression[] for your array of filters that you are sending to the kendo-filter component.

Cya

**Comment by svetq** [comment]
@cvivasf I am unable to reproduce the first reported issue. The `lt` and `lte` operators have the proper texts as demonstrated in the following example: https://www.telerik.com/kendo-angular-ui/components/filter/

**Comment by ipeshev** [comment]
Fix available in [latest dev version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by cvivasf** [comment]
> 
True, it was my mistake. I was incorreclty translating the shown text on the HTML from my JSON files using the directive filterLteOperator. My apologies.
Thanks for the fix on the second one, guys :)
