### ISSUE TITLE
Grid will be server-side Filterable at release?

### ISSUE THREAD

**Issue by aceptra** [telerik/kendo-angular#380]
We're highly dependent on the Filterable feature for other Telerik grid products?

Will this be supported?

**Comment by rkonstantinov** [comment]
As the Grid component itself does not execute any data processing, but this is in the hands of the developer, service-side filtering is possible. This is also true for paging, sorting, grouping etc.

If you are asking if Grid component will provide filtering UI. The answer is yes - we are currently working on filter row implementation.
