### ISSUE TITLE
[TreeList] selectionChange sometimes throws the wrong action when using multiple selection option

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3804]
**Describe the bug**
The selectionChange event sometimes throws `selected` action when using multiple selection with `ctrl + left mouse click`. This behavior breaks one of our examples of persisting the selection as it checks the actions before executing the selection logic.

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-jknask?file=src%2Fapp%2Fapp.component.ts
2.  Hold `ctrl` and start selecting items. At some point the selection action will be thrown even if its in multiple selection mode and clear the selection.

**Workaround**
The following workaround checks if the `ctrl` key is held on repeat by the user and the clearSelection condition will consider that to improve the behavior. The workaround isn't fully tested.
https://stackblitz.com/edit/angular-oaxvxm?file=src%2Fapp%2Fapp.component.ts

**Screen Recording**
![chrome_EdbDRH6dBe](https://user-images.githubusercontent.com/49076727/195531316-a8372a21-e0c4-4f0c-8a6c-d30ab0b992d4.gif)
![chrome_KGYB9UM1pc](https://user-images.githubusercontent.com/49076727/195531504-c90985a5-b2b0-49d0-8528-4626a6204329.gif)

**Comment by slavenai** [comment]
Fixed in `v16.11.0`
