### ISSUE TITLE
[DropDownList] Loading indicator renders inside a button which changes the component height

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3809]
**Describe the bug**
The loading indicator is rendering inside a button, which causes change in the component height:

![chrome_y1u5vGjMgZ](https://user-images.githubusercontent.com/49076727/195806406-6d128a92-e34f-46b2-9b36-69573e9ed47e.gif)

The indicator should be rendered only in a span element with the specific height and width as in Kendo UI for Vue ([example](https://stackblitz.com/edit/6xmsnw?file=src%2Fmain.vue,src%2Fmain.js)). Please check the screenshots applied to the issue.

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-syyhcd?file=src%2Fapp%2Fapp.component.ts
2.  Enable and Disable the loading to see the differences in height.

**Expected behavior**

**Screenshots**
Kendo UI for Angular:
![chrome_xXBTxXa2br](https://user-images.githubusercontent.com/49076727/195806462-5512ad3d-7b27-4e5a-86db-40a58c9ac6f9.png)

Kendo UI for Vue:
![chrome_6aEC2sHP2p](https://user-images.githubusercontent.com/49076727/195806698-c39ca2e3-d546-417d-b5f6-9d2c9c867162.png)

**Comment by michaelmarcuccio** [comment]
it has been some time.. is this on the radar at all?

**Comment by svetq** [comment]
Fixed in v 14.0.0
