### ISSUE TITLE
Angular 2 with KENDO UI not work unit test

### ISSUE THREAD

**Issue by Chili82** [telerik/kendo-angular#381]
Hi, when i run angular 2 command for unit test (ng test) i get error:
Can't bind to 'data' since it isn't a known property of 'kendo-grid'.
1. If 'kendo-grid' is an Angular component and it has 'data' input, then verify that it is part of this module.
2. If 'kendo-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
Please answer?

**Comment by KirilNN** [comment]
Maybe it is something similar to https://github.com/telerik/kendo-angular/issues/378

**Comment by Chili82** [comment]
Thank you very much, this is solve my problem.
