### ISSUE TITLE
Custom Icon click event not working in kendoPanelBarItemTitle

### ISSUE THREAD

**Issue by GaneshSingaravelu** [telerik/kendo-angular#3811]
**Describe the bug**
I am creating a custom panel title bar. I have a custom button with SVG in the title panel. When I clicked the button, the default collapse action event fired and the actual button did not fire. 

I want the collapse and expand icon next to the title, not the rightmost of the panel. Please do the needful

**To Reproduce**
https://stackblitz.com/edit/angular-iqzjd2-9w9gq4?file=app%2Fapp.component.ts

**Expected behavior**
1) I don't want to collapse the panel when I click the SVG button, and the SVG button function should be executed. 
2) I want the collapse and expand icon next to the title, not the rightmost of the panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/26732057/196105805-0efac2ca-12ce-4967-b7fa-9384e27f5c24.png)

**Browser**
 - OS: [windows 10]
 - Browser [Chrome]

**Comment by Raisolution** [comment]
Hi @GaneshSingaravelu

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios or configuration.
