### ISSUE TITLE
Need to Close the Kendo Splitter pane if it reached specified width

### ISSUE THREAD

**Issue by GaneshSingaravelu** [telerik/kendo-angular#3813]
**Describe the bug**
I want to close the left/right splitter bar pane if it reaches a specified width. Hereby, I have attached a sample code for the same. Even though the condition is matched, it is affected on screen.

**_Note: It is working if I drag the splitter bar very slowly, not when I drag it at normal speed._**

**To Reproduce**
https://stackblitz.com/edit/angular-kendo-splitter-bmjmb5?file=app%2Fapp.component.ts

**Expected behavior**
I want to close the left/right splitter bar pane if it reaches a specified width.

**Screenshots**

**Browser**
 - OS: [Windows 10]
 - Browser [ Chrome ]

**Additional context**

**Comment by Raisolution** [comment]
Hi @GaneshSingaravelu

This repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios or configuration.
