### ISSUE TITLE
[DropDownList] The value doesn't update when updating the FormGroup on blur

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3814]
**Describe the bug**
When using a form group that is set up to update on blur, the DropDownList doesn't update the FormControl value even though the UI shows a different value.

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-d1cd7b-atdxrj?file=src%2Fapp%2Fapp.component.ts

**Workaround**
Handle the (blur) event of the DropDownList:
https://stackblitz.com/edit/angular-d1cd7b-m1kpak?file=src%2Fapp%2Fapp.component.ts

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
