### ISSUE TITLE
Kendo Combobox Need two-time tab "Tab" button to move next control focus.

### ISSUE THREAD

**Issue by mahendraharode** [telerik/kendo-angular#3815]
**Describe the bug**
Move to Next control focus from combobox need to tab Tab button twice.

**To Reproduce**
When focus is on a combobox, users should only have to tap Tab once to move to the next field but need to tab Tab twice 

When focus is on a field next to a combobox, users should only have to tap Shift + Tab once to bring focus onto the combobox and be able to type but in this case also need to tab Shift + Tab twice

        <mat-label class="lbl_text">
          <mat-error class="errorleft">
            <span class="required">*</span>
          </mat-error>
          Type
        </mat-label>
        <kendo-combobox class="kendo-combobox" [ngClass]="{'inactive-color' : custColor}"
         #comboboxComponent [openOnKendoFocus]="comboboxComponent"
          formControlName="CustType" [data]="custTypes" textField="Description" valueField="CustTypeID"
          [suggest]="true" [valuePrimitive]="true" [allowCustom]="false" (selectionChange)="onCusttypechange($event)">
          <ng-template kendoComboBoxItemTemplate let-dataItem>
            <span class="template_lbl" [ngClass]="{'inactive-color' : dataItem.QInactive}">
              {{ dataItem.Description }}</span>
          </ng-template>
        </kendo-combobox>
      </div>
      <div class="form_group">
        <mat-label class="lbl_text">
          <mat-error class="errorleft">
            <span class="required">*</span>
          </mat-error> Name
        </mat-label>
        <mat-form-field class="mat-full-width" color="primary" appearance="outline">
          <input matInput placeholder="" value="" formControlName="Name" (focusout)="onNameFocusOut()">
        </mat-form-field>
      </div>
-->

**Expected behavior**
In Singe click focus should be move to Name input control.

**Screenshots**
![image](https://user-images.githubusercontent.com/115992217/196163484-82fee2b4-1440-4835-9147-24ed0106e079.png)

**Browser**
 - Microsoft Edge
 - Chrome

**Comment by Raisolution** [comment]
Hi @mahendraharode 

I was unable to reproduce the described behaviour locally or in our [documentation examples](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/). Please provide a runnable example and details about the exact dropdowns version being used, so we could determine if this is a bug.

Thank you
