### ISSUE TITLE
The "Select files" button of the Upload shows "No file chosen" even if files are selected

### ISSUE THREAD

**Issue by HeyImKyu** [telerik/kendo-angular#3817]
Same issue as https://github.com/telerik/kendo-react/issues/1124.

## I'm submitting a...

* Bug report 

## Current behavior

Hovering over the "Select files" button shows "No file chosen" tooltip even if files are selected.

## Expected behavior

Tooltip does not show "No file chosen" if a file is selected.

## Minimal reproduction of the problem with instructions

1. Implement a frontend with a "kendo-fileselect"-Component
2. Select a file 
3. Hover above the "Select files"-Button

## Environment

Can be recreated on https://www.telerik.com/kendo-angular-ui/components/uploads/fileselect/

Browser:

- Brave version 1.44.112

**Comment by Raisolution** [comment]
Fixed in latest version of the package
https://www.telerik.com/kendo-angular-ui/components/uploads/fileselect/
