### ISSUE TITLE
Kendo Switch Animation

### ISSUE THREAD

**Issue by iqmeta** [telerik/kendo-angular#382]
Switch Animation only works on click.
But not when changed model.

![switch](https://cloud.githubusercontent.com/assets/7533842/23939284/43bc6692-0960-11e7-96bb-b01b6f88b461.gif)

**Comment by KirilNN** [comment]
This behavior is expected, as programmatically setting the value is not user interaction and animation is not expected. The same is valid for the initial value - animation is not expected for the initial value setting.

**Comment by iqmeta** [comment]
As you see in the animated gif, it's an change of the observable, not an init on first load.

If you have connected/dependent elements, you should at least be able to 
apply animation with configuration of the component when to use and when not 
for a better UX.
