### ISSUE TITLE
[Avatar] imageSrc doesn't work with Blob URL 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3827]
**Describe the bug**
The rendering updates of the Avatar unintentionally prevent using Blob URLs as images. 
More details can be found in a private support ticket **1582137**

**Comment by PaskalevStoyan** [comment]
To be tracked in the Feedback Portal - [link](https://feedback.telerik.com/kendo-angular-ui/1609394-avatar-imagesrc-doesn-t-work-with-blob-urls)
