### ISSUE TITLE
[DateInput] FormatSettings interface does not allow all possible types

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-angular#3828]
**Describe the bug**
The FormatSettings interface limits the `displayFormat` and `inputFormat` properties to being a `string` while the following is also a valid scenario:

```js
public format: FormatSettings = {
    displayFormat: { date: 'short' },
    inputFormat: { date: 'long' },
}
```

**To Reproduce**
The issue and the workaround can be seen in [this Stackblitz example](https://stackblitz.com/edit/angular-m2wtdi-aumd3b?file=src/app/app.component.ts).

**Expected behavior**
The FormatSettings interface should allow for all possible scenarios.

**Screenshots**
N/A

**Browser**
N/A

**Additional context**
Related to ticket 1584354

**Comment by stnikolova** [comment]
The fix is available in **v14.2.0** of `@progress/kendo-angular-dateinputs`
