### ISSUE TITLE
Setting locked property to undefined breaks the auto-size functionality

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3829]
**Describe the bug**
Setting the **locked** property of a column to `undefined` breaks the auto-size functionality, by setting the column width to 0.

**To Reproduce**
Auto-size the ID column (by clicking the column splitter) and notice how the Product Name column width will be set to 0:
https://stackblitz.com/edit/angular-vaa48y

**Comment by Raisolution** [comment]
There is no need for the `locked` property to be set as `undefined`. We recommend setting as `true` or `false` instead.
