### ISSUE TITLE
Setting width to dynamically generated column in grid doesn't work

### ISSUE THREAD

**Issue by BartoszBaczek** [telerik/kendo-angular#383]
Hi, I am trying to dynamically generate grid, with columns names and cells based on input data. It works fine, but at the same time, makes it impossible to set [width] parameter to column. Is there any workaround for this?

Plunker ilustrating problem:
http://plnkr.co/edit/QjTt0arvuvOvnhG9wgKh?p=preview

**Comment by rkonstantinov** [comment]
There is no columns field defined in the sample. Thus, the columns are autogenerated by the Grid as the ngFor does not render any column components. You should try defining the `columns` field to be a non-empty array with the appropriate column configuration.

**Comment by BartoszBaczek** [comment]
Wow so stupid of me. I thought `columns` in `[ngForOf]="columns"` is some kind of "internal" field of kendo-grid. Alhtough I must say, that autogenerating grid in that case is a bit misleading ;) Thank you.
