### ISSUE TITLE
[DateRange] FloatingLabel doesn't update its state on focus

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3841]
**Describe the bug**
When using the `DateInput` component with `kendoDateRangeStartInput` and `kendoDateRangeEndInput` directives, wrapped in `FloatingLabel` component, the FloatingLabel does not relocate on the first click as expected, but the user must click a second time to achieve the desired behavior. Moreover, on the console appears the following error: `TypeError: Cannot read properties of null (reading 'setAttribute') `. Please, check the attached video for better visualization of the issue.

**To Reproduce**
1) Create two `DateInput` components.
2) Use the `kendoDateRangeStartInput` directive in the first `DateInput` component and `kendoDateRangeEndInput` in the second `DateInput` component.
3) Wrap each of the components in a `FloatingLabel`. 

Please, check this StackBlitz demo: https://stackblitz.com/edit/angular-bthmvk?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Expected behavior**
The `FloatingLabel` should relocate on the first click and no error should be thrown on the console. 

**Screenshots**
![image](https://user-images.githubusercontent.com/108671673/199738519-7419b126-1bdb-4ec7-a7e0-04ae8cb8570e.png)

https://user-images.githubusercontent.com/108671673/199733574-92df8cb1-5ecd-4e6d-91d6-7dbca029f9ba.mp4

**Comment by dtopuzov** [comment]
Released with @progress/kendo-angular-label@11
