### ISSUE TITLE
Pasting Excel data no longer formatted as table since v3.0.0

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3842]
**Describe the bug**
Pasting Excel data was formatted as a table in `v2.5.0` of the Editor:

https://user-images.githubusercontent.com/33104481/199943777-f22e81d0-5594-4873-ac31-69cc912a6175.mov

Demo:
https://stackblitz.com/edit/angular-bl1tfn

The KendoReact Editor behaves the same:

https://stackblitz.com/edit/react-2bpqay

Since `v3.0.0` pasting Excel data was converted as a regular paragraph.
Demo:
https://stackblitz.com/edit/angular-8ctx8a

**Expected behavior**
To be able to paste Excel data in table formatted value in Editor.

**Comment by Raisolution** [comment]
The prior behaviour was not an intended feature of the Editor. Thus, we have converted this from bug to an enhancement. It could be tracked and voted for in the feedback portal:

https://feedback.telerik.com/kendo-angular-ui/1590540-pasting-excel-formated-data
