### ISSUE TITLE
Set size on kendo-circularprogressbar  cause platform-browser error

### ISSUE THREAD

**Issue by MatheusJey** [telerik/kendo-angular#3845]
**Describe the bug**
Based on the doc I have changed the size of kendo-circularprogressbar component.
The size has been changed but the browsers console log showed the error:
`Error: <circle> attribute r: A negative value is not valid. ("-10")`

**To Reproduce**
Define style width and height on kendo-circularprogressbar element like:
`    <kendo-circularprogressbar
      [style.width.px]="40"
      [style.height.px]="40"
      [value]="currentProgress"
    ></kendo-circularprogressbar>`

**Expected behavior**
No error in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/29427210/200326333-760d4e3e-b4bf-43dc-a20c-8c22e28d1837.png)

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 107.0.5304.88

**Comment by PaskalevStoyan** [comment]
Hi @MatheusJey 

I've used the given configuration in the description and used it in this [StackBlitz example](https://stackblitz.com/edit/angular-mskb1c?file=src%2Fapp%2Fapp.component.ts) but I cannot reproduce the issue. Can you please modify the StackBlitz demo or provide a new one with the error. This will help us understand better what might be the cause.

Thanks in advance.
