### ISSUE TITLE
Multiselect component overflows when an item with long label is selected

### ISSUE THREAD

**Issue by kutkovav** [telerik/kendo-angular#3848]
**Describe the bug**
I have found a bug when using a multiselect component inside a container with dynamic width. When I select an item with a label longer than the current width of the container, it overflows.

**To Reproduce**
Can be seen on this [stackblitz example](https://stackblitz.com/edit/angular-qdobv8?file=src/app/app.component.ts) - the second and the third column. (You might possibly have to change the size of your screen.)

**Expected behavior**
The multiselect should behave the same as the combobox component (as can be seen in the first column) - if the selected item's label doesn't fit, it should be shortened.

**Screenshots**
![multiselect_overflow](https://user-images.githubusercontent.com/13157097/200791573-2e6637e1-d18c-4aec-925a-364e6647fc4e.PNG)

**Browser**
 - OS: Windows
 - Browser: Chrome (107.0.5304.88), Firefox (106.0.5)

**Comment by svetq** [comment]
The demonstrated behavior is caused by the custom html and css used in the example. Please see the default behavior of the components: https://stackblitz.com/edit/angular-4haolw
