### ISSUE TITLE
[Calendar] Component is not being disabled with the `classic` type

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3849]
**Describe the bug**
The `Calendar` component is not being disabled via its `disabled` property when the `classic` type is used. 

**To Reproduce**
1) Create a Calendar component
2) Bind the `disabled` property and set it to true
3) Set the type to `classic`

Please, see this StackBlitz example: https://stackblitz.com/edit/angular-h5wid6?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The `Calendar` component should get disabled when the `disabled` property is set to true.

**Screenshots**
<img width="206" alt="image" src="https://user-images.githubusercontent.com/108671673/201149644-3ee7c993-c372-4182-975a-86fba66b1835.png">

**Comment by svetq** [comment]
fixed in v [7.1.5](https://www.npmjs.com/package/@progress/kendo-angular-dateinputs/v/7.1.5) of the DateInputs package
