### ISSUE TITLE
Combobox isnt updating touched state when using in angular form

### ISSUE THREAD

**Issue by jensdc92** [telerik/kendo-angular#385]
When I select a value with a combobox the class ng-untouched stays unchanged. 

I have also tested this issue with the plunkers provided in the documentation.

**Comment by KirilNN** [comment]
maybe we should call onTouchedCallback and the right time

**Comment by tapopov** [comment]
Should be fixed with kendo-angular-dropdowns v0.39.0 (2017-04-18).
