### ISSUE TITLE
Floating label does not work properly with DateRange

### ISSUE THREAD

**Issue by joerg-bergner** [telerik/kendo-angular#3851]
**Describe the bug**
```
ERROR TypeError: Cannot read properties of null (reading 'setAttribute')
    at Ie.setAttribute (platform-browser.js:62:2498)
    at x.setAttribute (animations.js:8:3978)
    at fD.setAttribute (core-96c6cd00.js:1446:9789)
    at G.setAriaLabelledby (kendo-angular-label.js:1:7796)
    at G.ngAfterViewInit (kendo-angular-label.js:1:6892)
    at jv (core-96c6cd00.js:1151:4344)
    at Rv (core-96c6cd00.js:1151:4091)
    at Vv (core-96c6cd00.js:1151:3954)
    at vC (core-96c6cd00.js:1439:4798)
    at IC (core-96c6cd00.js:1439:11309)
```

**To Reproduce**
Open the console and your example: https://www.telerik.com/kendo-angular-ui/components/dateinputs/daterange/

You'll get the errors in the picture. - Problem for me are the errors: 

```
TypeError: Cannot read properties of null (reading 'setAttribute')
```

**Expected behavior**
A clear and concise description of what you expected to happen: No Errors

**Screenshots**
![image](https://user-images.githubusercontent.com/33862548/201632133-ab7b932a-d8ec-456d-a799-e9491f426bcb.png)

**Browser**
 - OS: MacOs
 - Browser: Chrome
 - Version: 107.0.5304.110 (Offizieller Build) (x86_64)

**Comment by yanmariomenev** [comment]
Hi @joerg-bergner,

I was not able to reproduce the error from the specific page or example on both Windows and Mac operating systems using Chrome. 

Are the mentioned errors also in the StackBlitz example? If so could you check if this fixes the issue with the error:
https://stackblitz.com/edit/angular-vevor7?file=src%2Fapp%2Fapp.component.ts
`public range = { start: new Date(), end: new Date() };`

**Comment by mbechev** [comment]
The Overview demo of the DateRange component needs to be updated according to the following article:
https://www.telerik.com/kendo-angular-ui/components/labels/floatinglabel/association/#toc-kendo-ui-for-angular-date-inputs.

The **placeholder** property needs to be set to an empty string when Associating the floating label with the date input component.

Following the instructions it looks the DateRange component cannot handle this scenario, ending on the following layout:
![image](https://user-images.githubusercontent.com/33104481/203542055-f7806804-4aeb-48ca-8895-cf0a5e5ec1da.png)

https://stackblitz.com/edit/angular-vevor7-tf3xm1

**Comment by svetq** [comment]
The issue is no longer reproducible with the latest version 14.0.0:
https://stackblitz.com/edit/angular-xaaxaz
