### ISSUE TITLE
[Grid] Drag selection doesn't work when dragging from inside to outside of the component

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3853]
**Describe the bug**
When the drag selection starts from the Grid and the user moves it outside of the Grid it doesn't select the rows that are part of the dragging hint.

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-xtznew?file=src%2Fapp%2Fapp.component.ts

2. Start the drag selection and move the cursor outside of the Grid and release finish the selection by releasing the right mouse button.

![chrome_wi6DOkiVmO](https://user-images.githubusercontent.com/49076727/202695351-615245b7-8c5f-45bb-afc3-a62e19ba6946.gif)

**Expected behavior**
To select the items that are covered by the hint selection similar to jQuery:
https://demos.telerik.com/kendo-ui/grid/selection
![chrome_3ldg6Og7gC](https://user-images.githubusercontent.com/49076727/202695638-e41c4a6e-5e0c-40fe-80ec-d62b976a1917.gif)

**Comment by Raisolution** [comment]
The demonstrated behaviour is expected when the drag action has finished outside the Grid boundaries.
