### ISSUE TITLE
[Chart]Series of Tooltip is displayed but not closed when mouse over a chart and display mess “Object doesn't support property or method 'fromEntries'” in dev tools

### ISSUE THREAD

**Issue by nmr1000** [telerik/kendo-angular#3855]
**Describe the bug**
Series of Tooltip is displayed but not closed when mouse over a chart and display mess “Object doesn't support property or method 'fromEntries'” in dev toolsSeries of Tooltip is displayed but not closed when mouse over a chart and display mess “Object doesn't support property or method 'fromEntries'” in dev tools

**To Reproduce**
Have kendo line chart(@progress/kendo-angular-charts": "^5.4.0") with angular 14. Mouse over the chart series of tool tip displayed with date information but not closed and  Object doesn't support property or method 'fromEntries' message logged in dev tools

**Expected behavior**
Only one tooltip should be displayed at a time and should be closed after some time and should not log error message.

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/20595650/202934736-98f7841c-8bff-45be-a637-17a93d463b1a.png)

**Browser**
 - OS: Windows (UWP)
 - Browser Edge
 - Version 107.0.1418.42

**Additional context**

**Comment by mbechev** [comment]
Hi @nmr1000,

In general `v5.4.0` is no longer compatible with Angular v14. 

Please update the **@progress/kendo-angular-charts** package to the latest stable version (currently v[7.3.2](https://www.telerik.com/kendo-angular-ui/components/charts/changelog/#c9911d2d-4ea6-5b1e-904e-e9248e633f16)) or at least to `v7.0.0` and test again the tooltips.
https://www.telerik.com/kendo-angular-ui/components/installation/up-to-date/#toc-updating-to-latest-versions
