### ISSUE TITLE
toODataString serialization for dates

### ISSUE THREAD

**Issue by cristiz1992** [telerik/kendo-angular#3858]
Hello,

When using toODataString function, dates are serialized without the single quotes and without the prefix.

Current behavior:
$filter=date ge 2022-05-22T00:00:00.000Z

What I would expect:
$filter=date ge datetime'2022-05-22T00:00:00.000Z'

The version of @progress/kendo-data-query is 1.6.0 .

To reproduce: [stackblitz](https://stackblitz.com/edit/angular-ivy-wtr3nb)

I'm not sure if this is the intended behavior or if it's a bug.

**Comment by mbechev** [comment]
Hi @cristiz1992,

Indeed this is the default behavior of the method when [JavaScript Dates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) are serialized.

To wrap the date into quotes, the provided date must be a string:
https://stackblitz.com/edit/angular-ivy-sbp4ec

This repository is for bug reports only, please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with specific scenarios, configuration or other questions.

**Comment by cristiz1992** [comment]
Is there a way to serialize with OData v3 instead of v4?

**Comment by Raisolution** [comment]
Hi @cristiz1992 
please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with the specific scenario.
