### ISSUE TITLE
NOTICE: End of Support for Angular 12

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#3859]
For the R1 2023 release in mid-January, we'll support Angular 13 as the minimum version. The [Long Term Support](https://angular.io/guide/releases#actively-supported-versions) for Angular 12.x expired on 2022-11-12.

This is part of a larger library reorganization that will also **lock all `@progress/kendo-angular-*` packages to a single version**, starting with v11. We hope that this will make the update process easier for everyone.

### Other changes
* Mixing and matching versions between packages will not be supported.
* Releases will be published with a single change log.
* The source code will be available through a single repository.
* The version lock will not apply to `@progress/kendo-angular-messages`. This package contains only message translations and will remain with independent versioning.
* Development builds will get a number-based suffix instead of timestamps, e.g. `v11.0.0-develop.1`

### Package breaking changes

We don't plan significant breaking changes, but we'll note any incompatibilities here.

- **Calendar** - The "Today" navigation element is now a flat button and has the `k-today` class removed.
- **Grid**
  - The grouping panel now uses the ChipList and Chip components instead of the custom GroupIndicator component.
  - The `kendoButton` directive [should be removed](https://feedback.telerik.com/kendo-angular-ui/1597569-kendogridaddcommand-no-longer-works-with-kendobutton) if it's used alongside the `kendoGridAddCommand`, `kendoGridEditCommand`, `kendoGridRemoveCommand`, `kendoGridSaveCommand`, and `kendoGridCancelCommand` directives.
- **Button** - `Button` is no longer a Directive, but a Component instead.
- **Toolbar** - Responsive Toolbar's overflow rendering is changed. This will affect all custom tools, and they will need to be adapted to the new mechanic for providing tool options when the tool is in the overflow popup.
- **All components with icons** - all packages that contain components featuring Kendo icons will have a new peer dependency on the `kendo-angular-icons` package
- **Menu** - `ExpandArrowDirective` is now `ExpandArrowComponent`. The selector is the same as before.

**Comment by tsvetomir** [comment]
#### UPDATE
* We have started publishing development snapshots on npmjs.com, see [Obtaining Development Builds](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).
  Please, feel free to give them a try together with the `dev` release of the kendo-theme packages.
* The [staging site](https://www.telerik.com/kendo-angular-ui-develop/components/) is also updated and now includes an unified [Changelog](https://www.telerik.com/kendo-angular-ui-develop/components/components/changelogs/kendo-angular-ui/).

**Comment by tsvetomir** [comment]
The v11.0.0 release is [now live](https://www.telerik.com/kendo-angular-ui/components/)! See the [Changelog](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/) for the final list of changes.

We're working on bringing online an archive with the changelogs of the individually versioned packages.

**Comment by s-hoff** [comment]
> #### UPDATE
> * We have started publishing development snapshots on npmjs.com, see [Obtaining Development Builds](https://www.telerik.com/kendo-angular-ui-develop/components/installation/development-builds/).
>   Please, feel free to give them a try together with the `dev` release of the kendo-theme packages.
> * The [staging site](https://www.telerik.com/kendo-angular-ui-develop/components/) is also updated and now includes an unified [Changelog](https://www.telerik.com/kendo-angular-ui-develop/components/changelogs/kendo-angular-ui/).

Can you please put the old changelogs back up somewhere as well? While its great to have easier updates by having one version for all, if anyone now needs to look at changes from before yesterday they need to use the googe cache for that, which also will eventually loose them once the crawler looks at them again.

**Comment by tsvetomir** [comment]
The changelog archive is live at the staging site:
https://www.telerik.com/kendo-angular-ui-develop/components/changelogs/archive/barcodes/
