### ISSUE TITLE
Update kendo-angular-icons to use the latest kendo-svg-icons

### ISSUE THREAD

**Issue by maxs-rose** [telerik/kendo-angular#3860]
Is it possible to update `@progress/kendo-angular-icons` to use the latest `@progress/kendo-svg-icons`?

When installing with yarn 2+ a warning is produced:

`project@workspace:. provides @progress/kendo-svg-icons (p4405d) with version 0.6.0, which doesn't satisfy what @progress/kendo-angular-icons requests`

From the `package.json` of the latest `kendo-angular-icons` (2.0.3 at time of writing) the package seems to request `^0.1.2` as a peer dependency.

**Comment by Raisolution** [comment]
Fixed in `v11.0.0` of the `kendo-angular-icons` package.
