### ISSUE TITLE
ColorPicker gradient selector goes out of box

### ISSUE THREAD

**Issue by AndrewJohnWalker** [telerik/kendo-angular#3861]
When picking certain colours on the far right of the gradient view, renavigating to the gradient view sees the colour indicator displayed outside of the picker

**To Reproduce**
https://stackblitz.com/edit/angular-pd4ujb?file=src/app/app.component.ts
https://angular-pd4ujb.stackblitz.io

1. Navigate to gradient view, pick a colour on the far right of the colour picking area
2. Navigate away from gradient view
3. Navigate back to gradient view
4. Icon indicating selected colour is outside of the colour picking area.

**Expected behavior**
Icon indiciating selected colour is inside of the colour picking area

**Screenshots**
![image](https://user-images.githubusercontent.com/94181505/204243704-5f3f0322-0ae4-487b-8e97-4a0c40bcadca.png)

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version [for example, 22]

**Additional context**
Appears to be specific to the number of columns set in the PaletteSettings, and having the default view as the palette view.
I used 11 columns in the stackblitz example.

PaletteSettings = {
        columns: 11
    }

**Comment by Raisolution** [comment]
Reproducible when the `activeView` is palette and the palette columns are more than the default 10.

**Comment by Raisolution** [comment]
Fixed in `v11.0.0` of the `kendo-angular-inputs` package.
