### ISSUE TITLE
[Tooltip] Interacting with TextBox or Editable Grid throws an error in v4.1.0

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3864]
**Describe the bug**
When the Tooltip wraps a TextBox component as an example it throws an error when typing or deleting the contents of the input.
`Error: Cannot read properties of null (reading 'content')`

**To Reproduce**

1. Open the following example:
https://stackblitz.com/edit/angular-i2zzoc?file=package.json,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts
2. Start typing and deleting the text to see the error from the Tooltip component.

**Expected behavior**
Not throw the error like version Tooltip version 4.0.4.

**Screenshots**
![chrome_nbjpOcY6zw](https://user-images.githubusercontent.com/49076727/205024528-e483203d-e743-4245-a0b2-9c5a7ed30ff6.png)

**Comment by PaskalevStoyan** [comment]
Fixed in v. 4.1.1 of the @progress/kendo-angular-tooltip package.
