### ISSUE TITLE
Wrong import in list.component.d.ts

### ISSUE THREAD

**Issue by joerg-bergner** [telerik/kendo-angular#3866]
Hi!

There is a wrong a import in @progress/kendo-angular-menu/rendering/list.component.d.ts:

Line 9: 
`import { MenuSize } from 'src/size';`

Should be:
`import { MenuSize } from '@progress/kendo-angular-menu/size';`

Menu Component Version: 4.1.0

Could you please update it.

**Comment by stnikolova** [comment]
The fix is shipped with **v4.1.1** of `@progress/kendo-angular-menu` package.
