### ISSUE TITLE
[MultiSelectTree] Dropdown arrows not displayed correctly when RTL is enabled

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3868]
**Describe the bug**
When utilizing the `RTL` functionality of the `MultiSelectTree`, the arrows, responsible for the dropdowns, are pointing to the right as it would be if `RTL` is not enabled. The same unexpected behavior is also observed for the `TreeView` and `TreeList` components.

<img width="249" alt="image" src="https://user-images.githubusercontent.com/108671673/206156182-fcd437ca-17bd-44c3-b7fe-5bdb28726d07.png">

**To Reproduce**
1. Create a `MultiSelectTree` component.
2. Utilize the `RTL` functionality. 
3. Open the dropdown of the component and notice the direction of the arrows.

Please, see the following StackBlitz example: https://stackblitz.com/edit/angular-dv4aqh-8gi5qt?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The arrows for the dropdowns should correspond to the RTL functionality and should point to the left.

**Screenshots**
![image](https://user-images.githubusercontent.com/33104481/206163330-4c6a0072-622d-4154-8534-a8b6c6d0d029.png)

**Comment by JoomFX** [comment]
Fixed in latest version.
