### ISSUE TITLE
Kendo Angular2 Theme Builder

### ISSUE THREAD

**Issue by lelong37** [telerik/kendo-angular#387]
Team,

Question, is it road mapped for a Kendo Theme Builder for Kendo UI Angular 2 and for out of the box themes e.g. Flat, Office 365, Bootstrap, etc.?

**Comment by lelong37** [comment]
![image](https://cloud.githubusercontent.com/assets/4691404/24157737/41a0c7f0-0e28-11e7-89f5-5057f31155c0.png)

**Comment by tsvetomir** [comment]
Please note that these themes (LESS based) are not available in the Angular suite.
See the help topic on [Styling](http://www.telerik.com/kendo-angular-ui/components/styling/).

There's a new SASS-based Theme Builder in the works that will go live soon. It supports the two new themes - "Default v2" and "Bootstrap" (based on Bootstrap v4).

**Comment by gyoshev** [comment]
The SASS-based ThemeBuilder has just been published on http://themebuilder.telerik.com/kendo-angular-ui

See the [theme builder topic](http://www.telerik.com/kendo-angular-ui/components/styling/theme-builder/) for details on how to use it to create a theme for your project.
