### ISSUE TITLE
[SplitButton] The focus leaves the dialog when a split button is used as the last focusable element within the dialog

### ISSUE THREAD

**Issue by Freeze8** [telerik/kendo-angular#3870]
**Describe the bug**
When using a split button inside a ```DialogComponent``` as the last focusable element and tabbing through the focusable elements inside that dialog, the user steps out of the dialog and focuses elements outside the dialog.

**To Reproduce**
1. Create a dialog using the ```DialogComponent```
2. Place a regular button first
3. Place a split-button after the regular button
4. Use tab to focus all focusable elements inside the dialog
5. Notice that the focus is getting outside of that dialog

Please, see the following StackBlitz example based on the kendo dialog example:
https://stackblitz.com/edit/angular-qeesh9

**Expected behavior**
The focus should remain within the dialog and not step out of that context.

**Browser**
Tried it in Chrome Version 108 and Firefox Version 107

**Comment by Raisolution** [comment]
Fix is available in `v11.1.0`.
