### ISSUE TITLE
[Splitter] Expanding the pane has a step limit that breaks the smooth dragging experience 

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3874]
**Describe the bug**
The pane seems to have a step limit that prevents the user to expand freely to the size they want.

![chrome_6aL82prK4F](https://user-images.githubusercontent.com/49076727/207847328-11f003cd-3224-473c-b047-a88a20de615c.gif)

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-sszz15-zverr1?file=src%2Fapp%2Fapp.component.ts
2. Start vertically expanding the last pane.

**Expected behavior**
To freely expand the pane similarly to Kendo UI for Blazor Splitter:
https://blazorrepl.telerik.com/QcYxObaW35YVPa0C23
![chrome_CSmyOXqNu2](https://user-images.githubusercontent.com/49076727/207847781-4f196efd-2a0d-480a-8a84-3ac9b0c38ed7.gif)

**Comment by Raisolution** [comment]
Fixed in v17.0.0
