### ISSUE TITLE
Filter and column menu don't close initially when loosing focus by clicking outside of the popup

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3879]
**Describe the bug**
When the filter menu is opened for the first type on initialization it doesn't close when losing focus and the user would need to click two times outside of the popup container. Afterward, the issue isn't present anymore and one click would be enough to close the popup. 
![chrome_BK11ckhW0d](https://user-images.githubusercontent.com/49076727/209628532-826a65ce-5906-4764-a6e3-3c99d907efd5.gif)
The first interaction is double-clicking outside the Grid and the second just takes one click.

**To Reproduce**
Can be tested in our examples:
https://www.telerik.com/kendo-angular-ui/components/grid/filtering/filter-menu/

**Comment by tswetti** [comment]
Also reported in private support thread 1625598

**Comment by gtteamamxx** [comment]
Also reported in private support thread, ticket no.: 1662701

**Comment by Raisolution** [comment]
Fixed in `v16.11.0`
