### ISSUE TITLE
Chart legend color does not match series when colorField is used

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#388]
See Plunker:

[http://plnkr.co/edit/F7kell8zml8AVCry6dQk?p=preview](http://plnkr.co/edit/F7kell8zml8AVCry6dQk?p=preview)

The legend matches the series color when the `color` attribute is used, but not `colorField`.

Is this a bug or a configuration issue?

**Comment by danielkaradachki** [comment]
The colorField will not be taken into account when determining the series color because it could have different values for the different points. You should explicitly set the series color:
http://plnkr.co/edit/KouRhpOkfk3PzOWGKdH7?p=preview

**Comment by SeriousLemon** [comment]
@danielkaradachki makes sense, cheers.

**Comment by Flaviocrtt** [comment]
thanks danielkaradachki, that was so easy.
