### ISSUE TITLE
Converting Odata string to CompositeFilterDescriptor object

### ISSUE THREAD

**Issue by idanporat** [telerik/kendo-angular#3881]
Today there is toODataString, converting odata string to CompositeFilterDescriptor object.
It would be helpful to have the opposite convert.

**Comment by mbechev** [comment]
Hi @idanporat 

This repository is for bug reports only. 

Please log a new feature request item in our [Feedback portal ](https://feedback.telerik.com/kendo-angular-ui) explaining in detail the requested functionality. Thus we can track the customer demand and consider adding it to our Roadmap based on the interest.
