### ISSUE TITLE
[ColorPicker] Console error / cannot tab between RGB when opacity set to false

### ISSUE THREAD

**Issue by AndrewJohnWalker** [telerik/kendo-angular#3883]
**Describe the bug**
When a ColorPicker has a GradientSettings with opacity: false you cannot tab between rgb values, a console error is present. 

**To Reproduce**
1. Open colour picker
2. Focus on R value
3. Attempt to navigate to G using the tab button on keyboard

https://stackblitz.com/edit/angular-9kvaig?file=src%2Fapp%2Fapp.component.ts
https://angular-9kvaig.stackblitz.io

**Expected behavior**
You are able to tab to the next colour value

**Screenshots**
![image](https://user-images.githubusercontent.com/94181505/210362485-39fbe672-fab1-4846-9890-5dff647750b0.png)

**Comment by PaskalevStoyan** [comment]
Fix is available in the latest [@dev](https://www.npmjs.com/package/@progress/kendo-angular-inputs/v/11.3.0-develop.3) version of the Inputs package.

**Comment by dtopuzov** [comment]
Released with v11.3.0
