### ISSUE TITLE
[Drawer] Ignores the data  hierarchy and selects the parent index instead the previously selected child index

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3884]
**Describe the bug**
This issue is present when the drawer is in non-mini mode. It does save the correct index but if the parent containing the selected child isn't expanded it will select a parent with the corresponding index ignoring the hierarchy. 

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-uxz9js?file=src%2Fapp%2Fapp.component.ts
2. Expand Calendar -> Notes and select Archive. Collapse the Drawer by clicking the menu icon and expand it again to see the incorrect selection.

![chrome_k7clmkIKW6](https://user-images.githubusercontent.com/49076727/210516229-09fa4438-8e02-483f-9560-695eef895b0f.gif)

**Workaround**
Set the [selected ](https://www.telerik.com/kendo-angular-ui/components/layout/api/DrawerItem/#toc-selected)property of every item and updated it manually:
https://stackblitz.com/edit/angular-1hscbs-mmpf5j?file=src%2Fapp%2Fcontent.component.ts

**Comment by Raisolution** [comment]
The Drawer does not persist the expanded state of the items. The developer should set the selected item, based on the current expanded state, as per the documentation:
https://www.telerik.com/kendo-angular-ui/components/layout/drawer/hierarchical-drawer/#toc-setup

The listed workaround is the expected configuration in the mentioned scenario.
