### ISSUE TITLE
[Editor][Toolbar] Tools that are part of a ButtonGroup have no text in the overflow popup

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3889]
**Describe the bug**
Tools that are part of a ButtonGroup show only icon in the overflow popup and not the corresponding text. 

**To Reproduce**
1. Create an `Editor` component.
2. Set the `Editor`'s toolbar to responsive.
3. Open the Overflow Popup.

Please, see this StackBlitz example: https://stackblitz.com/run/?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
In the Overflow Popup, the different tools should display an icon and the corresponding text.

**Screenshots**
Current Behavior: 
![image](https://user-images.githubusercontent.com/108671673/212023956-b75c0970-4635-4b78-98f4-3c91ca3ab34e.png)

Expected Behavior (could be seen in version 2.3.0):
![image](https://user-images.githubusercontent.com/108671673/212024137-41158017-3bc2-445e-a4d4-ccc154657fdd.png)

**Comment by Raisolution** [comment]
Fixed in `v11.0.0` of the `kendo-angular-editor` package.
