### ISSUE TITLE
How can I access the XHR object with the UploadComponent?

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular#389]
I need to show the progress of the uploads in real time, so I have to use `XHR.onprogress `. How can I have access to the XHR object? Cheers!

**Comment by Raisolution** [comment]
Hi @maximedupre,

currently Angular does allow accessing the underlying XHR object and even stated [here](https://github.com/angular/angular/issues/10424) that they don't have plans to support it.

**Comment by maximedupre** [comment]
I see. Then why not discard angular's http and use xhr instead? It seems like upload progression is a pretty standard feature in most of the file upload plugins out there. Anyway, thanks for the help!

**Comment by maximedupre** [comment]
Actually it can be done without discarding angular's `http`, I just did it in my own project. All you have to do is extend `BrowserXhr` and listen to `onprogress`.

**Comment by maximedupre** [comment]
I mean it's not working with the kendo-upload component if that's why you're closing the ticket haha. It would also need to be done in the Upload module

**Comment by KirilNN** [comment]
As we already said - currently it is not supported due to the mentioned framework limitation. We will consider it for future improvement. In case you have any suggestions -please use our feedback portal here:

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback

**Comment by maximedupre** [comment]
There are no framework limitations, you just have to extend `BrowserXhr`, add one event listener, and provide that instead. Sure I'll add that in the feedback portal, thanks for the support!
