### ISSUE TITLE
[Editor] Clear Value button of the ForeColor and BackColor tools does not reset the color of the text

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3891]
**Describe the bug**
The `Clear Value` button of the `ForeColor` and `BackColor` tools in the Editor's toolbar does not reset the color of the text. 

**To Reproduce**
1. Create an `Editor` component.
2. Select some text. 
3. Choose a foreColor and backColor. 
4. Go back in the picker and click the `Clear Value` button.

Please, see the following StackBlitz example: https://stackblitz.com/edit/angular-e6oom8?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The `Clear Value` button should reset the color property on the selected text (if there's any) and reset the tools' color to the default one (for current and future text).

**Screenshots**
![image](https://user-images.githubusercontent.com/108671673/212656408-81812d96-bad8-48c0-853d-c9e25663c27c.png)

**Comment by Raisolution** [comment]
Fixed in `v11.1.0`
