### ISSUE TITLE
[FormField][Upload][FileSelect] Null reference error thrown when a FileSelect or Upload is used within FormField

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#3892]
**Describe the bug**
`ERROR TypeError: Cannot read properties of null (reading 'hasAttribute')` thrown when FileSelect is used within FormField or Upload.

**To Reproduce**

Reproducible in the official documentation demos:

https://www.telerik.com/kendo-angular-ui/components/uploads/fileselect/forms/#toc-formfield-association
https://www.telerik.com/kendo-angular-ui/components/uploads/upload/forms/#toc-formfield-association

**Expected behavior**
No JavaScript error is thrown and the scenario is working as expected.

**Comment by Raisolution** [comment]
Fix is available in `v11.1.0`
