### ISSUE TITLE
[Scheduler] rendering misalignment when using  kendoSchedulerEventTemplate directive

### ISSUE THREAD

**Issue by SirAjZellweger** [telerik/kendo-angular#3896]
**Describe the bug**
The Events overlap the grid of the scheduler if the kendoSchedulerEventTemplate directive is used.

**To Reproduce**
Nothing needs to be adjusted in the code as the bug is also visible on the [documentation page](https://www.telerik.com/kendo-angular-ui/components/scheduler/templates/#toc-all-day-events).

https://stackblitz.com/edit/angular-abqsfw?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The Event should be placed inside the grid and not overlap it.

**Screenshots**
![image](https://user-images.githubusercontent.com/32460556/214290147-cf5e879a-5d81-4917-b417-1b41ec043d80.png)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 109.0.5414.75

**Additional context**

**Comment by yanmariomenev** [comment]
The issue appears when the component is initially rendered. Navigating or changing the view would fix the rendering:
![chrome_4icB38aAki](https://user-images.githubusercontent.com/49076727/216637152-2356d066-6f41-4aa6-8f9e-2e9f0cc278b6.gif)

**Comment by geo242** [comment]
I have the same issue. In my case it seems to resolve itself when the window, or the space of the container, is resized.

**Comment by dtopuzov** [comment]
Fix available at @progress/kendo-angular-scheduler@12.0.0
