### ISSUE TITLE
[DateTimePicker] Programmatically resetting min and max properties does not work

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3899]
**Describe the bug**
Having initially set the `min` and `max` properties of the `DateTimePicker`, when trying to change their values programmatically to `null` or `undefined`, the component still displays the initial date range.  

**To Reproduce**
1. Create a DateTimePicker component.
2. Bind its `min` and `max` properties. 
3. Programmatically reset the values of the `min` and `max` properties to `null` or `undefined`. 

For a better illustration of the issue, please reference the following StackBlitz demo: https://stackblitz.com/edit/angular-z5gwd7-nteo1h?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
When the `min` and `max` properties are set to `null` or `undefined`, the component should not display a specific range but all dates instead.

**Comment by spierala** [comment]
I am also facing this issue. 
This is clearly regression and should be fixed as fast as possible.

It is strange that you can set the min/max to any date dynamically but it is not possible to set it to undefined.
I can not imagine that it would be hard to fix.
This should be low hanging fruit to make your paying (!) clients happy.

If Kendo would be open-source this issue would have been fixed long time ago.

**Comment by tswetti** [comment]
Fixed in [v15.2.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.2.0)
