### ISSUE TITLE
Additional "Space" is present in the "Contains" field cell of the Filter component

### ISSUE THREAD

**Issue by VeselinShterev** [telerik/kendo-angular#3900]
**Describe the bug**
An additional "Space" appears in the "Contains" filed cell of the Kendo UI for Angular Filter component which causes a misalignment of the text with the text of the other filter cells.

**To Reproduce**
Observe the added space by inspecting the "Contains" cell in the following running code example - https://stackblitz.com/edit/angular-ehpztv-wufvxe 

**Expected behavior**
The text content of the "Contains" cell should not have additional spaces added.

**Screenshots**
![Contains field additional space](https://user-images.githubusercontent.com/105972817/215524322-eef9ec89-3a36-4860-96af-0f144a8a0539.png)

**Browser**
 - OS: [Windows 11]
 - Browser [Chrome, Edge]

**Comment by yanmariomenev** [comment]
Available in version 13.2.0 - https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v13.2.0
