### ISSUE TITLE
[DateTimePicker] FormGroup reset method doesn't clear the component input field

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3901]
**Describe the bug**
The DateTimePicker input field doesn't reflect when the FormGroup is being rested. It is only affected when the date is full. It seems that it affects the DateTimePicker as the DatePicker doesn't have such an issue.

**To Reproduce**
https://stackblitz.com/edit/angular-6cbyfm?file=src%2Fapp%2Fapp.component.ts
![chrome_6ys1EjLdNI](https://user-images.githubusercontent.com/49076727/215776056-8383787d-cb2c-4d65-a935-ee836ee025ae.gif)

**Workaround**
Set the value of the form and then reset it:
https://stackblitz.com/edit/angular-rfp9zs?file=src%2Fapp%2Fapp.component.ts

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
