### ISSUE TITLE
[DropDownList] Search bar's icon is not positioned correctly 

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3902]
**Describe the bug**
The icon of the search bar which appears when the DropDownList's filtering is enabled is not positioned properly.

**To Reproduce**
1. Create a DropDownList 
2. Enable its filtering functionality 
3. Notice the position of the search icon

Please, reference the following StackBlitz demo: https://stackblitz.com/edit/angular-ukzw9t?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The search icon should be placed entirely inside the search bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/108671673/215791827-9bd09e93-b34d-497d-b564-bc014e74691c.png)

**Comment by aldrashan** [comment]
It appears the "k-input-icon" class is missing in the latest version.
Adding it to either the "kendo-icon" component or the "kendo-icon-wrapper" component fixes the problem.

**Comment by dtopuzov** [comment]
Released with v11.3.0
