### ISSUE TITLE
Incorrect ButtonGroup focus behavior on Safari 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3907]
The `.k-focus` class is always applied on the first button regardless of the clicked button in the group. This behavior is reproduced only in **Safari** browser (tested with v16.0 ).

https://user-images.githubusercontent.com/33104481/216259749-75fb320e-d698-4a6e-abef-339dd4aa8fdf.mov

**To reproduce**
https://stackblitz.com/edit/angular-yuujdc

Related issue: https://github.com/telerik/kendo-themes/issues/4268

**Comment by dtopuzov** [comment]
Released with @progress/kendo-angular-buttons@11.3.0
