### ISSUE TITLE
Kendo Upload append values to FormData

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#391]
Is it possible to append other values to the FormData? 
I need to append an ID to the FormData to know where the uploaded files belong to.

**Comment by Raisolution** [comment]
Hi @simon11196 ,

yes you could use the [upload event handler](http://www.telerik.com/kendo-angular-ui/components/upload/#toc-on-uploading-files) to achieve the task.
```
  onUpload(e: UploadEvent) {
    e.data = {
      id: "File id"
    };
  }
```
