### ISSUE TITLE
[DropDownButton] Toggle method seems to fire close event

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3910]
**Describe the bug**
The default behavior of the DropDownButton's toggle method implies that it should not fire the open and close events of the component. However, when trying to use this method to open/close the DropDownButton from an external component with open and close events prevented, nothing happens. 

**To Reproduce**
1. Create a DropDownButton component. 
2. Use the toggle method to open/close the DropDownButton from an external component. 

Please, reference the following StackBlitz demo: https://stackblitz.com/edit/angular-vbkfnn-jw6ga4?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The toggle method should not trigger the open and close events of the DropDownButton.

**Comment by dtopuzov** [comment]
Released with @progress/kendo-angular-buttons@11.3.0
