### ISSUE TITLE
Date in "kendoSchedulerTimeSlotTemplate" with "kendo-scheduler-timeline-view"

### ISSUE THREAD

**Issue by lgisselbrecht** [telerik/kendo-angular#3916]
**Describe the bug**

We are using a scheduler in both "Day" and "Timeline" views, with a "time slot template" to display the date value.
In "day" view the time correspond to its header, but it's not the case in "Timeline" view.

**To Reproduce**

To reproduce :
- fork the "Time slots template demo" from here :
https://www.telerik.com/kendo-angular-ui/components/scheduler/templates/#toc-time-slots
- update the "kendoDate" pipe format to "HH:mm"
- add the "kendo-scheduler-timeline-view" at the same level of "kendo-schedule-day-view"

Changing between the two views will show you that the date in a "8:00 AM" cell is not the same if you're in on one mode or another.

You can try this here :
https://codesandbox.io/s/currying-fast-wfn7sw?file=/src/app/app.component.ts

**Expected behavior**

The date returned for a "8:00 AM" cell in "Day" view is the same as the date returned for a "8:00 AM" cell is "Timeline" view.
The other views like "Week" or "Timeline-week" have the same reaction, so the need to get the same value too.

Thanks in advance :)

**Screenshots**

"Day" view
![image](https://user-images.githubusercontent.com/124897752/217870104-434c3217-19af-4e1d-b36e-5a4397fe30c7.png)

"Timeline" view
![image](https://user-images.githubusercontent.com/124897752/217870289-f57f3e19-387d-45b7-84ad-83cf1926a615.png)

**Browser**
 - OS: Windows 11 Pro
 - Browser: Chrome
 - Version: 109.0.5414.120 (64 bits)

**Comment by dtopuzov** [comment]
Released with v13.1.0
