### ISSUE TITLE
[Filter] Dynamic filter via Component declarations

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-angular#3922]
**Describe the bug**
We can define filters via Component declarations as documented here https://www.telerik.com/kendo-angular-ui/components/filter/filters-configuration/#toc-component-declaration

However when we change them dynamically, the filter do not change.

Note this works via the Filter input property

**To Reproduce**
https://stackblitz.com/edit/angular-agt9ap?file=src%2Fapp%2Fapp.component.ts

click `Change Filters`, not that the filters has not changed

**Expected behavior**
Filters change

**Screenshots**
![image](https://user-images.githubusercontent.com/13205912/219023522-37a2f2ca-3cf1-4530-806a-e9a8f0a3e983.png)

**Browser**
 - OS: [for example, iOS]
 - Browser [for example, Chrome, Safari]
 - Version [for example, 22]

**Additional context**
11.2.0

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
