### ISSUE TITLE
Changelog pages are missing from documentation

### ISSUE THREAD

**Issue by geo242** [telerik/kendo-angular#3923]
**Describe the issue**
All changelog pages are missing from the online documentation. The pages are still indexed on google but the links are all broken. (e.g. https://www.telerik.com/kendo-angular-ui/components/navigation/changelog/)

**Screenshots**
N/A

**Browser**
 - OS: All
 - Browser: All
 - Version: N/A

**Additional context**
Google search: https://www.google.com/search?q=site%3Atelerik.com+kendo+angular+change+log

**Comment by geo242** [comment]
@dtopalov Thank you, this helps a lot!

**Comment by slavenai** [comment]
Hi @KimBum ,

The Kendo UI for Angular Changelog is updated when a new version is released. It contains information for the respective bug fixes, features and breaking changes. For example, here is a list of all changes for `v13.0.0`:

https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v13.0.0
