### ISSUE TITLE
[Drag&Drop] Dropping an element throws error

### ISSUE THREAD

**Issue by slavenai** [telerik/kendo-angular#3925]
**Describe the bug**
When an element is dropped from one dropTarget to another or outside of a valid one, an error is thrown:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/67437411/220086969-3d44c141-e445-48c6-849d-0b706596696f.png">

**To Reproduce**
https://stackblitz.com/edit/angular-2jz52j?file=src%2Fapp%2Fapp.component.ts

**Comment by dtopuzov** [comment]
Released with version 11.3.0
