### ISSUE TITLE
Kendo ErrorComponent and HintComponent throws an error when implemented with the Editor

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3927]
**Describe the bug**
The following error is present when implementing ErrorComponent together with the Editor component:

`ERROR Error: Cannot read properties of null (reading 'hasAttribute')`

Setting [iframe ](https://www.telerik.com/kendo-angular-ui/components/editor/api/EditorComponent/#toc-iframe)to **false** will avoid the issue.

**To Reproduce**

1. Open - https://stackblitz.com/edit/angular-3hlzfw-n37f2w?file=src%2Fapp%2Fapp.component.ts (hint component [example](https://stackblitz.com/edit/angular-3hlzfw-lzxzhw?file=src%2Fapp%2Fapp.component.ts))
2. See the browser console.

**Comment by geo242** [comment]
Just encountered this error. Please fix.

**Comment by Raisolution** [comment]
Fix available in `v.17.1.0`
