### ISSUE TITLE
[PDFExport] CSS text-underline-offset is not reflected in the exported document

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#3931]
**Describe the bug**
Using the [`text-underline-offset`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset) CSS property is not reflected in the exported document.

Also, when exporting, the line is by default higher than usual. Same problem is observed when using `line-through` - the line is again higher than the default one, rendered in the browser.

**To Reproduce**
https://codesandbox.io/s/small-cookies-4fmkid?file=/src/app/app.component.ts

**Expected behavior**
The expored document styling matches the one on the page.

**Comment by dtopuzov** [comment]
Released with v11.5.0
