### ISSUE TITLE
[Editor] Underline color doesn't match the text color

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3935]
**Describe the bug**
The underline color is not changed when setting a fore text color, it stays always black:

![image](https://user-images.githubusercontent.com/33104481/222078076-94e2a09d-2d71-4f9f-84b4-049ba1f99536.png)

In MS Word and Kendo UI for jQuery Editor, the underline is also colored:

![image](https://user-images.githubusercontent.com/33104481/222078758-bd4b8bfd-47ab-42b3-8aac-8c2bea218bbe.png)

**To Reproduce**
https://stackblitz.com/edit/angular-gzmcho?file=src%2Fapp%2Fapp.component.ts

**Comment by Raisolution** [comment]
Issue is fixed in `v13.0.0` of the Editor package.
