### ISSUE TITLE
Kendo Filter 2.3.1 / 2.3.0 / 11.*.* has a bug that on 2.2.2 wasn't

### ISSUE THREAD

**Issue by cvivasf** [telerik/kendo-angular#3937]
I'm submitting a bug on Kendo Filter 2.3.0+.

**On version 2.2.2 of the Kendo Filter:**

Basically , if you use the kendoFilterValueEditorTemplate to customize the value editor for specific filters and you load programatically the value of the entire Kendo Filter by doing the following (for example, on ngOnInit())...

  @ViewChild("kendoFilter") kendoFilter: FilterComponent;

this.kendoFilter.value = MY_KENDO_FILTER_VALUE;

... then, the value editors load succesfully for every filter expression that uses and does not use the kendoFilterValueEditorTemplate and you can focus dropdowns, comboboxes, text inputs, numerics, boolean with no problem.

If you try to load the initial value for the Kendo Filter with the [value] input, the value editor for the filters that go through the  kendoFilterValueEditorTemplate  template dont load as dropdowns or comboboxes, just as textfields.

WORKAROUND: I load the kendo filter initial value programatically from TS by accessing this.kendoFilter.value and all filters load correctly even with the kendoFilterValueEditorTemplate .

**On version 2.3.0 or superior:**

The problem is that on version 2.3.0 or superior this workaround doesn't work anymore and loading the initial Kendo Filter Value with the [value] input doesn't propertly show either the kendoFilterValueEditorTemplate value editors.

After much testing, my conclusion is that some change was implemented on version 2.3.0 that fixed some bugs but generated this new one.

I would like to move to ng13 in order to upgrade to newer Kendo Components but because I use persistence and initial values of the Kendo Filter with kendoFilterValueEditorTemplate I need this bug to be fixed.

Imagine a Reactive Form where you have many steps and in one of them you configure a Kendo Filter that on some filters you use the kendoFilterValueEditorTemplate . If you go back to a previous step and move forward again to the step containing the Kendo Filter, you need to load the Kendo Filter Value with an initial value. Here is where the problem occurs on version 2.3.0+.

Im using version 2.2.2 and setting the value via this.kendoFilter.value (from TS) works fine, but to see this bug in Kendo Filter happening in version 2.3.0 or bigger is really limiting my upgrading capabilities...

Thanks!

**Comment by svetq** [comment]
@cvivasf 
see the following example where the initial values of a reused filter expression value editor template are set properly:
https://stackblitz.com/edit/angular-upd8ry-s53qbc?file=src%2Fapp%2Fapp.component.ts

please provide an example demonstrating the exact use-case scenario on your side if further assistance is required

**Comment by svetq** [comment]
The provided example doesn't reproduce the reported issue. It mixes two different approaches to setting the Filter fields:

https://www.telerik.com/kendo-angular-ui/components/filter/filters-configuration/

For further assistance about the [editorFormat](https://www.telerik.com/kendo-angular-ui/components/filter/api/FilterExpression/#toc-editorformat) property or the Filter, in general, open a support thread: https://www.telerik.com/kendo-angular-ui/components/support/
