### ISSUE TITLE
ComboBox with valuePrimitive="true" and customValue="true" options does not display custom values in forms

### ISSUE THREAD

**Issue by sakkce** [telerik/kendo-angular#394]
Hi,

It would appear that having a KendoComboBox with both valuePrimitive and customValue options fails to display custom value assigned to form control.

Here is sample plunkr: http://plnkr.co/edit/yGbMCCTwIzCZl1UknebD?p=preview

Expected behaviour is to have ComboBox display the value of 5.

**Comment by szavoda** [comment]
This is a pretty big deal for anyone using custom values.  Is there a work around or ETA for the bug fix?

**Comment by tapopov** [comment]
Thank you both for bringing this to our attention.
We are currently working on resolving it, however at this point there is no good workaround that we can suggest.

**Comment by szavoda** [comment]
In my case, the problem occurs specifically when the source data is an array of complex objects and the  model that it is bound to is a property of a complex object.  It would look similar to this:

`<kendo-combobox 
    name="myComboBox"
    [(ngModel)]="someOtherObject.theValue"
    [allowCustom]="true"
    [textField]="'theValue'"
    [valueField]="'theValue'"
    [valuePrimitive]="true"
    [data]="myObjects">`

As a workaround, I have found that if I create a local variable that is of type "MyObject" and then set the value of that variable when the form loads and update the real target property on a selection change, I can get around it.  The result would look something like:

`<kendo-combobox 
    name="myComboBox"
    [(ngModel)]="myLocalObject"
    [allowCustom]="true"
    [textField]="'theValue'"
    [valueField]="'theValue'"
    [data]="myObjects"
    (selectionChange)="myComboBoxSelectionChange($event)>`

and in the .ts:

`var myLocalObject: MyObject;
var myObjects: MyObject[];

private GetObjectIAmWorkingOn{
  var myLocalObject = GetTheObject();
}

  private myComboBoxSelectionChange(changedObject): void {
    if (changedObject)
      this.someOtherObject.theValue= changedObject.theValue;
    else
      this.someOtherObject.theValue= "";
  }`

**Comment by tapopov** [comment]
Should be fixed in kendo-angular-dropdowns v0.39.5

**Comment by sakkce** [comment]
Working perfectly now. Big thanks!
