### ISSUE TITLE
[TreeView] load more button remains loading endlessly

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3941]
**Describe the bug**
When using remote data and the "Load More" button feature of the TreeView, then the "Load More" button remains in a loading state after it has been clicked once. The issue is present when using remote data.

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/treeview/load-more-button/#toc-remote-data

**Comment by dtopuzov** [comment]
Released with [v11.5.0](https://github.com/telerik/kendo-angular-private/releases/tag/v11.5.0)
