### ISSUE TITLE
MultiWeek events are misaligned when the component is initialized

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3942]
**Describe the bug**
On Scheduler initialization, the events are misaligned and didn't update according to the slots only on MultiWeek view:

![image](https://user-images.githubusercontent.com/33104481/223393660-4992a1ec-0b59-434f-b182-1f4ba1375afd.png)

When the page is resized and the Scheduler dimensions are changed, the alignment of the event is updated correctly.

**To Reproduce**
1. Notice the misalignment of the events.
2. Try resizing the StackBlitz by dragging the splitter.

https://stackblitz.com/edit/angular-zh8qzs?file=src%2Fapp%2Fapp.component.ts

**Comment by stnikolova** [comment]
Fix available at @progress/kendo-angular-scheduler@12.0.0
