### ISSUE TITLE
[Treelist] selectionChange is triggered twice inconsistently

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3945]
**Describe the bug**

Clicking row by row of the TreeList the `selectionChange` event is triggered twice (when drag selection is enabled):

https://user-images.githubusercontent.com/33104481/224029138-cdbc2ec6-1f98-4a68-9287-e2352a4a0db5.mov
 

Might be related to:
https://github.com/telerik/kendo-angular/issues/3804

**To Reproduce**
https://stackblitz.com/edit/angular-pt71hz-o2boqh

**Comment by slavenai** [comment]
Fixed in `v16.11.0`
