### ISSUE TITLE
Mask not clearing

### ISSUE THREAD

**Issue by Sevensnake** [telerik/kendo-angular#395]
http://plnkr.co/edit/vqQfFl0SNsAhT13yjtKA?p=info

not exactly the example, but after there is a value in the text box. If my Json array return blank "", it does not clear out. It holds the last value until there is a new value.

**Comment by rusev** [comment]
Recently we released version `0.21.0` for the `kendo-angular-inputs` package and it seems that the example in your plnkr works right now.

**Comment by Sevensnake** [comment]
Thanks, I will try to store this in my project and let you guys know if the problem is resolved.

**Comment by Sevensnake** [comment]
Problem is fixed. Thanks again.
