### ISSUE TITLE
[FileSelect] Cannot link an external drop zone with kendoFileSelectDropZone as input

### ISSUE THREAD

**Issue by slavenai** [telerik/kendo-angular#3950]
**Describe the bug**
The UploadDropZone directive is missing a kendoFileSelectDropZone input, thus the [kendoFileSelectDropZone]="..." binding does not link the drop zone with the component.

**To Reproduce**

https://www.telerik.com/kendo-angular-ui-develop/components/uploads/fileselect/external-dropzone/#toc-dropzone-directive

**Comment by AndrewJohnWalker** [comment]
Hello, are there any updates on this bug getting fixed?

**Comment by Raisolution** [comment]
Fixed in v. 16.9.0
