### ISSUE TITLE
[intl] importing locale files dynamically throws error

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#3955]
**Describe the bug**
Trying to import a locale file dynamically:

`import(@progress/kendo-angular-intl/locales/bg/all.js).then(locale => {
    console.log(locale);
});`

throws the following error:

`Module not found: Error: Package path ./locales is not exported from package node_modules/@progress@kendo-angular-intl `

The static import of the same locale file is fine:

`import '@progress/kendo-angular-intl/locales/bg/all';`

**To Reproduce**
The issue is reproducible in a default Angular CLI project.

**Comment by CarmenTalnariu** [comment]
same issue here after updating kendo packages to version 11.4.0

**Comment by svetq** [comment]
The issue is caused by the following bug in webpack:
https://github.com/webpack/webpack/issues/13865
