### ISSUE TITLE
Form is submit when clicking the DatePicker in the Toolbar

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3956]
**Describe the bug**
Similar to https://github.com/telerik/kendo-angular/issues/3515

Clicking the DatePicker in the Scheduler Toolbar triggers the `submit` event of the `<form>`.
```html
<form (submit)="onSubmit()">
   <kendo-scheduler...>...</kendo-scheduler>
</form>
```

![image](https://user-images.githubusercontent.com/33104481/226304745-ec4f7a6a-3f71-4ecf-9801-86e30861e3b4.png)
https://stackblitz.com/edit/angular-sfvqst-bmsvs1

**Comment by dtopuzov** [comment]
Released with v11.5.0
