### ISSUE TITLE
grid-No records available (??)

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#397]
1. navigate to [this plnkr](http://plnkr.co/edit/tKRqF8YgHueJDfRDDj3O?p=preview)
2. navigate to last page on grid
3 .press _filter grid_ button (under the grid)
4. grid display "**No records available**"
   actually, there are records.
the problem is that we "stuck" on current page.
there should be **automatic navigation** to first page with results after **grid source changed**

**Comment by rkonstantinov** [comment]
As you, as developer, are in change for managing the state of the Grid. It is up to you to change the skip in this scenario.
