### ISSUE TITLE
[Grid] Toggling the navigable attribute dynamically does not work as expected

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#3972]
**Describe the bug**
Dynamically changing the value of the navigable attribute on a button click does not change the navigation of the Grid.

**To Reproduce**
1. Create a Grid component and bind the navigable property. 
2. Create a button that changes the value of the navigable property dynamically. 

Please, check out the following StackBlitz demo: https://stackblitz.com/edit/angular-dvdqvq-7fjo7u?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Dynamically changing the value of the navigable property should modify the Grid's navigation.

**Comment by Raisolution** [comment]
The behaviour expected, as changing the `navigable` property on the fly is not supported. We will update the corresponding documentation section to indicate this.
