### ISSUE TITLE
Possible Cross-Site Scripting (XSS) attack when pasting content in Editor

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#3974]
Copying a failed image and pasting it inside the Editor emits the `onerror` event of the `<img  />`

https://user-images.githubusercontent.com/33104481/231734420-30b74a0c-abe9-4537-a446-bf1ba9bdd3e2.mov
 
This could be potentially used to inject malicious code. 

To reproduce:

1. Create a local HTML file with the image definition inside
    ```html
    <img src="/imagepath" onerror="alert('xss')">
    ```
2. Click the file and open it inside the browser (an alert is displayed).
3. Copy the failed image (**Ctrl+A** and **Ctrl+V**)
4. Paste the content inside the Editor.
5. The alert is also displayed, hence the `onerror` event is triggered.

**Comment by sky0matic** [comment]
Hi there,

I'm the one who logged this issue to support.

Just noticed that going on https://www.telerik.com/kendo-angular-ui/components/editor/examples/overview/?theme=default-ocean-blue&themeVersion=6.2.0 (like the gif), it triggers the XSS only once.

Going to the paste example of the editor on https://www.telerik.com/kendo-angular-ui/components/editor/examples/paste-cleanup/?theme=default-ocean-blue&themeVersion=6.2.0 and doing the same thing, triggers it twice, so you may have at least two places that triggers it.

**Comment by Raisolution** [comment]
Fix available in `v12.0.0` of the Editor package.
