### ISSUE TITLE
CellCloseEvent rowIndex is always undefined

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3978]
**Describe the bug**
The [CellCloseEvent ](https://www.telerik.com/kendo-angular-ui/components/gantt/api/CellCloseEvent/)always returns [rowIndex ](https://www.telerik.com/kendo-angular-ui/components/gantt/api/CellCloseEvent/#toc-rowindex)as undefined. The issue is related to the TreeList component as the Gantt component uses it under the hood. 

**To Reproduce**
Edit a cell and close in the following example - https://stackblitz.com/edit/angular-b9vvz6?file=src%2Fapp%2Fapp.component.ts

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
