### ISSUE TITLE
[ListBox] KB navigation does not respect newly added items

### ISSUE THREAD

**Issue by PaskalevStoyan** [telerik/kendo-angular#3984]
**Describe the bug**
When adding a new item to the Listbox, its not included in the KB navigation.

**To Reproduce**
1. Open this Stackblitz demo: https://stackblitz.com/edit/angular-4mj79j?file=src%2Fapp%2Fapp.component.ts
2. Click on the `Add Country` button.
3. Try to navigate to the newly added item.

**Expected behavior**
Newly added items should be included in the KB navigation

**Comment by dtopuzov** [comment]
Released with @progress/kendo-angular-listbox@12.0.1
