### ISSUE TITLE
ListBox buttons emit ngSubmit events.

### ISSUE THREAD

**Issue by arrayofletters** [telerik/kendo-angular#3987]
# Bug report:

ListBox buttons emit ngSubmit events.

## Current behavior

ListBox buttons emit ngSubmit events.

## Expected behavior

ListBox buttons should not emit ngSubmit events.

Reproduction:

https://stackblitz.com/edit/angular-nvaedk?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Comment by yanmariomenev** [comment]
Similar to https://github.com/telerik/kendo-angular/issues/3956  https://github.com/telerik/kendo-angular/issues/3958

**Comment by dtopuzov** [comment]
Released with @progress/kendo-angular-listbox@12.0.1
