### ISSUE TITLE
Kendo calender is not working properly. (no view at first)

### ISSUE THREAD

**Issue by gayan1991** [telerik/kendo-angular#399]
I have a problem with kendo-angular-date-inputs@0.3.7. I have scroll down then up again to view the dates inside the date (numbers..etc). And it scrolled down to the minimum date. Once i can view the numbers, if I select week, it will be scrolled to focus date. Then if i scroll up, high chance of going to minimum date (probably scroll faster or further).

**Comment by ggkrustev** [comment]
@gayan1991, could you provide a runnable plunkr and/or a specific reproduction steps that we can follow? This will help us to observe the issue locally and find a resolution faster.

**Comment by ggkrustev** [comment]
The latest version of the Calendar seems to work as expected:
http://plnkr.co/edit/2ZkR06on9cKPzxurmMUC?p=preview

I'll close the thread for now. Please post a repro demo that demonstrate the issue in order to reopen it.
