### ISSUE TITLE
TextBox Type Password shows extra eye icon on Microsoft Edge

### ISSUE THREAD

**Issue by PTancek** [telerik/kendo-angular#3990]
**Describe the bug**
Kendo textbox shows 2 eye icons in Microsoft Edge browser

**To Reproduce**
Open the sample from documentation in Microsoft Edge
https://www.telerik.com/kendo-angular-ui/components/knowledge-base/textbox-password-type/

When enetring text into the input, a second eye icon is shown. The icon dissapears when you leave the input. 

**Expected behavior**
A single icon should be displayed, same as in chrome / firefox / .. 

**Screenshots**
![slika](https://user-images.githubusercontent.com/30393224/236451213-2aaadec3-857f-4da9-b935-36a811861444.png)

**Browser**
Microsoft Edge
Version 112.0.1722.68 (Official build) (64-bit)

**Comment by Raisolution** [comment]
Hi @PTancek,

The demonstrated behavior is expected - the first eye icon is built-in browser feature, and the second eye icon is added manually via template. For further assistance please open a [support ticket](https://www.telerik.com/account/support-tickets).
