### ISSUE TITLE
Grid throws an error when kendoGridFooterTemplate is used with enabled filtering and navigation

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#3994]
**Describe the bug**
An error is triggered in the Kendo Grid when attempting to filter its data using the kendoGridFooterTemplate feature, specifically when typing in the filter field after it has been focused on. Error message:

`Cannot read properties of undefined (reading 'cells')`

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-uxxwif?file=src%2Fapp%2Fapp.component.ts
2. Focus on the filter input and type something inside to reproduce the error.

**Workaround**
Remove the navigable property or set it to false.

**Comment by Raisolution** [comment]
Issue is fixed in `v13.0.0` of the Grid package.
