### ISSUE TITLE
<kendo-signature> does not work if you have multiple instances inside of <mat-tab>

### ISSUE THREAD

**Issue by PdrLins** [telerik/kendo-angular#3995]
**Describe a bug**
I have a **mat-tab-group** with some  **mat-tab**, in each tab I had to add one kendo-signature. They supposed to be independent however when signatures are rendered, it is possible to draw a signature only in the kendo signature in the first tab, but in the second tab it does not work.

![image](https://github.com/telerik/kendo-angular/assets/30423539/353751df-d003-4d71-a4df-ee5f6817889a)

![image](https://github.com/telerik/kendo-angular/assets/30423539/99b7fef9-b9af-4871-b03b-dceb0cd6e5f3)

Using consolog to get info, i could realized that the canvas in the first tab could be rendered but the canvas in the second, is set width = 0 and height = 0
![image](https://github.com/telerik/kendo-angular/assets/30423539/4fa540ed-0967-4704-bbc8-29d1e5a4691d)

**To Reproduce**

1. Create a `<mat-tab-group> </mat-tab-group>`
2. Add 2 `<mat-tab></mat-tab>`
3. In the first mat tab add a `<kendo-signature>`
4. In the second mat tab add another `<kendo-signature>`
5. try to draw a signature in the second signature pad

**Comment by PaskalevStoyan** [comment]
Hi @PdrLins,

While we do not guarantee that our components cover all possible scenarios and integrations with other component libraries, we can ensure that they work as expected when combined together, for instance the Signature component in combination with our TabStrip component.

Please refer to the following StackBlitz demo demonstrating the said above:

https://stackblitz.com/edit/angular-1hvpbb?file=src%2Fapp%2Fapp.component.ts
