### ISSUE TITLE
Buttons in the editor's toolbar behave incorrectly with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by Celentia** [telerik/kendo-angular#3998]
**Describe the bug**
In the kendo editor component with ChangeDetectionStrategy.OnPush enabled, after updating the main @progress dependencies to 11.6.0 along with @progress/kendo-theme-bootstrap and @progress/kendo-theme-default to 6.2.0, the buttons in the editor's toolbar started behaving incorrectly. 

Upon loading the page with the editor, the Clear button is displayed as active until the editor is clicked on (even though the class with disabled styles should be attached to the button immediately). Additionally, when clicking on the B button or any other button, the k-selected class is not added, but ng-reflect-selected becomes "true". However, clicking on another button in the toolbar results in the class being added and the button being recolored.

**To Reproduce**

1. Enable ChangeDetectionStrategy.OnPush in the kendo editor component.
2. Click on buttons in the toolbar.

Here is an example: https://stackblitz.com/edit/angular-nvstid?file=src/app/editor.component.ts

**Expected behavior**
Toolbar buttons should get selected styles immediately upon clicking. Here is an example: https://stackblitz.com/run/?file=app/app.component.ts

**Comment by Celentia** [comment]
Looks like the following code fixes the issue:
`ngDoCheck(): void {
 this.cdr.markForCheck();
 }`
 
 However, it looks like an issue that should be fixed on Kendo's behalf.

**Comment by Raisolution** [comment]
Issue is fixed in `v13.0.0` of the Editor package.
