### ISSUE TITLE
DropDown selecting default item not set form value to null

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#400]
If you set [defaultItem] and [valuePrimitive]="false", when selecting item and then default item, value is not null, so form is valid, but it shouldn't (because control is required).

[Plunkr](http://plnkr.co/edit/tYQ5rJaszddpHhJTKtgR?p=preview).

![2017-03-18_20-54-53](https://cloud.githubusercontent.com/assets/1589573/24075510/2d816a48-0c1d-11e7-99fe-3fd5cbbcf8fd.gif)

**Comment by valchev** [comment]
@MaklaCof 

The required Angular built-in validator does not support object validation. If a `defaultItem` is set, the developer needs to implement the required custom validation. Check the 2nd example from [this help topic](http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/forms/#toc-reactive-forms).
