### ISSUE TITLE
[Sortable] uses incorrect kendoDraggable directive

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#4007]
**Describe the bug**
The Sortable component throws errors when it uses the Grid or TreeList within its item template.

The issue is caused due to the multiple elements within the Grid or TreeList that use the `kendoDraggable` attribute.  

**To Reproduce**
Please see the following example:
https://stackblitz.com/edit/angular-gnbeam-nmat3g?file=src%2Fapp%2Fapp.component.ts

**Comment by dtopuzov** [comment]
Released with v13.0.0
