### ISSUE TITLE
Is there a way to configure the animation of the new AdaptiveMode on several components

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#4009]
The new AdaptiveMode property on several components, like DropdownList and DatePicker, is a nice feature.
But is there a way to configure the animation? Mainly the speed or just disabling it at all.
Would be nice if it could somewhere globally.

**Comment by PaskalevStoyan** [comment]
To be tracked in the feedback portal - [link](https://feedback.telerik.com/kendo-angular-ui/1609959-adaptivemode-add-a-way-to-configure-the-animation-on-several-components)
