### ISSUE TITLE
Feature: drop down should hide default item if component value is requred

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#401]
I think title says all.

[Used plunker](http://plnkr.co/edit/tYQ5rJaszddpHhJTKtgR?p=preview).

![2017-03-18_20-58-10](https://cloud.githubusercontent.com/assets/1589573/24075592/cc7d9b2a-0c1e-11e7-8be8-f32017615a96.png)

**Comment by valchev** [comment]
@MaklaCof 

The `defaultItem` is an optional configuration property. If your business logic does not require it you may leave it undefined. The component itself does not modify the input properties provided by the developer.
