### ISSUE TITLE
[DropDownList] Wrapping DropDownList in a label does not open on click

### ISSUE THREAD

**Issue by PaskalevStoyan** [telerik/kendo-angular#4010]
**Describe the bug**

Wrapping a DropDownList in a label element prevents the component from opening on click. It works when the arrow icon is clicked.

**Steps to reproduce**

1. Open this [Stackblitz demo](https://stackblitz.com/edit/angular-wmwohj?file=src%2Fapp%2Fapp.component.ts)
2. Click on the DropDownLists
3. The first DropDownList is wrapped in a label element and will not open on click. The second is not wrapped and works as expected.

**Workaround**
One workaround is to set the **for** attribute on the label and connect it with an identical **id** on the dropdownlist.

**Comment by stnikolova** [comment]
Fixed in **v14.1.0**.
