### ISSUE TITLE
[Grid] Resizing locked columns causes misalignment

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4011]
**Describe the bug**
When the user resizes the width of a column in the Grid component with the locked columns feature enabled, the columns are getting misaligned. 

**To Reproduce**
1. Create a Grid component 
2. Enable the resizable functionality
3. Enable the locked columns feature
4. Resize any of the locked columns (downsize it)

Please, check out the following StackBlitz demo: https://stackblitz.com/edit/angular-nfvhfe

**Expected behavior**
Resizing the locked columns should not cause any misalignment. 

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/108671673/5b7a2638-0c92-47fa-b954-abc7bd009de5)

**Comment by Lagombi** [comment]
I'm also having this issue with kendo-treelist
