### ISSUE TITLE
[TabStrip] Active elements must have unique IDs

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4012]
**Describe the bug**
Axe throws accessibility errors when declaring more than one TabStrip on the page:
- Ensures every id attribute value of active elements is unique
- Ensures every id attribute value used in ARIA and in labels is unique

https://stackblitz.com/edit/angular-dx35mt?file=src%2Fapp%2Fapp.component.ts

It looks like the tabs (`<li>` elements) on the different TabStrip have the same id value:

![image](https://github.com/telerik/kendo-angular/assets/33104481/87971911-771f-484e-b144-82ddf92fe0b7)

```[tasklist]
### Tasks
```

**Comment by dtopuzov** [comment]
Released with v13.1.0.
