### ISSUE TITLE
Tooltip displays at the wrong Chart when `appendTo` is set

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4014]
**Describe the bug**
Setting a custom popup container through the `appendTo` option, the Tooltip is displayed at the wrong Chart when multiple Charts are defined in the page.
The issue is that if we hover the second Chart series, the tooltip will be displayed in the first Chart.

https://stackblitz.com/edit/angular-ssad6k-jralf7

The tooltip is displayed correctly if we didn't change the popup container.

**Comment by stnikolova** [comment]
After a thorough investigation by our team, we would like to provide clarification on the observed behavior.

The reported behavior is not a bug but rather a result of the intended implementation of the `appendTo` option. It is important to note that the Chart component, when configured with `appendTo` to a specific container, dynamically places the tooltip in the HTML DOM right after the specified container (as a sibling). In such a configuration, it is crucial for developers to ensure that the specified container in the DOM is within an element that has the CSS property `position: relative.`

The reason behind this requirement lies in the calculation logic used by the Chart component for tooltip positioning. When the tooltip is within a container with `position: relative`, it establishes a new positioning context, and the calculations for tooltip placement are based on this context. If the container lacks `position: relative`, the calculations may not accurately reflect the intended behavior, leading to the observed issue where the tooltip is displayed in an unexpected location.

Please refer to the following example: https://stackblitz.com/edit/angular-ssad6k-z9sdd9
