### ISSUE TITLE
Selecting an item in a listbox after an item has been moved throws a JS error

### ISSUE THREAD

**Issue by arrayofletters** [telerik/kendo-angular#4015]
**Describe the bug**
Selecting an item in a listbox after an item has been moved throws a JS error

**To Reproduce**

https://stackblitz.com/edit/angular-mmghm6?file=src%2Fapp%2Fapp.component.ts

Move an item from the left listbox to the right listbox.  Then select an item from the left listbox.

**Expected behavior**

An error should not be thrown.

This is a showstopper bug and prevents us from using v12.1.0

**Comment by PaskalevStoyan** [comment]
Hello @arrayofletters,

The issue has been addressed and fixed in the latest version of the Listbox component - `v13.0.2`.
