### ISSUE TITLE
treelist a11y issues

### ISSUE THREAD

**Issue by dtopuzov** [telerik/kendo-angular#4017]
**To Reproduce**
Open a page with TreeList component and run [axe](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd)

**Expected behavior**
No errors.

**Actual**

Axe Issues:

- aria-allowed-role
- label
- aria-valid-attr-value
- aria-input-field-name
- aria-required-children

**Additional context**

Gantt component use TreeList, so you can see same issues in Gantt as well.

**Comment by PaskalevStoyan** [comment]
https://github.com/telerik/kendo-angular-private/issues/981 - This issue is related to the `aria-valid-attr-value` issue coming from the Axe, it will be handled seperately.

**Comment by Raisolution** [comment]
Issue is fixed in `v13.0.0` of the Treelist package.
