### ISSUE TITLE
Row reordering breaks when adding new records to the Grid

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4019]
**Describe the bug**
When row reordering is enabled and new records are added to the Grid, the reordering functionality breaks, specifically when the user attempts to reorder over the newly added records.

**To Reproduce**
Open - https://stackblitz.com/edit/angular-pyen2x?file=src%2Fapp%2Fapp.component.ts
Add new records and try to reorder over the newly added records.

**Recording**
![chrome_BCcM2FHaCr](https://github.com/telerik/kendo-angular/assets/49076727/f9556fe0-ad50-4f80-b795-8d16c72c0094)

**Comment by slavenai** [comment]
Fixed in `v13.0.3` of the Grid package.
