### ISSUE TITLE
[Sortable Component] sometimes dragEnd Event doesn't occur

### ISSUE THREAD

**Issue by jongsue** [telerik/kendo-angular#402]
Sometimes dragEnd Event doesn't occur especially in multiple Sortable Component.

see below a plunk link.
[Drag between Lists](http://plnkr.co/edit/cslgvBBe022DWogs1wvT?p=preview)

**Comment by alexsalmon** [comment]
@tapopov Any update regarding this?

**Comment by ipeshev** [comment]
Fix available in [latest development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tapopov** [comment]
Shipped in `kendo-angular-sortable` v2.0.0
