### ISSUE TITLE
NOTICE: Switch to default SVG icons

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#4022]
## BREAKING CHANGE

In the June 2023 Kendo UI for Angular R2 release, SVG icons will replace font icons as a default icons type across all components. All default built-in icons will be working out-of-the-box. To accommodate your code base for scenarios, using alternative icons, set through the component options (for example using the `icon` input), use the `svgIcon` input instead.

## Using Alternative Kendo SVG Icons in Components

If alternative Kendo font icons are set through the respective component options, replace the existing code as follows:

Before:

```
    <button kendoButton icon="folder"></button>
```

After:

```
    import { SVGIcon, folderIcon } from '@progress/kendo-svg-icons';
    ...
     <button kendoButton [svgIcon]="folderIcon"></button>
     ...
     export class AppComponent {
         public fontIcon: SVGIcon = fontIcon; 
     }
```

### SVGIcon Naming Convention

Most SVG icons from the `@progress/kendo-svg-icons` package use camelCase - `nameIcon`, where "name" is also the name of the previously used font icon. If the name consists of two or more words, for example `icon="align-left"`, each word after the first one will be capitalized, and the icon name will end with `Icon` - the name of the corresponding SVG icon will be `alignLeftIcon`.

The lists of all available Kendo font and SVG icons are available in the following documentation articles:

[LIST OF FONT ICONS](https://www.telerik.com/kendo-angular-ui/components/icons/icon/icon-list/)
[LIST OF SVG ICONS](https://www.telerik.com/kendo-angular-ui/components/icons/svgicon/svgicon-list/)

## Using Custom SVG Icons in Components

To use custom SVG icons, the respective icon needs to conform to the [SVGIcon interface](https://www.telerik.com/kendo-angular-ui-develop/components/icons/api/SVGIcon/). Such icons can be used in the same manner as Kendo SVG icons.

## Continue Using Font Icons

If switching to SVG icons is undesirable, you can continue displaying font icons for Kendo UI for Angular components. To achieve this, set the type of icons to `font` using the [ICON_SETTINGS](https://www.telerik.com/kendo-angular-ui-develop/components/icons/api/ICON_SETTINGS/) token:

```
    import { ICON_SETTINGS } from "@progress/kendo-angular-icons";
    @NgModule({
    ...
        providers: [{ provide: ICON_SETTINGS, useValue: { type: 'font' } }]
    })
    export class AppModule {}
```

> After R3 2023, scheduled for October, 2023, the font icons will no longer be shipped as a part of the Kendo Themes. To continue using the Kendo font icons after the R3 release, you will need to load the respective font separately.

**Comment by geo242** [comment]
Are we also expected to migrate to using the `kendo-svg-icon` element rather than the `kendo-icon` element? It seems the `kendo-icon` element does not support svg icons.
