### ISSUE TITLE
chart.component.d.ts imports EmbeddedViewRef from @angular/core/core

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#4023]
**Describe the bug**
Error: node_modules/@progress/kendo-angular-charts/chart.component.d.ts:56:33 - error TS2307: Cannot find module '@angular/core/core' or its corresponding type declarations.

**Expected behavior**
Should import from @angular/core

**Comment by dtopuzov** [comment]
Released with v13.0.3
