### ISSUE TITLE
[Scheduler] Toolbar date picker popup does not open in Safari

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4024]
**Describe the bug**

The Scheduler toolbar date picker popup doesn't open in Safari. There are no errors in the console.
![image](https://github.com/telerik/kendo-angular/assets/33104481/70d24b08-88f7-4562-aa31-7a9cb693f60f)

If the control is focused using keyboard shortcuts (left/right arrows and `Enter`), the popup is opened.

Open the following demo in the Safari browser:
https://stackblitz.com/edit/angular-n2zjxl

**Comment by dtopuzov** [comment]
Fix released with v13.2.0
