### ISSUE TITLE
kendo-grid-filter-cell-operators is broken

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#4025]
**Describe the bug**
kendo-grid-filter-cell-operators can not be used in custom filter components, once included in `kendoGridFilterCellTemplate` the component fires `Error: Cannot read properties of undefined (reading 'title')`

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/knowledge-base/grid-filter-by-time/ the last example is broken
or
https://stackblitz.com/edit/angular-yzld2e?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
To be able to use filter operators for custom filters

**Comment by dtopuzov** [comment]
Released with v13.1.0.
