### ISSUE TITLE
[Line, Area] Persistent Highlight on Legend Hover with Tooltips

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4026]
**Describe the bug**
The bug occurs when hovering over the legend names in the chart. It should highlight the corresponding series, but the highlight does not reset properly. As a result, one series remains highlighted while the others remain blurred or at a lower opacity. Typically this behavior resets when you hover outside of the Chart but when tooltips are included then it doesn't reset.

**To Reproduce**
1. Open https://stackblitz.com/edit/angular-fgao9f?file=src%2Fapp%2Fapp.component.ts
2. Hover over the legend names and try to reset the highlight state

**Recording**
![chrome_2M4tdCosVb](https://github.com/telerik/kendo-angular/assets/49076727/cd485508-648e-4749-9d3d-6d754608e300)

**Comment by tsvetomir** [comment]
Should be fixed in the current [development build](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/)(13.4.0-develop.12).

**Comment by yanmariomenev** [comment]
Fixed in version [13.4.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v13.4.0)
