### ISSUE TITLE
Adaptive mode close button causes the form to be submitted

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4027]
**Describe the bug**
Closing the ActionSheet causes the form to be submitted.

**To Reproduce**
Example with ComboBox:
https://codesandbox.io/s/cranky-browser-qmj3vs
Example with DropDownList:
https://stackblitz.com/edit/angular-5d8zva?file=src%2Fapp%2Fapp.component.ts

**Comment by dtopuzov** [comment]
Released with v13.1.0.
