### ISSUE TITLE
ComboBox custom template

### ISSUE THREAD

**Issue by qina83** [telerik/kendo-angular#403]
Is there a way to define a custom template for selected value of ComboBox?
eg I would like to add an icon inside ComboBox

![image](https://cloud.githubusercontent.com/assets/15413007/24093595/ef956732-0d54-11e7-979b-2bfa30e9b46c.png)

**Comment by tapopov** [comment]
Hi @qina83 
By design, the ComboBox supports list item templates only. Adding a value template feature is currently not planned.

**Comment by qina83** [comment]
I think it could be an improtant improvement. In this example

http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/templates/#toc-item-template

there are differents between Item and Selected Value and sometimes this could be ambiguous

**Comment by valchev** [comment]
@qina83 

A quick follow up: If your component is designed to work with pre-defined items (no custom values) you may use DropDownList as it supports custom template for the selected value. Check [this demo](http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/templates/#toc-value-template).
