### ISSUE TITLE
[DropDownList, DropDownTree] Opening the popup causes the Grid cellClick event to emit

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4030]
**Describe the bug**
Opening the popup on both **DropDownList** and **DropDownTree** will emit the **cellClick** event of the Grid component.

Might be related to - https://github.com/telerik/kendo-angular/issues/3617. Selecting an item doesn't emit the **cellClick** event.

Some older versions like DropDowns 5.5.0 don't seem to be affected.

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-5ujrzn-tke1gq?file=src%2Fapp%2Fapp.component.ts
2. Open the popup by clicking on the inner input. Clicking on the icon won't emit the cellClick event.

**Comment by svetq** [comment]
When using a template the developer has control over the events fired from within the template. To avoid the bubbling of the click event that triggers the **cellClick** of the Grid you can follow one of the following approaches:

- Use the `.k-grid-ignore-click` class as documented: https://www.telerik.com/kendo-angular-ui-develop/components/grid/editing/in-cell-editing/#toc-disabling-the-click-handler-for-specific-elements
example: https://stackblitz.com/edit/angular-5ujrzn-69aozs
 
- Stop the propagation of the click event manually: https://stackblitz.com/edit/angular-5ujrzn-ksheez
