### ISSUE TITLE
Grid header always contains pointer cursor from `k-active` class

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4034]
**Describe the bug**
The Grid should incorporate the addition of the `!k-cursor-default` class based on its configuration. Specifically, a basic Grid that lacks any data manipulation functionalities should include the mentioned class.

Discussion - https://github.com/telerik/kendo-themes/issues/3680#issuecomment-1344094656

**Screenshots**
Kendo UI for React Grid:
![chrome_jsXlSSaGWX](https://github.com/telerik/kendo-angular/assets/49076727/d03a40aa-cfce-44cc-abdf-2ef4aa7f0ca6)

**Comment by Raisolution** [comment]
Issue to be resolved in the Kendo UI themes package as part of upcoming Grid rendering unification.
