### ISSUE TITLE
[PDFViewer] Setting the zoom property does not update the value in the combobox controlling the zoom level

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4037]
**Describe the bug**
When binding the zoom property of the PDFViewer component and assigning it a value different than the default one, the value in the combobox, controlling the zoom level, is not getting updated and stays at 125%. 

**To Reproduce**
1. Create a PDFViewer component. 
2. Bind the zoom property and set it to a value different than 1.25. 
3. Check the value in the combobox controlling the zoom level.

Please, check the following StackBlitz demo for reference: https://stackblitz.com/edit/angular-xcz29b 

**Expected behavior**
Setting the value of the zoom property should also update the value in the combobox in the toolbar. 

**Screenshots**
![a22292d9-7551-44c2-aeaf-cfaaeda45a30](https://github.com/telerik/kendo-angular/assets/108671673/76051b76-218e-4cd5-a291-3f9a09f4a815)

**Comment by dtopuzov** [comment]
Released with v13.1.0.
