### ISSUE TITLE
[MultiSelectTree] Placeholder is not visible

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4040]
**Describe the bug**
Binding the `placeholder` property does not display a placeholder in the component.

**To Reproduce**
1. Create a `MultiSelectTree` component.  
2. Bind the `placeholder` property. 
3. Check how the component is rendered. 

Please, check out the following StackBlitz demo that demonstrates this issue: https://stackblitz.com/edit/angular-e6652k

**Expected behavior**
When the `placeholder` property of the `MultiSelectTree` is set, the placeholder should be visible in the component.

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/108671673/56ab7191-31dd-4703-ae53-202c9d3671ca)

**Additional context**
The issue could be reproduced in version 13 of the Kendo packages. In version 12, the placeholder is visible. 

Check out the following demo that demonstrates the behavior of the `placeholder` property with version 12: https://stackblitz.com/edit/angular-ewpmas

**Comment by svetq** [comment]
This issue will be fixed in the Kendo themes. Please track it at the following link: https://github.com/telerik/kendo-themes/issues/4618
