### ISSUE TITLE
Grid performance issue when having 50 -100+ columns

### ISSUE THREAD

**Issue by Duskfall** [telerik/kendo-angular#4046]
**Describe the bug**
Grid doesn't scale well when having a lot of columns because it renders every single column that is not in the viewport. The more columns you add, the more it deteriorates the renderering of the grid. We can't use virtualColumns in our case because we also want sticky columns.

**To Reproduce**
Using the existing stackblitz that loads a lot of items, I have made some changes to depict the issue. You can manually change the number of the columns to see that the grid doesn't scale. 
https://stackblitz.com/edit/angular-htvgqe-ka1rqk

**Expected behavior**
The grid should only render what is in the view port

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/2528125/4f9f704f-ebce-487b-90a9-81b3f276f59e)

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version 114

**Comment by yanmariomenev** [comment]
Hi Duskfall,

The Grid provides column virtualization that rendered only the columns that are in the current viewport:

https://www.telerik.com/kendo-angular-ui/components/grid/columns/virtual/

For more performance tips, please visit the following page:

https://www.telerik.com/kendo-angular-ui/components/grid/browser-performance/

**Comment by Duskfall** [comment]
This configuration doesn't work when you have sticky columns though as I said in the description

**Comment by yanmariomenev** [comment]
That is correct and documented on our page:

https://www.telerik.com/kendo-angular-ui/components/grid/columns/sticky/#toc-known-limitations

The alternative option would be to use [locked columns](https://www.telerik.com/kendo-angular-ui/components/grid/columns/locked/):

https://stackblitz.com/edit/angular-jwjnvk?file=src%2Fapp%2Fapp.component.ts
