### ISSUE TITLE
[Upload, FileSelect] `focus` and `blur` events are emitted incorrectly 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4048]
The `focus` and `blur` events are triggered incorrectly. 

When a file is selected the `focus` event gets triggered, instead of when the component wrapper is focused.

1. Focus the Upload component (notice that the `focus` event isn't fired).
2. Upload a file (now the `focus` event is fired).
https://stackblitz.com/edit/angular-v8wwvt

**Additional Context**
If the component is focused with `Tab` key, the focus event isn't triggered as well. But when the Upoad gets blurred, the focus event is triggered.

The focus event should be triggered once the control is focused:

![image](https://github.com/telerik/kendo-angular/assets/33104481/35204dd0-4320-4192-9da6-111e86b54a74)

**Comment by Raisolution** [comment]
Fix is available in `v13.5.0`
