### ISSUE TITLE
Is TreeList available as alpha/beta?

### ISSUE THREAD

**Issue by coder925** [telerik/kendo-angular#405]
Is it possible to start using the TreeList already even if it is in alpha or beta? Thanks.

**Comment by tsvetomir** [comment]
The TreeList development is not started yet.
Please [cast your vote for it](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback/suggestions/16636987-treelist-component) on our Feedback portal so we can prioritize. Thanks!

**Comment by coder925** [comment]
Thanks for the quick reply. I just wanted to check.
