### ISSUE TITLE
[Grid] Changing the order of selectedKeysChange and selectedKeys definitions changes the selection behavior

### ISSUE THREAD

**Issue by chrrasprodot** [telerik/kendo-angular#4054]
**Describe the bug**
The order of the `selectedKeysChange` output and the two way binding on the `selectedKeys` input of the `SelectionDirective` changes the behavior of the selection. If the `selectedKeysChange` output is defined before the `selectedKeys` binding, the component property bound to the `selectedKeys` input does not contain the element that was just selected and shows the previous selection. If the definitions are swapped, the `selectedKeys` contains all expected keys.

**To Reproduce**
- I have created this StackBlitz snippet: https://stackblitz.com/edit/angular-y4gwud
- The StackBlitz was forked from the example on selecting all items: https://www.telerik.com/kendo-angular-ui/components/grid/selection/persisting/#toc-selecting-all-items
- The only change to the example from the docs are:
  - I swapped the order of the definitions of `selectedKeys` and `selectedKeysChange` so that `selectedKeysChange` is defined first
  - I added a console.log in the `onSelectedKeysChange` callback that prints the contents of the selected keys

**Expected behavior**
The order of the definitions in the HTML should not influence the selection functionality. If the behavior is unavoidable, it should be clearly documented.

**Browser**
 - OS: Windows 11
 - Edge 114.0.1823.82
 - Firefox Developer 116.0b7

**Comment by slavenai** [comment]
Hi @chrrasprodot ,

The observed behavior is the default Angular behavior. Two-way binding automatically updates the respective property. In case the change event is handled separately and before the property is updated, its previous value will be retrieved.

Our team will further discuss whether the above should be explicitly mentioned in our documentation as it is common Angular behavior and is not Kendo UI for Angular specific.

With that said, as this repository is for bug reports only, I am closing this issue. Please use our [support system](https://www.telerik.com/account/support-tickets) if you need any further assistance with specific configuration or setup.
