### ISSUE TITLE
[Grid, TreeList]: PDF Export Functionality Ignores Column Widths

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4055]
**Describe the bug**
This seems to be related to newer versions of the Grid as in older the issue isn't present. This doesn't seem to affect the standalone PDF component as it exports the columns with their respective widths.

**To Reproduce**
Open the following example and export the Grid - https://stackblitz.com/edit/angular-fi3ykx-s8xjmx?file=src%2Fapp%2Fapp.component.ts

#### Working versions
Older versions where the column widths are proper - https://stackblitz.com/edit/angular-4jvh4z-hwqppx?file=src%2Fapp%2Fapp.component.ts

Standalone PDF Export(latest version) - https://stackblitz.com/edit/angular-w4zjxo?file=src%2Fapp%2Finvoice.component.ts

**Screenshots**
![t2OUAeG4x3](https://github.com/telerik/kendo-angular/assets/49076727/27afc4d3-650a-42a6-9456-ee3757aa96e4)

**Comment by Raisolution** [comment]
Fix is available in `v13.5.0`
