### ISSUE TITLE
(question) Draggable / resizable dialog

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#406]
Hey guys, do you have plans for draggable and resizable kendo-dialog component and if yes do you know if it will be ready for the official release?

Thx :)

**Comment by tsvetomir** [comment]
Not at the moment. Please feel free to cast your vote for a [Window](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback/suggestions/17597812-window-component) on our UserVoice portal so we can prioritize.
