### ISSUE TITLE
[PDFViewer] Text layer is not aligned to the document during search and selection

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#4064]
Text highlighting during selection or search matching is not working as expected - the highlighted area(s) are in the wrong place and do not cover the respective text appropriately.

Reproducible in the Angular demos - https://www.telerik.com/kendo-angular-ui/components/pdfviewer/

**Comment by marcolongol** [comment]
Hi @dtopalov, any ETA on when is it going to be generally available?
