### ISSUE TITLE
Grid - how to retrieve the selected element

### ISSUE THREAD

**Issue by qina83** [telerik/kendo-angular#407]
in this example

http://plnkr.co/edit/jF9wvszqm936neXy5DDV?p=preview

the selection index depends on how data is grouped (the same happens if are sorted or filtered)
how to retrieve the element selected? why is not privide by events?

**Comment by tsvetomir** [comment]
We're working on a complete selection support for the Grid. It will include means to identify the selected element by something more specific than an index, e.g. a key field.

**Comment by jaypeelh** [comment]
This worked for me, not grouping though:
 onSelectionChanged(event) {
        let row: any = this.gridData.data[event.index];
        this.showProfile(row);
    }

**Comment by tsvetomir** [comment]
Merging this issue into #634
