### ISSUE TITLE
Disabled property of FormControl components not working in Reactive Forms

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#4070]
**Describe the bug**
The [disabled property](https://www.telerik.com/kendo-angular-ui/components/inputs/textbox/disabled-state/) is not working in Reactive forms after upgrading to Angular 15. It works as expected in Angular 13.

**To Reproduce**

[disabled property in Angular 13](https://stackblitz.com/edit/angular-zeakfr?file=src%2Fapp%2Fapp.component.ts) - working fine
[disabled property in Angular 15](https://stackblitz.com/edit/angular-qxy8en-sjq572?file=src%2Fapp%2Fapp.component.ts) - not working

Note: works as expected when used w/out `formControlName` binding, as well as outside `formGroup`.

**Expected behavior**
The TextBox should be disabled in Angular 15 as well.

**Comment by hetalishah** [comment]
Workaround: Use the FormControl to set the [disabled property](https://angular.io/api/forms/AbstractControl#disabled) to true.

[StackBlitz example](https://stackblitz.com/edit/angular-qxy8en-7wcl3w?file=src%2Fapp%2Fapp.component.ts)

**Comment by dimsis** [comment]
Hi,
There is a problem with the resolution. When we disable using the {value:'', disabled: true} property on the FormControl, when the form is submitted, **the form field and its value are not sent** and this can cause a problem if there are backend validations.

**Comment by dimsis** [comment]
Update:

It seems it's an Angular 15 reactive form change for the disabled state.

"This behavior change was caused by a fix to make setDisabledState always called. Previously, using [attr.disabled] caused your view to be out of sync with your model."

Another workaround if you want to pass the formControl and it's value is to use:  title: this.form.getRawValue().title,

**Comment by dimsis** [comment]
Another problem with setting disable via FormControl is that you lose the ability to disable based on conditions like this example that does the trick in the template:

kendo-textarea formControlName="comments" [maxlength]="400" **[disabled]="selectedfundingType?.setting!=='MDT'"** [placeholder]="(selectedfundingType?.setting==='MDT') ? '* specify: free text (400 characters)' : ''" [rows]="3" class="form-input comments-height"></kendo-textarea>

**Comment by JohannesHoppe** [comment]
I compared the relevant parts of Kendo with an older version of 2019 and the latest version – the code regarding `[disabled]` wasn't touched at all. So this is not a Bug introduced by the Kendo Team!

But this is a well-known regression in Angular, which was introduced with the upgrade to Angular 15!
See: https://github.com/angular/angular/issues/48350#issuecomment-1405900515

Solution:

```ts
// BEFORE
@NgModule({
  imports: [
    ReactiveFormsModule
  ]

// AFTER
@NgModule({
  imports: [
    ReactiveFormsModule.withConfig({ callSetDisabledState: 'whenDisabledForLegacyCode' })
  ],
```

After changing this setting, the Kendo Controls will behave like before. 

Expected (old) behaviour:
When the `[disabled]` binding is set to true, the underlying DOM element will be disabled and can't be changed anymore. BUT it will not behave like `formControl.disable()`. The value is still accessible via `form.values`. If the control is disabled via the dedicated function, then the value disappears!
Please Kendo Team, never touch this behaviour – or our full codebase is screwed!

**Comment by yanmariomenev** [comment]
Our documentation is now updated to reflect the behavior changes in the disabled state of Reactive forms from Angular 15 and above. For example our DateInputs forms article:

https://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/forms/#toc-managing-the-dateinput-disabled-state-in-reactive-forms
