### ISSUE TITLE
Grid: Resetting the Selections With SelectionDirective.reset()

### ISSUE THREAD

**Issue by gilmorem560** [telerik/kendo-angular#4077]
I've got a question on the GridComponent that I'm hoping someone here can help me out with.

So my goal is simple, clear the set of selected rows in a grid in an event.  In the plain JavaScript version of the grid, this can be achieved by: https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/methods/clearselection

Pretty cut and dry right?

Well, in the Angular interface, I can find no such way to perform this simple, data agnostic operation.  I'm not trying to make any specific edits to the selection list, maintain it in any different way, literally just flush *everything* selected out so that the grid does not visually, nor in the background, indicate anything is selected. My use case, if it helps, is that I'm deleting records out of a backing store based on which records are selected in a table (using selectionChanged to keep a running list of the RowArgs records involved.)  I map to the dataItem field and iterate over my objects when I hit my delete button, and refresh the data set sitting up under the grid.  The rows (by index) that I had selected previously retain a red highlight through them as the indexing is simply based on row number.  I am fine with the defaults, I literally just need a table to visualize my selection of rows for the operation. It's all local data supplied as "[data]", not a binding directive or anything complex like that.

The problem is that when they're gone, and those highlights remain, those highlights are now no longer consistent with my actual backing data. I thought the simple answer would be "make the selections go away entirely", but I literally can't find a way to do this without implementing my own selected keys collection and all of that extra stuff with the SelectionDirective. I don't need that complicated of a grid, I literally just need to be able to snap my fingers and the selection state is entirely reset to what it was when the grid first loaded.

Now, as for how I've landed on this thus far, I've decided to add the directive and take a look around at what is on the object if I don't define any of the other bits. There is a reset() method exposed on the SelectionDirective that, when I call it, actually appears to do what I want. The current state of which rows are selected is completely cleared and the grid for all intents and purposes is initialized with regards to selection state.

However, looking at https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/#toc-selectiondirective/ I do *not* see this documented. Am I going about this simple operation the right way?

Just to reiterate the simplicity, I literally just need "call a method -> zero rows are selected in Grid <xyz>", not any logic iterating over selections, not any complex management of what's selected across pages, any of that, literally just "selections cleared". Given that the JavaScript version of the grids has clearSelection(), I would think that there is some sort of succinct path without mountains of configuration involved to do the same thing here. If I really have to draft up all sorts of stuff based on specifics of objects, define my own selection handling for the selectedKeys collection management too, etc. I'll do it, but I feel like that is overkill for what I'm trying to achieve.

Thoughts?

**Comment by PaskalevStoyan** [comment]
Hello @gilmorem560,

Thanks for the thorough observation which you provided. Indeed the only way to clear the selection is by using the [kengoGridSelectBy](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/#toc-selectiondirective/) directive by emptying the [selectedKeys](https://www.telerik.com/kendo-angular-ui/components/grid/api/SelectionDirective/#toc-selectedkeys). 

I've prepared a short StackBlitz to demonstrate the said above:

https://stackblitz.com/edit/angular-xlafln?file=src%2Fapp%2Fapp.component.ts

This being said, I would suggest to submit a feature request in our Feedback portal through here: https://feedback.telerik.com/kendo-angular-ui

As this repository is for bug reports only, if you have any questions about using the Kendo UI for Angular components, please use our [support system](https://www.telerik.com/account/support-tickets).
