### ISSUE TITLE
[DatePicker] Selecting the DatePicker content with Ctrl + A and changing its value leads to unexpected results

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4086]
**Describe the bug**
Currently, the first time the user selects the content of the DatePicker and changes the value, the component produces a correct result. However, reselecting the content with Ctrl + A and changing the value leads to unexpected output. 

**To Reproduce**
1. Create a DatePicker component. 
2. Click inside the DatePicker input field to get the "month/day/year" placeholder.
3. Select the content with the keyboard shortcut(Ctrl + A).
4. Enter a valid date (e.g. "01/01/2020").
5. Select this date field again with CTRL+A and enter the same date again ("01/01/2020").

Please, check out the following demo: https://stackblitz.com/edit/angular-rm7jns

**Expected behavior**
Reselecting the content and modifying the value should lead to the expected date inputted by the user.

**Screenshots**
Please, check out the following screen recording: https://www.loom.com/share/430eb3f604c640a0ab508ebe55e0311e?sid=25f97d58-0779-412a-92f5-e501f2ce7515

**Comment by JoomFX** [comment]
closing in favor of https://github.com/telerik/kendo-angular/issues/3409
