### ISSUE TITLE
[editor] selecting cells in a table in the editor throws error

### ISSUE THREAD

**Issue by hannecolaers** [telerik/kendo-angular#4095]
**Describe the bug**
Selecting cells in a table in the editor crashes the editor.

```
Error: Cannot read properties of undefined (reading 'localsInner')
```

**To Reproduce**
Add a table to the Kendo editor, it doesn't matter if it's small or large.
Try to select some cells.

Started from the toolbar tools example:
https://stackblitz.com/edit/angular-frtzwa?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
No error, it's possible to select cells.

**Screenshots**

![editor-table](https://github.com/telerik/kendo-angular/assets/25689425/8cc3a806-e037-447f-af92-a254f8819eca)

**Browser**
 - OS: macOS
 - Browser: Chrome
 - Version:tried on 13.2.1 and 13.4.0

**Comment by yanmariomenev** [comment]
Please test this issue on a local project, as it seems to be specific to the StackBlitz environment. It could be related to some conflict between StackBlitz and ProseMirror, not to Kendo UI for Angular Editor component. If that is the case, this won't be considered a bug.

Sample project for testing:
[editor.zip](https://github.com/telerik/kendo-angular/files/12535202/editor.zip)

**Comment by hannecolaers** [comment]
We have the issue in our Angular project, not only in StackBlitz, but it looks like ProseMirror already fixed the issue: overriding the version of `prosemirror-view` to `1.31.7` in our project instead of `1.31.5` fixes it.

**Comment by yanmariomenev** [comment]
Thank you for the update.

I am glad that you were able to resolve the issue by updating the prosemirror-view. It is interesting that you have the issue in your local project as I wasn't able to reproduce it in mine.

I will keep track if other people report similar issues and at some point, we will also update our Editor to use 1.31.7.
