### ISSUE TITLE
[MultiSelectTree] breaks when you use heterogenous data binding & tags for removing selection from items.

### ISSUE THREAD

**Issue by gultyayev** [telerik/kendo-angular#4099]
**To Reproduce**

1. Open the official documentation https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselecttree/data-binding/#toc-heterogenous-data
2. Select a whole group
3. Start deselecting items using tags
4. Notice errors in the console and how the input eventually gets broken

This does not happen if you de-select items using the dropdown, though.

**Expected behavior**
It should work the same way it does when you un-select using dropdown (i.e. it should not break)

**Screenshots**

https://github.com/telerik/kendo-angular/assets/22374911/1c1f0e6c-e7c1-4e2b-a4fd-f322d3e3991f

**Browser**
 - OS: MacOS
 - Browser: latest versions of Chrome, Safari

**Comment by gultyayev** [comment]
https://github.com/telerik/kendo-angular/assets/22374911/68d65296-8901-4b48-915e-b9c3de72d021

Just found a bit more to the strange behavior even when you use the dropdown only. It may be related.

**Comment by svetq** [comment]
Fixed in v 14.0.0
