### ISSUE TITLE
Dropdown list in grid editor display issue

### ISSUE THREAD

**Issue by yanbu0** [telerik/kendo-angular#410]
![image](https://cloud.githubusercontent.com/assets/26099646/24168449/103dd0e8-0e2f-11e7-8a71-2f7fc07d4536.png)

The dropdown list does not show past the end of the grid when used as an editor in-line.  My html is:

![image](https://cloud.githubusercontent.com/assets/26099646/24168979/022178c8-0e31-11e7-8788-729678435b09.png)

**Comment by ipeshev** [comment]
@yanbu0 we have working example of dropdown inside grid http://plnkr.co/edit/f0mQftpxywemUt9cXnub?p=preview, could you provide a bit more code ?

**Comment by yanbu0** [comment]
That plunker doesn't work, at least for me, it gets stuck on Loading....
![image](https://cloud.githubusercontent.com/assets/26099646/24215133/aaa8645a-0eec-11e7-8846-61a753d4736e.png)

I believe I have up to date versions of the components, see package.json below.  What else would you want?
![image](https://cloud.githubusercontent.com/assets/26099646/24215325/469c7efa-0eed-11e7-8648-3091df86af67.png)

**Comment by yanbu0** [comment]
Also, it only appears to be an issue when paging is enabled.  Once I turned off paging, the dropdown list and autocomplete were visible past the end of the grid.
![image](https://cloud.githubusercontent.com/assets/26099646/24215664/50f16838-0eee-11e7-9ce5-4b3112a00458.png)

**Comment by ipeshev** [comment]
Could you check this [link](http://plnkr.co/edit/vJdda5VYXRdsqTrA3udq?p=preview)

**Comment by yanbu0** [comment]
Still stalls out at the Loading... bit.

**Comment by ipeshev** [comment]
@yanbu0 is there some error in the console - F12 ?

**Comment by zhao125787935** [comment]
@ipeshev  I also cannot see the UI.  There are some errors.
![image](https://cloud.githubusercontent.com/assets/15974161/24492949/9da75698-155f-11e7-990d-584954aa54f4.png)

**Comment by ipeshev** [comment]
Sorry we had some references to internal resources , could you check [this one](http://plnkr.co/edit/jmZxy2YoICUdZmsq2KVs?p=preview)

**Comment by yanbu0** [comment]
Checked the link again today and it does work for me now.  Not sure if anything changed.  The Plunker doesn't show what version number of the grid you are using, can you let me know and I will try with that version?  I will try to spin up a grid using your exact config today as well.

**Comment by yanbu0** [comment]
Ok, figured it out.  If you remove the `[scrollable'="'none'"`, that is what breaks it.

**Comment by yanbu0** [comment]
This works:
![image](https://cloud.githubusercontent.com/assets/26099646/24515948/8f42c3b0-1525-11e7-8615-4cc09e491373.png)
![image](https://cloud.githubusercontent.com/assets/26099646/24516122/154b2c04-1526-11e7-8cca-e04efd938cd7.png)



This does not:
![image](https://cloud.githubusercontent.com/assets/26099646/24515997/bad44b02-1525-11e7-8ae2-7235f52774d4.png)
![image](https://cloud.githubusercontent.com/assets/26099646/24516074/efe19c50-1525-11e7-97c5-832b1d153a94.png)

**Comment by gyoshev** [comment]
@yanbu0 we can confirm that this is a bug when nesting components with popups in a scrollable grid. I am afraid that at this time we do not have a workaround other than setting scrollable other than `none`, or setting a height on the grid so that it accommodates the popup height.

For more background on the issue, it is caused because the popups use `position:fixed` and are placed in a container with CSS transitions. We are still looking for options on how to solve the problem.

**Comment by mogwai1** [comment]
BTW, for now we use workaround for this issue with datepicker (didn't check on dropdown).
just add this style
>>>.k-grid div.k-grid-content>table[style] {
   transform: none !important;
}

**Comment by gyoshev** [comment]
@mogwai1 Indeed, this workaround is acceptable, as long as you don't use virtual scrolling. It will work on all popups.

**Comment by tsvetomir** [comment]
The bug should be fixed in v1.0.10 of kendo-angular-dropdowns
