### ISSUE TITLE
[editor] resizing table columns can make columns invisible

### ISSUE THREAD

**Issue by hannecolaers** [telerik/kendo-angular#4100]
**Describe the bug**
Table in Kendo-editor
When resizing columns it's possible to push columns 'outside of' the table. It's confusing for people who don't realise what happened because it looks like adding a column doesn't work anymore because they don't see the new column. 

**To Reproduce**

In toolbar tools [example](https://www.telerik.com/kendo-angular-ui/components/editor/tools/): 
![invisible-columns](https://github.com/telerik/kendo-angular/assets/25689425/45cc91d0-7d96-4e92-ae73-05085da84c05)

I've tried to reproduce the same behaviour in the [prosemir-tables example](https://prosemirror-tables.netlify.app), but there the table grows when making the columns wider so that's why I'm logging it here.

**Expected behavior**
All columns are always visible even when making a column very wide. 
Adding a column always adds a visible column.

**Browser**
 - OS: macOS
 - Browser Chrome, FireFox
 - Version: latest

**Comment by slavenai** [comment]
Hi @hannecolaers , 

This behavior is expected as when resizing a column, the other columns overlap each other. To visualize them again, the resizing should be done in the opposite direction:

https://github.com/telerik/kendo-angular/assets/67437411/5abc0ed2-d096-4bf4-9c7d-6366e0b72d3e
