### ISSUE TITLE
Multiselect initial load failling

### ISSUE THREAD

**Issue by pabloelca** [telerik/kendo-angular#4101]
Issue: When we have a multiselect form field, whose data is taken from a filterable service, and select any value. If is requiered to preload data at the init of the component, it's failling.

https://stackblitz.com/edit/angular-h2q34m-hatjg4?file=src%2Fapp%2Fapp.component.ts

How to reproduce:
- Add to the multiselect any value.
- Refresh browser and wait until data is loaded from local storage.
- The multiselect didn't maintain the selected values because the initial multiselect data is empty.

Is added the allowCustom property to the multiselect component in order to try to prevent this issue and allow to load at the init of the component, but the issue is not prevent with this change how is expected even though is not requiered that the value is contained in the data.

How to reproduce:
- Add to the multiselect any value.
- Refresh browser and wait until data is loaded from local storage.
- The multiselect didn't maintain the selected values because the initial multiselect data is empty.
- Filter in the input to obtain the previous selected value, and it is automatically added to the multiselect. 

If this test is reproduced with a custom value don't contained in the data, is never included to the multiselect.

**Comment by svetq** [comment]
@pabloelca the demonstrated scenario is custom and doesn't show a specific issue with the MultiSelect component. Instead, the undesired behavior is caused by the specific implementation. Feel free to [open a private support thread](https://www.telerik.com/blogs/how-to-submit-a-support-ticket) on the matter.
