### ISSUE TITLE
Moving Series / Editing Does Not Render Recurring Events Correctly

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4102]
**Describe the bug**

The scheduler component is currently experiencing a bug where moving a series does not render the events correctly. When dragging and editing the series, the dragged event disappears upon confirmation of the edit, while the rest of the series data is updated but not rendered correctly.

**To Reproduce**

1. Open either of the following links:

- [Reactive Forms Example](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-reactive-forms/)
- [Editing Directives Example](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/editing-directives/)

2. Create a series with a simple event, set it to be weekly recurring, and then save the event.

3. Drag and drop one of the events to another day and confirm the move for the entire series.

4. The event disappears, and the rest of the series remains where it was. (Expected: All events should be displayed on the other day.)

**Recording**

https://github.com/telerik/kendo-angular/assets/49076727/5ee77f74-abfc-4d7a-a3e3-78bcf759e183

**Comment by phil-prodot** [comment]
When do you start fixing this?

**Comment by slavenai** [comment]
Fixed in `v16.3.0` of `kendo-angular-scheduler` package.
