### ISSUE TITLE
[Grid] Edit buttons misalignment

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4103]
**Describe the bug**
Currently, when the user clicks the Edit button, the Update and Cancel buttons appear correctly but there seems to be some odd misalignment between these buttons and the Edit and Remove buttons on the other rows.

**To Reproduce**
1. Create a Grid component.
2. Implement the editing functionality.
3. Click the Edit button.

Please, check out the following StackBlitz demo: https://stackblitz.com/edit/angular-bnprhy

**Expected behavior**
The Update and Cancel buttons should be aligned to the Edit and Remove buttons on the other rows of the Grid.

**Screenshots**
Current behavior:
![image](https://github.com/telerik/kendo-angular/assets/108671673/7e2f5e32-1c1a-41a5-bf01-13258408936a)

Expected behavior: 
![image](https://github.com/telerik/kendo-angular/assets/108671673/73b945bc-b76c-46c3-a04b-92129a2842c3)

**Additional context**
Workaround: https://stackblitz.com/edit/angular-edpwet

**Comment by Raisolution** [comment]
Fix to be tracked in the `kendo-themes` repository https://github.com/telerik/kendo-themes/issues/4702
