### ISSUE TITLE
[MultiSelectTree] Items cannot be removed when lazyLoading is set to true

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4105]
**Describe the bug**
Currently, when the lazyLoading option of the MultiSelectTree component is set to true and the user tries to remove a single child item, an error is thrown on the console and the item remains selected.

**To Reproduce**
1. Create a MultiSelect component.
2. Set the lazyLoading option to true
3. Remove a child item using the X icon. 

For reference, please check out the following StackBlitz demo: https://stackblitz.com/edit/angular-ert1j4

**Expected behavior**
Clicking on the X icon should remove the item and no error should be thrown on the console.

**Screenshots**
<img width="776" alt="image" src="https://github.com/telerik/kendo-angular/assets/108671673/ce608851-db57-46d9-9af8-7db01a18a0a5">

**Additional context**
It seems like the component behaved according to the expectations in version 5.5.0 of the Dropdowns: https://stackblitz.com/edit/angular-d1fgra-zd8wak

**Comment by tswetti** [comment]
Fixed in [v14.3.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v14.3.0)
