### ISSUE TITLE
Multi select group tag does not show when selected item has a value of null

### ISSUE THREAD

**Issue by jstransparity** [telerik/kendo-angular#4108]
**Describe the bug**
Using the kendoMultiSelectSummaryTag directive on a kendo-multiselect, the tag does not appear if the selected drop-down item has a value of null.

**To Reproduce**
Select the 'NullValue' item in the dropdown on the following example:

https://stackblitz.com/edit/angular-6kcefk-kxegp4?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
I would expect the tag to show "1 item selected".

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 116.0.5845.188

**Comment by tswetti** [comment]
Fixed in v.14.0.0
