### ISSUE TITLE
[Scheduler] 24-hour event is converted to All day event although the flag is equal to false 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4110]
## Describe the bug
Setting the `isAllDay` property to _false_ when the event is longer than 24h, still displays the event in the all-day slot.
```ts
{
  id: 15,
  title: 'Attending HR Conference',
  start: new Date('2013-06-25T00:00:00.000Z'),
  end: new Date('2013-06-26T00:00:00.000Z'),
  isAllDay: false,
}
```

## Steps to Reproduce
1. Create a new event longer than 24 hours
2. Set`isAllDay: false`
3. Check the scheduler

https://stackblitz.com/edit/angular-gyhn6r?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fevents-utc.ts

## Expected Behavior
The event should **not** be located in the `All day` row. It should fill in all respective time slots.

**Comment by tswetti** [comment]
Also reported in private support thread 1625951
