### ISSUE TITLE
[Grid] Detail expand/collapse column too wide when all column widths are defined

### ISSUE THREAD

**Issue by JBildstein** [telerik/kendo-angular#4114]
**Describe the bug**
When enabling master/detail grids the expand/collapse column is too wide if all column widths are defined and there is enough space left.

**To Reproduce**
Open the example and make the window wide enough so that all columns fit.
Note how the expand/collapse column is too wide and/or starts to get bigger as you make the window larger.

If you remove the width from any column, the size of the expand/collapse column is as expected.

https://stackblitz.com/edit/angular-uf5uec?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The expand/collapse column should always have the same, smallest possible size.

**Screenshots**
With all column widths defined:
![Grid-Bug-All-Widths-Defined](https://github.com/telerik/kendo-angular/assets/12777835/df8d3b13-0a61-45f4-b1c3-2bdc8f20ea6d)

With only some column widths defined:
![Grid-Some-Widths-Defined](https://github.com/telerik/kendo-angular/assets/12777835/294e30ea-de11-46f7-b83d-e89532190474)

**Browser**
 - OS: Windows, Linux
 - Browser: Chrome/Chromium
 - Version: 13.5

**Comment by slavenai** [comment]
Hi @JBildstein ,

When all columns have their width explicitly set, and the available Grid width is greater than the cumulative widths of all columns, the remaining width is distributed between all columns:
https://www.telerik.com/kendo-angular-ui/components/grid/columns/width/

The expand/collapse column makes no exception, thus the described behavior is expected.

**Comment by unicornflax** [comment]
If `[resizable]="true"` and you manually resize a column, the width of the expand column snaps back to its defined value. I’m not sure what happens to the width values of the cols, but I would expect that all column still have set width values.

First, why is it expected that the expand column also receives a portion of the remaining width?
Second, why does the behavior become inconsistent after you manually resize a column?
