### ISSUE TITLE
Update sample apps and standalone apps

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4115]
**Describe the bug**
The **[ASP.NET Web Api](https://github.com/telerik/kendo-angular/tree/master/examples-standalone/aspnetwebapi-data#using-the-suite-with-aspnet-web-api)** sample app needs an update in order to comply with the supported versions of Angular and .NET Core.

Current versions of the app:
Angular: v8
.NET Core: v5

See the private support thread **1625321**

**Comment by Raisolution** [comment]
Closing this issue, as the current applications will be recreated with the new .NET Core template.
