### ISSUE TITLE
Dropdown Container Overlapping Issue

### ISSUE THREAD

**Issue by DhanushS212003** [telerik/kendo-angular#4116]
**Describe the bug**
When I click on the 'Open In' tab within the table diagram on the provided webpage (https://www.telerik.com/kendo-angular-ui/components/grid/accessories/no-records-template) I observe that the dropdown container within the header section is overlapping or conflicting with other elements. This results in an undesirable visual rendering where the dropdown menu appears to interfere with the header, impacting the user experience.

**To Reproduce**
To resolve this matter, apply a z-index value of 1 to the <div> element with the class name 'bOABqi.' This element can be found in the code around lines 480 to 490.

**Expected behavior**
The dropdown container should remain visually distinct from and not overlap with any other elements.

**Video**
https://github.com/telerik/kendo-angular/assets/116268711/e797ec71-7f9b-4565-b6cf-1cbd2135df5a

**Comment by PaskalevStoyan** [comment]
Hi @DhanushS212003,

Thanks for the reported issue. 

As this is related to our documentation website, we will transfer the issue there (its a private repo), but will leave this one open for visibility and when we fix the problem at hand, we will update this issue and close it.

**Comment by Raisolution** [comment]
Fixed with latest documentation design update.
