### ISSUE TITLE
Unable to get GBP £ currency symbol with the LOCALE_ID en-GB

### ISSUE THREAD

**Issue by Cognition3142** [telerik/kendo-angular#412]
Following the example in the Kendo UI for Angular 2 docs for Internationalization, I am able to change my Applications culture and currency to bg-BG just like in their example. The setup can be seen [in their docs][1] and [this plunker][2].

I would like to get my App to use the en-GB and therefore use £ rather than the default $. But when I change the LOCALE_ID to en-GB and load in the cldr **en** data I just get dollars. [Plunker][3]

Has anyone been able to get the £ symbol and know what I am missing?

Here is the app.module.ts:

    import { LOCALE_ID, NgModule }      from '@angular/core';
    import { BrowserModule } from '@angular/platform-browser';
    
    import { AppComponent }   from './app.component';
    
    import { load, IntlModule } from '@progress/kendo-angular-intl';
    
    load(require("cldr-data/main/en/numbers.json"),
         require("cldr-data/main/en/currencies.json"),
         require("cldr-data/main/en/ca-gregorian.json"),
         require("cldr-data/main/en/timeZoneNames.json"),
         require("cldr-data/supplemental/likelySubtags.json"),
         require("cldr-data/supplemental/currencyData.json"),
         require("cldr-data/supplemental/weekData.json"));
    
    @NgModule({
      imports:      [ BrowserModule, IntlModule ],
      providers:    [
        { provide: LOCALE_ID, useValue: 'en-GB' }
      ],
      declarations: [ AppComponent ],
      bootstrap:    [ AppComponent ]
    })
    
    export class AppModule { }

  [1]: http://www.telerik.com/kendo-angular-ui/components/internationalization/
  [2]: http://plnkr.co/edit/7jnQLgwTNPwcfWCf6Gik?p=preview
  [3]: http://plnkr.co/edit/lZsuBeNSEr8vk1PTzdjO?p=preview

**Comment by ggkrustev** [comment]
@Cognition3142, in general you will need to load the culture with the proper **teritory** information. "en" defaults always to "en-US" (stated in the docs). You will need to load the 'en-GB' culture.

The plunker, however, won't load the en-GB culture correctly and the cause most probably is due to an old `@progress/kendo-angular-intl` package.

I tested the demo in a standalone Angular project and the "£" symbol was shown correctly. I would suggest you check it locally. Follow these steps for easier setup:
1. https://github.com/ggkrustev/ng2-test-demo/tree/intl
2. `npm install`
3. `git checkout intl`
4. `npm start`

This will start the test page with "en-GB" culture.

**Comment by Cognition3142** [comment]
@ggkrustev thank you for this! Using your project I was able to work out where the issue comes from.
It turns out that the order that you load the cldr Json files actually matters. If you load the en-GB locale files first then it seems that the supplemental ones will override them.

So if you change the load in your app.module.ts to the following then it will no longer work:

`load(
   // locale data
   require(`cldr-data/main/en-GB/numbers.json`),
   require(`cldr-data/main/en-GB/currencies.json`),
   require(`cldr-data/main/en-GB/ca-gregorian.json`),
   require(`cldr-data/main/en-GB/timeZoneNames.json`),

   // supplemental data
   require(`cldr-data/supplemental/likelySubtags.json`),
   require(`cldr-data/supplemental/weekData.json`),
   require(`cldr-data/supplemental/currencyData.json`),
);`

I suppose this is may be a bug since loading non-en locales first seems to work. The supplemental files probably hold some en locale data which takes precedence if loaded second. If not a bug then the docs should be modified as all the examples load the locale first.

I updated my [Plunker](http://plnkr.co/edit/lZsuBeNSEr8vk1PTzdjO?p=preview) app.module.ts to show this.

**Comment by ggkrustev** [comment]
@Cognition3142, no problem at all! I'm glad that you was able to resolve the issue.
 
As to the scripts order statement, **the order is irrelevant**, as it can be seen by the `load` implementation:
https://github.com/telerik/kendo-intl/blob/master/src/cldr/load.js#L17

The test demo also loads the `supplemental` scripts first and it still works:
https://github.com/ggkrustev/ng2-test-demo/blob/intl/src/app/app.module.ts#L9

I'm sure that the issue that we observe in the Plunker is related to the version of `kendo-angular-intl` package fetched from the site. Once we use the latest official version `0.11.1`, the culture loading works just fine.

Let me know if I'm missing smth.

**Comment by Cognition3142** [comment]
@ggkrustev sorry I realise my comment above wasn't clear (or formatted!), but I agree that looking at the code it does seem that the order doesn't matter.

However, I've set up a new github repo which shows it does:
https://github.com/Cognition3142/KendoInternationalizationOrder

I cloned your code (so the versions are up to date) and only changed the load order. If you run it up it won't load and if you check the console in your browser then you can see it has an error about not being able to get GB data. If you put the order back then it works.

**Comment by ggkrustev** [comment]
@Cognition3142, you are absolutely right! Somehow, I missed to test the other way around :).

The documentation is updated in the repos:
https://github.com/telerik/kendo-intl

And the next site update will include the documentation changes.

Thanks for taking the time to reproduce the issue for us!

P.S. Please close the thread, if you consider the issue resolved.
