### ISSUE TITLE
[TreeList] Resizing TreeList locked column groups causes misalignment

### ISSUE THREAD

**Issue by tswetti** [telerik/kendo-angular#4123]
**Describe the bug**
When the TreeList has two or more locked column groups, resizing any of the columns causes misalignment. Sometimes the drag handle disappears until another column is resized.

https://github.com/telerik/kendo-angular/assets/65012268/cda1895f-801a-4b8a-8e4d-4de3d6779514

**To Reproduce**
https://stackblitz.com/edit/angular-pkmreb?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
The columns are aligned properly.

**Comment by destus90** [comment]
Duplicate of #4069 ?
