### ISSUE TITLE
[DateInputs] autoFill doesn't trigger a change in the form value

### ISSUE THREAD

**Issue by Julian-B90** [telerik/kendo-angular#4128]
**Describe the bug**
If i enable the autoFill option, enter the month and day and then leave the input no change is triggered. In this [example](https://stackblitz.com/edit/angular-8kfeve-c3fiif?file=src%2Fapp%2Fapp.component.ts)  you can see that there is no date was set in the ngModel user.birthDate.

**To Reproduce**
Open - https://stackblitz.com/edit/angular-8kfeve-my3njl?file=src%2Fapp%2Fapp.component.ts
Fill the month and blur the component for the autoFill option to work. This will result in an empty birthDate value.

**Comment by stnikolova** [comment]
The fix is available in **v14.2.0** of `@progress/kendo-angular-dateinputs`
