### ISSUE TITLE
Kendo Grid Error when using  Angular 2 with webpack 

### ISSUE THREAD

**Issue by sumchat** [telerik/kendo-angular#413]
When I am trying to drag a column header to drop at the top for group by operation, it is throwing the below error. The error is thrown when I am using webpack. I am testing with Visual Studio 2017. 

Unhandled exception at line 532, column 13 in http://localhost:65127/dist/app.bundle.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'remove'

I am wondering is it an issue or is it something I am doing wrong..

**Comment by rkonstantinov** [comment]
Could you please verify that you are using the latest (0.19.6) version of the kendo-angular-grid package.

**Comment by sumchat** [comment]
You are right. I was using a older version 0.10.0 . When I installed the latest one the error is not there.
