### ISSUE TITLE
[DateTimePicker] When added into FormGroup, doesn't accept manually set date as valid and doesn't update calendar state

### ISSUE THREAD

**Issue by DanielTakev** [telerik/kendo-angular#4137]
**Describe the bug**
The user is not able to set calendar date via the input field. Even if the date is correct, it's not accepted as valid and it doesn't change the calendar state. 

**To Reproduce**
Open the following template: 
https://stackblitz.com/edit/angular-6cbyfm?file=src%2Fapp%2Fapp.component.ts

  1. Set correct date and time manually
  2. Open the picker

https://github.com/telerik/kendo-angular/assets/56965899/80179508-16f2-46fe-ac49-d11955926d58

**Expected behavior**
The calendar should be set properly with the respective date.

**Note** The issue is reproducible only for `DateTimePickers`, but not for `DatePickers`. Also not reproducible for `DateTimePicker` within a `FormField`.

**Browser**
 - OS: MacOS Sonoma 14.0 
 - Browser: Chrome v.118.0.5993.88

**Relates to**
https://github.com/telerik/kendo-angular/issues/3901

**Comment by DanielTakev** [comment]
After the fix in `common` the issue is still reproducible, so I returned it to `In Progress` column.

**Comment by stnikolova** [comment]
The fix is available in **v14.2.0** of `@progress/kendo-angular-dateinputs`
