### ISSUE TITLE
[Chart] Legend title should be white color when using dark theme

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4138]
**Describe the bug**
The Legend title should change color depending on the loaded swatch from our Kendo Themes. Similar to the Chart [Title](https://www.telerik.com/kendo-angular-ui/components/charts/elements/title/) component.

**To Reproduce**
https://stackblitz.com/edit/angular-plf5xa?file=src%2Fapp%2Fapp.component.ts

**Screenshots**
![Screenshot 2023-10-26 at 14 35 42](https://github.com/telerik/kendo-angular/assets/49076727/0024078e-174f-439b-9f6c-432b20d37c4b)

**Workaround**
Adjust the [color](https://www.telerik.com/kendo-angular-ui/components/charts/api/LegendTitle/#toc-color) property of the title depending on the swatch.

**Feedback portal**
https://feedback.telerik.com/kendo-angular-ui/1627977-the-chart-legend-s-title-is-black-when-using-a-dark-theme

**Comment by tswetti** [comment]
Fixed in [v15.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.0.0)
