### ISSUE TITLE
group error

### ISSUE THREAD

**Issue by SmallShrimp** [telerik/kendo-angular#415]
I use the grid of grouping,it can group but i cannot remove the grouped item,I click the close icon but it do nothing!

**Comment by rusev** [comment]
We have a runnable example in this article which seems to be working properly - http://www.telerik.com/kendo-angular-ui/components/grid/grouping/groping-basics/

**Comment by SmallShrimp** [comment]
yes i know!
my code :
template>
![Uploading 1.png…]()
config>
![Uploading config.png…]()
loaddata>
![Uploading loaddata.png…]()
groupchang>
![Uploading groupchang.png…]()

**Comment by mast3rd3mon** [comment]
Is there a fix for this? It keeps cropping up in apps that i make but only appears to go away if i fully rebuild the grid

**Comment by tsvetomir** [comment]
Do you have a list of the necessary steps to reproduce the issue? A running sample in plunkr would be ideal.

**Comment by mast3rd3mon** [comment]
thats the issue, its unpredictable so reproducing it would be hard to do
