### ISSUE TITLE
[DateTimePicker] Input value not handled properly

### ISSUE THREAD

**Issue by Aiiden98** [telerik/kendo-angular#4158]
I already reported something similar before on the issue #4144... after updating the newer version it seemed to be fixed, but if you try to valorize the time input and the go back and modify the date value in the first input, I have the problem back again

**Comment by stnikolova** [comment]
Hi @Aiiden98,

Thank you for the report. Could you please provide further details about how is this reproduced? For example what component/s exactly are used? It does not become clear if you're only using the DateTimePicker or the TimePicker as well. Is there any specific configuration that needs to be applied? How exactly are you updating the value - selection/typing/keyboard navigation?

Thank you in advance.
