### ISSUE TITLE
KendoGrid autoFitColumns makes header text wrap

### ISSUE THREAD

**Issue by jstransparity** [telerik/kendo-angular#4160]
**Describe the bug**
When calling autoFitColumns on the grid component, the columns will be resized to be narrower than the header text, causing wrapping.

**To Reproduce**

https://stackblitz.com/edit/angular-thpap1-tpz63c?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Docs state that: _"Adjusts the width of the specified columns to fit the entire content, including headers, **without wrapping**. If no columns are specified, autoFitColumns is applied to all columns.The method must be executed after the Grid is already populated with data."_
I would expect the header not to wrap.

**Comment by slavenai** [comment]
Hi @jstransparity ,

In the provided demo the Grid's header cells content is additionally styled with custom CSS: `white-space: normal;` , thus the discrepancy. Removing the custom CSS styling yields the expected result:

https://stackblitz.com/edit/angular-thpap1-wpa9c6?file=src%2Fapp%2Fapp.component.ts

**Comment by jstransparity** [comment]
Hi @slavenai,

The custom CSS is intentional, and is to make the header text wrap in the same way as the row cell text.
I do not think this issue should be closed, as the functionality does not match the docs.

Please re-consider this.

**Comment by slavenai** [comment]
Hi @jstransparity ,

Please use our [support system](https://www.telerik.com/account/support-tickets) if you need any further assistance with specific configuration or setup.
