### ISSUE TITLE
multiselect scrolls to last selected item when popup is opened

### ISSUE THREAD

**Issue by kemmis** [telerik/kendo-angular#4161]
**Describe the bug**
When multiselect popup is opened, the list scrolls to the last selected item. For most cases, the user expects to see the top of the list. This might not seem problematic when your list only contains a few options (like in the doc examples), but when you have 50 or more options and it's easy to have them all selected (by adding something like a "select all" option), then this becomes a strange and disorienting experience for the user.

**To Reproduce**

1. Go to my example here: [https://stackblitz.com/edit/angular-n2cq9m?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-n2cq9m?file=src%2Fapp%2Fapp.component.ts)
2. Click inside the multiselect to make the popup open.
3. See that the list is scrolled to the bottom.

**Expected behavior**
I'm at the top of the list when the popup opens.

If this is intended behavior, then I'd like to request a feature to allow the developer to disable this behavior.

**Comment by stnikolova** [comment]
Hi @kemmis,

Indeed the described behavior is considered default and is expected.

As this repo is for bug reports only, please use our Feedback Portal to submit a feature request with a brief explanation for the desired functionality, and what common use cases it would be suitable for:

https://feedback.telerik.com/kendo-angular-ui/

Thank you in advance.
