### ISSUE TITLE
[Sortable] Navigation using the `enter` key is not functioning 

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4162]
**Describe the bug**
When navigation is enabled, pressing the `enter` key fails to focus on the first sortable item.

**To Reproduce**
Open our navigation example and try to focus the first item using the `enter` key:
https://www.telerik.com/kendo-angular-ui/components/sortable/keyboard-navigation/

**Comment by stnikolova** [comment]
As per the Sortable component's keyboard navigation specification, `Enter` focuses the first focusable element within the sortable item's **content** (if any, e.g. input) and not the sortable item itself, which is working as expected. Please refer to the following example: https://stackblitz.com/edit/angular-ywyesa
