### ISSUE TITLE
MultiSelectTree displays "No data found" even though data is displayed in Manual filtering

### ISSUE THREAD

**Issue by hetalishah** [telerik/kendo-angular#4164]
**Describe the bug**
I have encountered an issue with the MultiSelectTree component. It sometimes happens that "No data found" information is displayed, even though data is displayed just above the message.

**To Reproduce**
It's possible to reproduce this on your own example for [manual filtering](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselecttree/filtering/#toc-manual-filtering).

First, you need to type for example "asd" into the filter box, and then remove the last letter - and the situation above should happen.

**Expected behavior**
The "No data" block should not be displayed when data is available

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/25337886/cc658fc3-fe08-4ab7-9fe8-4ab8a30bc361)

**Comment by svetq** [comment]
Closing this in favor of https://github.com/telerik/kendo-angular/issues/3412
