### ISSUE TITLE
cannot style k-grid-edit-row

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#417]
1. press the red edit button
2. the edited row gets the k-grid-edit-row class
4. according to style definitions   background-color is red. but...

[cannot style k-grid-edit-row](http://plnkr.co/edit/c1Oxh3XRKuqZQXD5aTJc?p=preview)

**Comment by rkonstantinov** [comment]
You will need to set view encapsulation to `None` and use higher specificity for the CSS selector in order to override the existing background-color value.
```ts
@Component({
  selector: 'my-app',
  encapsulation: ViewEncapsulation.None,
  template: ` ....  `,
    styles:[`
    .k-grid tr.k-grid-edit-row{
      background-color: red;
    }
    .k-grid{
      background-color: yellow;
    }`,
  ]
})
```

**Comment by gilior** [comment]
**works**.
but why style definitions of `k-grid` works out of the box and `k-grid-edit-row` requires extra care?

**Comment by rkonstantinov** [comment]
Changing the [ViewEncapsulation](https://angular.io/docs/js/latest/api/core/index/ViewEncapsulation-enum.html) mode is required as otherwise the styles will be applied only on the top-level elements.
