### ISSUE TITLE
[Scheduler] "Show full day" button doesn't display all events in the timeline view

### ISSUE THREAD

**Issue by SumekQQ** [telerik/kendo-angular#4173]
I found the same issue like #2609  on version 4.3.7 but in scheduler views with timeline (day or week).

To reproduce please check the following example:
[https://stackblitz.com/edit/stackblitz-starters-9jaj2k?file=src%2Fmain.ts](https://stackblitz.com/edit/stackblitz-starters-9jaj2k?file=src%2Fmain.ts)

1. Click 'Timeline' button
2. You should see event outside business hours
3. Switch to business hours, then switch to full day.
4. The events outside the events are not visible.

**Comment by tswetti** [comment]
Fixed in [v15.2.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.2.0)
