### ISSUE TITLE
kendoGridHeaderTemplate within kendo-grid-command-column 

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#418]
if i define kendoGridHeaderTemplate inside kendo-grid-command-column, all the rows in the column gets the kendoGridHeaderTemplate.
 [domineering kendoGridHeaderTemplate ](http://plnkr.co/edit/nOSzSY4u9o46Swl0FsgA?p=preview)

**Comment by rusev** [comment]
Indeed this is a bug. We will do our best to address it shortly.

**Comment by rusev** [comment]
Grid package version 0.25.2 will address this issue. However there is a breaking change required to make this work. From now on we will have to use `kendoGridCellTemplate` directive to define command column content. Fixes https://github.com/telerik/kendo-angular/issues/418.

Before:
```
<kendo-grid>
   <kendo-grid-command-column title="command">
     <ng-template>
       <button kendoGridEditCommand class="k-primary">Edit</button>
     </ng-template>
   </kendo-grid-command-column>
</kendo-grid>
```

After:
```
<kendo-grid>
   <kendo-grid-command-column title="command">
     <ng-template kendoGridCellTemplate>
       <button kendoGridEditCommand class="k-primary">Edit</button>
     </ng-template>
   </kendo-grid-command-column>
</kendo-grid>
```
