### ISSUE TITLE
[Grid] Virtual scrolling with an expanded master grid and navigation turned on causes undesired scrolling behavior 

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4182]
**Describe the bug**
If the Grid is set up with virtual scrolling, a master grid, navigation, and expanded rows, it will create a scrolling issue when you focus on one of the master Grid rows and then navigate the Grid.

There might be some relation with - https://github.com/telerik/kendo-angular/issues/3867

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-v7zivc-bagunl?file=src%2Fapp%2Fapp.component.ts
2. Focus on the first expanded row and then scroll the Grid up and down to see the scrolling behavior.

**Comment by slavenai** [comment]
The observed behavior is expected when scrolling triggers paging - when the data item associated with the currently active row is no longer available, the focus is moved to the first possible item present in the DOM. We will update our documentation accordingly.
