### ISSUE TITLE
[Splitter, TextArea] Using the component in an Angular application that utilizes SSR leads to errors

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4188]
**Describe the bug**
Currently, when developers create a Splitter component that has more than one pane inside an Angular application that utilizes server-side rendering, an error is being thrown on the console.

**To Reproduce**
1. Create an Angular SSR application.
2. Create the Splitter component so that it has more than one pane.
3. Run the application and open the DevTools console.

Please, check out the attached demo project: 
[splitter-component-demo.zip](https://github.com/telerik/kendo-angular/files/13819429/splitter-component-demo.zip)

**Expected behavior**
Creating a Splitter component with more than one pane inside an Angular SSR application should not throw any errors on the console.

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/108671673/b0ef465e-7ddb-4d35-8312-417d5726ff04)

**Additional context**
Setting **ngSkipHydration** to **true** seems to resolve the errors.

**Comment by slavenai** [comment]
Fixed in `v16.4.0` of `kendo-angular-layout` and `kendo-angular-inputs` packages.
