### ISSUE TITLE
Switch @angular 4.0 : Javascript error

### ISSUE THREAD

**Issue by nlgi** [telerik/kendo-angular#419]
Hi,

I updated angular to official 4.0.0. I've got an error with <kendo-switch> component : 
Cannot read property 'subscribe' of undefined

This line worked perfectly ;
`<kendo-switch [(ngModel)]="show" [ngModelOptions]="{standalone: true}"></kendo-switch>`

Is Angular 4.0 compatibility expected for the coming days ?

Many thanks,

Regards,

**Comment by tsvetomir** [comment]
The support for Angular 4.x is tracked in #346
