### ISSUE TITLE
[Dialog] Dialog wrapped in form closes when hitting enter key

### ISSUE THREAD

**Issue by geo242** [telerik/kendo-angular#4192]
**Describe the bug**
When a dialog/window is wrapped in a form element the dialog/window closes when hitting enter. This is because the close button in toolbar does not have the `type="button"` attribute. Thus the form assumes that the close button is the submit button.

**To Reproduce**
1. Wrap dialog/window in form element and add one text field and a button with the `type="submit"` attribute.
2. Open form and focus the text box
3. Hit enter

https://angular-8vc5rl.stackblitz.io

**Expected behavior**
Submit button should be clicked and dialog/window should remain open

**Screenshots**
N/A

**Browser**
 - OS: All
 - Browser All
 - Version N/A

**Additional context**
N/A

**Comment by mbechev** [comment]
Fixed in version [v15.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.0.0)
