### ISSUE TITLE
Grid selection aggregates doesn't work with delayed data

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4201]
**Describe the bug**

When the data is delayed from a remote server, it messes up with the selection directive and errors out when it has **cellAggregates** enabled.

**To Reproduce**
1. Open - https://stackblitz.com/edit/angular-hjbr9g-zkoqkg?file=src%2Fapp%2Fapp.component.ts or  https://stackblitz.com/edit/angular-hjbr9g-4so58y?file=src%2Fapp%2Fapp.component.ts
2.  Select a cell or use drag selection to get the error (Cannot read properties of undefined (reading '1'))

**Workaround**
Initialize the Grid when the data is available:
https://stackblitz.com/edit/angular-hjbr9g-wwzdby?file=src%2Fapp%2Fapp.component.ts

or initially set the data to an empty array:
https://stackblitz.com/edit/angular-hjbr9g-riz3tn?file=src%2Fapp%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fixed in `v16.11.0`
