### ISSUE TITLE
Error is thrown if style attribute has spaces at the end

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4202]
**Describe the bug**
![image](https://github.com/telerik/kendo-angular/assets/33104481/80321394-cd84-4c36-b491-3ec4f1e840e1)

The error is thrown when there is an unnecessary space at the end of the `style` attribute value:

```html
public value= `<p style="color: red;    "> The Editor enables users to create rich textual content. </p>`;
```

**To Reproduce**
https://stackblitz.com/edit/angular-qapm1z-v3pvxq?file=src%2Fapp%2Fapp.component.ts

**Comment by slavenai** [comment]
Fixed in `v16.1.0` of `kendo-angular-editor` package.
