### ISSUE TITLE
[ListBox] Clicking on a focusable element in the Item Template causes an error

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4205]
**Describe the bug**
When a focusable element is rendered in the Item Template of the ListBox and the user clicks on it, an error is being thrown.

**To Reproduce**
1. Create a ListBox component.
2. Utilize the built-in ItemTemplateDirective.
3. Render a focusable element in the template.
4. Click on the element.

Please, check out the following StackBlitz demo: 
https://stackblitz.com/edit/angular-jhejga-crde2l?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Clicking on the focusable element should not lead to an error on the console.

**Screenshots**
<img width="541" alt="image" src="https://github.com/telerik/kendo-angular/assets/108671673/3bfaf331-06e9-4a90-b513-ce7c5df6d80f">

**Additional Context**
The issue seems to be a regression that started in v12.0.1
Demo for v12.0.0: https://stackblitz.com/edit/angular-jhejga-h2brna
Demo for v12.0.1: https://stackblitz.com/edit/angular-jhejga-uzdsfw

**Comment by DanielTakev** [comment]
`E2E` test has been added to cover the issue.

**Comment by tswetti** [comment]
Fixed in [v15.1.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.1.0)
