### ISSUE TITLE
[Scheduler] Recurrence-Editor fails in 15.0.1 because of SchedulerLocalizationService

### ISSUE THREAD

**Issue by BeniFreitag** [telerik/kendo-angular#4208]
**Describe the bug**
No labels are shown in the recurrence editor component.

```<kendo-recurrence-editor>``` throws error:
> [SchedulerLocalizationService -> SchedulerLocalizationService]: 
  NullInjectorError: No provider for SchedulerLocalizationService!

**To Reproduce**
1. Open the Demo [Custom Edit Form](https://www.telerik.com/kendo-angular-ui/components/scheduler/editing/custom-reactive-editing/)
2. Edit or create a repeating event.
3. The UI shows no labels:
![image](https://github.com/telerik/kendo-angular/assets/6669093/b0458e58-5372-4395-9a1a-8f54f43d7d21)

[Sample with Angular 17.1.2 and Kendo 15.0.1](https://stackblitz.com/edit/kendo-recurrence-editor-1501?file=src%2Fscheduler%2Fscheduler.component.html) using `<kendo-recurrence-editor>`
1. Change Repeat to `Daily` or something
2. Check the console for this error:

> Error: R3InjectorError(Standalone[App])[SchedulerLocalizationService -> SchedulerLocalizationService -> SchedulerLocalizationService]:
> NullInjectorError: No provider for SchedulerLocalizationService!

![image](https://github.com/telerik/kendo-angular/assets/6669093/da4bbaca-4b5b-481d-9abb-1c8b95c5ce92)

**Expected behavior**
Recurrence Editor should load and show labels.

**Additional context**
Worked in Kendo 14.3.0.

**Comment by svetq** [comment]
A fix is available in v 15.0.2-develop.5 of the @progress/kendo-angular-scheduler.

**Comment by tswetti** [comment]
Fixed in [v15.1.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.1.0)
