### ISSUE TITLE
npm ERR! registry error parsing json not able to add dependencies

### ISSUE THREAD

**Issue by mragansh** [telerik/kendo-angular#421]
Access Denied when adding dependencies onto my APP. 
username for kendo : mragansh, email : mragansh.tomar@globalologic.com

C:\Users\mragansh.tomar\Desktop\HITLI\24-3-17-HVP-WEB\hvb-web\hvb-app>npm login
--registry=https://registry.npm.telerik.com/ --scope=@progress
Username: mragansh
Password:
Email: (this IS public) mragansh.tomar@globallogic.com
Logged in as mragansh to scope @progress on https://registry.npm.telerik.com/.

C:\Users\mragansh.tomar\Desktop\HITLI\24-3-17-HVP-WEB\hvb-web\hvb-app>npm view @
progress/kendo-angular-grid versions
npm ERR! registry error parsing json
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3
.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"
/>
npm ERR! <title>403 - Forbidden: Access is denied.</title>
npm ERR! <style type="text/css">
npm ERR! 
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>403 - Forbidden: Access is denied.</h2>
npm ERR!   <h3>You do not have permission to view this directory or page using t
he credentials that you supplied.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mragansh.tomar\AppData\Roaming\npm-cache\_logs\2017-03-27T
09_56_13_631Z-debug.log

**Comment by tsvetomir** [comment]
I'd like to ask you to [submit a support ticket](https://www.telerik.com/account/support-tickets/contact-support-team?pid=1800) for this problem. The issue tracker is public and therefore not suitable for discussing account issues.
