### ISSUE TITLE
DatePicker doesn't render correctly when ToolbarNavigationComponent is used in the Scheduler toolbar template

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4212]
**Describe the bug**
The DatePicker popup has a broken UI when rendered from the ToolbarNavigationComponent. It seems that this is present in the latest version, but not in 14.3.0([demo](https://stackblitz.com/edit/angular-3uy89g-unerdt?file=src%2Fapp%2Fapp.component.ts)).

**To Reproduce**
1. Use the kendoSchedulerToolbarTemplate and add the kendoSchedulerToolbarNavigation or open the following example:
https://stackblitz.com/edit/angular-ecp6mc-fjnyvn?file=src%2Fapp%2Fapp.component.ts,src%2Findex.html
2. Then click on the DatePicker component in the toolbar to see the broken UI.

**Screenshots**
![Screenshot 2024-02-09 at 9 32 43](https://github.com/telerik/kendo-angular/assets/49076727/ad507a4a-621d-4cab-9154-e602ebb2c749)

**Comment by svetq** [comment]
A fix is available in v 15.0.2-develop.5 of the @progress/kendo-angular-scheduler.
