### ISSUE TITLE
[DragAndDrop] Memory leak when utilizing kendoDragTarget directive

### ISSUE THREAD

**Issue by slavenai** [telerik/kendo-angular#4217]
**Describe the bug**
When the DragTargetDirective is rerendered multiple times, a memory leak is observed:

### With the directive applied:

![Screenshot 2024-02-13 at 12 40 11](https://github.com/telerik/kendo-angular/assets/67437411/b5a19320-7bc9-4f16-9edc-07b2318b40c1)

![Screenshot 2024-02-13 at 12 40 01](https://github.com/telerik/kendo-angular/assets/67437411/af703cc5-de71-43e7-860d-4b1a0e99414a)

### Without the directive:

![Screenshot 2024-02-13 at 12 39 49](https://github.com/telerik/kendo-angular/assets/67437411/1d47d77d-a911-47f1-98eb-75d835f1596e)

**To Reproduce**

1. Download and unzip the folder.  [router 3.zip](https://github.com/telerik/kendo-angular/files/14308824/router.3.zip)
2. Run **npm install** followed by **ng serve**.
3. Go to `localhost:4200`
4. Navigate to the "Crisis Center" component using the top navigation
5. Go back forth between that component and the "Heroes" component n number of times
6. Open the Chrome Console, go to the Memory tab and do a "Heap snapshot"
7. In the resulting snapshot, search for "component" and you will see the CrisisListComponent repeated n number of times

**Comment by Rcasco** [comment]
This is a major pain point for our application. We cannot wait any longer for a fix to this so we will be looking for a new product solution to handle drag and drop that does not have a critical memory leak.
