### ISSUE TITLE
Numeric Textbox ignores min / max

### ISSUE THREAD

**Issue by ERobishaw** [telerik/kendo-angular#422]
[min] and [max] attributes ignored, allowing any value to be set
http://plnkr.co/edit/g5i4eERxZW2uq8wCFXth?p=preview

**Comment by Raisolution** [comment]
Hi @ERobishaw,

this behavior can be configured by enabling the autoCorrect option of the Component. Here is the [updated plunkr](http://plnkr.co/edit/EcrOgKLiQMha9v4WHSaV?p=preview).
