### ISSUE TITLE
Incorrect toolbar button titles and order

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4221]
**Describe the bug**
Currently, the button order of the toolbar is incorrect and the `Transfer From` should be above the `Transfer To` button like in [React](https://www.telerik.com/kendo-react-ui/components/listbox/) and [jQuery](https://demos.telerik.com/kendo-ui/listbox/index) ListBoxes.

The titles of the buttons are also wrong and should be corrected together with the order.
Current order:
Move to left button: "Transfer To"
Move all to left button: "Transfer All From"
Move to right button: "Transfer From"
Move all to right button: "Transfer All To"

Should be:
Move to left button: "Transfer From"
Move all to left button: "Transfer All From"
Move to right button: "Transfer To"
Move all to right button: "Transfer All To"

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/listbox/

**Screenshots**
Current order:
![Screenshot 2024-02-22 at 10 16 38](https://github.com/telerik/kendo-angular/assets/49076727/0829593f-f38f-41d0-95ae-054b5a52734d)
Correct order:
<img width="385" alt="Screenshot 2024-02-22 at 10 17 47" src="https://github.com/telerik/kendo-angular/assets/49076727/6b00aa97-ac7a-4c3a-85da-72dee343b463">

**Comment by stnikolova** [comment]
The fix is available in [v15.5.0](https://url.us.m.mimecastprotect.com/s/VRKUC313W3cvBRDYsgQHHG?domain=telerik.com).
