### ISSUE TITLE
DateTimePicker Range Doesn't  shows  the months correctly when we select DateTimePicker with Min Date 

### ISSUE THREAD

**Issue by Pnayak10** [telerik/kendo-angular#4222]
**Describe the issue**
 DateTimePicker Range Doesn't  shows  the months correctly when we select DateTimePicker with Min Date.

It's Mentioned in the documentation that it should show  values between 3/10/2019 12:30 PM and 3/15/2019 12:30 PM are displayed in the Calendar and the TimePicker.

But when i click on date picker  for 1st  time it shows the month as February in the top. and after that if you preass any button it shows March.

**Screenshots**
![WhatsApp Image 2024-02-22 at 5 21 26 PM](https://github.com/telerik/kendo-angular/assets/35223661/8eaa56af-0066-42b7-905a-e087a78b6263)

<img width="869" alt="Screenshot 2024-02-22 at 5 14 51 PM" src="https://github.com/telerik/kendo-angular/assets/35223661/4d85145e-cbf1-48d2-b1fb-bac7516cdae5">

**Browser**
 - ALL
**Additional context**

Analysis:-
I have a Done Analysis on this and got the root cause:-

1. If i add a min date of future date in DateTimePicker and no dates are selected in the Box, then 1st time when i click on dateTimePicker button, it shows the min date correct, but month in the top is shown as current month. and If you press keyboard button, it will show the months correct.

**Comment by tswetti** [comment]
Closing this issue in favor of https://github.com/telerik/kendo-angular/issues/3588 because they both seem to describe the same bug.
