### ISSUE TITLE
[Grid] Pasted data is trimmed

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4226]
**Describe the bug**
When copying data that has empty values at the beginning, they are trimmed once pasted in the Grid. 

This Excel data:
![image](https://github.com/telerik/kendo-angular/assets/33104481/e80625d0-8183-4e34-974f-e0c79c40a5d3)

is displayed in Grid like:
![image](https://github.com/telerik/kendo-angular/assets/33104481/2c6d53dd-77f5-47f6-a741-96191b0a09ea)

The `clipboardData` is:
> "5\t1\r\n\t\t3"

**To Reproduce**
Copy this data and paste it into the Grid:
  |   | 1
-- | -- | --
  |   | 3

**Expected behavior**
The pasted data should look like in Excel, (with two empty cells at the beginning).

**Comment by slavenai** [comment]
Fix available in `v15.2.0` of `@progress/kendo-angular-grid` package.
