### ISSUE TITLE
[Editor] Paste event fired twice when iframe is set to false

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4230]
**Describe the bug**
Currently, when the developer sets the iframe property of the Editor to false, the paste event of the component is being fired twice.

**To Reproduce**
1. Create an Editor component.
2. Set the iframe property to false.
3. Handle the paste event.

Please, check out the following StackBlitz demos:
https://stackblitz.com/edit/angular-9qvkpb
https://stackblitz.com/edit/angular-4nwxdj 

**Expected behavior**
When the iframe property of the Editor component is set to false, the paste event should be triggered only once.

**Screenshots**
<img width="536" alt="image" src="https://github.com/telerik/kendo-angular/assets/108671673/d4f9addf-176e-439f-bdc6-4ac0f661a1b3">

**Comment by Raisolution** [comment]
Fixed in v17.0.0
