### ISSUE TITLE
[Chart] LegendMarkers configuration stopped working in the latest version

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4241]
**Describe the bug**
Due to some changes in the Legend element, the LegendMarkers stopped working for chart types like column, bar, and pie. This doesn't seem to affect the [line](https://stackblitz.com/edit/angular-quora3-sbjfzz?file=src%2Fapp%2Fapp.component.ts) chart.

**To Reproduce**
Demos:
https://stackblitz.com/edit/angular-quora3?file=src%2Fapp%2Fapp.component.ts
https://stackblitz.com/edit/angular-tdc6k5?file=src%2Fapp%2Fapp.component.ts

**Additional context**
This might be coming from v15.0.0 as 14.3.0 is working as expected:
https://stackblitz.com/edit/angular-yni72i-ddnqxm?file=src%2Fapp%2Fapp.component.ts

**Comment by nstoychev** [comment]
Since version v15.0.0, the Chart Legend renders the `markers area` and the markers for each item. For chart types like column, bar, and pie the area is a square. The markers in the legend are not visible by default since there aren't any markers in the chart as well.

To change the markers visibility, set `visible: true`.

Example: https://stackblitz.com/edit/angular-quora3-fsf3sn?file=src%2Fapp%2Fapp.component.ts

**Comment by yanmariomenev** [comment]
From my understanding, the Markers are the drawn element next to the Legend text and our option is provided to modify that element or provide custom visuals. 

https://docs.devexpress.com/WindowsForms/1985/controls-and-libraries/chart-control/visual-elements/legend-marker
![Screenshot 2024-03-13 at 9 46 36](https://github.com/telerik/kendo-angular/assets/49076727/9fe48420-caf0-4336-8b25-a6c24bf76a05)

The visibility is set **_true_** by default which is [documented](https://www.telerik.com/kendo-angular-ui/components/charts/api/LegendMarkers/#toc-visible) and also visible in the example.

Now if this is expected to render a separate element next to the legend marker, then it does look a bit strange in a way or the developers lose their option to modify the markers of the Chart legend. 
![Screenshot 2024-03-13 at 9 47 41](https://github.com/telerik/kendo-angular/assets/49076727/5b050389-0ca5-43de-a604-23724468c02f)

This will also break people who already use the markers to change the shape. On our side it looks like we are taking away an option from them without providing an alternative or maybe I am missing something and some further clarification would be good here.

**Comment by AaaStrky** [comment]
Is this behavior expected?
![image](https://github.com/telerik/kendo-angular/assets/165792339/379d9599-4a54-4340-ae85-21cb98025075)

In the older version, I had the Chart Legend like this:
![image](https://github.com/telerik/kendo-angular/assets/165792339/6e8ab921-7f30-48ee-bc08-81cfbd7bc635)
Now, if set visible: true is added, it looks like this: 
![image](https://github.com/telerik/kendo-angular/assets/165792339/51c1b6c0-aed1-4dd8-9bbc-39e166f2c776)

**Comment by yanmariomenev** [comment]
Due to the planned changes to the legend, the rendering is expected, and this issue will be closed as invalid. If the developer wants to revert to the old rendering, custom visuals should be used. For example the pie chart legend now renders square and to revert back to lines the following demo shows a custom visual implementation of the legend:

https://stackblitz.com/edit/angular-dijtnd-weevvb?file=src%2Fapp%2Fapp.component.ts

https://www.telerik.com/kendo-angular-ui/components/charts/elements/legend/#toc-customizing-the-shape
