### ISSUE TITLE
Datepicker is not rendering correctly - Header toolbar is hiding

### ISSUE THREAD

**Issue by RAMKI2** [telerik/kendo-angular#4245]
**Describe the bug**
Kendo-angular-dateInputs v14.3.0. DatePicker is not rendering correctly, the header template is hiding on opening the popup

**To Reproduce**
 - Simply create a kendo-datepicker component
 - open it in browser and clicker the calender icon
 - Header template which shows "Today" button is hiding

**Screenshots**
![datepicker issue kendo](https://github.com/telerik/kendo-angular/assets/37836643/220c6f83-2781-4718-85b7-3c790b5d3b65)

**Browser**
 - OS: Windows 11
 - Browser : All browsers

**Additional context**

**Comment by tswetti** [comment]
Hi, @RAMKI2. Can you send us a reproducible example of the undesired rendering? I attempted to reproduce it in the following Stackblitz demo but it seems to work as expected:
https://stackblitz.com/edit/angular-cfemdx?file=src%2Fapp%2Fapp.component.ts
