### ISSUE TITLE
Question: How to use bootstrap theme?

### ISSUE THREAD

**Issue by codershubhamverma** [telerik/kendo-angular#425]
I have to use bootstrap theme but i am not able to install bootstrap theme for kendo, Please suggest.

**Comment by Loetn** [comment]
You can install it with `npm install --save @progress/kendo-theme-bootstrap` and include the (s)css files in your app.

**Comment by gyoshev** [comment]
Detailed information on how to use the themes is available in the [styling overview help topic](http://www.telerik.com/kendo-angular-ui/components/styling/).
