### ISSUE TITLE
[PDFViewer] Inconsistent behavior of the pageChange event 

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4258]
**Describe the bug**
As of now, when the user changes the current page using the designated pager in the toolbar of the PDFViewer, the pageChange event provides information about the previous and current pages using a zero-based format. Alternatively, when the pages are scrolled using the scrollbar and the mouse, the pageChange event provides information about the pages using indexes starting from one.

**To Reproduce**
1. Create a PDFViewer.
2. Handle the pageChange event.
3. Change the pages of the component using the scrollbar.
4. Change the pages of the component using the built-in pager in the toolbar.

Please, check out the following StackBlitz demo: https://stackblitz.com/edit/angular-juaxlt

**Expected behavior**
The pageChange event should provide information about the pages of the PDFViewer in a consistent format.

**Screenshots**
<img width="704" alt="image" src="https://github.com/telerik/kendo-angular/assets/108671673/0de1c916-2af5-4197-9c90-a47d22eedc40">

**Comment by yanmariomenev** [comment]
A fix is available in version 15.5.0.
