### ISSUE TITLE
MultiSelect form clear (Reactive forms) does not clear visible items

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#426]
[Plunker](http://plnkr.co/edit/CKPBW4baYargHTLlgAe2?p=preview).

Problem after selecting something and click submit button:
![chrome_2017-03-28_08-53-10](https://cloud.githubusercontent.com/assets/1589573/24392423/1091a302-1394-11e7-8a84-4fc79f20943c.png)

**Comment by KirilNN** [comment]
Thanks for reporting it.

Should be resolved with version `v0.37.2` or above.
