### ISSUE TITLE
Toolbar popupSettings property isn't working

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4260]
**Describe the bug**
The [`popupSettings`](https://www.telerik.com/kendo-angular-ui/components/toolbar/api/PopupSettings/) property of the Toolbar doesn't apply the customization made through the available options - `height`, `width`, `animate`, etc.

**To Reproduce**
The following example should disable the animation of the popup, and change its width. But the default popup appears:

```html
  <kendo-toolbar [popupSettings]="{animate: false, width: '500px'}">
            <kendo-toolbar-dropdownbutton
                text="Paste Variations"
                [data]="data">
            </kendo-toolbar-dropdownbutton>
   </kendo-toolbar>
```

https://stackblitz.com/edit/angular-qhs6x9

**Comment by slavenai** [comment]
The Toolbar's `popupSettings` configure the overflow button's popup:
https://stackblitz.com/edit/angular-gtxnn1?file=src%2Fapp%2Fapp.component.ts

To tweak the appearance of the Toolbar buttons, bind to their `popupSettings` property, e.g.:
https://www.telerik.com/kendo-angular-ui-develop/components/toolbar/api/ToolBarDropDownButtonComponent/#toc-popupsettings.

https://stackblitz.com/edit/angular-qhs6x9-j77va8?file=src%2Fapp%2Fapp.component.ts

We'll make sure to update our documentation respectively.
