### ISSUE TITLE
grid filter menu input for decimals removes dot(.) sometimes

### ISSUE THREAD

**Issue by HarryTrue** [telerik/kendo-angular#4264]
Typing a decimal number in a grid filter menu input for number type removes dot sometimes.
Can be reproduced in this grid: https://www.telerik.com/kendo-angular-ui/components/grid/filtering/filter-menu/
![317066963-aaa1d19b-c0f3-461c-b39b-4978c5e5ce30](https://github.com/telerik/kendo-angular/assets/54777563/eb4fd976-8f4b-4777-8765-dbbd4091941f)

**Comment by HarryTrue** [comment]
It's been three weeks since the post, but no response. Thanks for the support. I guess I will have to try the other ways to reach out.

**Comment by yanmariomenev** [comment]
The experienced behavior is explained in the following thread - https://github.com/telerik/kendo-angular/issues/3835

**Comment by HarryTrue** [comment]
@yanmariomenev that post is not answering my question. Left a comment there too
