### ISSUE TITLE
[Grid] Selection Aggregate does not work when binding GridDataResult

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4265]
**Describe the bug**
When binding the Grid to a [GridDataResult](https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/local-data/#toc-binding-to-a-griddataresult-object) object, the selection aggregates aren't calculated. Only **count** is available. 

This limitation comes from the fact that `GridDataResult`  is an object with two properties, whereas the selection aggregates logic relies on arrays.

see _selection.aggregate.service.ts_ file:

```typescript
    public init(): void {
        if ((this.ctx.grid.selectable as SelectableSettings).cellAggregates) {
            this.data = this.dataChanges.data ? this.dataChanges.data : this.ctx.grid.data;
             ...
        }
    }
``` 
`this.ctx.grid.data` requires one more level deep to access the actual collection (`this.ctx.grid.data.data`).

**To Reproduce**
Select a range of cells.
https://stackblitz.com/edit/angular-ygxfpt-nj5g7l?file=src%2Fapp%2Fapp.component.ts

Possibly related to https://github.com/telerik/kendo-angular/issues/4201

**Comment by Raisolution** [comment]
Fixed in `v16.11.0`
