### ISSUE TITLE
[Editor] Images cannot be resized

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4268]
**Describe the bug**
Currently, when the user clicks on an image inside the Editor, the image can only be moved but cannot be resized.

**To Reproduce**
1. Create an Editor.
2. Render an image inside the component.
3. Click on the image and try to resize it.

Please, check out the following StackBlitz demo: https://stackblitz.com/edit/angular-yckj9c

**Expected behavior**
The user should be able to not only move the images inside the Editor component but also to resize them.

**Additional context**
It seems like the issue is not present in v14.3.0 of the Editor and starts from v15.0.0:
- v14.3.0: https://stackblitz.com/edit/angular-yckj9c-vrsyes
- v15.0.0: https://stackblitz.com/edit/angular-yckj9c-8wwnfe

**Comment by No1e** [comment]
When is this going to be fixed?

**Comment by No1e** [comment]
Hi @dtopalov,

thank you for the answer. This is really blocker for our product. Can you please provide the fix by the end of this month?

Thank you,
Nole
