### ISSUE TITLE
[MultiSelectTree, DropDownTree] Failing To Display Delayed Data and Leaving the no Data Template Rendered

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4271]
**Describe the bug**
When toggling the dropdown of both components before data loading completes, the **kendoDropDownTreeNoDataTemplate** and **kendoMultiSelectTreeNoDataTemplate** accurately indicate that data is loading.

However, upon completion of data loading, the dropdown fails to switch to displaying the loaded data. Instead, it persists with the content of the **kendoDropDownTreeNoDataTemplate** and **kendoMultiSelectTreeNoDataTemplate**, suggesting no data is available despite successful loading.

This seems to be related to changes in version 15.1.0, and versions below that don't replicate the above behavior ([example](https://stackblitz.com/edit/angular-yklar6-ekr5cx?file=src%2Fapp%2Fapp.component.ts)).

**To Reproduce**
Open the example and follow the instructions:
https://stackblitz.com/edit/angular-yklar6-v1apun?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Comment by stnikolova** [comment]
The fix is available in [v16.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.0.0)
