### ISSUE TITLE
NotificationService throws an error in SSR configured application

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4276]
**Describe the bug**
If the NotificationService is used in an SSR-configured application it will throw an `ERROR ReferenceError: document is not defined.` upon initialization. It seems that the notification doesn't check if the document is available, like our Dialogs package.

**To Reproduce**
Open and run the local project.
[A17-notifications-ssr (1).zip](https://github.com/telerik/kendo-angular/files/15038395/A17-notifications-ssr.1.zip)

**Workaround**
Checking the platform before initializing the NotificationService:
```
public notificationService!: NotificationService;

constructor(@Inject(PLATFORM_ID) private platformId: Object) {
    if(isPlatformBrowser(this.platformId)){
      this.notificationService = inject(NotificationService);}
}

public displayNotification(): void {
    if(isPlatformBrowser(this.platformId)){
      this.notificationService.show({
        content: "Custom Notification",
        position: { horizontal: "center", vertical: "bottom" },
        type: { style: "info", icon: true },
      });
    }
  }
```

**Comment by slavenai** [comment]
The error seems to be caused by an incorrect application set up - `document` is referenced in the `app.component.ts` providers. Removing it and setting the `appendTo` option of the NotificationSettings resolves the issue.

In `app.component.ts`:
```
  @ViewChild("container", { read: ViewContainerRef })
  public container: ViewContainerRef | any;

  constructor(private notificationService: NotificationService) {}

  ngAfterViewInit(){
    this.displayNotification()
  }

  public displayNotification(): void {
    this.notificationService.show({
      content: "Custom Notification",
      appendTo: this.container,
      position: { horizontal: "center", vertical: "bottom" },
      type: { style: "info", icon: true },
    });
  }
```

In `app.component.html`:

`  <div class="append-container" #container></div>`

**Comment by maulikshah30** [comment]
**Service base using**

import { isPlatformBrowser } from '@angular/common';
import { Inject, Injectable, PLATFORM_ID } from '@angular/core';
import { NotificationService } from '@progress/kendo-angular-notification';

@Injectable({
  providedIn: 'root',
})
export class ValidationmessageService {
  constructor(
    private notificationService: NotificationService,
    @Inject(PLATFORM_ID) private platformId: Object
  ) {}

  private ErrorMessage: string | null = null;

  private showNotification(
    message: any,
    type: 'none' | 'success' | 'warning' | 'error' | 'info',
    hideAfter: number
  ) {
    if (this.ErrorMessage === message) {
      return; // Do not show the message again
    }
    if (isPlatformBrowser(this.platformId)) {
      this.notificationService.show({
        content: message,
        hideAfter: 2000,
        position: { horizontal: 'center', vertical: 'top' }, //right,bottom,left
        animation: { type: 'fade', duration: 400 },
        type: { style: type, icon: true }, //warning,none,info,error,warning
      });
    }

    this.ErrorMessage = message;

    setTimeout(() => {
      this.ErrorMessage = null;
    }, hideAfter + 400); // Reset the message after hideAfter + animation duration
  }

  showSuccess(message: any) {
    this.showNotification(message, 'success', 2000);
  }

  showError(message: any) {
    this.showNotification(message, 'error', 5000);
  }

  showInfo(message: any) {
    this.showNotification(message, 'info', 2000);
  }

  showWarning(message: any) {
    this.showNotification(message, 'warning', 2000);
  }
}
