### ISSUE TITLE
Enter key on NumericTextBox -> how get correct value

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#428]
I really don't know how to have value of numericTextBox when user press enter key.
Here plunker to show what i would like to have:

http://plnkr.co/edit/GKe6d0vI7JeewOMI1lLF

Actually old jquery kendo ui method what just to get value form `event.target.value` field but now we have it in string format and not numeric.

Thanks.

**Comment by ggkrustev** [comment]
Hi @meriturva,
Indeed, the value cannot be retrieved on Enter, because the change event is raised only on blur.

**This is a bug**, that we are aware of. We are working on it right now and soon it will be addressed. I will notify you in this thread once the issue is addressed.

**Comment by meriturva** [comment]
So thanks @ggkrustev

**Comment by PleasantD** [comment]
I just noticed this myself. Pressing enter in an ngForm that the numeric text box is a part of fires the submit on the form **before** updating the model. So I wind up submitting the wrong value.

**Comment by tsvetomir** [comment]
The issue appears to be fixed in the current version, [see plunkr](http://plnkr.co/edit/YOkhSprbzoxJ6apVassN?p=preview).
