### ISSUE TITLE
[Inputs, DropDowns, DateInputs] Using custom validator on a FormControl component with input and calling a method on the value of the control throws an error

### ISSUE THREAD

**Issue by zstoyanova9** [telerik/kendo-angular#4281]
**Describe the bug**
When configuring a Kendo UI for Angular component that has an underlying input element as a FormControl and using a custom validator, in which a method is called for the value of this control, a "Cannot read properties of undefined (reading '{{name of method}}')" error is thrown in the console. 

This is a regression introduced with [v15.5.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.5.0).

**To Reproduce**
Open the following StackBlitz example that implements our [TextBox](https://www.telerik.com/kendo-angular-ui/components/inputs/textbox/) component as a FormControl and observe the error in the console:
https://stackblitz.com/edit/angular-im2mgt-nl4jat 

DateTimePicker example - https://stackblitz.com/edit/angular-bug-datetimepicker-xjnzga?file=src%2Fapp%2Fapp.component.ts

There is no such error when using the same configuration with the default HTML [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element. Example: https://stackblitz.com/edit/angular-im2mgt-ugbjqg 

**Expected behavior**
No error should be thrown when this configuration is used with a Kendo UI for Angular component. 

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/138521711/2dfd6f1a-173b-4d83-896d-803dcd9022de)

**Comment by tswetti** [comment]
Fixed in [v16.0.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.0.0)
