### ISSUE TITLE
[Grid][TreeList] Scrollable 'none' causes a11y errors

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4285]
**Describe the bug**

**axeDevTools** throws a critical issue when setting the Grid scrollable property to none.
_Certain ARIA roles must contain particular children_

<img width="1380" alt="image" src="https://github.com/telerik/kendo-angular/assets/33104481/25130bd5-e59f-4e08-b301-a772c82a2506">

**Comment by slavenai** [comment]
Fixed in `v16.0.0` of the respective packages.
