### ISSUE TITLE
[TabStrip] Incorrect setting of the aria-expanded property

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4287]
**Describe the bug**
Currently, the aria-expanded attribute is applied to the tab panels inside the TabStrip component despite the fact that there is no  mechanism that would allow expanding/collapsing them.

**Expected behavior**
The aria-expanded attribute should not be applied to the tab panels inside the TabStrip component.

**Additional context**
Ticket ID: 1649085

**Comment by slavenai** [comment]
Fixed in `v16.0.0` of the `kendo-angular-layout` package.
