### ISSUE TITLE
Grid: All rows hidden by .k-virtual-content>table if grid [height] not set (Not using virtual scrolling)

### ISSUE THREAD

**Issue by kkalitowski** [telerik/kendo-angular#429]
With the latest version none of the grid rows display in even the simplest scenarios possible (no features in use at all: paging, scrolling, templates...nothing). I've tracked it down to the CSS '.k-virtual-content>table' which sets 'position: absolute'.  If I remove the 'position: absolute' my rows all reappear. The only other fix I've found is to set [height] on the grid but I would rather have the grid auto determine it's height.

I wish I could give you a Plunker but I don't think the examples on the [product site](http://www.telerik.com/kendo-angular-ui/components/grid/paging/) are using the latest version of the controls so I cannot recreate it there. The HTML/CSS your Plunkers emit is different than what my local solutions are generating. I strongly suspect this is a recent breaking change since it was working fine until I got the latest controls.

![error](https://cloud.githubusercontent.com/assets/2752954/24462752/6370b53c-146a-11e7-9236-f17ab593bf0a.png)

**Comment by P-H-F** [comment]
I'm also experiencing this after updating `@progress/kendo-theme-default` from version `2.20.1` to `2.22.0`.

From what it looks like this is not affected by the version of `@progress/kendo-angular-grid`. 
(Works/Tested with grid versions `0.20.3` and `0.21.0` and theme version `2.20.1`)
