### ISSUE TITLE
[Grid, TreeList] Column and filter menu close when scrolling the content of the table

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4292]
**Describe the bug**
When opening the column menu and scrolling through the table content, it will close the menu upon scrolling. However, if the column menu is opened a second time and then scrolling through the table content, it will not close the popup.

**To Reproduce**
Open one of the column menus and scroll the Grid content in the following example:
https://stackblitz.com/edit/angular-dw5ar3?file=src%2Fapp%2Fapp.component.ts
If you open the column menu a second time it will not close upon scrolling.

https://github.com/telerik/kendo-angular/assets/49076727/d8f14379-4c87-4ad9-af1f-dd32c8c3c7d3

**Expected behavior**
The Column Menu popup shouldn't close upon content scroll like Kendo UI for jQuery Grid.

**Comment by slavenai** [comment]
May be related to https://github.com/telerik/kendo-angular/issues/3879
