### ISSUE TITLE
[Splitter] Pane size not persisted on collapse/expand

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4304]
**Describe the bug**
Splitter panes size are not persisted when the collapsed state is toggled and in case the first pane has the initial **size** set. 
After expanding the panes, the initially set size of the first pane is reset and changed.

Collapse the right pane to reproduce the issue:
https://stackblitz.com/edit/angular-x2krsr-w6rr5d?file=src%2Fapp%2Fapp.component.ts

If the split bar is resized a bit, the panes size is respected and the issue is not reproduced.

**Comment by slavenai** [comment]
Fixed in `v16.4.0` of `kendo-angular-layout` package.
