### ISSUE TITLE
[Editor] The focus() method of the Editor does not scroll the component into view

### ISSUE THREAD

**Issue by zstoyanova9** [telerik/kendo-angular#4312]
**Describe the bug**
When using the focus() method to programmatically focus the Editor, the component does not get scrolled into view in cases when it is out of the viewport. 

**To Reproduce**
1. Open the following StackBlitz example - https://stackblitz.com/edit/angular-k3rrm8 
2. Click the "Focus the Editor" button.

**Expected behavior**
The Editor should not only be focused, but also scrolled into the view.

**Workaround**
Use `editor.view.dom.focus();` to focus the Editor component instead.
Example with workaround - https://stackblitz.com/edit/angular-k3rrm8-m6may1

**Comment by slavenai** [comment]
Fixed in `v16.3.0` of `kendo-angular-editor` package.
