### ISSUE TITLE
[Drag and Drop] Row reordering in Grid causes text selection

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4321]
**Describe the bug**
When using the built-in row reordering functionality, it starts selecting text upon dragging the row of the Grid component.
<img width="1577" alt="Screenshot 2024-05-31 at 9 13 15" src="https://github.com/telerik/kendo-angular/assets/49076727/c76dd884-6b74-460f-9dcb-51995ee5926d">

**To Reproduce**
Open the following example and start reordering the rows - https://www.telerik.com/kendo-angular-ui/components/grid/rows/reordering/

**Comment by Raisolution** [comment]
Issue has been fixed in v16.3.0.
