### ISSUE TITLE
[Date Inputs] Cyrillic Letter Breaks Production Build

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4323]
**Describe the bug**
Currently, there seems to be a Cyrillic letter in the index.ts file of the Kendo UI for Angular Date Inputs package that leads to some issues when the customers try to build their code.

**To Reproduce**
1. Navigate to the dateinputs folder.
2. Open the index.ts file.
3. Scroll to the import of the internal FooterTemplateDirective.

**Expected behavior**
The Cyrillic letter should not be present in the code as this prevents the build of a project.

**Screenshots**
![image](https://github.com/telerik/kendo-angular/assets/108671673/92d7c763-de26-4c29-8779-3b8c231e04c3)

**Comment by Raisolution** [comment]
Issue has been fixed in v16.3.0.
