### ISSUE TITLE
[MultiSelect] Clicking on the chip doesn't open the popup list of the component

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4326]
**Describe the bug**
When a user tries to click on the chip, it no longer opens the component's popup list. In older versions, such as 11.6.0, the popup would open when the user clicked the chip.

**To Reproduce**
Open the following page and click the "Medium" chip:
https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/value-binding/#toc-primitive-values

[Example](https://stackblitz.com/edit/angular-qwrvsh-1eqczw?file=src%2Fapp%2Fapp.component.ts) where the behavior is correct in v11.6.0

**Comment by slavenai** [comment]
Fixed in `v16.4.0` of `kendo-angular-dropdowns` package.
