### ISSUE TITLE
Missing k-checkbox-wrap for Checkbox within the Grid's Column Menu

### ISSUE THREAD

**Issue by NickIliev** [telerik/kendo-angular#4328]
**Describe the bug**

The Checkbox should be rendered with a wrapper that holds **k-checkbox-wrap** CSS class (related to https://github.com/telerik/kendo-angular-private/issues/1913)

However, when creating a Grid with ColumnMenu, and there is an active column chooser item, then the rendered checkboxes are missing the wrapper element (no **k-checkbox-wrap**).

This is not the expected rendering as in the source of truth tests https://github.com/telerik/kendo-themes/blob/develop/tests/grid/grid-column-menu-angular.html#L25 
![image](https://github.com/telerik/kendo-angular/assets/18008302/fc5dda27-3557-48ee-807b-19ab93a7e58b)

**To Reproduce**
Open the official column chooser demo https://www.telerik.com/kendo-angular-ui/components/grid/accessories/column-menu/#toc-column-chooser-item
 and observe the rendering for the checkbox items 
![image](https://github.com/telerik/kendo-angular/assets/18008302/9dd9b3a5-bbd1-457d-8e9c-3f7e5b5ab8a1)

**Additional context**
reported through t.1655224

Kendo Angular Q2 2024
TB Q2 2024

**Comment by slavenai** [comment]
Fixed in `v17.0.0`
