### ISSUE TITLE
The sorted direction icon does not trigger sorting in a Grid with header template

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#433]
Can be observed in the following example:

[http://plnkr.co/edit/s1KzLnCqAvB1v69QWSeJ?p=preview](http://plnkr.co/edit/s1KzLnCqAvB1v69QWSeJ?p=preview)

**Comment by rusev** [comment]
There is a fix for this issue in version 0.25.1 of the Grid package. 

Note that clicking on the sort icon with header template will work, but clicking on the header template content will not trigger sorting.
