### ISSUE TITLE
[Signature] Not working properly in Ionic environment 

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4330]
**Describe the bug**
There seems to be some offset when trying to work with the signature component due to the Ionic environment. This is most likely due to styles and how Ionic works with canvas elements which the Signature uses. Useful information regarding the offset issue:

https://stackoverflow.com/questions/8693693/offset-when-drawing-on-canvas/8693791#8693791

https://github.com/wulfsolter/angular2-signaturepad/issues/42

Removing the styles attribute seems to fix the issue, but the canvas itself is too small.

```
<canvas 
style="width: 100%; height: 100%;"
></canvas> 
```

**To Reproduce**
Extract and use the following [steps](https://ionicframework.com/docs/angular/your-first-app) to install and run the project:

[ionic project.zip](https://github.com/user-attachments/files/15882470/ionic.project.zip)

1. Install Ionic globally:

`npm install -g @ionic/cli native-run cordova-res`

2. Install Capacitor plugins:

`npm install @capacitor/camera @capacitor/preferences @capacitor/filesystem`

3. Install Ionic PWA Elements:

`npm install @ionic/pwa-elements`

Serve the Ionic application:

4. Run `ionic serve` command

**Screen Recording**

https://github.com/telerik/kendo-angular/assets/49076727/d1b0cde0-bbcf-4fd3-b328-61fadabd2eed

**Comment by Raisolution** [comment]
The issue is not directly related to a problem in the Kendo component behavior.

**Comment by yanmariomenev** [comment]
A workaround is to render the component when [ionViewDidEnter](https://ionicframework.com/docs/angular/lifecycle#ionic-page-events) lifecycle triggers:

https://stackblitz.com/edit/ionic6-angular13-szky3itt?file=src%2Fapp%2Fapp.component.ts

or using setTimeout to render the component on ngAfterViewInit.
