### ISSUE TITLE
[DropDownList, DropDownTree, ...] All dropdowns are broken when zoom is added to the body in Firefox

### ISSUE THREAD

**Issue by jorenGoossens** [telerik/kendo-angular#4337]
## I'm submitting a...

* Bug report 

## Current behavior
When opening any dropdown the absolute positioning of the popup is incorrect. If a zoom of 1.5 is applied to the apps body then all positions should be divided by 1.5 to get the correct position.

## Expected behavior
The popup should open below the dropdown.

## Minimal reproduction of the problem with instructions
Adding a zoom != 1 to the <body> element of any app will break all type of dropdowns: 

Simplified demo - https://stackblitz.com/edit/angular-r11x6u?file=src%2Fapp%2Fapp.component.ts
Original post demo - https://stackblitz.com/edit/angular-v1ipiz-k7biqb

The page would need to be scrollable to reproduce the issue.

https://github.com/telerik/kendo-angular/assets/49076727/0b77bb34-9bd8-439a-b782-7da933b7f185

![Screenshot 2024-07-03 at 16 21 10](https://github.com/telerik/kendo-angular/assets/49076727/7582e115-58f4-4319-ba3a-966ae5364971)
![image](https://github.com/telerik/kendo-angular/assets/165364818/fec92311-4513-499a-afcf-ed9d7e3211cc)

Browser:

- Firefox version 127.0.2 (64-bits)
- Chrome latest

System:
- TypeScript version: 5.3.0
- Node version: v18.10.0
- Platform:  Windows & Mac

On the browser web support page I've read that zoomed-in pages are not supported, but is there any way to fix this issue with some custom css/jaavscript. This issue makes a web app completely broken for firefox users.

**Comment by Raisolution** [comment]
Hi @jorenGoossens 

As correctly noticed, the described behavior is expected and not considered a bug. Thus, I am closing the current issue as the repository is intended for bug reports only.

If further assistance is required, do not hesitate to contact us through our [support system](https://www.telerik.com/account/support-tickets).
