### ISSUE TITLE
Grid: Changing pages navigates to application root

### ISSUE THREAD

**Issue by kkalitowski** [telerik/kendo-angular#434]
Clicking on a page number or using the paging navigation arrows of the Grid redirects the browser to http://myUrl/# causing navigation away from the UI the user is on.

This worked in 0.21.0 but has started failing in 0.22.0 as verified by upgrading and downgrading.

**Comment by rkonstantinov** [comment]
Thanks for the report. The issue should be fixed with 0.22.1 version of the grid package.
