### ISSUE TITLE
[Grid] Row Reordering in Non-Scrollable Grid

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4347]
**Describe the bug**
Currently, when the scrollable property of the Grid is set to none and the built-in row-reordering is enabled, the user cannot drag and drop any of the rows in the component.

**To Reproduce**
1. Create a Grid component.
2. Set the scrollable property of the Grid to none.
3. Enable the built-in rowReordering feature.

Please check out the following StackBlitz demo: https://stackblitz.com/edit/angular-nc1vgr-tamzzk

**Expected behavior**
The row reordering feature should not be affected by the scroll of the Grid component - the built-in drag-and-drop of rows should also be possible in cases where the Grid is not scrollable.

**Possible workarounds**
https://stackblitz.com/edit/angular-nc1vgr
https://stackblitz.com/edit/angular-cir2nf

**Comment by Raisolution** [comment]
Fixed in v. 16.9.0
