### ISSUE TITLE
[DatePicker, DateTimePicker, TimePicker] Closing the popup with ESC key will throw an error when using Sentry

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4350]
**Describe the bug**

DateInputs with pop-ups will throw an error when [Sentry](https://www.npmjs.com/package/@sentry/browser) is used, and they are closed using the `ESC` key. 

Error message - `Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?`

**To Reproduce**
Open the popup of the DatePicker and close it using the `ESC` key in the following example: https://stackblitz.com/edit/angular-wxetbr-5xz9db?file=src%2Fapp%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fixed in `v16.11.0`
