### ISSUE TITLE
[SplitButton, DropDownButton] Active State Remains Applied

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4354]
**Describe the bug**
Currently, in a scenario where the user clicks on the SplitButton with the mouse, but does not release the left mouse button, moves the cursor away from the SplitButton, and then releases the mouse button, the active state of the component remains still applied.

**To Reproduce**
1. Create a SplitButton component.
2. Click on the button using the left mouse button but do not release it.
3. Move the cursor away from the SplitButton.
4. Release the left mouse button.

Please, check out the following StackBlitz demo for further reference: https://stackblitz.com/edit/angular-tsenbo-2bhk3g

**Expected behavior**
When the user releases the mouse button, the active state of the SplitButton should not be applied.

**Screenshots**

https://github.com/user-attachments/assets/d247b72a-474f-4328-9d2a-76475d633c4f

**Comment by Raisolution** [comment]
Fixed in v17.0.0
