### ISSUE TITLE
[DateInput] Spin buttons automatically focusing and changing value only for the first segment of the date

### ISSUE THREAD

**Issue by zstoyanova9** [telerik/kendo-angular#4355]
**Describe the bug**
When focusing a latter segment of the date value in the DateInput and trying to increase/decrease its value using the spin buttons, the focus automatically moves to the first segment and modifies its value instead.  

**To Reproduce**
1. Open the following StackBlitz example - https://stackblitz.com/edit/angular-1y3i38
2. Focus the year segment of the date value. 
3. Try to increase/decrease its value by using the spin buttons.

![chrome_oJBhXsbkfB](https://github.com/user-attachments/assets/2c8c9777-085e-4f7e-9d92-257e3e3faca1)

**Expected behavior**
The user should be able to modify the value of each segment in the date when it is focused by using the spin buttons. 

**Additional context**
This behavior is not present in versions before v15.0.0 of Kendo UI for Angular.
Example with v14.3.0 - https://stackblitz.com/edit/angular-cwrtpu-cp14im

**Comment by tswetti** [comment]
Fixed in v [16.7.1](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.7.1)
