### ISSUE TITLE
Upload: Buttons order in UploadActionButtonsComponent

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#436]
Our testers are confused with order of the action buttons.
Could you put the primary button to the left?

Now it's is 'Remove' and 'Upload'. 
I think it would be more logical to put the 'Upload' left, like 'Ok' and 'Cancel' :thumbsup:

**Comment by yordanov** [comment]
Both orders are valid depending on which OS one comes from. 

Here is a nice read on the topic:
https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150#04e7

We placed the **Upload** button on the right hand side (as well as all primary action dialog buttons) as we believe this is the better approach:

- feels natural for your "next >" step to be on the right
- mobile friendly - closer to your thumb
- somehow makes you read through all actions before you choose one

**Comment by EricSch** [comment]
I see, our users are used to Windows, so they prefer the approach Ok/Cancel -> Primary left. We used that approach all in our UI.

Could it made configurable? Would be nice.

**Comment by yordanov** [comment]
Thank you for the suggestion. We will consider it. We could either provide a property or a template directive. Yet, what if there are more than 2 buttons? In case of a property, would a reverse order work in that case, e.g. buttonsOrder: "ltr"/"rtl" or reversedButtonOrder: true/false?

**Comment by EricSch** [comment]
yes, a property like reversedButtonOrder would work

Thank you

**Comment by Raisolution** [comment]
Hi @EricSch,

Thank you for this suggestion. We have logged it internally for future enhancement, but it is not in our immediate plans for implementation. I am closing this issue for now.
