### ISSUE TITLE
[MultiSelect] Setting the valueField to a nested property value throws an error when valuePrimitive is true

### ISSUE THREAD

**Issue by zstoyanova9** [telerik/kendo-angular#4362]
**Describe the bug**
When the valueField of the MultiSelect is set to point to a nested property value and the valuePrimitive property is true, then the user selects an item, the emitted value from the component is the whole object, not the specified valueField. This causes an "Expected values of primitive type" error to be thrown in the console: 

![image](https://github.com/user-attachments/assets/5a7dec69-0c1c-42a3-917d-a6e31f93e660)

**To Reproduce**
1. Open the following StackBlitz example - https://stackblitz.com/edit/angular-fv9bym 
2. Select a value for the MultiSelect.
3. Observe the error in the console.

![chrome_evuz51evZt](https://github.com/user-attachments/assets/ebf53ea6-3e81-46af-9ee0-c3731f39753a)

**Expected behavior**
The emitted value from the MultiSelect should be of a primitive type (as specified in the valueField) and no error should be thrown. 

**Additional context**
When a value is set programmatically for the MultiSelect and is of the correct primitive type, the unexpected behavior is not observed.
Example - https://stackblitz.com/edit/angular-fv9bym-4dbeyz

**Comment by tswetti** [comment]
Fixed in [v16.7.1](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.7.1)
