### ISSUE TITLE
[DateInputs] Can not change values with usage of keyboard buttons Up and Down if 'readonly' Input was set to 'true' on initialization and then was changed to 'false'

### ISSUE THREAD

**Issue by RomanYablonskiEli** [telerik/kendo-angular#4364]
**Describe the bug**
Usually we can change values in the DateInput by clicking on day, month or year unit, this unit will be focused and can be changed by pressing on keyboard buttons Up and Down. 

But if 'readonly' Input was set to 'true' on initialization and then was changed to 'false', User can not change values in DateInput with usage of keyboard buttons Up and Down. Also they are not focused if you click on them.

**To Reproduce**
1) Create the DateInput with [readonly]="true".
2) Switch [readonly] to false, so you can edit the value
3) Try to change the value with Up and Down keyboard buttons

StackBlitz - https://stackblitz.com/edit/angular-bzjjck?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Expected behavior**
The value is changed when you click on Up and Down keyboard buttons
**Actual behavior**
The value is **not** changed when you click on Up and Down keyboard buttons

**Screenshots**
![image](https://github.com/user-attachments/assets/01f34dd4-a34c-43db-a434-bd60523e3071)

![image](https://github.com/user-attachments/assets/b025cf40-0d0d-4bd9-a0ee-e8929fbdde42)

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 126

**Comment by tswetti** [comment]
Fixed in [v16.8.0](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.8.0)
