### ISSUE TITLE
Scheduler inconsistent formatting of the event aria label and title when using different locales like es-ES

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4366]
**Describe the bug**
The Scheduler doesn't format the dates correctly when applying them to the event aria-label and title which will result in a wrong tooltip rendering.

![Screenshot 2024-07-19 at 8 53 20](https://github.com/user-attachments/assets/a0642d78-136b-494f-a2f7-47f555bfdfda)
![Screenshot 2024-07-19 at 8 31 12](https://github.com/user-attachments/assets/8701246d-fd34-4c39-aedf-424de64c2add)

The time should be in 24h format, but it seems that the start date is converted to a 12h format.

**To Reproduce**
Open the following example:

https://stackblitz.com/edit/angular-6r3v9g?file=src%2Fapp%2Fevents-utc.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

Inspect the event and hover over it to render the tooltip.

**Expected behavior**
The result should be - viernes, 19 de julio de 2024, 20:00–21:30, Car service

Example with our intlService - https://stackblitz.com/edit/angular-qsrafe?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Comment by Raisolution** [comment]
Fixed in v. 16.9.0
