### ISSUE TITLE
[MultiSelect] Clicking on the white space doesn't open the popup of the component

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4367]
**Describe the bug**
When there are chips in a new line the white space in the first line will not open the popup. This was working in an [older](https://stackblitz.com/edit/angular-dp1meg?file=src%2Fapp%2Fapp.component.ts) version and it seems that a newer version broke that behavior which also included the chip which is now fixed in https://github.com/telerik/kendo-angular/issues/4326

https://github.com/user-attachments/assets/79a5ae15-2c97-47f0-8399-49b61e6fb504

**To Reproduce**
https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/

1. Select enough items, to get them two wrap into a second line or more.
2. Close the dropdown.
3. Try to open the dropdown by clicking on the white space that is NOT the last line.
4. Notice that dropdown does not open, whilst any other clicks on items and/or filter input work fine.

**Expected behavior**
Should work like the older version or MultiSelectTree:
https://stackblitz.com/edit/angular-dp1meg?file=src%2Fapp%2Fapp.component.ts
https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselecttree/

**Comment by tswetti** [comment]
Fixed in [v16.7.1](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.7.1)
