### ISSUE TITLE
<template> element is deprecated

### ISSUE THREAD

**Issue by iqmeta** [telerik/kendo-angular#437]
Hi,
compile gives following warning now:

```
The <template> element is deprecated. Use <ng-template> instead
node_modules/@progress/kendo-angular-grid/dist/es/grid.component
```

ng --version
   
@angular/cli: 1.0.0
node: 7.8.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

**Comment by gyoshev** [comment]
Components are currently being updated to support Angular 4.x. Use issue #346 to track the implementation status.
