### ISSUE TITLE
[TreeView] Checkboxes remain permanently focused after interaction

### ISSUE THREAD

**Issue by zstoyanova9** [telerik/kendo-angular#4370]
**Describe the bug**
When checking and then unchecking a checkbox in a TreeView with checkboxes selection, the focus on the checkbox remains no matter where it is clicked afterward in order to remove the focus (on another checkbox or anywhere outside the TreeView).

**To Reproduce**
1. Open the following StackBlitz example - https://stackblitz.com/edit/angular-wdcrpj 
2. Check and then uncheck a random checkbox.
3. Click on another checkbox or anywhere in the DOM. 

![chrome_v19xEazExb](https://github.com/user-attachments/assets/7e9ead7f-4fe7-474e-9d7e-ca8f00d63b9b)

**Expected behavior**
The focus of the previously interacted checkbox should be removed when the focus moves to another element. 

**Additional context**
It seems that this behavior starts reproducing from v15.5.0 of the packages.
Example with v15.4.0 - https://stackblitz.com/edit/angular-sytmg2

**Comment by Raisolution** [comment]
Fixed in `v16.6.1`
