### ISSUE TITLE
[Menu] Throws NG0100 after hovering and clicking an item in Angular 18

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4374]
**Describe the bug**
If you hover and select an item sometimes it throws an NG0100 error. A similar issue that was resolved recently: https://github.com/telerik/kendo-angular/issues/4331

**To Reproduce**
Hover over a menu item and click one of the options:
https://stackblitz.com/edit/angular-mc3hud-s3phwb?file=src%2Fapp%2Fapp.component.ts

**Comment by Raisolution** [comment]
Fixed in `v16.6.1`
