### ISSUE TITLE
[DropDownList, MultiSelectTree] Throw NG0100 in Angular 18 project after opening and closing the popup

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-angular#4375]
**Describe the bug**
If you open the popup on each component and close it with a click outside of the popup, by not selecting an item it will throw an NG0100 error:

```Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'attr.aria-controls': 'k-f7dd1589-502a-47d4-8b02-ac14c2c66223'. Current value: 'null'. Expression location: AppComponent component. Find more at https://angular.dev/errors/NG0100```

Similar issues with Angular 18 and NG0100:
https://github.com/telerik/kendo-angular/issues/4331
https://github.com/telerik/kendo-angular/issues/4374

**To Reproduce**
Open the popup of one of the components and close it by clicking outside of the popup:
https://stackblitz.com/edit/angular-mc3hud-qj3kqx?file=src%2Fapp%2Fapp.component.ts

**Comment by tswetti** [comment]
Fixed in [v16.7.1](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v16.7.1)
