### ISSUE TITLE
[MS Edge] Two KendoButtons with [icon] set causes Angulars "Expression changed after it was checked..."

### ISSUE THREAD

**Issue by kparol-proacta** [telerik/kendo-angular#438]
Error is triggered only in MS Edge, IE is not affected.

Plunker:
http://plnkr.co/edit/XIGxKQ?p=preview

I'm using *kendoButton*s in *kendo-grid-command-column* template as bare icon buttons.

With one button it's ok, but with 2 buttons I'm getting Angular second pass error - in dev mode.

> EXCEPTION: Error in ./AppComponent class AppComponent - inline template:11:78 caused by: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

Important notices:
- When there is no [icon] set, error doesn't occur.
- When button is not empty, error doesn't occur.

My temporary fix is to add &nbsp; content to button, but I think it should be done in kendo button code.

**Comment by siyka-marinova** [comment]
@kparol-proacta I tried reproducing the problem with the plunker you provided, unfortunately to no avail: https://www.screencast.com/t/rHtkDjZBJ7

Could you, please, share a more detailed project and also the Angular version and the version of the Kendo Buttons you are currently using?

**Comment by kparol-proacta** [comment]
@siyka-marinova looks like it can be different version of Edge browser, i've tested the same plunker on 2 work stations getting error

Link to screencast:
https://www.screencast.com/t/upojkxdhu

In my project I use following versions (still seeing error)
- angular: "2.4.7"
- progress/kendo-angular-buttons: "0.23.0"

**Comment by siyka-marinova** [comment]
@kparol-proacta Thank you for the additional information. I managed to reproduce the exception on another device and we'll investigate what's causing it.

**Comment by tsvetomir** [comment]
This should be fixed in v0.24.1 of the package.
