### ISSUE TITLE
Dateinput autoCorrectParts results in console error

### ISSUE THREAD

**Issue by Zaixu** [telerik/kendo-angular#4393]
**Describe the bug**
When autoCorrectParts is set false, it accepts any character and results in error.

![image](https://github.com/user-attachments/assets/71b1038c-bc6c-43c4-914d-4cdced778305)

**To Reproduce**

1. [https://www.telerik.com/kendo-angular-ui/components/dateinputs/examples/datepicker/typing/auto-correct-parts/?theme=default-ocean-blue&themeVersion=8.2.1](https://www.telerik.com/kendo-angular-ui/components/dateinputs/examples/datepicker/typing/auto-correct-parts/?theme=default-ocean-blue&themeVersion=8.2.1)
2. Put cursor in first field.
3. Press 'd' or any character.
4. Error is thrown in console.

**Expected behavior**
To only accept applicable format and not result in error.

**Screenshots**

**Browser**
 - Browser: Chrome
 - Version: 128.0.6613.86

**Comment by Raisolution** [comment]
Fixed in `v16.11.0`
