### ISSUE TITLE
[MultiViewCalendar] Does not update to `CldrIntlService` default settings changes in standalone component

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4398]
**Describe the bug**
Overwriting default settings of the `CldrIntlService` are correctly updated when using DatePicker, Calendar, etc. components in a standalone component app.

However, the same changes are not updated in the MultiViewCalendar. Specifically following this article on changing the first day:
https://www.telerik.com/kendo-angular-ui/components/knowledge-base/change-first-day-week

**To Reproduce**
Notice the first day of the week. It's Monday for all components except the MultiViewCalendar.

https://stackblitz.com/edit/angular-r5wjsy?file=src%2Fapp%2Fapp.component.ts,src%2Findex.html

The same demo works as expected if NgModules are used:
https://stackblitz.com/edit/angular-hafecd

**Expected behavior**
MultiViewCalendar first day should be updated according to the new settings, just like the Calendar.

**Comment by Raisolution** [comment]
Fixed in `v16.11.0`
