### ISSUE TITLE
Switch -> Change event fired on keypress

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#440]
Here just a really simple plnkr: 

http://plnkr.co/edit/EXWnyT8f5xorEyuXwDha?p=preview

to reproduce issue:
1. Just change value of switch with a mouse click
2. Press any key on keyboard
3. See console log

As you can see if switch is focused it emits many change value events every time user press a key!

**Comment by rusev** [comment]
Version 1.0.2 of `kendo-angular-inputs` package addressed these issues.
