### ISSUE TITLE
Kendo dropdown popup position is not correct

### ISSUE THREAD

**Issue by SumanManna1** [telerik/kendo-angular#4400]
**Describe the bug**
The input field of the Combobox is being shifted left . It was working fine with Windows OS Build 17763.5820 and Edge  Browser version 128.0.2739.67 (Official build) (64-bit) but post upgradation with OS Build 19045.4780 and Edge Browser version 126.0.2592.61 (Official build) (64-bit) its displaced all kendo dropdown controls.

**To Reproduce**

Open [this Dojo example](https://dojo.telerik.com/aLEWaGEJ)
Run it and see the floating "Rib Knit" text which is the input field of the Combobox
<img width="576" alt="KendoDropDownPositionIssue" src="https://github.com/user-attachments/assets/64caf7e7-b502-4e49-97b0-22050bfc519c">

**Expected behavior**
 ComboBox pop-up should appear in correct position according to the set "top, bottom, left, right" parameters.
**Screenshots**

**Browser**
 - OS: Windows OS Build 19045.4780
 - Browser  : Edge 
 - Version :  126.0.2592.61 (Official build) (64-bit)

**Comment by tswetti** [comment]
Hello @SumanManna1,

This repository is the bug tracker for **Kendo UI for Angular**. For bug reports related to **Kendo UI for jQuery** please use the following bug tracker:
https://github.com/telerik/kendo-ui-core
For assistance with implementing specific scenarios or configurations, please open a [support ticket](https://www.telerik.com/account/support-tickets).
