### ISSUE TITLE
DateInputComponent: AoT doesn't work

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular#441]
I tried to do AoT but unfortunately I got the next error, if I use DateInputComponent :

![grafik](https://cloud.githubusercontent.com/assets/22910183/24606605/31f4691a-186e-11e7-8806-8facc81503ef.png)

thanks in advance

**Comment by ggkrustev** [comment]
@anj01, thank you for the report! We've just pushed a fix. Could you check the v0.5.3 version?

**Comment by anj01** [comment]
Tanks! It works!
