### ISSUE TITLE
[Scheduler] Event tooltip not working as expected in year view

### ISSUE THREAD

**Issue by Erg3048** [telerik/kendo-angular#4421]
### Description

Seemingly random dates in the year view of the scheduler will fail to show tooltip of event information when clicked.

### Steps To Reproduce

https://www.telerik.com/kendo-angular-ui/components/scheduler

From Kendo Documentation example:
 - switch to year view and click on dates Jan 1st or 2nd, note the tooltip popup
 - switch year from 2024 to 2025 and then back to 2024
 - try clicking  on the same dates Jan 1st or 2nd, tooltip does not show up.
 - happens to other days as well, can happen on event days

### Screenshots or video

![image](https://github.com/user-attachments/assets/50612415-9ffd-4e67-b35b-707afd015869)
![image](https://github.com/user-attachments/assets/421b66b5-629f-43da-bab0-521ed732175f)
![image](https://github.com/user-attachments/assets/edfd08a0-4279-4c61-b92d-8df3db6be4a4)
Expected behavior upon day click
![image](https://github.com/user-attachments/assets/de6d9569-d90e-409f-9b43-9e0b0217537d)
navigate to next year
![image](https://github.com/user-attachments/assets/98a54ea3-af75-474d-8fea-96bb5b51f4b1)
navigate back to previous year
![image](https://github.com/user-attachments/assets/3cce3e3f-eb3f-4351-a205-3d7a81fa8936)
![image](https://github.com/user-attachments/assets/96c05a48-f6e7-4c80-875d-026858abbaf2)
![image](https://github.com/user-attachments/assets/c90a82d8-bc82-4e9a-9836-3188f6d348f7)
Actual behaviour: No tooltip for 1st and 2nd but working for 3rd

### Actual Behavior

Tooltip not showing up upon clicking of days in year view

### Expected Behavior

Tooltip  shows up upon clicking of days in year view

### Browser

Chrome

### Browser version

latest

### OS type

Windows

### OS version

Windows 10 Pro build: 19045.4894

### Last working version of the Kendo UI for Angular package (if regression).

16.9.0

**Comment by Raisolution** [comment]
Fixed in v17.0.0
