### ISSUE TITLE
[TreeList] The rowIndex field of the EditTemplateDirective returns undefined

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4427]
### Description

Currently, the rowIndex field of the EditTemplateDirective returns undefined instead of the actual index of the row or -1 for newly added items. 

### Steps To Reproduce

1. Create a TreeList component.
2. Enable the editing feature.
3. Try to access the rowIndex in an EditTemplateDirective.

Please check out the following StackBlitz demo: https://stackblitz.com/edit/angular-un5ptu

### Actual Behavior

Currently, when the developer tries to access the rowIndex field of the EditTemplateDirective, the value that the field returns is undefined.

### Expected Behavior

The rowIndex should return the actual row index of the currently edited item or -1 if the user is adding a new record.

### Browser

All

### Browser version

latest

**Comment by Raisolution** [comment]
Fixed in v17.0.0
