### ISSUE TITLE
[Calendar] Error is being thrown when clicking on a week number with an enabled date range

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4428]
### Description

Currently, when the weekNumber option of the Calendar is set to true and a specific date range is enabled, a click on the week number of a week that is not entirely shown results in a console error, and the last day of the next week is focused.

### Steps To Reproduce

1. Create a Calendar component.
2. Enable the weekNumber option.
3. Set a date range.
4. Click on the week number of a week that is not fully rendered.

Please check out the following StackBlitz demo: https://stackblitz.com/edit/angular-aevpjm

### Actual Behavior

Setting a date range in such a manner that not all of the days of a specific week are displayed and clicking on the week number of such a week leads to a console error and the focus is shifted to the last day of the next week.

### Expected Behavior

Clicking on any week number should not lead to a console error.

### Browser

All

### Browser version

latest

**Comment by slavenai** [comment]
Fixed in `v17.1.1`.
