### ISSUE TITLE
[DateTimePicker] Date 1.1.1970 can't be set/delete from input

### ISSUE THREAD

**Issue by vavrinec-aspecta** [telerik/kendo-angular#4432]
### Description

When we write the specific value "1/1/1970 1:00 AM" ( time is depend on browser timezone ) in the input, it gets really weird. Sometimes it saves the value but cannot be deleted or it doesn't even save the value.

In general, operations with the date "1/1/1970" are bad.

**Potential problem:**
Apparently, somewhere there is a validation through `Date.parse(input)` where in the case of the date "1/1/1970" the `.parse()` method returns the value `0`, which is in the condition `false`. Maybe.

### Steps To Reproduce

Many ways of reproduction. This is one of them:

- open test url
- set "1/1/1970 1:00 AM" ( time is depend on browser timezone ) to value input in kendo date time 
- click to calendar icon

The value has been removed.

Or with setted value we can't delete it:
- open test url
- try delete value from input
- click on calendar icon
- old value is back

Test url: https://stackblitz.com/edit/angular-kitaqn-jwajrh?file=src%2Fapp%2Fapp.component.ts

Or the official URL demo: https://www.telerik.com/kendo-angular-ui/components/dateinputs/datetimepicker/events

### Screenshots or video

https://github.com/user-attachments/assets/6c167902-f54c-4a39-aafc-8375b3d9ec4b

### Actual Behavior

Weird behavior with "1/1/1970 1:00 AM" ( time is depend on browser timezone ) value.

### Expected Behavior

Normal behavior like any other values

### Browser

Chrome, Microsoft Edge

### Browser version

latest

### OS type

Windows

### OS version

Win 11

**Comment by zstoyanova9** [comment]
Hi @vavrinec-aspecta, thank you for the detailed explanation. 

I tried to reproduce the described issue on my side, but it seems that I can enter the mentioned date ("1/1/1970 1:00 AM") in the DateTimePicker as expected. Please check the following screen recording for reference:

https://github.com/user-attachments/assets/3ed53cdc-72b1-4fa5-93f6-2dc27aa10e25

Having said that, could you please clarify the exact timezone, in which the reported issue is experienced on your side? The timezone on my side is Eastern European Summer Time (EEST), with a UTC offset of -180 minutes (UTC+3).

Thank you in advance.

**Comment by vavrinec-aspecta** [comment]
Hi @zstoyanova9,

In my case, the time zone is UTC+1 (Europe/Bratislava).

For testing on your end, it is necessary to set the date and time 1/1/1970 03:00 AM

https://github.com/user-attachments/assets/0a509483-49b5-4282-93bb-e35bb184429b

**Comment by zstoyanova9** [comment]
Hi @vavrinec-aspecta, thank you for the additional clarification.

Indeed, after adjusting the entered time in the DateTimePicker given the timezone on my side, I am now able to reproduce the reported behavior as described in the issue and demonstrated in the screen recording. 

On that note, we identify the reported behavior as a valid bug in the DateTimePicker component and will update this issue accordingly when there is any progress on its resolution.

**Comment by Raisolution** [comment]
Fix available in `v.17.1.0`
