### ISSUE TITLE
Grid filtering - filter row 

### ISSUE THREAD

**Issue by danam19** [telerik/kendo-angular#444]
Hi, 
Init the filter with value filtering the grid, but the filter row not display the filter.

Example: 
http://plnkr.co/edit/SnthfifrVxYs92dqmnwU?p=preview

**Comment by rusev** [comment]
I can confirm that this is an issue. We will investigate and inform you back when we have more details.

**Comment by rkonstantinov** [comment]
This issue should be addressed with the 0.24.2 version of the `kendo-angular-grid` package.
