### ISSUE TITLE
Can't show combobox open and use an *ngIf directive in it

### ISSUE THREAD

**Issue by Dashiing** [telerik/kendo-angular#445]
I can't configure a combobox starting open while using a *ngIf directive in it as shown in this [Plunker](http://plnkr.co/edit/nmHeTQYUv7AaqWNDcviz?p=preview).

**Comment by ggkrustev** [comment]
@Dashiing, as I mentioned in the Stackoverflow thread, the described behavior is expected. Everyone interested in a feasible solution, please check the thread:

http://stackoverflow.com/a/43187520/324224

**Comment by Dashiing** [comment]
Yes, it solved my problem. Thanks ggkrustev.
