### ISSUE TITLE
Support of automatic numbered lists

### ISSUE THREAD

**Issue by AkshaykumarPhilips** [telerik/kendo-angular#4450]
We have a requirement to support automatic numbered list and restarting the numbered list.

For Eg:

1) Test
2) Test1

3) Test2

Display the numbering continuously even though there is a new empty line as mentioned above and there should be a mechanism to restart the number list from1 in the same document.

Currently I don't see the options in kendo to achieve the above requirement. Could you please provide some inputs on the above.

Thanks

**Comment by Raisolution** [comment]
Hello @AkshaykumarPhilips 

This repository is for bug reports only. For assistance with implementing specific scenarios or configurations, please open a [support ticket](https://www.telerik.com/account/support-tickets).
