### ISSUE TITLE
Dropdown position fixed in Firefox

### ISSUE THREAD

**Issue by aueelis** [telerik/kendo-angular#4459]
### Description

We are using the `<kendo-dropdownlist>` with `[popupSettings]="{appendTo: 'component'}"` and have issues in Firefox that the position of the dropdown isn't updated correctly. Other browser seem to be working fine.

Some observations:
1. if the component is at its original place, when it is clicked, the dropdown opens at the correct spot. However, when scrolling, the position is not updated.
2. if the component is getting scrolled to a different location (or moved to a different spot because of components above that are loading later and take an unknown amount of space), the location is wrong from the start and also doesn't update, when the page is scrolled.

### Steps To Reproduce

This can be reproduced by using the main dropdownlist example from the documentation and adding `[popupSettings]="{appendTo: 'component'}"`.

A more minimal example without all the stuff around and just some spaces for scrolling could be found here:
https://stackblitz.com/edit/angular-eesbaq?file=src%2Fapp%2Fapp.component.ts

### Screenshots or video

![Image](https://github.com/user-attachments/assets/215da6ae-7a8f-4afc-a9a4-ddd2dea8e7b9)

### Actual Behavior

Position of dropdown popup is fixed and doesn't update to be next to the dropdown component, when then position of the dropdown component changes.

### Expected Behavior

The popup is always attached to the dropdown component.

### Browser

Firefox

### Browser version

latest, developer

### OS type

Windows

### Last working version of the Kendo UI for Angular package (if regression).

Worked with `"@progress/kendo-angular-dropdowns": "4.3.0"`. We skipped from there to Kendo 16.10.

**Comment by Raisolution** [comment]
Fix available in `v17.1.1`
