### ISSUE TITLE
Kendo-Upload FileRestrictions

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#446]
- Open [Plunker](http://plnkr.co/edit/deK5stK2UPfHwfDcd4Wv?p=preview)
- Select a PDF to upload ( get a 'File type not allowed')
- Click the button 'change file restctions'
  ( the file list doesn't update on change)
- Select PDF to upload again ( type allowed )

Is it possible to check the files in the file list after restrictions are changed or show the retry button if the file type not allowed?

**Comment by Raisolution** [comment]
Hi @simon11196,

you could combine the `restrictions` property with `[(ngModel)]` binding - [documentation link](http://www.telerik.com/kendo-angular-ui/components/upload/model-binding/#toc-binding-values). This way when updating the restrictions, you could also update the files in the list.

**Comment by simon11196** [comment]
Hi @Raisolution ,

i tried your suggestion. [Plunker](http://plnkr.co/edit/eJqs9tGwG7bD4cz9y133?p=preview)
But the model doesn't get updated unless i press the upload button.

**Comment by Raisolution** [comment]
Hi @simon11196,

you are correct, the model is only updated on successful file upload. At the moment we don't consider updating the state of the already selected files, as this will introduce further issues (e.g. what should happen with the uploaded files).
I would suggest to clear the selected files (e.g. `this.myFiles = [];`) if the restrictions should be changed dynamically, to ensure correct file state at any time.
