### ISSUE TITLE
[Icons] Application cannot be configured to use `font` icons

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-angular#4462]
### Description

Currently, when the developer tries to configure an Angular application to use `font` icons instead of the default `svg` ones, only the icons that are explicitly provided as `font` icons reflect the modification and the default icons of the components continue using `svg`.

### Steps To Reproduce

1. Create an Angular application.
2. Install some of the Kendo components.
3. Configure the application to use `font` icons using [the following article](https://www.telerik.com/kendo-angular-ui/components/icons/icon-settings#using-font-icons).
4. Render a Kendo component, for instance, the Button, and explicitly render a `font` icon in it.
5. Render another Kendo component that contains a default icon and inspect it.
6. Check the browser console for a warning message.

For further reference, please check out the attached application: 
[font-icons.zip](https://github.com/user-attachments/files/17871270/font-icons.zip)

### Screenshots or video

![Image](https://github.com/user-attachments/assets/d0eb9cab-6473-41cb-97b8-e5aa0e17ce16)
![Image](https://github.com/user-attachments/assets/dfc20805-f4b0-4f36-aaa5-ca70ac3884bd)
![Image](https://github.com/user-attachments/assets/68b64cbc-f1ea-4f56-8c3d-f81f6efe2844)

### Actual Behavior

Even after performing the configurations suggested in the [Using Font Icons article](https://www.telerik.com/kendo-angular-ui/components/icons/icon-settings#using-font-icons), the application still seems to rely on `svg` icons - the native component icons are `svg` and only explicitly provides ones are rendered as `font` icons. Furthermore, there is a warning message on the console.

### Expected Behavior

When configuring an application to use `font` icons, all icons in the project should be rendered as `font` ones.

### Browser

All

### Browser version

latest

### OS type

MacOS

### Last working version of the Kendo UI for Angular package (if regression).

v16.11.0

**Comment by BenKorventeen** [comment]
Last working version of the Kendo UI for Angular package is v16.11.0.

We currently run your kendo packages on v17.1.0 except for @progress/kendo-angular-icons, which we run on version 16.11.0. (using --lgeacy-peer-deps to install and update)

**Comment by Raisolution** [comment]
Fix available in `v17.1.1`
