### ISSUE TITLE
DropdownList - popup doesn't close on viewport leave during scroll

### ISSUE THREAD

**Issue by vLutsevich** [telerik/kendo-angular#4472]
### Description

By default, when a DropdownList is opened and the viewport is scrolled out of view, the popup closes automatically. However, for some reason, this behavior does not occur when the dropdown is set to filterable=true.

As I understand it, the issue lies in the DropdownList source code:
```
    if (!this.filterable) {
        this.subs.add(this.popupRef.popupAnchorViewportLeave.subscribe(() => this.togglePopup(false)));
    }
```
In contrast, other similar components like ComboBox, MultiSelect, Autocomplete, DatePicker, TimePicker, etc., do not include this conditional check (if) and work as expected.

### Steps To Reproduce

Create the DropdownList with [filterable]="true" inside window.
Open dropdown's popup
Scroll down.

StackBlitz - https://stackblitz.com/edit/angular-nzjsvs?file=src%2Fapp%2Fapp.component.ts

### Actual Behavior

Dropdown's popup doesn't close on viewport leave during scroll.

https://github.com/user-attachments/assets/f3363c2a-c43f-4d6a-b80e-a17c795e99bd

### Expected Behavior

Dropdown's popup closes on viewport leave during scroll.

https://github.com/user-attachments/assets/fd8bf3ca-869c-435e-a92b-d0cf1c31f46d

### Browser

Chrome

### Browser version

latest

### OS type

MacOS

**Comment by svetq** [comment]
@vLutsevich,

The focus goes into the filter text box inside the popup when the `filterable` option of the DropDownList is set to `true`.  Thus the popup is not closed on viewport leave by default as the focus will be lost. You can prevent the default behavior of the `close` event to customize the behavior:

> <kendo-dropdownlist [filterable]="true" (close)="$event.preventDefault()"/>
