### ISSUE TITLE
IE11 Combobox or Dropdown not displaying values in kendo-dialog

### ISSUE THREAD

**Issue by peac3maker** [telerik/kendo-angular#448]
The combobox and dropdown display and behave correctly in Firefox but in IE11 it looks like the controls are created correctly, but you don't see the values. This completely destroys the use of these controls in a dialog.
Please check the following plunker link:
http://plnkr.co/edit/O4cn8OE4miWc4M8MQPs2?p=preview

To reproduce edit an item in the grid and try to use the combobox "Product name"

**Comment by tsvetomir** [comment]
I tried this with both IE Edge and 11, but the ComboBox appears correctly:

![image](https://cloud.githubusercontent.com/assets/247917/24663852/beb372f8-1961-11e7-8601-e38c31a8fb7a.png)

**Comment by peac3maker** [comment]
Thanks for testing. I will retry the issue and specify the exact version of ie asap

**Comment by peac3maker** [comment]
I can confirm that for me it runs correctly on edge as well.
But IE11 is not working.
My IE11 Version is: 11.953.14393.0
Update Versions: 11.0.40 KB4012204

**Comment by rusev** [comment]
I can confirm that on a Windows 8.1 with IE11 Update Versions: 11.0.40 the issue is reproducible.

**Comment by peac3maker** [comment]
Seems like alot is broken with KB4012204:
http://www.telerik.com/forums/recent-windows-update-causing-sizing-issues

**Comment by dtopalov** [comment]
Works as expected with latest versions of Kendo UI for Angular packages:

[http://plnkr.co/edit/5H5FxrKHHaIfOMtgHy1W?p=preview](http://plnkr.co/edit/5H5FxrKHHaIfOMtgHy1W?p=preview)
