### ISSUE TITLE
Kendo Grid -> Scroll enabled -> Empty space on end of rows

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#449]
Just open your plunker on page:

http://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/#toc-virtual-scrolling

When you scroll down on the end of grid you see a lot of space/row empty, i think main problem is that page change event has to be generated but anyway on process there is `total` property set correctly.

So main question is: how to avoid space on end of grid with scroll enabled?

Any advise here?

**Comment by gyoshev** [comment]
Thank you for reporting this, it has been fixed in [version **2.25.5**](https://github.com/telerik/kendo-theme-default/releases/tag/v2.25.5) of the Default theme.
