### ISSUE TITLE
DropDown Header not centered

### ISSUE THREAD

**Issue by PMoransais** [telerik/kendo-angular#451]
When resizing, at smaller sizes the drop down header is no longer vertically centered

**Comment by Raisolution** [comment]
Hi @PMoransais,

Could you demonstrate this with a plunkr example by modifying some of our demos?

**Comment by PMoransais** [comment]
Please check the picture. This happens only when resizing and the size is small. It is consistent.

![capture](https://cloud.githubusercontent.com/assets/19433579/24717432/737ff3ac-1a00-11e7-8738-ed1559a5c25f.PNG)

This is the code:
`<div class="row">
    <div class="col-12 col-sm-4 col-md-3 col-lg-2">
        <div class="card">
            <div class="btn-toolbar p-1" role="toolbar" aria-label="Toolbar with button groups">
                <kendo-dropdownlist [data]="breeds"
                                    [value]="breeds[0]"
                                    [textField]="'caption'"
                                    [valueField]="'value'"
                                    (selectionChange)="onBreedSelection($event)">
                </kendo-dropdownlist>
                <div class="btn-group btn-group-sm" role="group">
                    <button type="button" class="btn btn-secondary" [disabled]="!canCreate" (click)="onCreate()"><i [ngClass]="addButtonClass()"></i></button>
                </div>
            </div>
            <kendo-panelbar [items]="items" (stateChange)="onPanelChange($event)">
            </kendo-panelbar>

</div>
`.
So this happens when the component is inside a Bootstrap Grid. As you can see, the dropdown is included in div with a bootstrap button.

There are no particular styles applied except for the bootstrap styles.

I am short on time so I cannot replicate right now in your example.

I hope that helps

**Comment by PMoransais** [comment]
Sorry, I messed up the code listing in my previous post. It should be as follows:

<div class="row">
    <div class="col-12 col-sm-4 col-md-3 col-lg-2">
        <div class="card">
            <div class="btn-toolbar p-1" role="toolbar" aria-label="Toolbar with button groups">
                <kendo-dropdownlist [data]="breeds"
                                    [value]="breeds[0]"
                                    [textField]="'caption'"
                                    [valueField]="'value'"
                                    (selectionChange)="onBreedSelection($event)">
                </kendo-dropdownlist>
                <div class="btn-group btn-group-sm" role="group">
                    <button type="button" class="btn btn-secondary" [disabled]="!canCreate" (click)="onCreate()"><i [ngClass]="addButtonClass()"></i></button>
                </div>
            </div>
            <kendo-panelbar [items]="items" (stateChange)="onPanelChange($event)">
            </kendo-panelbar>

</div>

**Comment by ggkrustev** [comment]
@PMoransais, the code sample is still unclear. Would it be possible to post a plunkr demo directly?

**Comment by tsvetomir** [comment]
Closing the issue due to inactivity, feel free to reopen with more details.
