### ISSUE TITLE
Grid & Intl: Formatting of Date

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#453]
The kendoDate Pipe and Grid column format don't behave the same:

                <kendo-grid-column field="datum" title="Datum">
                    <ng-template kendoGridCellTemplate let-dataItem>
                        {{dataItem.datum | kendoDate: 'D'}}
                    </ng-template>
                </kendo-grid-column>

                <kendo-grid-column field="datum" title="Datum" format="{0:D}">
                </kendo-grid-column>

The pipe will format a string as date (by converting the string first to a date), but the GridColumn format function doesn't. Wouldn't it be better, when they do the same?

**Comment by ggkrustev** [comment]
@EricSch, I do believe that the described behavior is expected. In general, the grid works with Date objects and not with date-like strings.
Indeed, the kendoDate pipe performs the additional task of parsing the input, but it explicitly knows that the input should be a Date. This is not the case with the `format` column property.

I would strongly recommend you to convert the serialized JSON date strings into Date objects before feeding the grid.

**Comment by EricSch** [comment]
Thank you for answering
