### ISSUE TITLE
Theming: using transform makes screen blurry

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#455]
In the default theme, transform is used to position a dialog:

```
    // Centering
    .k-centered {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

   .k-dialog {
        padding: 0;
        min-width: 450px;
        position: fixed;

        // Centered
        &.k-dialog-centered {
            transform: translate(-50%, -50%);
            top: 50%;
            left: 50%;
        }
    }
```
In many cases this will make the screen blurry (seen in Chrome, 1920x1200):

![image](https://cloud.githubusercontent.com/assets/25437/24703801/2820222e-1a05-11e7-9a9b-b3f04d15b651.png)

Better use another method to position.

**Comment by gyoshev** [comment]
Indeed this is the case, we plan on changing these styles. Use issue #227 to track the progress of this bug.
