### ISSUE TITLE
MultiSelect primitiveValue = true not working

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#457]
If value is 0 then change return complete item and not only primitive value.
[Plunkr](http://plnkr.co/edit/IkqhKH4wZT8KKyJoFOLw?p=preview).
Video:
![2017-04-05_18-42-07](https://cloud.githubusercontent.com/assets/1589573/24716615/e70933cc-1a2f-11e7-8614-58114a929afc.gif)

**Comment by Raisolution** [comment]
Fixed in v0.38.2
