### ISSUE TITLE
 AoT compilation kendo-angular-grid error

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular#459]
I get the following error when running compilation

[10:53:24] **Error: Command failed: "node_modules/.bin/ngc" -p tsconfig-aot.json
Cannot determine the module for class PagerComponent** in C:/Work/kdapp/xxx/Source.Web/xxxx/node_modules/**@progress/kendo-angular-grid/dist/es/pager.component.d.ts**! Add PagerComponent to the NgModule to fix it.
    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Process terminated with code 1.

**Version**: "@progress/kendo-angular-grid": "**0.23.0**"

Many thanks!

**Comment by rusev** [comment]
Our AoT builds seems to work with latest Grid package and angular-cli 1.0.0/NG 4.0.1. Could you share a project where the error can be replicated?

**Comment by anj01** [comment]
I am sorry about, but I can't share any projekt now. 
My AoT compilation could been run up to version 0.21.2 without any problems. Do you have any ideas, that I could investigate?

**Comment by rohit-b** [comment]
@anj01 please delete the previous aot build folder and then try
after updating the project from angular 2 to angular 4 with kendo ui package updated to support angular 4 you need to clear your previous build and build it newly

**Comment by anj01** [comment]
Many thanks for hint... :-) It works perfectly and about 2 times faster! very nice!!!
