### ISSUE TITLE
Grid multiselect

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#460]
Hey team,

we really need to know when (a rough estimate) the mutliselect will be available for the grid component, this is a crucial part of our project. Please do not respond with "When it is ready it will be released".

**Comment by tsvetomir** [comment]
By _multiselect_ you mean the ability to select multiple rows or cells, correct? Just to be sure.

**Comment by moxival** [comment]
Hi @tsvetomir at the moment the multiple selection for rows is critical for us, the selection of cells is not.

**Comment by tsvetomir** [comment]
We're not currently working on the multiple selection, but looking forward to start soon. You can expect a basic implementation to be available in June.

We'll tracking this feature in #213

**Comment by moxival** [comment]
Hey, thanks for the info. 

That would be a very close call for us, we have to be ready with the final version in August, many components and workflow depend on selecting multiple items and I don't know how fast we can implement the changes throughout the app (it is a big crm). I will have to check this with my bosses and discuss if we can continue with kendo at all.

**Comment by tsvetomir** [comment]
Merging this issue into #634
