### ISSUE TITLE
kendo-dateinput: this.intl.dateFormatString is not a function  at DateInputComponent

### ISSUE THREAD

**Issue by RobyCresta** [telerik/kendo-angular#462]
I was following the [kendo-dateinput example (Basic Usage)](http://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/#toc-basic-usage) and I've got this error:

```
TypeError: this.intl.dateFormatString is not a function 
at DateInputComponent.writeValue (dateinput.component.js:202)
``` 
and, while debugging, I find out that  `this.intl` and `this.intl.formatDate` are valid, but `this.intl.dateFormatString` is undefined.

![console_error](https://cloud.githubusercontent.com/assets/25247236/24856097/d31f5db6-1de3-11e7-936a-ebcf23c114db.PNG)
![console_watch](https://cloud.githubusercontent.com/assets/25247236/24856108/da6f5486-1de3-11e7-9af8-6aec4b8d3b56.PNG)

I've recently updated angular 2 to angular 4. 
This morning I updated all the packages to the latest version.
What am I doing wrong? Thanks

**Comment by ggkrustev** [comment]
@RobyCresta, the DateInputs has a peer dependency to kendo-angular-intl, which I think is not updated properly. Could you just remove the `kendo-angular-intl` and `kendo-intl` packages and re-install them:
```
rm -rf node_modules/@progress/kendo-angular-intl node_modules/@telerik/kendo-intl && npm i
```

Also the latest version of DateInputs is `v0.6.0`.

If the problem still persists, could you share a runnable demo that demonstrates the issue? More details about the `package.json` would also be helpful.

**Comment by RobyCresta** [comment]
I thought I had updated all packages yesterday, but I did not have the latest version of DateInputs. 
I'm sorry, my fault. 
thank you
