### ISSUE TITLE
Kendo-angular-inputs 0.23.0 breaks kendo-angular-grid 0.25.3

### ISSUE THREAD

**Issue by szavoda** [telerik/kendo-angular#465]
The breaking change in angular-inputs found here [https://github.com/telerik/kendo-angular/issues/463](https://github.com/telerik/kendo-angular/issues/463) generates an error with the grids module, which tries to use [round] in the NumericFilterCellComponent.html file.

**Comment by rkonstantinov** [comment]
This should be addressed by `0.26.0` version of the grid package. Please give it a try.

**Comment by szavoda** [comment]
Looks good so far - thx!
