### ISSUE TITLE
why do we require Kendo Drawing and Kendo File Saver under packages in system js

### ISSUE THREAD

**Issue by rohit-b** [telerik/kendo-angular#466]
why to have overhead to import the full kendo package in the application when one does not require in their application but only few controls
after a recent update i get an error saying kendo drawing missing and after checking the package dependency which are part of the application i did no find any dependency. Is there any documentation update which is missing now?

**Comment by danielkaradachki** [comment]
Which packages are you using? The latest version of the kendo-angular-grid package has a peer dependency to kendo-drawing because of its pdf export feature.

**Comment by rohit-b** [comment]
please update the same in the grid component page under peer dependencies or is there any page discussing the changelog of a particular component then please share it. Thanks

**Comment by tsvetomir** [comment]
The [Grid Overview](http://www.telerik.com/kendo-angular-ui/components/grid/) section was updated in the last site update. Apologies for the caused inconvenience.
