### ISSUE TITLE
Custom Remote Directives: docs issues

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#467]
The documentation here http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/#toc-custom-remote-directives is quite confusing. 

The examples show the use of `this.grid` and that is not possible in TypeScript since `this.grid` is a private property of `DataBindingDirective`, furthermore `constructor(private grid: GridComponent)` this is also not allowed in TS because `grid` is defined in the parent class.

Probably the `grid` property should be protected and not private or we should define our own `_grid` property in the extending directive, either way this should be noted in the documentation.

**Comment by rkonstantinov** [comment]
Thanks for the report. Having the base's grid field as protected is much better and definitely an omission on our side which will be addressed with `0.25.5` version of the grid package.

**Comment by moxival** [comment]
This was fixed, thanx!
