### ISSUE TITLE
kendo angular grid for angular 2

### ISSUE THREAD

**Issue by HenrryPires** [telerik/kendo-angular#468]
Hello to all 

We are a team of 6 members and we are considering using the kendo tool-set.

I am setting up a sample project to show to my team but i am getting some errors. 
this is my configuration:

package.json
  "dependencies": {
      "@angular/common": "2.4.4",
      "@progress/kendo-angular-dropdowns": "^0.38.0",
      "@progress/kendo-angular-grid": "^0.25.4",
      "@progress/kendo-angular-inputs": "^0.23.0",
      "@progress/kendo-angular-intl": "^0.12.0",
      "@progress/kendo-angular-l10n": "^0.3.0",
      "@progress/kendo-data-query": "^0.5.1",
      "@progress/kendo-drawing": "^0.15.5",
      ...
  }

appModule.ts
...
import { GridModule } from '@progress/kendo-angular-grid';
...
@NgModule({
    declarations: [...],
    imports: [GridModule, ...]
    bootstrap: [AppComponent]
})

the component template HTML

<kendo-grid [data]="cleanDeliveries" [height]="370"> 
<kendo-grid-column field="routeNumber" title="ID" width="40">
    </kendo-grid-column>
    <kendo-grid-column field="dropId" title="Name" width="250">
    </kendo-grid-column>
    <kendo-grid-column field="invoiceNumber" title="Category">
    </kendo-grid-column>
    <kendo-grid-column field="accountId" title="Price" width="80">
    </kendo-grid-column>
    <kendo-grid-column field="assigned" title="In stock" width="80">
   </kendo-grid-column>
  <kendo-grid-column field="deliveryDate" title="Delivery Date">
  </kendo-grid-column>
</kendo-grid>

When i open the page i am getting this error
![untitled](https://cloud.githubusercontent.com/assets/6311325/24951989/0a73af8e-1f6e-11e7-942f-718b831d2438.png)

Also i am getting the feeling that these packages are fro angular 4 and i am using angular 2

Could you please help me out with this issue?

**Comment by P-H-F** [comment]
You can find the list of packages compatible with angular 2.x here: https://github.com/telerik/kendo-angular/issues/346#issuecomment-291180578

**Comment by tsvetomir** [comment]
We addressed this problem in #469
