### ISSUE TITLE
Angular 2: Compatible packages

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#469]
The latest versions of the packages in the suite support only Angular 4.x We recommend upgrading at the earliest of your convenience. Angular 4.x is designated as [Long Term Support version with 18 months of support](https://www.infoq.com/news/2017/04/ng-conf-2017-keynote).

If you're developing an Angular 2.x application you can use the `@ng2` tag to obtain the latest compatible versions. For example, to install the Grid use:

`npm install --save @progress/kendo-angular-grid@ng2 @progress/kendo-angular-dropdowns@ng2 @progress/kendo-angular-inputs@ng2 @progress/kendo-data-query@ng2 @progress/kendo-angular-intl@ng2 @progress/kendo-angular-l10n@ng2`

## Important notes
  * The documentation on the site is out of sync with regards of these packages
  * These packages are not expected to be updated

**Comment by aerlijman** [comment]
Can you give us more help in upgrading to angular 4? I ran what you suggest npm install with @ng2 but still see warnings of all controls  about 2.X. How can I upgrade all controls to version 4 and remove previous references?

If I ran npm install --save @progress/kendo-angular-buttons@ng2 @progress/kendo-angular-l10n@ng2 I still see  npm WARN @progress/kendo-angular-buttons@0.23.0 requires a peer of @angular/common@^2.4.0 but none was installed.
npm WARN @progress/kendo-angular-buttons@0.23.0 requires a peer of @angular/core@^2.4.0 but none was installed.

**Comment by tsvetomir** [comment]
Just install the packages without a tag. This will pull the latest version:

`npm install --save @progress/kendo-angular-buttons @progress/kendo-angular-l10n`

**Comment by aerlijman** [comment]
I still get warnings for buttons after running that without the ng2 tag. Is the 0.23 the latest version?

npm WARN @progress/kendo-angular-buttons@0.23.0 requires a peer of @angular/common@^2.4.0 but none was installed.
npm WARN @progress/kendo-angular-buttons@0.23.0 requires a peer of @angular/core@^2.4.0 but none was installed.

**Comment by tsvetomir** [comment]
No, [the buttons are at 0.24](http://www.telerik.com/kendo-angular-ui/components/buttons/changelog/). You might need to update your package.json manually.

**Comment by aerlijman** [comment]
With that change to .24 I get:

npm WARN @progress/kendo-angular-buttons@0.24.0 requires a peer of @progress/kendo-angular-l10n@^0.3.0 but none was installed.

After changing to 0.3, that other warning was removed.
Where can I get all latest versions that support angular 4 so I can change my package manually?
thx for all!

**Comment by aerlijman** [comment]
Got it in the Change log of every component.
Never mind
thx for all!

**Comment by eliahum** [comment]
Hi
if i run 
npm install --save @progress/kendo-angular-grid@ng2     
in package manager console in VSTS 2015
i get this error 

Unrecognized token in source text.

help please

**Comment by Quovadisqc** [comment]
@eliahum The tag is added at the end of the package name. 
Ex; `npm install --save @progress/kendo-angular-dialog@ng2`

**Comment by tsvetomir** [comment]
Check out the [Angular Update Guide](https://angular-update-guide.firebaseapp.com/). First impressions are good.

![screen shot 2017-06-16 at 8 10 52](https://user-images.githubusercontent.com/247917/27212827-67e66032-526b-11e7-87dc-5b60cb0cdb6d.png)
