### ISSUE TITLE
Typo in kendo.culture.nb-NO.js

### ISSUE THREAD

**Issue by tomaszgrabowski** [telerik/kendo-angular#470]
last: "Sidste side" ->       last: "Siste side",

**Comment by ggkrustev** [comment]
Hi @tomaszgrabowski, I just like to clarify whether the suggested improvement is for [Kendo UI for jQuery](http://www.telerik.com/kendo-ui)? The [Kendo UI for Angular](http://www.telerik.com/kendo-angular-ui/) (community known as Angular 2) messages are kept in a [different format](https://github.com/telerik/kendo-angular-messages).

If this is the case, then I can offer you to move the issue in the correct repo, where it can be addressed. It will be even better if you can make a [PR](https://github.com/telerik/kendo-ui-core/pulls)

**Comment by tomaszgrabowski** [comment]
Hello!
Yes it should be in Angular thread. Sorry!
Tomasz

2017-04-14 8:43 GMT+02:00 Georgi Krustev <notifications@github.com>:

**Comment by ggkrustev** [comment]
Hi, no problem at all. I moved the issue in the `kendo-ui-core` repo where it could be addressed.

Link: https://github.com/telerik/kendo-ui-core/issues/3052
