### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HenrryPires** [telerik/kendo-angular#472]
Hi to all

Is there anywhere i can find the full documentation for angular2 components? The samples are built on angular 4 and I am using ver. 2

**Comment by gyoshev** [comment]
As noted in https://github.com/telerik/kendo-angular/issues/469, the documentation will continue onwards with Angular 4, as Angular 2.x will not receive any updates. The upgrade path to Angular 4.x is short, it is planned to be a long-term support (LTS) version, and is the only officially supported version by angular-cli, so upgrading is recommended.
