### ISSUE TITLE
Sortable grid does not reflect changes upon edit/delete row

### ISSUE THREAD

**Issue by Rafunk** [telerik/kendo-angular#474]
A nonpaged (bound to array), sortable grid does not refresh its view when a row is updated or deleted.
The view is refreshed only when you change the sort column/direction.

[http://plnkr.co/edit/u8NhXWyLabcsvUBs3wtU](url)

**Comment by rkonstantinov** [comment]
Indeed, when Grid component is populated using automatic operations, mutating the data passed to the `kendoGridBinding` directive will not be tracked. You will need to create a new instance of it instead. 

An updated version of the remove and save handlers, demonstrating possible implementation:
```javascript
 public saveHandler(customer: Customer) {
      if(this.isNew) {
        this.gridData = this.gridData.concat([customer]);
      } else {
        let i = this.gridData.findIndex(c => c.Id == customer.Id);
        this.gridData = [
          ...this.gridData.slice(0, i),
          customer,
          ...this.gridData.slice(i + 1)
        ];
      }
      this.editDataItem = undefined;
  }
  
  public removeHandler({dataItem}) {
      let i = this.gridData.findIndex(c => c.Id == dataItem.Id);
      this.gridData = [
        ...this.gridData.slice(0, i),
        ...this.gridData.slice(i + 1)
      ];
  }  
```

**Comment by Rafunk** [comment]
Your explanation it's crystal clear.
I was able to make it work, thanks!
