### ISSUE TITLE
Tabstrip - Will support tabPosition(left, right, bottom) in coming release？

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#475]
Hi Kendo team,

I notice that previous Kendo UI Tabstrip supports tabPosition, http://demos.telerik.com/kendo-ui/tabstrip/tab-position  so is there any plan for this feature in kendo angular tabstrip ?

Thanks,
Shane

**Comment by petyosi** [comment]
Hi, 

the feature is not in our immediate plans - please post it in our feedback portal. We will consider it for our next iterations. 

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback

**Comment by MaklaCof** [comment]
Needed the same functionality.
Tried this and works (for now):
```
/deep/ kendo-tabstrip {
                flex-direction: row;

                ul {
                    flex-direction: column;
                    border-right-width: 1px;
                    border-bottom-width: 0;

                    li {
                        &.k-state-active {
                            border-bottom-color: inherit;
                            border-right-color: $body-bg; /*Not sure if $component-bg should be used.*/
                            margin-right: -1px; /*Insures li border is over ul border*/
                        }
                    }
                }
            }

```
Image:
![chrome_2017-12-11_09-13-30](https://user-images.githubusercontent.com/1589573/33821324-b70bd1aa-de53-11e7-8f7c-38b4b78cfcde.png)

Not sure if this is all that needs to be done, but if it is, kendo team should add this feature. They would spend more time evaluating feedback portal then implementing.
