### ISSUE TITLE
Grid export as PDF : Remove / hide column

### ISSUE THREAD

**Issue by nlgi** [telerik/kendo-angular#476]
Hi,

Many thanks for PDF export (wishing Excel !)

I'd like to remove columns in my export, like an "action column" with buttons (same as kendo-grid-command-column, exported in PDF too).
Like with jQuery, i added a class on the cell and on the header cell. The column doesn't appear, but the grid's body doesn't take 100% width.

See plunker: http://plnkr.co/edit/k9R5TUIXCokZSTe8wnER?p=preview

Many thanks,

Regards,

**Comment by danielkaradachki** [comment]
The latest version supports configuring the [exported columns](http://www.telerik.com/kendo-angular-ui/components/grid/pdf-export/#toc-customizing-exported-columns) so now this can be achieved by including the columns that you need in the `kendo-grid-pdf` component:

http://plnkr.co/edit/3C3JxePUpGxJHzIefEvF?p=preview
