### ISSUE TITLE
MultiSelect allowCustom

### ISSUE THREAD

**Issue by jacktho** [telerik/kendo-angular#478]
How would I allow custom values in a MultiSelect. I do not see the allowCustom input in the documentation. Is this a feature still to come or do we roll our own using the filterChange event?

**Comment by KirilNN** [comment]
Hi @jacktho,

Currently the custom tag option is not supported for the MultiSelect component. It is however part of our future plans for sure.

**Comment by jacktho** [comment]
Thank you @KirilNN. I look forward to seeing that feature.

**Comment by valchev** [comment]
The feature was added in the latest dev version of the package.

**Comment by tsvetomir** [comment]
Shipped, see [Custom Values](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/custom-values/) for more info.
