### ISSUE TITLE
Grid: Custom filter component

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#479]
When using custom filter component (dropdown) for the grid, the component gets recreated on the first change event.

See here (`console.log`):
http://plnkr.co/edit/8IDk7qbgb9NfqI3OaLPv?p=preview

While this can be handled (as you show in the example) it would be much better if this wasn't happening.

**Comment by rkonstantinov** [comment]
Thanks for the report. It should be addressed with 0.26.3 version of kendo-angular-grid package.
