### ISSUE TITLE
Slider handle can go off the track limit

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular#481]
Before `v0.21.3`
![screen shot 2017-04-18 at 12 06 12 pm 2](https://cloud.githubusercontent.com/assets/5158181/25140949/f5447a50-242f-11e7-8b72-ae5712d57c58.png)

Since `v0.21.3`
![screen shot 2017-04-18 at 12 08 01 pm 2](https://cloud.githubusercontent.com/assets/5158181/25140964/05a5aacc-2430-11e7-8b21-e699dfb26c4a.png)

As you can see, since `v0.21.3`, the maximum left position of the handle is outside the track. This isn't related to the `@progress/kendo-theme-default` package. What causes this bug is really `v0.21.3` of `@progress/kendo-angular-inputs` (even though the change log only notes a bug fix for "do not include buttons when hidden")

**Comment by KirilNN** [comment]
@maximedupre can you help me create a sample where the issue can be reproduced, so I can better understand the problem? Check this [plunkr](http://plnkr.co/edit/qDmONWuCIFyjQBwrYLQO?p=preview)

**Comment by maximedupre** [comment]
I've upgraded everything for angular 4 and now I can't reproduce this issue.

**Comment by KirilNN** [comment]
So can I close the issue?

**Comment by maximedupre** [comment]
No I'm working on reproducing the issue in your plunkr.

**Comment by maximedupre** [comment]
It was a custom CSS issue. In the original component, half of the handle overflows each side of the slider track when placed at maximum or minimum value. In our application, we want the handle to always stay inside the slider boundaries (like screenshot 1). The following CSS examples assume that the handle has a width of 12px.

This was the custom CSS before `v0.21.3`:

    kendo-slider .k-slider-wrap .k-slider-track {
	    left: 6px !important;
	    margin-left: 1px;
    }

    kendo-slider .k-slider-wrap .k-slider-track .k-slider-selection {
        margin-left: -6px;
    }

The previous CSS doesn't work in the newest versions because of some "breaking changes". The custom CSS for after `v0.21.3`:

    kendo-slider .k-slider-wrap .k-slider-track {
        box-sizing: border-box;
        border-left: 6px solid transparent;
        border-right: 6px solid transparent;
    }

I understand that is impossible to support custom CSS code and that it might break with future releases. Maybe add some variables in the SASS that allows to achieve something similar?

Anyway, thanks for the help.
