### ISSUE TITLE
Unmet dependencies when using kendo-angular-grid

### ISSUE THREAD

**Issue by sebasfiorent** [telerik/kendo-angular#482]
npm install --save @progress/kendo-angular-grid @progress/kendo-angular-grid @progress/kendo-angular-l10n @angular/animations

+-- @angular/animations@4.0.2
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-dropdowns@^0.38.0
+-- @progress/kendo-angular-grid@0.26.5
| +-- @progress/kendo-file-saver@0.1.2
| `-- @telerik/kendo-draggable@1.5.1
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-inputs@^0.23.0
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-intl@^0.12.0
+-- @progress/kendo-angular-l10n@0.3.0
+-- UNMET PEER DEPENDENCY @progress/kendo-data-query@^0.5.0
`-- UNMET PEER DEPENDENCY @progress/kendo-drawing@^0.14.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-angular-dropdowns@^0.38.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-angular-inputs@^0.23.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-angular-intl@^0.12.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-data-query@^0.5.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-drawing@^0.14.0 but none was installed.

**Running again to install for example dropdowns get unmet dependencies also**
npm install --save @progress/kendo-angular-dropdowns

ui@0.0.0 C:\Users\sebas\Documents\Proyectos\sdc\somon\backend\src\main\ui
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-dropdowns@0.39.1
| +-- @progress/kendo-angular-popup@0.17.0
| | `-- @progress/kendo-popup-common@0.3.4
| `-- @telerik/kendo-dropdowns-common@0.2.2
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-inputs@^0.23.0
+-- UNMET PEER DEPENDENCY @progress/kendo-angular-intl@^0.12.0
+-- UNMET PEER DEPENDENCY @progress/kendo-data-query@^0.5.0
`-- UNMET PEER DEPENDENCY @progress/kendo-drawing@^0.14.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-angular-dropdowns@^0.38.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-angular-inputs@^0.23.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-angular-intl@^0.12.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-data-query@^0.5.0 but none was installed.
npm WARN @progress/kendo-angular-grid@0.26.5 requires a peer of @progress/kendo-drawing@^0.14.0 but none was installed.

**Comment by sebasfiorent** [comment]
Following this guide doesn't work neither: http://www.telerik.com/kendo-angular-ui/components/grid/

**Comment by tsvetomir** [comment]
Thanks for the heads-up, we'll get this fixed. You can safely ignore the warnings for the moment, the Grid will operate normally.

We'll also update the documentation with more information regarding `@angular/animations`, see #454

**Comment by tsvetomir** [comment]
This is fixed in v0.26.6 of the Grid package.
