### ISSUE TITLE
Grid toolbar with kendoGridAddCommand Error

### ISSUE THREAD

**Issue by szavoda** [telerik/kendo-angular#484]
With the following code:

`                        <kendo-grid-toolbar>
                            <button kendoGridAddCommand>Add new</button>
                        </kendo-grid-toolbar>`

I receive the error:

ERROR Error: Uncaught (in promise): Error: No provider for EditService!

Using Grid version 0.27.0 - I also regressed to 0.26.3 (I think) and found the same issues.

**Comment by rkonstantinov** [comment]
It seems that on [our demo site](http://www.telerik.com/kendo-angular-ui/components/grid/editing/) editing is working as expected. Maybe you could provide a runnable sample which demonstrates the issue in question.

**Comment by szavoda** [comment]
Please take a look at this page for a sample of the error: [http://jsa-seed.azurewebsites.net/#/test/editserviceerror](http://jsa-seed.azurewebsites.net/#/test/editserviceerror).

**Comment by rkonstantinov** [comment]
Looking at the page source, it seems that the `kendo-grid-toolbar` component is placed outside of the `kendo-grid`, which is not supported.

**Comment by szavoda** [comment]
That would do it - sorry for the inconvenience...
