### ISSUE TITLE
Tabbing into a MaskedTextBox with ( at the start

### ISSUE THREAD

**Issue by jacktho** [telerik/kendo-angular#485]
If you tab into a MaskedTextBox like the basic example in the [documentation](http://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/), the first number pressed is overwritten by the second number pressed.

IE. With focus elsewhere, tab to the input, press 1 then 2. The value will now be 2 instead of 12.

**Comment by szavoda** [comment]
Confirming that I am having this problem as well with phone mask...

**Comment by rusev** [comment]
I can confirm that we are able to replicate the described behavior. We will investigate it and will update this thread when we have more details.

**Comment by rusev** [comment]
Version 0.23.5 will contain a fix for this issue.
