### ISSUE TITLE
The grid now has @progress/kendo-angular-excel-export peer dependency

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#486]
The new dependency is required for the grid excel export feature.

**Comment by EricSch** [comment]
Which is the lastest version, without the excel export modul? The latest version breaks my build.

Thanks

**Comment by tsvetomir** [comment]
Turned out to be an issue with Rollback that we've worked around in #489 

Projects based on Angular CLI or Angular Quickstart seem to be unaffected.
