### ISSUE TITLE
Opening a second dialog opens behind first dialog

### ISSUE THREAD

**Issue by szavoda** [telerik/kendo-angular#487]
Many times, I have a dialog that give the user, for example, a grid of items to work with.  In that grid, the will want to delete something which shows another modal dialog to confirm the deletion.

When the delete confirmation opens, it opens behind the calling dialog box.

Example of issue: [http://jsa-seed.azurewebsites.net/#/test/modalproblem](http://jsa-seed.azurewebsites.net/#/test/modalproblem)

**Comment by gyoshev** [comment]
The dialog windows do not maintain their z-index, but use the DOM order. To place one modal over another, make sure that it is placed later in its declaration, or change its z-index via CSS.

To illustrate this in the linked example, you can either move the `<delete-confirm-modal>` element after the `<kendo-dialog>`, or style it with `position: relative; z-index: 10003;`. For this specific example you can also consider opening the confirmation dialog through an [angular service](http://www.telerik.com/kendo-angular-ui/components/dialog/service/), and placing its `kendoDialogContainer` at the end of the page.
