### ISSUE TITLE
Adding second item in grid edit mode has no values

### ISSUE THREAD

**Issue by szavoda** [telerik/kendo-angular#488]
Base on the demo: [http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-template-forms/](http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-template-forms/).

On the example, click "Add New".  Add an item with values in all fields.  "Add New" again and input new values.  Notice that the 2nd new item does not reflect the values.

Additionally, the second item row defaults to the 1st items values even though the item passed to the "addRow" function is a new Product() and should not have values.

**Comment by tsvetomir** [comment]
Thanks for the bug report, we'll look into it.

**Comment by rusev** [comment]
@szavoda Version 0.28.3 of `kendo-angular-grid` package will address this issue. Thank you for reporting it once again.
