### ISSUE TITLE
How can I add a foreign key custom dropdown  editor for grid column ? 

### ISSUE THREAD

**Issue by erangaapp** [telerik/kendo-angular#491]
Please add a sample for forign key binding with dropdown editor control in a grid column. 

Tnx

**Comment by rusev** [comment]
Indeed we will add such example.

**Comment by erangaapp** [comment]
Oki.. 

I m trying to make it as follows. Can you please make me correct with few lines. I can't manage the editMode with dataitem. Please help me with few lines.

> <kendo-grid-column width="150px" field="client" title="Client" let-dataItem>
>                 
>                     <template kendoGridCellTemplate>
>                         <div *ngIf=dataItem.isEditMode else viewBlock>
>                             <kendo-combobox [data]="clientData"
>                                             [textField]="'code'"
>                                             [valueField]="'id'"
>                                             [filterable]="true"
>                                             (filterChange)="handleClientFilter($event)"
>                                             [placeholder]="'Please select'">
> 
>                                 <template widht="100%" kendoComboBoxItemTemplate let-dataItem>
>                                     <span class="template">{{ dataItem.code + ' ' + dataItem.name }}</span>
>                                 </template>
>                             </kendo-combobox>
>                         </div>
>                         <template #viewBlock>{{ dataItem.code + ' ' + dataItem.name }}</template>
>                     </template>
> 
>             </kendo-grid-column>

**Comment by erangaapp** [comment]
I got a sample . Tnx all. 

http://www.telerik.com/kendo-angular-ui/components/grid/editing/custom-reactive-editing/
