### ISSUE TITLE
Open another dialog from a dialog

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#492]
It seems that it is currently not possible to open from a dialog (for example a detail view) a confirmation dialog ("do you really want to delete...?"). If you don't do anything the new dialog lies behind the already opened one.

You can find a plunker example based on one of your example the situation. Just press on the second dialog the open dialog button.
http://plnkr.co/edit/htcfqiLUfRQnZNA9yyXV?p=preview

I found out, that if i put on the dialog component another dialog container the behavior is slightly better (i can in this case at least see me dialog because it is not behind the other). However i don't know if this is the way to go and the shade is still not working.

Thanks for some information about how this can be accomplished.

**Comment by gyoshev** [comment]
@rdnscr this has been confirmed as a bug in the dialog. We are working on a fix that will resolve this. For an immediate workaround, don't use the `DialogService` if you need to create multiple dialogs that are visible at the same time. Instead, declare them in the template.

**Comment by gyoshev** [comment]
The bug has been fixed in version `0.21.1` of the dialog.
