### ISSUE TITLE
Multi Select breaks the router with server side rendering

### ISSUE THREAD

**Issue by yanbu0** [telerik/kendo-angular#494]
I have a few pages that have the kendo-multiselect widget on them.  All of them are no longer directly navigable to, by which I mean if I paste in the url to navigate directly to that page or hit refresh while on that page I get the below exceptions.  Strangely enough, if I click a link to get to the page, it works.  If I comment out the <kendo-multiselect> node everything starts to work properly again, but the multiselect doesn't render.

![image](https://cloud.githubusercontent.com/assets/26099646/25412310/40af382e-29ce-11e7-91c2-fcae27d0dad4.png)

Config:
```
<kendo-multiselect style="width:400px"
                               [data]="siteValues"
                               [textField]="'siteCode'"
                               [valueField]="'siteId'"
                               [(ngModel)]="siteFilters"
                               [placeholder]="'Select Sites To Filter...'"
                               (valueChange)="updateFilter($event, workSection)">
</kendo-multiselect>
```

Note that it doesn't seem to matter what the config is, even the below will re-create the error: 
`<kendo-multiselect></kendo-multiselect>`

Also, I have confirmed that if I turn off server side rendering, the error does not occur.

**Comment by KirilNN** [comment]
Hi @yanbu0,

The error message that you paste looks like .NET related, and the behavior that you describe is not a familiar one. Would it be possible to isolate a sample where the issue can be debugged?

**Comment by yanbu0** [comment]
I'm not sure how to isolate a sample.  I'd have to set up server side rendering, Node, et cetera.  I don't think thats possible in Plunker.  Could probably send you a zip file or something?

This isn't a problem with .NET though.  Like I said, exact same page with the kendo-multiselect commented out of the html works fine.  Page with the kendo-multiselect commented back in and server side rendering turned off, works fine too.  There is an issue with this widget and server side rendering.

**Comment by yanbu0** [comment]
I dug around in the logging a bit more and found this error: 
```
originalStack: 'Error: Uncaught (in promise): TypeError: Cannot read property \'add\' of undefined\nTypeError: Cannot read property \'add\' of undefined\n    at MultiSelectComponent.ngAfterViewInit 
```

**Comment by yanbu0** [comment]
Continued looking into this today.  I spun up a template that has server side rendering and inserted the multi select and continued to get the error, although it is being handled gracefully in my template for some reason so the page renders, but the multiselect doesn't really work properly.

I took a look into the javascript and found exactly where the failure is occurring.  It happens on the first "add" call on observableSubscriptions below:
```
    MultiSelectComponent.prototype.ngAfterViewInit = function () {
        var _this = this;
        this.searchbar.resizeInput(Math.max(1, this.placeholder.length));
        this.observableSubscriptions.add(this.searchbar.onFocus.subscribe(function (event) {
            if (!_this.isFocused) {
                _this.isFocused = true;
                _this.onFocus.emit(event);
            }
        }));
        this.observableSubscriptions.add(this.searchbar.onBlur.subscribe(function (event) {
            if (_this.isFocused) {
                _this.isFocused = false;
                _this.onBlur.emit(event);
                _this.onTouchedCallback();
            }
        }));
    };
```

**Comment by rusev** [comment]
I think we've spotted the cause of the issue. Version `0.39.8` should contain a fix for it. 
Please give it a try and let us know how it goes.

**Comment by yanbu0** [comment]
Updated to `"@progress/kendo-angular-dropdowns": "^0.39.8",` and everything works as expected!!!  Thanks!
