### ISSUE TITLE
Theming: Styling DatePicker and TimePicker with bootstrap

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#495]
Would be nice, when the controls are following the bootstrap rules.

Like you see here http://plnkr.co/edit/6NpdvAJ7slyPC1mKvioI?p=preview, the control isn't using the whole width for the column. 
Is there a workaround? Setting the control to 100% width, let grow only the right side button.

Txs

**Comment by gyoshev** [comment]
Currently the theme does not provide integration with the Bootstrap forms. This is a feature we have logged in https://github.com/telerik/kendo-theme-default/issues/450 . The plunker demo shown in that issue shows some styles that you can apply to achieve the effect, or wait for the feature to be implemented and update the theme.

Alternatively, consider using the [Kendo UI form styles](http://www.telerik.com/kendo-angular-ui/components/forms/).
