### ISSUE TITLE
Sortable does not work in IE when items are buttons

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#497]
When buttons are used as items in a Sortable component, they cannot be dragged in IE (update v. 11.0.41).

Reproducible in the following example:

[http://plnkr.co/edit/IHKj33rgbdFF8P7WKuZH?p=preview](http://plnkr.co/edit/IHKj33rgbdFF8P7WKuZH?p=preview)

**Comment by Xizario** [comment]
Set `draggable="true"` in the declaration of your button to resolve it.

**Comment by tsvetomir** [comment]
There's little we can do here since the `<button>` element is in a template.

We'll update the documentation to highlight this limitation.

**Comment by tapopov** [comment]
Same goes for anchor elements, as noted [here](https://github.com/telerik/kendo-angular-sortable/issues/69)

**Comment by tsvetomir** [comment]
Documented in [Known Limitations](http://www.telerik.com/kendo-angular-ui/components/sortable/#toc-known-limitations)
