### ISSUE TITLE
Panelbar header template

### ISSUE THREAD

**Issue by dydFreeman** [telerik/kendo-angular#498]
Is it possible to customize the panelbar header?
For istance, adding custom components within a ng-template?

I would like to replace the expand icon with a custom button:
![image](https://cloud.githubusercontent.com/assets/2900220/25425136/2c054d44-2a6b-11e7-88ac-435f2933e05e.png)

**Comment by Raisolution** [comment]
Hi @dydFreeman,

You could use the _icon_ or _iconClass_ properties of the PanelBarItemComponent to achieve this -
 [documentation](http://www.telerik.com/kendo-angular-ui/components/layout/api/PanelBarItemComponent/).

If additional customization is needed, use the [PanelBarItemTitleDirective](http://www.telerik.com/kendo-angular-ui/components/layout/api/PanelBarItemTitleDirective/).

**Comment by dydFreeman** [comment]
Hi @Raisolution , thanks a lot!

**Comment by alexeikostevich** [comment]
I am so excited to have these rich customization features already in place! 
From my perspective, it could be helpful for others to provide an example of a [PanelBarItemTitleDirective](http://www.telerik.com/kendo-angular-ui/components/layout/api/PanelBarItemTitleDirective/) usage on the [PanelBar/Tempates](http://www.telerik.com/kendo-angular-ui/components/layout/panelbar/templates/) page.

Thank you!

**Comment by tsvetomir** [comment]
Documented in [Customizing the Appearance of the Title
](https://www.telerik.com/kendo-angular-ui/components/layout/panelbar/templates/#toc-customizing-the-appearance-of-the-title).
