### ISSUE TITLE
DatePicker: localization

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#499]
In en-US it shows the text: 
![image](https://cloud.githubusercontent.com/assets/25437/25433067/62d595ec-2a87-11e7-8052-9546072cfd9f.png)

In de-CH it doesn't:
![image](https://cloud.githubusercontent.com/assets/25437/25433096/7e1bdbd6-2a87-11e7-852b-c1e1ddefdcfa.png)

The project (IntlService, ..) is correctly configured, everything else is translated correctly.
I assume you are using the CLDR packages and not LocalizationService for that?

Thanks

**Comment by danielkaradachki** [comment]
Seems to be working [here](http://plnkr.co/edit/4ATApJGTonMrZRGOaXOu?p=preview). Have you loaded the `cldr-data/main/de-CH/dateFields.json` data?

**Comment by EricSch** [comment]
No, that was it. 
Seems I didn't got the requirements changes 😄, I was still loading only 4 local data files.

**Comment by danielkaradachki** [comment]
I guess we should throw an error in this case. We will fix this.

We are also considering generating locale files that include all the data that we need. Should simplify the loading unless you are also using the cldr data for some other purpose.

**Comment by EricSch** [comment]
Locale files:
Using generally the cldr data is a smart move. So if you stick to the format, but prebuilding them, this would simply our whole build process. Are you also considering to load configured languages automatically?
We are using the cldr data only for your controls.

**Comment by danielkaradachki** [comment]
Could you clarify what you mean by "load configured languages automatically"? 
I do not think we can dynamically load a locale when requested without including all locales in the bundle.

**Comment by tsvetomir** [comment]
This could be solved elegantly by an Angular CLI plugin.
Sadly, the extensibility story there is still [up in the air](https://github.com/angular/angular-cli/issues/2906).

**Comment by EricSch** [comment]
And we don't use Angular CLI.
I solved it via a factory provider for the APP_INITIALIZER in app.module.ts.         `       {
            provide: APP_INITIALIZER,
            useFactory: AppInitializerFactory.initialize,
            deps: [UserService],
            multi: true
        },`
This loads depending of our language (LOCALE_ID, that depends on the browser language), the corresponding cldr data (only one language). Of course we published first all (for us) possible cldr JSON files to our wwwroot folder. 

Perhaps including a loader which assumes those files somewhere in the wwwroot or via CDN and the publishing depends on the build process?

**Comment by danielkaradachki** [comment]
Thank you for clarifying. 

I do not think that assuming a specific path is a good option for a library and given that setting the required data will a single line of code with the generated locales, I think that we should leave this to the developers at least for now.

**Comment by tsvetomir** [comment]
The pre-built locales have been added in v1.1.0 of the `@progress/kendo-angular-intl package`.
See [Load Pre-Built Data](http://www.telerik.com/kendo-angular-ui/components/internationalization/#toc-load-pre-built-data) for more details.
