### ISSUE TITLE
ToolbarComponent: position in grid

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#500]
Hey guys

please make it possible to position the grid toolbar below the pager toolbar in a grid. At the moment i can not find a way to do that and a grid with filters/headers and groups looks a bit too much when the toolbar is added:
![image](https://cloud.githubusercontent.com/assets/323925/25476241/3b945a98-2b42-11e7-8022-16ad9461e6c8.png)

**Comment by rkonstantinov** [comment]
Thanks for the suggestion. Indeed, we are considering this. Unfortunately with current implementation it will require a breaking change in the way toolbar is declared. Most probably the declaration will be changed from `<kendo-grid-toolbar>...</kendo-grid-toolbar>` to a `<ng-template kendoGridToolbar>...</ng-template>`.

**Comment by rkonstantinov** [comment]
Hey @moxival, the toolbar positioning is available with 0.32.0 version of the Grid package. Please check the https://github.com/telerik/kendo-angular/issues/509 for a code snippet of the configuration. Possible values are `top`, `bottom` and `both`. Also the docs site will be updated in the following days to show the change in the configuration.

**Comment by moxival** [comment]
Hi @rkonstantinov thanx for this, now it looks awesome! You can close this issue.
