### ISSUE TITLE
Blur/click outside on Dropdownlist on IE11

### ISSUE THREAD

**Issue by adnanakgun** [telerik/kendo-angular#502]
It seems the Dropdownlist component doesn't close when blurred or clicked outside on IE11.

Test the Dropdownlist on this page using IE11:
http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/

It does close when testing with Chrome.

**Comment by tsvetomir** [comment]
The fix is included in v1.0.9 of the `@progress/kendo-angular-dropdowns` package
