### ISSUE TITLE
[NumericTextBox] Visible format on focus

### ISSUE THREAD

**Issue by dydFreeman** [telerik/kendo-angular#503]
Now format (ex: $ for currency) is hidden on focus.
Do you think will be possible to have it always visible?

**Comment by petyosi** [comment]
Hi, 

That sounds interesting, we haven't seen such behavior. I imagine something like a readonly/disabled segment of the input. I may be missing the point, though. Are you aware of a component (regardless of the platform) that behaves like the one you describe? We would like to examine it.

**Comment by tsvetomir** [comment]
Perhaps the [MaskedTextBox](http://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/) is more suitable for this scenario.

**Comment by dydFreeman** [comment]
Hi @petyosi 
I don't know of a component that has this behaviour, btw it would be nice to have something like that: http://stackoverflow.com/questions/15181417/how-to-make-only-some-text-in-a-text-box-read-only-while-allowing-the-rest-to-be.  
This is our scenario:
 - Different measure units
 - No max lenght for the input (so we cannot use a MasketTextBox as suggested by @tsvetomir )

**Comment by tsvetomir** [comment]
Our recommendation is to place the format hint besides the input, as in [this Bootstrap example](https://v4-alpha.getbootstrap.com/components/input-group/#basic-example).

There are no plans to make this a built-in feature at the moment.

**Comment by tsvetomir** [comment]
Check out [Using with Input Groups](http://www.telerik.com/kendo-angular-ui/components/forms/integration-with-bootstrap/#toc-using-with-input-groups) for an example with our components.
