### ISSUE TITLE
kendo-grid filter entered SelectionChange click wrong index

### ISSUE THREAD

**Issue by cimachris** [telerik/kendo-angular#504]
Using Kendo-angular-grid 0.30.0

Kendo Grid Issue:

Code:
                
```
<kendo-grid [kendoGridBinding]="projectList" (selectionChange)="onSelect($event)" [height]="810" [pageSize]="20"
            [pageable]="true"
            [sortable]="true"
            [filterable]="true"
            [groupable]="true"
            [selectable]="true" 
            >
    <kendo-grid-column field="projectid" title="Project ID" width="80"></kendo-grid-column>
    <kendo-grid-column field="projectname" title="Project" width="250"></kendo-grid-column>
    <kendo-grid-column field="projectnum" title="Project Num"></kendo-grid-column>
    <kendo-grid-column field="cima_status" title="Project Status"></kendo-grid-column>
    
</kendo-grid>
```

When I do the filter and click an item in the table, the index returned is for another row.  

No Filter the correct index is returned.  Type a filter in, and the incorrect is returned.  Remove the filter and it shows another row selected.
![kendoissue-1](https://cloud.githubusercontent.com/assets/28155841/25538603/00d7056e-2c09-11e7-9178-260ccfcef9eb.PNG)
![kendoissue-2](https://cloud.githubusercontent.com/assets/28155841/25538602/00d6badc-2c09-11e7-8567-7a2f142a4eee.PNG)
![kendoissue-3](https://cloud.githubusercontent.com/assets/28155841/25538604/00db93fe-2c09-11e7-8a9d-f869a4999b4e.PNG)

**Comment by rkonstantinov** [comment]
The index provided in the select event is the index of the data displayed in the component. Thus, when the Grid is filtered the index will be correct for the filtered data, not for the entire, non-filtered data set. This means that you cannot apply the index directly to the original data, but instead you can use the Grid component's data field to access the processed one. For example: 
```js
import { Component, ViewChild } from '@angular/core';
import { customers } from './customers';
import { GridComponent } from '@progress/kendo-angular-grid';

@Component({
    selector: 'my-app',
    template: `
        <kendo-grid
            [kendoGridBinding]="gridData"
            [pageSize]="10"
            [pageable]="true"
            [sortable]="true"
            [filterable]="true"
            [groupable]="true"
            [selectable]="true"
            (selectionChange)="onSelect($event)"
            [height]="510">
            <kendo-grid-column field="CompanyName" [width]="140"></kendo-grid-column>
            <kendo-grid-column field="ContactName" [width]="120"></kendo-grid-column>
            <kendo-grid-column field="City" [width]="100"></kendo-grid-column>
            <kendo-grid-column field="ContactTitle" [width]="130"></kendo-grid-column>
        </kendo-grid>
    `
})
export class AppComponent {
    @ViewChild(GridComponent) grid : GridComponent;
    
    private gridData: any[] = customers;
    
    public onSelect({ index }) {
      const dataResult = this.grid.data;
      console.log(JSON.stringify(dataResult.data[index], null, 2))
    }
}
```
Note that accessing the Grid's data should not be needed once the new selection functionality and API are ready as the dataItem will be available inside the selectionChange event handler.

**Comment by cimachris** [comment]
Re: Note that accessing the Grid's data should not be needed once the new selection functionality and API are ready as the dataItem will be available inside the selectionChange event handler.

Is this going to be released soon?

**Comment by rkonstantinov** [comment]
I'm afraid that I cannot commit to a time frame for when the new selection API will be available.
