### ISSUE TITLE
Cannot see buttom part of screen under your grid sorting plunker, even with browser full screen mode

### ISSUE THREAD

**Issue by Longfld** [telerik/kendo-angular#505]
Cannot see buttom part of screen under your grid sorting plunker, even with browser full screen mode
http://plnkr.co/edit/CCwxOM6MX7SARgQWb6FM?p=preview

Following
http://www.telerik.com/kendo-angular-ui/components/grid/sorting/

I clicked "open as plunker" and create fork a new plunker by using chrome or Firefox, in index.html I've add four  < h3 >hellow< /h3 >  as hellow1, 2, 3 and 4 that you can see here:
 
http://plnkr.co/edit/CCwxOM6MX7SARgQWb6FM?p=preview

as it running,  we can see whole table and I can sort column, but cannot see bottom part of page, which are hellow1,2,3 and 4; with full screen mode, I can see only hellow1,2,3 but 4.
 
Then click "Open the embedded view" button on top right, and http://embed.plnkr.co/CCwxOM6MX7SARgQWb6FM/  opened and still cannot see hellow1,2,3 or 4 at bottom.

But if I open http://plnkr.co/edit/CCwxOM6MX7SARgQWb6FM?p=preview  with IE11 I can see see whole table and hellow1,2,3 but hellow4.

************************
Found the same issue on your grouping, i.e. only the first group show up on plunker screen, rest of grouping not there
http://www.telerik.com/kendo-angular-ui/components/grid/grouping/groping-basics/

**Comment by gyoshev** [comment]
The scrollbars of the page and the `my-app` element are hidden through styles in `index.html`:

    html, body { overflow: hidden; }
    my-app { display: block; overflow: hidden; }

To show the scrollbars, remove these styles.
