### ISSUE TITLE
Allow empty TabStrip tabs when the component is used for navigation

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#506]
The following JavaScript error is thrown if the TabStrip tabs have no content, and some tab is selected:

> TypeError: Cannot read property 'templateRef' of undefined

The following workaround seems to resolve the problem currently:
[http://plnkr.co/edit/OSYPTsxWNOPoVcHawlmb?p=preview](http://plnkr.co/edit/OSYPTsxWNOPoVcHawlmb?p=preview)

... but it would be nice to add built-in support for such scenarios. Navigation via TabStrip is also requested in the following UserVoice entry:

[http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19066006-tabstrip-router-support-for-routes-and-subroutes](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19066006-tabstrip-router-support-for-routes-and-subroutes)

**Comment by Raisolution** [comment]
Fixed
