### ISSUE TITLE
template for .net core, angular-cli, angular 4+, SPA and Keno UI.

### ISSUE THREAD

**Issue by kriskumar70** [telerik/kendo-angular#507]
Hi,
I liked Ed Charbeneau's .core angular 2 example (
http://www.telerik.com/blogs/cooking-with-aspnet-core-and-angular-2).

I am struggling to implement this with angular-cli and latest angular version. Do you have a template that I can use?

Thanks

Kris

**Comment by tsvetomir** [comment]
We have a [project template](http://www.telerik.com/kendo-angular-ui/components/installation/system-js/) based on the [Angular Quickstart](https://angular.io/docs/ts/latest/quickstart.html). 
There's an [official guide](https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html) on how to integrate this project with Visual Studio.

**Comment by MaklaCof** [comment]
Hi, I use [this one](https://github.com/MarkPieszak/aspnetcore-angular2-universal). It is without Kendo, but you can easily add it with npm --save. Everything else works.

**Comment by tsvetomir** [comment]
Thanks @MaklaCof, we'll fork this project as an example on how to integrate with ASP.NET Core.

**Comment by dtopalov** [comment]
[http://www.telerik.com/kendo-angular-ui/components/installation/dotnet-core/](http://www.telerik.com/kendo-angular-ui/components/installation/dotnet-core/)
