### ISSUE TITLE
Grid filter next to Column Header like normal Kendo Grid

### ISSUE THREAD

**Issue by nm-a** [telerik/kendo-angular#508]
Hi,
I couldn't find option to set Filter next Grid Column (http://demos.telerik.com/kendo-ui/grid/filter-menu-customization). Do we have this option in Angular Grid as well.

thank you
-nm

**Comment by rusev** [comment]
Currently there are no plans for filter menu as in the Kendo UI Grid for jQuery. You can log your request in the [Kendo UI for Angular Feedback](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback) portal.

**Comment by TrevorBroderick1** [comment]
I think this is an important feature. The current filter implementation takes up far too much column width. In grids with many smaller columns (such as numeric columns), enabling the filters increases the grid width dramatically and will cause horizontal scrolling.

**Comment by tsvetomir** [comment]
The new [Filter Menu](https://www.telerik.com/kendo-angular-ui-develop/components/grid/data-operations/filtering/#toc-filter-menu) is available for you to try out in the [dev channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). Let us know what you think.

**Comment by TrevorBroderick1** [comment]
That's way better, great work. 👍

I notice the sort icon doesn't show up on the smaller columns due to space constraints. Is that a known issue?

**Comment by gyoshev** [comment]
Yes, this is logged in https://github.com/telerik/kendo-theme-default/issues/708 . It cannot be fixed easily without a rendering change in the grid headers, but we will fix it nevertheless. You can subscribe to the issue to receive a notification when the fix is released.
