### ISSUE TITLE
Grid numeric editor displayed as invalid

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#511]
Hey,
could you explain to me, why the numeric box is displayed as invalid?

Image from your demo:
![image](https://cloud.githubusercontent.com/assets/21359517/25611793/b18dc75e-2f28-11e7-93fe-13263cc1d530.png)

http://www.telerik.com/kendo-angular-ui/components/grid/editing/#toc-configure-the-type-of-the-columns-editor

**Comment by gyoshev** [comment]
We have confirmed this as a bug, and will shortly release a theme version that addresses it.

As for the explanation, the default numeric editor at this time uses `<input type="numeric" />`. The default `step` of this element is `1`, thus the HTML5 validation interprets `121.35` as an invalid value (it is not integer). The theme highlights invalid elements that use the `.k-textbox` class without realizing that the Angular validation has passed. The resolution is to handle the case where the Angular validation passes, but the HTML5 validation fails, and resolve the conflict (in favor of Angular, as it uses `novalidate` to disable form validation).
