### ISSUE TITLE
Datepicker in grid with paging gets overlapped

### ISSUE THREAD

**Issue by mogwai1** [telerik/kendo-angular#512]
Hello,

Datepicker gets overlapped when used as editor template in grid with paging.
See plunkr example
http://plnkr.co/edit/hcUC8BlrmS1R7fdvCmPV?p=preview

Removing [pageSize]="pageSize" line (breaking the paging support), makes datepicker opening without overlapping.

**Comment by tsvetomir** [comment]
Closing this as duplicate of #410. We're working on a fix for the problem.
