### ISSUE TITLE
@progress/kendo-theme-default theme with jQuery grid breaks column size-to-fit

### ISSUE THREAD

**Issue by sprell** [telerik/kendo-angular#513]
For projects needing to use both jQuery and Angular2 Kendo components, my understanding is that we should use the new @progress/kendo-theme-default for both instead of the jQuery specific themes. This theme is supposed to be compatible with both libraries (where the jQuery specific ones are not). However, when doing so, the jQuery grid no longer resizes columns correctly when you double click the right bother of a column header. 

I have an example where I changed this jQuery grid demo...
http://demos.telerik.com/kendo-ui/grid/column-resizing
...to use the new @progress/kendo-theme-default. 

Here is the modified version...
http://dojo.telerik.com/Ekiqu

All I did was replace the existing CSS with this...
http://www.telerik.com/kendo-angular-ui/npm/node_modules//@progress/kendo-theme-default/dist/all.css

The grid seems to look and behave properly otherwise.

**Comment by gyoshev** [comment]
Thank you for reporting this, the styles required for this feature are indeed missing from the theme. Since this tracker is for the angular components, the issue has been moved to https://github.com/telerik/kendo-theme-default/issues/456 .
