### ISSUE TITLE
Pasting into MaskedTextBox from clipboard content does not work as expected.

### ISSUE THREAD

**Issue by sprell** [telerik/kendo-angular#514]
Using this phone number example...
http://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/

If you copy this text onto the clipboard...
359884123321

Then, if you select all text in the MaskedTextBox (either manually or by simply tabbing into the field which will auto-select all the text), and attempt to paste in the clipboard contents, it does not paste all of the numbers. Even if you attempt to copy formatted text as in (359)884-12-33-21 it still does not work as expected and does not paste in everything.

**Comment by rusev** [comment]
Indeed seems like a bug. We will look into it. Thank for reporting it.

**Comment by rusev** [comment]
Version 0.23.5 will contain a fix for this issue.
