### ISSUE TITLE
Mixing Reactive Editing and Template Editing in Grid Breaks Template Editing on Create

### ISSUE THREAD

**Issue by yanbu0** [telerik/kendo-angular#515]
So this one took me down the rabbit hole for hours trying to figure out what was going on. 

If you have a grid with a mix of Reactive Forms editing, i.e. setting the `editor="boolean"` as an example on a `<kendo-grid-column>`, and Template Editing, i.e. using `<ng-template kendoGridEditTemplate>` to define the editor, the template editing column does not bind properly on create of a new row.  Any changes are not propagated to the dataItem and the formGroup is sent to the save handler as it was first instantiated.   The Reactive columns WILL work, however.  Everything seems to work on Edit as well, both Reactive and template editing.

**Comment by yanbu0** [comment]
Grid version : `"@progress/kendo-angular-grid": "^0.26.3`

**Comment by rkonstantinov** [comment]
Is there any particular reason you are mixing the reactive and template-driven forms. It is better to stick to only one of them. 
If you need to customize the appearance of the editors you could still use reactive forms. How to do this is demonstrated in [the docs](http://www.telerik.com/kendo-angular-ui/components/grid/editing/custom-reactive-editing/).

**Comment by yanbu0** [comment]
Yeah, that is what I am doing now, but it was just easier to not have to set up templates for some of the columns.  There isn't an error message or anything in the documentation (that I could find) that said not to do this, and it does appear to work other than on create, so it looked like a bug to me.  Thought I'd submit a bug report since it cost me several hours trying to figure it out, but it isn't something that I need to have to use the grid obviously.  It would be helpful if it isn't going to be fixed to have it throw an error and put something in the docs though as a suggestion.

**Comment by tsvetomir** [comment]
Closing sue to inactivity, but feel free to reopen if you have a test project.
