### ISSUE TITLE
User not found : @telerik/kendo-draggable when installing kendo-angular-grid

### ISSUE THREAD

**Issue by stephankeel** [telerik/kendo-angular#516]
C:\develop\tpa\tpa_webapp\source\src\app>npm view @progress/kendo-angular-grid version
0.32.1

npm install fails:

C:\develop\tpa\tpa_webapp\source\src\app>npm install --save @progress/kendo-angular-grid
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@progress/kend
o-angular-grid"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 User not found : @telerik/kendo-draggable
npm ERR! 404
npm ERR! 404  '@telerik/kendo-draggable' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@progress/kendo-angular-grid'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by tsvetomir** [comment]
Can you try [logging in](http://www.telerik.com/kendo-angular-ui/components/installation/npm-registry/) again?

**Comment by stephankeel** [comment]
looks fine now, thxs
