### ISSUE TITLE
Datepicker - How to change the placeholder string ?

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#517]
Hi kendo team,

Recently I am using  datepicker component,  I'd like to change the default placeholder string "month/day/year" to something else,   for example I change  "placeholder" to be "mm/dd/yyyy" or "__/__/____",   but it does not work.  

So I am wondering is there any way that I can change that ?

Thanks,
Shane

**Comment by ggkrustev** [comment]
Hi Shane,
The `placeholder` property was exposed by mistake. It will be removed for the official release:
https://github.com/telerik/kendo-angular/issues/519

If you would like to change the order of the displayed date parts, then you will need to change the used format using the [`format`](http://www.telerik.com/kendo-angular-ui/components/dateinputs/api/DatePickerComponent/#toc-format) property.

**Comment by mogwai1** [comment]
Hi,
But what about replacing placeholder with custom message for datepicker **without value**?
For example, I want to replace "month/day/year" message with blank line, or phrase like "Enter date".

**Comment by jmaronge** [comment]
I would also like to get rid of it.  I need it to show nothing in the textbox when there is no value set.

**Comment by ggkrustev** [comment]
Hi guys.

Currently, the placeholder cannot be changed to anything custom. It is defined automatically based on the format value. It cannot be hidden too. It will be displayed if the component doesn't have value or it is partially entered.

I would suggest you share your feature request in our feedback portal:
http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

Based on the user interest, we will decide whether to schedule the desired functionality for further investigation.

**Comment by ggkrustev** [comment]
Will close the thread as the discussion should be moved into the feedback portal.

**Comment by hasithapg** [comment]
Hi,

Definitely the placeholder string should allow for customization. When the page viewed in a small device, the text area gets shrink and only can see a part of the format string.

**Comment by ggkrustev** [comment]
Hi @hasithapg, this functionality is already planned and will be introduced till the end of the quarter or sooner. More information about the feature can be found in this issue and the related ones:

https://github.com/telerik/kendo-angular/issues/859

**Comment by imvarnit1996** [comment]
hi @ggkrustev  
I am getting error in using kendodatepicker element when i am using when i try to change date by typing month in it,the cursor does not programmatically move further after '/' to change  date ,I have to manually move it to other portion i.e. after '/' can you help me with it.
