### ISSUE TITLE
Switch and Slider mark the form as "dirty" on initial load

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#518]
Both the Switch and Slider components mark the form as dirty on initial load, if ngModel binding is used:

[http://plnkr.co/edit/5lwtui6VjOleqX4ANo4d?p=preview](http://plnkr.co/edit/5lwtui6VjOleqX4ANo4d?p=preview)

[http://plnkr.co/edit/Lhm4EKMa3FqKn0Qx65Hi?p=preview](http://plnkr.co/edit/Lhm4EKMa3FqKn0Qx65Hi?p=preview)

Related to:
[https://github.com/telerik/kendo-angular-inputs/issues/119](https://github.com/telerik/kendo-angular-inputs/issues/119)
[https://github.com/telerik/kendo-angular-inputs/issues/121](https://github.com/telerik/kendo-angular-inputs/issues/121)

**Comment by rusev** [comment]
Version 1.0.2 of `kendo-angular-inputs` package addressed these issues.
