### ISSUE TITLE
Remove [placeholder] property binding

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#519]
### Description
The DateInput and DatePicker components expose a `placeholder` property incorrectly. By default, the date format string, e.g. month/day/year, is displayed.

The built-in placeholder format can be modified only with changes of the `format` option. The component doesn't accept 'free text'.

**Comment by dtopalov** [comment]
Starting from version 0.9.0, the placeholder property binding is removed from the DateInput and DatePicker components.

**Comment by ggkrustev** [comment]
We've planned to introduce `placeholder` attribute which will work a bit differently. More details can be found here:

- https://github.com/telerik/kendo-angular/issues/911
