### ISSUE TITLE
Popup animates from incorrect position in IE11 on Windows 7

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#522]
Can be observed in [this pulnkr snippet](http://plnkr.co/edit/B4u4CiVDf34DleCmKY3v?p=preview).

**Comment by siyka-marinova** [comment]
Fix for this issue should be released shortly (currently available in the latest dev version).

**Comment by tsvetomir** [comment]
Fixed in v1.0.2 of the kendo-angular-popup package. Run `npm update` to get it.
