### ISSUE TITLE
Missing cdn bundles for kendo-file-saver

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#523]
We have fixed other issues related to cdn/bundle files:

https://github.com/telerik/kendo-angular/issues/350

https://github.com/telerik/kendo-angular/issues/243

But now latest version of `kendo-file-saver` (1.0.0) has not anymore cdn folder.
We have different flows and one of them use cdn files...so could you please add bundle file to `kendo-file-saver`?

I mean for big project we are going with aot compilation and tree shaking....but we already have other setups and we have to maintain flexibility here. Plus you first add bundle, then remove....please keep stable approach to all packages!

What do you think?

**Comment by tsvetomir** [comment]
Nice catch. Will bring back the bundle with an update shortly.

**Comment by tsvetomir** [comment]
Should be good in 1.0.1

**Comment by meriturva** [comment]
Well done and thanks!

**Comment by meriturva** [comment]
With version 1.0.3 issue is back!

**Comment by tsvetomir** [comment]
Sorry, I thought this was fixed for good. On it.

**Comment by tsvetomir** [comment]
Should be fixed in v1.0.4 of the package.

A change to our build process nuked it, but it's fixed for good now.

**Comment by meriturva** [comment]
Fixed! Thanks!
