### ISSUE TITLE
How To works aot when loading CLDR data

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular#524]
My application needs some cldr-data (SystemS-Integrated Application), which works nice until using Aot. After compiling it can't be loaded anymore. 

![grafik](https://cloud.githubusercontent.com/assets/22910183/25703843/86179c98-30d7-11e7-9e77-fabf0b7cfbdb.png)

![grafik](https://cloud.githubusercontent.com/assets/22910183/25703902/c517712a-30d7-11e7-8c46-06022e3f81d4.png)

What can be wrong? Any idea?

Thanks a lot!

**Comment by ggkrustev** [comment]
Hi @anj01,

I would suggest you checking our `kendo-angular-quickstart-cli` project for more details about Intl data loading:

https://github.com/telerik/kendo-angular-quickstart-cli/blob/master/src/app/app.module.ts

The most important part is here:

https://github.com/telerik/kendo-angular-quickstart-cli/blob/master/src/typings.d.ts

**Comment by anj01** [comment]
Because of using rollup.js I had to include cldr-data jsons to the bundle too... and so it works now

Thanks for your answer!
