### ISSUE TITLE
Question: Sortable dataClickEvent/Template

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#525]
Hi,
could we get a dataClick event for the kendo-sortable? 
Also is it possible to let us set a custom dataTemplate?

Thanks

**Comment by Xizario** [comment]
@simon11196,
You may want to see this example with templates, where it show nested sortable.
http://www.telerik.com/kendo-angular-ui/components/sortable/api/SortableComponent/#toc-data
You could place anything inside the template the same way.

The Sortable does not handle the browser click event, and it is not aware if you click inside the items, nor it should be. It is based on Drag and Touch events. 

If you need to handle click event, attach such to a normal div inside the template.
http://plnkr.co/edit/pDPUv0xdv0oRocYvQeyD?p=preview
