### ISSUE TITLE
Newly added grid row disappears when clicking cancel in edit.

### ISSUE THREAD

**Issue by chrisgwilliams** [telerik/kendo-angular#526]
This occurs in the sample in the docs, regardless of the backend.

Follow this link to the documentation, and open in Dojo.
[http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#events-edit](http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#events-edit)

Repro steps:

1. Add a new row
2. Click edit on new row, then click cancel.
3. Row disappears from grid.

If you do the same on a previously existing row, it does NOT disappear.

**Comment by rkonstantinov** [comment]
Hey @chrisgwilliams, this repository is for issue related to the Kendo UI for Angular product. 

For Kendo UI for jQuery please visit the [Kendo UI Premium Forums at telerik.com](http://www.telerik.com/forums) or submit a ticket in our support system.
