### ISSUE TITLE
Set width/height for dialog through DialogService methods.

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#528]
It is suggested from user, he needs to set dialog width/height using DialogService methods, currently it is not possible.

**Comment by MaklaCof** [comment]
Does anybody knows any work around this limitation until this is possible? 
I would like to set width for dialog _(.k-widget .k-window .k-dialog)_ to 90%.

**Comment by gyoshev** [comment]
@MaklaCof You can set the width of the dialog by specifying it on the `k-window` element. You may want to change the `min-width` to match your scenario:

    styles: [`
      >>> .k-dialog {
        width: 90%;
        min-width: 0;
      }
    `]

Here is [a plunker snippet that shows the approach](http://plnkr.co/edit/j1QFf8cePjw3AIY9oW4Y?p=preview).

**Comment by gyoshev** [comment]
The service API has been released in version `1.1.0` of the dialog package.
