### ISSUE TITLE
Dialog are not centered after update

### ISSUE THREAD

**Issue by MiNiCo88** [telerik/kendo-angular#531]
I've just update dialog module to fix the dialogservice, but now modals are not centered.
How can I fix?
Thank's!!

**Comment by gyoshev** [comment]
Can you reproduce the problem in the [online demos](http://www.telerik.com/kendo-angular-ui/components/dialog/)? If so, in which browser and OS, and which example? If not, please provide a plunker that shows the problem.

**Comment by simon11196** [comment]
Got the same problem. Just check it in your [theme builder](http://themebuilder.telerik.com/kendo-angular-ui)

![image](https://cloud.githubusercontent.com/assets/21359517/25796197/dd466ff4-33d8-11e7-9665-d14311fb9f1d.png)

**Comment by MiNiCo88** [comment]
@gyoshev i've update default theme and now it looks like correctly. Thank you

**Comment by gyoshev** [comment]
@simon11196 This may happen if the theme is updated, but the dialog is not. To resolve this, make sure you are running the latest dialog package. We strive to reduce such dependency problems to a minimum, and this was one of the final changes before the dialog hit 1.0

**Comment by simon11196** [comment]
Thanks for your reply.
I'd like to update the theme but i'm still getting an empty css file from the theme builder... (#529)
