### ISSUE TITLE
DateInput / DatePicker gives current time when entering value with keyboard

### ISSUE THREAD

**Issue by sigVince** [telerik/kendo-angular#532]
It only happens when you start with a null / undefined value bound. 

See plunker:
http://plnkr.co/edit/DXG4kxU1my6ySLkOOftH?p=preview

Behavior is the same for date picker and date input.

Picking a date from the calendar gives a correct time (00:00:00)

**Comment by ggkrustev** [comment]
Indeed, the DateInput will use `now` time instead of midnight (00:00:00) as default. IMO that this is intended behavior. Unfortunately, it causes confusion and we will change it to midnight time to have a consistent behavior with other Date components.

I will post here once the fix is published.

**Comment by siyka-marinova** [comment]
Fix for this issue will be available in version 1.0.2 of kendo-angular-date-inputs package

**Comment by siyka-marinova** [comment]
Fixed in verison 1.0.2 (2017-06-01)
