### ISSUE TITLE
DatePicker inside transformed element renders popup incorrectly

### ISSUE THREAD

**Issue by sv0505** [telerik/kendo-angular#533]
Transform cut pop-up window.

```
        <div style="height: 300px; width: 300px; overflow: hidden; transform: translate(0, -100px);">
          <div style="height: 200px;  background-color: blue;">
          </div>
          <div style="height: 100px;  background-color: gold;">
            <kendo-datepicker></kendo-datepicker>
          </div>
        </div>

```

[OPEN AS PLUNKER](http://plnkr.co/edit/n7J6SU5w9ArCbdTJy4hO?p=preview)

**Comment by gyoshev** [comment]
Thank you for reporting this. We are aware of the problem and are currently working on a solution that resolves it. We track the status in #410, as it is the instance of the same problem.
