### ISSUE TITLE
Grid: Built-in string/number filters debounce

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#536]
Hey kendo team,

Is it possible to implement debounce (RxJS) with the built-in string and number filters, this would be really helpful for lazy loaded tables?

**Comment by rkonstantinov** [comment]
This could be achieve by debouncing the filterChange event: 

```javascript
    public ngAfterViewInit(): void {
      this.grid.filterChange.debounceTime(500).subscribe(filter => {
        this.state.filter = filter;
        this.gridData = process(sampleProducts, this.state);
      });
    }
```
This is demonstrated in [this plunkr](http://plnkr.co/edit/HDnykSMy9kXVVgvPIxnH?p=preview). 

Note that this means that handling the rest of the operations should be split in their individual handlers.

**Comment by moxival** [comment]
Thanks for the fast response but we are mostly extending the DataBindingDirective and i cannot find a way to debounce the rebind() calls, that's why I thought that having a debounce for the filters makes sense.

**Comment by rkonstantinov** [comment]
Actually, you could apply same approach using a custom DataBindingDirective (I guess you are already using such). Similar to the following:
```javascript
import { Directive, OnInit, OnDestroy } from '@angular/core';
import { DataBindingDirective, GridComponent, PageChangeEvent } from '@progress/kendo-angular-grid';
import { ProductsService } from './northwind.service';
import { Subscription } from 'rxjs/Subscription';

@Directive({
    selector: '[productsBinding]'
})
export class ProductsBindingDirective extends DataBindingDirective implements OnInit, OnDestroy {
    private subscriptions: Subscription;

    constructor(private products: ProductsService, grid: GridComponent) {
        super(grid);
    }

    public ngOnInit(): void {
        this.subscriptions = this.products.subscribe((result) => {
            this.grid.data = result;
        });

        // super.ngOnInit();
        
        subscriptions.add(
           this.grid.filterChange.debounceTime(500).subscribe(filter => {
              this.skip = 0;
              this.filter = filter;
              this.rebind();
          })
        );

        subscriptions.add(
          this.grid.pageChange.subscribe(({skip, take }: PageChangeEvent) =>{
              this.skip = skip;
              this.take = take;
              this.rebind();
          })
        );
    
        this.rebind(); 
    }

    public ngOnDestroy(): void {
        if (this.subscriptions) {
            this.subscriptions.unsubscribe();
        }

        super.ngOnDestroy();
    }
    

    public rebind(): void { 
        this.products.query(this.state);
    }
}
```
Regarding exposing a hook for each individual built-in filter component. Although possible, I think that this will complicate the way built-in filters are used in this scenario - it will be required to use filter template approach to hook the Rx code to the filter component. Thus, I'm a bit reluctant about adding this at this time.

**Comment by moxival** [comment]
wow, thanx for the idea and explanation. I will close this.

**Comment by moxival** [comment]
There is a bug (i think) in the grid.component.d.ts. The definition of the filterChange emitter is:
```
filterChange: EventEmitter<{
        filter: CompositeFilterDescriptor;
    }>;
```

But i think it should be:
```
filterChange: EventEmitter<CompositeFilterDescriptor>;
```

**Comment by rkonstantinov** [comment]
Hey @moxival, thanks for the report. Indeed, the type signature is not correct. We will fix it for the next version of the grid package.

**Comment by moxival** [comment]
thanks this appears to be fixed in 1.0.3

**Comment by tsvetomir** [comment]
@rkonstantinov Should we add the `filterChange` and `pageChange` subscriptions to the [Automatic Operations](http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/) sample and enable filtering?

**Comment by rkonstantinov** [comment]
I do not think it is appropriate to add it to the example, as it is not needed in the general case and will add more complexity to the directive's source. However, maybe a side note or something similar in the article will be a good fit.

**Comment by hir06** [comment]
> This could be achieve by debouncing the filterChange event:
> 
> ```js
>     public ngAfterViewInit(): void {
>       this.grid.filterChange.debounceTime(500).subscribe(filter => {
>         this.state.filter = filter;
>         this.gridData = process(sampleProducts, this.state);
>       });
>     }
> ```
> 
> This is demonstrated in [this plunkr](http://plnkr.co/edit/HDnykSMy9kXVVgvPIxnH?p=preview).
> 
> Note that this means that handling the rest of the operations should be split in their individual handlers.

Hi @rkonstantinov I won't be able to debounce it since I am passing some custom params from template with filterChange event so do we have provision of providing debounce with filterchange event?
` protected filterChange(state, options: CompositeFilterDescriptor,cols) {
   // code goes here
  }`

**Comment by tsvetomir** [comment]
Should not be necessary in the latest versions, see https://github.com/telerik/kendo-angular/issues/1036#issuecomment-389786185.
