### ISSUE TITLE
Question: Grid View PDF Export - Server Side Paging

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#537]
Understand that to export all the pages of the grid, requires all records (although off-screen) to be rendered at once.

Managed to do custom implementation for excel export for all pages with server side paging kendo-excelexport. Would like to know is there a way we can do custom implementation for PDF export for all pages with server side paging?

**Comment by danielkaradachki** [comment]
I am not sure if I understand correctly what you mean by "custom implementation". Please clarify. Generally, the Grid PDF export should work the same way no matter if you are using server or client side paging.

**Comment by skyfremen** [comment]
Currently while implementing Grid PDF export it only generates the first page of the grid as we are doing server side paging to retrieve the records only while the user page change.

I also notice that in http://www.telerik.com/kendo-angular-ui/components/grid/pdf-export/
it is stated that **"The export of all Grid pages requires all records (although off-screen) to be rendered at once."**

**Comment by danielkaradachki** [comment]
Have you set the [allPages](http://www.telerik.com/kendo-angular-ui/components/grid/api/PDFComponent/#toc-allpages) option to true? The grid should request and export all pages if the option is set:
http://plnkr.co/edit/6UKICSY4glxL7mQl6ZM7?p=preview

**Comment by skyfremen** [comment]
Thank you for the plunker, I found the issue. Its due to the "Take" changing when pageChange is being fired. However i was still using my own declared take. 
Thanks for the help
