### ISSUE TITLE
DatePicker error when manually entering date in IE11

### ISSUE THREAD

**Issue by DieterDS1983** [telerik/kendo-angular#538]
Hi,

When I manually enter a date in the DatePicker control, the date is changed to NaN/NaN/NaN.
This happens on IE11 as soon as I change the year part of the date.

No problems in Edge/Chrome

Best regards.

**Comment by ggkrustev** [comment]
Indeed, the issue is reproducible using the DatePicker component (the same problem was fixed in DateInput while ago).

I will post a update in this thread once the issue is resolved.

**Comment by siyka-marinova** [comment]
Fix for this issue should be released shortly (currently available @dev).

**Comment by DieterDS1983** [comment]
Thanks for the update.

**Comment by tsvetomir** [comment]
Fixed in v1.0.2 of kendo-angular-date-inputs
