### ISSUE TITLE
datepicker not "working" (scss bug)

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#539]
I've currently installed the following dependencies

    "@angular/animations": "4.0.3",
    "@angular/common": "4.0.3",
    "@angular/compiler": "4.0.3",
    "@angular/core": "4.0.3",
    "@angular/forms": "4.0.3",
    "@angular/http": "4.0.3",
    "@angular/platform-browser": "4.0.3",
    "@angular/platform-browser-dynamic": "4.0.3",
    "@angular/router": "4.0.3",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.25",
    "@progress/kendo-angular-buttons": "0.25.1",
    "@progress/kendo-angular-dateinputs": "1.0.1",
    "@progress/kendo-angular-dialog": "0.21.1",
    "@progress/kendo-angular-dropdowns": "0.39.9",
    "@progress/kendo-angular-inputs": "0.23.5",
    "@progress/kendo-angular-intl": "1.0.0",
    "@progress/kendo-angular-l10n": "1.0.0",
    "@telerik/kendo-theme-default": "1.33.4",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "2.4.1",
    "font-awesome": "4.7.0",
    "rxjs": "5.0.1",
    "zone.js": "0.8.4"

I am using WebPack 2 to build my Project. and I am already using the Autocomplete Dropdown and this is working finde also the normal dropdowns are working.

As you can see the dropdowns look nice but the datepicker is not working. the Styles are not loaded and when I click on the calendar icon, then the "8" is selected for a short moment and then nothing happens.

![grafik](https://cloud.githubusercontent.com/assets/1572878/25850882/5ff530f2-34c4-11e7-9510-d6c96dcd0921.png)

currently I am using the following modules from Kendo Ui

    DialogModule,
    DateInputsModule,
    CalendarModule,
    DatePickerModule,
    DropDownsModule,
    InputsModule

thats my "html snipped

     <kendo-datepicker [(value)]="datum"></kendo-datepicker>

when you need more Informations about my setup then tell me what you need.

**Comment by squadwuschel** [comment]
I've investigated a bit in my problem. And I think its a problem how I "customize" the kendo Ui Styles.

I've a custom Build Process with webpack 2 and I am importing the following in my styles.scss

    $accent: #ff5800;
    $border-radius: 0px;

    @import "~@telerik/kendo-theme-default/styles/packages/all.scss";
    @import "sxpNavigation.scss";

and that is working fine so far.

**Comment by squadwuschel** [comment]
I've found my Problem: 

    "@telerik/kendo-theme-default": "1.33.4",

I was using the "old Styles" with "@telerik" but I need to implement the "@progress"

    "@progress/kendo-theme-default": "2.33.1",

**Comment by kambbado** [comment]
I'm having an issue where the calendar is not displaying.  I verify the theme and I'm using

> @import '~@progress/kendo-theme-default/scss/all';

This was working a few version back.  The kendo-popup is inserted into the DOM but do activated.

I'm also getting this error

> ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.

Any ideas?

Thank you
