### ISSUE TITLE
Problem with Dialog and Reactive Forms on Saving ( custom action templateref )

### ISSUE THREAD

**Issue by MiNiCo88** [telerik/kendo-angular#540]
Hello,
in my web application i'm using dialog service to open dialogs and perform CRUD operations.
The content of the dialog for every operation has own component, and every dialog has also its template for custom actions.
I'm having problem to get value from FormGroup that's in content component while save button is in the app component ( list component )

**Comment by rusev** [comment]
We need a runnable example demonstrating the scenario in order to assist you further.
