### ISSUE TITLE
kendo-theme-bootstrap not working

### ISSUE THREAD

**Issue by sebasfiorent** [telerik/kendo-angular#541]
Using lastest release of Kendo Angular,

Then:
- npm install --save @progress/kendo-theme-bootstrap
- npm install --save bootstrap@git://github.com/twbs/bootstrap.git#95f37e4c402df37db16781995ffa1592032df9c8

On styles.scss

add:

@import "../node_modules/@progress/kendo-theme-bootstrap/scss/all";

That gives me the error:

 File to import not found or unreadable: ~@progress/kendo-theme-default/scss/variables.

**Comment by SeriousLemon** [comment]
If you're using angular-cli, it seems to be related to this: [https://github.com/angular/angular-cli/issues/6242](https://github.com/angular/angular-cli/issues/6242)

**Comment by HolgerPersch** [comment]
This works for me:

`@import "~@progress/kendo-theme-bootstrap/dist/all.css";`

**Comment by squadwuschel** [comment]
the "all" only works if the webpack

     extensions: ['.ts', '.js', '.json', '.css', '.scss', '.less']

extensions array contains the extension you can find in the directory if not included then its not working.

**Comment by codehippie1** [comment]
Why is this issue closed? How to make it work with Sass?

**Comment by tsvetomir** [comment]
The initially discussed issue was resolved. Please open a support ticket if you need assistance with setting up your project.

**Comment by shamilovtim** [comment]
this theme is still busted

**Comment by tsvetomir** [comment]
@shamilovtim please, open an issue with more details about the issues you're experiencing.

**Comment by shamilovtim** [comment]
I apologize, it was the import order. It really needs to be specified on the docs. I posted a common on the relevant ticket (which was closed in the past).
