### ISSUE TITLE
kendo-panelbar: iconClass not working when binding to an array of PanelBarItemModel objects

### ISSUE THREAD

**Issue by JoeDiaz** [telerik/kendo-angular#542]
Binding to an array of PanelBarItemModel objects that has the iconClass property is not creating the icon element.  This works if I create a kendo-panelbar-item html element and set iconClass. 

See _app/app.component.ts_ in the folowing plunker:
http://plnkr.co/edit/eO9bsfyBPvHbHpIvXEdo?p=preview

**Comment by Raisolution** [comment]
Hi @JoeDiaz,

Thank you for reporting this. A fix is on the way.

**Comment by siyka-marinova** [comment]
Fixed in v.1.0.1
