### ISSUE TITLE
Select a row from code behind in Kendo-Grid

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#544]
We would like to select a row from our component typescript code of a kendo-grid. Currently it seems to us this is not possible or we don't know the right approach to do this.

Is this feature currently not available and if so is a solution for this planned? Are there any workarounds to reach this behavior?

Thanks a lot in advance for your feedback.

**Comment by Raisolution** [comment]
Hi @rdnscr ,

The selection feature is currently in process of development. We will have this suggestion in mind.

At the moment, the only workaround would be to trigger the click event of the row to be selected.

**Comment by rdnscr** [comment]
@Raisolution how can we trigger such a click event from the code?

**Comment by deeppriy** [comment]
Hi @Raisolution,
How we can trigger click event for specific row in grid?

**Comment by tsvetomir** [comment]
Merging this issue into #634
