### ISSUE TITLE
DropDown: Cannot access 'dataItem.text' in ValueTemplate with primitive value

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular#546]
When I am using the dropdown with primitive values from object fields (as shown in the plunker provided [there](http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/value-binding/#toc-primitive-values-from-object-fields)) the `textField` is shown as the value of the selected item.

However when I am using a `kendoDropDownListValueTemplate` I can only access the `valueField` via `let-dataItem` and not the object itself ([Plunker](http://plnkr.co/edit/3tN8L1tAj3GhCqCR8dAk?p=preview)).

Is this intended behavior?

**Version:** 
@progress/kendo-angular-dropdowns: 1.0.1

**Comment by valchev** [comment]
Hi @P-H-F and thank you for bringing this to our attention.

The problem occurs only if the `valuePrimitive` is set to `true` like in your example. We will provide a fix for this.
