### ISSUE TITLE
MultiSelect doesn't work inside Popup

### ISSUE THREAD

**Issue by chronicbint** [telerik/kendo-angular#547]
Using a component inside a Kendo popup, with the component loading a Kendo Multi select I get nothing but the select box.

If I use a template instead with an identical multi select it works correctly.

Should this work? Is there additional setup/config required?

Plunker
http://plnkr.co/edit/PXfSrusCUOebGabhLa5X?p=info

**Comment by rusev** [comment]
Thank you for reporting the issue. We will update this thread once we address the issue.

**Comment by tsvetomir** [comment]
This bug should be fixed in v1.0.10 of kendo-angular-dropdowns
