### ISSUE TITLE
Public API to control scroll position

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#548]
As suggested from user. We need to control scroll position via code.

**Comment by jiangyh1024** [comment]
hi, has this functionality done?

**Comment by siyka-marinova** [comment]
@jiangyh1024 This functionality is now available with the [scrollTo](https://www.telerik.com/kendo-angular-ui-develop/components/grid/api/GridComponent/#toc-scrollto) method in `@progress/kendo-angular-grid v.4.5.0`.
