### ISSUE TITLE
Grid - CommandColumnComponent not showing title

### ISSUE THREAD

**Issue by dassjosh** [telerik/kendo-angular#549]
When setting the title on the kendo-grid-command-column the given title is not displayed.

This can be seen in the example provided on:
[http://www.telerik.com/kendo-angular-ui/components/grid/api/CommandColumnComponent/](url)

**Comment by rusev** [comment]
Thanks for reporting it. We will update this thread once it is addressed.

**Comment by rusev** [comment]
Latest Grid package `v1.0.4` contains a fix for this. Thank you once again for reporting it!
