### ISSUE TITLE
Item index in dragEnd is -1 if item is not dropped immediately

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#550]
It can be reproduced [here](http://www.telerik.com/kendo-angular-ui/components/sortable/#toc-events) drag and drop very quickly some item the event log is correct , but if you hold a bit, then 'undefined' appears in the log for dragEnd event.index.

**Comment by ipeshev** [comment]
Fix available in [latest development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tapopov** [comment]
Shipped in `kendo-angular-sortable` v2.0.0
