### ISSUE TITLE
Grid - Performance issue in an Angular CLI application

### ISSUE THREAD

**Issue by rsharmapinnakl** [telerik/kendo-angular#551]
I have been upgrading my application from AngularJS to Angular(v4). I created my Angular application using the Angular CLI. I noticed that the Grid becomes very slow(on scrollling, sorting etc.) when there are a significant number of rows(>100). This was never a problem with kendo UI for AngularJS.

Also, when I tested this on a Kendo plunker, the grid performed well, though not as good as the grid for AngularJS or jQuery.

Here's a minimal Angular CLI project using the kendo grid for around 500 rows- https://github.com/rsharmapinnakl/angular-kendo-grid-example

Here's the same code on a plunker - http://plnkr.co/edit/zhegT2?p=preview

I don't understand why these two perform differently. The grid in the Angular CLI project does not provide an acceptable user experience. Is there a way to fix this?

**Comment by rkonstantinov** [comment]
You should make sure that the app is running in production mode by starting it with `ng serve --prod`

**Comment by tsvetomir** [comment]
For Angular CLI projects append the `--env=prod` flag, e.g. `ng build --env=prod`

Closing this issue, but feel free to reopen if you identify any specific performance problems.
