### ISSUE TITLE
Question: kendoGridDetailTemplateShowIf behavior

### ISSUE THREAD

**Issue by ulgen** [telerik/kendo-angular#554]
I am trying to let users expand only specific rows of the grid. Is there any way to display the + symbol for some rows only? Setting `kendoGridDetailTemplateShowIf` to a function that evaluates to false removes the row completely. Is that the intended behavior? If so, how can I achieve what I need?

**Comment by ulgen** [comment]
I found the answer to my question at http://stackoverflow.com/questions/41492005/how-to-show-and-hide-detail-row-in-kendo-grid-with-angular-2. 

The documentation was not clear enough for me. Thanks!

**Comment by tsvetomir** [comment]
Flagging this for some additional documentation. We need an example with _kendoGridDetailTemplateShowIf_ in both [the API reference](http://www.telerik.com/kendo-angular-ui/components/grid/api/DetailTemplateDirective/) and the [Detail Row Template article](http://www.telerik.com/kendo-angular-ui/components/grid/detail-template/)

**Comment by rusev** [comment]
Docs is updated with a runnable example for the feature.
