### ISSUE TITLE
dropdownlist Reset selectedItem to defaultItem not working

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#555]
I've created a dropdownlist with a default Value and when I try to reset the dropdownlist with the default Value with an extra button. Then the ngModel Value is set, but the dropdownlist don't shows the "defaultItem" as selected Value

![grafik](https://cloud.githubusercontent.com/assets/1572878/26014408/b5e32f92-375c-11e7-8154-0614e123ec2d.png)

then i click the reset Button

![grafik](https://cloud.githubusercontent.com/assets/1572878/26014424/c4aa7a3a-375c-11e7-8d5b-91a8ce3884c9.png)

and you see the model looks good but not the Viewed Item.

Example Plunkr

http://plnkr.co/edit/a1bOz208yxttj2AfUDPJ?p=preview

**Comment by rusev** [comment]
This is intended behavior. The default data item is actually not part of the data items, it is an extra item.
It will be selected only when the value of the component is not set. That said if you set the value to `null` default data item will be selected.

Here is the updated example - http://plnkr.co/edit/76hFIiQzUzqBqhz73EJV?p=preview

**Comment by squadwuschel** [comment]
works fine : -)

**Comment by MisiM** [comment]
In the template, add this attribute into your kendo ddl component elemnent : #itemsDdl.
Add this property in the class @ViewChild('itemsDdl') itemsDdl;
and in your reset() function just add : this.itemsDdl.reset() and Voila!
