### ISSUE TITLE
Error in compiling angular style

### ISSUE THREAD

**Issue by wongCH** [telerik/kendo-angular#557]
after adding 
**@import "~@progress/kendo-theme-default/scss/all";** into my global style, i got error during compile time with below error message. if i remove the @import of kendo theme, my project works.
please advise...

ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./
~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/assets/styles/app
.scss
Module build failed:
$selected-hover-bg: mix( $selected-bg, black, 92) !default;
                   ^
      Argument `$color-1` of `mix($color-1, $color-2, $weight: 50%)` must be a color

Backtrace:
        node_modules/@progress/kendo-theme-default/scss/_variables.scss:153, in function `mix`
        node_modules/@progress/kendo-theme-default/scss/_variables.scss:153
      in /Users/testProjects/ng/node_modules/@progress/kendo-theme-default/scss/_variables.scss (line 153, column 21)
 @ ./src/assets/styles/app.scss 4:14-204
 @ multi ./~/quill/dist/quill.snow.css ./~/dragula/dist/dragula.css ./~/leaflet/dist/leaflet.css ./~/an
gular-calendar/scss/angular-calendar.scss ./~/@swimlane/ngx-datatable/release/index.css ./~/@swimlane/n
gx-datatable/release/themes/material.css ./src/assets/fonts/pe/css/pe-icon-set-weather.css ./src/assets
/fonts/data-table/icons.css ./src/assets/styles/app.scss
webpack: Failed to compile.

**Comment by gyoshev** [comment]
Quite unusual -- the line `@import "~/scss/all";` does not match the instructions for referencing a theme -- and themes are usually located in the `node_modules/@progress/kendo-theme-*` directories. Can you please provide a sample project that shows the problem?

**Comment by gyoshev** [comment]
Closing this due to a lack of reply. In case the problem persists, please post more details on how it occurs.
