### ISSUE TITLE
Keyboard selection: select row(s) with Arrow Up/Down keys

### ISSUE THREAD

**Issue by ngfx** [telerik/kendo-angular#558]
Hi team,

Have you planned to add keyboard selection support. It is very desired in our project.

Expected result: 

- When a row is selected, then when navigate with arrow up/down keys, the selection should change to previous/next row. 

- In multiselection mode (in the future perhaps), the selection should be all rows that are gone through with arrow keys.

Thanks.

**Comment by rusev** [comment]
You can keep track on navigation+selection features progress in [this issue](https://github.com/telerik/kendo-angular/issues/213).

**Comment by tsvetomir** [comment]
The multiple-selection behavior doesn't sound right to me. What if you want to select non-consecutive rows with the keyboard?

What do you think about having a modifier to the select action, say Ctrl? You'd be able to set it to None to achieve the behavior described above.

**Comment by ngfx** [comment]
Yeah, I agree for multi-selection, it will be cool if we can have modifier like Ctrl (for non-consecutive rows) and Shift (for consecutive rows).

**Comment by tsvetomir** [comment]
Merging this issue into #634
