### ISSUE TITLE
Dateinput toggle button at wrong position with explicit width

### ISSUE THREAD

**Issue by JBildstein** [telerik/kendo-angular#560]
When setting the width of a dateinput big enough the toggle button does not stay on the right side. 
In my app it only happens on Edge/IE but in the Plunker it also happens in Chrome and Firefox (did not try other browsers).

Plunker adapted from the example in the documentation:
http://plnkr.co/edit/yVRCtFQsjfNeN1eSaGA7?p=preview

**Comment by ggkrustev** [comment]
The component wasn't resized correctly due to a incorrect configuration. The component breaks before it is fully initialized. If the `value` property binding is defined correctly, the component is sized properly:

http://plnkr.co/edit/ExDjzvtpfZXysl8W67OR?p=preview

**Comment by JBildstein** [comment]
oh that's a stupid mistake and it would explain why it didn't work in any browser. thank you for pointing that out!
In my app I'm using reactive forms though and it seems to be initialized correctly.
I did some more tests and it looks like it only happens in debug with the jit compiler and only in IE and Edge. In prod with aot it works just fine on all browsers.
Here's a screenshot of both versions in IE11:

Debug:
![debug_jit](https://cloud.githubusercontent.com/assets/12777835/26129077/1cc5d374-3a8f-11e7-877d-d1c8ada997db.png)
Production:
![prod_aot](https://cloud.githubusercontent.com/assets/12777835/26129078/1f0c2304-3a8f-11e7-88d4-f35c3d179252.PNG)

I know it's not a lot to go on, if you need some additional info let me know.
Since it works fine in production it's not urgent at all, so no pressure.

**Comment by ggkrustev** [comment]
Does the modified demo works in IE or Edge? It seems to work just fine on our end (tested in IE). I'm asking, because the plunkr actually uses JIT and it is in a debug mode and if it works, probably the issue is somewhere else.

Could you send us a repro demo? It will be really hard to replicate the problem locally with the given information.

**Comment by ggkrustev** [comment]
Hey @JBildstein, I will close the thread for now. 

Please feel free to share more details when possible  in order to reopen the issue and continue with the investigation.

**Comment by JBildstein** [comment]
it's ok. I just tried to reproduce the page as close as possible in Plunker but I was not able to get that behavior.
I'm afraid I'm not able to give you the actual app so it looks like it will remain a mystery for now.
your modified example worked just fine btw.
