### ISSUE TITLE
Currency/Number display in NumericTextbox

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#562]
We want to use the NumericTextBox for displaying currencies and numbers. However we are facing two issues which are preventing us from using the control:
- The control always uses the "," character for a step of thousand (1,000,000). However in our region (CH) the separation character should be a " ' " (1'000'000).
- The control always displays the currency code upfront (CHF 100) but we want it at the end what is usual in our region (100 CHF)

Can this somehow be reached with the current control? If now what workaround would you suggest if there are any or do we need to build a control on our own?

**Comment by danielkaradachki** [comment]
The corresponding group separator should be used if you load and set the locale:
http://www.telerik.com/kendo-angular-ui/components/internationalization/

According to the standard currency format("¤ #,##0.00;¤-#,##0.00") from the cldr data which is used for the formatting, the currency symbol should be placed before the number for the de-CH locale. The currency accounting format places the symbol after the number but we do not currently support it. We will consider adding option for using the accounting format. For now I can suggest to use a custom format which places the symbol as needed:
http://plnkr.co/edit/LGWWLUPezQct2HaxWuxZ?p=preview

**Comment by danielkaradachki** [comment]
We implemented support for the accounting format in the latest version:

http://plnkr.co/edit/JrLfydkPMCHMv7gCeqMX?p=preview
