### ISSUE TITLE
NumericTextBox does not allow empty field if autocorrect with min and max is set

### ISSUE THREAD

**Issue by AisDevelopment** [telerik/kendo-angular#563]
We are using NumericTextBox to display weights in percent. For that we need to set minimum and maximum values (min=0, max=100) and autocorrect=true, so that the user really cannot set a different value outside that range. 

However, we would like to allow the user to empty the field again, so that there is nothing/null in NumericTextBox. With the given setup, the user can empty the field, but the value is set to 0 instead to nothing. We would like the field to be nullable even if autocorrect, min and max are set. One possiblity would be to add a new flag to the attributes of NumericTextBox which could handle that.

**Comment by danielkaradachki** [comment]
The numerictexbox should allow empty value with auto correction. Could you check [this](http://plnkr.co/edit/jlHMhIo37hXNLJPsPCWo?p=preview) example and let me know if it works as expected. The value is set to null when clearing the input value at least on my side.

**Comment by AisDevelopment** [comment]
Thank you for your reply. I realized the problem is, that we do calculations with the value.
`<kendo-numerictextbox`
           ` [value]="value * 100"`
            `(valueChange)="value = ($event / 100).toFixed(6)"`
           ` [min]="0" [max]="100"`
           ` [autoCorrect]="true">`
        `</kendo-numerictextbox>`
The division with 100 results in always setting the value to 0, instead of leaving it empty. We will think about a solution for that on our side.
