### ISSUE TITLE
ClearButton does not reset combobox options list

### ISSUE THREAD

**Issue by Dashiing** [telerik/kendo-angular#564]
Steps to reproduce:

1. Open [plunker](http://plnkr.co/edit/dXSPm7fQn611jZ7fekrq?p=preview)
2. Insert "s"
3. After the insert do not lose focus and click clear (x)
4. Clicking the dropdown button will only display the filtered option (Small) and not all the other options.

Is this expected?

**Comment by tapopov** [comment]
@Dashiing 

This should be fixed in the latest version. One can also subscribe to the component's [open event](http://www.telerik.com/kendo-angular-ui/components/dropdowns/api/ComboBoxComponent/#toc-open) and filter the data when it is triggered.

**Comment by Dashiing** [comment]
I'll use open event then, thanks @tapopov.
