### ISSUE TITLE
Grid, export to Excel error

### ISSUE THREAD

**Issue by evgenf** [telerik/kendo-angular#565]
I got the following error while trying to add button with _kendoGridExcelCommand_ directive:
- Error: Uncaught (in promise): Error: No provider for ExcelService!

Button was NOT in _kendoGridToolbarTemplate_. I tried to move button in  _kendoGridToolbarTemplate_ and it worked!

How can I use _kendoGridExcelCommand_ outside _kendoGridToolbarTemplate_?

angular: 4.1.2
kendo-angular-grid: 1.0.5
kendo-angular-excel-export: 1.0.1

**Comment by tsvetomir** [comment]
The _kendoGridExcelCommand_ directive can only be used within the Grid. To trigger the export externally, use the saveAsExcel method. See [Triggering Export Externally](http://www.telerik.com/kendo-angular-ui/components/grid/excel-export/#toc-triggering-export-externally).
