### ISSUE TITLE
Chart, rendered in a ScrollView, causes constant refreshing of the first and last <LI> elements

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#566]
When a Chart is rendered in the ScrollView, and the first or last item is selected, the respective LI element is constantly refreshed:

[http://plnkr.co/edit/Lcpu8QI1T5Xesqx783Lc?p=preview](http://plnkr.co/edit/Lcpu8QI1T5Xesqx783Lc?p=preview)

This causes serious performance issues in Chrome and a crash in IE.

**Comment by tsvetomir** [comment]
Fixed in v1.0.1 of the kendo-angular-scrollview package.
