### ISSUE TITLE
Grid: orderBy and process from kendo-data-query sometimes return wrong order

### ISSUE THREAD

**Issue by paoluptecoi** [telerik/kendo-angular#568]
orderBy and process from kendo-data-query return the wrong order using Google Chrome Version 58.0.3029.110 (64-bit) (not IE, not FF) when no sorting is selected.

Steps to reproduce:

- Open Chrome (NOT IE, NOT FF)
- Open http://www.telerik.com/kendo-angular-ui/components/grid/sorting/
- Select "OPEN TO PLUNKER"
- Have a look at the order of the IDs in the list: 39, 1, 3, 4, ... 37, 38, 2, 40, 41,... instead of 1, 2, 3,...
- Sort by ID column: Everything is fine!
- click into 2 ID column again and again to switch off sorting: Problem is there again.

Problem occurs in other project with other data, too.

**Comment by paoluptecoi** [comment]
![order](https://cloud.githubusercontent.com/assets/1819223/26200810/44e79724-3bd0-11e7-97c1-6d5c47064486.PNG)

**Comment by rkonstantinov** [comment]
@paoluptecoi, thanks for the report. 
The behavior in question is related to Chrome's unstable sort (try running `[1,2,3,4,5,6,7,8,9,10,11].sort((a,b) => 0)` in the console and see the result).

Anyway, we have addressed the issue in question and the fix will be included in the next (1.0.1) version of the `kendo-data-query` package.

**Comment by paoluptecoi** [comment]
Thank you for the quick response! It behaves in Chrome's console like you said.

**Comment by paoluptecoi** [comment]
Works fine now, with version 1.0.6. Thank You!
