### ISSUE TITLE
Best Practise for Multiselect Dropdown prevent close on Select

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#573]
the example on your page 

http://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/open-state/

only shows how to prevent the close event, in the second example I can't close the multiselect anymore.

In the old jQuery/ angular 1 Version there was just a property I could set to prevent the dropdown for closing and when I click somewhere else in my app the dropdown closes - that would be a cool implementation. But when I have to implement this with these events myself would be not so nice.

**Comment by tapopov** [comment]
Thanks for the input @squadwuschel, 
We will update the example shortly and consider adding an option that forces the popup to stay open.

**Comment by tapopov** [comment]
Hi @squadwuschel,

We've updated the [Preventing Opening and Closing](http://kendobuild/kendo-angular-ui/components/dropdowns/multiselect/open-state/#toc-preventing-opening-and-closing) examples. Adding this as a built-in feature however is still on our to-do list.

**Comment by squadwuschel** [comment]
@tapopov yes that works great now - but like you said a build-in feature is needed if you have many of this multiselect lists on a page :-)
