### ISSUE TITLE
PDF page template is applied on last page only

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#575]
Can be seen in the [Specifying Page Template](http://www.telerik.com/kendo-angular-ui/components/grid/pdf-export/#toc-specifying-page-template) demo.

**Comment by mast3rd3mon** [comment]
I'm also having this issue, is there any progress or workaround?

**Comment by tsvetomir** [comment]
The problem should be fixed in **v1.1.2** of `@progress/kendo-angular-grid@`

**Comment by mast3rd3mon** [comment]
Thanks, that does indeed work.
