### ISSUE TITLE
Aggregates on column footer with custom remote directives for data binding

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#577]
I followed your example for aggregates on groups and it works like a charm : http://www.telerik.com/kendo-angular-ui/components/grid/grouping/grouping/. I use a custom remote directives for fetching the datas, and so your variable `let-aggregates` help me a lot to show the value I needed, only with Angular HTML templating.

```HTML
<ng-template kendoGridGroupFooterTemplate
                   let-aggregates>

    <div *ngIf="column.Sum">{{aggregates[columnName].sum}}</div>
    <div *ngIf="column.Count">{{aggregates[columnName].count}}</div>
    <div *ngIf="column.Average">{{aggregates[columnName].average}}</div>
    <div *ngIf="column.Min">{{aggregates[columnName].min}}</div>
    <div *ngIf="column.Max">{{aggregates[columnName].max}}</div>
</ng-template>
```
Like your example, I need to redefine the column footer to show the total unit price, but with the custom remove directive I don't have all my aggregates stored into the component. I think Something is missing (maybe into the `GridDataResult`, like a property `aggregates` ?) to provide aggregates accross all columns. Or maybe you have any other solution for that ?

**Comment by rkonstantinov** [comment]
Indeed, footer aggregates using a custom remote directives is a bit trickier, as the aggregated result should be in the scope of the grid's host component. However, this is still possible by adding two input field to the directive - one for the aggregate descriptors and one for the aggregated result. The second one will be used by the directive to assign the result after the computation.

[Here](http://plnkr.co/edit/nCNjsliDoKV65N9RQWws?p=preview) you can find a plunkr which demonstrates this approach in action.

**Comment by ChrisProlls** [comment]
Ok I see, thanks ! I managed this with an event on the directive, it works too !

```HTML
<kendo-grid sfkGridBinding
            (aggregatesChanged)="aggregatesChanged($event)"
            [...]">
</kendo-grid>
```

And this is the definition of my directive :

```TS
export class GridBindingDirective extends DataBindingDirective implements OnInit, OnDestroy {
  @Output() aggregatesChanged: EventEmitter<any> = new EventEmitter<any>();

   ngOnInit(): void {
    this.serviceSubscription = this.gridService.subscribe((result: any) => {
      this.aggregatesChanged.emit(result.aggregates);

      this.grid.data = result;
      this.grid.onDataChange();
    });

    super.ngOnInit();

    this.rebind();
  }
}
```

Thanks for your reply.
