### ISSUE TITLE
DateInput unexpected behavior when date is entered and then month portion is selected via mouse

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#579]
The bug can be reproduced using the online demo:

[http://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/](http://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/)

Steps to reproduce:

1) Enter a date, e.g. 11/11/2011.
2) Selecting the month input (first 2 digits) by mouse
3) Keyboard input: 1

Expected result: 1 is inserted into the month field
Actual result: selection jumps directly to the next field (day), but the month fields is still showing 11

**Comment by ggkrustev** [comment]
Unfortunately, the behavior is caused due to a limitation in our string comparison logic.

**Comment by tsvetomir** [comment]
Closing as we're unable to provide a fix.
