### ISSUE TITLE
Kendo UI Dropdownlist is not closed on IE when clicking elsewhere on page

### ISSUE THREAD

**Issue by ldtung** [telerik/kendo-angular#580]
Hello 

I have an issue with Kendo UI Dropdown list on IE11. As I can reproduce on the Plunker http://plnkr.co/edit/?p=preview and also in demo page http://www.telerik.com/kendo-angular-ui/components/dropdowns/. When I click somewhere else on page, the dropdownlist is not closed. 

This is working for ComboBox component but not DropDownList.

Thanks for your help
Tung

**Comment by valchev** [comment]
Duplicates #502
