### ISSUE TITLE
Grid Excel Export - allPages missing

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#581]
I want to use the `kendo-grid-excel` component to export my grid to an Excel file. I've seen that the PDF export has a parameter `allPages` to export all pages of the grid, but not the `kendo-grid-excel` component. Is it a missing parameter ? Any workaround for that ? 
Thanks !

**Comment by danielkaradachki** [comment]
You can use the approach demonstrated in [this](http://www.telerik.com/kendo-angular-ui/components/grid/excel-export/#toc-exporting-specific-data) example to export any data you need. To export all pages just return the data for all pages as result.

**Comment by CayetanoHerreraLuisRicardo** [comment]
@danielkaradachki  it works to export all data, but if  i apply filters to the kendo-grid, still exporting all dat. 
I want export the excel from the filter applied to the kendo-grid, any solution? thanks!

**Comment by danielkaradachki** [comment]
In this case you should return the filtered data from the function:
https://plnkr.co/edit/vOtfVfowdHXsfttMiY5w?p=preview

Please note that this issue tracker is for bug reports only. If you have questions regarding implementation scenarios or configuration please open a support ticket.
