### ISSUE TITLE
kendo grid toolbar template issue with material button

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular#582]
Hi, 

when using material button inside grid toolbar template, the whole grid become button.  
Refer to the link below :
http://plnkr.co/edit/wwKumQkKsYreZCblmCed?p=preview

**Comment by rkonstantinov** [comment]
Thanks for the report. The described behavior seems related to the excel command directive. We will fix it for the next version of the grid-package.

**Comment by skyfremen** [comment]
Just to note that it is also applicable to PDF.
http://plnkr.co/edit/MhKKGdY21afbSMo8xhsY?p=preview
