### ISSUE TITLE
DatePicker based on the format

### ISSUE THREAD

**Issue by nm-a** [telerik/kendo-angular#584]
I am trying to use DatePicker with mmm-yyyy (only Month & Year) format. When I open the Picker it showing the dates as well. If we can allow to disable Date / Month based on the format that might be helpful.

thank you

**Comment by ggkrustev** [comment]
@nm-a, could you elaborate a bit more? Do you need to dynamically disable the input or the calendar popup based on the format? Wouldn't it be sufficient to control the `open` event based on the format, keeping the popup closed if the format is not applicable?

**Comment by nm-a** [comment]
Hi @ggkrustev , I feel we need to have calendar popup, need to display calendar popup based on the Date Format.
For ex:
dd-MMM-yyyy = calendar popup will have Date, Month & Year
MMM-yyyy = calendar popup will have Month & Year
yyyy = calendar popup will have Year

thank you

**Comment by ggkrustev** [comment]
Hi @nm-a, thanks a lot for the clarification, as it sheds more light on the required functionality.
The Calendar component supports a single 'month' view now, which will fulfill your request for 'dd-MMM-yyyy' date. For the other formats, we will need different calendar views which we don't have right now. They are under consideration and it will be great if you can cast your vote for them here:

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18990187-calendar-picker-component-fast-navigation

**Comment by ggkrustev** [comment]
Will close the thread as the issue is a missing feature that has already a UserVoice discussion.
