### ISSUE TITLE
[IE11, Edge] Cursor jumps to the beginning of the filter input when DropDownList is closed and opened again

### ISSUE THREAD

**Issue by dzmitrykarnitski** [telerik/kendo-angular#585]
Hi,

I found an issue with a DropDownList component when filtering enabled. 

Steps to reproduce:
1) Type some text to the filter input;
2) Click on the dropdown once to close dropdown's popup;
3) Click on the dropdown again to open dropdown's popup;
4) Observe the cursor's position in the filter input.

ER: The cursor is located after the entered text.
AR: The cursor is located at the very beginning of the entered text.

The issue is reproducible in **IE11** and **Edge** browsers.
Reproduced on the demo page:
http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/

Could you please take a look at it?
Thanks!

**Comment by valchev** [comment]
Hi @dzmitrykarnitski,

Thank you for reporting this. The issue should be fixed in a short period of time.

**Comment by siyka-marinova** [comment]
Fix for this issue should be released shortly (currently available @dev).

**Comment by siyka-marinova** [comment]
Fixed in kendo-angular-dropdowns v.1.0.10.
