### ISSUE TITLE
Pie chart labels are not fully shown or overlap chart legend

### ISSUE THREAD

**Issue by dzmitrykarnitski** [telerik/kendo-angular#587]
Hi, 

I have an issue when pie chart's labels overlap a chart's legend or not even displayed when chart component width is limited.
Plunkr: http://plnkr.co/edit/6eqQ0993MNxRWse9Elm3?p=preview

As you can see one of the labels is not fully shown and another one overlaps a legend.
Are there any workarounds for the issue? I mean, can we control the position at which graph's labels should be rendered? 
On my opinion graph labels should be rendered at a free space near the graph (e.g. on a free space above or below the legend)
Is it possible to fix that?

Thanks!

**Comment by danielkaradachki** [comment]
Currently there isn't a built-in option to automatically fit the labels. I can suggest either to increase the chart size or adjust series [labels](http://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesLabels/) and [padding](http://www.telerik.com/kendo-angular-ui/components/charts/api/Series/#toc-padding) options to fit in the available space:

http://plnkr.co/edit/3uCwhJxMF4gPzroMCEQF?p=preview
