### ISSUE TITLE
Selection is not properly visualized in DatePicker

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-angular#588]
It seems the visualization of the selected date portion depends on the previously selected date:
https://www.screencast.com/t/Xmqzeq4c2EW

Steps to reproduce:
1. Navigate to [Controlling Focused Calendar Dates demo](http://kendobuild-staging.openstack.progress.com/kendo-angular-ui-develop/components/dateinputs/datepicker/#toc-controlling-focused-calendar-dates) and run code
2. Select some date in September (9-th month) - the result is selection of 5 symbols, equal to the initial value ('month') lenght
3. Select some date in Octomber (10-th month) - selection is one digit, as September is the 9-th month

**Comment by Xizario** [comment]
It is still an issue if the format starts with literal.
http://plnkr.co/edit/xFdKctjkOufYeGED7kC3?p=preview

My suggestion is to change:
`this.selectDateSegment(this.currentFormat[start]);`
to
`this.selectNearestSegment(start)`

**Comment by ggkrustev** [comment]
Good catch! Will push the suggested fix right away.
