### ISSUE TITLE
Grid Grouping with virtual Scrolling

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#591]
In the current kendo grid is an issue if you would like to use grouping and virtual scrolling together. In general everything works perfect until you start to collaps a group. In this case the virtual scrolling (paging) is not triggered and therefore you just see an empty space in your grid. My assumption is, that the items within the grid which are displayed are not calculated correctly in a way that hidden items in a group somehow still are accounted as displayed.

You can see the behavior with the following plunkr:
http://plnkr.co/edit/CTyUzjzJJoxOs4wy4B6t?p=preview

just collapse the top group in the example and you will see the issue.

**Comment by rkonstantinov** [comment]
I'm afraid that currently having both grouping and virtualization enabled is not supported. We will add support for such scenario in future version of the component.

**Comment by rkonstantinov** [comment]
Having both grouping and virtualization is possible (with some limitations) using the 1.4.0 version of the package. Please check the following help topic for more details.
http://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/#toc-using-virtualization-with-grouping
