### ISSUE TITLE
Offline docs

### ISSUE THREAD

**Issue by darianferrer** [telerik/kendo-angular#593]
Hi, is there a document repository for kendo ui for angular that allows me to clone and generate the doc site? I do this for kendo ui for jquery, because sometimes I'm working offline.

**Comment by tsvetomir** [comment]
We don't have a solution for offline docs access at the moment.

That said, we'll enable access to the package sources soon. It's not the same as the live site, but all the important information is there in markdown format.

**Comment by tsvetomir** [comment]
The [source code repos](http://www.telerik.com/kendo-angular-ui/components/installation/source-code/) contain a `docs` folder with the articles in markdown format.
There's an unofficial `gulp docs` task that can serve you the content in a simplified site.
