### ISSUE TITLE
Switch - form contains old value in valueChange

### ISSUE THREAD

**Issue by dassjosh** [telerik/kendo-angular#594]
When the valueChange event is called and we pull the current value from the form for the switch we are getting the old value. This was not an issue in version 1.0.1 as it returned the new value.

Current Result: 
the form and the valueChange contain opposite values

Expected Result:
The values from the form and the value change should be the same

Issue is viewable at this plunker: [http://plnkr.co/edit/72TQpE7Ns2tEEZ4XdmLk](url)

**Comment by ggkrustev** [comment]
Hi @dassjosh,
The component's `valueChange` event is triggered before the form control change, as it seemed right at the time. In the context of the reactive forms though, it seems impractical. 

After an offline discussion with the dev team, we decided to change this behavior for all input components and to start triggering our change event after the form control's one.

I will update the thread once the change is published.

**Comment by tsvetomir** [comment]
Fixed in `@progress/kendo-angular-inputs@1.1.0`
