### ISSUE TITLE
DateInputs module fails to install

### ISSUE THREAD

**Issue by KenS-MvcDev** [telerik/kendo-angular#597]
Attempting to install the @progress/kendo-angular-dateinputs module to Angular-CLI Tutorial application fails with an Unexpected Token Error.

[2017-05-31T05_38_27_529Z-debug.log.txt](https://github.com/telerik/kendo-angular/files/1040381/2017-05-31T05_38_27_529Z-debug.log.txt)

**Comment by moxival** [comment]
Same here.

**Comment by ggkrustev** [comment]
We've got a temporary network issues with our private packages. We will update once the issue is resolved.

Please excuse us for the inconvenience caused.

**Comment by ggkrustev** [comment]
Hey guys, could you check whether the issue is still present? It seems to work on our side now.

**Comment by KenS-MvcDev** [comment]
It appears to work properly.  Thanks for the update.
