### ISSUE TITLE
Stacked Dialogs

### ISSUE THREAD

**Issue by paulstringerdb** [telerik/kendo-angular#600]
Hi,

Please see this plunk...
http://plnkr.co/edit/whXTOp?p=preview

1. You can open the first dialog, no problem,
2. Open a second from the first, no problem
3. Close the second..
[You can now repeat 2 & 3 over without issue]
...however...
Close the first dialog and you can no longer open it from the initial "Please confirm" button on the page.

Are your dialogs capable of being stacked? They do appear to stack up quite well (I've tried recursively using a component) but once the later stacked dialogs are closed it affects the behavior of the opening... of the "below" ones again i.e. it breaks completely. It would be really useful to have stacked dialogs... 

I know there are people who will argue the toss, but walk a mile in our footsteps with our users before you judge !

The upshot is we do display dialogs for pop-up form data entry, these then need to warn the users with errors and/or confirm a "Delete" action with a message box style popup - all of which would be 2 levels deep of stacked dialog. Would be useful to have this functionality...

**Comment by gyoshev** [comment]
Dialogs can be nested. The problem in this plunk is that there are two `[kendoDialogContainer]` elements and dialogs are inserted after the last one inserted in the application. To resolve this, use only one container, preferably at a higher place in the component hierarchy. See the [updated plunker](http://plnkr.co/edit/r3CNXW14q1ppkxe7hlAm?p=preview).

**Comment by paulstringerdb** [comment]
Awesome. Thanks Alex !
