### ISSUE TITLE
Donut series item label not rendering properly when using HTML entity codes.

### ISSUE THREAD

**Issue by ibra038** [telerik/kendo-angular#602]
http://plnkr.co/edit/tTl3GVipCAEqggNi27pc?p=preview

**Comment by danielkaradachki** [comment]
HTML entities are not supported for the labels. You can use regular spaces and canvas rendering if you need to insert multiple spaces:

http://plnkr.co/edit/DTPvGfNuzyMXUlwLxuCj?p=preview

 We are also working on adding support for the same for SVG.

**Comment by danielkaradachki** [comment]
The latest version now supports preserving the spaces for SVG output.
