### ISSUE TITLE
Grid pageChange called to many times

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#603]
If I scroll in [this plunkr](http://plnkr.co/edit/SyxSafvrELCDnNy4ywOB?p=preview) only 1 scroll down, and then again up, 2 problems occur:

1. pageChange is called, but it shouldn't
2.  and this one is a bug: several (7 to be exact) pageChange events are called

I have problems with scrolling, because there are so many request to server, that scrolling become unresponsive.
![2017-06-01_19-15-23](https://cloud.githubusercontent.com/assets/1589573/26691811/d3456cb0-46fe-11e7-8e31-416c74024099.gif)

**Comment by rkonstantinov** [comment]
Thanks for the report. The issue in question should be addressed with the next version of the `kendo-angular-grid package`

**Comment by MaklaCof** [comment]
Tested and it 's fixed.
