### ISSUE TITLE
Angualr 2 Grid to support local data virtualization  as Angualr 1 Grid

### ISSUE THREAD

**Issue by xiaowvmware** [telerik/kendo-angular#604]
Kendo Grid for Angular 1 is an important performance feature that are supported by most of common widget library.

Kendo Grid for Angular 1 support this feature and have a user-friendly way to turn it on.

While it is possible for Kendo Grid for Angular 2 to implement it with virtual scroll, it requires a quite bit of effort on the consumer side.

I would like to request the method to handle local data virtualization that is consistent with Kendo Grid for Angular 1

The  local data virtualization in Angular 1 Grid: http://demos.telerik.com/kendo-ui/grid/virtualization-local-data

**Comment by rkonstantinov** [comment]
Thanks for the feedback.
Although,  the [virtual scrolling demo](http://www.telerik.com/kendo-angular-ui/components/grid/scroll-modes/#toc-set-up-virtual-scrolling) shows a more involved way to handle the paging of the data, it is also possible to use [automatic binding](http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/) approach with virtual scrolling. [Here](http://plnkr.co/edit/nSsuuopthnL7mW8xC2ER?p=preview) you can find a plunkr demonstrating this.

**Comment by xiaowvmware** [comment]
Thanks. It solved my problem.
