### ISSUE TITLE
Chart: Export as PDF doesn't scale correctly

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#605]
I'm trying to export the chart into a PDF:

```
        const visual = this.chart.exportVisual();
        exportPDF(visual, {
            paperSize: "A4",
            landscape: true,
            margin: {top: 15, left: 15}
        }).then((dataURI) => {
            saveAs(dataURI, 'planung.pdf');
            });
```

After the export, the chart is cut off on the side (the legend).

I'm not sure if is this an issue or should I scale it myself? When scaling, how?

Txs

**Comment by danielkaradachki** [comment]
Automatic scaling for the drawing elements is not supported. It is possible to fit the chart either by scaling the export visual or by specifying its size - [example](http://plnkr.co/edit/J5vVzPIClfMQaM38doKV?p=preview). We will include an example demonstrating these approaches.

**Comment by EricSch** [comment]
Thank you :+1:

**Comment by EricSch** [comment]
I have a following up question. Thank you for your sample.

When I add a title as text at the top of the chart, the chart is rendered at the top left corner and the title is overwritten. How I can do it? I assume I have to position the visual, but didn't find any option.
Didn't work:
```
const visual = this.chart.exportVisual();
const group = new Group();
const title = new drawing.Text("detail-grafik", [20, 25], <drawing.TextOptions> { font: "bold 20px Arial"});
group.append(title, visual);
fit(group, this.PAGE_RECT);
exportPDF(group, <pdf.PDFOptions> {
...
```

**Comment by tsvetomir** [comment]
Elements are stacked in order so you need to place the title last, see [plunkr](http://plnkr.co/edit/ylLqMr7c5VoaIOaR9ppb?p=preview):
`group.append(visual, title);`

**Comment by EricSch** [comment]
The bug with the chart stays. changing the order only avoids it.
see also #806

**Comment by AliNafees0800** [comment]
I my case I have multiple graphs and I am export them to pdf use kendo export to pdf which works on elements, what I can do, since I can do exportVisual etc because this is not graph elements

**Comment by tsvetomir** [comment]
@AliNafees0800 this repository is for bug reports only. Please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios.
