### ISSUE TITLE
How can I make a multiple row selection in a grid?

### ISSUE THREAD

**Issue by hero106wen** [telerik/kendo-angular#607]
Hi,
I find that a lot of functions are not realized in the angular version, compare with the jquery version. Can I get a comparation list? 
I used kendo-ui.all.d.ts ,but it's not convenient. So I think about to use the angular version. But it does not realize the whole functions. I hope a to-do-list, then I can go on. Thank you.

**Comment by tsvetomir** [comment]
Multiple row selection is planned as part of #65. Closing this issue as a duplicate.
