### ISSUE TITLE
Can we get a functionaliity comparation list between the angular version an the jquery version?

### ISSUE THREAD

**Issue by hero106wen** [telerik/kendo-angular#608]
Hi,
I find that a lot of functions are not realized in the angular version, compare with the jquery version. Can I get a comparation list?
I used kendo-ui.all.d.ts ,but it's not convenient. So I think about to use the angular version. But it does not realize the whole functions. I hope a to-do-list, then I can go on. Thank you.

**Comment by tsvetomir** [comment]
There's no extensive comparison between the two products. Are there any specific features that you need for your project?

**Comment by hero106wen** [comment]
I wonder witch one to use. My project is starting.

**Comment by tsvetomir** [comment]
It would be best if you file a [support ticket](https://www.telerik.com/account/support-tickets) with more specifics regarding your project.This issue tracker is focused on Kendo UI for Angular and does not cover our full product portfolio and pre-sales questions.
