### ISSUE TITLE
ComboBox is focused by default on Microsoft Edge

### ISSUE THREAD

**Issue by magapios** [telerik/kendo-angular#610]
# Description
On Microsoft Edge the ComboBox is selected by default. I tested this on Microsoft Edge 38.14393.1066.0 but I would expect this to be an issue on other versions as well.

# How to reproduce
- open the first [ComboBox plunker](http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/#toc-basic-usage) from the official documentation
- launch the preview in a separate window
- hit the refresh button (the one underneath the QR code)
- as the preview is refreshed (i.e. while the "Loading..." text is shown), focus on the preview by clicking on the preview's content
Result: the combo box's focused
Expected result: the combo box should not be focused

# Other useful details
As per our investigation, the issue could be caused by SearchBarComponent's `setInputSelection` method—if most browsers don't focus the input on which the `setInputSelection` method is called, Edge seems to be doing so.

If the bug is indeed that, it's also worth noting that the same issue might exist in other component using the SearchBar e.g. the AutoComplete.

**Comment by tapopov** [comment]
Thanks for the detailed report @mihai-agape!
We will investigate and update the thread once we know more.

**Comment by mihai-agape** [comment]
@tapopov Thanks!

**Comment by siyka-marinova** [comment]
Fix is available in `@progress/kendo-angular-dropdowns@1.1.3`
