### ISSUE TITLE
Grid: Master Details + Filter -> Strange behaviour

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#614]
We have implemented a simple plunker to show filter applied on master details grid:

http://plnkr.co/edit/FVnDD9EDO5jznYH5QXkZ?p=preview

To reproduce:
1) Open first row details
2) Search `Bob` on product name

You will see the only row has details opened.
An workaround here? Anyway to store correctly detail open/close state on data item? (i'm just thinking about virtualized + filtered + detailed grid).
Thanks.
Diego

**Comment by rkonstantinov** [comment]
Currently, the detail rows expand/collapsed state is persisted by index. This is why this row is expanded after filtering. 
You could use the expandRow/collapseRow methods to modify which row is expanded/collapsed. For example collapse all of the rows during filtering.

**Comment by meriturva** [comment]
We are implementing exactly same solution during filtering. But just to be clear....will it be fixed or is something "by design" and it will not change in future?

**Comment by rkonstantinov** [comment]
Persisting the state by index is the designed behavior :). However, in the future we may add a way to provide a strategy to handle the state persistence, thus allowing for comparing based on a property of the data item.

**Comment by meriturva** [comment]
Perfect and thanks for your answer.
You could close issue or add Enhancement label.

**Comment by meriturva** [comment]
Hi @tsvetomir !
is it possible to include this Enhancement on R3 2017?

**Comment by rkonstantinov** [comment]
@meriturva I'm afraid that this is will not make to the R3 release.

**Comment by meriturva** [comment]
any eta?
Thanks

**Comment by rkonstantinov** [comment]
Sorry, at this time it is not in our immediate plans. You should keep an eye on this issue to track the progress.

**Comment by elena-gancheva** [comment]
This issue is a duplicated with https://github.com/telerik/kendo-angular/issues/2212.

**Comment by elena-gancheva** [comment]
The feature is available in the latest [`dev`](https://github.com/telerik/kendo-angular-grid/releases/tag/v4.7.0-dev.202003101536) version of the package. Please, check out the examples and the documentation [here](https://www.telerik.com/kendo-angular-ui-develop/components/grid/master-detail/expanded-state/).
