### ISSUE TITLE
Primary, Secondary and Tertiary buttons styles difficult to implement on DropDownButton and SplitButton

### ISSUE THREAD

**Issue by normVent** [telerik/kendo-angular#615]
I have a requirement to implement Primary, Secondary and Tertiary colors on a DropDownButton and it's popup items list. But since the popup list is not a child element of the associated kendo-dropdownbutton element, I cannot find a way, using styles, to assign more than one background-color to a group of DropDownButtons in a component.

**Comment by valchev** [comment]
Hi @normVent 

I suggest to set a specific class to the popup element using [popupSettings property](http://www.telerik.com/kendo-angular-ui/components/buttons/api/DropDownButtonComponent/#toc-popupsettings). This will give you the opportunity to style popup's children.
