### ISSUE TITLE
Grid performance in IE 11

### ISSUE THREAD

**Issue by abhissha** [telerik/kendo-angular#616]
We are currently using Kendo angular 2 grid. We have noticed grid has terrible rendering performance(up to 300 rows) in IE 11 to where the browser keeps on freezing and users can not use the application. We have about 8 columns, with two custom template.  

When opened in chrome, the experience is seamless without any hiccups. I looked into the issues list and there was a similar issue #345 but I didn't see any resolution. 

Is there anything in progress to resolve the issue?

**Comment by tsvetomir** [comment]
Please make sure you have enabled [production mode](https://angular.io/docs/ts/latest/api/core/index/enableProdMode-function.html) for your application.
Can you share a plunkr that is similar to your scenario?
