### ISSUE TITLE
Elements of type <button> and <a> trigger row selection when they have children

### ISSUE THREAD

**Issue by Dunos** [telerik/kendo-angular#618]
The selection over a row should not be triggered when the user clicks in some element like a button or a link. Right now this behaviour only happens when those elements don't have any children inside, only text.

You can check [this plunkr](http://plnkr.co/edit/gXkqPvy33Vw3t1HWc5P5?p=preview) to check it out, the buttons labeled "First" never trigger the selection but the "Second" ones do.

Also it would be nice to add this functionality for Angular Material elements (like md-checkbox).

**Comment by tsvetomir** [comment]
Sorry for taking so long to get back to you.

It's rather hard to tell in a generic way when a click inside the cell should be treated as a "cell click". To that end we intend to start recognizing a special marker class that designates elements that we should ignore. For example:

```html
<ng-template kendoGridCellTemplate>
  <div class="k-grid-ignore-click">
    <button type="button">First</button>
    <button type="button"><span>Second</span></button>
  </div>
</ng-template>
```

This class will also prevent closing the [in-cell editor](http://www.telerik.com/kendo-angular-ui/components/grid/editing/in-cell-editing/).

What do you think?

**Comment by Dunos** [comment]
Sure, that sounds like a good approach!

**Comment by tsvetomir** [comment]
This feature is shipping in v1.5.0 of the Grid, see [the updated plunkr](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-disabling-the-selection-of-specific-elements). Documented in [Disabling the Selection of Specific Elements](https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-disabling-the-selection-of-specific-elements).
