### ISSUE TITLE
Kendo-Dialog - Null title attribute

### ISSUE THREAD

**Issue by barncastle** [telerik/kendo-angular#619]
It appears that by default the kendo-dialog component adds a title attribute with "null" as the value i.e.

`<kendo-dialog title="null" ng-reflect-title="Please confirm" dir="ltr" class="k-dialog-wrapper">`

It also appears on the demos on the http://www.telerik.com/kendo-angular-ui/components/dialog/ page.

**Comment by dtopalov** [comment]
Thank you for logging this. Here are couple of workarounds until we fix it:

1) Show custom tooltips:
[http://plnkr.co/edit/m1Vpyh0Mia3kkeTTCV9K?p=preview](http://plnkr.co/edit/m1Vpyh0Mia3kkeTTCV9K?p=preview)

2) Do not show any tooltips:
[http://plnkr.co/edit/Xb3zDF2bFVUZK7YzFURS?p=preview](http://plnkr.co/edit/Xb3zDF2bFVUZK7YzFURS?p=preview)

**Comment by gyoshev** [comment]
Version `1.0.2` of the dialog package contains the bug fix. Please update to resolve the issue.
