### ISSUE TITLE
DropDownList is not working in hybrid applications

### ISSUE THREAD

**Issue by AlexKichkailo** [telerik/kendo-angular#620]
Popup Service and all dependent components such as DropDownList do not work in hybrid applications. The root cause is that in hybrid applications AngularJS part of app owns the root component, not the Angular part. Therefore, when using Popup Service it throws 'View Container not found!'.  Hybrid applications is a common scenario, do you have any plans to support it? It would be really nice if we could set the root view for Popup Service manually.

**Comment by ggkrustev** [comment]
Hi @AlexKichkailo,
We definitely want to support hybrid (AngularJS + Angular) apps, as they will be the most common and the beginning. 

Right now, you can provide a container element using a [POPUP_CONTAINER](http://www.telerik.com/kendo-angular-ui/components/popup/api/POPUP_CONTAINER/) InjectionToken. The code should like something like this:

```
...
  providers: [
    ContainerService,
    {
      provide: POPUP_CONTAINER,
      useFactory: () => {
        return ({ nativeElement: document.body } as ElementRef);
      }
    }
  ],
  bootstrap: [AppComponent]
...
```
This will tell the PopupService to append to the `document.body`, which is perfectly safe when only a server rendering is used.

We are also planning to expose an `appendTo` property to the PopupService (probably proxied by the DropDowns). Do you think that this will be a better solution than the DI? Please note that this solution will require to define the popup container to every DropDownList component.

**Comment by AlexKichkailo** [comment]
Hi @ggkrustev 

Thanks for the code. It works like a charm!

I think that the DI solution is better than the appendTo in the hybrid application scenario. 

May I suggest improving the error message in Popup Service so instead of 'View Container not found!' it would say 'View Container not found!' Inject the POPUP_CONTAINER. See http://www.telerik.com/kendo-angular-ui/components/popup/api/POPUP_CONTAINER/ for more details;’?

**Comment by ggkrustev** [comment]
Absolutely! This definitely will improve the experience and will help the developers to find a solution of the issue.

**Comment by nbcormier** [comment]
@ggkrustev could you explain this workaround in more detail? How is `ContainerService` used? I have tried adding the provider as described above, but the DropDownList still does not open in my hybrid app.

**Comment by tsvetomir** [comment]
@nbcormier can you please log a new issue with more details about the error you're seeing?

As far as I can see, `ContainerService` is included in the example to indicate the context. It's not a reference to an existing class.

**Comment by tsvetomir** [comment]
Might be a different issue as the OP reports a run-time error. Please, open a separate issue or a [support ticket](https://www.telerik.com/account/support-tickets) with more details about your setup.

**Comment by lawphotog** [comment]
Hi, I am having exact issue as the OP. I am working on a hybrid Angular app. Although, the solution provided by ggkrustev works in terms of removing the error, and showing the dropdown, the popup of the dropdownlist appears somewhere else on the page instead of below the dropdownlist. 

Do we have a solution now for this issue? many thanks.

My angularjs version is 1.7.7. angular version is 7.2.0. and "@progress/kendo-angular-dropdowns": "^3.4.2", "@progress/kendo-angular-popup": "^2.5.0",
