### ISSUE TITLE
Extra element generated in Grid

### ISSUE THREAD

**Issue by xiaowvmware** [telerik/kendo-angular#623]
When we inspect the grid and found the following element:

<div class="k-height-container">
            <div style="height: 3.5e+06px;"></div>
 </div>

I am not sure why it is needed. Please check the attached the screen shot.

![image](https://user-images.githubusercontent.com/29129509/26904499-0c9a2b9e-4b97-11e7-9979-d5dd1d66b827.png
![k-height-container](https://user-images.githubusercontent.com/29129509/26904551-4c1f5d02-4b97-11e7-99d4-621f97f1980b.png)

**Comment by rkonstantinov** [comment]
This element is part of the virtual scrolling rendering. Looking at the screenshot, I suspect that rowHeight setting is defined, but virtual scrolling is not enabled. In such case you should remove the rowHeight setting.

**Comment by rkonstantinov** [comment]
We could add a warning in dev mode for this invalid configuration.

**Comment by tsvetomir** [comment]
Warning added in v1.2.0
