### ISSUE TITLE
IE11: AutoComplete in a Dialog is shown wrong

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#624]
When I use a AutoComplete in a dialog, the list appears behind the backdrop:

http://plnkr.co/edit/H5tJ9en2owYOuDuyoRXx?p=preview

Any quick fix?

Thanks

**Comment by MaklaCof** [comment]
Same in Chrome.

**Comment by EricSch** [comment]
@MaklaCof Thanks, but half true :smile:
With this plunker, it doesn't work in Chrome, but in our use case / app it does work in Chrome, but not in IE.

**Comment by barncastle** [comment]
We came across this as well. As a temporary fix we added a custom style to force the z-index to be higher than the k-overlay.

`.k-animation-container-shown, .k-animation-container>.k-popup { z-index: 10002; }`

**Comment by tsvetomir** [comment]
Tracking this issue in #630
