### ISSUE TITLE
Flip popup when it is positioned above/before the viewport top/left side

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#626]
### Description
The Popup component is designed to flip once the end of the viewport is reached. This is not true when the popup is positioned before the viewport beginning (point [0, 0]). 

It will be nice to enhance current behavior and enable popup flipping and in such scenarios too.

Repro demo: http://plnkr.co/edit/M3aPbtuTn0uLgaOzkzRx?p=preview

Reported in TicketID: 1113065

**Comment by shaharvaldman** [comment]
hi,
We're using the Popup component extensively and this issue has a negative affect for us on a few features.
When is it planned to be resolved?

**Comment by ggkrustev** [comment]
@shaharvaldman, I am afraid that we still don't have a specific ETA for this bug. Until it is addressed, please use different alignment to ensure that the popup is displayed downwards:

http://plnkr.co/edit/nH32t891FCC86NjBPmdC?p=preview

**Comment by ggkrustev** [comment]
Done in latest version.
