### ISSUE TITLE
Trigger `valueChange` after the form control value is updated

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#627]
### Description
Our inputs components will trigger the `valueChange` event before calling the event defined through the ControlValueChange.registerOnChange callback.

#### Solution
Just call the ControlValueAccessor change event before ours.

### Affected packages

- [x] `kendo-angular-inputs` components
- [x] `kendo-angular-dateinputs` components
- [x] `kendo-angular-dropdowns` components
- [x] ~~`kendo-angular-buttons` components~~
- [x] `kendo-angular-upload` component

**Comment by ggkrustev** [comment]
Close this https://github.com/telerik/kendo-angular/issues/594 when enhancement is implemented

**Comment by EricSch** [comment]
Thanks, but too late for me, see my earlier issue #291 . I had to rewrite everything.

**Comment by bjornharvold** [comment]
+1

**Comment by ggkrustev** [comment]
Hi @EricSch,
it seems that we overlooked the scenario in the linked issue. Please excuse us for that.
Well it's better later than never, I guess :).

**Comment by kkalitowski** [comment]
Is this issue still being actively pursued? I'm waiting for `Switch` to be "fixed" in `kendo-angular-inputs` and there doesn't seem to have been any movement in a long time.

**Comment by tsvetomir** [comment]
@kkalitowski the switch is fixed in the latest [development builds](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). Working on the rest. Sorry for the delay!

**Comment by tsvetomir** [comment]
Not applicable to the Buttons package as they do not emit `valueChange`.

**Comment by tsvetomir** [comment]
Inputs fixed in `@progress/kendo-angular-inputs@1.1.0`
