### ISSUE TITLE
DropDownList inside Dialog - data list not appearing correctly

### ISSUE THREAD

**Issue by buaziz** [telerik/kendo-angular#628]
[plunk](http://embed.plnkr.co/8ZXZwv21hd63Z0FrDaID/)

on clicking the DropdownList - the list appears behind the dialog.
![snip_20170608134558](https://user-images.githubusercontent.com/553002/26925024-d2371c2c-4c50-11e7-87c6-f9bcfe21877d.png)

**Comment by tsvetomir** [comment]
Tracking this issue in #630

**Comment by fulfillGit** [comment]
Hi guys.

It's really a kendo UI issue.
We're able to solve it with z-index.

**Comment by andy1992** [comment]
> Hi guys.
> 
> It's really a kendo UI issue.
> We're able to solve it with z-index.

Hi web-hollywood,

Could you share about how you solved the problem? I encountered the same problem, although it only affects dropdownlist with filter functionality enabled.

**Comment by abdulkhaliquem9** [comment]
@andy1992 
you need to overwrite the styles of kendo combobox component as in this solution
[https://reactfaqs.blogspot.com/b/post-preview?token=APq4FmBINusbZk83xgCAcZ2QisoScEKs_huMkjFB_mDIqFGGY_fJWmy7vzbZLo1Dkut_pZ8V4XSCyjgHYUgOWNo7MACxnYk_hdsQVKICHJ8C2zM3KkJksy8A5FNkurKJHzqUPWQYkq54&postId=1095126582061891894&type=POST](url)
