### ISSUE TITLE
kendo popup is not created in kendo popup

### ISSUE THREAD

**Issue by junghwan0624** [telerik/kendo-angular#631]
I have a big problem.
suddenly, kendo popup is not created in kendo dialog.

I used kendo autocomplete function (filter option) in kendo dialog.
but, There is no response even when inputting.
After checking, I found kendo popup is not created in kendo dialog.

I was using it normally. howevenr, it can not be used now.

Please give me a good answer.  (junghwanlee@fashiongo.com)

**Comment by tapopov** [comment]
Hello @junghwan0624 
We are aware of the issue and already working on it. I will close this thread as it is a duplicate of https://github.com/telerik/kendo-angular/issues/630. We will post updates in the other thread.

**Comment by BruceAndLee** [comment]
I has the same issue with kendo dialog,please resolve it,thanks a lot.

**Comment by tsvetomir** [comment]
@BruceAndLee can you please open a new issue with details about the problem? A runnable snippet in StackBlitz would be great to have.

**Comment by BruceAndLee** [comment]
> @BruceAndLee can you please open a new issue with details about the problem? A runnable snippet in StackBlitz would be great to have.

Thanks a lot, the problem had resolved yestoday。
