### ISSUE TITLE
Kendo UI Date picker is slow on IE11

### ISSUE THREAD

**Issue by ldtung** [telerik/kendo-angular#632]
Hi 

I just checked on the demo page, http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/. The Date picker is quite slow when I am moving from one month to the other.

For example, i'm opening Date Picker at month June. I click month March, the date picker is slowly moving

Thanks for your help
Tung

**Comment by ggkrustev** [comment]
Hi Tung,

The rendering performance is different across all popular browsers. Unfortunately, IE11 is slower than the others and this become visible in a more complex layout. The Calendar component for instance, creates multiple month views (when needed) while scrolling, which isn't handled well by IE11.

In general, enabling the Angular production mode improves the situation and makes the component usable, IMHO. Here is a demo that utilizes the Angular production mode:
http://plnkr.co/edit/FfDNGPOSIahyvoGm8iUE?p=preview

and a screencast demonstrating its performance:
https://screencast.com/t/teD6UA2N6On

The Calendar component is already quite perf optimized using all best practices popularized by the Angular core team. I am afraid that there isn't much that we can do for the time being. What I would suggest is exactly to call `enableProdMode` before testing the component responsiveness.

**Comment by daryl0313** [comment]
Hi @ggkrustev 

I'm seeing the same issue as Tung.  In IE11, scrolling through the months is a little slow even when calling enableProdMode(), although it's not terrible.

I am also seeing the popup on the datepicker opening slowly.  This is more noticeable when there are multiple datepickers on the screen as in the plunker below.

[http://plnkr.co/edit/rS90b8qUoxOU1SPCZy1s?p=preview](http://plnkr.co/edit/rS90b8qUoxOU1SPCZy1s?p=preview) (Open in IE11 to see slowness issue)

Is there anything that we can do to help alleviate these issues?  Can we do something with manual change detection to help this control work faster in IE?

**Comment by ggkrustev** [comment]
Hi @daryl0313, sorry for the delayed answer.
The Calendar component, as mentioned, creates multiple month views which will be destroyed on scroll - new dates are passed, which will spin change detection and hence new components will be created. This seems to be noticeably slower in IE11 than in other browsers, mainly due to the slower JS engine.

We, for sure, will further investigate the case further. For now, the only available option is to run the project in Prod mode. None of the change detection strategies will improve the behavior of the component, due to the Angular specifics that I mentioned earlier.

**Comment by ldtung** [comment]
Hello @ggkrustev, any news on this component? Since our application is mainly running on IE11 (with PROD mode) so this is quite difficult for end-user to use the date picker.

Thanks for your support
Tung

**Comment by ggkrustev** [comment]
Hello @ldtung, we are in a process of investigating how the component can render faster in IE11. Once we have more details on the subject, I will update the thread. I hope that it will be in a week time slot.

**Comment by ekungurov** [comment]
We also experience the same problem. Unexpectedly the Calendar component works a bit faster than DatePicker (in IE11).

**Comment by ldtung** [comment]
Hello @ggkrustev 
Did you have any update on this issue? It has been 2 months from the recent investigating :)

Thanks
Tung

**Comment by ggkrustev** [comment]
I can assure you that we haven't forgot this issue :). The good news is that we narrowed the issue down and an improvement in the performance should be introduced soon. Please note that it will be released in DEV channel after the `fast navigation` feature is out (soon after the R3 release).

As mentioned in my previous reply, the thread will be updated once we have something tangible.

**Comment by tsvetomir** [comment]
The dev channel has been updated, give it a spin with `npm install --save @progress/kendo-angular-dateinputs@dev`

**Comment by ggkrustev** [comment]
Also the latest official version `@progress/kendo-angular-dateinputs@1.3.0` includes the optimization along with the new `fast navigation` feature.

**Comment by ldtung** [comment]
Hello @ggkrustev
Thanks for this information. Can we consider that the performance issue has been solved with @progress/kendo-angular-dateinputs@1.3.0?

**Comment by ggkrustev** [comment]
@ldtung, I believe so. Give it a spin and let us know what your findings are.

**Comment by ggkrustev** [comment]
Will close the thread as resolved. Please feel free to comment below if anything rises up.
