### ISSUE TITLE
Groupable - exclude column from groups

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#633]
Is it possible (and if yes how) to just do `[groupable]="false"` on a column component inside groupable grid (just like sortable etc.).

Essentially i want to disable the dragging of the column header.

**Comment by rkonstantinov** [comment]
Currently this is not possible. You could use the `dataStateChange` event to filter the generated group descriptors to remove those that are not needed. However, it is not possible to set a given column to be not draggable at this time.

**Comment by moxival** [comment]
Thanx for the comment. I think it would lead to a very poor user experience if we remove the descriptors but still allow dragging of the column header, at the very least it will be confusing to the end user. 
Will you consider implementing this?

**Comment by rkonstantinov** [comment]
Indeed, it is not the perfect workaround.
We have consider adding such option before, however it will still work funny when combined with column reordering, once column reordering is implemented. Basically it will work the same way as with the suggested workaround.
Maybe, when column reordering is added, we could give it a second thought.

**Comment by moxival** [comment]
In our case reordering or grouping would be equally unwanted as the column in question is column with actions (view, edit, add etc.). 
But in cases where reordering is wanted but not grouping (or vice versa) maybe a no-drop zone can be implemented - headers for no grouping and group header (the toolbar above headers) for no grouping.

There is also an issue with columns without titles (our "action cols" have no titles) where the drag handle says "undefined".

**Comment by rkonstantinov** [comment]
Actually, looking at the description you have given, it appears that there is diffrent problem - the column should not be draggable at all if there is no field set. Thus, maybe addressing this issue will help in getting the desired behavior in your scenario.

**Comment by moxival** [comment]
Yes, for us that will work perfectly.

This possess the same problem (i think), one may want to reorder an action (or whatever) column but will never want to group by it.

**Comment by rkonstantinov** [comment]
Maybe :wink: Either way column without a field should not be groupable as it does not make sense.

**Comment by jsimmonstx** [comment]
I have another suggestion - if all of the values in the column are identical, disable sorting AND grouping for that column automatically. There's no point in allowing it if it won't actually change the grid. To appease the hyper-configurators, a property in the grid control could be provided that allows you to toggle this behavior on/off.

Just saying...

**Comment by tsvetomir** [comment]
@jsimmonstx traversing the data to determine if all values are identical would be impractical and slow. If the developer is certain that this is the case, then she can bind the [groupable](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/#toc-groupable) and [sortable](https://www.telerik.com/kendo-angular-ui/components/grid/api/ColumnComponent/#toc-sortable) column attributes to `false`.
