### ISSUE TITLE
Grid - Tabbing in filter causes grid header and grid data to become unaligned

### ISSUE THREAD

**Issue by dassjosh** [telerik/kendo-angular#635]
If the grid has a horizontal scroll bar and filtering is enabled. If you click on the filter in the first column and keep pressing tab to get to the last filter column. The grid title and filter areas will scroll leaving the grid data unaligned.

Observable at this [Plunker](http://plnkr.co/edit/bUftLDCVR73TPL218bBQ?p=preview)

Steps to reproduce:
1. Click on the first columns filter text box
2. Press tab till you cycle all the way to the last columns filter
3. Observe the filter and title columns move while the data columns remain in place.

Expected Behavior:
Grid data columns should move with the filter and title columns

**Comment by rkonstantinov** [comment]
Thanks for the report. We will address the issue in question for the following versions of the grid package.

**Comment by siyka-marinova** [comment]
Fixed in v1.2.0
