### ISSUE TITLE
Dialog - Title Attribute has null value on Dialog header

### ISSUE THREAD

**Issue by TranHPDung** [telerik/kendo-angular#637]
Solution:

Updated in dialog.component.js as below:
```
DialogComponent.prototype.ngOnInit = function () {
        this._renderer.setAttribute(this._elRef.nativeElement, 'title', '');
    };
```

**Comment by gyoshev** [comment]
Thanks for reporting this, and suggesting a fix! The `null` value was used with the previous version of the rendered, in order to emulate `removeAttribute`. Since `Renderer2` has a `removeAttribute` method, it can be used instead in this case. I'll post an update once this is released.

**Comment by gyoshev** [comment]
Version `1.0.2` of the dialog package contains the bug fix. Please update to resolve the issue.
