### ISSUE TITLE
Popups are hidden behind dialog overlay

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#641]
[Reproduction](http://plnkr.co/edit/jOfik0IEC9Gu3oJ0L8yu?p=preview)

Caused by the z-index of the popup being lower than that of the dialog container.

Workaround: set the z-index of the popup ([demo](http://plnkr.co/edit/zeksavVU4l2Q9v0gu5sJ?p=preview))

    styles: [`
      >>> .k-animation-container-fixed {
        z-index: 10005;
      }
    `]

**Comment by ggkrustev** [comment]
Duplicate to https://github.com/telerik/kendo-angular/issues/630
