### ISSUE TITLE
Charts - is it possible to use ViewChild to set properties?

### ISSUE THREAD

**Issue by mcm-ham** [telerik/kendo-angular#642]
If I take this example and bind using code instead:
http://www.telerik.com/kendo-angular-ui/components/charts/series-types/donut/

```ts
import { Component, ViewChild, AfterViewInit } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <kendo-chart #chart="kendoChart">
    </kendo-chart>
  `
})
export class AppComponent implements AfterViewInit {
  @ViewChild('chart') chart: ChartComponent;

  public data: any[] = [{
    kind: 'Hydroelectric', share: 0.175
  }, {
    kind: 'Nuclear', share: 0.238
  }, {
    kind: 'Coal', share: 0.118
  }, {
    kind: 'Solar', share: 0.052
  }, {
    kind: 'Wind', share: 0.225
  }, {
    kind: 'Other', share: 0.192
  }];

  public labelContent(e: any): string {
    return e.category;
  }

  ngAfterViewInit() {
    this.chart.series = [{
      type: 'donut',
      data: this.data,
      categoryField: 'kind',
      field: 'share',
      labels: {
        content: this.labelContent,
        color: '#fff',
        background: 'none'
      }
    }];
    this.chart.legend = {
      visible: false
    };
  }
}
```
It just shows an empty chart. Is this approach supported and if so what I'm I missing?

**Comment by danielkaradachki** [comment]
This GitHub Issues list is for bug reports only, so I'm going to close this issue with this comment.

The supported approaches to set the charts options are described in the [configuration](http://www.telerik.com/kendo-angular-ui/components/charts/chart/configuration/#toc-configuration) help topic. To provide the entire configuration objects you can set the options [inline](http://www.telerik.com/kendo-angular-ui/components/charts/chart/configuration/#toc-inline-options). 
I hope this helps. If you need additional information, please open a support ticket.

**Comment by mcm-ham** [comment]
Apologies for posting here, thanks for the help.
