### ISSUE TITLE
How to add modules in plunkr

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#644]
I open plunkr from kendo-popup example and I am trying to add DateInputsModule to the plunkr, but compile fails.
Here is [non-working plunkr](http://plnkr.co/edit/3KpnYbRN5yMBJh3BXSyW?p=preview).

Error:
![chrome_2017-06-14_16-00-49](https://user-images.githubusercontent.com/1589573/27136120-b79267f4-511a-11e7-8be7-910cd36b1fc0.png)

**Comment by gyoshev** [comment]
Adding packages requires that they are registered in the systemjs configuration of the application. For the DateInputsModule to be available, add the following line to the `packages` object in the SystemJS configuration:

    "@progress/kendo-angular-dateinputs": {"main":"dist/cdn/js/kendo-angular-dateinputs.js","defaultExtension":"js"},

If this has no performance implications, perhaps this step can be omitted, by adding all packages to the configuration.
