### ISSUE TITLE
Kendo UI File upload with authentication header token

### ISSUE THREAD

**Issue by bjornharvold** [telerik/kendo-angular#647]
How can I secure the upload of the Kendo UI Angular 2 File upload component?

**Comment by Raisolution** [comment]
Hi @bjornharvold,

you could use the [saveHeaders](http://www.telerik.com/kendo-angular-ui/components/upload/api/UploadComponent/#toc-saveheaders) option to add header to each upload request OR the [headers](http://www.telerik.com/kendo-angular-ui/components/upload/api/UploadEvent/#toc-headers) parameter of the `upload event` to attach unique header per request.
