### ISSUE TITLE
When there is initially selected item in the Multiselect, selecting and deselecting another item leads to incorrect selection

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-angular#649]
When there is initially selected item in the Multiselect, selecting and deselecting another item leads to incorrect selection - the second item remains selected in the search bar, but it is not selected in the dropdown and can be selected again (so that the it will appear twice in the searchbar). At the same time, the initially selected item is cleared from the searchbar, but remains selected in the dropdown.

[https://www.screencast.com/t/OvCYBztvvjav](https://www.screencast.com/t/OvCYBztvvjav)

Steps to reproduce:
1. Open Multiselect > Data Binding > [Services demo](http://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/data-binding/#toc-services).

2. Select one item - Chai, for example.
3. Select another item - Aniseed Syrup, for example.
4. Expand the dropdown and deselect Aniseed Syrup by clicking on it (or select it with the keyboard and press Enter).

Result:
1) Chai item is cleared from the searchbar, but remains selected in the dropdown.
2) Aniseed Syrup remains in the search bar, but is not selected in the dropdown and can be selected again (so that the same item appears twice in the searchbar).

**Comment by valchev** [comment]
Seems to be fixed in the latest dev version.

**Comment by ipeshev** [comment]
On same demo selecting different items results taglist populated with items with same label.
![capture 2017-11-04 at 14 37 00](https://user-images.githubusercontent.com/4143177/32326398-52c91964-bfdb-11e7-83df-dfe235b577b9.png)

**Comment by danielkaradachki** [comment]
Incorrect value field. 'ProductId' -> 'ProductID'

**Comment by valchev** [comment]
Demos are already fixed (not just for the multiselect), the pull request was merged earlier today, but the staging is not updated yet.
