### ISSUE TITLE
[Grid] Column resizing

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#650]
It was possible with the Grid JQuery version to allow the user to resize manually each column with his mouse, like this example : http://demos.telerik.com/kendo-ui/grid/column-resizing.
Is it possible to do this with the Angular version ? Any possible release date for this feature ?

**Comment by tsvetomir** [comment]
Column resizing is on our short-term plans, but work has not commenced yet. We hope to have it ready for the September release.

**Comment by ChrisProlls** [comment]
Thanks for you reply.
I let you close this issue if you need it 👍

**Comment by wenminglee** [comment]
Great! Resize is an important feature for grid.

**Comment by HarishVJ** [comment]
AS we are in mid of September already , when you planned to release Resizing feature for Angular Grid .Please let us know.

**Comment by tsvetomir** [comment]
The column resizing got delayed a bit, sorry! We need few weeks to complete it and will publish an incremental update.

**Comment by fatihsimsek** [comment]
could we use [resizable] with kendo-grid@dev?

**Comment by tsvetomir** [comment]
@fatihsimsek, all - the column resizing feature is now available in [development builds](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). Just set _resizable_ to true:

```ts
import { Component } from '@angular/core';
import { sampleProducts } from './products';

@Component({
    selector: 'my-app',
    template: `
        <kendo-grid
            [kendoGridBinding]="gridData"
            [resizable]="true"
            style="height: 300px">
            <kendo-grid-column-group title="Product Info">
                <kendo-grid-column
                    field="ProductID"
                    [width]="50"
                    [minResizableWidth]="30"
                    title="ID">
                </kendo-grid-column>

                <kendo-grid-column
                    field="ProductName"
                    title="Product Name"
                    [width]="360">
                </kendo-grid-column>
            </kendo-grid-column-group>

            <kendo-grid-column
                field="Category.CategoryName"
                title="Category"
                [width]="180">
            </kendo-grid-column>

            <kendo-grid-column
                field="UnitPrice"
                title="Unit Price"
                [width]="180"
                filter="numeric"
                format="{0:c}">
            </kendo-grid-column>
        </kendo-grid>
    `
})
export class AppComponent {
    private gridData: any[] = sampleProducts;
}
```

:beers: go to @rusev
