### ISSUE TITLE
Close kendo-popup on ESC and outside boundary click

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#654]
It would be nice if you would add boolean options to close popup when:

- ESC is pressed 

- outside popup content is clicked.

**Comment by gyoshev** [comment]
Thank you for the suggestions! Just to clarify, is this for the `<kendo-popup>` element or the `<kendo-dialog>` element? The `<kendo-popup>` should close automatically when the page is clicked.

If these are for the Dialog, the keyboard support (for the `Esc` key) is tracked in #530, and the latter is a sensible feature which can be tracked in this trhead.

**Comment by MaklaCof** [comment]
kendo-popup and it does not close. I just tried [Basic usage demo](http://www.telerik.com/kendo-angular-ui/components/popup/#toc-basic-usage) and it does not close, no mater where I click, except Hide Popup button.

**Comment by ggkrustev** [comment]
Hi @MaklaCof, the `<kendo-popup>` component visibility is controlled by the developer using any of the Angular structural directives, e.g. *ngIf. That being said, it is up to the developer to show/hide the component whenever he/she wants.

I do believe that a how-to demo in our documentation will be helpful to accomplish the desired functionality. What do you think?

**Comment by MaklaCof** [comment]
It would be helpful, but since you ask what do I think here it is:

I think ESC and outside click are very common patterns and native support would be great Enhancement.
Apparently something similar [is coming for dialog component](https://github.com/telerik/kendo-angular/issues/530). I hope in not too distant future. 👍

**Comment by ggkrustev** [comment]
Documented as a common scenario:

http://www.telerik.com/kendo-angular-ui/components/popup/#toc-common-scenarios
