### ISSUE TITLE
Chart styling - minor issue

### ISSUE THREAD

**Issue by mcm-ham** [telerik/kendo-angular#655]
Just letting you know it looks like you have the following defined in the default theme:

```css
.k-chart, .k-stockchart {
    height: 400px;
}
```

This conflicts when setting the height using this property:
http://www.telerik.com/kendo-angular-ui/components/charts/api/ChartAreaComponent/#toc-height

So for now I'm adding CSS to override the height of 400px to match what I've set in chart properties.

-------------

Another feedback is I'm looking at only importing the css I need so for the chart I only imported:

```scss
@import "~@progress/kendo-theme-default/scss/dataviz";
```

However the tooltip didn't render properly until I discovered it's a popup and included the css for kendo popup as well. Might be good to mention this in the documentation.

**Comment by danielkaradachki** [comment]
Thank you for pointing out these problems. They should be fixed in the dev channel and will be release after some further testing.
