### ISSUE TITLE
Loading icon is displayed when select item in DropDownList with remote binding/filtering 

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#658]
When I select filtered item in drop down list loading icon is displayed.
![2017-06-17_09-44-43](https://user-images.githubusercontent.com/1589573/27251175-cd3c0c62-5341-11e7-8383-45a0db5c852f.gif)

My html code:
```
    <kendo-grid-column *ngIf="!categoryId" field="category" title="{{'Category' | translate}}">
        <ng-template kendoGridEditTemplate
                     let-dataItem="dataItem"
                     let-formGroup="form">
            <kendo-dropdownlist #listCategories [data]="categories"
                                textField="title"
                                valueField="id"
                                [valuePrimitive]="true"
                                [filterable]="true"
                                [formControl]="form.get('categoryId')">
            </kendo-dropdownlist>
        </ng-template>
    </kendo-grid-column>
```
My ts code:
```
    @ViewChild('listCategories') set setListCategories(content: DropDownListComponent)
    {
        if (!content)
            return;
        if (this.listCategories)
            this.listCategories.unsubscribe();
        this.listCategories = content.filterChange.asObservable()
            .do(() => content.loading = true)
            .debounceTime(300)
            .mergeMap(value => this.categoryAdminService.listLookup({ take: 20 }, { filter: value }))
            .subscribe(categories =>
            {
                this.categories = categories;
                content.loading = false;
            });
    }

```
I can not prepare a plunkr, because I do not know if any of your backend support remote filtering.

**Comment by MaklaCof** [comment]
Hey Telerik!!
Any news.

**Comment by valchev** [comment]
@MaklaCof 

I tried to reproduce the behaviour in a Plunker, but to no avail. Could you please [check my test page](http://plnkr.co/edit/EZ3FAi8SxftsT9P2hkA9?p=preview) and let me know what I am missing?

**Comment by MaklaCof** [comment]
Hi. Strange. I also can not reproduce with your plunkr. My dropdownlist is in grid with reactive forms.
I just have one question, and then I will close issue until I reproduce problem with plunkr.

Is it by design that kendoDropDownList clears filter when item is selected? Because after you select item, another request to server is made and this leads to undesired loading icon.

[Plunkr](http://plnkr.co/edit/gy2EKlpoS0dwSIU8tjSc?p=preview).
![2017-08-30_07-16-11](https://user-images.githubusercontent.com/1589573/29856454-297fb5fa-8d53-11e7-9c80-fabeec048acc.gif)

**Comment by valchev** [comment]
> Is it by design that kendoDropDownList clears filter when item is selected?

Yes, by design the component will emit `filterChange` with empty string after DropDownList value changes, e.g. after item is selected from the list either via enter key or mouse click.
