### ISSUE TITLE
FilterDescriptor does not parse date from querystring

### ISSUE THREAD

**Issue by artyukh** [telerik/kendo-angular#659]
I have FilterDescriptor with value **2017** but in my querystring is **2017-06-20T00-00-00**

{Kendo.Mvc.FilterDescriptor}
    ConvertedValue: **2017**
    Member: "deliveryDate"
    MemberType: null
    Operator: IsGreaterThanOrEqualTo
    Value: **2017**
But QueryString is: {?filter=**deliveryDate~gte~2017-06-20T00-00-00**&page=1&sort=dateAndTime-asc&pageSize=10}

![ask telerik](https://user-images.githubusercontent.com/29544129/27286423-c340b140-5508-11e7-8948-6d72d6b52d86.png)

**Comment by rkonstantinov** [comment]
duplicate to https://github.com/telerik/kendo-angular/issues/657
