### ISSUE TITLE
Unable to format Kendo UI Chart Legend

### ISSUE THREAD

**Issue by mast3rd3mon** [telerik/kendo-angular#660]
I am wanting to format the Kendo UI Legend on the Chart from `SUN JUN 18 2017 00:00:00 GMT+0100 (GMT Summer Time)` to something like `Sun, 18 June 17`.

Looking through the documentation, http://www.telerik.com/kendo-angular-ui/components/charts/api/LegendLabelsContentArgs/ appears to be able to format the legend on the kendo ui chart. I have been unable to get the label content to apply in the format i would like.

**Comment by mast3rd3mon** [comment]
Currently i have a bad workaround of using a for statement to go through my data then manually pipe the data into a string before binding the to screen

**Comment by danielkaradachki** [comment]
Assuming the the values are JS Dates you can use the [IntlService](http://www.telerik.com/kendo-angular-ui/components/internationalization/) to format the values:
http://plnkr.co/edit/eCRJzlHm9HAvSjqSTMjD?p=preview

**Comment by mast3rd3mon** [comment]
But how do you do it with the kendo legend api? my workaround is basically the same as that but allows for grouping dates together

**Comment by danielkaradachki** [comment]
I am not sure if I understand the question but the legend labels do not have built-in formatting because their values are expected to be strings.

Also, note that the GitHub Issues list is for bug reports only, so If you need additional information, please open a support ticket.

**Comment by mast3rd3mon** [comment]
I believe this to be a bug though, you are able to format the labels on charts and going by the docs, you can format the legend but i havent been able to get anything from the legend api docs to work
