### ISSUE TITLE
MultiSelect valueChange issue

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#664]
There is some issue with the valuechange event in the MultiSelect component

http://plnkr.co/edit/7HOSxzklWguPRZE7umYd?p=preview

When you select an item from dropdown valueChange  fires with the correct (current) value but the value of the form control is still the old one - this is not the case when you remove an item (click the X icon) or with the rest of the dropdown family

**Comment by moxival** [comment]
Anyone?

**Comment by tapopov** [comment]
Hey @moxival 

This behavior is not intended. The component's value property is updated before the `valueChange` event is emitted, so I am not sure what's causing this. Perhaps the Angular's change detection cycle hasn't finished at that point. Adding a timeout before logging the component's value yields the expected results.

We will investigate and provide an update as soon as possible.

**Comment by tapopov** [comment]
Quick update, seem to be related to https://github.com/telerik/kendo-angular/issues/627 and should be fixed with kendo-angular-dropdowns v1.1.1
