### ISSUE TITLE
Calendar layout is broken in IE10

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#665]
The Calendar is not displayed as expected in IE10:
[http://run.plnkr.co/mHr5CfoKaupCIzHc/](http://run.plnkr.co/mHr5CfoKaupCIzHc/)

![screenshot_3](https://user-images.githubusercontent.com/7533599/27335118-263fbc52-55d4-11e7-8ac3-8f628b78a625.png)

**Comment by tsvetomir** [comment]
Looks like a duplicate of #651

**Comment by gyoshev** [comment]
Closing as duplicate, will follow up in the other thread.
