### ISSUE TITLE
Loading panel for the Grid

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#666]
Will improve the UX with remote data. See #622 and #154

**Comment by magapios** [comment]
Any clue about when you'll release this?

**Comment by tsvetomir** [comment]
Not yet, sorry! We're working on the roadmap for the next release and will bring it up during planning.

**Comment by willemshe** [comment]
Any updates on this? Or a work around to fix the jumps?

**Comment by tsvetomir** [comment]
No updates yet, sorry.

**Comment by tsvetomir** [comment]
The latest versions introduce a [loading](https://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-loading) property. See [Data Binding Basics](https://www.telerik.com/kendo-angular-ui/components/grid/data-binding/) for an example.

**Comment by JosephIaquinto** [comment]
The loading property doesn't stop the grid from snapping back to the start of the last 'page' loaded into the grid. Is there some way to stop the grid from doing this without completely hiding the content behind a loading indicator? 

We have a custom loading overlay for all http requests which is mostly transparent, so the user sees this jarring jump back to the last batch while the request is waiting for a response. 

I have added the loading indicator in addition to our custom loading indicator and it doesn't end up showing the loading indicator for long enough to avoid seeing it snap back and forth when the request fires.
