### ISSUE TITLE
Chart tooltip formatting issue

### ISSUE THREAD

**Issue by codenewa** [telerik/kendo-angular#667]
I'm trying to format the series tooltip content in the attached plunk: http://plnkr.co/edit/PRRBG3HD4T7aipr2sjvt?p=preview

But the formatting is not happening. 

I used the same template as this example from the site: http://www.telerik.com/kendo-angular-ui/components/charts/chart/globalization/

Please help me understand the issue.

**Comment by danielkaradachki** [comment]
The values must be numbers in order for the format to work:

http://plnkr.co/edit/iknn9amxANDywO3YSF30?p=preview

**Comment by codenewa** [comment]
Oops, thanks.
