### ISSUE TITLE
Batch Editing

### ISSUE THREAD

**Issue by lelong37** [telerik/kendo-angular#668]
Do we know when Batch Editing will make its way to Angular Kendo UI? e.g. http://demos.telerik.com/kendo-ui/grid/editing, feel like all that's missing with the current in-line editing http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/, is tabbing between rows and putting the row your tabbing to, in edit mode. Is there a way to wire this until this feature is official with the Grid API e.g. (saveRow)="", (editRow)="", (rowClick)="", etc.

**Comment by tsvetomir** [comment]
It looks like we missed your question, sorry!

The Grid does not control how the data is submitted to the server. This should be handled in the service code.

The latest version offers [In-Cell Editing](http://www.telerik.com/kendo-angular-ui/components/grid/editing/in-cell-editing/), check it out.

Keyboard navigation (see #46) is still in the works, but I'd like to confirm something with you. The [WAI-ARIA best practices](https://www.w3.org/TR/wai-aria-practices-1.1/#grid) recommend that a Grid "Has only one focusable element in the page tab sequence." This is to avoid "trapping" the user in a Grid with many rows. As a result:
* Navigation between cells is done with the keyboard arrows.
* Edit mode will be toggled with Enter.

Does that sound right?
