### ISSUE TITLE
change datepicker textbox value from month/day/year to something else ex: MM/dd/yyyy

### ISSUE THREAD

**Issue by smdao** [telerik/kendo-angular#669]
if no data in the text, it always shows month/day/year. 
can i change it to something else such as MM/dd/yyyy?

**Comment by ggkrustev** [comment]
Hi @smdao,
the placeholder value of the DateInput is defined directly by the used date format. The specific date parts, e.g. MM, dd, are translated using the corresponding CLDR culture data. The messages are stored in the CLDR `dateFields` scripts, that is loaded during culture setup:
```
...
require("cldr-data/main/bg/dateFields.json"),
...
```

That being said, the only possible way to modify the placeholder is actually to change the corresponding culture date fields defined in the related culture script, the corresponding `dateFields.json` file.

If you would like define a custom placeholder text that will override the date format, then I would suggest you post your idea in our UserVoice portal:

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

This will help us to further evaluate the idea and possibly to schedule it for further investigation.

**Comment by ggkrustev** [comment]
Closing the issue due to inactivity. Feel free to post any related comments in the thread. We will address them accordingly.
