### ISSUE TITLE
combobox with suggestion not go to the text in the middle of string

### ISSUE THREAD

**Issue by smdao** [telerik/kendo-angular#670]
Ex: Hello world

When I type w, it doesn't jump to Hello world
How can I do it?

**Comment by tapopov** [comment]
Hello @smdao 

The behavior you're after is not supported out of the box, as the built-in search functionality uses the "startswith" approach. You can get similar results using a custom filter.
This repository is for bug reports only, so I am going to close the thread.  If you need additional information, please open a support ticket.
