### ISSUE TITLE
Internationalization seems broken

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#671]
Until the version 1.1, it did work. Now it's broken.

I'm loading the external cldr data, similar like mentioned here:
http://www.telerik.com/kendo-angular-ui/components/internationalization/#toc-load-cldr-data.

I debugged through your load method, and it goes through:
![image](https://user-images.githubusercontent.com/25437/27370893-b789cc7c-565e-11e7-87ae-a73be0e25fce.png)

But at runtime it doesn't find the cldr data via `localeInfo(locale)`, clrd[locale] doesn't contain my 'de-CH' culture, only the defaultData. 

Thanks

**Comment by danielkaradachki** [comment]
Seems to be working in this plunker:
http://plnkr.co/edit/PHyPydhOnqpxfLA5UBi2?p=preview

A possible reason for the info not to be found is that there are multiple versions of the kendo-intl package. Are you using the load method exported from kendo-angular-intl or from kendo-intl? The first should guarantee that the data is loaded in the kendo-intl version used by kendo-angular-intl.

**Comment by EricSch** [comment]
Thanks, I'm using it, like it was in your doc.
`import { load } from '@telerik/kendo-intl';`

But it seems, it has changed. So I should use it from kendo-angular-intl?

**Comment by danielkaradachki** [comment]
Yes, this should guarantee that you are loading the data in the correct kendo-intl version.  The examples were also updated to use the method from kendo-angular-intl for the same reason.

**Comment by EricSch** [comment]
Great, thank you, Daniel, the app is working again. 
Wouldn't have found the problem so fast without your help. :clap:
