### ISSUE TITLE
Chart tooltip - Value from another object property

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#673]
In our application I have a simple chart like this :
```
<kendo-chart [title]="'Sql query perf. (in ms)'">
            <kendo-chart-series>
              <kendo-chart-series-item [data]="logService.sql | async"
                                       [labels]="{ visible: true }"
                                       type="column"
                                       field="perfcountFormatted"
                                       [tooltip]="{ visible: true }">

              </kendo-chart-series-item>
            </kendo-chart-series>
          </kendo-chart>
```

Label shows the value correctly, `logService.sql` is a collection of object and in my case I want the tooltip to display another property of this object, is it possible now ?

**Comment by mcm-ham** [comment]
http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19610890-add-ability-to-display-category-to-tooltipcomponen

**Comment by tsvetomir** [comment]
The data item is accessible in the tooltip template. See the third example in [Series Tooltip](http://www.telerik.com/kendo-angular-ui/components/charts/chart/elements/tooltips/#toc-series-tooltip). The full list of available fields is available in the [TooltipTemplatePoint](http://www.telerik.com/kendo-angular-ui/components/charts/api/TooltipTemplatePoint/) API reference.

**Comment by ChrisProlls** [comment]
Thanks !
