### ISSUE TITLE
Dropdowns - dependency on npm 5 causing problems

### ISSUE THREAD

**Issue by mcm-ham** [telerik/kendo-angular#674]
kendo-angular-dropdowns version 1.0.11 has dependencies of:

```json
"dependencies": {
    "@progress/kendo-angular-popup": "^1.1.0",
    "@progress/kendo-angular-resize-sensor": "^1.0.0",
    "@telerik/kendo-dropdowns-common": "^1.0.0",
    "npm": "^5.0.3",
    "webdriver": "0.0.1"
}
```
npm 5 is a new version that has a number of issues for us, by defining this as a dependency it will now get installed under `.\node_modules\.bin\npm` in our project. We are calling `npm i` in our build script inside packages.json, it works the first time but after that it doesn't because it now uses npm ver 5 under `.\node_modules\.bin\npm` instead of npm ver 4 we have installed globally under `%appdata%\npm`.

I would have thought npm and webdriver would belong under "devDependencies"?

**Comment by tsvetomir** [comment]
A genuine WTF moment. We'll fix it right away.
