### ISSUE TITLE
Group layout click problem

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#675]
Hey guys,

The "X" that is supposed to remove the group from the grouping toolbar is not working consistently.  Sometimes it removes the grouping but sometimes it does not - it initiates drag (reorder), sometimes this can get fixed by reload of the page but sometimes it cannot.

I cannot reproduce this consistently so here are  2 gif examples (one is our implementation, the other is one of the grouping examples from the docs)

![frph6hruh0](https://user-images.githubusercontent.com/323925/27381762-b71dffdc-568c-11e7-8c3c-7213ffa003cd.gif)

![wmxguonnvm](https://user-images.githubusercontent.com/323925/27381764-b9aa6c86-568c-11e7-8c76-a3b85edfe3c1.gif)

Nothing is logged in the console.

**Comment by rkonstantinov** [comment]
@moxival thanks for the report.
We have disallowed dragging of the group indicator by its remove button. Thus, this behavior should not be visible anymore. The change will be available in the next version of the grid package.

**Comment by mast3rd3mon** [comment]
Ive had this issue many times, the only thing ive found is to restart your ide and re run the app, and only then it still might not fix

**Comment by tsvetomir** [comment]
Seems to be fixed in the latest version.

**Comment by moxival** [comment]
it is working as expected, thanx
