### ISSUE TITLE
Column name with number: SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#677]
See here to reproduce error:

http://plnkr.co/edit/UAExMRZnJb4li8wCst30?p=preview

I just would like to use auto generated columns: http://www.telerik.com/kendo-angular-ui/components/grid/columns/#toc-auto-generated-columns

but no way when we have numbers on column name as `Col 1`. It works with `Col1`.
Thanks.

**Comment by rkonstantinov** [comment]
Indeed, this is by design. Spaces are not allowed inside field names.

**Comment by meriturva** [comment]
What about just number as: `1`
Thanks

**Comment by rkonstantinov** [comment]
I'm afraid not :disappointed:  Field name _can_ be anything which can be accessed using the "dot" notation like obj.SOMETHING.

**Comment by meriturva** [comment]
Perfect and again thanks!
