### ISSUE TITLE
Cannot use Paging and Grouping at once in chrome

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#678]
Browser: Chrome
Version 59.0.3071.109 (Official Build) (64-bit)

If I use grouping and paging at once, I cannot undo the grouping. I can group fine, but additional events like sorting the grouping and removing the grouped column is not working. This happens in chrome but not in firefox.

Open [this plunker](http://plnkr.co/edit/nX5OKcQRNJKEkt0wF9x9?p=preview) in firefox, everything is working fine. But in chrome, this isn't working.

**Comment by rkonstantinov** [comment]
It seems that the plunker is working as expected on our end, both in Chrome and Firefox. 
Maybe it is due to some Chrome extension you are using. Could you try running the page in incognito mode and see if there is any change in the behavior.

**Comment by vivek201** [comment]
Yup. The issue just disappeared without even doing anything but a PC restart. Retested the plunker as well as my application, both are working fine. Anyways, thanks @rkonstantinov for checking it out.
