### ISSUE TITLE
Collapsing groups in grid breaks page navigation

### ISSUE THREAD

**Issue by zarpilla** [telerik/kendo-angular#679]
Hi, 

If some groups in a grid are collapsed by code, the navigation to other pages is broken sometimes. In the example, you can navigate to page 2, 3, 4, 5, but no data is shown in page 6.

http://plnkr.co/edit/25YTuLe1R0KRbYg4bGNC?p=preview

thanks

**Comment by zarpilla** [comment]
The same happens if all groups in page 1 are closed by clicking in it instead of doing it by code and then we try to navigate to page 6.

http://plnkr.co/edit/YxMom5B6jJ2b5VTscGji?p=preview

**Comment by rkonstantinov** [comment]
Thanks for the report @zarpilla. 
The fix for the this issue will be available in the next version of the grid package.
