### ISSUE TITLE
Grid refresh functionality

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#680]
The Kendo Grid for jQuery has a refresh button in the pager (eg. [grid](http://demos.telerik.com/kendo-ui/grid/index)). 
I couldn't find such a functionality for the angular version.
Is it possible to add something like that for the angular version?

Example:
`<ng-template kendoPagerTemplate>`
 &nbsp; &nbsp; &nbsp;`<kendo-pager-refresh-button (onRefresh)="refreshGrid()"></kendo-pager-refresh-button>`
`</ng-template>`

**Comment by tsvetomir** [comment]
The Grid doesn't currently provide a built-in refresh button.

Please, file a request for this feature on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback) if you have minute.
This will help us gauge the overall interest and prioritize.

Further assistance can be obtained by [submit a support ticket](https://www.telerik.com/account/support-tickets/contact-support-team?pid=1800).
