### ISSUE TITLE
Grid - Collapsing group won't hide detail template

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#681]
- Open [plunker](http://plnkr.co/edit/IE2iebfgxEIvQblqXBLy?p=preview)

- Expand the detailTemplate of the first item (Chai)

- Collapse the first group (Beverages)

- The master row is hidden but the detailTemplate is still visible

**Comment by rkonstantinov** [comment]
Thanks for the report. This issue should be resolved with the next version of the `kendo-angular-grid` package
