### ISSUE TITLE
Error Installing older Dropdown versions from 0.39.0 to 1.01

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#683]
Hi, because of this issue  https://github.com/telerik/kendo-angular/issues/630

I tried to install the older version I am running an a other project that was the 0.39.9 => it doesn't exist anymore and thats not cool, because my Build Script for automatic deploy will fail. So I've tried to install the 0.39.0 but here I get the following error:

    938 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\blubb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
    939 error node v7.0.0
    940 error npm  v4.1.2
    941 error shasum check failed for C:\Users\blubb\AppData\Local\Temp\npm-25536-9b4baf4a\registry.npm.telerik.com\_40progress_252fkendo-angular-dropdowns\-\kendo-angular-dropdowns-0.39.0.tgz
    941 error Expected: 1db709badaeda5ec3bb20cb75bd5ac42211d6530
    941 error Actual:   da08bfa546ee45e22f9c29fd8907b55f2c4da7c9
    941 error From:     https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns/-/kendo-angular-dropdowns-0.39.0.tgz
    942 error If you need help, you may report this error at:
    942 error     <https://github.com/npm/npm/issues>

so currently I am only able to install Version 1.1.0 all lower Versions bring the error above

**Comment by tsvetomir** [comment]
Caused by the same issue in #682, working on it.

**Comment by tsvetomir** [comment]
Try upgrading to 0.39.9 for the moment:
`npm install --save @progress/kendo-angular-dropdowns@0.39.9`

**Comment by qina83** [comment]
the 0.39.9 depends on angular4
I need a version that depends on angular2 as 0.39.0

**Comment by meriturva** [comment]
Stock on same problem. No working version for angular 2.
Actually when i run:

`npm install --save @progress/kendo-angular-dropdowns@ng2`:

```
npm ERR! shasum check failed for C:\Users\diego\AppData\Local\Temp\npm-40320-1bfb5b0d\registry.npm.telerik.com\_40progress_252fkendo-angular-dropdowns\-\kendo-angular-dropdowns-0.37.3.tgz
npm ERR! Expected: 2f593f5537675dd8abbf1ada68db4a724df12b2a
npm ERR! Actual:   9abe9d07b24924b0beb9379113e7097b88237921
npm ERR! From:     https://registry.npm.telerik.com/@progress%2fkendo-angular-dropdowns/-/kendo-angular-dropdowns-0.37.3.tgz
```

Please correct as soon as possible!

**Comment by tsvetomir** [comment]
@meriturva please try again, the package cheksum should be good now

**Comment by josh3184** [comment]
Hi, I was having the same issue and it now works as it did before

**Comment by tsvetomir** [comment]
@squadwuschel 0.39.0 should work now

**Comment by meriturva** [comment]
Perfect! so thanks!
@tsvetomir  what happened?...just to know!

**Comment by tsvetomir** [comment]
We had to restore the dropdowns package from backup, other packages are unaffected. In the meantime we tried to rebuild some of the versions, but that didn't work very well due to the different checksums.

We're working on a solution that will ensure this type of accident won't happen any more.

**Comment by tbrookin** [comment]
Now I'm getting "unregistered users are not allowed to access package @progress/kendo...  If have an .npmrc file with the auth token and it's all been working fine until now.
This is a serious problem.  I can't build.  And if I can't build, then I can't deploy any fixes to my product.  If I have a security incident or other high-impact problem now I'm screwed.

**Comment by squadwuschel** [comment]
it seems that all versions are back online.
