### ISSUE TITLE
The Grid layout is broken in RTL mode when all columns have widths

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-angular#689]
In RTL mode, when all scrollable Grid's columns have explicit widths and the sum of these widths is less than the width of the viewport, the Grid layout is broken:

[http://plnkr.co/edit/Skhm1hzXAXchgotiZkf5?p=preview](http://plnkr.co/edit/Skhm1hzXAXchgotiZkf5?p=preview)

This is caused by the **_inline width_**, which is applied to the Grid content **table** element.

Note: this problem does not present in LTR more: 

[http://plnkr.co/edit/PTnVU7IoKAY0g91TXSnv?p=preview](http://plnkr.co/edit/PTnVU7IoKAY0g91TXSnv?p=preview)

**Comment by gyoshev** [comment]
After some digging, the width is set to resolve an issue with virtual scrolling in RTL in Webkit, as demonstrated in [this Dojo snippet](http://dojo.telerik.com/IjUSE) (see `7f4f2cb7`). A possible workaround is to set `min-width:100%` on the tables.

**Comment by gyoshev** [comment]
The suggested workaround (`min-width:100%`) causes problems when used together with the column resizing feature, thus the fix has been reverted. The problem can be solved by not setting widths on all columns or by adding the style in user styles, via `.k-grid table { min-width: 100%; }`, if column resizing is not used.
