### ISSUE TITLE
Dialog not truly modal

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-angular#690]
You can tab focus to links in the page behind the dialog and hit enter and activate them.

I have a form in a dialog that users will generally be tabbing through the input fields.  If they can accidentally send focus to the page beneath the dialog and activate links there, users can acccidentally lose all the data they put into the form in the dialog.

**Comment by gyoshev** [comment]
Thank you for the feedback. Indeed, the Dialog does not constrain focus within it. This is a good enhancement that can be provided as a property -- if another dialog is opened, this functionality needs to be suppressed.

**Comment by mast3rd3mon** [comment]
Does anyone know if there is any progress on this?

**Comment by gyoshev** [comment]
@mast3rd3mon we have not yet started implementing this. As a workaround, the code from [this gist](https://gist.github.com/gustavpursche/5907263) can be [adapted as a component](http://plnkr.co/edit/Zxr10IlLgllpzxvEhr8l?p=preview).

**Comment by mast3rd3mon** [comment]
Thanks for the reply. I might do just that if we need it

**Comment by Raisolution** [comment]
The issue has been addressed in v3.3.0-dev.201803141141. The fix will also be in the next official release.

**Comment by Raisolution** [comment]
v3.3.0 has been released.
