### ISSUE TITLE
Grid Column Headers - not visible in Bootstrap collapse div until window is resized

### ISSUE THREAD

**Issue by kallenkortuem** [telerik/kendo-angular#691]
Hello,

When a grid with locked columns is nested inside a collapsed div, all non-locked column headers do not appear until the window is resized.

[http://plnkr.co/edit/DJY3OjeEx4J8MNNfrFPK?p=preview](http://plnkr.co/edit/DJY3OjeEx4J8MNNfrFPK?p=preview)

**Comment by rkonstantinov** [comment]
The issue is caused by the fact that the component is not visible while its layout is calculated. Please instead consider using a ngIf to toggle the component visibility.

**Comment by tsvetomir** [comment]
Related to #709

**Comment by tsvetomir** [comment]
Appears to be fixed in the latest version.
