### ISSUE TITLE
Customize upload action button bar in File Upload

### ISSUE THREAD

**Issue by xiaowvmware** [telerik/kendo-angular#692]
If autoUpload is false, the file load component shows the upload action button bar with "Clear" and "Upload" actions.

We would like to change the look and feel of the action bar. It will nice to have a way to overwrite the action bar with a given template.  Such as kendoUploadFileTemplate that overwrites file list item.
![fileupload](https://user-images.githubusercontent.com/29129509/27562934-bf722e4c-5a83-11e7-8dd6-238bed5265c7.png)

**Comment by Raisolution** [comment]
Hi @xiaowvmware,

Thank you for the suggestion. We will consider to add it to our development plans.

**Comment by Raisolution** [comment]
We don't plan to implement this customization in the Upload component.

A suitable workaround would be to hide the action buttons via CSS (targeting them using the `k-action-buttons` class) and adding external buttons bellow the component that invoke the [clearFiles](https://www.telerik.com/kendo-angular-ui/components/upload/api/UploadComponent/#toc-clearfiles) and [uploadFiles](https://www.telerik.com/kendo-angular-ui/components/upload/api/UploadComponent/#toc-uploadfiles) methods of the Upload API.

Similar approach is demonstrated in the following [How-To Example](https://www.telerik.com/kendo-angular-ui-develop/components/upload/how-to/external-btn-uploading/).
