### ISSUE TITLE
Legends on Stock Chart 

### ISSUE THREAD

**Issue by rdontireddy** [telerik/kendo-angular#694]
Hi, I tried to use Legends on stock chart and did not see any affect. Does legends supported on Stock chart?

http://plnkr.co/edit/UCG0tk4KHXl9uc6TYeWa?p=preview

**Comment by danielkaradachki** [comment]
The legend visibility defaults to false for the stockchart. Setting the visible option to true will enable the legend:

http://plnkr.co/edit/oMzq6VPzmZZssdJoePmS?p=preview

We will consider setting the option to true automatically when the legend component is present.

**Comment by danielkaradachki** [comment]
The presence of the component should automatically enable the legend in the latest version:

http://plnkr.co/edit/qY9WK2m8G0BVRlnq6tJU?p=preview

**Comment by Praxsr014** [comment]
This is not working. The Legend is still not showing on my StockChart. 
I have updated @progress/kendo-charts to 1.13.1 and @progress/kendo-angular-charts to 4.0.1
The Legend is not showing up even on the Examples on the Telerik website.

**Comment by tsvetomir** [comment]
The legend will not be visible unless at least one of the series has a set name. See [updated example](https://stackblitz.com/edit/angular-h2ozaa?file=app/app.component.ts).
