### ISSUE TITLE
grid Hiding the List of Operators

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#695]
when i set the _[showOperators]="false"_ attr, you need to cancel the kendo-grid-filter-wrapper-cell **padding**.
 **padding** is **unnecessary** when no filter controls displayed.
See _name filter_ in [this plunkr snippet](http://plnkr.co/edit/oVehhNqq63LozCdcgjD2?p=preview)

**Comment by gyoshev** [comment]
Thank you for reporting this. Indeed, the padding appears unnecessary in that case.
