### ISSUE TITLE
cannot css  .k-filtercell-wrapper

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#696]
I set a css rule for `.k-filtercell-wrapper c lass` but it doesnt affect the `kendo-grid-filter-wrapper-cell` element.
see [http://plnkr.co/edit/KlHhlNshO1XKpy4WazR6?p=preview](url)

**Comment by rkonstantinov** [comment]
The CSS class is not applied due to the [Angular's view encapsulation](https://angular.io/guide/component-styles#view-encapsulation). Therefore, you will need to either set it to `None` or use the [`deep`|`>>>`](https://angular.io/guide/component-styles#deep) prefix.

**Comment by gilior** [comment]
ng docs says: "The :host selector is the only way to target the host element." 
but in this case i dont need the host element. the k-grid is nested inside my component. my Q is why do i need to address the host element?

**Comment by rkonstantinov** [comment]
Did you manage to take a look at the links that I have referenced in my message.

You cannot address it directly due to default Angular's view encapsulation mode, which scopes the CSS to the component's view.
 
Thus, the plunkr in question should be modified to use:
```js
styles:[`
    >>>.k-filtercell-wrapper{background: red !important}
`]
```

**Comment by gilior** [comment]
got it. tnx
