### ISSUE TITLE
grid selection use arrow key for switching items

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#697]
The current default behavior if you use the grid with the selection feature for the key up and key down press is to do scrolling. Wouldn't it be more intuitive if the selection would change in this case (at least that is the behavior of a lot of other grids)?

Usually if a user selects a row and then presses key down he expets the selection to move one line down and not a scrolling to happen. Is there any workaround we can implement on our own to mimic such a behavior?

Thanks in advance for your help :)!

**Comment by rkonstantinov** [comment]
The described behavior will be part of the selection/keyboard navigation feature which progress you could track [here](https://github.com/telerik/kendo-angular/issues/634).
