### ISSUE TITLE
Bootstrap theme input sizes not working "form-control-sm"

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#698]
I try to use the bootstrap theme from kendo but the input sizes are not shown right

![grafik](https://user-images.githubusercontent.com/1572878/27624912-fc63744a-5be2-11e7-8260-3f627049fa25.png)

as you can see the form from the "guid" is a default input field and it looks good, but the kendo inputs like "Long" or "float" are "numerictextbox" from kendo and here there input size is not working for sm.

Also the width is not right, I am using a default form-group from bootstrap

             <div class="col-md-12">
            <div class="form-group row">
                <label class="col-md-3 col-form-label col-form-label-sm text-right font-weight-bold" title="{{row.Name}}">{{row.Name | truncate:40}}</label>
                <div class="col-md-9">
                       <input *ngIf="isString(row)" [(ngModel)]="row.ValueString" [maxlength]="row.MaxLength" name="{{row.Name}}" class="form-control form-control-sm" type="text">
                </div>
            </div>
        </div>

             <div class="col-md-12">
            <div class="form-group row">
                <label class="col-md-3 col-form-label col-form-label-sm text-right font-weight-bold" title="{{row.Name}}">{{row.Name | truncate:40}}</label>
                <div class="col-md-9">
       <kendo-numerictextbox *ngIf="isNumber(row)" [(ngModel)]="row.ValueInteger" [min]="0" [max]="row.MaxLength" [format]="'n0'" class="full-width form-control-sm" name="{{row.Name}}"></kendo-numerictextbox> 
                </div>
            </div>
        </div>

currently I am only importing the following sccs from kendo-theme-bootstrap I am NOT using any kendo-theme-default styles.

@import '~@progress/kendo-theme-bootstrap/scss/all.scss';

I am using the following dependencies

    "dependencies": {
      "@angular/animations": "4.2.4",
      "@angular/common": "4.2.4",
      "@angular/compiler": "4.2.4",
      "@angular/core": "4.2.4",
      "@angular/forms": "4.2.4",
      "@angular/http": "4.2.4",
      "@angular/platform-browser": "4.2.4",
      "@angular/platform-browser-dynamic": "4.2.4",
      "@angular/router": "4.2.4",
      "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.26",
      "@progress/kendo-angular-buttons": "1.0.4",
      "@progress/kendo-angular-dateinputs": "1.0.1",
      "@progress/kendo-angular-dialog": "1.0.3",
      "@progress/kendo-angular-dropdowns": "1.1.0",
      "@progress/kendo-angular-inputs": "1.0.5",
      "@progress/kendo-angular-intl": "1.2.0",
      "@progress/kendo-angular-l10n": "1.0.1",
      "@progress/kendo-theme-bootstrap": "^2.6.0",
      "@progress/kendo-theme-default": "2.37.5",
      "bootstrap": "git://github.com/twbs/bootstrap.git#95f37e4c402df37db16781995ffa1592032df9c8",
      "cldr-data": "31.0.2",
      "core-js": "2.4.1",
      "font-awesome": "4.7.0",
      "lodash": "4.17.2",
      "moment": "2.18.1",
      "rxjs": "5.0.1",
      "zone.js": "0.8.4"
    },

**Comment by gyoshev** [comment]
Thank you for the feedback! Indeed, the [current Bootstrap integration styles](https://github.com/telerik/kendo-theme-default/blob/develop/scss/common/_forms.scss#L263-L341) do not take the `form-control-sm / -lg` classes into account, and can be improved. However, it appears that the different width is not related to the issue. See this [plunkr snippet](http://plnkr.co/edit/NvQ7hKDoMW9Q4lQi4Spn?p=preview).

**Comment by kibbled** [comment]
@gyoshev is there a good workaround for this? Any plans for the Kendo team to implement -sm -lg classes for input and select controls?

**Comment by gyoshev** [comment]
@kibbled You can workaround this limitation by [copying these lines](https://github.com/telerik/kendo-theme-default/blob/develop/scss/common/_forms.scss#L333-L348) and redefining them for `-sm` and `-lg` sizes using the bootstrap variables. For example, the `-sm` classes should be along the lines of:

      .k-widget.form-control-sm .k-input,
      .k-maskedtextbox.form-control-sm .k-textbox,
      .k-textbox.form-control-sm {
          padding: $input-padding-y-sm $input-padding-x-sm;
      }
  
      .k-widget.form-control-sm .k-input {
          height: $input-height-sm;
      }
  
      .k-maskedtextbox.form-control-sm .k-textbox,
      .k-textbox.form-control-sm {
          height: calc(#{$input-height-sm} + 2px);
      }

We plan on implementing these, however there is no specific timeline. You can track the implementation status by subscribing to this issue.

**Comment by kibbled** [comment]
@gyoshev thanks for the snippet this is definitely an improvement! I tweaked it a bit as follows:

.k-widget.form-control-sm {
    padding: 0;
}

.k-widget.form-control-sm .k-input,
.k-maskedtextbox.form-control-sm .k-textbox,
.k-textbox.form-control-sm {
    padding: $input-padding-y-sm $input-padding-x-sm;
}

.k-widget.form-control-sm .k-input {
    font-size: $font-size-sm;
    height: $input-height-sm;
}

.k-maskedtextbox.form-control-sm .k-textbox,
.k-textbox.form-control-sm {
    font-size: $font-size-sm;
    height: calc(#{$input-height-sm} + 2px);
}

**Comment by siyka-marinova** [comment]
Fix is available in `@progress/kendo-theme-default@2.40.0` and later versions.
