### ISSUE TITLE
virtual scrolling and scroll into view

### ISSUE THREAD

**Issue by rdnscr** [telerik/kendo-angular#699]
We use a kendo grid with virtual scrolling. We wrote ower own directive which uses the selectionservice to properly select an item from code. How can we now scroll this item into the viewable part of the grid? We are looking for a funtionlality like scrollIntoView(item).

Is there a way to get such a behavior or is a feature like this planned for grids with virtual scrolling planned in the future?

**Comment by rkonstantinov** [comment]
Thanks for the question. I'm afraid that there is no such method currently available. However, we could consider adding such in the future.

**Comment by tsvetomir** [comment]
Merging with #548
