### ISSUE TITLE
ComboBox OnPush displays wrong value

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#700]
Hello,
I've noticed that using combobox component in ChangeDetectionStrategy.OnPush context updates it's template with previous ngModel value but not the current one.

Here is a plunkr: http://plnkr.co/edit/MqrrwlS9DCYz2zt2grFK?p=preview

Clicking `next` button increments model value but combobox label gets updated with the previous model value.

**Comment by tapopov** [comment]
Hi @ilianiv,
Thanks for reporting this. 
We are currently updating the OnPush strategy implementation and will make sure this scenario is handled as well. The fix should be available soon.

Stay tuned.

**Comment by ilianiv** [comment]
Just an addition. Chart's tooltips don't show up if in OnPush context, too.

**Comment by danielkaradachki** [comment]
I opened a separate issue for the chart:

https://github.com/telerik/kendo-angular/issues/730

**Comment by siyka-marinova** [comment]
Fix is available in kendo-angular-dropdowns v1.1.2
