### ISSUE TITLE
MultiSelect input is auto focused after page loads in Safari

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#702]
All MultiSelects on page are sequentially focused after page loads, it happens only on Safari.
it can be reproduced [here](http://plnkr.co/edit/NSK0XAnolJWo3H8dIfa6?p=preview) it need to be tested in full-screen and browser in window mode.

**Comment by valchev** [comment]
Probably related to telerik/kendo-angular#610

**Comment by siyka-marinova** [comment]
Fix is available in `@progress/kendo-angular-dropdowns@1.1.3`
