### ISSUE TITLE
NumericTextBox unexpected behavior when autoCorrect is active

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#703]
In the following plunker, try to enter 2000 (or another valid value like 1900) via the keyboard:

[http://plnkr.co/edit/1CZJ0Hub6HssZc0dnbbe?p=preview](http://plnkr.co/edit/1CZJ0Hub6HssZc0dnbbe?p=preview)

**Comment by siyka-marinova** [comment]
Fix for this issue will be released shortly, it is currently available in the latest dev version.
To install the latest development build, run `npm install --save @progress/kendo-angular-inputs@dev`

**Comment by tsvetomir** [comment]
The fix is shipped in v1.0.7 of the `@progress/kendo-angular-inputs` package.
