### ISSUE TITLE
Upload - Input field not focusable in a template

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#705]
Reproduced here - [http://plnkr.co/edit/fIDIJit5mb7fMWHXECvu?p=preview](http://plnkr.co/edit/fIDIJit5mb7fMWHXECvu?p=preview)

**Comment by siyka-marinova** [comment]
Fix for this issue is currently available in the latest dev. version of the kendo-angular-upload package: `@progress/kendo-angular-upload@1.2.1-dev.201708300744`. The official package will be release shortly

**Comment by Raisolution** [comment]
Fixed in v1.2.1.
