### ISSUE TITLE
Q: couldn't find grid context menu in "http://www.telerik.com/kendo-angular-ui/roadmap/"...

### ISSUE THREAD

**Issue by gilior** [telerik/kendo-angular#706]

**Comment by tsvetomir** [comment]
There are no plans for a Menu/Context menu components at the moment.

Please, file a request for this feature on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback) if you have minute.
This will help us gauge the overall interest and prioritize.
