### ISSUE TITLE
MultiSelect: Values set via ngModel are not properly reflected in the selected items

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#707]
When the MultiSelect is bound to an array via NgModel, the selected items taglist does not reflect the actual component value when the array is manipulated programmatically:

[http://plnkr.co/edit/ec5P3vMYwbEeboWoRSwh?p=preview](http://plnkr.co/edit/ec5P3vMYwbEeboWoRSwh?p=preview)

**Comment by siyka-marinova** [comment]
Fix for this issue is currently available in the latest dev. version of the package `@progress/kendo-angular-dropdowns@1.2.0-dev.201708290747`

**Comment by siyka-marinova** [comment]
Released in the official package: `@progress/kendo-angular-dropdowns@1.2.0`
