### ISSUE TITLE
Import helpers from tslib

### ISSUE THREAD

**Issue by BahjatSalem** [telerik/kendo-angular#708]
When compiling and packaging the next release of Kendo for Angular, please use the `--importHelpers`  [compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html). 
When using bundling tools like Rollup, the `__extends` declarations and definitions are duplicated and add up to tens of kilobytes.

Example : `@progress/kendo-angular-grid/dist/es/excel/excel-export-event.js`
Bad:
```
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
import { PreventableEvent } from '../preventable-event';
/**
 * Arguments for the `excelExport` event.
 */
var ExcelExportEvent = (function (_super) {
    __extends(ExcelExportEvent, _super);
    function ExcelExportEvent(workbook) {
        var _this = _super.call(this) || this;
        _this.workbook = workbook;
        return _this;
    }
    return ExcelExportEvent;
}(PreventableEvent));
export { ExcelExportEvent };
```
Good : 
```
import * as tslib_1 from "tslib";
import { PreventableEvent } from '../preventable-event';
/**
 * Arguments for the `excelExport` event.
 */
var ExcelExportEvent = (function (_super) {
    tslib_1.__extends(ExcelExportEvent, _super);
    function ExcelExportEvent(workbook) {
        var _this = _super.call(this) || this;
        _this.workbook = workbook;
        return _this;
    }
    return ExcelExportEvent;
}(PreventableEvent));
export { ExcelExportEvent };
```
Thanks in advance.

**Comment by tsvetomir** [comment]
The change is implemented across all packages and upcoming releases will import the helpers from `tslib`.

**Comment by meriturva** [comment]
I think that you have to update documentation here. If you look on get started from kendo official site there is no ref to tslib or `--importHelpers` compilation flag.

Actually just updating packages i get errors due to: `http://localhost:9000/src/tslib 404 (Not Found)`

Do i have to enable importHelpers flag on my tsconfig?

**Comment by tsvetomir** [comment]
The `importHelpers` flag is needed only in our projects. We've also added a package dependency on `tslib`.

What's probably missing is the SystemJS configuration for tslib. We'll need to update our [sample project ](https://github.com/telerik/kendo-angular-quickstart/blob/master/src/systemjs.config.js) as well.
```js
System.config({
    map: {
      'tslib': 'npm:tslib'
    },
...
```

**Comment by meriturva** [comment]
What i think is that if i need to import tslib on my project due to kendo library i could use it also for my classes so i would like to compile my libraries with `--importHelpers` .
I mean, we have a decision here to take to optimise kendo library but also user codes.

I also say that official angular umd bundles contains setPrototypeOf method definition, so no tslib dependencies. am i right?

**Comment by tsvetomir** [comment]
I can't find definite answer on how Angular approaches the problem, but they seem to [depend on tslib](https://github.com/angular/angular/blob/master/packages/common/package.json#L12) . Yet the importHelpers flag is not enabled and the bundles contain generated helpers.

Note that you shouldn't need to import tslib directly, as it is a normal dependency. SystemJS 0.19 might need a hint on how to load it though.

**Comment by tsvetomir** [comment]
I've updated the SystemJS configuration above and in [our sample project](https://github.com/telerik/kendo-angular-quickstart/blob/master/src/systemjs.config.js#L35)
