### ISSUE TITLE
grid fails when accesing a property starting with '@'

### ISSUE THREAD

**Issue by niklas-dahl** [telerik/kendo-angular#711]
modified plunkr: http://plnkr.co/edit/jye0L426fyQnKy8LMTbY?p=preview

I only changed
`<kendo-grid-column field="ProductID" title="ID" width="40">`
to
`<kendo-grid-column field="@ProductID" title="ID" width="40">`
and the grid doesn't render properly anymore.

**Comment by tsvetomir** [comment]
The Grid expects field names to be valid [JavaScript identifiers](https://developer.mozilla.org/en-US/docs/Glossary/Identifier).

We'll note this in the documentation and consider adding a run-time verification in development mode.

**Comment by niklas-dahl** [comment]
fair enough :)

A run-time verification would be amazing, I was using objects similar to this
```
{
  '@id': '213',
  // ..
}
```
and the grid failed silently.

I updated the grid package and now there is at least an error message `Invalid or unexpected token` like in the plunkr.
