### ISSUE TITLE
Retiring the Progress NPM Registry

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#712]
Starting from this week the Kendo UI for Angular packages will be published on [npmjs.com](https://www.npmjs.com/~progress) to address the many concerns users were having with this distribution channel.

Please remove the following lines from your `.npmrc` file to switch to the default registry:
```
@progress:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken=<token>
```

The npm registry at https://registry.npm.telerik.com will continue to function until all users have migrated away from it. 

**IMPORTANT:** New versions of the packages will be published only on npmjs.org.

**Comment by rvovard** [comment]
Installing Kendo UI for Angular packages from npmjs.com works, thank you.

But will it go on working as it is? I mean, packages are now available for free, openly. Is this the wanted behaviour or will there be future changes?

**Comment by tsvetomir** [comment]
Packages are available without authentication, but the license still applies:

## License

This is commercial software. To use it, you need to agree to the [**Telerik End User License Agreement for Kendo UI Complete**](http://www.telerik.com/purchase/license-agreement/kendo-ui-complete). If you do not own a commercial license, this file shall be governed by the trial license terms.

All available Kendo UI commercial licenses may be obtained at http://www.telerik.com/purchase/kendo-ui.

**Comment by Jaygholap** [comment]
Have questions:
1.If you asking to remove two lines containing 'registry.npm.telerik.com' from .npmrc file then do we still need to keep .npmrc in project ? Because .npmrc  contains only those lines with _authToken.
2.What about _authToken ? do we need to remove that as well ?
3.Can you give some example how this will work without _authToken in team project ?

**Comment by tsvetomir** [comment]
@Jaygholap if that's all `.npmrc` contains then go ahead and remove it entirely.
The packages will be accessible with the default npm settings and no auth token.

**Comment by squadwuschel** [comment]
@Jaygholap is the a npm command how I can remove this from my global .npmrc file. Because we don't have any .npmrc in our project folders, it seems to be globaly stored for the current user.

Or where can I find this file on a windows 7 /10 pc

**Comment by tsvetomir** [comment]
@squadwuschel it should be located at `%USERPROFILE%\.npmrc`

**Comment by JohannesHoppe** [comment]
I had to setup the Progress NPM Registry in multiple corporate environments, which was not funny.
Many thanks for this great discussion!

:+1: :+1: :+1:

**Comment by The-Meek-Developer** [comment]
Hope docs get updated soon: http://www.telerik.com/kendo-angular-ui/getting-started/

**Comment by tsvetomir** [comment]
@danobri try running `npm cache clean` and remove your projects `node_modules` folder for good measure.

**Comment by danobri** [comment]
Cache clean did it - thanks!

**Comment by yasiryc** [comment]
I followed the steps above and cleaned .npmrc file. After cleaning the file, i used following command to install the grid but I got code 403 Forbidden error. Please note i am a licensed user.

npm install --save @progress/kendo-angular-grid @progress/kendo-angular-dropdowns @progress/kendo-angular-inputs @progress/kendo-angular-dateinputs @progress/kendo-data-query @progress/kendo-angular-intl @progress/kendo-angular-l10n @progress/kendo-drawing @progress/kendo-angular-excel-export @angular/animations

**Comment by tsvetomir** [comment]
@yasiryc the public npm registry doesn't have authentication. It's likely that the npm cache or configuration is still pointing to the Progress registry.

Please run `npm cache clean` and remove the 'node_modules' folder from the project. If that fails, please open a support ticket and attach the `npm-debug.log` file for us to analyze.

**Comment by yasiryc** [comment]
@tsvetomir Thank you for the feedback. I followed the steps and still no luck. I have opened support ticket and attached the log as well. 

One thing i noticed in the log that 403 error was returned on following fetch request

65 http fetch GET 403 https://registry.npm.telerik.com/@progress%2fkendo-angular-buttons/-/kendo-angular-buttons-0.23.0.tgz 244ms
66 silly fetchPackageMetaData error for @progress/kendo-angular-buttons@https://registry.npm.telerik.com/@progress%2fkendo-angular-buttons/-/kendo-angular-buttons-0.23.0.tgz 403 Forbidden: @progress/kendo-angular-buttons@https://registry.npm.telerik.com/@progress%2fkendo-angular-buttons/-/kendo-angular-buttons-0.23.0.tgz

**Comment by brownieboy** [comment]
@yasiryc,

You are still pointing to the retired Telerik repository.  You need to be pointing to the standard npmjs repository, e.g:

https://registry.npmjs.org/@progress/kendo-angular-buttons/-/kendo-angular-buttons-0.23.0.tgz

Did you follow all the instructions and suggestions in the previous posts on this thread?

**Comment by niklas-dahl** [comment]
this is a very appreciated change, since it makes installing kendo in a CI environment much easier :+1: 

will this also mean that Kendo UI Professional will become open source?

**Comment by tsvetomir** [comment]
@niklas-dahl there are no plans for open sourcing the components at the moment.

Some packages, most notably the themes and [kendo-intl](https://github.com/telerik/kendo-intl) are dual-licensed with a commercial and Apache 2.0 license.

**Comment by yasiryc** [comment]
In my case package-lock,json file still had reference cached to old repository. I removed it and "npm install" command worked without any issues

**Comment by tsvetomir** [comment]
Be advised that the Progress NPM registry will be shut down by the end of January due to infrastructure reorganization. Installation of `@progress/kendo-*` packages will fail if you reference _registry.npm.telerik.com_ in _.npmrc_, _package-lock.json_ or _yarn.lock_ files.

**Please, make sure that you have removed references to _registry.npm.telerik.com_ by following the steps outlined above.**

**Comment by mohitgupta86** [comment]
@tsvetomir I have a Kendo UI complete license which got expired in Oct 2017. Can I download "KendoUI For Angular" packages and use them in my organization projects.?

**Comment by tsvetomir** [comment]
@mohitgupta86 please open a support ticket for issues regarding licensing. Thanks!
