### ISSUE TITLE
Accessing TooltipTemplatePoint values in a chart tooltip

### ISSUE THREAD

**Issue by petebetelgeuse** [telerik/kendo-angular#715]
similar to [673](https://github.com/telerik/kendo-angular/issues/673) ; but not a dupe.

Plunker below is trying to surface dataItem contents in the tooltip. 
Examples on the Kendo site show the use of let-value directive, but the contents of 'value' are very limited (depending on the chart, might just show the numeric value of the point) 

In this example, how can we access the category value, and a property of the data item that is not used directly in the chart
[Plunker](http://plnkr.co/edit/n87LTwODV0EX0c0qAHFG?p=preview)

[Docs suggest a range of values should be available, depending on the chart type:](http://www.telerik.com/kendo-angular-ui/components/charts/api/TooltipTemplatePoint/)

**Comment by tsvetomir** [comment]
You need to assign variable names using the full `let-x="..."` syntax:

```html
<ng-template kendoChartSeriesItemTooltipTemplate
             let-dataItem="dataItem" let-category="category" let-value="value">
```

**Comment by petebetelgeuse** [comment]
Thanks for your help
I can now access category 
[Plunker](http://plnkr.co/edit/HdGAPrBAQ87ZtbDEwFW2?p=preview)

But it looks like the dataItem just contains the point value; I was expecting something more like the dataItem in the grid template, which contains all of the underlying object attributes, which would allow the attribute 'flibble' to be accessible

**Comment by tsvetomir** [comment]
The Chart will inherit the original data item when category aggregates are in effect - that is, two points have the same category value and a categoryField binding.

The dataItem fields are accessible via the prototype chain of the dataItem. See the [updated plunkr](http://plnkr.co/edit/bx34T62DlXeBfIXLy1eQ?p=preview).

**Comment by petebetelgeuse** [comment]
Awesome; Thanks for your help
