### ISSUE TITLE
SplitButton - use *ngIf binding will show error: "ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by zhao125787935** [telerik/kendo-angular#716]
Hi kendo team,

I am using splitbutton in my template like this:
`<kendo-splitbutton id="splitBtn" *ngIf="options.hasSplit"
	[data]="options?.splitBtnOptions.items"
	(buttonClick)="onSave($event)"
	(itemClick)="onItemClick($event)">{{options?.splitBtnOptions.text}}
</kendo-splitbutton>
`
I bind the variable "options" by an observable,
`		this.service.getData()
			.filter((layout: any) => layout !== null && layout !== undefined)
			.subscribe((layout: any) => {
				this.options = layout;
			});`
But when I load the app, it will show the error: ExpressionChangedAfterItHasBeenCheckedError: "Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'."

I also try with Html button and use same binding, it works fine.
I don't know why it happens, I use some workarounds, it will show at the first time, the second time will show the same error.
Would you please help with this issue ?

**Comment by zhao125787935** [comment]
I work out a workaround to force to detect the changes in the hook afterViewChecked which fixes this issue.
`ngAfterViewChecked(): void {
      this._detector.detectChanges();
}`
I don't know why splitbutton has to do this, because other kendo components work fine when trying to use ngIf binding,

**Comment by rusev** [comment]
@zhao125787935 I've tried to replicate the describe behavior in the following example - https://plnkr.co/edit/PdRgZ1N2uLablHEBBjhs?p=preview

However all seems to work properly? Do I miss something?
