### ISSUE TITLE
Grid Paging buttons not working as expected

### ISSUE THREAD

**Issue by mbrookson** [telerik/kendo-angular#718]
The Grid page buttons do not work with latest packages like it does in the Plunker demo (http://www.telerik.com/kendo-angular-ui/components/grid/paging/)

It looks like the subscription chain gets to `this.pageChange.emit(event)` in `PagerComponent.prototype.changePage` but it never calls anything that updates the buttons, so the active page button and the current page state never change.

For example, I have 25 rows in my grid. The `skip` starts at 0 and `take` is 12. The initial grid loads correctly with page 1 active and display 12 results. If I click the page 2 button, rows 13 to 24 load but button 1 stays active, and button 3 loads row 25 but 1 still stays active.

Also, clicking the  'next' button always passes in index 1 so it only ever display data from page 2 (and still doesn't update the active button).

I have tried on a grid that has no grouping, filtering or sorting.

Can't see what I'm doing wrong. 

**app.component.html**
`<kendo-grid [data]="gridView" [groupable]="true" [group]="gridState.group" [sortable]="true" [sort]="gridState.sort" [filterable]="true"
  [filter]="gridState.filter" (dataStateChange)="dataStateChanged($event)" [pageable]="true" [pageSize]="pageSize" [skip]="skip"
  height="500" scrollable="scrollable">
  <kendo-grid-excel fileName="Beers.xlsx"></kendo-grid-excel>
  <ng-template kendoGridToolbarTemplate>
    <button type="button" kendoGridExcelCommand><span class="k-icon k-i-file-excel"></span>Export to Excel</button>
  </ng-template>
  <kendo-grid-column field="id" title="ID" [width]="80"></kendo-grid-column>
  <kendo-grid-column field="name" title="Name" [width]="180" *ngIf="!showNumbersOnly"></kendo-grid-column>
  <kendo-grid-column field="abv" title="ABV" [width]="80"></kendo-grid-column>
  <kendo-grid-column field="tagline" title="Tag Line" [width]="180" *ngIf="!showNumbersOnly"></kendo-grid-column>
  <kendo-grid-column field="volume.value" title="Volume" [width]="120"></kendo-grid-column>
  <kendo-grid-column field="volume.unit" title="Volume Unit" *ngIf="!showNumbersOnly">
    <ng-template kendoGridGroupHeaderTemplate let-value="value">
      {{value}}
    </ng-template>
  </kendo-grid-column>
  <kendo-grid-column field="image_url" title="Image" *ngIf="!showNumbersOnly" [filterable]="false">
    <ng-template kendoGridDetailTemplate let-dataItem>
      <img [src]="dataItem.image_url" alt="" style="width: 100px;">
    </ng-template>
  </kendo-grid-column>
</kendo-grid>`

**app.component.ts**
`@\Component({
  selector: 'app-table-all',
  templateUrl: './table-all.component.html',
  styleUrls: ['./table-all.component.scss']
})
export class TableAllComponent implements OnInit {
  showNumbersOnly: boolean = false;
  gridView: DataResult;

  skip: number = 0;
  pageSize: number = 12

  gridState: State = {
    group: [],
    sort: [],
    take: 15,
    skip: 0
  };

  private data = [];

  constructor(private http: Http) {
    let beers = JSON.parse(localStorage.getItem('beers')) as BeerItem[];
    this.data = beers;
  }

  ngOnInit() {
    this.loadData();
  }

  dataStateChanged(state: DataStateChangeEvent) {
    this.gridState = state;
    this.loadData();
  } 
  private loadData() {
    this.gridView = process(this.data, this.gridState);
  }`

**package.json**
`"@angular/animations": "^4.2.5",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@progress/kendo-angular-buttons": "^1.0.5",
    "@progress/kendo-angular-dateinputs": "^1.0.5",
    "@progress/kendo-angular-dropdowns": "^1.1.1",
    "@progress/kendo-angular-excel-export": "^1.0.3",
    "@progress/kendo-angular-grid": "^1.2.2",
    "@progress/kendo-angular-inputs": "^1.0.6",
    "@progress/kendo-angular-intl": "^1.2.1",
    "@progress/kendo-angular-l10n": "^1.0.2",
    "@progress/kendo-angular-layout": "^1.0.5",
    "@progress/kendo-data-query": "^1.0.5",
    "@progress/kendo-drawing": "^1.1.1",
    "@progress/kendo-theme-default": "^2.38.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"`

**Comment by rkonstantinov** [comment]
@mbrookson  The `skip` and `take` are not bound to the state, but to fields which are not updated.

**Comment by mbrookson** [comment]
@rkonstantinov Would you be able to give a little extra guidance? I have set the `[pageSize]` and `[skip]` attributes on `<kendo-grid>` which are bound to properties of my class. Not having much luck getting it to work still

**Comment by mbrookson** [comment]
@rkonstantinov I see! So adding `this.skip = state.skip;` in `dataStateChanged()` enables it to work properly 👍
