### ISSUE TITLE
kendo-numerictextbox inside kendoGridEditTemplate using Reactive Forms doesn't work

### ISSUE THREAD

**Issue by savarex** [telerik/kendo-angular#722]
Hi,
I need to configure a numerictextbox as editor for a column.
As usual I started from docs specifically here 
[grid/editing/custom-reactive-editing](http://www.telerik.com/kendo-angular-ui/components/grid/editing/custom-reactive-editing/)
but when I used a numerictextbox I got an error because `[formControl]` property doesn't exist.

So I read that
[inputs/numerictextbox/forms](http://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/forms/)
but also adding `formControlName="myfieldname"` it doesn't work

This is my grid edit template column
```
            <kendo-grid-column field="day" title="Cassa" width="100">            
                <ng-template kendoGridEditTemplate 
                        let-column="column" let-formGroup="formGroup" let-isNew="isNew">                    
                    <kendo-numerictextbox [formControl]="formGroup.get(column.field)" [min]="1" [max]="31" [spinners]="false"></kendo-numerictextbox>
              </ng-template>                
            </kendo-grid-column>

```

I'm not evaluating this library... I'm a developing a real app for a customer, so any help it's very appreciated.

Many thanks,
Emanuele Savarese

**packages versions**
   kendo-angular-grid 1.2.2
   kendo-angular-inputs 1.0.6

**Comment by danielkaradachki** [comment]
Have you imported the Inputs or the NumericTextBox module?

http://plnkr.co/edit/SpyCKetegRWTLeSqNq5U?p=preview

**Comment by savarex** [comment]
It seems I did a stupid error!

## **Thank you very much @danielkaradachki** 

I added all modules that you indicate and now it works perfectly!

It all new for me and I still need some time to be confident in managing all new stuff
