### ISSUE TITLE
Grid rows are not in sync when edit mode content height is greater than the locked container

### ISSUE THREAD

**Issue by rkonstantinov** [telerik/kendo-angular#724]

**Comment by siyka-marinova** [comment]
Fixed in `@progress/kendo-angular-grid v.1.2.3`

**Comment by oscarrodar** [comment]
Hi, I'm trying to do an upgrade to `v.1.2.3` but npm says the following
![image](https://user-images.githubusercontent.com/8369553/29540061-e8d675f4-8689-11e7-9de2-5f839d06c470.png)

**Comment by rkonstantinov** [comment]
@oscarrodar most probably you are still using the retired private NPM registry. Please take a look at https://github.com/telerik/kendo-angular/issues/712
