### ISSUE TITLE
Calendar navigation bar is incorrectly offset when used with bootstrap and flexbox

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#726]
### Description
The Calendar fast navigation list is incorrectly offset when bootstrap with flexbox applied to the document.body is used. It displays 4 months behind the actual focused date.

![screen shot 2017-07-07 at 1 47 15 pm](https://user-images.githubusercontent.com/495188/27954924-cf1b6b70-631a-11e7-8819-12c630fb4cfa.png)

Here is a repro demo:
http://plnkr.co/edit/zMccZ9Y1ffHd7iAtzxc0?p=preview

Originally reported in https://github.com/telerik/kendo-angular/issues/685

**Comment by siyka-marinova** [comment]
Fix for this issue will be released shortly, it is currently available in the latest dev version.
To install the latest development build run npm install --save @progress/kendo-angular-dateinputs@dev

**Comment by ggkrustev** [comment]
Released under `v1.0.6`
