### ISSUE TITLE
MaskedTextBox width cannot be styled

### ISSUE THREAD

**Issue by jacktho** [telerik/kendo-angular#727]
See Plunker: http://plnkr.co/edit/ssMuJAtrcAPUIUEb6UNb

`style="width: 100%"` seems to be ignored.

**Comment by jacktho** [comment]
`/deep/ input, kendo-maskedtextbox {
  width: 100%!important;
}` in the parent component's scss does work.

**Comment by rmeltonmi** [comment]
Is the workaround to inject the following CSS after the loading of the theme?

.k-maskedtextbox {
display: inline-flex;
border-width: 0;
}
.k-maskedtextbox .k-textbox {
flex: 1 0 0;
min-width: 0;
}

**Comment by siyka-marinova** [comment]
Fix is available in `@progress/kendo-theme-default` v.2.38.1 (2017-07-12)

**Comment by gyoshev** [comment]
@rmeltonmi these styles should provide a workaround, however it is recommended to upgrade the theme instead.

**Comment by oscarrodar** [comment]
Is this fixed for `@progress/kendo-theme-bootstrap`?

**Comment by gyoshev** [comment]
@oscarrodar yes, here is a [plunker snippet](https://plnkr.co/edit/WnSrQTiIk5fMnTSq2u87?p=preview) with the latest bootstrap theme.
