### ISSUE TITLE
Popup is detached from the anchor when opened in iOS device

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#728]
### Description
The popup detaches itself from the anchor when virtual keyboard shows up. This is particular observable with the DropDowns

Repro demo:
- http://plnkr.co/edit/dzBJ2AG9WWE5go5WFg9Y

Steps:
1. Open the demo
2. Maximize the example (use 'X' in the top right corner)
3. Open the popup and notice how there is a gap between the multiselect and the popup

Originally reported in 1118022

**Comment by dtopalov** [comment]
Also reported in this support thread:

Ticket ID: 1118341

**Comment by siyka-marinova** [comment]
Still reproducible with `@progress/kendo-angular-popup@.1.1.2-dev.201707191640` on iOS device with this [plunker](http://plnkr.co/edit/9dfBKnA1mMWGF5aPrwVo?p=preview)

**Comment by ggkrustev** [comment]
This turned out to be a problem with the `position: fixed` implementation in mobile OS (more tests [here](https://remysharp.com/2012/05/24/issues-with-position-fixed-scrolling-on-ios)). Will update the thread with more details, once we introduce a proper solution.

**Comment by ggkrustev** [comment]
We introduced a second position strategy for the Popup. It will be able to position absolutely (`position: absolute`), which will overcome the unsupported `position: fixed` in major mobile browsers. The fix should be available in DEV soon.

**Comment by siyka-marinova** [comment]
Fixed in `@progress/kendo-angular-popup@1.2.0`
