### ISSUE TITLE
Apply a custom CSS class to a grid row based on some condition.

### ISSUE THREAD

**Issue by skorunka** [telerik/kendo-angular#729]
Is there a way how to apply a custom CSS class to a grid row?

I have a gird which displays some data and each row in the model has `unread(bool)` property. I need to apply a custom class to each row (TR element) in the grid where the item has `unread` set to true.

**Comment by tsvetomir** [comment]
You can use [rowClass](http://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-rowclass) for this purpose. The docs are not very exhaustive on it at the moment, see #139.

**Comment by skorunka** [comment]
Thank you!
