### ISSUE TITLE
In IE11 Kendo Multi Select is focused by default

### ISSUE THREAD

**Issue by rdontireddy** [telerik/kendo-angular#732]
Hi , In IE11 Multi Select is focused by default. 

http://embed.plnkr.co/sM5kzxmvTcy8RbQcIH63/

Thanks,
Raj

**Comment by rusev** [comment]
Thank you for reporting this. We will investigate the behavior and report back when we have more details.

**Comment by valchev** [comment]
Related to telerik/kendo-angular#610

**Comment by tsvetomir** [comment]
Tracking in #610
