### ISSUE TITLE
Zooming in and out on Stock Chart doesn't work when categoryAxis type is category

### ISSUE THREAD

**Issue by rdontireddy** [telerik/kendo-angular#734]
Hi , When I use stock chart with category axis type as category, the zoom doesn't work correctly.

In the below plunker, using mouse wheel try to zoom in and out when the focus is on the chart, and notice how it jumps all the way end. When focused on navigator zoom works fine. 

http://plnkr.co/edit/htyFMGpyzky9WNwm9St1?p=preview

**Comment by danielkaradachki** [comment]
The stock chart works only with date axis. Using category axis type category is not currently supported.
