### ISSUE TITLE
Incorrect value in Kendo switch placed inside an *ngIf in Kendo Dialog

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#735]
Plunker: [http://plnkr.co/edit/pXQuHGYIGqf4dD4pJMOH?p=preview](http://plnkr.co/edit/pXQuHGYIGqf4dD4pJMOH?p=preview)

When using forms inside a kendo dialog, If the kendo switch control is inside an `*ngIf`, the value of the Kendo Switch is incorrect. 

Please note:
- This happens only if the form is inside a Kendo dialog. Removing the Kendo Dialog and placing the form inside another `div` with the same `*ngIf` does not show this problem [http://plnkr.co/edit/MiZ6JKOstTY2q1SSBgZa?p=preview](http://plnkr.co/edit/MiZ6JKOstTY2q1SSBgZa?p=preview)

- Also, just removing the `*ngIf` from the `div` just outside the switch also fixes this problem. [http://plnkr.co/edit/EaFnAGt1TS9zj8yPdY6w?p=preview](http://plnkr.co/edit/EaFnAGt1TS9zj8yPdY6w?p=preview)

**Comment by gyoshev** [comment]
There is a problem with the SystemJS configuration in the example, here is an updated plunker with the latest scripts: http://plnkr.co/edit/pXQuHGYIGqf4dD4pJMOH?p=preview

It appears that the reported problem has changed, as currently the slider appears in an invalid state.

**Comment by vivek201** [comment]
@gyoshev Thanks for fixing the plunker. I've updated the title and description of this issue.

**Comment by vivek201** [comment]
@tsvetomir Is there any update on this?

**Comment by tsvetomir** [comment]
We pushed a fix in the latest [development build](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/). Can you please give it a go?

**Comment by tsvetomir** [comment]
Fixed in `@progress/kendo-angular-inputs@1.1.0`
