### ISSUE TITLE
Kendo Label `[for]` binding does not work with checkboxes

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#738]
Can be reproduced in [this plunker demo](http://plnkr.co/edit/VYgbPDXPskqNXJ1TJVji?p=preview).

Workaround: use the `[attr.for]` binding to render a `for` attribute.

As a side-note, it will be good for accessibility to render the `for` attribute if the target is an input element.

**Comment by tsvetomir** [comment]
Fixed in v1.0.3 of the `@progress/kendo-angular-label` package.
