### ISSUE TITLE
Frame of TabStrip is incomplete

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular#739]
Hi, the frame seems to be incomplete again, please check

http://www.telerik.com/kendo-angular-ui/components/layout/tabstrip/

Thanks

**Comment by tsvetomir** [comment]
Looks good with the latest version 
![image](https://user-images.githubusercontent.com/247917/30963500-4af1f094-a456-11e7-859b-e4f5a3dacb2b.png)
