### ISSUE TITLE
DropDownButton documentation styling issue

### ISSUE THREAD

**Issue by davidboothe** [telerik/kendo-angular#741]
http://www.telerik.com/kendo-angular-ui/components/buttons/dropdownbutton/items-and-templates/

in the url above, the example looks like it only shows 1 dropdown element due to the height of the display area and how it has an overflow hidden style.

![image](https://user-images.githubusercontent.com/433071/28240566-0ac0de14-694a-11e7-995e-0fc67042ef97.png)

opening in plunker, the example works as expected.

**Comment by gyoshev** [comment]
Thanks for reporting this! It has been fixed and will go live with the next website update.
