### ISSUE TITLE
Grid Overview error

### ISSUE THREAD

**Issue by sjsusce** [telerik/kendo-angular#744]
I followed the instruction at http://www.telerik.com/kendo-angular-ui/components/grid/ and generated errors when trying to run: 

npm install --save @progress/kendo-angular-grid @progress/kendo-angular-dropdowns @progress/kendo-angular-inputs @progress/kendo-angular-dateinputs @progress/kendo-data-query @progress/kendo-angular-intl @progress/kendo-angular-l10n @progress/kendo-drawing @progress/kendo-angular-excel-export @angular/animations.

npm ERR! path D:\kendo-angular\node_modules\@progress\kendo-angular-grid
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\kendo-angular\node_modules\@progress\kendo-angular-grid' -> 'D:\kendo-angular\node_modules\@progress\.kendo-angula
r-grid.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.

System:
Angular CLI Version (1.2.1)
NPM 5.0.0
Nodejs v8.0.0

**Comment by tsvetomir** [comment]
This is not a known issue to us. Try running `npm install -g npm` to get the latest npm.
