### ISSUE TITLE
Chart: Wrong position of Axis title

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#745]
With the latest chart version, the axis title 'Datum' is positioned wrong. 

http://plnkr.co/edit/miMRl1atlMPF4w07LGmc?p=preview

Should be at the bottom, outside of the chart, like on the x axis.

BTW: Is there also a way to position the category labels outside the chart?

Thanks

**Comment by tsvetomir** [comment]
The title position looks as expected. Do you know which version behaved differently?

I've updated [the snippet](http://plnkr.co/edit/jUtgK8ZgXRn9WRUKdJt3?p=preview) to include a second axis, positioned at the bottom. It's only used to display the title. This is the recommended workaround at the moment.

**Comment by EricSch** [comment]
So this is expected? Surely not the desired outcome for displaying a title.

And I thought it was in version 1.2.0, but could be, that I missed to see effect

**Comment by tsvetomir** [comment]
Indeed, the title will be positioned below the axis labels, regardless of crossing value.

An option to position the title at the bottom of the chart would be a good addition. Please, file a request for this feature on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback) if you have minute.
This will help us gauge the overall interest and prioritize.

**Comment by EricSch** [comment]
As you mentioned UserVoice, would be great to get a feedback for [my idea ](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19213267-add-a-toaster-service), what I posted in May :stuck_out_tongue_winking_eye:

And I will post my request, thank you
