### ISSUE TITLE
Decimal input problem about relation between comma and dot into NumericTextBox

### ISSUE THREAD

**Issue by stansamyn** [telerik/kendo-angular#747]
With a nl-NL culture, decimals are seperated with a comma. (no dot) 

The AngularJS version of NumericTextBox interpreted the dot of the numeric keyboard as a comma, even though it's a dot with keyboard in Belgian Period (.)

Will this also be possible in future releases of the Angular 2 NumericTextBox component?

Because now we have to force our users to switch their keyboard settings to Belgian Comma, than the component works as expected. 
But in the AngularJS version the numeric dot/comma key was interpreted as the decimal seperator used by the culture.. 

http://plnkr.co/edit/cmDoINKdWAz3yk0Yk8f0?p=preview

Thanks in advance!

**Comment by danielkaradachki** [comment]
This is not currently planned but we will consider it for future versions.

**Comment by JaapMosselman** [comment]
Created an [idea](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/31154305-numerictextbox-allow-decimal-key-numeric-keypad-in) for it. Please vote!

**Comment by JaapMosselman** [comment]
Please, can you fix this asap? It prevents us from using this component in production.
Seems to me as a simple thing.

**Comment by siyka-marinova** [comment]
This feature is currently implemented in the dev. version of the kendo-angular-inputs package: `@progress/kendo-angular-inputs@1.3.0-dev.201709060902`

**Comment by ggkrustev** [comment]
Nope, it should be out within a week or two. 

We release the package officially once we are sure that the change is correct and additionally tested.

**Comment by siyka-marinova** [comment]
Released in the official package version 1.3.0: `@progress/kendo-angular-inputs@1.3.0`
