### ISSUE TITLE
SystemJS applications: Unable to load Pako

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#748]
Version 1.2.0 of the `@progress/kendo-drawing` package adds a dependency on the [Pako](https://www.npmjs.com/package/pako) library to enable PDF compression.

Adding an npm dependency is not normally an issue and no action is necessary for projects that are based on Webpack, including projects scaffolded with the Angular CLI.

Projects based on SystemJS, including the Angular Quickstart, need [explicit configuration](https://github.com/telerik/kendo-angular-quickstart/commit/76261d470ff3bbf47a53eaabcf1afdc6ed40c579) for each npm package. Add the following configuration to your SystemJS config file:

```js
map: {
  'pako': 'npm:pako',
  ...
},
packages: {
  pako: {
      defaultExtension: 'js',
      main: './index.js'
  }
  ...
}
```

**Comment by EricSch** [comment]
Rollup complains, that  'deflate' isn't exported by pako. Do you know, if Rollup needs also explicit configuration? txs

**Comment by tsvetomir** [comment]
@EricSch I've managed to reproduce the problem and pushed a fix in the dev channel of `kendo-drawing`. Try upgrading to it to see if it makes a difference:

`npm install --save @progress/kendo-drawing@dev`

**Comment by tsvetomir** [comment]
Pushed the fix to `@progress/kendo-drawing@1.2.1` as it was broken in other scenarios as well.

**Comment by EricSch** [comment]
@tsvetomir now it is broken in general. 
Before I was able to compile it with that named export in rollup:
`                'node_modules/pako/index.js': ['deflate', 'inflate', 'constants']`
Now it doesn't help anymore: 
```
[10:33:44] Error: 'deflate' is not exported by node_modules\pako\dist\pako_deflate.js
    at error (C:\_Projects\_Git\ab\sbv\node_modules\rollup\dist\rollup.js:181:12)
```
Rollup is 0.48.2

**Comment by tsvetomir** [comment]
Try setting the path to `pako_deflate` directly, as in our [sample project](https://github.com/telerik/kendo-angular-quickstart-seed/blob/master/tools/config/project.config.ts#L43):

```js
{ 'node_modules/pako/dist/pako_deflate.js': [ 'deflate' ] }
```

**Comment by EricSch** [comment]
ok, I had some problems, rollup 0.49.1 throws an error:
```
[13:44:09] TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at Node.hasEffectsWhenMutated (C:\_Projects\_Git\abc\ab\node_modules\rollup\dist\rollup.js:6885:10)
```

after downgrading to 0.48, it did work.
