### ISSUE TITLE
 Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by yasiryc** [telerik/kendo-angular#749]
I don't get this error locally but when i push my changes for team city CI build, the build agent log this and build fails. I have removed the package-lock.json file, executed "npm i" command. It builds fine locally but when team city try to build, this error is thrown. 
`**Error: Error encountered resolving symbol values statically. Could not resolve @progress/kendo-angular-grid relative to .......app.module.ts**`
>

**Comment by tsvetomir** [comment]
It's hard to say what's wrong from the error message alone. Have you tried replicating the exact build steps locally?

Make sure to clear the npm cache as well.

**Comment by yasiryc** [comment]
Some of the files in node modules were missing. The issue is resolved now.
