### ISSUE TITLE
Grid: Inline Editing on Row Click

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#750]
http://plnkr.co/edit/pdcBacAD9MqDYfr3CYw6?p=preview

I'm using your sample [Inline Editing on Row Click](http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/) changed it by adding paging. It doesn't work on the second page. 
What are the steps to get it working?

Thank you

**Comment by rkonstantinov** [comment]
@EricSch 
As the rowIndex from the directive is relative to the current page, you will need to offset it with the current skip. Similar to the following:
```js
    public editClick(rowIndex: number): void {
        this.editHandler({
            sender: this.grid,
            rowIndex: this.grid.skip + rowIndex,
            dataItem: this.view[this.grid.skip + rowIndex]
        });
    }
```

**Comment by EricSch** [comment]
@rkonstantinov Thank you, would be great when you mentioned that (index is absolute) in the docu for the editRow method. Usually the index used in the grid are relative to the current page, like for ex SelectionEvent.

**Comment by rkonstantinov** [comment]
Thanks for the suggestion, we will add such note.
However, you should be aware that selection index as with all of the other row indexes (for grouping etc. for example) is 'absolute' (offset with the current skip).
