### ISSUE TITLE
[GRID] How to get the correct selected index with kendoGridBinding

### ISSUE THREAD

**Issue by xiaowvmware** [telerik/kendo-angular#751]
We have a selectable and sortable grid using kendoGridBinding directive. The selectionChange emits an event with the index of the select item: Object { index: 0, selected: false }

After the grid data order is changed by sorting, the selected index is the index in the sorted data not the original data.

How do we get the correct selected item or index in the original grid data?

The steps is to reproduce the problem:
- Go to http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/automatic-operations/ and open the first example in Built-In Directive as plunker

- Replace app/app.component.is with the following code

`
import { Component } from '@angular/core';
import { customers } from './customers';

@Component({
    selector: 'my-app',
    template: `
        <kendo-grid
            [kendoGridBinding]="gridData"
            [pageSize]="20"
            [pageable]="true"
            [sortable]="true"
            [scrollable]="'virtual'"
            [groupable]="true"
            [selectable]="true"
            (selectionChange)="onSelect($event)"
            [rowHeight]="50"
            [height]="510">
            <kendo-grid-column field="CompanyName" [width]="140"></kendo-grid-column>
            <kendo-grid-column field="ContactName" [width]="120"></kendo-grid-column>
            <kendo-grid-column field="City" [width]="100"></kendo-grid-column>
            <kendo-grid-column field="ContactTitle" [width]="130"></kendo-grid-column>
        </kendo-grid>
    `
})
export class AppComponent {
    private gridData: any[] = customers;
    
    onSelect(event) {
      console.log(event);
    }
}`

- Once the grid is displayed, clicked on the first row "Alfreds Futterkiste". The message in console: Object { index: 0, selected: true }
- Unselect the row and sort by company in descending order
- Click on he first row "Wolski Zajazd". The message in console: Object { index: 0, selected: true }

The index 0 is the index in the internal sorted gridData. We are not able to use the index to look up the corresponding data item in "this.gridData"

**Comment by xiaowvmware** [comment]
[app.component.ts.txt](https://github.com/telerik/kendo-angular/files/1156984/app.component.ts.txt)

Upload the sample app.component.ts in a file

**Comment by EricSch** [comment]
I'm using this.grid.data and the index to get the selected data item.

**Comment by xiaowvmware** [comment]
>> I'm using this.grid.data and the index to get the selected data item.

Thanks for your response.

I tried to get this.grid.data by the following approach:

<kendo-grid #kendoGrid

@ViewChild('kendoGrid') kendoGrid: KendoGridComponent;

this.kendoGrid.data is a GridDataResult of the current page. 

However, I still have an issue. There are 3 "grid data list" involved here:

1. My external data list: it is unsorted in the original order

2. Kendo internal data list: it is sorted but full list

3. data list of the current page: it is subset of #2 and in my case page size is 20.

My observation is:
The index returned from selectionChange event is for #2 
this.kendoGrid.data is #3.

Therefore I am still not able to get the correct data item.

**Comment by EricSch** [comment]
you can calculate the relative position with the event.index (#2). Divide it through the pagesize (index % this.kendoGrid.pageSize) and the rest is your relative position in #3

**Comment by ChrisProlls** [comment]
You have to retrieve yourself the data following the index passed in `selectionChange` with the `grid.data`.
Pay attention to the grouping functionnality : `grid.data` has no longer the same object structure.

**Comment by xiaowvmware** [comment]
It seems that adjusted index = index - state.skip

the state is the object returned from dataChange event

**Comment by Raisolution** [comment]
I am closing this issue as it is not related to the new selection API. Feel free to open a new one if you notice an unexpected behavior.
