### ISSUE TITLE
TreeList not working properly with a kendo.data.DataSource instance as its DataSource

### ISSUE THREAD

**Issue by caiolrm** [telerik/kendo-angular#753]
**Code snippet:** [http://plnkr.co/edit/ijDbLTVWvRSRylQBZxo2?p=preview](http://plnkr.co/edit/ijDbLTVWvRSRylQBZxo2?p=preview)

When I pass a kendo.data.DataSource instance to the dataSource option of a TreeList, it crashes with the following error:

`TypeError: Cannot read property 'toLowerCase' of undefined`

This happens at the calculateAggregate function inside Query.prototype. Apparently, there's an aggregate function with no name being passed to it causing the problem. If I use a object containing the properties of the kendo.data.DataSource as the TreeList dataSource, it works. The thing is, I need to use kendo.data.DataSource functions like fetch, read, etc.

Am I doing something wrong?

**## Relevant excerpt**
```javascript
var dataSourceOptions = {
    data: [{ id: 1, nome: "Mercearia", parentId: null }, { id: 12, nome: "Doces", parentId: 1 }]
};

var dataSource = new kendo.data.DataSource(dataSourceOptions);

$scope.treeListOptions = {
    //dataSource: dataSourceOptions, //this works
    dataSource: dataSource, //this doesn't work
    columns: [
        { field: "nome", title: "Nome" }
    ]
}
```

**Comment by tsvetomir** [comment]
This repository is for reporting issues in [Kendo UI for Angular](http://www.telerik.com/kendo-angular-ui/) which targets Angular 2 and later.

Issues with the Angular 1.x integration in Kendo UI for jQuery can be submitted at through the [support ticketing system](https://www.telerik.com/account/support-tickets/my-support-tickets.aspx
) or the [kendo-ui-core](https://github.com/telerik/kendo-ui-core) repository.
