### ISSUE TITLE
Cannot implement Grouping with Server side paging

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#754]
[http://plnkr.co/edit/xrXISPabBsKfuJHlRjjK?p=preview](http://plnkr.co/edit/xrXISPabBsKfuJHlRjjK?p=preview)

I've been trying to implement client-side grouping with server side paging. The plunker above is from the server side paging example where I've enabled the grouping for the grid and added the processing for the grid in the `northwind.service.ts`.

The grouping happens but the grid is not properly displaying that. Can anyone advise how I should go on form there?

**Comment by rkonstantinov** [comment]
The discrepancy in the groups display is due to not binding the `group` options of the Grid component.
```html
      <kendo-grid
          [group]="state.group"
          [groupable]="true"
          (dataStateChange)="dataStateChange($event)"
          .....
        >
       ....
      </kendo-grid>
```

**Comment by vivek201** [comment]
@rkonstantinov Thanks a lot! That was definitely the issue.
