### ISSUE TITLE
How to set specific colors for line chart

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#755]
How can I set specific colors for line chart?

Series component's `color` input is only applied to the points but `colorField` input does not work with line chart.

Here is a plnkr using `color` input:
http://plnkr.co/edit/bx4lTJLNz2ZCr7JLhqt7?p=preview

My goal is to set specific color for the whole line but not only the points.

**Comment by tsvetomir** [comment]
Thanks for reporting this issue. The workaround for the moment is to use a hashmap instead of function, [see plunkr](http://plnkr.co/edit/xxMiusy0jE7Z0EHwYlWE?p=preview):

```html
<kendo-chart-series-item *ngFor="let d of data" ... [color]="seriesColors[d.name]">
```

```ts
export class AppComponent {
  seriesColors = {
    'a' : '#0000ff',
    'b' : '#00ff00',
    'c' : '#ff0000'
  }
}
```

**Comment by tsvetomir** [comment]
We discussed this issue and came to the conclusion that the current behavior is correct. The line is considered a single entity and can only have a single color, set statically.

What happens in this case is that `marker.color` is aliased to `color` and is evaluated per-point. This can be confusing and should be addressed in the docs.

**Comment by g4b0-88** [comment]
> Thanks for reporting this issue. The workaround for the moment is to use a hashmap instead of function, [see plunkr](http://plnkr.co/edit/xxMiusy0jE7Z0EHwYlWE?p=preview):
> 
> ```
> <kendo-chart-series-item *ngFor="let d of data" ... [color]="seriesColors[d.name]">
> ```
> 
> ```ts
> export class AppComponent {
>   seriesColors = {
>     'a' : '#0000ff',
>     'b' : '#00ff00',
>     'c' : '#ff0000'
>   }
> }
> ```

Workaround works perfect.
