### ISSUE TITLE
Cannot click in the text of MultiSelect's input

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#756]
When some filter text is typed in the MultiSelect's input, the user can no longer click somewhere in the text to either put the cursor there or select the text via mouse:

[http://plnkr.co/edit/S1HBK9MCNWVSbZjUEmpB?p=preview](http://plnkr.co/edit/S1HBK9MCNWVSbZjUEmpB?p=preview)

Type "foo" and try to select the text or click between the letters.

Desired behavior - the user is able to put the cursor somewhere in the typed text or select the text via click-dragging with the mouse like in the jQuery version:

[http://demos.telerik.com/kendo-ui/multiselect/index](http://demos.telerik.com/kendo-ui/multiselect/index)

**Comment by ipeshev** [comment]
Shipped with: v1.6.1
