### ISSUE TITLE
TabStripTab: Expression has changed after it was checked

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#757]
Hey guys, 
we need to know if a certain tab is active or not. I see that the `TabStripTabComponent` has public `active` property (that is not documented) and it actually does exactly what we need. But using it inside `*ngIf` for tab that is selected by default leads to `Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.`

**Plunker**  
http://plnkr.co/edit/5yIAfEvjCmidFicdo5zZ?p=preview
*Check the console*

**Comment by rusev** [comment]
The reason for the exception is that we internally update the `active` state of the tab on `ngAfterViewInit` event hook. However `active` is not considered a public API and is not part of the official documentation for the [TabScripTab component](https://www.telerik.com/kendo-angular-ui/components/layout/api/TabStripTabComponent/#toc-tabstriptabcomponent).

That said you should be able to use [selected](https://www.telerik.com/kendo-angular-ui/components/layout/api/TabStripTabComponent/#toc-selected) instead. Updated example - https://plnkr.co/edit/WdSG3NxAHx6p4S4fGbAD?p=preview
