### ISSUE TITLE
[Grid] PDF export with wrong encoding

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#758]
In our project we use grid for PDF export. I strictly followed [your example](http://www.telerik.com/kendo-angular-ui/components/grid/pdf-export/), but we have an encoding problem. Some accents are replace by the empty symbol.

Data displayed throught the grid component :
![image](https://user-images.githubusercontent.com/1511666/28418642-afcbc5ca-6d5c-11e7-8ad2-ac54b795bc21.png)
And here the data exported into the PDF file :
![image](https://user-images.githubusercontent.com/1511666/28418652-beb64c40-6d5c-11e7-99f4-885056f5da6d.png)

```
@progress/kendo-angular-grid: 1.1.2
@progress/kendo-drawing: 1.1.1
```

If I try to put accent into the footer, I've got the same result.
Any clue ?

**Comment by tsvetomir** [comment]
Please make sure that you're embedding fonts with Unicode support. See [Custom Fonts](http://www.telerik.com/kendo-angular-ui/components/drawing/pdf-output/#toc-custom-fonts).

**Comment by ChrisProlls** [comment]
I don't embed any fonts in our application. So you say that standard PDF fonts don't support Unicode ?

**Comment by ChrisProlls** [comment]
Problem solved : I haven't noticed that we used a custom font for our grid. I needed to use CSS `@font-face` :

```
@font-face {
  font-family: "open sans";
  src: url("/assets/css/fonts/Open-Sans/open-sans.ttf") format("truetype");
}
@font-face {
  font-family: "open sans";
  font-weight: bold;
  src: url("/assets/css/fonts/Open-Sans/open-sans.bold.ttf") format("truetype");
}
@font-face {
  font-family: "open sans";
  font-style: italic;
  src: url("/assets/css/fonts/Open-Sans/open-sans.italic.ttf") format("truetype");
}
@font-face {
  font-family: "open sans";
  font-weight: bold;
  font-style: italic;
  src: url("/assets/css/fonts/Open-Sans/open-sans.bold-italic.ttf") format("truetype");
}
```

I'm closing this issue, thanks for your help !
