### ISSUE TITLE
Grid - prevent column growth when all columns have an explicit width

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-angular#760]
I have a grid with a variable number of columns depending on settings.  I have a fixed width for each column type.  For example column A is always 200px, B is always 300px C through G are all 50px and H is 100px.  However any combination of these columns could be displayed at any given time based on various factors, so the width of the grid could be anywhere from 50px to whatever the max there would be.  Is there an easy way to make the grid actually respect the column width settings and not grow to fill all possible width?

I know I can wrap it in a div and put an explicit width on the div, but then I have to write of logic to figure out what that ever changing width should be, and then when the users decide they want a new column added to the potential display or widths changed etc. someone has to remember to go update the code for determining the wrapper width.

I'm hoping there's some grid setting or simple CSS I'm missing so I don't have to do that.

**Comment by tsvetomir** [comment]
The grid will behave much like a regular table in this case, expanding the columns to fill the available space. Any possible solution would involve the grid setting it's own width which is a big no-no for a component.

Your workaround is valid and can likely be automated. For example, the columns definitions can be stored in an array. This way you'd be able to create them using *ngFor and to iterate them to compute their actual width.

P.S. Pardon the glacial response time.

**Comment by ssarkisy** [comment]
One of possible solutions is to add empty column with no width defined. Then this column will eat up all the extra space, or will be collapsed to 0 width if there is no space left.
