### ISSUE TITLE
Gauge components

### ISSUE THREAD

**Issue by ChrisProlls** [telerik/kendo-angular#761]
Have you any plans for Gauge components (both radial + vertical / horizontal) ?

**Comment by tsvetomir** [comment]
Not at the moment, but we can re-evaluate if there's enough interest. Please, [cast your vote](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18944239-gauge-components) on our UserVoice portal if you have a minute.

**Comment by tsvetomir** [comment]
Porting the Gauges is scheduled for the R1'18 release in January. Thank you for your patience.

**Comment by tsvetomir** [comment]
Shipped at https://www.telerik.com/kendo-angular-ui/components/gauges/
