### ISSUE TITLE
Kendo npm install error

### ISSUE THREAD

**Issue by abhissha** [telerik/kendo-angular#762]
We are getting below issue trying to install kendo packages related to input(1.0.5), charts(1.2.0) and kendo theme bootstrap theme(2.6.0). It's failing trying to find dependencies any help would be appreciated.

![1](https://user-images.githubusercontent.com/20051265/28477211-fa08a184-6e20-11e7-9f7a-e2e2af6990ee.png)
![2](https://user-images.githubusercontent.com/20051265/28477212-fa40b7b8-6e20-11e7-9d78-74e1a5a53ab8.png)
![3](https://user-images.githubusercontent.com/20051265/28477214-fb85b330-6e20-11e7-9b88-649256e85090.png)

**Comment by tsvetomir** [comment]
Please reset your npm registry configuration to use the default npmjs.org registry. See #712 for detailed instructions.

**Comment by abhissha** [comment]
Thanks, had to remove .npmrc file from %USERPROFILE%\.npmrc.
