### ISSUE TITLE
Kendo grid not supporting odata v4 

### ISSUE THREAD

**Issue by afsalcodehack** [telerik/kendo-angular#763]
I did try server side filtering using angular 2 kendo grid with odata v4 but it showing 'contains' keyword not supporting. new version using 'substringof' instead of 'contains' how can i solve this issue

**Comment by tsvetomir** [comment]
The OData V4 specification lists [contains](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html#_Toc444868695) as an operator. The `substringof` is used in OData V2 and V3.

This is [a demo](http://plnkr.co/edit/RSwOdqpkPwU9POEh30BD?p=preview) of the Grid bound to OData V4 service with filtering enabled. You can see the generated requests in the Network tab.

**Comment by windians** [comment]
The demo is not opening. @tsvetomir

**Comment by tsvetomir** [comment]
Thanks, I've updated the SystemJS configuration and updated the link above.
