### ISSUE TITLE
[DateInput]: first char typed in 'yyyy' section is ignored

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#764]
### Description
The DateInput component will set '0000' value ignoring the typed char when `yyyy/MM/dd` format is used.

#### Reproduction
1. Open this demo http://plnkr.co/edit/AE0sWTOcUsaOHreB9CBY?p=preview
```
<kendo-dateinput [(value)]="value" [format]="'yyyy/MM/dd'"></kendo-dateinput>
```
2. Focus DateInput
3. Type '1'
4. The result is '0000', which is incorrect.
*The observation shows that the value is decremented by 1 in this case*

Initially reported in TicketID: 1120424

**Comment by spaceman101** [comment]
commenting line 181 of te file @progress\kendo-angular-dateinputs\dist\es\dateinput\dateinput.component.js fixed it for me. But that is just a patch I guess.

**Comment by ggkrustev** [comment]
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.
