### ISSUE TITLE
[MULTISELECT] Missing feature to clear the search input of a multiselect

### ISSUE THREAD

**Issue by VeldMuijz** [telerik/kendo-angular#765]
There is a reset function to reset the multiselect values but there is no function that also clears the search input.

I was missing this function in a situation where I needed to clear the search text a user had entered.

Will this be added?

**Comment by tapopov** [comment]
A button for clearing the filter alone is not included in the component's initial design. 
There are two buttons - one for removing either an individual selected item and one for removing everything, including the current filter criteria.
![image](https://user-images.githubusercontent.com/5184468/31335923-520891c6-acfd-11e7-98ca-28cf8a481808.png)
![image](https://user-images.githubusercontent.com/5184468/31336204-77be23d0-acfe-11e7-9798-6153d8dafe98.png)
Adding the described feature is not planned either, as we believe it would make the UI too crowded.
