### ISSUE TITLE
input field format time format

### ISSUE THREAD

**Issue by premiumwd** [telerik/kendo-angular#767]
Hi,

How do format an input field to be in hour format?

**Comment by ggkrustev** [comment]
The DateInput/DatePicker components support `format` property binding, which enables you to format the input value. Check the documentation for more details.
- http://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/#toc-formats
All formats defined in the `kendo-intl` repo are available here too.

Please note that the Github repo is used only for bug reports or feature requests. Should you have any general how to questions, please use our ticketing system. It is available if you have downloaded a trial or purchased a license.
