### ISSUE TITLE
input format temperature format

### ISSUE THREAD

**Issue by premiumwd** [telerik/kendo-angular#768]
Hi,

How do format an input field to be in temperature (C) format?

**Comment by ggkrustev** [comment]
The only component that come to my mind that could be useful in this case is the [MaskedTextBox component](http://www.telerik.com/kendo-angular-ui/components/inputs/maskedtextbox/). Only it accepts custom literals, e.g. (C), and can be forced to accepts only numbers.
The NumericTextBox wouldn't be suitable in this case.

Please note that the Github repo is used only for bug reports or feature requests. Should you have any general how to questions, please use our ticketing system. It is available if you have downloaded a trial or purchased a license.
