### ISSUE TITLE
value binding kendo-dropdownlist

### ISSUE THREAD

**Issue by premiumwd** [telerik/kendo-angular#770]
can you please let me know how to value bind using ngmodel for dropdownlist. thanks.

**Comment by ggkrustev** [comment]
@premiumwd, check the `Template-driven form` demo, which shows how to use `ngModel` directive.
- http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/forms/#toc-template-driven-forms

Please note that the Github repo is used **only** for bug reports or feature requests. Should you have any general *how to* questions, please use our ticketing system. It is available if you have downloaded a trial or purchased a license.
