### ISSUE TITLE
Filter row looks just awful

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#772]
Since sometime the filter row of the grid looks pretty bad and wastes so much space.

Example:
![image](https://user-images.githubusercontent.com/323925/28565238-47d7b326-7134-11e7-9d66-a30e263ff4c9.png)

I don't really understand why there should be empty space at all times (the clear button)  - "Client" and "Net" are columns with digits and if i want to be able to actually show the filter i have to at least double the column width but we really do not need such wide columns.

Look at the "Nights" column it is a simple numeric filter with disabled operators and huge blank space.

This reserved space for the clear button is really preventing either filtering or the possibility to optimize the width of the grid columns and avoid horizontal scrolling.

Can't you guys incorporate the clear button inside the operators dropdown and when there is no dropdown show it when we need it?

**Comment by caseylutz** [comment]
I want to second an emphasis on reducing the "visual impact" of the filter row. It's actually impeding general ability to get as many columns on the screen as we otherwise should and (partially due to Angular itself) is very, very difficult to style around without writing one's own custom filters.

**Comment by moxival** [comment]
I see that there is "question" tag and i see no answer for the last 2 months :)

**Comment by yordanov** [comment]
@moxival Excuses for the delayed response - the empty space is a front-end implementation bug - there should be no such non-functional whitespaces in the filter row. Reference - https://github.com/telerik/kendo-ux/blob/master/themes/default/grid.psd .

We are aware of the issue and addressing it (fix coming with one of the following releases) together with the [filter menu functionality requested on uservoice](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/19115545-grid-filter-next-to-column-header-like-normal-kend) (preview coming by end of 2017, expected to be officially available with R1 2018). That said, for smaller screen sizes, as in the scenario shown above, the header filter menu is the more usable and recommended option.

**Comment by moxival** [comment]
Thanks for the comment, i casted my vote on uservoice. You can close the issue if you want to.
