### ISSUE TITLE
Multiselect defined width and height

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#774]
Currently the multiselect can not be used in constraint containers where width and height of the components need to stay constant. The Multiselect component grows vertically when the width is exhausted which restricts the usefulness of it.

Would you implement something like `maxSelectedLabels` e.g.: https://www.primefaces.org/primeng/#/multiselect 

If there is a way to actually control the height/width of the component can you please give me a hint :)

**Comment by moxival** [comment]
Another nice implementation is here: http://ng-lightning.github.io/ng-lightning/#/components    (search for picklist)

**Comment by moxival** [comment]
Is this issue ever gonna get some love and attention?

**Comment by tsvetomir** [comment]
It's on our plans for the January release, we'll update the [UserVoice item](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/17762557-dropdown-with-multiselect-ability) with the status.

Please cast your vote for it so you can stay notified. Closing this issue to avoid duplication.
