### ISSUE TITLE
Drop Down positions do not work with CSS zoom property

### ISSUE THREAD

**Issue by caseylutz** [telerik/kendo-angular#777]
* Bug report 

## Current behavior
Add the zoom CSS property to any parent element. Utilize a drop down control (in my case, the Filters in a Grid) or date picker. The drop downs will generally not position themselves accurately.

## Expected behavior
The drop downs should appear relative to the same position they would have while the zoom was 1.0.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/i8CimIsxnFnECqo1HO96

## What is the motivation / use case for changing the behavior?
We have requirements to put a lot of data on-screen at many different display resolutions. In many cases we have no choice but to make things smaller to comfortably fit everything on-screen. In many cases, I want to use media queries to adjust the presentation as needed. Zoom is just another tool in the toolbox.

## Environment

Package versions:

```
+-- @angular/animations@4.3.1
+-- UNMET PEER DEPENDENCY @angular/cdk@2.0.0-beta.8
+-- @angular/cli@1.2.2
+-- @angular/common@4.3.1
+-- @angular/compiler@4.3.1
+-- @angular/compiler-cli@4.3.1
+-- @angular/core@4.3.1
+-- @angular/flex-layout@2.0.0-beta.8
+-- @angular/forms@4.3.1
+-- @angular/http@4.3.1
+-- @angular/language-service@4.3.1
+-- @angular/material@2.0.0-beta.8
+-- @angular/platform-browser@4.3.1
+-- @angular/platform-browser-dynamic@4.3.1
+-- @angular/router@4.3.1
+-- @ngtools/json-schema@1.1.0
+-- @progress/kendo-angular-buttons@1.0.5
+-- @progress/kendo-angular-charts@1.2.2
+-- @progress/kendo-angular-dateinputs@1.0.5
+-- @progress/kendo-angular-dialog@1.0.4
+-- @progress/kendo-angular-dropdowns@1.1.2
+-- @progress/kendo-angular-excel-export@1.0.3
+-- @progress/kendo-angular-grid@1.2.3
+-- @progress/kendo-angular-inputs@1.0.7
+-- @progress/kendo-angular-intl@1.2.1
+-- @progress/kendo-angular-l10n@1.0.2
+-- @progress/kendo-angular-label@1.0.3
+-- @progress/kendo-angular-layout@1.0.5
+-- @progress/kendo-angular-popup@1.1.1
+-- @progress/kendo-angular-scrollview@1.0.3
+-- @progress/kendo-angular-sortable@1.0.2
+-- @progress/kendo-angular-upload@1.1.1
+-- @progress/kendo-data-query@1.0.5
+-- @progress/kendo-drawing@1.1.2
+-- @progress/kendo-theme-default@2.38.2
+-- @types/concaveman@1.1.2
+-- @types/faker@4.1.0
+-- @types/jasmine@2.5.38
+-- @types/jquery@2.0.48
+-- @types/leaflet@1.0.66
+-- @types/leaflet.markercluster@1.0.0
+-- @types/lodash@4.14.70
+-- @types/moment@2.13.0
+-- @types/node@6.0.84
+-- @webcomponents/custom-elements@1.0.0
+-- bootstrap@4.0.0-alpha.6
+-- codelyzer@3.1.2
+-- concaveman@1.1.1
+-- core-js@2.4.1
+-- faker@4.1.0
+-- font-awesome@4.7.0
+-- hammerjs@2.0.8
+-- immutable@3.8.1
+-- istanbul-instrumenter-loader@2.0.0
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- jquery@3.2.1
+-- json-schema@0.2.3
+-- karma@1.7.0
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- leaflet@1.1.0
+-- leaflet-editable@1.0.0
+-- leaflet.markercluster@1.0.6
+-- lodash@4.17.4
+-- mutationobserver-shim@0.3.2
+-- ng-http-interceptor@3.1.2
+-- parse-json@2.2.0
+-- protractor@5.1.2
+-- rxjs@5.4.2
+-- strip-bom@3.0.0
+-- ts-node@3.0.6
+-- tslint@5.3.2
+-- typescript@2.3.4
+-- UNMET PEER DEPENDENCY webpack@3.3.0
`-- zone.js@0.8.14
```

Browser:
- Chrome (desktop) version 60
- Edge version 25

System:
- TypeScript version: 2.4.1
- Node version: 8.1.3
- Platform:  Windows / Mac

**Comment by tsvetomir** [comment]
Our previous attempts to support browser zoom have failed miserably. We'll investigate, but I don't have high hopes that we'll be able to support it properly. 

The zoom property is [non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) and is implemented differently across browsers.  It's standard counter-part: `translate: scale()` causes similar problems and this is something we'll investigate.

**Comment by ggkrustev** [comment]
We've made some attempts to improve the popup positioning in a zoomed (zoom: >1) page. It seems to work better now ([demo](http://plnkr.co/edit/KpLYG3VyFNH43SfctVMZ?p=preview)). 

We haven't researched the opposite case (zoom: <1), but for now it won't be supported scenario. Will update the thread once we have more details to share.

**Comment by ggkrustev** [comment]
We won't be supporting `zoom: <1` scenario for the time being. Please post your enhancement request in our UserVoice portal. Thus more people could cast their vote for it.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

**Comment by tsvetomir** [comment]
Reopening this issue to discuss possible workarounds. /cc @danielkaradachki 

One possible workaround is to allow the developer to declare the scale factor, e.g. by using an injection token:

```ts
import { SCALE } from '@progress/kendo-angular-popup`;

@NgModule({
   providers: [{ provide: SCALE, useValue: 0.75 }],
})
export class AppModule { }
```

**Comment by tsvetomir** [comment]
Preliminary support added in the [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/), see [Support for Document Scale](https://www.telerik.com/kendo-angular-ui-develop/components/popup/document-scale/).
