### ISSUE TITLE
[SplitButton] disable only a single popup item but not whole split button

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular#778]
## I'm submitting a...

* Suggestion for improvement
* Documentation issue or request

## Current behavior

Can't disable a single popup item in similar split buttons repeated with *ngFor or kendo grid 

## Expected behavior

Disable a single popup item in split button.

## What is the motivation / use case for changing the behavior?

I want to set split buttons on each row of kendo grid but available actions differ a little.

**Comment by ilianiv** [comment]
![image](https://user-images.githubusercontent.com/3925630/28773566-c4be1188-75f2-11e7-8541-0dde3e7390ca.png)

**Comment by danielkaradachki** [comment]
Sorry, seems we missed this issue. Disabling single items is possible by setting the items disabled field:
https://plnkr.co/edit/wOOpBrDEOEEOwLSb1ju0?p=preview

Seems that this is not explained very well in the documentation. Will keep the issue opened until the documentation is updated.

**Comment by danielkaradachki** [comment]
The documentation has finally been updated:
https://www.telerik.com/kendo-angular-ui-develop/components/buttons/splitbutton/data-binding/
