### ISSUE TITLE
ComboBoxComponent datasource number[] doesn't display 0

### ISSUE THREAD

**Issue by hpknight** [telerik/kendo-angular#780]
If ComboBoxComponent is bound to an array of numbers (ie: [-1,0,1,2,3]), once the drop down is clicked on in the UI, 0 doesn't show. It shows a blank space where the 0 should be displayed. Clicking on the blank space shows 0 in the input box, which is good, but in the drop down, it doesn't show.

[View Plunkr](http://plnkr.co/edit/4PAxZqiQS51mpgDN6ALZ?p=preview)

Thoughts?

**Comment by tapopov** [comment]
Hello @hpknight 

Thanks for bringing this to our attention. Indeed, it looks like a bug in the default item template, which we will take care of as soon as possible. Meanwhile you can use a custom item template as a workaround. Here's an [example](http://plnkr.co/edit/uC9gQo1Z3UihIzq7wi3W?p=preview).

**Comment by hpknight** [comment]
@tapopov Thank you for your response. I will go ahead and use the workaround until a solution is in place.

**Comment by ipeshev** [comment]
The problem is still visible on [this demo](http://plnkr.co/edit/0cZpEDMdeb4QxNmjtyku?p=preview)

**Comment by valchev** [comment]
@ipeshev it looks OK on my end, the zero number is displayed in the list.
Here is a quick [screen cast](https://screencast.com/t/RTi8QlQgi), am I missing something?
