### ISSUE TITLE
[Multiselect] When you prevent the close and have a lot of items, the scroll goes back to beginning

### ISSUE THREAD

**Issue by GersonDias** [telerik/kendo-angular#782]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When you have a lot of values in your multi select component and prevent the closing behavior while you selecting the items, the component's scroll bar returns to the beginning after each selection.
http://plnkr.co/edit/hGicYC0Xi32nJIQqWryh?p=preview

## Expected behavior
The component should not return to the beginning after the user click.
* I've made a hack using jquery, check out in:
http://plnkr.co/edit/gk1JM6xXcNKGvQN6Zmx1?p=preview

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/hGicYC0Xi32nJIQqWryh?p=preview

## What is the motivation/use case for changing the behavior?
It's terrible for UX the returning to the beginning of list

## Environment

Package versions:

```
+-- @angular/animations@4.2.5
+-- @angular/cli@1.0.1
+-- @angular/common@4.2.5
+-- @angular/compiler@4.2.5
+-- @angular/compiler-cli@4.2.5
+-- @angular/core@4.2.5
+-- @angular/forms@4.2.5
+-- @angular/http@4.2.5
+-- @angular/platform-browser@4.2.5
+-- @angular/platform-browser-dynamic@4.2.5
+-- @angular/platform-server@4.2.5
+-- @angular/router@4.2.5
+-- @ngrx/core@1.2.0
+-- @ngrx/effects@2.0.3
+-- @ngrx/router-store@1.2.6
+-- @ngrx/store@2.2.2
+-- @ngrx/store-devtools@3.2.4
+-- @progress/kendo-angular-buttons@1.0.5
+-- @progress/kendo-angular-dateinputs@1.0.5
+-- @progress/kendo-angular-dialog@1.0.4
+-- @progress/kendo-angular-dropdowns@1.1.1
+-- @progress/kendo-angular-excel-export@1.0.3
+-- @progress/kendo-angular-grid@1.2.1
+-- @progress/kendo-angular-inputs@1.0.6
+-- @progress/kendo-angular-intl@1.2.1
+-- @progress/kendo-angular-l10n@1.0.2
+-- @progress/kendo-angular-layout@1.0.5
+-- @progress/kendo-angular-popup@1.1.1
+-- @progress/kendo-angular-upload@1.1.1
+-- @progress/kendo-data-query@1.0.5
+-- @progress/kendo-date-math@1.0.3
+-- @progress/kendo-drawing@1.1.1
+-- @progress/kendo-file-saver@1.0.2
+-- @progress/kendo-ooxml@1.0.1
+-- @progress/kendo-popup-common@1.0.1
+-- @progress/kendo-theme-default@2.38.0
+-- @telerik/kendo-dropdowns-common@1.0.0
+-- @telerik/kendo-intl@1.2.0
+-- @types/jasmine@2.5.47
+-- @types/jquery@2.0.48
+-- @types/node@7.0.33
+-- bootstrap-sass@3.3.7
+-- codelyzer@3.1.1
```

Browser:
- Chrome (desktop) version 60
- Edge version 41

System:
- TypeScript version: 2.4.2
- Node version: 6.10 / 5.3.0
- Platform:  Windows

**Comment by GersonDias** [comment]
I've made a hack using Jquery http://plnkr.co/edit/gk1JM6xXcNKGvQN6Zmx1?p=preview. But it's ugly and the UX still not so good. One question that pop-ups in my head are why I unselect the item, the scroll doesn't go back to the beginning?

**Comment by valchev** [comment]
Fixed in the latest dev version.

**NOTE** The example provided in the initial description is incorrect as the data does not contain unique values. Here is an updated version of the Plunkr that should be used for testing:

http://plnkr.co/edit/6d61UQUGjrNk0NbvBNYV?p=preview

**Comment by ipeshev** [comment]
Shipped , available in latest major verions
