### ISSUE TITLE
Tab style binding triggers change detection

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#784]
## I'm submitting a...
* Bug report (on behalf of customer, ref #1122378)

## Current behavior
When using kendo-tabstrip any action outside of kendo-tabstrip causes refresh of tabstrip tab class.

## Expected behavior
The tab class should not be refreshed on external actions.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/5HZzyHKNGH6oiiIQQInj?p=preview

Clicking on the button which is above kendo-tabstrip is causing refresh of every class on every `<li role="tab" />`

## What is the motivation / use case for changing the behavior?
In large application every action / click (even in a different component or module) is going to cause a refresh of every tabstrip-tab class. With many tabstrip components on the page this could cause poor performance of a site.

## Environment
Any

**Comment by Raisolution** [comment]
Issue is fixed in the latest dev release `v1.0.8-dev.201710091141`
