### ISSUE TITLE
[MultiSelect] Search bar unexpectedly wraps on new line

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#785]
## I'm submitting a...

* Bug report 

## Current behavior

![multiselect-input-glitch](https://user-images.githubusercontent.com/90405/28708938-c08bca10-7386-11e7-9287-7b923f5a63f0.gif)

When the input is cleared, the caret is moved to a new line.

## Expected behavior

Cleaning out the input field should not move the caret to a new line, if there is enough space available on the previous one.

## Minimal reproduction of the problem with instructions

Can be reproduced in [this plunker](http://plnkr.co/edit/8N195XRHa7IqWCa6lSIg?p=preview)

## What is the motivation / use case for changing the behavior?

The MultiSelect won't wrap if there is no need, which creates a better UX.

**Comment by ipeshev** [comment]
Fixes in v1.2.5-dev.201711161412
