### ISSUE TITLE
stockchart ignores max category axis value

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-angular#792]
## I'm submitting a...

* Bug report 

## Current behavior
stockchart cuts off display based on data points regardless of max setting on category axis

## Minimal reproduction of the problem with instructions
In plunker below the standard chart shows the expected range when you explicitly set the max, but the stockchart does not.
[plunker with problem](http://plnkr.co/edit/6MAFhOpppqlZB0F819zU?p=preview)

**Comment by tsvetomir** [comment]
The main chart axis will always be locked to the navigator selected range. What you can do instead is to set the maximum of the navigator's category axis, [see plunkr](http://plnkr.co/edit/XygluQrzMeJ3cmRVbsvp?p=preview):

```html
<kendo-chart-navigator [categoryAxis]="{ max: max }">
```

**Comment by ncrawlins** [comment]
ah thanks, missed that.  Works now.
