### ISSUE TITLE
PDFOptions not exported from '@progress/kendo-drawing'

### ISSUE THREAD

**Issue by niklas-dahl** [telerik/kendo-angular#795]
## I'm submitting a...

* Bug report 

## Current behavior

You are not able to import PDFOptions from `@progress/kendo-drawing`.

`import { PDFOptions } from '@progress/kendo-drawing';`
Module '"c:/Users/..../node_modules/@progress/kendo-drawing/main"' has no exported member 'PDFOptions'.

The only way to import PDFOptions seems to be the following:
`{ PDFOptions } from '@progress/kendo-drawing/dist/es/pdf';`

## Expected behavior

The first approach should work.

## Environment
angular-cli project
Package versions:

```
+-- @angular/animations@4.3.1
+-- @angular/cli@1.2.4
+-- @angular/common@4.3.1
+-- @angular/compiler@4.3.1
+-- @angular/compiler-cli@4.3.1
+-- @angular/core@4.3.1
+-- @angular/forms@4.3.1
+-- @angular/http@4.3.1
+-- @angular/platform-browser@4.3.1
+-- @angular/platform-browser-dynamic@4.3.1
+-- @angular/router@4.3.1
+-- @angularclass/hmr@2.1.3
+-- @ngrx/effects@4.0.1
+-- @ngrx/router-store@4.0.0
+-- UNMET PEER DEPENDENCY @ngrx/store@4.0.0
+-- @ngrx/store-devtools@4.0.0
+-- @progress/kendo-angular-buttons@1.0.5
+-- @progress/kendo-angular-charts@1.2.2
+-- @progress/kendo-angular-dateinputs@1.0.5
+-- @progress/kendo-angular-dialog@1.1.0 extraneous
+-- @progress/kendo-angular-dropdowns@1.1.2
+-- @progress/kendo-angular-excel-export@1.0.3
+-- @progress/kendo-angular-grid@1.2.3
+-- @progress/kendo-angular-inputs@1.0.7
+-- @progress/kendo-angular-intl@1.2.1
+-- @progress/kendo-angular-l10n@1.0.2
+-- @progress/kendo-angular-layout@1.0.5
+-- @progress/kendo-data-query@1.0.5
+-- @progress/kendo-drawing@1.1.2
+-- @progress/kendo-theme-default@2.38.2
+-- @telerik/kendo-intl@1.2.0-dev.201706120800 extraneous
+-- @types/node@6.0.85
+-- bootstrap@3.3.7
+-- codelyzer@2.0.1
+-- core-js@2.4.1
+-- d3@4.10.0
+-- font-awesome@4.7.0
+-- hammerjs@2.0.8
+-- lodash@4.17.4
+-- ngrx-store-freeze@0.1.9
+-- reselect@3.0.1
+-- rxjs@5.4.2
+-- socket.io-client@2.0.3
+-- ts-node@2.0.0
+-- tslint@4.4.2
+-- typescript@2.4.0
`-- zone.js@0.8.14
```

System:
- TypeScript version: 2.4.2 
- Node version: v8.2.1 
- Platform:  Win7

**Comment by EricSch** [comment]
Add 
`import { pdf } from '@progress/kendo-drawing';`

and then use
`pdf.PDFOptions`

This did work for me.

**Comment by niklas-dahl** [comment]
@EricSch this works, thanks.

Is this the intended behaviour?

**Comment by EricSch** [comment]
I think so. One of different possibilities. :smirk:

**Comment by tsvetomir** [comment]
The "official" one is `import { PDFOptions } from '@progress/kendo-drawing/pdf`. In any case, the class must be imported from the [`pdf` sub-module](http://www.telerik.com/kendo-angular-ui/components/drawing/api/#toc-progresskendo-drawingpdf), see [demo](http://www.telerik.com/kendo-angular-ui/components/drawing/pdf-output/).

**Comment by EricSch** [comment]
I have to do like that (`import { pdf } from '@progress/kendo-drawing';`), because all the Kendo stuff is re-exported from one of our own module.
