### ISSUE TITLE
[DropDowns] Value is not selected after updating items

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#796]
## I'm submitting a...

* Bug report 

Reported in 1123431.

## Current behavior

After updating the items binding, the ComboBox / DropDownList do not select the value specified by `ngModel`.

## Expected behavior

The value should be selected.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/hcQUfHUsJtJ6kJwUxktX?p=preview

Click the button to add an item to the items collection. The ComboBox is not updated to show the item, even though it is in the list of values. The HTML select is updated.

The same behavior occurs with the DropDownList.

## Workaround

Trigger change detection on the model after updating the items list. See [this plunker](http://plnkr.co/edit/1m2JM5r7FrJ4iIajWlGP?p=preview).

**Comment by ipeshev** [comment]
Fixed in v1.2.3-dev.201711071404

**Comment by tsvetomir** [comment]
Shipped in v1.1.1

**Comment by ipeshev** [comment]
Shipped with v1.3.0
