### ISSUE TITLE
Inputs in Grid newly added row lose focus during typing when there are locked columns in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#797]
## I'm submitting a...

* Bug report 

## Current behavior

Grid editors are losing focus during typing when a new row is added to the Grid in IE and there is a locked column. Not observed in other browsers, or in IE when there are no locked columns, or an existing row is edited instead of a new one added.

## Expected behavior
Grid editors work normally as in all other browsers and scenarios, listed above.

## Minimal reproduction of the problem with instructions
[http://plnkr.co/edit/oLdEb97yfKbE1jFfPOT8?p=preview](http://plnkr.co/edit/oLdEb97yfKbE1jFfPOT8?p=preview)

## Environment

Browser:
- IE version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ipeshev** [comment]
Currently focus is lost right after opening editor
