### ISSUE TITLE
Rtl With Aot Build 

### ISSUE THREAD

**Issue by kokodda** [telerik/kendo-angular#801]
I try using Rtl variable  to change languages direction if  Rtl  is always false  with aot building 
i don't know what 's the problem 
snapshot of my code 

var isRtl = document.getElementsByTagName("html")[0].getAttribute("dir") == 'rtl';
var locale = document.getElementsByTagName("html")[0].getAttribute("lang") == "ar" ?"ar-OM":"en";

 providers: [
        { provide: RTL, useValue: isRtl },
        { provide: LOCALE_ID, useValue: locale },
        DialogService, ErrorLogService, AppConfig, AuthGuard, SharedService,
        AuthService, TranslationLoaderService,
        LoggerService, { provide: ErrorHandler, useClass: MyErrorHandler },
        { provide: APP_INITIALIZER, useFactory: initFactory, deps: [AppConfig], multi: true }

    ],

**Comment by tsvetomir** [comment]
What you see is expected. Providers configured with `useValue` will be resolved statically.

You need to use a [factory provider](https://angular.io/guide/dependency-injection#factory-providers) for dynamic values.
