### ISSUE TITLE
DropDown into Grid Detail Row -> Wrong align on scroll

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#802]
Just see: http://plnkr.co/edit/A0YQQVi5VS5v4Ol1faOw?p=preview

How to reproduce:

1. Open detail of a single row clicking on `+` symbol
2. Click on drop-down just to show kendo popup with tshirt sizes
3. Scroll grid to see wrong alignment

**Comment by valchev** [comment]
Hi @meriturva 

Thank you for bringing this to our attention. We will investigate further the scenario and provide fix as soon as possible.

**Comment by siyka-marinova** [comment]
Fix for this issue is now available in the latest official package: `@progress/kendo-angular-popup@1.2.1`

**Comment by meriturva** [comment]
Ok issue seems to be fixed. Just a question: is it possible to close dropdown when user scroll page? As default select/option behaviour: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_option_selected

**Comment by ggkrustev** [comment]
The Popup component, used in the DropDowns package, is designed to reposition on scroll. If the anchor is outside of the viewport, it will trigger [anchorviewportleave](http://www.telerik.com/kendo-angular-ui/components/popup/api/PopupComponent/#toc-anchorviewportleave) event, which dropdowns will use to close the component. *This behavior cannot be modified nor altered*.

**Comment by meriturva** [comment]
Mainly problem is that reposition step is quite slow compared into a grid so i guess have a way to close dropdown on scroll could be cool. Anyway thanks.
