### ISSUE TITLE
Grid - wrong date time sent as filter expression

### ISSUE THREAD

**Issue by bobo-kovacevic** [telerik/kendo-angular#805]
When filtering grid by a date column. Wrong filter expression is built. To the date/time entered in a filter, query string adds Z at the end of date/time string which denotes UTC time, but time is not converted to UTC.
I believe proper behavior should be to convert date/time from filter in UTC and.

Please see Plunker sample project for details 
http://plnkr.co/edit/aRe2XlSrG2gtmpvkAKPz?p=preview

**Comment by rkonstantinov** [comment]
Hey @bobo-kovacevic,
Sorry for the late reply. The current implementation of the `toODataString` treats the dates as  if they are already in UTC.

Please, check the following modified plunker, which demonstrate how the desired result could be achieved. http://plnkr.co/edit/npJszDjhtN5OYR8GBZku?p=preview

**Comment by bobingham** [comment]
Are you kidding me?  And this is closed.  So every time I want to use a date filter in my grid i have to do this:
```
<kendo-grid-column field="DateTime" filter="date" format="{0:F}">
          <ng-template kendoGridCellTemplate let-dataItem>
              <!--UTC date times converted to local time.-->
              {{dataItem.DateTime | date:'medium'}}
          </ng-template>
        </kendo-grid-column>
```
and then this:
```
    public getQuery(state: any): string {
      
      flatten(state.filter).forEach(x => {
        if (x.value && x.value.getTime) {
          x.value = toUTC(x.value)
        }
      });
      
      return `${toODataString(state)}&$count=true`;
    }
```
As well as converting in my server _get_ statement?

**Comment by jkendl** [comment]
In the meanwhile it is possible to configure Kendo to transform the date into UTC by using a parameter:

`toOdataString(state, { utcDates: true })`

See: https://www.telerik.com/kendo-angular-ui/components/data-query/api/toODataString/
and: https://www.telerik.com/kendo-angular-ui/components/data-query/api/ODataSettings/
