### ISSUE TITLE
[Drawing]: Overlapping elements

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#806]
* Bug report

## Current behavior
I'm exporting a chart with a title. When I add a title as text at the top of the chart, make a Group with the two elements, the chart is rendered at the top left corner and the title is overwritten. 

## Expected behavior
The two elements should be at least stacked somehow.

## Minimal reproduction of the problem with instructions
I'm using the [chart sample](http://www.telerik.com/kendo-angular-ui/components/charts/chart/export-options/#toc-fitting-charts-to-paper-size) :
```
const visual = this.chart.exportVisual();
const group = new Group();
const title = new drawing.Text("detail-grafik", [20, 25], <drawing.TextOptions> { font: "bold 20px Arial"});
group.append(title, visual);
fit(group, this.PAGE_RECT);
exportPDF(group, <pdf.PDFOptions> {
...
```

## Environment
Latest kendo version, Angular 4 and 5

Browser:
- Chrome (desktop) version 59.0

**Comment by danielkaradachki** [comment]
The exportPDF method outputs whatever drawing elements it is passed. It is up to you to position the elements however you need. The drawing [alignment](http://www.telerik.com/kendo-angular-ui/components/drawing/api/) functions or the [Layout](http://www.telerik.com/kendo-angular-ui/components/drawing/api/Layout/) element can be used to simplify this task:
http://plnkr.co/edit/BfWWj2fH5PqZtUdu3E2P?p=preview

**Comment by EricSch** [comment]
Thanks, some more samples how to use the functions for Drawing API would be very helpful :wink:

**Comment by EricSch** [comment]
![image](https://user-images.githubusercontent.com/25437/29162338-6d39b038-7db9-11e7-9636-cc8e9961da62.png)

And the text is cut off, so vStack isn't very helpful

**Comment by danielkaradachki** [comment]
You need to [define the font](http://www.telerik.com/kendo-angular-ui/components/drawing/pdf-output/#toc-custom-fonts) used for the Text element:

http://plnkr.co/edit/BvPqObO7ylRxaaLePN3h?p=preview

Otherwise the font used in the PDF will not be the same and so the size measured by vStack will not be correct in the PDF.

**Comment by danielkaradachki** [comment]
Thought this worked but there is still some minor overlapping. An easy fix will be to switch the order in which the title and the chart element are appended:

http://plnkr.co/edit/BvPqObO7ylRxaaLePN3h?p=preview

**Comment by EricSch** [comment]
I used Arial, and this font should be known by the system. You see it, when 2 text and the chart are added, the first text is rendered correctly, but the second is cut off by the chart.
So it has to be a problem, how the chart is appended and positioned. 

But your easy fix did work, so thank you.
