### ISSUE TITLE
Grid scroll jumps on several clicks on scroll rulers

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#810]
## I'm submitting a...
* Bug report 

## Current behavior
When clicked several times on scroll rulers ( little arrows ) there is a moment when the scroll jumps for a second in the opposite  direction.
Reported from user. 

## Expected behavior
Scroll should not jump in both directions when scrolling/clicking on rulers

## Minimal reproduction of the problem with instructions

  1. It can be observed [here](http://plnkr.co/edit/L3yuFPrfISijnn8LWC8J?p=preview) pageSize is reduced to 30 so to break it easily
  2. Try clicking on lower scroll ruler several times.
 
Browser:
 All

System:
N/A

**Comment by tsvetomir** [comment]
Possibly related to #666. The new records are not yet available and must be covered with a loading panel.

**Comment by tsvetomir** [comment]
No longer observed in the latest version, [see plunkr](http://plnkr.co/edit/3z2kjFmo4VIlOHI5nDzs?p=preview).
