### ISSUE TITLE
Button within a header template cannot be clicked reliably when the Grid is groupable

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#811]
## I'm submitting a...

* Bug report 

## Current behavior

Clicking the button sometimes is treated as the start of dragging.

## Expected behavior
The button click handler to be executed each time the button is clicked.

## Minimal reproduction of the problem with instructions
[http://plnkr.co/edit/gYfpnPCWY9LbhY4UGg1B?p=preview](http://plnkr.co/edit/gYfpnPCWY9LbhY4UGg1B?p=preview)

[https://www.screencast.com/t/QY2UABJyE](https://www.screencast.com/t/QY2UABJyE)

**Comment by tsvetomir** [comment]
Seems to be fixed in the latest version, see [plunkr](http://plnkr.co/edit/8HnYJGym54cPTnVB9Tyy?p=preview).

**Comment by ipeshev** [comment]
fixed in v1.4.3-dev.201709281122
