### ISSUE TITLE
TreeView and ListView components

### ISSUE THREAD

**Issue by jackjoy** [telerik/kendo-angular#813]
TreeView & ListView are very common used controls for build ui.We are very disappointed that these components will not be released in near future.Currently kendo-angular lack many common used controls for building business application and we are forced to transfer from kendo-angular to other solutions.

**Comment by EricSch** [comment]
This is my personal view only 😄 
Not really a bug and wrong place to comment, for me too. 
Those elements, specially ListView, has already great support with Angular and the templates. Not sure what kind of control you expect. I'm very happy with Kendo Angular. This was the first and only control set which was really made as true Angular components without strange DOM hacks. So good luck!

**Comment by tsvetomir** [comment]
A TreeView component is on our tentative plans for the January release. Preview versions may be available earlier. No ListView is considered at the moment.

@EricSch agreed, especially with the ListView there's little to offer besides a pager and and editing. The rest is handled nicely by Angular and Bootstrap/Material.

Please cast your vote for new components and major features on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback). This will help us gauge the overall interest and prioritize.

**Comment by MaklaCof** [comment]
I agree with both. 

There is really hard to wait for basic controls. There are also misleading informations on [components site](http://www.telerik.com/kendo-angular-ui/components/). Really funny, but soon it will be a year, and it still writes Comming soon for ToolBar, TimePicker, ColorPicker.

On the other hand, kendoAngular is the only real Angular components and there is no other alternative. We must wait and hope Telerik will add a few more developers on KendoAngular project.

**Comment by tsvetomir** [comment]
Thank you for the feedback, everyone.

@MaklaCof the TimePicker is about to hit production in a week or so, you can try it out in the development channel. No good estimates on the color picker and toolbar at the moment.

On a side note, the Grid and the form components turned out to be a huge pain to get right. I'm not implying that misleading you is okay and we're trying to be more precise with our estimates.

**Comment by MaklaCof** [comment]
@tsvetomir I [see it](https://github.com/telerik/kendo-angular/issues/263#issuecomment-321233669) and it looks great. Not too happy about ToolBar, but I guess this is life of a developer. :disappointed:

I am sure you are on the right track and everything you will deliver will be fantastic as I am sure you understand us (developers) that we would like to see complete KendojQuery in Angular by tomorrov. :smiley:

**Comment by j-pdx** [comment]
I really need the TreeView. We can't update our app from Angular 1 without it. I'm also disappointed that functionality we had before (like column reordering) is currently missing from the Grid.

I just wish there was more information about the timeline for these implementations. At this point we're being forced to look at alternative libraries to be able to move forward.

**Comment by tsvetomir** [comment]
@j-pdx it's possible to use the Kendo UI for jQuery TreeView as a stop-gap measure, see [Kendo UI for jQuery Integration](http://www.telerik.com/kendo-angular-ui/components/framework/kendo-jquery/)

I have no precise estimate for the column reordering feature as work has not started yet. It could be anywhere between 2 and 4 months from now.

**Comment by jackjoy** [comment]
I tried to implement these controls by myself. It's not too hard to implement the logic,but  really difficult to make the controls' style consistent with kendo's theme.Are there documents about visual structures of kendo-ui-jquery controls that we can used to implement the missed controls in angular version with same styles and themes?

**Comment by tsvetomir** [comment]
There's no such detailed guide available, but you could reuse the markup and classes from the [Kendo UI for jQuery components](http://demos.telerik.com/kendo-ui/treeview/index).

The Default and Bootstrap themes are shared between the suites and the styles are present even though the components are not there.

**Comment by tsvetomir** [comment]
The TreeView first official release is [now available](https://www.telerik.com/kendo-angular-ui/components/treeview/).

Please, vote for the ListView on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18778405-listview-component). Closing this issue to avoid duplication with UserVoice.
