### ISSUE TITLE
Upload and HttpModule vs HttpClientModule

### ISSUE THREAD

**Issue by ncrawlins** [telerik/kendo-angular#814]
The upload module currently depends on the HttpModule, but I think HttpClientModule is the standard now and it's what we are using.    Would prefer not to have to include both modules.  I tried just providing the HttpClient as a replacement for the Http token injector, but that barfed, I guess the API changed enough that it won't work.

If you can't switch to the HttpClientModule, can you give an approximation of the surface area of the HttpModule api and the Response Object api that you use and maybe we can just make a simple wrapper around HttpClient that will satisfy the way you use Http.

**Comment by sgwatgit** [comment]
My team is also working on a project using Angular 4.3 (and then 5.0 when it releases) and we would prefer to use the HttpClient service.

**Comment by yanbu0** [comment]
I upgraded my project to 4.3+ and just got around to removing all the references to the old HttpModule as well, which breaks the upload.  Would be great to see an updated version of this from my end as well, would prefer not to have both clients in the project just to support this widget.

**Comment by tsvetomir** [comment]
Upload v2 and later support HttpClientModule, [see documentation](https://www.telerik.com/kendo-angular-ui/components/upload/).
