### ISSUE TITLE
Removing rxjs/rx imports

### ISSUE THREAD

**Issue by thaoula** [telerik/kendo-angular#815]
Hi Guys,

I frequently search our code base for the accidental import rxjs elements using rxjs/Rx. 

As you know this statement will load the entire rxjs library. 

Are you able to update your components to use specific imports?

**Example from the combo box component**
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/merge';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/let';
import 'rxjs/add/operator/partition';
import 'rxjs/add/operator/throttleTime';
import 'rxjs/add/operator/distinctUntilChanged';
import { Subject } from 'rxjs/Subject';
**import { Subscription } from 'rxjs/Rx';**
import { isPresent, isChanged, guid, isDocumentAvailable, getter } from './util'; 

I came across this when trying to track down issues when using the new build optimiser settings.
https://github.com/angular/angular-cli/issues/7110

Regards,
Tarek

**Comment by tsvetomir** [comment]
Thanks for the heads-up, will do.

**Comment by tsvetomir** [comment]
Fixed in the dev versions of the Dropdowns, DateInputs and Upload. Will be included in their next official releases.

**Comment by siyka-marinova** [comment]
Fix is now available in the latest official packages:
`@progress/kendo-angular-dropdowns@1.2.0`
`@progress/kendo-angular-dateinputs@1.2.0`
`@progress/kendo-angular-upload@1.2.1`
