### ISSUE TITLE
Placeholder is partially hidden initially

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#817]
## I'm submitting a...
* Bug report
## Current behavior
Only first 3 letters from placeholder are shown
## Expected behavior
Whole placeholder should be visible

## Minimal reproduction of the problem with instructions
 It can be reproduced [here](http://www.telerik.com/kendo-angular-ui/components/dropdowns/)
Try to clear all multiselect items
If you add item and again clear all items it is ok.

**Comment by valchev** [comment]
Duplicated with #1144, fixed thanks to @elena-gancheva
