### ISSUE TITLE
Dropdown menu is opened when clear button is clicked

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#819]
## I'm submitting a...
* Bug report 

## Current behavior
When item is selected in multiselect and clear button is triggered two thing are happening dropdown menu is opened and user sees glimpse/flash of deselecting item  
## Expected behavior
Opening dropdown might be considered as a feature ( in some cases ) , but the flash is something unneeded.

## Minimal reproduction of the problem with instructions
Open [this demo](http://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/)
Select item 
Click on clear button.

## Environment

v1.1.3

Browser:
All

**Comment by valchev** [comment]
Seems to be fixed in the latest version
