### ISSUE TITLE
license for Non-Commercial, Non-Competitive app

### ISSUE THREAD

**Issue by nni123** [telerik/kendo-angular#820]
I want to develop non-commercial applications using KendoUI. Do I have to pay for license?

Thanks

**Comment by tsvetomir** [comment]
Yes, you must obtain a commercial license.

The [Kendo UI for Angular license](https://github.com/telerik/kendo-angular/blob/master/LICENSE.md) is granted to an individual developer. It does not have provisions for the type of applications being developed.

**Comment by nni123** [comment]
thank you
