### ISSUE TITLE
k-ng-model gives " Unexpected token {"

### ISSUE THREAD

**Issue by CoderSquirrel** [telerik/kendo-angular#821]
## I'm submitting a...
* Bug report 

## Current behavior
I'm using the kendo editor inside of my directive, i used the code from the exemple but when o put the k-ng-model i get the "Unexpected token {" message

## Expected behavior
Update the model and dont shows up error
## Minimal reproduction of the problem with instructions
`<textarea id="editor" kendo-editor ng-model="ngModel"  k-ng-model="ngModel" name="editor" ng-required="ngRequired"></textarea>
`
## Environment

Browser:
- Chrome (desktop) version 60.0.3112.9

System:
- Node version: 4.6.1
- Platform:  Windows

**Comment by tsvetomir** [comment]
The error report seems to be related to the AngularJS 1.x wrappers of Kendo UI for jQuery. Please, file it at [telerik/kendo-ui-core](https://github.com/telerik/kendo-ui-core/issues) or submit a support ticket.

This issue tracker is for [Kendo UI for Angular](http://www.telerik.com/kendo-angular-ui/), which is a separate code base.
