### ISSUE TITLE
kendo grid inside reactive nested form

### ISSUE THREAD

**Issue by premiumwd** [telerik/kendo-angular#825]
inside a formgroup and have kendo grid in it. How would I add kendogrid to it with properties, I get error saying I need to add it to form group with formgroupname, but when I do I get this error. 

No value accessor for form control with name.

**html**
```
<kendo-grid 
          formControlName="AnalyteDetailsGrid"
          name="AnalyteDetailsGrid"
          [ngClass]="{error: !AnalyteDetailsGrid}"
        >
```
**component**
```
  // REACTIVE FORM
  @Input() public AnalyteDetailsForm: FormGroup;

  ngOnInit() {

    // REACTIVE FORM
    this.AnalyteDetailsForm = this.fb.group({
      AnalyteDetailsGrid: ['', [Validators.required, Validators.minLength(2)]]
    });     
  }
```

**Comment by rusev** [comment]
The Grid component does not implement `ControlValueAccessor` which is required in order to work with `formControl` and `formControlName` directives. 

The component is not meant to be used as a form control.

**Comment by premiumwd** [comment]
@rusev what are some alternatives? you cant just close and say no.
