### ISSUE TITLE
NG2 DatePicker parseFormats for input

### ISSUE THREAD

**Issue by ginamako** [telerik/kendo-angular#827]
Is there a possibility to define the parseFormats for the Kendo DatePicker NG2 component (like there was in the NG1 component)?  I am looking for a way to make it possible for the user to enter the  date with the keyboard in different formats (e.g.D.M.YY, D.M.YYYY,  DD.MM.YY, DD.MM.YYYY). In NG1 there was the property parseFormats. In  the NG2 component I can't find a similiar thing.

**Comment by ggkrustev** [comment]
The DatePicker component uses DateInput internally, which works with a single format only. This behavior is enforced by the masking functionality of the DateInput, which would not work properly with multiple parsing formats. 

I'm afraid that the required functionality is not supported for the time being. What I can suggest is posting your request in our Feedback portal. Based on the users interest, we will decide whether to schedule it for further investigation.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback
