### ISSUE TITLE
Sortable should not mutate data

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular#828]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
The Sortable mutates its `data` when dragging items. This makes it very hard to override the default actions and to customize the drag and drop logic.

## Expected behavior
The Sortable should only fire events corresponding to the user actions without modifying the data. The developer should decide what actions to perform.

Note that this change will make #354 redundant. The current behavior must remain the default to avoid breaking changes.

**Comment by tapopov** [comment]
Shipped in kendo-angular-sortable v2.0.0
