### ISSUE TITLE
Kendo Grid 1.3.2 selection issue

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#831]
## I'm submitting a...
* Bug report 

## Current behavior
This is rather peculiar  issue that only surfaces in our project. I cannot reproduce it in plunkr!

The problem we are facing is in a grid with multi selection enabled and SelectionDirective, the steps to reproduce this issue (in our project) are as follows:
- click to select a row
- click on the same row (nothing happens as expected)
- click any other row to deselect the current row and select the new one
- `core.es5.js:1020 ERROR TypeError: Cannot read property 'id' of undefined`

This happens every time no matter what i do.

What i found while debugging:
When clicking on the selected row the selection service still gets triggered but realizes at some point that there is nothing to be de/selected, but before realizing that it modifies the currentSelection property (IMHO) with invalid data `selection.service.js:53`
```javascript
this.currentSelection[item.index] = item.data;
```

![image](https://user-images.githubusercontent.com/323925/29356990-b09585ae-827e-11e7-897c-947e3e454034.png)

This does not fit in the signature of the `currentSelection` (RowArgs) as the item.data is really the data of the grid row and not `RowArgs { dataItem: any;   index: number; }`

In our case, clicking on the same row leaves the `currentSelection` in invalid state, meaning currentSelection[index] is equal to the current data and not dataItem.... so deselcting this row after that is not possible.

I really don't know why can't i reproduce this in plunkr.

## Expected behavior
-

## Minimal reproduction of the problem with instructions
-

## What is the motivation or use case for changing the behavior?
-

## Environment

Package versions:
```
@progress/kendo-angular-grid@1.3.2
```

I am sorry for the wall of text :) and if I am wrong, please give suggestion where to search for the root cause

**Comment by Raisolution** [comment]
Hi @moxival,

We would really appreciate an example, reproducing the issue. You could also paste the exact Grid configuration as a snippet here, so we could try to find something odd, that may be the cause of the problem.

**Comment by moxival** [comment]
@Raisolution if I could I would believe me i tried many times, i cannot post any of our code - you know how that works.

**Comment by zjs1024** [comment]
This is happen on my project too. I think the issue is the "selectionChange" event is not fired if the row has already been selected;  Also there is no double clicked function for GridView,  and it can't be done through "selectionChange", thins the event can not be fired twice.

**Comment by Raisolution** [comment]
Hi @zjs1024,
could you demonstrate the problem in a small plunkr example by modifying some of our demos?

**Comment by zjs1024** [comment]
@Raisolution  
http://plnkr.co/edit/Dr7ybklOzxaA3576dWnO?p=preview
click once, alert will show, click the same row again or double click, nothing happened.

**Comment by Raisolution** [comment]
@zjs1024,
this behavior is expected and by design. The `selectionChange` event will not fire for already selected rows.

**Comment by zjs1024** [comment]
@Raisolution 
Then how to catch double click? what if you want to unselect the row?

**Comment by moxival** [comment]
@zjs1024 there is no doubleclick event in the grid selection (I am not sure if it is planned) and this issue is not about doubleclicking the row, please take a look at the [README](https://github.com/telerik/kendo-angular#when-do-you-plan-on-releasing-feature-x) how to submit a feature request.

@Raisolution can you please confirm that there is nothing wrong with `this.currentSelection[item.index] = item.data;`  so I can go hunt for something else?

**Comment by zjs1024** [comment]
@Raisolution even just for this case, I think it is a bug, you can't do unselect in multiple selections
if(!isPresent(ev){
 ev = this.select(item);
  this.currentSelection[item.index] = item.data;
}else{
   //  remove selection
}

**Comment by Raisolution** [comment]
@zjs1024 this behavior is intended. Deselecting the row is achieved by ctrl+clicking it.

@moxival currently we haven't found any issues with the mentioned line of code.

**Comment by moxival** [comment]
Ok then I am closing the issue and if/when ii find something more useful will open another one
