### ISSUE TITLE
Drag left/right not working as expected

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#832]
## I'm submitting a...
* Bug report
## Current behavior
If we try to drag&drop sortable item right/left false draghandle appears on the screen and the drag is not smooth as opposed to up/down drag.

## Expected behavior
The drag right/left should be smooth as drag up/down

## Minimal reproduction of the problem with instructions

It can reproduced [here](http://www.telerik.com/kendo-angular-ui/components/sortable/)

## Environment

v1.0.2

Browser:

- Safari (iOS) version XX

**Comment by tapopov** [comment]
Unable to reproduce using latest `kendo-angular-sortable` and iOS Safari.
