### ISSUE TITLE
DataBound Event Grid / Generic Bound Event ?

### ISSUE THREAD

**Issue by iqmeta** [telerik/kendo-angular#833]
## I'm submitting a Feature requests

* Suggestion for improvement
* Documentation issue or request

DataBound Event on Grid
-> only     public dataStateChange(state: DataStateChangeEvent): void {}

## Current behavior
Does not fire on initial DataBound

## Expected behavior
Event when Data is loaded

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/OVJzTaoJ9h2PvQyIn2jU?p=preview

## What is the motivation or use case for changing the behavior?
Need to do things after grid is loaded

**Comment by tsvetomir** [comment]
In this case the data is being fetched by the service. Since it's an observable you can monitor for new data by subscribing to it, just like the Grid does:

```js
this.view.subscribe(data =>
  console.log(data)
);
`
