### ISSUE TITLE
I can't install @progress/kendo-angular-grid@1.3.2

### ISSUE THREAD

**Issue by vickydp** [telerik/kendo-angular#834]
npm ERR! notarget No compatible version found: @progress/kendo-angular-grid@1.3.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.8.1, 0.8.2,
0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.
16.2, 0.17.0, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.19.5, 0.19.6, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.21.2, 0.2
2.0, 0.22.1, 0.22.2, 0.22.3, 0.23.0, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 0.25.4, 0.25.5, 0.26.0, 0.26.1, 0.26.2, 0.26
.3, 0.26.4, 0.26.5, 0.26.6, 0.27.0, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 1.0.0, 1.0.1,
 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.1.0, 1.1.1-dev.201705240914, 1.1.1, 1.1.2-dev.201705251029, 1.1.2-dev.201705251143, 1.1.2-de
v.201705251156, 1.1.2, 1.1.3-dev.201705291416, 1.1.3-dev.201705311458, 1.1.3-dev.201705311516, 1.1.3-dev.201705311559, 1.1.3-dev.20170601
0842, 1.1.3-dev.201706011439, 1.1.3-dev.201706021312, 1.1.3, 1.1.4-dev.201706021548, 1.1.4-dev.201706061314, 1.2.0-dev.201706081346, 1.2.
0-dev.201706091117, 1.2.0-dev.201706131128, 1.2.0-dev.201706131429, 1.2.0, 1.2.1-dev.201706151103, 1.2.1-dev.201706161105, 1.2.1-dev.2017
06211424, 1.2.1-dev.201706221406, 1.2.1-dev.201706221449, 1.2.1-dev.201706261335, 1.2.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! **notarget a package version that doesn't exist.**

## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by gyoshev** [comment]
Please verify that you are using the official NPM registry for the @progress packages. We have retired the private registry, and new package versions are not published there. See https://github.com/telerik/kendo-angular/issues/712 for more information.

**Comment by vickydp** [comment]
thanks !!!
