### ISSUE TITLE
Virtual Scrolling Grid + Async Data produces erratic results

### ISSUE THREAD

**Issue by ERobishaw** [telerik/kendo-angular#837]
## I'm submitting a...

* Bug report 

## Current behavior

**Plunkr can be found here:**
http://plnkr.co/edit/2iU6kFF9Y5r1WmWWu8ib?p=preview

When using virtual scrolling with an asynchronous data source, the scrolling is erratic and wrong.
Scrolling DOWN rapidly, if you watch carefully the Id column, you can see that the Ids increase and decrease, increase and decrease... they should ONLY be increasing.
Values get inserted incorrectly.

## Expected behavior

Scrolling should halt until the desired results are returned, and the results should always be sequential.

## Minimal reproduction of the problem with instructions

**Plunkr can be found here:**
http://plnkr.co/edit/2iU6kFF9Y5r1WmWWu8ib?p=preview

I copied the example from your site and only made slight modifications to the loadProducts() method to simulate async loading of data.

## What is the motivation or use case for changing the behavior?

It doesn't work correctly, OR an example needs to demonstrate the proper mechanism to async data loading with the virtual grid.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version 60.0.3112.90

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by rkonstantinov** [comment]
The behavior in question is a known one. Please refer to this issue https://github.com/telerik/kendo-angular/issues/622 for more details.

**Comment by tsvetomir** [comment]
Tracking in #666
