### ISSUE TITLE
Issue with Reactive Form editing after hiding a column

### ISSUE THREAD

**Issue by rusev** [telerik/kendo-angular#839]
## I'm submitting a...

* Bug report 

## Current behavior
All buttons flip to edit mode.

## Expected behavior
Command buttons should be in correct state.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/niCkoaY2g62duCZ4eY9B

1. Open the plunker
2. verify that edit works
3. Click "hide me" button that hides one column
4. Click "Edit". All buttons flip to edit mode. always the LAST row goes to edit mode.

Package versions:

```
@angular/core@4.x.x
@progress/kendo-angular-grid@1.3.3
```

**Comment by siyka-marinova** [comment]
Released `@progress/kendo-angular-grid@1.4.1`
