### ISSUE TITLE
kendo-angular-inputs: bundling of es modules failed with Error:  'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by pvskasyrskiy** [telerik/kendo-angular#841]
## I'm submitting a...
* Bug report 
Since version 1.1.0 of kendo-angular-inputs we getting bundling error. On version 1.0.7 all works fine.
I believe issue related to duplicate comments at start of the file
https://github.com/Microsoft/TypeScript/issues/12979
Originally in version 1.1.0 file @progress\kendo-angular-inputs\dist\es\common\enums.js looks like:
`
/**
 * @hidden
 */
/**
 * @hidden
 */ export var Keys;
(function (Keys) {
    Keys[Keys["backspace"] = 8] = "backspace";
    Keys[Keys["tab"] = 9] = "tab";
    Keys[Keys["enter"] = 13] = "enter";
    Keys[Keys["shift"] = 16] = "shift";
    Keys[Keys["ctrl"] = 17] = "ctrl";
    Keys[Keys["alt"] = 18] = "alt";
    Keys[Keys["space"] = 32] = "space";
    Keys[Keys["page up"] = 33] = "page up";
    Keys[Keys["page down"] = 34] = "page down";
    Keys[Keys["end"] = 35] = "end";
    Keys[Keys["home"] = 36] = "home";
    Keys[Keys["left"] = 37] = "left";
    Keys[Keys["up"] = 38] = "up";
    Keys[Keys["right"] = 39] = "right";
    Keys[Keys["down"] = 40] = "down";
    Keys[Keys["delete"] = 46] = "delete";
})(Keys || (Keys = {}));
`

And in this case bundling error appears.
When I manually remove unnecessary comments and move code to new line enum.js file looks like this

`
/**
 * @hidden
 */
export var Keys;
(function (Keys) {
    Keys[Keys["backspace"] = 8] = "backspace";
    Keys[Keys["tab"] = 9] = "tab";
    Keys[Keys["enter"] = 13] = "enter";
    Keys[Keys["shift"] = 16] = "shift";
    Keys[Keys["ctrl"] = 17] = "ctrl";
    Keys[Keys["alt"] = 18] = "alt";
    Keys[Keys["space"] = 32] = "space";
    Keys[Keys["page up"] = 33] = "page up";
    Keys[Keys["page down"] = 34] = "page down";
    Keys[Keys["end"] = 35] = "end";
    Keys[Keys["home"] = 36] = "home";
    Keys[Keys["left"] = 37] = "left";
    Keys[Keys["up"] = 38] = "up";
    Keys[Keys["right"] = 39] = "right";
    Keys[Keys["down"] = 40] = "down";
    Keys[Keys["delete"] = 46] = "delete";
})(Keys || (Keys = {}));
`
and bundling again works fine!

## Current behavior
Bundling failed with message:
Error compiling global module "@progress/kendo-angular-inputs/dist/es/common/enums.js" at node_modules\@progress\kendo-angular-inputs\dist\es\common\enums.js         node_modules/@progress/kendo-angular-inputs/dist/es/common/enums.js: 'import' and 'export' may appear only with 'sourceType: module' (6:4)

## Expected behavior
Success bundling

##

**Comment by danielkaradachki** [comment]
Thank you for pointing out this problem. We will fix it.

**Comment by tsvetomir** [comment]
Should be fixed in `@progress/kendo-angular-inputs` v1.1.1
