### ISSUE TITLE
"hidden" in kendo-grid-column

### ISSUE THREAD

**Issue by nm-a** [telerik/kendo-angular#842]
Hi Team,
I see "hidden" in kendo-grid-column is not working.
Here is my code snippet that I am using inside template ng-template

`
                <ng-template ngFor [ngForOf]="reportMetaData" let-column>
                    <kendo-grid-column field="{{column.Value}}" title="{{column.Title}}" [width]="220" hidden="{{column.IsHidden}}">

                    </kendo-grid-column>
                </ng-template>
`

Thank you
-nm

**Comment by tsvetomir** [comment]
The binding syntax should be `[hidden]="{{column.IsHidden}}"` otherwise the value will be converted to a string.

**Comment by nm-a** [comment]
This is not working.

**ERROR Error**: Uncaught (in promise): Error: Template parse errors:
Parser Error: Got interpolation ({{}}) where expression was expected at column 0 in [{{column.IsHidden}}] in ng:///TbModule/ReportsComponent.html@40:103 ("                 <kendo-grid-column field="{{column.Value}}" title="{{column.Title}}" [width]="220" [ERROR ->][hidden]="{{column.IsHidden}}">

                    </kendo-grid-column>
"): ng:///TbModule/ReportsComponent.html@40:103
Parser Error: Unexpected token {, expected identifier, keyword, or string at column 2 in [{{column.IsHidden}}] in ng:///TbModule/ReportsComponent.html@40:103 ("                 <kendo-grid-column field="{{column.Value}}" title="{{column.Title}}" [width]="220" [ERROR ->][hidden]="{{column.IsHidden}}">

**Comment by tsvetomir** [comment]
Sorry, my bad - forgot to trim the curly braces, see [property binding](https://angular.io/guide/template-syntax#property-binding--property-):

`[hidden]="column.IsHidden"`

**Comment by nm-a** [comment]
thank you @tsvetomir ; it is working as expected. Can I follow the same for format as well..!

I am trying like this [format]="column.Format"
colsList[1].Format="{0:dd/MMM/yyyy}"

thank you

**Comment by tsvetomir** [comment]
Indeed, that should work fine. Are you having any troubles with it?

**Comment by nm-a** [comment]
It is working fine for static column, not working when to try place inside ng-template

```
<ng-template ngFor [ngForOf]="reportMetaData" let-column>
<kendo-grid-column field="{{column.Value}}" title="{{column.Title}}" [width]="220" [format]="column.IsHidden">
```

**Comment by tsvetomir** [comment]
I can't spot anything wrong with the snippet. We'll need a more complete code sample to assist.

I'd like to ask you to submit a [support ticket](submitting a support ticket - Telerik) as the problem does not seem to be caused by a bug in the component itself.

**Comment by nm-a** [comment]
thank you @tsvetomir , will raise the ticket.

**Comment by ranjith88** [comment]
Can I do something like this? This is not working for me.
 
<kendo-grid-column field="Category" title="Category" width="50">
           <ng-template kendoGridGroupHeaderTemplate let-value="value" let-aggregates let-field="field" [hidden]="column.IsHidden">
                                    {{value}} (Count: {{aggregates.aggregates[field].count}})
                                </ng-template>
                            </kendo-grid-column>
