### ISSUE TITLE
Kendo-Grid: groupService.changes.filter is not a function

### ISSUE THREAD

**Issue by SyntaxStacks** [telerik/kendo-angular#843]
## I'm submitting a...

* Bug report 

## Current behavior
When attempting to create a kendo grid. I receive the error below
![issue](https://user-images.githubusercontent.com/2099863/29534050-1fd69fd0-867a-11e7-8d19-b216fd64d222.png)

## Expected behavior
No error when copying the example

## Minimal reproduction of the problem with instructions
I've been unable to reproduce this with plunker, the sources are pulled from the dist/cdn directory on plunkr but dist/es/main.js is what the angular 2 project is using

## What is the motivation or use case for changing the behavior?
Things should work with console errors

## Environment

Package versions:

```

```

Browser:
- Chrome (desktop) version XX

System:
- TypeScript version: 2.4
- Node version: node - 6.11.1 npm - 3.10.10
- Platform:  Mindows

I was looking at the changelog and it appears that in 1.2.3 "filter is missing from DataStateChangeEvent type declaration" was fixed and I believe that might be the case again as `import 'rxjs/add/operator/filter'; is missing in grid.component.js

![issue1](https://user-images.githubusercontent.com/2099863/29534306-1a381f4e-867b-11e7-85e4-8386200d60d5.png)

**Comment by rkonstantinov** [comment]
@SyntaxStacks I'm not sure why you are getting the mentioned error nor we are able to re-create it. The rxjs filter operator is imported by the list.component, thus it should be loaded.

Could you please provide a small sample in which the issue can be observed locally?

Also you may test if manually importing the operator on the host page resolves the error.

**Comment by SyntaxStacks** [comment]
I've tried bringing in the import on the host page but no luck, I'll continue to work on a reproduction for testing. Thanks for the reply

**Comment by SyntaxStacks** [comment]
I've attempted to start a fresh project and reproduce the issue, but the issue was not present in the newly created app :[ 

Thank you for your time but there must be something weird in the current project. I'll continue to debug. Thanks again.

**Comment by SyntaxStacks** [comment]
@rkonstantinov I actually was able to add 
`import 'rxjs/add/operator/filter';`
and get passed that error.

Then I received an error about map and a few others,
```
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/merge';
import 'rxjs/add/operator/groupBy';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/take';
```

We're building an internal component library, I'm sure this is due to a misconfiguration with peer dependencies on our side. I'll update this ticket with any info I find in case someone else has an issue like this in the future.
