### ISSUE TITLE
ComboBox search value is cleared when there are multiple pending requests

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#844]
## I'm submitting a...
* Bug report 

## Current behavior
When the ComboBox is bound to a remote service, and there are multiple pending requests, the search text is cleared from the input when the second pending request's response arrives.

## Expected behavior
The search text should remain in the input.

## Minimal reproduction of the problem with instructions
[http://plnkr.co/edit/3MtESWTIW5335Lnuikzu?p=preview](http://plnkr.co/edit/3MtESWTIW5335Lnuikzu?p=preview)

1. insert a "s"
2. wait ~ 500ms
3. insert a "p"

When the data in the options list is refreshed with the response of the second request, the input is cleared.

**Comment by szavoda** [comment]
I can verify this is a problem.  We are supposed to be going into production on Monday.  Please advise if there is a workaround...

**Comment by lexon0011** [comment]
Unfortunately we have no working workaround ...

**Comment by dtopalov** [comment]
You can allow custom values as a workaround:

[http://plnkr.co/edit/GwNOAsD1XQG81renUu69?p=preview](http://plnkr.co/edit/GwNOAsD1XQG81renUu69?p=preview)

[http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/#toc-object-values](http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/custom-values/#toc-object-values)

**Comment by szavoda** [comment]
Mine already allows custom values and exhibits the same behavior.

**Comment by lexon0011** [comment]
Yes, the workaround has the same wrong behavior

**Comment by talynone** [comment]
ComboBox has many issues including this one, which I provided a plunkr for 17 days ago:

https://github.com/telerik/kendo-angular/issues/812

**Comment by siyka-marinova** [comment]
Fix for this bug is now available in the latest dev. version of the

**Comment by szavoda** [comment]
Looking good so far with minimal testing on my side - thx!!

**Comment by tsvetomir** [comment]
Fix shipped in `kendo-angular-dropdowns@1.2.0`
