### ISSUE TITLE
npm install getting 443 error

### ISSUE THREAD

**Issue by ndlganeshu** [telerik/kendo-angular#845]
## I'm submitting a...
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed http://registry.npm.telerik.com:443/@progress%2fkendo-ooxml/-/kendo-ooxml-1.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed http://registry.npm.telerik.com:443/@progress%2fkendo-file-saver/-/kendo-file-saver-1.0.2.tgz
npm ERR! fetch failed http://registry.npm.telerik.com:443/@progress%2fkendo-angular-excel-export/-/kendo-angular-excel-export-1.0.3.tgz

I'm getting the above errors when i run npm install from terminal
I already has the package.json file with all these components

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior
Getting 443 error with bulk npm install

## Expected behavior
it should work, i have done this with previous projects it's worked. But today i'm getting these erorrs.

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ggkrustev** [comment]
Private Progress NPM registry was retired a month ago. Remove the following lines from your .npmrc file to switch to the default registry:
```
@progress:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken=<token>
```

More details and workaround can be found in the relevant Github issue:

https://github.com/telerik/kendo-angular/issues/712

**Comment by ndlganeshu** [comment]
Thank you Georgi for replying....

I got it resolved my problem with npm shrinkwrap.
i renamed the file and run the command npm install it's worked as expected.

Once again thanks
