### ISSUE TITLE
Inline Editing on Row Click can't edit rows on multiple clicks

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#848]
## I'm submitting a...

* Bug report 

## Current behavior
After several clicks on rows for editing ( just click on row without edit ),  edit mode can't be enabled for some rows.
In addition, if we try to edit last row,  the last column button receives "display:none" while in edit mode.
## Expected behavior
Any consecutive click should invoke edit mode.
The button in any column shouldn't be hidden.

## Minimal reproduction of the problem with instructions

1. Open this [demo](http://plnkr.co/edit/cXokKFTcQ25GQxHSE21I?p=preview)

2. Start clicking consecutive on rows to edit them.

3. Try click on last row.  

## Environment

v1.3.3

Browser:
N/A

**Comment by danielkaradachki** [comment]
The problem with the buttons should be fixed in the dev channel. 
The issue with entering edit mode is related to the validation in the demo code - Validators.pattern('^[0-9]{1,2}')
which is invalid for the initial data. The demos have been updated to have correct rule for the initial data.

**Comment by tsvetomir** [comment]
Fix shipped in `@progress/kendo-angular-grid@1.4.0`
