### ISSUE TITLE
When ComboBox Set [valuePrimitive]="true" and after select a value click enter key

### ISSUE THREAD

**Issue by baiyunchen** [telerik/kendo-angular#851]
When I select One Of the Combobox,the cursor does not leave Combobox，click the enter key,Combobox the content of the empty.And expand the dropdown list,the previously selected items are still highlighted.

Kendo official demo also has this problem:
http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/value-binding/#toc-primitive-values-from-object-fields

**Comment by ggkrustev** [comment]
@baiyunchen, I am afraid that the given details are not clear enough. Could you follow the ticket template and providing more information about environment and clear reproduction steps? This will help us to observe the erroneous behavior locally and find solution faster.

**Comment by simon11196** [comment]
I think i could reproduce this behavior.
What i did:

- Run [Code](http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/value-binding/#toc-primitive-values-from-object-fields)
- Clear Value
- Typed in 'Lar'
- Hit Enter
- Dont leave ComboBox and Hit Enter again -> Value is cleared
- Open ComboBox-Popup -> 'Large' is still selected/highlighted

Only happens with [valuePrimitive]="true"

gif:
![851](https://user-images.githubusercontent.com/21359517/30060028-e0bad176-9241-11e7-81a5-f8e4289b0513.gif)

OS: Windows 10 64 bit
Browser: Google Chrome / Version 60.0.3112.113

**Comment by ggkrustev** [comment]
@simon11196, thanks a lot for the heads up. Indeed, the erroneous behavior is reproducible with the given steps. I marked the issue with `[bug]` tag and we will schedule it for fixing in some of our next releases.

**Comment by tapopov** [comment]
Should be fixed in dev -  `v1.2.1-dev.201709251137` and beyond.

**Comment by ipeshev** [comment]
Currently the caret is staying in the middle of the word on first 'Enter' hit.

**Comment by ipeshev** [comment]
This [issue](https://github.com/telerik/kendo-angular/issues/923)  has same problem but it will be referenced here

**Comment by ipeshev** [comment]
Fixed in v1.2.2-dev.201710021504
