### ISSUE TITLE
kendoComboBox re-enter value on items loaded

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#852]
* Bug report 

## Current behavior
If you define open event in kendo-combobox and in event handler remotely load items value is filled with some value, when remote server response, even if you change value before server loads items. **It changes currect value.**

## Expected behavior
kendo-combobox should load items but not automatically select an item (fill value with one of loaded items). Maybe even open popup.

## Minimal reproduction of the problem with instructions
```
<kendo-combobox [data]="parameter.values"
         textField="value"
         valueField="id"
         [allowCustom]="true"
         [valueNormalizer]="intNormalizer"
         [value]="parameter.selectedValue"
         (valueChange)="changeParameterValue(parameter, $event)"
         (open)="loadDropDownListItems(parameter)"></kendo-combobox>
```

```
public loadDropDownListItems(parameter: IConfigurationParameter)
    {
        if (!parameter.values)
            this.configuratorService.listPartParameterValues(parameter.id).subscribe(result => parameter.values = result);
    }
```

## What is the motivation or use case for changing the behavior?
It is really annoying and user not-friendly.

## Environment
Package versions:
```
+-- @progress/kendo-angular-dropdowns@1.1.3
```

Browser:
- Chrome (desktop) Version 60.0.3112.101

System:
- TypeScript version: 2.1.6
- Node version: 4.6.1
- Platform: Windows

As they say image says more then 1000 words.
In first combobox I press backspace and value should stay 85, but combobox fill it with 850.
In second combobox I select all and press 1, but combobox fill it with 2000 (when items loads)
![2017-08-25_08-19-54](https://user-images.githubusercontent.com/1589573/29701783-2f7b589e-896e-11e7-9c9e-b0dafc387674.gif)

**Comment by tapopov** [comment]
Hello @MaklaCof,

I tried reproducing this using `kendo-angular-dropdowns` v1.2.0, but to no avail. Would you please share more details about your setup? For example, what does the data look like, and what kind of data is used once the `open` event is triggered? Are the datasets identical or they have different key/value pairs? Are there overlapping IDs having different values? Sharing a small plunkr where this is isolated will really help us identify what's causing the issue. Last but not least, is this behavior still observed when using the latest `dev` version of the `kendo-angular-dropdowns` package?

**Comment by MaklaCof** [comment]
Hello, 
it will take a few days, because I did same major changes and can't upgrade to latest version right now.

**Comment by MaklaCof** [comment]
Hi, 
I tried with `"@progress/kendo-angular-dropdowns": "^1.2.1"`, and it is not working, so I prepare [plunkr](http://plnkr.co/edit/REW2hFA2D9j5WSlNDAOw?p=preview).

Just enter custom value and it will be overridden after 1 second when results load from "server".

**Comment by tapopov** [comment]
Thanks @MaklaCof 
We will investigate and post updates as we know more.

**Comment by tapopov** [comment]
Hello @MaklaCof 
I can confirm that this scenario is currently not handled as expected. We'll release a fix soon and in the meantime you can enable the filtering as a workaround. Here's a working [plunkr example](http://plnkr.co/edit/UGv4CzFLJF5QM6sp1TCl?p=info).

**Comment by MaklaCof** [comment]
I just found the time to upgrade and it works. Thank you.
