### ISSUE TITLE
Incorrect slider calculations with fractional step

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-angular#853]
Example: http://plnkr.co/edit/znsmzbd3AkLl2SwgIT5i?p=preview

To reproduce, use the increase and decrease buttons.

**Comment by siyka-marinova** [comment]
Needs further fix - some of the fractional values that the slider shows when moving the handle are not properly rounded [(https://www.screencast.com/t/mDynPz0Zg).](https://www.screencast.com/t/mDynPz0Zg) Tested with `@progress/kendo-angular-inputs@1.2.0-dev.201709011333`

**Comment by siyka-marinova** [comment]
Fixed in the dev version of the kendo-angular-inputs package: `@progress/kendo-angular-inputs@1.3.0-dev.201709060902`

**Comment by siyka-marinova** [comment]
Released in `@progress/kendo-angular-inputs@1.3.0`
