### ISSUE TITLE
ComboBox - highlight an item when filtering is enabled

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#854]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
ComboBox with filtering does not highlight the first item, whereas when there is no filtering, it does. 

Perhaps we should consider either providing means for selecting an item when the component's data is filtered, or select the first item, matching the filter, by default, for consistency with the behavior when the component is not filterable.

For further details see Ticket ID 1126617

**Comment by siyka-marinova** [comment]
Currently, the matching item is highlighted if the filtering criteria is "starts with". The matching item is not highlighted if the filtering criteria is "contains". We can improve this further by adding the highlight on an item that contains the filter text.
For example, in this [plunker](http://plnkr.co/edit/3MtESWTIW5335Lnuikzu?p=preview) search for "beer". It will be good to highlight the first item containing the filter text "beer" (as we do when the filter we apply is "split", for example)

**Comment by tapopov** [comment]
Since the component is unaware of the filter operator, the best we can do is always highlight the first result.

**Comment by JaapMosselman** [comment]
I would not select anything when suggest=false, as it is now.
But when suggest=true, perhaps you can select the first item within the filtered items, which matches the "starts with" criteria, just like when using suggestion without filtering.
Currently it is displaying already the correct suggestion in the input box, but it is not selected when leaving the control. So you are almost there.

**Comment by JaapMosselman** [comment]
So to summaries (after thinking in the weekend :-) ):

- When suggest=false, nothing should be selected automatically, with or without filtering. No changes needed I think.

- When suggest=true, no filtering, the first item matching "starts with" is suggested in the input box and when tabbing out, it is made the current value. Fine

- When suggest=true, with filtering (doesn't matter how implemented, e.g. with a "contains"), it works half way. The correct suggestion is shown in the input box when typing, matching the first item matching "starts with" form the filtered items. Just perfect. **But the thing missing is, that, when tabbing out, that item is not made the current value**. That's only thing I would like to change.

**Comment by JaapMosselman** [comment]
Created a [plunker](http://plnkr.co/edit/ey1aeR3LgmUXobOnsId2?p=preview) to demonstrate what is going wrong (in my opinion). In the combobox, type "lar". You will see the item list is filtered and the item "Large" is suggested. Then tab out the field: value of the combobox is not changed

**Comment by tapopov** [comment]
Thanks for the input @JaapMosselman. We'll address how the value changes on blur (given the text matches an actual data item).

**Comment by JaapMosselman** [comment]
Looks like the enhancement I suggested is already made in the @dev channel.

**Comment by ipeshev** [comment]
Fixed in 1.2.2-dev.201710021504 (2017-10-02)
