### ISSUE TITLE
Documentation Issue: Grid Inline Editing

### ISSUE THREAD

**Issue by davidboothe** [telerik/kendo-angular#855]
There is an error in the example under step 3 on this page: http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-row-click/

the documentation has the save click event as such:

`(saveRow)="saveClick()"`

this should be changed to

`(saveRow)="saveClick($event)"`

this will not cause an error when running in development but without the $event you will get a compile error when you try to run

`ng build --prod`

**Comment by dmihaylo** [comment]
@davidboothe thank you for your feedback! We've already addressed the issue and I'll be closing it now.
