### ISSUE TITLE
Popup alignment on DropDownButton/SplitButton

### ISSUE THREAD

**Issue by j-pdx** [telerik/kendo-angular#858]
I guess this would be a feature request since I don't see any way to change this behavior in the API documentation. I need an option to have the popup menu aligned to the right side of the button instead of the left (default).

If I have the button against the right side of the screen, the menu doesn't align with the button properly.

![screenshot 2017-08-28 14 19 43](https://user-images.githubusercontent.com/1747494/29795085-990a94ee-8bff-11e7-86a4-ad6c222e63bf.png)

**Comment by LaniMoo** [comment]
Aligning the button to the right also forces the menu to wrap, which doesn't look very good:

![cursor_and_windows_10_x64_-_base](https://user-images.githubusercontent.com/24845394/49557504-bc361080-f8bc-11e8-82d8-e6887bee59ef.png)

Unlike kendo's Dropdownlist, there's no `width` property available for `popupSettings`, which I would normally set to `'auto'`.

**Comment by colinparker-er** [comment]
I'm running into the same problem with buttons on the right-hand side of the screen, so wanted to add a vote to have this capability added. Thanks.

**Comment by tsvetomir** [comment]
Fixed in v4.4.0
