### ISSUE TITLE
Grid Column Text Highlighting

### ISSUE THREAD

**Issue by TrevorBroderick1** [telerik/kendo-angular#861]
## I'm submitting a...
* Bug report

## Current behavior
You can't highlight text in grid columns when selection is enabled.

It will only allow you to highlight text if checkboxOnly mode is set for selection.

## Expected behavior
You should always be able to highlight text on a grid column.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/h9Qfp9XXF4HIzNtH9wUZ?p=preview

## What is the motivation or use case for changing the behavior?
So that the user can copy and paste text from the grids.

## Environment

Browser:
- Chrome (desktop) version 60.0.3112.101

System:
- TypeScript version: 2.5.0
- Node version: 8.1.0
- Platform:  Windows

**Comment by siyka-marinova** [comment]
Fix for this issue is currently available in the latest dev. version of the kendo-angular-grid package: `@progress/kendo-angular-grid@1.4.0-dev.201708311144`. The official package will be released shortly.

**Comment by siyka-marinova** [comment]
Released `@progress/kendo-angular-grid@1.4.1`
