### ISSUE TITLE
kendo-datepicker - hard to change year

### ISSUE THREAD

**Issue by monkeecheetah** [telerik/kendo-angular#862]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
You have to scroll through all the months to change year.

## Expected behavior
The old date-picker was easier to switch from ie. 2013 to 2017 without scrolling through all the years. You can type but feels harder than it should to switch between years.

## Minimal reproduction of the problem with instructions
Add datepicker to a kendo-angular project.

Try to choose a date that is a couple of years from current chosen date.

## What is the motivation or use case for changing the behavior?
When working with dates that is long between, ie. startdate and enddate for employers.

Browser:
- Chrome (desktop) version XX

**Comment by ggkrustev** [comment]
@monkeecheetah, thanks for the suggestion and for the opened issue. [The requested enhancement](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18990187-calendar-picker-component-fast-navigation) is already planned and the feature is under active development.

I will update the thread once an early preview is available.

**Comment by ggkrustev** [comment]
Hey guys, the latest official release of `@progress/kendo-angular-dateinputs` (v1.3.0) includes the `fast navigation` feature. Please give it a try.

https://www.telerik.com/kendo-angular-ui/components/dateinputs/calendar/

**Comment by ggkrustev** [comment]
Closing this issue as resolved, because the feature is out and working.
Please feel free to comment if something is not clear.

**Comment by JaapMosselman** [comment]
Nice work!
The only remark I have is that I feel it is not very visible/intuitive for the user that they can click on the month-year label. The TODAY label is more intuitive, because of the text, the user thinks: "perhaps as I click on it, I select the date of today". But the month-year label does not attract the user the try the nice feature behind it. Only when he by accident hovers over the label, he recognizes that it is clickable. It should perhaps be a bit more visible that it is a clickable element.

**Comment by yordanov** [comment]
Thanks for the feedback @JaapMosselman. Appreciated. We do agree it is not that visible. 

In our cautious efforts not to clutter the UI with what might happen to be unnecessary hints, we decided to proceed this way and see what people think about it. The introduction of additional UI elements might unintentionally focus users’ attention in a direction that is wrong for a specific task. The current behavior mimics the [Kendo UI for jQuery Calendar](http://demos.telerik.com/kendo-ui/calendar/index), in which no initial hint is available. 

The said, let’s give users time to test and get used to this new functionality, gather feedback and make an informed decision whether we add a hint or not. In the meantime you can easily tweak e.g. underline the header title as show in this [Plunker](http://plnkr.co/edit/mEIM7U4QzwWPVLTiHw1N?p=preview).
