### ISSUE TITLE
Copy anchor font styles to popup container

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#865]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Detached popups do not inherit the font of the component, which does not look good.

![image](https://user-images.githubusercontent.com/90405/29920807-f60dd3a4-8e57-11e7-9abd-37dffdbc8712.png)

## Expected behavior
Introduce a `copyAnchorStyles` option, [like the one in the jQuery widgets](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.popup.js#L248-L253) (true by default).

**Comment by ggkrustev** [comment]
Done. Available in `1.4.0` release.
