### ISSUE TITLE
[Button] Remove [bare] property binding

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular#866]
## Current state

- The Button component exposes `bare` property binding that is used to change the default appearance of the component.
- User is able to change the default appearance also by adding manually pre-defined classes to the Button element such as `k-flat` and `k-outline`.

```
<button kendoButton [bare]="true">Bare Button</button>
<button kendoButton class="k-flat">Flat Button</button>
<button kendoButton class="k-outline">Outline Button</button>
```

## New state

- `bare` property binding will be removed
- `type` property binding will be added, it will accept string value that will specify the style of the button

```
<button kendoButton [type]="'bare'">Bare Button</button>
<button kendoButton [type]="'flat'">Flat Button</button>
<button kendoButton [type]="'outline'">Outline Button</button>
```

Combining multiple appearance types is **not supported**.

```
<!-- not supported -->
<button kendoButton [type]="'bare, flat'">Not supported</button>
```

Combining appearance type with functional type (primary, togglable) **is supported**.

```
<!-- togglable flat button -->
<button kendoButton [type]="'flat'" [togglable]="true">Flat togglable button</button>
```

**Comment by gyoshev** [comment]
@joneff raised a very good question, how will this work with the HTML `type` attribute of the button (e.g. `<button type="submit">`, `<button type="reset">`)? We should probably rename the property to something that doesn't clash with the predefined HTML attributes. Some suggestions: `mode` or `kind` or `buttonStyle`.

**Comment by valchev** [comment]
Good point, in my opinion `look` sounds like the best replacement.
