### ISSUE TITLE
[ButtonGroup] Add [type] property binding

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular#867]
The `type` property binding will be used to define the type of all buttons inside a button group.
Possible types are:

- default (no need to set the `type` property binding)
- flat
- bare
- outline

Button group `type` property will take precedence over the `type` property of the individual buttons that are part of the group.

```
<kendo-buttongroup type="'flat'">
  <button kendoButton>1</button>
  <button kendoButton>2</button>
</kendo-buttongroup>
```

When the `type` of the group is set, its host element will receive CSS class that corresponds to the type:

- flat -> `k-button-group-flat`
- bare -> `k-button-group-bare`
- outline -> `k-button-group-outline`

Prerequisites: telerik/kendo-angular#866

**Comment by tsvetomir** [comment]
Shipped in `@progress/kendo-angular-buttons` v2.0.0
