### ISSUE TITLE
ComboBox in template driven form not clearing model value when clearing the combobox

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#871]
## I'm submitting a...
* Bug report

## Current behavior
When Combobox has filtering enabled and uses ngModel, the underlying value in the model is not cleared when the combobox is cleared with the keyboard.
When filtering is disabled or the clearbutton is used, the model is cleared correctly.

## Expected behavior
Clear the model value, when using the keyboard to clear the input value.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/lGeonnLM4xeyFiH9zWYs?p=preview

## What is the motivation or use case for changing the behavior?
Usability

**Comment by JaapMosselman** [comment]
I fixed it in a local copy of the source. If you are interested, let me know.

**Comment by tapopov** [comment]
Related to https://github.com/telerik/kendo-angular/issues/824. A fix should be available in the dev channel this week.

**Comment by ipeshev** [comment]
Fixed in v1.2.2-dev.201709281629
