### ISSUE TITLE
Is there any way of doing chunking in Kendo-upload with Angular as I found something with JQuery

### ISSUE THREAD

**Issue by ranag14** [telerik/kendo-angular#872]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Raisolution** [comment]
Hi @ranag14,

This behavior is currently not supported, but it is in our future plans for implementing. No specific time span is set yet.

**Comment by tsvetomir** [comment]
Just a reminder to cast your vote for this feature on our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback). This will help us prioritize future development.
