### ISSUE TITLE
Scrollview prevents scrolling up/down on mobile

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#875]
## I'm submitting a 
* Suggestion for improvement

## Current behavior
The Scrollview does not allow scrolling up/down when the touch event targets the Scrollview on mobile.

## Expected behavior
The user should be able to scroll the page up/down.

## Minimal reproduction of the problem with instructions
Observe in the online demo: 
[http://www.telerik.com/kendo-angular-ui/components/scrollview/](http://www.telerik.com/kendo-angular-ui/components/scrollview/)

## Environment
Touch/mobile devices

**Comment by JaapMosselman** [comment]
I just encountered the same issue. ScrollView should only trigger on horizontal swipes. Vertical swipes should just bubble up.
In addition, for my particular situation, it would be fine to have property to disable dragging (and left/right arrowkeys) completely, so the user can not have any interaction with the scrollview.

**Comment by JaapMosselman** [comment]
Is there any way to fix this in my own code? In my particular case it would be fine if the ScrollView would not interact with any touch event.

**Comment by Raisolution** [comment]
We are closing this issue, as it is no longer reproducing the latest versions of the [Scrollview](https://www.telerik.com/kendo-angular-ui/components/scrollview/).

If you are still experiencing it, please specify the exact device and OS being used.
