### ISSUE TITLE
Calendar: Navigation bar displays incorrectly on different font-sizes

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#876]
Currently the оnly way to control the calendar width is to change its font-size, and users are likely to want to do this. However, the navigation bar does not calculate its offset correctly:

![image](https://cloud.githubusercontent.com/assets/90405/25382219/532ad9b8-29bf-11e7-9ebf-de7ffc2902dc.png)

In the figure above, October is focused, but the navbar shows December.

http://plnkr.co/edit/V5bT8hA6blqjH1JzAima?p=preview

**Comment by JaapMosselman** [comment]
Also the top label with the month and year can get  out of sync when you are scrolling.
![small calendar](https://user-images.githubusercontent.com/22192317/30095803-28c82ea8-92d5-11e7-9308-c2a136821cce.PNG)

(The plunker above seems to have a problem. [Here ]([http://plnkr.co/edit/7piD4my1e5k4F8vkqEEr?p=preview]is another.)

**Comment by ggkrustev** [comment]
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
