### ISSUE TITLE
Context Menu on every Grid Row

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#877]
I just would like to implement context menu on single row of grid.

Any best practice here? i could add context menu event on every cell of a row but it is not so "smart" as approach for a big grid and a lot of data.

Thanks.
Diego

**Comment by dtopalov** [comment]
Introducing a context menu component is currently not among our immediate plans, but we have an opened feature request that you can vote for in our UserVoice portal:

[http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18428263-contextmenu-component](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/18428263-contextmenu-component)

... and we can consider creating such a component, if the idea gains enough popularity among the community.

Meanwhile you can try some of the following relatively straightforward custom implementations:

[http://plnkr.co/edit/pZIpV7cBCYW3mz17DKOY?p=preview](http://plnkr.co/edit/pZIpV7cBCYW3mz17DKOY?p=preview)

[http://plnkr.co/edit/5AXdk3vldXJdKta5Kjbu?p=preview](http://plnkr.co/edit/5AXdk3vldXJdKta5Kjbu?p=preview)

The former utilizes the [cellClick event](http://www.telerik.com/kendo-angular-ui/components/grid/api/GridComponent/#toc-cellclick), while the latter - a Popup component with a custom content and anchor.
