### ISSUE TITLE
TimePicker Now button should close the popup

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#878]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
Clicking the Now button does not close the popup.

## Expected behavior
Clicking the Now button should close the popup.

## Minimal reproduction of the problem with instructions
See standard demo

## What is the motivation or use case for changing the behavior?
Skipping the unnecessary click on Set and be more consistent with the DatePicker.

**Comment by ggkrustev** [comment]
This is already implemented and the next release of `@progress/kendo-angular-dateinputs` will include this behavior. You can test it in `@dev` channel for now.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.2.0` is out and includes the required behavior.

**Comment by JaapMosselman** [comment]
I can confirm that is works.
