### ISSUE TITLE
Add mouse wheel support in ComboBox and DropDownList

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#882]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When the ComboBox or DropDownList is focused (and popup closed) you can use arrow up and down to select next or previous value in the list. But the mouse wheel does not work. The date-inputs supports this, so now there is no consistent user input experience.

## Expected behavior
Scrolling with mouse wheel should select next or previous value in the list just like the arrow up and down key.

## Minimal reproduction of the problem with instructions
Standard demo example.

## What is the motivation or use case for changing the behavior?
Consistent user input experience.

**Comment by ggkrustev** [comment]
The Kendo ComboBox/DropDownList components strives to provide an enhanced [*HTML Select like*](https://www.w3.org/wiki/HTML/Elements/select) control.

As far as I know, the `<select>` control doesn't select different value on mouse wheel. That being said, such functionality will introduce an inconsistent behavior with the `<select>` control.

In order to schedule the required enhancement for further investigation, we will need to gather community feedback for it. I would suggest you open a UserVoice discussion on the topic.

http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback

Our decision for future implementation will depend entirely on the feedback and interest in the feedback portal.

I will close the issue, as it should be moved in the UserVoice portal.

**Comment by JaapMosselman** [comment]
Browser vendors are not consistent in the implementation of Select. In Chrome mouse wheel does indeed not work, but in Edge it is working. Would create a nice Select like :-).
http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/31209040-enable-mousewheel-scrolling-in-combobox-inputfield

**Comment by ggkrustev** [comment]
Seems to be a proprietary IE/Edge feature, as it doesn't work in Chrome, Firefox or Safari.
Thanks for posting the request in the UserVoice portal.

**Comment by JaapMosselman** [comment]
I already implemented this feature (for ComboBox) in a local copy of the source code. I you are interested to see the changes I did, let me know...

**Comment by salmanfa1992** [comment]
Hey, for Angular I just created a directive that listens to the mouse wheel event and then sets the selected item for the combobox accordingly.

@Directive({
  selector: '[appMouseScrollCombobox]'
})
export class MouseScrollComboboxDirective {

  @Output() onValueChanged: EventEmitter<any> = new EventEmitter();

  constructor(private combobox: ComboBoxComponent) { }

  @HostListener('mousewheel', ['$event'])
  scroll(event: WheelEvent) {    

    if (this.combobox) {
      let dataList: any[] = this.combobox.data;
      if (dataList && dataList.length > 0) {

        if (event.deltaY < 0) {
          this.goUp(dataList);
        } else {
          this.goDown(dataList);
        }
      }
    }
  }

  private goDown(dataList: any[]) {
    let selectedItem = this.combobox.value;
    if (selectedItem) {
      let selectedIndex = dataList.indexOf(selectedItem);
      if (selectedIndex !== dataList.length - 1) {
        this.combobox.value = dataList[selectedIndex + 1];
        this.onValueChanged.emit(this.combobox.value);
      } else { 
        // Last item in the list, cannot go down
      }
    } else {
      this.combobox.value = dataList[0];
      this.onValueChanged.emit(this.combobox.value);
    }
  }

  private goUp(dataList: any[]) {
    let selectedItem = this.combobox.value;
    if (selectedItem) {
      let selectedIndex = dataList.indexOf(selectedItem);
      if (selectedIndex !== 0) {
        this.combobox.value = dataList[selectedIndex - 1];
        this.onValueChanged.emit(this.combobox.value);
      } else {
        // First item in the list, cannot go up
      }
    } else {
      this.combobox.value = dataList[0];
      this.onValueChanged.emit(this.combobox.value);
    }
  }

}

----------------------------

Using the directive:

<kendo-combobox id="va"
                                name="va"
                                [data]="vaScaleList"
                                [textField]="'value'"
                                [valueField]="'id'"
                                [(ngModel)]="selectedVa"
                                [placeholder]="placeHolderVac"
                                **appMouseScrollCombobox (onValueChanged)="onSelectedVaChangedByScroll($event)"**>
                </kendo-combobox>

**Comment by JaapMosselman** [comment]
Thanks for the interesting idea @salmanfa1992 .
I want to get rid of my customized kendo UI dropdowns packages and use the standard of telerik.
I already have wrapped the combobox component in an own wrapper component, so I think I can add this code in one place.
Want to spend some time on it soon.

**Comment by salmanfa1992** [comment]
Great!
