### ISSUE TITLE
Allow spinners to be disabled for the grid's numeric editor

### ISSUE THREAD

**Issue by simonneedham** [telerik/kendo-angular#887]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When using the grid's numeric editor, spinners are always visible. It would be nice if there was a convenient way to switch them off with an attribute, rather than resorting to define a template.

## Expected behavior
Being to define a column with a spinner-less numeric textbox like this would be handy.
`<kendo-grid-column field="UnitPrice" editor="numeric" [spinners]="false" title="Price"></kendo-grid-column>`

**Comment by rkonstantinov** [comment]
Hi @simonneedham,
I'm afraid that this is not possible. Exposing all of the possible built-in editors options as top level column settings will result in explosion of options, which beside confusing, will not work together. This is why customizing the editor components should be done via editor template.
