### ISSUE TITLE
two grid with checkbox each will cause error

### ISSUE THREAD

**Issue by wenminglee** [telerik/kendo-angular#888]
If in one page with two grid, every grid with a checkbox column, when checked the second grid checkbox cell, the first grid checkbox cell will be checked, the reason is they have the same checkbox id.
![image](https://user-images.githubusercontent.com/25415660/30156618-b38a1a24-93f2-11e7-856d-f1faa37607e8.png)

**Comment by Raisolution** [comment]
Thank you for reporting this behavior, we will address it.

**Comment by nghiado** [comment]
@Raisolution This is a critical bug for us since we have multiple grid on the same screen as well. . Do you have ETA when this is fixed?

**Comment by Raisolution** [comment]
Hi guys,

The fix is available in the `v1.4.2-dev` version and will soon be released in an official one too.
