### ISSUE TITLE
Shift+Home/End keys do not work as expected in ComboBox

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#890]
## I'm submitting a...
* Bug report

## Current behavior
When the input field of the cursor has the focus and you want to select text from cursor position to start or end with Shift+Home or Shift+End, this is not working. Instead the first or list item of the list is set as if Home or End was pressed.

## Expected behavior
Shift+Home or Shift+End should select text and the list should ignore it. Send key events to list service only when not meta keys are pressed.

## Minimal reproduction of the problem with instructions
Just standard Combobox demo.
Choose last item in the list. Then place cursor at the end of the input field. Then press Shift+Home. Instead of selecting whole text, the first item of the list is set.

**Comment by ipeshev** [comment]
Currently sole HOME and END button does not work as expected

**Comment by tapopov** [comment]
Home and End buttons should not select from or navigate through the list. The documentation will be updated shortly to reflect the changes recently implemented.
