### ISSUE TITLE
Translatable "NO DATA FOUND" string

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#896]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
"NO DATA FOUND" string used in DropdownsPackage is not translatable via MessageService 

## Expected behavior
It should be translatable via [MessageService](http://www.telerik.com/kendo-angular-ui/components/localization/messages/#toc-using-the-message-service)

## What is the motivation or use case for changing the behavior?
Consistency with other packages

## Environment
Package versions:
v1.2.0
Browser:
N/A

**Comment by Jahrenski** [comment]
Any news on this? There is no way to translate this bit and makes it unusable for production unless I'm missing something.

**Comment by valchev** [comment]
@Jahrenski currently you can change the text via template. Check [this example](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/templates/#toc-no-data-template).

**Comment by tapopov** [comment]
Fixed in kendo-angular-dropdowns 3.1.0 (2018-09-20)
