### ISSUE TITLE
Introduce a 'display:flex' fallback to support IE9

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular#898]
## Description
The Calendar component uses `display: flex` to layout its content. This styling, however, is not supported in IE9. The only solution is introducing a fallback styling (parallel styling that works in IE9).

## Current behavior
Calendar doesn't display anything.
![90e7d108-a53b-47c2-bb31-88e2d26074cf_messageimage_1505098923097](https://user-images.githubusercontent.com/495188/30313384-cb69f360-97a5-11e7-9208-669284773d33.jpg)

## Expected behavior
Calendar should work as expected.

## Minimal reproduction of the problem with instructions
Open simple `<kendo-calendar></kendo-calendar>` component in IE9. 

Note to include all required polyfills:

https://angular.io/guide/browser-support#polyfills

## Environment

Package versions:
├── @angular/animations@4.3.6
├── @angular/common@4.3.6
├── @angular/compiler@4.3.6
├── @angular/compiler-cli@4.3.6
├── @angular/core@4.3.6
├── @angular/forms@4.3.6
├── @angular/http@4.3.6
├── @angular/platform-browser@4.3.6
├── @angular/platform-browser-dynamic@4.3.6
├── @angular/platform-server@4.3.6
├── @progress/kendo-angular-intl@1.2.2
├── @progress/kendo-angular-l10n@1.0.3
├── @progress/kendo-angular-popup@1.2.0
├── @progress/kendo-angular-tasks@9.1.31
├── @progress/kendo-date-math@1.0.3
├── @progress/kendo-theme-default@2.41.0
├── @telerik/semantic-prerelease@1.2.1
├── @types/core-js@0.9.35
├── @types/zone.js@0.0.27
├── codelyzer@3.1.2
├── core-js@2.5.0
├── rxjs@5.4.3
├── typescript@2.3.4
└── zone.js@0.8.12

Browser:
- IE version 9

System:
- TypeScript version: 2.3.4
- Node version: 6
- Platform:  all

**Comment by ggkrustev** [comment]
Reported in https://github.com/telerik/kendo-angular/issues/884 Also mentioned in TicketID: 1129261, 1129742

**Comment by gyoshev** [comment]
We have introduced specific instructions on how to target IE9 when using Kendo UI for Angular in the [Browser Compatibility help topic](http://www.telerik.com/kendo-angular-ui/components/styling/ie9-support/).
