### ISSUE TITLE
404 Not Found: @progress/kendo-angular-pdf-export@latest

### ISSUE THREAD

**Issue by richqez** [telerik/kendo-angular#904]
npm install --save @progress/kendo-angular-pdf-export @progress/kendo-drawing

404 Not Found: @progress/kendo-angular-pdf-export@latest

**Comment by tsvetomir** [comment]
The package seems functional to me:
```sh
(~) npm info @progress/kendo-angular-pdf-export 'dist-tags'
{ dev: '1.0.0-dev.201708101403', latest: '1.0.0' }
```

Are you, by any chance using the Progress NPM Registry? It has been deprecated for a while, see #712
