### ISSUE TITLE
[Bug] Dropdown with filtering not closing

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular#905]
* Bug report

## Current behavior

When you use the DropDownlist with filtering enabled, then you can open the dropdownliste but when you directly try to close the dropdownlist by clicking at the same location where you open the dropdownlist, its not working it closes and reopens the ddl directly again, and so you can't close it. Only when you click somewhere else in your screen so that the dropdownlist looses focus and then click at the location where you opened it it closes.

It only happens on ddls where you see the filter input

## Expected behavior

You should allways be able to open and close the dropdownlist without selecting any value. 

## Minimal reproduction of the problem with instructions

Look at your own example there its not working in Chrome and FF I've tested it so far.

http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/

Browser:
- Chrome desktop newest version
- FF Destop newest version

**Comment by valchev** [comment]
@squadwuschel thank you for bringing this to our attention. We will investigate the case and provide  fix as soon as possible.

**Comment by valchev** [comment]
duplicates telerik/kendo-angular#688

**Comment by tsvetomir** [comment]
Closing as duplicate.
