### ISSUE TITLE
Themebuilder output breaks grid filter row

### ISSUE THREAD

**Issue by mac-bhaird** [telerik/kendo-angular#907]
## I'm submitting a...

* Bug report  

## Current behavior
Using themes from the theme builder breaks the grid filter row resulting in undesirable vertical white space

## Expected behavior
Using themes from the theme builder doesn't alter the dimensions of an element, only the colors

## Minimal reproduction of the problem with instructions
1. Generate a theme from themebuilder
2. Download the css
3. Add to project
4. Observe grid filter row anomalies

Example: http://plnkr.co/edit/TiITHXdJl8x0PWywaq3a?p=preview

**Comment by joneff** [comment]
The issue in question is that we haven't updated ThemeBuilder in a while so it's using old themes as a base. I've tested internally with the next update of ThemeBuilder with update bootstrap theme and it works as expected.

One minor note -- you don't really need to include both theme-default and theme-bootstrap styles, just one. Unlike the less-based themes, the sass themes for KendoUI produce self contained theme.css files.
