### ISSUE TITLE
Kendo angular 2 UI grid - Common filter for whole i grids not working(Column wise filter is working buth there when i tried common filter for whole grid its not working)

### ISSUE THREAD

**Issue by MidunKumar** [telerik/kendo-angular#908]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by rkonstantinov** [comment]
I'm not sure what you mean by `Common filter for whole i grids`. 
The Grid component does not provide built-in UI for filtering across all of the data fields.

If you need additional assistance, please fill the provided issue template with the appropriate information.

**Comment by MidunKumar** [comment]
Hi  rkonstantinov ,
I will explain clearly what i required,
In current Kendo angular 2 grid there is option to filter for each column for example i have 5 columns in grid if i want filter option in grid i can enable "filterable:true" and it will enable filter for each column but i want to create search filter for whole table for eg.i want to place the search input above the table and if i enter anything in search component it should search whole grid(means of the columns present in the grid) for this only i have raised the above issue
I dint find any documentation for this option in kendo angular 2 UI

Thanks & Regards,
Midun Kumar

**Comment by rkonstantinov** [comment]
@MidunKumar 
This repo is for bug reports only. If you need technical support assistance, please either ask on [SO](http://stackoverflow.com/questions/ask?tags=kendo-ui-angular2,angular2). Or if you are looking for direct support from our team, a valid license which includes Kendo UI provides the ability to submit tickets in our support system.
