### ISSUE TITLE
Popup open animation wrong direction when displayed above component

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#909]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
For components with a popup (like DatePicker, TimePicker, ComboBox and so on), when there is not enough space left below the component, the popup is display above the component. 
But the animation is from top to bottom.

## Expected behavior
Animation should be from bottom to top in this case.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/7zcTMwnA0kWH7hmc2XgJ?p=preview
Resize your browser so that the combobox is just above the bottom edge of the browser window and then open the popup.
Use a browser which supports animations, like Chrome. (Edge seems not to support this animation?)

**Comment by danielkaradachki** [comment]
This issue should be fixed for some time now. Plunker with updated systemjs config:
http://plnkr.co/edit/PDXGy0wzez8fNeFN2UiP?p=preview

**Comment by ipeshev** [comment]
Shipped with v2.1.0
