### ISSUE TITLE
DateInput should not display dateformat placeholders when no date is set and not focused

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#911]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
In the DateInput component, when no date is set, the date format placeholders are displayed.

## Expected behavior
Display the date format placeholders only when the component is focused.
This keeps your screen more clean when you have empty date fields in your form and it is more visible to the user that the field is still empty.
Even better would be to add a placeholder string property (like in NumericTextBox and ComboBox) and show that when the control has no date and is empty.

This applies of course also for DatePicker and TimePicker.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/yhvaISgY9WFy03nEuJpW?p=preview

**Comment by ggkrustev** [comment]
This should be a configuration option related to this enhancement https://github.com/telerik/kendo-angular/issues/859. We haven't thought about the specific configuration structure, but both features should be related.

Please note that unlike NumericTextBox, the DateInput component applies specific date mask. Incomplete date value will still result in "10/day/year" string even if we enable regular placeholder text. This is my reservation in general. We will determine whether to enable free text or not based on the upcoming research.

**Comment by JaapMosselman** [comment]
Incomplete date is still no date. Underlying model will still be empty/null. So I think it would be ok if nothing should be displayed when the component has no focus (or an optional regular placeholder).
When component is focused again, display the incomplete date again.
I think that would be a better user experience.

**Comment by ggkrustev** [comment]
I absolutely agree that an incomplete date is still a `null` (this is how the DateInput works now). 

If the user, however, wants to continue typing from a specific date section, then displaying the regular placeholder won't be a good UX. In other words, typing the `month`, blurring and then focusing the `day` section with the mouse won't be possible with regular placeholder. As I mentioned, there is a hefty list of unexpected scenarios that will occur with such regular placeholder. Native `<input type="date"/>` doesn't provide any placehoder. IMHO the best solution is to provide Label for such masked inputs.

Nevertheless, we haven't given up from the idea of a regular placeholder. We just need to determine whether it will be usable or not. This will be decided once we start the implementation.

**Comment by JaapMosselman** [comment]
Ok, I see there is a lot more to think about.
I think for my situation it would be best to make the text color lighter when there is no date and component is not focused. This way the format placeholder is less emphasized. But I can handle this in my wrapper component which I have created for the Kendo UI component.

**Comment by ggkrustev** [comment]
The feature is available in the latest @dev version of `@progress/kendo-angular-dateinputs`. Just install `@progress/kendo-angular-dateinputs@1.4.0-dev.201711011505`.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. Will close the thread as resolved.
Please feel free to comment if something is not OK.
