### ISSUE TITLE
Publishing a ASP.NET Core 2.0 Angular 4 App with Kendo components in Visual Studio fails

### ISSUE THREAD

**Issue by JStarkl** [telerik/kendo-angular#912]
## I'm submitting a...
* Bug report

## Current behavior
When adding a Kendo package to a new DotNet Core 2.0 Angular 4 Project in Visual Studio, the project runs flawless in Debug-Mode, but if I want to publish it, I get errors

## Expected behavior
The app gets published

## Minimal reproduction of the problem with instructions
* Create a new Visual Studio ASP.NET Core Web Application with Core 2.0 Framework and Angular Template

Run the app => Fine
Publish the app => Fine

* Add a Kendo-Angular Component and the Default Theme
* Use the component and include all.css

Run the app => Fine
Publish the app => Publishing failed

Demo-App: [https://github.com/JStarkl/Angular4KendoTest](url)

    ERROR in ./$$_gendir/~/@progress/kendo-angular-popup/dist/es/popup.component.ngfactory.ts
    Module parse failed: C:\TFS\Angular4KendoTest-master\TestAng\$$_gendir\node_modules\@progress\kendo-angular-popup\dist\es\popup.component.ngfactory.ts Unexpected token (17:27)
    You may need an appropriate loader to handle this file type.
    | import * as i6 from '@progress/kendo-angular-popup/dist/es/services/resize.service';
    | import * as i7 from '@progress/kendo-angular-popup/dist/es/services/scrollable.service';
    | const styles_PopupComponent:any[] = ([] as any[]);
    | export const RenderType_PopupComponent:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,
    |     styles:styles_PopupComponent,data:{'animation':[{type:7,name:'toggle',definitions:[{type:1,
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts 10:0-118
     @ ./ClientApp/boot.browser.ts
    
    ERROR in ./$$_gendir/~/@progress/kendo-angular-dateinputs/dist/es/datepicker/datepicker.component.ngfactory.ts
    Module parse failed: C:\TFS\Angular4KendoTest-master\TestAng\$$_gendir\node_modules\@progress\kendo-angular-dateinputs\dist\es\datepicker\datepicker.component.ngfactory.ts Unexpected token (29:32)
    You may need an appropriate loader to handle this file type.
    | import * as i18 from '@progress/kendo-angular-popup/dist/es/popup.service';
    | import * as i19 from '@progress/kendo-angular-l10n/dist/es/rtl';
    | const styles_DatePickerComponent:any[] = ([] as any[]);
    | export const RenderType_DatePickerComponent:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,
    |     styles:styles_DatePickerComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/components/home/home.component.ngfactory.ts 9:0-145
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
     @ ./ClientApp/boot.browser.ts
    
    ERROR in ./$$_gendir/~/@progress/kendo-angular-dateinputs/dist/es/timepicker/timepicker.component.ngfactory.ts
    Module parse failed: C:\TFS\Angular4KendoTest-master\TestAng\$$_gendir\node_modules\@progress\kendo-angular-dateinputs\dist\es\timepicker\timepicker.component.ngfactory.ts Unexpected token (26:32)
    You may need an appropriate loader to handle this file type.
    | import * as i15 from '@progress/kendo-angular-popup/dist/es/popup.service';
    | import * as i16 from '@progress/kendo-angular-l10n/dist/es/rtl';
    | const styles_TimePickerComponent:any[] = ([] as any[]);
    | export const RenderType_TimePickerComponent:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,
    |     styles:styles_TimePickerComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/components/home/home.component.ngfactory.ts 16:0-145
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
     @ ./ClientApp/boot.browser.ts
    Child
    Hash: ff2dd80b81a5881beddb
    Time: 23635ms
             Asset     Size  Chunks                    Chunk Names
    main-server.js  3.67 MB       0  [emitted]  [big]  main-server
         ./all.css   384 kB          [emitted]  [big]  
    
    ERROR in ./$$_gendir/~/@progress/kendo-angular-popup/dist/es/popup.component.ngfactory.ts
    Module parse failed: C:\TFS\Angular4KendoTest-master\TestAng\$$_gendir\node_modules\@progress\kendo-angular-popup\dist\es\popup.component.ngfactory.ts Unexpected token (17:27)
    You may need an appropriate loader to handle this file type.
    | import * as i6 from '@progress/kendo-angular-popup/dist/es/services/resize.service';
    | import * as i7 from '@progress/kendo-angular-popup/dist/es/services/scrollable.service';
    | const styles_PopupComponent:any[] = ([] as any[]);
    | export const RenderType_PopupComponent:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,
    |     styles:styles_PopupComponent,data:{'animation':[{type:7,name:'toggle',definitions:[{type:1,
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts 10:0-118
     @ ./ClientApp/boot.server.ts
    
    ERROR in ./$$_gendir/~/@progress/kendo-angular-dateinputs/dist/es/datepicker/datepicker.component.ngfactory.ts
    Module parse failed: C:\TFS\Angular4KendoTest-master\TestAng\$$_gendir\node_modules\@progress\kendo-angular-dateinputs\dist\es\datepicker\datepicker.component.ngfactory.ts Unexpected token (29:32)
    You may need an appropriate loader to handle this file type.
    | import * as i18 from '@progress/kendo-angular-popup/dist/es/popup.service';
    | import * as i19 from '@progress/kendo-angular-l10n/dist/es/rtl';
    | const styles_DatePickerComponent:any[] = ([] as any[]);
    | export const RenderType_DatePickerComponent:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,
    |     styles:styles_DatePickerComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/components/home/home.component.ngfactory.ts 9:0-145
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
     @ ./ClientApp/boot.server.ts
    
    ERROR in ./$$_gendir/~/@progress/kendo-angular-dateinputs/dist/es/timepicker/timepicker.component.ngfactory.ts
    Module parse failed: C:\TFS\Angular4KendoTest-master\TestAng\$$_gendir\node_modules\@progress\kendo-angular-dateinputs\dist\es\timepicker\timepicker.component.ngfactory.ts Unexpected token (26:32)
    You may need an appropriate loader to handle this file type.
    | import * as i15 from '@progress/kendo-angular-popup/dist/es/popup.service';
    | import * as i16 from '@progress/kendo-angular-l10n/dist/es/rtl';
    | const styles_TimePickerComponent:any[] = ([] as any[]);
    | export const RenderType_TimePickerComponent:i0.RendererType2 = i0.╔Ácrt({encapsulation:2,
    |     styles:styles_TimePickerComponent,data:{}});
     @ ./$$_gendir/ClientApp/app/components/home/home.component.ngfactory.ts 16:0-145
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
     @ ./ClientApp/boot.server.ts

**Comment by dtopalov** [comment]
The described issue is probably related to the following line in the webpack,config.js file:

[https://github.com/JStarkl/Angular4KendoTest/blob/master/TestAng/webpack.config.js#L22](https://github.com/JStarkl/Angular4KendoTest/blob/master/TestAng/webpack.config.js#L22)

The "include: /ClientApp/," part needs to be removed so that code, related to Angular components that is located outside this folder can be properly processed and included in the bundle.

Here is the related issue from the JavaScript services repository:

[https://github.com/aspnet/JavaScriptServices/issues/1168#issuecomment-320026397](https://github.com/aspnet/JavaScriptServices/issues/1168#issuecomment-320026397)
