### ISSUE TITLE
Filter Virtual Grid: Scroll not updated

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#915]
Here how to reproduce:

1. Go: http://plnkr.co/edit/V3IceRYOFq4rvkVAYULE?p=preview
2. Scroll to the end of the grid
3. Push filter button
4. You see now `No records available.` label is floating. It is not on top.

Same when filter returns few results. Scroll is not correctly updated.

**Comment by rkonstantinov** [comment]
When filtering the skip should also be reset as otherwise the component will stay on a non-existing page. Resetting the skip will also move the scroller to the top.

**Comment by meriturva** [comment]
Perfect...it works! Thanks!

**Comment by meriturva** [comment]
@rkonstantinov i have to reopen issue due to a strange effect when filter has no result and i reset skip property to zero.
How to reproduce:

1.  Open http://embed.plnkr.co/rgDxsUBBLHPAJ2IUR1x2/
2.  Scroll down
3.  Apply filter
4.  No record label is wrong positioned

**Comment by ipeshev** [comment]
Fixed in v1.4.1-dev.201709071058
