### ISSUE TITLE
Kendo Switch doesn't expand for larger labels

### ISSUE THREAD

**Issue by isatemple** [telerik/kendo-angular#917]
## I'm submitting a...

* Bug report 

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by ggkrustev** [comment]
@isatemple, thanks for the bug report. In order to continue with the investigation we will need a runnable demo and a specific reproduction steps. Could you fill in the missing parts of the template form suggested during the issue submission?

**Comment by tsvetomir** [comment]
The switch renders with a fixed size. This is by design. /cc @yordanov 

A switch with variable size is not on our plans.

**Comment by yordanov** [comment]
The Switch component is used to toggle and visually indicate the state of a single option. Its core functionality, and respectively appearance, are identical to RadioButton/CheckBox.

Introduction of larger inline labels is in contrast with component's main purpose and usage. 

E.g. Material guidelines deprecated inline labels: ["The on/off slide toggle with the text “on” and “off” included within the asset is deprecated."](https://material.io/guidelines/components/selection-controls.html#selection-controls-switch)
