### ISSUE TITLE
Add floatingLabel functionality to all input box components

### ISSUE THREAD

**Issue by gyoshev** [telerik/kendo-angular#918]
Currently the `<kendo-textbox-container>` component introduces the `floatingLabel` property that allows floating labels to be added to HTML `<input>` components. This issue tracks the implementation status of the `floatingLabel` property in other Kendo UI for Angular components.

**Comment by ashkandaie** [comment]
The feature works when placed inside the root module [(plunker)](http://plnkr.co/edit/aVEMx83KQaHDIXaEOyKJ?p=preview). Does not work inside a child module [(plunker)](http://plnkr.co/edit/eS0CjutstRxFM3aLvr3i?p=preview).

**Comment by gyoshev** [comment]
This feature has been added to the latest **inputs** and **dropdowns** packages, as well as the **dateinputs** [development channel](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

Note that for the functionality to work, you need to bind the component to a form field, with either a template or a reactive form. This limitation might change when #1127 is fixed.

[This plunker demo](https://plnkr.co/edit/0d8x54m0DHGVmDdXSPTs?p=preview) shows this functionality. It also demonstrates version `0.3.0` of the Material theme, which is available for these components.

**Comment by gyoshev** [comment]
The feature and the theme have been released officially, so this issue is now closed.
