### ISSUE TITLE
kendo grid breaks when I manipulate kendo grid

### ISSUE THREAD

**Issue by premiumwd** [telerik/kendo-angular#919]
trying to manipulate kendo grid and want to filter automatically by this value. However it messes with kendo grid when I try to manipulate the controls on the front end. Can you help me out? Where would I put this code so it fires with kendo grid.

tysm.

```
 var s = document.querySelectorAll('.k-grid thead tr:not(:last-child) th');
    var a = document.querySelectorAll('.k-grid thead tr:last-child th');

        for (var i = 0; i < s.length; i++) { 
          var d = document.querySelectorAll('.app-viewer .k-grid thead tr th a');
          var c = d[i].textContent.replace(/\s/g, '').toLowerCase();
          
          a[i + 1].className = c;
        } 
 
document.querySelector('.status input').value = 'active'; 
```

**Comment by tsvetomir** [comment]
Manipulating the DOM directly as an anti-pattern in Angular and we don't recommend.

Instead, you can build the initial [filter conditions](http://www.telerik.com/kendo-angular-ui/components/dataquery/#toc-filtering) and add bind them to the [filter property](http://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/). See [plunkr](http://plnkr.co/edit/3i8K2y8X04ipEXqMHeph?p=preview).

**Comment by premiumwd** [comment]
thank you very much.
