### ISSUE TITLE
Does Kendo-angular support Angular 4.4 ?

### ISSUE THREAD

**Issue by OAlQuaseer** [telerik/kendo-angular#921]

**Comment by rusev** [comment]
We are not aware of any issues with latest 4.x version of Angular. 

The Grid examples seems to work properly. Here is a quick example - http://plnkr.co/edit/OeHp30hBSrcXbIQ9TOov?p=preview

**Comment by tsvetomir** [comment]
@OAlQuaseer are you getting errors similar to the ones in #922?

**Comment by tsvetomir** [comment]
All packages are now compatible with Angular 5 RC1, so 4.4 shouldn't pose a problem.
