### ISSUE TITLE
Autocomplete caret jumps outside double quotes

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#923]
## I'm submitting a...
* Bug report 
## Current behavior
Writing inside a double quote moves the caret outside the quotes.

## Expected behavior
The caret should not jump after the quotes when typing.

## Minimal reproduction of the problem with instructions

  1. Open [Plunkr example](http://plnkr.co/edit/ngbc7AVhNltUU1y8dJd6?p=preview)
  2. Type in two double quotes inside the input
  3. Move the caret between the quotes and start typing

## What is the motivation or use case for changing the behavior?
Unexpected component behavior.

## Environment

Package versions:
```
kendo-angular-dropdowns 1.2
```

Browser:

- Chrome (desktop) version 58

**Comment by skuruva** [comment]
It is allowing to type the text inside quotes which does not moves the caret outside the quotes but at that time auto suggestions are not coming.

**Comment by ipeshev** [comment]
It is working as expected in v1.2.2-dev.201709281629. 
@skuruva isn't it normal to not suggest, when the term is in the quotes ?
