### ISSUE TITLE
kendo-angular-popup has wrong position in IE11 when placed in a scrolled container

### ISSUE THREAD

**Issue by QuangAnh84** [telerik/kendo-angular#924]
Description:
Current the kendo-angular-popup v 1.2.0 seems that calculate wrong position in IE11 (top is wrong).
When we click to open the DateTime Input, DropDownList ... and scroll the container, the popup will update incorrect top property. 

http://plnkr.co/edit/Z55XGTHt09LnQMLSM330?p=preview 
(please run demo by click button "Launch the preview in a separate window")
Steps:

1. Click to open datetime picker
2. Drag down the scroll bar (slowly  to see the effect)

3. Scroll to middle 
4. Click to open datetime picker

## Environment

Package versions:
"angular/animations": "^4.4.1",
    "angular/common": "^4.4.1",
    "angular/compiler": "^4.4.1",
    "angular/core": "^4.4.1",
    "angular/forms": "^4.4.1",
    "angular/http": "^4.4.1",
    "angular/platform-browser": "^4.4.1",
    "angular/platform-browser-dynamic": "^4.4.1",
    "angular/platform-server": "^4.4.1",
    "angular/router": "^4.4.1",
    "progress/kendo-angular-buttons": "^1.1.0",
    "progress/kendo-angular-dateinputs": "^1.2.0",
    "progress/kendo-angular-dialog": "^1.1.0",
    "progress/kendo-angular-dropdowns": "^1.2.0",
    "progress/kendo-angular-excel-export": "^1.0.4",
    "progress/kendo-angular-grid": "^1.4.1",
    "progress/kendo-angular-inputs": "^1.3.0",
    "progress/kendo-angular-intl": "^1.2.2",
    "progress/kendo-angular-l10n": "^1.0.3",
    "progress/kendo-angular-layout": "^1.0.6",
    "progress/kendo-angular-popup": "^1.2.1",
    "progress/kendo-angular-upload": "^1.2.1",
    "progress/kendo-data-query": "^1.0.7",
    "progress/kendo-drawing": "^1.3.0",
    "progress/kendo-popup-common": "^1.2.0",
    "progress/kendo-theme-default": "^2.41.2",
    "progress/kendo-ui": "^2017.3.913"

Browser:
- IE version 11

System:
- Node version: 6.9.2
- Platform:  Windows

**Comment by ggkrustev** [comment]
@QuangAnh84 thank you for the report. I will close it as it is a duplicate to [this one](https://github.com/telerik/kendo-angular/issues/924). Please follow the opened issue for updated.

https://github.com/telerik/kendo-angular/issues/924

[TL;DR]
Indeed, we changed the positionining to `absolute` in `1.2.0` version in order to overcome the hefty list of unsupported scenarios in mobile devices using `position: fixed`. The issue has a high priority and will be fixed as soon as possible.

**Comment by QuangAnh84** [comment]
Hello @ggkrustev , 

You said that it is a duplicate, but you give the link to exactly my post. #924
Please check it and give me the correct link to subscribe news.

Thanks,
Quang Anh

**Comment by ggkrustev** [comment]
Yeah, sorry. The issue https://github.com/telerik/kendo-angular/issues/900
I will update the my previous answer to avoid any confusion.
