### ISSUE TITLE
Timepicker traps user in AM/PM zone

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#926]
Suggested by user ticket

## I'm submitting a...
* Bug report
## Current behavior
User is not able to switch from AM zone to PM zone under IE11

## Expected behavior
User should be able to switch from AM zone to PM zone under any browser 

## Minimal reproduction of the problem with instructions
1. Open [this demo](http://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/)
2. Open widget
3. Hover Hours line and try to scroll to 1 PM, it tries to switch to PM but then returns you in AM zone

Sometimes it is possible to do the transition but then going out of PM zone is problem. 

## Environment

Package versions:

Broken in v1.2.1-dev.201709180936

Browser:

- IE version 11( Edge ? )

**Comment by binki** [comment]
> Hover Hours line and try to scroll to 1 PM, it tries to switch to PM but then returns you in AM zone

I can’t repro this with scrolling. Rather, it happens when clicking on “AM” or “PM”. It animates moving towards the one I clicked on and then reverts to the original value.

> Browser:
>
> * IE version 11( Edge ? )

For me, I only see this issue in IE (IE-11.0.16291.0 / 11.0.47). Edge handles it fine.

**Comment by ggkrustev** [comment]
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by windians** [comment]
In this [Changelog](https://www.telerik.com/kendo-angular-ui/components/dateinputs/changelog/) I only see till version v1.3.1 (2017-10-24). Is it released yet to use ?

**Comment by windians** [comment]
Ok so i was able to get the  @v1.4.0-dev.201710310730  and I can validate that its no more trapping in AM/PM zone. But I have other question which might be related to this thread.

I am saving time from timepicker in DateTime format. Here is example of my timepicker.

`                    <kendo-timepicker id="txtScheduledTime" name="txtScheduledTime" [(ngModel)]="Model.ScheduledTime"></kendo-timepicker>
`
It saves time in Greenwich time zone which is ok i will do the conversion on my side. But when I go back to the component to display the saved time which we get back from model it doesnt display the time in timepicker.  And in console we get an error which says the below:
Object doesn't support property or method 'getTime'
Here is a screenshot of the error I see.
[https://imgur.com/a/WUM2O](url)

**Comment by windians** [comment]
@ggkrustev @ipeshev  I guess another way of asking my question is I get the date back in this format:
"2017-11-09T20:30:00". How should I format it to display the time in timepicker ?

**Comment by ggkrustev** [comment]
@windians, I would strongly suggest check our documentation on how to consume JSON date literal inside an Angular component:

https://www.telerik.com/kendo-angular-ui/components/dateinputs/timepicker/#toc-integration-with-json

*May I ask you to open a support ticket on the subject* in order to address the discussed issue if the given documentation is not clear enough. Parsing and consuming JSON values is not related to the reported bug in this thread and I would like to refrain from continue discussing the subject, as it will bloat the issue undesirably. Thanks for the understanding.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.
