### ISSUE TITLE
Calendar columns are misaligned in RTL

### ISSUE THREAD

**Issue by kokodda** [telerik/kendo-angular#927]
when i use kendo datepicker  in 
rtl style of days with name of the day not in the same column 

you can try this  and see 

http://plnkr.co/edit/uK1K5XACPXxE5KIg9awC?p=preview

**Comment by gyoshev** [comment]
Thank you for reporting this. We have confirmed this to be a bug in the Calendar component which is used inside the DatePicker. This will be addressed in the next version of the themes; until then, you can use the following styles to workaround the issue:

      .k-calendar .k-content.k-scrollable {
          margin-left: -117px;
          margin-right: -100px;
      }

Here is the [updated plunker](http://plnkr.co/edit/38D4scZs3aXXg0WE6RdL?p=preview).

**Comment by gyoshev** [comment]
After further inspection of the provided plunker, we have determined that RTL mode is not triggered in the example. Setting `[dir=rtl]` on the root-level HTML element is not sufficient. Use the approach documented in the [RTL support help topic](http://www.telerik.com/kendo-angular-ui/components/localization/rtl/), and the component will use the styles available in the theme.
