### ISSUE TITLE
Timepicker does not enable / disable properly with formControl

### ISSUE THREAD

**Issue by mruncola** [telerik/kendo-angular#928]
I am using the component as follows:
<kendo-timepicker [formControl]="fg.controls['tp']"></kendo-timepicker>

When disabling / enabling via "this.fg.controls['tp'].disable()" the timepicker fails to refresh the timepicker

This is reproducible via the following demo:
http://plnkr.co/edit/S92cxvyizIc8JgkkBHdh?p=preview

Click on the disable button - until you click on the timepicker it does not look disabled.
Click on the enable button - never re-enables.

Browser:
- Chrome (desktop) version 60.0.3112.113 (Official Build) (64-bit)
- Safari (desktop) version Version 11.0 (12604.1.38.1.7)

**Comment by ggkrustev** [comment]
Thanks for the bug report. We'll look into it.

**Comment by ggkrustev** [comment]
The issues is fixed in the latest @dev version of @progress/kendo-angular-dateinputs. Just install the @progress/kendo-angular-dateinputs@v1.4.0-dev.201710310730 and give it a spin.

**Comment by ggkrustev** [comment]
`@progress/kendo-angular-dateinputs@1.4.0` is out. It includes the fix. Will close the issue as fixed.
Please feel free to comment if something is not correct.

**Comment by gchurchley** [comment]
I experienced this issue on the TimePicker and version 1.4 has definitely fixed it for me. However, I now seem to be seeing the same problem on the DatePicker! Anybody else seeing this?

**Comment by ggkrustev** [comment]
I suppose that you are seeing this issue - https://github.com/telerik/kendo-angular/issues/1149
Let me know if it is different one.

**Comment by gchurchley** [comment]
@ggkrustev Yes - I'm seeing issue #1149. Thanks.

**Comment by gchurchley** [comment]
@ggkrustev - Would you be able to provide a date on which we can expect a fix for this?

**Comment by ggkrustev** [comment]
We don't have a specific ETA for the time being. Nevertheless, the issue should be addressed with the next batch fixes for DateInputs planned early next year.
