### ISSUE TITLE
Measure unit for numeric input text box

### ISSUE THREAD

**Issue by qina83** [telerik/kendo-angular#929]
## I'm submitting a...

* Bug report 

## Current behavior

I try to write an numeric input box with measure unit. I use format as string to add this feature.
If I use "mm" or "km" or "kg" as measure unit behavior is what I expect. If I use "%" it changes display value.

## Expected behavior

Since there isn't support for measure unit and I have to use format, I expect that writing something like "0.0 mm" or "0.0 %" provides the same result on data displayed

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/B7eGpdr2MgYvZTDSnV1Y?p=preview

Other solution is to add measure unit (as string) in format options.
## What is the motivation or use case for changing the behavior?

Browser:

- Chrome (desktop) last version

**Comment by ggkrustev** [comment]
@qina83, thanks for the post. 

The `p` (standard format)  or `%` (custom format) applies special rule  of multiplying the value by 100. This is built-in in the format specs and is the desired output.

If you would like to avoid this behavior, then you can easily overcome it escaping the `%` symbol. Check the updated plunkr demo:

http://plnkr.co/edit/gjMdlUVMR2R20QGH9AZf?p=preview

More details on the subject can be found in the corresponding documentation:

http://www.telerik.com/kendo-angular-ui/components/internationalization/
https://github.com/telerik/kendo-intl/blob/master/docs/num-formatting/index.md

I will close the thread as the described behavior and the available configurations are described in the documentation links I shared.
