### ISSUE TITLE
Column Re-order

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#931]
I've been looking into #1 and it mentions that column re-ordering is also on the todo list. Are there any updates or plans for that?

**Comment by tsvetomir** [comment]
Column reordering is on our roadmap for the January release. We'll post updates for [this feature](http://kendoui-feedback.telerik.com/forums/555517/suggestions/19398232) on our UserVoice portal. Please, vote or comment to receive notifications.
