### ISSUE TITLE
[Bug] Editing in Template-Driven Forms

### ISSUE THREAD

**Issue by msQwertz** [telerik/kendo-angular#932]
## I'm submitting a...

* Bug report 
* Documentation issue or request

## Current behavior

* Press enter in editing mode or in fitler input calls add handler and opens the row to add something
## Expected behavior

* Press enter should save the changes of editing respectively filters the rows
## Minimal reproduction of the problem with instructions

* Test it by yourself on the example on http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-template-forms/  
* Press enter on edit mode and the add handler will be called

Browser:

- Chrome (desktop)

**Comment by danielkaradachki** [comment]
The issue is with the demo. buttons are by default type submit. Setting the type explicitly to button should fix this:

http://plnkr.co/edit/HrIESUJQriPbKzzZHaVb?p=preview

We will update the example.
