### ISSUE TITLE
Floating Labels

### ISSUE THREAD

**Issue by neterium** [telerik/kendo-angular#933]
I'm submitting a...

* Bug report 

## Current behavior
In IE (even 11!), the floating label does not work. When you put the focus in the text box, the label stays inside it

## Expected behavior
The label should be animated and move on top of the text box.

## Minimal reproduction of the problem with instructions
See your doc page, the example there does not work under IE, the plunker example neither:
http://www.telerik.com/kendo-angular-ui/components/inputs/textbox

## What is the motivation or use case for changing the behavior?
If you type a value in the text box, the label remains so it's unreadable :(

## Environment
IE11
IE10

**Comment by tsvetomir** [comment]
Thanks for the bug report, we'll look into it. Apologies for the inconvenience.

**Comment by gyoshev** [comment]
Issue is resolved in `v2.42.1` and later of the `@telerik/kendo-theme-default` package.
