### ISSUE TITLE
nested object binding not working in Grid Edit mode

### ISSUE THREAD

**Issue by WaleedMKasem** [telerik/kendo-angular#934]
nested object binding not working in Grid Edit mode
http://embed.plnkr.co/VGnJkEQKoJSKPsGh1zCH/

**Comment by tsvetomir** [comment]
Nested fields are editable through [nested form groups](https://angular.io/guide/reactive-forms#nested-formgroups). See the [updated plunkr](http://plnkr.co/edit/iXgGMYtCj70rbGr2BLjd?p=preview).
