### ISSUE TITLE
Footer does not scroll with the grid

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#938]
The footer does not scroll with the grid when using *ngIf directive which evaluation relies on dynamically generated data. Please check the following sample plunker:

[http://plnkr.co/edit/uEACy4jb1GJyd3nv8XgP?p=preview](http://plnkr.co/edit/uEACy4jb1GJyd3nv8XgP?p=preview)

**Comment by ipeshev** [comment]
Still behaving wrong in this [plunker](http://plnkr.co/edit/IaXpMWIuUufZUSAFVDBP?p=preview) with latest dev version

**Comment by tsvetomir** [comment]
Fix published in v1.5.0
