### ISSUE TITLE
Grid filter icons not displaying properly in Firefox

### ISSUE THREAD

**Issue by Feeni** [telerik/kendo-angular#941]
## I'm submitting a...
* Bug report

## Current behavior
Filter icons (show filter / clear filter) do not show appropriately in Firefox due to the input field being too wide in Firefox.

## Expected behavior
The filter input should accommodate the filter icons in Firefox regardless of width.

## Minimal reproduction of the problem with instructions
1) Open the Plunker noted in the "Filtering Basics" section in Firefox: http://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/
2) Note how the "Product Name" column's does not show the filter icons appropriately. 

## What is the motivation or use case for changing the behavior?
When we add custom widths to these columns, we would like the filter bar to display appropriately in Firefox as well.

## Environment
Windows 10
Firefox v. 55.0.3

**Comment by ipeshev** [comment]
Yes indeed it is a bug, in other version of FF it is same.

**Comment by gyoshev** [comment]
For an immediate workaround of the problem use the following style:

      .k-filtercell .k-filtercell-wrapper>.k-textbox {
        min-width: 0;
      }

See [this plunker](http://plnkr.co/edit/BXPeXUe6mMY93axXf9Xt?p=preview).

The issue will be released in the next version of the theme, and the fix will soon be available in the [dev channel](http://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fix published in v2.42.1 of the `@progress/kendo-theme-default` package.
