### ISSUE TITLE
How can we upload file with international file names in Kendo-upload?

### ISSUE THREAD

**Issue by ranag14** [telerik/kendo-angular#942]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by Raisolution** [comment]
Hi @ranag14,

we are not aware of such issue. If you would like to receive support regarding the Upload component, please open a ticket in our support channel.
