### ISSUE TITLE
Multiselect - missing 'X' icon to remove typed text from input field

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#943]
When typing in the input field of a Multiselect there is no 'X' icon to remove the typed text.

Please check the following plunker sample:
[http://plnkr.co/edit/48Vd6Iz1m9oRbaY452UD?p=preview](http://plnkr.co/edit/48Vd6Iz1m9oRbaY452UD?p=preview)

**Comment by ipeshev** [comment]
Fixed in v1.2.2-dev.201709280940
