### ISSUE TITLE
Dialog - Can't show dialog in front of ionic popover

### ISSUE THREAD

**Issue by Jahrenski** [telerik/kendo-angular#944]
There is no way to show the kendo dialog in front of an ionic popover at the moment.
The problem lies in the stacking context of the two components. 

The highest element the kendo dialog can live is into the app-root element while the ionic popover resides directly in the body making the popover always up front.

A solution could be to expose the dialog container constant same as you did with POPUP_CONTAINER so we can change the parent element to the document.body.

**Comment by Jahrenski** [comment]
I would like to add in the same vein that it's impossible to show the kendo dialog as fullscreen either when there is an ion-header on the page. Even without the header, there seems to be some 3 to 5px padding/margin around the dialog I can't seem to get rid of.

**Comment by Raisolution** [comment]
Hi @Jahrenski,

After further evaluation of this scenario from the developer team, it will currently not be considered for a built in enhancement.

As a workaround, the stacking context of the popup that resides outside the Angular app, as a direct descendant of the body element, could be manipulated via CSS. This way it could be visualized above or below the Kendo UI Dialog, depending on the current requirements. Here is [an example of this in action](https://stackblitz.com/edit/angular-bznray-hiqrcj?file=index.html).
