### ISSUE TITLE
Scrolling with open Popup/Dialog/Calender

### ISSUE THREAD

**Issue by iqmeta** [telerik/kendo-angular#946]
Is it supported? Open Datepicker and Scroll with Mousewheel... How to make it sticky?

http://plnkr.co/edit/ejMjYow1GI1pk3QqzlNN?p=preview

**Comment by ggkrustev** [comment]
@iqmeta, the described behavior is a known limitation with the latest release of Popup component reported here:

https://github.com/telerik/kendo-angular/issues/900

We are working on the issue and will release a fix soon. Please follow the original thread for updates.
