### ISSUE TITLE
Using the is-equal-to filter, the clear filter button disappears when input is deleted via backspace

### ISSUE THREAD

**Issue by Feeni** [telerik/kendo-angular#947]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
When using the is-equal-to filter and the input is cleared via backspace, the clear filter button disappears, even though there is a filter present.

## Expected behavior
When using the is-equal-to filter and the input is cleared via backspace, the clear filter button should still be present to let the user know there is still a filter being applied to the grid. 

## Minimal reproduction of the problem with instructions
1) Open the Plunker noted in the "Filtering Basics" section: http://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/
2) Under the "Product Name" column, select the is-equal-to filter.
3) Type in a filter that returns no records (ex. "wasd"). The grid should return `No Records Available`.
4) Clear the filter by using backspace rather than the clear filter button.
5) Note that the clear filter button disappears when there is still a filter of `isEqualTo===''` (empty string)

## What is the motivation or use case for changing the behavior?
We would like to let the user know that a filter is still present. Otherwise, a user would have to enter another input to get the clear filter button to appear and then click it in order to get the grid back to an unfiltered state.

## Environment
Windows 10
Chrome v. 61.0.3163
Firefox v. 55.0.3
Internet Explorer 11 v. 11.540

**Comment by rkonstantinov** [comment]
This one sounds like a duplicate of https://github.com/telerik/kendo-angular/issues/873. Are you using the latest (1.4.2) version of the kendo-angular-grid package?

**Comment by Feeni** [comment]
We were using `1.4.0`. After upgrading to `1.4.2`, the problem has been fixed. Thanks! Sorry for the duplicate.
