### ISSUE TITLE
DropDownList popup problem on scrolled window

### ISSUE THREAD

**Issue by jaandric** [telerik/kendo-angular#948]
## I'm submitting a...

* Bug report 
## Current behavior
DropdownList expand (popup) problem. If page has a scrollbar and dropDownList component is expanded, on scroll event it doesn't calculate popup **height and width** correctly.

## Expected behavior
 Calculate popup **height and width** correctly.

## Minimal reproduction of the problem with instructions

1. `npm install -g @angular/cli`
2. `ng new my-first-angular-project --style=scss`
3. `cd my-first-angular-project`
4.  `npm install --save @progress/kendo-angular-buttons @progress/kendo-angular-l10n @angular/animations`
5. Add `DropDownListModule`
6. Add `BrowserAnimationsModule`
7. Add list of string for DropdownList component
`public listItems: Array<string> = ["X-Small", "Small", "Medium", "Large", "X-Large", "2X-Large"];`
8. Add dropdownlist tag with some style to `app.component.html`
```
<div class="example-wrapper" style="width: 2000px; height:2000px; text-align: center; margin-top: 400px;">
	<p>Kendo DropDownList:</p>
	<kendo-dropdownlist [data]="listItems"></kendo-dropdownlist>
</div>
```
9. Try to scroll vertically and horizontally
## Environment

Package versions:
```
+-- @angular/animations@4.4.3
+-- @angular/cli@1.2.1
+-- @angular/common@4.4.3
+-- @angular/compiler@4.4.3
+-- @angular/compiler-cli@4.4.3
+-- @angular/core@4.4.3
+-- @angular/forms@4.4.3
+-- @angular/http@4.4.3
+-- @angular/language-service@4.4.3
+-- @angular/platform-browser@4.4.3
+-- @angular/platform-browser-dynamic@4.4.3
+-- @angular/router@4.4.3
+-- @progress/kendo-angular-buttons@1.1.0
+-- @progress/kendo-angular-dropdowns@1.2.1
+-- @progress/kendo-angular-l10n@1.0.3
+-- @progress/kendo-theme-default@2.42.0
+-- @types/jasmine@2.5.54
+-- @types/jasminewd2@2.0.3
+-- @types/node@6.0.88
+-- codelyzer@3.0.1
+-- core-js@2.5.1
+-- jasmine-core@2.6.4
+-- jasmine-spec-reporter@4.1.1
+-- karma@1.7.1
+-- karma-chrome-launcher@2.1.1
+-- karma-cli@1.0.1
+-- karma-coverage-istanbul-reporter@1.3.0
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- protractor@5.1.2
+-- rxjs@5.4.3
+-- ts-node@3.0.6
+-- tslint@5.3.2
+-- typescript@2.3.4
`-- zone.js@0.8.17
```

Browser:

- Chrome (desktop) version 61.0.3163.100
- Firefox version 55.0.3 (32-bit)
- **Works fine on Microsoft Edge 40.15063.0.0**

System:
- TypeScript version: 2.3.2
- Node version: 6.9.1, npm: 4.0.2
- Platform:   Windows 10
- Laptop screen: 15,6", 1366 x 768
- Monitor: 23", 1920 x 1080

Screenshot:
![image](https://user-images.githubusercontent.com/3298880/30906910-86a1e000-a379-11e7-82bb-42bd60052d35.png)

**Comment by ggkrustev** [comment]
@jaandric, he described behavior is a known limitation with the latest release of Popup component reported here:

https://github.com/telerik/kendo-angular/issues/900

We are working on the issue and will release a fix soon. Please follow the original thread for updates.
