### ISSUE TITLE
ComboBox with numeric data emits valueChange on each blur

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-angular#950]
## I'm submitting a...

* Bug report 

## Current behavior

Each time a component using an array of numbers for its `data` is focused then blurred it emits a valueChange event. 

## Expected behavior
The component should not emit a valueChange unless there is one.

## Minimal reproduction of the problem with instructions

  1. Open http://plnkr.co/edit/YgyrUUUh6nlI5M2nQMQC?p=preview
  2. Focus the component
  3. Blur it

## What is the motivation or use case for changing the behavior?

Unexpected behavior.
## Environment

Browser:
- All

**Comment by ipeshev** [comment]
Fixed in v1.2.2-dev.201709281629
