### ISSUE TITLE
[Grid] Does grid support selectAll/deselectAll

### ISSUE THREAD

**Issue by xiaowvmware** [telerik/kendo-angular#951]
I am looking the grid selection example in http://www.telerik.com/kendo-angular-ui/components/grid/selection/

Does the grid support selectAll/deSelectAll function?

**Comment by Raisolution** [comment]
Hi @xiaowvmware,

We are currently working to provide this functionality out of the box and it will be released very soon. At the moment you could achieve it manually by populating the `selectedKeys` collection with all Grid items.
