### ISSUE TITLE
[GRID] Disable row selection

### ISSUE THREAD

**Issue by xiaowvmware** [telerik/kendo-angular#952]
In a multiple or single selectable grid, is it possible to lock the selection state for given rows. 

These rows cannot be either select or deselect.

"rowSelected" callback in GridComponent seems to able to archive the function. However, it is not clear to me how "rowSelected" relates to "selectedKeys" and select a row by clicking.

**Comment by Raisolution** [comment]
Hi @xiaowvmware,

The built in implementation of the rowSelected function checks whether the key of the item is in the selectedKeys collection. However you could build on top of that with additional conditions by manually specifying the function.

As a side note, please use our support channels for general questions and GitHub for issues mainly. Thanks in advance.
