### ISSUE TITLE
(selectionChange) does not fire on (click) event of ComboBox 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#953]
When using ComboBox with [data] bound to an array of Objects, the (selectionChange) event does not fire on (click).

Please check the following sample plunker:

[http://plnkr.co/edit/RdhC5VROtcpql6f6dfko?p=preview](http://plnkr.co/edit/RdhC5VROtcpql6f6dfko?p=preview)

**Comment by ipeshev** [comment]
Fixed in v1.2.2-dev.201710050732
