### ISSUE TITLE
Intl date format discrepency for ja locale

### ISSUE THREAD

**Issue by SeriousLemon** [telerik/kendo-angular#958]
## I'm submitting a...
* Bug report

## Current behavior
Setting the date format option 'hour12' to true for the locale 'ja' outputs the letter K instead of the hour.

## Expected behavior
The correct hour is output.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/YvCOpK8KSKJUIEuT8lfs?p=preview

Browser:
- Chrome (desktop) version 61
- Firefox version 56

System:
- TypeScript version: 2.3.4
- Node version: v6.10.3, 5.4.2
- Platform:  Windows

**Comment by danielkaradachki** [comment]
Seems that the available pattern for the locale uses the currently unsupported K specifier. We will look into it and will implement support for the additional hours specifiers in a future version.

**Comment by ipeshev** [comment]
Fixed in v1.3.0-dev.201710031120
