### ISSUE TITLE
How can I prevent arrow keys selection in dropdownlist.

### ISSUE THREAD

**Issue by ranag14** [telerik/kendo-angular#959]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by tapopov** [comment]
Hi @ranag14 
I am not sure I understand your question very well, however disabling keyboard navigation is not supported. 
On a side note I would like to remind you that the GitHub repository is for submitting bug reports only. Feel free to ask any general use questions by opening a support ticket or posting a StackOverflow thread.

**Comment by ranag14** [comment]
Thanks
