### ISSUE TITLE
RTL support implementation

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-angular#96]
We will need to have RTL support for all Kendo UI Angular 2 packages. I have made a [sample implementation](https://github.com/telerik/kendo-angular-layout/pull/43) for the TabStrip component in the Layout package. 

[Documentation](https://github.com/telerik/kendo-angular-intl/pull/19) on the topic has been added as well (will be merged in production when all packages are done). 

State of readiness:
- [x] @progress/kendo-angular-buttons
- [x] @progress/kendo-angular-charts
- [x] @progress/kendo-angular-sortable
- [x] @progress/kendo-angular-dropdowns
- [x] @progress/kendo-angular-scrollview
- [x] @progress/kendo-angular-dialog
- [x] @progress/kendo-angular-grid
- [x] @progress/kendo-angular-inputs (partial)
- [ ] ~~@progress/kendo-angular-dateinputs~~
- [x] @progress/kendo-angular-layout
- [x] @progress/kendo-angular-upload

**Comment by BtShp** [comment]
Do you no when it will be ready to use?

**Comment by rusev** [comment]
@BtShp RTL is a feature which will be incrementally added to each component (where applicable).

In the above list you can track which components are considered ready at the time. Have in mind that some of the components have more higher priority features that must be addressed first. That is the reason for having the list public so anyone can track state of readiness.

**Comment by BtShp** [comment]
I want to use the RTL implementation in my project.
How to use it?
Can you give any explanation? the links ablove not exists, I did not find explanation in your site
[](http://www.telerik.com/kendo-angular-ui)

**Comment by KirilNN** [comment]
Check the documentation http://www.telerik.com/kendo-angular-ui/components/internationalization/rtl/

**Comment by tsvetomir** [comment]
The RTL implementation is mostly complete with few exceptions, namely the MaskedTextBox, NumericTextBox and the DateInput.

Note that it is now activated with a token. See #340

**Comment by ipeshev** [comment]
Input does have some problems with RTL https://github.com/telerik/kendo-angular-inputs/issues/117
