### ISSUE TITLE
Grid - Selection: Cannot click checkbox

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular#960]
## I'm submitting a...
* Regression report

## Current behavior
After updating `@progress/kendo-angular-grid` from `1.4.1` to `1.4.2`, the checkbox selection stopped working.

When clicking the row/checkbox it does not get selected.

## Expected behavior
When clicking the checkbox the row should be selected/deselected.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/y3YYis0WK5A6TMGMayam?p=preview

## Environment

Package versions:

```
@progress/kendo-angular-grid@1.4.2
@progress/kendo-theme-bootstrap@2.8.2
@progress/kendo-theme-default@2.42.2
```

Browser:
- Chrome (desktop) version 63
- IE version 11

System:
- TypeScript version: 2.3.4
- Node version: 6.11.0 / npm: 3.10.10
- Platform:  Win7 64bit

**Comment by ipeshev** [comment]
It will be tracked [here](https://github.com/telerik/kendo-angular/issues/962) since it is send in support ticket
