### ISSUE TITLE
Click on selection checkbox doesn't select the row

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-angular#962]
## I'm submitting a...

* Bug report - found by user

## Current behavior
In grid with selection click on checkbox does not select the whole row, but clicking on the row does change checkbox state - checked

## Expected behavior

It should work both ways

## Minimal reproduction of the problem with instructions
Open [this demo](http://www.telerik.com/kendo-angular-ui/components/grid/selection/)
Try to select row by clicking on checkbox 
Try to select row by clicking in the row

## Environment

```
broken in v1.4.3-dev.201710021025
```

Browser:
All

**Comment by Raisolution** [comment]
The fix is available among other selection feature in the latest dev release `v1.5.0-dev.201710060848`.

**Comment by tsvetomir** [comment]
Fix published in v1.5.0
