### ISSUE TITLE
[grid][bug]  - Angular universal issue virtualized grid npe

### ISSUE THREAD

**Issue by earlyster** [telerik/kendo-angular#966]
## I'm submitting a...
* Bug report 

## Current behavior

When I run grid syncRowsHeight function in row-sync.js  on server side using angular 4.4 I receive this message

ERROR TypeError: Cannot read property 'length' of undefined
coming from syncRowsHeight

Issue with table1.rows being undefined

Appears that angular universal is not supporting .rows property for a table

https://www.w3schools.com/jsref/coll_table_rows.asp

## Expected behavior

Expected now error on server side angular universal

## Minimal reproduction of the problem with instructions

  1. http://plnkr.co/edit/UoagEQsiSmbC43mPkbbk?p=preview
  2. Must run with angular universal starter project
   3. You will see error that looks like this in console running in nodejs server

```
ERROR TypeError: Cannot read property 'length' of undefined
    at zip (dist/server.js:100773:33)
    at syncRowsHeight (dist/server.js:100795:16)
    at SafeSubscriber._next (dist/server.js:27190:101)
    at SafeSubscriber.__tryOrUnsub (node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (node_modules/rxjs/Subscriber.js:185:22)
    at Subscriber._next (node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (node_modules/rxjs/operator/filter.js:87:30)
    at FilterSubscriber.Subscriber.next (node_modules/rxjs/Subscriber.js:89:18)
    at SwitchMapSubscriber.notifyNext (node_modules/rxjs/operator/switchMap.js:124:30)
```

## What is the motivation or use case for changing the behavior?

Rendering initial first page of data on server in a virtualized grid 

## Environment

Package versions:
```
test
├── @angular/animations@4.4.4
├── @angular/common@4.4.4
├── @angular/compiler@4.4.4
├── @angular/compiler-cli@4.4.4
├── @angular/core@4.4.4
├── @angular/forms@4.4.4
├── @angular/http@4.4.4
├── @angular/platform-browser@4.4.4
├── @angular/platform-browser-dynamic@4.4.4
├── @angular/platform-server@4.4.4
├── @angular/router@4.4.4
├── @ngtools/webpack@1.7.2
├── @nguniversal/express-engine@1.0.0-beta.3
├── @progress/kendo-angular-dateinputs@1.2.0
├── @progress/kendo-angular-dropdowns@1.2.1
├── @progress/kendo-angular-excel-export@1.0.4
├── @progress/kendo-angular-grid@1.4.2
├── @progress/kendo-angular-inputs@1.3.1
├── @progress/kendo-angular-intl@1.2.2
├── @progress/kendo-angular-l10n@1.0.4
├── @progress/kendo-data-query@1.0.7
├── @progress/kendo-drawing@1.4.0
├── @types/express@4.0.37
├── @types/node@8.0.32
├── bootstrap@4.0.0-beta
├── css-loader@0.28.7
├── css-to-string-loader@0.1.3
├── express@4.16.1
├── express-minify-html@0.11.4
├── file-loader@0.11.2
├── html-webpack-plugin@2.30.1
├── UNMET PEER DEPENDENCY jquery@>=3.0.0
├── memory-cache@0.2.0
├── ngx-bootstrap@1.9.3
├── node-sass@4.5.3
├── nodemon@1.12.1
├── UNMET PEER DEPENDENCY popper.js@^1.11.0
├── raw-loader@0.5.1
├── rimraf@2.6.2
├── rxjs@5.4.3
├── sass-loader@6.0.6
├── script-ext-html-webpack-plugin@1.8.5
├── serialize-javascript@1.4.0
├── style-loader@0.18.2
├── typescript@2.5.3
├── url-loader@0.5.9
├── webpack@3.6.0
├── webpack-merge@4.1.0
├── webpack-node-externals@1.6.0
├── xhr2@0.1.4
└── zone.js@0.8.18
```

Browser:

Not applicable for browsers happens with server

System:
- TypeScript version: XX 
Version 2.2.2
- Node version: XX  
v6.9.5
- Platform:  
Mac

**Comment by rkonstantinov** [comment]
If I understood correctly you are manually executing the private `syncRowsHeight` function during the server-side rendering. If this is the case it is expected to throw an error. 
This function, should not be executed by default during the grid's server-side rendering.

**Comment by earlyster** [comment]
No I am not explicitly calling syncRowsHeight is being called by grid during ngInit lifecycle event

**Comment by rkonstantinov** [comment]
In such case, could you please prepare a small sample in which this issue can be observed locally.
You may use the following repository as a base (the home component already uses the plunker you have referred to)
https://github.com/rkonstantinov/kendo-grid-universal-test

**Comment by tsvetomir** [comment]
Closing, feel free to reopen if more information becomes available.
