### ISSUE TITLE
Wrong Grid row height when in editing mode

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#969]
Some children of the ".k-grid-edit-row" element get erroneous margin-top and margin-bottom, making the Grid row too high when in editing mode. The issue is observable in the online demos:

[http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-reactive-forms/](http://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-reactive-forms/)

Suggested workaround:

    .k-grid-edit-row td>.k-textbox, .k-grid-edit-row td>.k-widget {
      margin-top: 0;
      margin-bottom: 0;
    }

**Comment by yordanov** [comment]
Row height with Default Theme must be **46px** in all modes.

For detailed specs refer to the [grid.psd](https://github.com/telerik/kendo-ux/blob/master/themes/default/grid.psd).

**Comment by tsvetomir** [comment]
Doesn't seem like an issue in the current version.
