### ISSUE TITLE
[MultiSelect] When AutoClose is false and list is long, the list scrolls back to the first element every time

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#970]
Related issue #782 
---
In the related issue, the OP was using the `close` event for the popup.

Plunker
---
Now, in this plunker
[http://plnkr.co/edit/yZ5dZlirMxJRQzC4qEPI?p=preview](http://plnkr.co/edit/yZ5dZlirMxJRQzC4qEPI?p=preview)
I'm using the `[autoClose]="false"` input but it's having the same problem.

Steps to reproduce
---
1. Click on the input to open popup
2. Scroll down and click an item
3. The list suddenly jumps back to the first element

Expected Behavior
---
The list should stay still so that the user can continue selecting elements without having to scroll down everytime

**Comment by ipeshev** [comment]
@vivek201  we can confirm that this is not expected behavior.
Broken since v1.2.2-dev.201710050732

**Comment by valchev** [comment]
Related with #kendo-angular/782

**Comment by ipeshev** [comment]
Shipped , available in latest major verions
