### ISSUE TITLE
Is it possible to implement multiple headers in kendo-dropdownlist?

### ISSUE THREAD

**Issue by codeyad** [telerik/kendo-angular#971]
i have to show a list in the dropdown and it has multiple titles (headers) for certain sections of the data, please let mi know if its possible of i have to make a workaround by my self.

**Comment by ggkrustev** [comment]
@codeyad, if you are referring to so called 'grouping' functionality, DropDownList doesn't support it right now. You can cast your vote for it in our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-feedback/suggestions/20409841-grouping-on-combobox).

I am afraid that there is no feasible workaround for the time being.

Last but not least, please avoid posting implementation questions in this channel as it is dedicated only for bug reports/ feature requests. If you have specific questions, please either open support ticket within Telerik ticketing system or post your case in StackOverflow.
