### ISSUE TITLE
[disabled] input of Kendo Buttongroup does not change its state accordingly

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#972]
[disabled] input of Kendo Buttongroup does not change its state accordingly. 

Please check the following sample plunker:
[http://plnkr.co/edit/Jn7OcZPMj0VV0NReYk1W?p=preview](http://plnkr.co/edit/Jn7OcZPMj0VV0NReYk1W?p=preview)

The issue does not exist if the Buttongroup's [disabled] input is bound to a property which is initially set to false.

**Comment by ipeshev** [comment]
When we start from disabled=true we can't enable button the opposite is working correct.

**Comment by ipeshev** [comment]
Fix available in [latest development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/).

**Comment by tsvetomir** [comment]
Fixed in v4.3.0
