### ISSUE TITLE
Kendo Component Dialog Service Action Button Disable?

### ISSUE THREAD

**Issue by Tjax33** [telerik/kendo-angular#973]
I am following the [documentation](http://www.telerik.com/kendo-angular-ui/components/dialog/service/) to create custom dialog actions however the documentation doesn't state any way to capture a user action event in another component.

I have a dialog action noted below that needs to be disabled until the user inputs data.

```
  template: `<ng-template #dialogActions>
   <button kendoButton  [primary]="true"
    [disabled]="!modalForm.controls.commentBox.valid>{{yesBtn}}</button> 
   <button kendoButton >{{cancelBtn}}</button>
 </ng-template>`
```

My caller component looks like this

```
 @ViewChild('dialogActions' )actionTemplate: TemplateRef<any>;
 
 const dialog: DialogRef = this.dialogService.open({
       content: CommentsDialogComponent,
       actions: actionTemplate
    });
```

My  CommentsDialogComponent html looks like this

 ```
<form [formGroup]="modalForm" novalidate>
 <label class="control-label" for="commentBox">Comment:</label>
           <div class="textwrapper" id="commentBox"><textarea cols="2" rows="10" #comments formControlName="commentBox" (blur)="this.comment = comments.value"></textarea></div>
           <span *ngIf="!modalForm.controls.commentBox.valid" class="text-danger">
                   Comment Required.
            </span>
         </div>
 </form>
```

The comments span will show and works fine as modalForm exists on the component however since the parent form holds the dialog actions I get an error 'modalForm is undefined' since the modalForm exists on the actual dialog component and not the caller dialog component. 

Why do we have to use and assing the dialogactions on the calling componen?. Why cant they be included with some sort of flag on the actual component and the dialogservice sees its exists on the component and picks it up?

If I put the dialog actions in the actual CommentsDialogComponent html then  I have no way of capturing the action button input and the documentation says nothing about doing this.

**Comment by gyoshev** [comment]
> Why do we have to use and assign the dialog actions on the calling component?

How do you suggest that we split the CommentsDialogComponent so that it declares both the content and the actions, and provide a return value?

Since the dialog needs customization of both actions and content, you can define the dialog in a component template, and provide a service that controls if it is open. If you need help with implementing this, please open a support ticket, as this is a repository for issues only.

**Comment by gyoshev** [comment]
This functionality will be available when https://github.com/telerik/kendo-angular/issues/1046 is implemented.
