### ISSUE TITLE
Provide dev channel changelog

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#974]
Provide a way to follow the versions and their content of the dev releases. Currently only official releases are displayed in the changelog.

**Comment by tsvetomir** [comment]
There's an idea to provide an RSS feed for all releases. It passed validation, but no plans for implementation just yet.

**Comment by tsvetomir** [comment]
We can also ship the changelog in the packages themselves. Suggested in #1158

**Comment by tsvetomir** [comment]
The latest build will now be included on top of the changelog, regardless if it's in the "dev" channel or not. Can be previewed on the [develop website](https://www.telerik.com/kendo-angular-ui-develop/components/grid/changelog/).

![image](https://user-images.githubusercontent.com/247917/44460844-4f518000-a617-11e8-9678-c38aef6f3a4c.png)
