### ISSUE TITLE
Grid: Shift selection broken after selecting and deselecting row.

### ISSUE THREAD

**Issue by wsm95** [telerik/kendo-angular#975]
## I'm submitting a...

* Bug report

## Current behavior

If you shift click a row with nothing else selected, then the selection will be from the top to the selected row, but if you select and deselect a single row (still with nothing else selected), then shift click a row, the selection shown will be from the previously selected and deselected row to the shift clicked row.

## Expected behavior

When shift clicking a row with nothing else selected, the selection should always be from the top to the selected row.

## Minimal reproduction of the problem with instructions

Reproducible in this example: http://www.telerik.com/kendo-angular-ui/components/grid/selection/

1. Select and deselect a single row with nothing else selected.
2. Shift click a different row.

## What is the motivation or use case for changing the behavior?

Row Selection should always have the same behavior.

**Comment by Raisolution** [comment]
Hi @wsm95,

The described behavior is by design. The selection will initially start from the first row and then from the last row that was interacted with.
