### ISSUE TITLE
cannot AOT compile 

### ISSUE THREAD

**Issue by SkeletonSkelettron** [telerik/kendo-angular#979]
Hello
I want to AOT compile kendo project, but it gives me an error: 

node_modules/.bin/rollup : Error: Error: 'deflate' is not exported by node_modules\@progress\kendo-drawing\dist\es\pdf\pako\dist\pako_deflate.js
At line:1 char:1
+ node_modules/.bin/rollup -c rollup-config.js
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: Error: '...pako_deflate.js:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

node_modules\@progress\kendo-drawing\dist\es\pdf\deflate.js (1:9)

1: import { deflate as pakoDeflate } from './pako/dist/pako_deflate';
            ^
2: 
3: export var deflate = pakoDeflate;

my configs:

"typescript": "^2.5.3",

![image](https://user-images.githubusercontent.com/26940527/31276697-4ea169d2-aaae-11e7-9f97-b37b7e21fce1.png)

**Comment by EricSch** [comment]
Check #748 and my answers

**Comment by SkeletonSkelettron** [comment]
Thanks Eric

Misha

**Comment by tsvetomir** [comment]
Thanks @EricSch, closing as duplicate.
