### ISSUE TITLE
Install latest version of package from npm

### ISSUE THREAD

**Issue by destus90** [telerik/kendo-angular#980]
Hello. How to install from npm the latest version of some package (dropdowns, for example). If try to install with command: [npm install @progress/kendo-angular-dropdowns@latest](url) we get 1.1.1. But [here ](https://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-dropdowns/package.json)i see version 1.2.2.

**Comment by tsvetomir** [comment]
You're probably using from the now defunct Progress NPM Registry.
Please remove the configuration [as described in Troubleshooting](https://www.telerik.com/kendo-angular-ui/components/troubleshooting/#toc-i-cannot-install-the-latest-versions-of-kendo-ui-packages-for-angular).

**Comment by destus90** [comment]
@tsvetomir thx for help.
