### ISSUE TITLE
Chart: YAxis on right

### ISSUE THREAD

**Issue by meriturva** [telerik/kendo-angular#982]
We have to move yaxis on left and right alternative.
I know that we have to play with `axisCrossingValue` property of `kendo-chart-x-axis-item` and it works.
Main problem here is that we don't know value of series and we would like to have a common approach not based on series values.

We are thinking to use Number.MAX_SAFE_INTEGER constant as `axisCrossingValue` just to be sure to show axis on right. Do you have any advise here? any better strategy code to align axis?

Thanks.

**Comment by tsvetomir** [comment]
Setting the crossing value to a "large enough" number is what we recommend as well. It doesn't matter if its `Number.MAX_SAFE_INTEGER`, `Number.MAX_VALUE` or anything else.

I prefer `Infinity` as it expresses the intent as well as possible withing the capabilities of the API.

**Comment by meriturva** [comment]
Thanks!
