### ISSUE TITLE
Switch RTL/LTR on production with angular-cli according to variable in global window object

### ISSUE THREAD

**Issue by MOstafaMRady** [telerik/kendo-angular#984]
I've an app which is multi-lang using angular-cli, need to be able to switch RTL/LTR on production 
I don't know how to dynamically change the RTL/LTR, I've tried this but is not working
let useValue=window['someValue']; // true or false according to active user settings
providers: [   
    {provide: RTL, useValue: useValue}
]
assigning useValue from a flag from the window object but it doesn't change the output when reloading the page, style keeps RTL always while the value has changed has false,
please provide me with the way of how to do it properly

**Comment by tsvetomir** [comment]
Changes to the provided value will not be reflected with `useValue`.
You need to use a [factory provider](https://angular.io/guide/dependency-injection#factory-providers) to dynamically resolve values.

**Comment by MOstafaMRady** [comment]
Thanks for your reply,
I added this factory function
export function enableRTL() {
  if (window['dirConfig'] && window['dirConfig'].isRtl) {
    return RTL;
  }
  return null;
}
And added 
providers: [    
    {provide: RTL, useFactory: enableRTL}
  ]
It worked but not sure if this is the best way to do it

**Comment by tsvetomir** [comment]
That would do it, although the token value should be a boolean.

Please note that this repository is for bug reports only. Please open a support ticket if you'd like assistance with project-specific inquiries.
