### ISSUE TITLE
ComboBox does not reflect ngModel change after value is cleared via the clear button

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#986]
When the ComboBox is bound via NgModel, and the value is cleared via the "X" clear button in the input, changing the value of the field, bound via ngModel programmatically, is not reflected in the component:

[http://plnkr.co/edit/Etyw4R9Un5cyRuMTdata?p=preview](http://plnkr.co/edit/Etyw4R9Un5cyRuMTdata?p=preview)

1) Clear the preselected value, using the clear button in the input

2) Press the "Select..." button

(Reported by customer in TicketID: 1134365)

**Comment by tapopov** [comment]
Related to https://github.com/telerik/kendo-angular/issues/796

**Comment by ipeshev** [comment]
Shipped with v1.2.3
