### ISSUE TITLE
Grid column resizing

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular#987]
## I'm submitting a...
* Bug report 

## Current behavior
The resizing does not work when the change detection is onPush

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/7dv5Amo3JIxZw1rZ7B05?p=preview

**Comment by alexeikostevich** [comment]
Our team has noticed the same issue also. It can be very beneficial to support resizing with the _OnPush_ change detection strategy for performance reasons.

**Comment by ilianiv** [comment]
Anything new about this issue? May we expect fix in @progress/kendo-angular-grid@1.5.1 ?

**Comment by rusev** [comment]
Hey folks the latest release in the `@dev` channel addresses this. You can go and give it a go.

**Comment by tsvetomir** [comment]
Live demo at:
https://www.telerik.com/kendo-angular-ui-develop/components/grid/columns/#toc-column-resizing

**Comment by ilianiv** [comment]
`@dev` version seems OK with ChangeDetectionStrategy.OnPush.

___

Not a critical issue but shouldn't odd rows have gray background to the end when shrinked like this?
![image](https://user-images.githubusercontent.com/3925630/32054503-3fbff348-ba67-11e7-9975-05464ec9b769.png)

**Comment by rusev** [comment]
@ilianiv The white area is the background of the `div` wrapper around the `table` element. When the sum of all columns width is less then the width of the Grid this area will appear.

**Comment by ilianiv** [comment]
OK. I guess nothing can be done except expanding last column width which will be strange behaviour, too.
