### ISSUE TITLE
Data Query: updateFilter

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#988]
* Suggestion for improvement
## Current behavior
updateFilter only allows FilterDescription as parameter
`    protected updateFilter(filter: FilterDescriptor): CompositeFilterDescriptor;`
    protected applyFilter(filter: CompositeFilterDescriptor): void;

## Expected behavior
updateFilter should allow FilterDescription and CompositeFilterDescriptor as parameter
`    protected updateFilter(filter: FilterDescriptor | CompositeFilterDescriptor): CompositeFilterDescriptor
`

As I read your code and also tried it, both are working. Specially useful when a grid filter have to use a range

Thanks

**Comment by rkonstantinov** [comment]
The current implementation of `updateFilter` expects only a `FilterDescriptor` as otherwise it will not be possible to find and substitute the exact nested `CompositeFilterDescriptor`.

If you need to add multiple filters at the same time. I would suggest to skip `updateFilter` and directly modify the root filter. Something similar to the following:

```js
public onChange(values: string[]): void {
    this.removeFilter(this.column.field);

    if (values.length) {
      this.filter.filters.push({
        logic: "or",
        filters: values.map(x => ({ field: this.column.field, operator: "eq", value: x }))
      });
    }

    this.applyFilter(this.filter);
  }
```

**Comment by EricSch** [comment]
I did something like that:
```
            let filters = {
                logic: "and",
                filters: [{
                    field: this.column.field,
                    operator: "lte",
                    value: valueTo
                },
                {
                    field: this.column.field,
                    operator: "gt",
                    value: corrected
                }]
            };

            return this.updateFilter(<any>filters);
```
It seems, in updateFilter you use as default a CompositeFilterDescriptor:

```
        var root = this.filter || {
            filters: [],
            logic: "and"
        };
```
But I understand the problem with the substitution. As my CompositeFilter use the same column, I assume he gets correctly removed.

As suggestion: Provide a method to easier handle a range filter
Thank you

**Comment by tsvetomir** [comment]
We currently don't have an abstraction for a range filter, making such helper hard to implement.
