### ISSUE TITLE
Grid: Export FilterCellWrapperComponent

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular#989]
* Suggestion for improvement
## Current behavior
I'm trying to implement a custom filter, like in your example: [Filter](https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/reusable-filter/#toc-reusable-custom-filter-components)

While browsing your code, is saw a useful component to building a more complicated filter: FilterCellWrapperComponent

## Expected behavior
FilterCellWrapperComponent is exported and usable for own filters.

**Comment by rkonstantinov** [comment]
I'm afraid that this is not possible at this time. The component in question is intended for internal use only, as it rely on a specific usage in combination with other internal components.

**Comment by EricSch** [comment]
@rkonstantinov I see, thank you. It would be great, to have a sample, how to build a range filter (ex. column value has to be between two dates, or greater or less than a date). So I built my own, but not sure if everything was done correctly :smirk:

**Comment by rkonstantinov** [comment]
Actually, I do have [such example](http://plnkr.co/edit/V7iajTuNktfvknw4L1Gn?p=preview) laying around for some time. Maybe we could add it to the docs.

**Comment by tsvetomir** [comment]
Documented in [Filtering by Date Ranges](https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-filtering-by-date-ranges).
