### ISSUE TITLE
Panning/zooming on category chart causes chart window to resize

### ISSUE THREAD

**Issue by pat-son** [telerik/kendo-angular#991]
## I'm submitting a...
* Bug report

## Current behavior
Panning with a category chart that has a max value set causes the width of the chart to resize slightly as it approaches the next category on the x-axis.

See [this video](https://gfycat.com/PoisedLargeIndigobunting), and watch the right edge of the chart.

## Expected behavior
Panning should not affect the width of the chart

## Minimal reproduction of the problem with instructions
Load a category chart, set the categoryAxis option "max" to something less than the max value, and enable panning in the x-axis. Pan the chart and watch the edges as the chart pans.

Plunker that reproduces the issue: [link](http://plnkr.co/edit/ZIwqnXlSDleGDH0GblAf?p=preview)

## What is the motivation or use case for changing the behavior?
Obviously, the chart isn't supposed to do that.

Browser:
- Chrome (desktop) version 61
- Firefox version 56

System:
- TypeScript version: 2.5.3
- Node version: 8.1.2 with npm 5.3
- Platform:  Windows 10

**Comment by danielkaradachki** [comment]
This is a known issue. The axis is being expanded/shrinked to fit the labels. We will be looking for approach to fix this in future versions.

**Comment by pat-son** [comment]
Any word on this issue?

**Comment by danielkaradachki** [comment]
No fix is available yet. We will update the issue once there is a version with a fix.

**Comment by danielkaradachki** [comment]
The problem should be fixed in the latest version.
