### ISSUE TITLE
Uploader does not show the message for drag-and-drop

### ISSUE THREAD

**Issue by alexeikostevich** [telerik/kendo-angular#992]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

The [Upload](https://www.telerik.com/kendo-angular-ui/components/upload/) component displays show the message "_Drop files here to upload_" only when a user starts dragging files.

## Expected behavior

The [Upload](https://www.telerik.com/kendo-angular-ui/components/upload/) provides an ability to configure the component to render a message (or a template) for the initial state and when dragging is started.

## Minimal reproduction of the problem with instructions
**MINIMAL DEMO**
http://plnkr.co/edit/Qr0ff7VJrvalP9ARTFbz?p=preview

## What is the motivation or use case for changing the behavior?

According to the feedback from our customers, showing the message can be helpful for not experienced users. Otherwise, the presence of the drag-and-drop feature is not obvious.

## Environment

Package versions:

```
├── @progress/kendo-angular-upload@1.2.1
├── @progress/kendo-theme-default@2.42.2
```

**Comment by Raisolution** [comment]
Hi @alexeikostevich,

at the moment we don't plan to add this as an option. You could achieve it by overriding the CSS styles of the dropzone. Here is an [example of this](http://plnkr.co/edit/NzeoiRu9pTestatt2h8N?p=preview). I hope it suits the current requirements.

**Comment by alexeikostevich** [comment]
Hi @Raisolution,

Thank you for the response and an example! I appreciate your help so much!

Overriding CSS solves our issues. I would like to suggest to add a CSS class to this element in the future, since, currently, we have to use a bit leaky selector to display this message. As a result, styles can become broken after updating an upload package. But, this is, actually, not a big issue at this point.

**Comment by Raisolution** [comment]
Thank you for your input. We will consider it for upcoming versions.

**Comment by alexeikostevich** [comment]
The latest version adds `k-dropzone-hint` class to the hint! This makes styling much reliable and simpler! Thank you for addressing the issue!
