### ISSUE TITLE
User cannot type in the MaskedTextBox or DatePicker input on a Samsung Galaxy Tab A device

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#995]
The Kendo masked inputs and date/time inputs do not work on Galaxy Tab A (2016) device. User is unable to type in the textbox or the date picker input, as the component doesn't register any typing has occurred.

The issue is reproducible in the online demos when opened in Galaxy Tab A (2016) device.

Reported in TicketID: 1134302

**Comment by ggkrustev** [comment]
After a thorough research, we couldn't find a feasible solution. Unfortunately, we will mark this issue with `Won't fix`, at least for time time being.

We could reopen it in future if we find a proper workaround. Any possible solutions from the community are always welcomed too.
