### ISSUE TITLE
Lint is failing for templates-use-public with current grid sort example code

### ISSUE THREAD

**Issue by the-mace** [telerik/kendo-angular#998]
## Current behavior
lint is failing with current grid sort example code.

This example:
https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/sorting/

Gives lint errors when the templates-use-public check is enabled:
You can bind only to public class members. "sort" is not a public class member.
You can bind only to public class members. "sortChange" is not a public class member.

## Expected behavior
No Lint errors, good clean examples.

## Minimal reproduction of the problem with instructions
npm lint on the example with templates-use-public enabled.

## What is the motivation or use case for changing the behavior?
People want clean lint runs and to use triggers when lint fails.

## Environment

Package versions:
├── @angular/animations@4.4.4
├── @angular/cdk@2.0.0-beta.12
├── @angular/cli@1.4.4
├── @angular/common@4.4.4
├── @angular/compiler@4.4.4
├── @angular/compiler-cli@4.4.4
├── @angular/core@4.4.4
├── @angular/forms@4.4.4
├── @angular/http@4.4.4
├── @angular/language-service@4.4.4
├── @angular/platform-browser@4.4.4
├── @angular/platform-browser-dynamic@4.4.4
├── @angular/router@4.4.4
├── @progress/kendo-angular-buttons@2.0.0
├── @progress/kendo-angular-dateinputs@1.2.1
├── @progress/kendo-angular-dropdowns@1.2.2
├── @progress/kendo-angular-excel-export@1.0.4
├── @progress/kendo-angular-grid@1.5.0
├── @progress/kendo-angular-inputs@1.3.1
├── @progress/kendo-angular-intl@1.2.2
├── @progress/kendo-angular-l10n@1.0.4
├── @progress/kendo-angular-layout@1.0.7
├── @progress/kendo-data-query@1.0.7
├── @progress/kendo-drawing@1.4.0
├── @progress/kendo-theme-default@2.42.2
├── @types/jasmine@2.5.54
├── @types/jasminewd2@2.0.3
├── @types/node@6.0.89
├── angular-in-memory-web-api@0.5.0
├── codelyzer@3.2.1
├── core-js@2.5.1
├── jasmine-core@2.6.4
├── jasmine-spec-reporter@4.1.1
├── karma@1.7.1
├── karma-chrome-launcher@2.1.1
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@1.3.0
├── karma-jasmine@1.1.0
├── karma-jasmine-html-reporter@0.2.2
├── protractor@5.1.2
├── rxjs@5.4.3
├── ts-node@3.2.2
├── tslint@5.7.0
├── typescript@2.3.4
└── zone.js@0.8.18

Browser:
Not related

System:
- Node version: v8.5.0
- Platform:  OSX

**Comment by tsvetomir** [comment]
Thanks for spotting this problem. All examples are now linted with the official rule set from Angular CLI projects.
